== Introduction.

Although several lives of William Penn are already before the public,
yet none of them appeared to comport fully with the design of the Friends`' Library,
and it was therefore deemed expedient to compile another.--In performing this task,
it is not expected that much which is new will be brought to light,
the design being chiefly to place more prominently in view
the religious life of this eminent and worthy man.

Nor does it comport with the purpose of the present undertaking,
to enter into an elaborate defence of William Penn,
from the numerous and unfounded calumnies,
which envy or malevolence have arrayed against him.
The best refutation of them, is the life he led, the death he died,
and the lasting memorials he has left of the exercise of those
Christian virtues which ennoble and adorn the character of man.
Some of these slanders however, are noticed and briefly refuted;
and they will serve to confirm the observation so often made,
that men who have been conspicuous for the purity and integrity of their lives have,
for that very reason,
been marks for the envenomed shafts of those who felt their own conscious defects reproved,
by the silent but forcible testimony of a holy and unblameable conduct and conversation.

If the memoirs do not present the attraction of novelty,
it is believed that they will furnish the reader with much that is valuable and instructive,
as well as interesting, in a dress somewhat different from any other compilation,
and will repay him for the labour of a careful and serious perusal.

[.signed-section-signature]
William Evans, Thomas Evans.
