== Chapter I

The subject of the following memoir occupied a conspicuous
station in civil and religious society.
As an eminent and faithful minister of the Gospel, and a consistent and pious Christian,
he was justly honoured and beloved by his brethren,
while the liberal and enlightened views of his enlarged
mind on the subject of human rights and liberty,
which he steadily advocated through life and carried
out in founding the government of Pennsylvania,
have gained for him the esteem and admiration of mankind.

William Penn was honourably descended;
his paternal ancestors for several generations having been persons
of high respectability and considerable note in the world.
His grandfather, Giles Penn, was a captain in the English navy,
and for a time held the office of British Consul in the Mediterranean.
His father, William Penn, at an early age, became a distinguished naval officer,
and passed rapidly through the successive grades of promotion,
so that at the age of thirty-one he was created Vice Admiral.
He was a man of good understanding, and a thoughtful turn of mind;
though his opinions on the subject of religion were
widely different from those embraced by his son.
Accustomed to the exercise of absolute control over others,
he could not endure opposition; and though his temper was neither cruel nor morose,
its irritability sometimes hurried him into measures which his more sober judgment condemned.
To the habits of undisputed authority and impatience of contradiction,
growing out of the nature of his employment, rather than to a want of paternal affection,
we are to attribute these acts of severity toward his son,
which the biographers of the latter have had occasion to record.

William Penn was born in London, on the 14th of the eighth month,
(now the tenth,) A. D. 1644.
Of his very early years but little is known.
Being the heir to a considerable estate, and a youth of promising abilities,
his father appears to have spared no expense to confer upon
him the best education which the country could afford.
He received the rudiments of learning at Chigwell school, which was near Wanstead,
in Essex, then the country residence of his father.
Although he left this seminary at the age of twelve years,
yet he appears while there to have received some serious
impressions in regard to the concerns of religion.
The Lord, who designed to make him an instrument of good to many souls,
visited his mind by his holy Spirit,
bringing him under a weighty consideration respecting his eternal well being;
and though he then knew not what it was which thus solidly impressed him,
yet it had a good effect on his mind.

From the age of twelve to fifteen years, he resided in London,
and had the advantage of a private tutor to aid him in the prosecution of his studies.

During this period, his religious thoughtfulness was often renewed,
and though the buoyancy of youthful spirits might at times dissipate it,
yet there was a work begun, which the enemy of souls could not wholly lay waste,
and which, as he advanced toward manhood,
began to produce those blessed fruits of the Spirit,
by which his after life was conspicuously marked.

At fifteen he went to college,
where he entered as a gentleman commoner at Christ`'s church, Oxford.
While there he appears to have pursued his studies with diligence,
and cultivated the acquaintance of such of his fellow-students
as were distinguished for their talents or their worth;
and among his intimate friends at that time, was John Locke,
celebrated for his Essay on the Human Understanding.
Amid the dissipation and wickedness which abounded in the University, the Lord,
by his invisible power and Spirit, preserved him from corruption;
and soon after he entered there, attending a religious meeting appointed by Thomas Loe,
formerly a member of the college, but then one of the people in scorn called Quakers,
he was so thoroughly reached by bis living and powerful ministry,
that his previous religious exercise was effectually renewed and strengthened.
His desires after the experimental knowledge of true
vital religion were earnest and fervent,
and his understanding being divinely enlightened to see the emptiness
and formality which too much prevailed among all sorts of professors,
he longed to come to the full enjoyment of that inward and spiritual work,
by which the heart and affections are changed and all things made new,
and all things of God.
In this seeking state of mind, he was induced,
in company with some of his fellow-students whose views were similar to his own,
to withdraw from the established worship of the University,
and to hold meetings for religious edification among themselves,
in which they were engaged in preaching and prayer.
This conduct gave great offence to the heads of the seminary,
and he and his companions were fined for non-conformity.

This, however, instead of reconciling William Penn,
only served to increase his zeal for the principles he had imbibed,
and believing it his duty to continue the religious practices he had thus begun,
he was on that account soon afterward expelled the college.^
footnote:[Clarkson relates in his [.book-title]#Life of Penn,# that William Penn,
in company with Robert Spencer and some others,
tore the surplices over the heads of the students who wore them;
and attributes his expulsion from college to this outrage.
The story appears to have been copied from Oldmixon,
and is in part contradicted by the letter of William Penn to the same Robert Spencer,
after he became Earl of Sunderland; for it appears by that letter,
that their acquaintance was formed at a subsequent period
in France.--See [.book-title]#Memoirs of Pennsylvania Historical Society,
Vol.
II.# Page 244. This gives reason to apprehend that
the whole story of the surplices may be an error,
especially as Besse, the original biographer, is silent upon the subject,
and attributes his expulsion to his continued absence from the national worship.]

He returned home,
and in his conduct and manners gave evidence of the
work of grace which was going on in his heart.
"`He refrained from associating with the fashionable world,
or mingling in its vain amusements,
and took great delight in the company of the most grave and sober persons,
with whom he mixed almost entirely.`"
His father readily perceived, that if he persisted in this course,
those prospects of worldly promotion and advantage,
which his own interest at court opened before him, must be blasted,
and he endeavoured by argument, entreaty, and eventually by violence,
to divert the attention of his son to the brilliant career which his talents,
and the influence of his father would enable him to pursue.
But the ambition of William Penn led him another way--his eye and
expectation were fixed upon heaven and heavenly things,
and thither all his hopes and prospects tended;
and his father being unable to alter his course, at length sent him away from his house.

How long he remained an exile from the paternal home
is not known--but probably it was not long;
for his father was in reality much attached to him, and his mother,
who was a most amiable and worthy woman, tenderly interceded for his return.
There is no doubt, that after the first burst of anger had passed by,
his father quickly relented,
and we soon find him devising plans for the completion of
his education and giving a different turn to his thoughts.
With this view he sent him to France in company with some persons of quality,
who were making a tour on the continent, and for some time he was a resident at Paris.
This gay and licentious metropolis furnished little society calculated
to strengthen the pious resolutions of William Penn;
and whatever he might acquire of fashionable manners or polite accomplishments,
he certainly did not increase in religious stability.

While at Paris, he met with an incident which he has recorded,
for the purpose of showing the folly of those outward demonstrations of honour,
which the pride of man has led him to invent and afterwards covet.
"`What envy, quarrels and mischief,`" says he,
in a work written after he became a Friend, "`have happened among private persons,
upon their conceit that they have not been respected
according to their degree of quality among men,
with hat, knee, or title--even duels and murders not a few.
In France I was myself once set upon about eleven o`'clock at night,
as I was walking to my lodgings,
by a person who waylaid me with his naked sword in his hand,
and demanded satisfaction of me for taking no notice of him,
at a time when he civilly saluted me with his hat, though the truth was,
I saw him not when he did it.
Suppose he had killed me, for he made several passes at me, or that I, in my defence,
had killed him, when I disarmed him; I ask any man of understanding or conscience,
if the whole round of ceremony were worth the life of a man,
considering the dignity of his nature, and the importance of his life,
with respect to God his Creator, himself, and the benefit of civil society.`"
In the issue of this attack,
he displayed his humanity and regard for the life of a fellow-being,
in permitting his assailant to pass away unharmed,
though he had him completely in his power,
and had not at that time wholly laid aside the warrior.

He afterward resided some time at Saumur,
where he went for the purpose of receiving instruction from the celebrated Moses Amyrault,
a learned Calvinistic minister and professor of divinity,
who was then held in high estimation.
Under this instructor, he renewed his studies,
read the ancient fathers as well as the modern works of theology,
and acquired an accurate knowledge of the French language.
After leaving Saumur, he proceeded toward Italy, but when he arrived at Turin,
a letter from his father reached him, desiring his return home.
The admiral having received orders to take command of the fleet under the duke of York,
against the Dutch, wished to leave his family in the care of his son.
William accordingly returned in 1664, having been absent about two years.

On his return, his father perceived not only that he had become a good French scholar,
but that he had acquired a considerable tincture
of the characteristic manners of that nation.
His new associations had in some degree worn off the seriousness of his demeanour,
so that his carriage and behaviour were what would be deemed courtly and polite.
He received his son with evident marks of satisfaction,
supposing he had gained his point,
and for some time nothing occurred to convince him to the contrary.

Soon after this, however, his spiritual exercises and conflicts were renewed.
The Lord who loved him, and designed him for usefulness in his church,
followed him by the secret but powerful convictions of his Spirit.
His worldly prospects were highly flattering to the
natural ambition of a young and ardent mind.
He possessed a manly form blooming with health, a lively and active disposition,
a ready wit, and talents improved by great literary and scientific attainments,
and many rich and powerful friends.
These, added to his father`'s interest at court, and his intimacy with the duke of York,
presumptive heir to the crown, as well as the solicitations of numerous friends,
strongly inclined him to embrace the glory and pleasures of this world,
which might be said to court his acceptance.
But the glory and joy of the heavenly inheritance had taken a deep hold of his mind,
and at seasons his earnest supplications were poured
out to the Lord for preservation and right direction.
And He who regards the prayer of the sincere seeker,
was graciously pleased to hear his cry,
and to favour him with a renewed visitation of his own holy power and Spirit,
which enabled him to reject all the glittering allurements of worldly grandeur and honour,
and with holy resolution determine to follow Christ Jesus in the regeneration,
whatever sacrifices, sufferings or reproaches it might cost him.

In giving an account some years after, of his religious exercises and convincement,
he remarks, "`Yea, it is Christ the true and only Seed of God, who visited my soul,
even in my young years, spread my sins in order before me,
reproved me and brought godly sorrow upon me, making me often to weep in solitary places,
and say within my soul, O that I knew the Lord as I ought to know him!
O that I served him as I ought to serve him!
Yea, often was there a great concern upon my spirit about my eternal state,
mournfully desiring that the Lord would give my soul rest in the great day of trouble.
Now was all the glory of the world as a bubble; yea,
nothing was dear to me that I might win Christ; for the love,
pleasure and friendship of this world were a burden to my soul.
In this seeking state, I was directed to the testimony of Jesus in mine own conscience,
as the true shining Light, given me to discern the thoughts and intents of my own heart.
And no sooner was I turned unto it,
but I found it to be that which from my childhood had visited me,
though I distinctly knew it not; and when I received it in the love of it,
it showed me all that ever I had done, and reproved all the unfruitful works of darkness,
judging me as a man in the flesh, and laying judgment to the line,
and righteousness to the plummet in me.
By the brightness of his coming into my soul,
the Lord Jesus discovered the man of sin there, upon his throne,
and by the breath of his mouth, which is the two-edged sword of his Spirit,
he destroyed his power and kingdom;
and having made me a witness of the death of the cross,
he hath also made me a witness of his resurrection--so
that in good measure my soul can now say,
I am justified in the spirit;
and although the state of condemnation unto death was glorious,
yet justification unto life was, and is, more glorious.`"

Speaking of an interview with some pious persons, he says,
"`I let them know how and when the Lord first appeared unto me,
which was about the twelfth year of my age, and how at times,
between that and my fifteenth, he continued to visit me,
and the divine impressions he gave me of himself--of my persecution at Oxford,
and how the Lord sustained me in the midst of the
hellish darkness and debauchery of that place;
of my being banished the college;
the bitter usage I underwent when I returned to my father, whipping,
beating and turning out of doors; of the Lord`'s dealings with me in France,
and in the time of the great plague in London; in fine,
the deep sense he gave me of the vanity of this world
and of the irreligiousness of the religions of it;
then of my mournful and bitter cries to Him,
that he would show me his own way of life and salvation,
and my resolution to follow Him whatever reproaches or suffering it might cost me,
and that with great reverence and brokenness of spirit.
How, after all this, the glory of the world overtook me,
and I was even ready to give myself up unto it,
seeing as yet no such things as the primitive spirit and church on earth;
and being ready to faint concerning my hope of the restitution of all things.

"`It was at this time that the Lord visited me with
a certain sound and testimony of his eternal Word,
through one of those the world calls Quakers, namely, Thomas Loe:
I related the bitter mockings and scornings that fell upon me,
the displeasure of my parents, the cruelty and invective of the priests,
the strangeness of all my companions, and what a sign and wonder they made of me;
but above all,
that great cross of resisting and watching against my own vain affections and thoughts.`"

It is easy to perceive, from his own account,
that at this period his mind was the subject of no ordinary religious conflict and travail,
and that he was ardently panting after the more full disclosure of divine Truth.
At the suggestion of his father, he entered as a student of law at Lincoln`'s Inn,
soon after his return from the Continent, where he continued until the great plague,
which prevailed in London in 1665, induced him to abandon the city.
The mind of William Penn was now bent on higher and nobler pursuits.
He was seeking an acquaintance with the law of the Spirit of life in Christ Jesus,
that he might experience it to set him free from the law of sin and death;
and pressing toward that city which hath foundations, whose builder and maker is God.
The gravity for which he had formerly been conspicuous, again appeared and increased;
he turned his back upon the fashions and follies of the world,
and sought the company of the most religious people.

On his return from his naval employments,
the Admiral found his son wholly divested of that
gait of manners which he had contracted in France,
and the prospect of his becoming a man of the world,
fitted to shine among statesmen and courtiers, was as distant as ever.
With a view of breaking off his connections at home,
and introducing him into society more suited to his own taste,
and more likely to promote his worldly advancement,
his father gave him the charge of a considerable estate belonging to him,
which lay in the county of Cork in Ireland.
Although William Penn, as we have seen, had passed through much exercise,
and by the operation of Truth on his mind,
been brought to acknowledge many of the principles of Friends, yet he does not appear,
previous to his residence in Ireland, to have known much of that Society,
or manifested any particular inclination toward them.
We find him writing to his father in 1666, in the usual complimentary style;
and it also appears,
that in the same year he accepted the office of victualler to the king`'s ships at Kinsale.

In the last quotation from William Penn,
he speaks of the visitation extended to him through the ministry of Thomas Loe.
It happened about this time, that being at Cork on some business,
he heard that this Friend was to be at meeting there;
and having on a former occasion been a partaker of the benefit of his ministry,
he resolved to go again.
Thomas began his testimony with these striking and appropriate words:
"`There is a faith which overcomes the world,
and there is a faith which is overcome by the world.`"
He enlarged with great clearness and authority on
the difference between the living faith,
which works by love and gives the victory over the world, the flesh and the devil,
and that formal dead faith which is confined to the head only,
and readily yields to the seductive allurements of time and sense.
At this meeting William Penn was fully reached and convinced;
the doctrine preached was like seed cast upon the prepared ground,
which took root downward as well as sprang upward,
and soon brought forth fruits to the praise of the great Husbandman.
He embraced the Truth as held by Friends, in sincerity and love,
and from that time attended their meetings,
notwithstanding the reproaches and persecutions by which he was assailed.

In the autumn of 1667, being again at a meeting in Cork, he was arrested,
and with a number of others carried before the mayor.
His dress and appearance being different from those
usually observable in the Society of Friends,
the Mayor was inclined to set him at liberty, but required surety for his good behaviour,
which he, knowing that no charge of misdemeanor could be sustained against him,
refused to give, and the consequence was, that with about eighteen others,
he was committed to prison.
The ostensible ground of this prosecution,
was a proclamation forbidding all dissenting meetings and conventicles,
issued by the ministers of Charles II.,
in consequence of the violent conduct of a few misguided Anabaptists,
usually styled Fifth Monarchy men.
Although the disturbance they created did not extend beyond the vicinity of London,
and was very soon suppressed,
yet it was made the pretext for vexatious proceedings against the
peaceable meetings of Friends in various parts of the kingdom,
for many years afterward.

Being intimately acquainted with many of the nobility and gentry of Ireland,
William Penn addressed a letter to the earl of Orrery, then Lord President of Munster,
in which he exposed the injustice and illegality of the proceedings,
and in a firm but respectful manner,
solicited the interposition of the earl`'s authority
tor the release of his fellow prisoners and himself.
Though suffering for his religious principles,
he had not at this time so fully joined himself to Friends,
as to adopt their simple and scriptural language,
but addressed the earl in the usual fashionable style.
His request was granted as regarded himself, but his companions,
whose imprisonment was as unjust as his own, were continued in confinement.

As the suffering he had previously endured at the University and in his father`'s house,
had not deterred him from the path of apprehended duty,
it was not to be expected that this instance of more public
persecution would shake his resolution or change his opinions.
The contrast which it presented to his mind, between the religion of the state,
enforced by the secular arm, and that of the people called Quakers,
patiently and meekly supported with unflinching integrity, even under persecution,
increased his attachment to the latter,
and strengthened him in the resolution to unite himself more closely to them.
His open profession of the principles of a society then generally held in contempt,
exposed him to scorn and derision from both professors and profane,
who could not appreciate the motives which induced a young man of twenty-three,
the son of the Vice Admiral of England,
to relinquish his brilliant prospects of worldly preferment,
to become a humble disciple of a meek and crucified Saviour,
and associate himself with a people so despicable in the eyes of the world.

A letter from a nobleman soon acquainted the Admiral
with the danger his son was supposed to be in,
of becoming a convert to Quakerism, who thereupon directed him to return home,
which he promptly obeyed.
Although but little change was visible in his general appearance,
yet the evidence he gave of solid religious engagement,
and his frequenting the company of persons of corresponding sentiments and habits,
as well as his disuse of the customary compliments,
soon convinced his father of the truth of the report which had reached him.
An interview, which took place between the father and the son,
is described as particularly pathetic.
The father actuated by natural affection and aiming
chiefly at the temporal advancement of his son,
grieved to see him, when just ripe for promotion,
renouncing the world and its flattering hopes, and entreated him to yield to his desire,
by complying with the prevailing customs and fashions of the day.
On the other hand, the son regarding mainly his eternal welfare,
was deeply afflicted to perceive that a compliance with the wishes
of his earthly parent was incompatible with his duty to God,
and modestly craved permission to refrain from a practice which must wound his conscience.
Persuasion being ineffectual, the Admiral threatened to disinherit him,
but he humbly and readily submitted to his father`'s pleasure in that respect,
who thereupon turned his back on him in anger,
while the son lifted up his heart to God in prayer,
for strength to support him in that hour of severe trial.

Finding him firmly grounded in the principles and profession,
which on solid conviction he had espoused,
the Admiral gave up the prospect of prevailing upon him to conform fully with his views,
and inclined to bear with his peculiarities,
upon condition that he would consent to appear with
his hat off when in the presence of the king,
the duke of York and himself.
In the eyes of many this might seem a small concession,
and it is probable the Admiral viewed it as such.
That William Penn was anxiously desirous to comply, as far as he conscientiously could,
with his father`'s wishes, there can be no doubt; and when the proposal was made to him,
he asked time to consider it.
His father supposing the delay was for the purpose of consulting some of the Quakers,
William assured him he would see none of them until he returned an answer.
If compliance with the request was a small matter in the eyes of others,
it was not so in his view--it was a question of principle, involving as he believed,
his obedience to God,
and nothing of this character was too small to be
carefully regarded by a mind divinely awakened,
as was his.
Uncovering the head is the mode by which Friends,
in conformity with the practice of the primitive Christians,
indicated their reverence to the Supreme Being,
when they approached him in the solemn act of prayer;
and as they believed that the pride of man induced
him to claim it as a token of respect to himself,
they therefore felt themselves conscientiously restrained from giving it.
In this light the subject presented itself to the mind of William Penn.
Retiring to his chamber, he humbled himself before the Lord,
with fasting and supplication to know his mind and will therein,
and for strength to perform his duty at this critical period of his life.
The result of this religious exercise was a settled conviction,
that his peace of mind was concerned in the matter;
and being confirmed in his duty to maintain his testimony
against this species of pride and idolatry,
he returned to his father,
and humbly signified that he could not comply with his request.

Unable to comprehend the principles upon which his son acted,
and probably considering his refusal as the effect of perverseness and obstinacy,
rather than religious obligation,
in the excitement of the moment the Admiral so far forgot his affection for him,
that he again expelled him from his house.^
footnote:[The fact of his expulsion from his father`'s house is obliquely,
if not directly denied in the [.book-title]#Life of Admiral Penn,# by his great-grand-son,
recently published; but the language of William Penn himself, already quoted,
sets the fact beyond contradiction.
His unquestioned reputation for integrity, as well as his filial affection,
exclude the supposition,
that he magnified his sufferings at the expense of his father`'s reputation.]
This fresh trial of his faith and allegiance to God was very severe.
His tender regard for his father made the thought
of incurring his displeasure exceedingly painful;
and he was literally giving up all his worldly hopes for
the sake of following Christ Jesus in the way of his requirings.
He had no estate of his own, had been brought up to no business,
and had no other means of subsistence than the charity of his friends,
except what his affectionate mother privately sent him.
Under these trying circumstances, the conviction that he was in the way of his duty,
and the divine consolation graciously vouchsafed to his mind,
enabled him to support this afflicting dispensation with patience and firmness.
The propriety and uprightness of his demeanour soon won upon his father,
whose displeasure in a little time subsided, so that he permitted his return home;
and when he became involved in difficulty,
in consequence of his faithfulness in attending meetings for divine worship,
he privately used his influence in his favour.

About the year 1668, being then in the twenty-fourth year of his age,
William Penn came forth in the important work of the ministry of the Gospel.
Having passed through many deep exercises and probations, both inwardly and outwardly;
having parted with all that the world holds dear for Christ`'s sake,
and been made a partaker of the powers of the world to come,
a gift in the ministry of the Gospel of life and salvation
was dispensed to him by the head of the Church.
Being thus divinely qualified and called to the work,
he was engaged in the renewed openings of the holy Spirit,
to declare unto others what he had seen and tasted and handled of the good Word of life,
and from blessed and happy experience,
to recommend the path of self-denial and entire dedication,
in which he himself had so steadfastly walked.
Being redeemed out of the fallen and corrupt nature by the power of Christ,
he was sent to call others to come out from under the dominion of Satan,
into the glorious liberty of the children of God,
that they might receive remission of sins,
and an inheritance among them that are sanctified, through faith in Jesus Christ.
Animated with an ardent concern for the everlasting welfare of his fellow creatures,
his heart warmed with divine love,
and reaching forth in good will toward all without distinction of name or party,
he became a zealous,
indefatigable and effectual labourer in the vineyard of his divine Master.

The following letter, written about this time to a young person of his acquaintance,
who was captivated with the vain customs and fashions of the age,
will serve to show his solicitude for others,
and the Christian plainness with which he maintained
his testimony against what he considered wrong things.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Navy Office, 10th of the Fifth Month, 1668.

[.salutation]
Friend,

It was a true word spoken by Jesus Christ, to undeceive the careless, wanton Jews,
among whom he manifested his glorious Truth,
through that body prepared of God for that very end,
That the way which leads to everlasting life and rest, is straight and narrow.
My friend, how much it concerns the welfare of thy immortal soul,
to reflect upon the course of life and way thou now art walking in,
before an evident stroke from heaven call thee hence,
and send thy so much indulged flesh and blood into the grave,
an entertainment for noisome worms.
I beg thee, as thou wouldst be saved from that unspeakable anguish,
which is reserved for worldlings, and from whence there is no redemption,
to keep thyself from those vanities, follies, and pollutions,
which unavoidably bring that miserable state.
Alas! how unsuitable is thy life and practice, with those holy women of old,
whose time was mostly spent in heavenly retirements, out of that rattle, noise,
and conversation thou art in.
And canst thou imagine that those holy men recorded in Scripture, spent their days,
as do the gallants of these times?
Where is the self-denying life of Jesus, the cross, the reproach, the persecution,
and loss of all, which He and his suffered, and most willingly supported,
having their eyes fixed upon a more enduring substance.
Well, my friend, this know, and by these shalt thou be judged, and in it I am clear,
That as without holiness none can see God, so without subjection to that Spirit, Light,
or Grace in the heart, which God in love hath made to appear to all,
that teacheth to deny all ungodliness and worldly lusts, and to live soberly,
righteously, and godly in this present world; I say, without subjection hereunto,
there is no attaining to that holiness,
which will give thee an entrance into His presence,
in which is joy and pleasure forever.
Examine thyself,
how remote thou art from the guidings and instructions of this Spirit of grace,
who canst countenance this age in frequenting their wicked and vain sports,
plays and entertainments, conforming thyself to ridiculous customs,
and making one at idle talking and vain jesting, wheresoever thou comest,
not considering thou shalt account to God for every idle word.
And let all thy frolicking associates know, the day is hastening,
in which they shall not abide the presence of Him that sits upon the throne.
It shall be a time of horror, amazement and distress.
Then shall they know there is a righteous, holy Judge of all.
As for thee, with pity is thy condition often in my thoughts,
and often is it my desire that thou mayst do well; but whilst I see thee in that spirit,
which savours of this world`'s delights, ease, plenty and esteem,
neglecting that one thing necessary, I have but little hopes.
However, I could not let this plain admonition pass me;
and what place soever it may have in thy thoughts,
I am sure it is in true love to that which shall be happy or miserable to all eternity.
I have not sought fine words or chiming expressions; the gravity,
the concernment and nature of my subject, admit no such butterflies.
In short, be advised, my friend, to be serious,
and to ponder that which belongs to thy eternal peace.
Retire from the noise and clatter of tempting visibles,
to the beholding Him who is invisible, that He may reign in thy soul, God over all,
exalted and blessed forever.
Farewell.

[.signed-section-closing]
I am thy well-wishing real friend,

[.signed-section-signature]
William Penn.

--

In the same year he appeared before the public as an author, in his first printed work,
entitled "`Truth Exalted,`" the principal object
of which is to show wherein professing Christendom,
both Roman Catholic and Protestant,
come short of the purity and spirituality of the Christian religion,
as set forth by Christ and his Apostles,
and to invite them to come to Christ Jesus the true light,
which enlighteneth every man that cometh into the world,
that by receiving and obeying Him, they might no longer walk in darkness,
but have the light of life,
and experience his precious blood to cleanse them from all sin,
and obtain the victory over the transgressing and sinful nature.

In the same year he published a tract,
entitled "`The Guide Mistaken,`" being a reply to Jonathan Clapham,
who having drawn up certain articles which he pronounced to be the true Christian Creed,
entitled his work,
"`A Guide to True Religion,`" and declared that those who did not assent to them,
were incapable of salvation, and inveighed especially against the Papists,
Socinians and Quakers treating these last however, with most severity.

William Penn`'s reply is divided into four chapters,
the first showing the errors of the Guide`'s system, the second reproving his aspersions,
the third detecting his hypocrisy, and the fourth exhibiting his contradictions.

In replying to the Guide`'s charges against the principles of the Society,
he has the following paragraphs, viz.

[.embedded-content-document]
--

Thou must not, reader, from my querying thus,
conclude we do deny (as he hath falsely charged us) those glorious three,
which bear record in heaven, the Father, Word and Spirit, neither the Infinity,
Eternity and Divinity of Jesus Christ; for we know that he is the mighty God;
nor what the Father sent his Son to do on the behalf of lost man,
declaring to the whole world, we know no other name, by which atonement,
salvation and plenteous redemption comes; but by his name, are according to our measures,
made sensible of its mighty power.

His next accusation is, That they extol the light in all men,
as the only sufficient rule to walk by, to the apparent slighting of Scriptures,
and preaching.

Reader, If yet thou art a stranger to this Light he thus explodes and villifies,
let me beseech thee once to observe it in thyself,
and tell me then if it has not that Divine quality
to discern between the precious and the vile,
and manifest every thought, word, and act; whether it is well-pleasing, or the contrary,
to the great God?
If it be criminal to own those Scriptures he falsely says we slight, the case is changed,
otherwise, we all confess that God is Light, and that he hath enlightened every man;
by heeding and obeying the dictates of which, we may be preserved in that capacity,
as the same Scripture says, which shall bring us into the pure fellowship,
and that the blood of Jesus shall cleanse us from all sin.
Nor do they own a principle in the clouds, but above all people,
have demonstrated the power and authority of their
principle by that redemption it has wrought for them,
and the alteration it has made from that condition which nakedly exposed their
immortal souls to the snares and entanglements of this world`'s perishing glories,
to experience the blood which cleanseth from all iniquity,
the unspeakable peace of perfect reconciliation with God.

And for his confident affirming we slight both Scriptures and preaching,
I have this to say, That as there is not any who discover more respect for them,
by a conformity of life to what they require, so do they both read,
and as often quote them in preaching, or declaration,
as any who profess them for their rule.
And, reader,
that thou mayst be the better informed concerning the esteem we have them in,
take but the pains to visit our assemblies,
and that shall be a sufficient vindication of our innocency.

His fifth reflection is; Our openly denying the doctrine of the Trinity;
But methinks it would become him who is reproving others
for not paying that respect they ought unto the Scriptures,
to be a little more exemplary in using their unquestionable phrase, and sound expression,
for I am altogether ignorant of any Scripture that mentions that word Trinity;
and it is his own opinion,
that fundamentals should not be drawn from dubious and obscure places,
but rather that the Scriptures were evident and perspicuous,
as to what was necessary to be believed;
yet if by Trinity he understands those three witnesses in heaven, Father, Word,
and Spirit, he should have better acquainted himself with what we disown,
than thus ignorantly to blaze abroad our open denial
of what we most absolutely credit and believe.

His next slander runs thus: The person of Jesus Christ, as to his human nature,
with all his offices assigned to him by his Father, they utterly reject,
though this is an arcanum that is kept hid from their novices.

Fain would he here insinuate to people, by his most invective impostures,
hard thoughts concerning an inoffensive people,
whilst in reality they own no other name by which
salvation is obtainable than the Christ of God;
and all the offices that ever were assigned him by his Father, are by them acknowledged;
and so remote are they from hiding their sentiments,
or being jealous of exposing them to all,
that whosoever will but give himself the time of frequenting their meetings,
or perusing their books, will soon perceive how very far this character is wide of Truth.

His next report is, we call not upon God in the name and mediation of Jesus Christ.
But, reader, that thou mayst not thus be dogmatized upon,
but better satisfied in thy sober inquiries, assure thyself,
the Quakers never knew any other name than that of Jesus Christ,
through which to find acceptance with the Lord; nor is it by any other, than Jesus,
the Mediator of the new covenant, by whom they expect redemption,
and may receive the promise of an eternal inheritance.

He further says, they trust not in his death for pardon and salvation,
but in a pretended sinless perfection.

They are so far from disowning the death and sufferings of Christ,
that there is not a people on the earth that so assuredly
witness and demonstrate a fellowship therewith,
confessing before men and angels, that Christ died for the sins of the world,
and gave his life a ransom.
Perfection from sin they hold attainable because he that is born of God sins not,
and that nothing which is unclean can enter the kingdom of God; no crown without victory;
the little leaven leavens the whole lump; the strong man must be cast out.
Paul prays they might be sanctified wholly; be ye perfect as God is perfect; be perfect,
be of good comfort; unto a perfect man; as many as be perfect;
that the man of God may be perfect; the God of peace make you perfect in every good work;
the God of all grace make you perfect;
let us cleanse ourselves from all filthiness of flesh and spirit;
perfecting holiness in the fear of God; leaving those things behind,
let us go on unto perfection; and this will we do if God permit.
If perfection were unattainable,
it would be strange that the Scriptures should speak of such a state,
and very preposterous, that Paul, Peter, etc.,
should so solicit and pray for the ancient saints, that they might come thither,
even to the spirits of just men made perfect; nay,
he positively avouches to have arrived there, at the heavenly Jerusalem,
at the church of the first born, etc.
And notwithstanding, that this excellent state should never be enjoined,
seems to me no less than a giving the apostles`' doctrine the lie,
and tacitly impeaching them of gross dissimulation and contradiction.

The doctrine of the resurrection of the just and unjust, last judgment, heaven and hell,
as future rewards; they believe and confess:--And,
as my faithful testimony both to their life and doctrine, I am necessitated to declare,
and be it known to all that ever knew me,
that when the unspeakable riches of God`'s love visited me,
by the call of his glorious light, from the dark practices, wandering notions,
and vain conversations of this polluted world, and that my heart was influenced thereby,
and consequently disposed for the more intimate and sincere reception of it;
those very habits, which once I judged impossible, whilst here, to have relinquished,
(as well as I was unwilling) and did allow myself a liberty therein,
because not openly gross or scandalous, I thought myself excusable,
became not only burdensome,
and by that light were manifested to be of another nature
than that which I was called to the participation of;
but in my faithful adherence to its holy counsel and instructions,
I was immediately endued with a power and authority that gave dominion over them.
And being in measure redeemed from that to which the curse is pronounced,
I sensibly enjoyed the blessings that attended a reconciliation.
And never since I have been conversant with their principles,
have I found one article that did not receive a full
and satisfactory assent from that very grace,
spirit, or light of God, which first called me from the gross impieties,
vain entertainments, tempting glories and will-worships of this generation.
As I have the seal of God`'s eternal spirit of love upon my soul,
as an infallible assurance; so, since my first frequenting of them and their assemblies,
I have observed that holy, innocent, and righteous conversation,
which harmonizes with the severity, circumspection, and self-denying life of the Gospel;
and testify, (as revealed from God) that since those centuries,
in which the apostacy eclipsed the beauty of the primitive light,
there has not been so glorious a discovery of spiritual, pure, and evangelical worship,
life and doctrine, as God hath, in his lovingkindness,
raised the so much despised Quakers to own, practise and declare amongst the nations;
as the good old way of holiness, that leads from intemperance, vanity, pride, oppression,
and the love of this world`'s perishing glories,
to that everlasting joy and rest which is reserved for the people of the most high God.
In short, they are sound in principle, zealous for God, devout in worship,
earnest in prayer, constant in profession, harmless and exemplary in their lives,
patient in sufferings, orderly in their affairs, few in words, punctual in dealings,
merciful to enemies, self-denying as to this world`'s delights and enjoyments;
and to sum up all, standards for the God of heaven, against the pride, cruelty, lust,
avarice, etc., of this Godless generation--whom the unborn shall call blessed,
when their testimonies are finished,
and they gathered into the unspeakable solace and possession of God`'s eternal presence.

--

About this time he visited Thomas Loe,
who was then on the eve of his departure from a world in which he had laboured
faithfully to promote the extension of the Messiah`'s peaceful reign.
This eminent minister, we may remember,
had been the messenger of good to William Penn while at Oxford,
and it was by his powerful ministry,
that he was afterwards effectually reached and convinced.
It is therefore probable,
that he was regarded by the latter with something like filial affection.
In this interview he addressed William to the following import: "`Bear thy cross,
and stand faithful to God; then he will give thee an everlasting crown of glory,
that shall not be taken from thee.
There is no other way which shall prosper, than that which the holy men of old walked in.
God hath brought immortality to light, and life immortal is felt,
this love overcomes my heart.
Glory be to his name forevermore.`"
This dying testimony of his honoured friend,
must have furnished a strong confirmation to the mind of William Penn,
of the solidity of the religion which he had embraced,
and toward which his attention had been so forcibly
attracted by the labours of the dying Christian.^
footnote:[Clarkson, in his [.book-title]#Biography of William Penn,# represents his visit to Thomas Loe,
as being subsequent to his release from the tower;
but this I conceive to have been an error.
His letter to Lord Arlington is dated the 1st of fifth month, 1669, in which he states,
that he had then been imprisoned six months;
and as the whole time of his confinement was about seven months,
he must have been discharged near the end of the fifth, or beginning of the sixth month,
1669; and Sewel informs us, that Thomas Loe died on the 5th of October, +++[+++eighth month,+++]+++
1668.]

About the same time William Penn was involved in another controversy,
which occasioned him no small share of trouble.
The seventeenth century is known to have been a period remarkable for the distensions
which existed in England among the different professions of religion.
An extraordinary interest in relation to the concerns of salvation,
seemed to be awakened,
and many were earnestly seeking after the knowledge of the Truth as it is in Jesus.
Public disputes on doctrinal subjects were very common,
and were too often managed with an acrimony and rudeness,
inconsistent with that divine charity which is peaceable,
gentle and easy to be entreated.
The Society of Friends, then in its infancy,
had greatly increased in numbers and attracted considerable attention.
Its doctrines were but little understood and much misrepresented,
and its members were therefore frequently engaged in defending
themselves from the aspersions of their enemies,
often in public disputes.
Possessing an active and uncommonly vigorous mind,
and ardently attached to the religion of his choice,
it was not to be expected that William Penn would
remain an idle spectator of the prevailing commotions.
He considered the spreading and defence of the Truth, an object of the first concernment,
and zealously vindicated it from the assaults of its opponents.
Hence he was often involved in controversies,
and the one about to be noticed took its rise in the following manner.
Two of the hearers of Thomas Vincent,
the pastor of a Presbyterian congregation in Spitalfields,
going one day to a meeting of Friends, were convinced of the truth of their doctrines,
and joined the Society.
Vincent took offence at this,
and showed his displeasure by charging the Society with
entertaining "`the most erroneous and damnable doctrines.`"
William Penn coming to the knowledge of these circumstances,
demanded an opportunity of clearing the Society of the accusation,
where it had been made, and after some difficulty,
the promise of a conference in the Presbyterian meetinghouse was obtained.

At the time appointed, the two Friends appeared,
but Thomas Vincent had taken care to have the house pre-occupied by his usual auditory,
and had three of his clerical brethren to assist and support him in the expected discussion.
As Friends had been publicly charged with holding erroneous and dangerous doctrines,
George Whitehead attempted, soon after the opening of the meeting,
to explain to the audience what their doctrines really were.
To this Vincent objected,
and insisted upon deducing their principles from their answers
to such questions as he should propound to them.
Being supported in his plan by the company, who were chiefly his own hearers,
he began to catechise them.
A protracted and desultory discussion ensued; in which much was said but nothing settled.
Many of the company behaved rudely, manifesting by their levity and abusive language,
not only a want of religious sobriety, but of common civility.
After the dispute, for such it soon became, had continued till late at night,
Thomas Vincent suddenly fell to prayer,
in the course of which he charged the Friends present with being blasphemers against God;
and as soon as he had finished, he requested the company to disperse,
setting them the example by retiring with his three associates.

As William Penn and George Whitehead had not obtained the desired
opportunity of vindicating themselves and their principles,
they disregarded this request, and a number of the company remaining together,
they spoke for some time in defence of their principles,
and in reply to the charges which had been brought against them.
Thomas Vincent finding the company had not dispersed, returned to them,
and urged a dismission of the assembly.
To this demand Friends acceded, upon his promising to afford them another meeting.

After waiting some time for the fulfilment of his promise,
William Penn and George Whitehead went to his meeting on a lecture day,
and having waited till the service was over,
requested an opportunity of clearing themselves from
the aspersions which had been cast upon them.
But Vincent would neither retract the charges he had made,
nor afford them the opportunity of vindicating themselves.

William Penn therefore wrote a pamphlet,
which he entitled "`The Sandy Foundation Shaken,`" giving
an account of the proceedings at the before-mentioned meeting,
and the efforts subsequently used to procure an opportunity of
rebutting the charges against the principles and doctrines of Friends.

Of this controversy and the essay which grew out of it, we may observe,
that the method Thomas Vincent adopted to establish
his charges of erroneous doctrines against Friends,
was to bring them to deny some of those opinions which he
and his fellow-professors held to be fundamental truths.
The dispute therefore turned, not so much on the doctrines of Friends,
as upon those of the Presbyterians,
or at least upon those which Thomas Vincent and his co-adjutors proposed.
The object which William Penn designed to effect by the pamphlet in question,
consequently, was to prove that the doctrines, as stated by his opponent,
were not sound and Scriptural, rather than to illustrate his own.
He was then a young man, about twenty-four years of age,
had but recently become a professor in the Society of Friends;
was well versed in the learning of the schools, possessed a very acute,
discriminating mind, and having embraced the religion of the Quakers with all his heart,
was full of zeal;
it is therefore not surprising that he followed his
opponent upon the ground which he took,
and exposed his absurdities and contradictions by arguments and illustrations,
which have very little, if any, connection with the doctrines of Friends.

The opinions advocated by Vincent, and which it is the object of the pamphlet to refute,
are thus expressed in the title page, [.book-title]#The Sandy Foundation Shaken,#
or those so generally believed and applauded doctrines of
one God subsisting in three distinct and separate persons;
the impossibility of God`'s pardoning sinners without a plenary satisfaction;
and the justification of impure persons by an imputative righteousness,
refuted from the authority of Scripture testimonies and of right reason.`"

Upon the first of these topics it may be fairly admitted, that the arguments advanced,
partake more of the metaphysical than the evangelical character.
But they were elicited by the questions and arguments of his opponents.
From the narrative of this dispute, as well as the general practice of Friends,
it is manifest,
that if William Penn and George Whitehead had been
permitted to give their own exposition of their doctrines,
in their own way, we should have heard nothing of these metaphysical subtleties.
In a subsequent period of his life,
we find William Penn expressing very clearly his disapprobation of the practice
to which the theological disputants of that day were too much addicted;
and of which the course pursued by Thomas Vincent
and his co-adjutors is a striking example.

Being intent upon the exposure of Thomas Vincent`'s
notion of distinct and separate personality,
he directed his attention in the body of the work, strictly to that object.
Yet, as if he was apprehensive that his manner of treating the subject,
might incur the imputation of denying the Scriptural
doctrine of the three that bear record in heaven,
toward the conclusion he distinctly repels this imputation, in these words;
"`Mistake me not--we never have disowned a Father, Word and Spirit, which are One;
but men`'s inventions.`"

With regard to the other two subjects embraced in the title, it may be observed,
that the stress of the arguments lay in the impossibility
of pardon being extended to sinners,
without a plenary and rigid satisfaction,
and in the justification of sinners by imputed righteousness,
while they continued in their sins.
To these points William Penn directed his arguments, without, in the smallest degree,
invalidating the virtue or benefits, to the penitent and returning sinner,
of that most acceptable propitiatory sacrifice,
which our Saviour offered upon the cross for the sins of mankind.
This is apparent from the work itself, in which he quotes several passages of Scripture,
where this precious doctrine is clearly enforced;
but the following extracts from a letter which he wrote in 1673 to Dr. John Collenges,
in reply to some exceptions he had taken to the Sandy Foundation Shaken,
will place all the subjects in their true light.

[.embedded-content-document.letter]
--

The matter insisted upon, relating chiefly to us on this occasion, is, that we,
in common with Socinians, do not believe Christ to be the Eternal Son of God;
and I am brought for proof of the charge.
To this hath been already answered, that my book,
called, [.book-title]#The Sandy Foundation Shaken,# touched not upon this,
but Trinity and separate personality, etc.
But this will not serve thy turn, thou must both accuse us,
and then wring and rack our books to maintain it.
I have two things to do; first,
to show I expressed nothing that divested Christ of his Divinity; next,
declare my true meaning and faith in the matter.
I am to suppose, that when any adversary goes about to prove his charge against me,
out of my own book, he takes that which is most to his purpose: now,
let us see what thou hast taken out of that book,
so evidently demonstrating the truth of thy assertion.
I find nothing more to thy purpose than this,
that I deny a Trinity of separate persons in the Godhead.
Ergo--what?
Ergo--William Penn denies Christ to be the only true God, or that Christ, the Son of God,
is from everlasting to everlasting, God.
Did ever man yet hear of such argumentation?
Doth Dr. Collenges know logic no better?
but (which is more condemnable in a minister,) hath he learned charity so ill?
Are not trinity and personality one thing,
and Christ`'s being the Eternal Son of God another?
Must I, therefore, necessarily deny his Divinity,
because I justly reject the popish school personality?
This savours of such weakness, or disingenuity,
as can never stand with the credit of so great a scribe to be guilty of.

--

William Penn, then instances the cases of Paulus Samosatenus and Sabellius,
and proceeds to give the following declaration of his faith:

[.embedded-content-document.letter]
--

And now I will tell thee my faith in this matter; I do heartily believe,
that Jesus Christ is the only true and everlasting God, by whom all things were made,
that are made, in the heavens above, or the earth beneath, or the waters under the earth;
that he is, as omnipotent, so omniscient, and omnipresent, therefore God.
This is confessed by me, in two books,
printed a little before '`The Sandy Foundation Shaken,`' viz:
'`Guide Mistaken,`' page 28, and '`Truth Exalted,`' pages 14, 15; also at large,
in my '`Innocency with her open Face.`'

What dangerous inquiry and wanton curiosity is that,
which cannot set down with this Scripture definition,
'`There be three that bear record in heaven, the Father, the Word,
and the Spirit?`' It is more truly religious, if not to deride,
at least to reject human inventions and pagan philosophy,
the chief ingredients that make up the school definitions,
and acquiesce in the naked text of holy writ;
unless the comment were more clear and unquestionable: clear it is not,
and for unquestionable, the present Protestant nation, call it popery;
as if it were an infallible mark of sound doctrine,
to cry up the fallibility of all doctrine;
a piece of new-fashioned divinity that is not two removes from atheism.

For '`satisfaction,`' thou knowest, or oughtest to do,
that is a term belonging to the civil law, and was never read in Scripture.
I have this to say, that the Friend took me right; namely,
that I chiefly opposed the impossibility of God`'s otherwise pardoning, etc.,
and thou showest great acquaintance with some late writers, and such, too,
as go for no small divines;`" +++[+++here he inserts their
names and proceeds]--He that would not have me mistaken,
on purpose to render his charge against me just, whether it be so or no,
may see in my apology for The Sandy Foundation Shaken,
that I otherwise meant than I am charactered.

In short, I say, both as to this and the other point of justification,
that Jesus Christ was a sacrifice for sin,
that he was set forth to be a propitiation for the sins of the whole world;
to declare God`'s righteousness for the remission of sins that are past, etc.,
to all that repented and had faith in his Son.
Therein the love of God appeared,
that he declared his good will thereby to be reconciled;
Christ bearing away the sins that are past, as the scape-goat did of old,
not excluding inward work; for, till that is begun, none can be benefitted,
though it is not the work, but God`'s free love that remits and blots out, of which,
the death of Christ, and his sacrificing of himself,
was a most certain declaration and confirmation.
In short, that declared remission, to all who believe and obey,
for the sins that are past; which is the first part of Christ`'s work,
(as it is a king`'s to pardon a traitor, before he advanceth him,) and hitherto,
the acquittance imputes a righteousness, (inasmuch as men, on true repentance,
are imputed as clean of guilt as if they had never sinned,) and thus far justified;
but the completing of this, by the working out of sin inherent,
must be by the power and Spirit of Christ in the heart,
destroying the old man and his deeds,
and bringing in the new and everlasting righteousness.
So, that which I writ against,
is such doctrine as extended Christ`'s death and obedience, not to the first,
but this second part of justification; not the pacifying +++[+++of]
conscience, as to past sin; but to complete salvation, without cleansing and purging,
from all filthiness of flesh and spirit,
by the internal operation of his holy power and Spirit.

--

The work when it was published gave great offence.
Among the offended persons were some of the prelates,
of whom the bishop of London was the most conspicuous.
By these men it was made a subject of public animadversion,
and an order was procured for the arrest of the author and his imprisonment in the tower.

In his new habitation, he was treated with great severity.
He was not only kept in close confinement, but his friends were denied access to him.
He was informed that the bishop of London had resolved that he
should either publicly retract his opinions or die a prisoner.
But William Penn possessed too much of the spirit
of the martyrs to be shaken by such a menace.
He boldly replied,
that his prison should be his grave before he would retract his opinions,
for he owed his conscience to no mortal man.
That great and good things were not attained without loss and hardship.
That he would weary out the malice of his persecutors by patience,
the never-failing companion of those who suffer for Christ`'s sake.
That those who would reap without labour, must perish in disappointment;
but he reposed on the assurance,
that a hair of his head would not fall without his heavenly Father`'s notice.

His zeal for promoting the cause of religion was not abated by imprisonment,
and he employed his time and talents in writing.
His first work was entitled [.book-title]#No Cross, No Crown.#

No adequate idea could be formed of this excellent treatise,
from any analysis of which the limits of these memoirs would admit--and
as it has already appeared in the first volume of the Library,
it seems unnecessary to attempt it.
It is a work adapted to all times and to every denomination of professors,
and may justly be ranked among the best performances of the author.
It sets forth, in a lucid and impressive manner,
the absolute necessity of daily taking up the cross of Christ to every inclination,
thought, word and deed, which is opposed to the purity of the Christian religion,
if we expect to be made partakers of the crown of eternal life,
which He graciously confers on his obedient followers;
and administers a just reproof to the vain and sinful practices, in which many,
even of the professors of religion, indulge themselves.
It manifests great depth and maturity of reflection,
as well as extensive acquaintance with books and men,
and is replete with edifying and instructive matter,
which will richly reward the labour of a serious perusal.
For those who are desirous of walking in the narrow but safe path,
which leads to eternal life,
and of regulating their conduct by the standard of Christian purity and holiness,
and especially to the young,
it forms a manual which cannot be too often or closely consulted;
being especially calculated to counteract that temporizing policy,
which would fritter and explain away the plain and obvious precepts of the Gospel,
to suit fleshly ease and accommodate times and circumstances.
Had he left no other fruit of his pen,
this would justly entitle him to rank among the first Christian authors.

He also wrote a letter to Sir Henry Bennett, lord Arlington,
then principal secretary of state, by whose warrant he was committed to prison.
In this letter he denies the charges which had been brought against him,
attributes the zeal shown by his persecutors to malice and ignorance,
and requests that he may be restored to his liberty,
as being imprisoned without just cause, or proper examination of his case.
He then demonstrates, in a forcible manner,
the absurdity of attempting to correct the errors of opinion by the application of force,
and shows that the practice of the rulers in that respect,
fell below the example of the wiser ancient Heathens.
He requests the liberty of presenting his case to the king,
and of clearing himself before him of the accusations of his enemies; and finally,
if that request should be denied,
that Sir Henry Bennett himself would allow him an opportunity of vindicating his innocence,
so that if he must remain a prisoner,
he might at least understand why he was thus detained.
The style of the letter is firm, yet respectful,
strongly marked with the plainness of conscious integrity and innocence.

From its tenor, and from a tract soon afterwards published,
it appears that his commitment was altogether arbitrary--that
he was detained as a state prisoner,
and not even informed of the accusation on which his imprisonment was founded.
His request to be brought before the king, or the secretary of state,
to be informed of the offence laid to his charge and permitted to vindicate his innocence,
was disregarded.
Having waited for some time in expectation of the desired opportunity,
he resumed his pen and produced a small tract,
by way of apology or explanation of [.book-title]#The Sandy Foundation Shaken.#
This he entitled [.book-title]#Innocency with Her Open Face.#
In that tract he reviewed the subjects discussed in the former,
and explained himself more clearly on some points which had been misunderstood.

Of the cause of his confinement, he remarks:
"`That which I am credibly informed to be the greatest reason for my imprisonment,
and that noise of blasphemy which hath pierced so many ears of late,
is my denying the Divinity of Christ, and divesting him of his eternal Godhead;
which most busily hath been suggested, as well to those in authority,
as maliciously insinuated amongst the people.`"

He then enters into an argument of considerable length,
to prove the Godhead of Jesus Christ, which he thus concludes:--"`In short,
this conclusive argument for the proof of Christ, the Saviour`'s, being God,
should certainly persuade all sober persons of my innocency, and my adversaries`' malice.
He that is the everlasting Wisdom, Divine Power, the true Light, the only Saviour,
the creating Word of all things, whether visible or invisible,
and their upholder by his own power, is,
without contradiction God--but all these qualifications, and Divine properties,
are by the concurrent testimonies of Scripture, ascribed to the Lord Jesus Christ;
therefore, without a scruple, I call and believe him, really to be, the mighty God.
And for a more ample satisfaction, let but my reply to J. Clapham be perused,
in which Christ`'s Divinity and eternity is very fully asserted.`"

On the other points, he says; "`As for the business of satisfaction,
I am prevented by a person,
whose reputation is generally great among the Protestants of these nations;
for since the doctrine, against which I mostly levelled my arguments,
was the impossibility of God`'s forgiving sin upon repentance,
without Christ`'s paying his justice by suffering
infinite vengeance and eternal death for sins past,
present, and to come, he +++[+++viz. Stillingfleet,]
in his late discourse about Christ`'s sufferings, against Crellius,
plainly acknowledges me no less,
by granting both the possibility of God`'s pardoning sins as debts,
without such a rigid satisfaction,
and the impossibility of Christ`'s so suffering for the world,
reflecting closely upon those persons,
as giving so just an occasion to the church`'s adversaries
to think they triumph over his faith,
whilst it is only over their mistakes, who argue with more zeal than judgment.`"
He winds up this subject in these words:
"`However positively I may reject my adversaries`' unscriptural and imaginary satisfaction,
let all know this, that I pretend to know no other name by which remission, atonement,
and salvation can be obtained, but Jesus Christ, the Saviour,
who is the power and wisdom of God.`"

"`As for justification by an imputed righteousness, I still say,
that whosoever believes in Christ, shall have remission and justification;
but then it must be such a faith as can no more live
without works than a body without a spirit;
wherefore I conclude, that true faith comprehends evangelical obedience.`"

His belief is summed up in the following declaration: "`I sincerely own,
and unfeignedly believe,
by virtue of the sound knowledge and experience received
from the gift of that holy unction and Divine grace,
inspired from on high, in one holy, just, merciful, Almighty and eternal God,
who is the Father of all things; who appeared to the holy patriarchs and prophets of old,
at sundry times, and in divers manners: and in one Lord Jesus Christ,
the everlasting Wisdom, Divine Power, true Light, only Saviour and preserver of all;
the same one holy, just, Almighty and eternal God,
who in the fulness of time took and was manifest in the flesh.
At which time he preached, and his disciples after him,
the everlasting Gospel of repentance,
and promise of remission of sins and eternal life to all that heard and obeyed; who said,
'`He that is with you, (in the flesh,) shall be in you,`' (by the spirit);
and though he left them, as to the flesh, yet not comfortless,
for he would come to them again, in the spirit:
for a little while and they should not see him, as to the flesh;
again a little while and they should see him, in the spirit:
for the Lord Jesus Christ is that Spirit,
a manifestation whereof is given to every one to profit withal.
In which holy Spirit I believe, as the same Almighty and eternal God; who,
as in those times he ended all shadows,
and became the infallible guide to them that walked therein;
by which they were adopted heirs and co-heirs of glory; so am I a living witness,
that the same holy, just, merciful, Almighty and eternal God, is now, as then,
(after this tedious night of idolatry, superstition and human inventions,
that hath overspread the world) gloriously manifested
to discover and save from all iniquity,
and to conduct unto the holy land of pure and endless peace; in a word,
to tabernacle among men.
And I also firmly believe, that without repenting and forsaking of past sins,
and walking in obedience to his heavenly voice,
which would guide into all truth and establish there,
remission and eternal life can never be obtained;
but them that fear his name and keep his commandments, they, and they only,
shall have right unto the tree of life.
For his name`'s sake I have been made willing to
relinquish and forsake all the vain fashions,
enticing pleasures, alluring honours and glittering glories of this transitory world,
and readily to accept the portion of a fool, from this deriding generation,
and become a man of sorrows and a perpetual reproach to my familiars: yea,
and with the greatest cheerfulness can obsignate and confirm,
with no less seal than the loss of whatsoever this doating world accounts dear,
this faithful confession, having my eye fixed upon a more enduring substance,
and lasting inheritance; and being most infallibly assured,
that when time shall be no more, I shall, if faithful hereunto,
possess the mansions of eternal life,
and be received into everlasting habitations of rest and glory.`"

Soon after the publication of this work, the author was discharged from the tower,
after being detained there, upon terms of unusual severity, about seven months.
His discharge came suddenly from the king,
who had been moved to it by the intercession of the duke of York.
Whether the father of William Penn applied to the duke for his interference,
or whether the act was spontaneous on the part of the latter, is not now known.
It is, however understood,
that his enlargement was owing to the friendly offices of the duke.
This and other acts of kindness,
are sufficient to explain the reason of William Penn`'s friendship for James,
when he became involved in trouble, without imputing to the former any improper motives.
