== Chapter II.

1669+++.+++ At the time when William Penn was discharged from his confinement in the tower,
his father`'s asperity towards him was considerably softened.
The mortification which he felt on discovering that
his son was firmly united to the Society of Friends,
then almost universally vilified and despised,
must have rendered him averse to an open reconciliation.
Yet the severity with which he saw him treated,
the malicious efforts which were used to destroy his reputation,
and the tedious imprisonment to which he had been subjected,
could hardly fail to excite his sympathy:
while the patience with which he sustained his complicated trials,
the firmness with which he maintained his principles,
and the innocent boldness with which he vindicated his character, excited his respect,
and tended to satisfy his father,
both of the sincerity of his intentions and the soundness of his religious principles.
He allowed him to reside at his own house, though he did not see him,
and caused it to be signified to him, through his mother,
that he might return to Ireland, to execute a commission for him.

He accordingly left London in the seventh,
and arrived at Cork in the eighth month of this year.
It had happened when he was returning from Ireland, nearly two years before,
that a person belonging to the Society of Friends, was a passenger in the same vessel.
The religious conversation of this man,
was at that time a strength and encouragement to him, being then recently convinced.
Upon taking passage at this time, he found himself again in company with the same Friend.
But their relative situation was now materially changed.
The Friend had the discernment to perceive,
that William Penn was much his superior in religious experience and weight.
This discovery brought him to reflect seriously on his own want of faithfulness,
and he expressed with many tears,
his concern to pursue his journey heaven-ward with greater vigilance in future.

Upon his arrival at Cork, he immediately visited his friends who were imprisoned there,
and the next day had a meeting among them,
in which their spirits were mutually refreshed.
Having remained a few days, he went from thence to Dublin, and on the 5th of ninth month,
attended the National Meeting of Friends, which was held at his lodgings.
At that meeting, an account of the sufferings of Friends was prepared,
which a few days afterwards he presented to the lord-lieutenant.

During his continuance in Ireland, he usually resided either at Dublin or Cork;
and although the care of his father`'s estate occupied a large part of his time,
he was careful to attend religious meetings,
in which he was frequently engaged in Gospel ministry.
His solicitude for the promotion of true religion,
and his sympathy with those who were suffering on that account,
led him often to visit those who were in prison, and to hold meetings among them.
He was also very active in bringing their sufferings to the knowledge of those in power;
and soliciting their release.
His efforts were so far successful,
that he obtained an order from the proper authorities, in the fourth month, 1670,
for their discharge.

But his zealous and active mind did not rest satisfied with the exercise of his ministry,
and his labours for the relief of his suffering friends;
he also wrote several tracts to promote the cause of religion, one of which,
viz. "`A Letter to the Young Convinced,`" was afterwards published in his printed works.
The general object of this letter, which is a very pathetic one,
is to fix the attention of those to whom it is addressed,
more closely upon that light of Christ and grace of God, in the heart,
by which they had been convinced and measurably enlightened;
that by walking in this light, and following the teachings of this blessed Spirit,
they might be enabled to make their calling and election sure;
and to support the trials unavoidably attendant upon
a life devoted to the cause of Jesus,
in that age of licentiousness and persecution.

Some idea of the character and spirit of this production,
may be formed from the following extracts, viz.:

[.embedded-content-document.epistle]
--

In the tender love of Jesus Christ, I earnestly entreat you,
let us no more look back upon our ancient pastimes and delights,
but with holy resolution press on, press on; for they will steal away our precious souls,
beget new desires, raise the old life, and finally ensnare and pollute our minds again;
and what will be the end of such rebellion,
but woes and tribulations from the hand of the just God, world without end.
Neither let us enter into many reasonings with opposers,
for that is the life which God`'s power is revealed to slay; it is the still,
the quiet and the righteous life, which must be exalted over all.
And this I say in a sound understanding, through the mercies of the Lord, that deadness,
darkness and anguish of spirit, will be the end of such disputing,
pragmatical Christians, whose religion consists much more in words than works,
confessing than forsaking, and in their own will-performances and external observations,
than in the reformation and conversion of their souls to God.
And we who have known something more of the Lord,
may also reduce our good conditions to an utter loss,
by seeking to comprehend dubious matters in our understandings,
and disputing about them with every opposer, whom the devil, in a way of temptation,
shall present to us;
which does no way advance our growth and increase in the noble principle of Truth.

And I beseech you, my dear friends, let not the fear of any external thing,
overcome the holy resolution we have made, to follow the Lamb, Christ Jesus,
through all the tribulations, trials and temptations, he and his followers meet with.
O let us be valiant in God`'s cause on earth, who have but a few days to live.
Let the constancy of the world to the momentary fashions, pleasures and pollutions of it,
the more ardently stir us up to express ours, for the honour of our God against them all,
who will reward us for whatsoever we bear, suffer, or part with, on his account.
Let neither father nor mother, sister nor brother, wife nor child, house nor land,
liberties nor life itself, deter us from our holy constancy;
but as the faithful ancients did, through deserts, wildernesses, and solitary places,
in goat-skins and sheep-skins,
endure torments and bitter mockings in this earthly pilgrimage,
for the inheritance which is everlasting.

So my dear friends, let us do as we have them for our example.
Let us however be careful to show all due respect to our relations,
not to be exalted nor any way unruly, lest there be just cause taken against us,
and the blessed Truth should suffer; but in the still, retired, holy and patient life,
which this pure Spirit of light and truth, as seriously and diligently waited on,
certainly brings into, let us all dwell and abide;
so shall we feel the powerful operation of God`'s holy Spirit,
to the more complete redeeming of our exercised souls, from under the dominion of sin,
and to the giving us all a clearer understanding and sounder judgment,
of those things that are to be parted from, as the pleasures,
cares and customs of the world,
that stand in the fallen nature and only nourish the same,
but crucify the self-denying Lord of glory;
and also of the things of God and his spiritual kingdom, which are to be adhered to,
that in his pure wisdom which is from above, we may be all kept and preserved,
over all the snares and temptations of the adversary,
both on the right hand and on the left.

And as one who is a traveller in his way, I even beseech,
caution and admonish you all in the holy awe of God,
that you never forbear meeting and assembling yourselves,
with the holy remnant amongst whom we first received our blessed convincement.
O forever let us honour the Lord`'s Truth, and those who sincerely profess the same;
but more especially such as were in Christ before us,
for this is well pleasing to the Lord.
Beware of lightness, jesting or a careless mind, which grieves the holy Spirit,
that stands ready to seal us unto the day of our perfect redemption; but let us be grave,
weighty and temperate, keeping low in body as well as mind,
that in all things we may be examples, and a sweet savour for God,
who hath loved and called us.

And my dear friends, keep in the simplicity of the cross of Jesus,
even in plainness of speech, and out of the world`'s flattering and deceitful respects;
for we are as well to be a cross in our garb, gaits, dealings and salutations,
as religion and worship, to this vain, adulterated and apostatized generation.
In the pure measure of Truth that has been manifested to every particular,
and has convinced us of the unrighteousness of the world,
and the vanity and emptiness of all its professions of God, Christ and religion,
let us stand and abide, that we may feel it to be our refuge and strong tower,
when the enemy shall approach, either by inward exercises,
or outward bonds and suffering,
which may overtake us for the trial of our most precious faith;
so shall we sensibly experience that heavenly blood of cleansing,
which only can give remission, cleanse from all sin,
and finally purge the conscience from dead works to serve the living God.

--

1670+++.+++ Having accomplished his visit in regard to his father`'s business,
and rendered a number of signal services to his friends in Ireland,
he returned to his native land.

It now becomes the pleasing duty of his biographer to mention,
that his father was fully reconciled to him.
Though the Admiral was only about forty-nine,
yet his constitution had been so much impaired by the hardships of a sea-faring life,
and exposure to a variety of climates,
that he was then sinking under the infirmities of premature old age.
Thus circumstanced, his opinions of the world,
its honours and emoluments appear to have been greatly changed.
He could then perceive the wisdom of his son`'s choice,
and appreciate the magnanimity displayed by him in his inflexible
adherence to the path of apprehended duty.
To William Penn himself, it must have been a peculiar satisfaction to find,
that after incurring his father`'s displeasure,
and sacrificing all his prospects on the side of the world,
for the sake of obtaining peace with God and the hope of final acceptance hereafter,
his father`'s favour was now restored,
without any compromise of principle or loss of peace.

In the spring of this year, an act was passed,
professedly for the suppression of seditious conventicles,
but actually to prevent all meetings for religious worship, in any other way,
than according to the liturgy of the Episcopal church.
The substance of this act was, that if any person upwards of sixteen years of age,
should be present at any assembly, conventicle, or meeting,
under colour or pretence of the exercise of religion,
in any other manner than according to the liturgy and practice of the church of England,
where there were five or more persons present, besides those of the household,
in such cases the offenders were to pay five shillings for the first offence,
and ten for the second.
"`The preachers and teachers, in any such meeting,
were to forfeit twenty pounds for the first, and forty for the second offence.
Those who suffered such conventicles to be held in their houses, barns, etc,
were also to forfeit twenty pounds.

Though this act was principally aimed at the Presbyterians,
who were considered as the political opponents of the court,
its weight fell chiefly upon Friends,
because they supported their principles without flinching,
and openly attended their meetings for divine worship; believing with the apostles,
that they ought to obey God rather than man.
Other professors frequently held their meetings in private,
but Friends continued to assemble at the usual times and places,
notwithstanding the perils which awaited them.
It was not therefore to be expected, that William Penn,
who was now become one of the conspicuous members and ministers in the Society,
could long remain undisturbed.

Friends being forcibly excluded from their meeting house in Grace-church street,
met as near it as they were permitted, and performed their worship in the street.
William Penn attending a meeting held there on the 14th of the month, called August,
and being engaged in the ministry, was arrested by a warrant from Sir Samuel Starling,
mayor of the city, and committed to Newgate.
At the next sessions held at the Old Baily, he was indicted, together with William Mead,
for being present at and preaching to an unlawful, seditious and riotous assembly.
In the trial that ensued,
he maintained his civil rights with the greatest firmness and self-possession,
and manifested throughout a protracted and exceedingly vexatious prosecution,
the magnanimity and patience of a true Christian.

This trial, as a specimen of the arbitrary conduct of the courts of that day,
and the firmness with which William Penn defended his civil and religious rights,
is too important to be omitted.
To give the proceedings in all their detail would
be to swell this work beyond its intended limits.
I shall therefore endeavour to present it to the reader in an abridged form.
This trial came on the 1st of the seventh month, (September) 1670.

The persons on the bench were, Samuel Starling, mayor; John Howell, recorder;
Thomas Bludworth, William Peak, Richard Ford, John Robinson, Joseph Sheldon, aldermen;
Richard Brown, John Smith, James Edwards, sheriffs.
The jurors empannelled to try this cause, were Thomas Veer, Edward Bushel, John Hammond,
Charles Milson, Gregory Walklet, John Brightman, Wm. Plumstead, Henry Henley,
James Damask, Henry Michel, Willam Lever and John Baily.

The indictment stated that William Penn and William Mead,
with other persons to the number of three hundred,
with force and arms unlawfully and tumultuously assembled
together on the 15th day of August,
1670, and the said William Penn, by agreement made beforehand with William Mead,
preached and spoke to the assembly;
by reason whereof a great concourse and tumult of
people continued a long time in the street,
in contempt of the king and his law, to the great disturbance of his peace,
and to the terror of many of his liege people and subjects.

On the first day they were brought to the bar,
and required to plead guilty or not guilty to the indictment.
They both answered not guilty,
having been previously promised an opportunity of making their defence,
and that a fair hearing would be allowed them.
They were afterwards kept waiting while some other prisoners,
charged with felony and murder, were tried.

On the 3rd of the month they were again brought into court.
As they came in, one of the officers pulled off their hats,
upon which the mayor in an angry manner, ordered him to put them on again.
The recorder then fined them forty marks apiece for an alledged contempt of court,
in not pulling off their hats.
This arbitrary proceeding immediately met with a merited reproof from both the prisoners.
To sustain the indictment, three witnesses were successively examined.
The first testified that he saw three or four hundred people assembled in Gracious street,
and that William Penn was speaking to them, but he could not hear what he said.
He also saw William Mead there, who spoke to the witness.
The second asserted that he saw a great crowd in Gracious
street and heard William Penn preach to them,
on the 14th of August,
yet the indictment stated that the offence charged
against the prisoners was committed on the 15th,
a discrepancy sufficient in law to secure a verdict of acquittal.
He also saw William Mead speaking to the former witness, but did not know what he said.
Upon being questioned,
he acknowledged the noise was so great that he could not tell what William Penn said.
The third witness deposed that he saw a great number of people,
and saw William Penn make a motion with his hands;
he also heard some noise but did not understand any thing that was said.
As to William Mead he did not see him there.
This was the amount of the testimony produced to establish the guilt of the prisoners.

The evidence being closed, William Penn, instead of taking advantage of its weakness,
boldly declared; "`We confess ourselves to be so far from recanting,
or declining to vindicate the assembling of ourselves, to preach,
pray or worship the eternal, holy, just God, that we declare to all the world,
that we do believe it to be our indispensable duty
to meet incessantly upon so good an account;
nor shall all the powers upon earth be able to divert us
from reverencing and adoring the God who made us.`"
To this Richard Brown replied, you are not here for worshipping God,
but for breaking the law.
William Penn immediately affirmed that he had broken no law,
and was not guilty of the indictment;
he therefore desired them to inform him upon what law the
indictment and the proceedings of the court were founded.
The recorder answered, upon the common law.
William Penn inquired where that law was.
The recorder replied,
he must not expect him to run over so many adjudged cases which they called common law,
to answer his question.
William Penn told him if the law was common it ought not to be hard to produce.
He was then told to plead to the indictment.
He insisted upon having the law pointed out on which the indictment was grounded,
and which he was charged with breaking,
so that the jury might understand the case and decide upon his innocence or guilt.
He told them the answer "`that it was founded on
the common law,`" was too general and imperfect,
unless they knew where and what that law was.
Where there is no law there is no transgression, and that law which is not in being,
is so far from being common that it is no law at all.
The recorder asserted that it was _lex non scripta,_
indignantly inquiring whether he expected him to tell in a moment
what some have studied thirty or forty years to understand.

William Penn, in return to this legal bravado, quoted the declaration of lord Coke,
that common law was common right, and common right the great charter privileges,
confirmed by Henry III., Edward I., and Edward III.
The recorder manifested great irritation, while William Penn,
apparently quite calm and collected,
urged the propriety of knowing upon what law the indictment was founded;
declaring plainly, that if they denied the information demanded,
and still refused to point out the law which he was charged with violating,
they denied him a common right,
and evinced a determination to sacrifice the privileges
of Englishmen to their arbitrary designs.

Upon this the mayor and recorder united in ordering
him to be taken away and turned into the bale-dock.
William Penn replied, these are but so many vain exclamations.
Must I therefore be taken away, because I plead for the fundamental laws of England?
However, this I leave upon your consciences, who are of the jury, and my sole judges,
that if these ancient fundamental laws, which relate to liberty and property,
and are not limited to particular persuasions in matters of religion,
must not be indispensably maintained and observed,
who can say he hath a right to the coat on his back?

Certainly our liberties are to be openly invaded, our families ruined,
and our estates led away in triumph by every sturdy beggar and malicious informer,
as their trophies, but our pretended forfeits for conscience sake.
The Lord of heaven and earth will be judge between us in this matter.

William Penn being then rudely turned into the bale-dock,
William Mead renewed the demand for an account of
the law upon which their indictment was founded,
denied the facts stated in the indictment, as well he might,
and explained from lord Coke what constituted a riot or unlawful assembly in common law,
but was treated with greater indignity than William Penn had been,
and turned with him into the bale-dock.

When they were thus arbitrarily driven out of the court,
in violation of the promise made at the opening of the trial;
the recorder proceeded to give his charge to the jury in the absence of the prisoners,
taking care to present the case in a light very unfavourable to the accused.
Against this illegal procedure, the prisoners, who though put out of the court,
were not out of hearing, both remonstrated,
but their remonstrance had no other effect than to bring further abuse upon them.

The jury were then sent to their room to agree upon their verdict.
As several of their number were unwilling to bring
in such a verdict as the rest were disposed to give,
the dissentients, and particularly Edward Bushel,
were Seated by the bench with contumely and menacing language.
At length they returned into court, when the foreman, on behalf of the whole,
gave their verdict, that William Penn was guilty of speaking in Gracious street.
Efforts were used by the court to extort a declaration
that he was speaking to an unlawful assembly,
but the foreman declared that the verdict already given was all he had in commission,
and Bushel, Hammond and some others opposed the addition,
openly testifying that they allowed of no such words as unlawful assembly in their verdict.
This verdict being rejected by the court, the jury were again sent out,
and returned their verdict in writing, with all their names affixed,
that William Penn was guilty of speaking or preaching
to an assembly met together in Gracious street,
and that William Mead was not guilty of the indictment.

This result exceedingly exasperated the mayor and recorder,
who gave vent to their anger in very unbecoming language,
and ordered the jury to return to their chamber and reconsider their verdict.
The jury protested against this piece of arbitrary authority,
declaring they had already agreed; but they were rudely sent back to their room,
and kept all night without food, fire or any other accommodations.
In the morning they returned and delivered their verdict,
that William Penn was guilty of speaking in Gracious street.
This verdict was four times returned, but at length,
after the jury had been kept two days and two nights without
refreshment they delivered a verdict of not guilty,
in case of both the prisoners, to the manifest satisfaction of the spectators,
but to the great mortification of the bench.
The recorder then addressing the jury, expressed his dissatisfaction with their verdict,
and informed them that the court fined them forty marks a man,
and imprisonment till the fines were paid.
William Penn then demanded his liberty, being cleared by the jury,
but he and William Mead were still detained, and sent to Newgate,
as were also the jury for nonpayment of the fines
which were thus arbitrarily laid upon them.

Upon this celebrated trial, which William Penn, in his twenty-sixth year,
sustained with so much ability, a few remarks may be made.

It appears probable, that the arrest was made in consequence of the Conventicle act,
then recently passed,
but a prosecution upon that act was not sufficient
to gratify the malice of the mayor and his associates.
The mayor indeed, on their first arrest, when they were examined before him,
treated William Penn in a very indecent and scurrilous manner,
threatening to send him to Bridewell and have him whipped,
casting at the same time some unhandsome reflections upon his father.
This touched the filial affection of the son,
who told him he could very well bear his severity to himself,
but he was grieved to hear his father abused, who was absent.

The mayor chose to commit them as rioters,
and the indictment was apparently framed with a view to involve
them and their case in the intricacies of the unwritten law,
and to subject them to such penalty as the malice of the court might prescribe.
The definition of an unlawful assembly,
would appear to have been borrowed from the Conventicle act;
for in the fourth section of that act, meetings for religious purposes,
not according to the liturgy of the church of England, are reckoned unlawful assemblies,
yet we have no account that this act was quoted or referred to during the trial.
The jury were urged to convict William Penn of preaching to an unlawful assembly,
without being informed what constituted such an assembly,
or what penalty would be awarded.
The fact of his speaking to a number of people in the street, being established,
if the jury could have been induced to decide that he was speaking to a tumultuous assembly,
the court would unquestionably have put their own construction upon it,
and decided that the penalty as well as the offence was to be found in the _lex non scripta._

As the jury, notwithstanding the menaces of the court,
eventually delivered a verdict of not guilty,
the court did not venture to set that verdict aside, but manifested their haste,
as well as displeasure, by setting a fine both on the prisoners, and the jury,
in direct violation of the provisions of the great charter.

In regard to the jurymen after their commitment,
the biographers of William Penn are entirely silent.
Their names deserve to be transmitted to posterity,
and the repositories of the law have preserved the pleasing intelligence,
that they were not long permitted to languish in prison.

From the history of the trial we readily perceive, that they were not of a temper,
particularly Edward Bushel, to be dragooned out of their civil rights,
or to be made the passive instruments of injustice in the hands of others.
Being conscious that their imprisonment was illegal,
they determined not to pay their fines,
but to remain in prison till discharged by due course of law.
By the advice of council, they demanded their freedom every six hours.
But after a short trial of that course, a more effectual one was adopted.
The trial of William Penn and William Mead,
appears to have closed on the 5th of the month, called September,
on which day the jurymen were probably committed to prison.
A writ of _habeas corpus,_ was sued out by Edward Bushel, dated the 9th of November,
by which he was brought before judge Vaughan, of the court of Common Pleas,
for the purpose of trying the legality of his commitment and detention.
The return to the writ stated, that the said Bushel and eleven others particularly named,
were fined forty marks each, because they being the jurors sworn and charged,
at the Old Bailey, on the 31st of August, 1670,
to try several issues then joined between the king and William Penn and William Mead,
for certain trespasses, contempts, unlawful assemblies and tumults,
perpetrated by the said Penn and Mead, together with others,
whereof the said Penn and Mead were indicted, did, against the law of the realm,
contrary to full and manifest evidence openly given in court
and against the direction of the court in matter of law,
acquit the said William Penn and William Mead of the said trespasses, contempts,
unlawful assemblies and tumults, to the great obstruction of justice,
and to the evil example of all other jurors similarly offending.
That the said Bushel had not paid the fine,
and was therefore detained in the jail at Newgate.

This return was ably canvassed and its fallacy exposed by judge Vaughan.
In regard to the first assertion,
that the jurors had acquitted the prisoners contrary
to full and manifest evidence openly given in court,
he observed, that it was very common for two men, students, barristers, or judges,
to deduce opposite conclusions from the same case in law;
and that it was equally possible for two men to deduce
different conclusions from the same testimony.
That what one witness or a number of witnesses declare, may,
to the mind of one man prove one thing, and to the mind of another,
may honestly appear to prove the contrary.
That this was often the case with the judge and jury.
It was therefore improper that any one should suffer fine and imprisonment
for doing what he could not avoid without violating his oath and integrity.
He thence decided that this charge did not exhibit cause of fine or imprisonment.
He observed that the verdict of a jury, and the evidence of a witness,
were very different things in regard to truth or falsehood.
The witness testifies to what he has seen or heard,
but the juryman engages to give a verdict according to what he
can infer from the evidence by the force of his understanding,
to be the facts in relation to the subject of inquiry.

On the second part of the charge, the judge remarked that the words,
"`the jury acquitted the prisoners against the direction of the court,
in matter of law,`" taken literally were unintelligible;
for no issue can be joined of matter in law;
no jury can be charged with the trial of matter in law barely; no evidence ever was,
or can be given to a jury of what is, or is not law; and no oath to try matters of law,
can be administered to or taken by a jury,
nor can a jury be attainted for perjury upon such an oath.

But if the meaning of the charge was, that the judge having heard the evidence,
was to decide that the law was in favour of the plaintiff or defendant,
and require the jury, under pain of fine and imprisonment,
to pronounce a correspondent verdict,
then the jury was rendered entirely useless in regard
to the determination of right and wrong,
and became an expensive appendage which they would be better without.
He afterwards assigned various reasons why the jurors might be expected
to understand the facts of a case more clearly than the judge,
and confirmed the doctrine of lord Coke, that the jury and not the judge,
were the arbiters in regard to facts;
and that the province of the judge was to point out and
apply the law to such facts as are found by the jury.

The issue of the trial was, that the prisoners were ordered to be discharged.

This is reported as the trial of Bushel`'s case,
yet the final decision is expressed in the plural,
from which we may infer that the suit was conducted in the name of Edward Bushel,
but that some, if not all his colleagues were included in the result.

This celebrated trial was productive of important
and beneficial results to the people of England.
It awakened their attention to the arbitrary and oppressive proceedings
of the courts under the pretended sanction of law,
by which the most flagrant violations of justice were often practised with impunity.
The able and undaunted manner in which the prisoners
contended for their rights and liberties,
and the noble stand made by the jurors against the rude and shameless
attempts of the court to browbeat and intimidate them,
opened the eyes of the people to their true interests,
and the necessity of claiming their chartered privileges;
and thus the trial was instrumental in establishing
them on a firmer basis than they ever were before;
the freedom of juries being now asserted by a solemn judicial decision.

Two accounts of this trial were soon afterwards given to the world.
The first by William Penn, and the second by Thomas Rudyard, a lawyer; in both of which,
particularly the latter,
the illegality and arbitrary proceedings of the court were fully and clearly exposed.

William Penn being now imprisoned for conscience sake, and in manifest violation of law,
wrote very affectionately to his father,
expressing his conviction of the goodness of the cause in which he was suffering,
intimating a design to bring the legality of his
imprisonment before the court of Common Pleas,
and requesting that he would not purchase his freedom by the payment of the fine.
But the admiral was then fast descending to the grave,
and very desirous of the company and consolation of his son;
he therefore did not choose to wait the tardy operation of the law,
but privately sent the money and procured the discharge of both the prisoners.

Notwithstanding the displeasure and mortification which the union of William
Penn with the Society of Friends occasioned his father at the time it took place,
he was now entirely reconciled to him.
Foreseeing that he must often be subjected to inconvenience
from the persecuting laws of the time,
he sent one of his friends to the duke of York, with his dying request,
that he would endeavour to protect his son, as far as he consistently could,
and that he would desire the king to do the same in case of future persecution.
The answers both from the king and the duke, were favourable to the wishes of the admiral.
Only eleven days were left to Sir William Penn,
after the close of the trial at the Old Bailey,
for he expired on the 16th of the same month.

In the course of his illness he thus addressed his son:--"`Son William,
if you and your friends keep to your plain way of preaching,
and keep to your plain way of living,
you will make an end of the priests to the end of the world.`"
It is also remarkable, that in his dying admonition to him,
he strictly enjoined the very course of conduct which had formerly incurred his displeasure,
and risked the loss of all his worldly prospects to maintain.
"`Let nothing in the world, said he, tempt you to wrong your conscience.
I charge you, do nothing against your conscience;
so you will keep peace at home which will be a feast to you in the day of trouble.`"

By the death of his father, William Penn was left in possession of an ample estate,
supposed to be not less than fifteen hundred pounds a year,
which evidently placed him in affluent circumstances.
But from the general tenor of his subsequent life,
it is manifest that he employed his wealth as the
means of being more extensively useful in the world,
and particularly in his own religious Society,
not for the indulgence of those passions which he
made it the business of his life to control and subdue.
