== Chapter IV.

It was not long after the decease of his father,
that William Penn was involved in another public dispute,
in defence of his religious principles and doctrines.
A Baptist teacher, of the name of Ives, residing in Buckinghamshire,
had taken the liberty, in the pulpit,
of casting reflections on the people called Quakers
in general and on William Penn in particular.
This circumstance coming to the knowledge of the latter, he demanded,
and finally obtained an agreement, that a meeting should be held at West Wycomb,
where the doctrines, to which exceptions had been taken, were to be examined.
William Penn was to appear on behalf of Friends, and Jeremy Ives,
the brother of the original assailant, on behalf of the Baptists;
the aggressor himself being judged unequal to the controversy.

The doctrine assailed, was the universality of the divine light,
which William Perm was expected to defend, and the Baptists to oppose.
According to the laws of disputation then in force on such occasions,
it belonged to the assailant to speak first.
He had come armed with a collection of syllogisms ready prepared for his purpose;
and therefore, went on boldly till he had exhausted his stock,
when he stepped suddenly down from his seat and left the place.
The object of that strange procedure evidently was to break up the meeting,
and thus prevent a reply.
But in this he was disappointed, for a small number only,
and they such as belonged immediately to his party, followed his example.
A great part of the audience remained; to them William Penn addressed himself in reply,
and supported the cause which he had undertaken,
to the general satisfaction of the assembly.
Jeremy Ives, mortified at what was passing,
returned and expressed his disapprobation of their conduct.

But instead of gaining his object, he excited the displeasure of the assembly,
which they did not fail to express.
Thomas Ellwood, who was present,
communicated the result of the dispute to one of
his absent friends in the following laconic epistle:

Prsevaluit Veritas: inimici terga dedere: Nos sumus in tuto: laus tribuenda Deo.

Literally--The truth has prevailed: the enemies have turned their backs:
we are in safety: praise be rendered to God.

The conduct of Jeremy Ives in this case,
as well as that of Thomas Vincent two years before, is a sufficient evidence,
that the angry opponents of Friends in that day,
found it easier to villify them and their doctrines, in their absence,
than to meet them in fair and open argument.
It may also be noted as a proof of the sincerity as well as the zeal of our early Friends,
that they were always ready to render a reason for the hope which was in them,
and seldom,
if ever permitted a public attack on their principles or character to pass unanswered.

In the ninth month of this year, William Penn took a short journey,
in the course of which he stopped at Oxford.
There he found that a number of Friends had been cruelly
persecuted by the junior students of the university,
with the connivance, if not the actual encouragement of their superiors,
whose duty it was to instruct and restrain them.
In consequence of this information, he wrote a letter to the Vice-chancellor,
remonstrating in energetic terms, against these abuses,
and warning him of the judgments which would inevitably
overtake the oppressors of the innocent.
In the concluding sentence he declared himself above the fear of man,
whose breath is in his nostrils, and who must one day come to judgment;
because he feared the living God only, who made the heavens and the earth.^
footnote:[It may appear to some readers,
that William Penn was unreasonably severe upon the Vice-chancellor,
and that the misconduct of the students was not properly chargeable on him.
But we find that this man was an active persecutor of the non-conformists,
and about this time so far degraded his own character and station,
as to employ an unprincipled fellow to travel about the country,
and under the assumed character of a religious professor,
insinuate himself into the company and confidence of the various dissenters,
for the purpose of subjecting them to the penalties
prescribed by the persecuting laws of the time.
This man thrust himself upon a Friend, under the assumed character of a Quaker,
but was suspected and dismissed unentertained.
{footnote-paragraph-split}
He
afterwards insinuated himself into the favour of the Baptists,
and drew one of them, who was a man of reputation,
into some incautious remarks upon the severity of the times.
He then impeached him with having spoken treasonable words,
and brought this honest man into danger of losing both his estate and his life.
From this danger he was happily delivered by the opportune discovery
of some vicious conduct which the prosecutor had practised elsewhere,
on account of which he fled from the court and country.
A Vice-chancellor of Oxford, who could employ such characters to effect his purposes,
could expect but little deference from a man of William Penn`'s principles and understanding.
See Gough`'s Hist.
Vol. II. Page 304.]

During the winter of this year he resided at the family seat, in Buckinghamshire.
A pamphlet falling into his hands,
which contained a professed summary of the doctrines held by the Roman Catholic church,
he wrote a reply to it, which he entitled, "`A seasonable caveat against Popery.`"

To prevent a misapprehension of his design, he distinctly stated in his preface,
that he fully believed many of the Romanists were abused zealots,
(ignorantly zealous,) through the idle voluminous traditions of their church,
whom he rather pitied than dared to wrong,
and that he had no design to incense the civil magistrate against them,
for he professed himself a friend to universal toleration in regard to faith and worship.

From the manner in which he treated his subject throughout the essay,
and more especially from some observations near the close,
it appears that he entertained some apprehension that efforts were then about being made,
near the court, to re-introduce the popish religion in its ancient splendour,
into England.

The history of that time,
appears now to prove the position that the establishment of popery and arbitrary power,
were the great objects of the policy pursued by Charles and James.
As an antidote to the lurking poison of popery,
this pamphlet would appear to have been written.

The doctrines and practice of the Romish church,
are exposed with great freedom and severity.
The inconsistency of many of their tenets, with the testimony of Scripture,
with right reason, with the opinions of the early Christians, and with each other,
are clearly pointed out; and the gross immorality of the clergy,
unceremoniously condemned.
If we had no other evidence in the case,
the publication of this tract would be amply sufficient
to refute the calumny of the author being a concealed Papist.
The sentiments more than once expressed in this essay,
that he did not wish to excite the civil magistrate against them,
but was in favour of universal toleration,
was quite consistent with his uniform declarations, and what is more to the purpose,
with his practice when he was afterwards invested with power.

About the end of the year, it appears he returned to London;
and on the 5th of the twelfth month, attended a meeting in Wheeler street.
Sir John Robinson, lieutenant of the tower, having obtained information of his prospect,
sent a sergeant with a file of soldiers to take him.
They took their station near the door,
where they waited until William Penn stood up and began to preach,
when the sergeant pulled him down, and led him to the door.
There a constable and his assistants were standing ready to join him,
and they conveyed their prisoner to the tower and set a guard over him.
In the evening be was taken before the lieutenant for examination.
This John Robinson, we may remember,
was one of the members of the bench at the trial of William Penn and William Mead,
about three months before, at the Old Bailey.
At the time of this examination, there were present, in company with the lieutenant,
Sir Samuel Starling, Sir John Sheldon and others.

When the examination commenced, John Robinson inquired his name,
pretending he did not know him,
notwithstanding their recent acquaintance at the Old Bailey,
and the glaring fact that he had a mittimus already prepared, with his name inserted.
When they were about to prove, by the oaths of the constables,
that he had been taken at a meeting,
he requested that the oath might not be administered,
for he freely acknowledged he was at the meeting at Wheeler street,
and spoke to the people there.
The oath however was administered,
and the testimony obtained was to the same import as his own acknowledgment;
for though the witnesses testified that he was speaking to the people,
they could not be induced to declare that the assembly was an unlawful one.
This appears to have disconcerted Robinson, for he then told William Penn,
that he knew the law, and knew that these things were contrary to law,
without attempting to explain what laws were violated.
William Penn,
concluding that the late Conventicle act was the one which he was supposed to have broken,
began to explain to the company his reasons for believing
that act was not applicable to his case;
but John Robinson informed him they were not going to try him upon that act,
but upon one passed in 1665, usually called the Oxford act,
because the parliament were sitting at Oxford when it was enacted,
having removed thither on account of the plague.
This act, in its terms, applied to "`parsons and others, in holy orders,
who had not subscribed the act of uniformity, and yet had taken upon them to preach,
in unlawful assemblies, and to instil the poisonous principles of schism and rebellion,
in the hearts of his majesty`'s subjects,
to the church and kingdom;`" and required that all such non-conformist
ministers should take an oath of a prescribed form.
In case of refusal to take the oath, they were subjected to certain disabilities,
under heavy forfeitures.
Any two justices of peace,
upon oath made before them of any offence committed against the act,
were empowered to commit the offender to prison for six months.

William Penn immediately showed them, that the Oxford act did not apply to him,
for he had never been in orders at all.
John Robinson however, ordered the oath to be read,
and inquired whether he would take it or not.
He replied,
that he was conscientiously restrained from doing all that
he was required by the oath to engage not to do,
and therefore the oath was to him entirely needless.
He informed them that his refusal to swear was not
on account of the matter contained in the oath;
but was founded on better reasons than they could give for urging him to swear.
In the course of the examination, John Robinson told him, he had been as bad as others;
on which William Penn demanded of him, when and where.
He replied, abroad and at home too.
To which William Penn returned the following energetic reply:
"`I make this bold challenge to all men, women and children upon earth,
justly to accuse me with ever having seen me drunk, heard me swear, utter a curse,
or speak one obscene word, much less that I ever made it my practice.
I speak this to God`'s glory,
who has ever preserved me from the power of these pollutions,
and who from a child begot an hatred in me towards them.
But there is nothing more common, when men are of a more severe life than ordinary,
than for loose persons to comfort themselves with the conceit,
that they were once as they are.
Thy words shall be thy burden, and I trample thy slander as dirt under my feet.`"
The following dialogue then ensued.

John Robinson.--Well, Mr. Penn, I have no ill-will towards you;
your father was my friend, and I have a great regard for you.

William Penn.--But thou hast an ill way of expressing it.
You are grown too high to consider the plea of those you call your forefathers,
for liberty of conscience against the Papists, Cranmer, Latimer, Ridley, Bradford, etc.
It was then plea good enough; my conscience won`'t let me go to mass,
and my conscience wills that I should have an English Testament.
But that single plea for separation, then reasonable, is now by you,
that pretend to succeed them, adjudged unreasonable and factious.
I say, since the only just cause of the first revolt from Rome,
was a dissatisfaction in point of conscience,
you cannot reasonably persecute others who have a right to the same plea,
and allow that to be warrantable.

J+++.+++ Robinson.--But you do nothing but stir up the people to sedition,
and there was one of your friends that told me,
you preached sedition and meddle with the government.

W+++.+++ Penn.--We have the unhappiness to be misrepresented,
and I am not the least concerned therein.
Bring me the man that will dare to justify this accusation to my face;
and if I am not able to make it appear that it is both my practice and all my friends,
to instil principles of peace and moderation,
and only to war against spiritual wickedness,
that all men may be brought to fear God and work righteousness,
I shall contentedly undergo the severest punishment all your laws can expose me to.
And as for the king, I make this offer, that if any living can make it appear,
directly or indirectly, from the time I have been called a Quaker,
since from thence that you date me seditious,
I have contrived or acted anything injurious to his person, or the English government,
I shall submit my person to your utmost cruelties and esteem them all but a just recompense.
It is hard, that I, being innocent, should be reputed guilty;
but the will of God be done: I accept of bad report as well as good.

J+++.+++ Robinson.--Well, I must send you to Newgate for six months, and when they are expired,
you will come out.

W+++.+++ Penn.--Is that all?
Thou knowest a larger imprisonment has not daunted me:
I accept it at the hand of the Lord, and am contented to suffer his will.
Alas! you mistake your interest, you will miss your aim;
this is not the way to compass your ends.

J+++.+++ Robinson.--You bring yourself into trouble, you will be heading of parties,
and drawing people after you.

W+++.+++ Penn.--Thou mistakest, there is no such way as this to render men remarkable.
You are angry that I am considerable, and yet you take the very way to make me so,
by making this bustle and stir about a peaceable person.

J+++.+++ Robinson.--I wish your adhering to these things
do not convert you to something at last.

W+++.+++ Penn.--I would have thee and all men to know,
that I scorn that religion which is not worth suffering for,
and able to sustain those that are afflicted for it.
Mine is, and whatever may be my lot for my constant profession of it,
I am no ways careful, but resigned to answer the will of God, by the loss of goods,
liberty and life itself.
When you have all, you can have no more, and then perhaps you will be contented,
and by that you will be better informed of our innocency.
Thy religion persecutes, mine forgives:
and I desire my God to forgive you all that are concerned in my commitment,
and I leave you all in perfect charity, wishing you eternal salvation.

He was then sent to Newgate, to expiate, by a six months`' imprisonment,
the offence of preaching the Gospel to his brethren,
and refusing to disobey the commandment of Christ.

His imprisonment in this case, though not so manifestly illegal as the former one,
was certainly unauthorized by the act upon which it was ostensibly founded.
It however, does not appear, that he adopted any legal course to procure his discharge,
but waited patiently till the time of his confinement expired.
