== Chapter V.

William Penn did not permit the time of his imprisonment
to be lost to himself or the community;
but wrote several tracts, chiefly of a religious character,
which were soon afterwards given to the world.

The first of these is entitled, "`The great case of Liberty of Conscience,
once more briefly debated, and defended by the authority of reason, Scripture,
and antiquity.`"

The first part of this tract consists of an Address to the supreme authority of England,
dated the next day but one after his commitment.
In this Address,
he gave a rapid sketch of the sufferings which Friends
had endured within the last ten years,
which we may observe, was the time since king Charles`' restoration,
the expectation which had been entertained that the liberty of conscience,
so frequently promised, would be granted,
and the continued disappointment which they had experienced.
He attributed the oppressions which they suffered, in part,
to a want of correct information respecting them and their principles,
and requested that a conference might be granted them, in order that the points,
in which their opinions were deemed unfavourable to the maintenance of government,
might be freely examined and understood.
He expressed a belief, that if such a conference as he desired, was allowed them,
they would be able to evince the consistency of their
doctrines with the peace of the country,
and that the toleration for which he argued,
would be fully compatible with prudence as well as with Christian benevolence.

And finally, if this offer should be disregarded,
and persecution continue to be their portion, he expressed a hope,
that they would be divinely supported, and enabled, by patient endurance,
to weary out their persecutors and obtain a victory more glorious
than their adversaries could achieve by all their cruelties.

The tract is divided into six chapters.

In the first, he lays down the proposition, that imposition,
restraint and persecution for conscience sake, invade the Divine prerogative,
the Almighty alone having a right to control conscience.

In the second, that they are inconsistent with the Christian religion.

In the third, that they oppose the plainest testimonies of Divine writ,
which condemn all force upon conscience.

In the fourth, that they are enemies to the privilege of nature.

In the fifth, that they carry a contradiction to government.

In the sixth, that they reflect upon the sense and practice of the wisest, greatest,
and best states, and persons of ancient and modern times, as of the Jews, Romans,
Egyptians, Germans, French, Hollanders, nay, Turks and Persians also.

These propositions are argued with great clearness and force.
The reasons advanced by the early Protestants for
separating themselves from the Romish church,
are shown to be equally applicable to the case before us.
The absurdity as well as impiety,
of applying pains and penalties to correct the errors of the understanding,
and the scandal which the persecution of one set of Protestants by another,
must occasion among the Roman Catholics, are pointed out; and the wisdom of toleration,
enforced by quotations from numerous writers, ancient and modern.

The dissertation is closed in these words:

To conclude, "`liberty of conscience, as thus stated and defended,
we ask as our undoubted right by the law of God, of nature, and of our own country;
it has been often promised, we have long waited for it, we have written much,
and suffered in its defence, and have made many true complaints,
but found little or no redress.

"`However, we take the righteous, holy God to record against all objections,
that are ignorantly or designedly raised against us, that

"`1st, We hold no principle destructive of the English government.

"`2nd, We plead for no such dissenter, if such an one there be.

"`3rd, We desire the temporal and eternal happiness of all persons,
in submission to the Divine will of God, heartily forgiving our cruel persecutors.

"`4th and lastly, We shall engage, by God`'s assistance, to lead peaceable, just,
and industrious lives amongst men, to the good and example of all.

"`But, if after all we have said, this short discourse should not be credited,
nor answered in any of its sober reasons and requests,
but sufferings should be the present lot of our inheritance from this generation,
be it known to them all, That meet we must, and meet we cannot but encourage all to do,
whatsoever hardship we sustain,
in God`'s name and authority who is Lord of hosts and King of kings,
at the revelation of whose righteous judgments, and glorious tribunal,
mortal men shall render an account of the deeds done in the body;
and whatever the apprehensions of such may be, concerning this discourse,
it was written in love, and from a true sense of the present state of things;
and time and the event, will vindicate it from untruth.
In the mean while, it is matter of great satisfaction to the author,
that he has so plainly cleared his conscience,
in pleading for the liberty of other men`'s,
and publicly borne his honest testimony for God, not out of season to his poor country.`"

As the recent act of parliament under which Friends had been prosecuted,
for attending their religious meetings, was, according to the terms of it,
an act to prevent and suppress seditious conventicles, and the object of the act,
as stated in the preamble was,
to provide remedies against the dangerous practices
of seditious sectaries and other disloyal persons;
and further, as the meetings which were prohibited by that act,
were those which were held under colour or pretence of religion,
William Penn subjoined to the preceding tract a postscript,
showing by an examination of the correct and legal meaning of those terms,
that the act did not apply to the meetings of Friends.
They were not seditious, that is,
productive of strife and debates or dangerous to the government.

They were not conventicles, that is, diminutive secret assemblies,
contriving or designing evil against the government or against particular persons,
but large assemblies, and open to public view.

They were not sectaries; separatists from the body of Truth,
and adherents to strange and unsound opinions.
Neither did they convene to plot and conspire, under colour and pretence of religion,
but in deed and in truth for the worship of God.

Hence, as the ingredients which constitute the kind of assemblies described in the act,
were wanting in the meetings of Friends,
the extension of its penalties to them was a perversion and misapplication of law.
This postscript serves to explain and vindicate the declaration
which he made on his trial at the Old Bailey,
that he had broken no law.

A second tract was entitled "`Truth rescued from Imposture,`" being a reply to
a pretended answer to the account of the trial of William Penn and William Mead,
then just published.
This answer contained among other misrepresentations,
a number of severe reflections on the late Admiral Penn.
The reply refutes those calumnies, and vindicates the character of the author`'s father;
at the same time that it testifies against the employment
in which a large portion of his time was spent.

A third tract was "`A Cautionary Postscript,`" to his first publication,
called "`Truth Exalted,`" which was very short,
but contained a solemn warning to the people of England,
and an encouraging address to such as believed in Christ Jesus, the true Light,
were walking in the daily cross, and through good report and evil report,
were journeying towards an everlasting inheritance.

A fourth tract was,
"`A serious Apology for the principles and practices of the people called
Quakers,`" in reply to the aspersions of Thomas Jenner and Timothy Taylor,
in their book called "`Quakerism Anatomized.`"
This answer is said to have been generally acceptable.

In explanation of the doctrine of Friends on the subject of immediate revelation,
we take the following from this work.

"`First, By revelation,
we understand the discovery and illumination of the light and spirit of God,
relating to those things that properly and immediately concern the daily information
and satisfaction of our souls in the way of our duty to Him and to our neighbour.

"`Second, We renounce all fantastical and whimsical intoxications,
or any pretence to the revelation of new matter, in opposition to the ancient Gospel,
declared by Christ Jesus and his apostles;
and therefore not the revelation of new things,
but the renewed revelation of the eternal way of Truth.

"`Third, That this revelation is the life, virtue, condition,
and very soul of the Gospel and second covenant.

"`Fourth, That none oppose this but such as the god of this world has blinded,
and that through their ignorance of the spirituality of the evangelical dispensation are,
whilst they pretend to be under it, sticklers for a more embondaged state,
than that of the ancient Jews.`"

On the subject of the primary rule of life, he says,

"`Methinks this, our demonstration, should satisfy all:
when neither man nor Scriptures are near us; yet there continually attends us,
that Spirit of Truth, which immediately informs us of our thoughts, words and deeds,
and gives us true directions what to do and what to leave undone.
Is not this the rule of life?
If ye are led by the spirit of God, then are ye sons of God.
Let this suffice to vindicate our sense of a true and unerring rule,
which we assert not in a way of derogation from those holy writings,
which with reverence we read, believe,
and desire always to obey the mind and will of God, therein contained;
and let that doctrine be accursed that would overturn them.`"

To the charge that Friends were displeased with others for observing times,
days and hours, he says,

"`If by set times he means, days set apart, not as more intrinsically sacred,
or in themselves more holy than others, but only to assemble upon, to wait upon God,
and receive of his heavenly benefits, we are so far from being destitute of them,
that as it is impossible for us to perform an action without time,
so have we distinct days and times we meet upon, well known throughout the world,
where any of us do inhabit.
In this sense we cannot be obnoxious; for it is perfect matter of fact,
that in that sense we allow of days and times.
But as to consecrated days and times, and the superstitious observation of them,
as if the holiness of the day called loudly on us for our particular devotion,
as being this or the other saints`',
and not that our devotion rather required a time to be performed in;
this we are displeased with, and boldly testify against, as beggarly and Jewish.
What said the apostle, urged by his godly jealousy,
to the Galatians?'`But now after ye have known God, or rather are known of God,
how turn ye again to the weak and beggarly elements,
whereunto ye desire again to be in bondage?
Ye observe days and months, and times and years.
I am afraid of you,
lest I have bestowed upon you labour in vain.`' Which is defence enough for us;
for if the apostle said it, the Holy Ghost said it; and we are sure,
whoever require or practise any thing contrary to this reproof,
they are great strangers to the liberty of the Gospel,
being yet in bondage to the beggarly elements of weak and antichristian dispensations;
for such implicitly deny him +++[+++Christ]
to be come in the flesh, that hath put an end to them all,
who is the everlasting rest and sabbath to his people.`"

"`In short, I do declare,
that though we utterly renounce all special and moral holiness in times and days,
yet we both believe it requisite that time be set apart for the worship of the Almighty,
and are also everywhere found in the diligent practice of the same.
And howbeit we cannot own so strict an institution as to sabbatize the first-day,
or that it has any holiness inherent to it,
yet as taking the primitive saints for an example,
with godly reverence we constantly assemble upon it.

"`His charge of our denying family duties, is equally false with all the rest;
for we know it is our duty, and it is also our practice,
to retire from our external affairs and wait upon the Lord every day,
that we may receive strength from him,
and feel his heavenly peace and blessing to descend upon us,
at our rising up and lying down; that so to Him, over and above all visible things,
honour and praise may be returned, who is worthy forever.`"

In the sixth chapter he says;

"`I am constrained, for the sake of the simple-hearted, to publish to the world,
of our faith in God, Christ and the holy Spirit.

"`We do believe in one only holy God Almighty, who is an eternal Spirit,
the Creator of all things.

"`And in one Lord Jesus Christ, his only Son, and express image of his substance,
who took upon him flesh, and was in the world; and in life, doctrine, miracles, death,
resurrection, ascension and mediation,
perfectly did and does continue to do the will of God; to whose holy life, power,
mediation and blood, we only ascribe our sanctification, justification,
redemption and perfect salvation.

"`And we believe in one holy Spirit,
that proceeds and breathes from the Father and the Son,
a measure of which is given to all to profit with; and he that has one, has all;
for those Three are One, who is the Alpha and Omega, the First and the Last,
God over all, blessed forever, Amen.`"

Being informed that the parliament had it in contemplation,
to make some addition to the act for suppressing seditious conventicles,
which would be likely to subject Friends and other conscientious
dissenters to great imposition and abuse,
he prepared an address "`to the high court of parliament,`" stating
the injustice already occasioned by the existing law;
the plunderings and ruin to which many families had been subjected,
the sufferings of the poor, the widows and the fatherless, in consequence of it,
and the apprehension which he entertained of the consequences
likely to follow the proposed supplementary enactments.
To show the injustice of subjecting Friends to the operation of such oppressive laws,
he declared;

First, That they owned civil government as an ordinance of God,
for the punishment of evil doers and the praise of them that do well;
and although they could not comply with those laws,
which prohibited them from worshiping God according to their consciences,
because they believed it to be his prerogative alone
to preside in matters of faith and worship,
yet they were ready to yield obedience to every ordinance of man,
relating to human affairs, and that for conscience sake.

Secondly, That they renounced as horrible impiety,
all plots and conspiracies for the promotion of religion or their own interest,
by the blood of those who dissented from them, or even of those who persecuted them.

Thirdly, That in all the revolutions which had taken place,
notwithstanding the injuries Friends had suffered from cruel and ungodly men,
they had conducted themselves in a pacific manner,
and thus given a practical demonstration of the peaceableness of their principles.

Fourthly,
That as Friends had always lived peaceably under the various
governments which had existed since their first appearance,
notwithstanding the injuries they had suffered,
so it was their fixed resolution to continue in the same practice;
and when they could not actively obey, they should patiently suffer,
leaving their cause to God, and thus manifesting to the world,
that they loved him above all, and their neighbours as themselves.

Finally,
he requested that if the parliament should not abandon
their intention of reinforcing their former act,
they would permit the subscribers or some other Friends to explain to them,
the many important reasons they had to offer against such severe proceedings.
And he intimated a hope that the parliament,
upon becoming better informed respecting them and their principles,
would remove the burdens under which they were labouring.
This address was signed by William Penn and several others,
who were then prisoners at Newgate.

The sheriffs of London for that year, being men of moderation,
William Penn wrote to them,
acknowledging the kindness which Friends had received at their hands,
and acquainting them with the rude and savage conduct of some of the keepers at Newgate.

A Roman Catholic having written him a letter, in which he manifested considerable warmth,
on account of what was contained in his "`Seasonable caveat against Popery,`"
William Penn wrote him a calm and dignified reply from his Newgate residence.

In these employments the time of his confinement passed away,
and at the expiration of the six months he was released.
It appears, that soon after, he visited Holland and some parts of Germany,
in the capacity of a minister of the Gospel;
but of these labours or the fruits of them we have no particular account.

In the spring of this year, king Charles issued a proclamation,
suspending the execution of all the penal law, against non-conformists.
This act is attributed, by historians, to a wish to favour the Roman Catholics,
and was considered as a stretch of prerogative.
Its practical effect, however, was very favourable to Friends, near five hundred of them,
who had been imprisoned upon a premunire and some who had been detained several years,
being set at liberty, and the rage of persecution was checked for a time.
