== Chapter V.

In the beginning of 1672, being then in the twenty-eighth year of his age,
William Penn was married to Gulielma Maria Springett,
the posthumous daughter of Sir William Springett,
who lost his life in the war between king and parliament,
in the time of Charles I. His widow was afterwards married to Isaac Penington.
While this daughter was yet young,
the family were convinced of the principles of Friends,
and became valuable members of the Society.
Gulielma was a pious young woman, of amiable manners and highly accomplished.
After their marriage, they took up their residence at Rickmansworth, in Hertfordshire.

His marriage, and the consequent cares of a family,
did not prevent the exercise of his ministerial gift,
for besides the attendance of meetings in his own neighbourhood,
he visited Friends in the course of the year, in Kent, Sussex and Surry.
His labours in this journey were to general edification,
contributing to strengthen Friends and silence opposers,
and he and his companions were filled in the performance
of this duty with spiritual consolation.

He closes his narrative of the journey in the following manner:
"`The Lord sealed up our labours and travels according
to the desire of my soul and spirit,
with his heavenly refreshments and sweet living power and word of life,
unto the reaching of all, and consoling our own hearts abundantly.
Thus hath the Lord been with us in all our travels for his Truth,
and with his blessings of peace are we returned,
which is a reward beyond all worldly treasures.`"

In the ninth month of this year, being at home, he wrote a letter to Dr. Hasbert,
a physician at Embden,
with whom it appears he had become acquainted when he was in that country,
cautioning him against taking his rest in a profession of religion,
without the experience of its effectual and purifying operation in his own mind,
and exhorting him to attend to the teachings of the spirit of Truth in his heart;
that by living in the cross, not only to the sins,
but also to the righteousness and judgment of the world, he might come to inherit glory,
immortality and eternal life.

The sunshine of royal indulgence soon brought from their places of retreat,
some of those dissenters who kept out of sight while the
storm was spreading its rage on the heads of others.
The persecuting laws, which together with the barbarous manner of their execution,
have stamped an indelible stigma upon the reign of Charles II.,
were probably designed by their authors to crush the Presbyterians and Independents,
on account of their political opposition to the dominant party.
Yet as the religion of many of these people was abundantly more
pliable than that embraced by William Penn and his fellow professors,
the burden of persecution fell principally, though not wholly on the latter.
Their unflinching support of their religious meetings and
their constant refusal to take the oaths required of them,
furnished employment and plunder for the harpies of the law.
Besides,
as it was vain to expect a general conformity to the religion
of the court among the dissenters at large,
while there was one society which openly refused to mould its doctrines
or worship to the opinions of the Episcopal church,
the principal efforts of the established clergy appear
to have been directed to their suppression,
from a conviction, that if they were once removed out of the way,
the other dissenters would be likely to yield with more facility.
But while they thus weathered the storm and sheltered the heads of other dissenters,
Friends could not fail to attract the attention of the more sober and considerate class,
and a religion which was found capable of supporting its
professors under such sufferings as were cast upon them,
was very likely to gain proselytes among those who were witnesses of their constancy.

Thus the firmness and faithfulness of Friends,
carried conviction to the minds of many religiously disposed persons of that day,
who were induced to abandon the societies to which they belonged,
and unite in fellowship with them.
This sometimes roused the zeal of their former teachers,
and occasioned repeated attacks upon the principles and characters of Friends.
One of those teachers, about this time published anonymously,
a tract called the _Spirit of the Quakers Tried,_ which
brought William Penn again before the public in a reply,
entitled the _Spirit of Truth Vindicated._

John Reeve and Lodowick Muggleton,
who professed to have been favoured with extraordinary revelations,
having excited considerable attention, and drawn a number of people after them,
William Penn wrote a tract, in the autumn of this year,
detecting and exposing the impostures of these pretended prophets,
under the title of the _New Witnesses Proved Old Heretics._
A copy of this treatise was sent by the author to Muggleton, with a letter,
severely rebuking him for his presumptuous profession, and exhorting him to repentance,
if haply he might yet find forgiveness from an offended God.

John Morse, an Anabaptist preacher of Watford,
having published some reflections against the Society
of Friends in general and William Penn in particular,
he wrote a reply entitled, _Plain Dealing with a Traducing Anabaptist._

_Controversy Ended,_ soon followed, which was the production of Henry Hedworth,
another preacher, and which was of a similar stamp with the former.
His answer to this was entitled, _A Winding-sheet for Controversy Ended._

John Faldo, an Independent preacher, near Barnet,
finding that some of his hearers had united with Friends, was greatly incensed,
and gave vent to his displeasure, by writing and publishing a book,
entitled [.book-title]#Quakerism No Christianity.#
To this William Penn wrote a reply, with the title,
_Quakerism a New nickname for Old Christianity._
John Faldo soon after published a Vindication of his former production,
which was followed on the part of William Penn, by a rejoinder,
styled the _Invalidity of John Faldo`'s Vindication._
In the following year, John Faldo repeated his attack, and William Penn returned a reply,
which closed the contest between them.

As these tracts, elicited by John Faldo`'s attack, form collectively a considerable work,
being more than two hundred pages in the folio edition of our author`'s writings,
a brief analysis of them, may probably be acceptable to my readers.

Our author begins by expressing his regret that the predictions of some,
who are not friendly to the dissenters, that if tolerated by the government,
they would quarrel among themselves,
should be so amply verified by this assault upon them.
The declared wish of Friends was to live peaceably with all men, but when thus assailed,
silence might be construed as an evidence of incompetency to defend their principles.
This defence, is therefore a necessary vindication of their doctrines and characters.

He then lays down the doctrine, that although it pleased God,
at the opening of the Christian dispensation, to send his Son, a light into the world,
yet he was in degree spiritually manifested in all ages,
as the Word of God nigh in the heart, and that they who believed in and obeyed Him,
obtained remission of sins and eternal salvation.
Thus Christ was the Rock which followed Israel, and whose day Abraham saw and was glad.
That Christianity is not a mere historical belief of the
outward acts which Christ performed in his bodily appearance,
but a firm belief in Him that so appeared, had died, rose and ascended,
both as testified in the Scriptures of Truth,
and as he breaks in upon the soul by his divine discoveries,
as the true light enlightening every man.

The testimony of Friends to the divine light or manifestation
of the spirit of Jesus Christ in the soul,
having been made an occasion to charge them with denying his outward manifestation,
the falsehood of this charge is proved, and it is shown,
that the latter being universally admitted,
while the former was either overlooked or denied,
by many of the professors of Christianity,
Friends have been specially called to bear testimony to
the`' inward and spiritual appearance of Christ to the soul,
a measure of whose spirit is given to all, reproving the unfruitful works of darkness,
and leading to a true knowledge of the way of life and salvation.

Christianity having been introduced into the world
more than sixteen hundred years before that time,
and Quakerism only about the middle of that century,
John Faldo infers that the latter is not Christianity;
but William Penn shows that the same argument would
unchristianize him and all the modern dissenters,
and that the revival of the ancient doctrines of
Christianity after a long night of apostacy,
is no evidence of a new religion.

John Faldo advances the charge, that the Quakers deny the Scriptures, which,
upon a little examination,
is found to mean nothing more than that they do not admit that they are the Word of God.
In explanation of this charge,
it is declared that Friends believe the Scriptures to be the words of God,
and a declaration of the mind and will of God to those ages in which they were written;
that they were given forth by the holy Spirit, moving upon the minds of holy men,
and that they ought to be read and believed in the present day,
being profitable for doctrine, for reproof, for correction,
for instruction in righteousness; but that the Scriptures apply the term, the Word,
or Word of God, to Christ and not to themselves.
Friends, therefore, apply that term only to Christ Jesus, the living,
all-powerful and quickening Word, by which God vouchsafes to disclose his will to man.

To John Faldo`'s charge,
that the Quakers deny the Scriptures to be the primary and principal rule of faith,
it is answered, that the Spirit from which the Scriptures emanated,
are the primary and proper rule of faith; even the grace of God in the soul of man,
of which the Scriptures testify.
Yet that the Quakers utterly reject all such as deny
the Scriptures to be profitable for doctrine,
for reproof, instruction and edification; earnestly contending,
not against the Scriptures, but for that living experimental knowledge of them,
which those witness who are truly taught and led by the Spirit.

To the charge that the Quakers deny a Gospel church, he answers,
we believe there is one and but one universal church, the pillar and ground of Truth,
and that it is in God, anchored, established and built upon the Rock of ages,
and foundation of many generations.
And as such, neither is every visible society,
making profession of religion nor all of them together, that church;
but such alone as are washed in the blood of the Lamb, and engrafted into the true Vine,
bringing forth the fruits of holiness, to the honour,
glory and renown of Christ the Head, who is over all God blessed forever.

In regard to preaching and prayer, on which some singular charges had been made,
our author declares that Friends believe and preach no other doctrines,
than what are contained in the Scriptures.
That the true Gospel ministers are called by Christ Jesus,
and anointed by him for his own work;
and that acceptable prayer is only from the motions of the Spirit of God in the heart.

On the subject of baptism and the supper, our author proves,
that the baptism enjoined by our Lord in his final charge to the disciples,
was not with water, but with the Spirit;
and that those who experience a spiritual communion with the Father and the Son,
have attained the substance, of which the bread and wine were a figure.

John Faldo having charged Friends with denying that the actions of Jesus Christ in the
flesh had any influence in procuring our justification before God and our salvation;
William Penn replies, that justification in Scripture language has a two-fold meaning,
viz: remission or non-imputation of sin, upon repentance and faith in the promise of God;
and purification of heart, an inward and real righteousness.
And that Christ was and is God`'s free gift, by whom alone remission,
justification and eternal salvation can be obtained; and that faith in him,
as to his visible appearance, works and death in the world,
and obedience to his teachings and leadings by his Spirit in the heart, are necessary.

One of John Faldo`'s last charges,
exhibited in his [.book-title]#Quakerism No Christianity,# is that
the Quakers do not profess a belief in future rewards.
To this William Penn returns a positive denial,
and challenges his opponent to name one acknowledged member of the Society,
who has ever made such a declaration.
The subsequent strictures on the writings of John Faldo,
consist chiefly of further explanations of the subjects embraced in the preceding analysis.

About the same time, Henry Hallywell published a work, entitled _An Account of Familism,
as It Is Revived and Propagated by the Quakers,_ in which he asserted,
that their doctrines were destructive, both of civil government and religion.
This drew a reply from William Penn,
under the title of _Wisdom Justified of Her Children,_ in which the
errors and misrepresentations of the assailant are clearly exposed,
and the doctrines of Friends on the several points which were drawn into controversy,
successfully vindicated.

In the fourth month, 1673, we find William Penn,
in company with his wife and George Whitehead,
attending the meetings of Friends at Bristol;
but of this journey no particular account remains.

His time appears to have been chiefly occupied in writing; and indeed,
the works produced by his pen, in this and the following year,
were quite enough to engross the time of a man of ordinary industry.

Thomas Hicks, a preacher among the Baptists of London,
was among the number of those who laboured to render the Society of Friends,
and the principles which they held, odious in the sight of the people of that day.
He published a pamphlet,
called _A Dialogue Between a Christian and a Quaker,_ so artfully managed,
that an incautious reader might readily suppose this pretended dialogue a real one.
Having both sides of the controversy to manage,
he took care to make his pseudo-quaker talk in a very weak and ridiculous manner,
and utter opinions grossly erroneous and objectionable;
so that such readers as mistook the caricature for
a true portrait of the principles of Friends,
could not fail to entertain very unfavourable opinions respecting them.
Upon the appearance of this pamphlet,
William Penn wrote the first part of his _Christian Quaker,
and His Divine Testimony Vindicated._

The object of this work is principally to explain and vindicate the doctrine
of the Light of Christ being manifested in the hearts of all men,
as the root and spring of Divine life in the soul, to those who receive and obey it,
which is a distinguishing characteristic of the faith
and testimony of the people called Quakers.
The salvation to which this Divine light leads its followers,
is shown to be a redemption from sin here, and from its consequence, wrath to come.
This light comes from Christ, the Sun of Righteousness,
who enlighteneth every man that cometh into the world, and leadeth those that obey him,
to eternal salvation.
It convinces of sin, and leads those who obey it, out of all sin;
and the reason that all mankind are not led by it into righteousness is,
that all are not obedient to it.
This light was dispensed, though in a much less degree,
before the appearance of Christ in the flesh; and the Gentiles as well as the Jews,
were favoured with it.
He also shows the harmony of this doctrine with the
other great fundamental principles of the Gospel;
as the divinity of our Lord and Saviour Jesus Christ, his mediation, etc,
and the propitiatory sacrifice which he made on the cross for the sins of all mankind.
Such are the leading doctrines of the work,
and they are illustrated and enforced by numerous arguments,
drawn from Scripture and the writings of a number of ancient authors.
But the work of Thomas Hicks is not, I believe, any where mentioned in it,
though his misrepresentations were obviated.

It was not long until a second pamphlet from the same author, was given to the world,
under the character of the _Dialogue Continued,_ in which
he reiterated the false accusations against the Quakers;
but the _Christian Quaker,_ was not noticed.

William Penn soon made a direct reply to these pretended dialogues,
under the title of _Reason Against Railing, and Truth Against Fiction._

In this, he first points out the unfairness of their assailant,
manifested by making his pseudo-quaker deliver sentiments which Friends had never uttered,
instead of making them express their real opinions, and then refuting them if he could.
He next shows,
that where unsound doctrines are professedly deduced from the declarations of Friends,
their meaning has been perverted.
He afterwards proceeds to vindicate the sufficiency
of the Divine light in the heart of man,
to lead in the way of life and salvation, and to show,
in opposition to the objections of his opponent,
that the degeneracy of man in faith and worship,
is no evidence of the insufficiency of this Divine light;
and that an argument against its sufficiency, derived from this consideration,
would be equally available to show,
that the Scriptures and all other means divinely afforded for the salvation of man,
are inadequate to their object.
Neither can it be fairly inferred, that because other means, promotive of the same end,
have been dispensed to us, the Divine light is insufficient.
The acknowledgment of Christ Jesus, as the light and life of man,
does not lead to a denial of his appearance and work in the prepared body,
nor of the important benefits conferred upon mankind,
by what he performed and suffered in that outward manifestation, but confirms them;
yet the work of man`'s salvation is preeminently to be
ascribed to the Word which was in the beginning with God,
which is God, and likewise, the light and life of men.
This Divine teacher and Word of life,
is proved to be the primary rule and guide of saving faith.
The doctrine of justification by an imputed righteousness,
without actual purification from sin, is refuted, and its dangerous tendency exposed.
Thomas Hicks charged Friends with denying the resurrection of the dead and eternal recompense,
because George Whitehead had quoted the saying of the apostle, "`Thou fool,
the body which thou sowest is not the body which shall be,
but God giveth it a body as it pleaseth him.`"
To which William Penn replies,
that we acknowledge a resurrection in order to eternal recompense,
and rest contented with the body which it shall please God to give us,
without vainly inquiring what body that shall be.

Of this tract, as of many other controversial writings of that day,
it may be justly observed,
that there is more severity of language than we should now consider
becoming a defence of the doctrines of a meek and crucified Saviour.
But in forming a judgment upon this subject,
we ought not to overlook the manners of the times.
The period in which these works appeared,
was one in which strong emotions were not unfrequently expressed in corresponding language.
And the sincerity, which was a remarkable characteristic of our primitive Friends,
naturally led them to express their sentiments without disguise or concealment.
It may also be remembered, that if their language was sometimes harsh,
their actions appear to have been uniformly inoffensive.

Thomas Hicks, not yet satisfied,
issued a third pamphlet as a further continuation of the dialogue,
which drew from William Penn another reply,
entitled _The Counterfeit Christian Detected, and the Real Quaker Justified._
This tract consists principally of the exposure of Thomas Hicks`' perversions,
either of the words or meaning of those passages in his writings or those of other Friends,
which he professed to quote.
To this Thomas Hicks made no reply.
The controversy however did not end here.
Thomas Hicks had made so many misrepresentations
of the character and principles of Friends,
and particularly of William Penn and George Whitehead,
that a complaint against him was presented to his fellow professors, in and about London.
A meeting was, in consequence, appointed to be held in one of their houses,
avowedly for the purpose of examining into the truth
of the charges which were exhibited against him.
But the time of this meeting was fixed, either from accident or design,
when both William Penn and George Whitehead were absent,
on a religious visit to a distant part of the island.
When notice of the intended meeting was left at their lodgings Friends informed
the Baptists that they were too far from the city to obtain intelligence,
either by letter or express, in time to attend the meeting,
and requested its postponement until they could be present.
This request was not granted,
but a large attendance of those who were favourable to Hicks was obtained,
and but few of those who could expose his calumnious charges being present,
he was readily acquitted.

When William Penn returned to London,
he laid his complaint of these partial proceedings before the public,
and demanded another meeting of the Baptists,
in order that the complaint of Friends might be heard.
To this demand, after considerable opposition and delay, they assented,
and a meeting was appointed to be held in their own house at Barbican, London.

When the parties met, Thomas Ellwood undertook to read the charges against Thomas Hicks,
which, not without considerable difficulty, he at length effected.
But instead of entering upon an examination of those charges,
the Baptists commenced an attack upon William Penn`'s _Christian Quaker._
As William Penn in that work, as well as others,
advanced and maintained the Scriptural doctrine, that the Light,
which lighteth every man that cometh into the world, is Christ;
they took occasion to infer from thence, that he, and therefore the Society of Friends,
denied his manhood, and consequently were no Christians.
Friends were therefore drawn into a discussion of that question.
The principal disputants on the side of the Baptists, were Thomas Hicks and Jeremy Ives,
and on the part of Friends, William Penn, George Whitehead, and George Keith.

It may perhaps be interesting to some of my readers,
to see a specimen of the manner in which the opponents of Friends in that day,
attempted to unchristianize the Society.
The prevailing mode of conducting polemic discussions, at that time,
was to reduce the propositions which were intended to be established, into syllogisms,
and much of the skill displayed in argument,
consisted in the facility of reducing propositions to that form.

Thomas Hicks appears to have commenced the dispute with this argument:

[.syllogism]
* They that deny the Lord`'s Christ are no Christians.
* But the Quakers deny the Lord`'s Christ.
* Therefore they are no Christians.

To this William Penn returned, "`I deny the minor,
viz. that the Quakers deny the Lord`'s Christ.`"

Thomas Hicks replied,

[.syllogism]
* They that deny Christ to be a distinct person without them, deny the Lord`'s Christ;
* But the Quakers deny Christ to be a distinct person without them,
* Therefore the Quakers deny the Lord`'s Christ.

William Penn then desired,
that Thomas Hicks would explain what he meant by the term person; to which he answered,
that he meant the man Christ Jesus.
William Penn then replied, "`I deny the minor, viz. that we deny the man Christ Jesus.`"

Thomas Hicks replied, "`I prove that ye deny the man Christ Jesus:
one of your writers asserts, that Christ was never seen with carnal eyes,
nor heard with carnal ears.`"
From which Jeremy Ives framed a syllogism.
"`He that denies that Christ was ever seen with carnal eyes, denies the Lord`'s Christ,
but the Quakers deny that Christ was ever seen with carnal eyes;
therefore the Quakers deny the Lord`'s Christ.`"

George Keith then replied, that Christ, as God, was never seen with carnal eyes;
but as man he was.

Ives replied, But he was Christ as he was man;
how then was not Christ seen with carnal eyes?

George Keith rejoined,
"`We are to consider that the terms Jesus Christ are sometimes applied to him as God,
and sometimes as man; yea sometimes to the very body of Jesus: but the question is,
whether those names more properly, immediately and originally belong to him as God,
as he was before he took the manhood upon him; or to the manhood?
We affirm, that those names are given to him most properly and eminently as God;
and less properly, yet truly as man; and least properly to his body; yea,
to his dead body.`"

This brought from Jeremy Ives,
an expression which excited considerable disgust among the audience:
but William Penn besought them to treat the subject in a manner becoming Christians,
which appears to have quieted them,
and George Keith proceeded to show that the term was applied to the dead body,
from the expression of Mary, "`They have taken away my Lord,
and I know not where they have laid him;`" and from that of the angel,
"`Come see the place where the Lord lay.`"
And that he was Christ before he took flesh, from the saying of the apostle;
"`who created all things by Jesus Christ.`"

Jeremy Ives still urging the opinion,
that a declaration that Christ cannot be seen with carnal eyes,
and was never seen by wicked men, was a denial of the Lord`'s Christ;
William Penn explained the subject, by stating,
that wicked men might see him in his bodily appearance,
and yet not see him to be the Christ of God.
They might see his manhood but not his Christship.
This was illustrated by the declaration of our Lord to Peter,
when he had acknowledged him to be the Christ, the Son of the living God,
viz. "`Flesh and blood hath not revealed it unto thee,
but my Father which is in heaven.`"
Hence he inferred that Peter could not, with a carnal eye, have seen the Lord`'s Christ,
much less could wicked men.
A further proof was derived from the words of the apostle;
"`Whom none of the princes of this world knew, for had they known him,
they would not have crucified him.`"
He also observed,
that seeing and knowing were sometimes used in Scripture as equivalent terms;
to which George Keith added the saying of Christ; "`He that hath seen me,
hath seen the Father,`" observing that no wicked man had seen the Father,
and therefore no wicked man had seen Christ as such.

The Baptists derided this distinction; but Friends still averred,
that those who saw Jesus, as the carpenter`'s son,
did not all see him as the Christ of God.

Jeremy Ives then asked, "`Is the manhood a part of the Lord`'s Christ?`"

To this William Penn returned the inquiry,
Is this to prove the charge of our denying the Lord Christ?
It seems we must be here to be catechised, and ye will not answer us one question,
yet I shall answer Jeremy Ives`' question, if he will promise to answer mine.
Jeremy Ives promising that he would, William Penn replied,
that they believed that holy manhood to be a member of the Christ of God:
and then directing his discourse to Jeremy Ives, he asked,
"`Was he the Christ of God before he was manifest in the flesh?`"
"`He was,`" returned Jeremy Ives, "`the Son of God.`"
But to the question as stated by William Penn, he would not answer.
His silence in that case was attributed to the prevalence
of Socinian opinions among them,
which William Penn probably designed to make him acknowledge or deny.
But he was too cautious to do either.
William Penn adduced, in proof of the affirmative of his own question,
the declaration of the apostle,
"`They all drank of that spiritual Rock that followed them,
and that Rock was Christ:`" and the epistle of Jude, in which,
according to some of the Greek copies,
it is stated that Jesus brought the people of Israel out of Egypt.

Though Jeremy Ives would not return a direct answer to the question of William Penn,
he soon propounded another to Friends, viz. Whether they believed that Christ,
in his human nature, was in heaven.
This caused George Whitehead to observe,
that the auditory had heard the charge advanced against them,
and the distinction that had been made between the
spiritual saving sight of the Lord`'s Christ,
and the seeing of his outward man, person, or body.
In this last sense it could never be intended that it was not visible to the outward eye,
but it was the spiritual Rock which all Israel drank of, as he was before Abraham was,
and as glorified with the Father before the world began;
and as Christ himself said to Philip, "`He that seeth me,
seeth my Father also,`" and only saints, or children of light, could truly say,
We have seen his glory as the only begotten of the Father, full of grace and truth.
In all which senses of seeing,
the Lord`'s Christ was only seen spiritually and not with carnal eyes.

To this Jeremy Ives agreed--yet he soon repeated the question,
whether they believed that Christ was in heaven with his human nature.
To which William Penn replied,
"`We do believe the man Christ Jesus to be glorified in heaven.`"
This answer, not being in the terms of the question, was rejected as insufficient.
Upon which William Penn inquired,
what difference he made between the manhood and human nature of Christ.
None, was his reply, if you answer candidly.
To which William Penn replied, "`I do mean and speak candidly;
we believe that holy manhood to be in heavenly glory.`"

Night coming on, a proposal was made to quit for that time,
and resume the subject at another, but nothing was settled,
and the meeting was broken up rather abruptly.

The reader may well wonder why an assembly which was convened to examine the
charges which Friends were prepared to offer against one of the Baptist preachers,
should be occupied in the discussion of such questions as these.
But we may remember, that the object of Thomas Hicks`' pamphlets,
was to show that Friends were not Christians.
He and his brethren therefore, still kept this object in view;
and instead of going into the inquiry,
whether he had endeavoured to effect his object by misrepresentations and falsehood,
they laboured to establish the original charge.
This was evidently evading the demand of Friends to which they had professedly acceded.

But even if the proper business of the meeting had been to establish this charge,
it must, in fairness and equity, have been attempted by an exposure of their doctrines,
as already declared, either in their acknowledged writings,
or in their public testimonies.
And having failed in the attempt to establish it in that manner,
the charge ought to have been abandoned.
But we see, that when the documents relied on for sustaining the charge, were explained,
the expedient of asking them questions,
and thus endeavouring to convict them by their confession on the spot, was adopted.
William Penn had penetration enough to see the object and unfairness of this procedure,
but as Friends had no doctrinal opinions which they were afraid or ashamed to avow,
they gave candid, though cautious answers to these ensnaring questions.

From the narrative of this controversy, two inferences may be fairly deduced--first,
That the only tenable ground upon which the opponents of our early
Friends attempted to divest them of the Christian character,
was the greater spirituality of their doctrines.
And, second,
That while they faithfully and fearlessly maintained their
testimony to the spiritual nature of the Christian religion,
and rejected the gross and carnal constructions so generally
given to the declarations of our Lord and his apostles,
they never refined away the plain and obvious truths which the sacred volume contains.
They in fact,
adhered very closely to the letter as well as to the spirit of the Holy Scriptures.

The meeting at Barbican having separated abruptly,
Friends endeavoured to procure another for the purpose of examining
and establishing their charges against Thomas Hicks;
but as he and his supporters declined a compliance with their request,
they appointed one in their own meeting-house, at Wheeler street, London,
and gave the Baptists timely notice of it.
This meeting Thomas Hicks did not think proper to attend;
but sent his friend Jeremy Ives, and some others of their party,
who were so far from entering into an examination of the charges
which Friends had to offer against their fellow-professor,
that they would not even suffer them to be heard.
The object which Friends had in view,
viz. to obtain from Thomas Hicks an acknowledgment
of the injustice with which he had treated them,
or from his fellow-members a disavowal of his unchristian conduct,
was therefore no more answered by this meeting than by the former.
The controversy was subsequently continued awhile by Thomas Ellwood,
on the part of Friends, and Thomas Plant, one of Thomas Hicks`' compurgators,
on the side of the Baptists.
But William Penn does not appear to have taken any further part in the contest.
The effect which Thomas Hicks had encountered all this toil to prevent,
was eventually promoted by the controversy;
for a number of those who previously adhered to the Baptists,
were induced by what they saw and felt, in the course of these proceedings,
to abandon that Society, and join in religious fellowship with Friends.

Although John Faldo,
after the publication of William Penn`'s strictures already mentioned,
appeared no more in his own name as an antagonist,
yet he was the means of prolonging the controversy;
for he assembled a council of clergymen, by whose advice his first work,
called _Quakerism No Christianity,_ was republished.
This edition was accompanied by a commendatory preface,
which was produced by the united labours of this assembly.
This drew from William Penn a pamphlet,
entitled _A Just Rebuke to One-and-Twenty Learned and Reverend Divines,_ (so called.)
As this work was not intended to enforce or explain the doctrines of Friends,
but rather to expose and refute the errors or misrepresentations of their opponents,
it may be justly considered as one of a temporary character.
I shall therefore, give no other account of it than to observe,
that while it breathes the same spirit of piety which
pervades the works of this author in general,
and manifests the same desire for the substantial improvement of the reader,
we find in it a greater share of keen and piercing wit than
in most of the other writings of William Penn.
He has evidently considered these one-and-twenty, self-styled,
learned and reverend divines, as engaged in an enterprise much beneath their profession,
and treated them accordingly.
Dr. Henry Moore,
who was then considered to be one of the most pious
and learned men in the church of England,
soon after the publication of this pamphlet, addressed a letter to William Penn,
in which he observed, that he found in it such a taste, both of wit and seriousness,
and the argument so weighty,
that he was induced to purchase and read the tracts on both sides of the controversy;
and that he found in the writings of our author,
several passages which were nobly Christian,
containing a testimony which he highly prized,
and on account of which he felt no small degree of esteem for the writer.
I do not find that John Faldo or his coadjutors made any reply to this pamphlet.
They probably thought of his facts, as welt as his arguments,
that the less was said of them the better it would be for them and their cause.

Alexander Parker, one of the early members and ministers of the Society, had published,
about the year 1657, a tract,
entitled a _Testimony of the Light Within,_ of which Samuel Grevill,
a priest near Banbury, wrote a pretended refutation.
The doctrine thus assailed, being one of great importance, and indeed,
lying at the foundation of the testimony which Friends
believed themselves called to support,
William Penn produced a pamphlet entitled _Urim and Thummim,
or the Doctrines of Light and Perfection Maintained,_
in opposition to that of Samuel Grevill;
proving from Scripture testimony, that the witness for God in the mind of man,
is the light of Christ,
the true light which lighteth every man that cometh into the world,
and that this light not only discovers to us what is sinful,
but is sufficient as it is followed and obeyed, to lead out of all sin,
into the glorious liberty of the children of God.
He lays it down as the reason why many of the professors of religion
deny the sufficiency of this Divine light or holy Spirit,
to lead into entire redemption and to the knowledge of God, whom to know is life eternal,
that they have known it only as a reprover, and have not, for want of obedience,
experienced the salvation from sin and death to which it leads;
and admonishes his readers to try the effect of obedience to its small and tender appearances,
before they object to its nature or sufficiency.

We have in his printed works, under date of this year, a doctrinal treatise,
entitled _Of the General Rule of Faith and Practice._
He describes "`the general rule`" to be,
"`that constant measure or standard by which men,
in all ages have been enabled to judge of the truth or error of doctrines,
and the good or evil of thoughts,
words and actions;`" and faith to be "`an assent of the mind in such manner,
to the discoveries made of God thereto,
as to resign up to God and have dependence upon Him,
as the great Creator and Saviour of his people, which +++[+++faith]
is inseparable from good works.`"
The object of this tract is to show the unsoundness of the opinion
so generally entertained by the professors of Christianity,
that the Holy Scriptures compose the general and primary rule of this faith and practice.

In opposition to this opinion,
he lays it down that a rule cannot be general which is limited in its nature.
That mankind, in all ages, and long before the Scriptures were written,
had some knowledge of God; and that knowledge must have been given by Divine inspiration.
The rule of faith by which the righteous walked before
any part of the Scriptures were written,
was the light of Christ, the law divinely written in their hearts.
This is more ancient and more general than the Scriptures.
The righteous had this rule of faith before they had the Scriptures,
and the faith of God`'s people in all ages, being of one and the same nature,
the rule must be the same.
This faith is inward and spiritual,
therefore the rule of faith is also inward and spiritual.
The Scriptures no where declare themselves to be the general rule of faith,
and therefore those who declare them such, deviate from Scripture authority,
and make their own interpretation, and not the Scriptures the rule.
It is under the enlightening operations of the holy Spirit,
that the Scriptures are properly and savingly understood, therefore the former,
and not the latter is the primary rule.
This is a very brief summary of the doctrines contained in this essay,
which are enforced by various arguments and illustrations,
and fortified by the testimonies of a number of pious men, in ancient and modern time.

The controversies in which William Penn had been hitherto engaged,
were with persons of other religious persuasions;
but at the time to which we are now arrived,
he was drawn into a contest with some who professed
to hold the same fundamental doctrines as he did.
The prime mover in this controversy, was John Perot,
a man who appears to have possessed more imagination than judgment,
and a much higher opinion of himself than his attainments, natural or spiritual,
justified.
He was one, who at an early day joined the Society,
and too soon engaged in the important service of the ministry.
Imagining himself commissioned to convert the pope,
he procured a man of the name of John Luff to accompany him on this embassy.
Arriving at Rome, they were soon arrested and cast into prison.
John Luff was confined in the inquisition, where he died,
not without circumstances exciting the opinion that he was privately murdered.
John Perot was committed to the bedlam,
from whence he occasionally found means to transmit letters to England for publication,
expressed in a style which seemed to indicate that the place of his confinement
was not altogether unsuitable to the state of his mind.
After being a considerable time in confinement,
his release was procured by the solicitation of some of his friends,
and he soon afterwards returned to England.
The report of his sufferings at Rome, which common fame had exaggerated,
united to the appearance of unusual sanctity,
gave him more place than he deserved in the minds
of some well meaning but not very judicious Friends.
Mistaking the suggestions of his own misguided imagination,
for the indications of the Divine Spirit,
he declaimed against the practice of taking off the hat in time of prayer,
as a piece of formality, inconsistent with the spirituality of the Christian religion,
unless they felt themselves divinely required so to do.
And a number of the less experienced Friends were
carried away with his notions and adopted his practice.

As Friends had always considered the uncovering of the head,
when they approach the Supreme Being in prayer,
as an external sign of the homage due to Him,
and of the reverence with which they engage in that solemn act;
and furthermore the practice of praying vocally with the head covered,
is directly contrary to the apostolic admonition;
the conduct of John Perot and his followers was disapproved
by the most judicious among them.
At a meeting held in London in 1666,
George Fox laboured to convince those Friends who had fallen into it,
of the impropriety of this unseemly practice,
and with such success that most of them acknowledged their error,
and united with their more experienced brethren.
John Perot however, was too confident of the correctness of his own opinions,
or too obstinate to change his course, and was at length disowned.--Whether he had,
previously to his disownment, manifested any considerable deviations in other respects,
certain it is, that subsequently he cast off the profession,
fantastically putting on a fashionable dress and wearing a sword,
and afterwards removed to America, where he obtained an office in the government,
and became a rigid exacter of oaths.

After his disownment, a pamphlet was published, without the name of the author,
but attributed to him,
with the title of _The Spirit of the Hat,_ to which William Penn wrote a reply with
the curious title of _The Spirit of Alexander the Coppersmith Justly Rebuked._
Shortly after the appearance of the latter, a second anonymous pamphlet,
under the title of _Tyranny and Hypocrisy Detected_ was given to the world.
This came out under the character of a reply to _The Spirit
of Alexander the Coppersmith Rebuked;_ and like the former,
was understood to be the work of John Perot.
It drew a rejoinder from William Penn,
which he styled _Judas and the Jews Combined Against Christ and His Followers._

This controversy assumes a degree of importance which it would
not otherwise possess from the principles involved in it.
This anonymous writer took the ground,
that those who refused to uncover their heads at the time of prayer,
were led to this practice by the light of Truth in their own minds,
and that a requisition, on the part of other Friends,
of a conformity to the usages of the Society in this respect,
was an abridgement of their Christian liberty.
Their charge against the Society, is thus concentrated.
The Quakers teach that every man is enlightened with a manifestation of the holy Spirit,
sufficient to salvation, and that all faith in, and worship of God,
ought to depend upon the convictions and leadings of this Divine light;
yet they were required by the body of Friends,
to do what they had no inward motion to do, but rather to omit;
and that upon a refusal to comply with this demand, they were disowned.
Hence the sufficiency,
convictions and leadings of the light must yield to the decisions of the body,
and not the body to the light.

Consequently, the body of the Society, not the Divine light in the heart,
had become the rule with the Quakers.
The consequence of disownment was also exaggerated,
as including a denial of the privilege of marriage, burial, trading, etc.
This appears plausible, and to put the question at issue in a proper view,
William Penn states the doctrine as unquestionably true,
that the Divine light is universal and sufficient to lead to salvation,
and that every man ought to follow its teachings in matters of faith and worship.
The dispute between them was not in regard to the principle, but its application.
The following questions are laid down as including the matter at issue:

[.numbered]
1+++.+++ Whether Christ has or has not given to his church,
consisting of faithful believers and obedient walkers
by the light or spirit of God within,
a just sense, relish and savour of those spirits which the great enemy of man may assume,
under plausible appearances, to condemn what the church has practiced,
or to introduce what the church has condemned?

[.numbered]
2+++.+++ Whether such a society, body or church, may not,
after due admonition given to such dissenting or innovating person,
lawfully and without deviation from Christian principles,
deny their communion to such person or persons,
as a testimony against the spirit by which they are actuated?

[.numbered]
3+++.+++ Whether such person or persons may acknowledge the truth of
this fundamental doctrine of the Divine light as a leader and guide,
and yet be actuated by a wrong spirit to the production of rents and divisions,
and then oppose the church under pretence of being guided by this inward light;
and consequently whether such persons ought to be judged by any for acting in this manner,
seeing it is the duty of all to act according to the dictates of the light of Christ?

[.numbered]
4+++.+++ Whether the body of those called Quakers, or their opposers were that church?

In answer to the first,
it is shown that such a power of discernment does belong to the true church,
from various passages in Scripture, and particularly from the words of our Saviour;
"`My sheep hear my voice, and a stranger will they not follow.`"
This stranger may be a false spirit, as well as false doctrine,
which the voice of the true Shepherd, the spirit of Christ, detects.
Though the stranger may come in the name of Christ, pretending authority from him,
and speaking words that are true in themselves,
yet his false covering is detected by those who are really
the children of the light and of the true Gospel day.
For this end the disciples were admonished to have salt in themselves,
the divine anointing and spirit,
by which they should discern the spirit of truth and the spirit of error.

The second is also answered affirmatively, both from the testimony of Scripture,
and the reasonableness of the case.
Alexander the coppersmith is noted, as one who was denied and rejected,
notwithstanding his profession of Christianity.
From the injunction of our Saviour in relation to those, who,
in case of private offences, refuse to hear the church, it is inferred,
that such as reject the counsel of the church in matters relating to faith and worship,
are to be regarded as heathens and publicans.

In regard to the third question, it is stated,
that men may acknowledge and believe the doctrine of the inward light of Christ,
and yet mistake the suggestions of their own dark
imaginations for the leadings of this divine light;
and yet neither the profession nor the belief of being guided by it,
can exempt those who are not really led by it, from the just judgment of those who are.
If the mere profession of being led by the spirit of Truth,
could exonerate those who are strangers to it,
from the judgment and censure of such as actually walk in the Spirit,
a door would be opened to all kinds of libertinism.
Though it is the duty of all to walk in the light, and to wait for it,
that by it they may be instructed in the way of life and salvation,
yet it is they only who are actually led by it,
that can rightly discern between the false spirits and the true.

This work of William Penn`'s was one of the first, if not the very first,
in which the authority of the Society,
to testify against those of their members who dissented
from them in matters of faith and worship,
was publicly proclaimed.
And we may perceive that the ground assumed by the author,
was the same as that taken by Robert Barclay, in his treatise on church government,
published in the following year.

The fourth question was one upon which the application of the principles
laid down in the answers to the former three essentially depended.
Whether the body of those who were called Quakers,
or the few who were joined with John Perot, were the true church,
acting under the influence of the divine light?
Though the number of those who adhered to John Perot,
appears to have borne a very small proportion to
the number of those who discarded his notions,
yet our author does not build any part of his argument on this basis.
He raises it on a much more solid foundation.

According to the concessions of John Perot, the Society at one time was a true church,
with a living and powerful ministry; among whom the everlasting Gospel was preached,
and by which the church was greatly increased.
Now, as the dissatisfaction of John Perot and his party,
did not arise from any change in the principles or practice of the Society,
but grew out of their own innovations; the Society was the same church still,
but they were not the same members.
The change was in them, and not in the Society.
An adherence to the order and practice which prevailed,
when John Perot and his followers united with the Society,
could not be denounced as an imposition,
or admitted as an evidence of a change of character.
Harmony prevailed, and religious refreshment was experienced among them,
till the innovation of keeping on the hat in the time of public prayer, was attempted.
The change of character, must therefore,
be attributed to those who had adopted this innovation, and not to those who refused it.

In these controversies,
it is remarkable that various denominations who were very much opposed to each other,
united in their opposition to Friends.
This was what William Penn intimated by the title of the last mentioned pamphlet.
As a postscript to this work, he enumerated the various points of doctrine,
in which their opponents were divided against each other.
Showing that there was very little agreement among them,
except in their opposition to the Society, of which he was a member.
Thus Judas united with the Scribes and Pharisees in betraying Christ,
and the Jews combined with the heathens in the persecutions of the early Christians.

Besides the works already mentioned, he wrote, in the course of this year,
several letters of a religious character, which are still extant.

One to Justice Fleming, deputy lieutenant of Westmoreland, who it appears,
had used considerable severity towards Friends in that county.
In this letter he first expressed his obligation on account of
some kindness shown several years before to Gulielma Maria Springett,
afterwards Penn;
observing that however he might differ from some
others in his opinions respecting the life to come,
he knew of no religion that destroyed courtesy, civility, and kindness in this.
He then in plain but respectful terms, pointed out the folly as well as injustice,
of attempting to change the opinions of men by the application of force,
and expressed his conviction, that truth would not suffer by examination,
and finally requested that the Justice would accept
and peruse some tracts which he then sent him,
in explanation of the principles and doctrines of Friends.

He also wrote to Mary Pennyman, who had taken part in the recent opposition to Friends.
In this, he remonstrated with her in great freedom,
against the spirit by which she was actuated,
and solemnly admonished her to repent of the evil she had done,
and the reproach she had brought upon the way and professors of Truth.

One to all the suffering Friends in Holland and Germany,
admonishing them to faithfulness, and a full reliance upon the unfailing Shepherd,
without whose providence a sparrow falls not to the ground;
to dwell in the faith which works by love, and casts out fear;
and to remember that the way of Truth would be judged
of by many according to their conduct.
That by walking in the light of Christ, the just man`'s path, they might glorify God,
and obtain for themselves eternal salvation.

He also wrote one to Friends in the United Provinces.
This begins with a very pathetic declaration of his love toward them,
and his desire that they might be abundantly replenished with the light and love of God,
the everlasting Fountain.
They are then admonished not to be turned out of the way by the reproaches of the profane,
the cruelty of persecutors, or the treachery of apostates;
but as pilgrims seeking a durable inheritance, eternal in the heavens,
to pass the time of their sojourning here, in fear and in a godly conversation,
that the life and power of godliness might shine through all these dark clouds,
with which the envy of their opposers was seeking to eclipse their religious profession,
and God be glorified through them.
Those who had been recently visited with the evidence of heavenly love,
were particularly exhorted to leave the dead to bury the dead,
to make no bargains for ease to flesh and blood,
which can never enter the kingdom of God; and by consulting with which,
they would be in danger of landing in eternal perdition.

One to Friends in Maryland,
who were subjected to some difficulties with the proprietor of the province,
lord Baltimore, on account of their testimony against oaths.
In that letter he furnished them with some arguments
and authorities against the use of oaths.

Lastly, a letter to John Collenges, a doctor of divinity,
who had charged Friends with denying the Divinity of Jesus Christ,
and cited William Penn`'s _Sandy Foundation Shaken,_ in proof of the charge.
Extracts from this letter have already been given,
showing that what he denied in that work, was not the Divinity of Christ,
but the unscriptural dogma of the popish school personality.

He there declares that his arguments in _The Sandy Foundation
Shaken,_ were directed against the doctrines of his opponents,
and not against those of the Holy Scriptures;
and that the objections to the doctrines of Friends, which were generally advanced,
arose from their opponents attaching their own consequences to what Friends declared,
and then charging those consequences as their principles,
when there was in reality no necessary connection between them.
