== Chapter VII.

1674+++.+++ The declaration of indulgence to those who dissented from the established church,
which was issued by the king, in 1671, was not long permitted to pass unopposed.
From the character of the reigning monarch, and the measures of the court,
it was inferred that this act of indulgence was not
designed for the relief of Protestant dissenters,
so much as the protection of Roman Catholics; and at all events,
it was obviously an assumption of power under the character of the royal prerogative,
which excited the jealousy even of those who would have gladly
obtained the same indulgence in a constitutional way.
The parliament which met in 1673, complained of this suspension of the penal laws,
by the dispensing power of the crown, as one of the grievances to be redressed;
and having the power of granting or withholding supplies, they used it in this case,
so that their prodigal and needy monarch revoked his proclamation
and broke the seals with his own hands.

Though the parliament was then composed of men rather more favourable
to toleration than in the early part of Charles II`'s reign,
yet when the declaration of indulgence was revoked,
no effectual measures were adopted to secure a legal toleration; and therefore,
the persecuting bigots of the day availed themselves
of that revocation to revive the Conventicle act,
and to renew the oppression of conscientious dissenters.
These unrighteous proceedings soon attracted the attention of our author,
and furnished employment for his pen, through a considerable part of the year 1674.

Justice Bowles of Wiltshire,
having brought one of his fellow-professors under these persecuting laws,
William Penn addressed a letter to him, remonstrating against his conduct,
and giving him to understand,
that the revocation of the king`'s declaration was
not owing to a desire either in the king or parliament,
to restrain the exercise of religious liberty.
He therefore requested that he would order the restoration
of the goods which had been unjustly seized by his authority,
and not so far degrade himself below the character of a Christian or gentleman,
as to be the tool of a crew of ungodly and lawless informers.

In the same year he wrote an Address to king Charles,
informing him of the cruel execution of those persecuting laws,
which his declaration was designed to suspend, and of sundry extra-judicial proceedings,
sustained by perjury, to the great injury of a number of innocent people;
by which oppressive measures,
several families were nearly ruined and their just creditors deprived of their dues.
The object of this address,
was to procure some public declaration of the king`'s
disapprobation of these violent measures;
but Charles had other concerns to manage, in which he felt more interested,
than in the sufferings of an inoffensive and unresisting people.

Some justices of the peace in Middlesex,
having used an unexpected degree of harshness towards Friends,
who had assembled at a meeting in their neighbourhood, at which, it appears,
he was present; he addressed a respectful letter to them,
forcibly appealing to their own understandings against the persecuting measures,
to which they had given too much countenance.

In that letter he assumed the ground that the king`'s
declaration of indulgence was revoked,
not because there was any objection to its principles,
but on account of the manner of the grant.
He further urged, that the kingdom was then undisturbed,
that there was consequently no just cause for the execution of such laws,
and that when the reason of a law had ceased, the law itself became obsolete,
without a formal repeal; and that it was very questionable,
whether the law by which Protestants were burnt for
their opposition to the church of Rome,
had ever been repealed.
Laws, he observed, were either fundamental, and therefore permanent;
or enacted upon particular emergencies, and to expire of themselves,
when the cause of their enactment had passed away:
that their liberty and property were not derived from the Protestant religion,
but were of an older date; and that a nonconformity to it, purely conscientious,
ought not to deprive them of either.
"`Be pleased,`" says he, "`to remember, that faith is the gift of God,
and that what is not of faith, is sin.
Either give us better faith, or leave us with such as we have.
For it seems unreasonable in you, to disturb us for this that we have,
and yet be unable to give us any other.`"
Again, "`I am well assured, it shall less repent you upon your dying bed,
to have acted moderately than severely.
You cannot but know how fallible Protestants acknowledge
themselves to be in matters of religion,
and consequently, with what caution they should proceed against any about religion.`"
Subsequently, "`Think not that mere persuasion condemns us, it is sin,
whose wages is death.
I love and honour all virtuous persons that differ from me,
and hope God will have regard to every such one, according to his sincerity.
And however it shall please you to deal with us, at this or any other time,
I pray God to forgive you, open your eyes, tender your hearts,
and make you sensible how much more moderation and virtue are worth your study and pursuit,
than the disturbance of religious dissenting assemblies, that so far as I know of them,
desire to honour the king, love their neighbours as themselves,
and do unto all men as they would have all men do unto them.`"

Accounts being received that Friends in the city of Embden had suffered great persecutions,
by banishment, fines and imprisonment, by order of the authorities there, William Penn,
near the end of this year, addressed a letter to the senate and council of that city,
labouring both by argument and entreaty to incline them to greater lenity.

In this letter he pointed out the inconsistency of these persecuting measures,
with the declared principles of their Protestant ancestors,
who strenuously opposed and protested against the popish impositions of their time;
and showed, that the senate and council,
by persecuting those who conscientiously dissented from them,
gave encouragement to the neighbouring Roman Catholic powers,
to persecute their Protestant brethren.
The letter contains a number of noble sentiments.
"`Have the senate and council of Embden more Christian
authority than the chosen witnesses of our Saviour?
If calling fire from heaven, was judged by Him who was wiser than Solomon,
to be an improper means of converting opposers formerly,
it shows little modesty in the authorities of this day,
to kindle a fire on earth to destroy them now.
Conscience is God`'s throne in man, and the power of it his prerogative.
To restrain it by violence, is to usurp his authority.
The Protestants deny the Roman Catholic assumption of infallibility,
and yet by persecuting others for their religion,
are guilty of an equal or greater presumption;
for they either assume an infallibility themselves,
or endeavour to compel others to embrace an uncertain belief.
The day will come, when one act of tenderness in matters of conscience,
shall find a better reward than all the severity by which
men attempt to propagate their persuasions in the world;
for one flows from the Saviour, the other from the destroyer of men.
Imitate the God of nature and grace, whose sun shines upon all, whose rain falls on all,
and whose grace visits all.
Let his goodness to you, prevail with you to show clemency to others,
that so the great God of the spirits of all flesh,
who respects not the persons of the rich, poor, or powerful, in judgment,
may show you mercy in the day of his righteous judgments.`"

Persecution now raging with nearly as much violence as ever,
the envious magistrates frequently resorted to their old expedient.
When Friends were brought before them, and could not be convicted of any offence,
they tendered the oath of allegiance to them; and upon their refusing to swear,
they were subjected to the penalties designed for a very different class of people.

To evince to the world that they had substantial reasons for refusing to swear,
William Penn, in 1675, published a treatise on oaths;
which was addressed to the king and parliament; with a brief introduction,
expressing a hope,
that inasmuch as it was understood they were going
to employ that session in the redress of grievances,
the parliament would consider the great injustice Friends were suffering,
on account of their conscientious refusal to swear,
and apply to those grievances an effectual redress.
This introduction was signed by thirteen Friends.

This is a very valuable treatise.
The author first shows the reason of oaths to be
the degeneracy of man from primitive integrity;
and fortifies his opinion by the testimony of a number of ancient writers.

He then assigns various reasons why a Christian ought not to swear.

1st, As oaths originate in perfidy,
they ought to be excluded by a religion that establishes integrity,
and therefore takes away the reason of them.

2nd,
They abolish the distinction between men of veracity
and those of loose and perfidious characters.

3rd,
A fear of rebellion against the discoveries which
God has afforded of his ancient way of truth.

4th, Oaths, by their frequent and familiar use,
have lost the awful influence which is the alleged reason for their continuance.

5th, Those who entertain a just sense of the omnipresence of God,
have no need of an oath to confine them to the truth.

6th,
They do not convince the hearers of the truth of any declaration to which they are affixed;
for there is no evidence of Divine displeasure usually attendant upon false swearing,
as there was in the ancient law of jealousy.

7th, It is irreverent to appeal to God as a witness on trivial occasions.

8th, The form of the modern oaths is highly exceptionable,
being made up of superstition and ceremony.

9th, The example and precepts of our Saviour are directly opposed to all oaths.
This is shown by our author at considerable length.

10th, Swearing is contrary to the nature and general character of Christianity.`"

He then cites the testimonies of a great number of the ancient Gentiles,
in disapprobation of swearing,
followed by the opinions of several Jewish writers of similar import.

He next produces the declarations of a great number of Christian fathers, doctors,
martyrs, and early reformers, from Polycarp to Erasmus,
against the lawfulness of swearing under the Gospel dispensation.
This is followed by the opinions of several of the school men and others,
as Thomas Aquinas, Cajetan, etc, against the use of oaths.
These authorities, extracted from a number of writers, ancient and modern,
are no questionable evidence of the industry and reading of William Penn.
The treatise, though printed among the works of our author,
and in all probability produced chiefly by his pen,
is signed by him and Richard Richardson,
from which it appears that the latter had some part in the authorship.

At the end of this treatise,
two letters are inserted from the prince of Orange to the magistrates of Middleburg,
dated in 1577, requiring them to accept the yea and nay of the Menonists,
in their commercial and civil transactions, instead of an oath;
and in case they should violate such declaration, to punish them as perjurers.
It is also stated,
that in the treaty of peace between the United Provinces and the neighbouring powers,
then recently made, there was a special provision,
that their ships should be furnished with briefs,
granted upon the oaths of their commanders,
yet the magistrates in Holland were accustomed to accept the solemn
affirmation of such as could not conscientiously swear.
The assertion is advanced,
that the prosperity of the United Provinces is more
promoted by the industry of these indulged dissenters,
than by the members of the established religion.
Hence, a powerful argument is drawn, in favour of a similar indulgence in other countries.

In the same year, 1675, William Penn produced a work,
addressed to the consideration of those in power; in which,
after briefly enumerating the acts of oppression,
which were then frequently visited upon Friends, he proceeded to argue the question,
of the rights of conscience on legal and political grounds.
The tract clearly proves the ability of the author,
as a political defender of those rights,
and shows that the true interests of the government
would not have been endangered by a complete toleration.

The efforts hitherto made to check the torrent of persecution,
not effecting their design, our indefatigable author produced in the same year,
"`The continued cry of the oppressed for justice,`"
addressed to the king and both houses of parliament.

In the introduction,
he showed that the constitution of Great Britain was particularly
careful of the liberty and property of its freeborn^
footnote:[The ancient laws of Great Britain being formed during the existence of villeinage,
were designed rather for the protection of the free, than of the servile class.
But that system having become extinct before this tract was written,
William Penn could very consistently urge the privileges of the freeborn,
without giving any countenance to the invidious distinction
between the servile and the free.]
inhabitants;
and that the laws which had been enacted to enforce
uniformity in religious doctrine and practice,
had greatly interfered with the ancient and fundamental laws of the kingdom.
These laws had changed the character of the government,
and were injurious to the commerce of the country.
He therefore requested a perusal of the statements which were offered,
and a redress of the numerous and important grievances,
of which he and his friends so justly complained.

This was followed by a circumstantial account of the oppressions which Friends,
in various parts of the kingdom,
had endured on account of their peaceable meetings for the worship of God.
These details consist of numerous exactions of heavy and ruinous fines;
in some instances not sparing the beds,
wearing apparel or working tools of the sufferers:
and of instances of great personal abuse, with little regard to age, sex or condition.

The labours of William Penn in the ministry of the Gospel,
appear to have increased the number of Friends in the neighbourhood where he lived.
The celebrated Richard Baxter, who was unquestionably a zealous and pious man in his way,
passing through that part of the country, and finding so many of that Society,
became alarmed for their situation.
Entertaining the opinions, which were common in that day,
of the dangerous character of the doctrines held by the Society,
he became desirous of preaching to them,
in order that they might "`hear what could be said for their recovery.`"
Whether any opportunity of the kind was obtained, does not appear;
but the circumstance led to a correspondence with William Penn,
and eventually to a public dispute.
The parties met at Rickmansworth,
where the disputants alternately addressed the audience on the subject of controversy.
The discussion was continued from ten in the morning till five o`'clock in the afternoon.
Among the auditors were one lord, two knights,
and four clergymen of the established church.

The particular points in controversy are now unknown;
and we have no minute account of the manner in which it was conducted.
The disputants appear to have parted with their former opinions unchanged.
William Penn, in a letter written soon afterwards to Richard Baxter,
intimates that the discussion was not so methodical as he could have desired.
Several letters were subsequently exchanged between the parties.
Of those written by Richard Baxter we know nothing,
except what may be gleaned from the replies of William Penn.
But from these it may be fairly inferred,
that Richard Baxter`'s zeal for his own persuasion,
betrayed him into no inconsiderable severity towards William Penn,
as well as his doctrines.
The last letter of our author, after animadverting with sufficient freedom,
on the communications of his opponent, closes in the following manner:--

"`Do not so harshly represent, nor cruelly characterize a poor people,
that are given up to follow the leadings of that Jesus,
abundance of you have long told us, has stood even all night at the door of our hearts,
knocking that he might come in; whose pure spirit and fear, we desire to be subject to,
and wait upon God when together, in true silence from all fleshly thoughts,
that we may feel our hearts replenished with his Divine love and life,
in which to forgive our opposers, and those that spitefully use us.
In which dear love of God, Richard Baxter, I do forgive thee,
and desire thy good and felicity.
And when I read thy letter, the many severities therein could not divert me from saying,
that I could freely give thee an apartment in my house,
and thy liberty therein--that I could visit and yet discourse thee in much tender love,
notwithstanding this hard entertainment from thee.`"

Near the end of the year 1675,
a man who had been a conspicuous opposer of Friends and their doctrines, was brought,
on his death bed, into great trouble of mind on that account.
His name was Matthew Hyde, a man of reputable morals, and sober demeanour.
His opposition was principally directed against the
doctrine which Friends have always maintained,
that Christ, the true light, has enlightened every man that comes into the world.
The universality and sufficiency of this light to lead to salvation, he resolutely denied.
Yet his denial was not made in a furious or frothy manner, but with apparent sobriety;
and by argument, rather than declamation.
When near his end, he expressed a desire to see some of the people called Quakers,
upon which George Whitehead, in company with one or two other Friends, paid him a visit.

In their presence he expressed his sorrow for his opposition to Friends,
his desire of forgiveness from God, and his wish that their number might be increased.
He said, that if the Lord should lengthen his life,
he should willingly bear a testimony in their favour
as publicly as he had formerly opposed them.

This circumstance gave occasion to William Penn to publish a small tract,
entitled "`Saul smitten to the ground,`" containing a brief
narrative of the death and dying declarations of this man,
attested by his wife and another female attendant,
followed by an address to all atheistical, persecuting,
and contentious opposers of the Divine light, to take warning from this example,
and repent before the things which belonged to their peace were hid from their eyes.
An admonition was also addressed to his brethren in religious profession,
to maintain their faith without wavering,
and to trust that the same Divine power which had
wrought conviction in the mind of this opposer,
would at length vindicate their cause in the eyes of their more furious persecutors.
