== Chapter VIII.

It has been mentioned in a preceding chapter, that William Penn, about the year 1671,
travelled in the work of the ministry through some parts of the continent;
but of that journey I can find no particular account.
Some traces appear in some of his letters of the
acquaintances he had formed there at that time.
Whether the princess Elizabeth was one of them, does not appear; it is certain, however,
that letters occasionally passed between her and Friends in England.
William Penn, it appears, wrote one to her besides that mentioned in the last chapter.
By the labours of Friends, particularly William Penn and William Caton,
a knowledge of the doctrines of the Society was spread on the continent;
and a number had been convinced and joined in fellowship with them,
among whom were the parents of William Sewel the historian.

In the fourth month of this year,
we find William Penn leaving his family at Worminghurst, in Essex, where he then lived,
and attending the Yearly Meeting at London,
where he met George Fox and a number of other Friends, from various parts of the nation.
When the meeting was over,
George Fox and John Burnyeate returned with William Penn to his house,
where they wrote a work called "`The New England fire-brand
quenched,`" in reply to a publication by Roger Williams,
an inhabitant of New England.
This reply being prepared at the house of William Penn,
it is not improbable that he may have given some assistance in the composition.

Soon after the close of the Yearly Meeting, he parted with his wife and family,
in order to make a second visit, in the love of the Gospel,
to Friends and others in Holland and Germany.
Of this journey he has preserved an account,
which is so full of lively interest and instruction,
that the narrative cannot be better conveyed than in his own language.
It was first published in the year 1694, as follows.

[.asterism]
'''

=== Preface.

This ensuing journal of my travels in Holland and Germany,
in the service of the Gospel of my Lord and Saviour Jesus Christ,
was written for my own satisfaction, and that of some relations and particular friends,
as the long time it has lain silent shows.
But a copy that was found amongst the late countess of Conway`'s papers,
falling into the hands of a person who much frequented that family,
he was earnest with me, both by himself and others,
to have leave to publish it for a common good.
Upon perusal, I have found a willingness to comply with +++[+++this request;]
hoping that the Lord will make the reading of it effectual to some into whose hands
it may fall;--as well those who have received a dispensation of the same ministry,
for their encouragement in their public service for God,
as those who are under the same ministry, unto zeal and faithfulness.

For it is the glorious Gospel-day, in which God is exalting his dear Son, as Prophet,
Priest, and King, in the hearts of his people.
O that the nations would hear him, their only saving health,
and Israel`'s great Shepherd! who takes care of his sheep, that hear his voice,
and gives unto them that follow him in the daily cross unto regeneration, eternal life.
He hath sent, and is sending, forth his servants,
to gather home the sheep that are gone astray in all nations,
that so there may be but one Shepherd and one sheep-fold;
according to the glorious promise made to these latter times, in which he said,
he would be the teacher of his people himself.
For he is teaching thousands, by the Light, Spirit, and Grace of his Son Christ,
in whom he is well pleased.
To this, God hath sent forth his servants in this day, to turn all people,
as God`'s call and visitation to the nations:
and blessed are all those who hearken to this testimony, both mediately and immediately.

God is awakening men to the knowledge of his glory in the face or appearance of Christ,
by his Spirit in their hearts and consciences, which reveals to men the Father, yea,
the deep things of God.
O that they would hear and fear, and learn the things that make for their eternal peace!
For if the righteous scarcely are saved, where, O where,
shall they appear that neglect so great salvation!--a salvation that comes so near them,
as to knock at the door of their hearts; that searches them and tries their reins,
and tells unto them their most inward thoughts;
and brings a line of judgment over all their words and works.
This is Christ Jesus, the Light of the world,
who was given of God for salvation to the ends of the earth.
He has enlightened all, and shines to all, and calls all,
that they should see their sins and be sorry for them, and forsake them,
and take up his daily cross and follow him,
whom God hath given for an example as well as a propitiation for our sins.
And none can know him to be their propitiation,
who reject him as their example and leader in their lives and conversations.

Wherefore, reader, be serious, inward, and inquisitive for thy soul`'s sake.
What faith hast thou?
Is it one that overcomes the world,
or one that the spirit of the world overcomes`'? This is not the faith of God`'s elect,
without which we cannot please God.
For that faith works by love.
Is it such a love to God as will not offend him,
but seeks his glory through a most willing obedience to his holy will?
Blessed are the souls in whom this love dwells!
For such have none in heaven but God, nor in the earth in comparison of him.
As they receive all good from him, so they resign all up to him;
and though it be through many tribulations that they must attain the rest of God;
yet as nothing can separate them from his love,
so neither can any thing deprive them of their reward in the end.

Wherefore, reader, be thou persuaded to take thy lot among that blessed number,
if thou art not yet one of them.
Thou seest the way to that Divine privilege; walk in it; for the end crowns all.
And if thou art one of that number, who have chosen God for their portion, be diligent,
zealous and fervent in the work and service of God.
Redeem thy time, and run thy race with care and constancy; looking unto Jesus,
the author, that he may be the finisher of thy faith.
Remember who said, there are many mansions prepared for the faithful.
Do we believe and look for another world?
Let us not then live in this, as if there were no other.
Let our eyes be upon our better world,
and live here as strangers who are but on our way to our eternal home;
that so we may answer the end of God`'s love,
by working out the salvation of our own souls by his power with fear and trembling;
knowing that God will judge all, by Christ Jesus,
according to the deeds done in the body.

Reader, this journal is of a religious voyage,
and has some passages in it that may engage thy soul to seriousness,
and let thee see how good God is to those that go of his holy errands.
Mayst thou be heartily affected with this testimony
of his love and presence with his people;
and feel good desires raised in thee to serve the Lord also,
according to his blessed will, in thy day; that thou mayst know peace to thy soul,
when time here shall be no more.

[.signed-section-closing]
I am thy assured friend in the best things,

[.signed-section-signature]
William Penn.
