== Chapter IX.

On the 22nd of the fifth month, 1677, being the first-day of the week,
I left my dear wife and family at Worminghurst, in Sussex, in the fear and love of God,
and came well to London that night.
The next day I employed myself on Friends`' behalf, who were in sufferings,
until the evening; and then went to my own mother`'s in Essex.

On the 24th I took my journey to Colchester, and met George Watts of London upon the way;
who returned with me, and came well to that town the same evening.
We lodged at John Furly`'s the elder,
and had a blessed meeting at Jonathan Furly`'s house that night.

The next morning early I left Colchester, and came to Harwich about noon,
accompanied by George Watts and John Furly the elder, William Tailcoat,
and J. Whiterly of Colchester; where we found dear George Fox at J. Vanderwall`'s house,
with many more Friends.
After dinner we all went to the meeting,
where the Lord gave us a blessed earnest of his love and presence,
that should be with us in this voyage.
For his holy, overcoming, refreshing power did open all our hearts,
and many of our mouths in ministry, prayer and praises,
to the magnifying of his own name and Truth in that place.

The meeting done, we returned to John Vanderwall`'s house,
where we took our leave of Friends; that is to say, of the Friends of that place,
with others that came with us, or met us there.
And so we went on board the packet-boat: where,
by the special favour of the master of the packets to me,
(he having formerly served under my father,) we had the best accommodation given to us.
Many of the Friends accompanied us to the ship, not leaving us until all was fixed;
and then we parted in the fellowship of Jesus.

Those that came over, were George Fox, Robert Barclay, G. Keith, G. Watts, John Furly,
William Tailcoat, Isabel Yeomans, Elizabeth Keitb, and myself, with two of our servants.
We set sail about three o`'clock in the morning of the 26th,
being the fifth-day of the week;
and got the sixth-day at night within half a league of the Briel.
We had good service those two days in the ship with several passengers, French and Dutch:
and though they seemed at first to be shy of us, and to slight us,
yet at last their hearts were much opened in kindness towards us,
and the universal principle had place.

The next morning Friends were fetched on shore by a boat of Rotterdam,
with some Friends of that city who came to the Briel to meet us.
The Friends that came were Aaron Sonnemans, Benjamin Furly, and S. Johnson, Vettekeuken,
with three young men that live at B. Furly`'s house.
After we had eaten, we took boat immediately for Rotterdam; where we arrived about noon,
and where many Friends came to see us, among whom we were comforted.

On the 29th, being the first-day of the week, we had two meetings at B. Furly`'s house;
whither resorted a great company of people,
some of them being of the most considerable note in that city;
and blessed be the true Word of life,
that never failed them that rest upon it and abide in it! the Gospel was preached,
the dead were raised, and the living comforted; God, even our God,
bore heavenly record to his only begotten Son;
and truth is honourable in the eyes of several of that place.

The next day we spent in visiting Friends from house to house, not in one company,
being lodged in several quarters of the city.
All our visits were precious meetings; for, indeed,
for that end God brought us into this land.
Several of us dined and supped that day at two great men`'s houses,
where we had blessed opportunities to make known
unto them what was the hope of our glory;
that mystery, which to the Gentiles is now revealing, even Christ Jesus,
the light and life of the world manifested in us.

On the 31st G. F., J. F., W. T., and myself,
after having broken our fast at A. Sonnemans`', took boat for Leyden,
where we came that night,
in order to be at Harlem next day at a meeting appointed by G. F. and myself from Rotterdam:
being accompanied by J. Bocliffs, J. Arents, and J. Claus,
who came from Amsterdam on purpose to conduct us thither.

At Harlem we arrived about the eleventh hour, and went to the house of a good old man,
who had long waited for,
and is now come to behold the consolation and salvation of Israel.
After we had a little refreshed ourselves, we went to the meeting;
where the Lord gave us a blessed opportunity, not only with respect to Friends,
but many sober Baptists and professors who came in and stayed the meeting to the end:
blessed be the name of the Lord.

The meeting done, we went to Amsterdam, in company with several Friends of that city,
and of Alkmaer and Embden, who met us at the meeting at Harlem.
We were lodged at Gertrude Dirick`'s house.
G+++.+++ K. and his wife, and R. B. stayed over the fourth-day`'s meeting at Rotterdam,
and so came not till the next day;
which was the day of the general meeting of Friends in this country.

On the 2nd of the sixth month, at G. D.`'s house, the general meeting was held,
both of men and women: and the Lord, who is setting up his own kingdom by his own power,
owned us with his blessed presence, and opened us in that wisdom and love,
that all things ended with peace, great concord, and comfort: many things being spoken,
especially by our dear friend G. F., that were of good service;
and I hope will dwell with them forever.

These several things agreed upon, being of good savour and report,
I think fit here to insert.

[.embedded-content-document]
--

[.blurb]
=== At the General Meeting of Friends at Amsterdam, the 2nd of the sixth month, 1677.

[.numbered-group]
====

[.numbered]
1+++.+++ Be it known to all men, that the power of God, the Gospel,
is the authority of all our men`'s and women`'s meetings;
and every heir of that power is an heir of that authority,
and so becometh a living member of right of either of those meetings,
and of the heavenly fellowship and order in which they stand: which is not of man,
nor by man.

[.numbered]
2+++.+++ That each Monthly Meeting have a collection apart;
and also that there be another collection quarterly at Amsterdam from each meeting,
for general services; and that it be not disposed of,
but by the consent of the said Quarterly Meeting.

[.numbered]
3+++.+++ It is agreed upon, that henceforth a Yearly Meeting be held here at Amsterdam;
unto which Friends in the Palatinate, Hamburgh, Lubeck, and Fredericstadt, etc.,
be invited;
of which meeting there shall be given notice to the
Friends of the Yearly Meeting at London,
to be kept always on the fifth-day of that week,
which is fully the third week following after the Yearly Meeting at London.

[.numbered]
4+++.+++ It is also agreed upon,
that henceforth this General Meeting is to be changed into a Quarterly Meeting:
and that the first Quarterly Meeting hereafter shall be
on the second fifth-day of the ninth month following,
and so forth every quarter on the second fifth-day of the month.
This 2nd of the ninth month is to be this first Quarterly Meeting.

[.numbered]
5+++.+++ It is also agreed,
that henceforth a Monthly Meeting in Friesland should be established,
as also at Rotterdam; and that on the second second-day of each month:
and at Harlingen upon the third third-day of the month.

[.numbered]
6+++.+++ Further, that in the interim, the Friends of Alkmaer, and Harlem, and Waterland,
are to have their Monthly Meeting with Friends at Amsterdam:
and to begin the said meeting the 6th day of the seventh month, and so forth;
always upon the first second-day of the month at the eighth hour.

[.numbered]
7+++.+++ And further, concerning Gospel order:
though the doctrine of Christ Jesus requireth his
people to admonish a brother or sister twice,
before they tell the church; yet that limiteth none,
so as they shall use no longer forbearance, before they tell the church;
but that they shall not less than twice admonish their brother or sister,
before they tell the church.
And it is desired of all, that before they publicly complain,
they wait in the power of God to feel if there is
no more required of them to their brother or sister,
before they expose him or her to the church.
Let this be weightily considered.

[.numbered]
8+++.+++ And further, when the church is told,
and the party admonished by the church again and again,
and he or she remain still insensible and unreconciled;
let not final judgment go forth against him or her,
till every one of the meeting hath cleared his or her conscience:
that if any thing be upon any, further to visit such a transgressor,
they may clear themselves, if possibly the party may be reached and saved.
And after all are clear of the blood of such an one,
let the judgment of Friends in the power of God go forth against him or her,
as moved for the Lord`'s honour and glory sake;
that no reproach may come or rest upon God`'s holy name, truth and people.

[.numbered]
9+++.+++ As much as possibly can be, let all differences be ended by some honest Friends;
and trouble not the Monthly or Quarterly Meetings with them: and if that will not do,
proceed to your particular Monthly Meetings.
But if they be not there ended,
then take aside six honest Friends out of the Quarterly Meeting,
and let them hear and determine the matter.
And in case any person or persons be so obstinate,
as that they refuse the sense and love of Friends, and will not comply with them;
then proceed towards them according to the way of Truth in such cases.

[.numbered]
10+++.+++ That all such as behold their brother or sister in a transgression,
go not in a rough, light, or upbraiding spirit to reprove or admonish him or her,
but in the power of the Lord and spirit of the Lamb; in the wisdom and love of the Truth,
which suffereth thereby, to admonish such an offender.
So may the soul of such a brother or sister be seasonably
and effectually reached unto and overcome,
and have cause to bless the name of the Lord on their behalf:
and so a blessing may be rewarded into the bosom of the
faithful and tender brother or sister that so admonisheth.

[.numbered]
11+++.+++ And be it known unto all, we cast out none from among us:
for if they go from the light, and spirit, and power, in which our unity is,
they cast out themselves.
And it has been our way to admonish them,
that they may come to the spirit and light of God which they are gone from;
and so come into unity again: for our fellowship standeth in the light,
that the world hateth, and in the spirit, that the world grieveth, vexeth, and quencheth.
And if they will not hear our admonitions, the light condemneth them,
and then goeth our testimony out against them.

[.numbered]
12+++.+++ That no condemnation is to go further than the transgression is known.
And if he or she return, and give forth a condemnation against himself or herself,
which is more desirable than that we should do it,
this is a testimony of his or her repentance and restoration before God, his people,
and the whole world: as David, when Nathan came to admonish him.
Psal.
li.

[.numbered]
13+++.+++ That no testimony by way of condemnation be given forth against any man or woman,
whatever crime they commit, before admonition,
and till such time as they have Gospel order, according to Christ`'s doctrine.

[.numbered]
14+++.+++ And if any brother or sister hear any report of any brother or sister,
let him or her go to the party, and know the truth of the report; and if true,
let the thing be judged; if false, go then to the reporter, and let him or her be judged.
And if any should report it at a second or third hand,
without going to the party of whom the report goeth, let such be brought to judgment;
for thou shalt neither raise nor suffer a report to lie upon my people, saith the Lord:
for they are to be holy as he is holy; and just as he is just.

[.numbered]
15+++.+++ And if any controversy or weakness should appear in either men`'s or women`'s meetings,
let it not be told out of your meetings;
because such speeches tend to the defaming of such persons and meetings,
and to the hurt of the common unity, and breach of the heavenly society and privilege.

====

--

[.offset]
This is an account of what passed in this general meeting.

Next day, notice being already given, we had a large public meeting,
in which the sound of the everlasting Gospel, testament, and covenant went forth;
and the meeting ended with a sweet and weighty sense.
That evening we had a more select meeting of Friends than the day before,
in which the nature of marriage,
and the practice of Friends relating to it and other
things were very weightily and closely discoursed.
The resolutions were these following:

[.embedded-content-document]
--

[.numbered-group]
====

[.numbered]
1+++.+++ A scruple concerning the law of the magistrate about marriage,
being proposed and discoursed of in the fear of God among Friends in a select meeting;
it was the universal and unanimous sense of Friends,
that joining in marriage is the work of the Lord only, and not of priest or magistrate.
For it is God`'s ordinance and not man`'s,
and therefore Friends cannot consent that they should join them together.
For we marry none; it is the Lord`'s work, and we are but witnesses.

[.numbered]
2+++.+++ But yet, if a Friend, through tenderness,
have a desire that the magistrate should know it before the marriage be concluded;
they may publish the same, after the thing hath by Friends been found clear;
and after the marriage is performed in a public meeting of Friends and others,
according to the holy order and practice of Friends in Truth throughout the world,
and the manner of the holy men and women of old,
may go and carry a copy of the certificate to the magistrate;
they are left to their freedom herein, that if they please they may register it.
But for priests or magistrates to marry, or join any in that relation,
is not according to Scripture;
and our testimony and practice have been always against it.
It was God`'s work before the fall, and it is God`'s work alone in the restoration.

[.numbered]
3+++.+++ If any Friend have it upon him to reprint any book already
printed and approved either in England or here,
they may do it upon their own charges.

[.numbered]
4+++.+++ It is also agreed, that the care of reading and approving books,
be laid upon some of every meeting; to the end no book may be published but in the unity.
Yet any other faithful Friends not so nominated, are not thereby excluded.
Though in all these cases it is desired,
that all would avoid unnecessary disputes about words, which profit not,
but keep in the love that edifieth.

[.numbered]
5+++.+++ It is further concluded,
that the general stock of the Quarterly Meeting be not disposed of,
but by the consent of the Quarterly Meeting.
But if, betwixt times, there should be a pressing necessity concerning the public;
let that Monthly Meeting, where it shall fall out, lay down the money,
and give in an account at the next Quarterly Meeting in order to their relief,
if it appear that they are thereby overcharged.
And let all things be done without favour, affection, relation or any respect to persons,
even for the Lord`'s sake, and his blessed everlasting Truth;
that God may bless and prosper his people.

====

And let all things be written down,
both as to your Monthly and Quarterly Meeting collections; what you receive,
and what you disburse; that all may be fair and clear,
to the satisfaction of all that desire to see and examine the books.

--

And the Lord`'s fear, and life, and power was over all,
in which the Lord God preserve his forever.

The 4th of the sixth month, being the seventh-day of the week,
was employed in visiting Friends, and preparing ourselves for a further journey;
that is to say, George Keith, Robert Barclay, Benjamin Furly, and myself.

Finding letters here from the Friends of Dantzic,
complaining of the heavy sufferings they underwent;
informing us also that the king of Poland was there,
and asking advice about an address to him,
it fell upon me to write the following letter in the name of the Friends of Dantzic:

[.embedded-content-document.address]
--

[.letter-heading]
To the King of Poland.

[.salutation]
Great Prince!

Actions of justice, mercy, and Truth are worthy of all men;
but in a most excellent manner of the serious consideration of kings and princes.
We, certain inhabitants of the city of Dantzic, have been long great sufferers,
not for any wickedness committed against the royal law of God,
or any breach of those civil laws of this city,
that relate to the well government of it in all natural and civil things;
but purely and only for the cause of our tender consciences towards God.

This severity being by us represented to the magistrates of this city,
we could not as yet receive from them any relief; some expressing,
as if easing the burden of our oppressions should give thee, O King,
an occasion of dissatisfaction against them; who art our acknowledged protector.

Being thus necessitated, and in a manner driven to make this address unto thee;
take it not amiss, that we, with that humility and patience,
that becometh the servants and followers of Jesus,
and with all manner of Christian respect and sincerity of mind, briefly relate to thee,
the most fundamental principles most surely believed by us;
which we hope thou wilt believe, deserve not those punishments,
that are inflicted upon us as evil doers.

[.numbered-group]
====

[.numbered]
1+++.+++ We do reverently believe, that there is one God and Father, one Lord Jesus Christ,
and one Holy Spirit, and these three are one. Eph. 4:6.

[.numbered]
2+++.+++ We believe the Scriptures of the Old and New Testament
to have been given forth by Divine inspiration;
and that they are profitable for doctrine, for reproof, for correction,
for instruction in righteousness;
'`able to make the man of God wise unto salvation through faith,
which is in Christ Jesus.`' 2 Tim. 3:15-16.

[.numbered]
3+++.+++ That these Holy Scriptures are not to be understood, but by the discoveries,
teachings and operations of the eternal Spirit, from whence they came.

[.numbered]
4+++.+++ We believe that all mankind, through disobedience to the spirit of God,
are fallen short of the glory of God, and in that state are under condemnation;
but that God out of his infinite goodness and kindness,
hath sent his Son a light into the world,
that whosoever believeth and obeyeth this light, should not abide in darkness,
but have the light of eternal life.

[.numbered]
5+++.+++ We believe this gift of light and grace through Jesus Christ to be universal;
and that there is not a man or woman upon earth,
that hath not a sufficient measure of this light,
and to whom this grace hath not appeared to reprove their ungodly works of darkness,
and to lead them that obey it to eternal salvation.
And this is the great condemnation of the world at this day,
under all their great professions of God, Christ, Spirit and Scriptures:
that though Christ hath enlightened them,
yet they will not bring their deeds to the light, but hate the light,
and love their dark customs and practices rather than the light,
'`because their deeds are evil.`'

[.numbered]
6+++.+++ We do believe in the birth, life, doctrine, miracles, death, resurrection,
and ascension of Jesus Christ our Lord; and that he laid down his life for the ungodly,
not to continue so, but that they should deny their wickedness and ungodliness;
and live soberly, righteously, and godly in this present evil world;
as the saints of old did, who were redeemed from the earth, and sat in heavenly places.

[.numbered]
7+++.+++ We do believe,
that as the devil through man`'s disobedience brought sin into man`'s heart,
so Christ Jesus, through man`'s belief in, and obedience to his Holy Spirit,
light and grace, cleanseth the heart of sin; destroyed the works of the devil;
finisheth transgression, and bringeth in everlasting righteousness.
That as the devil hath had his kingdom of darkness in man,
so Christ may have his kingdom of light, life, righteousness,
peace and joy in the Holy Ghost in the heart of man;
and not that Christ Jesus saveth men from wrath and not from sin;
'`for the wages of sin is death`' in whose heart soever it liveth;
'`but the gift of God is eternal life,`' to all that believe and obey,
through Jesus Christ.

[.numbered]
8+++.+++ We do believe,
that all true ministry and worship stand only in the experimental sense,
operations and leadings of this holy light, spirit or grace,
that is shed abroad in the hearts of men and women,
to conduct them in the holy way of regeneration unto life eternal.
This was the ancient apostolical doctrine; they spoke what they had seen, tasted,
and handled of the Word of God.
And this is our faith, doctrine, and practice in this day.

====

And be not displeased with us, O King, we entreat thee,
if we give this for the reason of our absenting ourselves
from the public and common ministry or worship;
namely, that we have no taste or relish,
no sense or evidence that their ministry and worship are authorized
and performed by the apostolical power and spirit of Jesus;
but rather that they are the inventions, studies and powers of man`'s nature;
all which are but strange fire;
and therefore cannot kindle a true and acceptable sacrifice to God.

For it is not man`'s spirit and degenerate nature,
speaking and professing the words of God`'s Spirit, that giveth acceptance with the Lord,
or administereth heavenly edification to men.
Nor can we believe, that where pride, passion, wrath, malice, persecution, envy,
and strife, lusts, vanity, wantonness, and worldly-mindedness have such sway and power,
that the true Christian spirit, life, and doctrine,
can be heartily received and followed.

And as this is the reason in the sight and presence of that God,
that made heaven and earth, and will judge the quick and dead,
wherefore we cannot join in the common and public worship of these parts;
so doth the same light and Spirit of God lay an holy necessity upon us,
with a meek and quiet spirit,
to come together after the manner of the ancient Christians,
that were the true followers of Jesus;
and with godly fear and a retired mind to wait upon God,
and meditate in his holy law of life, that he hath written in our hearts,
according to his new covenant promise; that he may feed us, teach us, strengthen us,
and comfort us in our inward man.
And as by this Holy Spirit, according to the practice of the churches of old,
any are inclined or moved to reprove, exhort, admonish, praise, or pray,
we are found exercised in these holy practices.

Now, O Prince! give us poor Christians leave to expostulate with thee.
Did Christ Jesus or his holy followers endeavour by precept
or example to set up their religion with a carnal sword?
Called he any troops of men or angels to defend him?
Did he encourage Peter to dispute his escape with the sword?
But did he not say, put it up?
Or did he countenance his over-zealous disciples,
when they would have had fire from heaven, to destroy those that were not of their mind?
No; but did not Christ rebuke them, saying,
'`Ye know not what spirit ye are of?`' And if it was neither Christ`'s spirit,
nor their own spirit that would have fire from heaven, oh! what is that spirit,
that would kindle fire on earth,
to destroy such as peaceably dissent upon the account of conscience`'?
If we may not wish that God would smite men of other judgments,
because they differ from us,
(in which there is no use of carnal weapons,) can we so far deceive ourselves,
as to esteem ourselves Christians and followers of Christ,
whilst we encourage men with worldly weapons to persecute such as dissent from us?

O King! when did the true religion persecute?
When did the true church offer violence for religion?
Were not her weapons prayers, tears, and patience?
Did not Jesus conquer by those weapons, and vanquish cruelty by suffering?
Can clubs and staves, swords, and prisons, and banishments reach the soul,
convert the heart, or convince the understanding of man?
When did violence ever make a true convert, or bodily punishments a sincere Christian?
This maketh void the end of Christ`'s coming, which is to save men`'s lives,
and not to destroy them; to persuade them and not to force them; yea,
it robbeth God`'s Spirit of its office, which is to convince the world;
that is the sword by which the ancient Christians overcame.
It was the apostle`'s testimony, that their weapons were not carnal, but spiritual;
but the practice of their pretended successors proveth,
that their weapons are not spiritual, but carnal.

Suppose we are tares, as the true wheat hath always been called;
yet pluck us not up for Christ`'s sake, who saith,
'`Let the tares and the wheat grow together until the harvest,`' that is,
till the end of the world.
Let God have his due as well as Caesar; the judgment of conscience belongeth to him;
and mistakes about religion are best known to him.

And here give us leave to remind thee of a noble saying of one of thy ancestors, Stephen,
king of Poland; '`I am king of men, not of consciences; king of bodies,
not of souls.`' And there have been found, and still are among the emperors, kings,
princes, and states of the world,
some who have had that noble spirit of indulging their conscientious dissenting subjects;
and not only with Gamaliel and Gallio not to persecute,
but also eminently to protect and defend them from
the hatred and violence of their enemies.
Be not thou less noble than they;
consider how quietly and comfortably our Friends live under other governments.

And indeed, we conceive it to be the prudence of the kings and states of the world.
For, if the wise man say true,
'`The glory of a prince is in the multitude of his people;`' but this practice saith, No,
the glory of a prince is in the conformity of the people to the canons of the clergy;
which seemeth to strike at all civil society, which consisteth in men of virtue, parts,
arts, and industry.
But let men have ever such excellent abilities; be ever so honest, peaceable,
and industrious; all which render them good and profitable subjects to the prince;
yet they must not live within their native country,
unless they will sacrifice the peace of their consciences by an
hypocritical submission to the canons and fashions of the church.
Is not this, O Prince, to set the church above the state?
the bishop above the king?
to waste and give away the strength and glory of a kingdom?

O that thou mayst be wise even in thy generation!
and use the power that God hath given thee,
for God, and truth, and righteousness; that therein thou mayst be like unto God, who,
Peter telleth us, accepteth of all that fear him and work righteousness,
throughout the world: whose sun shineth upon all; whose rain cometh upon all.

And lest any should be so injurious to us,
as to render us enemies to civil government be it known unto thee, O King,
that we honour all men in the Lord, not with the vain invented honours of this world,
but with the true and solid honour that cometh from above; but much more kings,
and those whom God hath placed in authority over us.
For we believe magistracy to be both lawful and useful,
for the terrifying of all evil doers,
and the praise and encouragement of those that do well.

The premises duly considered, we entreat thee, O Prince,
to take our suffering case into thy serious regard;
and by that power and influence thou hast with the magistrates of this city,
to recommend our suffering condition to their serious consideration;
that we may no longer lie under these not only unchristian, but unnatural severities,
but receive that speedy and effectual relief,
which becometh Christian magistrates to give to their own sober and Christian people.^
footnote:[Our author had greeted these sufferers
with a consolatory letter as early as the year 1673,
after his first journey to the continent.
It appears by Besse`'s account of these Friends,
that they had no sooner joined the Society,
and began to distinguish themselves as belonging to it,
by publicly assembling after their usual manner for the purpose of divine worship,
than three of them were apprehended by the magistrates.
After being detained some time in prison,
they were actually banished beyond the seas by order of the senate.
The little company continuing to meet together,
came to be more and more molested both by magistrates and people; till, in one instance,
the rude mob, to the number of a hundred persons, thronged into their meeting room,
pillaging their property, and using almost all manner of shameful insolence; on which,
the town officers making their appearance,
carried off these unoffending sufferers into confinement.
Nor did such cogent appeals as that of William Penn prevail on their behalf.
For during the space of some years the storm of persecution continued,
insomuch that most of them by frequent imprisonment, oppression, and banishment,
were reduced to poverty,
and unable for a considerable time to support themselves and their families.
In 1684, two letters from them were read at the Yearly Meeting in London,
describing their strait bondage in the house of correction,
under extremely hard usage and cruelty, being chained together two and two by the hands,
fed only with bread and water, and forced to lie upon straw through the severe winter.]

--
