== Chapter X.

On the 5th of the sixth month, being the first-day of the week,
meeting began about the eleventh hour, and held till the fourth hour in the afternoon.
There was a mighty concourse of people from several places of this country,
and of several persuasions, Baptists, Presbyterians, Socinians, Seekers, etc,
and God was with his people, and his Word of life and power, of wisdom and strength,
covered them; yea, the hidden things both of Esau and Jacob,
the mystery both of iniquity and godliness were opened and declared
in the demonstration of the eternal Spirit that day.
And, blessed and magnified be the name of the Lord, who hath not left himself,
nor his servants without a witness!
Oh, he is worthy to be loved, and feared, and obeyed, and reverenced forever!

The next day George Keith, Robert Barclay, Benjamin Furly and myself,
having taken our leave of dear George Fox and Friends, took boat for Naerden;
arriving there about the second hour in the afternoon.
After having eaten, we took our leave of those Friends that had accompanied us thither,
and begun our journey in the common post-waggon to Osnaburg;
where we came on fourth-day the 8th, in the evening.

We passed through a very dark country to that place;
yet I felt not so great a weight and suffering in my spirit as six years ago,
when I went through the same places.

At Osnaburg we had a little time with the man of the inn, where we lay;
and left him several good books of Friends in the Low and
High Dutch tongues to read and to dispose of.

The next morning, being the 9th of the sixth month,
we set forward for Herwerden or Herford, and came thither at night.
This is the city where the princess Elizabeth Palatine of the Rhine hath her court; whom,
and the countess in company with her, it was especially upon us to visit; and that,
upon several accounts.
First, in that they are persons seeking after the best things.
Secondly,
in that they are actually lovers and favourers of those who separate
themselves from the world for righteousness`' sake.

The princess is not only a private supporter of such,
but gave protection to De Labadie himself, and his company; yea,
when they went under the reproachful name of Quakers about seven years since.
This man was a Frenchman,
who being dissatisfied with the looseness and deadness of the French Protestants,
even at Geneva itself, left them and came for Holland;
and so vehemently declaimed against the apostacy of the priests and people there,
that the clergy were enraged and stirred up the magistrates against him, and the rather,
because many followed him, and several women of great quality.
Upon this, the princess gave them an invitation, and they came and were protected by her.
But since, some miscarriages falling out in that place,
she thereupon in good measure withdrew her favour from them,
and they removed to another place.

I was moved to visit this man and his company six years ago;
and saw him and his two great disciples; but they would not suffer me to see the people,
which I laboured for.
In that day I saw the airiness and unstableness of the man`'s spirit,
and that a sect-master was his name.
And it was upon me, both by word of mouth and writing to let them know,
that the enemy would prevail against them to draw them into inconvenient things;
if they came not to be stayed in the light of Jesus Christ, and to know the holy silence;
and that at last they would come to fall out one with another, and moulder away;
which is in some measure come to pass as I feared.
For I clearly perceived, that though they had received some divine touches;
there was a danger, they would run out with them, and spend them like prodigals;
not knowing then where to stay their minds for daily bread.
Yea, though they were something angelical and like to the celestial bodies,
yet if they kept not their station, they would prove fallen stars.
They moved not in the motion of Him who had visited them,
but were filled with gross mixtures, and thereby brought forth mixed births,
that is to say, things not natural but monstrous.
In fine, they were shy of us, they knew us not;
yet I believed well of some of the people, for a good thing was stirring in them.

The Countess was commendable in this also, that she left all to join with a people,
who had a pretence at least to more spirituality and self-denial
than was found in the national religion she was bred up in;
for God had reached her, as she told me, about nine years ago,
and that by an extraordinary way.
It seemed to us a great pity, that persons of their quality in the world,
should so willingly expose themselves for the false Quaker, the reprobate silver,
the mixtures;
and that they should not be acquainted with the life and testimony of the true Quakers.

About a year since,
Robert Barclay and Benjamin Furly took that city in the way from Fredericstadt to Amsterdam,
and gave them a visit; in which they informed them somewhat of Friends`' principles,
and recommended the testimony of Truth to them;
as both a nearer and more certain thing than the utmost of De Labadie`'s doctrine.
They left them tender and loving.

Soon after this,
Gertrude Diricks and Elizabeth Hendricks from Amsterdam
visited them and obtained a meeting with them:
improving that little way, God by his providence had made,
more closely to press the testimony.

And though they, especially the Countess, made some objections,
in relation to the ordinances and certain practices of Friends,
yet she seemed at that time to receive satisfaction from them.

These visits occasioned a correspondence by way of letter betwixt them and several of us,
wherein the mystery of Truth hath been more clearly opened to their understandings;
and they have been brought nearer into a waiting frame,
by those heavenly directions they have frequently
received by way of epistles from several of us.

In answer to two of mine, the princess sent me the following letter,
which being short I here insert.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Herford, 2nd of May, 1677.

This, Friend, will tell you that both your letters were very acceptable,
together with your wishes for my obtaining those virtues,
which may make me a worthy follower of our great King and Saviour, Jesus Christ.
What I have done for his true disciples, is not so much as a cup of cold water;
it affords them no refreshment;
neither did I expect any fruit of my letter to the Dutchess of Lauderdale,
as I have expressed at the same time unto Benjamin Furly.
But since Robert Barclay desired I should write it, I could not refuse him,
nor omit to do any thing that was judged conducing to his liberty,
though it should expose me to the derision of the world.
But this a mere moral man can reach at; the true inward graces are yet wanting in,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Elizabeth.

--

This digression from the present history, I thought not altogether unnecessary.

But to return.--Being arrived at that city, part of which is under her government,
we gave her to understand it;
desiring to know what time next day would be most proper for us to visit her.
She sent us word, she was glad that we were come;
and should be ready to receive us next morning about the seventh hour.

The next morning being come, which was the sixth-day of the week, we went,
about the time she had appointed us,
and found both her and the Countess ready to receive us;
which they did with a more than ordinary expression of kindness.
I can truly say it, and that in God`'s fear,
I was very deeply and reverently affected with the sense that was upon my spirit,
of the great and notable day of the Lord,
and the breakings-in of his eternal power upon all nations;
and of the raising of the slain Witness to judge the world;
who is the treasury of life and peace, of wisdom and glory,
to all that receive him in the hour of his judgments, and abide with him.
The sense of this deep and sure foundation, which God is laying,
as the hope of eternal life and glory for all to build upon,
filled my soul with an holy testimony to them;
which in a living sense was followed by my brethren;
and so the meeting ended about the eleventh hour.

The Princess entreated us to stay and dine with her; but,
with due regard both to our testimony and to her at that time, we refused it; desiring,
if she pleased, another opportunity that day.
To which she with all cheerfulness yielded; she herself appointing the second hour.

So we went to our quarters; and some time after we had dined, we returned.
The meeting soon began; there were several present besides the Princess and Countess.
It was at this meeting, that the Lord in a more eminent manner began to appear.
The eternal Word showed itself a hammer at this day, yea, sharper than a two-edged sword,
dividing asunder between the soul and the spirit, the joints and the marrow.
Yea, this day was all flesh humbled before the Lord! it amazed one, shook another,
broke another; the noble arm of the Lord was truly awakened,
and the weight and work thereof bowed and tendered us also,
after an unusual and extraordinary manner;
that the Lord might work an heavenly sign before them, and among them;
that the majesty of Him that is risen among the poor Quakers,
might in some measure be known unto them, what God it is we serve,
and what power it is we wait for and bow before.
They had a sense and a discovery that day, what would become of the glory of all flesh,
when God shall enter into judgment.
Well, let my right hand forget its cunning, and my tongue cleave to the roof of my mouth,
when I shall forget the lovingkindness of the Lord,
and the sure mercies of our God to us his travailing servants that day.
O Lord, send forth thy light and thy truth, that all nations may behold thy glory!

Thus continued the meeting till about the seventh hour; which done,
with hearts and souls filled with holy thanksgivings to
the Lord for his abundant mercy and goodness to us,
we departed to our lodging;
desiring to know whether our coming the next day might not be uneasy
or unseasonable to her with respect to the affairs of her government;
it being the last day of the week,
when we were informed she was most frequently attended with addresses from her people.
But with a loving and ready mind she replied,
that she should be glad to see us the next morning, and at any time when we would.

The next morning, being the 11th of the sixth month,
we were there betwixt eight and nine; where,
Robert Barclay falling into some discourse with the Princess,
the Countess took hold of the opportunity, and whispered me to withdraw,
to set a meeting for the more inferior servants of the house;
who would have been bashful to present themselves before the Princess.
And, blessed be the Lord! he was not wanting to us;
the same blessed power that had appeared to visit them of high,
appeared also to visit them of low degree;
and we were all sweetly tendered and broken together;
for virtue went forth of Jesus that day,
and the life of our God was shed abroad amongst us as a sweet savour;
for which their souls bowed before the Lord, and confessed to our testimony.

It did not a little please that noble young woman,
to find her own report of us and her great care of them so effectually answered.
Oh! what shall we say?
Is there any God like unto our God?
who is glorious in holiness, fearful in praises, working wonders!
To his eternal name, power and arm, be the glory forever!

The meeting done, the Princess came to us, expressing much satisfaction,
that we had that good opportunity with her servants; telling us,
she much desired they should have a true and right character of us,
and therefore she chose to withdraw, that they might have freer access,
and that it might look like their own act; or words to that purpose.

The twelfth hour being come, we returned to our inn; letting them understand,
we purposed (the Lord willing) to visit them some time that afternoon.

I must not here forget, that we found at our inn, the first night at supper,
a young merchant of a sweet and ingenuous temper, belonging to the city of Bremen;
who took occasion from that night`'s discourse, the sixth-day at dinner and supper,
and the seventh-day also, to seek all opportunities of conference with us;
and (as we have reason to believe) he stayed twenty-four hours in that city on our account.
We opened to him the testimony of Truth.
I know not that in any one thing he contradicted us.
At last he plainly discovered himself unto us,
to be a follower of a certain minister in Bremen,
who is even by his fellow-ministers and Protestants reproached with the name of Quaker,
because of his singular sharpness against the formal,
lifeless ministers and Christians in the world.

We laid fast hold upon this; and asked him, in case any of us should visit that city,
if he would give us the opportunity of a meeting at his house,
which he readily granted us.
So we gave him some books;
recommending him to the true and blessed testimony of Christ Jesus, the Light,
and Judge of the world, and life of them that receive him and believe in him;
and so we parted.

It being now about three in the afternoon, we went to the Princess`'s; where being come,
after some little time,
the Princess and Countess put me in remembrance of a promise
I made them in one of my letters out of England,
that I would give them an account, at some convenient time, of my first convincement,
and of those tribulations and consolations,
which I had met withal in this way of the kingdom, to which God hath brought me.
After some pause, I found myself very free and prepared, in the Lord`'s love and fear,
to comply with their request; so, after some silence, began.
But before I had half done, it was supper-time;
and the Princess would by no means let us go, we must sup with her; which importunity,
not being well able to avoid, we yielded to, and sat down with her to supper.

Among the rest present at these opportunities, it must not be forgotten,
that there was a Countess, sister to the Countess, then come to visit her,
and a Frenchwoman of quality; the first behaving herself very decently,
and the last was often deeply broken;
and from a light and slighting carriage towards the very name of a Quaker,
she became very intimately and affectionately kind and respectful to us.
Supper being ended, we all returned to the Princess`'s chamber;
where making us all sit down with her, she, with both the Countesses and the Frenchwoman,
pressed from me the continuance of my relation;
but none more than the Countess`'s sister; with which though late,
I was not unwilling to oblige them,
because I knew not when the Lord would give me such an opportunity.

I found them affected; it continued till about ten o`'clock at night,
yet many particulars omitted, partly through forgetfulness, and partly for want of time.
Howbeit, I must needs say, they heard me with an earnest and tender attention;
and I hope and believe the Lord hath made it profitable unto them.
This done, they had some discourse upon it,
and afterwards we spoke about a meeting for the next day,
being the first-day of the week;
and that we might have not only as many of her own family,
but as many of her town as would willingly be there; she yielded to it,
and appointed the meeting to begin at the second hour; so we parted,
being near the eleventh hour at night.

The next morning we had a meeting among ourselves in our chamber,
wherein the Lord refreshed us; and there was a great travail upon our spirits,
that the Lord would stand by us that day and magnify
the testimony of his own truth by us;
that he might have a seed and people in that place to lift up a standard for his name.

At dinner there were several strangers, who came by the post wagon that day; among whom,
there was a young man of Bremen, being a student at the college at Duysburg;
who informed us of a sober and seeking man of great note in the city of Duysburg;
to him we gave some books.
There was another, who was tender and inquiring, to whom also we gave books.

The second hour being at hand, we went to the meeting; where were several,
as well of the town as of the family.
The meeting began with a weighty exercise and travail in prayer,
that the Lord would glorify his own name that day.
And by his own power he made way to their consciences,
and sounded his awakening trumpet in their ears, that they might know that he was God,
and that there is none like unto him.
Oh! the day of the Lord livingly dawned upon us,
and the searching life of Jesus was in the midst of us!
The Word that never faileth them that wait for it, and abide in it,
opened the way and unsealed the book of life; yea,
the quickening power and life of Jesus wrought and reached to them;
and virtue from him in whom dwelleth the Godhead bodily, went forth,
and blessedly distilled upon us his own heavenly life,
sweeter than the spices with pure frankincense, yea,
than the sweet smelling myrrh that cometh from a far country.
And as it began, so it was carried on, and so it ended; blessed be the name of the Lord,
and confided in be our God forever!

As soon as the meeting was done, the Princess came to me, and took me by the hand,
(which she usually did to us all,
coming and going,) and went to speak to me of the
sense she had of that power and presence of God,
which was amongst us; but was stopped.
And turning herself to the window, she broke forth in an extraordinary passion,
crying out,
"`I cannot speak to you--my heart is full`"--clapping her hands upon her breast.
It melted me into a deep and calm tenderness;
in which I was moved to minister a few words softly to her,
and after some time of silence, she recovered herself;
and as I was taking my leave of her, she interrupted me thus;
"`Will you not come hither again?
Pray call here as ye return out of Germany.`"
I told her, we were in the hand of the Lord;
and being his could not dispose of ourselves; but the Lord had taken care,
that we should not forget her and those with her;
for he had raised and begotten an heavenly concernment in our souls for her and them,
and we loved them all with that love wherewith God had loved us;
with much more to that purpose.

She then turned to the rest of the Friends,
and would have had us all gone down to supper with her.
But we chose rather to be excused;
we should eat a bit of her bread and drink a glass of her wine, if she pleased,
in the chamber where we were.
At last we prevailed with her to leave us.
The Countess, the Frenchwoman, and the Countess`'s waiting woman stayed with us;
and we had a very retired and seasonable opportunity with them.

After the Princess had supped, we went all down and took our solemn leave of her,
the Countess, her sister, the Frenchwoman, with the rest of the family,
whose hearts were reached and opened by our testimonies;
recommending to them holy silence from all will-worship, and the workings, strivings,
and images of their own mind and spirit;
that Jesus might be felt by them in their hearts,
his holy teachings witnessed and followed in the way of his blessed cross,
which would crucify them unto the world, and the world unto them; that their faith, hope,
and joy might stand in Christ in them, the heavenly Prophet, Shepherd, and Bishop;
whose voice, all that are truly sheep will hear and follow,
and not the voice of any stranger whatever.
So we left them in the love and peace of God;
praying that they might be kept from the evil of this world.

We returned to our lodging,
having our hearts filled with a weighty sense of
the Lord`'s appearance with us in that place;
and it being late, towards the ninth hour, we prepared to go to rest.
