== Chapter XII.

On the 23rd of sixth month,
we arrived by the way of Worms at Krisheim in the Paltzgrave`'s country, where we found,
to our great joy, a meeting of tender and faithful people.

But it seems the inspector of the Calvinists had joined the Vaught, or chief officer,
not to suffer any preaching to be among our friends; who,
poor man! fearing the indignation of the clergy,
came next day to desire Friends not to suffer any preaching to be amongst them,
lest he should be turned out of his place.
To whom we desired Friends to say, that, if he pleased he might apprehend us,
and carry us to the Prince, before whom we should give an account of our testimony.

But, blessed be the Lord! we enjoyed our meeting quietly and comfortably;
of which a coach full from Worms made a part,
amongst whom was a governor of that country, and one of the chief Lutheran priests.

It came upon me in this place to salute the Princess
and Countess with this following epistle.

[.embedded-content-document.epistle]
--

[.blurb]
=== A salutation to Elizabeth, Princess Palatine, and Anna Maria de Homes, Countess of Homes, at Herwerden in Germany.

[.salutation]
My worthy friends,

Such as I have, such I give unto you; the dear and tender salutation of light, life,
peace, and salvation by Jesus Christ, the blessed Lamb of God;
with the unspeakable joy of which, he has replenished my soul at this time,
that my cup overfloweth;
which is the reward of those who cheerfully drink his cup of tribulations,
love the cross, and triumph in all the shame, reproaches,
and contradictions of the world that do attend it.
My God take you by the hand,
and gently lead you through all the difficulties of regeneration;
and as you have begun to know and love his sweet and tender drawings,
so resign the whole conduct of your lives to him.

Dispute not away the precious sense that you have of him,
be it as small as a grain of mustard-seed, which is the least of all seeds;
there is power in it, if you do but believe,
to remove the greatest mountains of opposition.
Precious is this faith, yea,
more precious than the glory and honour of this world that perisheth:
it will give courage to go with Christ before Caiaphas and Pilate;
yea,`' to bear his cross without the camp, and to be crucified with him,
knowing that the spirit of God and of glory shall rest upon them.
To the inheritors of this faith,
is reserved the eternal kingdom of peace and joy in the Holy Ghost.

O! be you of that little flock, unto whom Jesus said, '`Fear not,
for it is my Father`'s good pleasure to give you the kingdom:`' and, to be of this flock,
you must become as sheep and to be as sheep, you must become harmless;
and to become harmless, you must hear and follow the Lamb of God;
as he is that blessed Light which discovereth and
condemneth all the unfruitful works of darkness,
and maketh harmless as a dove; which word, all,
leaveth not one peccadillo or circumstance undiscovered or unjudged;
and the word darkness, taketh in the whole night of apostacy; and the word unfruitful,
is a plain judgment against all those dark works.
Wherefore, out of them all come, and be you separated;
and God will give you a crown of life, which shall never fade away.

O! the lowness and meanness of those spirits,
that despise or neglect the joys and glories of immortality,
for the sake of the things which are seen, that are but temporal;
debasing the nobility of their souls, abandoning the government of the divine Spirit,
and embracing with all ardency of affection the sensual pleasures of this life;
but such as persevere therein, shall not enter into God`'s rest forever.

But this is not all that hindereth and obstructed in the holy way of blessedness;
for there is the world`'s fear as well as the world`'s joy that obstructeth many,
or else Christ had not said, '`Fear not,`' to his little flock.
The shame of the cross is a yoke too uneasy,
and a burden too heavy for flesh and blood to bear, it is true; but therefore,
shall flesh and blood never enter into the kingdom of God.
And not to them that are born of the flesh,
but to those that are born of the Spirit through the word of regeneration,
is appointed the kingdom, and that throne which shall judge the twelve tribes of Israel,
and all the world.
The Lord perfect what he hath begun in you,
and give you dominion over the love and fear of this world.

And, my friends, if you would profit in the way of God,
despise not the day of small things in yourselves: know this,
that to desire and sincerely to breathe after the Lord, is a blessed slate.
You must seek, before you find.
Do you believe?
make not haste;
extinguish not those small beginnings by an over earnest or impatient desire of victory.
God`'s time is the best time; be you faithful,
and your conflict shall end with glory to God, and the reward of peace to your own souls.

Therefore love the judgment, and love the fire; start not aside,
neither flinch from the scorchings of it,
for it will purify and refine you as gold seven times tried;
then cometh the stamp and seal of the Lord upon his own vessel, holiness to him forever;
which he never gave, nor will give to reprobate silver,
the state of the religious worshippers of the world.
And herein be comforted, that Zion shall be redeemed through judgment,
and her converts through righteousness; and after the appointed time of mourning is over,
the Lord will give '`beauty for ashes, the oil of joy for mourning,
and the garment of praise tor the spirit of heaviness.`' Then shall you be able to say,
'`Who is he that condemneth us?
God hath justified us; there is no condemnation to us that are in Christ Jesus,
who walk not after the flesh, but after the Spirit.`'

Wherefore, my dear friends, walk not only not after the fleshly lusts,
but also not after the fleshly religions and worships of the world;
for that which is not born of the Spirit is flesh;
and all flesh shall wither as the grass,
and the beauty of it shall fade away as the flower of the field,
before God`'s Sun that is risen, and rising.
But the Word of the Lord in which is life, and that life, the light of men,
shall endure forever, and give life eternal to them that love and walk in the light.

And I entreat you, by the love you have for Jesus,
have a care how you touch with fleshly births, or say Amen, by word or practice,
to that which is not born of the Spirit; for God is not to be found of that,
in yourselves or others, which calleth him Father, and he hath never begotten it in them;
that latitude and conformity is not of God, but secretly grieveth his Spirit,
and obstructeth the growth of the soul in its acquaintance
and intimate communion with the Lord.
'`Without me,`' saith Jesus,
'`you can do nothing;`' and '`all that came before me are thieves and robbers.`' If so,
what are they that pray, and preach, and sing without Jesus,
and follow not him in those duties, but even crucify him in them?
O that I may find in you an ear to hear,
and a heart to perceive and embrace these truths of Jesus!

And I can say, I have great cause to hope,
and patiently to wait till the salvation of God be further revealed to you,
and the whole family; with whom, I must acknowledge,
I was abundantly refreshed and comforted,
in that God in measure made known the riches of his grace,
and operation of his celestial power to you; and his witness shall dwell with you,
if we never see you more, that God magnified his own strength in our weakness.
With him we leave our travails,
affectionately recommending you to his holy Spirit of grace,
that you may be conformed to the image of his own dear Son,
who is able and ready to preserve you.
O stay your minds upon him, and he will keep you in perfect peace,
and abide with you forever!
The Almighty take you into his holy protection now and forever.

I am your true friend, ready to serve you with fervent love in the will of God.

[.signed-section-signature]
William Penn.

[.postscript]
P+++.+++ S. My dear companions do, with me, give you the dear salutation of unfeigned love,
and those in the family that love and desire to follow
the Lord Jesus in sincerity and truth without wavering.
We are this evening bound towards Manheim, the court of the prince Palatine,
and have travelled about twelve English miles on foot.

--

That night we lodged at Frankenhal, and got the next morning,
being the seventh-day of the week, to Manheim; but were disappointed of our design,
which was, to speak with the prince; for he was gone the day before to Heidelberg,
his chief city, about fifteen English miles from that place.
Considering, that by reason of the meeting next day with Friends at Krisheim,
already appointed, we could neither go forward, nor stay till he returned;
and yet being not clear to come away, as if we had never endeavoured to visit him,
it was upon me to write him this following letter, to let him know we had been there,
and briefly our end in coming.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Prince Elector Palatine of Heidelberg.

[.salutation]
Great prince,

It would seem strange that I, both a stranger and a subject,
should use this freedom of address to a prince, were he not one,
whose actions show him to be of a free disposition, and easy access to all:
would to God all princes were of that mind!
But I have not chosen this way of application; I am driven to it,
by the disappointment thy absence from this court gave me,
and the necessity I am under to expedite my return.
And though I cannot so fully, and consequently not so clearly,
express by letter the grounds inducing me to attempt this visit;
yet this being all the way that is left me, I shall declare them as well as I can.

In the first place, I do with all sincere and Christian respect,
acknowledge and commend that indulgence thou givest to all people professing religion,
dissenting from the national communion: for it is in itself a most natural, prudent,
and Christian thing.

Natural,--because it preserves nature from being
made a sacrifice to the savage fury of fallible,
yet proud opinions, outlawing men of parts, arts, industry, and honesty,
the grand requisites of human society;
and exposing them and their families to utter ruin for mere non-conformity,
not to religion, but to modes and fashions in religion.

Christian,--since the contrary expressly contradicts
both the precept and example of Christ,
who taught us to love enemies, not to abuse our friends,
or triumph in the destruction of our harmless neighbours.
He rebuked his disciples, when they called for fire from heaven upon dissenters,
it may be, opposers: certainly then,
he never intended that they should kindle fire on earth to devour men for conscience.
And if Christ, to whom all power was given, and his holy apostles,
refused to employ human force and artifice so much as to preserve themselves,
it is an arrogancy every way indefensible in those that pretend to be their followers,
that they assume an authority to supersede, control,
and contradict the precepts and examples of Christ and his apostles;
whose kingdom not being of the nature of this ambitious, violent world,
was not erected or maintained by those weapons that are carnal,
but spiritual and intellectual, adequate to the nature of the soul,
and mighty through God to cast down the strong holds of sin,
and every vain imagination exalted in man above the lowly, meek fear of God,
that ought to have the preeminence in the hearts of the sons of men.

Indulgence is prudent, in that it preserveth concord: no kingdom divided against itself,
can stand.
It encourageth arts, parts, and industry, to show and improve themselves,
which indeed are the ornaments, strength, and wealth of a country:
it encourageth people to transplant into this land of liberty,
where the sweat of the brow is not made the forfeit of the conscience.

And lastly, it rendereth the prince peculiarly safe and great.
Safe, because all interests, for interest-sake, are bound to love and court him.
Great, in that lie is not governed or clogged with the power of his clergy;
which in most countries is not only a co-ordinate power,
a kind of duumvirateship in government, imperiwn in imperio,
at least an eclipse to monarchy, but a superior power,
and rideth the prince to their designs, holding the helm of the government,
and steering not by the laws of civil freedom,
but certain ecclesiastical maxims of their own,
to the maintenance and enlargement of their worldly empire in their church.
And all this acted under the sacred, peaceable, and alluring name of Christ,
his ministry and church; though as remote from their nature, as the wolf from the sheep,
and the pope from Peter.

The next thing I should have taken the liberty to have discoursed, would have been this;
what encouragement a colony of virtuous and industrious
families might hope to receive from thee,
in case they should transplant themselves into this country,
which certainly in itself is very excellent, respecting taxes, oaths, arms, etc.

Further, to have represented the condition of some of our Friends, and thy own subjects;
who though they are liable to the same tax as Menists, etc,
yet the Vaught of the town where they live,
came yesterday to forbid all preaching amongst them,
which implies a sort of contradiction to the indulgence given.

And in the last place,
forasmuch as all men owe their being to something greater than themselves,
to which it is reasonable to believe they are accountable,
from whence follow rewards or punishments,--I had
an earnest desire to have spoken of the nature,
truth, use, benefit, and reward of religion; and therein to have discoursed,
what the Christian religion is in itself,
freed from those unreasonable garbs some men make it to wear,
so justly offensive to wise and thinking men--thus to have proved
the principle and life of the people in scorn called Quakers,
to be suitable to the true followers of holy Jesus.
But, as the particulars would swell a letter to a book,
I shall take the freedom to present thee, upon my return,
with some tracts treating upon all these subjects.

Prince! my soul is filled with love and respect to thee and thy family;
I wish you all true and lasting felicity,
and earnestly desire that you may never forget your afflictions,
and in the remembrance of them be dehorted from those lusts and impieties,
which draw the vengeance of heaven upon the greatest families on earth;
that God may look upon you with the favourable eye of his providence.
And blessed is that man, whose God by profession is his Lord in reality;
who is ruled and governed by the Lord, lives in subjection to his grace,
and having a Divine sense of God in his heart,
delights to retain that sense and knowledge of him,
and be meditating in his noble royal law, that converts the soul to God,
and redeems man from the sensual pleasures of this world,
to the true satisfaction of the intellectual and Divine life.

O the meanness and lowness of their spirits,
who abandon themselves to the government of sense, the animal life,
thereby debasing their natures, rejecting the Divine light, that shineth in their hearts,
saying, '`Let us eat and drink,
for tomorrow we shall die;`' forgetting whence they are descended,
and not considering the peace and joy of the virtuous!

I desire that the Lord would put it into thy heart to think of thy latter end,
and with the light of Christ in thy conscience examine how it stands with thy soul,
that thou mayst know,
and diligently watch to do those things that belong to thy eternal peace.

One thing more give me leave to recommend to thee, and that is,
to be very careful to inculcate generous, free, and righteous principles into thy son,
who is likely to succeed thee; that when thou art gone,
the reputation of the country may not sink by contrary practices,
nor the people of divers judgments, now thy subjects, be disappointed, distressed,
or ruined.
Which, with sincere desires for thy temporal and eternal good, conclude this,

[.signed-section-closing]
Thy unknown, but sincere friend,

[.signed-section-signature]
William Penn

[.signed-section-context-close]
From Manheim, 25th of Sixth month, 1677.

--

This being done, and having refreshed ourselves,
we returned that night by the Rhine to Worms; whence, the next morning,
being the first-day of the week, we walked on foot to Krisheim,
about six English miles from Worms.
We had a good meeting from the tenth till the third hour,
and the Lord`'s power was sweetly opened to many of the
inhabitants of the town who were at the meeting.
The Vaught or chief officer himself stood at the door behind the barn,
where he could hear and not be seen; and went to the priest and told him,
that it was his work, if we were heretics, to discover us to be such,
but for his part he heard nothing but what was good, and he would not meddle with us.

In the evening we had a more retired meeting of the Friends only,
very weighty and tender; yea, the power rose in a high operation among them,
and great was the love of God that was in our hearts at the meeting to visit them;
and there is a lovely, sweet, and true sense among them.
We were greatly comforted in them, and they were greatly comforted in us.
Poor hearts! a little handful surrounded with great and mighty countries of darkness;
it is the Lord`'s great goodness and mercy to them,
that they are so finely kept in the seed of life.
Most of them were gathered by dear William Ames.

On the 27th we had another meeting, where we took our leave of them,
and accompanied by several of them, came to Worms; where having refreshed ourselves,
we went to visit the Lutheran priest,
who was at the meeting the sixth-day before at Krisheim.
He and his wife received us very kindly, not without some sense of our testimony.
After we had discoursed about an hour with him of
the true and heavenly ministry and worship,
and in what they stood, and what all people must come to,
if they ever know how to worship God aright; we departed,
and immediately sent them several good books of Friends in High Dutch.

We took boat about the third hour in the afternoon,
and came down the river Rhine to Menlz,
where we arrived about the fifth hour in the morning;
and immediately took an open chariot for Frankfort,
where we came about the first hour in the afternoon.
We presently informed some of those people that had received us the time before,
of our return to that city, with desires that we might have a meeting that afternoon;
which was readily granted us by the noble women at whose house we met,
whither resorted some that we had not seen before.
And the Lord did, after a living manner, open our hearts and mouths amongst them,
which was received by them as a further confirmation
of the coming of the day of the Lord unto them;
yea, with much joy and kindness they received us.
The meeting held till the ninth hour at night;
they constrained us to stay and eat with them, which was also a blessed meeting to them.
Before we parted, we desired a select meeting the next morning at the same place,
of those that we felt to be more inwardly affected with Truth`'s testimony,
and that were nearest to the state of a silent meeting; to which they joyfully assented.

We went to our lodging, and on the 29th returned to them,
with whom we had a blessed and heavenly opportunity;
for we had room for our life amongst them: it was as among faithful Friends;
life ran as oil, and was a-top of all.

We recommended a silent meeting to them,
that they might grow into a holy silence unto themselves; that the mouth that calls God,
Father, and is not of his own birth, may be stopped, and all images confounded;
that they may hear the soft voice of Jesus to instruct them,
and receive his sweet life to feed them and to build them up.

About the ninth hour we departed from that place, and went to Vanderwalls,
where the meeting was the time before; and there we had a more public meeting,
of all that pleased to come.
The Lord did so abundantly appear amongst us,
that they were more broken than we had seen them at any time; yea,
they were exceedingly tender and low,
and the love of God was much raised in their hearts to the testimony.
In this sensible frame we left them,
and the blessings and peace of our Lord Jesus Christ with and among them.

After having refreshed ourselves at our inn, we took boat down the Main to Mentz,
where we arrived about the fifth hour.
It is a great city, but a dark and superstitious place, according to the popish way,
and is under the government of a popish bishop.
We stayed no longer there, than until our boat was ready,
which might be more than half an hour.

From Mentz we went on our way down the Rhine six German miles,
and came that night to Hampack.
From thence the next morning by Bacharach, Coblentz, and other places upon the Rhine,
to Tressy that night, being about eleven German miles.

Next day, the 31st, we got to Cologne, a great popish city,
about the third hour in the afternoon.
We gave notice to a sober merchant, a serious seeker after God, that we were arrived;
who presently came to us.
We sat down, and had a living and precious opportunity with him;
opening to him the way of the Lord, as it had been manifested to us; entreating him,
if he knew any in that city, who had desires after the Lord,
or were willing to come to a meeting,
that he would please to inform them of our being here,
and of our desire to meet with them.
He answered, that he would readily do it.
This night, when we were in bed, came the resident of several princes,
a serious and tender man, to find us out; we had some discourse with him; but,
being late, he promised to see us the next day.

The next morning the aforesaid merchant informed us, that it was a busy time,
several preparing for the mass or great fair at Frankfort; yet some would come,
and he desired it might be at his house about three in the afternoon.

That morning, we went to visit the resident, whom we met coming to see us;
but he returned and brought us to his house.
We had a good time with him; for the man is an ancient seeker,
oppressed with the cares of this world, and he may be truly said to mourn under them.
His heart was opened to us, and he blessed God that he had lived to see us.
We gave him an account, how the Lord had appeared in the land of our nativity,
and how he had dealt with us;
which was as the cool and gentle showers upon the dry and scorched desert.
About noon we returned home, and after we had eaten,
we went to the merchant`'s house to the meeting; where came four persons,
one of whom was the Presbyterian priest,
who preached in private to the Protestants of that place,
for they are in no ways publicly allowed in that city.
Surely,
the true day and power of the Lord made itself known to the consciences of those present:
yea they felt that we were such as had been with Jesus,
and bad obtained our testimony through the sufferings and travails of the cross.
They were tender: the resident and merchant conducted us to our inn,
and from thence to the boat, being about seven at night.
We set out towards the city of Duysburg, of the Calvinist way,
belonging to the Elector of Brandenburg; in and near to which, we had been informed,
there was a retired and seeking people.

We arrived there on the 2nd of seventh month, about noon, being the first-day of the week.
The first thing we did, after we came to our inn, was to inquire out one Dr. Maastricht,
a civilian, for whom we had a letter to introduce us, from a merchant of Cologne:
whom quickly finding, we informed him what we came about, desiring his assistance;
which he readily promised us.
The first thing we offered, was an access to the Countess of Falkenstein and Bruck.
He told us she was an extraordinary woman,
one in whom we should find things worthy of our love; that he would write to her,
to give us an opportunity with her; that the fittest time was the present time,
in that we might find her at the minister`'s of Mulheim,
on the other side of the river from her father`'s castle;
for that she used to come out on first-day morning, and not return till night:
that we must be very shy of making ourselves public, not only for our own sakes,
but for hers, who was severely treated by her father,
for the sake of those religious inclinations that appeared in her,
although her father pretended to be of the Protestant religion.

We therefore dispatched towards Mulheim, having received his letter,
and being also accompanied by him about one-third of the way.
But being six English miles, and on foot,
we could not compass the place before the meeting was over;
for it was past three before we could get out of Duysburg: and,
following that way which led to the back of the Graef`'s castle and orchard,
which was also a common way to the town,
(though if we had known the country we might have
avoided it,) we met with one Henry Smith,
school-master and catechiser of Speldorp, to whom we imparted our business,
and gave the letter of Dr. Mastricht of Duysburg to introduce us to the Countess.

He told us, he had just left her, being come over the water from worship,
but he would carry the letter to her, and bring an answer suddenly;
but notwithstanding stayed near an hour.
When he came he gave us this answer; namely, that she would be glad to meet us,
but she did not know where;
but rather inclined that we should go over the water to the minister`'s house, whither,
if she could, she would come to us;
but that a strict hand was held over her by her father.
After some more serious discourse with him,
concerning the witness of God in the conscience, and the discovery, testimony,
and judgment of that true light,
unto which all must bow that would be heirs of the kingdom of God;
recommending him to the same, we parted; he returning homewards,
and we advancing to the town.
Being necessitated to pass by her father`'s castle,
who is seignior or lord of that country,
it so fell out that at that very instant he came forth to walk;
and seeing us in the habit of strangers,
sent one of his attendants to demand who and from whence we were?
and whither we went]
calling us afterwards to him, and asking us the same questions.
We answered, that we were Englishmen come from Holland,
going no further in these parts than his own town of Mulheim.
But not showing him,
or paying him that worldly homage and respect which was expected from us,
some of his gentlemen asked us, if we knew whom we were before?
and if we did not use to deport ourselves after another manner before noblemen,
and in the presence of princes?
We answered, we were not conscious to ourselves of any disrespect or unseemly behaviour.
One of them sharply replied, "`Why do not you pull off your hats, then?
Is it respect, to stand covered in the presence of the sovereign of the country?`"
We told them, it was our practice in the presence of our prince, who is a great king,
and that we uncovered not our heads to any, but in our duty to Almighty God.
Upon which the Graef called us Quakers, saying to us, "`We have no need of Quakers here;
get you out of my dominions, you shall not go to my town.`"

We told him we were an innocent people, that feared God,
and had good-will towards all men; that we had true respect in our hearts towards him,
and would be glad to do him any real good or service;
and that the Lord had made it matter of conscience to us,
not to conform ourselves to the vain and fruitless customs of this world,
or words to this purpose.
However, he commanded some of his soldiers to see us out of his territories;
to whom we also declared somewhat of the reason and
intention of our coming to that place,
in the fear and love of God; and they were civil to us.

We parted with much peace and comfort in our hearts;
and as we passed through the village where the school-master dwelt,
(yet in the dominions of the Graef,) we called upon him,
and in the sense of God`'s power and kingdom opened
to him the message and testimony of Truth,
which the man received with a weighty and serious spirit.
Under the dominion of the Graef,
there is a large congregation of Protestants called Calvinists, of a more religious,
inward, and zealous frame of spirit,
than any body of people we met with or heard of in Germany.

After we had ended our testimony to him, we took our leave; desiring him not to fear,
but to be of good courage,
for the day of the Lord was hastening upon all the workers of iniquity:
and to them that feared his name, wherever scattered throughout the earth,
he would cause the Sun of righteousness to arise and visit them,
with healing under his wings.
We desired he would remember us with true love and kindness to the Countess,
daughter to the Graef; and to desire her not to be offended in us,
nor to be dismayed at the displeasure of her father,
but eye the Lord who hath visited her soul with his holy light,
by which she seeth the vanity of this world,
and in some measure the emptiness and deadness of the religions that are in it;
and he would preserve her from the fear of the wrath of men,
that worketh not the righteousness of God.
So we left the peace of Jesus with him and walked on towards Duysburg,
being about six English miles from thence, and near the eighth hour at night.
The Lord was with us, and comforted our hearts with the joy of his salvation,
as we walked, without any outward guide, through a tedious and solitary wood,
about three miles long.
He gave us to remember,
and to speak one unto another of his blessed witnesses in the days past,
who wandered up and down like poor pilgrims and strangers on the earth,
their eye being to a city in the heavens that hath foundations,
whose builder and maker is God.

Between nine and ten o`'clock, we reached the walls of Duysburg; but the gates were shut,
and there being no houses without the walls, we laid us down together in a field,
receiving both natural and spiritual refreshment: blessed be the Lord.
About three o`'clock in the morning we rose,
sanctifying God in our hearts who had kept us that night; and walked till five o`'clock,
often speaking one to another of the great and notable
day of the Lord dawning upon Germany,
and of several places in that land that were almost ripe unto harvest.
