== Chapter XIV.

The next morning, being the 4th of the seventh month, we set out for Wesel,
and got thither at noon.
The first thing we did, as had been our custom, was to inquire who was worthy;
particularly for two persons, recommended to us by the Countess of Homes,
who lives with the Princess Elizabeth.
We found one of them was gone to Amsterdam with his wife,
who had formerly been a preacher,
and being conscientiously dissatisfied with his own preaching, laid it down,
and is now in a seeking state.
But in lieu of him, we found out three more,
with the person who had been recommended to us.
We bespoke a meeting amongst them after dinner,
which accordingly we had at a woman`'s house of good note in the town; who told us,
that she had been long in a solitary estate,
dissatisfied with the religions generally professed in that country,
waiting for salvation, and she hoped that now the time was come,
and that we were the messengers of it.

The Lord was with us in the meeting, and their hearts were opened by the word of God,
to receive our testimony as glad tidings of salvation.
Meeting being done, we immediately returned to our lodging,
desiring we might see them together in the same place the next morning,
to take our leave of them; to which they readily assented.

Next morning we came, and had a precious meeting with them,
and there were some present who were not there the night before.
So we left them in much love, and after having refreshed ourselves at our inn,
we went to Rees; where we met with a counsellor of Gelderland,
with whom we had a good opportunity to declare the testimony of Jesus, who received it,
and parted with us in much kindness.

From thence we went to Emrick, and there called upon an eminent Baptist teacher,
recommended to us by one of Wesel.
We spent some time with him, opening to him the way of life,
as in the light it is manifested to all that love and obey the light;
and of that more spiritual and pure ministry,
which from the living word of God is received by many true ministers in this day.
The man was somewhat full of words;
but we felt the living visitation of the love of God reached to him, and so we left him;
making all the haste we could, to get to Cleve that night; which accordingly we did,
though late, being forced to walk one-third part of the way.

That night, notwithstanding, one of us went to a certain lady,
to whom we had recommendations from the Princess,
and who was particularly known to one of us; informing her, we were come to that city,
desiring to know what time next day we might give her a visit;
she appointed eight o`'clock in the morning.

About that time we went to see her; she received us agreeably,
considering her quality and courtship,
far from showing any appearance of offence at our deportment.
We told her, our message and visit was to those of that city,
who had any inclinations or desires,
hunger or thirst after the true and living knowledge of God: for that end,
we had left our own country, and had travelled up and down in several parts of Germany.
She told us, that some there were who searched after God;
but she feared the name of Quaker would make them shy,
because they were called Quakers themselves, by people of the same profession,
only for being more serious and retired in their conversation.
We replied, that it was an honour to the name,
that all sobriety throughout Germany was called by it;
this ought to make the name less odious, yea,
it will make the way easier for those that are truly called so,
or that are Quakers indeed.
It will take off much of the wonder, and it may be,
of the severity of the places where we come, that the name is gone before us,
and hath received a dwelling-place in their towns and cities.
In fine, to all such, God had committed to us the word of life to preach,
and such we seek out in all places whither the Lord brings us:
and hitherto we can say it, to the praise of our God,
he hath vindicated our service and testimony by his own blessed power,
shed abroad in their hearts to whom we have been sent.

She told us, she would send for an attorney at law,
one who was more than ordinarily eminent; having deserted the church,
and being therefore reproached with the name of Quaker.

In this interval, we had close discourse with her;--a woman certainly of great wit,
high notions, and very ready utterance;
so that it was hard for us to obtain a true silence,
a state in which we could reach to her.
But, through some travail of spirit more than ordinary,
we had a sweet time of refreshment, and the witness was raised in her;
and we really and plainly beheld a true nobility, yea,
that which was sensible of our testimony, and did receive it.

By this time, the person she sent for came, and a blessed sweet time we had:
for the power and presence of the Lord, our staff and strength,
unto whom our eye hath been throughout all our travels,
that we might only be acceptable in him--plenteously appeared amongst us;
both of these individuals confessing to the truth of what had been said,
and the attorney especially, to the living sense in which the Truth had been declared.
The Lord have the glory of his own work!

We would have returned to our inn to eat, according as we had appointed in the morning;
but she laid a kind of violent hands upon us,
and necessitated us to stay and eat with her; which we did.
We had no sooner sat down, but her brother-in-law,
a man of quality and employment in the court of the Elector of Bradenburg,
came in and dined with us.
As we sat at meat, we had a good meeting;
for the time was much taken up about the things of God,
either in answering their questions, or ministering;
to them about the true Christian nature and life; in all which,
her brother behaved himself with great sweetness and respect.
After dinner, we took our Christian leave of them in the fear of God,
recommending unto them the light of Christ Jesus,
that brings all that receive it into the one spirit,
to live in holy peace and concord together;
particularly and alone speaking to the lady and the attorney,
what was upon us as to their states.

We departed; and soon after took wagon for Nimeguen,
where arriving about the seventh hour that night, we immediately took wagon for Utrecht,
and got thither about the tenth hour next morning.
We hear there is a people in that city; but had not now time to visit them,
referring it to another opportunity.

About the first hour in the afternoon,
George Keith and Benjamin Furly took wagon for Rotterdam, and I took wagon for Amsterdam,
where I came safely that night, about six o`'clock in the evening;
and I found Friends generally well, though it is a sickly time in this country.
The meeting-house is much enlarged,
and there is a fresh inquiry among many people after the Truth,
and great desires to hear the testimony and declaration of it.
I also understand,
that dear George Fox is returned from Fredericstadt and Hamburg into Friesland,
whither T. R. and I. Y. are gone from this city to meet with him.
He has had a hard time of travel with respect to the weather,
yet I hear is in good health, through the Lord`'s power that hath kept him.

Here I received a letter from the Princess Elizabeth,
in answer to mine of the 25th of the sixth month, from Manheim, alias Fredericksburg.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
The 4th (14th) of September, 1677.

[.salutation]
Dear Friend,

I have received your greetings, good wishes, and exhortations with much joy,
and shall follow the latter as far as it will please
our great God to give me light and strength.

I can say little for myself, and can do nothing of myself,
but I hope the Lord will conduct me in his time, by his way, to his end;
and shall not shrink from his fire; I do long for it; and when he assures my ways,
I hope he will give me power to bear the cross I meet therein.
I am also glad to hear the journey hath been prosperous,
both in the constitutions of your bodies, to withstand the badness of the weather,
and in the reception you had in Cassel, Frankfort,
and Krisheim Nothing surprised me there, but the good old Dury,
in whom I did not expect so much ingenuity, having lately written a book,
entitled '`Le veritable Chretien,`' which speaks in another way.
I wish to know what reception you have had at Fredericsburg,
and if this find you at Cleve,
I wish you might take an occasion to see the two pastors of Mulheim,
who do really seek the Lord, but have some prejudice against your doctrine,
as also the Countess there.
It would be of much use for my family to have them disabused;
yet God`'s will be done in that, and all things else, concerning

[.signed-section-closing]
Your loving friend in the Lord Jesus,

[.signed-section-signature]
Elizabeth.

[.postscript]
====

P+++.+++ S. Let both your friends and companions receive my hearty commendations here.

====

--

This day, being the 8th, at night came John Hill from Friesland,
to the house of Gertrude Diricks in Amsterdam.

The next day, being the first-day of the week, we had a blessed and large meeting,
larger than ordinary, because a great addition of room +++[+++had been made]
since our journey into Germany.
Indeed, there was a great appearance of sober, professing people, yea,
several of the chief of the Baptists, as Galenus and companions.
The Lord`'s heavenly power was over all,
and the meeting ended blessedly about the fourth hour.

That night, after supper, having taken my leave in a sweet little meeting among Friends,
I took boat for Horn, P. Hendricks accompanying me, about the seventh hour at night,
and got thither about two o`'clock in the morning: here,
lying down till about six o`'clock, we took wagon for Enckhuysen.
We came thither a little after eight o`'clock in the morning;
and having refreshed ourselves,
about the ninth hour we took ship for Worcum in Friesland, arriving about one o`'clock;
and thence immediately took wagon for Harlingen, where we came about six o`'clock;
there we met with dear George Fox, J. T., I. Y., T. R., John Claus and his wife.

The next day we had two blessed meetings; one amongst Friends,
being the first Monthly Meeting that was settled for Friesland, Groningen, and Embden;
the other a public meeting, where resorted both Baptists, Collegians, and others,
and among the rest, a doctor of physic and a Presbyterian minister.
All sat with great attention and sobriety, but the minister and doctor more especially.
The first having a lecture-sermon to preach that evening, went away; but notwithstanding,
speedily returned, George Fox still speaking: but, as a man in pain to be gone,
yet willing to stay, sat at the door till G. F. had done; and then stood up,
and pulling off his hat, looking up to heaven, in a solemn manner, and with a loud voice,
spake to this purpose; "`The Almighty, the all-wise, the omnipotent great God,
and his Son Jesus Christ, who is blessed forever and ever,
confirm his word that hath been spoken this day:`" apologizing,
that he could not longer stay, for that he was a minister of the Reformed religion,
and was just now going to preach, where all that would come should be welcome;
and so left the meeting.

The physician also was called away, but returned and stayed till the meeting ended.
Just as the meeting ended, came the minister again,
who said in the hearing of some Friends,
that he had made his sermon much shorter than ordinary,
that he might enjoy the rest of the meeting.
At night came the physician to see me, who after a serious and Christian discourse,
expressing great satisfaction in most things relating to Friends, left me:
withal telling me, that if I had not been going the fourth hour next morning,
he would either have stayed longer with me, or come again.

He also remembered the parson`'s love to us; and told me,
that if it had not been for fear of giving offence,
or coming too much under the observation of the people, he would have come to see us:
adding, that it was great pity,
this people had not printed their principles to the world: to which the doctor answered,
that he had some of our books, and he would lend him them.
Blessed be the Lord, his glorious work goeth on, and his power is over all!
It being now the tenth hour at night, I took my leave of George Fox and Friends.

This day it came upon me to write a letter to the noble young woman at Frankfort,
as follows.

[.embedded-content-document.letter]
--

[.salutation]
Dear friend, Joanna Eleonora Malane,

My dear and tender love,
which God hath raised in my heart by his living word to all mankind,
(but more especially unto those,
in whom he hath begotten a holy hunger and thirst after him,) saluteth thee.
And amongst those of that place where thou livest, the remembrance of thee,
with thy companions, is most particularly and eminently at this time brought before me.
And the sense of your open-heartedness, simplicity,
and sincere love to the testimony of Jesus, delivered by us unto you,
hath deeply engaged my heart towards you;
and often raised in my soul heavenly breathings to the God of my life,
that he would keep you in the daily sense of that Divine life, which then affected you.
For this know, it was the life in yourselves,
that so sweetly visited you by the ministry of life through us.

Wherefore, love the Divine life and light in yourselves: be retired and still;
let that holy seed move in all heavenly things before you move.
For no one receiveth any thing that truly profiteth, but what he receiveth from above.
Thus said John to his disciples.
Now, that that stirreth in your hearts, draweth you out of the world,
slayeth you to all the vain glory, and pleasure, and empty worships that are in it,
this is from above, the heavenly seed of God, pure and incorruptible,
which is come down from heaven to make you heavenly;
that in heavenly places you may dwell, and witness, with the saints of old,
this heavenly treasure in earthen vessels.

O stay your minds upon the appearance of Jesus in you, in whose light you shall see light.
It will make you of a weighty, considering spirit, more and more;
that you may see how the mystery of iniquity hath wrought,
and how mankind is corrupted in all things,
and what part you yet have which belongeth not to the paradise of God;
that you may lay it all down at the feet of Jesus, and follow him,
who is going up and down, doing good to all that believe in his name.
So, possess your souls in the sensible feeling of his daily Divine visits,
shillings and breathings upon your spirits; and wait diligently, and watch circumspectly,
lest the enemy surprise you, or your Lord come at unawares upon you,
and you be unprepared to receive his sweet and precious visitations; that so,
those holy beginnings, which thou art a witness of with thy companions, may not be lost,
or as if they had never been; but that you may, from day to day,
feel the growth of his light, life, power, and kingdom in your souls,
that you may be able to say, '`The kingdom of God is come, yea,
it is given to the saints.`'

And what I say unto one, I say unto all that received our testimony in that city,
to whom thou mayst give, if thou pleasest, the remembrance of my dear love;
who travail in the Spirit for their redemption,
that they may be brought into the glorious liberty of the sons of God.
Particularly salute me the young woman that met with us at thy lodging.
The Lord Jesus Christ, the Prince of peace, dwell amongst you,
keep your hearts steadfast in his holy light, without wavering,
all the days of your appointed time, until your great and last change shall come;
when he will receive his own sheep into his own everlasting kingdom,
from the power of the foxes and the wolves,
and all the devouring beasts and birds of prey;
when he will wipe away all tears from their eyes,
and sighing and sorrowing shall be no more; and when it shall be said,
there is no more death, no more night, no more time.

The Lord hath brought us well to Amsterdam, not without good service by the way;
for at Cologne we had a precious meeting, and were received with much gladness of heart.
We also went to Duysburg, and from thence towards Mulheim,
(being the first-day of the week,) hoping to get
an opportunity with the Countess of Bruck,
and to deliver thy letter: but her father, who is a cruel and severe man,
meeting us near his castle, stopped us; and after some little time, finding what we were,
said, they wanted no Quakers there,
and sent us with some of his soldiers out of his territory.
It was about sunset, so that we were forced to return towards Duysburg:
but the gates of the city being shut, and there being no houses without it,
we were forced to lie in the fields all night,
where the Lord made us a good and comfortable bed.
We told the Graef at parting, we were men that feared the Almighty God,
we desired the good of all men, and that we came not thither for any evil design;
but he would not hear; the Lord, if he pleaseth, forgive him.
Nevertheless, we had a good meeting at Duysburg, where we had our heart`'s desires;
the blessed power and life of God making its own
way in the hearts of those that heard our testimony.
I also wrote a large and tender letter to the Countess,
and received a sweet and loving message from her;
and I have great hopes that all things will work for the best.

From Duysburg we went to Wesel, where we inquired who was worthy,
and found four or five separated from all congregations,
waiting for the consolation of Israel, with whom we had two precious meetings.
Leaving the peace of Jesus with them, we went to Emrick,
where we visited the chief Baptist teacher, who confessed to our testimony,
and received us lovingly.
We directed him to the gift of God in himself, that pure and eternal word in the heart,
that he might know the pure ministry of that, from the ministry of man`'s spirit,
which cannot profit or give life to the soul.

From thence we went to Cleve, where at a lady`'s house, belonging to the court,
we had a precious meeting: and we found some who had deserted the public ministry,
as not being anointed of God to preach,
neither knowing by a true experience the way and travail of the new birth,
but are made and maintained by men.
We sounded the joyful Gospel amongst them; and from thence,
by the way of Nimeguen and Utrecht, we came the last sixth-day to Amsterdam,
which was the 7th of the seventh month.

This last first-day I had a great and blessed meeting at Amsterdam,
almost of every quality and religion; the Lord`'s heavenly power,
which is quickening people into a living sense of him, that they may say,
'`The Lord liveth, and he liveth in me,`' reigned that day over all.

In the evening I took boat for Horn,
and from thence came last night to this city of Harlingen,
where we met with some of our brethren, who had been at Hamburg and Fredericstadt;
and this day we are to have two meetings here, the one among our Friends,
the other public for the town.
It is upon me to visit J. de Labadie`'s people, that they may know Him in themselves,
in whom their salvation standeth; for these simple people are to be pitied.
From thence, I think to visit Leuwarden, Groningen, Embden, Bremen, Herwerden, Wesel,
Emrick, Cleve, Utrecht, and so to return to Amsterdam; the Lord enabling me by his power.

This ariseth in my heart to thee, Give not thy bread to dogs; spend not thy portion;
feed not the serpent, neither hearken to him: abide with Jesus,
and he will abide with thee, that thou mayst grow in wisdom and in righteousness,
through the cross that crucifieth thee to the world, and the world to thee.
So, in the love which overcometh the world, that is Divine and from above,
and leadeth all thither who receive it into their hearts, I take my leave of thee,
with thy companions, and all the rest of that city known to us,
remaining "`Thy faithful friend, and the Lord`'s day-labourer,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Harlingen, 11th of the Seventh month, 1677.

--
