== Chapter XVII.

The narrative from the 27th of the seventh month,
to the 9th of the eighth month inclusive,
is inserted in the following letter to the Countess of Homes.

[.embedded-content-document.letter]
--

[.letter-heading]
For Anna Maria de Homes, styled Countess of Homes, at Herioerden in Germany.

[.salutation]
My dear friend!

O that thou mayst forever dwell in the sweet and
lender sense of that Divine love and life,
which hath visited thy soul, affected and overcome thy heart!
O tell me, hath it not sometimes raised thy spirit above the world,
and filled thee with fervent and passionate desires, yea,
holy resolutions to follow Jesus, thy blessed Saviour,
who hath given his most precious blood for thee, that thou shouldst not live to thyself,
but to him that hath so dearly purchased thee.

O the retired, humble, reverent frame I have beheld thee in,
when this blessed life hath drawn thee into itself,
and adorned and seasoned thee with its own heavenly virtue;
beautifying thy very countenance,
beyond all the vain and foolish ornaments of the wanton daughters of Sodom and Egypt;
for therein are charms not known to the children of this world.

O that this holy and chaste life may be always precious with thee! and that thou
mayst be forever chastely kept in the love and fellowship of it!
That out of this world`'s nature, spirit and practice, thou mayst be redeemed by Him,
who is the way, the truth, and the life; who, as thou watchest with holy vigilance,
will not only daily manifest the devices of the enemy to thee, but save thee from him.
For Christ`'s work in thee is thy sanctification, as it is in him, his Father`'s will;
as he said of old to his disciples, '`This is the will of God,
even your sanctification.`'

My dear beloved friend, be steadfast, immovable, without wavering;
and work out thy great salvation with fear and trembling;
and lose not that sweet and precious sense, which the Lord hath begotten in thee:
it is soon lost, at least weakened, but hard to recover.
Wherefore, let not the spirit of the world in any of its appearances, vain company,
unnecessary discourse or words, or worldly affairs,
prevail upon the civility of thy nature; for they will oppress the innocent life,
and bring grievous weights and burdens upon thy soul, and prolong the coming of the Lord,
whom thou lookest for, and put the day of thy redemption afar off.
O beware of this compliance!
Let me put thee in mind of that sensible resolution,
so frequently and so passionately repeated by thee; '`Il faut que je rompe.
Il faut que je rompe.`' Ah! this speaketh a weight, this weight a sense,
and this sense a strong conviction.
Now, be assured,
that till obedience be yielded to that present manifestation and conviction,
the good things desired and thirsted after can never be enjoyed.

Wherefore, my dear friend, be faithful,
and watch against the workings of the spirit of this world in thyself;
that the nature and image of it in all things may be crucified,
that thou mayst know an entire translation, with holy Enoch, and walk with God.
Jesus, the holy Light, is this power of God, that killeth and maketh alive;
and he is the heavenly Vine too, if thou abidest in him, thou wilt bring forth fruit:
but if thou abidest not in him, thou wilt not bring forth that fruit,
in which his heavenly Father only can be glorified.
O see what the mind daily abideth in!
My soul is even ravished with the sense of that holy
and quiet habitation! '`In the world,`' saith he,
'`you shall have trouble; however, be of good cheer, I have overcome the world:
I am not of the world.`' As if he had said: '`I am not of the world`'s ways, worships,
customs, or fashions; for whatever is of the nature and spirit of this world,
hath no part in me; and as I am not of this world, neither are you of this world;
for I have chosen you out of the world; out of the inventions,
out of the worships and fashions of the world.
You are to leave them all, to come out of them all,
and live and walk as pilgrims in the world;`' that is, strangers; to what?
To the life and practice of the world; not using,
but renouncing the vain customs and ceremonies, yea, the whole conversation of the world;
remembering that '`the friendship of this world is
enmity with God.`' And what '`if the world hate you,
it hated me first;`' and '`the disciple is not greater than his master,
nor the servant than his Lord:`' if you were '`of the world,
the world would love you,`' and not reproach and persecute you;
for the world loveth its own.
O my dear friend, that thou mayst be perfectly sensible what it is,
not to be of this world.

But there is yet a further mystery in these words, not discerned of many,
in whom some tenderness and inquiry is begotten, much less of the worldly Christians.
This world hath a false earth and a false heaven, a false foundation, and a false joy:
not only gross wickedness, but iniquity in a mystery, inwardly and outwardly.
The false prophet, and dragon, and all their offspring are here concerned.
This is their world, that must be burnt with fire, that Christ is not of,
nor his true disciples.
The light of Jesus discovereth it!
He is that spiritual Solomon that giveth true judgment, and saveth the living child,
the true birth; giving it to the right mother, and not to the false pretender.
All that hear his voice and follow him, shall receive true light, discerning,
and judgment, to whom all judgment is given; they shall know his voice from man`'s.

There are two trees, of differing natures, that have contrary fruits and leaves.
The one is the tree of life, which is Christ; the other the tree of death,
and that is Satan.
The fruit of the one giveth life; the fruit of the other bringeth death;
the leaves of the first heal; the leaves of the last poison.
Many that discern the tree, cannot clearly distinguish the branches:
and those that see many arms and branches, cannot distinctly behold the fruit,
much less the leaves.
This cometh by the gradual discoveries and revelations of the light of Jesus,
the Word of God, as it is daily received and daily obeyed.
Yea, and that Word is the axe and sword of the Almighty, to cut it down:
daily feel the strokes of this eternal searching
Light and Word at the very root of this corrupt tree,
this evil one and his corrupt nature, works and effects.
For which end Jesus Christ is come, and therefore is called a Saviour,
which is little known in truth to the Christians of this world.

Ah! my dear friend, thou knowest this Word, yea, thou hast felt it.
O hide it in thy heart! treasure it up in thy soul, and love it,
and abide with it forever.
Alas!
Whither shouldst thou go?
He hath the words, and is the Word of eternal life: daily, therefore, watch and wait,
that thou mayst be grafted more into him;
that thou mayst live and grow by his virtue and life; and that he may grow in thy heart,
as among the first Christians, the holy followers of the persecuted Jesus.
And when he searcheth thy wound, and cutteth away thy dead flesh; yea,
when he separateth between the soul and the spirit of this world,
and divideth between joints and marrow; when he cutteth off the right hand,
and plucketh out the right eye; watch unto prayer,
and pray that thou mayst endure Keep the holy patience of this pure and living Word;
and this very Word will keep thee in the hour of thy sharpest trials,
and sorest tribulations!
All virtue is in him!
He is a tried Word, a sure refuge; the staff and strength of the righteous in all ages.
He was David`'s teacher and buckler; a light to his feet, and a lantern to his paths.
Walk thou in the light thereof, and thou shalt not stumble: in this Word is life,
(as in the root,) and this life is the light of men.
They that receive and love the light of it,
will therein receive Divine life from it to live to God.
This is the bread of God that cometh from God, and feedeth and leadeth up to God:
by this only, that which is born of God liveth, and is nourished.
This is that carcass to which the wise eagles gather; and see thou gatherest to no other,
and feedest on no other.
This is that hidden manna that cometh from heaven; that feedeth God`'s Gospel Israel.
The world hath a manna, but it perisheth; but this endureth forever:
for it is not of man, nor from man, but immortal, and from God;
hid from the knowledge of all the vain Christians in the world;
so that the Israel of God can say to the children of this world,
and that in truth and righteousness,
'`We have bread to eat that you know not of.`' For this manna wait daily,
that thou mayst be strengthened in thy wilderness travel to the land of eternal rest.

Wherefore, '`labour not for the bread that perisheth,`' that is,
the bread of man`'s inventing and making, which cometh from below, and profiteth not,
because it giveth not life eternal.
But labour thou, my dear friend, for the bread that never perisheth,
that endureth forever, and that giveth life eternal to all that feed upon it.
O cast thy care upon this Word, love it and dwell with it; wait daily upon it,
hear its voice only, and follow it;
for it bringeth the soul to the eternal habitation of rest and glory.
Yea, when all flesh shall wither, and the beauty thereof fade away, this Word,
and they that are grafted into it, shall abide forever.
O that this may be thy choice, and it shall be thy diadem, and thy eternal crown of glory!

These are the fervent desires, and these the daily prayers of my soul,
to the God of my salvation for thee; not only that nothing in thee may be lost,
besides the son of perdition; but that thou mayst cast off every weight and burden,
and that sin that doth so easily beset thee, that grieveth, boweth, and oppresseth thee,
under the heavy weight of which thou groanest and sighest,
that thy Redeemer would come from Zion to deliver thee.
Give not heed to the enemy, the false accuser,
who seeketh to devour that which is begotten of God in thee;
neither look upon thine own sins, burdens, or weaknesses; but lift up thy head,
and look to Jesus, the author of thy blessed visitation,
and wholly hunger and thirst after Him, the spiritual brazen serpent,
that healeth and relieveth all who in faith and full assurance look to him.
Want of looking to him, hearing and obeying him and having true faith in him,
is the cause both of all the presumption and despair that are at this day.
He did no mighty things of old in those places where they believed not.

O faint not, look not back, remember the holy ancients, the holy pilgrims of faith,
the royal generation of heaven! Heb. 11.
Thou believest in God,
believe also in him for the work`'s sake that he has already wrought in thee:
he will minister to thee, as he was ministered unto by his Father`'s angels,
in the hour of his abasement and great temptation.
Watch, and be faithful, and thou shalt be a noble witness for the Lord.

Once more let me expostulate with thee.
Wouldst thou overcome the enemies of thy soul`'s peace,
and enjoy the delightful presence of the Lord with thee?
Then keep nothing back; let nothing be withheld that he calleth for:
remember that Saul of old lost his kingdom, for keeping that alive,
which he should have slain; and thou knowest what befell Ananias and Sapphira outwardly.
But be thou like the poor widow of old,
that gave more into the treasury than all the rest,
because they reserved the greatest part to themselves; but she gave all she had.
O blessed are they that make no bargains for themselves; that have no reserves for self,
neither consult with flesh and blood, nor in any sense conform to the least ceremony,
which is born of them; but that submit their wills, in all things, to the Lord`'s,
that they may be made perfect through sufferings.

Read me in the mystery of life: I speak not of deserting,
or flinging away all outward substance; but that thy heart may reign above all visibles,
and make God its treasure, and never stick in any thing of this lower world,
or rest short of Christ, the eternal rest of all the seed of faith.

[.offset.centered]
__Here beginneth the narrative.__

The Lord brought us well to Wesel on the fifth-day after we left Herwerden,
having some service by the way.
At Wesel we had a good time with Dr. Schuler, and Rosendale,
and the woman we mentioned to thee;
but the tailor was shy and fearful of coming to us at the doctor`'s.

The next day, the 28th, we went towards Duysburg,
and visited the Schult or chief governor that night, whom we found at home;
he received us with much kindness.
His wife and sister, we fear, have been shaken in their good belief of our testimony,
since we were last there; some fowls of the air have devoured the seed that was sown.
O that sweet and tender frame, in which we left them the time before!
However, the entrance we had upon the spirit of the Schult, a little consolated us.
Hence we sent Maria Martha`'s friend a letter;
desiring him to let us have his answer the next night at Dusseldorf, enclosed to Neander,
when and where we might see him, either at Dusseldorf, Mulheim, or Duysburg;
and if it were possible, we would gladly visit the Countess of Bruck.

We got early to Dusseldorf next day, being the last day of the week:
but Neander was gone to Mulheim, in order to preach on the morrow;
so that we were disappointed of our intelligence.

Next morning the 30th, we went towards Cologne, and there arrived that evening.
The day after, we had a good opportunity with Van Dinando and Docemius,
at the house of the latter; and that afternoon took boat back for Dusseldorf;
where arriving next morning, we presently sent for Neander, who came to us,
and three more in company.
We had a blessed meeting with them, and with one of the three that came with him,
our souls were exceedingly affected.

The meeting done, they went away, but Neander returned.
And first, of our letter to Mulheim.
We found by him, as also at our return to Duysburg,
that Kuper was so far from endeavouring our visit to the Countess,
that he would not meet us himself, either at Dusseldorf, Mulheim, or Duysburg: nay,
it did not please him to send us an answer, much less any the least salutation.
I confess it grieved us now for Neander: the young man hath a zeal for God,
and there is a visitation upon him, my soul desireth that it may not be ineffectual:
but I have a great fear upon me.
For this I know certainly, from the Lord God that liveth forever,
and I have a cloud of witnesses to my brethren, that retirement and silence before God,
is the alone way for him to feel the heavenly gift to arise,
and come forth pure and unmixed.
This only can aright preach for God, pray to God, and beget people to God,
and nothing else.
But alas! his office in that family is quite another thing; namely,
to perform set duties at fixed times; pray, preach, and sing,
and that in the way of the world`'s appointments.
His very office is Babylonish, namely, a chaplain; for it is a popish invention.

In the good old times, godly Abraham who was a prince, and Joshua a great general,
and David a king, with many more,
instructed their families in the knowledge and fear of God:
but now people are too idle or too great to pray for themselves,
and so they worship God by proxy.
How can a minister of the Gospel be at the beck of any mortal living,
or give his soul and conscience to the time and appointment of another?
The thing in itself is utterly wrong,
and against the very nature and worship of the new and everlasting covenant.
You had better meet to read the Scriptures, the Book of Martyrs, etc.,
if you cannot sit and wait in silence upon the Lord,
till his angel move upon your hearts, than to uphold such a formal, limited,
and ceremonious worship.
This is not the way out of Babylon.
And I have a deep sense upon my soul, that if the young man strive,
beyond the talent God hath given him, to answer his office, and fill up his place,
and wait not for the pure and living word of God in his heart, to open his mouth,
but either studieth for his sermons, or speaketh his own words,
he will be utterly ruined.

Wherefore, dear friend, have a care thou art no snare to him, nor he to thee!
Man`'s works smother and stifle the true life of Christ.
What have you now to do, but to look to Jesus,
the author of the holy desires that are in you, who himself hath visited you.
Tempt not the Lord, provoke not God.
What should any man preach from, but Christ?
And what should he preach people to, but Christ in them, the hope of glory?
Consider, nothing feedeth that which is born of God, but that which cometh down from God,
even the bread of God, which is the Son of God, who giveth his life for the world.
Feel it, and feed on it; let none mock God, or grieve his Eternal Spirit,
who is come to seal them up from the mouth of man, who hath deceived them,
that Jesus the anointing may teach them and abide with them forever.

Be steadfast and immovable; and this will draw the young man nearer to the Lord,
and empty him of himself, and purge away mixtures;
and then you will all come to the Divine silence.
And when all flesh is silent before the Lord, then is it the Lord`'s time to speak,
and if you will hear, your souls shall live.
O! my soul is in great pain, that you may be all chastely preserved in that divine sense,
begotten in your hearts by the eternal Word of God, that abideth forever;
that nothing may ever be able to extinguish it.
But more especially that thou my dear friend, mayst be kept in faithfulness:
for the Lord is come very near to thee, and thou must begin the work;
the Lord God expecteth it at thy hand.
If one sheep break through, the rest will follow.
Wherefore watch; O watch! that thou mayst be strengthened and confirmed;
and strengthen all that is begotten of God in that family, by thy weighty, savoury,
and circumspect life.
O how is my soul affected with thy present condition!
It is the fervent supplication of my heart, that thou mayst,
through the daily obedience of the cross of Jesus,
conquer and shine as a bright and glorious star in the firmament of God`'s eternal kingdom.
So let it be, Lord Jesus!
Amen.

We tenderly, yet freely spoke our hearts to him, before we parted; which done,
in God`'s love we took our leave of him at Dusseldorf, and got that night to Duysburg,
being the third-day of the week.
We first visited Dr. Mastricht, a man of a good natural temper, but a rigid Calvinist.
I perceived by him, that they held a consultation about seeing us at Bruck;
but they all concluded, it was best to decline meeting with us, because of the Graef,
he being ready to fling our name in reproach upon them, in his displeasure;
and this would confirm him in his jealousies of them.
This might excuse the Countess, but by no means Kuper; and if I had any sense,
Mastricht was there with them upon design,
to frustrate the hopes we had conceived of meeting with her.
We, from that, descended to other things of weight, and in love and peace parted.

From his house we returned to our inn; and after supper we visited the Schult,
who with much civility and some tenderness received us.
His sister also came to us, and we had a good little meeting with them,
and our God was with us; and his pure and tender life appeared for our justification,
and pleaded our innocent cause in their consciences: and so we parted with them,
leaving our Master`'s peace amongst them.

The next day we came to Wesel, being the 3rd of the eighth month;
where we understood by Dr. Schuler,
that thy sister desired we would be so kind as to see her when we returned.
Upon that we went and visited her; she received us very kindly.
Thy brother-in-law`'s two sisters were present; we stayed with her at least two hours.
Many questions she put to me, which I was glad to have an opportunity of answering,
for it made way for a meeting.
She entreated us to come again if we stayed,
and told us our visit was very grateful to her: adding,
that because we passed her by the last time, she concluded with herself,
we had no hopes of her; with more to that effect.
From thence we went to Dr. Schuler`'s,
who freely offered us his house for a meeting next day: and indeed, the man is bold,
after his manner.

The next day about seven o`'clock I wrote a billet in French to thy sister,
to inform her of the meeting, to begin about eight: she came,
and her two sisters with her.
There were Rosendale, Colonel Copius and his wife, and about three or four more;
and to our great joy the Lord Almighty was with us,
and his holy power reached their hearts,
and the Doctor and Copius thereby confessed to our testimony.

The meeting lasted about four hours: being ended,
we took our leave of them in the spirit of Jesus, and so returned to our inn.
The tailor was all this while afraid of coming to our inn,
or to the Doctor`'s to the meeting: great fears have overtaken him,
and the poor man liveth but in a dry land.
After dinner we visited Copius and Rosendale;
and at Copius`'s we had a blessed broken meeting, he and his wife,
Rosendale and his wife, with another woman, wife to one Dr. Willick`'s brother,
being present; they were extremely affected and overcome by the power of the Lord,
it was like one of our Herwerden meetings;
indeed much tenderness was upon all their spirits.

This done, and having left books both there and with thy sister,
we left Wesel with hearts full of joy and peace: and let me say this,
that more kindness and openness, we have scarcely found in all our travels.
O that this blessed sense may dwell with them!
A seed there is in that place, that God will gather; yea,
a noble people he will find out;
and I doubt not but there will be a good meeting of Friends in that city,
before many years go about: my love is great to that place.
O how good is our dear Lord to us, who helpeth our infirmities,
and carrieth through all opposition, and feedeth us with his Divine presence,
in which is life!
His candle hath hitherto rested on our tabernacle,
and he hath made us glad in his own salvation: eternal glory be to his excellent name.

We immediately took a post-car and came next day, about two in the afternoon, to Cleve;
where we had a very precious meeting at an honest procurator`'s house,
who received us with much love: four or five more were present, all grave and tender:
our hearts were greatly affected with their love and simplicity.
We also visited the Lady Hubner, who was kind to us.

The following morning the 6th, we set out for Nimeguen,
and thence immediately to Utrecht, where we arrived that night;
and took the night boat for Amsterdam;
because of a pressure upon my spirit to be next day at the meeting, and the rather,
having intimated as much from Cologne.

We arrived in the morning at Amsterdam, where we found our dear friends generally well,
the city much alarmed, and great curiosity in some, and desires in others,
to come to the meeting.
We had a very great meeting, and many people of note resorted:
God`'s Gospel bell was rung, the great day of the great God sounded,
and the dead were raised, so that much tenderness appeared in several.
O blessed be the name of the Lord, whose work and testimony prosper!

The next day was spent in divers affairs relating to the Truth.
The day following, the 9th, we had a meeting with Galenus Abrahams,
the great father of the Socinian Menists in these parts,
accompanied by several preachers, and others of his congregation:
divers of our friends were also present.
It continued about five hours; he affirmed in opposition to us,
that there was no Christian church, ministry, or commission apostolical now in the world;
but the Lord assisted us with his wisdom and strength, to confound his attempts.

[.offset.centered]
__Here endeth the narrative.__

I intend a visit at the Hague to the Lady Overkirk, sister of the Somerdykes,
and some others who have sober characters of Truth and Friends; and thence to Rotterdam,
where I have much to do, both with respect to meetings and the press.

Thus my dear friend, have I given thee a tedious narrative,
yet I hope not altogether unpleasant.
Perhaps the brevity of my letters hereafter may best apologize for the length of this:
however I consider two things; one is, that thou hast time enough,
one time or other to look over it; and next,
that I have plentifully answered thy requests,
and demonstrated I have not forgotten thee.

Dear friend! let us live and remember one another, now absent,
in that Divine sense in which the Lord God dissolved our spirits when together.
O the unity of this faith, the purity of this love,
and the bond of this peace The Lord Jesus be with thy spirit,
and keep thee in this the hour of thy temptation,
that thou mayst come forth as gold seven times tried:
so shall thy testimony shine for the God that hath called thee,
and he will reward thee with honour, glory, and eternal life.
Amen.

Thus saith the Lord, I remember thee, the kindness of thy youth,
the love of thine espousals, when thou wentest after me in the wilderness,
in a land that was not sown.`' Dear friend, consider this.
Yet again: "`The way of the just is uprightness; thou, most upright,
dost weigh the paths of the just.
Yea, in the way of thy judgments, O Lord, have we waited for thee;
the desire of our soul is to thy name, and to the remembrance of thee.
With my soul have I desired thee in the night; yea,
with my spirit within me will I seek thee early; for when thy judgments are in the earth,
the inhabitants of the world will learn righteousness.
Lord, thou wilt ordain peace for us; for thou also hast wrought all our works in us.
O Lord our God, other lords besides thee have had dominion over us;
but by thee only will we make mention of thy name.
Lord, in trouble have they visited thee;
they poured out a prayer when thy chastening was upon them.
Thy dead men shall live, together with my dead body shall they arise.
Awake and sing, ye that dwell in the dust, for thy dew is as the dew of herbs,
and the earth shall cast out the dead.
Come my people, enter thou into thy chambers, and shut thy doors about thee;
hide thyself as it were for a little moment, until the indignation be overpast.
For, behold,
the Lord cometh out of his place to punish the inhabitants of the earth for their iniquities;
the earth also shall disclose her blood, and shall no more cover her slain.`"

So come, dear Lord Jesus, who was dead, and is alive, and liveth forever.
Amen.
Very dearly farewell.

[.signed-section-closing]
Thy friend, that faithfully travaileth for thy redemption,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Amsterdam, the 10th of the Eighth month, 1677.

--
