== Chapter XXIII.

1684+++.+++ It has been already mentioned that William Penn, in the autumn of 1682,
paid a visit to Lord Baltimore,
with a view of effecting a settlement of their mutual boundary,
but that the business was postponed to the ensuing spring.
The negotiation was accordingly renewed in the following year,
but without any decisive result.

Although this question continued for many years to be a subject
of controversy between the proprietaries of Maryland and Pennsylvania,
and was not finally adjusted until long after the death of William Penn;
it is not my design to investigate the subject any further than appears requisite,
in order to vindicate the character of the illustrious founder of Pennsylvania.
This vindication appears indispensable in a memoir of his life,
particularly as some recent authors have indulged in very acrimonious
reflections upon the part which he acted in this protracted litigation.

When the charters for Maryland and Pennsylvania were granted,
there were no correct maps of those countries in existence.
The former, if not the latter, appears to have been traced from Smith`'s map,
contained in his History of Virginia.
In that map the latitude of forty degrees appears near where
the division line between the provinces was eventually settled.
In Lord Baltimore`'s patent,
the northern boundary is described as lying on the bay of Delaware,
under the fortieth degree of north latitude.
Hence it is manifest that the province of Maryland was not understood,
when the patent was granted, to bound on the river Delaware, but merely on the bay.
The two descriptions being incompatible, the true construction would necessarily be,
that the grant should include what was intended to be granted,
and that intentions should be inferred from the part
of the description which was best understood.
Now the relative situation of the Delaware and Chesapeake bays was tolerably
well known when the patent of Lord Baltimore was granted,
though the latitudes were not correctly ascertained
until William Penn`'s charter was obtained.

But besides the controversy respecting the northern boundary of Maryland,
there was another in regard to the eastern one.
Lord Baltimore claimed the lands on the Delaware bay,
which were embraced in the grant of the Duke of York.
This claim was not then new,
and the tract would have been within the limits of his patent,
in case it had then belonged to the British crown and remained unoccupied.
For the grant to Lord Baltimore was expressly confined to land hitherto uncultivated.
It does not appear to be now certainly known at what time the first Europeans obtained
possession of the land on the western shore of the Delaware river and bay,
but it is clearly ascertained that the three lower counties,
now composing the state of Delaware,
never were under the actual jurisdiction of the governor of Maryland.
The land was claimed by Lord Baltimore as early as 1659,
but the envoy of the New-Netherlands firmly maintained the right of the Dutch,
pleading purchase and colonization before the Maryland patent was granted.
The facts upon which this argument was founded, were not denied.
Still the claim was continued, and upon the restoration of King Charles,
it was vigorously renewed.
But the claim was resisted by the Dutch authorities; until the conquest, in 1664,
subjected the Dutch possessions in North America to the dominion of Great Britain.
Upon that event, this tract of land came into possession of the Duke of York,
from whom William Penn obtained his grant.
Had this land been then considered as a part of Maryland,
the eighteen years which elapsed between the conquest and the grant to William Penn,
afforded an opportunity for Lord Baltimore to establish his claim.
The agents of Lord Baltimore as well as the duke,
were heard before the charter for Pennsylvania,
or the deeds for the lower counties were obtained,
and it is not reasonable to suppose that the territory granted to William Penn was understood
to be either wholly or in part comprehended within the patent of Lord Baltimore.
The description of the northern boundary in the Maryland
patent is not quite free from ambiguity;
as the fortieth degree may signify the beginning or the end of that degree;
but in the charter for Pennsylvania,
the southern boundary is expressly placed at the beginning of the fortieth degree,
or in latitude thirty-nine.
This affords testimony nearly if not quite conclusive,
that the legal authorities who were consulted respecting the charter of William Penn,
considered the beginning and not the end of the fortieth degree as the boundary of Maryland.
It does not appear that previous to the arrival of William Penn,
any part of the disputed territory was ever occupied under Maryland titles,
except by a small colony on the Schuylkill, which was expelled by the Dutch in 1642.

Although the tract in question included a large portion of valuable land;
yet William Penn was more anxious to secure to his
province the benefit of an outlet upon the Chesapeake,
than to obtain for himself or his heirs the profits arising from the sale of the lands.
"`The whole history of these transactions,`" says a modern writer,
"`shows conclusively the fairness and candour,
the moderation and firmness of William Penn,
the illustrious and irreproachable founder of Pennsylvania,
and the justice of the claims of his posterity;
and rescue his name from the imputation of injustice.`"

Being solicitous for the religious advancement,
as well as the temporal prosperity of the people under his charge,
and more especially those of his own Society, he wrote in 1684,
an epistle addressed to the people of God called Quakers,
in Pennsylvania and the territories thereto belonging;
which manifests his tender and paternal regard for the inhabitants of his American plantations.
It is as follows, viz:

Dear friends,

The salutation of my love is unto you who make a profession
of the blessed way of Truth in the inward parts,
desiring both night and day,
with tender and fervent supplication to the God of the light
that hath sprung upon us in a living and powerful visitation,
that we may all answer the love and mercy of the Lord so plenteously manifested to us.

Friends, it is upon me, and long hath been, from the God of truth and righteousness,
to communicate to you a short word of counsel and advice.
God hath brought us hither, and we are yet among the living.
He hath a work for us to do here, though the spiteful and envious will not believe us.
O! that we may be faithful to the measure of grace received,
that the evil-minded may be disappointed.
Friends, keep in the sense of that which first visited you and kept you,
and he that was with you to bless you in your native country,
will be with you and bless you and yours,
and make you a blessing to them that you are come among, who know him not,
in this wilderness also.
The earth is the Lord`'s, and his presence fills it, and his power upholds it,
and it is a precious thing to enjoy and use it in the sense and feeling of the same;
truly this honour have all the saints, to whom he will give it for a quiet habitation.
Have a care of cumber and the love and care of the world.
It is the temptation that lieth nearest to those who are redeemed from looseness,
or not addicted to it.
The moon, the figure of the changeable world, is under the foot of the true woman,
whose seed we ought to approve ourselves.
God hath ordained it for a footstool, and we must not make a throne of it,
nor doth it become them who seek heavenly places in Christ Jesus.
Show forth a blessed example, for the Lord`'s sake; and truly,
blessed is that man and woman who in the invisible
power rule their affections about the visible things,
and who use the world as true travellers and pilgrims, whose home is not here below;
such do not extort, grind or oppress their neighbours in their dealings,
but are content with moderate gain, looking to the blessing that follows;
knowing right well, that they who over-value and overcare,
fall into divers snares and sorrows, that hurt and pierce the soul`'s peace.
And in like manner, dear friends, have a care of looseness,
for it becometh us to be watchful, and to gird up the loins of our minds, and be sober,
and hope to the end.
Are we from under outward sufferings and trials that we once knew,
and that carry an humiliation with them upon the spirits of people?
Let us be more circumspect,
that we forget not the Lord nor his tender mercies towards us; for he is God,
and he can find us out, and trouble, and vex,
and plague the disobedient and careless here, as well as in other lands.
Be zealous therefore for the Lord, for he is a jealous God,
and especially over those that have betrothed themselves
unto him by the profession of his holy Truth:
yea, he will be avenged of the hypocrite and rebellious, but the obedient he will bless,
which my soul prayeth you may be,
that so I may never have an occasion to exercise
any other power than that of love and brotherly-kindness.

And dear friends, remember who it was that said to his children and followers,
'`Ye are brethren:`' and have a care of unnaturalness in the profession of the truth.
To be without natural affection to one another in the truth, is a mark of apostacy;
wherefore love one another, and help and assist, and comfort one another.
This was the new and living commandment of our blessed Lord and Master,
which if you keep, then can you not fall out, backbite, slander, go to law,
or hate one another, in the sight of the world, and that for the things that perish;
verily, if any do these things, the wrath of God will overtake them.

O, friends! let us call to mind the day that hath dawned upon us,
and what manner of persons we ought to be.
Besides, you know that the eyes of the inhabitants of the lands,
and those of neighbouring countries, yea,
the people of remote regions are upon us and our doings; how we live, how we rule,
and how we obey, and joy would it be to some to see us halt,
hear evil tidings of our proceedings,
as it would be an heavy and an unspeakable grief to those that wish well to our Zion.
Friends, God requireth great watchfulness from you,
especially elders and teachers in the church of Christ,
that they watch over their own and others`' families, that whatever appears in any,
contrary to the testimony and mind of Truth, may be brought to judgment and disowned,
that the camp of the Lord may be kept clean of the uncircumcised who resist the Spirit.

My friends, remember that the Lord hath brought you upon the stage,
he hath now tried you with liberty, yea, and with power too;
he hath now put precious opportunities into your hands; have a care of a perverse spirit,
and do not provoke the Lord by doing those things,
by which the inhabitants of the land grieved his spirit, that were before you;
but sanctify God, the living God in your hearts,
that his blessings may fall and rest as the dew of heaven upon you and your offspring;
then shall it be seen by the nations, that there is no enchantment against Jacob,
nor divination against Israel, but your tents shall be goodly,
and your dwellings glorious:
which is the daily humble supplication of my soul to my God and your God,
and to my Father and your Father; who am, with unfeigned love, in that lasting relation,

Your tender, faithful friend and brother,

William Penn.

After residing nearly two years in Pennsylvania,
and adjusting the concerns of his government,
as well as his numerous avocations and the materials with which he had to work,
would admit, he thought it best to revisit his native land.

Persecution was still raging in England.
King Charles having concentrated in his own hands nearly all the powers of government;
the dissenters in general were subjected to a rigorous persecution,
in which Friends as usual bore the greatest share.
By an account presented, in the beginning of the subsequent reign,
to the king and both houses of parliament, it appears, there were about this time,
nearly fifteen hundred members of this Society imprisoned,
some in Wales and the rest in England, under the charge of violating the laws of the day.
The pretexts for the incarceration of these unoffending people,
were chiefly the obsolete acts of Queen Elizabeth`'s time,
now revived and rigorously executed;
together with the persecuting laws enacted soon after the restoration.
But these laws, oppressive as they were in their nature,
were in many instances rendered still more intolerable by the manner of their execution.
Numerous families, in comfortable circumstances,
were reduced to poverty by the ruinous fines imposed upon them.
In some cases,
the officers seized upon every article of value which
they could find within doors or without.

As the councils of the king were supposed to be greatly
influenced by the advice of his brother,
the presumptive heir to the crown,
and William Penn had probably more place with that prince
than any other member of the Society to which he belonged;
these circumstances presented an inducement for his
return at this time to his native land.

The dispute with Lord Baltimore, which, from the trial already made,
was evidently not to be settled without the intervention of the authorities at home,
formed another reason.
It also appears that numerous efforts had been made,
by persons impelled by interest or envy,
to bring his character and government into disgrace,
in the view of those who held the reins at home.
These efforts it was judged requisite to counteract,
and that could be most effectually done in person.
Nor are we to suppose that the society of his own family,
with an amiable and accomplished wife at its head,
was destitute of attractions to such a mind as William Penn`'s. Indeed,
we can hardly believe that any thing less than a sense of
imperious necessity could induce him to reside in America,
while his wife and children remained in his native land.
And it is not probable that the accommodations,
which custom had rendered essential to their comfort,
could then be procured by any means in the newly settled province of Pennsylvania.

Having made the necessary dispositions relative to
the administration of the government during his absence,
strictly charging the officers entrusted with the principal authority,
to do justice to all of all degrees, without delay, fear or regard,
he repaired on board the vessel which was to convey him '`to the land of his nativity.
But such was the activity of his mind and his zeal for the religious
preservation and advancement of his friends in Pennsylvania,
that he wrote from on board the vessel the following epistle; viz.

For Thomas Lloyd, J. Claypoole, J. Simcock, Charles Taylor and J. Harrison,
to be communicated in meetings in Pennsylvania, etc, among Friends.

Dear friends,

My love and my life is to you and with you; and no water can quench it,
nor distance wear it out, or bring it to an end.
I have been with you, cared over you, and served you with unfeigned love;
and you are beloved of me, and near to me, beyond utterance.
I bless you, in the name and power of the Lord;
and my God bless you with his righteousness, peace and plenty, all the land over.
Oh, that you would eye him in all, through all, and above all the works of your hands;
and let it be your first care, how you may glorify God in your undertakings.
For to a blessed end are you brought hither;
and if you see and keep in the sense of that Providence, your coming,
staying and improving will be sanctified; but if any forget God,
and call not upon his name in truth, he will pour out his plagues upon them;
and they shall know who it is that judgeth the children of men.

Now you are come to a quiet land, provoke not the Lord to trouble it.
And as liberty and authority are with you, and in your hands,
let the government be upon His shoulders, in all your spirits; that you may rule for him,
under whom the princes of this world will one day
esteem it their honour to govern and serve,
in their places.
I cannot but say, when these things come mightily upon my mind,
as the apostle did of old, '`What manner of persons ought we to be,
in all holy conversation and godliness?
Truly, the name and honour of the Lord are deeply concerned in you,
as to the discharge of yourselves, in your present stations; many eyes being upon you;
and remember, that as we have been belied about disowning the true religion,
so of all government; to behold us exemplary and Christian in the use of that,
will not only stop our enemies,
but minister conviction to many on that account prejudiced.
Oh, that you may see and know that service, and do it for the Lord in this your day.

And thou, Philadelphia, the virgin settlement of this province,
named before thou wert born, what love, what care, what service,
and what travail has there been,
to bring thee forth and preserve thee from such as would abuse and defile thee.

Oh, that thou mayst be kept from the evil that would overwhelm thee; that,
faithful to the God of thy mercies,
in the life of righteousness thou mayst be preserved to the end.
My soul prays to God for thee, that thou mayst stand in the day of trial,
that thy children may be blessed of the Lord,
and thy people saved by his power;--my love to thee has been great,
and the remembrance of thee affects mine heart and mine eye!--the God
of eternal strength keep and preserve thee to his glory and thy peace.

So, dear friends, my love again salutes you all, wishing that grace, mercy and peace,
with all temporal blessings, may abound richly among you;--so says, so prays,
your friend and lover in the Truth,

William Penn.

From on board the ketch Endeavour, the Sixth month, 1684.

Oldmixon, a contemporary author, who appears to have derived his information in part,
at least, from William Penn,
states that Philadelphia contained at that time three hundred houses,
and about two thousand five hundred inhabitants.
The Indians within the province were estimated at six thousand.
William Penn is said to have made a league of amity
with nineteen Indian nations or tribes,
ten of which are supposed to have resided within the limits of the province.
It is characteristic of the benevolence of the founder of Pennsylvania,
that the friendship engaged thus was on behalf of all the English in America.
The intercourse between him and these native sons of the forest, was not,
as already intimated, one of empty profession;
for he had expended several thousand pounds in his efforts to instruct,
support and oblige them.
This benevolent treatment procured for his name and character,
a veneration in the minds of these people,
which the lapse of a century and a half has not obliterated.
And it is a subject of gratulation,
that the friendship thus established between William
Penn and the native inhabitants of the land,
has been maintained between their descendants and
the Society of Friends from that time to this.

He sailed on the 12th of sixth month,
(now eighth) and after a voyage of about seven weeks, arrived safely in England.
Landing within seven miles of his own house,
he soon had the satisfaction to find his wife and family in good health,
for which and his own preservation and exemption from sickness,
amidst the hardships and dangers of his American excursion,
he did not fail to express his gratitude to the Father and Fountain of all good.

We find that he obtained, soon after his arrival,
an interview with the king and Duke of York, by whom and the nobility,
he was respectfully treated;
and he was encouraged to hope that way would be made in their hearts,
by which he should be enabled to lighten the burdens of his suffering friends,
as well as to promote his American interests.
In regard to his friends, nothing appears to have been effected during the existing reign.

A letter from Stephen Crisp, received after his arrival in England,
informed him of a number of reports injurious to his character,
which had been put in circulation.
One of these indicated that he had dishonoured his profession
by giving his sanction to some military operations.
This drew from him a letter in return, in which he repelled the charges adduced.
In regard to the military one, he observed that he knew of no act of hostility.
There was at New-Castle, an old timber house, above the sessions chamber,
standing upon a green, on which lay seven old cannon,
the property of the government of New-York, some on the ground,
and others on broken carriages; but there was neither a military man,
nor powder nor ball belonging to them.
Whether the people of New-Castle had placed them under enclosure, since he left them,
he could not tell; but he was sure that while he was there,
no soldier or militia-man was seen.
There was no one who had any military commission from him;
and no law existed to authorize the issuing of one.

The other charges were answered in a manner which
sufficiently demonstrated their frivolous character.

We have here a sample of the spirit with which William Penn was obliged to contend,
in consequence of the eminence of his station;
and are fully admonished of the sacrifice of personal repose,
at which a conspicuous situation in the world, must be purchased.
If any man, in such situation, could escape the shafts of envy,
William Penn might reasonably have expected to be the man.
Whatever suavity of manners could be superinduced by the best education,
and by intercourse with the world, he had unquestionably acquired,
before he became united with the Society of Friends.
And although the principles of that Society forbade a compliance
with the manners and maxims of the fashionable world,
they had no tendency to diminish attention to genuine politeness.
On the other hand, while they stripped off the tinsel,
they substituted the essence of true civility.
George Fox himself, as William Penn, from an intimate acquaintance with him, asserts,
was "`civil beyond all forms of breeding;`" and the
latter has shown in various parts of his works,
that he did not consider his religion as dispensing with
any part of those attentions to the feelings of others,
in which true politeness consists.
While these exterior characteristics were a security against minor offences,
the integrity of his principles, and the remarkable disinterestedness of his character,
were a sufficient guarantee against graver causes of complaint.
It was not likely that a man who treated the untutored
Indians with such distinguished justice and humanity,
would be guilty of injustice to his own countrymen.
Yet while he was spending the prime of his life and the income of an ample estate,
in constant efforts to improve the condition of his contemporaries,
and to lay a foundation for the melioration of ages to come,
we find the tongue of slander was busily employed in defaming his character,
and counteracting his endeavours.
So true is the observation of the poet--Envy will merit, as its shade, pursue,
and like the shadow, proves the substance true.
