== Chapter XXIV.

One of the objects which William Penn had in view, in returning to England,
was the adjustment of the dispute with Lord Baltimore.
The history of that controversy being given in a
preceding chapter need not be repeated here.
In regard to his friends,
although the king does not appear to have had any particular antipathy to the Society,
or to have delighted in cruelty,
yet his indolent habits and temporizing policy prevented even the energy
and zeal of William Penn from procuring for them any effectual relief.

It was not long however till the reins of government fell into other hands.
For on the 2nd of the twelfth month, 1684-5,
the king was suddenly seized with an apoplexy, under which he continued for some hours,
in a state of insensibility.
He afterwards revived, and remained in a suffering condition, until the 6th of the month,
when he expired.
Little as he thought of serious things when in health,
we find that the pains of expiring nature and the prospect of approaching dissolution,
humbled his mind and made him feel his dependent state.
He was ready not only to pray for pardon on account of his sins,
but to crave forgiveness of such as he had injured.
A few hours after his death, the Duke of York was proclaimed king,
by the name of James II.

The accession of James, who openly professed the Roman Catholic religion,
and went with his queen shortly after he mounted the throne, publicly to mass,
excited the fears of the people.
The arbitrary measures of the deceased king were
chiefly attributed to the counsel of James;
and the persecutions of Mary`'s reign,
the last British sovereign who professed the popish religion,
were identified with the religion itself.
Hence, the arbitrary measures and fiery persecutions of Mary`'s days,
were arrayed before the affrighted eyes of the British nation.
James had frequently protested in the hearing of William Penn,
that he was principled in favour of liberty of conscience,
and as the prince had been considered a man of unimpeachable veracity,
there was certainly no absurdity in believing him.
The integrity of William Penn`'s religion,
would not permit him to take advantage of what he considered an unfounded apprehension,
and gratitude to the reigning monarch for personal favours, led him,
as far as his influence extended, to compose rather than to augment,
the prevailing agitation.
In a letter to Thomas Lloyd, president of the Provincial council,
written soon after James`' accession,
he expressed a caution against any indecent reflections on the government,
on account of the open profession which the king was making.
Considering freedom of conscience as an unalienable right,
he was as ready to allow it to the king as to his subjects;
and was no more disposed to make a concurrence in religious principles,
the reason of his allegiance to the former, than of civil liberty to the latter.
But while he used the freedom to tell the king that
he approved the open avowal of his own opinions,
he took care to remind him of the religious rights of others,
and to express a hope that Friends would be permitted
to enjoy the unmolested exercise of their religion.

Being desirous of improving the influence which he possessed with the king,
to the advantage of his suffering friends, he took lodgings at Kensington,
a village two miles west of London.
He appears to have made it his business to serve his friends;
and as every man is a friend to him that giveth gifts,
he soon found the number of his very great.
His house and gates were daily thronged with clients and suppliants
desiring him to present their addresses to the king.
According to Gerard Croese,
there were sometimes upwards of two hundred of these applicants in attendance.
But instead of becoming impatient with their importunity,
he treated them with the utmost kindness,
and promoted their desires with promptitude and cheerfulness.
Instead of seeking emolument from these incessant labours,
he often defrayed out of his own funds the expense,
unavoidably attendant upon the preparation of the
documents which passed through his hands.
Yet, numerous as were the applications for the employment of his interest at court,
he does not appear to have waited for an application when
he knew of cases in which his interference could be of use.
Nor were his efforts confined to those in which the
members of his own religious society were concerned.

It has been already mentioned that there were at the time of king
Charles`'s death nearly fifteen hundred Friends confined in prison.
An address was presented to the new king, about a month after his accession,
soliciting his interposition on their behalf.
A parliament being convened in the early part of this year,
a particular statement of these sufferings was drawn up by Friends of London,
addressed to the king and both houses of parliament;
in which they portrayed in strong but natural colours
the multiplied hardships to which they were exposed,
for no other offence than a care to preserve a conscience void of offence;
and solicited a repeal of those iniquitous laws.

Whether an opportunity was afforded of laying this address before parliament,
is uncertain.
It is, however, known that no redress was then procured.^
footnote:[William Sewel quotes a proclamation of king James, dated 18th of April, 1685,
which he represents as putting a stop to persecution;
but it appears to me that he must have been mistaken,
for the proclamation evidently relates to a totally different class of sufferers,
though the laws on which they were prosecuted,
were probably the same as those of which Friends had so much reason to complain.]
The news of the Duke of Monmouth`'s arrival,
with a view of disputing the crown with the reigning monarch,
soon put an end to the deliberations of that body.

The history of Monmouth`'s invasion,
has little or no connection with the biography of William Penn,
except as he was indirectly involved in its consequences.
It is well known that after the defeat of the Duke,
the military commanders Feversham and Kirk,
manifested a very great share of cruelty towards his unfortunate accomplices;
and that Chief-justice Jeffreys astonished and disgusted the nation by the severity
with which he punished those who were charged with participating in the rebellion.
So great indeed was the terror infused into the juries by the menaces of the judge,
that very little evidence of guilt was required to ensure conviction;
and so unrelenting the rigour with which trifling offences were visited,
that some were executed for having furnished hay or victuals to Monmouth`'s soldiers.
The sufferers being mostly persons in the humbler walks of life,
could not be objects of jealousy with the court.
Hence the severity with which they were treated, created the greater odium.
Although these barbarities were originally inflicted
by the military and judicial organs of the government,
the king turned the odium upon himself,
by rewarding the inhumanity of Jeffreys with a peerage, and the office of chancellor.
The measures which followed,
were generally considered as clear indications of
a determination on the part of the king,
to govern the nation without regard to the restraints of law;
and the proceedings in favour of the Romish religion,
awakened anew the dread of popery and arbitrary power,
which the declaration of James upon his accession to the crown, had contributed to allay.

There is no reason to believe that any of these offensive
proceedings were countenanced by William Penn;
for every part of his conduct, as far as known, leads to the opposite conclusion,
yet his intimacy at court, and his supposed influence with the king,
turned upon him no inconsiderable share of the odium which
attended the religion of the king and the measures of government.
But in this case, as usually happens, the tongue of slander defeated its own purposes,
at least with posterity,
by loading his character with charges too inconsistent
with its general tenor to admit of belief.
Not satisfied with imputing to him a participation in the political errors of James,
over which he certainly had no control, they represented him to be a papist or Jesuit,
or engaged in a correspondence with the Jesuits at Rome.
He was even said to have been bred at St. Omers,
and to have received a priest`'s orders at Rome.
As it was obvious he was married, which the Romish priests were not permitted to be,
it was asserted that he had obtained a dispensation from the pope for that purpose.
Among the means which were used to fix upon him the charge of popery,
was a copy of some verses, published soon after the death of Charles,
signed with the initials of his name.
These verses, condoling the death of the late king,
and gratulating the accession of James,
were sufficiently marked with flattery and popish predilections,
to render the author odious in the view of an excited populace.
This production, as was probably intended, was attributed to him.
To disabuse the credulous public,
and satisfy his friends that the imputation was erroneous, he issued the following paper.

To my esteemed friends, called Quakers,
on occasion of two copies of verses printed and subscribed W. P.

Dear friends,

I have written this for your satisfaction, and yet not for yours, as you well say,
but to inform those many that importune you on my account, asking,
if I was the author of the condoling and congratulating
verses on the late and present king;
printed (say they) in my name: concluding if I were the author,
I must needs have turned papist, flatterer, and what they please.

Others, I perceive, without this help, as well as without truth or modesty,
stick not to report me a declared papist, and that I openly go to mass.

Now though it looks idle in any to wonder I should be a papist at this time of day,
who have been thought, and upon just as good grounds, a Jesuit so many years,
yet because they have no better evidence,
a man would wonder why they should be so believing, but that we lamentably see,
men are apter to be injurious than just.
In the mean while I have a fine time of it, to be reported a papist on one hand,
and presented and prosecuted as a disaffected person on the other hand;
but I know myself, and the world too well, to be troubled at this, and worse,
if that can be: it is enough for me it is false.

For the verses, if it be considered,
the two letters W. P. may begin five hundred names besides mine;
and I that pretend not to poetry at any time, should hardly have done it then,
when I must needs look to have such sad company,
as the dull flattery of all the suburbs of the town.

But that I did not write them, the stuff itself shows,
and they must be bereaved of sense as well as charity, that can think it:
for to own myself a Quaker, and jeer the profession:
to use their phrases and profane them: to promise as Quakers to live peaceably,
and yet engage to be no more such: to make ourselves loyal in one stanza,
and ask pardon for not being so in another: be now a mistaken and wilful rout,
and presently the loving and loyal friends of Charles and James,
make up a jar and a nonsense that I have not been used to be guilty of in prose;
and whenever I turn such a penny-poet, let such confusion be my judgment: however,
it would look rude to be angry at them;
for certainly they put a mighty compliment upon my name,
that thought two letters of it would make their drug sell:
and because I am so known a friend to property,
to the unknown hawker-wit that writ them I leave them,
with the credit of all the fine and foolish fancy they are laboured with:
contenting myself against all defamations that I have this
defence of my religion and conduct in my conclusion;

First, That the Grace of God within me, and the Scriptures without me,
are the foundation and declaration of my faith and religion,
and let any man get better if he can.

Secondly, That the profession I make of this religion, is in the same way and manner,
that I have used for almost these eighteen years last past.

Thirdly, That my civil conduct, I humbly bless my God, has been with peace on earth,
and good will to all men, from the king on the throne, to the beggar on the dunghill.

I have ever loved England, and moderation to all parties in it, and long seen,
and foreseen the consequences of the want of it.
I would yet heartily wish it might take place, and persuasion that of persecution,
that we might not grow barbarous for Christianity,
nor abuse and undo one another for God`'s sake.

These have been, these are, and with God`'s strength shall be,
through all the crooked and uneven paths of time, the principles and practice of,

Your ancient and constant friend,

William Penn.

Worminghurst-place, the last of the Second month, called April, 1685.

P+++.+++ S. If this will not serve and satisfy the mistaken,
for the malicious I fear are past cure, let them but prove the report upon any body,
and I will yet, as late in the day as it looks for such work,
effectually convince them with the judgment of the law,
that ought to be every honest man`'s shield.

William Penn.

The charge of his being at least popishly inclined, continued to be entertained;
and some persons in the higher ranks appear to have given credit to it.
Among this class was Dr. Tillotson, afterwards archbishop of Canterbury,
who having imbibed a suspicion of him dropped some expressions,
which were afterwards reported to his disadvantage.
This coming to the ears of William Penn, he wrote to the doctor on the subject;
a correspondence followed, which terminated in a full conviction,
in the mind of the latter, that the suspicion was groundless.
The correspondence is subjoined.

William Penn to Dr. Tillotson.

Worthy friend,

Being often told that Dr. Tillotson should suspect me, and so report me, a papist,
I think a Jesuit, and being closely pressed, I take the liberty to ask thee,
if any such reflection fell from thee: if it did,
I am sorry one I esteemed ever the first of his robe, should so undeservedly stain me,
for so I call it; and if the story be false,
I am sorry they should abuse Dr. Tillotson as well as myself without a cause.
I add no more, but that I abhor two principles in religion, and pity them that own them.
The first is, obedience upon authority without conviction; and the other,
destroying them that differ from me for God`'s sake.
Such a religion is without judgment, though not without teeth: union is best, if right;
else charity: and as Hooker said, "`The time will come,
when a few words spoken with meekness, and humility and love,
shall be more acceptable than volumes of controversies;`" which commonly destroy charity,
the very best part of true religion: I mean not a charity that can change with all,
but bear all, as I can Dr. Tillotson in what he dissents from me,
and in this reflection too, if said, which is not yet believed by,

Thy Christian true friend,

William Penn.

Charing-cross, 22nd of the Eleventh month, 1685-6.

Dr. Tillotson to William Penn.

Jan.
26, 1685.

Honoured sir,

The demand of your letter is very just and reasonable, and the manner of it very kind,
therefore in answer to it, be pleased to take the following account.
The last time you did me the favour to see me at my house, I did,
according to the freedom I always use, where I profess any friendship,
acquaint you with something I had heard of a correspondence you held with some at Rome,
and particularly with some of the Jesuits there.
At which you seemed a little surprised, and after some general discourse about it,
you said, you would call on me some other time, and speak further of it:
since that time I never saw you, but by accident and in passage,
where I thought you always declined me, particularly at Sir William Jones`'s chamber,
which was the last time, I think, I saw you; upon which occasion I took notice to him,
of your strangeness to me, and told him what I thought might be the reason of it,
and that I was sorry for it, because I had a particular esteem of your parts and temper.
The same, I believe, I have said to some others,
but to whom I do not so particularly remember.

Since your going to Pennsylvania, I never thought more of it, till lately,
being in some company, one of them pressed me to declare,
whether I had not heard something of you, which had satisfied me that you were a Papist?
I answered, No, by no means.
I told him what I had heard, and what I said to you,
and of the strangeness that ensued upon it; but that this never went further with me,
than to make me suspect there was more in that report which I had heard,
than I was at first willing to believe; and that if any made more of it,
I should look upon them as very injurious both to Mr. Penn and myself.

This is the truth of that matter,
and whenever you will please to satisfy me that my suspicion
of the truth of that report I had heard was groundless,
I will heartily beg your pardon for it.
I do fully concur with you in the abhorrence of the two principles you mention,
and in your approbation of that excellent saying of Mr. Hooker`'s,
for which I shall ever highly esteem him.
I have endeavoured to make it one of the governing principles of my life,
never to abate any thing of humanity or charity,
to any man for his difference from me in opinion,
and particularly to those of your persuasion, as several of them have had experience.
I have been ready upon all occasions to do all offices of kindness,
being truly sorry to see them so hardly used; and though I thought them mistaken,
yet in the main I believed them to be very honest.
I thank you for your letter, and have a just esteem of the Christian temper of it,
and rest,

Your faithful friend,

Jo. Tillotson.

William Penn to Dr. Tillotson.

Worthy friend,

Having a much less opinion of my own memory, than of Dr. Tillotson`'s truth,
I will allow the fact, though not the jealousy.

For besides that I cannot look strangely where I am well used,
I have ever treated the name of Dr. Tillotson with another regard.
I might be grave, and full of my own business;
I was also then disappointed by the doctor`'s; but my nature is not harsh,
my education less, and my principle least of all.
It was the opinion I have had of the doctor`'s moderation, simplicity and integrity,
rather than his parts, or post, that always made me set a value upon his friendship,
of which, perhaps, I am better judge, leaving the latter to men of deeper talents.
I blame him nothing, but leave it to his better thoughts, if in my affair,
his jealousy was not too nimble for his charity.
If he can believe me,
I should hardly prevail with myself to endure the
same thought of Dr. Tillotson on the like occasion,
and less to speak of it.
For the Roman correspondence I will freely come to confession.
I have not only no such thing with any Jesuit at Rome,
(though Protestants may have without offence) but I hold none with any Jesuit,
priest or regular in the world, of that communion.
And that the doctor may see what a novice I am in that business, I know not one any where.
And yet, when all this is said, I am a Catholic, though not a Roman.
I have bowels for mankind, and dare not deny others what I crave for myself, I mean,
liberty for the exercise of my religion; thinking faith,
piety and providence a better security than force,
and that if Truth cannot prevail with her own weapons, all others will fail her.

Now, though I am not obliged to this defence,
and that it can be no temporizing now to make it,
yet that Dr. Tillotson may see how much I value his good opinion,
and dare own the truth and myself at all turns, let him be confident,
I am no Roman Catholic, but a Christian, whose creed is the Scripture,
of the truth of which I hold a nobler evidence,
than the best church authority in the world; and yet I refuse not to believe the porter,
though I cannot leave the sense to his discretion; and when I should,
if he offends against those plain methods of understanding,
which God hath made us to know things by, and which are inseparable from us,
I must beg his pardon; as I do the doctor`'s for this length,
upon the assurance he has given me of his doing the like upon better information;
which that he may fully have, I recommend him to my Address to Protestants,
from page 133 to the end, and to the four first chapters of my No Cross, No Crown;
to say nothing of our most unceremonious and unworldly way of worship,
and their pompous cult; where at this time I shall leave the business,
with all due and sensible acknowledgments to thy friendly temper,
and assurance of the sincere wishes and respects of thy affectionate real friend,

William Penn.

Charing-cross, the 29th of the Eleventh month, 1686.

William Penn to Dr. Tillotson.

Charing-cross, 27th of Second month, 1686.

Worthy friend,

This should have been a visit,
but being of opinion that Dr. Tillotson is yet a debtor to me this way,
I chose to provoke him to another letter by this, before I made him one.
For though he was very just and obliging when I last saw him,
yet certainly no expression, however kindly spoken,
will so easily and effectually purge me from the unjust
imputation some people cast upon me in his name,
as his letter will do.
The need of this he will better see when he has read the enclosed, which,
coming to hand since my last, is, I presume, enough to justify this address,
if I had no former pretensions.
And therefore I cannot be so wanting to myself,
as not to press him to a letter in my just defence, nor so uncharitable to him,
as to think he should not frankly write what he has said,
when it is to right a man`'s reputation, and disabuse the too credulous world.
For to me it seems from a private friendship, to become a moral duty to the public,
which, with a person of so great morality, must give success to the reasonable desire of,

Thy very real friend,

William Penn.

Dr. Tillotson to William Penn.

April the 29th, 1686.

Sir,
I am very sorry that the suspicion which I had entertained concerning you,
of which I gave you the true account in my former letter,
hath occasioned so much trouble and inconvenience to you.
And I do now declare with great joy,
that I am fully satisfied there was no just ground for that suspicion,
and therefore I do heartily beg your pardon for it.
And ever since you were pleased to give me that satisfaction,
I have taken all occasions to vindicate you in this matter; and shall be ready to do it,
to the person that sent you the enclosed, whenever he will please to come to me.
I am very much in the country,
but will seek the first opportunity to visit you at Charing-cross,
and renew our acquaintance, in which I took great pleasure.
I rest,

Your faithful friend,

Jo. Tillotson.

A work written by the Duke of Buckingham, in defence of liberty of conscience,
for which he had always been an advocate, near this time drew from an anonymous author,
some unjust reflections, both on the duke and on William Penn.
This induced the latter to make a reply, in which he exposed the absurdities,
misrepresentations and contradictions of the writer,
with the force of argument and keenness of wit for which he was, at times, so remarkable.

A larger tract soon followed, entitled,
"`A Persuasive to Moderation,`" the object of which was to show
the propriety of a general toleration to church dissenters.
This is a very valuable treatise;
and though the doctrine which the author was then labouring to establish,
is now generally received as self-evident,
it is worthy of a serious perusal in the present day.
I shall attempt a concise analysis of its contents.

He begins by defining conscience to be the apprehension
and persuasion a man has of his duty to God;
and liberty of conscience, to mean a free and open profession and exercise of that duty,
especially in regard to worship;
but expressly limits that freedom to a conscience which keeps within the bounds of morality,
and is as exact to yield to Caesar the things that are Caesar`'s,
as jealous of withholding from God the things that are God`'s.

He next shows, by a series of historical facts,
that the toleration of different professions in religion,
has never been destructive to governments which used it;
and that the revolutions of political power have been more frequently
effected by the adherents than by the opponents of the prevailing religion.
He also argues that the toleration of dissenters,
would increase the security of the state,
by removing the causes which frequently give rise to discontent and rebellion.
He then explains the causes of the contests which had agitated
the English nation during the reign of Charles I.;
and the motives by which the different parties were actuated at that time,
as well as under the protectorate;
and shows that a general toleration would have prevented
or cured a great part of the evils of the state.
A general toleration, by rendering the property of all persuasions secure,
would increase the industry and wealth of the nation.
This doctrine is illustrated and confirmed by the results
of King Charles`' declaration of indulgence to dissenters,
which was issued in the year 1672.
He does not examine the motives or legality of this declaration,
but shows that its effect was highly recommendatory of a general toleration.
The case is afterwards argued on grounds more clearly religious;
viz. That offerings contrary to conscience,
are as odious to God as uneasy to those who make them.
That our Saviour would not permit fire to be brought, though from heaven,
to consume the dissenters of his day.
That he commanded them to let the tares grow with the wheat until harvest;
and to exclude worldly strife for religion,
we are informed that his kingdom is not of this world.
The apostle Paul advocates the same doctrine.
He advised that every man should be fully persuaded in his own mind,
and if any were mistaken, God, in his own time, would inform them better.
He spoke of schismatics and heretics; they were to be admonished,
and if admonition should fail, they were to be denied the fellowship of the church.
But there the authority of the church ended.

The essay was closed with a number of quotations from the Christian fathers,
and the opinions of others eminent for their wisdom or stations in life,
in support of religious toleration.
Among these were the father and grand-father of the reigning monarch.
These tracts are without date,
except as the year of their publication appears in the margin,
in the printed works of our author.

From what J. Besse, the biographer of William Penn, has said on the subject,
we may infer that this tract was written, if not published,
previous to the proclamation for a general pardon issued in 1686,
and we find that a particular charge was given by the king
to the judges of assize in their several circuits,
to extend the benefits of the pardon to such of the people called Quakers,
as were convicted or under process in order for conviction, of premunire,
for refusing to swear, or presented for absence from church, or other similar causes;
by which means about thirteen hundred Friends,
many of whom had lain in prison a number of years, were restored to liberty.
Whatever motives may have influenced the king and his council in this proceeding,
it was not to be doubted that Friends would receive the boon,
with gratitude to the king as the immediate dispenser,
and primarily to the Author of all good as the supreme and original disposer of events.

In the course of the year 1686, William Penn paid a visit to the continent.
The king being informed of his prospect,
requested him to undertake a mission to the Prince of Orange, afterwards William III.
The object of the mission was to procure his consent
to a general religious toleration in England,
together with the removal of all tests.^
footnote:[The Test act was passed in 1673,
and it required that all persons holding any public office,
besides taking the oaths of allegiance and supremacy,
and receiving the sacrament according to the rites of the church of England,
should abjure the doctrine of transubstantiation.]

The object in view was very congenial with William Penn`'s opinions and principles.
In his "`Persuasive to Moderation,`" then just published, he had expressed the sentiment,
that the business of the state might be better managed,
by allowing the prince to choose his agents out of six denominations,
than by limiting him to one.
In his own practice in Pennsylvania, he manifested the liberality of his principles.
He not only secured freedom of conscience to all the inhabitants,
but frequently entrusted important offices to the hands
of persons who did not belong to his own religious Society.

Upon arriving on the continent, he went immediately to the Hague,
where he had several conferences with the prince, on the subject.^
footnote:[It may appear strange that William Penn should countenance
an application to a foreign prince for permission to repeal the
penal laws and abolish the tests in Great Britain.
The Prince of Orange certainly had no authority to
interfere with the legislation of the kingdom;
yet as his wife, the eldest daughter of James, was presumptive heiress to the crown,
it was obvious that in case of her succession,
the prince must have great influence over the affairs of the nation.
He was indeed considered as the hope of the Protestants,
and in the existing state of public opinion,
there was little prospect of carrying so important,
a measure through the British parliament without his approbation.
I find no account of the effect, if any was produced,
of the interviews with William Penn;
but it appears that the prince subsequently authorized Fagel,
counsellor and chief-pensionary at the Hague, to inform the king,
that he and the Princess Mary highly approved of granting
an entire toleration to all Protestant dissenters;
and were willing the Roman Catholics should also enjoy the liberty of their consciences.
But that they could not agree to the repeal of the test and the other penal laws which
excluded the professors of that religion from parliament and public employment.]
Here he met with Burnet the historian, who was then at the same court,
endeavouring to procure the consent of the prince to a toleration in England,
but not to a removal of the tests.
They spent several hours in discussing the subject.
William Penn supported the opinion that tests were not necessary as a security to toleration,
because dissenters were amenable to the laws for any deviation from constitutional rectitude.

While he was executing his commission, he became acquainted with several persons,
both English and Scotch,
who had fled from their country on account of persecution for their religion.
These were not of his religious persuasion,
yet upon his return to England he interested himself in their favour,
and procured their indemnity.
One of them, upon his return, finding his estate in possession of another,
acquainted William Penn with the circumstances; who immediately called on the possessor,
and by his remonstrances obtained the restitution of a part of it.
After the revolution the remainder was recovered.

The object of his visit to the continent, was a religious one, but of the particulars,
very little is known.
It appears he visited his friends at Amsterdam,
and was at the house of William Sewel the historian,
who was then engaged in translating his account of Pennsylvania, and No Cross, No Crown,
into the Low Dutch language.
With him he carried on for some time a correspondence in Latin,
some portions of which were used by Thomas Clarkson in his biography of William Penn.

From Amsterdam he pursued his travels in the work of the ministry to Utrecht;
but of the other places he visited nothing is now known.
It is understood, however, that he extended his visit to some parts of Germany,
and in a letter written afterwards, to one of his friends,
he expressed that he had had blessed service for the Lord.

After his return from the continent, he visited a considerable part of his native land.
He travelled in the work of the Gospel through Oxfordshire, Warwickshire, Staffordshire,
Derbyshire, Cheshire, Lancashire, Yorkshire, and the counties of Westmoreland and Durham.
This religious service appears to have been accomplished
to the satisfaction of his own mind,
for he thankfully testified that the Lord had been
with him at that season in a sweet and melting life,
to the great joy of himself and refreshment of his friends.

Soon after the proclamation of pardon already noticed,
King James checked the rapacity of the informers about London and Middlesex,
by signifying his pleasure to the justices that they should withhold their encouragement,
from that unprincipled crew.
Still Friends were persecuted as popish recusants,
particularly by the act of 23 Elizabeth, for twenty pounds a month,
on account of absence from the national worship.
Application being made to the king, he was pleased to grant a nolle prosequi,
and gave orders to the attorney-general,
that no writs should be issued out of the exchequer against Friends on these accounts.
Thus the ruin of great numbers of Friends was prevented,
and their estates saved to the amount of many thousand pounds;
a result which the labours and influence of William
Penn were no doubt instrumental in producing.

The relief thus afforded,
may perhaps be considered as fairly included in the royal prerogative;
but in the early part of 1687, the king issued a declaration of general indulgence,
or liberty of conscience, by his sovereign authority and absolute power,
to his subjects of all religions;
ordering that thenceforth the execution of all penal
laws concerning ecclesiastical affairs,
for not coming to church, for not receiving the sacraments,
or for any other non-conformity with the established religion,
or for performing religious worship in other ways, should be suspended.^
footnote:[There were two proclamations published,
one for Scotland and the other for England.
The former expressly granted a toleration by his sovereign authority,
prerogative royal and absolute power; but in the latter the language was softened,
and a confident expectation of the concurrence of parliament introduced.]

This was certainly a stretch of the royal prerogative totally
irreconcilable with the nature of a limited monarchy.
Yet as the boon, so far as liberty of conscience was regarded,
was nothing more than reason and justice required,
the dissenters in general accepted it with gratitude.
Addresses of thanks to the king were therefore presented from numerous quarters.
Among others, Friends of the city of London presented one,
expressive of their gratitude to the king for this act of justice and mercy.
But this address being presented only by Friends in the vicinity of London,
the ensuing Yearly Meeting held in that city prepared
one in behalf of the Society at large,
and deputed William Penn, in conjunction with some others, to present it.

Being admitted to the king,
William Penn introduced the address by a speech to the following import.

It was the saying of our blessed Lord to the captious Jews in the case of tribute,
'`Render to Caesar the things that are Caesar`'s,
and to God the things that are God`'s.`' As this distinction ought
to be observed by all men in the conduct of their lives,
so the king has given us an illustrious example, in his own person,
that excites us to it: for while he was a subject he gave Caesar his tribute,
and now he is Caesar he gives God his due, namely, the sovereignty over consciences.
It were a great shame then, for any Englishman that professes Christianity,
not to give God his due.
By this grace he has relieved his distressed subjects from their cruel sufferings,
and raised to himself a new and lasting empire by adding their affections to their duty.
And we pray God to continue the king in this noble resolution;
for he is now upon a principle that has good nature,
Christianity and the good of civil society, on its side,
a security to him beyond the little arts of government.

I would not that any should think we come hither
with design to fill the gazette with our thanks;
but as our sufferings would have moved stones to compassion,
so we should be harder if we were not moved to gratitude.

Now, since the king`'s mercy and goodness have reached to us
throughout the kingdom of England and principality of Wales,
our General Assembly from all those parts, met at London about our church affairs,
has appointed us to wait upon the king with our humble thanks, and me to deliver them;
which I do, by this address, with all the affection and respect of a dutiful subject.

The address of the Yearly Meeting was then read, being as follows:

We cannot but bless and praise the name of Almighty God,
who hath the hearts of princes in his hand,
that he hath inclined the king to hear the cries of his suffering subjects for conscience-sake;
and we rejoice, that, instead of troubling him with complaints of our sufferings,
he has given us so eminent an occasion to present him with our thanks.
And since it hath pleased the king, out of his great compassion,
thus to commiserate our afflicted condition,
which hath so particularly appeared by his gracious proclamation and warrants,
whereby twelve hundred prisoners were released from their several imprisonments,
and many others from spoil and ruin in their estates and properties,
and by his princely speech in council and Christian declaration for liberty of conscience,
in which he doth not only express his aversion to all force upon conscience,
and grant all his dissenting subjects an ample liberty to worship
God in the way they are persuaded is most agreeable to his will,
but gives them his kindly word the same shall continue during his reign.
We do, as our friends of this city have already done, render the king our humble,
Christian and thankful acknowledgments, not only in behalf of ourselves,
but with respect to our friends throughout England and Wales;
and pray God with all our hearts to bless and preserve thee, O king,
and those under thee, in so good a work.
And as we can assure the king it is well accepted
in the several counties from which we came,
so we hope the good effects thereof for the peace,
trade and prosperity of the kingdom will produce such a concurrence
from the parliament as may secure it to our posterity in aftertimes;
and while we live, it shall be our endeavour, through God`'s grace, to demean ourselves,
as in conscience to God and duty to the king, we are obliged, his peaceable,
loving and faithful subjects.

To this the king then replied,

Gentlemen, I thank you heartily for your address.
Some of you know, I am sure you do, Mr. Penn,
that it was always my principle that conscience ought not to be forced;
and that all men ought to have the liberty of their consciences.
What I have promised in my declaration I will continue to perform as long as I live.
And I hope, before I die,
to settle it so that after ages shall have no reason to alter it.

It has been made a subject of censure that Friends and other dissenters,
should offer their acknowledgments to the king for a favour which
was dispensed by the violation of a constitutional principle.
A few observations will be sufficient to vindicate the Society of Friends.
Their principles have always led them to live peaceably under the established governments;
but to take no part in setting them up or pulling them down.
They were not accustomed to scrutinize very closely the
extent of the powers exercised by men in authority.
The limits of the royal prerogative were at that time very imperfectly defined.
Indeed Sir Edward Herbert, chief-justice of the king`'s bench,
had declared a few months before,
that there was nothing whatever with which the king as supreme lawgiver,
might not dispense; and this decision was confirmed by eleven judges out of the twelve.
It was not then to be expected that the exercise of this dispensing power would
be disputed by those who were relieved by it from an oppressive burden.
The penal laws, inasmuch as they abridged the freedom of worship,
were justly considered as an usurpation of the Divine prerogative;
the suspension of those laws by royal authority alone,
might therefore be viewed as counteracting usurpation.
As the king had always professed himself a friend to liberty of conscience,
and the measures of his government, so far as they were then developed,
were not incompatible with such profession,
Friends were at liberty to attribute his proclamation to justifiable motives.
And we may observe, they modestly intimate, in their address,
the necessity of a concurrent action by the parliament, to render the measure permanent.

In the summer of 1687, William Penn again travelled in the work of the Gospel,
through various parts of England, and in the course of the journey,
held several meetings for worship at Bristol,
where Friends had been so violently persecuted.
These meetings were remarkably crowded, the people flocking to them in great numbers;
showing that their zeal was rather increased than diminished by the recent persecutions.
At Chew, about five or six miles from Bristol, he had a meeting in the open air,
there being no building to be had sufficiently capacious
to accommodate the multitude that attended.
"`A large and heavenly meeting it was,`" says J. Whiting,
"`many Friends and others of the country round about, being there; and the more,
that it was the first time, as I remember, that William Penn was ever in our county.`"

Among the places he visited in Cheshire, was Chester itself.
The king being then on a journey, and arriving there at the time, attended the meeting;
as he did at two or three other places,
where he happened to be when the meetings were held.
Visiting Oxford in the course of his journey, he there met with the king again.
James was then attempting to introduce into the presidentship of Magdalen College,
Parker, a man of dissolute morals, and strongly suspected of popish principles.
The members of the college considering the interference of the king,
as an encroachment upon their rights, had elected a president,
whose character was more congenial to their principles.
This brought on a contest between the king and the members of the college;
in which the latter applied to William Penn for his interposition with the king.
He had the courage and magnanimity to express,
as modestly as the nature of the case would admit, yet in terms sufficiently explicit,
his disapprobation of the measures the king was pursuing;
and though he had endeavoured to procure a repeal
of the test act as well as the penal laws,
he proved himself no friend to popish ascendency.
His remonstrance however, did not arrest the proceedings of James,
by whose orders the fellows of the college were displaced,
and Parker forcibly installed in the presidency.

In the same year, probably after his return from the journey just mentioned,
he again took up his pen in the cause of liberty of conscience.

The freedom from persecution which Friends and other dissenters enjoyed,
being founded upon the dispensing power of the king,
was evidently held by a precarious tenure, as the proclamation might be revoked,
as that of Charles II. had been.
William Penn, therefore,
with a view of promoting the good work of placing the religious
liberties of the people upon a solid and permanent basis,
produced a tract, entitled, "`Good advice to the church of England,
Roman Catholics and Protestant Dissenters.
In which it is endeavoured to be made appear, that it is their duty,
principle and interest to abolish the penal laws and tests.
Beati Pacifici.`"

This tract was published without the author`'s name,
as the Persuasive to moderation had been,
probably from an apprehension that the unjust odium, under which he laboured,
might prejudice the public against any production which was known to be his.
It is classed in his printed works among his political tracts;
but is decidedly of a religious rather than a political character,
for the subject is argued on Christian principles.

In the first place he urges that it is the duty of
the three classes to whom the work is addressed,
to promote the abolition of the penal laws and tests;
because they all profess the Christian religion,
and Christianity requires us to believe that faith is the gift of God;
that he only is Lord of conscience, and is able to enlighten, persuade and establish it.
Consequently, to injure men in their persons or property,
or to exclude them from stations of trust on account of their religion,
is contrary to the tenderness and equity of Christianity.
This is confirmed by the consideration, that the Christian religion is founded in love.
Its origin, progress and consummation, were all in love.
Our Lord`'s rebuke to his disciples, who wished to call down fire from heaven,
to consume those who rejected him, is applicable to all times and places.
Christ commanded that the tares should be permitted to grow with the wheat,
until the harvest; so that he was in favour of a toleration;
and his mandates are not to be modified by reasons of state.
When the disciples related the circumstance of having
found one casting out devils in their master`'s name,
whom they forbade, because he followed not with them,
their decision was reversed by the Saviour himself,
the great Wisdom of God to his people, from whom there is no appeal.

The church of England was extremely scandalized by the severity
with which protestants were treated in France,^
footnote:[The Edict of Nantz, issued by Henry IV., in 1598,
granted to the French protestants, the free exercise of religion,
and a share in the administration of justice,
and the privilege of being appointed to all employments of trust, profit and honour.
It was revoked by Louis XIV., in 1685,
and a severe persecution commenced against the protestants,
in consequence of which the kingdom lost nearly 600,000 of its most valuable inhabitants,
who transported their industry and skill to other countries.]
yet the penal laws of England were directed to the same end, conformity or ruin.
The arguments in support of the penal laws in England, were of no more force,
than those in defence of the persecutions in France.
In Germany, the two religions were peaceably maintained together.

The church of England was deemed by many, a bulwark against popery;
but this she could hardly be, when she was bringing in the worst part of popery,
as she declared

persecution to be.
The part of popery to which the church of England most successfully objects,
is her violence; and this is indeed the only part she has cause to fear.
The doctrines of the papists are easily refuted, but forcing others to their faith,
or ruining them for refusing it, was the terrible thing they were taught to apprehend.
But this very evil was practiced by the church of England;
nearly twenty laws being then in force to compel uniformity;
and those laws executed as far as she thought it her interest to enforce them.

It is asserted that the plots of the papists, during the reign of Elizabeth,
caused the enactment of those laws.
But this is no substantial reason; for there were laws enough in existence,
or laws might have been enacted, to punish all civil enormities,
without forming any against them as papists.
The passage of those laws was a great error,
and very dishonourable to the principles of the first reformers.
Hence their continuance was the more obviously improper.
Let laws be enacted to detect and punish conspiracies and treasons,
and to preserve the peace.
But let the actions and not the opinions of men,
turn the magistrates`' sword against them.

A church by law established, is not necessarily a true one.
A true church is of the Saviour`'s making, and established by the gospel;
and it was a token of a false church, that none must buy or sell in her dominion,
who would not receive her mark in the forehead or right hand.
No church can give faith, and therefore cannot force it.
Another`'s faith cannot save me, though it should save him.
Penal laws serve only to manifest the sincerity of those who suffer by them,
and the cruelty of those who inflict them.

Our author in the second part of this treatise, proceeds to show,
that laws restraining the free exercise of religion,
are contrary to the avowed principles of the church of England.
This is proved in the first place,
by the declarations of the martyrs in the reign of queen Mary;
who uniformly denounced persecution as anti-christian;
and in the second by copious extracts from the writings and sermons
of a number of the most eminent members of her communion;
viz., Dr. Usher, bishop Saunderson, bishop Taylor, the bishop of St. Asaph,
Dr. Stillingfleet, Dr. Tillotson, Dr. Burnet, Sir Robert Pointz, Charles I., of England,
and lastly Dr. Hudson, the chaplain of Charles,
who told his royal master that he looked upon the calamities he then laboured under,
to be the hand of God upon him, for not having given God his due over conscience.

With regard to dissenters,
their judgment has been sufficiently expressed in opposition to all persecuting laws,
by their numerous addresses of thanks to the king,
for his recent declaration in favour of liberty of conscience.

Hence it is inferred,
that it is not only the duty of all parties as they value the character of Christians,
to promote the repeal of the penal laws on account of religion; but that they have all,
at one time or another, avowed the doctrine that conscience ought not to be compelled,
nor religion imposed by worldly penalties.

In the third part, he advances the opinion that the repeal of those laws,
was the interest of all parties, and especially of the church of England.

The reasons for that opinion are,
that they have been an argument against the first reformers,
and overthrow the principles upon which they separated from the church of Rome.
Those laws have also been the great cause of contention from the time of their enactment.
The operation of those laws is traced from Henry VIII.
to his own time, and their bitter fruits briefly exposed.

Throughout this essay,
we perceive a constant effort to lead the people of that day in the path
which their religious duty as well as civil interest pointed out--to allay
the jealousies which the conflict of parties had excited,
and to compose the fears, which, as a selfish politician,
regarding the progress of his own province,
he might have found it his interest to increase.
If King James and his advisers, had been governed by his prudent and Christian counsel,
that monarch would probably have escaped the disasters
which clouded the rest of his life.

A second tract on the repeal of the penal laws, entitled,
"`The great and popular objection against the repeal of the penal laws,
briefly stated and considered,`" soon followed.
This being of a temporary nature, is not contained in the printed works of our author.

William Penn had now been about three years absent from his American possessions.
During this time he appears to have been chiefly employed in assiduous
endeavours to procure the repeal of the persecuting laws.
A royal proclamation, as we have seen, had been issued,
suspending the execution of those laws.
Yet as this suspension, and consequently the ease resulting from it,
was founded upon the exercise of the royal prerogative,
and had not been confirmed by the parliament, he was not satisfied to return to America,
until he could see the religious liberties of his friends more fully secured;
the Society possessed at that time,
a large number of members eminently qualified for the religious service of their day,
but the talents of William Penn, natural and acquired,
joined with his influence at court,
rendered him a more efficient labourer in this particular field,
than any of his brethren.

The affairs of Pennsylvania had suffered from his absence.
Some unpleasant disputes had risen among the people there,
which his influence and authority, if present, would probably have prevented.
Of this the new settlers appear to have been conscious,
and were therefore very solicitous for his return.
Some disorders and immoralities were also permitted to grow up among them,
which he was very desirous to suppress.
In his letters and instructions to his friends and agents in Pennsylvania,
he repeatedly urged them to employ their influence or authority,
for the promotion of harmony, and the correction of vice and immorality,
in that infant colony.

There is reason to apprehend that he had, by this time,
begun to feel himself embarrassed in consequence of the heavy expenses
he had incurred in the settlement of the province,
and the slow returns received.
In several of his letters in 1686,
he noticed the tardiness of the returns for his labour and expense,
asserting that his expenditures had exceeded his receipts,
by not less than six thousand pounds, without taking any account of his labour,
hazard of life and separation from his family and friends, at home.
He expressed an ardent desire to return to Pennsylvania,
but intimated that this could not be done until greater
attention was paid by the inhabitants there,
to his interest and income.
In the course of 1687 a number of dispatches to persons in public stations,
and letters to his friends, were sent, in which the promotion of peace,
the suppression of immorality,
and the civil and religious advancement of the people were the burden of his theme.
His desire to be with them, was still forcibly expressed;
but the security of his friends, by the repeal of the penal laws,
which were then suspended,
was an object too near his heart to admit of his leaving England at that time.^
footnote:[A late historian, whose illiberal exposition of William Penn`'s motives,
was noticed in a former chapter,
imputes his continuance in England to the gratification
which he found at the court of St. James.
His labours to procure religious toleration are represented as being at an end when
the proclamation for religious indulgence and the suspension of the penal laws was issued.
But this author ought to have known,
that William Penn wrote one of his most elaborate works,
advocating the repeal of the penal laws after the
proclamation for their suspension was issued;
and that in his letter to J. Harrison, quoted by Proud,
he spoke of being engaged in the business of the nation and Friends--that
those in authority desired him to see the establishment of the
liberty which he had been a small instrument to begin;
and that the object expressly in view was to have
the penal laws repealed which were then suspended.]
