== Chapter XXIV.

1688-9. In the second month of this year,
King James published anew his declaration in favour of liberty of conscience,
inviting his subjects to accede to it,
and to choose such members of parliament as might do their part,
to finish what he had begun.
This parliament, it was announced, would be convened in the ensuing November.
To this declaration was annexed an order of council,
requiring it to be read in all the churches and chapels;
the bishops being enjoined to distribute it, for that purpose,
throughout their respective dioceses.

From the disposition manifested by the clergy of the established church,
during the preceding reign,
it is reasonable to believe that the liberty thus granted to dissenters,
was very disagreeable to them.
They had however a reason for opposing this mandate which they could advance,
without making any objection to its ostensible object.
The archbishop of Canterbury and six bishops accordingly
met and prepared an address to the king,
beseeching him not to insist upon a compliance with this order of council;
alleging that their aversion to reading the declaration did not
arise from any want of duty and obedience to their sovereign,
or of tenderness to dissenters;
but because it was founded upon a dispensing power which
had been repeatedly declared illegal by parliament.

Though this petition was delivered by the petitioners themselves, into the king`'s hands,
without being previously divulged to any one, he resented it so highly,
as to order them to be committed to the tower,
on their refusal to give bail for their appearance before the court of king`'s bench,
to answer for what was denominated a high misdemeanour,
and afterwards prosecuted as a libel.
This proceeding excited no little alarm among the people.
As a counterpoise to this excitement, the petition was published by authority,
accompanied with satirical remarks,
stating that the bishops had exercised great cruelties towards dissenters,
and had rigorously endeavoured to exalt the regal power above the law,
so long as it was employed for the oppression of others;
but now when exerted for their relief, as in 1672, they are desirous to limit it by law,
in order that the persecuting laws may retain their wonted force.
It may be added, that these bishops,
were afterwards brought to trial at Westminster hall;
and notwithstanding the judges held their seats during the pleasure of the king,
two of them had the firmness to declare against the dispensing power of the crown.
The jury at length brought in a verdict of acquittal,
which was received with applause by the nation.

These proceedings,
together with the encouragement openly given to the Roman Catholic worship and
the induction of many of its professors into stations of trust and power,
rendered the government of James, at that time,
exceedingly unpopular with Protestants of almost every denomination.
The favour shown to dissenters, however acceptable and reasonable in itself,
was viewed with distrust,
as an expedient to remove the existing disabilities
from the professors of the popish faith,
and finally to reestablish popery in England upon
the ruin of every denomination of protestants.
The removal of tests, which the king appeared determined to effect,
either by an act of parliament or by his own prerogative,
was considered as a means of paving the way for the introduction of Roman Catholics,
into all the departments of government.
The motives which were believed to actuate the king,
and for which indeed his measures gave too much reason, were by a natural association,
attributed to his advisers,
and William Penn from his intimacy at court became deeply involved
in the odium attendant upon the proceedings of the king.

It came to be understood, that he had been engaged in a mission to the Hague,
to procure the consent of the Prince of Orange to a repeal of the
test law as well as those restraining the freedom of worship.
He also became known as the writer of the "`Good advice to the
church of England,`" etc. which he had published anonymously.
Though there was nothing in any part of this conduct
inconsistent with his public and uniform profession,
and his frequent visits to the king furnished no evidence that
he was the adviser of any of his unconstitutional measures,
the suspicion of popery and Jesuitism was renewed with greater confidence than ever.

One of his particular friends, though not a member of his own religious Society,
conscious of the purity and integrity of his principles,
and anxious to rescue his character from the opprobrium
which ignorance and prejudice had fastened upon it,
wrote him the following letter.^
footnote:[The writer was secretary to the lords commission for trade and plantations.]

[.embedded-content-document.letter]
--

[.letter-heading]
To the honourable William Penn, esq., proprietor and governor of Pennsylvania.

[.salutation]
Honoured sir,

Though the friendship with which you are pleased to honour me,
doth afford me sufficient opportunities of discoursing with you upon any subject,
I choose rather at this time to offer unto you in writing,
some reflections which have occurred to my thoughts in a matter of no common importance.
The importance of it doth primarily and directly respect yourself,
and your own private concernments,
but it also consequentially and effectually regards the king, his government,
and even the peace and settlement of this whole nation.
I entreat you therefore to bear with me,
if I endeavour in this manner to give somewhat more weight
unto my words than would be in a transient discourse,
and leave them with you as a subject that requires your, retired consideration.

You are not ignorant that the part you have been
supposed to have had of late years in public affairs,
though without either the title, or honour, or profit of any public office,
and that especially your avowed endeavours to introduce amongst us a general
and inviolable liberty of conscience in matters of mere religion,
have occasioned the mistakes of some men, provoked the malice of others,
and in the end have raised against you a multitude of enemies,
who have unworthily defamed you with such imputations as I am sure you abhor.
This I know you have been sufficiently informed of,
though I doubt you have not made sufficient reflection upon it;
the consciousness of your own innocence seems to me to have given
you too great a contempt of such unjust and ill-grounded slanders;
for however glorious it is, and reasonable, for a truly virtuous mind,
whose inward peace is founded upon that rock of innocence,
to despise the empty noise of popular reproach,
yet even that sublimity of spirit may sometimes swell to a reprovable excess.
To be steady and immoveable in the prosecution of wise and honest resolutions,
by all honest and prudent means, is indeed a duty that admits of no exception;
but nevertheless it ought not to hinder that, at the same time,
there be also a due care taken of preserving a fair reputation.
A good name, says the wise man, is better than precious ointment.
It is a perfume that recommends the person whom it accompanies,
that procures him everywhere an easy acceptance,
and that facilitates the success of all his enterprizes; and for that reason,
though there were no other, I entreat you observe,
that the care of a man`'s reputation is an essential part of that
very same duty that engages him in the pursuit of any worthy design.

But I must not entertain you with a declamation upon this general theme.
My business is to represent to you, more particularly,
those very imputations which are cast upon yourself,
together with some of their evident consequences; that, if possible,
I may thereby move you to labour after a remedy.
The source of all arises from the ordinary access you have unto the king,
the credit you are supposed to have with him,
and the deep jealousy that some people have conceived
of his intentions in reference to religion.
Their jealousy is, that his aim has been to settle popery in this nation,
not only in a fair and secure liberty,
but even in a predominating superiority over all other professions:
and from hence the inference follows,
that whosoever has any part in the councils of this reign,
must needs be popishly affected;
but that to have so great a part in them as you are said to have had,
can happen to none but an absolute papist.
That is the direct charge; but that is not enough,
your post is too considerable for a papist of an ordinary form,
and therefore you must be a Jesuit: nay,
to confirm that suggestion it must be accompanied with all the
circumstances that may best give it an air of probability--as that
you have been bred at St. Omer`'s in the Jesuit`'s college;
that you have taken orders at Rome, and there obtained a dispensation to marry;
and that you have since then frequently officiated as a
priest in the celebration of the mass at Whitehall,
St. James`'s and other places.
And this being admitted, nothing can be too black to be cast upon you.
Whatsoever is thought amiss either in church or state,
though never so contrary to your advice, is boldly attributed to it,
and if other proofs fail, the Scripture itself must be brought in to confirm,
that whosoever offends in one point (in a point especially so essential as that
of our too much affected uniformity) is guilty of the breach of all our laws.
Thus the charge of popery, draws after it a tail like the et cetera oath,
and by endless innuendoes,
prejudicates you as guilty of whatsoever malice can invent or folly believe:
but that charge therefore being removed,
the inferences that are drawn from it will vanish,
and your reputation will easily return to its former brightness.

Now that I may the more effectually persuade you to apply some remedy to this disease,
I beseech you, sir, suffer me to lay before you some of its pernicious consequences.
It is not a trifling matter for a person raised as you are above the common level,
to lie under the prejudice of so general a mistake, in so important a matter.
The general and the long prevalency of any opinion gives it a strength,
especially among the vulgar, that is not easily shaken.
And as it happens that you have also enemies of an higher rank,
who will be ready to improve such popular mistakes, by all sorts of malicious artifices,
it must be taken for granted that those errors will be thereby still more confirmed,
and the inconveniencies that may arise from thence no less increased.
This, sir, I assure you, is a melancholy prospect to your friends;
for we know you have such enemies.
The design of so universal a liberty of conscience
as your principles have led you to promote,
has offended many of those whose interest is to cross it:
I need not tell you how many and how powerful they are.
Nor can I tell you, either how far,
or by what ways and means they may endeavour to execute their revenge.
But this however I must needs tell you, that in your present circumstances,
there is sufficient ground for so much jealousy at least,
as ought to excite you to use the precaution of some public vindication.
This the tenderness of friendship prompts your friends to desire of you;
and this the just sense of your honour, which true religion does not extinguish,
requires you to execute.

Pardon, I entreat you, sir, the earnestness of these expressions; nay,
suffer me without offence to expostulate with you yet a little further.
I am fearful lest these personal considerations should
not have their due weight with you,
and therefore I cannot omit to reflect also upon some more
general consequences of your particular reproach.
I have said it already, that the king, his honour, his government,
and even the peace and settlement of this whole nation, either are,
or have been concerned in this matter.
Your reputation, as you are said to have meddled in public affairs,
has been of public concernment.
The promoting a general liberty of conscience having been your particular province;
the aspersion of popery and Jesuitism, that has been cast upon you,
has reflected upon his majesty, for having made use, in that affair,
of so disguised a personage as you are supposed to have been.
It has weakened the force of all your endeavours, obstructed their effect,
and contributed greatly to disappoint this poor nation
of that inestimable happiness and secure establishment,
which I am persuaded you designed, and which all good and wise men agree,
that a just and inviolable liberty of conscience would infallibly produce.
I heartily wish this consideration had been sooner laid to heart,
and that some demonstrative evidence of your sincerity in the profession you make,
had accompanied all your endeavours for liberty.

But what do I say, or what do I wish for?
I confess that I am now struck with astonishment at that
abundant evidence which I know you have constantly given,
of the opposition of your principles to those of the Romish church,
and at the little regard there has been paid to it.
If an open profession of the directest opposition against popery,
that has ever appeared in the world,
since popery was first distinguished from common Christianity, would serve the turn;
this cannot be denied to all those of that Society,
with which you are joined in the duties of religious worship.
If to have maintained the principles of that Society, by frequent and fervent discourses,
by many elaborate writings, by suffering ignominy,
imprisonment and other manifold disadvantages in defence thereof,
can be admitted as any proof of your sincere adherence thereunto; this,
it is evident to the world, you have done already.
Nay further; if to have inquired as far as was possible for you,
into the particular stories that have been framed against you,
and to have sought all means of rectifying the mistakes upon which they were grounded,
could in any measure avail to the settling a true character of you in men`'s judgments;
this also I know you have done.
For I have seen under the hand of a reverend dean^
footnote:[Dr. Tillotson.]
of our English church,
a full acknowledgment of satisfaction received from you
in a suspicion he had entertained upon one of those stories,
and to which his report had procured too great credit.
And though I know you are averse to the publishing
of his letter without his express leave,
and perhaps may not now think fit to ask it;
yet I am so thoroughly assured of his sincerity and candour,
that I cannot doubt but he has already vindicated you in that matter, and will,
according to his promise, be still ready to do it upon all occasions.
Nay, I have seen also your justification from another calumny of common fame,
about your having kidnapped one who had been formerly a monk,
out of your American province, to deliver him here into the hands of his enemies; I say,
I have seen your justification from that story under that person`'s own hand.
And his return to Pennsylvania, where he now resides,
may be an irrefragable confutation of it,
to any that will take the pains to inquire thereinto.

Really it afflicts me very much to consider that all this does not suffice.
If I had not that particular respect for you which I sincerely profess;
yet I could not but be much affected,
that any man who had deservedly acquired so fair a reputation as you have formerly had,
whose integrity and veracity had always been reputed spotless,
and whose charity had been continually exercised in serving others,
at the dear expense of his time, his strength and his estate,
without any other recompense than what results from the consciousness of doing good;
I say, I could not but be much affected,
to see any such person fall innocently and undeservedly
under such unjust reproaches as you have done.
It is an hard case, and I think no man that has any bowels of humanity,
can reflect upon it without great relentings.

Since, therefore, it is so, and that something remains yet to be done,
something more express, and especially more public,
than has yet been done for your vindication, I beg of you, dear sir,
by all the tender efficacy that friendship, either mine,
or that of your friends and relations together, can have upon you;
by the due regard which humanity and even Christianity obliges you to have to your reputation;
by the duty you owe unto the king by your love to the land of your nativity;
and by the cause of universal religion and eternal truth,
let not the scandal of insincerity, that I have hinted at, lie any longer upon you;
but let the sense of all these obligations persuade
you to gratify your friends and relations,
and to serve your king, your country and your religion,
by such a public vindication of your honour, as your own prudence upon these suggestions,
will now show you to be most necessary and most expedient.
I am, with unfeigned and most respectful affection,

Honoured sir, Your most humble and most Obedient servant.

[.signed-section-context-close]
London, October the 20th, 1688.

--

[.offset]
This letter drew from William Penn the following reply:

[.embedded-content-document.letter]
--

[.salutation]
Worthy friend,

It is now above twenty years, I thank God,
that I have not been very solicitous what the world thought of me.
For since I have had the knowledge of religion from a principle in myself,
the first and main point with me has been, to approve myself in the sight of God,
through patience and well-doing.
So that the world has not had weight enough with me,
to suffer its good opinion to raise me, or its ill opinion to deject me.
And if that had been the only motive or consideration,
and not the desire of a good friend in the name of many others,
I had been as silent to thy letter,
as I use to be to the idle and malicious shams of the times.
But as the laws of friendship are sacred, with those that value that relation,
so I confess this to be a principal one with me,
not to deny a friend the satisfaction he desires,
when it may be done without offence to a good conscience.

The business chiefly insisted upon, is my popery, and endeavours to promote it.
I do say then, and that with all sincerity, That I am not only no Jesuit, but no papist.
And which is more, I never had any temptation upon me to be it,
either from doubts in my own mind about the way I profess,
or from the discourses or writings of any of that religion.
And in the presence of Almighty God, I do declare, that the king did never once,
directly or indirectly, attack me, or tempt me upon that subject,
the many years that I have had the advantage of a free access to him; so unjust,
as well as sordidly false, are all those stories of the town.

The only reason that I can apprehend, they have to repute me a Roman Catholic, is,
my frequent going to Whitehall,
a place no more forbid to me than to the rest of the world, who yet, it seems,
find much fairer quarter.
I have almost continually had one business or other there for our Friends,
whom I ever served with a steady solicitation, through all times,
since I was of their communion.
I had also a great many personal good offices to do,
upon a principle of charity for people of all persuasions,
thinking it a duty to improve the little interest
I had for the good of those that needed it,
especially the poor.
I might add something of my own affairs too, though I must own, if I may without vanity,
that they have ever had the least share of my thoughts or pains,
or else they would not have still depended as they yet do.

But because some people are so unjust, as to render instances of my popery,
or rather hypocrisy, for so it would be in me,
it is fit I contradict them as particularly as they accuse me.
I say then solemnly, that I am so far from having been bred at St. Omer`'s,
and having received orders at Rome, that I never was at either place,
nor do I know any body there;
nor had I ever a correspondence with any body in those places,
which is another story invented against me.
And as for my officiating in the king`'s chapel, or any other, it is so ridiculous,
as well as untrue, that besides that nobody can do it but a priest,
and that I have been married to a woman of some condition above sixteen years,
which no priest can be, by any dispensation whatever;
I have not so much as looked into any chapel of the
Roman religion and consequently not the king`'s,
though a common curiosity warrants it daily to people of all persuasions.

And once for all, I do say, That I am a Protestant dissenter, and to that degree such,
that I challenge the most celebrated Protestant of the English church or any other,
on that head, be he layman or clergyman, in public or in private.
For I would have such people know,
it is not impossible for a true Protestant dissenter to be dutiful,
thankful and serviceable to the king, though he be of the Roman Catholic communion.
We hold not our property or protection from him by our persuasion,
and therefore his persuasion should not be the measure of our allegiance.
I am sorry to see so many who seem fond of the reformed religion,
by their disaffection to him, recommend it so illy.
Whatever practices of Roman Catholics we might reasonably object against,
and no doubt but such there are,
yet he has disclaimed and reprehended those ill things
by his declared opinion against persecution;
by the ease in which he actually indulges all dissenters,
and by the confirmation he offers in parliament,
for the security of the Protestant religion and liberty of conscience.
And in his honour, as well as in my own defence, I am obliged in conscience to say,
that he has ever declared to me, it was his opinion, and on all occasions, when duke,
he never refused me the repeated proofs of it,
as often as I had any poor sufferers for conscience-sake to solicit his help for.

But some may be apt to say,
Why not any body else as well as I? Why must I have the preferable access to other dissenters,
if not a papist?
I answer, I know not that it is so.
But this I know, that I have made it my province and business;
I have followed and pressed it, I took it for my calling and station,
and have kept it above these sixteen years; and which is more,
if I may say it without vanity or reproach, wholly at my own charges too.
To this let me add the relation my father had to this king`'s service,
his particular favour in getting me released out of the tower of London in `'69,
my father`'s humble request to him upon his deathbed,
to protect me from the inconveniences and troubles my persuasion might expose me to,
and his friendly promise to do it, and exact performance of it,
from the moment I addressed myself to him.
I say, when all this is considered, any body that has the least pretence to good nature,
gratitude or generosity, must needs know how to interpret my access to the king.
Perhaps some will be ready to say, This is not all, nor is this yet a fault,
but that I have been an adviser in other matters disgustful to the kingdom,
and which tend to the overthrow of the Protestant
religion and the liberties of the people.
A likely thing indeed, that a Protestant dissenter, who from fifteen years old has been,
at times, a sufferer in his father`'s family, in the university, and by the government,
for being so, should design the destruction of the Protestant religion.
This is just as probable as it is true that I died a Jesuit six years ago in America.
Will men still suffer such stuff to pass upon them?
Is any thing more foolish as well as false, than that because I am often at Whitehall,
therefore I must be the author of all that is done there, that does not please abroad.
But supposing some such things to have been done, pray tell me,
if I am bound to oppose any thing that I am not called to do?
I never was a member of council, cabinet or committee,
where the affairs of the kingdom are transacted.
I have had no office or trust, and consequently, nothing can be said to be done by me,
nor for that reason,
could I lie under any test or obligation to discover my opinion of public acts of state,
and therefore neither can any such acts, nor my silence about them, in justice,
be made my crime.
Volunteers are blanks and cyphers in all governments.
And unless calling at Whitehall once a day, upon many occasions,
or my not being turned out of nothing, for that no office is,
be the evidence of my compliance in disagreeable things,
I know not what else can with any truth, be alleged against me.
However, one thing I know, that I have everywhere most religiously observed,
and endeavoured in conversation with persons of all ranks and opinions,
to allay heats and moderate extremities, even in the politics.
It is below me to be more particular, but I am sure it has been my endeavour,
that if we could not all meet upon a religious bottom,
at least we might upon a civil one, the good of England;
which is the common interest of king and people.
That he might be great by justice, and we free by obedience;
distinguishing rightly on the one hand, between duty and slavery; and on the other,
between liberty and licentiousness.

But, alas!
I am not without my apprehensions of the cause of this behaviour towards me,
and in this I perceive we agree;
I mean my constant zeal for an impartial liberty of conscience.
But if that be it, the cause is too good to be in pain about.
I ever understood that to be the natural right of all men;
and that he that had a religion without it, his religion was none of his own.
For what is not the religion of a man`'s choice, is the religion of him that imposes it.
So that liberty of conscience is the first step to have a religion.
This is no new opinion with me.
I have written many apologies within the last twenty years to defend it,
and that impartially.
Yet I have as constantly declared, that bounds ought to be set to this freedom,
and that morality was the best; and that as often as that was violated,
under a pretence of conscience, it was fit the civil power should take place.
Nor did I ever once think of promoting any sort of
civil liberty of conscience for any body,
which did not preserve the common Protestancy of
the kingdom and the ancient rights of the government.
For to say truth, the one cannot be maintained without the other.

Upon the whole matter, I must say, I love England; I ever did so;
and that I am not in her debt.
I never valued time, money nor kindred, to serve her and do her good.
No party could ever bias me to her prejudice,
nor any personal interest oblige me in her wrong.
For I always abhorred discounting private favours at the public cost.

Would I have made my market of the fears and jealousies of people,
when this king came to the crown, I had put twenty thousand pounds into my pocket,
and an hundred thousand into my province.
For mighty numbers of people were then upon the wing.
But I waved it all, hoped for better times;
expected the effects of the king`'s word for liberty of conscience, and happiness by it.
And till I saw my friends, with the kingdom, delivered from the legal bondage,
which penal laws for religion had subjected them to,
I could with no satisfaction think of leaving England;
though much to my prejudice beyond sea, and at my great expense here;
having in all this time, never had either office or pension;
and always refusing the rewards or gratuities of those I have been able to oblige.

If therefore an universal charity, if the asserting an impartial liberty of conscience,
if doing to others as one would be done by,
and an open avowing and steady practising of these things, in all times, to all parties,
will justly lay a man under the reflection of being a Jesuit or papist, of any rank,
I must not only submit to the character but embrace it too; and I care not who knows,
that I can wear it with more pleasure,
than it is possible for them with any justice to give it me.
For these are corner-stones and principles with me;
and I am scandalized at all buildings that have them not for their foundation.
For religion itself is an empty name without them, a whited wall, a painted sepulchre,
no life or virtue to the soul; no good or example to one`'s neighbour.
Let us not flatter ourselves; we can never be the better for our religion,
if our neighbour be the worse for it.
Our fault is, we are apt to be mighty hot upon speculative errors,
and break all bounds in our resentments; but we let practical ones pass without remark,
if not without repentance.
As if a mistake about an obscure proposition of faith,
were a greater evil than the breach of an undoubted precept.
Such a religion the devils themselves are not without;
for they have both faith and knowledge, but their faith doth not work by love,
nor their knowledge by obedience.
And if this be their judgment, can it be our blessing?
Let us not then think religion a litigious thing;
or that Christ came only to make us good disputants,
but that he came also to make us good livers.
Sincerity goes further than capacity.
It is charity that deservedly excels in the Christian religion; and happy would it be,
if where unity ends, charity did begin, instead of envy and railing,
that almost ever follow.
It appears to me to be the way that God has found
out and appointed to moderate our differences,
and make them at least harmless to society; and therefore I confess,
I dare not aggravate them to wrath and blood.
Our disagreement lies in our apprehension or belief of things;
and if the common enemy of mankind had not the governing of our affections and passions,
that disagreement would not prove such a canker as it is, to love and peace,
in civil societies.

He that suffers his difference with his neighbour about the other world,
to carry him beyond the line of moderation in this, is the worse for his opinion,
even though it be true.
It is too little considered by Christians,
that men may hold the truth in unrighteousness; that they may be orthodox,
and not know what spirit they are of; so were the apostles of our Lord;
they believed in him, yet let a false zeal do violence to their judgment,
and their unwarrantable heat contradict the great end of their Saviour`'s coming, love.

Men may be angry for God`'s sake, and kill people too.
Christ said it, and too many have practised it.
But what sort of Christians must they be, I pray, that can hate in his name, who bids us,
love; and kill for his sake, that forbids killing; and commands love, even to enemies?
Let not men or parties think to shift it off from themselves.
It is not this principle, or that form, to which so great a defection is owing,
but a degeneracy of mind from God.
Christianity is not at heart, no fear of God in the inward parts.
No awe of his Divine omnipresence.
Self prevails and breaks out more or less, through all forms, but too plainly, (pride,
wrath, lust, avarice) so that though people say to God, Thy will be done,
they do their own; which shows them to be true heathens, under a mask of Christianity,
that believe without works, and repent without forsaking,
busy for forms and the temporal benefits of them, while true religion,
which is to visit the fatherless and the widow,
and to keep ourselves unspotted from the world, goes barefoot,
and like Lazarus is despised.
Yet this was the definition the Holy Ghost gave of religion before
synods and councils had the meddling with it and modelling of it.
In those days bowels were a good part of religion,
and that to the fatherless and widow at large.
We can hardly now extend them to those of our own way.
It was said by him that could not say amiss; Because iniquity abounds,
the love of many waxeth cold.
Whatsoever divides man`'s heart from God, separates it from his neighbour;
and he that loves self more than God, can never love his neighbour as himself.
For, as the apostle said, if we do not love him whom we have seen,
how can we love God whom we have not seen?

O that we could see some men as eager to turn people to God, as they are to blow them up,
and set them against one another.
But indeed those only can have that pure and pious zeal,
who are themselves turned to God, and have tasted the sweetness of that conversion,
which is to power, not form; to godliness, not gain.
Such as those bend their thoughts and pains to appease,
not increase heats and animosities, to exhort people to look at home,
sweep their own houses, and weed their own gardens.
And in no age or time was there more need to set men at work in their own hearts,
than this we live in, when so busy, wandering, licentious a spirit prevails.
For whatever some men may think, the disease of this kingdom is sin, impiety against God,
and want of charity to men.
And while this guilt is at our door, judgment cannot be far off.

Now this being the disease, I will briefly offer two things for the cure of it.
The first is, David`'s clean heart and right spirit, which he asked and had of God.
Without this we must be a chaos still; for the distemper is within; and our Lord said,
All evil comes from thence.
Set the inward man right, and the outward man cannot be wrong.
That is the helm that governs the human vessel.
And this nothing can do but an inward principle, the light and grace that came by Christ,
who the Scriptures tell us, enlightens every one, and hath appeared to all men.
It is preposterous to think, that he who made the world,
should show least care of the best part of it, our souls; no,
he that gave us an outward luminary for our bodies,
hath given us an inward one for our minds to act by.
We have it; and it is our condemnation that we do not love it and bring our deeds to it.
It is by this we see our sins, are made sensible of them, sorry for them,
and finally forsake them.
And he that thinks to go to heaven a nearer way, will, I fear, belate his soul,
and be irreparably mistaken.
There are but goats and sheep at last, whatever shapes we wear here.
Let us not therefore, dear friend, deceive ourselves.
Our souls are at stake, God will not be mocked, what we sow we must expect to reap.
There is no repentance in the grave; which shows, that if none there, then no where else.
To sum up this divinity of mine; it is the light of Jesus in our souls,
that gives us a true sight of ourselves, and that sight that leads us to repentance,
which repentance begets humility, and humility that true charity,
that covers a multitude of faults,
which I call God`'s expedient against man`'s infirmity.
The second remedy to our present distemper is this;
since all of all parties profess to believe in God, Christ, the Spirit and Scripture,
that the soul is immortal, that there are eternal rewards and punishments,
and that the virtuous shall receive the one, and the wicked suffer the other; I say,
since this is the common faith of Christendom,
let us all resolve in the strength of God to live up to what we agree in,
before we fall out so miserably about the rest in which we differ.
I am persuaded, the change and comfort which that pious course would bring us to,
would go very far to dispose our natures to compound easily for all the rest,
and we might hope yet to see happy days in poor England;
for there I would have so good a work begun.
And how it is possible for the eminent men of every religious persuasion,
especially the present ministers of the parishes of England,
to think of giving an account to God at the last day,
without using the utmost of their endeavours to moderate
the members of their respective communions,
towards those that differ from them, is a mystery to me.
But this I know and must lay it at their doors, I charge also my own soul with it,
God requires moderation and humility from us; for he is at hand,
who will not spare to judge our impatience, if we have no patience for one another.
The eternal God rebuke, I beseech him, the wrath of man,
and humble all under the sense of the evil of this day: and yet, unworthy as we are,
give us peace, for his holy name`'s sake.

It is now time to end this letter, and I will do it without saying any more than this.
Thou seest my defence against popular calumny;
thou seest what my thoughts are of our condition and the way to better it,
and thou seest my hearty and humble prayer to Almighty God, to incline us to be wise,
if it were but for our own sakes.
I shall only add,
that I am extremely sensible of the kindness and
justice intended me by my friends on this occasion,
and that I am for that and many more reasons,

[.signed-section-closing]
Thy obliged and affectionate friend,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Teddington, October the 24th, 1688.

--

It must be admitted, that a more full,
clear and manly defence of his conduct and principles, than this letter contains,
could not have been written.
Whether it was then published, or retained among the friends of the receiver,
does not appear.
Nor do I find any account how far the suspicion of popery
was allayed by this unequivocal denial of it.
Certain it is, however, that his intimacy at court,
and acknowledged friendship for James,
subjected him to great inconvenience in the ensuing reign,
and that some writers of established reputation have given
to posterity an unfavourable representation of his conduct.
It will appear in the sequel that none of those charges
were supported by substantial or even probable evidence.

A few days after the date of William Penn`'s letter,
the Prince of Orange landed at Torbay,
and being joined by most of the leading men in the nation, King James fled into France,
and thus left the way open for the accession of the Prince and Princess of Orange.
A convention being called, they were declared King and Queen of England.

The effect of this change in the government was soon felt by William Penn;
for on the 10th of the tenth month, as he was walking in Whitehall,
he was sent for by the lords of the council, who were then sitting,
when he underwent an examination.
We have no account what charge, if any, was exhibited against him.^
footnote:[From what Clarkson has told us on the subject,
I should infer that this examination was based upon a suspicion that he was a papist,
or perhaps a Jesuit,
and had aided King James in his attempt to establish popery and arbitrary power.
But it is not clearly stated.]
In reply to some questions which were put to him,
he assured them that he had done nothing but what he could answer before God,
and all the princes in the world;
that he loved his country and the Protestant religion above his life,
and had never acted against either; that all he ever aimed at, in his public endeavours,
was no other than what the prince had declared for;
that King James was always his friend and his father`'s friend,
and in gratitude he was the king`'s friend; and did always, as much as in him lay,
influence him to his true interest.
Notwithstanding this manly and open declaration, and that nothing appeared against him,
he was required to give security for his appearance on the first day of next term,
which he did.
Upon his appearance in court he was continued on
the same security to the Easter term following.
On the last day of that term his case was brought before the court; when,
no charge of any kind appearing against him, he was publicly discharged.

The convention which placed William and Mary upon the throne of Great Britain,
having in the year 1689 been converted into a parliament,
proceeded to enact such laws as were judged requisite to secure the objects of the revolution.
A bill abolishing the test act was passed by the commons,
thus preparing the way for the admission of dissenting
Protestants into the offices of government.
But this bill was rejected by the house of lords.

The next measure in favour of dissenters was more successful.
A bill was introduced and passed into a law, usually styled the act of toleration.
By this act all dissenters were exempted from certain penalties,
provided they would take the oaths to government--and
as Friends could not conscientiously take an oath,
they were allowed the benefit of the act upon subscribing
a declaration of a prescribed form.
Dissenters were allowed to hold their meetings without molestation,
provided the doors were not bolted during the time.

From the works which William Penn had produced in defence of toleration,
and the clearness and force of his arguments,
we may safely consider him as one of the agents in the production of this great event.
The repeal of the penal laws will no doubt be attributed, by many,
to the growing liberality of the age.
But that liberality itself may be justly ascribed to the labours and sufferings
of those enlightened men whom that and the preceding ages produced;
among whom he and his friends held a conspicuous place.

During the time that William Penn was employed as we have seen in England,
the want of his presence in Pennsylvania was felt and lamented by the inhabitants there.
The burden of government had rested principally upon Thomas Lloyd,
a valuable member and minister of the Society of Friends;
but as he was desirous of being released from the
care and responsibility of his public station,
William Penn reluctantly granted his request, and nominated John Blackwell,
who was not a Friend, as his deputy.
Among the instructions, accompanying the commission sent to this officer,
I find the following: "`That the widow, orphan,
and absent may be particularly regarded in their rights;
for their cry will be loudest in all ears; but by absent,
I mean such as are so of necessity.`"
"`To have a special care that sheriffs and clerks of the peace impose not upon the people;
and that the magistrates live peaceably and soberly;
for I could not endure one loose or litigious person in authority.
Let them be men having some fear of God, and hating covetousness,
whatever be their persuasion: to employ others is to profane an ordinance of God.`"
"`Rule the meek meekly; and those that will not be ruled, rule with authority;
and God Almighty prosper all honest and prudent endeavours.`"

The appointment of Deputy-governor Blackwell did
not answer the expectations of the proprietary.
He did not harmonize with the inhabitants there;
and William Penn was induced in a short time to revoke his commission.
Although he expressed an apprehension that Friends were not altogether free from
blame in the controversies which arose between them and his deputy,
his letters were still expressive of his tender attachment to them,
and fervent desires for their temporal and spiritual welfare.
The inhabitants of the province being exempt from
the commotions which then agitated their native land,
were making rapid advances in the accumulation of estates;
and the watchful eye of William Penn did not fail to discover
the danger attendant upon the sudden increase of wealth.
In one of his letters written about this time,
he seriously admonished his friends in Pennsylvania to beware lest
the things of the world should occupy too much place in their minds;
"`For,`" says he "`it is a blessed state to enjoy and use the world,
in the dominion of his life and power, who has quickened us by his light and spirit.
In this stands all our peace and blessedness, that God be eyed in the first place;
that we set him continually before our eyes;
and that our eye be directed toward him in all things;
as the eye of a handmaid to her mistress;
that we may be able to say in truth and righteousness,
that we have none in heaven but him; nor on the earth besides him.`"

The year 1689 gave rise to Friends`' public school in Philadelphia;
which was incorporated in 1697 by a charter from William Penn`'s deputy.
This was subsequently confirmed, by a fresh charter from William Penn himself in 1701,
and a second in 1708.
By this charter the corporation was "`forever thereafter
to consist of fifteen discreet and religious persons,
of the people called Quakers, by the name of the Overseers of the Public School,
founded in Philadelphia, at the request, cost and charges of the people called Quakers.`"
A third and final one was granted in 1711, confirming the preceding charters,
and extending the privileges of the corporation.
Fifteen individuals were named in this charter,
several of whom are known to have been eminent for literary and scientific attainments,
as well as for religious worth.
Vacancies occurring in this body, are supplied by their own election.
By this charter the corporate title was changed to "`The Overseers of
the Public School founded by charter in the town and county of Philadelphia,
in Pennsylvania.`"

The design of this institution was not only to afford the
means of education in the common branches of learning,
in which the poor were taught gratuitously,
but to furnish an opportunity of instruction in the
higher departments of science and literature.

An extract from the preamble to this charter will show the design of its founders:--

[quote]
____
Whereas, the prosperity and welfare of any people depend, in great measure,
upon the good education of youth,
and their early instruction in the principles of true religion and virtue,
and qualifying them to serve their country and themselves, by breeding them in reading,
writing and learning of languages, and useful arts and sciences, suitable to their sex,
age and degree; which cannot be effected in any manner,
so well as by erecting public schools for the purposes aforesaid; therefore, etc.
____

The first teacher of that seminary was George Keith,
who afterwards rendered himself so conspicuous by his opposition to Friends.
He was engaged upon terms, which at that time must have been deemed liberal,
yet he retained his station there only about a year.
The seminary thus commenced in the infancy of the colony,
has been maintained to the present time;
the corporation have now under their superintendence a number of flourishing schools.^
footnote:[Though this public school was instituted in 1689,
it is not to be inferred that the business of education was neglected until then.
On the contrary, it appears by a minute of council dated in 1683,
that a teacher was then engaged to instruct the youth in reading, writing and accounts.]
This early attention to the establishment of seminaries of learning,
is an ample refutation of the charge so frequently brought against the Society of Friends,
that they are opposed to the literary instruction of their youth.
The imputation itself, when it is seriously entertained,
arises from ignorance both of the conduct and opinions of Friends.
The instruction of youth in science and literature,
to qualify them for usefulness in civil and religious society,
has always been promoted in the Society.
George Fox encouraged the education of youth "`in
whatsoever things were useful and civil.`"
It is to the assumption of human literature as a qualification for the ministry,
that Friends object, not when confined to its legitimate objects.
The establishment of a printing press in the neighbourhood of Philadelphia,
within four years after the landing of William Penn,
may also be adduced as evidence that the new settlers, a large part of whom were Friends,
were not averse to the encouragement of literature.
