== Chapter VII.

In the year 1676,
William Penn became engaged in the concerns of the province of New Jersey.
That province, while almost wholly a wilderness,
had been granted by Charles II. to his brother, the duke of York;
and the latter sold his interest in it to Sir George Berkely and lord Carteret.
Edward Byllinge, one of the Society of Friends,
afterwards became a purchaser of lord Berkely`'s share of the province.
In this transaction, John Fenwick, another member of the same Society,
acted as agent for Byllinge.
Some difficulty arising between Fenwick and Byllinge,
the subject was submitted to the arbitration of William Penn; and by him,
after considerable labour, brought to an amicable adjustment.
Soon afterwards, John Fenwick, with his family and a number of other Friends,
sailed to America.
But Edward Byllinge having been drained of his money by the purchase,
and afterward subjected to some losses, became unable to meet his pecuniary engagements.
He therefore agreed to give up his property for the benefit of his creditors.
In doing this, he looked to the friendly assistance of William Penn, who,
in compliance with his earnest entreaty,
became one of three trustees in the management of this complicated affair.

In consequence of this engagement,
William Penn became one of the managers of West New Jersey.
In this station he was associated with a number of others,
among whom were several of his own Society; under whose management,
a peaceable settlement was effected.
In the formation of this colony, as well as that of Pennsylvania,
we are furnished with a practical demonstration of the superiority
of the pacific principles of the Gospel,
over the policy of the world.
In the history of the first settlement of these provinces,
we hear nothing of the tomahawk and scalping-knife of the savage;
but we find the people of the old world mingling in friendly interaction
with the wild and untutored inhabitants of the woods.

In the same year he again came before the public as an author.
John Cheyney, a preacher, living near Warrington,
who had previously written several tracts against the people called Quakers,
which were answered by other hands, came out about this time,
with a small work called _A Skirmish Upon Quakerism._
In this he animadverted with great severity,
upon a passage in William Penn`'s reply to John Faldo.
This drew from our author a reply, entitled _The Skirmisher Defeated,
and Truth Defended._

The design of William Penn,
in the passages from which his opponent had garbled the matter objected to,
was to show the necessity and importance of a strict regard
to the teachings of the holy Spirit in the heart,
in order that we may clearly understand and properly perform our religious duties;
and not rest satisfied with a lifeless imitation of others.
In his _Skirmisher Defeated,_ he fully explains the conscience to which he alludes,
to be that which is Divinely enlightened,
and that no countenance is given in his doctrines
to a licentious life under the pretence of conscience.
So far is this doctrine from invalidating the Scriptures,
that it is proved to be this Divine light in the conscience,
which gives a right and saving knowledge of them,
and of the sacred truths which they contain.

In the same year he wrote a remarkable letter to
two Protestant women of quality in Germany.
One of them was the princess Elizabeth, daughter of Frederick V.,
prince Palatine of the Rhine and king of Bohemia,
and grand-daughter of James I. of England.
The other was Anna Maria, countess of Homes, the friend and companion of Elizabeth.
They were both religious women,
and the princess had manifested her liberality by affording an asylum in her dominions,
to persons who were persecuted for religion.
Robert Barclay and Benjamin Furly when travelling in Germany in the service of the Gospel,
had paid them a visit and were favourably received.

This visit gave the princess such a knowledge of the principles of Friends,
and so favourable an opinion of them, that hearing about this time,
of the imprisonment of Robert Barclay, she wrote to her brother, prince Rupert,
soliciting him to use his influence with the king,
to prevent or mitigate the severity with which he was threatened.
The letter of William Penn, which is of great length,
manifests a deep sympathy with them in the numerous trials to which
their condition in the world necessarily exposed them;
and contains a pathetic exhortation to pursue the path of holiness,
which had been opened before them.
It concludes in the following manner, "`Remember the poverty, simplicity, self-denial,
patience and the cross of Jesus.
I beg of you, by all that is dear and sacred to you, shrink not at this baptism,
neither so much as tamper with any latitude that would evade his bitter cup.
Let not his vinegar and gall be unpleasant, nor his crown of thorns troublesome:
last of all, let not his nails and spear be terrible to you.
For they that will not forsake him in his agonies,
but be the companions of his tribulations,
and cheerfully lay down their life and die with him to the world;
they and none else shall rise with him in the newness of life;
and ascend with him to his Father, by him to be glorified with that glory,
which he had with his Father before the world began.
Unto which kingdom, God Almighty conduct you, through this earthly pilgrimage. Amen.`"
