== Chapter XI.

The next morning, being the 13th of the sixth month, George Keith, Benjamin Furly,
and myself got ready to begin our journey towards Frankfort,
which by the way of Cassel is about two hundred English miles.
Robert Barclay prepared himself to return by the way we came, directly back to Amsterdam.
But before we parted, we had a little time together in the morning in our chamber;
where came one of the Princess`'s family, and one of the town.
The Lord moved me to call upon his great name, that he would be with them that stayed,
and with them that returned also, and with us that went forward in wild,
untrodden places.
And his blessed love and life overshadowed us; yes,
he filled our cup together and made us drink into one spirit,
even the cup of blessings in the fellowship of the everlasting Seed;
in which we took leave of one another.
After having eaten, it being about the seventh hour, we departed the city.

We came to Paderborn that night, six German miles, which are about thirty-six English;
it is a dark Popish town, and under the government of a bishop of that religion.
Howbeit, the woman where we lodged was an ancient, grave, and serious person;
to whom we declared the testimony of the Light,
showing her the difference between an outside and an inside religion;
which she received with much kindness.
We left some books with her, which she took readily.

There was also with us at supper a Lutheran who was a lawyer;
with whom I had very good service,
in opening to him the great loss of the power of godliness,
as well among them who separated from Rome, as in the Roman church; which he confessed.
I directed him to the Divine light in his conscience,
that let him see the lifeless state of the false Christians;
and if he turned his mind to that, and waited there,
he would receive power to rule and govern himself according to true godliness:
and that it was the loss of Christendom, that they went from this Holy Spirit,
in which the power stands,
that conforms the soul to the image and likeness of the dear Son of God;
and there they must come again, if ever they have the true knowledge of God,
and enjoy life and salvation; with much more to that purpose,
all which he received lovingly.

The next morning we set forward toward Cassel; but through great foulness of weather,
having only open carts to ride in, the waters being also high with the rains,
we did not set to Cassel till the next day, which was the fourth-day of the week.
It being late, we made little inquiry that night,
being also wearied with the foulness of the ways and weather.

But on the 16th we made our usual inquiry, namely, who was worthy in the city;
and found some that tenderly and lovingly received us;
to whom we declared the visitation of the light and love of God.
Among the rest was Dureus our countryman, a man of seventy-seven years of age,
who had learned in good measure to forget his learning, school divinity,
and priest`'s craft; and for his approaches towards an inward principle,
is reproachfully saluted by some with the honest title of Quaker.
It is much better than Papist, Lutheran, or Calvinist, who are not only ignorant of,
but enemies to quaking and trembling at the word of the Lord, as Moses and others did.

Upon the sixth-day of the same week about noon, we set out towards Frankfort,
having left several books behind us; which has been our practice in our journey.

At Frankfort we arrived on the 20th about noon, being just a week from Herwerden;
and having from there and Cassel, made known our intentions of coming,
two considerable persons came and met us about half a German mile from the city;
informing us of several who were well affected in that town.
Upon which, we told them the end of our coming,
and desired to have a meeting with them in the afternoon;
which we easily obtained at the house of a merchant, one of the two that met us.
The persons who resorted there, were generally people of considerable note,
both of Calvinists and Lutherans; and we can say,
they received us with gladness of heart,
and embraced our testimony with a broken and reverent spirit,
thanking God for our coming among them,
and praying that he would prosper his work in our hands.
This engaged our hearts to make some longer stay in this city.
We therefore desired another meeting the next day, which they cheerfully assented to;
where several came who were not with us the day before,
and the Lord who sent us into the land was with us, and by his power reached to them,
insomuch that they confessed to the truth of our testimony.

Of these persons, there were two women, one a virgin, +++[+++Joanna Eleonora de Malane,]
the other a widow, both noble of birth,
who had a deep sense of the power and presence of God which accompanied our testimony,
and their hearts yearned strongly towards us;
the virgin giving us a particular invitation to her house the next morning,
where we had the most blessed opportunity of the three;
for the Lord`'s power so eminently appeared,
that not only those who had been with us before were most effectually reached,
but a certain student, residing in the house of a Lutheran minister,
(sent for by that young woman,) was broken to pieces,
and magnified that blessed power which appeared.
There accidentally came in also a doctor of medicine, who unexpectedly was affected,
and confessed to the Truth, praying God to prosper us.
This was the blessed outcome of our visit to Frankfort.

But there is one thing more not unfit to be mentioned.
Among some of those who have inclinations after God,
a fearful spirit together with the shame of the cross has entered;
against which our testimony in part striking,
we took notice it was as life to these noble women, for that was it, as they told us,
which had long oppressed them, and obstructed the work of the Lord among them.
Therefore, said the young woman, "`Our quarters are free for you;
let all come that will come, and lift up your voices without fear; for,`" continued she,
"`it will never be well with us till persecution come,
and some of us be lodged in the stadthouse,`" that is the prison.

We left the peace of Jesus with them,
and the same afternoon we departed out of that city, being the fourth-day of the week.

Here I wrote an epistle to the churches of Jesus.

[.embedded-content-document.epistle]
--

[.blurb]
=== To the churches of Jesus throughout the world, gathered and settled in his eternal light, power and Spirit, to be one holy flock, family, and household to the Lord.

[.salutation]
Dear Friends and Brethren,

Who have been visited with the fatherly visitation from on high,
and have received God`'s eternal word and testament in your hearts,
by which you have been gathered home to Christ Jesus, the true Shepherd,
from all the idol-shepherds and their barren mountains and unprofitable hills,
where you have been scattered in the dark and gloomy day of apostacy; and by his light,
Spirit, and power have been convinced of sin, righteousness, and judgment; and can say,
the prince of this world is judged by his holy, righteous,
and powerful appearance in you, unto whom all judgment in heaven and earth is committed;
who is the blessed Lamb of God, the Light and Saviour of the world; who is King of Salem,
and Prince of Peace; my soul loves you with everlasting love,
even with the love with which my God and your God,
my Father and your Father has loved me, and visited my soul and your souls.
In this, do I dearly salute and embrace you all,
in this the day of the fulfilling of his glorious promises to his church in the wilderness,
and witnesses in sackcloth.

And, O magnified be his name,
and everlastingly praised and renowned be his holy power and arm,
by which he has reached unto us, and brought salvation near us!
For he has found us out, and has heard our solitary cries,
the deep and mournful supplications of our bowed spirits,
when we were as the dove without its mate, and the lonely pelican in the wilderness;
when we were ready to cry out, Is there none to save, is there none to help!
O when shall the time and times and half a time be finished!
When shall the one thousand two hundred and sixty days be accomplished!
And when shall the abomination that stands in the holy place, be cast out!
When shall the captivity of the people be turned back!
O when shall Babylon come into remembrance before God; the dragon, beast,
and false prophet be cast into the lake!
And when shall the law go forth out of Zion, and the word of the Lord out of Jerusalem!
When shall Zion become the joy, and Jerusalem the praise of the whole earth!
And when shall the earth be covered with the knowledge of the Lord,
as the waters cover the sea!

Friends, the Lord of heaven and earth has heard our cries, and the full time is come,
yes, the appointed time is come,
and the voice of the eternal Spirit in our hearts has been heard in this way many a time;
awake you that sleep, and I will give you life; arise out of the dust, and shine;
for your light is come, and the glory of the Lord is risen upon you!
And the Lord God has given us that light,
by which we have comprehended the darkness in ourselves and in the world;
and as we have believed in it, dwelt in it, and walked in it,
we have received power to overcome the evil one in all his appearances in ourselves,
and faithfully and boldly to testify against him in the world.
And the blood of Jesus, in this holy way of the light, have we felt in our souls,
to cleanse us from unrighteousness;
and give us to know the mystery of the fellowship of the Gospel one with another,
which stands in life and immortality.
And here we become a holy household and family unto God,
that live in his presence day and night, to do his will, as becomes his children,
redeemed and ransomed by the most precious blood of his Son,
and no more to return to folly.

And, Friends, let it never pass out of our remembrance, what our God has done for us,
since he has made us a people: has any weapon formed against us prospered?
Has he called us, and not protected us?
Has he given power to conceive, and not to bring forth?
Has he not sheltered us in many a storm?
Did he ever leave us under the reproaches and contradictions of men?
No, has he not spoken peace to us?
Were we ever cast out by men, and he forsook us`'.`' No, the Lord has taken us up.
Were we ever in prison, and he visited us not?
hungry, and he fed us not?
naked, and he clothed us not?
or have we been sick, and he came not to see us?
When were the jails so close, that he could not come in?
and the dungeons so dark that he caused not his light to shine upon us?
O no! he has never left us, nor forsaken us; yes, he has provided richly for us;
he has brought us into the wilderness not to starve us, but to try us;
yet not above our measure; for he fed us with manna from on high,
with pure honey and water out of the rock, and given his good Spirit to sustain us;
by night he was a pillar of fire to us, to comfort us; and by day a pillar of cloud,
to hide and shelter us.
He was a shadow of a mighty rock that followed us;
and we never failed to find a brook by the way to refresh us.
Was God good to Israel outward?
Much more has he abounded to his spiritual Israel,
the proper seed and offspring of himself.
O the noble deeds and valiant acts that he has wrought in our day for our deliverance!
He has caused one to chase ten, and ten a hundred, and a hundred a thousand many a time.
None has been able to snatch us out of his hands, who abode in his Truth.
For though the winds have blown, and the sea has raged,
yet has he rebuked the winds and the sea for his seed`'s sake; he has said to the winds,
'`be still;`' and to the sea, '`thus far shall you come,
and no further.`' He has cast up a highway for his ransomed to walk in, so plain,
that though a fool he shall not err therein.
This is the light, in which all nations of them that are saved must walk forever.

And therefore, Friends, let us stay our minds in the light of the Lord forever;
and let the awe, fear, and dread of the Almighty dwell in us.
And let his holy Spirit be known to be a covering to us,
that from the spirit of this world we may be chastely kept and preserved unto God,
in the holy light and self-denying life of Jesus,
who has offered up himself once for all,
leaving us an example that we should also follow his steps; that as he,
our dear Lord and Master, so we his servants and friends and children,
might by the eternal Spirit offer up ourselves to God in body, in soul, and in spirit,
which are his; that we may be his workmanship, created in Christ Jesus unto good works,
to the praise of him that has called us; which calling is a high and holy calling,
by the eternal Light and Spirit in our consciences.
O that it might forever remain in high estimation with us!
And that it may be the daily watch and travail of us all,
in the presence of the holy and living God who has called us,
to make our great call and election sure, which many have neglected to do,
who have been convinced by the blessed light and
Truth of Christ Jesus revealed in their hearts,
and who for a time have walked among us.
These have been overcome by the spirit of this world,
and turned their hands from the plough, and deserted the camp of the Lord,
and gone back again into Egypt; whereby the heathen have blasphemed,
and the way and people of the Lord have greatly suffered.

Therefore, O my dear Friends and brethren! in the sense of that life and power,
which God from heaven has so gloriously dispensed among us,
and by which he has given us multiplied assurances of his lovingkindness unto us,
and crowned us together with heavenly dominion,
in which my spirit is at this time broken before the Lord,
do I most earnestly entreat you to watch continually, lest any of you,
who have tasted of the good Word of God, and the powers of the world to come,
fall by temptation;
and by carelessness and neglect tempt the living God to
withdraw his fatherly visitation from any of you,
and finally to desert such; for the Lord our God is a jealous God,
and he will not give his glory unto another.
He has given to man all but man himself,
and him he has reserved for his own peculiar service,
to build him up a glorious temple to Himself; so that we are bought with a price,
and we are not our own.

Therefore let us continually watch and stand in awe, that we grieve not his Holy Spirit,
nor turn his grace into wantonness; but let all of us wait, in a holy travail of spirit,
to know ourselves sealed by the Spirit of adoption,
unto the day of our complete redemption; when not only all our sins, but all sorrows,
sighings, and tears shall be wiped away from our eyes;
and everlasting songs of joy and thanksgivings shall melodiously fill our hearts to God,
who sits upon the throne, and to his blessed, immaculate Lamb,
who by his most precious blood shall have completely redeemed us from the earth,
and written our names in the book of life.

Friends, the Spirit of the Lord has often brought you into my remembrance,
since I have been in this desolate land;
and with joy unutterable have I had sweet and precious
fellowship with you in the faith of Jesus,
that overcomes the world; for, though absent in body,
yet present in Him that is Omnipresent.
I can truly say, you are very near and very dear to me;
and the love that God has raised in my heart unto you, surpasses the love of women.
Our testimony, I am well satisfied, is sealed up together, and I am well assured,
that all who love the light, shall endure to the end throughout all tribulations,
and in the end obtain eternal salvation.

And now, Friends, as I have been travelling in this dark and solitary land,
the great work of the Lord in the earth has been often presented to my view,
and the day of the Lord has been deeply upon me,
and my soul has frequently been possessed with a holy and
weighty concern for the glory of the name of the Lord,
and the spreading of his everlasting Truth, and the prosperity of it through all nations;
that the very ends of the earth may look to him, and may know Christ, the light,
to be given to them for their salvation.
And when the sense of these things has been deeply upon me,
a holy and strong cry God has raised in my soul to him, that we,
who have known this fatherly visitation from on high,
and who have beheld the day of the Lord, the rising of the Sun of righteousness,
who is full of grace, and full of truth, and have beheld his glory,
and confessed it to be the glory of the only begotten Son of God;
and who by obedience to his appearance are become the children of light and of the day,
and as the first fruits to God after this long night of
apostacy,--might forever walk and dwell in his holy covenant,
Christ Jesus, the Light of the world; because in him we have always peace,
but out of him comes all the trouble.

And while this heavenly sense rested with me,
the Lord God that made me and called me by his grace unto salvation,
laid it upon me to visit you in a holy exhortation.
And it is the exhortation of my life at this time,
in the earnest and fervent motion of the power and Spirit of Jesus, to beseech you all,
who are turned to the light of Christ, which shines in your hearts, and believe in it;
that you carefully and faithfully walk in it, in the same dread, awe and fear,
in which you began; that that holy poverty of spirit,
which is precious in the eyes of the Lord, and was in the days of your first love,
may dwell and rest with you; that you may daily feel the same heavenly hunger and thirst,
the same lowliness and humility of mind, the same zeal and tenderness,
and the same sincerity and love unfeigned;
that God may fill you out of his heavenly treasure with the riches of life,
and crown you with holy victory and dominion over the god and spirit of this world;
that your alpha may be your omega, and your author your finisher,
and your first love your last love;
that so none may make shipwreck of faith and of a good conscience, nor faint by the way.
As in this state we are kept, in holy watchfulness to God as in the beginning;
the table which our heavenly Father spreads,
and the blessings with which he compasses us about, shall not become a snare unto us,
nor shall we turn the grace and mercies of the Lord into wantonness;
but we shall eat and drink in a holy fear, apparel ourselves in fear,
buy and sell in fear, visit one another in fear, keep meetings,
and there wait upon the Lord in fear; yes, whatsoever we take in hand to do,
it shall be in the holy fear of God, and with a holy tenderness of his glory,
and regard to the prosperity of his Truth: yes, we shall deny ourselves,
not only in the unlawful things, but in the things that are even lawful to us,
for the sake of the many millions that are unconverted to God.

For my Friends and brethren, God has laid upon us,
whom he has honoured with the beginning of his great work in the world,
the care both of this age, and of the ages to come;
that they may walk as they have us for examples:--yes,
the Lord God has chosen you to place his name in you;
the Lord has entrusted you with his glory, that you might hold it forth to all nations;
and that the generations unborn may call you blessed.

Therefore let none be treacherous to the Lord, nor reward him evil for good;
nor betray his cause directly by wilful wickedness,
nor indirectly by negligence and unfaithfulness,
but be zealous and valiant for Truth on earth.
Let none be slothful or careless:--O! remember the slothful servant`'s state.
Let the lovingkindness of the Lord overcome every soul to faithfulness;
for with him are riches and honour, and every good thing.
And where should any go?
He has the words of eternal life.
O! let none lose their testimony, but hold it up for God; let your gift be ever so small,
your testimony ever so little.
Through your whole conduct bear it for God; and be true to what you are convinced of.
And wait all upon the Lord, that you may grow in your heavenly testimony;
that life may fill your hearts, your houses, and your meetings;
that you may daily wait to know, and to receive power to do, the will of God on earth,
as it is in heaven.

And O! that the cross of Jesus may be in high and honourable esteem with every one;
that the liberty of all may stand in the cross, which alone preserves:
for it is the power of God, that crucifies us to the world, and the world to us.
And through death, way is made unto life and immortality; which by this blessed cross,
the Gospel, the power, is brought to light.
So shall the seed of life that God has sown in our hearts, grow;
and in that seed shall we all come to be blessed,
unto whom God has appointed the dominion over us.

And it is good for all to live under the holy government of it;
for the ways of it are ways of pleasantness, and all its paths are peace;
and all that are born of it, can say, Your sceptre is a sceptre of righteousness.
And O! that all Friends everywhere, may continually bow unto his righteous sceptre,
and keep to his holy law, which is written in their hearts;
that it may be a light to their feet, and a lantern to their paths.
So shall they come to witness that holy promise made good unto them,
'`The Spirit which I have given unto him, the Seed;
and the words which I have put into his mouth, shall not depart from him,
nor from his seed, nor from his seed`'s seed unto all generations.`'

Wherefore, Friends, redeem the time,
because the days are evil;--God has given you to see they are so:
and be separated more and more, yes, perfectly disentangled from the cares of this world.
And be not cumbered with the many things; but stand loose from the things that are seen,
which are temporal.

And you that are poor murmur not; but be patient and trust in the Lord,
and submit to his providence,
and he will provide for you that which is convenient for the days of your appointed time.
And you that are rich, keep in the moderation,
and strive not to multiply earthly treasure,
nor to heap up uncertain riches to yourselves;
but what God has given you more than is convenient for your own use, wait for his wisdom,
to employ it for his glory; that you may be faithful stewards of this world`'s mammon;
and the Lord God shall reward you into your bosoms,
of the riches of that kingdom that shall never have an end.

O my Friends and brethren! whether rich or poor, in bonds or at liberty,
in whatsoever state you are, the salutation of the universal life of Jesus is to you.
And the exhortation is, to bow to what is made known unto you; and in the light,
by which you have received in measure the knowledge of God,
watch and wait diligently to the further revelation of the mind and will of God unto you;
that you may be endued from on high with power and might in your inward man,
to answer the call and requirings of the Lord;
that you may be enabled to make known to the nations,
what is the riches of the glory of this blessed mystery in the Gentiles;
which is Christ Jesus, the light of the world, in you the hope of glory.
For this,
I have to tell you in the vision of the Almighty,--that
the day of the breaking up of the nations about you,
and of the sounding of the gospel-trumpet unto the inhabitants of the earth,
is just at the door; and they that are worthy,
who have kept their habitation from the beginning,
and have dwelt in the unity of the faith that overcomes the world,
and have kept the bond of peace,
the Lord God will empower and spirit you to go forth with his everlasting word and testament,
to awaken and gather kindreds, languages,
and people to the glory of the rising of the Gentiles`' Light;
who is God`'s salvation unto the ends of the earth.

And I must tell you, that there is a breathing, hungering, seeking people,
solitarily scattered up and down this great land of Germany, where the Lord has sent me;
and I believe it is the like in other nations.
The Lord has laid it upon me, with my companions, to seek some of them out,
and we have found several in various places.
We have had many blessed opportunities among them,
wherein our hearts have greatly rejoiced;
having been made deeply sensible of the love of God towards them,
and of the great openness and tenderness of spirit in them,
to receive the testimony of light and life through us.
We have a steadfast belief,
that the Lord will carry on his work in this land effectually;
and that he will raise up those,
that shall be as ministers of his eternal testament among them.
And our desire is,
that God would put it into the hearts of many of his faithful witnesses,
to visit the inhabitants of this country,
where God has a great seed of people to be gathered;
that his work may go on in the earth, till the whole earth be filled with his glory.

And it is under the deep and weighty sense of this approaching work,
that the Lord God has laid it upon me, to write to you,
to wait for the further pourings out of the power and Spirit of the Lord;
that nothing which is careless, sleepy, earthly, or exalted may gel up,
whereby to displease the Lord,
and cause him to withdraw his sweet and preserving presence from any that know him.
But let all keep the peace of the King of Righteousness,
and walk in the steps of the flocks of his companions;
for withering and destruction shall come upon all such as desert the camp of the Lord,
or with their murmuring spirit disquiet the heritage of God;
for they are greater enemies to Zion`'s glory and Jerusalem`'s peace,
than the open armies of the aliens.

And it is a warning to all who make mention of the name
of the Lord in this dispensation he has brought us to,
that they have a care how they let out their minds
in any wise to please the lusts of the eye,
the lusts of the flesh, and the pride of life,
which are not of the Father but of this world;
lest any be exalted in a liberty that makes the cross of Jesus of none effect,
and the offence thereof to cease; for such will become as salt that has lost its savour,
and at last will be trodden under the feet of God and men.
For, the Lord will withdraw his daily presence,
and the fountain will come to be sealed up, and the well of salvation be stopped again.

Therefore, as all would rejoice in the joy of God`'s salvation,
let them wait for the saving power, and dwell in it; that,
knowing the mystery of the work of regeneration--Christ formed in them
the hope of their glory--they may be able in the motion of him,
that has begotten them through death to life,
to go forth and declare the way of life and salvation.

And all you that are young, convinced of the eternal Truth, come into it,
and then you will feel the virtue of it: and so you will be witnesses,
otherwise vain talkers, wells without water, clouds without rain; for which state,
is reserved the blackness of darkness forever.
Wherefore, gird up the loins of your minds, be sober, and tempt not God;
but receive the day of your visitation, walk worthy of so great love,
and delight to retain God in your knowledge; grieve not his holy Spirit, but join to it,
and be led by it, that it may be an earnest to you of an eternal inheritance.
Take up your daily cross and follow Christ, and follow not the spirit of this world.
He was meek and lowly, he was humble and plain; he was few in words, but mighty in deeds.
He loved not his life unto death, even the reproachful death of the cross;
but laid down his life, and became of no reputation, and that for the rebellious.
O, the height and depth, the length, and the breadth, yes,
the unsearchableness of the love of God in Christ Jesus.

Wherefore, while it is today, hearken to his voice, and harden not your hearts:
and make no bargains for self, neither consult with flesh and blood:
but let the Lord be your light, and your salvation; let him be the strength of your life,
and the length of your days.
And this know assuredly, that none ever trusted to the Lord, and were confounded.
Wherefore, hold up your testimony for God,
as you would enjoy the increasings of his life and love; and let your light shine,
and confess him before the whole world.
Smother not his appearance, neither hide the candle which God has lighted in you,
under a bushel; for Christ walks among his candlesticks of pure and tried gold.
Wherefore, set your light upon a candlestick,
and show forth your good conduct in meekness and godly fear,
that you may become a good example, and others beholding your good works,
may glorify God.
But, for the rebellious, the fearful, and the unbelieving, the day hastens upon such,
in which the things that belong to their peace, shall be hid from their eyes forever.

And all you, my dear Friends and brethren,
who are in sufferings for the testimony of Jesus, and a good conscience,
look up to Jesus, the author and finisher of your faith; who,
for the joy that was set before him, endured the cross and despised the shame,
and is set down at the right hand of the Father in the heavenly place:--into which,
if you faint not, you shall all be received,
after the days of your pilgrimage shall be at an end, with a '`Well done,
good and faithful servant.`' And though these afflictions seem not joyous,
but grievous for the present;
yet a far more exceeding weight of glory stands at the door.
Wherefore, count it all joy when you fall into these trials, and persevere to the end;
knowing, He that shall come, will come, and will not tarry,
and that his reward is with him.
Remember the martyrs of Jesus, who loved not their lives to the death, for his namesake,
who had called them; and Jesus himself, who made a good confession before Pontius Pilate;
who has consecrated through his blood a new and living
way for all that come unto God by him;
who is made a High-priest, higher than the heavens,--one that can be touched and moved,
and is daily touched and moved with our weakness and infirmity;--that
through him we may be made strong in the Lord,
and more than conquerors through him that has loved us.

Wherefore, let it not seem as if some strange thing had happened to you;
for all these things are for the trial of your faith,
which is more precious than the gold that perishes.
It is the old quarrel;--children of this world, against the children of the Lord;
those that are born after the flesh,
warring against those that are born after the Spirit the Jews,
under the profession of the letter of the law, against Christ,
that came to fulfill the law, and all his spiritual followers and disciples;
and all the false apostate Christians,
against the true and spiritual Christians and martyrs of Jesus.
So, your conflict is for the spiritual appearance of
Christ Jesus against those that profess him in words,
but in works and conduct every day deny him;
doing despite to the spirit of grace in themselves, and those that are led by it.
But though Gog and Magog shall gather themselves together to lay waste the city of God;
yet the Lord has determined their destruction, and he will bring it to pass.

Wherefore rejoice, O you hill of God, and clap your hands for joy;
for He that is faithful and true, just and righteous, and able to deliver you,
dwells in the midst of you: who will cause you to grow and increase,
till you become a great mountain, till you become the praise of the whole earth,
and the whole earth be filled with your glory!

And to you all, who are the followers of the Lamb of God, who was dead, but is alive,
and lives forevermore,--who is risen in your hearts, as a bright shining light,
and is leading you out of the nature and spirit of this world,
in the path of regeneration,--I have this to say,
by way of holy encouragement unto you all; The Lord God that was, and is, and is to come,
has reserved for you the glories of the last days.
And if the followers and martyrs of Jesus in ages past,
when the church was going into the wilderness and his witnesses into sackcloth, were,
notwithstanding, so noble and valiant for the Truth on earth,
that they loved not their lives unto the death,
and suffered joyfully the spoiling of their goods for the testimony of
Jesus;--how much more ought you all to be encouraged unto faithfulness,
who are come to the resurrection of the day which shall never more be eclipsed;
in which the Bridegroom is to come, to fetch you his spouse out of the wilderness,
to give you beauty for ashes, and the garment of praise for the spirit of heaviness;
who will cover you with his Spirit, and adorn you with his fine linen,
the righteousness of the saints.
Lean upon His breast forever! and know your joining in an everlasting covenant with him,
that he may lift up the light of his countenance upon you, and delight to do you good;
that in blessing he may bless you, increase you,
and multiply you in all spiritual blessings now and forever; that to God, through him,
you may live all the days of your appointed time;--to whom be glory and honour,
praises and thanksgivings in the church, throughout all ages, and forever!

I am, in the faith, patience, tribulation, and hope of the kingdom of Jesus,
your friend and brother,

[.signed-section-signature]
William Penn.

[.postscript]
====

My companions in the labour and travail of the testimony of Jesus,
salute you all in the love of our God.
We have passed through several cities of Germany, and are now at Frankfort,
where the Lord has given us three blessed opportunities with a serious and seeking people;
whereof, as in other places of this country, many are persons of great worldly quality.
Blessed be the name of the Lord, to whom be glory forever!

====

[.signed-section-signature]
W+++.+++ P.

[.signed-section-context-close]
Frankfort, the 22nd of the Sixth month, 1677.

--
