== Chapter XIII.

Soon after the clock had struck five, they opened the gates of the city,
and we had not long been at our inn, when it came upon me, with a sweet,
yet fervent power,
to visit this persecuted Countess with a salutation from the love and life of Jesus,
and to open unto her more plainly the way of the Lord;
which I did in this following epistle:

[.embedded-content-document.epistle]
--

[.letter-heading]
To the Countess of Falkenstein and Bruck, at Mulheim.

[.salutation]
My dear friend,

Jesus, the immaculate Lamb of God, grieved and crucified by all the workers of iniquity,
illuminate your understanding, bless and be with your spirit forever!

Though unknown, yet you are much beloved,
for the sake of your desires and breathings of soul after the living God;
the report whereof, from some in the same state,
has made deep impression of true kindness upon my spirit,
and raised in me a very singular and fervent inclination to visit you: and the rather,
because of that suffering and tribulation you have begun
to endure for the sake of your zeal towards God;
myself having from my childhood been both a seeker after the Lord,
and a great sufferer for that cause, from parents, relations, companions,
and the magistrates of this world.
The remembrance whereof, has so much the more endeared your condition unto me;
and my soul has often, in the sweet sense and feeling of the holy presence of God,
and the precious life of his dear Son in my heart,
with great tenderness implored his Divine assistance unto you,
that you may both be illuminated to do, and made willing to suffer for his name`'s sake;
that the spirit of God and of glory may rest upon your soul.

And truly I can say, I felt the good-will of God,
his holy care and heavenly visitation of love to extend unto you.
But one thing more especially lay upon my spirit to have communicated to you,
which made me the more pressing for an opportunity to speak with you, and that was this;
that you should have a true, right, and distinct knowledge of your own state,
and what that is which has visited you; in what your faith, patience, hope,
and salvation stand; where to wait, and how to find the Lord;
and to distinguish between that which is born of God, and that which is not;
both with respect to yourself in all the motions and conceptions of your heart,
and with respect to others in their religious worships and performances; to the end,
that you may not be deceived about things relating to God`'s kingdom,
and your eternal peace: this is of the greatest weight.

Now, know certainly, that which has discovered unto you the vanities of this world,
the emptiness and the fading of all earthly glory, the blessedness of the righteous,
and the joy of the world that is to come, is the light of Christ Jesus,
wherewith he has enlightened your soul: for, '`in him was life,
and that life is the light of mankind.`' Thus God promised by the prophet Isaiah,
to give him '`for a light to lighten the Gentiles,
and for his salvation to the ends of the earth.`'
So that Christ the Light is God`'s gift,
and eternal life is hid in him, yes, all the treasures of wisdom and knowledge;
who is the light of the Gospel temple, even true believers.

And all who receive this light into their hearts, and bring their deeds to it,
to see in what ground they are wrought, whether in God or in the evil one,
and make this blessed light the guide of their life; fearing, with a holy fear,
to do anything that this light manifests to be evil;
wailing and watching with a godly care,
to be preserved blameless before the Lord;--I say, all such become children of light,
and witnesses of the life of Jesus.
O blessed will you be forever,
if in the way of this holy light your mind walks to the end!

Let this that has visited you lead you; this seed of light and life,
which is the seed of the kingdom.
Yes, it is Christ, the true and only seed of God, that visited my soul,
even in my young years; that spread my sins in order before me, reproved me,
and brought godly sorrow upon me; making me often to weep in solitary places,
and say within my soul, '`O that I knew the Lord as I ought to know him!
O that I served him as I ought to serve him!`' Yes,
often was there a great concern upon my spirit about my eternal state,
mournfully desiring, that the Lord would give my soul rest in the great day of trouble.
Now was all the glory of the world as a bubble; yes,
nothing was dear to me that I might win Christ: for the love, friendship,
and pleasure of this world were a burden unto my soul.
And in this seeking state, I was directed to the testimony of Jesus in my own conscience,
as the true shining light, giving me to discern the thoughts and intents of my own heart.
And no sooner was I turned unto it,
but I found it to be that which from my childhood had visited me,
though I distinctly knew it not.
And when I received it in the love of it, it showed me all that ever I had done,
and reproved all the unfruitful works of darkness; judging me as a man in the flesh,
and laying judgment to the line, and righteousness to the plummet in me.
And as by the brightness of his coming into my soul, he discovered the man of sin there,
upon his throne; so by the breath of his mouth,
which is the two-edged sword of his Spirit, he destroys his power and kingdom.
And having made me a witness of the death of the cross,
he has also made me a witness of his resurrection.
So that in good measure my soul can now say, I am justified in the spirit;
and though the state of condemnation unto death was glorious,
yet justification unto life was and is more glorious.

In this state of the new man, all is new: behold, new heavens and a new earth!
Old things come to be done away; the old man with his deeds put off`". Now, new thoughts,
new desires, new affections, new love, new friendship, new society, new kindred,
new faith; even that which overcomes this world, through many tribulations; and new hope,
even that living hope that is founded upon true experience, which holds out all storms,
and can see to the glory that is invisible to carnal eyes,
in the midst of the greatest tempest.

It is the same blessed seed of light, life, and grace,
which from God the Father is sown in your heart,
and which has moved and wrought there the change which you
have witnessed from the spirit of this world.
Turn to it, watch in it,
that by it you may be kept from all that it discovers to be contrary to God;
especially from yourself, from your own runnings, willings, and strivings.
For whatsoever is not born of the Spirit is flesh,
and that inherits not the kingdom of God;
but all that sow to it shall inherit corruption.
By this you will come to feel, not only all sin to be a burden,
but all your own righteousness, yes, all man`'s righteousness to be a burden.
You will see the difference between the duties and prayers which you beget,
and the duties and prayers which, in your true silence from all self-activity of mind,
the Lord begets in you.

O that you might know the mystery of the new birth,
and what that is that can truly call God, Father; even that which is begotten of him,
which lives, and breaths,
and has its beginning and being in that life which is hid with Christ in God,
and by which it has been quickened to the knowledge and worship of Christ and God.
And this you shall not fail to know and enjoy,
as you patiently allow the Lord to work his own work in you by his own blessed Spirit.
And that which will give you to savour and discern the right motions and conceptions,
duties and performances in yourself, from the false,
will give you to savour and discern that which is
right from that which is false in others;
that which is of God, from that which is of man.

Have a care of gathering sticks, and kindling a fire of your own,
and then compassing yourself about with the sparks of the fire which you have kindled,
for the end of this state is to lie down in sorrow; because the heavenly fire is absent,
which makes the sacrifice acceptable: yes, the Lord may stir in your heart,
but you may bring forth: but he that gives to conceive, he brings to the birth,
and he gives power to bring forth acceptably; for without Christ we can do nothing;
and blessed are they that stir not, before the angel moves the waters,
and go not before Christ, but are led by him,
and that awaken not their Beloved till he please;
in whose hands the times and the seasons are.
O blessed are they, whose eyes are opened to see him always present,
a God always nigh at hand; whose hearts are stayed upon his holy appearance in them,
and are thereby translated into his likeness; whose faith and hope are in Christ in them,
the hope of glory.

My dear friend, weigh these things with a serious, retired, sweet,
and tender frame of spirit; and God who has called me and you,
by the light of his dear Son,
open your understanding to perceive the Truth as it is in Jesus,
and what is the mystery of the fellowship of the saints in light.
So to the Lord I recommend you, the watchman and keeper of Israel.
The Lord be your strength and holy comfort, and speak peace to you,
and never leave you nor forsake you till he has conducted you, through all tribulations,
to his everlasting kingdom of rest and glory.

O dear heart! be valiant, and stay yourself upon Christ Jesus, the everlasting rock,
and feel him a fountain in your soul; feel his blood to cleanse, and his blood to drink,
and his flesh to eat: feed upon him, for God has given him for the life of the world.

I had seen you, had not your father`'s strange sort of severity hindered.
I confess I do not use to be so treated in my own country,
where the Lord has raised up many thousands of witnesses, that he has gathered,
out of all sects and professions, to worship him, not in their spirits or wills,
but in his will, Spirit, and Truth.
And we are generally, after much affliction and suffering, in good esteem,
even with the great ones of this world.
And this let me add for your particular comfort,
that though I have been a man of great anguish and sorrow,
because of the scorn and reproach that has attended my separation from the world,
(having been taught of Jesus, to turn my back upon all,
for the sake of that glory that shall be revealed;) yet to God`'s honour I can say it,
I have a hundred friends for one, yes,
God has turned the hearts of my enemies towards me; he has fulfilled his promise,
to turn the hearts of the parents unto the children.
For my parents, that once disowned me for this blessed testimony`'s sake, (of the Jew,
Christian, circumcision, and baptism inward,
against the fleshly Christian,) have come to love me above all, and have left me all;
thinking they could never do and leave enough for me.
O how good is the Lord! yes, the ways of his mercy are even past finding out.

Wherefore, my dear friend, trust in the Lord forever; and the God of Abraham, Isaac,
and Jacob, the God of the prophets and of the apostles,
the God of all the holy martyrs of Jesus, illuminate, fortify and preserve you steadfast;
that in the end you may receive the reward of life and eternal salvation:
to whom be glory, and to the Lamb that sits upon the throne, one God, and one Lord,
blessed and magnified forever and ever, amen!

Your great and faithful lover for the blessed and holy Truth`'s sake,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Duysburg, the 13th of the Seventh month, 1677.

[.postscript]
P+++.+++ S. The enclosed I received from a religious young woman at Frankfort.
We have had a blessed opportunity in this town with
some that have a desire after the Lord,
in which we are abundantly comforted.
We have just now received your message and salutation from H. V.,
which has exceedingly refreshed and revived us; for our trouble was not for ourselves,
but for you; and we hope our love will not turn to your disadvantage,
for we mentioned nothing of your name, nor the name of any other person,
only that we desired to speak with the minister of Mulheim,
and that was only to the soldier.
The Lord made us a good bed in the fields, and we were very well satisfied.
We are going this afternoon out of the town towards Wesel, from there to Cleve,
and from there to Herwerden, (the Lord willing;) so farewell in the Lord.

--

Here follows a letter to her father, the Graef of Bruck and Falkenstein.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Graef or Earl of Bruck and Falkenstein.

[.salutation]
Friend,

I wish your salvation,
and the Lord reward you good for the evil that you
showed unto me and my friends the last night,
if it be his will.
But since you are but a mortal man, one that must give an account, in common with all,
to the immortal God, let me a little expostulate with you.

By what law are men not scandalous, under no proscription, harmless strangers,
about lawful occasions, and men, not vagabonds, but of good quality in their own country,
stopped, menaced, sent back with soldiers, and that at sunset,
exposed to the night in an unknown country, and therefore forced to lie in the fields?
I say, by what law are we judged, yes, thus punished, before heard?
Is this the law of nations, or nature, or Germany, or of Christianity?
Oh! where is nature?
where is civility?
where is hospitality?
But where is Christianity all this while?
Well, but we are Quakers: Quakers!
What is that for a name?
Is there a law of the empire against that name?
No. Did we own it?
No. But if we had, the letters of that name neither make up drunkard, adulterer, thief,
murderer, nor traitor: why so odious then?
what harm has it done?
why could Jews pass just before us, that have crucified Christ,
and not Quakers that never crucified him?
But ignorance is as well the mother of persecution as superstition:
and the false Christian, and the false Jew have but one father.

But argumentum ad hominem my friend, bear with me a little.
Are you a Christian?
How can you be rude, uncivil, and persecute then?
You are to love enemies, not abuse friends, harmless strangers.
Well, but this life is dead, this doctrine antiquated, Jesus Christ turned out of doors,
I perceive.

What are you for a Christian?
A Lutheran?
Yes. Can you so soon forget the practices of the Papists,
and with what abhorrence your ancestors declared against such sort of entertainment?
Were not they despised, mocked, and persecuted?
And are their children treading in the steps of their old enemies?
Friend, it is not reformed words, but a reformed life that will stand you instead.
It is not to live the life of the unregenerate, worldly-minded, and wicked,
under the profession of the saints`' words, that will give an entrance into God`'s rest.
Be not deceived, such as you sow, such you must reap in the day of the Lord.
You are not come to the Berean state that tried all things,
and therefore not noble in the Christian sense.
The Bereans were noble, for they judged not before examination.

And for your saying, "`We need no Quakers here;`"--I say, under favour, You do:
for a true Quaker is one that trembles at the word of the Lord,
that works out his salvation with fear and trembling,
and all the days of his appointed time waits in the light and grace of God,
till his great change comes.
One that takes up the daily cross to his will and lusts,
that he might do the will of God manifested to him by the light of Jesus in his conscience;
and according to the holy precepts and examples in the Holy Scriptures of Truth,
laid down by Jesus and his followers for the ages to come.
Yes, he is one that loves his enemies rather than fears them;
that blesses those that curse him, and prays for those that despitefully treat him;
as God knows we do for you.
O that you were such a Quaker!
Then would you rule for God,
and act in all things as one that must give an account
to God for the deeds done in the body,
whether good or evil.
Then would temperance, mercy, justice, meekness,
and the fear of the Lord dwell in your heart, and in your family, and country.

Repent, I exhort you, and consider your latter end,
for your days are not like to be many in this world;
therefore mind the things that make for your eternal peace,
lest distress come upon you as an armed man, and there be none to deliver you!

[.signed-section-closing]
I am your well-wishing friend,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Duysburg, 3rd of the Seventh month, 1677.

--

This being done, we went to Dr. Mastricht`'s to inform him of what had passed,
who though of a kind disposition, and very friendly to us,
yet seemed surprised with fear, (the common disease of this country,) crying out,
"`What will become of this poor Countess?
Her father has called her Quaker a long time, behaving himself very severely to her,
but now he will conclude she is one indeed, and he will lead her a lamentable life:
I know,`" said he, "`you care not for suffering, but she is to be pitied.`"
We told him, that we both loved her, and pitied her,
and could lay down our lives for her, as Christ has done for us, in the will of God,
if we could thereby do her good; but that we had not mentioned her name,
neither was the letter, that he gave us to her, so much as seen or known of her father.
But still he feared that our carriage would incense
the Graef so much the more against both his daughter,
and all those serious and inquiring people up and down his country.
We answered with an earnestness of spirit,
that they had minded the incensings and wrath of men too much already,
and that true religion would never spring or grow under such fears;
and that it was time for all, who felt anything of the work of God in their hearts,
to cast away the slavish fear of man,
and to come forth in the boldness of the true Christian life; yes,
that sufferings break and make way for greater liberty,
and that God was wiser and stronger than man.

We asked him,
if there were any in that city who inquired more diligently after the way of the Lord.
He recommended us,
(as we had already been informed in another place,) to the family of the Praetor,
or chief governor of the town; whose wife, and sister more especially,
were seeking after the best things.
So we parted with him in love, and by the help of his daughter,
were conducted to this family.

We had not been long there, before a schoolmaster of Dusseldorf,
and also a minister came in, inquiring after us, having heard of us at Mulheim,
where he preached the day before to the people,
or else by the way of our attempt to visit that place,
and the entertainment we received at the hands of the Graef.
He sat down with us, and though we had already had a sweet opportunity,
yet feeling the power of God to rise, the meeting renewed.
And, O magnified be the name of the Lord! he witnessed to our
testimony abundantly in all their hearts and consciences,
who were broken into much tenderness: and certainly there is a blessed power and zeal,
stirring in that young man; yes, he is very near the kingdom.
So we took our leave of them, leaving the Lord`'s peace and blessing upon them.

It was now something past the twelfth hour of the day.
In the way to our lodging, we met a messenger from the Countess of Falkenstein,
a tender young man, near to the kingdom, who saluted us in her name with much love;
telling us, that she was much grieved at the entertainment of her father towards us,
advising us not to expose ourselves to such difficulties and hardships,
for it would grieve her heart, that any who came in the love of God to visit her,
should be so severely handled; for at some he set his dogs,
upon others he puts his soldiers to beat them:--"`But what shall I say?--that
itself must not hinder you from doing good,`" said the Countess.

We answered him, that his message was joyful to us, that she had any regard to us,
and that she was not offended with us.
We desired the remembrance of our kind love unto her,
and that he would let her know that our concern was not for ourselves, but for her.
We invited him to eat with us; but he told us, he was an inhabitant of Meurs,
and was in haste to go home.
So we briefly declared our principle and message,
recommending him to Christ the true Light in his conscience, and parted.
We went home to dinner, having neither eaten nor drank since first-day morning,
and having lain out all night in the field.

We had no sooner got to our inn, but the man was constrained to come after us,
and sat down with us, and inquired concerning our Friends, their rise, principles,
and progress, and in all things about which he desired satisfaction,
he declared himself satisfied.
Dinner being done, and all cleared, we departed that city,
being about the fourth hour in the afternoon, and for lack of accommodation,
were forced to walk eight English miles to a town called Holten,
where we rested that night.
