== Chapter XV.

Next morning, the 12th of the seventh month, about the fourth hour,
I took boat for Leuwarden; John Glaus, who had been at Fredericstadt with George Fox,
went with me.
G+++.+++ F., H. T., and T. R., with P. H., returned that day towards Amsterdam.

At Leuwarden we came about nine, and began the meeting about ten o`'clock;
which we enjoyed with peace and refreshment, several being there as in other places,
who were never at a meeting before.

The meeting being done and having refreshed ourselves with food,
we took wagon for Wiewart, the mansion-house of the family of the Somerdykes,
where J. de Labadie`'s company reside;
it being strong upon my spirit to give them a visit.
We got there about five o`'clock; and as we were walking over a field to the house,
we met a young man of that company who conducted us in.
I asked for Ivon the pastor, and Anna Maria Schurmans.
Ivon presently came, with his co-pastor: they received us very civilly; however,
they seemed shy of letting me speak with Anna Maria Schurmans, objecting her weakness,
age, taking medicine, etc.: but, putting them in mind,
how unhandsomely I was used at Herwerden six years ago by J. de Labadie their father,
who though I came a great journey to visit him and his people,
suffered me not to speak with them; they presently complied, and went in to let her know,
that such a person desired to speak with her, and quickly returned,
desiring me to come in.
But foreseeing my time would be too short for my message, the sun being near setting,
and having to go on foot two English miles of unknown way to our lodging,
I desired that they would give me an opportunity the next morning,
which they readily complied with.
So I took my leave of them, who in a friendly manner brought us a little on our way.
That night a great weight was upon my spirit, and especially the next morning;
yet my faith was in the power of God, and I had a plain sight,
that I should have a good service among them,--however, I should clear my conscience,
and my peace should rest with me.

The next morning I returned to them, and John Glaus along with me.
So soon as we came, we were brought into Anna Maria Schurmans`' chamber;
where also was with her one of the three Somerdykes.

This Anna Maria Schurmans aforesaid, is an ancient maiden, above sixty years of age;
of great note and fame for learning, in languages and philosophy,
and has obtained a considerable place among the most learned men of this age.
The Somerdykes are daughters to a nobleman of the Hague;
people of great breeding and inheritances.
These, with several other persons,
being affected with the zealous declamation of J. de Labadie,
against the dead and formal churches of the world,
and awakened to seek after a more spiritual fellowship and society,
separated themselves from the common Calvinistic churches,
and followed him in the way of a refined independency.

They are a serious, plain people, and are come nearer to Friends,
as to silence in meetings, women speaking, preaching by the Spirit,
plainness in garb and furniture in their houses.
With these two, we had the company of the two pastors, and a doctor of medicine.
After some silence, I proposed this question to them;
What was it that induced them to separate from the common way they formerly lived in?
I desired them that they would be pleased to be plain and open with me,
as to the ground of their separation; for I came not to cavil,
but in a Christian spirit to be informed.

Upon this Ivon, the chief pastor, gave us the history of J. de Labadie`'s education;
how he was bred among the Jesuits, and deserted them,
and embraced the Protestant religion; and finally,
of his great dissatisfaction with the Protestant churches of France;
and that if God would not give them a purer church,
they three would sit down by themselves;
resolving never more to mix themselves among the Babylonish assemblies of the world:
adding several solemn appeals,
concerning the simplicity and integrity of their hearts in these things.

Ivon having done, Anna Maria Schurmans began in this manner;
"`I find myself constrained to add a short testimony.`"
She told us her former life, of her pleasure in learning,
and her love to the religion she was brought up in;
but confessed she knew not God or Christ truly all that while.
And though from a child God had visited her at times,
yet she never felt such a powerful stroke, as by the ministry of J. de Labadie.
She saw her learning to be vanity, and her religion like a body of death;
she resolved to despise the shame, desert her former way of living and acquaintance,
and to join herself with this little family, that was retired out of the world;
among whom she desired to be found a living sacrifice, offered up entirely to the Lord.
She spoke in a very serious and broken sense, not without some trembling.
These are but short hints of what she said.

After she had done, one of the Somerdykes began,
in a very reverent and weighty frame of mind,
and in a sense that very well suited her contempt of the world.
She told us how often she had mourned from her young years,
because she did not know the Lord, as she desired; often saying within herself,
"`If God would make known to me his ways,
I would trample upon all the pride and glory of the world.`"
She earnestly expressed the frequent anguish of spirit she had,
because of the deadness and formality of the Christians she was bred among;
saying to herself, "`O the pride, the lusts, the vain pleasures in which Christians live!
Can this be the way to heaven?
Is this the way to glory?
Are these followers of Christ?
O no!
O God! where is your little flock?
Where is your little family, that will live entirely to you,--that will follow you?
Make me one of that number.`"
"`And,`" continued she, "`when the servant of the Lord, J. de Labadie, came into Holland,
I, among others, had a curiosity to hear him; and with several,
was deeply affected by him.
He spoke the very thoughts of my heart: I thought my heart was pricked when I heard him;
and I resolved by the grace of God, to abandon all the glory and pride of this world,
to be one of those,
who should sit down with him in a separation from
the vain and dead worships of this world.
I count myself happy that I ever met with him, and these pastors,
who seek not themselves but the Lord.
And we are a family that live together in love, of one soul, and one spirit,
entirely given up to serve the Lord; and this is the greatest joy in the world.`"

After her, du Lignon, the other pastor,
gave us also an account of his inducement to embrace J. de Labadie, but not so lively.

After him the doctor of medicine, who had been bred for a priest,
but voluntarily refused that calling, expressed himself after this manner;
"`I can also bear my testimony in the presence of God,
that though I lived in as much reputation at the university,
as any of my colleagues or companions, and was well reputed for sobriety and honesty;
yet I never felt such a living sense of God, as when I heard the servant of the Lord,
J+++.+++ de Labadie:`" adding, "`The first day I heard him, I was so struck and affected,
that I can truly say, through the good grace of God, and the conduct of the holy Spirit,
it was to me as the day of my salvation;
he did so livingly touch my heart with a sense of the true Christian worship:
upon which I forsook the university, and resolved to be one of this family;
and this I can say in the fear of the Lord.`"

P+++.+++ Ivon concluded, "`This is what we have to say concerning the work of God among us.`"

All this while I minded not so much their words,
as I felt and had unity with a measure of divine sense that was upon them.
Certainly the Lord has been among them; yes, I had a living sense in my heart,
that somewhat of the breath of life had breathed upon them;
and though they were in great mixtures, yet God`'s love was towards them.

After some silence, I began in this way; "`I come not to judge you, but to visit you;
not to quarrel or dispute, but to speak of the things of God`'s kingdom;
and I have no prejudice, but great love and regard in my heart towards you:
wherefore hear me with Christian patience and tenderness.

"`I do confess and believe, that God has touched your hearts with his divine finger,
and that his work is among you: that it was his Spirit,
that gave you a sight of the vanity and folly of this world,
and that has made you sensible of the dead religions that are in it.
It is this sense I love and honour;
and I am so far from undervaluing or opposing this tender sense I feel upon you,
that this it is I am come to visit, and you for the love of it.
And as for the reproaches that may attend you on the score of your separation,
with all the reports that therefore go concerning you, they are what I respect you for,
being well acquainted with the nature and practice
of this world towards those that retire out of it.

"`Now since I have with patience, and I can truly say with great satisfaction,
heard your account of your experiences,
give me the like Christian freedom to tell you mine;
to the end you may have some sense of the work of God in me:
for those who are come to any measure of a Divine sense,
they are as looking-glasses to each other, seeing themselves in each other,
as face answers face in a glass.`"

Here I began to let them know, how and when the Lord first appeared unto me,
which was about the twelfth year of my age, anno 1656.
How at times, between that and the fifteenth, the Lord visited me;
and the Divine impressions he gave me of himself: of my persecution at Oxford,
and how the Lord sustained me in the midst of that hellish darkness and debauchery:
of my being banished the college,
the bitter usage I underwent when I returned to my father; whipping, beating,
and turning out of doors in 1662: of the Lord`'s dealings with me in France,
and in the time of the great plague in London.
In fine, the deep sense he gave me of the vanity of this world,
of the irreligiousness of the religions of it.
Then of my mournful and bitter cries to him,
that he would show me his own way of life and salvation,
and my resolutions to follow him, whatever reproaches or sufferings should attend me;
and that, with great reverence and brokenness of spirit.
How after all this, the glory of the world overtook me,
and I was even ready to give up myself unto it,
seeing as yet no such thing as the primitive spirit and church on the earth,
and being ready to faint concerning my hope of the restitution of all things.
It was at this time that the Lord visited me with
a certain sound and testimony of his eternal word,
through one of those the world calls a Quaker, namely, Thomas Loe.
I related to them the bitter mockings and scornings that fell upon me,
the displeasure of my parents, the invectiveness and cruelty of the priests,
the strangeness of all my companions: what a sign and wonder they made of me;
but above all,
that great cross of resisting and watching against
my own inward vain affections and thoughts.

Here I had a fine opportunity to speak of the mystery
of iniquity and ungodliness in the root and ground,
and to give them an account of the power and presence of
God which attended us in our public testimonies and sufferings:
after an indirect manner censuring their weaknesses,
by declaring and commending the contrary practices among Friends,
too large to be here related.
And notwithstanding all my sufferings and trials by magistrates, parents, companions;
and above all, from the priests of the false religions in the world,
the Lord has preserved me to this day, and has given me a hundred-fold in this world,
as well as the assurance of life everlasting:
informing them of the tenderness of my father to me before and at his death;
and how through patience and long-suffering, all opposition was conquered.
Then I began my exhortation unto them, which was in this way.

That since God had given me and them a Divine sense of him, our eye should be to him,
and not to man; that we might come more into a silence of ourselves,
and a growth into that heavenly sense.
That this was the work of the true ministry, not to keep people to themselves,
ever teaching them, but to turn them to God, the new covenant teacher, and to Christ,
the great Gospel minister.
Thus John did, and thought it no dishonour, that they left him to go to Christ.
"`Behold the Lamb of God,`" said he, "`that takes away the sins of the world!`"
And even John`'s disciples left him to follow Christ.
No, John testifies of himself, that he was to decrease, and Christ was to increase.
Wherefore, I pressed them to have their eye to Christ who takes away the sin;
who is from heaven, heavenly; to see that he increase in them.
Yes, that henceforward they should know no man after the flesh.
That their knowledge of, and regard for and fellowship one with another,
should stand in the revelation of the Son of God in them; who is God`'s great prophet,
by whom God speaks in these latter days.
And if their ministers be true ministers,
they will count it their glory to give way to Christ, and that they decrease,
and Christ increase; that the instrument gives way to him that uses it,
the servant to the Lord.
Which, though it seems to detract from the ministers,
yet it was and is the glory of a true minister, that God and Christ should be all in all,
and that his will should be fulfilled.
I told them the day of the Lord God was come,
and all people must look to him for salvation:
that all people must now come to keep God`'s great sabbath, to rest from mere man,
and the spirit of man, and all men`'s thoughts, words and works;
and that if they were true believers they were at least, entering into their rest.

I closely recommended it to them,
that they might not be of those who begin in the Spirit, and end in the flesh;
for that those who should do so, and thereby break God`'s sabbath-day,
would be stoned to death, by the stone which is cut out of the mountain without hands;
yes, that should fall upon them as a millstone, and grind them to powder.
Therefore let Christ have his honour; let him preach and speak among you and in you,
and you in him and by him only, to sigh, groan, pray, preach, sing, and not otherwise,
lest death come over you: for thereby the apostacy came in, by their going before Christ,
instead of Christ going before them.

Wait in the light and spirit of judgment that has visited you,
that all may be wrought out that is not born of God;
so will you come to be born of the incorruptible seed and Word of God,
that lives and abides forever: that you may be a holy priesthood,
that offers up a living sacrifice with God`'s heavenly fire,
that God may have his honour in you all, and through you all by Jesus Christ.
And turning myself towards the Somerdykes, with a serious and tender spirit,
I thus expressed myself: "`That you should be pilgrims in the inheritance of your Father,
I have a deep and reverent sense of: O that you might dwell with him forever,
and exalt him that has so visited you,
with whom are the rewards of eternal blessedness!`"

I left the blessing and peace of Jesus among them,
departing in the love and peace of God; and I must needs say, they were,
beyond expectation, tender and respectful to us;
all of them coming with us to the outer door, but the ancient Anna Maria Schurmans,
who is not able to walk; giving us their hands in a friendly manner,
expressing their great satisfaction in our visit.
And being come to the porch, and meeting several persons of the family,
I was moved to turn about and exhort them, in the presence of the rest,
To keep to Christ, who had given them a sense of the spirit of this world,
and had raised desires in them to be delivered from it;
and to know no man after the flesh, but to have their fellowship in Christ,
union and communion with God, and one with another;
that all their worship and performances might stand in him, that he might be all in all.
Desiring that the Lord might keep them in his fear all the days of their appointed time,
that so they might serve him in their generation, in his own universal Spirit,
to his glory, who is blessed forever!

The Lord comforted my soul in this service: yes,
all that is within me magnified his holy name,
because of his blessed presence that was with us!
O let my soul trust in the Lord, and confide in him forever!
Let me dwell and abide with him that is faithful and true, and blessed forevermore!

The two pastors and the doctor came with us a field`'s length, where we took wagon;
and the chiefest of them took occasion to ask me,
If the Truth rose not first among a poor, illiterate, and simple sort of people?
I told him, Yes, that was our comfort,
and that we owed it not to the learning of this world: "`Then,`" said he,
"`let not the learning of this world be used to defend
that which the spirit of God has brought forth;
for scholars now coming among you,
will be apt to mix school learning among your simpler and purer language,
and thereby obscure the brightness of the testimony.`"
I told him, it was good for us all to have a care of our own spirits, words and works,
confessing what he said had weight in it; telling him,
it was our care to write and speak according to the Divine sense,
and not human invention.
So in a very sober and serious manner we parted, being about the twelfth hour at noon.

This night about ten o`'clock we got to Lippenhausen,
where there is a little meeting of Friends, being about twenty-five English miles.

The next morning, the 14th, we had a blessed meeting among Friends;
many of the world came in, were very serious and well affected;
one whereof was a magistrate of the place.
The Lord pleads his own cause, and crowns his own testimony with his own power.
There is likely to be a fine gathering in that place.
After dinner we took wagon for the city of Groningen,
where we arrived at eight o`'clock at night, being about twenty-five English miles.

The next morning we had a meeting among Friends of that city,
where resorted both collegians and Calvinist students, who behaved themselves soberly:
the Lord`'s power was over all, and his testimony stands.
When meeting was ended they went out; and as I was concluding an exhortation to Friends,
there came in a flock of students to have had some conference with us:
but having set the time of our leaving the city,
we recommended them to the universal love of God,
promising them some books of our principles;
with which they expressed themselves satisfied, and civilly parted from us.
After dinner we took boat for Delfzyl, and came there about six o`'clock at night.
