== Chapter XVI.

The next morning about seven o`'clock, being the 16th of the seventh month,
we took boat for Embden, which is about three leagues.
On board of that vessel, it came upon me to write a letter to Friends in England,
concerning the Separatists,^
footnote:[This alludes to Wilkinson, Story, Rogers, and their followers,
who had raised a schism in the Society on the subject of church discipline.]
and their spirit of separation, which has several times been opened unto me,
and had remained some days upon my spirit.
The letter follows.

[.embedded-content-document.letter]
--

[.letter-heading]
To Friends everywhere, concerning the present Separatists,
and their spirit of separation.

[.salutation]
Friends and brethren!

By a mighty hand and by an outstretched arm,
has the Lord God everlasting gathered us to be a people,
and in his own power and life has he preserved us a people unto this day:
and praises be to his eternal name! no weapon that has yet been formed against us,
either from without or from within, has prospered.

Now this I say unto you,
and that in his counsel who has visited us;--whoever
goes out of the unity with their brethren,
are first gone out of unity with the power and life of God in themselves,
in which the unity of the brethren stands; and the least member of the body in the unity,
stands on the top of them, and has a judgment against them.
Unto which judgment,
of both great and small among the living family that in unity are preserved,
they must bow before they can come into the unity again.
Yes, this they will readily do,
if they are come into unity with the life and power of God in themselves;
which is the holy root, that bears the tree, the fruit, and the leaves;
all receiving life and virtue from it, and thereby are nourished unto God`'s praise.

And let all have a care how they weaken that,
or bring that under the exaltation and high imagination of those,
against whom it is revealed.
For I feel this unruly spirit is tormented under the stroke and judgment of the power,
and in its subtlety is seeking occasion against the instruments,
by whom the power gave it forth.
Let all have a care how they touch with this spirit in those workings;
for by being one with this spirit in judging those who have been faithful,
according to the gift of wisdom they have received from God,
they will feed it and fortify it,
and in the end come to be one with it against the power itself;
and at last run out and become open enemies and despisers,
for whom is reserved the blackness of darkness forever, unless they repent.

Wherefore,
all that labour for the restoration of those who are out of unity with the brethren,
let them be such as are of a sound mind themselves: else what will they gather to?
or, what will they gather from?
And let them labour in the simplicity, integrity, love,
and zeal of the power that first gathered us to God.
For that which is rightly gotten will endure,
but that which is obtained by the contrivance, interest and persuasions of men,
gets no further than man, and is of the flesh; and what is of flesh is fleshly,
and shall never inherit the kingdom of God.

Therefore let none look out of the Seed for help; for all power is in it,
and there the true light and judgment stand forever;
and that Seed only has God ordained to bruise the serpent`'s head.
They that would save it, and those that would bruise it by any other thing,
are breakers of God`'s great ordinance, and fly to Egypt for strength.
For it is David the stripling, that shall be too hard for Goliath the giant;
and that not by Saul`'s armour,
but with God`'s living little stone cut out of the mountain without hands;
without man`'s invention and contrivance.
This has wrought all our mighty works in us, and for us to this day!
Wherefore let us be still, and trust and confide therein forever.
Let none look back, faint, or consult; for if they do, they will darken their pure eye,
and lose their way,
and into the eternal rest of the flocks of the companions will never come.

Brethren, the judgment given forth against this spirit,
and against all those who have resisted our love and forbearance that are joined to it,
must stand, and all that are out of our unity with the judgment are judged by it.
Therefore, as all would stand before the Lord and his people,
let not this spirit be reasoned withal; enter not into proposals and articles with it,
but feed it with judgment; that is God`'s decree: so may the souls that are deceived,
come by the right door into the heavenly unity.

My brethren look forwards, and lift up your eyes;
for the fields are even white unto harvest, up and down the nations.
Remember the great name of the Lord,
and behold the great work that he is doing before all people;
whose saving health is visiting the world,
and whose eternal word and testament is going forth to gather the nations.
Let that that will be unjust, be unjust still; let the dead bury the dead;
let us all who have received the gift from God, wait in deep humility,
to be raised up and empowered by him, more and more,
to eye and prosecute his universal service in the world;
to whose appearance the kings and kingdoms of the Gentiles shall bring their glory.
Which noble work, had those who are gone into the separation but laid deeply to heart,
they would never have sat at home, murmuring, fretting,
and quarrelling against the comely and godly order and practice of their brethren:
but love, peace, and joy had filled their hearts,
and not the troubler and accuser of the brethren; who has opened an evil eye in them,
and begotten them into a discontented self-separating mind, and this image they bear,
and the pure eye sees it.

O let none tempt the Lord!
Let none provoke the eyes of his jealousy:
let us all dwell in that Divine sense that he has begotten in us; where our love,
as a fresh and pure stream, will always flow to God and to one another.
Here, all his ways are pleasantness, and all his paths are peace;
for where he keeps the house, who is Prince of peace,
he will keep all in his heavenly peace.
We are but as one family, and therefore we have but one Lord and Master.
We are but as one flock, and we have but one heavenly Shepherd to hear,
who goes before us, and gives us eternal life to follow him.
If any are offended in him or in his, it is their own fault;
if they faint and grow weary, we are truly sorry;
if through unwatchfulness the enemy has entered, begotten coldness to the brethren,
and carelessness of embracing the opportunities by which the unity is renewed and increased;
so that what is done by the brethren without them, is looked upon,
first with a slight eye, and then with an evil eye; which begets distance,
and this distance, in time, a separation, and separation continued, brings forth enmity,
and this enmity, death itself; we are in our spirits truly grieved for them.
However, the judgment of God must stand against them and that spirit that leads them,
in which they gather not to God but to themselves.
Woe to them that strengthen their hands and despise counsel,
they will have much to answer for before the Lord.
I feel a slighting, scornful, laughing spirit,
often flying at me with its venomous sting; but the Seed of life is over it,
and the Lord God will destroy it.

Wherefore, Friends, in all places where this spirit has had entrance,
keep sound judgment upon it, if you will keep your garments clean:
and enter not into disputes and contests with it; it is that it seeks and loves;
but go on in your testimony and business for the Lord,
in the Lord`'s peaceable power and spirit;
and his blessings and presence of life shall be with you;
and in multiplying he shall multiply you; for no good thing will he withhold from you.
We can say it of a truth, '`God is good to Israel,
and to all that are of an upright heart.`' And let us be of good cheer,
for it is God`'s determination that the house of David shall grow stronger and stronger,
and his branch shall increase and spread, and of his government,
kingdom and dominion there shall be no end.

Your faithful friend and brother in the service of our dear Lord,

[.signed-section-signature]
William Penn.

[.postscript]
====

P+++.+++ S. God`'s blessed work increases and prospers in these lands,
magnified be his everlasting name.

====

[.signed-section-context-close]
From on board the passage-boat, between Delfzyl and Embden,
the 16th of the Seventh month, 1677.

--

We arrived at Embden about the eleventh hour.
This is the city where Friends have been so bitterly and barbarously used,
the like has scarcely been known in any place where Truth has broken forth in our day;
they having here been banished some thirty, and some forty times and above.
The first family that received Truth in this city, was doctor John William Hasbert,
a physician, and his wife;
at whose house also the first meeting was set up among Friends,
to wait upon the Lord by way of public testimony: they are now both dead,
but the memory of their fidelity is as precious ointment among the righteous.

They were with me at a meeting six years ago, in this city; and I remember,
the power of the Lord had that operation upon them, that I said to B. F. and T. R.,
then with me,
it will not be long before they will publicly own and bear testimony in this place:
and about three months after, he came forth, and she about a year after him.
And from their fidelity and integrity,
notwithstanding all the sore and bitter tempests of persecution, a fine meeting sprang;
but at this day they are scattered, being still sent away as fast as they return.^
footnote:[After William Penn`'s first visit to Embden in 1671,
he addressed Dr. Hasbert an encouraging letter,
earnestly recommending him to persevere in the path of duty cast up before him.
Stephen Crisp,
who many times visited these parts of the continent
of Europe in the character of a minister of the Gospel,
gives the following interesting account of Dr. Hasbert and the Friends in Embden:
"`I had a meeting in his house upon the first-day of the week, in the first month, 1673;
where many people of various persuasions heard the Truth declared,
in great plainness and simplicity; and after some time,
those that were convinced were drawn in love to God to assemble together,
to worship God in spirit and in truth,
and in the silence of that fleshly wisdom that can speak when it wish,
and say what it wish.
At the first, they sat down about ten persons in Hasbert`'s house to wait upon the Lord:
and when this was noised about the city,
the wicked one stirred up the priests and rulers against them;
and they stirred up the rude and ignorant people to assault them, mock, reproach,
and revile them; and the rulers fell quickly to fining, imprisoning, threatening,
and banishing those weak and tender plants, in an almost unheard of manner.
They banished some sixteen or twenty times, spoiling all they had, save their clothes,
and at last fell upon them also; taking away their coats, boots, gloves, aprons, etc.,
and driving them through the streets almost naked,
aboard the ships that were to carry them away: all which and much more,
by the mighty power of the Lord, did these innocent,
harmless lambs bear with great patience and quietness,
and were not dismayed at all at these cruelties: for the Lord had regard to his name,
and to their innocent cry, and supported them, and does support them;
and they have found it true, that those who wait upon the Lord renew their strength.
Blessed be the Lord forever!`" [.book-title]#--Crisp`'s Memoirs,# p. 79. Persecution, however,
did not cease as regards the Friends in this place for nine
years after this visit was paid them by William Penn.
It is a singular circumstance,
that when the magistrates began to see their true interest,
and the error of their cruel policy,
they actually came to the resolution of inviting the people called Quakers,
both in Holland and in England, to come and settle among them, promising them protection,
and that they should be well received.
See [.book-title]#Besse`'s Sufferings of Friends.#]

We visited his mother`'s family;
where we found three of his sisters in the love of Truth,
his fourth sister being also a Friend, and is wife of John Claus, living at Amsterdam.
We had a little sweet comfortable meeting with them.
After it, I returned to my lodging, and as I was writing to Doctor Andrews,
president of the council of state,
who is reported to have been the author of this cruelty to our Friends,
a burden came upon me; my writing would not serve the turn, I must go myself;
and in the fear and name of the Lord,
plead the innocent and suffering cause of our Friends with him.
So away we went to his house.
He was at first astonished to see what manner of men we were; but after a little time,
he comported himself with more kindness than we expected at his hand.
I asked him,
if he and the senate had not received a letter in
Latin from an Englishman about two years since,
concerning their severity towards the people called Quakers?
He told me he had: I replied, I was the man;
and I was constrained in conscience to visit him on their behalf;
and I could not see how he, being a commonwealth`'s-man and a Protestant,
could persecute.

I pleaded the unnaturalness, the unchristianity, and imprudence of such proceedings,
and pressed our reasons earnestly, but tenderly upon him.
He assaulted us with several objections; but, blessed be the Lord,
they were mostly fictitious, and therefore easily removed and answered.
He also promised me,
that if I would write to the senate a remonstrance of the case of our friends,
and express my request to them, and enclose it to him,
he would both present it and get it to be read;
and make it appear that he was not so much our enemy as we looked upon him to be.
I promised to send him some books, containing a defence of our principles,
which were accordingly put into the hands of Elizabeth Hasbert,
to deliver to him in my name.

Having taken our leave of the old woman and her daughters,
and a man Friend residing in that city,
and left the blessings and peace of our God among them, we took ship for Lier,
where we arrived the next morning.
From there we took wagon for Bremen, where we came safely, through the Lord`'s goodness,
on the 18th; and met our friends and companions, George Keith and Benjamin Finely,
who were come there some hours before us from Amsterdam.
In this city, there is a work of the Lord begun, though yet obscurely:
we had a travail upon our spirits,
that the blessed and precious Truth of our dear Lord and Master,
might find a place to rest its foot upon.

To that purpose we wrote to two ministers, under some suffering from their brethren,
because of their great zeal against the formality
and deadness of the so called reformed churches.
This we sent by a merchant, whom we formerly met at Herwerden.
With some difficulty we got to them, but the person chiefly struck at,
was shy to speak with us: his reason was this; it was known that we were in town,
and it was one of the accusations against him,
that he was a fosterer of all the strange religions that came through the town.
Also he was then actually under process,
and that the people who had heard of the innocency of his cause,
conceived a prejudice against our name, though it might be without cause.
Therefore he could not at present confer with us;
and said he was sorry for it with all his heart,
but what we should say to his brother should be the same as if it had been said to him;
to whom he referred us.

However, I took hold of his arm and said, "`I have this message to deliver to you,
that I may disburden myself before the Lord,`" which was this:
"`Mind that which has touched your heart; let that guide you, and do not you order that:
consult not with flesh and blood, how to maintain that cause,
which flesh and blood in your enemies persecutes you for.`"
He answered, "`Rather than I will betray that cause, or desert Christ,
by God`'s strength, they shall pull my flesh off my bones.`"
So he left us in his house, and truly we had a good time with his companion,
the other minister, about three hours, testifying unto him,
that the day was come and coming,
in which the Lord would gather out of all sects that stand in the oldness of the letter,
into his own holy Spirit, life, and power;
and that in this the unity of faith and bond of peace should stand.
And therefore,
that he and all of them should have an eye to the spirit of God in themselves;
that being turned to it, they might speak from it; and that therein,
they would glorify God, and be edified.
So we parted, leaving the man in a sensible and savoury frame.
We visited the merchant twice, and had a very good time with him;
the man is of a loving and sensible spirit, and the love of God opened our hearts to him.

We also visited Doctor Johannes Sophronius Cozack, an odd compositum of a man.
He has had great and strange openings; has written several scores of tracts;
is a great enemy to priests, and in society with none: of a merry,
yet of a rough disposition, without any method or decency in his clothes, food,
furniture, and entertainment.
He is seventy-seven years of age, yet of wonderful vigour and acuteness.
We were twice with him, and we have reason to think he was as loving to us as to anybody.
And truly, he did show at parting, some serious and hearty kindness:
but we could fasten little upon him as to God`'s power,
or any inward sense of us or our testimony;
yet we had little to object against what he said too;
no some things were very extraordinary.

From him we went to Doctor Belingham, an English physician,
a man of lowly and tender spirit, who received us in much love, lamenting,
when we left him, that he had no more time with us.

At the inn we had frequent opportunity to declare the way of Truth,
and we must needs say, we were heard with patience and sobriety;
particularly by a doctor of law, who lodged at the house,
and an ancient man of Kiel in Holstein.
We left books among them all;
and in the love and fear of God we took our leave of them on the fifth-day after dinner,
and begun our journey towards Herwerden, the court of the Princess;
where we arrived on seventh-day the 22nd in the morning,
every way well through the mercies of the Lord.
We sent to inform her of our arrival,
and to know what hour it would be convenient for us to visit her;
who returned us this answer,--that being then employed in the business of her government,
it would be the second hour in the afternoon before she could be at leisure.

The time being come, we went to visit her,
and found both her and the Countess ready to receive us;
which they did with much love and tenderness.
I observed them to be much lower in their spirits than ever,
and that our former opportunities had had a blessed effect upon them.
That afternoon was employed in the narrative of our travels,
which they heard with great attention and refreshment.
The whole discourse ended with a precious little meeting.
The house being clear of strangers, they both earnestly pressed us to sup with them,
which being not well able to decline, we submitted to.

At supper, the power of the Lord came upon me, and it was a true supper to us,
for the hidden manna was manifested and broken among us; yes,
a blessed meeting it proved to us.
O, the reverent tenderness and lowly frame of spirit that appeared this evening,
both in the Princess and Countess.
The Frenchwoman we found greatly improved, both in her love and understanding; yes,
she was very zealous and very broken, and was always with us on these occasions.
After supper we returned to the Princess`'s chamber,
where we stayed till it was about ten at night.
At parting, I desired the Princess would give us such another opportunity next day,
being the first-day of the week, as we had the last time we were with her:
she answered me, "`With all my heart: but will you not come in the morning too?`"
I replied, "`Yes, willingly; what time will you be ready to receive us?`"
she answered, "`At seven o`'clock.`"

About seven o`'clock the next morning we came; about eight the meeting began,
and held till eleven: several persons of the city, as well as those of her own family,
being present.
The Lord`'s power very much affected them,
and the Countess was twice much broken while we spoke.
After the people were gone out of the chamber,
it lay upon me from the Lord to speak to them two, the Princess and the Countess,
with respect to their particular conditions, occasioned by these words from the Princess,
"`I am fully convinced: but O, my sins are great!`"

While I was speaking, the glorious power of the Lord wonderfully rose, yes,
after an awful manner, and had a deep entrance upon their spirits;
especially the Countess`'s, so that she was broken to pieces: God has raised,
and I hope fixed his own testimony in them.

We returned to our inn, and after dinner we came back to the second meeting on that day,
which began about the second hour in the afternoon: and truly, the reverent, blessed,
sure word of life was divided aright,
and a precious sense of Truth was raised in the meeting.
There came more of the city than in the morning,
and we were much comforted in the Lord`'s power that was with us.
For the Truth had passage, and the hungry were satisfied,
and the simple-hearted deeply affected.

This day at both meetings was one of the Princess`'s women,
who never was at meeting before; and she, though very shy of us the last time,
became tender and loving to us;--she was truly reached.
Magnified be the name of the Lord, whose presence was with us, and whose arm stood by us!
After meeting, the Princess pressed us to stay and sup with her,
pleading the quietness of the family, and that they were alone.
At supper, as the night before, it was upon me to commemorate the goodness of the Lord,
his daily providences, and how precious he is, in the covenant of light,
to the dear children and followers of the light.
Great was the reverence and tenderness,
that was upon the spirits of both Princess and Countess at that instant.
After supper, we returned to the Princess`'s chamber,
where we spent the rest of our time, in holy silence, or discourse,
till about the tenth hour, and then we repaired to our quarters.

Next morning about eight o`'clock, we returned to the court,
where the Princess and Countess were ready to receive us.
The morning was employed in a very serious relation, concerning the affairs, practice,
and sufferings of our Friends in England, with which they seemed greatly affected; when,
about the eleventh hour, the rattling of a coach interrupted us.
The Countess immediately stepped out to see what was the matter;
and returned with a countenance somewhat uneasy, telling us that the young Princes,
nephews to the Princess and the Graef of Donau, were come to visit her.
Upon which I told them, we should withdraw, and return to our lodging; but entreated,
that forasmuch as we were to depart that night with the post-wagon,
we might not be disappointed of a farewell meeting with them; and the rather,
for that I had a great burden upon my spirit: which they readily complied with,
telling me, these persons would only dine and be gone.
As we went to the door, the Countess stepped before us, and opened it for us;
and as I passed by, she looked upon me with a weighty countenance,
and fetched a deep sigh, crying out,
"`O the cumber and entanglements of this vain world! they hinder all good.`"
Upon which, I replied, looking her steadfastly in the face,
"`O come you out of them then!`"

After we had dined at our lodging,
something being upon me to write to the professors of religion of that country,
I went up to my chamber, that I might be the more retired.
Just as I was about the conclusion of the paper,
came the steward of the house of the Princess, with this message,
that the Princess entreated us to come to her;
for the Graef of Donau had a great desire to see us, and to speak with us.
This brought a fresh weight and exercise upon us; but committing all to the Lord,
and casting our care upon him, we went.

Being arrived, the Graef approached us in French:
at first he took no great notice of our unceremonious behaviour,
but proceeded to inquire of our success in our journey,
and what we found answering our journey and inclinations.
Then we fell to points of religion, and the nature and end of true Christianity,
and what is the way that leads to the eternal rest.
After some short debate about complete sanctification in this life,
we both agreed that self-denial, mortification, and victory was the duty,
and therefore ought to be the endeavour, of every sincere Christian.

From this, I fell to give him some account of my retreat from the world,
and the inducements I had thereto, and the necessity of an inward work;
with which he seemed much pleased.
After this, he fell to the hat, etc. This chokes, and the rather, because it tells tales.
It tells what people are; it marks men for separatists; it is blowing a trumpet,
and visibly crossing the world; and this, the fear of man,
(greatly prevalent with too many serious people in that land,) cannot abide, starts at,
and runs away from.
Howbeit, the Lord enabled me to open the thing to him: as,
that it was no plant of God`'s planting, but a weed of degeneracy and apostasy;
a carnal and earthly honour, the effect, feeder, and pleaser of pride and of a vain mind;
and that no advantage redounded to mankind by it;--and how could they,
who ought to do all to the glory of God, use that vain and unprofitable custom,
which cannot be done to the glory of God?
I entreated him seriously to consider with himself the rise and end of it;
from where it came, what it pleased, and what that was which was angry if it had it not.

I also told him of the sincere and serviceable respect,
which Truth substitutes in place thereof:
and I exhorted him to simplicity and poverty of spirit:
to be like that Jesus whom he professed to be his Saviour,
whose outside as well as doctrine pleased not the Jews;--and so we parted.
He took his leave of the Princess, and then of us, with great civility.

After he was gone, the Princess desired us to withdraw to her bed-chamber,
and there we began our farewell meeting.
The thing lay weighty upon me, and that in the deep dread of the Lord;
and magnified be the name of the Lord, he overshadowed us with his glory.
His heavenly, breaking, dissolving power richly flowed among us,
and his ministering angel of life was in the midst of us.
Let my soul never forget the divine sense that overwhelmed all.
At that blessed farewell I took of them,
much opened in me of the hour of Christ`'s temptation, his watchfulness,
perseverance and victory; also about the ten virgins, what the true virgin was,
the true oil, and lamp; and what the bridegroom, his door, chamber, and supper;
and in the conclusion of that stream of heavenly melting love,
with which we were all deeply affected, I fell upon my knees,
recommending them unto the Lord, with strong cries to him for their preservation,
and besought the Lord`'s presence with us,--and so ended.

After some pause I went to the Princess, and took her by the hand,
which she received and embraced with signs of a weighty kindness, being much broken.
I spoke a few words apart to her,
and left the blessing and peace of Jesus with and upon her.
Then I went to the Countess, and left a particular exhortation with her,
who fervently besought me to remember her, and to implore the Lord on her behalf.
From her, I went to the Frenchwoman,
and bid her be faithful and constant to that which she knew; she was exceedingly broken,
and took an affectionate leave of us.

Then I spoke to the rest and took leave severally of them; my companions did all the like.
They followed us to the outer room; and there, it was upon me to step to the Countess,
and once more to speak to her, and to take my leave of her;
which she received and returned with great sense, humility, and love.
So turning to them all, my heart and eye to the Lord, I prayed that the fear, presence,
love and life of God, with all heavenly blessings, might descend and rest upon them,
then and forever.

We went to our lodging, cleared the house, exhorted the family, left books,
and then took wagon for Wesel, about two hundred English miles from Herwerden.
We rode three nights and days, without lying down on a bed, or sleeping,
otherwise than in the wagon, which was only covered with an old ragged sheet.
The company we had with us, made twelve in number, which much straitened us:
they were often, if not always, vain, even in their religious songs,
which is the fashion of that country, especially by night;
they call them Luther`'s songs, and sometimes psalms.
We were forced often to reprove and testify against their hypocrisy;
to be full of vain and often profane talk one hour, and sing psalms to God the next,
we showed them the deceit and abomination of.
We passed through several great towns by the way, Lipstadt, Ham, etc.
Many discourses we had of Truth, and the religion and worship that was truly Christian,
and all was very well; they bore what we said.

But one thing was remarkable, that may not be omitted:
I had not been six hours in the wagon,
before a heavy weight and unusual oppression fell upon me; yes,
it weighed me almost to the grave, that I could almost say,
my soul was sad even unto death.
I knew not at present the ground of this exercise:
it remained about twenty-four hours upon me.
Then it opened in me, that it was a travail for the seed of God,
that it might arise over all in them I had left behind,
and that nothing might be lost but the son of perdition.
O the strong cries, and deep agonies,
many tears and sincere bowings and humblings of soul before the Lord,
that his holy sense, which was raised in them, might be preserved alive in them,
and they forever in it! that they might grow and spread,
as heavenly plants of righteousness, to the glory of the name of the Lord.
