== Chapter XVII.

The narrative from the 27th of the seventh month,
to the 9th of the eighth month inclusive,
is inserted in the following letter to the Countess of Homes.

[.embedded-content-document.letter]
--

[.letter-heading]
For Anna Maria de Homes, styled Countess of Homes, at Herioerden in Germany.

[.salutation]
My dear friend!

O that you may forever dwell in the sweet and lender sense of that Divine love and life,
which has visited your soul, affected and overcome your heart!
O tell me, has it not sometimes raised your spirit above the world,
and filled you with fervent and passionate desires, yes,
holy resolutions to follow Jesus, your blessed Saviour,
who has given his most precious blood for you, that you should not live to yourself,
but to him that has so dearly purchased you.

O the retired, humble, reverent frame I have beheld you in,
when this blessed life has drawn you into itself,
and adorned and seasoned you with its own heavenly virtue;
beautifying your very countenance,
beyond all the vain and foolish ornaments of the wanton daughters of Sodom and Egypt;
for therein are charms not known to the children of this world.

O that this holy and chaste life may be always precious with you! and
that you may be forever chastely kept in the love and fellowship of it!
That out of this world`'s nature, spirit and practice, you may be redeemed by Him,
who is the way, the truth, and the life; who, as you watch with holy vigilance,
will not only daily manifest the devices of the enemy to you, but save you from him.
For Christ`'s work in you is your sanctification, as it is in him, his Father`'s will;
as he said of old to his disciples, '`This is the will of God,
even your sanctification.`'

My dear beloved friend, be steadfast, immovable, without wavering;
and work out your great salvation with fear and trembling;
and lose not that sweet and precious sense, which the Lord has begotten in you:
it is soon lost, at least weakened, but hard to recover.
Wherefore, let not the spirit of the world in any of its appearances, vain company,
unnecessary discourse or words, or worldly affairs,
prevail upon the civility of your nature; for they will oppress the innocent life,
and bring grievous weights and burdens upon your soul,
and prolong the coming of the Lord, whom you look for,
and put the day of your redemption afar off.
O beware of this compliance!
Let me put you in mind of that sensible resolution,
so frequently and so passionately repeated by you; '`Il faut que je rompe.
Il faut que je rompe.`' Ah! this speaks a weight, this weight a sense,
and this sense a strong conviction.
Now, be assured,
that till obedience be yielded to that present manifestation and conviction,
the good things desired and thirsted after can never be enjoyed.

Wherefore, my dear friend, be faithful,
and watch against the workings of the spirit of this world in yourself;
that the nature and image of it in all things may be crucified,
that you may know an entire translation, with holy Enoch, and walk with God.
Jesus, the holy Light, is this power of God, that kills and makes alive;
and he is the heavenly Vine too, if you abide in him, you will bring forth fruit:
but if you abide not in him, you will not bring forth that fruit,
in which his heavenly Father only can be glorified.
O see what the mind daily abides in!
My soul is even ravished with the sense of that holy
and quiet habitation! '`In the world,`' says he,
'`you shall have trouble; however, be of good cheer, I have overcome the world:
I am not of the world.`' As if he had said: '`I am not of the world`'s ways, worships,
customs, or fashions; for whatever is of the nature and spirit of this world,
has no part in me; and as I am not of this world, neither are you of this world;
for I have chosen you out of the world; out of the inventions,
out of the worships and fashions of the world.
You are to leave them all, to come out of them all,
and live and walk as pilgrims in the world;`' that is, strangers; to what?
To the life and practice of the world; not using,
but renouncing the vain customs and ceremonies, yes, the whole conduct of the world;
remembering that '`the friendship of this world is
enmity with God.`' And what '`if the world hate you,
it hated me first;`' and '`the disciple is not greater than his master,
nor the servant than his Lord:`' if you were '`of the world,
the world would love you,`' and not reproach and persecute you;
for the world loves its own.
O my dear friend, that you may be perfectly sensible what it is, not to be of this world.

But there is yet a further mystery in these words, not discerned of many,
in whom some tenderness and inquiry is begotten, much less of the worldly Christians.
This world has a false earth and a false heaven, a false foundation, and a false joy:
not only gross wickedness, but iniquity in a mystery, inwardly and outwardly.
The false prophet, and dragon, and all their offspring are here concerned.
This is their world, that must be burnt with fire, that Christ is not of,
nor his true disciples.
The light of Jesus discovers it!
He is that spiritual Solomon that gives true judgment, and saves the living child,
the true birth; giving it to the right mother, and not to the false pretender.
All that hear his voice and follow him, shall receive true light, discerning,
and judgment, to whom all judgment is given; they shall know his voice from man`'s.

There are two trees, of differing natures, that have contrary fruits and leaves.
The one is the tree of life, which is Christ; the other the tree of death,
and that is Satan.
The fruit of the one gives life; the fruit of the other brings death;
the leaves of the first heal; the leaves of the last poison.
Many that discern the tree, cannot clearly distinguish the branches:
and those that see many arms and branches, cannot distinctly behold the fruit,
much less the leaves.
This comes by the gradual discoveries and revelations of the light of Jesus,
the Word of God, as it is daily received and daily obeyed.
Yes, and that Word is the axe and sword of the Almighty, to cut it down:
daily feel the strokes of this eternal searching
Light and Word at the very root of this corrupt tree,
this evil one and his corrupt nature, works and effects.
For which end Jesus Christ is come, and therefore is called a Saviour,
which is little known in truth to the Christians of this world.

Ah! my dear friend, you know this Word, yes, you have felt it.
O hide it in your heart! treasure it up in your soul, and love it,
and abide with it forever.
Alas!
Where should you go?
He has the words, and is the Word of eternal life: daily, therefore, watch and wait,
that you may be grafted more into him; that you may live and grow by his virtue and life;
and that he may grow in your heart, as among the first Christians,
the holy followers of the persecuted Jesus.
And when he searches your wound, and cuts away your dead flesh; yes,
when he separates between the soul and the spirit of this world,
and divides between joints and marrow; when he cuts off the right hand,
and plucks out the right eye; watch unto prayer,
and pray that you may endure Keep the holy patience of this pure and living Word;
and this very Word will keep you in the hour of your sharpest trials,
and sorest tribulations!
All virtue is in him!
He is a tried Word, a sure refuge; the staff and strength of the righteous in all ages.
He was David`'s teacher and buckler; a light to his feet, and a lantern to his paths.
Walk in the light thereof, and you shall not stumble: in this Word is life,
(as in the root,) and this life is the light of men.
They that receive and love the light of it,
will therein receive Divine life from it to live to God.
This is the bread of God that comes from God, and feeds and leads up to God:
by this only, that which is born of God lives, and is nourished.
This is that carcass to which the wise eagles gather; and see you gather to no other,
and feed on no other.
This is that hidden manna that comes from heaven; that feeds God`'s Gospel Israel.
The world has a manna, but it perishes; but this endures forever: for it is not of man,
nor from man, but immortal, and from God;
hid from the knowledge of all the vain Christians in the world;
so that the Israel of God can say to the children of this world,
and that in truth and righteousness,
'`We have bread to eat that you know not of.`' For this manna wait daily,
that you may be strengthened in your wilderness travel to the land of eternal rest.

Wherefore, '`labour not for the bread that perishes,`' that is,
the bread of man`'s inventing and making, which comes from below, and profits not,
because it gives not life eternal.
But labour, my dear friend, for the bread that never perishes, that endures forever,
and that gives life eternal to all that feed upon it.
O cast your care upon this Word, love it and dwell with it; wait daily upon it,
hear its voice only, and follow it;
for it brings the soul to the eternal habitation of rest and glory.
Yes, when all flesh shall wither, and the beauty thereof fade away, this Word,
and they that are grafted into it, shall abide forever.
O that this may be your choice, and it shall be your diadem,
and your eternal crown of glory!

These are the fervent desires, and these the daily prayers of my soul,
to the God of my salvation for you; not only that nothing in you may be lost,
besides the son of perdition; but that you may cast off every weight and burden,
and that sin that does so easily beset you, that grieves, bows, and oppresses you,
under the heavy weight of which you groan and sigh,
that your Redeemer would come from Zion to deliver you.
Give not heed to the enemy, the false accuser,
who seeks to devour that which is begotten of God in you;
neither look upon your own sins, burdens, or weaknesses; but lift up your head,
and look to Jesus, the author of your blessed visitation,
and wholly hunger and thirst after Him, the spiritual brazen serpent,
that heals and relieves all who in faith and full assurance look to him.
Lack of looking to him, hearing and obeying him and having true faith in him,
is the cause both of all the presumption and despair that are at this day.
He did no mighty things of old in those places where they believed not.

O faint not, look not back, remember the holy ancients, the holy pilgrims of faith,
the royal generation of heaven! Heb. 11.
You believe in God,
believe also in him for the work`'s sake that he has already wrought in you:
he will minister to you, as he was ministered unto by his Father`'s angels,
in the hour of his abasement and great temptation.
Watch, and be faithful, and you shall be a noble witness for the Lord.

Once more let me expostulate with you.
Would you overcome the enemies of your soul`'s peace,
and enjoy the delightful presence of the Lord with you?
Then keep nothing back; let nothing be withheld that he calls for:
remember that Saul of old lost his kingdom, for keeping that alive,
which he should have slain; and you know what befell Ananias and Sapphira outwardly.
But be like the poor widow of old, that gave more into the treasury than all the rest,
because they reserved the greatest part to themselves; but she gave all she had.
O blessed are they that make no bargains for themselves; that have no reserves for self,
neither consult with flesh and blood, nor in any sense conform to the least ceremony,
which is born of them; but that submit their wills, in all things, to the Lord`'s,
that they may be made perfect through sufferings.

Read me in the mystery of life: I speak not of deserting,
or flinging away all outward substance; but that your heart may reign above all visibles,
and make God its treasure, and never stick in anything of this lower world,
or rest short of Christ, the eternal rest of all the seed of faith.

[.centered]
__Here begins the narrative.__

The Lord brought us well to Wesel on the fifth-day after we left Herwerden,
having some service by the way.
At Wesel we had a good time with Dr. Schuler, and Rosendale,
and the woman we mentioned to you;
but the tailor was shy and fearful of coming to us at the doctor`'s.

The next day, the 28th, we went towards Duysburg,
and visited the Schult or chief governor that night, whom we found at home;
he received us with much kindness.
His wife and sister, we fear, have been shaken in their good belief of our testimony,
since we were last there; some fowls of the air have devoured the seed that was sown.
O that sweet and tender frame, in which we left them the time before!
However, the entrance we had upon the spirit of the Schult, a little consolated us.
Hence we sent Maria Martha`'s friend a letter;
desiring him to let us have his answer the next night at Dusseldorf, enclosed to Neander,
when and where we might see him, either at Dusseldorf, Mulheim, or Duysburg;
and if it were possible, we would gladly visit the Countess of Bruck.

We got early to Dusseldorf next day, being the last day of the week:
but Neander was gone to Mulheim, in order to preach on the morrow;
so that we were disappointed of our intelligence.

Next morning the 30th, we went towards Cologne, and there arrived that evening.
The day after, we had a good opportunity with Van Dinando and Docemius,
at the house of the latter; and that afternoon took boat back for Dusseldorf;
where arriving next morning, we presently sent for Neander, who came to us,
and three more in company.
We had a blessed meeting with them, and with one of the three that came with him,
our souls were exceedingly affected.

The meeting done, they went away, but Neander returned.
And first, of our letter to Mulheim.
We found by him, as also at our return to Duysburg,
that Kuper was so far from endeavouring our visit to the Countess,
that he would not meet us himself, either at Dusseldorf, Mulheim, or Duysburg: no,
it did not please him to send us an answer, much less any the least salutation.
I confess it grieved us now for Neander: the young man has a zeal for God,
and there is a visitation upon him, my soul desires that it may not be ineffectual:
but I have a great fear upon me.
For this I know certainly, from the Lord God that lives forever,
and I have a cloud of witnesses to my brethren, that retirement and silence before God,
is the alone way for him to feel the heavenly gift to arise,
and come forth pure and unmixed.
This only can aright preach for God, pray to God, and beget people to God,
and nothing else.
But alas! his office in that family is quite another thing; namely,
to perform set duties at fixed times; pray, preach, and sing,
and that in the way of the world`'s appointments.
His very office is Babylonish, namely, a chaplain; for it is a popish invention.

In the good old times, godly Abraham who was a prince, and Joshua a great general,
and David a king, with many more,
instructed their families in the knowledge and fear of God:
but now people are too idle or too great to pray for themselves,
and so they worship God by proxy.
How can a minister of the Gospel be at the beck of any mortal living,
or give his soul and conscience to the time and appointment of another?
The thing in itself is utterly wrong,
and against the very nature and worship of the new and everlasting covenant.
You had better meet to read the Scriptures, the Book of Martyrs, etc,
if you cannot sit and wait in silence upon the Lord,
till his angel move upon your hearts, than to uphold such a formal, limited,
and ceremonious worship.
This is not the way out of Babylon.
And I have a deep sense upon my soul, that if the young man strive,
beyond the talent God has given him, to answer his office, and fill up his place,
and wait not for the pure and living word of God in his heart, to open his mouth,
but either studies for his sermons, or speaks his own words, he will be utterly ruined.

Wherefore, dear friend, have a care you are no snare to him, nor he to you!
Man`'s works smother and stifle the true life of Christ.
What have you now to do, but to look to Jesus,
the author of the holy desires that are in you, who himself has visited you.
Tempt not the Lord, provoke not God.
What should any man preach from, but Christ?
And what should he preach people to, but Christ in them, the hope of glory?
Consider, nothing feeds that which is born of God, but that which comes down from God,
even the bread of God, which is the Son of God, who gives his life for the world.
Feel it, and feed on it; let none mock God, or grieve his Eternal Spirit,
who is come to seal them up from the mouth of man, who has deceived them,
that Jesus the anointing may teach them and abide with them forever.

Be steadfast and immovable; and this will draw the young man nearer to the Lord,
and empty him of himself, and purge away mixtures;
and then you will all come to the Divine silence.
And when all flesh is silent before the Lord, then is it the Lord`'s time to speak,
and if you will hear, your souls shall live.
O! my soul is in great pain, that you may be all chastely preserved in that divine sense,
begotten in your hearts by the eternal Word of God, that abides forever;
that nothing may ever be able to extinguish it.
But more especially that you my dear friend, may be kept in faithfulness:
for the Lord is come very near to you, and you must begin the work;
the Lord God expects it at your hand.
If one sheep break through, the rest will follow.
Wherefore watch; O watch! that you may be strengthened and confirmed;
and strengthen all that is begotten of God in that family, by your weighty, savoury,
and circumspect life.
O how is my soul affected with your present condition!
It is the fervent supplication of my heart, that you may,
through the daily obedience of the cross of Jesus,
conquer and shine as a bright and glorious star in the firmament of God`'s eternal kingdom.
So let it be, Lord Jesus!
Amen.

We tenderly, yet freely spoke our hearts to him, before we parted; which done,
in God`'s love we took our leave of him at Dusseldorf, and got that night to Duysburg,
being the third-day of the week.
We first visited Dr. Mastricht, a man of a good natural temper, but a rigid Calvinist.
I perceived by him, that they held a consultation about seeing us at Bruck;
but they all concluded, it was best to decline meeting with us, because of the Graef,
he being ready to fling our name in reproach upon them, in his displeasure;
and this would confirm him in his jealousies of them.
This might excuse the Countess, but by no means Kuper; and if I had any sense,
Mastricht was there with them upon design,
to frustrate the hopes we had conceived of meeting with her.
We, from that, descended to other things of weight, and in love and peace parted.

From his house we returned to our inn; and after supper we visited the Schult,
who with much civility and some tenderness received us.
His sister also came to us, and we had a good little meeting with them,
and our God was with us; and his pure and tender life appeared for our justification,
and pleaded our innocent cause in their consciences: and so we parted with them,
leaving our Master`'s peace among them.

The next day we came to Wesel, being the 3rd of the eighth month;
where we understood by Dr. Schuler,
that your sister desired we would be so kind as to see her when we returned.
Upon that we went and visited her; she received us very kindly.
Your brother-in-law`'s two sisters were present; we stayed with her at least two hours.
Many questions she put to me, which I was glad to have an opportunity of answering,
for it made way for a meeting.
She entreated us to come again if we stayed,
and told us our visit was very grateful to her: adding,
that because we passed her by the last time, she concluded with herself,
we had no hopes of her; with more to that effect.
From there we went to Dr. Schuler`'s,
who freely offered us his house for a meeting next day: and indeed, the man is bold,
after his manner.

The next day about seven o`'clock I wrote a billet in French to your sister,
to inform her of the meeting, to begin about eight: she came,
and her two sisters with her.
There were Rosendale, Colonel Copius and his wife, and about three or four more;
and to our great joy the Lord Almighty was with us,
and his holy power reached their hearts,
and the Doctor and Copius thereby confessed to our testimony.

The meeting lasted about four hours: being ended,
we took our leave of them in the spirit of Jesus, and so returned to our inn.
The tailor was all this while afraid of coming to our inn,
or to the Doctor`'s to the meeting: great fears have overtaken him,
and the poor man lives but in a dry land.
After dinner we visited Copius and Rosendale;
and at Copius`'s we had a blessed broken meeting, he and his wife,
Rosendale and his wife, with another woman, wife to one Dr. Willick`'s brother,
being present; they were extremely affected and overcome by the power of the Lord,
it was like one of our Herwerden meetings;
indeed much tenderness was upon all their spirits.

This done, and having left books both there and with your sister,
we left Wesel with hearts full of joy and peace: and let me say this,
that more kindness and openness, we have scarcely found in all our travels.
O that this blessed sense may dwell with them!
A seed there is in that place, that God will gather; yes,
a noble people he will find out;
and I doubt not but there will be a good meeting of Friends in that city,
before many years go about: my love is great to that place.
O how good is our dear Lord to us, who helps our infirmities,
and carries through all opposition, and feeds us with his Divine presence,
in which is life!
His candle has hitherto rested on our tabernacle,
and he has made us glad in his own salvation: eternal glory be to his excellent name.

We immediately took a post-car and came next day, about two in the afternoon, to Cleve;
where we had a very precious meeting at an honest procurator`'s house,
who received us with much love: four or five more were present, all grave and tender:
our hearts were greatly affected with their love and simplicity.
We also visited the Lady Hubner, who was kind to us.

The following morning the 6th, we set out for Nimeguen,
and from there immediately to Utrecht, where we arrived that night;
and took the night boat for Amsterdam;
because of a pressure upon my spirit to be next day at the meeting, and the rather,
having intimated as much from Cologne.

We arrived in the morning at Amsterdam, where we found our dear friends generally well,
the city much alarmed, and great curiosity in some, and desires in others,
to come to the meeting.
We had a very great meeting, and many people of note resorted:
God`'s Gospel bell was rung, the great day of the great God sounded,
and the dead were raised, so that much tenderness appeared in several.
O blessed be the name of the Lord, whose work and testimony prosper!

The next day was spent in various affairs relating to the Truth.
The day following, the 9th, we had a meeting with Galenus Abrahams,
the great father of the Socinian Menists in these parts,
accompanied by several preachers, and others of his congregation:
several of our friends were also present.
It continued about five hours; he affirmed in opposition to us,
that there was no Christian church, ministry, or commission apostolical now in the world;
but the Lord assisted us with his wisdom and strength, to confound his attempts.

[.centered]
__Here ends the narrative.__

I intend a visit at the Hague to the Lady Overkirk, sister of the Somerdykes,
and some others who have sober characters of Truth and Friends;
and from there to Rotterdam, where I have much to do,
both with respect to meetings and the press.

Thus my dear friend, have I given you a tedious narrative,
yet I hope not altogether unpleasant.
Perhaps the brevity of my letters hereafter may best apologize for the length of this:
however I consider two things; one is, that you have time enough,
one time or other to look over it; and next,
that I have plentifully answered your requests,
and demonstrated I have not forgotten you.

Dear friend! let us live and remember one another, now absent,
in that Divine sense in which the Lord God dissolved our spirits when together.
O the unity of this faith, the purity of this love,
and the bond of this peace The Lord Jesus be with your spirit,
and keep you in this the hour of your temptation,
that you may come forth as gold seven times tried:
so shall your testimony shine for the God that has called you,
and he will reward you with honour, glory, and eternal life.
Amen.

Thus says the Lord, I remember you, the kindness of your youth,
the love of your espousals, when you went after me in the wilderness,
in a land that was not sown.`' Dear friend, consider this.
Yet again: "`The way of the just is uprightness; you, most upright,
do weigh the paths of the just.
Yes, in the way of your judgments, O Lord, have we waited for you;
the desire of our soul is to your name, and to the remembrance of you.
With my soul have I desired you in the night; yes,
with my spirit within me will I seek you early; for when your judgments are in the earth,
the inhabitants of the world will learn righteousness.
Lord, you will ordain peace for us; for you also have wrought all our works in us.
O Lord our God, other lords besides you have had dominion over us;
but by you only will we make mention of your name.
Lord, in trouble have they visited you;
they poured out a prayer when your chastening was upon them.
Your dead men shall live, together with my dead body shall they arise.
Awake and sing, you that dwell in the dust, for your dew is as the dew of herbs,
and the earth shall cast out the dead.
Come my people, enter into your chambers, and shut your doors about you;
hide yourself as it were for a little moment, until the indignation be overpast.
For, behold,
the Lord comes out of his place to punish the inhabitants of the earth for their iniquities;
the earth also shall disclose her blood, and shall no more cover her slain.`"

So come, dear Lord Jesus, who was dead, and is alive, and lives forever.
Amen.
Very dearly farewell.

[.signed-section-closing]
Your friend, that faithfully travails for your redemption,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Amsterdam, the 10th of the Eighth month, 1677.

--
