== Chapter XVIII.

On the 10th of eighth month, at Amsterdam, we had a blessed public meeting,
never to be forgotten.
O the majesty, glory and life, with which the Lord attended us!
Our hearts were deeply affected with his presence;
great reverence and brokenness was over the meeting, more than I had seen.
The meeting done, we were opposed by a preacher,
who was closely encountered and pursued by several merchants, etc, (not of us) who cried,
he was rude and ignorant, and that they had a testimony for us;
and offered to dispute in our defence, but the priest ran away:
they followed him till they housed him; but what followed I know not.

It was upon me this day to engage Galenus Abrahams to a second conference,
that we might more fully debate and confute his grand
objections against the present dispensation of Truth,
and the heavenly ministry, witnessed among Friends.
He refused not my offer of a second meeting; but sent me word,
his business would not give him leave to let it be any time this day.
Upon which, the next morning was fixed for the conference, to begin at eight o`'clock;
which accordingly it did, and held till one.
The account of both the conferences is not yet found,
but with the latter some of his own friends seemed better satisfied,
and it ended very comfortably to us, because to a general satisfaction.

The meeting thus ended, and having refreshed ourselves,
after a solemn leave taken of our dear friends at Amsterdam,
George Fox and myself went that night to Leyden, accompanied by Benjamin Furly;
coming there late at night, we forbore to inquire after any worthy in that place.

But the next morning we found out two, one a German of or near Darmstadt;
who not only expressed much love to the principle of Truth,
and unto us the friends thereof;
but also informed us of a retired person of great quality,
that lives about two hours back again towards Amsterdam, at a village called Wonderwick.
Our resolution of being that night at Rotterdam,
and having the Hague to visit by the way, made our return at that time impracticable:
however,
the relation of the German concerning the good inclinations
of the great man and his wife,
their disdain of the world, and voluntary retreat from the greatness and glory of it,
rested strongly upon our spirits.
This person presently conducted us to the house of
one who had formerly been a professor in the university;
and there left us.

To this person both George Fox and myself were more than ordinarily open:
he was of a sweet, yet quick, of a wise, yet very loving and tender spirit:
there were few strangers towards whom we felt greater love.
He assented to everything we said:
and truly his understanding was very clear and open
to the things that lay upon us to declare.
He expressed his firm belief of great revolutions at hand,
and that they should terminate in the setting up
of the glorious kingdom of Christ in the world.

What shall I say?
The man felt our spirits, and therefore loved us, and in the fresh sense of that love,
wrote a letter by us to a retired person at the Hague, like himself: which,
in several places of Germany,
was the way whereby we found out most of the retired people we visited.
After nearly two hours time with him, we took wagon for the Hague,
leaving the peace of God upon him.

The first thing we did there, was to inquire out the Lady Overkirk;
a person of a retired and religious character,
separated from the public worship of that country: she was at home,
but her husband with her; and being a great man of the army,
of another disposition and way of living, hindered our access at that time.

The next person we went to, was a judge of the chief court of justice in that republic.
He received us with great respect,
and a more than ordinary desire to know the truth of our faith and principles.
We declared of the things most surely believed among us, in the power and love of God.
He made his observations, objections, and queries upon several things we spoke;
to whom we replied, and explained all matters in question;
insomuch that he declared himself satisfied in our confessions,
and his good belief of us and our principles.
We took a solemn and sensible leave of him,
and we felt the witness of God reached in him, and his spirit tendered;
which filled our hearts with dear love to him: he brought us to his street door,
and there we parted.

From him we went to visit that person for whom we had a letter from the doctor at Leyden;
but he was not at home.
We immediately took wagon for Delft, and from there an express boat for Rotterdam,
where we arrived about eight o`'clock at night.

The 13th of the month was mostly spent in visiting Friends,
and the friendly people in that place, who consisted of several persons of worldly note.

The next day, being the first-day of the week, we had a large and blessed meeting;
wherein the deep mysteries of the kingdom of Christ and antichrist were declared,
in the power of an endless life.
Several of different religions were there, but no disturbance or contradiction;
a profound silence and reverent attention were over the meeting.^
footnote:[A person then convinced, +++[+++says W. P.]
though the world prevailed, died lately, acknowledging it, and cried out,
"`How happy had I been, if I had then obeyed!`"]

That night I had a blessed meeting at my lodging, with those persons of note,
who at some times had visited our public meetings, as on that day;
and they have a convincement upon them: the Lord`'s love, Truth,
and life preciously reached towards them, and they were very sweetly affected.

Next day I bestowed in perfecting and correcting several public letters,
which I was moved to write both in my first and second journey in Germany,
and after my return to these Low Countries.
The titles of them follow.--1. "`A Summons or call to Christendom,
in an earnest expostulation with her,
to prepare for the great and notable day of the Lord,
that is at the door.`"--2. "`Tender Counsel and Advice, by way of Epistle,
to all those who are sensible of the day of their visitation,
and who have received the call of the Lord by the
light and spirit of his Son in their hearts,
to partake of the great salvation, wherever scattered throughout the world;
but more especially in the High and Low Dutch nations: faith, hope, and charity,
which overcome the world,
be multiplied among you.`"--3. "`To all those Professors of Christianity,
that are externally separated from the visible sects
and fellowships in the Christian world,
so called, wherever hidden or scattered: true knowledge, which is life eternal,
from God the Father, by Christ Jesus.`"--4. "`A tender Visitation,
in the love of God that overcomes the world,
to all people in the High and Low Dutch nations,
who hunger and thirst after righteousness,
and desire to know and worship God in truth and in sincerity;
containing a plain testimony to the ancient and apostolical life,
way and worship that God is reviving and exalting in the earth,
in his Spirit and Truth.`"

The sense of the serious retreat of the great man we heard of at Leyden,
was so strong upon me,
that I could not see myself clear to leave the country before I had given him a visit.
I purposed therefore the next morning, the 16th, to set forward to the Hague,
from there to Leyden, and so to Wonderwick.

I arrived there in the evening with Benjamin Furly, A. Sonnemans, and M. Sonnemans;
and immediately made known our coming,
and the end of it to him and his wife by means of the young German,
who was got there before us, to visit them.
An invitation came to us all at our inn; and immediately we repaired to his house,
which was very stately, and yet plain.
He presently came to us, took us by the hand, and bid us heartily welcome.
We immediately sat down; and after some time of retirement,
I spoke something of what was upon me,
yet not before he had given us a sober and pathetical account of his life,
and of the present frame and disposition of his spirit.

All this was in the absence of his wife:
but so soon as I had finished what was then upon me to speak of the witness of God,
and of its work in man, upon the occasion of the history he gave us of his life;
he led us into another room where his wife was.
He told her, here were some Christian Friends come to visit her:
she saluted us very kindly.

We all sat down; and after some silence,
the heavenly power of God did in a living and tender
manner open their states and conditions to me,
and open my mouth to them.
The substance of my testimony was to this purpose, that death reigned from Adam to Moses;
Moses was till the prophets, the prophets till John, and John till Christ:
what Christ`'s day was, how few see this day;
and while people are talking of being in Christ under grace, and not under the law,
death reigns over them, and they are not come to Moses,
nor the shaking or quaking mountain, the thunderings, lightnings, and whirlwinds:
and what was that way which led to Christ; and what it was to be in him,
and under the government of his grace; directing them to the blessed light of Christ,
Spirit of Truth, and grace, which God had shed abroad in their hearts.
I declared the nature and manner of the appearing and operating of this Spirit;
and appealed to their own consciences for the truth of what was said:
and I can truly say, the holy life of Jesus was revealed among us, and like oil,
swam on the top of all.
In this sense I was moved to kneel down and pray: great brokenness fell upon all;
and He who was before the world began, was richly manifested in and among us.

The meeting being done, the great man and his wife blessed us,
and the work of God in our hands; saying with tears in his eyes,
"`My house is blessed for your sakes, and blessed be God that I ever lived to see you.`"
And thus we left them, though with much difficulty;
for they pressed us with great earnestness, both to eat and to lodge with them;
and it was hard for them to bear our refusal.
They said it was a scandal to their house that they should
let such good people as we were go out of it;
or allow us to lodge at any other place: but we declared our pre-engagement elsewhere,
and that it was not for lack of true kindness towards them.

One passage I had almost forgotten to mention: "`I was,`" said he,
"`once at a table with the Duke of Holstein at Fredericstadt,
when the magistrates came to complain against a people called Quakers in that city.
The Duke was ready to be prejudiced against them; but at the very naming of them,
I conceived a more than ordinary kindness in my mind towards them.
I asked the magistrate, What they were for a people?
He told me that they would not pull off their hats to their superiors.

I asked him, Whether they would pull off their hats to God?
He said, '`Yes.`' Said I, '`That may be the reason why they will not pull them off to man.
Do they live peaceably?`'
'`Yes.`' '`Do they pay their taxes?`'
'`Yes.`' '`Do they rub their hats in your eyes?`' '`No`'
'`Do they do any harm with them?`' '`No.`' '`Why,
what is your quarrel then?`' '`They meet in silence, and they will not speak or pray,
unless they be moved by the Spirit.`' '`Why that is according to the doctrine of Scripture:
if this be to be a Quaker, I would I were a Quaker too.`' '`But,`" said he,
"`I never saw one before, but I bless God I see you now.`"
He very much inveighed against the false Christianity that is in the world,
and greatly magnified a tender, mortified and retired estate.
I have great hopes he and his wife will die in the Truth.
We returned to our inn to supper and to bed.

Next morning, we took wagon for the Hague; where we met with Docemius,
the King of Denmark`'s resident at Cologne, who had been at Rotterdam to seek us,
and came back there, with hopes to meet us.
We had some service there with a lawyer;
but were again disappointed of visiting the Lady Overkirk,
because of her husband`'s presence;
and the other retired man before mentioned was again from home:
the judge would gladly have received us,
but a great cause then depending commanded his attendance.
That afternoon we took boat for Delft, and so to Rotterdam, where we all arrived well.

It was my desire to have been the day following at a meeting at Dort; but it seems,
the way that we hoped had been open for us, was shut;
insomuch that we were prevented of that service.
However,
I applied myself to the perfecting of what yet needed to
be completed in those writings I left behind me to be printed.

The next day, being the 19th of the eighth month, we had a very blessed public meeting,
therein taking our leave of the country.
And after that was done, we had another among Friends,
recommending to them the peaceable, tender, righteous Truth;
desiring that they might live and grow in it, and be a people to the Lord`'s praise;
so should his work prosper, his dominion be enlarged and increased among them.
In the evening, I had also a meeting at my lodging, among the great people of that place,
of which I have before made mention.
And magnified be the name of the Lord, his power did so sweetly visit them,
and effectually reach them, that at their departure, some of them fell upon our necks,
and with tears of love prayed that they might be remembered by us,
and that they might have strength to answer our great travail for them.
We recommended them unto the Lord, and the pure word of his grace in their hearts.

The next day the generality of Friends of that place
met at Simon Johnson`'s house early in the morning;
where we took our leave of one another, in the love and power of the Lord,
feeling his living presence with them that stayed, and with us who went.

Several accompanied us to the Briel; where we arrived about noon.
There accompanied us the King of Denmark`'s resident at Cologne,
who had been with us at those meetings at Rotterdam,
P+++.+++ Hendricks and C. Rocloffs of Amsterdam, and A. Sonnemans, Benjamin Furly,
M+++.+++ S. and S. J. with several others of Rotterdam.
The packet-boat not being come, we were necessitated to lie there that night.

That night it was upon me in the earnest love of God,
to salute the Princess and Countess with a few farewell lines, as follows:

[.embedded-content-document.letter]
--

[.letter-heading]
To the Princess Elizabeth.
Salvation in the cross.
Amen.

[.salutation]
Dear and truly respected friend,

My soul most earnestly desires your temporal and eternal felicity;
which stands in your doing the will of God now on earth, as it is done in heaven.
O dear Princess do it!
Say the word once in truth and righteousness, '`Not my will, but yours be done,
O God!`' Your days are few; and then you must go to judgment;^
footnote:["`She died about four years after,`" adds W. P in a note.]
then an account of your talent, God will require from you.
What improvement have you made?
Let it prove and show its own excellency, that it is of God,
and that it leads all that love it to God.
O that you may be able to give an account with joy!

I could not leave this country, and not testify the resentments I bear in my mind,
of that humble and tender entertainment you gave us at your court:
the Lord Jesus reward you!
And surely he has a blessing in store for you.
Go on: be steadfast, overcome and you shall inherit.
Do not despond; One who is mighty is near you;
a present help in the needful time of trouble.
Let the desire of your soul be to his name, and to the remembrance of him!
Wait upon the Lord, and you shall renew your strength! the youths shall faint,
and the young men shall fail, but they that trust in the Lord shall never be confounded.

I wish you all true and solid felicity, with my whole soul.
The Lord God of heaven and earth have you in his keeping; that you may not lose,
but keep in that Divine sense, which by his eternal Word he has begotten in you.
Receive, dear Princess, my sincere and Christian salutation.
Grace, mercy and peace be multiplied among you all that love the Lord Jesus.

Your business I shall follow with all the diligence and discretion I can,
and by the first opportunity give you an account,
after it shall please the Lord to bring me safe to London.
All my brethren are well,
and present their dear love to you and the rest in your family that love Jesus,
the Light of the world.
You have taught me to forget you are a Princess, and therefore I use this freedom;
and to that of God in you am I manifest; and I know my integrity.
Give, if you please, the salutation of my dear love to Anna Maria de Homes,
with the enclosed.
Dear Princess, do not hinder, but help her.
That may be required of her, which, considering your circumstances,
may not yet be required of you.
Let her stand free, and her freedom will make the passage easier unto you.
Accept what I say, I entreat you, in that pure and heavenly love and respect,
in which I write so plainly to you.
Farewell, my dear friend, and the Lord be with you!

I am, more than I can say, your great lover and respectful friend,

[.signed-section-signature]
William Penn.

[.postscript]
P+++.+++ S. I refer you to the enclosed for passages.
We visited Giftall and Hooftman, and they us.
They were at one or two of the meetings at Amsterdam.
Vale in aternum!

--

[.embedded-content-document.letter]
--

[.letter-heading]
For Anna Maria de Homes, styled Countess of Homes.

Jesus be with your spirit.
Amen.

Beloved,
and much esteemed for the sake of that love which
is raised in your heart to the eternal Truth of God;
the increase of which I earnestly desire; that you may be more than a conqueror,
through the powerful workings of that Divine love in your soul,
which casts out all false fear and overcomes the world.
In this eternal love, it is that I love you, and would be loved of you:
blessed are they that hold their fellowship in it.
It is pure, harmless, patient, fervent and constant: in fine, it comes from God,
and leads all that receive it to God.
Indeed, it is God; and they that live in love, live in God.
If we keep and abide in him who has visited us,
we shall always feel this love as a fountain; and wonderful are the effects of it.
It can lay down its life for its friend!
It will break through all difficulty and has power to conquer death and the grave.
This transcends the friendship of the world,
and the vain-glorious honour of the courts of this world.
This kindness is inviolable: our purest faith works by this love.
O the tenderness of that soul in which this love lives and has
place! the humility and compassion that always keep it company!

And who can lively enough describe the lovely image it gives,
the attracting and engaging conversation it has?
But it is discerned and greatly valued by the children of love, who are born of it,
which all the children of light are.
What shall I say?
It is the great command, and it keeps all the commands; love, pure and undefiled,
fulfills the law and Gospel too:
blessed are they that feel any of this love shed abroad in their hearts.

With this love, it is that God has loved us; and by the power of this love,
Christ Jesus has died for us.
Yes, it is this love that quickens us to Jesus,
that inflames our souls with pure and ardent love to him, and zeal for him: yes,
it is this holy love that +++[+++engages to]
forsake father and mother, sister and brother, husband, wife and children,
house and land, liberty and life for the sake of Jesus;
that leaves the dead to bury the dead,
and follows Jesus in the narrow way of regeneration;
that can trust him in the winds and in the earthquakes, in the fire and in the waters,
yes, when the floods come in even unto the soul, this desponds not, neither murmurs.

And as it cannot despair, so it never presumes; yes, it can triumphantly say,
What shall be able to separate me from the love of God that is in Christ Jesus?
Shall principalities or powers, things present or things to come, shall life or death?
O no, neither time nor mortality!

My dear friend, let this noble plant of paradise grow in your heart.
Wait upon the Lord, that he would water it, and shine upon it, and make a hedge about it;
that your whole heart may be replenished with the heavenly increase and fruits of it.
O! that you may grow in your inner man, in wisdom, strength and a pure understanding;
in favour with God, and with all people that are in the same nature and image:
for the world only loves its own.

I hoped not to have been so quick upon my last long letter;
but God`'s pure love which has redeemed me from the earth,
and the earthly nature and spirit,
moved fervently upon my spirit to visit you once more before I leave this land.
I deferred it to this extremity; and being not clear to go hence,
I send you my Christian salutation, in this pure love, that many waters cannot quench,
distance cannot make it forget, nor can time wear it out.
My soul reverently bows before the God and Father of our Lord Jesus Christ,
that it would please him to preserve you.
Fear him, and you need not fear;
for the angel of the Lord encamps about those that trust in his name.
The angel of his eternal presence guard you,
that none of the enemies of your soul`'s peace may ever prevail against you!
Perseverance and victory be your portion in this world,
and a crown of endless glory be your reward in that which is to come.
Amen!

Since my last (being the next day after the date thereof)
we had a meeting with Galenus Abrahams and his company:
the success you may perhaps see suddenly in print;
and therefore I shall defer the narrative: only in general, our dear Lord,
our staff and strength, was with us, and Truth reigned over all.

That night we went to Leyden, where we visited some retired persons.
From there, next day, to the Hague, where also we had a little meeting.
O the lust and pride of that place You earnest into my mind as I walked in the streets;
and I said in myself, '`Well, she has chosen the better part.`' Be faithful,
and the Lord will give you an eternal recompense "`From there we came to Rotterdam,
where the Lord has given us several heavenly opportunities in private and public.
We are now come to the Briel, and wait our passage.
The Lord Jesus be with you that stay, and with us that go,
that in Him we may live and abide forever!

Salute me to my French friend; bid her be constant.
I wish your servants`' felicity; but yours as my own: God Almighty overshadow you,
hide you under his pavilion, be your shield, rock and sanctuary forever.
Farewell, farewell

[.signed-section-closing]
Your friend and the Lord`'s servant,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Briel, 20th, (30th,) Eighth month, 1677.

--

Next morning, the 21st, the packet-boat arrived; and about ten o`'clock we went on board,
having first taken our solemn leave of those Friends that accompanied us there.
We immediately set sail with a great number of passengers:
but by reason of contrary and tempestuous weather,
we arrived not at Harwich till the 24th about the sixth hour.
From where, next morning,
I wrote this following salutation and account to the Friends
of Holland and Germany to return with the boat.

[.embedded-content-document.epistle]
--

My soul magnifies the Lord, and my spirit rejoices in God my Saviour,
who has rebuked the winds and the seas,
and made us to drink of his salvation upon the great deeps.
Yes, we could not but praise him in the tempest; for all things are full of his majesty.
Blessed is the eye that sees, and the heart that depends upon him at all times!
There is not another God; he is the Lord alone, whom the holy ancients trusted in,
and were not confounded.
What shall my soul render unto the Lord?
We are full of his mercy; he has made us witnesses of his care.
We can say in righteousness, they are blessed whose God is the Lord,
and that serve all the day long no other master than our God.

Friends, this is an endeared salutation to you all in High and Low Dutchland,
in the deep and fresh sense of the Lord`'s preserving power.
O! that you may abide in that sense of him, which he has begotten in you,
and in the reverent knowledge of him,
according to the manifestation which you have received of him,
in the light of his dear Son; that you may be faithful and fervent for the Lord;
that his glorious life and power may break through you; and these lands,
long dry and barren as the wilderness, may spring and blossom as the rose.
For what have we to do here, but to exalt him who has visited and loved us, yes,
saved us in great measure?
Ah, he is worthy! my spirit reverences him, my heart and soul do bow before him:
eternal blessings dwell forever with him.

Dear friends, my love flows to you as a fountain.
God, even my God and your God, has made you dear to me; yes,
dearer than all natural kindred.
You are flesh of my flesh indeed.
Nor sea nor land, nor time nor place can ever separate our joy, divide our communion,
or wipe out the remembrance that I have of you.
Yes, the living remembrance, which my God often gives me of you, in the life of his Son,
abides; which breaks my heart to pieces: and I can say,
I left much of my heart behind me;
and the Lord alone could have outwardly separated me so soon from you.
This love is stronger than death, more excellent than the love of women;
for it endures forever: this privilege have all the saints.
Jesus, the Light of the world, who saves from the world, be with you.
Amen.

We got well last night at about seven o`'clock to Harwich,
being three days and two nights at sea:
most part of the time there was a great storm of wind, and rain, and hail;
the weather was against us, and the vessel so leaky, that two pumps went night and day,
or we had perished.
It is believed, that they pumped twice more water out than the vessel could contain;
but our peace was as a river, and our joy full.
The seas had like to have washed some of the seamen overboard,
but the great God preserved all well.
Frights were among the people, and despondencies in some;
but the Lord wrought deliverance for all.
We were mightily thronged, which made it the more troublesome.

But it is observable, that though the Lord so wonderfully delivered us,
yet some vain people soon forgot it,
and returned quickly to their wanton talk and conversation,
not abiding in the sense of that hand which delivered them:
nor can any do it as they should,
but those who are turned to his appearance in their hearts;
who know him to be a God nigh at hand; which,
O may it be your experience and portion forever!

And the Lord be with you, and refresh and sustain you;
and in all your temptations never leave you, nor forsake you; that conquerors you may be,
and in the end of days and times,
stand in your lot among the spirits of the just made perfect.
Amen, amen.

[.signed-section-closing]
Yours in that which is eternal!

[.signed-section-signature]
William Penn.

[.postscript]
P+++.+++ S. Let this be sent to Friends in High and Low Dutchland.

[.signed-section-context-close]
Harwich, 24th of the Eighth month, 1677.

--

At Harwich, I left dear George Fox and Gertrude Diricks and her children,
who came over with us, to follow me in a coach:
but having a desire to be that day at Colchester meeting, I went early away on horseback,
George Keith accompanying me.
We got to the meeting, and were well refreshed in Friends.

That evening we had a mighty meeting at J. Furly`'s house, where we lay;
many of the town being there, who would not come to a public meeting.
And indeed the Lord`'s Divine power and presence were in the assembly.

Next day the 26th, we had a great meeting at a marriage,
where we had good service for the Lord.
That afternoon about four o`'clock we took horse for London; George Fox and the others,
through the miscarriage of a letter about the coach, not being come to Colchester.
That night we lay at I. Ravens, eight miles on our way.
There we met Giles Barnardiston and William Bennet; with whom,
and some other Friends thereabout, we were comforted in the life and power of the Lord.

The day following, we took our journey for London,
and came there in good time that evening; where I found all things relating to Friends,
in a good condition: blessed be the name of the Lord.
I stayed about a week in town; both to visit Friends at meetings,
and to be serviceable in the more general affairs of the Truth.

The fifth-day of the next week I went to Worminghurst, my house in Sussex,
where I found my dear wife, child and family all well:
blessed be the name of the Lord God of all the families of the earth.
I had that evening a sweet meeting among them;
in which God`'s blessed power made us truly glad together; and I can say,
truly blessed are they who cheerfully give up to serve the Lord:
great shall be the increase and growth of their treasure, which shall never end.

To him that was, and is, and is to come; the eternal, holy, blessed, righteous, powerful,
and faithful One, be glory, honour and praises, dominion and a kingdom, forever and ever!
Amen.

[.signed-section-signature]
William Penn.

[.asterism]
'''

At London, the following letter from the Princess Elizabeth came to hand.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Herford, the 29th of October, 1677.

[.salutation]
Dear friend,

Your tender care of my eternal wellbeing does oblige me much,
and I will weigh every article of your counsel to follow as much as lies in me;
but God`'s grace must be assistant; as you say yourself,
He accepts nothing that does not come from him.
If I had made me bare of all worldly goods, and left undone what he requires most,
(I mean,
to do all in and by his Son,) I shall be in no better condition than this present.
Let me feel him first governing in my heart, then do what he requires of me;
but I am not able to teach others, being not taught of God myself.

Remember my love to George Fox, Benjamin Furly, George Keith, and dear Gertrude.^
footnote:[This was Gertrude Diricks, who had visited the Princess.
She afterwards came to live in England, and was married to Stephen Crisp.]
If you write no worse than your postscript, I can make a shift to read it.
Do not think I go from what I spoke to you the last evening;
I only stay to do it in a way that is answerable before God and man.
I can say no more now, but recommend to your prayers,

[.signed-section-closing]
Your true friend,

[.signed-section-signature]
Elizabeth.

[.postscript]
P+++.+++ S. I almost forgot to tell you that my sister writes me word,
she had been glad you had taken your journey by Osnaburg to return to Amsterdam.
There is also a drossard of Limburg near this place,
(to whom I gave an exemplar of Robert Barclay`'s Apology,)
very desirous to speak with some of the Friends.

--

Another letter was received some time after,
in answer to one which he had written to her while in Holland--being as follows.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
This 17th of November, 1677.

Dear friend, I have received a letter from you,
that seems to have been written at your passage into England,
which I wish may be prosperous, without date, but not without virtue to spur me on,
to do and suffer the will of our God.
I can say in sincerity and truth, '`Your will be done,
O God!`' because I wish it heartily; but I cannot speak in righteousness,
until I possess that righteousness which is acceptable unto him.
My house and my heart shall be always open to those that love him.
Gichtel has been well satisfied with the conferences between you.
As for my business, it will go as the Lord pleases, and remain in him,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Elizabeth.

--

The following short Epistle, written to Friends in Germany etc,
who were under severe persecution,
is a beautiful specimen of the Christian sympathy of our author,
and the religious consolation which he was capable of imparting:

[.embedded-content-document.epistle]
--

[.letter-heading]
To all suffering Friends in Holland or Germany,
particularly in Fredericstadt and in or near Dantzic.

[.signed-section-context-open]
Rickmansworth, 1st of Seventh month, 1673.

[.salutation]
My dear friends,

In God`'s everlasting Truth, and that heavenly power, strength,
and dominion that stand therein, does my soul very dearly salute you all,
who have tasted of the invisible and heavenly life,
that is made known unto those who have been begotten
into the living way of light and righteousness.
Oh! pleasant are the outgoings of the Lord to and in his children,
whose minds are truly stayed upon him,
and are freely resigned up to his all-wise disposal;--such
shall abound in the joy of God`'s salvation,
even in sufferings, persecutions, tribulations, yes, deaths,
and every peril that may attend your most holy faith.
Therefore, hold up your heads, and be comforted,
little flock! your Shepherd will not fly, though the wolf come.
Know your Shepherd, and dwell with him,
and he will bring you into sweet and green pastures, in the midst of your enemies.
Consult not with flesh and blood, to know what may be the cause of your trials,
how you may shun them, or which way you may keep mammon and a good conscience too;
but eye the Lord, without whose providence a sparrow falls not to the ground.
No new or strange thing can happen unto you: dwell in the faith that works by love,
and that will cast out all fear which begets any staggering from your holy testimony.
Remember that many eyes are upon you,
and as you acquit yourselves in this exercise that
may quickly be allowed to come upon you,
so will God`'s Truth be well or illy spoken of;
for people will measure your most holy way by you.
The way they see not, you they will behold; what do you know,
but the Lord is now preparing and brightening you for further service,
both where you live, and in other places.
In the light of Jesus, the just man`'s path, live and walk,
that to the end you may endure; so shall you glorify God,
answer their labours who have travailed among you,
and obtain unto yourselves eternal salvation.
So dear hearts! be still, quiet, and given up in life and death.
God`'s great work is going on: he comes upon the world in a storm,
and sometimes to his children, that they may be the more weaned from the world,
that people may be the more stirred up to mind them,
and that Truth may be more effectually manifested through their self-denial, patience,
and resolution.
Stand then, be valiant, and keep your minds to the invisible life,
which is felt in the light; and then I am persuaded, neither principalities, nor powers,
nor life, nor death, nor any other thing,
shall be able to separate you from the love of God,
that has been and daily is revealed to you in Christ Jesus, the Lamb of God,
and Light of the world.

The God of all peace keep your minds and spirits in perfect peace,
amidst the greatest trials and disquiets from without,
that you may finish your testimonies with us, to His eternal praise who has called us,
who is over every name worthy, even God, blessed forever.
Amen, amen!

Your fellow-feeling brother in the unchangeable Truth,

[.signed-section-signature]
William Penn.

[.postscript]
P+++.+++ S. Truth greatly prevails in these islands,
and grows daily famous over the heads of its peevish opposers: and Friends,
who have heard lately of you, travail and sympathize with you; you are not alone,
and He that is in you, is greater than he that is in the world.
Farewell.

--

The subjoined extracts from a letter written in 1676
to the Princess Elizabeth and the Countess of Homes,
are deemed worthy of insertion:

[.embedded-content-document.letter]
--

Jesus be with your spirits, the immaculate Lamb of God, and glorious Light of the world!
His pure Spirit redeem you from the evil and ignorance that are in it,
and replenish you with his everlasting righteousness,
whose end is peace and assurance forevermore!

Noble of this world, but more noble for your inquiry after the Truth and love to it,
the fame whereof has sounded to the ears of some of us in this island,
whom God has made both his certain witnesses and messengers,
through many and great tribulations: heavenly praises to his holy and powerful name,
who lives and reigns over all principalities, and powers, and thrones,
and dominions forever!

I have had you, worthy women! often in my remembrance,
with that honour which is not of this world;
even when my soul has been in its purest retirements, not only from all visibles,
but from their very ideas in the mind, and every other imagination;
resting with the Lord in his own sabbath, which is the true silence of all flesh indeed,
which profits above the formal Christian`'s bodily exercise.
And in these heavenly sequestrations of soul,
and true resignation unto the divine will of my Father,
have I taken a most clear prospect of you,
and every circumstance that may be fit for me to know: your education, your quality,
your dignity, the envy of the clergy, the fury of the rabble,
and the strength and power of temptation, arising from all these considerations,
if possible to smother your blessed beginnings; and as so many bands of soldiers,
employed and commissioned of their great prince of darkness,
to watch and to hinder Jesus from rising in you.
In a weighty sense of all which, my heart opens itself unto you in God`'s counsel,
after this manner.

Be faithful to what you know,
and obedient to that which God by the light of his Son makes manifest in your consciences.
Consult not away the pure and gentle strivings of the Holy Spirit;
drown not his still voice with the crowd of careful thoughts, and vain contrivances:
break not the bruised reed, neither quench the smoking flax in yourselves.
If you truly love Jesus, hear him: and since it has pleased God in some measure,
as with Paul, to reveal his blessed Son in you, consult not with flesh and blood,
which are below the heavenly things; for that inherits not the kingdom of God:
but with sincere Mary, from a deep sense of the beauty, virtue,
and excellency of that life, that is hid with Christ in God, wait out of all cumber,
free from that running, willing, sacrificing spirit that is in the world,
in the pure obedience, humiliation, godly death or silence, at the feet of Jesus,
choosing the better part, which shall never be taken from you:
and Jesus will be with you, he will shed his peace abroad in the midst of you,
even that which flows from the crystal streams of life,
that arise from under the throne of God.

--

After describing the sad declension and apostacy from the
life and power of the religion of the primitive believers,
which had come upon professing Christendom,
and the unfaithfulness and worldly compliances, he proceeds thus;

[.embedded-content-document.letter]
--

And though the Lord has not left himself without witnesses in any age;
yet they were so few, and most of them, though accepted according to their day and work,
so short as to the main work, that a remnant can say,
When the Lord first opened the eyes of their understanding,
the world lay in a great heap of wickedness, vanity and confusion;
all following the desires of their own hearts, to gratify the lusts of the same,
living vainly and wantonly upon the earth; yes,
the whole earth looked like one great wilderness, full of briars and thorns,
birds and beasts of prey.

And when God poured out of the Spirit of judgment and of burning upon us,
not only making us sensible of his holy terrors in and for ourselves,
but of that day of fiery trial he would overtake the world with;
our faces gathered paleness, and our knees smote together, our hearts fainted,
our lips quivered, and our bodies trembled;
and all that we might rest in the day of trouble. Hab. 3:16.

But while we were under the lightning and thunders, and great earthquakes, wars,
and rumours of wars, such as had not been since the foundation of the world,
as to us--for the sun became darkened, and the moon was turned into blood,
and none of the stars of the night appeared,--while our agonies took strong hold upon us,
and we were in the extremity of our pains; O! the gazing-stock that we were made to all,
yes, spectacles to angels and to men.
Some said, we were bewitched; others that we were strongly possessed of the devil;
all astonished: parents beating and disowning their children;
children insulting over their parents; masters evilly entreating their servants:
servants abusing their masters: the husband using violence to the wife:
the wife becoming strange and unnatural to her own husband; and all most cruelly vexed,
abused, and tormented by the magistrates,
through the wicked and unwearied instigations of the priests of all sorts, by jails,
dungeons, whippings, stocks, pillories, plunders, etc.
O the calamity! the bitter distress of that day! and though we were but few in that day,
and very low, poor, and even despicable in our own eyes;
yet were we exceedingly strong and valiant in the Lord Jehovah, our everlasting strength.
For our inward man was daily renewed, and we greatly loved one another:
but never till now, did we truly know who Christ was, either in conception, birth,
reproaches, sufferings, death, resurrection, or ascension;
a mystery to the whole Christian world at this day,
who are not turned to his light in their own consciences.

And as in the holy watch we kept,
not being staggered by the reproaches of the men of this world,
but with Moses choosing them, rather than the treasures and pleasures of Egypt,
where our dear Lord lay crucified; we exceedingly grew in the grace and favour of God,
and we were very tender, by any wandering thought, much more by any evil act,
to grieve his holy Spirit of righteousness in ourselves, whom we desired should reign;
being overcome with joy, that He brought life with him to our immortal souls.
And after we had stayed at Jerusalem, the city of our God and King,
to receive his instructions, commission, and authority, abroad we went,
upon the pourings out of his Spirit.
And we went in the name and power of our God,
to declare of his judgments and to tell of his terrible day, to call all to repentance,
and to prepare to meet the Lord, to make ready the way of our God;
who was coming to lay judgment to the line, and righteousness to the plummet, to examine,
sift, and winnow the sons and daughters of men, to judge in righteousness;
who will not be deceived by vain shows of religion:
for he is a jealous God of his honour and his glory will he give to no man,
neither will he acquit the guilty, nor punish the innocent.

But after this breaking forth and publishing of our message to the world,
especially to professors; the Scribes and Pharisees took the alarm, finding their call,
qualification and credit, and which is most of all in their eye, their maintenance,
brought into question, and their whole kingdom shaking;
man-made ministry being proved insufficient; forced maintenance anti-christian;
and that no man could know, much less preach,
Divine things without Divine revelations and inspirements;
and that no man was a true Christian, much less a true minister,
who was not born of water and the Spirit, the fire and Holy Spirit.
They raged greatly, dispatched their Sauls to Damascus, to the rulers of the nation,
crying, '`Help, help, or religion is lost, and the kingdom of Christ will go down;
behold great deceivers and seducers, and false prophets, and anti-christs are risen,
as was prophesied should come in the last days: now they are come, bestir yourselves,
make laws, catch them, whip them, imprison them, banish and burn them.`'

And truly, they lay in wait for blood, and several of us were tried for our lives,
for blasphemers, haled out of their synagogues for our pure testimony`'s sake,
some crying, '`Knock the rogues down;`' '`They are witches,`' said others;
'`Devils,`' said others; '`We have a law, and by our law they ought to die.`'

They were never without false evidence to produce,
as well as that we were frequently made offenders for our true and savoury words,
whether in reproof or exhortation uttered, with our lives in our hands,
in obedience to the heavenly vision.
No justice, no mercy: if we escaped the multitude, the magistrate had the stocking,
imprisoning or whipping of us; if we escaped the magistrate, the multitude,
at the instigation of the priest,
fell like so many greedy wolves or hungry tigers upon us,
beating and kicking and dragging us, till some part of our flesh has been like a jelly,
often breaking our heads and bones;
and some they have murdered by the like barbarous usage:
we not daring all this while to fly the place, or return them one railing accusation;
committing our cause to God alone, to plead our innocency; having no helper in the earth.

Nor were these things all our sufferings, or the depths of our tribulation.
By no means; for the sharpest of our trials were from men of a religious profession,
whose hearts contrived mischief,
and their tongues and pens uttered it with all manner of slander and contradiction;
insomuch that when we were not in the hands of the magistrates or multitude;
we were almost perpetually employed in disputations and conferences,
personally or by writing.
On which occasion, the world loving its own, we had great difficulty and wrong;
such perversions of our words and sayings, such flouts and jeers,
such interruptions and noises, as would have been abhorred of sober heathens.

However, we bore it all through the holy patience of Jesus;
and in the end of these encounters with Ephesian-like beasts,
we rarely missed of gaining some to the faith.
And finding at long run, that they could neither wrangle, slander,
nor persecute us out of that testimony we had borne for the living God,
and perceiving that the multitude began to flag,
and would no longer be the instruments of their cruelty,
taking notice of our great increase, notwithstanding all these oppositions;
as also seeing that some of their own kindred and acquaintance were converted,
whom they always confessed to be more religiously addicted than themselves,
and that this change augmented both their virtue and their tender love to their kindred;
many gave over this way of proceeding, and some moderate respite we had for a time.
But persecution came by fits; that is,
as at any time the clergy has prevailed with the civil magistrate: and because most,
if not all other ways of non-conformity hid for self-preservation;
and that we cannot desert our standard or testimony,
(since it were to be accessory to the prevalence of darkness,)
therefore has suffering been our lot above all other non-conformists;
as our nation can witness.

But blessed be the name of the everlasting God, he has been as a pillar of fire by night,
and a pillar of cloud by day, and a rock in a weary land,
and a pure spring by the wayside;
and has sustained us by the invisible cordials of his own love, life, peace and joy;
and in the ark of his eternal testament preserved us;
making good to us what he promised of old, That the old lions should be hungry,
and the young lions lack their food, and the youth should faint;
but they that waited upon the Lord, and trusted in their God,
should renew their strength: and no good thing would be withheld from them;
they should run and not be weary; they should walk and not faint.
Yes, he often compassed us about with many and precious promises,
and great was our resolution for the Lord; that with Habakkuk we could say,
'`Though the fig-tree shall not blossom, neither shall fruit be in the vines,
the labour of the olive shall fail, and the fields shall yield no food;
the flock shall be cut off from the fold, and there shall be no herd in the stalls;
yet we will rejoice in the Lord, we will joy in the God of our salvation:
the Lord God is our strength, and he will make our feet like hinds`' feet,
and he will make us to walk upon the high places;`'
and this has he done many a time to our astonishment.
For he has given us power from on high to bind kings in chains,
and nobles in fetters of iron, to tread upon the necks of our enemies,
and to possess the gates of them that once hated us.
I could write a volume of the judgments and mercies and faithfulness of the Lord;
who has kept us, increased us, confirmed us, protected us,
and comforted us to this very day: for which thousands are the souls and spirits,
that day and night in white linen, the raiment of the first resurrection,
bow and reverence, honour and praise, glorify and exalt him, that sits upon the throne,
and the Lamb who is worthy forever "`But much of that wonderment,
suffering and reproach is over; the rigour of our enemies abated;
and the blessed Light and Truth in the conscience becomes valuable in the esteem of many,
and the sincere followers of it are greatly respected;
and that by persons of very great quality.
And though the laws, oaths,
and other customs of our country restrain men of
authority from entirely falling in with us,
or conferring any secular employments upon us;
yet have they with great importunity sought to us in their own personal and family concerns,
and reposed all trust and confidence in us.
And blessed be the Lord, who has kept us in the way of integrity,
and has so marvellously turned the hearts of the great ones in the earth,
insomuch that we can say, when those who would be thought as the heavens,
have sought our destruction, '`the earth,`' mere worldly great men,
have often helped '`the woman,`' and saved us from
the raging envy of the Scribes and Pharisees:
blessed be the name of the Lord our God!
Who is a God like unto him?

And furthermore, this we know:
now that God has made this passage in the land of our nativity;
and cast his firm anchor of hope in the souls of many thousands in this island,
he will break in upon the nations about us;
and all these distresses that now are in Europe are to prepare the way of the Lord.
God will thin the people: he will pinch, pine and wither countries;
and Europe shall run into confusion more and more: and when their distress is complete,
then shall they cry early and earnestly after the Lord.
And welcome, O beauteous, shall the feet of them be,
that bring glad tidings to the weary and the distressed;
and when Europe is brought so low as to see there is no helper in the earth,
then shall heaven be in request; and to heaven shall her inhabitants look;
and from there shall he come into their hungry souls, whom they have looked for.

And this is the word of the Lord that lives in my soul to you:
the Lord whom you look for, shall suddenly come to his temple, even your hearts.
O prepare, prepare! make ready; watch unto his appearing in you,
to make you a fit habitation for his holiness to dwell in.
Let him have your whole hearts; let the mangers be for the beasts,
and not for the Babe of glory, whose very birth brings glory to God on high,
peace on earth, and goodwill towards men.
Yet sorrow goes before, and will gird all nations; for in that day,
when they shall see Him whom they have pierced, all kindreds,
tribes and families shall mourn, as one would sorrow for his first-born,
and be in bitterness as for an only child--and with such shall it be well;
for to them will it be not only a day of visitation, but redemption.

But woe unto the idol shepherds in that day, who have fed themselves and not the flock;
who have run, and God never sent them; and cried,
'`Thus says the Lord,`' and God never spoke to them; and who have preyed upon the flock,
and prepared war against those that in conscience could not put into their mouths;
that have been the great emissaries of the false prophet;
and to all that commit sin with greediness, and will have none of the Lord,
nor of the knowledge of his ways.

'`Behold I stand at the door and knock,`' says the Lord God, I am ready to be revealed.
It shall not be said, the fathers have eaten sour grapes,
and the children`'s teeth are set on edge: but thus says the Lord,
Every soul shall bear his own burden, and for the iniquity that he has done,
shall he die; unless he die to sin by unfeigned repentance; for my swift Witness,
who is faithful and true, is arising, and by him will I plead with all flesh.

Wherefore, woe to all the inhabitants of the earth,
who have cast my law behind their back, and grieved my holy Spirit;
have taken counsel and not of me, and have forgotten me days without number;
that have lived wantonly upon the earth, and consumed their days in pleasures;
have multiplied sacrifices unto me, but have not hearkened unto my word;
that serve me with their lips, while their hearts are far from me;
that offer unto me incense, and yet oppress the Holy One of Israel with their iniquities:
my soul loathes your assemblies, and your sacrifices are an abomination unto me.
O, repent!
Repent! why will you die?
Turn unto me that I may give you life: obey the light of my Son in your hearts,
and you shall yet live before me.

And all you that separate yourselves from the multitude,
in whom my Spirit has been stirring, but have quenched it with your own stirrings,
and have made a fire of the sticks that you have gathered;
and that compass yourselves about in the sparks of the fire that you have kindled,
which is not the fire that comes from heaven; behold, '`This shall you have at my hand;
you shall all lie down in sorrow.`' "`Wherefore, hear and live;
my sacrifice is in my own Spirit; whose motions you must wait for,
in the silence of all flesh; and give up yourself in obedience unto the same,
and I will touch your heart with a coal from my own holy altar;
and a living sacrifice shall you offer unto me on my sabbath-day,
in which you shall rest from your own works, and therein shall my soul be delighted,
and you shall rejoice before me: for with me, the Lord, is everlasting wisdom,
strength and refreshment.

This is the ancient way of the Lord; this is the path of our God.
To you I write, worthy and great women, that you may walk in it, and be of that number,
who at this day, wherein one cries, '`Lo here,`' another,
'`Lo there,`' may lay hold on the skirt of the true Jew,
the spiritual circumcision, revealing himself, it may be,
but as a day of small things at first in your souls; that you may see Him,
the only Rock to build upon, that your peace may be great in the Lord,
when troubles are round about you.
For by this shall the begotten of God be known,
and eminently discovered in the days of universal calamity; tranquillity, patience,
faith and perseverance, shall conspicuously shine in their very countenances.

[.asterism]
'''

[.embedded-content-document]
--

[.blurb]
=== A summons or call to Christendom, in an earnest expostulation with her, to prepare for the great and notable day of the Lord, that is at the door.

Awake, O Christendom!
Awake, and come to judgment,
for the great and notable day of the Lord is drawing quickly upon you:
prepare to meet him, you and your children,
for the hour of his judgment hastens upon you; in which all your works shall be tried,
and that by fire.
For the day of the Lord shall burn as an oven, and all the proud,
and all that do wickedly, shall be as stubble.
Yes, by fire and by sword will the Lord God Almighty plead with all flesh;
with all fleshly worshippers and workers, who live after the flesh,
to fulfill the lusts thereof: and with the spirit of judgment, and the spirit of burning,
that is,
with spiritual judgment and burning will he visit all ranks and religions upon the earth:
yes, his holy terrors shall take hold of the rebellious,
and anguish and distress shall fill the souls of the guilty.
The faces of nations shall gather paleness, and their knees smite together,
because of the anger of God, that is kindling against them, and his fierce wrath,
that is revealing from heaven against all the ungodly;
but more especially against the children of the mystery of iniquity:
it is in this day that the kindreds of the earth shall mourn with a great lamentation.

O Christendom! you have long sat as a queen that should never know sorrow;
great have been your pretences, and large your profession of God, Christ,
Spirit and Scriptures; come,
let me expostulate with you and your children in the fear and presence of Him,
who shall bring every word and work to judgment.
God is pure, and the pure in heart only see him.
Are you pure?
Do you see him?
God is a Spirit, and none can worship him aright, but such as come to his Spirit,
and obey it: do you so?
Christ is the gift of God; have you received him into your hearts?
Does he rule there?
Then have you eternal life abiding in you: if not, you are not true Christians.
The Spirit of Truth leads into all truth,
and the children of God are born of it and led by it.
But are you led into all the holy way of Truth, born of this eternal Spirit?
Then you follow not the Spirit of this world, nor do your own wills, but the will of God.
You profess the holy Scriptures; but what do you witness and experience?
What interest have you in them?
Can you set to your seal they are true, by the work of the same spirit in you,
that gave them forth in the holy ancients?
What are David`'s roarings and praises to you, who live in the lusts of this world?
What are Paul`'s and Peter`'s experiences to you, who walk after the flesh`'?

O you, who are called Christians, give ear a little unto me,
for I am pressed in spirit to write to you: read with patience and consider my words;
for behold, what I have to say unto you, concerns your eternal good.

God has so loved the world, that he has sent his only begotten Son into the world,
that those who believe in him, should have eternal life.
And this Son is Christ Jesus, "`the true Light,
that enlightens every one coming into the world;`" and they that abide not in him,
the Light, dwell in darkness, in sin, and are under the region and shadow of death, yes,
dead in sin, and see not their own states,
neither perceive the sad condition of their own souls.
They are blind to the things of God`'s kingdom,
and insensible of true and spiritual life and motion, what it is to live to God;
and in that state are alienated from God, without true judgment and living knowledge,
and under the curse.
For in Jesus Christ, the Light of the world,
are hid all the treasures of wisdom and knowledge, redemption and glory;
they are hid from the worldly Christian,
from all who are captivated by the spirit and lusts of the world.
And whoever would see them,
(for therein consist the things that belong to their
eternal peace,) must come to Christ Jesus,
the true Light in their consciences, bring their deeds to him, love him and obey him;
whom God has ordained "`a light to lighten the Gentiles,
and for his salvation to the ends of the earth.`"
Light and salvation are joined together; and none can come to salvation,
but as they come first to the light, and submit to the manifestation of it,
which leads to salvation.
For the nations of them that are saved, shall walk in the light of the Lamb, Christ Jesus.
Light and sanctification are also joined together.
If we walk in the light, as God is in the light,
the blood of Jesus Christ his Son shall cleanse us from all sin.
And light and life eternal are joined together; for in the Word,
that was with God in the beginning, and was God, by whom all things were made,
that were made, was life, and that life is the light of men.
And this is the testimony of Jesus, "`I am the light of the world; he that follows me,
shall not abide in darkness, but have the light of life.`"
Yes, it is eternal life to believe in him, in Christ the Light, to receive, embrace,
and to follow him.
And this is that "`true light (says the same beloved disciple)
that enlightens every man that comes into the world.`"
Now this light shines in darkness, in the children of darkness, in their dark hearts,
in their defiled souls and consciences; but in this darkness they comprehend it not.
Neither can man know the nature and benefit of it, while he rebels against it;
for the virtue and excellency of it is shut up and hid from the children of disobedience.
To as many as received him of old, gave he power to become the children of God;
and they that did his will, knew his doctrine to be of God,
and of power and efficacy to their salvation.

But this is the great condemnation of the world at this day,
that though God has sent his Son, a light, into the hearts of all men and women,
to manifest and reprove their evil deeds, and to save them; yet they love darkness,
they love the lusts and imaginations of their vain hearts better than this holy light,
that is given unto them for salvation: they choose Barrabas rather than Jesus.
Yes, they have set up other lights than Christ Jesus, God`'s great Light;
and other prophets than Christ, God`'s great Prophet; and other priests than Jesus,
the High Priest of the new covenant: but they are dark lights,
false prophets and blind priests.
"`All that came before me,`" says Christ, "`are thieves and robbers:`" and all that pray,
preach, sing, worship, etc. and not by the light and spirit of Jesus,
they go before Christ, before Christ comes,
before he prepares their hearts and touches their
lips with a coal from his heavenly altar;
and perform worship in their own will, time and power, and stay not for his leadings.
And therefore all such rob Christ of his office,
who is the Leader of the true Christians;
their heavenly High Priest to anoint them and offer up their sacrifice to God for them;
and Prophet, to let them see and know, by his light in their hearts,
what they ought to do; according to the new and everlasting covenant,
"`I will write my law in their hearts, and put my Spirit in their inward parts,
and they shall be all taught of me, says the Lord.`"

Now this is the question to the whole world called Christian:
do you see with this Divine light?
have you searched your hearts with it?
And are you anointed by this High Priest with his holy unction that leads into all truth?
Does this heavenly Prophet give you vision, and reveal the Father to you?
Is he your eye, your head, your wisdom?
Do you live, move and have your life and being in him, in praying, preaching and singing,
yes, in your whole conduct?
Are you renewed into his life and image, and have you heard his voice and seen his shape?
Are you witnesses of his holy rebukes, his pure judgments,
the shame and death of his cross?
Is he the fountain of your knowledge, the author of your faith?
O consider!
Are you of those that have spoken with Jesus,
who have been taught in the school of his holy cross, students in his heavenly academy?
O have you drunk of his cup, and been baptized with his baptism?
Tell me, in the fear of the Lord God, you that call yourselves Christians;
does he go before you, and lead you, as a master teaches his disciples,
and a captain leads his soldiers?
and do you follow him in all the weighty things of this life?
and does he order your minds and rule your affections?
If not, you are thieves and robbers; for you rob Christ of his office.
For God has appointed him to be the Leader and Ruler of all people; yes,
it is God`'s decree; and those whom he leads not in their thoughts, words and works,
shall never come to God: for all must come to God by him, that is,
by his Light and Spirit ruling in their hearts, which sanctifies,
regenerates and converts the soul to God.

And the cause of the confusion and contention which
is about religion in Europe at this day,
is, that men have deserted this true Light and holy Spirit,
and so are degenerated from the life and power of pure and unspotted religion,
and have attempted to comprehend Christ`'s doctrines without Christ`'s light,
and to know the things of God without the spirit of God.
And being thus miserably erred by wicked works from the one Spirit of Truth,
they have wandered into the fallible conceits and opinions of men.
And in this state, one party has contended against another:
from words they have fallen to blows, and the strongest has oppressed the weakest.
And not knowing what spirit they were of, have called light darkness, and darkness light;
putting the sheep`'s-skin upon the wolf,
and the wolf`'s-skin upon the poor sheep of Christ,
endeavouring by carnal weapons to enforce their opinions,
and to extort conformity to their persuasions by worldly laws and punishments.
All this is out of the light, life and doctrine of Christ Jesus,
and in the spirit of darkness, confusion, strife and bloodshed, which are of the devil.
All which Babel, must and shall come down by the light, power and spirit of Jesus,
now rising in the world; and hell, death and the grave shall not be able to hinder it.
For the set time, the appointed time of the Father is come, and the judgment is begun.

O you, that are called Roman Catholics, tell me, are you truly catholic, that is,
of a universal spirit?
Then you will not persecute, but love all, and be tender to all.
Are you truly Roman, and successors of that ancient apostolical church?
Then you walk not after the flesh, but after the Spirit; yes,
the spirit of Christ dwells in you, and you are led by the spirit of God,
and can call him Father in truth and righteousness,
and the Word of God in the heart is your teacher, and not the traditions of men;
for so the Romans of old time were instructed.
O consider, if you are true successors, you must follow them in the same nature,
spirit and life; for in that alone stands the Christian succession, namely, in Christ:
and every branch, church or person, that abide not in this great Vine,
are rejected for the fire.
Therefore, deceive not yourselves, as the Jews of old did, with crying,
"`The temple of the Lord, the temple of the Lord:`" and saying,
"`We have Abraham to our Father, and to us belong the fathers, covenants, law,
priesthood and chair of Moses:`" for, as the apostle said of old, so say I to you;
his servants you are, whom you obey; and he that works wickedness, is of the devil.
So that Christ`'s successors are they that take up his cross, follow him,
and abide in his holy doctrine,
that keep his commandments and themselves unspotted from the world.
And those who follow the lust of the eye, the lust of the flesh and pride of life,
are not of Christ, nor of the Father, but of the world;
subjects of the prince of the power of the air, and successors of Sodom, Gomorrah, Egypt,
Tyre, Sidon and persecuting Jerusalem; and not of the harmless, self-denying, holy,
suffering spouse of Christ Jesus, who is ruled in all things by her husband, her head,
her Lord.
O search and try with the light of Jesus,
if you are not degenerated from primitive simplicity and purity?
For great are the abominations of all sects,
that flow like a deluge throughout your countries!
Repent and turn to the ancient apostolical spirit and life,
that you may enter into the rest of God.

O you, that call yourselves Evangelics or Gospellers, are you evangelical?
Are you saved from the lusts and pleasures, and dead worships of the world,
by the mighty power of God, and led by an evangelical spirit?
If not, you are not yet redeemed, you are not yet under grace, which is the Gospel state.

For you are not taught by it, but rebel against it; how then are you,
who are yet subjects and servants of sin, true Gospellers, men of Gospel liberty,
men of deliverance and redemption; to whom immortality is brought to light,
as it is to all that truly know and receive the blessed Gospel?
How can you sing the song of the Lamb, who are not delivered by the Lamb;
but by your vain conduct crucify the Lamb, and do despite to the Spirit of grace,
and that every day?
The true Gospellers are those that receive the angel`'s message,
who is the great preacher of the everlasting Gospel, namely, Fear God,
give glory to his name, for the hour of his judgment is come;
and no more worship the beast.
Do you fear God in truth and in sincerity?
Then are you fearful of offending the Lord, and tender of God`'s glory;
then are your hearts kept clean, then are you wise to salvation;
and so you can glorify God indeed:
otherwise your prayers and praises are not evangelical in God`'s sight.

But tell me, O you Gospellers, is the hour of his judgment come to you?
is it begun at your houses yet?
How do you feel it?
has it broken your hearts?
has it contrited your spirits?
Have you known the godly sorrow?
the chastisements of the Lord, and rebukes of the Almighty?
Has his pure eternal Word divided yet between your souls and spirits,
the joints and marrow?
Have you ever been weary and heavy laden with sin?
has it been a burden to you?
Did you ever cry out in the agony of your spirits, "`Men and brethren,
what shall we do to be saved?`"
"`Who shall deliver us from the body of sin here, and the wrath to come?`"
the travail of the holy ancients.
If not, you are yet strangers to Christ and his kingdom; and if you die in that state,
where he is gone you shall never come.
For Zion, God`'s city, must be redeemed through judgment,
and her converts through righteousness: yes, the house of God cannot escape it;
wherefore, said one of old, "`If judgment begin at the house of God,
where shall the ungodly and sinner appear?`"
Woe to them that live without the judgments of the Lord
woe to them that cast his reproofs behind their backs,
and live in earthly pleasures, fatting themselves in their lusts and pleasures,
as for the day of slaughter, and treasuring up wrath against the day of wrath!
The ancient saints lived not thus;
they worked out their salvation with fear and trembling; yes,
they gave all diligence to make their calling and election sure.
Which way do you work out yours?
Habakkuk, that holy prophet, his lips quivered, and his body trembled,
that his soul might rest in the day of trouble; is this your state?
Or are you not rather worshippers of the beast at this day, lovers of the worldly,
sensual, voluptuous life, walking in the lusts of the eye, the lusts of the flesh,
and pride of life; like rebellious Israel of old, forgetting God days without number?
But this know, that all who forget God shall be turned into hell.

What is become of the fatherly visitation made to your progenitors;
those good beginnings sown in persecutions and martyrdoms?
Have you answered the lovingkindness of God therein?
Have you advanced in the way of righteousness?
Are you become a holy nation, and a peculiar people to God, zealous of good works?
Have you not betaken yourselves to the wisdom and learning of this world to make ministers,
and deserted the spirit of the Lord,
and fled to the power and policy of this world to defend and protect you,
and not to the name of the Lord, which has always been the strong tower of the righteous?
No, are you not divided one against another,
and turned persecutors for religion yourselves, denying that liberty to others,
you took for yourselves?
Ah! where is the royal law, of doing as you would be done unto?

Thus have you decayed and degenerated into a worldly clergy, and a carnal people,
holding and maintaining reformed words, in an unreformed spirit.
Yes, are not the same evils, pride, passion, malice, wars, bloodshed, persecution,
deceit, fleshly lusts, wantonness, vain pleasures and sports, yes,
all manner of worldly-mindedness to be found in you,
that were in the persecutors of your fore-fathers,
and against which your most serious and best ancestors faithfully testified?
So that the difference now is about words and sentences, and not about the life,
nature and spirit of pure and undefiled religion;
and men are to be known now by their denominations
and subscriptions to certain human creeds,
manmade faiths and forms, and not by the spirit and image of Christ Jesus,
by the nature of the true sheep, and by that holy unction,
that was the bond of the heavenly fellowship of the saints of old.

And you, that are called Reformed, with the rest of the sub-divided sects,
what better are you for your names?
Are you regenerated yet?
Are you reformed from the lusts of the eye, the lusts of the flesh,
and the pride of life; from the devil and all his works?
Are you born of the incorruptible Seed, that lives and abides forever?
And are you come out of the corruptible things, and does Christ lead you?
Is the government of your souls upon his shoulders?
Tell me, is it the new birth, that which is born of God through many tribulations,
the new man created in Christ Jesus, that calls God Father in your prayers,
and that makes mention of him in your preachings?
Or is it the first birth, of the earth, earthly, the old man,
the corrupt and unregenerated nature, that which is born of the flesh, that is to say,
of the seed of the evil one, the father of all the fleshly lusts, inventions,
imaginations and traditions of men,
that takes pleasure in the vain and wicked sports and pleasures of this apostate world,
that forget God, and turn his grace into wantonness; reproaching, nicknaming,
and persecuting the children of regeneration with scornful names and cruel punishments;
calling God Father as the Jews did,
and crucifying Christ afresh by a vain conduct at the same time.

O you degenerated Christians of all sorts, who have deserted your first love,
and degenerated from the life and power of primitive godliness;
with the light of Christ Jesus in your hearts, examine yourselves.
God has lighted your candle, search and try yourselves;
see how it stands with you as to your eternal condition, before you go hence,
and be no more in this world.
Consider, are you in the true faith of Christ, or no?
For without true faith, none can please God; and without pleasing him,
no man can be saved.
The devils believe, yes, and tremble too; that is more than thousands, called Christians,
do; and so far they are short of the very devils.
Have you faith?
let us try it in the name of God.
What is it for faith?
Does it overcome the world?
does it live and depend upon God?
can it forsake country and kindred?
turn out Ishmael?
offer up Isaac?
live a pilgrim, a stranger in the world?
Does it work by that love which can forsake all for Christ`'s name`'s sake?
does it fight against the devil?
resist his fiery darts?
overcome his assaults and temptations?
and finally, purify the soul to God`'s use?
Is this your faith, O you carnal, outside Christians?
No such matter; for you live in the flesh, fulfilling the lusts thereof;
and your care is, what you shall eat, drink, and put on,
and how you should get the mammon, friendship, and glory of this world.
Examine yourselves, and prepare; for the day of the Lord hastens upon you.
And have a care, lest you partake of the plagues,
that God has prepared for Babylon;--she that calls herself the Lamb`'s bride,
and is a harlot, that is,
those who by a lying spirit have had their hearts seduced from God and his holy fear,
yet in words profess to be his people; who call themselves Jews, but are not; Christians,
and are not, but of the synagogue of Satan;
being strangers to the circumcision in spirit,
and the baptism that is with fire and with the Holy Spirit--with fire,
to consume the fleshly nature; and with the Holy Spirit,
to beget the heavenly nature in man.
The downfall of this great city,
and the desolation of this false church through all the sects in Christendom,
is come and coming! yes, in one day shall it be accomplished,
even in the day of the appearance of Christ; who is the second Adam,
the Lord from heaven,
who by the brightness of his coming and by the breath
of his mouth in the hearts of nations,
shall reveal, and destroy this great antichrist,--this man of sin in man,
that sits in the place of God, yes, exalted above all that is called God,
requiring conformity to all his inventions and injunctions upon pain of life, liberty,
and estate: nor are any allowed to buy or sell in this great city,
but such as will receive his mark.

Woe to you all, in the name of the Lord, that call God your Father,
and are not born of him; that name his name, and hate to be reformed;
that call Jesus Lord, and not by the Holy Spirit;
who take his pure name into your mouths, and depart not from iniquity.
I say to you on God`'s behalf, as God said to the Jews of old; your prayers,
your sacrifices, and your solemn assemblies, etc. in an unconverted state,
are abomination to the Lord.
No matter for your names, your pretences, your creeds;
if you live without God in the world, that is, without his holy awe in your hearts,
without a Divine sense of his presence in your souls, and know not that godly sorrow,
that works unfeigned repentance, the only way to eternal life, your worship God loathes:
a dog`'s neck, swine`'s blood, yes, to bless an idol, or kill an ox,
is altogether as acceptable with the Lord.
God is wroth with the feigned worships, as well as common ungodliness of the world.
Come to Christ`'s Spirit, be led of it, and do not your own wills,
but the will of Christ Jesus; and then you shall know the true worship.
The true ministry and worship of God stand not in the will, wisdom,
or appointment of men, nor can they be performed by unregenerated men;
but in the leadings of his eternal Spirit, by whom all the faithful offer up themselves,
an acceptable sacrifice to God, not to live unto themselves,
but to him that has purchased them.
It is true, Christ Jesus died for the ungodly, but not that they should continue ungodly,
but take up his daily cross, and follow him.
Christ, said Peter, has offered up himself once for all, leaving us an example,
that we should follow his steps; as he was in this world, so we should be, says John,
not conformable to the rudiments, fashions, and customs of this world, that pass away;
but transformed and renewed in our minds, by the grace that he has given us;
which grace brings salvation to all that obey it, teaching such to deny all ungodliness,
and worldly lusts, and to live soberly, righteously,
and godlikely in this present evil world: because without holiness,
none shall ever see the Lord; that is God`'s decree.

Wherefore, be you not deceived, you formal and titular Christians!
God will not be mocked: such as you sow, such shall you reap at the hand of the Lord;
yes, for every idle word shall you give an account in the day of judgment.
Think not with yourselves, you have Christ to your Saviour,
and you are reconciled to God through Christ, and that God looks not upon you,
as you are in yourselves, but as in Christ; while you walk not after the Spirit,
but after the flesh: for the wages of sin is death;
but the gift of God is eternal life through Jesus Christ our Lord.
To whom?
Not to them that despise his light in their hearts, that grieve his Spirit,
and by a worldly conduct go on to crucify him;
and who follow not Jesus in the way of tribulation and regeneration.
God is of purer eyes, than to behold iniquity; and he looks upon men and women to be,
what they really are, and not what they imagine themselves to be: behold, he comes,
and his reward is with him; and he will reward all according to their works.
Sinners, while they continue in sin, can no more come into Christ, than into God;
for God is in Christ, and Christ is in God: Christ is holy, harmless, pure and undefiled,
and separate from sinners.
And if ever you would have God look upon you to be in Christ, you must come into Christ:
and you can never come into Christ, the new and heavenly man,
who is undefiled and separated from sinners,
till you come out of sin and the author of it, the devil, the old man of sin,
and leave your deeds of darkness.

Therefore be separate from every evil way: Christ the immaculate Lamb of God,
came not only to save men from wrath, but from sin, which is the cause of wrath.
"`Behold the Lamb of God,`" says John,
"`which takes away the sin of the world:`" not their sin, who will not believe in him;
but the sins of those that are weary and heavy laden, that wait, hunger, thirst,
and cry for his salvation; whom God has given for a light to lighten the Gentiles,
and for his salvation to the ends of the earth.
O you, that are called by his sacred name, repent, repent!
Prepare, prepare to meet the Lord,
who is coming in the way of his judgments to visit the inhabitants of the earth;
and put away the evil of your doings, and turn to him that he may receive you.

But woe, in the name of the Lord to all that rebel against the light of Christ Jesus,
who serve another master, and follow another captain,
and obey the prince of the power of the air,
who reigns in the hearts of the children of disobedience.
Yes, woe unto all, who are covered with a covering, and not of my Spirit;
that take counsel, and not of me, says the Lord: who gather sticks,
and kindle a fire of their own,
and compass themselves about with the sparks which they have kindled;
for this shall they have at my hand, they shall lie down in sorrow.

Woe from God to all the will-worshippers, who worship,
but not in the Spirit and in the Truth; their worship is not available.
He that worships God aright, is turned to the Spirit, and is taught and led by the Spirit.
And such as have received the Spirit of Christ, are not led by their own spirits,
nor by the spirit of this world, nor according to the inventions and traditions of men:
neither do they conform themselves to the customs and fashions of this world,
nor will they bow to the glory of this world, or the God of it.

But having seen Him, whom they have pierced with their vain conduct in times past,
they mourn, and are in great bitterness,
because they have done despite to his Holy Spirit of grace,
that strove so long with them for their redemption.
And being called by his spiritual call in their hearts, to come out of Babylon,
the great city of will-worship, confusion, and darkness, that is in the earth,
they cheerfully resign up all to follow him in the narrow way of self-denial,
as his holy disciples did of old.
And such have learned by good experience, that without Christ they can do nothing:
though in these days scarcely anything is done with him, or by him.
For he is resisted in his spiritual appearance in the consciences of those,
who make a profession of him with their mouths;
and therefore he does not many mighty works in them; yes, he is smitten, spit upon,
crowned with thorns, pierced and crucified of all false Christians,
through their rebellion and wickedness.

Woe from the great and just God, that made heaven and earth, upon all people,
that work iniquity, and forget God!
Woe to you kings and princes, that have crucified the Lord of life and glory; yes,
you have crucified him in yourselves, and helped to crucify him in others:
he lies slain at this day in your streets.
For you have not ruled for God, as you ought to have done; but for yourselves,
to please your own lusts; and have not sought the glory of the Lord,
nor the prosperity of his work in the earth, so much as the greatness of your own names,
and to enlarge your worldly dominions; often oppressing the poor,
and persecuting conscientious dissenters;
but suffering almost all manner of vice and vanity to go unpunished.
How does the lust of the eye, the lust of the flesh,
and the pride of life reign in your territories?
Are not your courts the very schools of vanity,
and nurseries of worldly lusts and pleasures, which war against the soul,
and lead to eternal destruction?
O! you have much to answer for before the great God, at the day of his terrible tribunal,
who have power in your hands, to chase away wickedness, and to reform the world.
It is written,
"`A king upon his throne of judgment scatters all evil with his eye:`"
O! that the kings and princes of the world knew this throne of true judgment!
That they had this godlike majesty, that they would purge their lands of evil doers,
that they and their people might escape the wrath and vengeance of God,
that is ready to be poured forth upon them!

And woe to you, nobles of the earth, that spend your estates in pleasures,
and your days in vanity; that like those of old, drink wine in bowls,
and stretch yourselves upon couches of ivory:
that invent musical instruments for your mirth,
but remember not the afflictions of Joseph, neither consider of your latter end.
What pride, lust and excess lie at your doors!
What spoil and waste do you make in the world!
You live as if you should never die, caring only, what you should eat,
what you should drink, and what you should put on; how you should trim,
perfume and beautify your poor mortal selves,
and at which plays and sports you should divert and
spend away that troublesome and melancholy thing,
called time, as you esteem it, instead of redeeming the time, because the days are evil,
and preparing for the eternal judgment.
Is this the way to glory?
Did Jesus give you this example?
O, he is crucified by these things!
This is far from the true nobility and Christian honour that comes from above.

Woe to you, judges of the earth, who pervert judgment for a reward,
that oppress the poor, and despise the cause of the needy,
who regard the mighty and rich in judgment,
and delay justice for the fear or favour of man; that subject the laws to your wills,
and righteous rules to your passions and interest.
Repent and be just, for God, the just God, the great Judge of heaven and earth,
shall judge you all according to your works:
and dreadful shall that day of his reckoning and tribunal be to all the workers of iniquity,
but especially to unjust and corrupt judges!

And woe to you, lawyers, that refuse no cause for money; but will plead even against law,
truth and justice, for advantage, teaching your tongues to advocate for a lie,
and your mouths for gain, to plead the cause of unrighteousness;
raising unreasonable wealth unto yourselves, by the folly,
ignorance and contention of the people.
O the equivocation, deceit, falsehood and iniquity, that is in your profession;
in which you let your consciences out to hire at every summons for all sorts of causes:
insomuch that it is the money, and not the cause, that prevails.
And the worst cause most commonly is most desired; because the client,
doubtful of his success, is usually the most liberal to you: this also is for judgment.

And woe to you, merchants and traders, that have not the Lord`'s fear before your eyes;
whose god is gold and gain,
that neither buy nor sell with regard to his just principle in your consciences,
that use vain and deceitful words,
and that are not come to the just measure and the righteous balance;
but use frauds for advantage: that neither eye the Lord`'s providence by sea,
nor his care by land;
but day and night cast about how to raise to yourselves a great name and estate,
to exalt your nests, and rank your families among the rich and the noble of the earth!
The Lord will also plead with you!
Repent and fear before God.

Woe to you, farmers and countrymen, that reward the Lord evil for good,
who gives you increase of all things in their proper seasons;
yet you discern not his hand, you regard not his care; you live without God in the world:
yet no life is fuller of the Lord`'s providence, who preserves and prospers your flocks,
who increases your wine, your corn and your grass;
instead of remembering his goodness with reverence,
and in your harvests praising him with fear, you sacrifice to your lusts,
and rejoice only in your fulness; making merry at your harvests without the fear of God,
or looking to him that gives you to increase.
Repent and fear before the God of the whole earth.

But above all others, woe to you scribes, pharisees and hypocrites,
you priests and pastors, who have taken a charge that God never gave you; who run,
and he never sent you; who say, Thus says the Lord, and he never spoke to you or by you:
that steal the words of the prophets and apostles, and with them,
make merchandize of the people;
not knowing the pure word of God in your hearts to be as a hammer, a fire, a sword,
to destroy sin, and to purge, redeem and reconcile you to God;
but boast in other men`'s lines, and speak things made ready to your hands:
that teach for hire, and divine for money; who seek honour of men,
and love the uppermost places at feasts: who speak peace to the wicked,
and sow pillows under their elbows for reward: pleasers of men more than pleasers of God.
Woe to you in the name of the Lord,
that counterfeit his commission and deceive the people;
requiring their money for that which is not bread,
and their labour for that which does not profit:
at your doors lies the blood of souls in which you have traded.
O you physicians of no value, whom have you cured?
Where is the seal of your ministry?
Is it not an abominable cheat, that you take money to cure, yet cannot cure;
that have no medicine to cure; and at last maintain that the disease is incurable?
You are they that will neither enter into the kingdom yourselves, nor allow others.
For whenever we have seen your delusions, and deserted your assemblies,
presently a packet of letters must be sent to Damascus:
the magistrate must be called upon to be a jailer and hangman for the priest.
What wars, changes and persecutions ever befell the world, since you had a being,
in which you have not been at the head or tail?
Your practices shall more and more come to light: and the day hastens,
that your very name and calling as now held shall be had in abhorrence by the nations.
O! you numerous offspring of the great, false prophet,
that has been a liar from the beginning; hereby is it known, that God has never sent you,
that you have not profited the people they are God`'s words by the prophet Jeremiah.
Weep and howl, for the day of your great calamity hastens upon you!
Your father and mother are come into remembrance before the Lord;
the hour of their judgment is at the door.
God will fill you the cup of his fury, you shall drink it at his hand.

I cannot but cry aloud to you all, of all ranks and qualities,
from the highest to the lowest, that walk not after the Spirit, but after the flesh,
daily fulfilling the lusts thereof; that you would repent and be saved.
How has Christ`'s religion been profaned,
and his holy name blasphemed by the lewd life of professed Christians!
The very heathen are scandaled,
and the nations round about have you in scorn and derision.
Arise, O God, for your name`'s sake!
O what tremendous oaths and lies!
What revenge and murders, with drunkenness and gluttony!
What pride and luxury!
What chamberings and wantonness What fornications and adulteries!
What masks and revels!
What lustful ornaments and enchanting attire!
What proud customs and vain compliments!
What sports and pleasures!
What plays and romances!
What intrigues and pastimes!
Again, what falseness and treachery!
What avarice and oppression!
What flattery and hypocrisy!
What malice and slander!
What contention and law-suits!
What wars and bloodshed!
What plunders, fires and desolations!

And it is not only committed by Christians in general one against another,
but by Christians of the same faith, sect and church one against another;
praying to the same God to destroy one another; and singing psalms to God,
when they have wickedly destroyed one another.
O the fires, murders, and rivers of blood, that lie at the doors of professed Christians!
If this be godly, what is devilish?
If this be Christian, what is paganism?
What is anti-christian?
But to make God a party to their wickedness.
O profanation!
O blasphemy!
What need is there of any other demonstration,
that Christendom is foully apostatized from the doctrine
and example of Christ Jesus and his true followers;
who says, "`If you love me, keep my commandments:
by this you shall be known to be my disciples, if you love one another.
Whosoever does not love his brother, is of the devil, and whosoever hates his brother,
is a murderer; and you know that no murderer has eternal life abiding in him.`"
And it is not to be supposed that they kill one another in love:
for murder is not the effect of love and brotherly-kindness; but of malice,
envy and revenge.

O Christendom! how are you and your children degenerated from God,
and fallen from the doctrine of Christ, whose holy name you profess!
You are become a city full of uncleanness, following other lovers than Jesus,
whose spouse you profess to be.
O you rebellious city, you cage of unclean birds,
you and your children have filled the earth with your abominations!

O how expert have you been in these impieties!
How ingenious to work wickedness,
and how fruitful in your inventions to gratify the lust of the eye,
the lust of the flesh, and the pride of life!
O how has the heathen nature as an evil leaven prevailed,
and leavened the great body of Christians at this day,
as if the end of Christ`'s coming into the world had been to furnish us with a new profession,
but not to give us a new nature; to teach men to talk, and not to live; to cry Hosanna,
but in works to crucify him.
What did the heathens, that Christians have not done?
Yes, the same lusts,
vanities and impieties that reigned among them are to be found improved among Christians.
So that it is paganism made free by the Christian profession, or heathenism christened:
and not to conform to the heathen in the Christian, is not to be a Christian,
but a heathen.
O the ignorance as well as wickedness of the present Christian world!
Verily, the Christian life is oppressed under this mass of darkness and impiety,
found in the conduct of apostate Christians;
even as Christ was grieved and burdened with the
darkness and obstinacy of the apostate Jews.
And as the hard-heartedness of the false Jews crucified him outwardly,
so has the hard-heartedness of the false Christians crucified him inwardly:
which has fulfilled what is recorded in the Apocalypse, namely,
that the Lord was crucified in Sodom and Egypt spiritually so called:
for the false Christians are the spiritual Sodom and Egypt,
who love and live in Sodom`'s sins, and Egypt`'s lusts and pleasures.
Yes, they are of the race of them that stoned the prophets and crucified the Lord of glory:
of the same nature and spirit.
The blood of Jesus lies at their doors shed, spilt and trod under foot of them;
and will one day cry for eternal vengeance against them,
if they repent not with unfeigned sorrow, and turn to the Lord with their whole hearts:
certainly, woe, anguish and tribulation shall be their portion forever!
That which they have grieved shall grieve them;
and that which they have bruised and resisted shall reject and torment them: yes,
it shall be a never-dying worm, and an endless pain to them.
O woe to the worker of iniquity in that day!
Woe to the slothful servant!
Woe to the mocker and scoffer!
Woe to the drunkard and unclean person!
Woe to them that spend their days in vanity, and their life in earthly pleasures!
Woe to the proud pharisee, and disdainful scribe!
Woe to the fearful and unbelieving!
Woe to idolaters and liars!
Yes, and woe from God to all the cruel persecutors of the innocent lambs and sheep of Jesus,
for their pure conscience to him!
For they shall have their part in the lake, that burns with fire and brimstone,
which is the second death.

O that you might escape this great damnation!
And I testify to you in the word of the Lord,
that God gives unto you all a day of visitation,
in which you may escape the wrath to come.
For this end, God has sent his Son a light into your hearts;
it is he who manifests all your thoughts, words and deeds unto you;
it is he who checks and reproves you; yes,
it is he who expostulates and strives with you;
it is he that knocks at your doors and awakens you to judgment:
who condemns every unfruitful thought, word and work in you.
Repent, I exhort you, turn to him, hear his voice, and harden not your hearts;
but while it is today, and the light shines, and the Spirit strives, O humble yourselves,
bear his judgments, love his reproofs!
And though his word be as a fire in your hearts,
and though you are even scorched within you, because of the heat thereof;
yet bear the indignation of the Lord, in that you have sinned against him.
Wait, watch and walk in the light of the Lord Jesus;
that in his blood you may feel remission of sins, and sanctification unto life eternal:
that you may no more walk after the flesh, to fulfill the lusts thereof,
but in the spirit of holiness; that you may be sealed unto the day of redemption.
O the peace, the joy, the pleasure,
and the undeclarable comfort that is daily met with
in the holy and righteous way of the Lord!

This rises powerfully in my soul,
that his form has no comeliness in it that will please flesh;
his way and worship are most remote from it.
Flesh and blood have no share in his worship;
the will and runnings of man have no part in his way.
It is neither at the mountain, where one sort runs; nor at Jerusalem,
where another sort goes; but in spirit, within the veil, hid from flesh and blood; yes,
there it is that his worship is known and performed.
Any form is more pleasant than this:
his visage is more marred than any man`'s. All will-worship,
all human invention finds acceptance, where he cannot find a place to lay his head.
O this is a bitter cup to the creature; few will drink it!
They are hard to be persuaded to sit still,
and patiently to wait for the salvation of God to
let him work all their works in them and for them.
They know not what it is to have the mouth in the dust,
to have all flesh silent before the Lord, that the voice of God may be heard;
that he may prepare them, and that the will of God may be brought forth in them.
O this mystery of iniquity, how has it wrought and how does it yet work!
It claims a right to the living child; but she has no right to it:
she can bring forth no living fruit to God.
All nations have drunk her cup: but the hour of her judgment is come.
She is seen, unvailed and condemned by the living spirit of God,
that is felt and received, and obeyed by a remnant,
who are gathered from the mouths of idol shepherds,
and all the errings and strayings of false prophets, that have no vision;
and are come to the Lord to know his law in their hearts,
and his fear and Spirit to be in their inward parts, and are taught and led by him.
These follow the Lamb, and are his host this day,
that fight under his banner with his holy testimony against the false prophet and beast:
and behold they shall prevail.
For greater is he that is in them, than he that is in the world.

O this is a great mystery, but a greater truth; Moses, the servant,
is externally more comely than he: yes, the prophets were as pleasant singers,
and as delightful instruments of music; their visions,
sights and glorious prophecies of the last days and new covenant times,
were (says one of them of old,) as a pleasant song: but the Son, the substance,
when he came,--no beauty, no excellency, no comeliness.
What is the matter?
The way is narrow for flesh and blood; there is a cross must be taken up,
a bitter cup drunk, and a baptism, yes, of blood gone through.
Man must die to his own will, affections, imaginations and carnal conceptions;
he must wait and watch, yes, continually:
his own religion and righteousness is as odious as his sin and iniquity, yes,
in a sense more dangerous.
It is no outside will do; not that which pleases the busy,
active will and mind of the creature; that gratifies the external senses,
that have prevailed against the soul.
O no! it is a hidden life, a hidden temple, a hidden worship, and that in God`'s time;
yes, a hidden manna, a hidden supper, not discernible by the vain sects in this world.
Of this tabernacle is Jesus the builder, of this covenant and worship is he author,
of this altar is he priest: to this did he gather his of old,
and to this is he gathering the nations.
And the bride says, Come; and the Spirit says, Come; and he says, Come:
and blessed are they that come, and see how good he is.

But such, who like Sodom of old, go on to grieve the spirit of the Lord,
to rebel against his light, and vex God`'s just Lot, that lives in the midst of them,
persisting in their lusts and abominations, God`'s angel shall smite them with blindness:
the day of their visitation shall pass away,
and the forbearance of God shall be at an end, and fire from heaven shall devour them.
Which, with my soul, I fervently and tenderly desire you may all escape,
whom God has taught to hate your sin, deny your glory,
and separate from all your false worships by his own light, Spirit and truth,
and to follow his dear Son in the way of regeneration,
whose love to me has taught me to love all mankind, and to seek their salvation.

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Amsterdam, the 20th of tho Eighth month, 1677.

--

[.asterism]
'''

[.blurb]
=== Tender counsel and advice, by way of epistle, to all those who are sensible of their day of visitation; and who, wherever scattered throughout the world, have received the call of the Lord, by the Light and Spirit of his Son in their hearts, to partake of the great salvation: faith, hope and charity, which overcome the world, be multiplied among you.

[.salutation]
My dearly beloved friends,

Who are sensible of the day of your visitation,
by the light of the Lord Jesus in your hearts;
and who have gladly received the holy testimony thereof,
by which you have beheld the great apostacy that is in the world, from the life,
power and spirit of God;
and the gross degeneracy that is among those called Christians, from the purity,
self-denial and holy example of Christ Jesus and his primitive followers; and how pride,
lust and vanity reign, and how Christendom is become a cage of unclean birds;
who have mourned under the sense thereof, and have cried in your souls, "`How long,
O Lord God! holy and true, will it be,
before you take to yourself your great power and reign?`"
to whom the world is become a burden,
and the vanities and glory of it but vexation of spirit;
who despise the things that are seen, which are temporal,
for the sake of the things that are not seen, which are eternal;
whose eyes look through and beyond time and mortality, to that eternal city,
whose builder and Maker is God; whose daily cries and travails are,
to follow Jesus in the way of regeneration, to live as pilgrims in this world,
for the sake of that glory, which shall hereafter be revealed and can never fade away,
that you may attain unto the eternal rest of God.
To you, my dear friends, it is, that the God and Father of Him who was dead,
and is alive, and lives forevermore, Christ Jesus, the faithful and true witness,
who has loved and visited my soul, has now moved upon my spirit to write,
and visit you with this epistle.
Receive it then, and with it, the endeared salutation of that love and life,
which are not of this world, but overcome the world.
Great and frequent are my travails for you, that you may persevere and not faint,
but endure to the end;
that you may obtain that glorious salvation and redemption which is in Christ Jesus.
Yes, for this are my knees bended before the God of the spirits of all flesh,
that you may be entirely kept, that you may so run, as to obtain,
and so fight as to overcome; that an immortal crown and kingdom may be your portion,
when all sins and sorrows shall be done away.

And that you may do this, hear my exhortation to you in the Spirit of truth.
Dwell in the sense,
that God has begotten in your hearts by the light and spirit of his Son,
who is now in his Son in you, reconciling you unto himself.
Watch, that this blessed sense be preserved in you, and it will preserve you.
For where the holy sense is lost, profession, even of the highest truths,
cannot preserve against the enemy`'s assaults;
but the gates of hell will prevail against them, and the enemy`'s darts will wound them,
and they will be carried again captive by the power of his temptations.
Wherefore, I say again, live and abide in that light and life, which has visited you,
and begotten a holy sense in your hearts, and which has made sin exceeding sinful to you,
and you weary and heavy laden under the burden of it;
and has raised in you a spiritual travail, hunger and thirst after your Saviour,
that he might deliver you,
that you might be filled with the righteousness of his kingdom, which is without end.

Dear friends, God has breathed the breath of life in you, and in measure you live;
for dead men and women do not hear, or hunger, or thirst;
neither do they feel weights and burdens as you do.
The day of the Lord is dawned upon you, and it burns as an oven: you know it;
and all the works of iniquity are as stubble before it:
you feel it so--they cannot stand before the Lord: his judgments take hold of them,
and consume them.
O love his judgments! that with those of old you may say, "`In the way of your judgments,
O Lord! have we waited for you; the desire of our soul is to your name,
and to the remembrance of you.
With our souls have we desired you in the night, yes,
with our spirits within us will we seek you early:
for when your judgments are in the earth,
the inhabitants of the world will learn righteousness.`"
Part with all, my dear friends, that is for judgment: let him arise in your hearts,
that his and your enemies may be scattered;
that you may witness him to be stronger in you, than he that is in the world.
If the desire of your soul be to his name, and to the remembrance of him,
you will love his judgments, and abide there the days he allows for your purification.
Behold, his blessed visitation is upon you;
and his holy Spirit has begotten holy desires in you, I pray,
that they may never be extinguished, and that you may never faint.
Wherefore, look unto Jesus who is the author, that he may be the finisher.
I testify for God, he has appeared to you; yes, he has said to you, as to Andrew, Philip,
etc, "`Follow me:`" and I say unto you, follow him: come and see where he dwells;
do not lose sight of him, let him be lifted up in you, and your eye unto him, who,
wherever he is lifted up, draws all such after him.
And this is the reason why people are not drawn after Christ,
because he is not lifted up in their hearts, he is not exalted in their souls;
he is rejected, oppressed, crucified and buried; yes, they have rolled a stone upon him,
and set guards, that he should not rise in them to judge them.
But blessed are you, whose eyes have seen one of the days of the Son of man:
blessed are you at whose doors he has knocked, to whose heart he has appeared,
who have received his holy visitation, who believe it is He, and not another,
and therefore have said in your hearts, with Nathaniel of old, "`You are the Son of God,
you are the King of Israel!`" and with Thomas, "`My Lord and my God!`"
O what have you, my dear friends, to do, but to keep with him forever!
For where should you go, the words of eternal life dwell with Him.
He is full of grace and full of truth,
and of his fulness you have received grace for grace.
And this is that grace which brings salvation to all who receive it,
embrace it and will be led by it.
For it teaches such, as it did the ancient Christians,
to "`deny all ungodliness and the world`'s lusts,
and to live soberly and god-likely in this present evil world;
looking for that blessed hope,
and glorious appearing of the great God and their Saviour Jesus Christ,
who has given himself for them to deliver them from all sin,
and to redeem them from all iniquity.`"
You know that you are bought with a price; now you feel it,
and in measure discern the preciousness of that price which has bought you, namely,
the life of the dear Son of God.
Grieve not his Spirit, that is ready to seal you to the day of your perfect, redemption;
but give up your bodies, souls and spirits to his service, whose they are,
that they may be ordered by him to his glory.

I write not to you as to the world,
for you are called out of the world by him that has overcome the world;
that as he is not of this world, so you may not be of this world.
Come then out of it more and more, out of the nature, out of the spirit,
out of the fruits, and out of the fashions of the world!
They are all for the fire.
Christ said, "`The world loves its own.`"
Search with the light of the Lord Jesus, what there is in you,
that the world owns and loves; for that is its own.
And consider what it is that the world is offended with;
not that which comes from itself, of its own making and inventing,
but that which crosses its inventions, that is of another nature,
and springs from another root.
Be not conformed to the fashions of this world, that please those lusts,
which grieve the spirit of God: but be renewed in your minds; and being so within,
you will be a new people without.

They that have been truly with Christ are quickly discovered, they cannot be hid.
So it was of old; the Jews said of the disciples,
"`These men have been with Jesus;`" their speech and carriage betrayed them;
their outsides were not like the outsides of other men;
they were not current with the fashions and customs of that time.
Nor can they that have been with Jesus,
conform to the vain fashions and customs of this world; wherefore be not you,
in any sort, of this world,
but give diligence to make your holy high calling and election sure: for many are called,
and few are chosen; and the reason is, they are slothful servants,
they hide their talent in a napkin, neglect the day of their visitation,
and work not out their salvation with fear and trembling:
and then the night overtakes them, in which they can never work the works of repentance;
and the things that belong to their peace are hid from their eyes forever.

But the Lord forbid that it should be so with any of you!
I hope, yes, I believe better things of you.
And I am assured, that as you keep your hearts chastely to the light and grace,
with which you have been visited of the Lord, you shall be kept to eternal salvation.
For they are saved that walk in the light: into the light the enemy cannot come;
for the Light is Christ Jesus, and the enemy has no part or place in him;
he is driven out from the holy place by transgression,
and he is now a fugitive from heaven; but he goes up and down the earth,
seeking whom he may devour, whom he can catch and carry away with his baits and snares.

Wherefore, woe to the inhabitants of the earth, that is, the earthly inhabitants,
such as love and live in the earthly nature; for all such shall be a prey to him,
he shall have power over them, and keep up his kingdom in them.
But those who receive and abide in Christ Jesus, the Light, Life and Truth,
are out of his reach; they are in the munition of rocks, under the pavilion of the Lord,
and in the safe ark of the most high God.
However, he is permitted to tempt and try, till the time shall come,
that he is not only trodden under foot,
but also bound and cast into the lake that burns with fire and brimstone.
And he is the greatest enemy to those who turn their backs upon him; wherefore,
he watches to surprise them, that he might take them at unawares,
and triumph over their failings.
And for that reason,
Christ Jesus preached the watch earnestly and with repetition to his disciples.

My dear friends, there be several things, or the enemy in several appearances,
that will attend you in your holy march to the eternal land of rest;
of which I would caution you,
that you may none of you make shipwreck of any of those holy beginnings
you have experienced by the light and spirit of the Lord.
Beware of vain thoughts, for they oppress and extinguish the true sense.
These vain thoughts arise from the enemy`'s presentations of objects,
and the mind`'s looking upon them till they have made their impressions upon the mind,
and influenced it into a love of them.
This is a false liberty, a dangerous, yes,
destructive liberty to the holy sense that God has begotten in any.
For as that is not received but hindered by such thoughts, so it is not improved,
but destroyed by them.
The Divine sense in the soul is begotten by the Lord: it is his life and Spirit,
his holy breath and power that quickens the soul,
and makes it sensible of its own state and of God`'s will;
and that raises fervent desires in it to be eternally blessed.
This is that at which Satan rages; he fears his kingdom,
he finds that He is come who will cast him out of his possessions.
He cries out, "`Why are you come to torment me before my time?`"
He is the father of vain thoughts, he begets them in the mind,
on purpose to draw it off from that sense,
and to exercise it in a variety of conceptions,
in a self-liberty of thinking and imagining concerning persons and things.
Here he offers his baits and lays his snares,
and never fails to catch and defile the unwatchful soul.

If you should say, What are these vain thoughts?
I tell you, my friends, all those thoughts and conceptions,
that either bring not real profit to the soul, or that grieve,
hurt or oppress that holy sense, which is begotten of God in the soul.
And that by which thoughts are to be examined, is the light of Christ Jesus.
For as "`whatever may be known of God is manifested in man,
for there God has shown it him,`" as says the apostle Paul to the Romans;
so "`whatever is reproved, is made manifest by the light; for whatever makes manifest,
is light,`" says he to the Ephesians.
By this light of Christ Jesus, examine your own thoughts; see from where they rise,
from where they come, and to what they tend.
Friends! here is a mystery; and the evil one works here in a mystery.
For where he cannot prevail to draw out the mind from its sensible habitation,
to embrace his representations of old lusts and pleasures, that are wicked in themselves;
he will present you with lawful objects, your outward enjoyments, business and calling,
and steal upon your minds in the crowd of these lawful things, and there lay his snares,
hid and covered, and at unawares catch you.

My dear friends, blessed are they who see Jesus their Captain, going before them,
and counselling and leading them in all their outward and lawful concerns,
that they offend not.
For my friends this know; you may unlawfully think of lawful things,
either in thinking on them unseasonably,--mark that,
when your souls should be wholly retired and exercised in the Lord`'s light,
to feel his presence, in which is heavenly life:
or in thinking on lawful things carelessly, not with regard to your Guide,
even Him that has bought you throughout with his own precious blood,
that he might have the government of your bodies, souls and spirits; that is,
of your bodily concerns, as well as of the things relating to your souls and spirits.
This prevents much harm and mischief in business and families,
and preserves the Divine sense that God has begotten, and the creature in it;
so that its fellowship and peace with the Lord runs as a river--it
is not stopped or hindered by the designs of the enemy.
Or lastly, in thinking on lawful things excessively, too much, more than is needful,
without limits; thereby gratifying the fleshly mind, which is enmity with God,
and that sense which he begets in the soul.
O the mountains that are raised by such vain thoughts, between God and the soul!
How does the soul come under an eclipse, lose sight,
and at last all sense of the living God, like men drowned in great waters!
And thus many have lost their condition and grown insensible;
and then questioned all former experiences, if they were not mere imaginations;
till at last they arrived at atheism, denying and deriding God and his work,
and those who kept their integrity;
for whom is reserved the blackness of darkness forever,
unless they timely and truly repent.

But when this subtle enemy of man`'s salvation,
sees that he cannot make you bow to the glory of this world,
that all his snares which he lays in the things that are seen, which are temporal,
are discovered and broken;
and that your eyes are directed to those things that are eternal,
then will he turn accuser; he will aggravate your sins,
and plead the impossibility of their remission:
he will seem to act the advocate for the justice of God,
that he might cast you into despondency, that you may doubt of deliverance and salvation.
Many are the thoughts, with which he perplexes the sons and daughters of men:
but this know, that he was a liar from the beginning.
For the Lord does not visit the souls of any, to destroy them, but to save them.
For this end has he sent his Son, a light, into the world;
and they that bring their deeds to it, are not of the devil, who hates the light.
Neither does the Lord cause people to hunger and thirst after him,
and not fill them with his good things.
Be assured, my friends, wherever the Lord has begotten desires after him,
and wherever sin is become exceeding sinful, yes, a burden to the soul,
the devil`'s kingdom is shaken, the prince of this world is begun to be judged,
and God is at work for the redemption of that soul.
Hearken not to the voice of the serpent,
for that lost your first parents their blessed paradise;
and with the same subtle and lying spirit,
he would hinder you from returning into paradise.

But when he is herein disappointed he shifts his temptation, and presents another;
namely, that though you have begun well,
yet you will never be able to hold out to the end; that the temptations are so many,
and the enemies so strong, they are not to be overcome by you; and that it were better,
never to profess such high things, than to fall short of them;
that this will but bring reproach to the way, and the people of it.
Again, that it is curiosity, and spiritual pride, and conceitedness,
for you to be thought better than others, with the like suggestions,
on purpose to stagger your resolutions, and weaken your faith.
Ah! he is a devil still, a liar, and a destroyer; look not to him, but to Jesus,
who has called you.
Keep but your eye to him, of whom the brazen serpent in the wilderness was a figure,
and he shall cure you of all diseases,
of all wounds and stingings of serpents and scorpions,
etc. that may attend you in the wilderness travel, which is the hour of your temptation.
God is exalting him in you, a Saviour; therefore he is manifested, namely, to destroy sin.
Yes, stronger is he that is in you, than he that is in the world:
he is able to bind the strong man, and cast him out; do but believe truly in him,
and cleave to him.
Remember there were evil spies of old, those who brought false intelligence,
that Canaan was a pleasant land, but the way impassible;
but the faithful entered and inherited.

Keep therefore in the righteous life of Jesus, and walk in his holy light;
and you shall be preserved through all exercises and difficulties unto the eternal Canaan,
the land of rest.
Neither wonder at these things, that temptations attend you,
or that the Lord tries and proves you; it is the way of all that are gone to God.
For even Jesus was tempted and tried, and is therefore become our Captain,
because he overcame.
Neither be cast down, because the Lord sometimes seems to hide his face from you,
that you feel not always that joy and refreshment, which you sometimes enjoy.
I know what work the enemy makes of these withdrawings of the Lord.
Perhaps he will insinuate, that God has deserted yon in his displeasure,
that you must never expect to see him, that he will never come again:
and by these and the like stratagems, he will endeavour to shake your faith and hope,
and distract you with fear, and to beget great jealousies and doubts in you;
and by impatience and infidelity frustrate your good beginnings.
But though David said of old, in the distress of his soul,
"`One day shall I fall by the hand of Saul;`" yet he overcame him, and had the crown.
Yes, the Lord Jesus himself cried out in the agony of the cross, "`My God, my God,
why have you forsaken me!`" nevertheless he gloriously triumphed over all,
and led captivity captive, for the joy that was set before him: which joy is before you:
it is the mark of the prize of your great and holy calling.
Wherefore faint not, neither murmur,
if your spiritual Moses seem to withdraw awhile from you.
Do not make images in his absence, neither wax wanton;
but possess your souls in holy fear and patience,
waiting with holy reverence and diligence for his appearance,
who is your victorious Leader.

All these things are for your good, that proud flesh may be debased,
and that the soul may be redeemed.
Wherefore, bear the hand of the Lord; whom he loves, he chastens;
his anger lasts not forever, but his mercies endure forever.
Shrink not from the pure operations of his holy Word,
let it divide asunder between the soul and spirit, the joints and marrow in you;
allow your right hands to be cut off, and your right eyes to be plucked out,
that do offend; let not the pain scare you.
O bear the pure searchings of this heavenly Word!
Yes, if your minds be stayed in it, you will find it to be a word of patience,
which will keep you; for all virtue is in it: keep it and be still.
"`It is good,`" said one of old, "`that a man should both hope,
and quietly wait for the salvation of God.
Yes, it is good for a man that he bear the yoke in his youth;`" this is your youth,
and such a one "`sits alone, and keeps silence, because he has borne it upon him.`"
Ah! blessed are they that bear this holy yoke, who are come to this silence,
who die daily; that not they, but Christ may live and rule in them: therefore hear him,
and take up his cross, and follow him.
Follow him, keep him company; he has beaten the path, and trodden the way;
start not aside at his cup, neither shun his baptism: go with him to Caiaphas, to Pilate,
and to the cross; die with him to the world,
and you shall rise with him unto life eternal.
Honour, glory, and immortality, are at the end of this holy race:
O that you may run it with cheerfulness and perseverance!

But this is not the utmost stratagem of the enemy:
he has yet a more plausible and a more dangerous device,
with which to destroy the holy sense that God has quickened,
where he sees these temptations resisted,
and that he cannot hinder a religious work in the soul,
by any of his baits taken from the things that are seen; and that is,
his drawing you into imaginations of God, and Christ, and religion;
and into religious duties, not in God`'s way or time, nor with Christ`'s Spirit.
Here he is transformed into the appearance of an angel of light,
and would seem religious now, a saint, yes, a leader into religion,
so that he may but keep Him out of his office, whose right it is to teach, prepare,
enable, and lead his children with his holy power and Spirit.
Yes, if he can but keep the will of the creature alive,
he knows there is a ground for him to work upon; a place that he can enter,
and in which his seed will grow.

If this will of man is standing, he knows that the will of God cannot be done on earth,
as it is done in heaven.
O! this will is God`'s enemy, yes, the soul`'s enemy; and all will-worship arises hence:
it is the offspring of the serpent and of the will of man; and it can never please God.
Let all beware of this; God is a Spirit, and he will be worshipped in his own Spirit,
in his own life.
The worship of God stands in the will of God:
and is not brought forth of the will of the flesh, or of the will of man.
Remember that the word came not to Esau, the first birth,
the hunter who stayed not at home; but to Jacob, the plain man, he that dwelt in tents;
to him came the word of the Lord, that dwelt in a still and quiet habitation.
For in the true silence is God`'s word heard, into which the hunting nature of Esau,
the first birth, can never come.
It can never stand still, and therefore it can never see the salvation of God.
Against this nature watch, and know Jacob that inherits the birth-right,
the election of God, though now a worm, to wrestle and prevail.
Then worm Jacob, is Israel a prince, to whom belongs the statutes and the ordinances.
The word came to Jacob, and the statutes to Israel: here is dominion, government,
exaltation.
This is the lot of worm Jacob.
Wait therefore, till the angel move upon the waters, before you step one step.
Are you followers of the lamb, who has visited you, the Captain of your salvation?
Run not in your own wills, wait for his word of command,
do nothing of your own head and contriving, yet do all with diligence that he requires.
Remember what became of them of old, who offered false fire: and stay,
till a coal from his holy altar touch your hearts and your lips.
Jesus told his mother at the marriage in Cana in Galilee, his time was not come:
he rejected the will in her, and stayed till his time was come, that is,
his Father`'s time,
"`in whose hands are the times and seasons;`" whose will he came to do, and not his own;
leaving us therein a blessed example, that we should also follow his steps, that is,
not to attempt to perform even the things of God in our own wills,
nor out of God`'s season and time, which is the best: for in his seasons he is with us;
but in our own seasons and wills, he withdraws himself from us.
And this is the cause,
that the nation`'s worshippers have little sense of God in their hearts,
and that their priests cry out against inward sense; lest the people should go alone,
and come to a more acceptable worship.

My dear friends, as you would enjoy God`'s presence, love, and life,
and be acceptable with him, wait in his holy light, and Spirit that has visited you,
against these stratagems of Satan, and wake not your Beloved before his time:
watch against the will, that instrument of Satan and enemy of God`'s glory,
and your own comfort.
Let it be bridled, subjected, and kept under Christ`'s yoke, yes, subdued;
that the will of God may be done in you, and by you, which brings glory to the Lord,
and eternal peace to the soul.
One sigh rightly begotten, outweighs a whole volume of self-made prayers;
for that which is born of flesh, is flesh, and reaches not God`'s kingdom,
he regards it not; and all that is not born of the Spirit is flesh.
But a sigh or a groan, arising from a living sense of God`'s work in the heart,
pierces the clouds, enters the heavens; and the living God hears it, his regard is to it,
and his Spirit helps the infirmity.
He loves that which is of himself, and has care over it, though as poor as worm Jacob.
"`For the cries of the poor, and the sighing of the needy, will I arise,`" says the Lord;
even the poor in spirit, who have parted with all that they may win Christ;
who need him only and seek him above all; who have no helper in the earth,
but have denied all earthly helps, that he might bring and work their salvation for them.
And as you are not to run in your own wills,
or to offer up sacrifices of your own preparing,
so have a care how you touch with those that do; how you bow to their wills,
and join with their sacrifices.
For all these things greatly help to extinguish the Divine
sense begotten in your hearts by the Word of life.
And as you are faithful to the light and Spirit of Christ,
which gives you to discern and relish between that which stands in your own will,
and the will and motion of the Spirit of God in yourselves; so will you,
by the same light, discern and savour between that which proceeds from the will of man,
and the will and motions of the Spirit of God in others; and accordingly,
either to have or not to have fellowship with them.
For what has light to do with darkness?
or what has spirit to do with flesh?
or what has life to do with death?
for "`the grave cannot praise you, O Lord; death cannot celebrate you;
they that go down into the pit cannot hope for your truth.
The living, the living, he shall praise you, as does my soul this day.`"
This was the testimony of king Hezekiah, and it stands true forever;
according to the prophet Isaiah, "`You have ordained peace for us,
for you have wrought all our works in us.`"

Wherefore, I exhort you in the Spirit of truth, and in the counsel of the God of truth,
keep in the Divine sense and watch, if you would endure to the end in the will of God.
And I say again, Touch not with man-made ministries, nor man-made worships,
let their words be never so true:--`'Tis but man, `'tis but flesh, `'tis but the will;
and it shall have no acceptance with God.
This is the golden cup of her, who has gone from the leadings of the Spirit,
with which the nations are defiled; have nothing to do with it.
Keep to Christ Jesus, God`'s great Light; follow him as he shines in your hearts,
and you will not walk in darkness, but have the light of life;
not of death to condemnation, as in the world; but unto life,
which is justification and peace.
And remember, that nothing brings to Christ, that comes not from Christ.
Wherefore, all ministry that comes not from Christ,
God`'s great Prophet and High Priest to all true-born Christians,
cannot bring people to Christ.
Man only gathers to man, to hear and believe in man, and depend on man.
And if the church of Corinth sought a proof of Christ`'s speaking in Paul,
who had begotten them, and had wrought the signs and works of an apostle in them,
how much more reason have you to demand a proof of Christ`'s
speaking in the priests and ministers of this world,
who have not wrought the signs and works of apostles or true ministers?
And by what should you try them, but by the light and Spirit of Christ in you?
Yes, it is Christ Jesus in you, that gives you to savour,
if others speak from Christ in them.
And to this the apostle refers the Corinthians, for a proof of Christ`'s speaking in him:
for nothing leads to God, but that which came from God, even Christ Jesus,
the Son of God.
O let him be your vine: and know him to be your fig-tree: sit under his holy teachings,
whose doctrine shall drop as myrrh upon your souls:
he will feed you with the bread of God, that comes from heaven,
that feeds and leads them there that feed upon it: and He is that bread.

Therefore, wait and watch unto his daily and hourly visitations to your souls,
and against all the approaches of the enemy; that so he may not take you at unawares,
but that you may be preserved from the power of his darts,
and the force of his temptations, by the holy armour of light,
the defence of the faithful ancients; if you be willing and obedient,
you shall eat the good of the land.
Now is your day, now is your time: work while the Light is with you; for the night comes,
in which none can work: not only the night of eternal darkness to the wicked,
but the night of death unto all; for, in the grave there is no repentance,
neither can any man there, work the works of God.
You know the foundation; is he elect?
is he precious to you?
have you chosen him?
yes, I am satisfied you have: see what you build upon him.
Have a care of hay, straw, and stubble! have a care of your own wills and spirits!
Labour not for the bread which perishes, as all the bread of man`'s making does: but,
labour you in the light and strength of the Lord for the bread which never perishes,
that bread which comes from heaven,
which nourishes the soul in that life that is heavenly, and is hid with Christ in God,
the root and father of all life; that of this fountain you may drink,
which is clear and pure, and comes from the throne of God and of the Lamb,
and not of the muddy puddle of man`'s invention.
There is a bread that perishes, and there is a drink that perishes,
and woe to them that feed thereon, for their souls shall perish also, if they repent not.
But there is a bread that never perishes,
and there is a fountain that springs up unto eternal life,
and blessed are they that feed and drink thereof;
for they shall have eternal life with God.
This is that which only satisfies what is born of God; it will feed on no other bread,
and drink of no other water.
I cannot but warn you all, who are come to the Lord`'s day,
that you cease from all other food, from man and man`'s will and invention;
for that stifles the Divine sense, that overlays and kills this heavenly birth.
There are no grapes to be gathered of thorns, nor figs of thistles:
keep to your own vine and fig-tree, Christ Jesus; sit under him,
that you may eat of his fruit, which is the fruit of life, the hidden manna;
hid from the nature and spirit of this world, a mystery unto it.
Two things consider; first, you must wait till the manna comes;
and then you are not to be idle, you are to work and next, as it daily comes,
so it must be daily gathered and fed upon: for the manna that was gathered yesterday,
will not be food for today; it will not keep for that use.
As it was outwardly, so it is inwardly.
Time past is none of yours: it is not what you were, but what you are;
God will be daily looked unto.
Did you eat yesterday?
That feeds you not today: therefore, Jesus taught his disciples, and us in them,
to pray for our daily bread, for the present sustenance; and to look no further,
but depend upon the Lord, and live by faith in him that raised up Jesus from the dead;
so that the time to come is no more ours than the time past can be recalled.

Wherefore, blessed are they that fear the Lord and confide in him,
they shall never be confounded: they shall lack no good thing, for the Lord loves Israel;
he "`is good unto Israel,`" and to all "`that are
of an upright heart;`" whose hearts look up to heaven,
and not down to the earth; neither love nor live in the vain lusts of the world.
Such shall abide in his holy tabernacle, such shall dwell in his holy hill,
even they that walk uprightly, that work righteousness,
and speak the truth in their hearts; in whose sight a vile person is contemned,
but who honour them that fear the Lord.

O! my dear friends, I know experimentally, that this is hard to flesh and blood,
to that which is born of the corruptible seed;
but that can never enter into the kingdom of God: that must be crucified by Christ,
which has crucified Christ: blood requires blood.
Wherefore, give that which is for the famine to the famine; for the fire to the fire;
and for the sword to the sword.
Let all the sinful lusts be famished, let the stubble be burnt, and the corrupt, yes,
and the fruitless tree that cumbers the ground, be cut down and cast into the fire.
Let the work of the Lord be done in you; let him purge his floor thoroughly;
that you may come out as pure as gold seven times tried,
fitted for his use who has chosen you;
that you may bear his mark and wear his inscription,
"`Holiness to the Lord;`" so you will be vessels of honour in his house.
Therefore, I say, let your houses be swept by the judgments of the Lord,
and the little leaven of the kingdom, leaven you in body, soul and spirit,
that holy temples you may be to his glory.
This, I know is your desire, who are on your travel to this blessed enjoyment.

Well, you believe in God, believe also in Christ the Light, who has visited you:
and if you truly believe, you will not make haste:
you will not make haste out of the hour of judgment;
you will stay the time of your trial and cleansing, that you may be, as I said,
pure as gold seven times tried; and so receive the Lord`'s mark and stamp,
his image and approbation; that you may be his throughout, in body, soul and spirit;
sealed to him in an eternal covenant.

Dear friends, gird up the loins of your minds, watch and hope to the end;
be not slothful, neither strive; despond not, nor be presumptuous: be as little children;
for of such is the kingdom of God.
Dispute not, neither consult with flesh and blood:
let not the prudence of this world draw you from the simplicity that is in Christ Jesus.
Love and obey the Truth; hide his living Word in your hearts; though it be as a hammer,
a fire, a sword; yet it reconciles and brings you to God,
and will be sweeter to you that love it, than is the honey and the honey-comb.
Fear not, but bear the cross; yes, without the camp, the camp of this world`'s lusts,
glory and false worships.
But this know; when the enemy can prevail by none of these stratagems, if you resist him,
as the god of the world`'s glory, the prince of the air, and the false prophet,
then he turns dragon; then he declares open war; then you are heretics, fanatics,
enthusiasts, seducers, blasphemers, unworthy to live upon the earth.
But in all these things "`rejoice, and be exceeding glad,
for great shall be your reward in the kingdom of the Father.`"
What if your parents rise up against you; if your brethren betray you;
if your companions desert and deride you; if you become the song of the drunkard,
and the scorn and merriment of the vile person; yes,
though the powers of the earth should combine to devour you,
"`let not your hearts be troubled.`"
Shun not the cross, but despise the shame, and cast your care upon the Lord,
who will be afflicted with you in all your afflictions; in the fire he will be with you,
and in the water he will not forsake you.
Let your eye be to Him, whose name is as a strong tower,
the sanctuary of the righteous in all ages;
that you may be able to say in your hearts with David of old,
"`The Lord is my light and my salvation, whom shall I fear?
The Lord is the strength of my life, of whom shall I be afraid?
Though a host should encamp against me, my heart shall not fear;
though war should rise against me, in this will I be confident.
One thing have I desired of the Lord,
that will I seek after,--that I may dwell in the
house of the Lord all the days of my life,
to behold the beauty of the Lord, and to inquire in his temple.
For in the time of trouble he shall hide me in his pavilion, he shall set me upon a rock.
When my father and my mother forsake me, then the Lord will take me up.
I had fainted,
unless I had believed to see the goodness of the Lord in the land of the living.
Wait on the Lord, be of good courage, and he shall strengthen your heart: wait, I say,
on the Lord.`"

My dear friends, let it be your daily and hourly work to wait upon God.
How often does David speak of waiting upon God?
he felt the sweetness of it; therefore retire into your holy chamber: be still,
and the Lord will speak comfortably unto you.
Blessed are they that wait upon him, whose expectations are only from him:
"`for though the youths shall faint and be weary, and the young men shall utterly fall,
they that wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles, they shall run and not be weary,
they shall walk and not faint!`" "`I waited,`" says David,`" patiently upon the Lord,
and he inclined unto me and heard my cry.`"
And this was his testimony, "`Behold the eye of the Lord is upon them that fear him,
to deliver their soul from death, and to keep them alive in famine:
for the Lord is nigh unto them that are of a broken heart,
and saves such as be of a contrite spirit:`" David knew it, therefore he could speak it.

My dear friends, who are compassed about with many tribulations; the Lord God,
your staff and strength, is near you to sustain you.
Have you borne the reproach of Jesus and despised the shame of his cross,
and did he ever desert you?
Be not cast down, though to the eye of reason there seems none to help, no,
not one to save: though enemies within, and enemies without,
encamp themselves against you; though Pharaoh and his host pursue you,
and great difficulties be on each hand, and the Red Sea before you; stand still,
make no bargains for yourselves, let all flesh be silent before the Lord,
and his arm shall bring you salvation.
Yes, when you are ready to go down into the pit, when your throat is dry with crying,
and your eyes seem to fail with waiting, his salvation shall spring as the morning;
because his mercies are to all generations,
and the seed of Jacob never sought his face in vain.
"`This poor man cries,`" says David; what poor man was this?
He that is poor in his own eyes; that has no helper in the earth but God.
"`This poor man cried, and the Lord heard him and saved him out of all his troubles.`"
"`Our souls,`" said the righteous of old, "`waited for the Lord,
for he is our help and our shield forever.`"

Wherefore, my dear friends, be not you discomforted,
for there is no new thing happened unto you: it is the ancient path of the righteous.
"`For your sake,`" says David, "`have I borne reproach;
I am become a stranger to my brethren, and an alien unto my mother`'s children:
when I wept and chastened my soul with fasting, that was to my reproach.
I made sackcloth also my garment, and I became a proverb to them.
They that sat in the gate, spoke against me; and I was the song of the drunkards.
Save me, O God! for the waters are come in unto my soul;
and the water floods are ready to swallow me up.
They persecute him whom you have smitten; and they grieve those, whom you have wounded.`"
Do you not know this, dear friends?
are not your tears become a reproach, your fasts a wonder, your paleness a derision,
your plainness a proverb, and your serious and retired conduct a by-word?
Yes, when the Lord has wounded, have not they also grieved?
And when the Lord has smitten you, have not they mocked?
But this was David`'s joy, "`The Lord is my Shepherd, I shall not want:
he restores my soul, he leads me in the paths of righteousness for his name`'s sake;
he makes me to lie down in green pastures: he leads me beside the still waters.
Yes, though I walk through the valley of the shadow of death, I will fear no evil;
for you are with me; your rod and your staff they comfort me.`"
Who was the comforter and preserver of Shadrach, Meshech and Abednego,
that refused to obey the king`'s command against the commandment of God:
they would not bow to his image; but rather chose the fiery furnace,
than to commit idolatry, or bow to another thing, than to the living God.
"`Did not we cast three men into the midst of the fire?`"
said Nebuchadnezzar, "`Lo!
I see four men loose, walking in the midst of the fire, and they have no hurt:
and the form of the fourth is like the Son of God.`"
O my friends! the fire obeys him, as well as the winds and seas:
all power is given to the Son of God, who is given to you for your salvation.
Well, Shadrach, Meshech and Abednego, the king calls out of the fire,
and they have no harm;
though the mighty men that cast them into the fiery furnace were consumed.
The God of Shadrach, Meshech and Abednego, is magnified by the king`'s decree,
and Shadrach, Meshech and Abednego, are by the king highly preferred.
Here is the end of faithfulness; here is the blessing of perseverance.
God will bring honour to his name, through the patience and integrity of his people.

And it was this Son of God who preserved Daniel in the lion`'s den; it was his voice,
that David said, "`divides the flames of fire; he rides upon the winds,
he sits upon the floods.
The voice of the Lord is powerful, the voice of the Lord is full of majesty:
they that trust in him shall never be confounded.
Blessed are they whose God is the Lord:
for he is a present help in the needful time of trouble.
The angel of the Lord encamps round about them that fear him, and he delivers them.
O taste and see that the Lord is good: blessed is the man that trusts in him.
O fear the Lord; for those that fear Him lack nothing.
The young lions shall lack, and the old lions suffer hunger; but they that seek the Lord,
shall lack no good thing.
Many are the afflictions of the righteous, but the Lord delivers them out of them all;
for the Lord redeems the souls of his servants,
and none of them that trust in him shall be made desolate.`"

For which cause, my dear friends, cast away every weight and every burden,
and the sin that does so easily beset you.
Neither look at the enemy`'s strength, nor at your own weakness; but look unto Jesus,
the blessed author of your convincement and faith: the mighty one,
on whom God has laid help for all those that believe in his name,
receive his testimony and live in his doctrine; who said to his dear followers of old,
Be of good cheer, I have overcome the world.
Fear not, little flock; it is your Father`'s good pleasure to give you the kingdom:
and they that endure to the end shall be saved.
I will not leave you comfortless, said he, I will come to you: he that is with you,
shall be in you.
This was the hope of their glory, the foundation of their building, which stands sure.
And though sorrow comes over night, yet joy shall come in the morning.
"`You shall weep and lament,`" said Jesus, "`but the world shall rejoice:
and you shall be sorrowful,
but your sorrow shall be turned into joy,`" and their rejoicing into howling.
"`And lo!
I am with you always to the end of the world.`"
Be therefore encouraged in the holy way of the Lord;
wait diligently for his daily manifestations unto your souls;
that you may be strengthened in your inward man,
with might and power to do the will of God on earth, as it is done in heaven.
Watch, that you enter not into temptation!
Yes, watch unto prayer, that you enter not into temptation,
and that you fall not by the temptation.
Christ said to Peter, "`Can you not watch one hour?`"
Every one has an hour of temptation to go through;
and this is the hour that every one is to watch.
Jesus, the Captain of our salvation, was under great temptations; he was sad unto death;
he sweat drops of blood; but he watched, he prayed, he groaned, yes,
he cried with strong cries; but through suffering overcame: and remember,
how in the wilderness he was tempted, but the angels of the Lord ministered to him.
So they that follow him in the way of the tribulations and patience of his kingdom,
God`'s angel shall minister unto them all: yes,
he will keep them in the hour of temptation; he will carry their heads above the waves,
and deliver them from the devouring floods.

Wherefore, finally, my friends, I say unto you, in the name of the Lord, Be of good cheer!
Look to Jesus and fear not man, whose breath is in his nostrils:
but be valiant for the Truth on earth, love not your lives unto the death,
and you shall receive a crown of life and glory; which the God of the fathers,
the God of the prophets, the God of the apostles,
and the God of the martyrs and true confessors of Jesus, yes,
the God and Father of our Lord Jesus Christ, shall give unto all those,
that keep the pure testimony of his Son in their hearts,
and patiently and faithfully endure to the end.

Now to him that is able to keep you from falling,
and to present you faultless before the presence of his glory with exceeding joy;
to the only wise God, our Saviour, be glory and majesty, dominion and power,
both now and ever, Amen!

I am your friend that sincerely loves you, and earnestly travails for your redemption,

[.signed-section-signature]
William Penn.

[.asterism]
'''

[.blurb]
=== A Tender Visitation, in the Love of God that overcomes the world, to all people, +++[+++especially] in the High and Low Dutch nations, who hunger and thirst after righteousness, and desire to know and worship God in truth and in sincerity: containing a plain testimony to the ancient and apostolical life, way and worship, that God is reviving and exalting in the earth, in his Spirit and Truth.

[.salutation]
Friends,

In that love wherewith God, the Father of all mercy,
and our Lord Jesus Christ has loved and visited my soul, I likewise love and visit you;
wishing in the same love, that you with all the saints,
might come to experience what is the knowledge, faith, hope, worship and service,
that are of and from God, and which alone are truly acceptable unto him.
And that you might so run as to obtain; and being armed with the spiritual weapons,
may so fight, as to gain the prize and inherit the crown; so that the great God,
the Lord of heaven and earth, he who shall judge the quick and the dead,
may be known by you to be your God, and you may know yourselves to be his children; born,
not of blood, nor of the will of the flesh, nor of the will of man,
but born again of his holy and incorruptible Seed, by the Word of God,
born of his Spirit, and joined unto him in an everlasting covenant:
that while you live here, you may not live to yourselves, but to the glory of God;
and when you have finished your course may lay down your heads in peace,
and enter into everlasting rest with the faithful;
where all tears shall be wiped away from your eyes,
and everlasting joy and gladness shall be the portion of your inheritance.

Let me therefore, friends, speak freely and be open-hearted unto you,
and consider you my words in the fear of God, for I am pressed in spirit to write to you.

[.numbered-group]
====

[.numbered]
_First,_ Have you all turned yourselves to God, who was the teacher of Adam,
while in his innocency, who was the teacher of the Israelites, through his prophets,
and of the true Christians through his Son Jesus,
through whom he speaks his will in the hearts of all true Christians?
if not, then are you yet erring from his Spirit,
and going astray from the Lord who is the teacher of the new covenant.

[.numbered]
_Secondly,_ Know you the end and design of the coming of Christ?
are you come to an inward experience of what the same is?
Hearken to the words of his beloved disciple, who has said,
For this purpose the Son of God was manifested, that he might put an end to sin,
and destroy the works of the devil.--1 John 3:8. Do you know this by your own experience?
Deceive not yourselves; where, pray, does sin dwell?
and where are the works of the devil?
are they not in the hearts of men and women?
is not that the seat of wickedness, the tabernacle of sin, the temple of the devil?
have not men there worshipped his spirit?
have not men there bowed down before him?
and are not all such born of his evil seed?
Must not Christ, who is the Seed of God, there bruise his head,
there destroy his work and take his kingdom from him?
The soul, which by Satan is defiled and kept in captivity, must not Christ redeem,
purify and save, that it may be changed and seasoned with the Divine nature,
and so come to bear the holy image of the same;
to the end that Christ may come to dwell in a pure heart,
and that God may be worshipped in his own evangelical temple,
in his own Spirit in man and woman?
What of these things are you truly come to know, and what have you felt hereof?
Christ is therefore come into the world, even for that very end is he called Jesus,
namely, that he should save his people from their sins; Matt. 1:21.
and to that end has John directed all to him by these words,
"`Behold the Lamb of God, which takes away the sin of the world.`"

Look now to yourselves, O inhabitants of Christendom,
whether he has taken away your sins, and what those sins are.
Examine and try yourselves by his holy light; from what evil things you are now redeemed,
unto which you were before subject; for Christ saves no man from the wrath of God,
whom he has not first redeemed from sin: for the wages of sin is death,
and whatsoever men sow, that they shall reap, in the great and last day of judgment.

To whom then do you live, my friends, and in what life?
Do you live in the life of God and Christ, wherein the saints of old did live,
whose lives were hid with Christ in God; and who did live, because Christ lived in them?
Is the old wine, and are also the old bottles put away?
Is the old man with all his deeds put off?
The old evil and corrupt ground, which brings forth all evil and corrupt fruits;
is that burnt up by the fire of God?
for his word is like a fire.
The old heavens, the old service of God, in the fallen nature,
are they rolled up as a scroll and vesture,
and melted through the strong heat of the burning and judging Spirit of God?
Are you become as new bottles,
which receive the new wine of the kingdom of God that endures forever?
Have you my friends, put on the new man,
which after God is created in righteousness and true holiness?
Can you feel that there is brought forth in you the new heaven and the new earth,
wherein righteousness dwells?
Consider, you who truly and sincerely seek to know the Lord and his works in you,
and spend not your money for that which is not bread,
nor your labour for that which satisfies not,
nor will profit anything in the day of account; that your souls be not deceived,
but that you may be saved in day of the Lord.

Come, you that are weary and heavy laden,
and you that hunger and thirst after righteousness,
and desire to walk in the purity and righteousness of the saints;
be it known unto you that Jesus Christ, who can discharge, ease, help and save you all,
is near you, and stands at the door of your hearts and waits to be gracious to you;
he knocks that you may open unto him.
It is he who has visited you with his saving light,
whereby he has manifested your state and condition to you,
and begotten a holy feeling in you, whereby you are become weary of your evil doings,
and raises up a holy thirst in you after better things.
If you desire, and expect ever to be filled and satisfied from him,
then must you receive him as he is revealed,
and as his holy will is made known in your hearts,
and keep yourselves under his holy judgments and reproofs;
for the reproofs of instruction are the way of eternal life. Prov. 6:23.
Love, therefore, that which reproves you for evil,
and turn from those evils for which you are reproved;
for Zion shall be redeemed through judgment, and her converts with righteousness.
Isa. 1:27, iv.
4, Love, I say, the judgments of Christ and submit thereunto, and wait for him,
to feel him yet more and more, that you thus may say, with one of old,
"`In the way of your judgments, O Lord, have we waited for you;
with our souls have we desired you in the night season,
and with our spirits within us will we seek you early:
for when your judgments are in the earth,
the inhabitants of the world will learn righteousness.`"
"`For judgment,`" said Christ, "`am I come into this world,`" that is, as a holy light,
to make manifest, and as a righteous judge to condemn all unrighteousness of men:
and all those that love his reproofs,
and willingly permit his chastisings and fatherly rebukes,
they shall see judgment brought forth unto victory, and that the prince of this world,
and the corrupt root and nature in you, as well as the evil fruits,
and ungodly works thereof, shall be judged.
And when this is done and fulfilled,
then you shall know what it is to sing his high praises in truth and righteousness:
then you shall come to sing the song of the Lamb; and know that you, by that Lamb,
are redeemed and saved.

But, it may be, some will ask, Who is able to perform so great and blessed a work?
Fear not, you that seek the kingdom of God and his righteousness, with all your hearts:
for God has laid help upon One that is mighty, namely, upon Jesus Christ,
and he shall make your sins known unto you, and redeem you from all unrighteousness,
if you will walk in his light, as his beloved disciple speaks, saying,
"`If we walk in the light, as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ his Son cleanses us from all sin.`"
And, therefore, friends, if you will be saved by the blood of Christ,
then must you leave and forsake all which the light of Christ does condemn in you; yes,
you must watch against your own thoughts, words and deeds,
that you at unawares may not be overcome by the enemy of your souls;
for he comes as a thief in the night to destroy you.
Do not live or act so as to grieve the holy Spirit of God;
but turn your minds from all evil, in thoughts, words and deeds.
If you love the light of Christ, then bring your deeds every day to the light,
and see whether they are wrought in God or no;
for all things that are reproved or justified are made manifest by the light,
for whatsoever does make manifest is light:
and that light burns as an oven against all unrighteousness; yes,
it is like a refiner`'s fire.
For it is the fiery part of the baptism of Christ,
and therefore it is called in 2 Thess. 2:8. and Isa. 10:17,
the brightness of his coming, the consuming spirit of his mouth,
whereby that wicked one shall be revealed and burnt up, and rooted out:
the thorns and briars shall be burned up and devoured,
and the filthiness both of flesh and spirit purged away.
If now your sins are become a burden to you, if you thereby are wearied,
and if you heartily desire that they may be weakened in you, and at last conquered also;
then let the holy watch of Jesus be sincerely and earnestly kept in your hearts;
which watch is in the light; for in darkness there is no safe or true watching.

Watch therefore in the light of Christ wherewith you are enlightened;
against every unfruitful thought, word and work of darkness.
Stand upon your guard in the blessed light, and be you armed therewith,
like the saints of old, that you may discern the enemy, and resist him,
when and howsoever he does appear and approach unto you; that so he may not overcome you,
but that you may obtain victory over him; for when he sees his allurements ineffectual,
his snares discovered and broken,
(which is done in the light of Christ,) then is he weakened in his attempts,
and your souls grow stronger to resist him,
until at last he is wholly defeated and conquered.
For this was the way of the ancients, who were more than conquerors,
and walking in the light and spirit of Jesus, were redeemed from condemnation,
which will come upon all those that live after the flesh.
This light and this grace brings salvation;
for it teaches us to deny ungodliness and worldly lusts, which bring condemnation,
and to live soberly, righteously and godly in this present world:
and this is the only living way to the everlasting rest and peace of God.
This was the teacher of the saints,
this was Paul`'s refuge and comfort in his greatest temptations:
"`My grace,`" said the Lord, "`is sufficient for you.`"
And as it has been in time past, so is it in this our day,
to all them that come to receive, embrace and love it,
and who are willing to be guided by it, and follow it: and to them says the Lord,
Depart from all evil ways, from all vain uses and customs,
and from the vanities of this world: receive my counsel, which is the living oracle,
the fountain of all wisdom, and do not hew out to yourselves cisterns,
broken cisterns that can hold no water.

[.numbered]
_Thirdly,_ Are your preachers and teachers sent by God, or by men?
How are they come to be your teachers?
consider of this seriously.
Are they of those who have accompanied with Jesus?
are they instructed and sanctified by him?
are they born again?
have they received their commissions, and are they sent forth by him?
are they true and faithful witnesses?
have they heard, seen, tasted and handled that which they speak and deliver unto you?
Is it the living word which they preach unto you?
or do they, by their own spirit and understanding, in their own time and will,
explain and interpret those matters,
which the saints of old and the primitive Christians
spoke forth as they were moved by the Holy Spirit?
If it be so, then have they not received such work, or such victory,
through the holy Spirit in themselves, as the saints had experience of.

[.numbered]
_Fourthly,_ Do your preachers turn your minds to the light of Christ, that is,
the life in him, which shines in your hearts;
which discovers sin to the creature and shows every
man what the Lord does require of him?
Do they direct you to that light which did lead the saints of old,
and by their believing in the light, made them children of light,
wherein the nations of them that are saved shall walk?
Do they turn you, I say, to this light, to this grace and spirit in yourselves,
which comes by Jesus Christ?
Does your knowledge, feeling, experience and worship,
consist in the revelations and works which this blessed spirit of God begets in you?
so that your faith and hope consist not in words only, though they may all be true words,
nor in the education of an outward religious persuasion by vain teachers;
but that your faith and hope are grounded and builded upon the power of the living God,
who gives victory over the world, unto all those,
who in their hearts believe in the light of Jesus;
and this blessed hope purifies the heart, and fortifies the soul.

[.numbered]
_Fifthly,_ When you come to your meetings, both preachers and people, what do you do?
Do you then gather together in body only, and kindle a fire,
compassing yourselves about with the sparks of your own kindling,
and so please yourselves, and walk in the light of your own fire,
and in the sparks which you have kindled; as those did in the time of old,
whose portion it was to lie down in sorrow?
Isa. 1:11: Or rather do you sit down in true silence,
resting from your own will and workings, and waiting upon the Lord,
with your minds fixed in that light wherewith Christ has enlightened you,
until the Lord breathes life in you, refreshes you,
and prepares you and your spirits and souls, to make you fit for his service,
that you may offer unto him a pure and spiritual sacrifice?
For that which is born of the Mesh, is flesh; and he that sows to his flesh,
shall of the flesh reap corruption;
for flesh and blood cannot inherit the kingdom of God; but he that sows to the Spirit,
shall of the Spirit, reap life eternal, through Christ who has quickened him.

====

What have you felt then, my friends, of this work in your hearts?
has Christ there appeared?
what has he done for you?
have you bowed down before him, and received him in your hearts?
Is he formed in you?
Do you live no more, but does Christ live in you?
for if you know not Christ to be in you, then are you yet reprobates,
though you confess him in words; as the apostle said of old. 2 Cor. 13:5.

All you, therefore, that hunger and thirst after the righteousness of God`'s kingdom,
which is an everlasting, blessed kingdom, turn in my friends, and come to Christ,
who stands at the door of your hearts and knocks. Rev. 3:20.
He is the light of the world;
and it concerns all true servants of the Lord to direct all men to this light,
else they have not a right discerning, nor true sight or taste of the things of God;
namely, to turn men from darkness to light, from the kingdom of Satan,
to the power and kingdom of God; from the dark inventions and human traditions of men,
to Christ, the great Light of God, the high Priest and holy Prophet,
whom all men must hear,
and out of whose mouth the law of the Spirit of life must be received.
By this he judges men in righteousness,
and in him are hid all the treasures of wisdom and knowledge.
He is the high Priest of all true Christians, and their chief treasure.

Happy, therefore, are all those that receive him in their hearts,
those that know him to be their Light, their Guide, their King their Lawgiver,
their Bishop, and their heavenly Shepherd; who follow him through all things,
through all persecutions and sufferings, and steadfastly love his cross,
the power of God, and with all gladness embrace the reproach thereof:
who have experienced, that without Christ they can do nothing; John 15:5;
and therefore wait for his Divine power, strength and wisdom, to govern and guide them.
For such can receive no testimony from any preachers,
except that testimony which is given from the holy unction, in and through them;
because men, without Christ, can do nothing, as he has said; for men cannot preach,
men cannot pray, men cannot sing, as it ought to be done; yes, men, without him,
can do nothing to the praise and glory of God.
For it is only the Son of God that glorifies the Father through his children.

And therefore let him kindle the fire with the pure coals from his holy altar;
and do you not offer to him in your self-will; no, Jesus did not do his own will,
but the will of his Father.
So let us not do our own, but his will.
He has done nothing but what his Father had made known unto him;
and we must all witness what Christ has declared unto us, and what he has wrought in us,
or else we shall be false witnesses.
"`Woman,`" said Christ to his mother, "`my hour is not yet come.`"
So that he waited his Father`'s time, in whose hands the times and seasons are.
We must wait, but God orders, and happy are those who do his will.
"`My sheep,`" said Christ, "`hear my voice and follow me;
but they will not hear the voice of strangers.`"
Now those that speak, if their voices and conversations are not with the life, the power,
and with the spirit of Christ, they are strange voices,
(I pray you observe well,) and Christ`'s sheep will not sit under such voices,
nor under such shepherds; who do but steal the words of the prophets and apostles,
but do not experience them, or succeed them in their spirits and conduct.
Christ`'s sheep discern those that so teach, from his,
for he has given them that spiritual gift to see them,
which is not to be had or found in the crafty wisdom of the world, with all its learning,
arts and sciences, but in the innocent nature of the true sheep; namely,
souls that are become harmless, and are arrived at the state of a little child,
for to such God does reveal his secrets; because, by the work of regeneration,
they are become his own begotten;
and to such belongs the kingdom of God and the knowledge of the mysteries thereof.

Wherefore, pray take notice how it is with you.
Is sin revealed?
Yes. Through what?
By the light of Christ.
But is sin likewise judged?
Have you submitted yourselves to his light?
And are you therewith united?
Is your old self-righteousness thereby judged?
and are thereby all your false judgments judged?
Is the prince of this world judged in you?
Does Christ go before you?
And does he give you eternal life?
Examine and search yourselves, for thus he deals with his sheep: "`I go before them,
they follow me, and behold, I give them life eternal.`"
Does Christ go before you, and lead you in all your worship,
which you do as your bounden duty to God?
Do you wait for his leadings?
Is it the religion of Christ wherein you walk?
Read his holy sermon on the mount.
Or else, do you go before him, and do you climb up another way, before he stirs in you,
before he moves you, before he gives you power and ability to approach his throne?
Ah! true silence before the Lord,
is better abundantly than forward prayers and self-willed offerings,
or any traditional and formal performances: for consider,
that it is life eternal to know God.

Now, no man can know him, who has not heard his voice.
And no man can hear his voice who is not silent in himself,
and waits not patiently for him, that he may hear what God will speak to his soul,
through Christ Jesus, the great, holy and heavenly High Priest of God to mankind,
who is the heavenly Prophet also, unto all them that believe in his name.
But, my friends, do you know the fellowship of his holy life, of his blessed cross,
death and resurrection?
Do you confess him inwardly in yourselves, as well as outwardly before men?
If so, then has he given you life eternal.
Again, if you feel not in you, life and immortality brought to light,
then are you yet in your sins,
and know not the Lamb of God who takes away the sin of the world.
For "`as many as received him, to them gave he power to become the children of God.`"
And they know by the witness of God in themselves, that they are of God,
as said the beloved disciple John, and that the whole world lies in wickedness. 1 John 5:19.

Beloved friends, beware therefore of idolatry and worshipping of images,
I mean the worship of inward images, which is an inward idolatry;
for if you show a great aversion against outward idolatry,
yet if you worship God after the imagination you have of God,
and which you conceive in your own minds, without the inspiration of the Almighty,
you worship images of your own framing, and so come to commit idolatry.
And therefore take heed that your worship does not consist
in your own imaginations and self-conceits of God;
and do not bow down to such,
(which is indeed to yourselves,) and then think or
presume that you are bowing down to God and Christ;
when on the contrary, it is nothing else but a mere picture of your own making.
And this is the great abomination and loss of poor Christendom, namely,
That the spirit which deceives man, sits in the place of God, and is worshipped as God,
(see Daniel 12:11,
and 2 Thess. 2:4) by those that know not the true and living God,
who is as a consuming fire, and as everlasting burnings in the soul against sin,
the righteousness and judgment of the world.

Now he that reveals the Father, is the Son, the true Light; for he has said,
"`No man knows the Father but the Son, and he to whom the Son will reveal him.`"
Has Christ revealed the Father unto you?
Are you come to Jesus?
If so, then you have known the godly sorrow, the true mourning,
and that repentance which men need never to repent of.
But if you have not known this day of judgment and contrition,
then are you not come to Christ.
Wherefore, come you to Jesus, to his appearance in you, by his Divine Light and Spirit,
which every way discovers and judges the world`'s nature, spirit and image in you.
To him is all judgment committed, and he will reveal the Father; yes,
he that has seen the Son, has likewise seen the Father; for he is in the Father,
and the Father is in him. John 14:10-11.
If now the manifestation of Jesus in you, as well of the Father,
as of the Son, is the foundation of your knowledge, so that God and Christ,
(whom to know is life eternal,) are become the holy object of your worship;
then are you real worshippers in his Spirit and Truth; John 4:24;
then are you come out from the workmanship,
from the will and imaginations of your own spirits, and from all human worship,
and are come to the worship of the spirit of the living God, and to live in him,
be led and moved by him in all godly performances;
for the spirit of man only knows the things of man,
but the spirit of God knows and reveals the things of God. 1 Cor. 2:11.
And this worship of his kingdom and church,
has Christ raised up again in these our days,
which was set up by Christ sixteen hundred years ago.
And in this worship the true followers worshipped the Father before the great apostacy
from the spirit and power of the Lord broke in upon the primitive ages of the church.
And after such a glorious manner shall it be restored; yes,
so it is already with many thousands, whom God,
through the appearance of Christ in the heart, has gathered,
both in our and other countries, whereby he has judged them as men in the flesh,
in their fleshly lusts and worships, that they might live unto God and Christ,
who quickened them by the death of the cross, and justified them as men in the spirit,
risen from the dead.

Glory be therefore to God, who lives and reigns on high,
that that dark and sorrowful night is vanishing,
and that the sun-rising of the eternal day has already appeared,
and is arising more and more over the nations in the world: in which day, Babylon,
the mother of harlots +++[+++false worshippers,]
shall come in remembrance before the God of the whole earth; Rev. 16:19; namely,
that Babylon, which has followed merchandizing with the Scripture,
and with the souls of men, and has persecuted the spiritual Seed,
the children of God and faithful witnesses of Jesus, although clothed in sackcloth,
because they would not receive her mark, and her fine linen too,
nor submit to her fleshly birth, invention, profession, worship and dominion.
Rev. 18:13, and Rev. 13:16.

This Babylon lives but too much yet in every one, of all sorts of people or professors,
by whom the Truth is held in unrighteousness;
when they see not through the light of the spirit of Christ,
and when their knowledge and worship of God is not
received and performed by that same blessed Spirit:
there, I say, is Babylon, that is, confusion: "`Come out of her,
my people!`" says the Lord, "`and I will receive you.`"

He that calls God his Father, and is not born of God; he that calls Christ Lord,
and not by the holy Spirit, but meanwhile is serving another master;
and those that attribute to themselves the words of the regenerate,
their revelations and experiences,
when they are yet unregenerated and have no part therein,
but endeavour in all these things to make themselves a fair covering;
they shall experience in the day of the Lord, that it shall profit them nothing; for,
"`Woe to those,`" says the Lord, "`that cover with a covering, and not of my Spirit;
that take counsel, but not of me.`"
Let, therefore, all those that are yet in Babylon, hasten out of her speedily,
and you that are in the suburbs of that great city, hasten you away; yes,
make haste with all speed!
Prepare yourselves to meet the Lamb, your Bridegroom;
who comes now to you who are mourning, hungering and thirsting after him,
to lead you out of your bewildered states, to his saving light and blessed appearance:
for now he sees you, and now he calls you, and knocks at your doors to come in unto you.
And therefore open unto him and let him in; let him no longer lie as in the manger,
nor at your doors; but rather give him your hearts, and let him reign over you as a king,
for he has bought us with his own precious blood,
and is therefore worthy that we should serve and honour him, and he reign over us;
and that he be our King and Law-giver, who gave his own life for us,
that we should not perish, but have everlasting life in him.
He has laid down his life for you, and can you not lay down your sins for his sake; yes,
for your own sakes?
Consider, that he descended from the glory of his Father to bring you to glory;
and can you not depart from the withering glory of this world,
that you may inherit his glory which is everlasting?
It is that wrong, false self in man which only hinders it;
it is that only which objects against it,
that consults and endeavours to avoid the cross.

This self has in all times been desirous to be in great esteem,
and has therefore in all ages hindered men from doing the will of God on earth,
as it is in heaven; but where self is disannulled,
and men have had no great esteem for the selfish part,
but have humbled themselves to the death of the cross of Christ,
that he might deliver them from the wrath to come,
and give them an inheritance in the kingdom of his Father,
there the will of God will be done on earth, as it is in heaven,
and therein will the heavenly Father be glorified.
On the contrary, those that live in sin, are in communion with the devil,
and drink his cup of unrighteousness; which, however it is sweet in the mouth,
is afterwards bitter in the belly.
And though it be sweet here for a time, it shall afterwards be crabbed and distasteful.
Again, the cup of Christ is here bitter in the mouth, but sweet hereafter in the belly;
here sour, but hereafter pleasant: "`You,`" said he, "`shall weep and lament,
but the world shall rejoice:`" but observe the end hereof,
"`Your sorrow shall be turned into joy,`" but their rejoicing into weeping.

And this is therefore the word of truth; No man shall enjoy the cup of blessing,
or drink out of the cup of salvation,
but he that has first drunk of the cup of tribulation;
he that has first known his fellowship with the sufferings of Christ,
and of his holy mystical cross: for those that suffer with him, shall reign with him,
and--no cross, no crown.

Lean then upon his breast, for so does the bride in spirit. Song. 8:5.
Trust in him and not in man, nor in yourselves;
for he will guide you best, because he is given you of God, to be your heavenly Guide.
And if it should be in a way under the cross,
(which way is proper to him,) yet it is notwithstanding, a way of joy and pleasantness,
and all his holy paths are peace to those that love him.
Therefore, feel his holy drawings,
and wait in his light upon his holy movings in your souls;
stand still and see his salvation wrought in you by his own arm;
that you may know him to be Jesus indeed, namely, a Saviour as well from your sins here,
as from the wrath to come; and that he may preserve you from vain thoughts,
vain words and conduct, yes, from the voluntary worship of this world,
and from the slavish fear of man; to the end that he may work his own work in you,
and make you conformable to his own blessed image;
and that you may be made free by the Lord, through the power of his everlasting Gospel,
which is now again sounded forth by his own angel, to the inhabitants of the earth,
calling with a loud voice, "`Fear God, and give glory to him;
for the hour of his judgment is come.`"
And you must feel this judgment in your hearts, that the prince of this world,
with all his evil seed, with all his wrong plants and appearances, may be judged in you;
and that you may be witnesses upon earth for God and the Lamb, that sits upon the throne,
against all darkness of men and devils: no, against death, hell and the grave:
and that God may bless you with all sorts of blessings in Christ Jesus.

I find myself pressed in spirit, to give you one warning more; namely,
that you would no longer use vain words, though true in themselves,
because they are worth nothing, for they take God`'s name in vain,
who use it without life and power.
And I entreat all those that endeavour to know God,
and come up to the true life of his dear Son, that you make no profession of worship,
without the feeling, preparing and ordering of the true and overcoming power of God,
for such worship is not of God, and such professors are poor, lean,
naked and miserable people; yes, they are only as chaff`" among the corn.
And therefore, beware you of that false prophetess,
of whom the early Christians were warned, who has the words,
but not the life of the Son of God. Rev. 2:20.
Her preaching tends to death,
she makes a talk of the sound and fame of wisdom,
but will not afterwards harbour her when she cries in her streets; she awakens none,
she brings no man to God; she does not build up in the heavenly work,
nor administer the right spiritual bread to the soul.
For Christ only is the bread which gives life eternal,
and those that will eat of this bread must first come to him; John 6:32,33,35,51;
let him into their hearts as Lord and Master, to provide and order his, to his praise,
and as such must he be received, when he appears in their souls,
even as a refiner`'s fire, and as a fuller`'s soap,
to purify and refine from all unrighteousness; yes, to reveal unto men their sins,
and destroy the same with the brightness of his coming, and with the spirit of his mouth,
in which no deceit is found.
He is that Light, in the brightness of his coming, which you must love,
and whose testimony you must keep;
and he is "`the quickening Spirit,`" the breath of whose mouth revives the soul,
and destroys the sin that slays it:
for all those that come to receive him in this office, in this way, and in this work,
shall also know,
that he is "`the Lamb of God which takes away the
sin of the world,`" the spiritual Passover,
the heavenly Bread, the true Vine, which brings forth the new wine of the kingdom,
the blessed Olive-tree; yes, the Tree of life and eternal salvation,
which grows in the midst of the paradise of God,
whose leaves are for the healing of the nations. Rev. 2:7.

This is a salutation to you all from the holy and
fervent love which God has poured into my heart;
who am in a travail to help the nations to be gathered to Christ,
the Light and salvation thereof,
that Zion may be the joy and Jerusalem the praise of the whole earth.
Amen, Amen!

[.asterism]
'''

The narrative of this journey,
is the only portion of auto-biography which William Penn has left,
and furnishes the most complete account which is extant,
of the industry and fervour with which he prosecuted his religious services.
This extensive journey was accomplished in about three months; during which time,
in addition to the numerous religious meetings and conferences which he held,
and the distances traversed, sometimes on foot,
and at others in the tardy conveyances of that day,
his letters and epistles occupy about sixty-five folio pages in his printed works.
Yet, at a subsequent period of his life, he expressed a belief,
that if he had then had his time to live over again, he could with God`'s grace,
not only serve him, but his neighbour and himself, better than he had done,
and have seven years to spare.

If we are to consider the portion of his life, which he has so minutely described,
as a specimen of the rest, it is not easy to perceive,
out of what portion of it these seven years could have been obtained.
The reflection, however, furnishes a striking admonition to others,
to consider carefully while their time is passing,
how much of it is employed in the service of God and their neighbours,
to their own permanent advantage.

Soon after his return from the continent, he wrote a letter to John Pennyman,
who had once professed with Friends, but was now become an opposer of them.
This letter, containing advice which might advantageously apply to some in our times,
is as follows:

[.embedded-content-document.letter]
--

[.salutation]
John Pennyman,

I received a letter from you since my arrival in this land.
Let me tell you in the spirit of Truth and meekness,
my soul has been frequently sad and heavy for your sake,
because of those degenerate and sour grapes, which you have brought forth,
the unnatural and unkindly fruits, that of late years have proceeded from you.
Ah!
From where you have fallen, and what are you turned to?
What is become of your tenderness and your zeal for the way of Truth,
as professed among us?
Verily you are increasing your burden,
and strengthening the Lord`'s judgments against you,
and treasuring up wrath against the day of wrath.

Had you been told ten years since, of the things that you have done,
you would not have believed it; you would have cried out, God forbid, far be it from me.
But one weakness brings on another, and one unfaithfulness increases another.
O that you would be advised!
That you would see from where you have fallen, and repent and turn to your first love,
and do your first works.
I have nothing but love and good-will in my heart, both to you and your wife;
and it is with the grief of a friend of God, and of you both,
that I behold the evil and pernicious use that some envious,
prejudiced and unreasonable people make of you and your carriage to us;
yet scorn and deride you in their hearts, after they have served their turns of you.
O return, if yet mercy may be found with the Lord, and be not found fighting against him.
O that my love could take hold of you,
and that my life could raise any tenderness in you,
that yet you might be gathered and not utterly perish.

This I tell you in the name and fear of the Lord,
the weighty power and life and glory of God is among us as a people,
and though there may be some personal weaknesses or miscarriages,
through the unfaithfulness of some particulars,
that serve as food for prejudiced spirits to feed upon, and though some go out from us,
and turn against us, speaking lies in hypocrisy, that is, under the pretence of truth,
which may cause some to stumble, and several to be astonished,
yet all this shall work together for good to them that fear the Lord.
It shall tend to greater watchfulness, diligence and faithfulness to the Lord;
and the just shall live more and more by faith,
through which they shall overcome all their enemies,
and stand in their lot at the end of days, and live and reign with the Lord forever.
I should willingly spend an hour with you upon this subject, if I knew when and where,
without inconvenience to either of us.
In the mean while I wish you well, and forever;

[.signed-section-closing]
Your true friend,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
London, 18th of the Ninth month, 1677.

--
