== Chapter XIX.

1678-79-80. Some very severe laws had been enacted
against the Roman Catholics by the British parliament,
in 1582; one of which imposed a fine of twenty pounds a month,
for absence from the parish churches on the days appointed for Divine worship,
and another passed shortly after the discovery of the gunpowder treason in 1605,
made it optional with the king whether he should exact twenty pounds a month,
or all the personal and two-thirds of the real estate of the offender.
The persecutors of Friends failing in their efforts to repress
the rising Society by the cruel measures they had heretofore taken,
had recourse to these laws,
which answered the double purpose of grievously oppressing Friends,
and putting money into the pockets of their oppressors.

In the beginning of this year,
the parliament having the laws against popery under consideration,
a proposal was made to insert a clause in the bill in favour of those
who should take an oath and subscribe a declaration of a prescribed form.
As the conditions upon which this distinguishing clause was to be rendered available,
could not be complied with by Friends,
it was concluded to make a representation of their case to the two houses of parliament.
One was accordingly prepared, drawn up probably by William Penn,
in which the hardships they had endured by the operation of laws,
which were not intended to apply to them or to persons of their characters,
were briefly yet forcibly stated.
Their inability to avail themselves of the proffered distinction,
was shown to arise from their conscientious objection to oaths,
and not from an unwillingness to subscribe the required declaration,
if reduced to an unexceptionable form.
They therefore requested that their word might be admitted instead of the oath,
with the condition annexed, that in case of violating it,
they should suffer the penalties of perjury.

On the 22nd of the first month,
William Penn being admitted before a committee of parliament,
addressed them in the following terms.

[.embedded-content-document.address]
--

If we ought to believe that it is our duty, according to the doctrine of the apostle,
to be always ready to give an account of the hope that is in us,
and that to every sober and private inquirer, certainly,
much more ought we to hold ourselves obliged to declare with all readiness,
when called to it by so great an authority, what is not our hope,
especially when our very safety is eminently concerned in so doing,
and that we cannot decline this discrimination of ourselves from Papists,
without being conscious to ourselves of the guilt of our own sufferings;
for that must every man needs be that suffers mutely,
under another character than that which truly and properly belongs to him and his belief.
That which gives me a more than ordinary right to speak at this time and in this place,
is the great abuse that I have received above any other of my profession;
for of a long time I have not only been supposed a Papist, but a Seminary, a Jesuit,
an Emissary of Rome, and in pay from the Pope,
a man dedicating my endeavours to the interest and advancement of that party.
Nor has this been the report of the rabble,
but the jealousy and insinuation of persons otherwise sober and discreet.
No, some zealous for the Protestant religion have been so far gone in this mistake,
as not only to think ill of us and to decline our conversation,
but to take courage to themselves to prosecute us for a sort of concealed Papists;
and the truth is, what with one thing, and what with another,
we have been as the wool-sacks and common whipping-stock of the kingdom.
All laws have been let loose upon us, as if the design were not to reform,
but to destroy us, and that not for what we are, but for what we are not.
It is hard that we must thus bear the stripes of another interest,
and be their proxy in punishment,
but it is worse that some men can please themselves in such a sort of administration.

I would not be mistaken.
I am far from thinking it fit, that Papists should be whipped for their consciences,
because I exclaim against the injustice of whipping Quakers for Papists.
No, for though the hand pretended to be lifted up against them, has,
I know not by what discretion, lit heavily upon us, and we complain,
yet we do not mean that any should take a fresh aim at them,
or that they must come in our room.
We must give the liberty we ask, and cannot be false to our principles,
though it were to relieve ourselves, for we have good-will to all men,
and would have none suffer for a truly sober and conscientious dissent on any hand.
And I humbly take leave to add, that those methods against persons so qualified,
do not seem to me to be convincing, or indeed adequate to the reason of mankind,
but this I submit to your consideration.

To conclude, I hope we shall be held excused of the men of that profession,
in giving this distinguishing declaration,
since it is not with the design to expose them,
but first to pay that regard we owe to the inquiry of this committee,
and in the next place,
to relieve ourselves from the daily spoil and ruin which now attends
and threatens many hundreds of families by the execution of laws,
that we humbly conceive were never made against us.

--

He subsequently made to this committee a second speech,
but whether on the same or a different day, does not appear.
The second speech was as follows:

[.embedded-content-document]
--

The candid hearing our sufferings have received from this committee,
and the fair and easy entertainment you have given us, oblige me to add,
whatever can increase your satisfaction about us.
I hope you do not believe I would tell you a lie,
I am sure I should choose an ill time and place to tell it in,
but I thank God it is too late in the day for that.
There are some here who have known me formerly, I believe they will say,
I never was that man; and it would be hard,
if after a voluntary neglect of the advantages of this world,
I should sit down in my retirement, short of common truth.

Excuse the length of my introduction; it is for this I make it.
I was bred a Protestant, and that strictly too.
I lost nothing by time or study; for years, reading,
travel and observation made the religion of my education the religion of my judgment.
My alteration has brought none to that belief,
and though the posture I am in may seem odd, or strange to you, yet I am conscientious;
and till you know me better,
I hope your charity will rather call it my unhappiness than my crime.
I do tell you again, and here solemnly declare in the presence of Almighty God,
and before you all, that the profession I now make, and the society I now adhere to,
have been so far from altering that Protestant judgment I had,
that I am not conscious to myself of having receded from an iota of any
one principle maintained by those first Protestants and Reformers of Germany,
and our own martyrs at home, against the Pope and See of Rome.

On the contrary, I do with great truth assure you,
that we are of the same negative faith, with the ancient Protestant church,
and upon occasion shall be ready, by God`'s assistance, to make it appear,
that we are of the same belief as to the most fundamental
positive articles of her creed too.
And therefore it is, we think it hard,
that though we deny in common with her those doctrines
of Rome so zealously protested against,
(from which came the name Protestants,) yet that we should be so unhappy as to suffer,
and that with extreme severity,
by those very laws on purpose made against the maintainers of those doctrines,
we do so deny.
We choose no suffering, for God knows what we have already suffered,
and how many sufficient and trading families are reduced to great poverty by it.
We think ourselves a useful people.
We are sure we are a peaceable people; yet if we must still suffer,
let us not suffer as Popish recusants, but as Protestant dissenters.

But I would obviate another objection,
and that none of the least that has been made against us, namely,
That we are enemies to government in general,
and particularly disaffected to this we live under.
I think it not amiss, but very seasonable, yes, my duty now to declare to you,
and that I do with good conscience in the sight of Almighty God, first,
that we believe government to be God`'s ordinance, and next,
that this present government is established by the providence of God and law of the land,
and that it is our Christian duty readily to obey it in all its just laws,
and wherein we cannot comply through tenderness of conscience, in all such cases,
not to revile or conspire against the government,
but with Christian humility and patience tire out all mistakes about us,
and wait their better information, who, we believe,
do as undeservedly as severely treat us,
and I know not what greater security can be given by any people,
or how any government can be easier from the subjects of it.

I shall conclude with this, that we are so far from esteeming it hard or ill,
that the house has put us upon this discrimination, that on the contrary we value it,
as we ought to do, for a high favour,
and cannot choose but see and humbly acknowledge God`'s providence therein,
that you should give us this fair occasion,
to discharge ourselves of a burden we have not with
more patience than injustice suffered but too many,
years under.
And I hope our conduct shall always manifest the grateful resentment
of our minds for the justice and civility of this opportunity,
and so I pray God direct you.

--

This application was so far successful, that the committee inserted,
in the bill then depending before them, a clause, granting relief in the case,
which passed the house of commons, but before it had passed the house of lords,
the parliament was suddenly prorogued, and the bill lost.

In the course of this year, a work was given to the world,
purporting to explain the opinions of the Quakers,
by an author who chose to conceal his name.
This brought William Penn again before the public, in a tract, entitled,
_A brief Answer to a False and Foolish Libel._
Of this answer it is unnecessary to present any analysis,
as it consists chiefly of returns to misrepresentations
and perversions of the opinions of Friends.
The conclusion manifesting the readiness of the author to answer
all reasonable inquiries respecting his faith and principles,
is subjoined.

[quote]
____

Lastly,
I hereby offer a fair and free conference with the author or authors of the libel,
or any others who can soberly pretend to a conscientious
dissatisfaction about our faith or practice,
at such time as shall be mutually agreed upon to be convenient.
And this I offer, not out of vanity or ostentation,
but in duty to God my great Lord and Master, and in good-will to all such persons:
and did not these considerations prevail, to carry me to this condescension,
my manifold affairs,
and the many and large books I have already written
on occasion of these and the like imputations,
would have dissuaded me from any fresh undertaking of this nature,
and sufficiently guarded me against all reflections upon my silence.
____

The people of England were about this time thrown into great consternation,
by the pretended disclosures of Titus Oates and others, in regard to a popish plot.
However destitute of truth those disclosures and the rumours to which they gave birth,
must now appear,
they were probably considered at that time by the generality of the people,
as having at least some foundation in truth.

To prevent his friends in religious profession from being drawn into the popular excitement,
and from their accustomed reliance on Divine protection,
William Penn wrote an epistle directed to "`the children of light in this generation.`"

In this he expressed the great sorrow which he had long felt on account
of the vice and impiety which so extensively prevailed in that land;
and his deep apprehension that the judgments of God
were likely to be poured out upon them.
He then declared his belief, that the Divine mercy would still be extended to them,
for the sake of those who were truly conscientious,
and particularly for their sake to whom this epistle was addressed.
He therefore admonished them to repair to the place of safety, even the Lord,
who is the refuge of his people.
He stated his conviction,
that the Most High would drive the people from their false gods,
by these vexations and perplexities,
and bring them nearer to himself--that he would debase the mountain of an empty profession,
but that the mountain of his holiness would be exalted.
And that they were the people through whom the light
of righteousness must so shine in the view of others,
during those times of commotion and distress,
that their heavenly Father might be glorified.
He therefore earnestly exhorted them to flee from the spirit and cares of the world,
to their watch-tower, which is the name of the Lord.
A living, spiritual name, a strong tower, a peaceable habitation,
where they should rest in safety, while darkness and confusion prevailed in the world.
He particularly cautioned them against mingling with the crowd,
lest they should imbibe the spirit of the world,
instead of diffusing their spirit into the people;
and thus fall into the same temptations,
and be induced to fly to the mountains for protection,
and to confide in the arm of flesh for deliverance.
"`They,`" said he, "`must come to us, we must not go to them.
Yet we cannot be insensible of their infirmities,
as well as we shall not be free from some of their sufferings.
We must make their case as our own, and travail alike in spirit for them,
as for ourselves.
Let us stand in the counsel of our God,
and he will make us preachers to them of the work of his Divine power,
and the virtue of that faith, which comes from heaven;
that they may come to know the holy law and word of the Lord in their hearts,
and have their minds turned to him, and stayed upon him, that iniquity may no more abound,
nor ungodliness find a place.
But that in truth, righteousness and peace,
they may be established and the land keep its sabbath to the Lord forever.
Then shall God lift up the light of his countenance upon us, and water us from heaven,
and bless us with all temporal and spiritual blessings;
and we shall yet be called the land saved by the Lord.`"
"`And the Lord God of our visitation and redemption, stir you up to these things,
and keep us all in his holy fear, wisdom, love and patience,
through all these travails and exercises to the end of our days;
that having finished our testimonies, our heads may go down to the grave in peace,
and our souls be received into the rest which is reserved for the righteous,
with God and with his blessed Lamb forever.`"

In the year 1679, as the nation was still in commotion,
and great apprehensions were entertained of designs being
on foot for the subversion of the Protestant religion,
and the introduction of popery, he wrote and published an address to Protestants,
in which he exposed the vices which prevailed in church and state,
and laboured to excite the people to repentance and amendment of life,
as the most effectual means of allaying their fears, and preventing the impending evils.

In this address he first calls the attention of his
readers to the existence and attributes of God;
to the justice and certainty of his judgments,
and to the impossibility of concealing anything from his all penetrating eye.
From these considerations he infers the necessity of a strict
examination into their own lives and conduct;
that they might see whether their works were wrought in God or not.

He then proceeds to an exposition of the particular vices prevalent among them.
These are, the sin of drunkenness; the sin of unchastity;
the sin of luxury or excess in living; the sin of gaming; the sin of profanity.
On these several points he treats at considerable length,
showing how derogatory these vices are to the character of Christians,
and how destructive to the peace and good order of society.
His views on these subjects are illustrated and enforced by numerous
passages from the historical and doctrinal parts of the holy Scriptures;
clearly proving that these evils have, in different ages,
brought down the Divine judgments upon those who indulged in them.

He then addresses his admonitions to persons in authority,
urging them to exercise the power entrusted to them, for the suppression of these evils.
For this request three reasons are assigned.

First, The preservation of the government;
which by the indulgence of these vices is greatly weakened and endangered.
It is observed that history does not furnish an instance
in which the hand of God was against a righteous nation;
or one in which it was not, first or last, against an unrighteous one.
None where a just government perished, or an unjust one was long prosperous.
This is illustrated in the first instance by the destruction of the antediluvian world.
The people, whose land was given to the children of Israel, were also expelled,
because of their iniquities.
Saul likewise perished for his transgression.
The Assyrian, Babylonian and Persian empires sunk under the vices of their time.
The republics of Greece, the Roman commonwealth,
and several of the modern kingdoms of Europe were passed in review,
to show that nations as well as individuals, rise or fall,
according as the manners of the people are marked by the virtues of chastity, sobriety,
temperance and frugality, or by the opposite vices.
The duty of those in authority,
to exercise their power in restraining the prevailing evils,
is urged by the consideration,
that the responsibility is increased by the amount of the talents entrusted to our care,
and that the greatness of any will increase their condemnation
if they neglect the performance of their duty.

The second reason assigned is, the benefit, of posterity.
On this head, the importance of training up the youth in the way they should go,
and the irreparable injury to the rising generation which
results from the general corruption of manners and morals,
are largely insisted on, and the practice of allowing boys to read dissolute authors,
in the study of languages, is particularly objected to,
as likely to corrupt their principles and habits.

The third reason assigned, and the most important is, the promotion of God`'s glory.
The obligation resting upon those who then held the
reins of government in the British dominions,
to regard this object,
is urged by the consideration of the Divine goodness
displayed in their restoration and preservation.
Hence they are invited to manifest their gratitude by the suppression of vice,
and the promotion of virtue and religion.

Having thus expostulated with them,
on account of the evils which prevailed in civil society,
he proceeds in the second part of his address,
to treat of those which relate to the ecclesiastical state of those kingdoms.
In this part five capital evils are noted.

[.numbered-group]
====

[.numbered]
_First,_ Making the opinions of men, articles of faith; at least,
giving them the reputation of faith, and making them the bond of Christian society.

[.numbered]
_Second,_ Mistaking the nature of true faith,
and taking that for faith which is not gospel faith.

[.numbered]
_Third,_ Debasing the true value of morality, under the pretence of higher things.
Mistaking much of the end of Christ`'s coming.

[.numbered]
_Fourth,_ Preferring human authority above reason and truth.

[.numbered]
_Fifth,_ Propagating faith by force, and imposing religion by worldly compulsion.

====

Under the first division he censures and exposes the practice
of expounding a belief on religious subjects,
in terms which are neither scriptural nor fairly deducible from the Scriptures of Truth,
and requiring an assent to such exposition as the condition of Christian communion:
showing that inasmuch as the Scriptures were given by Divine inspiration,
and holy men gave them forth as they were moved by the holy Spirit,
the language in which they were given is to be preferred to any exposition
which can be framed by men who are not endued with a like inspiration.

Under the second head it is stated, that a mere assent of the understanding,
to the truth and authority of the history and doctrines of Scripture,
is not that true and living faith, which is the saints`' victory over the world.
But, as defined by the apostle, faith "`is the substance of things hoped for,
the evidence of things not seen.`"
"`True faith in God,`" says William Penn, "`is entirely believing and trusting in God;
confiding in his goodness, resigning up to his will, obeying his commands,
and relying upon his conduct and mercies,
respecting this life and that which is to come.`"
This is the faith which works by that Divine love which God plants in the heart,
and enables men to forsake whatever is displeasing in the Divine sight.
It is by this faith that the just in all ages have lived.

In regard to belief, our author shows at large,
that the great and essential article of Christian belief is,
that Jesus of Nazareth was the promised Messiah, the Son and Christ of God,
the Saviour of the world.
Of this, the testimony of the beloved disciple is adduced as one conclusive argument.
"`These things are written that you might believe that Jesus is the Christ,
the Son of God, and that believing you might have life through his name.`"
This belief, it is observed, fully and sincerely admitted,
necessarily leads to an assent to the doctrines of Christ,
and to the precepts which he taught.
And these precepts include the moral and religious duty of man.
Hence, "`as Christ is the Rock on which true Christians build,
so none can be truly said to build on this Rock, but those that keep his sayings,
that do his commandments, that obey his doctrine.
Wherefore that faith, of Jesus to be the Son and Christ of God,
must be such a faith as does the will of the heavenly Father,
and keeps the sayings of Christ.`"

"`Those, therefore, that would obtain this precious faith that overcomes the world,
must embrace the grace of our Lord Jesus Christ, by which this faith is begotten;
and they who believe not in this grace, nor receive it in the love of it,
nor give themselves up to be taught and led by it,
can never be said truly to believe in him from whom it comes,
any more than the Jews may be said to believe in God,
when they rejected him that came from God, even his beloved Son.
He that denies the measure, can never own or receive the fulness.
John bears record that he was full of grace and truth,
and that of his fulness they had all received, and grace for grace:
For the law was given by Moses, but grace and truth came by Jesus Christ.`"

In concluding this division, he says, "`I do fervently beseech Almighty God,
the giver of all saving faith, mercifully to vouchsafe, more and more,
to beget a serious inquiry in us, what that faith is which we have?
who is the author of it?
and what fruits it has brought forth?
that so we may not profane the name of God by a vain profession of it,
nor abuse ourselves unto eternal perdition.
But that we may endeavour, by God`'s assistance,
to approve ourselves such believers as sincerely fear God, love righteousness,
and hate every evil way, as becomes the redeemed of God by the precious blood of his Son.
Since, therefore, we are not our own, but the Lord`'s,
who has bought us with that great price, let us glorify him in our bodies, in our souls,
and in our spirits, which are his: Then shall we be children of Abraham indeed,
heirs of the promises, partakers of that resurrection and life,
that immortality and glory which God, the righteous Judge,
will one day plentifully distribute to them that
abide in this precious faith unto the end.`"

Under the third head he defines his moral man to be one
that does to all men as he would have all men to do to him;
and from this he argues that Christian morality is
the fruit of a sound practical belief in Christ,
and in the doctrines which he taught.
In regard to the end and design of Christ`'s coming into the world,
it is laid down that he came, to save his people from their sins;
not merely to take away the guilt, by his propitiatory sacrifice on the cross,
but to redeem from the nature of sin by the power of his Spirit,
and to establish an actual righteousness.
For the grace of God that brings salvation has appeared to all men,
teaching us that denying ungodliness and the world`'s lusts, we should live soberly,
righteously and godly in this present world, looking for that blessed hope,
and the glorious appearing of the great God and our Saviour Jesus Christ,
who gave himself for us, that he might redeem us from all iniquity,
and purify unto himself a peculiar people zealous of good works.

Under the fourth head is noticed the great power of the clergy,
and the people`'s reliance upon them for the knowledge of religion,
and the way of life and salvation;
so that in most protestant as well as popish countries,
very few were found possessed of any other religion than the tradition of the priest.
The clergy were thus become a sort of mediators between Christ and the people.
This implicit faith and blind obedience to the opinions of others,
is noted as a species of popery which protestants
are particularly required to examine and avoid.
The imposition of an implicit belief, without examination or conviction,
is shown to be contrary as well to the principles professed by the most pious writers,
even of the Roman Catholic persuasion, and the practice of our Saviour,
who referred the Jews, for the evidence of the truth of his doctrines,
both to the Scriptures and to the works which he performed.

The author declares, that every Christian ought to believe as the church believes,
provided the church is right.
But the church is defined to be a congregation or company of people agreed
together in the sincere profession and obedience of the Gospel of Christ.
The rule then which they jointly have for their belief, is the rule of each individual.
Now the great foundation of the protestant religion,
is the Divine authority of the Scriptures without us,
and the testimony and illumination of the holy Spirit within us.
Upon this ground the first reformers made and supported
their separation from the Church of Rome.
Hence protestant writers agree, that neither traditions, councils,
nor canons of any visible church, much less the edicts of any civil jurisdiction,
but the Scriptures only, interpreted by the holy Spirit in us,
give the final determination in matters of religion,
and that only in the conscience of every Christian to himself.

Under the last head, our author notices with just disapprobation,
the persecutions on account of dissent from the national mode of worship,
which prevailed in the days of Elizabeth and her two immediate successors,
and more particularly those of their own times;
in which many families had been reduced to poverty, not a bed left in the house;
not a cow in the field, nor any grain in the barn.
Widows and orphans stripped without pity, and no regard paid to age or sex.
And all this for no offence, except peaceably meeting to worship God,
in a manner different from that prescribed by the protestant authorities of the day.
These abuses and the rigorous application of laws, intended for popish recusants,
are held up as objects demanding the attention of those
who expect mercy themselves at the hand of God.
The impolicy and absurdity of the attempt to propagate religion by force,
and the opposition of such means to the nature of Christianity are copiously demonstrated.

This address, which occupies about one hundred pages in our author`'s folio works,
closes in the following terms.

[.embedded-content-document.address]
--

God Almighty open our understandings and hearts,
and pour out the spirit of thorough reformation upon us;
for it is in the spirit and not in the words of reformation,
that the life and prosperity of reformation stands; that is,
we may be all conscientiously disposed to seek and
pursue those things which make for love,
peace and godliness, that it may be well with us and ours, both here and forever.

--

In the same year he also prefixed to the works of Samuel Fisher,
which were then printing in folio, a testimony respecting the author.
This Samuel Fisher was a man of liberal education,
who held for a time a clerical station in the established church,
but becoming dissatisfied with their doctrines and practice,
he voluntarily relinquished his living of £200 per annum,
left them and became a preacher among the Baptists.
He was afterwards convinced of the principles of Friends,
travelled considerably in the service of the Gospel,
and in 1665 ended his days in prison,
where he had spent most of the last four years of his life,
rather than violate the command of Christ, "`swear not at all.`"

The parliament, which had continued about eighteen years,
having been dissolved and writs issued for the election of a new one,
great excitement prevailed among the people,
and strenuous efforts were made by the opposing parties to secure the ascendency.
On this occasion William Penn addressed a communication
to the freeholders and electors of the kingdom,
which may be considered as a political, rather than a religious production.
Yet the general object of the address evidently was the
promotion of justice and sound morality in the nation,
and we easily perceive that he had an eye to the
choice of men of more liberal and tolerant principles,
than those who enacted the persecuting laws under which
Friends and other conscientious dissenters were suffering.

Besides communicating this address to the electors,
he used considerable efforts to procure the election of Algernon Sidney,
of whose talents and character he had formed a favourable opinion.
The arbitrary measures of the court,
and the unrelenting rigour with which dissenters both in church and state,
were prosecuted,
appeared to demand the restraining hand of statesmen of firm and liberal minds.
Men of that character were those whom he recommended to the electors of England,
and such a one he appears to have thought he discerned in Algernon Sidney;
his efforts however were not successful,
and his friend did not obtain a seat in the national legislature.
The efforts of William Penn to promote his election,
may be considered as a complete refutation of the charge,
so frequently and recklessly advanced,
of his subserviency to the interests of popery and arbitrary power.
For Sidney was a man of liberal, if`" not republican principles, and fell,
a few years afterwards a sacrifice to the jealousy of the dominant party.
The opposition of our author to popish doctrines in government as well as in religion,
was clearly manifested on numerous occasions.

He wrote in the same year, a second pamphlet,
entitled _One Project for the Good of England,_ which partakes
quite as much of the political as of a religious character.
Yet it is observable that his politics were kept in subserviency to his religion;
and that in his efforts to influence the measures of government,
the recognition of the religious rights of the people was a prominent object.

The persecution of dissenters,
among whom Friends always sustained the heaviest part of the burden, still continuing,
three applications were made in the year 1680 to those in authority.

The first was entitled _The Case of the People Called Quakers Stated,
in Relation to Their Late and Present Sufferings,
Especially upon Old Statutes Made Against Popish Recusants._

The second was called _An Account of the Late and Present Great Sufferings and Oppressions,
of the People alled Quakers, upon Prosecutions Against Them, in the Bishop`'s Courts,
Humbly Presented to the Serious Consideration of the King, Lords and Commons._

The third was styled,
_A Brief Account of Some of the Late and Present Sufferings of the People Called Quakers,
for Meeting Together to Worship God in Spirit and in Truth, upon the Conventicle Act,
with an Account of Such Who Died Prisoners, from the Year 1660, for Several Causes._
It was addressed to the king, lords and commons, in parliament assembled.

In each of these works, William Penn wrote an appropriate preface,
which he signed in conjunction with a number of other members of the society.

Isaac Penington, an eminent minister among Friends,
who was married to the widow of Sir William Springett,
and consequently was father-in-law to William Penn,
having died in the latter part of the year 1679, the latter wrote, in this year,
a pathetic testimony to his character and worth, which was prefixed, with several others,
to the folio edition of his works.

In this year, died the virtuous princess Elizabeth,
with whose religious disposition and kindness to William Penn,
the reader of this narrative is already acquainted.
When a second edition of [.book-title]#No Cross No Crown,# was published, in 1682,
the author inserted her name and character among
the witnesses in favour of a religious life.

The important question to the Society of Friends,
of the establishment and extent of the discipline,
occasioning some diversity and even opposition of sentiments among them,
William Penn wrote, in 1681, a small tract on this subject,
in the way of question and answer,
in which he explained the nature and extent of the
authority which the church might justly exercise,
and the obligation of the members to submit to that authority.
This tract, containing many wise and appropriate observations, is here inserted at large.

[.asterism]
'''

[.blurb]
=== A brief examination of liberty spiritual, both with respect to persons in their private capacity, and in their church society and communion. To the people of the Lord called Quakers.

[.salutation]
Dear friends and brethren,

It has of long time rested with some pressure upon my spirit,
for Zion`'s sake and the peace of Jerusalem,
to write something of the nature of true spiritual liberty; liberty,
one of the most glorious words and things in the world, but little understood,
and frequently abused by many.
I beseech Almighty God to preserve you, his people,
in the right knowledge and use of that liberty, which Jesus Christ,
the Captain of our salvation, has purchased for us and is redeeming us into,
who has led captivity captive,
and is giving gifts to them that truly believe in his name.
Christ`'s liberty is obtained through Christ`'s cross; they that would be his freemen,
must be his bond`'s-men, and wear his blessed yoke.
His liberty is from sin, not to sin; to do his will, and not our own; no,
not to speak an idle word.
It is not I that live, (says the apostle) but Christ that lives in me,
who had set him free from the power of sin, and brought immortality to light in him;
from which he learned thus to triumph, O death, where is your sting!
O grave, where is your victory!
This is the personal freedom that comes by Jesus Christ,
to as many as receive him in the way, and for the end for which God has given him,
namely, to be a Saviour and a Leader, to save us from our corruptions,
and guide us in the narrow way of his holy cross,
and through the straight gate of self-denial, which leads to eternal life.
And as many as have entered at this door, are come to have unity with God,
and one with another; to love him above all, and their neighbours as themselves; yes,
to prefer each other before themselves.
Such will not violate the great law of their Lord and Master, love one another; the new,
and yet the old commandment.
These dwell in love, and so they dwell in God; for God is love.
It was the beloved disciple`'s testimony,
and it comes up to what another man of God has said, namely, The church dwells in God;
if she dwells in God, then in love; consequently her members are in union,
of one mind in church matters, since she has but one head to rule her.

Peruse this brief discourse in this love, and it may be to edification.
My aim is to assert the truth,
detect error and point in true brotherly kindness at those
shoals and sands some by mistake or overboldness,
have and may run upon.
O Friends!
I greatly desire, that the spirit of love, wisdom and a sound understanding, of meekness,
judgment and mercy, may ever rest upon you, that blamelessly you may be kept,
a holy family, at unity with itself, to the Lord God your Redeemer,
that he over all may in you, through you and by you, be exalted, honoured and praised,
who is worthy and blessed forever.

[.discourse-part]
_Question._
What is spiritual liberty?

[.discourse-part]
_Answer._
It is two-fold; there is a true and a false liberty, as a true and false spirit,
the right discerning of which concerns every one`'s eternal well-being.

[.discourse-part]
_Q+++.+++_ What is true spiritual liberty?

[.discourse-part]
_A+++.+++_ Deliverance from sin by the perfect law in the heart, The perfect law of liberty,
James 2., otherwise called, The law of the Spirit of life in Christ Jesus,
that makes free from the law of sin and death; elsewhere styled,
the law of Truth written in the heart, which makes free indeed, as says Christ,
If the Son shall make you free, you shall be free indeed.
So that the liberty of God`'s people stands in the Truth, and their communion in it,
and in the perfect spiritual law of Christ Jesus,
which delivers and preserves them from every evil thing that does or would embondage.
In this blessed liberty, it is not the will nor wisdom of man,
neither the vain affections and lusts that rule or give law to the soul;
for the minds of all such as are made free by the Truth,
are by the Truth conducted in doing and suffering through their earthly pilgrimage.

[.discourse-part]
_Q+++.+++_ What is false liberty?

[.discourse-part]
_A+++.+++_ A departing from this blessed Spirit of Truth,
and a rebelling against this perfect law of liberty in the heart,
and being at liberty to do our own wills; upon which comes reproof and judgment.

[.discourse-part]
_Q+++.+++_ But are there not some things wherein we ought to be left to our own freedom?

[.discourse-part]
_A+++.+++_ We are not our own, for we are bought with a price;
and in all things ought we to glorify God with our bodies, souls and spirits,
which are the Lord`'s.

[.discourse-part]
_Q+++.+++_ But must we have a motion or command from the
Spirit of Truth for all things that we do?

[.discourse-part]
_A+++.+++_ That may be according to the Truth,
which may not be by the immediate motion or command of the Truth;
for that is according to the Truth, that is not against the mind of the Truth,
either particularly or generally expressed.
The Truth commands me to do all to the praise and glory of God;
but not that I should wait for a motion to do every particular thing.
For example: The variety of actions in trading, commerce and husbandry,
the variety of flesh, fish and fowl for food, with more of the same nature,
in all which there is a choice and liberty, but still according to the Truth,
and within the holy bounds and limits of it.

[.discourse-part]
_Q+++.+++_ Then it seems there are some things left to our freedom.

[.discourse-part]
_A+++.+++_ Yes; but it must still be according to the mind of God`'s Truth.
There are things enjoined, such as relate to our duty to God, to our superiors,
to the household of faith, and to all men and creatures; these are indispensable.
There are also things that may be done or left undone, which may be called indifferent;
as what sort of food I will eat today, whether I will eat flesh, fish or herbs,
or what hours I will eat my meals at, with many such outward things of life and converse;
yet even in such cases I ought to act according to the Truth,
in the temperance and wisdom of it.

[.discourse-part]
_Q+++.+++_ But does not freedom extend further than this;
for since God has given me a manifestation of his Spirit to profit withal,
and that I have the gift of God in myself,
should I not be left to act according as I am free and persuaded in my own mind,
in the things that relate to God,
lest looking upon myself as obliged by what is revealed unto another,
though it be not revealed unto me, I should be led out of my own measure,
and act upon another`'s motion, and so offer a blind sacrifice to God?

[.discourse-part]
_A+++.+++_ This is true in a sense, that is,
if you are such a one that can do nothing against the Truth, but for the Truth,
then may you safely be left to your freedom in the things of God,
and the reason is plain; because your freedom stands in the perfect law of liberty,
in the law of the Spirit of life in Christ Jesus, and in the Truth,
which is Christ Jesus, which makes you free indeed, that is,
perfectly free from all that is bad, and perfectly free to all that is holy, just,
lovely, honest, comely and of good report;
but if you plead your freedom against such things, yes, obstruct and slight such good,
wholesome and requisite things, your freedom is naught, dark, perverse, out of the Truth,
and against the perfect law of love and liberty.

[.discourse-part]
_Q+++.+++_ But must I conform to things whether I can receive them or no?
Ought I not to be left to the grace and spirit of God in my own heart?

[.discourse-part]
_A+++.+++_ To the first part of the question, No; to the last, Yes.
But now let us consider what is the reason you can not receive them.
Is the fault in the things themselves?
Are they inconsistent with Truth, or will not the Truth own or assent unto them,
or is the fault in you?
That is to say, is it your weakness or your carelessness; if your weakness,
it is to be borne with, and to be informed; if your carelessness,
you ought to be admonished; for it is a dangerous principle,
and pernicious to true religion, and which is worse,
it is the root of ranterism to assert, That nothing is a duty incumbent upon you,
but what you are persuaded is your duty;
for the seared conscience pleads this liberty against all duty;
the dark conscience is here unconcerned; the dead conscience is here uncondemned,
unless this distinction be allowed of,
that there may be an ignorance or an insensibility from inability or incapacity,
or a dark education; and an ignorance and insensibility, from carelessness, disobedience,
prejudice, etc.
So that though you are not to conform to a thing ignorantly,
yet you are seriously to consider, why you are ignorant,
and what the cause of such ignorance may be; certainly it cannot be in God,
nor in his gift to you; it must then needs be in yourself,
who have not yet received a sense for or against the matter,
about which you are in doubt.
To the second part of the question;
Ought I not to be left to the grace of God in my own heart?
Answer, That is of all things most desirable,
since they are well left who are left there; for there is no fear of lack of unity,
where all are left with the one Spirit of Truth; they must be of one mind,
they cannot be otherwise.
So that to plead this against unity, is to abuse the very plea,
and to commit the greatest contradiction to that very doctrine of Scripture, namely,
That all should be guided by the grace and spirit of God in themselves;
for the end of that doctrine is certainty.
They shall all know me, says the Lord, from the least to the greatest.
And I will give them one heart and one way, that they may fear me forever,
for the good of them, and of their children after them, Jer. 32:39.
And I will give them one heart, and I will put a new spirit within you;
and I will take the stony heart out of their flesh,
and I will give them a heart of flesh, Ezek. 11:19.
And the multitude of them that believed were of one heart,
and of one soul, Acts 4:32. Is not this unity too?
I will restore unto you a pure language; they shall be of one heart and of one mind,
and great shall be their peace.
Therefore I must say to you, friend,
what if you will not be left with the grace and spirit of God in yourself,
nor wait for its mind, nor be watchful to its revelations,
nor humble and quiet till you have received such necessary manifestations,
but plead against the counsel of the spirit of the Lord in other faithful persons,
under the pretence of being left to his Spirit in yourself;
by which means you oppose the Spirit to the Spirit, and plead for disunity,
under the name of liberty; I ask you,
may not I exhort you to the practice of that I am moved to press you to the practice of?
If not, you are the imposer, by restraining me from my Christian liberty;
and not only so, but away goes preaching, and with it the Scriptures,
that are both appointed of God for exhortation, reproof and instruction.

[.discourse-part]
_Q+++.+++_ But are there not various measures, diversities of gifts,
and several offices in the body?

[.discourse-part]
_A+++.+++_ True; but are not the members therefore of one mind,
one will and one judgment in common and universal matters,
especially relating to the family and church of God?
and indeed there cannot be a falser reasoning than to conclude discord from diversity,
contrariety from variety.
Is there contrariety of bloods, lifes, feelings, seeings, hearings, tastings, smellings,
in one and the same body, at one and the same time?
No such matter.
Experience is a demonstration against all such insinuations.
So that though it be granted, that there is diversity of gifts,
yet there is no disagreement in sense; and though variety of offices,
yet no contrariety in judgment concerning those offices.
Well, say the holy Scriptures of Truth, there is but one God;
the Lord our God is but one Lord; there is but one God and Father of all things;
(that are good) and there is but one Lord, one faith and one baptism; and his light,
life and Spirit is at unity with itself in all; what comes from the light,
life or Spirit in one, it is the same in truth and unity to the rest,
as if it did rise in themselves.
This is seen in our assemblies every day,
and will be throughout all generations in the church of God,
among those that live in the lowly Truth,
in which the pure sense and sound judgment stands; God is not the God of confusion,
but order.
Every one in his order is satisfied,
has unity and true fellowship with whatever comes from the life of God in another;
For this precious life reaches throughout the heritage of God,
and is the common life that gives the common feeling and sense to the heritage of God.
Degree or measure in the same life can never contradict or obstruct that
which is from the same life for the common benefit of the family of God.
The Lord is the unmeasurable and incomprehensible glorious Being of life,
yet have we unity with him in all his works,
who are come to his Divine measure of light and Truth in our own hearts,
and live therein;
and shall we not have unity with that which proceeds from it in a fellow creature?

In short, the saints`' way is in the Light, wherein there is neither doubt nor discord;
yes, they are children of the Light, and called light, and the lights of the world;
and can it be supposed that such should disagree and contradict each other
in their exterior order and practice in the church before the world.
O the blessed seamless garment of Jesus! where that is known, these things can never rise.
But yet again, The just man`'s path is not only a light, but a shining light,
brightness itself.
Certainly there can be no stumbling.
It is also said, That light is sown for the righteous;
then the righteous shall never lack light upon any occasion.
And says that beloved evangelist and apostle of our Lord Jesus Christ,
They that walk in the light, have fellowship one with another,
1 John i. From which it is easy to conclude, they that go out of the fellowship,
go out of the Light; but if they that walk in the Light,
have fellowship one with another,
what shall we say of those that plead being left to the
Light to justify their not having fellowship one with another?
and, which is yet worse,
who suppose people may conscientiously and justifiably dissent within themselves,
and that by reason of the variety of the degrees of the
Spirit and grace that are given of God unto them;
as if the lesser degree may dissent from the greater,
because of its not being able to comprehend it.
And to make this principle more authentic, such tell us,
This is the ancient principle of Truth and object,
How will you else be able to maintain the Quakers`' principles?
The fallacy of all which lies, as I said before,
in not rightly distinguishing between diversity and disagreement,
variety and contrariety; for this diversity has concord, and this variety has unity.
And il is a blindness that has too much of late happened to some,
by going from the one life and spirit of our Lord Jesus Christ,
first to fall into disagreements, and then plead for it,
under the notion of diversity of measures.
I would ask all such persons,
who arrogate to themselves such a peculiar knowledge of the ancient principles of Truth,
or the Quakers`' first principles; Firstly,
Whether they believe there be a Christian body?
Secondly, Whether this body has a head?
Thirdly, Whether Christ be not this head?
Fourthly, Whether this head be without eyes, ears, smell and taste,
and this body without sense and feeling?
If not, whether this head sees, hears, smells,
tastes differingly and contrarily to itself?
And whether this body has a contrary feeling at the same time about the same thing?
And if it be true, that the church of Christ,
redeemed by his most precious blood to live to him, see with the same eye,
hear with the same ear, speak with the same mouth, live by the same breath,
and are led by the same spirit, where is this disagreement,
contrariety or dissent about the things of his church?

[.discourse-part]
_Q+++.+++_ But the members of Christ`'s church in the primitive times had different apprehensions;
as the apostles and the people gathered by them.

[.discourse-part]
_A+++.+++_ Pray let me know who they were, and in what cases?

[.discourse-part]
_Q+++.+++_ The persons were Paul and Peter, and those Christians who differed about meats;
and the Scripture is plain in the case.

[.discourse-part]
_A+++.+++_ The difference between Peter and Paul (in the Acts) testifies the weakness of Peter,
and the place justifies Paul`'s reproof of his too
great compliance with the Jews in some of their rites;
which makes against liberty of various practices, in the church of Christ,
and not for indulging them.
That instance about the difference of Christians as to meats, etc,
has nothing in it to the end for which it is alleged;
for this related not to church-order or communion, but private and personal freedoms,
what each might do with respect to themselves; that is,
they might make laws to themselves, in things that only concerned private persons,
and it centred there; here, what I will eat, when I will eat, things to myself,
and for myself, as a man having power over my own appetite.
The liberty in things private, personal and indifferent,
makes nothing for dissenting about church matters in things of communion and society,
and that also are not indifferent, as to eat fish, flesh, or herbs, plainly is:
but necessary; as to be careful and orderly about the external business of the church.
These are no Jewish rites, nor shadowy ceremonies,
no meats nor drinks that are private and personal,
where weakness is apt to mistake (that were an unnecessary
and an unchristian yoke to bear) but things comely,
orderly and of good report, that tend to purity,
peace and diligence in things acceptable to God,
and requisite among his people in their temporal Christian capacity.
And herein the apostle Paul exercised his godly authority;
and we find not only that those who opposed themselves to it,
as thinking he took too much upon him, and demanded a mark of Christ`'s speaking in him,
are in Scripture branded with contention, but the true believers,
that had in themselves a mark of Christ`'s speaking in him, were of one mind,
and avoided such as were given to contention;
for it was not the custom of the churches of Christ.
Thus were Christ`'s people of one heart, in things relating to their communion.
Yet a little further; they that have the mind of Christ, are of one mind;
for Christ is not divided.
They that have Christ for their head, have one counsellor and prophet,
one seer and bishop, they disagree not in their judgments
in things relating to him and the good of his church;
they have one and the same guide; for the one Spirit, into which they have all drank,
and by it are baptized into one body, leads them all.
Now to every member is a measure of the same Spirit given to profit with;
and though every member is not an eye, nor an ear, nor a mouth,
yet every member has unity with the eye, with the ear, with the mouth,
and in their proper and respective acts, and they one with the other.
The eye sees for the mouth, the mouth speaks for the eye, and the ear hears for both;
this variety has no discord, but in this diversity of gifts and offices,
each member is sensible of the other, and moves and acts by one and the same life,
spirit and guidance, which is omnipresent,
proportionable to every member in its distinct office.
It must be granted, that there are helps in the church,
as well as that there is a church at all; and the Holy Spirit has compared those helps,
as is before mentioned, to several members and senses of man`'s body, as an eye, a hand,
a foot, hearing, smelling, etc.
All then cannot be the eye, neither can all be the hand,
for then they would confound their office,
and act disagreeably to the ordination of the great orderer of his church.
And if I will not comply with him that God has made an eye, because I am not that eye,
or a hand, because I am not that member myself,
nor a party to the action or performance of that member, I resist the Lord,
though under pretence of resisting man for the Lord`'s sake.
And truly, this is the rock that some of our own time, as well as persons of former ages,
have split upon; they have not been contented with their own station in the body,
they have not kept to their own gift,
nor been taken up with the duty of their own place in the church.
If he that is a foot would be a hand, and the hand covets to be an eye,
envying others their allotted station, through height of mind,
and walking loose from the holy cross,
there can be no such thing as concord and fellowship in the church of Christ.

Furthermore, since the spirit of the Lord is one in all,
it ought to be obeyed through another, as well as in one`'s self;
and this I affirm to you,
that the same lowly frame of mind that receives and answers
the mind of the spirit of the Lord in a man`'s self,
will receive and have unity with the mind of the same Spirit through another,
and the reason is plain;
because the same self-evidencing power and virtue that arises
from the measure of the Spirit of Truth in one`'s self,
and that convinces a man in his own heart,
does also attend the discovery of the mind of the same Spirit, when delivered by another;
for the words of the second Adam, the quickening Spirit, through another,
are spirit and life, as well as in your own particular;
this is discerned by the spiritual man that judges all things,
although the carnal man pleads for being left to his freedom,
and it may be talks of being left to the Spirit in himself too;
the better to escape the sense and judgment of the spiritual man.
It is my earnest desire, that all who have any knowledge of the Lord,
would have a tender care how they use that plea against their faithful brethren,
that God put into their mouths against the persecuting
priests and hirelings of the world,
namely, I must mind the spirit of God in myself;
for though it be a great truth that all are to be left thereunto, yet it is as true,
that he who is left with the Spirit of Truth in himself,
differs not from his brethren that are in the same Spirit; and as true it is,
that those who err from the Spirit of Truth,
may plead for being left to the Spirit in themselves,
against the motion and command of the Spirit through another,
when it pleases not his or her high mind and perverse will;
for a saying may be true or false,
according to the subject matter it is spoken upon or applied to; we own the assertion,
we deny the application.
There lies the snare.
It is true,
the people of God ought to be left to the guidance of the spirit of God in themselves;
but for this to be so applied,
as to disregard the preaching or writings of Christ`'s enlightened servants,
because by them applied properly to the preaching or writing of false prophets and seducers,
will by no means follow.
I say the doctrine is true, but not exclusively of all external counsel or direction;
therefore false in application, where men are allowed to have had the fear of God,
and the mind of his Spirit,
and are not proved to have acted in their own wills and wisdom,
or without the guidance of the spirit of God, about the things of his church and kingdom.

[.discourse-part]
_Q+++.+++_ But though this be true, which has been alleged for heavenly concord,
yet what if I do not presently see that service in a thing,
which the rest of my brethren agree in; in this case, what is my duty and theirs?

[.discourse-part]
_A+++.+++_ It is your duty to wait upon God in silence and patience,
out of all fleshly consultations; and as you abide in the simplicity of the Truth,
you will receive an understanding with the rest of your brethren,
about the thing doubted.
And it is their duty, while you behave yourself in meekness and humility,
to bear with you, and carry themselves tenderly and in love towards you;
but if on the contrary, you disturb their godly care and practice, and grow contentious,
and exalt your judgment against them, they have power from God to exhort,
admonish and reprove you; and if you persevere therein,
in His name to refuse any further fellowship with you, till you repent of your evil.

[.discourse-part]
_Q+++.+++_ But lest I should mistake, when you speak of true liberty,
that it stands in being made free by the Truth, from all unrighteousness, do you mean,
that no other persons ought to have the liberty of exercising their dissenting consciences,
but that force may be lawful to reduce such as are reputed erroneously conscientious?

[.discourse-part]
_A+++.+++_ By no means.
It would be great wickedness against God, who is Lord of the souls and spirits of men,
and ought to preside in all consciences, who, as the apostle says, Is the only Potentate,
and has immortality.

For though I give the true liberty of soul and conscience
to those only that are set free by the power of Christ,
from the bondage of sin and captivity of death, yet do I not intend,
that any person or persons should be in the least harmed for the external
exercise of their dissenting consciences in worship to God,
though erroneous; for though their consciences be blind, yet they are not to be forced;
such compulsion gives no sight, neither do corporal punishments produce conviction.
This we above all people, in our day, have withstood, in speaking, writing and suffering,
and, blessed be God, continue so to do with faithfulness.
For faith is the gift of God, and forced sacrifices are not pleasing to the Lord.

[.discourse-part]
_Q+++.+++_ But according to your argument, it may be my fault, that I have not the gift of faith;
and upon this presumption, it may be, you will inflict some temporal penalties upon me.

[.discourse-part]
_A+++.+++_ No such matter;
for such kind of faults are not to be punished with temporal or worldly penalties;
for whether the errors be through weakness or willfulness, not relating to moral practice,
all external coercion and corporal punishment is excluded.
For the weapons of our warfare are not carnal, but spiritual.

[.discourse-part]
_Q+++.+++_ But what then is the extent of the power of the church of Christ,
in case of schism or heresy.

[.discourse-part]
_A+++.+++_ The power that Christ gave to his church was this, that offenders,
after the first and second admonition, not repenting, should be rejected.
Not imprisoned, plundered, banished or put to death;
this belongs to the false church and false prophet.
All these things have come to pass for lack of humility,
for lack of the ancient fear and keeping in the quiet habitation of the just.
The Truth in you all shall answer me.
And this I affirm, from the understanding I have received of God,
not only that the enemy is at work to scatter the minds of Friends, by that loose plea,
What have you to do with me?
Leave me to my freedom and to the grace of God in myself, and the like;
but this proposition and expression, as now understood and alleged,
is a deviation from and a perversion of the ancient principle of Truth.
For this is the plain consequence of this plea, if anyone,
especially if they are but lately convinced, shall say,
I see no evil in paying tithes to hireling priests,
in that they are not claimed by Divine right,
but by the civil laws of the land--I see no evil in marrying by the priest,
for he is but a witness--furthermore,
I see no evil in declining a public testimony in suffering times,
or hiding in times of persecution,
for I have Christ`'s and Paul`'s examples--I see no evil
in worshipping and respecting the persons of men;
for whatever others do,
I intend a sincere notice that I take of those I know and have a good esteem for--Lastly,
I see no evil in keeping my shop shut upon the world`'s holidays and mass-days,
as they call them,
though they are rather lewdly and superstitiously than religiously kept;
for I would not willingly give any offence to my neighbours;
and since your testimony is against imposition,
and for leaving every one to the measure of grace which God has given him, not only,
No man has power to reprove or judge me, but I may be as good a Friend as any of you,
according to my measure.
And now, here is measure set up against measure, which is confusion itself--Babel indeed.
This is the rock which both professors and profane would long since have run us upon,
namely, That a way is hereby opened to all the world`'s libertines,
to plead the light within for their excesses; which indeed grieves the spirit of God,
and was severely judged by our Friends in the beginning,
and is still reproved by them that keep their habitation,
though some are become as wandering stars through their own pride and
the prevalence of the hour of temptation that has overtaken them;
whereas had they kept in the channel of love and life,
in the orbit and order of the celestial power,
they had shined as stars in the firmament of God forever.
And from the deep sense that I have of the working of the enemy of Zion`'s peace,
to rend and divide the heritage of God, who under the pretence of crying down man,
forms and prescriptions, is crying down the heavenly man Christ Jesus,
his blessed order and government,
which he has brought forth by his own revelation
and power through his faithful witnesses.

This I further testify, First, That the enemy, by these fair pretences,
strikes at the godly care and travail which dwells
upon the spirits of many faithful brethren,
that all things might be preserved sweet, comely,
virtuous and of good report in the church of God.
Secondly, That there never was greater necessity of this godly care than at this day,
since we were a people, wherein the cross, by too many,
is not so closely kept to as in days past,
and in which there is not only a great convincement,
but a young generation descended of Friends,
who though they retain the form their education has led them into,
yet many of them adorn not the Gospel with that sensible,
weighty and heavenly conduct as becomes the children of the undefiled religion,
and the seed of that precious faith which works by the love that overcomes the world.
And the Lord God of heaven and earth,
that has sent his Son Christ Jesus a light into our hearts and consciences,
to whose search and judgment all ought to, and must, bring their deeds,
and render up their account, bears holy record,
that for '`this end has he moved upon the spirits of his servants,
and for this good end only have his servants given forth,
recommended and put in practice`",
those things that are now in godly use among his people,
whether in this or other nations, relating to men`'s and women`'s meetings,
and their various and weighty services.

And further; in the fear of the Almighty God I shall add,
that heavenly peace and prosperity dwell with those
who are found in a holy and zealous practice of them;
wherefore I warn all, that they take heed of a slighting and obstinate mind,
and that they have a care how they give way to the outcry of some, falsely entitled,
Liberty of conscience against imposition, etc, for the end thereof is to lead back again,
and give ease to the carnal mind,
which at last will bring death again upon the soul
to God and the living society of his children.
And indeed,
it is a great shame that any who have`' ever known the Truth of God in the inward parts,
and the sweet society of brethren,
especially those who were early in the work of this blessed day and heavenly dispensation,
should so far depart from the fear and awe of the Lord, as to use such unsavoury,
as well as untrue expressions.
This is very far from that meek spirit of Jesus, and the first love,
which they pretend to have so singularly kept in, which bears all things,
suffers all things, and endures all things,
and teaches to keep the word of patience in the hour of tribulation; no,
but it is judging of spiritual things with a carnal and prejudiced mind,
stumbling at the matter, for the sake of the persons through whom it comes,
not eyeing nor weighing the spirit the thing arises from,
but the person by whom it is spoken, which darkens the eye of the understanding,
and blinds, by prejudice, the mind that should discern, taste and judge;
from which many mischiefs have sprung to the church of Christ in various ages.
Nor is it the least evil this spirit of strife is guilty of, even at this day,
that it uses the words, liberty of conscience and imposition, against the brethren,
in the same manner that our suffering Friends have been always accustomed
to use them against the persecuting priests and powers of the earth;
as if it were the same thing to admonish and reprove conceited, high-minded,
loose or contentious persons in the church,
as to compel conformity in matters of faith and worship,
by violence upon the persons and estates of conscientious dissenters.
O such iniquity God will not leave unreproved!

This, dear Friends I send among you, as a token of my true love,
in the revelation of the free spirit of our God and Father,
who have ever been a friend to true liberty, as in the state according to law,
so in the church according to Scripture, and as it stands in the Truth of Jesus,
that makes them who love it free indeed; Let us all keep low,
and remember the rock from which we were hewn,
and dwell in a tender and reverent sense of the daily
mercies and providences of the Lord,
looking well to our own growth and prosperity in his heavenly way and work;
then shall the desire of our hearts be more and more after him,
and the remembrance of his name; and with our love to God,
will our love increase one towards another, helping and aiding one another.
And I do not doubt, that God who has brought us out of the land of Egypt,
and out of the house of bondage,
and delivered us from the mouth of the lion and the paw of the bear,
will preserve his people from this uncircumcised spirit that is not in covenant with God,
nor under the yoke of his holy royal law of true spiritual liberty;
for they that keep and walk in the light of Jesus,
are fenced from the power of this crooked serpent, that seeks whom he may betray;
nor are any stung by him but the unwatchful,
the listeners and hearkeners after his jealous whispers and detracting insinuations.
They are such as make their dwelling in the earth, where his region is,
and where he creeps and twists, who is earthly, sensual and devilish,
and so is all the wisdom that comes from him.

My dear Friends, keep, I pray you, in the simplicity of the Truth and cross of Jesus,
and wait for your daily bread, and to be daily renewed from the Lord;
look to your increase about eternal riches,
and be sure to lay up treasure in heaven that fades not away,
that your faith and hope may have eternal foundations,
which the cross occurrences of time, and fears of mortality cannot move.
And beware of that loose and irreverent spirit,
which has not those in high esteem among you, who are faithful in the Lord`'s work,
and who labour in his blessed word and doctrine.
I plainly see a coldness and shortness on this hand; and let the pretence be as it will,
it is not pleasing to the Lord.
They that love Christ, his servants are dear to them,
and they bear a tender regard to their trials, travails, spendings and sufferings,
who seek not yours, but you,
that you may all be presented blameless at the coming
of the great God and our Saviour Jesus Christ;
that so the Gospel ministry and testimony may be
held up with holy fervent love and godly esteem,
to the keeping under every raw and exalted mind,
and whatever may slight and turn against it,
lest God that has richly visited us with his fatherly
visitations and day springing from on high,
should remove his blessing from among us, and place his candlestick among other people.

Be wise therefore,
O Friends! for behold He is at the door that must have an account of your stewardship.
Be watchful, keep to your first love and works,
that so you may endure to the end and be saved.
And having overcome, you may have right to eat of the tree of life,
which is in the midst of the paradise of God.

The God of peace, who has brought our dear Lord Jesus from the dead, and us with him,
more abundantly enrich you all with wisdom and knowledge, in the revelation of himself,
through faith in his Son, by whom in these last days he has spoken to us,
who is the blessed and only Potentate, King of kings and Lord of lords,
who only has immortality; to whom be honour and power everlasting.
Amen.

Your friend and brother,
in the tribulation and salvation of the enduring kingdom of our God,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Worminghurst in Sussex, the 20th of the Ninth month, 1681.

[.asterism]
'''

About this time, the meetings of Friends and other dissenters, in the city of Bristol,
were subjected to a fresh persecution, at the instigation of John Knight, the sheriff,
and J. Helliar, an attorney, who with a band of unprincipled informers,
stretched the persecuting laws of the day beyond their legal extent,
seizing the property of Friends, and selling it for a fourth part of its value,
to satisfy their numerous distraints.
They also, by example and encouragement,
stimulated the rabble to commit the most shameful personal abuse,
without regard to age or sex,
upon those whom they found convened at their places of religious worship.
Friends were crowded into a filthy prison,
where one of the aldermen declared he would not put a favourite dog.

Though the rage of these oppressive officers was not vented upon Friends alone,
yet they as usual bore the heaviest part of the storm,
because of their open and unflinching testimony to the duty of assembling for the solemn
purpose of indicating their allegiance to the Giver of every good and perfect gift.^
footnote:[It is worthy of notice, that the persecution was carried to such an extent,
that nearly all the adult members of the society were imprisoned,
yet the boys and girls under sixteen continued to keep up the meetings.
And although the malice of the persecutors was frequently wreaked upon them,
yet they could not be deterred from supporting the
testimony for which their parents were suffering.]

As an encouragement to Friends under their grievous sufferings,
William Penn addressed them in the following epistle:

[.embedded-content-document.epistle]
--

[.blurb]
=== To the friends of God in the city of Bristol; this is sent to be read among them, when assembled to wait upon the Lord.

[.salutation]
My beloved in the Lord!

I do herewith send among you the dear and tender salutation of my unfeigned love,
that is held in the fellowship of the lasting Gospel of peace,
that has many years been preached and believed among you,
beseeching the God and Father of this glorious day of the Son of Man,
to increase and multiply his grace, mercy and peace among you, that you maybe faithful,
and abound in every good word and work, doing and suffering what is pleasing unto God,
that you may prove what is that good and acceptable, and perfect will of God,
which becomes you to be found daily doing,
that so an entrance may be administered unto you abundantly,
into the kingdom of our Lord and Saviour Jesus Christ, that is an everlasting kingdom.

My beloved brethren and sisters, be not cast down at the rage of evil men,
whose anger works not the righteousness of God, and whose cruelty the Lord will limit.
Nothing strange or unusual is come to pass,
it makes well for them that eye the Lord in and through these sufferings.
There is food in affliction, and though the instruments of it cannot see it,
all shall work together for good to them that fear the Lord.
Keep your ground in the Truth, that was and is the saints`' victory.
They that shrink go out of it; it is a shield to the righteous.
Feel it, and see, I charge you by the presence of the Lord,
that you turn not aside the Lord`'s end towards you in this suffering,
by consulting with flesh and blood in easing your adversaries, for that will load you.
Keep out of base bargainings or conniving at fleshly evasions of the cross.
Our Captain would not leave us such an example.
Let them shrink that know not why they should stand; we know in whom we have believed.
He is mightier in the faithful to suffer and endure to the end,
than the world to persecute.
Call to mind those blessed ancients, that by faith overcame of old,
that endured cruel mockings and scourgings, yes, moreover, bonds and imprisonments,
that accepted not deliverance, to deny their testimony,
that they might obtain a better resurrection.
They were stoned, they were tempted, they were sawn asunder,
they were slain with the sword; but you have not so resisted unto blood, and it suffices,
I hope to you, that the Lord knows how to deliver the godly out of temptation,
and to reserve the unjust unto the day of judgment to be punished,
when it may be truly said, it shall go well with the righteous,
but very ill with the wicked.

The Lord God by his power keep your hearts living to him,
that it may be your delight to wait upon him, and receive the bounty of his love,
that being fed with his daily bread and drinking of his cup of blessing,
you may be raised above the fear or trouble of earthly things,
and grow strong in Him who is your crown of rejoicing,
that having answered his requirings, and walked faithfully before him,
you may receive in the end of your days the welcome sentence of gladness.
Eternal riches are before you, an inheritance incorruptible.
Press after that glorious mark.
Let your minds be set on things that are above,
and when Christ that is the glory of his poor people shall appear,
they shall appear with him in glory; when all tears shall be wiped away,
and there shall be no more sorrow or sighing,
but they that overcome shall stand as Mount Zion that cannot be moved.

So, my dear friends and brethren, endure, that you may be saved,
and you shall reap if you faint not.
What should we be troubled for?
Our kingdom is not of this world, and cannot be shaken by the overturning here below.
Let all give glory to God on high, live peaceably on earth,
and show good will to all men, and our enemies will at last see,
that they do they know not what, and repent and glorify God our heavenly Father.
O great is God`'s work on earth.
Be universal in your spirits and keep out of all straitness and narrowness.
Look to God`'s great and glorious kingdom and its prosperity.
Our time is not our own, nor are we our own.
God has bought us with a price, not to serve ourselves, but to glorify him, both in body,
soul and spirit; and by bodily sufferings for the Truth, he is glorified.
Look to the accomplishing of the will of God in these things,
that the measure of Christ`'s sufferings may be filled up in us,
who bear about the dying of the Lord Jesus; else our suffering is in vain.
Wherefore, as the flock of God, and family and household of faith,
walk with your loins girded, being sober,
hoping to the end for the grace and kindness which shall
be brought unto you at the revelation of Jesus Christ,
to whom you and yours are committed.
His precious Spirit minister unto you,
and his own life be shed abroad plenteously among you,
that you may be kept blameless to the end.

I am your friend and brother in the fellowship of the suffering for the Truth,
as it is in Jesus,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Worminghurst, the 24th of the Twelfth month, 1681.
