== Chapter XXI.

1681+++.+++ We have seen that William Penn, as trustee for Edward Byllinge,
had become concerned in the colonization of West Jersey.
But in 1679, Sir George Carteret, proprietor of East Jersey, died,
leaving his property there to be sold for the benefit of his creditors.
This sale was effected in the beginning of 1682, William Penn and eleven others,
being the purchasers.
They soon afterwards took into the concern twelve others,
thus constituting a company of twenty-four proprietors,
nearly all members of the Society of Friends, and of whom Robert Barclay,
the celebrated Apologist, was one.
Of this growing colony, Robert Barclay was appointed governor for life;
but he never visited the country.
He held the office of governor only about two years,
having entrusted the execution of his official duties to a deputy.
Thus it happened that New-Jersey, both east and west, was settled in great part,
under the auspices of Friends.
The pacific principles upon which these settlements were made,
as well as those subsequently formed on the west of the Delaware,
were found capable of preserving the relations of
peace with the native inhabitants of the country;
and thus we are furnished with a practical demonstration,
of which the world has afforded but few, of the superior advantage to nations,
as well as individuals, arising from a strict regard to the principles of the Gospel.

The purchase of East-Jersey by William Penn and others,
was subsequent to the grant which he obtained of the province which bears his name,
yet his attention was not so fully engrossed by the latter as to prevent him
from contributing by his influence and his pen to the settlement of the former.
Yet as the management of his own province occupied great part of his time and attention,
we may reasonably suppose that he left the concerns of New-Jersey chiefly to his colleagues.

It appears by one of his letters, that at an early period of his life,
even while he was a student at Oxford,
William Penn had a distant prospect of service in the western world;
and his connection with the province of New-Jersey,
having made him partially acquainted with the country on the opposite side of the Delaware,
he formed the idea of procuring the grant of a territory there;
in which he might not only furnish an asylum to Friends and others
who were persecuted on account of their religious persuasion,
but might erect a government upon principles approaching
much nearer the standard of evangelical purity,
than any which had been previously raised.

The application of William Penn for the grant of the province which now bears his name,
it appears, was made in the summer of 1680.
The grant to Lord Baltimore, which was made by Charles the First, lay to the south,
and was understood to extend no further north than some point on the Delaware bay.
The Duke of York obtained a part of the tract lying on the east of that bay.
The application of William Penn was laid before the privy council,
and by them referred to the Lords Committee of Trade and Plantations.
The agent of the Duke of York was heard, in relation to the claims of the latter.
The rights of Lord Baltimore were also examined.
The advice of chief justice North and the attorney general, was taken on the subject.
After these contiguous claims had been fully canvassed,
a charter was granted to William Penn, dated at Westminster, the 4th of March, 1681,
constituting him proprietary and governor of the province of Pennsylvania.
This province is described in the charter, as bounded on the east by the Delaware river,
from a point twelve miles north of Newcastle,
to the beginning of the forty-third degree of north latitude,
in case the river should be found to extend that far north--or if it should not,
then a meridian was to be run from its head waters to the said latitude;
on the north by the parallel of latitude passing
through the beginning of the forty-third degree;
and to extend westward through five degrees of longitude,
computing from this eastern boundary.
The southern boundary was to be determined by a circle
described at twelve miles from Newcastle,
northward and westward,
until it intersected the beginning of the fortieth degree of north latitude;
and from there the line was to extend on that parallel
westward to the meridian previously determined.
The province was therefore, designed to include three degrees of latitude,
except a small part on the eastern side,
and five degrees of longitude on the northern parallel.
It was afterwards discovered, that owing to the ignorance of the people of that day,
in regard to the geography of the country,
the boundaries assigned to Pennsylvania were irreconcilable with each other,
and encroached on the chartered limits of Maryland.
This involved the proprietaries in a controversy,
which was not terminated during their lives.

In regard to the motives of William Penn in this undertaking,
it is not difficult to discover that he was more
influenced by religious than pecuniary considerations.
In one of his letters, he has this passage:

And now give me leave to say, I have served the Lord, his Truth and people in my day,
to my ability, and not sought myself, though much spent myself;
so has he made me firmly to believe that I shall not even outwardly go without my reward;
I see his blessed hand therein,
that has blessed my faith and patience and long attendance with success.
And because I have been somewhat exercised at times
about the nature and end of government among men,
it is reasonable to expect that I should endeavour
to establish a just and righteous one in this province,
that others may take example by it--truly this my heart desires.
For nations need a precedent,
and till vice and corrupt manners be impartially rebuked and punished,
and till virtue and sobriety be cherished, the wrath of God will hang over nations.
I do, therefore, desire the Lord`'s wisdom to guide me,
and those that may be concerned with me,
that we may do the thing that is truly wise and just.

In a letter to a particular friend, written in 1681, he says,

For my country, I eyed the Lord in obtaining it;
and more was I drawn inward to look to him,
and to owe it to his hand and power than to any other way.
I have so obtained it and desire to keep it, that I may not be unworthy of his love;
but do that which may answer his kind providence and serve his Truth and people;
that an example may be set up to the nations.
There may be room there, though not here, for such a holy experiment.

The motives of the king in making this grant,
as far as they can be inferred from the charter itself,
appear to have been a desire to favour William Penn
in his laudable efforts to enlarge the British empire,
to promote the trade and prosperity of the kingdom and to reduce the savage nations,
by just and gentle measures, to the love of civilized life and the Christian religion;
and a regard to the memory and merits of the deceased admiral.

It appears that the name assigned to the province
was not entirely agreeable to William Penn.
He was desirous of designating it New-Wales,
but the under secretary to the council opposed it.
He then proposed Sylvania, as expressive of its condition,
being mostly covered with woods; but the name of Penn was prefixed by others.
This prefix was designed as an honour to the father, and not to the son;
but the latter seems to have been apprehensive that the
act of naming the province would be attributed to him,
and be deemed an evidence of vanity.
He therefore tried his influence with the king and the under secretary,
offering twenty guineas to the latter,
to procure their consent to the erasure of the family name.
But the king chose to assume the responsibility of giving it a name,
and determined that it should be Pennsylvania.
Posterity will probably not regret the decision of Charles.
This, however, is the only one of the North American colonies, now states,
which bears the name of its founder.

The charter was followed by a declaration from the king,
dated the 2nd of April of the same year,
requiring all persons residing within the chartered limits of Pennsylvania,
to yield due obedience to William Penn, his heirs and assigns,
as absolute proprietaries and governors thereof,
and to his and their deputies and agents, according to the terms of the charter.^
footnote:[A few settlements had been formed on the Delaware,
within the chartered limits of Pennsylvania, by the Dutch and Swedes,
and these were now become subjects of the British crown.]
By this charter William Penn became possessed of great political power,
and was made the proprietor as far as the royal grant could render him such,
of an extensive tract of land which was nearly all covered with woods,
and occupied by wandering tribes of uncivilized Indians.
Whatever rights the discovery or conquest of any
of these lands was supposed to confer on the Europeans,
William Penn was sensible that the natives were the real proprietors of the soil.
In his expanded schemes of benevolence,
he did not overlook the rights and interests of any portion of the human family,
however weak or unlettered.
One of the early objects of attention therefore,
was the cultivation of a good understanding with the Indian inhabitants of Pennsylvania.

The original draught of William Penn`'s charter is said to have been drawn by himself,
and that the charter of Charles I. to Sir George Calvert was used as a model.
The liberality which marks this document,
certainly indicates that some other hands than the
ministers of Charles II. were employed in its preparation.
It however appears, that by whomsoever it was originally drawn,
it received its last revision from chief justice North, and the attorney general,
Sir William Jones.
Nothing now appears by which we can determine at whose suggestion that clause was introduced,
which invested William Penn with a military command.
It is very probable,
that the advisers of King Charles considered such an authority
essential to the maintenance of the government;
and it must be admitted,
that such a power could hardly have been entrusted to safer hands.
During his administration, the military authority was a dead letter.

Immediately after obtaining his charter,
William Penn commenced his preparations for settling the province.
He prepared such an account of the country as could then be obtained, which he published,
together with a copy of the charter, and other documents connected with it;
explaining the terms upon which the lands were to be sold.
The conditions of sale were, forty shillings sterling, in cash,
and one shilling per annum forever, as the price of one hundred acres of unseated land.
These annual payments were called quit-rents,
and were allowed to be principally purchased off at the option of the grantee.
A small annual sum however, was designed to remain as a perpetual rent.
These quit-rents were unquestionably at first a part of the original purchase.
The reason why they were not allowed to be totally extinguished by subsequent purchase,
is said to have been,
that William Penn held his title from the crown by a small annual rent,
and therefore a small yearly rent from the purchasers,
was requisite to give validity to their titles.
The yearly return of William Penn to the king,
appears by the charter to have been merely nominal,
except under the contingency of discovering mines of silver or gold;
in which case one-fifth of the ore was reserved.
Yet the title of the proprietary to the soil was, in point of law, a feudal,
not an allodial tenure; but divested of the military character of such tenures;
he therefore did not consider himself authorized to make sales upon allodial principles.
A nominal rent being considered necessary to give legal force to his grants,
he acted in good faith to the grantees,
when he stipulated that a small portion of the original
cost should remain unpaid at the time of sale,
and be made the basis of a permanent yearly rent.

These quit-rents subsequently became a subject of unpleasant discussion
between the settlers and the proprietary or his deputies.

The invitation which the proposals contained,
to such of his countrymen as might incline to emigrate to Pennsylvania,
was marked by his usual solicitude for their religious as well as temporal advancement.
The address was closed with the following judicious admonition.

I desire my dear country-folks, to consider seriously the premises,
as well the inconvenience as future ease and plenty; that so none may move rashly,
or from a fickle, but from a solid mind; having above all things,
an eye to the providence of God, in the disposing of themselves;
and I would further advise all such, at least to have the permission,
if not the good-liking of their near relations;
for that is both natural and a duty incumbent upon all.
And by this will natural affections be preserved,
and a friendly and profitable correspondence between them;
in all which I beseech Almighty God to direct us,
that his blessing may attend our honest endeavours;
and then the consequence of all our undertakings
will turn to the glory of his great name,
and all true happiness to us and our posterity.
Amen.

Upon the publication of these proposals, a great number of purchasers, from London,
Liverpool and Bristol, soon appeared.
Among the latter a company was formed,
which was termed "`The free Society of Traders in Pennsylvania,`"
who purchased twenty thousand acres of land,
and made preparations for engaging in various branches of trade.

The proprietary having made considerable sales of land,
agreed with the purchasers upon certain conditions,
which may be considered as an incipient constitution of government,
according to the powers granted by the charter.
This document was entitled,
"`Certain conditions or concessions agreed upon by William Penn,
proprietary and governor of the province of Pennsylvania,
and those who are the adventurers and purchasers in the same province.`"
It consists of twenty articles, most of which relate to the manner of locating,
improving and occupying the purchased lands.
In this the proprietary manifested a care to promote
the early improvement of the lands which were sold,
and to prevent purchasers from holding large tracts
in the vicinity of the principal settlements,
without occupying or improving them.
But there were several provisions which marked his care for the
maintenance of justice and sound morality in the province,
and particularly in their interactions with the Indians.
These are worthy of more particular notice.

In the sale and purchase of goods, intended for exportation,
whether the Indians were parties to the transaction or not,
the goods were to be submitted to public inspection.
If those offered for sale were not of the kind and
quality which they were represented to be,
or were deficient in measure or weight, they were forfeited to the public treasury.

As it had been usual for planters to defraud the Indians,
by the sale of goods of inferior quality or such as contained unsuspected mixtures,
it was stipulated that whatever was given to the Indians in exchange for their furs,
should be exposed to public view, and subjected to the proper test;
that goods of inferior quality should not be passed upon them under a deceptive character,
and no injury or provocation be offered to them.

In case any man should by any means, either in word or deed, wrong an Indian,
he was to incur the same penalty as though the offence was given to one of his fellow-planters.
And in case any man should receive an injury from an Indian,
he was not to be judge in his own case,
but must apply to the governor or some inferior officer,
by whom care should be taken to procure,
from the chiefs of the tribe to which such Indian belonged, the proper reparation.

All differences which might arise between the planters and Indians,
were to be settled by a board, composed of six planters and six Indians,
that thus equal justice might be maintained and all occasions of jealousy and discord be,
as much as possible, avoided.

Three ships sailed for Pennsylvania in the course of the year 1681,
two from London and one from Bristol.
In one of them, sailed William Markham, a relative of William Penn,
whom he appointed deputy-governor, and joined with him several commissioners,
who were authorized to treat with the natives for the sale of their lands;
and enjoined to treat them with all possible justice, candour and humanity.

The London vessels were the John and Sarah, commanded by Henry Smith, and the Amity,
of which Richard Dimon was master.
The former arrived at its place of destination,
being the first which conveyed the English emigrants under William Penn to the new province.
The latter meeting with contrary winds, was carried to the West Indies;
and did not arrive at Pennsylvania till the ensuing spring.
The Bristol Factor, commanded by Robert Drew, arrived at Uplands, now Chester,
on the 11th of the tenth month, which according to the present style,
would have been reckoned the 21st of the twelfth; where some houses being erected,
they went on shore.
In the ensuing night the river was frozen over,
and the passengers remained there till spring.

By these commissioners he sent a letter to the native inhabitants of Pennsylvania,
of which the following is a copy.

London, the 18th of the Eighth month, 1681.

My friends,

There is a great God and power that has made the world and all things therein,
to whom you and I and all people owe their being and well-being;
and to whom you and I must one day give an account for all that we do in the world.
This great God has written his law in our hearts,
by which we are taught and commanded to love and help, and do good to one another,
and not to do harm and mischief one unto another.
Now this great God has been pleased to make me concerned in your part of the world,
and the king of the country where I live has given me a great province therein,
but I desire to enjoy it with your love and consent,
that we may always live together as neighbours and friends;
else what would the great God do to us?
who has made us not to devour and destroy one another,
but to live soberly and kindly together in the world.
Now I would have you well observe,
that I am very sensible of the unkindness and injustice that have been
too much exercised towards you by the people of these parts of the world,
who have sought themselves, and to make great advantages by you,
rather than to be examples of justice and goodness unto you,
which I hear has been matter of trouble to you,
and caused great grudgings and animosities, sometimes to the shedding of blood,
which has made the great God angry.
But I am not such a man, as is well known in my own country.
I have great love and regard towards you,
and I desire to win and gain your love and friendship by a kind, just and peaceable life,
and the people I send are of the same mind,
and shall in all things behave themselves accordingly,
and if in anything any shall offend you or your people,
you shall have a full and speedy satisfaction for
the same by an equal number of just men on both sides,
that by no means you may have just occasion of being offended against them.
I shall shortly come to you myself,
at which time we may more largely and freely confer and discourse of these matters;
in the mean time I have sent my commissioners to treat with you about land,
and a firm league of peace.
Let me desire you to be kind to them and the people,
and receive these presents and tokens which I have sent you,
as a testimony of my good-will to you, and my resolution to live justly,
peaceably and friendly with you.

I am your loving friend,

William Penn.

By the same conveyance was probably communicated
a letter to the European inhabitants of the province,
which has been recently published in the Memoirs of the Historical Society of Pennsylvania.
In this he assured them of his desire for their happiness
in this world and in that to come;
and of his intention to allow them to be governed by laws of their own framing,
and that everything would be granted which a sober and free people
could desire for the security and improvement of their happiness.

As the conditions and concessions agreed upon in the summer of 1681,
contained nothing more than a general outline,
it was judged expedient to prepare a regular frame of government for the province,
together with a brief system of laws which were agreed upon in England by the
proprietary and several of those who were preparing to emigrate to Pennsylvania.
These laws were to be submitted for examination and adoption
to the first provincial assembly convened in the province.

In the preface, which was unquestionably the production of William Penn himself,
we find a number of valuable sentiments on the nature and origin of government.
It is observed that when the Creator of the world conferred
upon man his authority over the creatures he had made,
he furnished him not only with skill and power, but with integrity to use them justly.
The principle of Divine love was his preserver and guide;
and there was no need of compulsive means.
But man becoming disobedient to the Divine law written in the heart,
became necessarily subject to the reproof and conviction of the just law without,
in a judicial administration.
Thus outward government is established as an auxiliary to religion.
First, as a terror to those who do evil, and second,
to cherish and encourage those who do well.
The restraining power of government, which applies only to the transgressors,
is considered as its coarsest feature; the regulation of many other affairs,
of a milder character, making up a great part of it.

With regard to the forms of government, the author observes,
that any government is free to the people under it, whatever be the frame,
where the laws rule, and the people are a party to those laws,
and more than this is tyranny, oligarchy or confusion.
Governments rather depend upon men, than men upon governments.
Let men be good, and the government cannot be bad, or if it is, they will cure it.
But if men are bad, let the government be ever so good,
they will be likely to warp and spoil it.
A loose and depraved people love laws and an administration like themselves.
Therefore that which makes a good constitution is necessary to maintain it; namely,
men of wisdom and virtue.
As these qualities are not hereditary,
they ought to be carefully propagated by a virtuous education.

The frame of government and its accompanying laws,
are stated to have been adopted with reverence to God, and good conscience toward men,
according to the best capacity of their framers,
to answer the great end of all government, to support power in reverence with the people,
and to secure the people from the abuse of power,
that the people may be free by their just obedience,
and the magistrates honourable for their just administration;
for liberty without obedience is confusion, and obedience without liberty is slavery.^
footnote:[In a letter to one of his friends,
written about the time this frame of government was agreed upon, he observed,
"`For the matters of liberty and privilege, I purpose that which is extraordinary,
and leave myself and successors no power of doing mischief,
that the will of one man may not hinder the good of a whole community.`"]

Of the laws agreed upon and published with the frame of government,
I shall notice two or three which partake of a religious character.

That all persons living in the province,
who confess and acknowledge the one Almighty and eternal God, to be the Creator,
Upholder and Ruler of the world;
and that hold themselves obliged in conscience to
live peaceably and justly in civil society,
shall in no ways be molested or prejudiced for their religious persuasion or practice,
in matters of faith and worship, nor shall they be compelled, at any time,
to frequent or maintain any religious worship, place or ministry whatever.

That, according to the good example of the primitive Christians,
and the ease of the creation, every first-day of the week, called the Lord`'s-day,
people shall abstain from their common daily labour,
that they may better dispose themselves to worship God according to their understandings.

That as a careless and corrupt administration of
justice draws the wrath of God upon magistrates,
so the wildness and looseness of the people provoke
the indignation of God against a country;
therefore, that all such offences against God, as swearing, cursing, lying,
profane talking, drunkenness, drinking of healths, obscene words,
and several other scandalous acts particularly named, treasons, misprisions, duels,
murders, felony, sedition, maims,
forcible entries and other violences to the persons
and estates of the inhabitants of the province;
all prizes, stage-plays, cards, dice, may-games, gamesters, masques, revels,
bull-baitings, cock-fightings, bear-baitings and the like,
which excite the people to rudeness, cruelty and irreligion,
shall be respectively discouraged and severely punished,
according to the appointment of the governor and
freemen in provincial council and general assembly.

This system was signed by the governor and freemen in the third month, 1682.

The grant of territory which had been made to James, Duke of York,
having given him some claim, though at best a very doubtful one,
to the tract included within the limits of Pennsylvania, William Penn,
previous to entering himself upon his new possession, obtained from the duke,
a full release of all his claims upon the province.
This deed was dated the 20th of August, 1682.
He also obtained in the same year, by two separate deeds from the duke,
a grant of the tract on the Delaware river and bay, commonly termed,
the three lower counties, now the State of Delaware.
This grant was obtained to secure the free use of the river,
and to prevent the trouble which might probably arise from the
access to the province being in the possession of another.
It conveyed to William Penn the right of soil,
for which he agreed to pay to the duke and his heirs,
one-half of the rents and profits which he should receive from it.

But if there was any political power conveyed,
it was rather a consequence of the grant than a part of it.
According to the liberal opinions of William Penn in relation to government,
that the laws must rule and the people be a party to the law,
it seems that the power of government must rest chiefly with the people themselves.
Upon this principle,
William Penn and the inhabitants of these lower counties appear to have acted.

They considered themselves subjects of the British empire,
but I do not find that they ever after this time acknowledged
any authority in the government of New York,
to which previous to this grant these counties were an appendage.

In this year, 1682, the mother of William Penn was removed by death.
This event appears to have affected him very closely.
Besides the circumstances usually attendant on the maternal relation,
she had been peculiarly endeared to him by her tenderness
and care in the time of his greatest trials.
When exposed to the displeasure of his father on account of his religious principles,
she interposed her good offices and relieved his needs from her private purse.
