== Chapter XXI.

William Penn having completed his preparations for a voyage to America,
went in the sixth month of this year, on board the ship Welcome, of three hundred tons,
Robert Greenaway commander; and on the 30th of the month,
addressed a valedictory epistle to his friends in England.
He also wrote the following letter to Stephen Crisp, a valuable minister of the Gospel,
who travelled and suffered considerably in the service of his Divine Master.

[.embedded-content-document.letter]
--

[.salutation]
Dear Stephen Crisp,

My dear and lasting love in the Lord`'s everlasting Truth reaches to you,
with whom is my fellowship in the Gospel of peace,
that is more dear and precious to my soul than all
the treasures and pleasures of this world;
for when a few years are passed,
we shall all go the way from which we shall never return:
and that we may unweariedly serve the Lord in our day and place,
and in the end enjoy a portion with the blessed that are at rest,
is the breathing of my soul!

Stephen! we know one another, and I need not say much to you; but this I will say,
your parting dwells with me, or rather, your love at my parting.
How innocent, how tender, how like the little child that has no guile!
The Lord will bless that ground (Pennsylvania).
I have also a letter from you, which comforted me; for many are my trials,
yet not more than my supplies from my heavenly Father, whose glory I seek,
and the renown of his blessed name.
And truly, Stephen, there is work enough, and here is room to work in.
Surely God will come in for a share in this planting work,
and that leaven shall leaven the lump in time.
I do not believe the Lord`'s providence had run this way towards me,
but that he has a heavenly end and service in it: so with him I leave all, and myself,
and you and his dear people, and blessed name on earth.

God Almighty, immortal and eternal, be with us,
that in the body and out of the body we may be his forever!
I am, in the ancient dear fellowship,

[.signed-section-closing]
Your faithful friend and brother,

[.signed-section-signature]
William Penn.

--

As this voyage and residence in America,
were likely to keep him separated from his family, during a considerable time,
he left behind him an interesting and instructive address to his wife and children,
in relation to their conduct during his absence.
This communication is filled with important suggestions upon the economy of life,
and is worthy of a careful perusal, notwithstanding its length.

[.embedded-content-document.letter]
--

[.salutation]
My dear wife and children,

My love, which neither sea nor land, nor death itself,
can extinguish or lessen toward you, most endearly visits you with eternal embraces,
and will abide with you forever: and may the God of my life watch over you and bless you,
and do you good in this world and forever!--Some things are upon
my spirit to leave with you in your respective capacities,
as I am to the one a husband, and to the rest a father,
if I should never see you more in this world.

My dear wife, remember you were the love of my youth, and much the joy of my life;
the most beloved, as well as most worthy of all my earthly comforts:
and the reason of that love was more your inward than your outward excellencies,
which yet were many.
God knows, and you know it, I can say it was a match of Providence`'s making;
and God`'s image in us both was the first thing,
and the most amiable and engaging ornament in our eyes.
Now I am to leave you,
and that without knowing whether I shall ever see you more in this world,
take my counsel into your bosom, and let it dwell with you in my stead while you live.

[.numbered-group]
====

[.numbered]
_First:_
Let the fear of the Lord and a zeal and love to his glory dwell richly in your heart;
and you will watch for good over yourself and your dear children and family,
that no rude, light or bad thing be committed: else God will be offended,
and he will repent himself of the good he intends you and yours.

[.numbered]
_Secondly:_ Be diligent in meetings for worship and business;
stir up yourself and others herein; it is your duty and place:
and let meetings be kept once a day in the family to wait upon the Lord,
who has given us much time for ourselves.
And my dearest, to make your family matters easy to you, divide your time and be regular;
it is easy and sweet: your retirement will afford you to do it;
as in the morning to view the business of the house, and fix it as you desire,
seeing all be in order; that by your counsel all may move,
and to you render an account every evening.
The time for work, for walking, for meals, may be certain, at least as near as may be:
and grieve not yourself with careless servants; they will disorder you: rather pay them,
and let them go, if they will not be better by admonitions:
this is best to avoid many words, which I know wound the soul and offend the Lord.

[.numbered]
_Thirdly:_ Cast up your income, and see what it daily amounts to;
by which you may be sure to have it in your sight and power to keep within compass:
and I beseech you to live low and sparingly, till my debts are paid;
and then enlarge as you see it convenient.
Remember your mother`'s example,
when your father`'s public-spiritedness had worsted his estate, which is my case.
I know you love plain things, and are averse to the pomps of the world;
a nobility natural to you.
I write not as doubtful, but to quicken you, for my sake, to be vigilant herein;
knowing that God will bless your care, and your poor children and you for it.
My mind is wrapt up in a saying of your father`'s, '`I desire not riches,
but to owe nothing;`' and truly that is wealth,
and more than enough to live is a snare attended with many sorrows.
I need not bid you be humble, for you are so; nor meek and patient,
for it is much of your natural disposition:
but I pray you be often in retirement with the Lord,
and guard against encroaching friendships.
Keep them at arm`'s end; for it is giving away our power, aye, and self loo,
into the possession of another; and that which might seem engaging in the beginning,
may prove a yoke and burden too hard and heavy in the end.
Wherefore keep dominion over yourself, and let your children, good meetings and Friends,
be the pleasure of your life.

[.numbered]
_Fourthly:_ And now, my dearest, let me recommend to your care my dear children;
abundantly beloved of me, as the Lord`'s blessings,
and the sweet pledges of our mutual and endeared affection.
Above all things endeavour to breed them up in the love of virtue,
and that holy plain way of it which we have lived in,
that the world in no part of it get into my family.
I had rather they were homely than finely bred as to outward behaviour;
yet I love sweetness mixed with gravity, and cheerfulness tempered with sobriety.
Religion in the heart leads into this true civility,
teaching men and women to be mild and courteous in their behaviour,
an accomplishment worthy indeed of praise.

[.numbered]
_Fifthly:_ Next breed them up in a love one of another:
tell them it is the charge I left behind me;
and that it is the way to have the love and blessing of God upon them;
also what his portion is, who hates, or calls his brother fool.
Sometimes separate them, but not long;
and allow them to send and give each other small things to endear one another with.
Once more I say,
tell them it was my counsel they should be tender and affectionate one to another.
For their learning be liberal.
Spare no cost; for by such parsimony all is lost that is saved:
but let it be useful knowledge, such as is consistent with Truth and godliness,
not cherishing a vain conduct or idle mind;
but ingenuity mixed with industry is good for the body and mind too.
I recommend the useful parts of mathematics, as building houses or ships, measuring,
surveying, dialling, navigation; but agriculture is especially in my eye:
let my children be husbandmen and house-wives; it is industrious, healthy,
honest and of good example: like Abraham and the holy ancients,
who pleased God and obtained a good report.
This leads to consider the works of God and nature, of things that are good,
and diverts the mind from being taken up with the
vain arts and inventions of a luxurious world.
It is commendable in the princes of Germany and the nobles of that empire,
that they have all their children instructed in some useful occupation.
Rather keep an ingenious person in the house to teach them, than send them to schools,
too many evil impressions being commonly received there.
Be sure to observe their genius, and do not cross it as to learning:
let them not dwell too long on one thing; but let their change be agreeable,
and all their diversions have some little bodily labour in them.
When grown big, have most care for them;
for then there are more snares both within and without.
When marriageable, see that they have worthy persons in their eye, of good life,
and good fame for piety and understanding.

====

I need no wealth, but sufficiency; and be sure their love be dear, fervent and mutual,
that it may be happy for them.
I choose not they should be married to earthly, covetous kindred.
And of cities and towns of concourse beware;
the world is apt to stick close to those who have lived and got wealth there:
a country life and estate I like best for my children.
I prefer a decent mansion, of a hundred pounds per annum,
before ten thousand pounds in London, or such like place, in a way of trade.
In fine, my dear, endeavour to breed them dutiful to the Lord, and his blessed light,
truth and grace in their hearts, who is their Creator,
and his fear will grow up with them.
Teach a child, says the wise man, the way you will have him to walk,
and when he is old he will not forget it.
Next, obedience to you, their dear mother; and that not for wrath,
but for conscience-sake; liberal to the poor, pitiful to the miserable,
humble and kind to all; and may my God make you a blessing,
and give you comfort in our dear children;
and in age gather you to the joy and blessedness of the just,
where no death shall separate us, forever!

And now, my dear children,
that are the gifts and mercies of the God of your tender father, hear my counsel,
and lay it up in your hearts; love it more than treasure, and follow it,
and you shall be blessed here and happy hereafter.

In the first place, remember your Creator in the days of your youth.
It was the glory of Israel in the second of Jeremiah:
and how did God bless Josiah because he feared him in his youth! and so he did Jacob,
Joseph and Moses.
O my dear children, remember,
and fear and serve Him who made you and gave you to me and your dear mother;
that you may live to him and glorify him in your generations "`To do this,
in your youthful days seek after the Lord, that you may find him;
remembering his great love in creating you; that you are not beasts, plants or stones,
but that he has kept you, and given you his grace within, and substance without,
and provided plentifully for you.
This remember in your youth, that you may be kept from the evil of the world:
for in age it will be harder to overcome the temptations of it.

Wherefore, my dear children, eschew the appearance of evil,
and love and cleave to that in your hearts which shows you evil from good,
and tells you when you do amiss, and reproves you for it.
It is the light of Christ that he has given you for your salvation.
If you do this and follow my counsel, God will bless you in this world,
and give you an inheritance in that which shall never have an end.
For the light of Jesus is of a purifying nature;
it seasons those who love it and take heed to it; and never leaves such,
till it has brought them to the city of God, that has foundations.
O that you may be seasoned with the gracious nature of it! hide it in your hearts,
and flee, my dear children, from all youthful lusts; the vain sports,
pastimes and pleasures of the world; redeeming the time,
because the days are evil!--You are now beginning
to live--what would some give for your time?
Oh!
I could have lived belter, were I, as you, in the flower of youth.
Therefore love and fear the Lord, keep close to meetings,
and delight to wait on the Lord God of your father and mother, among his despised people,
as we have done; and count it your honour to be members of that Society,
and heirs of that living fellowship which is enjoyed among them,
for the experience of which your father`'s soul blesses the Lord forever.

Next: be obedient to your dear mother,
a woman whose virtue and good name is an honour to you;
for she has been exceeded by none in her time for her plainness, integrity, industry,
humanity, virtue and good understanding;
qualities not usual among women of her worldly condition and quality.
Therefore honour and obey her, my dear children, as your mother,
and your father`'s love and delight; no love her too,
for she loved your father with a deep and upright love,
choosing him before all her many suitors:
and though she be of a delicate constitution and noble spirit,
yet she descended to the utmost tenderness and care for you,
performing the painfulest acts of service to you in your infancy,
as a mother and a nurse too.
I charge you, before the Lord, honour and obey, love and cherish your dear mother.

Next: betake yourselves to some honest, industrious course of life,
and that not of sordid covetousness, but for example and to avoid idleness.
And if you change your condition and marry, choose,
with the knowledge and consent of your mother if living, or of guardians,
or those that have the charge of you.
Mind neither beauty nor riches, but the fear of the Lord,
and a sweet and amiable disposition, such as you can love above all this world,
and that may make your habitations pleasant and desirable to you.

And being married, be tender, affectionate, patient and meek.
Live in the fear of the Lord, and he will bless you and your offspring.
Be sure to live within compass; borrow not, neither be beholden to any.
Ruin not yourselves by kindness to others; for that exceeds the due bounds of friendship,
neither will a true friend expect it.
Small matters I heed not.

Let your industry and parsimony go no further than for a sufficiency for life,
and to make a provision for your children, and that in moderation,
if the Lord gives you any.
I charge you help the poor and needy;
let the Lord have a voluntary share of your income for the good of the poor,
both in our Society and others; for we are all his creatures;
remembering that '`he that gives to the poor lends to the Lord.`'

Know well your in-comings, and your out-goings may be better regulated.
Love not money nor the world: use them only, and they will serve you;
but if you love them you serve them,
which will debase your spirits as well as offend the Lord.

Pity the distressed, and hold out a hand of help to them; it may be your case;
and as you mete to others God will mete to you again.

Be humble and gentle in your conversation; of few words, I charge you;
but always pertinent when you speak, hearing out before you attempt to answer,
and then speaking as if you would persuade, not impose.

Affront none, neither revenge the affronts that are done to you;
but forgive and you shall be forgiven of your heavenly Father.

In making friends consider well first; and when you are fixed be true,
not wavering by reports nor deserting in affliction,
for that becomes not the good and virtuous.

Watch against anger, neither speak nor act in it; for, like drunkenness,
it makes a man a beast, and throws people into desperate inconveniences.

Avoid flatterers, for they are thieves in disguise; their praise is costly,
designing to get by those they bespeak; they are the worst of creatures;
they lie to flatter, and flatter to cheat; and which is worse,
if you believe them you cheat yourselves most dangerously.
But the virtuous, though poor, love, cherish and prefer.
Remember David, who asking the Lord, '`Who shall abide in your tabernacle?
who shall dwell upon your holy hill?`' answers, '`He that walks uprightly,
works righteousness, and speaks the truth in his heart;
in whose eyes the vile person is contemned, but honours them that fear the Lord.`'

Next, my children, be temperate in all things; in your diet,
for that is medicine by prevention; it keeps, no, it makes people healthy,
and their generation sound.
This is exclusive of the spiritual advantage it brings.
Be also plain in your apparel; keep out that lust which reigns too much over some;
let your virtues be your ornaments, remembering life is more than food,
and the body than raiment.
Let your furniture be simple and cheap.
Avoid pride, avarice and luxury.
Read my [.book-title]#No Cross, no Crown.# There is instruction.
Make your conversation with the most eminent for wisdom and piety;
and shun all wicked men as you hope for the blessing of God and
the comfort of your father`'s living and dying prayers.
Be sure you speak no evil of any, no, not of the meanest; much less of your superiors,
as magistrates, guardians, tutors, teachers and elders in Christ.

Be no busy-bodies; meddle not with other folks`' matters,
but when in conscience and duty pressed; for it procures trouble, and is ill manners,
and very unseemly to wise men.

In your families remember Abraham, Moses and Joshua, their integrity to the Lord;
and do as you have them for your examples.

Let the fear and service of the living God be encouraged in your houses,
and that plainness,
sobriety and moderation in all things as becomes God`'s chosen people;
and as I advise you, my beloved children, do you counsel yours,
if God should give you any.
Yes, I counsel and command them as my posterity,
that they love and serve the Lord God with an upright heart,
that he may bless you and yours from generation to generation.

And as for you,
who are likely to be concerned in the government of Pennsylvania and my parts of East-Jersey,
especially the first, I do charge you, before the Lord God and his holy angels,
that you be lowly, diligent and tender, fearing God,
loving the people and hating covetousness.
Let justice have its impartial course, and the law free passage.
Though to your loss, protect no man against it; for you are not above the law,
but the law above you.
Live therefore the lives yourselves you would have the people live,
and then you have right and boldness to punish the transgressor.
Keep upon the square, for God sees you: therefore do your duty,
and be sure you see with your own eyes, and hear with your own ears.
Entertain no lurchers, cherish no informers for gain or revenge; use no tricks;
fly to no devices to support or cover injustice;
but let your hearts be upright before the Lord,
trusting in him above the contrivances of men,
and none shall be able to hurt or supplant.

Oh! the Lord is a strong God, and he can do whatsoever he pleases;
and though men consider it not,
it is the Lord that rules and over-rules in the kingdoms of men,
and he builds up and pulls down.
I, your father, am the man that can say, He that trusts in the Lord,
shall not be confounded.
But God, in due time, will make his enemies be at peace with him.

If you thus behave yourselves,
and so become a terror to evil-doers and a praise to them that do well, God, my God,
will be with you in wisdom and a sound mind,
and make you blessed instruments in his hand for the settlement
of some of those desolate parts of the world,
which my soul desires above all worldly honours and riches,
both for you that go and you that stay; you that govern and you that are governed;
that in the end you may be gathered with me to the rest of God.

Finally, my children, love one another with a true endeared love,
and your dear relations on both sides,
and take care to preserve tender affection in your children to each other,
often marrying within themselves, so as it be without the bounds forbidden in God`'s law,
that so they may not, like the forgetting unnatural world,
grow out of kindred and as cold as strangers;
but as becomes a truly natural and Christian stock,
you and yours after you may live in the pure and fervent love of God towards one another,
as becomes brethren in the spiritual and natural relation.

So, my God, that has blessed me with his abundant mercies,
both of this and the other and blessed life, be with you all, guide you by his counsel,
bless you and bring you to his eternal glory! that you may shine, my dear children,
in the firmament of God`'s power, with the blessed spirits of the just,
that celestial family, praising and admiring him, the God and Father of it, forever.
For there is no God like unto him; the God of Isaac and of Jacob,
the God of the prophets, the apostles and martyrs of Jesus, in whom I live forever.

So farewell to my thrice dearly beloved wife and children!

Yours, as God pleases, in that which no waters can quench, no time forget,
nor distance wear away, but remains forever,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Worminghurst, 4th of Sixth month, 1682.

--

The Welcome proceeded to sea about the beginning of the seventh month (September).
The number of passengers, who were chiefly Friends, was about one hundred.
But they had not been long on the ocean, before the small-pox broke out among them,
and carried off thirty of their number before it disappeared.
In this trying situation,
William Penn administered to the sick every comfort in his power,
both by his personal assistance and his religious admonitions.
The voyage in other respects was prosperous, and in about six weeks,
they came in sight of the American shore.
They soon afterwards entered the Delaware, and on the 24th of the eighth month,
landed at New Castle.

As he sailed up the river, the inhabitants, consisting of English, Dutch and Swedes,
met the proprietary, and manifested their satisfaction with his arrival.
The town of New-Castle, where he first landed,
was originally commenced and at the time of his landing
principally occupied by the Dutch.
It was first called Fort Cassimir, subsequently Delaware town,
and finally designated by the name which it now bears.
There was a courthouse in the town, to which on the day after his arrival,
he invited the principal inhabitants of the place and its vicinity.
Possession of the territory was there taken in due form;
after which he addressed the magistrates and people,
explaining the design of his coming among them,
his views of the nature and end of government;
with an assurance of the free enjoyment of their civil and religious
rights--and an admonition to live in sobriety and peace.
He then renewed the commissions of the magistrates.^
footnote:[This circumstance is a clear indication,
that if the power of government was not expressly granted,
it was understood as connected with the grant of the territory.
For it is not doing justice to the wisdom or integrity of William Penn,
to suppose that he would signalize his arrival in America,
by an act of usurpation.]
Having arranged his concerns at New-Castle, he soon afterwards proceeded to Uplands.
The name of this place was then changed to Chester,
in compliment to one of the companions of his voyage,
who emigrated from Chester in England.
An assembly was convened at that place consisting
of an equal number from the province and territories.
It was not composed of members elected for the purpose,
but of such freemen as chose to attend.

The session lasted but three days,
yet some legislation of great importance to the colonists was effected.

[.numbered-group]
====

[.numbered]
1+++.+++ An act was passed for the union of the province and territories.

[.numbered]
2+++.+++ An act to naturalize the Dutch, Swedes,
and other foreigners then residing within the province and territories.^
footnote:[It may be recollected that the first Europeans who settled on the Delaware,
were Swedes and Dutch, principally the former; and that in 1665,
the latter obtained the complete ascendency.
In 1664, these settlements, were subjected to the authority of the British crown.
One of the articles of capitulation,
was that whoever should take the oaths of allegiance, to the king of Great Britain,
should be from that time a free denizen,
and enjoy all the privileges of trading in any of the king`'s dominions,
as freely as any Englishman.
A denizen however, according to English law, is in a kind of middle state,
between an alien and a natural born subject.
He may take lands by purchase or devise, which an alien cannot,
but he cannot take by inheritance.
In Great Britain, naturalization is effected only by act of parliament.
{footnote-paragraph-split}
By an act passed in the reign of James the First,
no person could be naturalized without taking the oaths of allegiance and supremacy,
and receiving the sacrament of the Lord`'s supper.
See [.book-title]#Blackstone, Vol. I.# 374. Hence we see the reason,
why an act of naturalization was judged necessary to entitle the
Dutch and Swedish inhabitants of the province and territories,
to the full enjoyment of all their civil rights.]

[.numbered]
3+++.+++ The laws agreed upon in England, were, with some alterations and additions,
accepted and confirmed.

====

These laws are understood to have been chiefly the work of William Penn,
and manifest a particular anxiety to preserve the rights of conscience unimpaired,
and to maintain a sound morality in this growing community.

The preamble was in the following words: "`Whereas the glory of God Almighty,
and the good of mankind, is the reason and end of government; and,
therefore government itself, is a valuable ordinance of God;
and forasmuch as it is principally desired and intended by the proprietary and governor,
and freemen of the province of Pennsylvania, and territories thereto belonging,
to make and establish such laws as shall best preserve true Christian and civil liberty,
in opposition to all unchristian, licentious and unjust practices,
whereby God may have his due, Caesar his due, and the people their due,
from tyranny and oppression on the one side,
and insolence and licentiousness on the other;
so that the best and firmest foundation may be laid,
for the present and future happiness of both the governor
and the people of this province and territories aforesaid,
and their posterity; Be it enacted,`" etc.

The first of these laws was to the following import:
"`Almighty God being the Lord of conscience, Father of lights,
and the author as well as object of all Divine knowledge, faith and worship;
who only can enlighten the mind and convince the understanding of people
in due reverence to his sovereignty over the souls of mankind,
be it enacted, that no person now or hereafter residing in this province,
who shall confess one Almighty God, to be the Creator, Upholder, and Ruler of the world,
and profess himself obliged in conscience to live peaceably and justly,
under the civil government,
shall in any wise be molested or prejudiced on account of his conscientious persuasion,
or practice; nor shall he be compelled to frequent or maintain any religious worship,
place or ministry, contrary to his mind,
but shall freely enjoy his liberty in that respect, without interruption or reflection.
And if any person shall abuse or deride another,
for his different persuasion or practice in religion,
such shall be looked upon as disturbers of the peace and be punished accordingly.`"

The officers of the government,
were required to be such as professed faith in Jesus Christ.
Scandalous vices of every description were prohibited,
and provision made for training children to business, to prevent beggary and pauperism.

In the criminal code then established,
a provision was introduced which had previously been but
little regarded in the administration of jurisprudence.
The reformation of the criminals,
as well as deterring others from the commission of crimes,
was viewed as an important object of attention.
Hence the prisons were required to be considered as workshops,
where the offenders might be industriously, soberly and morally employed.

Before the assembly broke up, which they did on the 7th of tenth month,
they returned their grateful acknowledgments to the governor:
the Swedes deputed an individual to assure him, that they would love, serve and obey him,
with all they possessed.

It appears that previous to the meeting of this assembly, William Penn paid a visit,
in part at least of a religious character, to New-York, Long Island, and East Jersey,
of which nothing but a brief notice remains.
Shortly after its dissolution, he repaired to Maryland,
where he was kindly received by Lord Baltimore,
and the principal inhabitants of that colony.
One object of this visit, was to settle with Lord Baltimore,
the boundaries of their respective colonies;
but two days having been spent in the discussion of the subject,
with very little prospect of a speedy adjustment of their adverse claims,
and the winter coming on, they agreed to meet in the ensuing spring.
When he was about returning to Pennsylvania,
Lord Baltimore accompanied him several miles on his way.
From this circumstance we may infer,
that the conference between them was amicably conducted,
and that they parted in a friendly manner.
After taking leave of Lord Baltimore, he proceeded to a meeting of Friends,
which was held at the house of Thomas Hooker, and from there to an appointed one,
at Choptank, on the eastern side of the Chesapeake bay,
which was attended by persons of various ranks and qualities.
Of this visit to Maryland, and the previous one to New-York,
he briefly states in a letter to one of his friends,
that he had had good and eminent service for the Lord.
Thus it appears that amidst the cares of his new political station,
he was sedulously engaged in the exercise of his ministerial gift.

In a letter dated at Chester, on the 29th of tenth month of this year,
he observed that he was much satisfied with his place and portion; yet busy enough,
having much to do to please all;
and yet to have an eye to those who were not there to please themselves.
After mentioning a number of advantages which the place afforded, he added, "`in fine,
here is what an Abraham, Isaac, and Jacob, would be well contented with;
and service enough for God, for the fields are white for harvest.
O! how sweet is the quiet of these parts,
freed from the anxious and troublesome solicitations,
heresies and perplexities of woeful Europe.`"

"`Blessed be the Lord, of twenty-three ships none miscarried;
only two or three had the small pox; else healthy and quick passages,
generally such as had not been known; some but twenty-eight days,
and few longer than six weeks.
Blessed be God for it, who is good to us, and follows with his abundant kindness;
my soul fervently breathes, that in his heavenly guiding wisdom, we may be kept;
that we may serve him in our day and lay down our heads in peace.`"

We have abundant evidence,
that the toils and cares which William Penn encountered in the settlement of Pennsylvania,
and the establishment of the government,
were not submitted to for the gratification of a worldly ambition,
or the promotion of his personal interests;
but that the advancement of the cause of universal righteousness,
and the increase of happiness to the human family,
were the primary and principal objects of these arduous engagements.
The following letter,
addressed to a person who had cast some unkind reflections upon him,
affords a forcible exposition of his motives and labours.

[.embedded-content-document.letter]
--

[.salutation]
My old friend,

I could speak largely of God`'s dealings with me in getting this thing.
What an inward exercise of faith and patience it cost me in passing.
The travail was mine, as well as the debt and cost, through the envy of many,
both professors, false friends and profane.
My God has given it me in the face of the world, and it is to hold it in true judgment,
as a reward of my sufferings, and that is seen here,
whatever some despisers may say or think.
The place God has given me, and I never felt judgment for the power I kept,
but trouble for what I parted with.
It is more than a worldly title or patent,
that has clothed me in this place.--Keep your place: I am in mine,
and have served the God of the whole earth, since I have been in it;
nor am I sitting down in a greatness, that I have denied.
I am day and night spending my life, my time, my money,
and am not six-pence enriched by this greatness, Costs in getting, settling,
transportation, and maintenance, now in a public manner at my own charge duly considered;
to say nothing of my hazard, and the distance I am at from a considerable estate,
and which is more, my dear wife and poor children.

Well,--the Lord is a God of righteous judgment.
Had I sought greatness, I had stayed at home,
where the difference between what I am here and was offered,
and could have been there in power and wealth, is as wide as the places are.
No, I came for the Lord`'s sake, and therefore have I stood to this day,
well and diligent, and successful, blessed be his power.
Nor shall I trouble myself to tell you what I am to the people of this place,
in travails, watchings, spendings, and my servants every way, freely,
(not like a selfish man) I have many witnesses.
To conclude, it is now in Friends`' hands.
Through my travail, faith and patience it came.
If Friends here keep to God, and in the justice, mercy, equity and fear of the Lord,
their enemies will be their footstool.
If not, their heirs and my heirs too will lose all, and desolation will follow;
but blessed be the Lord, we are well and live in the dear love of God,
and the fellowship of his tender heavenly Spirit,
and our faith is for ourselves and one another, that the Lord will be with us a King,
and a Counsellor forever.

[.signed-section-closing]
Your ancient, though grieved friend,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Chester, 5th of the Twelfth month, 1682.

--

In the autumn of this year, but whether previously to his visit to Maryland, or not,
is a little doubtful, was held at Shackamaxon, the celebrated treaty with the Indians.
It is a subject of regret, that so little information which can be entirely relied upon,
in relation to this treaty, now remains.
It is generally agreed, that it was held in the year 1682, under an elm tree,
within the present limits of Kensington.
But no record can now be found, which clearly establishes its date.
The subject has recently claimed the attention of the Pennsylvania Historical Society;
and a committee of their body have given an opinion,
founded on the best testimony within their reach,
that the treaty was held immediately after William
Penn`'s visit to New-York and Long Island,
and consequently before the session of the legislature at Chester.
The circumstances, as well as the date of this treaty, are involved in obscurity.
The records of it appear to have been lost.
The accounts which historians have given of the proceedings and speeches of the governor,
appear to have been chiefly derived from tradition.
It appears probable that it was a treaty of friendship and peace,
and not an agreement for the purchase of land.

At a treaty held at Conestogo, in 1728,
between Governor Gordon and the chiefs of several nations of Indians,
who then resided on the Susquehanna,
the governor addressed the Indians to the following import:

[.embedded-content-document.address]
--

My brethren!
You have been faithful to your leagues with us!
Your leagues with William Penn and his governors are in writing on record,
that our children and our children`'s children may have them in everlasting remembrance.
And we know that you preserve the memory of those things among you,
by telling them to your children, and they again to the next generation;
so that they remain stamped on your minds, never to be forgotten.
The chief heads or strongest links of this chain, I find are these nine, namely:

[.numbered-group]
====

[.numbered]
_1st._ That all William Penn`'s people or Christians,
and all the Indians should be brethren, as the children of one father,
joined together as with one heart, one head, and one body.

[.numbered]
_2nd._ That all paths should be open and free to both Christians and Indians.

[.numbered]
_3rd._ That the doors of the Christians`' houses should be open to the Indians,
and the houses of the Indians open to the Christians,
and that they should make each other welcome as their friends.

[.numbered]
_4th._ That the Christians should not believe any false rumours or reports of the Indians,
nor the Indians believe any such rumours or reports of the Christians,
but should first come as brethren to inquire of each other;
and that both Christians and Indians,
when they have any such false reports of their brethren,
they should bury them as in a bottomless pit.

[.numbered]
_5th._ That if the Christians heard any ill-news, that may be to the hurt of the Indians,
or the Indians hear any such ill-news, that may be to the injury of the Christians,
they should acquaint each other with it speedily, as true friends and brethren.

[.numbered]
_6th._ That the Indians should do no manner of harm to the Christians,
nor to their creatures, nor the Christians do any hurt to the Indians,
but each treat the other as brethren.

[.numbered]
_7th._ But as there are wicked people in all nations,
if either Indians or Christians should do any harm to each other,
complaint should be made of it by the persons suffering, that right might be done,
and when satisfaction is made, the injury or wrong should be forgot,
and be buried as in the bottomless pit.

[.numbered]
_8th._ That the Indians should in all things assist the Christians,
and the Christians assist the Indians against all wicked people that would disturb them.

[.numbered]
_9th._ And lastly,
that both Christians and Indians should acquaint their children
with this league and firm chain of friendship made between them,
and that it should always be made stronger and stronger,
and be kept bright and clean without rust or spot,
between our children and children`'s children while the creeks and rivers run,
and while the sun, moon and stars endure.

====

This is the only authentic account that we possess
of the stipulations of the great treaty,
and we are by no means satisfied with it.
It appears to us to have been mutilated,
as it contains but very general promises of hospitality, kindness and good neighbourhood,
between the Indians and whites;
we do not find in it the engagement mentioned in Mr. Clarkson`'s relation,
and confirmed by the speech of Civility to Governor Keith, nor the answer to the latter,
that the lands should be held in common between the two nations, nor,
as Mr. Clarkson relates,
that the Indians and the whites should have the same liberty
to do all things relating to the improvement of their grounds,
and providing sustenance for their families;
this last covenant is vaguely and obscurely expressed by the second
article '`that all paths should be open and free to both Christians
and Indians.`' This we have no doubt was explained by the founder,
otherwise than by an Indian metaphor,
which in our language may receive any interpretation.
Indeed Governor Gordon does not pretend that the nine articles
contain all the covenants between William Penn and the Indians;
he only says they are the principal ones.
It is much to be regretted that he did not give the whole;
but as he did not choose to do so,
we are obliged to make up the deficiency from other sources,
which we think may be done by taking together these nine articles,
with the conference between Civility +++[+++an Indian chief,]
and Governor Keith, and Mr. Clarkson`'s relation,
from all which we may obtain a pretty correct idea
of the stipulations of the great treaty.

The most important part of the speech of Governor Gordon,
is his acknowledgment that the leagues, as he calls them,
between the governors of Pennsylvania and the Indians, are in writing on record.
What has become of those records?
They are not to be found in the minutes of the Provincial Council at Harrisburg;
yet we know they have existed, and the question recurs, where are they?

It has been suggested, that the last Provincial governors, on leaving Pennsylvania,
have carried with them a great number of valuable records:
we believe this to be a base and unfounded calumny, and the best proof we can give of it,
is that several valuable documents, which,
under the colonial government must have made part of the public archives,
have been found here in private hands,
and there can be no doubt but that much dilapidation did take place,
on the change of government, and at the frequent removals of the state authorities.
It is possible, however, that the proprietary family may have retained some papers,
which they thought interesting only to themselves,
as evidences of the noble conduct and admirable life of their great ancestor:
if such should be the case,
we have no doubt that our venerated friend and philanthropist, Granville Penn, Esq.,^
footnote:[Who is the only surviving grand-son of our illustrious founder.]
will freely communicate those documents to this society,
whose views and feelings he well knows to be congenial with his own.

The point that we have found the most difficult to settle in the course of this investigation,
is the precise date of the great treaty;
and we are by no means certain that we have succeeded in discovering it;
certainly not to a day, or even a week.
We will, however, freely communicate the result of our researches.

The ambiguity of the language of Mr. Proud, of which we have above taken notice,
has induced a general belief that this treaty was made after
the return of William Penn from his visit to Lord Baltimore.
But we have many reasons that induce us to believe
that the treaty was made before that period.
When William Penn came here, he had six objects principally in view,
and to which his first attention was to be directed.
They were--

[.numbered-group]
====

[.numbered]
1+++.+++ To organize his government.

[.numbered]
2+++.+++ To visit his co-religionists on the shores of the Delaware in Pennsylvania and New-Jersey.

[.numbered]
3+++.+++ To conciliate the Indians.

[.numbered]
4+++.+++ To pay his respects to the governor of New-York,
who had had the command over Pennsylvania.

[.numbered]
5+++.+++ To fix upon a proper spot to build his capital city.

[.numbered]
6+++.+++ To visit Lord Baltimore,
with whom he had differences respecting the limits of his province.

====

It is to be remarked, and much to the honour of our great founder,
that if the treaty took place before his journey to Baltimore,
he accomplished all these things in little more than two months; for in January,
he had been at New-York and Maryland; had visited his friends on-the way;
he had organized his government and held an assembly at Chester,
and his city of Philadelphia was located, and buildings begun to be erected upon it.
This is a trait of his character that well deserves to be noticed.

Among those objects,
that of conciliating the Indians was by no means the least important:
and it is not to be presumed that William Penn postponed it to the last.
For, after his return from Maryland, everything else was done that we have mentioned.
He had organized his government at Chester, in December;
he had before that visited New-York and New-Jersey, and on the way, no doubt,
his friends on the Delaware; he had fixed upon the site of his new city,
and had it located and surveyed;
in short all that remained was to treat with the Indians,
and it would have been bad policy in him to have neglected them to the last moment.
We cannot, therefore, suppose that he did so.

Another reason is, that on his return from Maryland, the winter had already set in,
and it was a bad season to hold a treaty in the open air.
If he could have done otherwise, he would not surely have chosen it.
Now, he tells us himself that he met Lord Baltimore at West river,
on the 19th of December.
We learn from other sources, that after a conference of three days,
Lord Baltimore accompanied him on a visit to different parts of Maryland,
and particularly to Choptank, on the other side of the bay,
where there was a meeting of the principal persons in the colony.
All this must have taken time, and we do not find him returned to Chester,
until the 29th of that month,
which we learn by a letter which he wrote from there to a friend under that date.
The treaty, then, according to that supposition, must have been held in January,
too late in the season, we should think, if it could have been done before.
It is true that he describes that winter as pleasant,
when compared with the same season in England.
With that comparison we have nothing to do,
but at the same time he says that it was the coldest winter that
was known in this country within the memory of the oldest settlers,
which must carry us back to a period of at least forty years.
The cold must have been, therefore, very intense,
and the season not very eligible for holding a treaty in the open air,
on the banks of the Delaware, under an elm-tree.

Mr. Gordon, in one of the notes to his History of Pennsylvania, states that the Indians,
at a conference with Governor Keith, in 1722,
exhibited the roll of parchment containing the treaty,
(meaning the great treaty of 1682;) and it would seem, continues he,
that a copy of the conference, at least, held at the making of this treaty,
was once in the office of the secretary of this commonwealth,
since Mr. R. Conyngham assures us that he discovered
an envelope in a bundle of papers there,
relating to the Shawanese Indians, with the following endorsement:
'`Minutes of the Indian Conference in relation to
the great Treaty made with William Penn,
at the Big Tree, Shackamaxon, on the 14th of the tenth month, 1682.`'

We have written to Mr. Conyngham to obtain from him
more particular information upon the subject,
and here is his answer, dated the 12th of March last:

The endorsement on the envelope which you found in page 603,
of Gordon`'s History of Pennsylvania,
is a faithful copy of the original (I believe) at Harrisburg.
I made some inquiry as to the circumstance of its being thus found in the closet,
and received the following information.
Some years since,
the Indian treaties were transcribed in a book for their better preservation,
and this envelope of one of them was carefully folded up,
and placed in the closet with the historical papers.
The Indian treaty said to have been contained in this envelope, is dated June 15th, 1682,
and was the result of a conference held under the elm-tree at Shackamaxon,
between William Markham, the commissioners of William Penn (William Crispin,
John Bezar and Nathaniel Allen) and the Shackamaxine tribes of Indians.
The treaty was in the open air, but signed17 in Captain Lassee Cocke`'s house,
fronting the Delaware, in Shackamaxon.
The land granted was to begin at a white oak, on the ground in the tenure of John Wood,
called by him Grey Stones.^
footnote:[This is the description of the Pennsbury tract,
and therefore must refer to Markham`'s purchase.]
The minutes of the conference in June, and also those of the conference in December,
1682, are not to be found.

From the facts above stated,
Mr. Conyngham has concluded that the great treaty was held on the 14th of December, 1682,
and others have shared in his opinion.
We would not object to that date,
if it was not proved by William Penn himself to be impossible.
In his letter to the lords of plantations above cited,
he tells us that the 19th of December was the day agreed upon between
him and Lord Baltimore for their meeting at West river,
on the western shore of Maryland.
In the same letter, almost in the same breath,
he says--'`The 11th of the month I came to West river, where I met the proprietor,
attended suitably to his character.`' This at first appears contradictory,
but it may be easily reconciled, by supposing that William Penn, who wrote a great deal,
and was not very particular in the selection of his words,
made use of the word came instead of went or set out for,
a grammatical error not uncommon among fast speakers and fast writers.

West river, twelve miles below Annapolis,
lies at a considerable distance from Philadelphia,
and the journey must have been performed by water as well as by land.
It is natural to suppose, that anxious to be at the appointed place on the 19th,
the day agreed upon, and considering the season, the uncertainty of the winds,
the badness of the roads, and all the circumstances that might have impeded his progress,
he chose to set out with his retinue in sufficient time to meet
and overcome all the impediments that he might find on the road,
and a week was not too long a time for that purpose.
If, as he tells us, he left Philadelphia on the 11th,
he must have been on the 14th on his way to Maryland,
and could not have been at Shackamaxon to treat with the Indians.
We must, therefore, reject that date, the envelope notwithstanding.

We then consider ourselves at liberty to fix the epoch of the great treaty,
at such time as we shall think most consistent with probability,
and we believe that to be on his return from New-York, about the latter end of November.
The season was then beautiful, as is generally the fall season in our country.
His journey lasted about a month,
and he had sufficient time to go to New-York and Long Island,
visit his friends on the way in Pennsylvania and New-Jersey,
and treat with the Indians on his return.
On his departure from New-Castle,
his friend Markham had full time to give notice to the chiefs to meet him at Shackamaxon;
in short, by adopting this period,
we find ourselves free from the objections that meet
us at every step in choosing any other.
It is possible that documents may yet be discovered,
which will induce us to alter this opinion;
but until then we do not think that we can offer a better.

As to the Indian tribes that met William Penn, at this famous treaty,
our opinion is that they were those called the River Indians, chiefly if not all,
of the Lenni Lenape or Delaware stock.
To these must be added the Mingoes and other Susquehanna tribes,
who came to solicit his protection; they must have formed, together,
a very respectable assemblage.

Of the ceremonies of the treaty,
we have a full and very satisfactory account by William Penn himself,
in his letter to the free traders,
leaving out only what relates to the purchase of lands.
It is the form in which the Indians hold their most solemn treaties and conferences.
The same is also described by Campanius, and by other writers.

It will be in vain to look for a record of this treaty
and of the stipulations that it contained,
elsewhere than in the minutes of that conference,
if ever they should chance to be discovered.
It is certain that they have existed,
and that they were in the possession of Governor Gordon in 1728,
otherwise he could not have cited from them literally nine articles,
which it is impossible not to believe to have been a part of the great treaty.

But no one must expect ever to see a parchment roll signed and executed by all the parties.
It was not the way in which treaties were made at that time,
or at any time with the Indians.
They could neither read nor write;
they trusted to our records and their own strong retentive memories,
assisted by means peculiar to them.
We regret that we cannot make a more splendid display on this occasion.
We leave that to the painter and to the poet, who, no doubt,
will for a long time hereafter employ their pencil and their pen to this noble theme.
We hope that the memory of the great treaty, and of our illustrious founder,
will remain engraved on the memory of our children
and our children`'s children to the end of time.

--

This imperfect account of the great treaty, the best now upon record,
serves to show that the conditions were faithfully observed by the Indians.
It also indicates that a record of it was then in existence.
It was mentioned about the middle of last century, by Voltaire,
as the only treaty that had been made between the Indians and Christians,
which was not ratified by an oath; and was never infringed.
This relationship thus begun with the native inhabitants of the country,
and the extraordinary kindness uniformly manifested towards them,
produced in their minds a feeling of uncommon veneration for him,
and secured the peace of the province during the life of William Penn,
and for several years after his death.
The peaceable manner in which the first settlement of Pennsylvania was effected,
and the friendship established and maintained with the native inhabitants,
as long as the principles of William Penn and his coadjutors
were permitted to govern the councils of the province,
may be fairly considered as having settled the question whether the interaction
between nations could be carried on without the aid of military force.
The people among whom the first settlers in Pennsylvania erected their peaceful habitations,
were inured to the chase, an occupation more nearly allied, than any other, to war,
and they were not only destitute of the arts of civilized life,
but ignorant of the principles and doctrines of Christianity.

If the strict observance of justice, and a conduct uniformly pacific,
could preserve the relations of friendship and peace with such a people,
it is a libel on the religion which we profess,
to deny that the same relations might be maintained among Christians, by similar means.
And when we observe the rapid advances of Pennsylvania in population and wealth,
we must admit that the experiment of William Penn has sufficiently
proved the superiority of the pacific policy,
when viewed as a question of political expediency, above that usually adopted.

It is true, that William Penn was not the only one, nor the first,
who obtained possession of the Indian lands by purchase.
The example had been set in Massachusetts, New-York, Maryland, New-Jersey,
and by the Dutch, Swedes and Fins, on the Delaware.
It does not, however, appear, that in any other colony,
was so favourable and permanent an impression made, upon the original inhabitants,
as in Pennsylvania.
And it is not unreasonable to suppose,
that if William Penn could have seen his way clear to settle
himself and his family permanently in Pennsylvania,
at the time of his first visit; to have superintended in person,
the interactions between the new settlers and the native inhabitants,
and to have added the influence of his character and religious weight,
to the efforts which were made to enlighten the minds
and improve the condition of these people,
that the soil of Pennsylvania, might, at this day,
have contained no inconsiderable number of its native occupants,
enjoying the comforts of civilized life, and the benefits of the Christian religion.
It is cause of poignant regret, that the settlement of the Europeans in their vicinity,
instead of extending the benefits of civilization and Christianity,
among the untutored inhabitants of the wilderness,
should be the signal for their extinction.
Even in Pennsylvania, notwithstanding the prohibitory laws of the founder,
the sale of spirituous liquors to the Indians, was prosecuted to a considerable extent,
and was attended with its usual deteriorating consequences.^
footnote:[The most formidable evil visited upon the Indians,
and flowing from their connection with the Europeans,
was the introduction of ardent spirits.
That
terrible agent did not fail to ensnare the unreflecting Indian,
and feeding the fierce passions of his unsubdued nature, fitted him for every atrocity,
and made him the prey of every evil artifice.
The indulgence in the use of inebriating draughts, had, moreover,
the effect to introduce physical maladies before unknown among them,
and to subject them to outrage and wrong in the disposal of their lands and commodities;
in short,
that liquid fire threatened with swift destruction to sweep them from the face of the
earth.
{footnote-paragraph-split}
To protect the natives from these fearful consequences,
the wise and virtuous lawgiver of Pennsylvania saw, on his arrival,
the necessity of interposing his authority to correct mischiefs
which had existed antecedent to his possession of the province;
he therefore, in 1682, declared and enacted, that, "`Whereas, various persons,
as English, Dutch, Swedes, etc., have been known to sell to the Indians, rum and brandy,
and such like distilled spirits,
though they know the said Indians are notable to govern themselves in the use thereof,
but do commonly drink of it to such excess as makes themselves destroy one another,
and grievously annoy and disquiet the people of this province, and peradventure,
those of neighbouring governments, whereby they may make the poor natives worse,
and not better, for coming among them, which is a heinous offence to God,
and a reproach to the blessed name of Christ and his holy religion; it is, therefore,
enacted, that no person within this province,
do henceforth presume to sell or exchange any rum or brandy, or any other liquors,
at any time, to any Indian within this province; and if anyone shall offend therein,
the person so convicted, shall, for every such offence,
pay five pounds.`"
The same subject
claimed the attention of the Yearly Meeting of Friends,
in 1685, and 1687, and advice correspondent with the efforts of the proprietary,
were issued to the members of that Society.]

One of the objects of attention with William Penn, before the end of the year 1682,
was to lay out the principal town of the province.
The situation chosen for this purpose, was remarkably favourable.
The name assigned to this new capital of the province,
was expressive of the principles of its founder.
The Indian name of the place where that city now stands was Coaquannock.

So favourable an opinion was entertained of the country assigned to William Penn,
and of the character of its proprietor,
that within little more than a year after the arrangements were made for settling it,
between twenty and thirty vessels arrived with emigrants, amounting collectively,
to more than two thousand individuals.
A large part of these, were members of the religious Society of Friends.
They had left their own country, to avoid the vexations and vices of Europe,
that they might lead quiet and peaceable lives,
and worship God according to their conscientious persuasion.
The diffusion of the doctrines of Christianity among the ancient inhabitants of the land,
appears to have been one of the objects in view,
with these early settlers in Pennsylvania.
Though these emigrants were not generally rich,
yet many of them possessed considerable estates, and were persons of good education.
They were mostly sober, industrious people, of reputable characters,
well qualified to advance the interests of this rising colony.
As they arrived in succession,
they were kindly received and assisted by those who were there before them;
and scattering along the Delaware, as choice or convenience suggested,
the country was thinly peopled from the falls, at Trenton, to Chester.
The inhabitants, including the Dutch and Swedes,
who had been long resident in the country,
are computed at the time to which we have arrived, to be about four thousand;
so that William Penn may be said to have raised up a colony at once, in his new domains.

It may be readily conjectured, that the establishment of meetings for Divine worship,
and the preservation of order,
would early occupy the attention of the settlers in Pennsylvania.
We accordingly find, that before the arrival of William Penn,
a meeting of Friends was held at Shackamaxon, and that in 1682,
a meeting was held in a frame house erected for the purpose,
within the present limits of Philadelphia.^
footnote:[A brick meetinghouse, near the centre of the city, was built in 1684.
That on the bank, in Front Street, called the Bank Meetinghouse, was built in 1685.
The great meetinghouse in High Street, in 1695.
These are all that were erected in the city, during the life of William Penn;
but there were eighteen meetings of Friends in the province, as early as 1684.]
A meeting of the Society appears to have been held at Uplands, Chester,
several years before the arrival of William Penn, and at that place a meeting of record,
probably the first in the province, was held as early as 1681.
A meeting was settled at Darby, in 1682.

In the course of the year 1682, and the two following ones,
great numbers of emigrants arrived from England, Ireland, Wales, Holland and Germany,
who extended their settlements into the interior of the country.
The Welsh settled on both sides of the Schuylkill,
and have left in the names of the townships, Merion, Haverford, Radnor, Tredyffin,
Gwynedd, etc., a lasting memorial of their original locations.
Among the emigrants from Germany, were a number of Friends,
formerly inhabitants of Crisheim in the Palatinate,
among whom William Penn had travelled in the service of the Gospel during the year 1677.
They formed the flourishing settlement of Germantown;
and by their opportune removal to the asylum which was provided for them,
escaped the calamity which a few years afterward overtook their native land,
when Louis XIV., in the wantonness of power,
desolated the Palatinate with fire and sword.

During the year 1683,
William Penn appears to have been occupied with the secular concerns of the province.
A session of the legislature was held at Philadelphia,
the members being chosen as representatives of the freemen and acting on their behalf.
A new charter was granted to the inhabitants by the proprietary.
Very considerable progress was made in the building of the new city,
so that by the end of the year, no fewer than a hundred houses had made their appearance.
The land in the vicinity was in places cleared and brought into cultivation;
and the grains of Europe were beginning to flourish on the virgin soil of Pennsylvania.
A letter written a number of years afterwards, by one of the companions of William Penn,
describing the situation of the colony at this time,
is deemed on account of its native and beautiful simplicity,
not unworthy a place in these memoirs.

[.embedded-content-document.letter]
--

After our arrival, +++[+++says he,]
we found it a wilderness.
The chief inhabitants were Indians and some Swedes, who received us in a friendly manner;
and though there was a great number of us,
the good hand of Providence was seen in a particular manner,
in that provisions were found for us by the Swedes and Indians at very reasonable rates,
as well as brought from various other parts that were inhabited before.

After some time I set up a mill on Chester creek,
which I brought ready framed from London,
which served for grinding of corn and sawing of boards, and was of great use to us.
Besides, with Joshua Tittery, I made a net, and caught great quantities of fish,
which supplied ourselves and many others; so that,
notwithstanding it was thought near three thousand persons came in the first year,
we were so providentially provided for, that we could buy a deer for about two shillings,
and a large turkey for about a shilling,
and Indian corn for about two shillings and sixpence per bushel.

And as our worthy proprietor treated the Indians with extraordinary humanity,
they became very civil and loving to us, and brought us in abundance of venison.
As in other countries the Indians were exasperated by hard treatment,
which has been the foundation of much bloodshed,
so the contrary treatment here has produced their love and affection.

After our arrival there came in about twenty families
from High and Low Germany of religious good people,
who settled about six miles from Philadelphia, and called the place Germantown.
About the time when Germantown was laid out, I settled upon my tract of land,
which I had bought of the proprietor in England, about a mile from there,
where I set up a house and corn-mill,
which was very useful to the country for several miles round;
but there not being plenty of horses,
people generally brought their corn on their backs many miles.
I remember one man had a bull so gentle,
that he used to bring his corn on him instead of a horse.

Being now settled within six or seven miles of Philadelphia,
where I left the principal body of Friends together with the chief place of provisions,
flesh meat was very scarce with me for some time, of which I felt the lack.
I remember I was once supplied by a particular instance
of Providence in the following manner:

As I was in my meadow mowing grass, a young deer came and looked on me.
I continued mowing, and the deer in the same attention to me.
I then laid down my scythe and went towards him; upon which he ran off a small distance.
I went to my work again, and the deer continued looking on me;
so that several times I left my work to go towards him:
but he still kept himself at a distance.

At last, as I was going towards him, and he looking on me did not mind his steps,
he ran forcibly against the trunk of a tree, and stunned himself so much that he fell;
upon which I ran forward, and getting upon him held him by the legs.
After a great struggle, in which I had almost tired him out, and rendered him lifeless,
I threw him on my shoulders, holding him fast by the legs, and with some difficulty,
on account of his fresh struggling, carried him home, about a quarter of a mile,
to my house; where, by the assistance of a neighbour, who happened to be there,
and who killed him for me, he proved very serviceable to my family.
I could relate several other acts of Providence of this kind, but omit them for brevity.

As people began to spread, and to improve their lands, the country became more fruitful,
so that those who came after us were plentifully supplied;
and with what we abounded we began a small trade abroad; and as Philadelphia increased,
vessels were built, and many employed.
Both country and trade have been wonderfully increasing to this day; so that,
from a wilderness, the Lord, by his good hand of providence, has made it a fruitful land;
on which things to look back and observe all the steps, would exceed my present purpose.
Yet, being now in the eighty-fourth year of my age,
and having been in this country near forty-six years,
and my memory being pretty clear concerning the rise and progress of the province,
I can do no less than return praises to the Almighty,
when I look back and consider his bountiful hand, not only in temporals,
but in the great increase of our religious meetings,
wherein he has many times manifested his great lovingkindness in
reaching and convincing many persons of the principles of Truth:
and those who were already convinced, and who continued faithful,
were not only blessed with plenty of the fruits of the earth,
but also with the dew of heaven.

--

In the sixth month of this year,
William Penn wrote a letter to the Free Society of
Traders of Pennsylvania residing in London;
in which he gave an account of the settlements,
and such a description of the character of the Indians,
and the natural productions of the province as he was able to collect
from personal observation or the information of others.
Of this interesting communication, the following portion may suffice.

[.asterism]
'''

[.embedded-content-document.letter]
--

[.blurb]
=== For the province, the general condition of it take as follows:

[.numbered-group]
====

[.numbered]
I+++.+++ The country itself in its soil, air, water, seasons and produce,
both natural and artificial, is not to be despised.
The land contains various sorts of earth, as sand, yellow and black, poor and rich.
Also gravel both loomy and dusty; and in some places, a fast fat earth,
like to our best vales in England, especially by inland brooks and rivers;
God in his wisdom having ordered it so, that the advantages of the country are divided,
the back lands being generally three to one richer
than those that lie by navigable waters.
We have much of another soil, and that is a black hasel-mould,
upon a stony or rocky bottom.

[.numbered]
II. The air is sweet and clear, the heavens serene like the south parts of France,
rarely overcast; and as the woods come by numbers of people to be more cleared,
that itself will refine.

[.numbered]
III.
The waters are generally good,
for the rivers and brooks have mostly gravel and stony bottoms,
and in number hardly credible.
We have also mineral waters, that operate in the same manner with Barnet and North-Hall,
not two miles from Philadelphia.

[.numbered]
IV. For the seasons of the year,
having by God`'s goodness now lived over the coldest and hottest,
that the oldest liver in the province can remember,
I can say something to an English understanding.

First, Of the fall, for then I came in: I found it from the 24th of October,
to the beginning of December, as we have it usually in England in September,
or rather like an English mild spring.
From December, to the beginning of the month called March, we had sharp frosty weather;
not foul, thick, black weather, as our north-east winds bring with them in England;
but a sky as clear as in summer, and the air dry, cold, piercing and hungry;
yet I remember not that I wore more clothes than in England.
The reason of this cold is given,
from the great lakes that are fed by the fountains of Canada.
The winter before was as mild, scarcely any ice at all; while this, for a few days,
froze up our great river Delaware.
From that month, to the month called June, we enjoyed a sweet spring, no gusts,
but gentle showers, and a fine sky.
Yet this I observe, that the winds here, as there, are more inconstant spring and fall,
upon that turn of nature, than in summer or winter.
From there, to this present month, which ends the summer,
(commonly speaking) we have had extraordinary heats,
yet mitigated sometimes by cool breezes.
The wind that rules the summer season, is the south-west; but spring, fall and winter,
it is rare to go without the wholesome north-western seven days together.
And whatever mists, fogs or vapours, foul the heavens by easterly or southerly winds,
in two hours time are blown away; the one is followed by the other.
A remedy that seems to have a peculiar providence in it to the inhabitants;
the multitude of trees yet standing, being liable to retain mists and vapours,
and yet not one quarter so thick as I expected.

[.numbered]
V+++.+++ The natural produce of the country, of vegetables, is trees, fruits, plants, flowers.
The trees of most note, are the black walnut, cedar, cyprus, chesnut, poplar, gumwood,
hickory, sassafras, ash, beech and oak of various sorts, as red, white and black,
Spanish, chesnut and swamp, the most durable of all.
Of all which, there is plenty for the use of man.

The fruits that I find in the woods, are the white and black mulberry, chesnut, walnut,
plumbs, strawberries, cranberries, hurtleberries and grapes of various sorts.
The great red grape (now ripe) called by ignorance, the fox-grape,
because of the relish it has with unskilful palates, is in itself an extraordinary grape,
and by art, doubtless may be cultivated to an excellent wine, if not so sweet,
yet little inferior to the Frontiniac, as it is not much unlike in taste,
ruddiness set aside, which in such things, as well as mankind, differs the case much.
There is a white kind of Muscatel, and a little black grape,
like the cluster grape of England, not yet so ripe as the other; but they tell me,
when ripe, sweeter, and that they only lack skilful vinerons to make good use of them.
I intend to venture on it with my Frenchman this season,
who shows some knowledge in those things.
Here are also peaches, and very good, and in great quantities,
not an Indian plantation without them; but whether naturally here at first, I know not,
however, one may have them by bushels for little; they make a pleasant drink,
and I think not inferior to any peach you have in England, except the true Newington.
It is disputable with me, whether it be best to fall to fining the fruits of the country,
especially the grape, by the care and skill of art, or send for foreign stems and sets,
already good and approved.
It seems most reasonable to believe, that not only a thing grows best,
where it naturally grows,
but will hardly be equalled by another species of the same kind,
that does not naturally grow there.
But to solve the doubt, I intend, if God give me life, to try both,
and hope the consequence will be as good wine,
as any European countries of the same latitude yield.

[.numbered]
VI.^
footnote:[Note.
That Edward Jones, son-in-law to Thomas Wynn, living`' on the Schuylkill,
had with ordinary cultivation, for one grain of English barley,
seventy stalks and ears of barley.
And it is common in this country, from one bushel sown, to reap forty, often fifty,
and sometimes sixty.
And three pecks of wheat sows an acre here.]
The artificial produce of the country, is wheat, barley, oats, rye, peas, beans,
squashes, pumpkins, water-melons, muskmelons,
and all herbs and roots that our gardens in England usually bring forth.

[.numbered]
VII.
Of living creatures, fish, fowl and the beasts of the woods; here are various sorts,
some for food and profit, and some for profit only.
For food as well as profit, the elk, as big as a small ox, deer, bigger than ours,
beaver, raccoon, rabbits, squirrels, and some eat young bear, and commend it.
Of fowl of the land, there is the turkey, forty and fifty pounds weight,
which is very great; pheasants, heath birds, pigeons and partridges in abundance.
Of the water, the swan, goose, white and gray; brands, duck, teal,
also the snipe and curlew, and in great numbers; but the duck and leal excel,
nor so good have I ever eaten in other countries.
Of fish, there is the sturgeon, herring, rock, shad, cat`'s-head, sheep`'shead, eel,
smelt, perch, roach; and in inland rivers, trout, some say, salmon, above falls.
Of shell-fish, we have oysters, crabs, cockles, conchs and muscles;
some oysters six inches long; and one sort of cockles as big as the stewing-oysters,
they make a rich broth.
The creatures for profit only, by skin or fur, and that are natural to these parts,
are the wild-cat, panther, otter, wolf, fox, fisher, mink, musk-rat.
And of the water, the whale for oil, of which we have good store,
and two companies of whalers, whose boats are built, will soon begin their work,
which has the appearance of a considerable improvement.
To say nothing of our reasonable hopes of good cod in the bay.

[.numbered]
VIII.
We have no lack of horses, and some are very good and shapely enough;
two ships have been freighted to Barbados with horses and pipe-staves,
since my coming in.
Here is also plenty of cow-cattle, and some sheep; the people plough mostly with oxen.

[.numbered]
IX. There are diverse plants, that not only the Indians tell us,
but we have had occasion to prove by swellings, burnings, cuts, etc.,
that they are of great virtue, suddenly curing the patient.
And for smell, I have observed several, especially one, the wild myrtle;
the others I know not what to call, but are most fragrant.

[.numbered]
X+++.+++ The woods are adorned with lovely flowers, for colour, greatness, figure and variety.
I have seen the gardens of London best stored with that sort of beauty,
but think they may be improved by our woods.
I have sent a few to a person of quality this year for a trial.
Thus much of the country, next of the natives, or aborigines.

[.numbered]
XI. The natives I shall consider in their persons, language, manners,
religion and government, with my sense of their original.
For their persons, they are generally tall, straight,
well-built and of singular proportion; they tread strong and clever,
and mostly walk with a lofty chin.
Of complexion, black, but by design, as the gypsies in England.
They grease themselves with bear`'s fat clarified,
and using no defence against sun or weather, their skins must needs be swarthy.
Their eye is little and black, not unlike a straight-looked Jew.
The thick lip and flat nose, so frequent with the East Indians and blacks,
are not common to them; for I have seen as comely European-like faces among them of both,
as on your side the sea; and truly an Italian complexion has not much more of the white,
and the noses of several of them have as much of the Roman.

[.numbered]
XII.
Their language is lofty, yet narrow, but like the Hebrew; in signification full,
like short-hand in writing; one word serves in the place of three,
and the rest are supplied by the understanding of the hearer.
Imperfect in their tenses, lacking in their moods, participles, adverbs, conjunctions,
interjections.
I have made it my business to understand it,
that I might not require an interpreter on any occasion.
And I must say, that I know not a language spoken in Europe,
that has words of more sweetness or greatness, in accent and emphasis, than theirs.
For instance, Octocockon, Rancocas, Oricton, Shah, Marian, Poquesien,
all which are names of places and have grandeur in them.
Of words of sweetness, Anna, is mother, Issimus, a brother, Netcap, friend, Usque Oret,
very good, Pane, bread, Metse, eat, Matta, no, Hatta, to have, Payo, to come; Sepassen,
Passijon, the names of places Tamane, Secane, Menanse, Secatereus,
are the names of persons.
If one ask them for anything they have not, they will answer, Mattd ne Hattd,
which to translate is, not I have, instead of I have not.

[.numbered]
XIII.
Of their customs and manners, there is much to be said, I will begin with children.
The children will go very young, at nine months commonly; if boys,
they go a fishing till ripe for the woods, which is about fifteen; then they hunt,
and after having given some proofs of their manhood, by a good return of skins,
they may marry, else it is a shame to think of a wife.
The girls stay with their mothers, and help to hoe the ground,
plant corn and carry burdens; and they do well to use them to that while young,
which they must do when they are old;
for the wives are the true servants of the husbands;
otherwise the men are very affectionate to them.

[.numbered]
XIV.
When the young women are fit for marriage,
they wear something upon their heads for an advertisement,
but so as their faces are hardly to be seen, but when they please.
The age they marry at, if women, is about thirteen and fourteen, if men,
seventeen and eighteen; they are rarely older.

[.numbered]
XV. Their houses are mats, or barks of trees, set on poles,
in the fashion of an English barn, but out of the power of the winds,
for they are hardly higher than a man; they lie on reeds or grass.
In travel, they lodge in the woods about a great fire,
with the mantle of Dussills they wear by day, wrapt about them,
and a few boughs stuck round them.

[.numbered]
XVI.
Their diet is maize, or Indian corn, several ways prepared;
sometimes roasted in the ashes, sometimes beaten and boiled with water,
which they call hominy; they also make cakes, not unpleasant to eat.
They have likewise several sorts of beans and peas, that are good nourishment;
and the woods and rivers are their larder.

[.numbered]
XVII.
If a European comes to see them, or calls for lodging at their house or wigwam,
they give him the best place and first cut.
If they come to visit us, they salute us with an Itah, which is as much as to say,
Good be to you, and set them down, which is mostly on the ground, close to their heels,
their legs upright; it may be they speak not a word, but observe all passages.
If you give them anything to eat or drink, well, for they will not ask;
and be it little or much, if it be with kindness, they are well pleased,
else they go away sullen, but say nothing.

[.numbered]
XVIII.
They are great concealers of their own resentments, brought to it, I believe,
by the revenge that has been practised among them; in either of these,
they are not exceeded by the Italians.
A tragical instance fell out since I came into the country.
A king`'s daughter, thinking herself slighted by her husband, in allowing another woman,
rose up, went out, plucked a root out of the ground and eat it,
upon which she immediately died; and for which, last week,
he made an offering to her kindred, for atonement and liberty of marriage;
as two others did to the kindred of their wives, who died a natural death.
For till widowers have done so, they must not marry again.

[.numbered]
XIX.
In liberality they excel, nothing is too good for their friend; give them a fine gun,
coat or other thing, it may pass twenty hands before it sticks; light of heart,
strong affections, but soon spent; the most merry creatures that live,
feast and dance perpetually; they never have much, nor lack much.
Wealth circulates like the blood, all parts partake;
and though none shall go without what another has, yet exact observers of property.
Some kings have sold, others presented me with several parcels of land;
the pay or presents I made them, were not hoarded by the particular owners,
but the neighbouring kings and their clans being present when the goods were brought out,
the parties chiefly concerned, consulted what, and to whom, they should give them.
To every king then, by the hands of a person for that work appointed,
is a proportion sent, so sorted and folded, and with that gravity, that is admirable.
Then the king sub-divides it in like manner among his dependents,
they hardly leaving themselves an equal share with one of their subjects.
And be it on such occasions as festivals, or at their common meals, the kings distribute,
and to themselves last.
They care for little, because they need but little, and the reason is,
a little contents them.
In this they are sufficiently revenged on us; if they are ignorant of our pleasures,
they are also free from our pains.
They are not disquieted with bills of lading and exchange,
nor perplexed with chancery-suits and exchequer-reckonings.
We sweat and toil to live; their pleasure feeds them; I mean their hunting,
fishing and fowling, and this table is spread everywhere.
They eat twice a day, morning and evening; their seats and table are the ground.
Since the Europeans came into these parts, they are grown great lovers of strong liquors,
rum especially; and for it exchange the richest of their skins and furs.
If they are heated with liquors, they are restless till they have enough to sleep;
that is their cry, Some more, and I will go to sleep; but when drunk,
one of the most wretched spectacles in the world.

[.numbered]
XX. In sickness, impatient to be cured, and for it give anything,
especially for their children, to whom they are extremely natural.
They drink at those times, a decoction of some roots in spring-water;
and if they eat any flesh, it must be of the female of any creature.
If they die, they bury them with their apparel, be they man or woman,
and the nearest of kin fling in something precious with them, as a token of their love.
Their mourning is blacking of their faces, which they continue for a year.
They are choice of the graves of their dead; for lest they should be lost by time,
and fall to common use, they pick off the grass that grows upon them,
and heap up the fallen earth with great care and exactness.

[.numbered]
XXI.
These poor people are under a dark night in things relating to religion, to be sure,
the tradition of it; yet they believe in a God and immortality,
without the help of metaphysics; for they say, There is a great King that made them,
who dwells in a glorious country to the southward of them,
and that the souls of the good shall go there, where they shall live again.
Their worship consists of two parts, sacrifice and cantico.
Their sacrifice is their first fruits; the first and fattest buck they kill,
goes to the fire, where he is burnt,
with a mournful ditty of him that performs the ceremony,
but with such marvellous fervency and labour of body, that he will even sweat to a foam.
The other part is their cantico, performed by round-dances, sometimes words,
sometimes songs, then shouts, two being in the middle that begin,
and by singing and drumming on a board, direct the chorus.
Their postures in the dance are very antic and differing, but all keep measure.
This is done with equal earnestness and labour, but great appearance of joy.
In the fall, when the corn comes in, they begin to feast one another;
there have been two great festivals already, to which all come that will.
I was at one myself; their entertainment was a great seat by a spring,
under some shady trees, and twenty bucks, with hot cakes of new corn,
both wheat and beans, which they make up in a square form, in the leaves of the stem,
and bake them in the ashes; and after that they fell to dance.
But they that go, must carry a small present in their money, it may be six-pence,
which is made of the bone of a fish; the black is with them as gold, the white, silver;
they call it all wampum.

[.numbered]
XXII.
Their government is by kings, whom they call Sachems, and those by succession,
but always of the mother`'s side.
For instance, the children of him that is now king, will not succeed,
but his brother by the mother, or the children of his sister, whose sons,
and after them the children of her daughters will reign; for no woman inherits;
the reason they render for this way of descent is, that their offspring may not be spurious.

[.numbered]
XXIII.
Every king has his council, and that consists of all the old and wise men of his nation,
which perhaps is two hundred people.
Nothing of importance is undertaken, be it war, peace, selling of land or traffic,
without advising with them; and which is more, with the young men too.
It is admirable to consider, how powerful the kings are,
and yet how they move by the breath of their people.
I have had occasion to be in council with them upon treaties for land,
and to adjust the terms of trade; their order is thus:
the king sits in the middle of a half moon, and has his council,
the old and wise on each hand: behind them, or at a little distance, sit the younger fry,
in the same figure.
Having consulted and resolved their business,
the king ordered one of them to speak to me; he stood up, came to me,
and in the name of his king saluted me, then took me by the hand, and told me,
he was ordered by his king to speak to me, and that now it was not he,
but the king that spoke, because what he should say, was the king`'s mind.
He first prayed me, to excuse them that they had not complied with me the last time;
he feared there might be some fault in the interpreter, being neither Indian nor English;
besides, it was the Indian custom to deliberate, and take up much time in council,
before they resolve;
and that if the young people and owners of land had been as ready as he,
I had not met with so much delay.
Having thus introduced his matter,
he fell to the bounds of the land they had agreed to dispose of, and the price,
which now is little and dear, that which would have bought twenty miles,
now not buying two.
During the time that this person spoke,
not a man of them was observed to whisper or smile; the old, grave, the young,
reverend in their deportment; they speak little, but fervently, and with elegancy.
I have never seen more natural sagacity, considering them without the help,
I was going to say, the spoil, of tradition; and he will deserve the name of wise,
that out-wits them in any treaty about a thing they understand.
When the purchase was agreed,
great promises past between us of kindness and good neighbourhood,
and that the Indians and English must live in love, as long as the sun gave light.
Which done, another made a speech to the Indians,
in the name of all the sachamakers or kings, first, to tell them what was done;
next to charge and command them, to love the Christians,
and particularly live in peace with me and the people under my government.
That many governors had been in the river,
but that no governor had come himself to live and stay here before;
and having now such a one that had treated them well,
they should never do him or his any wrong.
At every sentence of which they shouted, and said, Amen, in their way.

[.numbered]
XXIV.
The justice they have is pecuniary.
In case of any wrong or evil fact, be it murder itself,
they atone by feasts and presents of their wampum,
which is proportioned to the quality of the offence or person injured,
or of the sex they are of.
For in case they kill a woman, they pay double, and the reason they render, is,
that she breeds children, which men cannot do.
It is rare that they fall out, if sober; and if drunk, they forgive it, saying,
It was the drink, and not the man, that abused them.

[.numbered]
XXV.
We have agreed, that in all differences between us, six of each side shall end the matter.
Do not abuse them, but let them have justice, and you win them.
The worst is, that they are the worse for the Christians,
who have propagated their vices, and yielded them tradition for ill,
and not for good things.
But as low an ebb as these people are at, and as glorious as their own condition looks,
the Christians have not out-lived their sight,
with all their pretensions to a higher manifestation.
What good then might not a good people graft,
where there is so distinct a knowledge left between good and evil?
I beseech God to incline the hearts of all that come into these parts,
to out-live the knowledge of the natives,
by a fixed obedience to their greater knowledge of the will of God;
for it were miserable indeed for us to fall under
the just censure of the poor Indian conscience,
while we make profession of things so far transcending.

[.numbered]
XXVI.
For their origin, I am ready to believe them of the Jewish race, I mean,
of the stock of the Ten Tribes, and that for the following reasons; first,
They were to go to a land not planted or known, which to be sure Asia and Africa were,
if not Europe; and he that intended that extraordinary judgment upon them,
might make the passage not uneasy to them, as it is not impossible in itself,
from the easternmost parts of Asia, to the westernmost of America.
In the next place, I find them of the like countenance,
and their children of so lively resemblance,
that a man would think himself in Duke`'s-place or Berrystreet in London,
when he sees them.
But this is not all; they agree in rites, they reckon by moons;
they offer their first fruits, they have a kind of feast of tabernacles;
they are said to lay their altar upon twelve stones; their mourning a year,
customs of women, with many things that do not now occur.
So much for the natives, next the old planters will be considered in this relation,
before I come to our colony, and the concerns of it.

[.numbered]
XXVII.
The first planters in these parts were the Dutch,
and soon after them the Swedes and Finns.
The Dutch applied themselves to traffic, the Swedes and Finns to husbandry.
There were some disputes between them some years,
the Dutch looking upon them as intruders upon their purchase and possession,
which was finally ended in the surrender made by John Rizeing, the Swedish governor,
to Peter Styvesant, governor for the states of Holland, Anno 1655.

[.numbered]
XXVIII.
The Dutch inhabit mostly those parts of the province, that lie upon or near to the bay,
and the Swedes the freshes of the river Delaware.
There is no need of giving any description of them, who are better known there than here;
but they are a plain, strong, industrious people,
yet have made no great progress in culture or propagation of fruit-trees,
as if they desired rather to have enough, than plenty or traffic.
But I presume, the Indians made them the more careless,
by furnishing them with the means of profit, namely, skins and furs,
for rum and such strong liquors.
They kindly received me, as well as the English, who were few,
before the people concerned with me came among them.
I must needs commend their respect to authority and kind behaviour to the English;
they do not degenerate from the old friendship between both kingdoms.
As they are people proper and strong of body, so they have fine children,
and almost every house full; rare to find one of them without three or four boys,
and as many girls; some six, seven and eight sons.
And I must do them that right, I see few young men more sober and laborious.

[.numbered]
XXIX.
The Dutch have a meeting-place for religious worship at New-Castle, and the Swedes,
three, one at Christiana, one at Tenecum, and one at Wicoco,
within half a mile of this town.

[.numbered]
XXX.
There rests, that I speak of the condition we are in, and what settlement we have made,
in which I will be as short as I can; for I fear, and not without reason,
that I have tried your patience with this long story.
The country lies bounded on the east,
by the river and bay of Delaware and Eastern sea it has the advantage of many creeks,
or rivers rather, that run into the main river or bay; some navigable for great ships,
some for small craft.
Those of most eminency, are Christiana, Brandywine, Skilpot and Schuylkill;
any one of which has room to lay up the royal navy of England,
there being from four to eight fathom water.

[.numbered]
XXXI.
The lesser creeks or rivers, yet convenient for sloops and ketches of good burden,
are Lewis, Mespilion, Cedar, Dover, Cranbrook, Feversham, and Georges below,
and Chichester, Chester, Toacawny, Pemmapecka, Poquessin,
Neshimenck and Pennbury in the freshes; many lesser that admit boats and shallops.
Our people are mostly settled upon the upper rivers, which are pleasant and sweet,
and generally bounded with good land.
The planted part of the province and territories is cast into six counties, Philadelphia,
Buckingham, Chester, New-Castle, Kent and Sussex, containing about four thousand souls.
Two general assemblies have been held, and with such concord and dispatch,
that they sate but about three weeks,
and at least seventy laws were passed without one dissent in any material thing.
But of this more hereafter, being yet raw and new in gear.
However, I cannot forget their singular respect to me in this infancy of things,
who by their own private expenses so early considered mine for the public,
as to present me with an impost upon certain goods imported and exported.
Which, after my acknowledgments of their affection,
I did as freely remit to the province and the traders to it.
And for the well government of the said counties,
courts of justice are established in every county, with proper officers, as justices,
sheriffs, clerks, constables, etc., which courts are held every two months.
But to prevent law-suits, there are three peacemakers chosen by every county-court,
in the nature of common arbitrators, to hear and end differences between man and man;
and spring and fall there is an orphans`' court in each county,
to inspect and regulate the affairs of orphans and widows.

[.numbered]
XXXII.
Philadelphia, the expectation of those that are concerned in this province,
is at last laid out, to the great content of those here,
who are anyways interested therein.
The situation is a neck of land, and lies between two navigable rivers,
Delaware and Schuylkill, whereby it has two fronts upon the water, each a mile,
and two from river to river.
Delaware is a glorious river,
but the Schuylkill being a hundred miles boatable above the falls,
and its course north-east toward the fountain of Susquehanna,
(that tends to the heart of the province,
and both sides our own) it is like to be a great part of the settlement of this age.
I say little of the town itself, because a plat-form will be shown you by my agent,
in which those who are purchasers of me, will find their names and interests.
But this I will say for the good providence of God,
that of all the many places I have seen in the world, I remember not one better seated;
so that it seems to me to have been appointed for a town, whether we regard the rivers,
or the conveniency of the coves, docks, springs,
the loftiness and soundness of the land and the air,
held by the people of these parts to be very good.
It is advanced within less than a year to about four-score houses and cottages,
such as they are,
where merchants and handicrafts are following their vocations as fast as they can,
while the country-men are close at their farms.
Some of them got a little winter corn in the ground last season,
and the generality have had a handsome summer crop,
and are preparing for their winter corn.
They reaped their barley this year in the month called May;
the wheat in the month following;
so that there is time in these parts for another
crop of various things before the winter season.
We are daily in hopes of shipping to add to our number; for blessed be God,
here is both room and accommodation for them;
the stories of our necessity being either the fear of our friends,
or the scare-crows of our enemies; for the greatest hardship we have suffered,
has been salt-meat, which by fowl in winter, and fish in summer,
together with some poultry, lamb, mutton, veal,
and plenty of venison the best part of the year, has been made very passable.
I bless God, I am fully satisfied with the country and entertainment I can get in it;
for I find that particular content which has always attended me,
where God in his providence has made it my place and service to reside.
You cannot imagine my station can be at present free of more than ordinary business,
and as such, I may say, it is a troublesome work;
but the method things are putting in will facilitate the charge,
and give an easier motion to the administration of affairs; however,
as it is some men`'s duty to plough, some to sow, some to water, and some to reap,
so it is the wisdom as well as duty of a man, to yield to the mind of Providence,
and cheerfully, as well as carefully, embrace and follow the guidance of it.

====

--
