== Chapter XXVI.

1690.--As William Penn had been in the practice of writing letters to the Duke of Buckingham,
who died in 1687;
a friend of his being apprehensive that these letters might contain matter, which,
in the existing state of things, and the prejudice under which he laboured,
would be construed to his disadvantage, had applied himself to the collection of them,
in order to prevent their falling into improper hands.
This coming to the knowledge of their author,
he addressed to him the following communication:

"`Though nothing of an interest of my own was the
reason of the ancient esteem I have had for you,
yet that only is the motive at this time to this freedom; for being informed by Jer.
Grimshaw, that some of my letters to the late Duke of Buckingham are in your hands,
and that your continued kindness to all of our communion
had shown itself in my regard by collecting them apart,
to prevent their falling under any improper notice,
I thought myself obliged both to return my acknowledgments for that friendly caution,
and to desire you to let them follow him they were written to,
who can be no more known to the living.
I need not trust another hand than that,
which was unwilling any other should be trusted with them but my own.
I know not what the circumstances of that time might draw from me;
but my only business with him ever was to make his
superior quality and sense useful to this kingdom,
that he might not die under the guilt of misspending the
greatest talents that were among the nobility of any country.
However, in the rubbish of those times, and the late extraordinary revolution,
let them lie,
and let us all think of this only way to the peace and happiness we pretend to seek,
namely, to give God his due out of us,
and then we shall have our dues out of one another;
and without it let us not wonder at the nimble turns of the world,
nor reflect upon the mischiefs that attend them.
They are the natural effects of our breach of duty to God, and will ever follow it.
We, like the Jews, are full of jealousy, humour, and complaint,
and seek for our deliverance in the wrong place.
When we grow a better people, we shall know better days;
and when we have cast off Satan`'s yoke, no other can hold longer upon us.
Things do not change.
Causes and effects are ever the same; and they that seek to over-rule the eternal order,
fight with the winds, and overthrow themselves.
But what is this to my subject?
I close with the true sense of all your tenderness to our poor folks,
and regards to myself, beseeching God,
that more than the reward of him that gives a cup of cold
water in the name of a disciple may be your portion,
when this very trifling world may be no more.

I am your affectionate, true friend,

William Penn.

One of the principal objects of his continuance in England being in great measure attained,
his attention was turned towards his American possessions.
But before he had prepared for his voyage, he was arrested,
and brought before the lords of the council.
He was charged with holding a traitorous correspondence with the exiled monarch,
who was then in France.
The charge was founded upon a letter from James to him,
which had been intercepted by the government.
He desired to appeal to King William himself, which was granted;
and a conference with the king and council ensued, and continued nearly two hours.
The intercepted letter was produced,
but it required much less sagacity than William Penn`'s to show that he
was not answerable for anything which James might choose to write to him.
Being questioned respecting the meaning of some expressions contained in the letter,
he frankly told them he supposed they meant that
he should endeavour to promote his restoration.
He confessed that he had loved King James, and as he loved him in his prosperity,
he could not hate him in his adversity.
He acknowledged that the had received many favours from him,
which he was willing to repay by any private service in his power;
but he must inviolably observe that duty to the state
which belonged to all the subjects of it.
He had therefore never had the wickedness even to think of attempting
his restoration to the crown which had fallen from his head.
It was consequently evident that nothing contained in that letter, could criminate him.
This meagre outline is all that remains of the examination.
The defence of William Penn, however, appeared so clear and satisfactory,
that King William inclined to discharge him, but some of the council interfering, he,
to please them, required him to give bail for his appearance at the next Trinity term.
During the interval between this examination and the time assigned for his trial,
he employed himself in preparations for his intended voyage to America.
He appeared in court, at the time appointed, when,
as no evidence was produced against him, he was honourably discharged.

It was not long after this event,
before he was again interrupted in his preparations for returning to Pennsylvania.
The nation was in great commotion, from apprehensions of an invasion from France,
for the purpose of restoring the exiled king.
James had many adherents in Ireland, who had taken up arms in his cause;
and King William was engaged in the reduction of that island.
To prevent the partisans of James from taking advantage of William`'s absence, the queen,
in addition to other precautionary measures, issued a proclamation, dated 12th of July,
requiring the arrest of a number of individuals, principally noblemen,
including William Penn,
upon a charge or suspicion of adhering to the enemies of the reigning monarch.
The case coming before the court of king`'s bench on the last day of Michaelmas term,
and no proof appearing against him, he was again discharged.

Being thus liberated, with a character untarnished,
and fully aware of the loss to his American interest, arising from continued absence,
he renewed his preparations for a voyage to Pennsylvania.
Proposals for a fresh settlement there being issued,
a number of colonists were preparing to embark for that country.
The preparations were nearly completed, and a heavy expense incurred,
when his proceedings were arrested by a fresh accusation.
King William going to the Congress at the Hague,
some of the disaffected party took that opportunity
of forming a new conspiracy against his government.
In order to accomplish their design, it was concluded that Lord Preston and one Ashton,
should concert with King James, in person, the measures to be adopted.
But their plot being discovered,
they were seized in the hold of a vessel which they had engaged to carry them to France,
together with the letters and papers which they were carrying over.
Ashton was executed; but Preston, in order to save his own life,
informed against several of the nobility who had been active in promoting the revolution,
as well as against a number of the partisans of James.
Among those who were thus accused William Penn was one;
and the accusation being seconded by the oath of one William Fuller,^
footnote:[This Fuller soon afterwards was prosecuted and
convicted in the court of king`'s bench as an impostor,
and, for publishing certain libels, condemned to stand in the pillory.
His testimony of course could attach no odium to
the character of such a man as William Penn.]
a warrant was granted for his apprehension.

Just as this storm was gathering over him, George Fox was removed from works to rewards.
A little before his death he sent for some of his particular friends,
to whom he gave his instructions respecting the circulation of religious books.
Of this number William Penn was probably one, for I find he was with him at his close.
He also attended his funeral,
and was largely engaged in the ministry to a company estimated at two thousand persons.
A messenger was sent there, to arrest him on the warrant above mentioned,
but mistaking the hour, he escaped his hands.

William Penn had hitherto defended himself before the king and council,
and established his innocence to general satisfaction.
But the prosecution which now awaited him seems to have
assumed a more threatening aspect than any preceding one.
His biographers have not given a very clear account of the
specific charge which was preferred against him.
It appears to have been a participation with others
in a conspiracy for the restoration of James.
One of his accusers was Lord Preston, who being engaged in the conspiracy himself,
could not be expected to be very scrupulous with regard to the
testimony he should give in relation to the conduct of others;
and from the character of Fuller,
there was no reason to hope that he would hesitate to advance
any charge which interest or malice might suggest.
This plot was principally charged upon the Roman Catholics; and William Penn was,
in the idle rumours of the day, ranked with the adherents to the popish faith.
There was therefore reason to apprehend that the general
odium resting upon the professors of that religion,
would be brought to bear upon this prosecution.
The trials and executions upon the pretended disclosures
of Oates and Bedloe must have been fresh in his memory.
Under these circumstances, William Penn judged it most prudent,
instead of exposing himself to the hazard of a public trial,
to remain for a time in retirement.
He accordingly appeared but little in public for two or three years.

A letter written a few months after this event, to his friend Thomas Lloyd,
shows the pious resignation with which this trial was endured.

By this time you will have heard of the renewal of my troubles,
the only let of my return; being in the midst of my preparations,
with a great company of adventurers, when they fell upon me.
The jealousies of some, and unworthy dealing of others have made way for them;
but under and over it all, the ancient Rock has been my shelter and comfort;
and I hope yet to see your faces, with our ancient satisfaction.
The Lord grant, if it be for his glory, whose I desire to be in all conditions;
for this world passes away, and the form and beauty of it fades;
but there are eternal habitations for the faithful; among whom I pray that my lot may be,
rather than among the princes of the earth.

I hope I need not urge my circumstances, to excite your love,
care and concern for me and my suffering interest, in that country.
I know you have better learned Christ and Cato, if I may so say,
and will embrace such an opportunity to choose to express your friendship and sincerity;
nor is uncertainty and changeableness your fault; wherefore I will say no more,
but desire that my afflictions may cease, if not cure your animosities, or discontents,
within yourselves, if yet they have continued; and that you will both in government,
and to my commissioners of property, yield your assistance all you can.
By all this God may prepare me to be fitter for future service, even to you there.
I ask the people forgiveness for my long stay;
but when I consider how much it has been my great loss, and for an ungrateful generation,
it is punishment!--It has been 20,000 pounds to my damage, in the country,
and above 10,000 pounds here, and to the province 500 families; but the wise God,
that can do what he pleases, as well as see what is in man`'s heart,
is able to requite all; and I am persuaded, all shall yet work together for good,
in this very thing, if we can overlook all that stands in the way of our views Godward,
in public matters.
See that all be done prudently and humbly; and keep down irreverence and looseness,
and cherish industry and sobriety.
The Lord God Almighty be with you, and among you, to his praise and your peace.

William Penn did not permit the time of his seclusion to pass unemployed,
but produced several valuable tracts.

In the first place that his friends, the members of his own religious Society,
might not be left under any unfavourable impression on account of his retirement,
he addressed the following epistle to the Yearly Meeting of London:

"`The 30th of the Third month, 1691.

"`My beloved, dear and honoured brethren, "`My unchangeable love salutes you;
and though I am absent from you,
yet I feel the sweet and lowly life of your heavenly fellowship, by which I am with you,
and a partaker among you, whom I have loved above my chiefest joy.
Receive no evil surmisings, neither permit hard thoughts,
through the insinuations of any, to enter your minds against me your afflicted,
but not forsaken friend and brother.
My enemies are yours, and in the ground mine for your sakes; and that God sees in secret,
and will one day reward openly.
My privacy is not because men have sworn truly, but falsely against me;
for wicked men have laid in wait for me,
and false witnesses have laid to my charge things that I knew not;
who have never sought myself, but the good of all, through great exercises,
and have done some good, and would have done more, and hurt to no man,
but always desired that truth and righteousness,
mercy and peace might take place among us.
Feel me near you, and lay me near you, my dear and beloved brethren, and leave me not,
neither forsake,
but wrestle with Him that is able to prevail against the cruel desires of some,
that we may yet meet in the congregations of his people,
as in days past to our mutual comfort.
The everlasting God of his chosen in all generations, be in the midst of you,
and crown your most solemn assemblies with his blessed presence, that his tender, meek,
lowly, and heavenly love and life may flow among you;
and that he would please to make it a seasoning and fruitful opportunity to you, that,
edified and comforted, you may return home to his glorious high praise,
who is worthy forever.
To whom I commit you, desiring to be remembered of you before him,
in the nearest and freshest accesses, who cannot forget you in the nearest relation.

Your faithful friend and brother,

William Penn.

Robert Barclay, the Apologist, having died in the eighth month, 1690,
in the prime of life, being only in his forty-second year,
his works were collected and published in folio in 1692.
William Penn furnished an excellent preface to this volume,
containing a concise explanation and defence of the
principles which his author had so successfully espoused,
together with a brief account of the contents of the various
tracts contained in the works of that admirable writer.

John Burnyeat of Dublin, a valuable minister,
who had travelled extensively in the work of the Gospel,
was also removed from the militant church in the course of the same year.
His writings being collected and published soon after his death,
William Penn wrote a preface to that volume also.

Another product of his retirement, was a small tract, entitled, "`Just measures,
in an Epistle of peace and love to such professors of Truth,
as are under any dissatisfaction about the present
order practised in the church of Christ.`"

A number of years had then elapsed since meetings
for discipline were first established in the Society.
The opposition to those meetings, which arose on their institution,
had very much subsided; yet a difference of opinion existed at this time,
upon some points connected with them,
particularly the maintenance of women`'s meetings distinct from those of the men.
The object of this epistle was to show the benefit and importance of these meetings,
and to allay the jealousy which had grown up in some
parts of the Society in regard to them.

A work, rather larger, soon followed.
It happened about this time,
that persons of some other persuasions renewed their attack
upon the religious principles and doctrines of Friends.
This was done by giving to the world their own misrepresentations,
as an exhibition of the doctrines of the Society.
William Penn having collected these perversions,
wrote an essay for the purpose of enabling others to distinguish the doctrines
and principles of Friends from the misrepresentations of their adversaries.

This work was so well received, that within about thirty years after its publication,
it passed through twelve editions.
Being concise,
and containing much valuable matter respecting the
Christian doctrines and testimonies of the Society,
it is inserted at length:

[.asterism]
'''

A Key, opening the way to every capacity,
how to distinguish the religion professed by the people called Quakers,
from the perversions and misrepresentations of their adversaries.
With a brief exhortation to all sorts of people to examine their ways and their hearts,
and turn speedily to the Lord.

Introduction.

Reader,

Observing the prevailing power of prejudice,
and the too great easiness of mankind to be imposed upon by designing persons,
and especially on the side of uncharitableness, so depraved is the nature of man,
and considering also what mischievous effects that
evil has produced among all sorts of people,
to the hurt of civil as well as religious society, by the coldness, jealousy,
uncharitableness and animosity, even to hatred and persecution,
the very contraries of the true Christian religion, that have thereby abounded,
we have the less wondered at the hard treatment which we, as a people,
have suffered from other persuasions; almost all of them having in their turn, some,
I hope, ignorantly, others, I fear, willfully, misrepresented our principles,
misgiven our plain meanings,
and called their own strained interpretations and downright perversions,
our faith and religion.
Thus dressing us in the bear`'s skin,
the credulous have been excited to look upon and treat us as heretics, seducers,
blasphemers and what not, while, blessed be God,
our aim and bent have been the very power and work of religion upon our souls,
that we might be God`'s workmanship through Christ Jesus,
his blessed Son and heavenly agent;
taking this to be the very life and soul of true religion;
the effect and fruit of the Divine nature, which makes us Christians indeed here,
and fits us for glory hereafter.
And because we have chosen retirement, moderation and self-denial,
which to be sure are the solids and inwards, the spirit and substance of religion,
and have therefore sequestered ourselves from more outward and pompous communions,
offence has been taken at us, and we have been disingenuously represented to the world.
On which account I have published this little treatise, for the sake of others,
as well as in our own vindication, but theirs especially,
that are under prejudices from vulgar abuses.
I would entreat such to consider,
that if it be an evil to judge rashly or untruly of any single man,
how much greater sin it is to condemn a whole people.
And if the matter about which the judgment is made, renders it more or less evil,
certainly to condemn the religion of a whole people in the lump,
which comprehends their faith, worship and morals also, must be, if false or mistaken,
as great an injustice as can well be committed,
and the Almighty will not hold them guiltless who have been
so uncharitable and injurious to their neighbours.
This we have frequently lamented as our great unhappiness,
above all that our enemies have been able argumentatively to urge against us,
that we are yet unknown of those that stick not to condemn us.
But they must certainly be inexcusable with just minds,
who will take our belief at the hands of our enemies rather than at our own,
who best ought to know what we believe.
It will be the business of this little key to explain the pretended obscurity,
and show the difference between our principles and the vulgar account and apprehensions,
and thereby open a way to so clear and plain an understanding of our true principles,
distinguished from our enemies`' perversions, that we hope, with God`'s blessing,
all impartial inquirers will be satisfied of our holy and Christian profession.
This we also earnestly desire for their good, that as we have been called of God,
out of the evil of the world, to be a people to his praise, through his grace,
so none may stumble or be offended at the truth we testify of;
but seeing the excellency of it, by the peace and purity it leads into,
they may embrace it and walk in it;
which is the best way to end controversy and obtain the great and true end of religion,
the salvation of the soul.

=== Section I. Of the Light within, what it is, and the virtue and benefit of it to man.

Perversion 1. The Quakers hold,
That the natural light in the conscience of every man in the world,
is sufficient to save all that follow it; and so they overthrow salvation by Christ.

A mighty error indeed, if it were true.

Principle.
But it is at best a great mistake.
For their belief and assertion is, That Christ, who is the Word that was with God,
and was God, and is so forever, has enlightened every man that comes into the world,
with his own light, as he is that true light, or such a light,
as there is no other to be compared with him;
which is the meaning of the emphasis true in the text, John 1:9.
And that such as follow the reproofs, convictions and leadings of that light,
with which he enlightens the understandings and consciences of men,
shall not walk in darkness, that is, in evil and ignorance of God,
but shall have the light of life; that is,
be in a holy and living state or condition towards God;
a state of acceptance and salvation, which is from sin here,
as well as from wrath hereafter, for which end Christ was given of God.
So that they assert the light of Christ, to be sufficient to save, that is,
to convince of sin, lead out of it and quicken the soul in the ways of holiness,
and not to be a natural light; but as all men, born into the world,
have a measure of Christ`'s light, so it may, in a sense,
be said to be natural to all men, because all men who come into the world have it.
This light is something else than the bare understanding man has as a rational creature;
since, as such, man cannot be a light to himself; but has only a capacity of seeing,
by means of the light with which Christ, the Word, enlightens him.
For we can no more be a mental or intellectual light to ourselves,
than we are an external and corporeal light to ourselves.
But as the sun in the firmament is the light of our bodies,
so the light of the Divine Word is the sun of our souls;
the glorious luminary of the intellectual world, and they that walk in it,
will by it be led to blessedness.

Perversion 2. The Quakers hold, That the light within them is God,
Christ and the holy Spirit; so that every Quaker has whole God,
Christ and holy Spirit in him, which is gross blasphemy.

Principle.
This is also a mistake of their belief.
They never said that every Divine illumination or manifestation of Christ,
in the hearts of men, was whole God, Christ or the Spirit,
which might render them guilty of that gross and
blasphemous absurdity some would fasten upon them.
But that God, who is light, or the Word Christ, who is light, styled the second Adam,
the Lord from heaven, and the quickening Spirit, who is God over all, blessed forever,
has enlightened mankind with a measure of saving light; who said,
I am the Light of the world, and they that follow me, shall not abide in darkness,
but have the light of life.
So that the illumination is from God, or Christ, the Divine Word;
but not therefore that whole God or Christ is in every man,
any more than the whole sun or air is in every house or chamber.
There are no such harsh and unscriptural words in their writings.
It is only a frightful perversion by some of their enemies,
to bring an odium upon their holy faith.

Yet in a sense the Scriptures say it, and that is their sense, in which only,
they say the same thing.
I will walk in them and dwell in them.
He that dwells with you, shall be in you: I will not leave you comfortless,
I will come to you: I in them and they in me: Christ in us, the hope of glory.
Unless Christ be in you, you are reprobates.
Little children, of whom I travail again in birth, until Christ be formed in you.
Now if they who denied his coming in the flesh, though highly professing Jews,
were to be accounted anti-christs,
because enemies to that appearance and dispensation of God to men;
what must they be reputed, who as stiffly disown his inward,
nearer and more spiritual coming, formation and dominion in the soul; which is,
to be sure, the higher and nobler knowledge of Christ?
Yes, the mystery hid from ages and now revealed to God`'s people the riches of the
glory of the mystery which God reserved to be made known to the Gentiles,
of whose stock we are.
Certainly, though they are called Christians,
they must be no whit less anti-christs than those obstinate Jews of old,
who opposed his more visible and bodily appearance.

Perversion 3. By the Quakers`' doctrine every man must be saved, for every man, they say,
is savingly enlightened.

Principle.
Not so either:
for though the light or grace of God has and does more or less appear to all men,
and brings salvation to as many as are taught by
it to deny ungodliness and worldly lusts,
and to live soberly, and righteously, and godly in this present world,
as the Scripture teaches; yet it no way follows that men must obey and learn so to do,
whether they will or not.
God tenders saving light or grace to all, and by it calls all,
and strives and pleads with all, according to the measure and manifestation of it;
but if they will not hearken to it, he is clear of their blood.
His light is saving that enlightens them, but it cannot be said to save them,
while they rebel against it.
In short, though men are enlightened or visited with a saving light or grace,
yet the Quakers never concluded, nor can it rightly be concluded from their testimony,
that such men must necessarily and absolutely be saved, whether they obey or rebel.

Perversion 4. By the Quakers`' Light or Spirit, they may be moved to murder, treason,
theft or any such like wickedness, because they say that such as are so led,
have the light within them.

Principle.
This never was their doctrine, nor is it consequent of it.
For though they hold that all have light, they never said that all obeyed it,
or that evil men, as such, or in such things, were led by it.
Much less could the light be chargeable with the
sins of those who refused to be led by it.
For herein they know the spirit of God and the motions of it,
from the spirit of this world and its fruits,
that the spirit of God condemns all ungodliness, and moves and inclines to purity, mercy,
and righteousness, which are of God.

They deny and abominate that loose and ranting mind,
which would charge the spirit of God with their unholy liberty.
God`'s spirit makes people free from sin, and not to commit sin.
Neither do they distinguish, as such loose people wickedly do,
between the act and the evil of it.
Wherefore they say, that as the tree is known and denominated by its fruits,
so spirits are by their influences, motions and inclinations;
and the spirit of God never did incline anyone to evil.
For that cause they renounce this construction of the Ranters,
that evil is no evil when they are led to it by God`'s spirit; for that grossly implies,
as if the spirit of God led man at any time to that which is evil in itself,
or that it were possible to be sinless in the commission of sin, as murder, theft,
revenge, etc.
For that never was or can be the way and method of God`'s spirit,
which is pure and holy forever;
and brings all who regard the convictions and motions of it,
into a sense and sorrow for sin, and so leads them into a state of reformation,
without which, all profession of religion is mere formality, and hypocrisy.
So that man`'s sin and destruction are of himself, but his help is in God alone,
through Jesus Christ, our blessed sacrifice and sanctifier.

=== Section II. Of Infallibility and Perfection.

Perversion 5. The Quakers must all be infallible and perfect,
if they have such an infallible Light in them.

Principle.
No such matter: this is also a great abuse of their true meaning.
They say, the spirit of Truth is pure, perfect, unerrable in itself,
or else it were very unfit to lead men out of error and impurity.
But they never did assert themselves such, merely because it was within them: by no means.
But that all who are led by it, and live according to its manifestation,
are so far perfect, and so far infallible in the right way, as they are led by it,
and not a jot farther.
For it is not opinion, or speculation, or notions of what is true; or assent to,
or the subscription of articles, or propositions, though never so soundly worded, which,
according to their sense, makes a man a true believer, or a true Christian.
But it is a conformity of mind and practice to the will of God,
in all holiness of conduct,
according to the dictates of this holy Spirit of light and life in the soul,
which denotes a person truly a child of God.
For the children of God are led by the spirit of God,
but if any man have not the spirit of Christ, he is none of his.
And let it be noted, that though this spirit be in man, yet it is not of man, but of God,
through Jesus Christ.
Who can lay down a more independent doctrine upon self,
and a more depending one upon the grace or gift of God?
Let us not, I pray, be mistaken, nor allow for such misapprehensions,
nor be made to hold what we do not, on purpose to disrepute us with sober people,
or to support the mistaken charges of our enemies.
Yet to show that a state of perfection from sin (though not in
fulness of wisdom and glory) is attainable in this life,
they, among others, refer to these Scriptures, which for brevity`'s sake,
are not set down at large, but the reader is desired to turn to them:
Gen. 17:1. Duet. 18:13. Job 1:1,8.; 2. 3., etc.; 8:20.
Ps. 18:32; 37:37; 119:1. Prov. 2:21. Matt. 5:48. Luke 6:40. 1 Cor. 2:6.
2 Cor. 13:11-9. Eph. 4:13. 1 Thess. 3:10. 2 Tim. 3:17. James 1:4.
1 Pet. 5:10. Heb. 6:1. 1 John 1:6-9.; 2:20. 27.; 3:5-8.; 4:17.

=== Section III.
Of the Scriptures, their truth, authority, and service.

Perversion 6. The Quakers deny the Scriptures, for they deny them to be the Word of God.

Principle.
They own and style the Scriptures, as they own and style themselves; namely,
a declaration of those things most truly believed, given forth in former ages,
by the inspiration of the holy Spirit;
consequently that they are profitable for doctrine, for reproof, for correction,
for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works.
They are the form of sound words.
We profess to believe them, and read them;
and say it is the work we have to do in this world,
and the earnest desire of our souls to Almighty God,
that we may feel and witness the fulfilling of them in and
upon ourselves that so God`'s will may be done in earth,
as it is in heaven.
But to call them the Word of God, the ground of the charge,
which they never call themselves,
but by which they peculiarly denominate and call Christ; in reverence to Christ,
and in no slight to them, (which we believe to be of Divine authority,
and embrace as the best of books, and allow to be as much the word of God,
as a book can be,) they do, as in duty and reason bound,
attribute that title to Christ only.

And yet as the word of God may, in some sense, signify the command of God,
referring to the thing or matter commanded, as the mind of God,
it may be called the word of the Lord, or word of God: as, on particular occasions,
the prophets had the word of the Lord to persons and places; that is to say,
the mind or will of God, or that which was commanded them of the Lord to declare or do.
So Christ uses it, when he tells the Pharisees,
that they had made the word (or command) of God of none effect, by their traditions.
But because people are so apt to think, if they have the Scriptures they have all,
(for that they account them the only word of God, and so look no farther; that is,
to no other Word,
from which those good words came) therefore this people have been constrained,
and they believe, by God`'s good spirit,
once and again to point them to the great Word of words, Christ Jesus, in whom is life,
and that life the light of men;
that they might feel something nearer to them than the Scriptures, namely,
the Word in the heart, from which all holy Scripture came, which is Christ within them,
the hope of their glory.
And to be sure he is the only right expounder as well as the author of holy Scripture,
without whose light, spirit, or grace,
they cannot be savingly read by those that read them.

Perversion 7. They deny them to be any means whereby to resist temptation.

Principle.
This is a very uncharitable aspersion.
True it is, that they deny the Scriptures merely, or of themselves,
to be sufficient to resist temptations; for then all that have them and read them,
would be sure to be preserved by them against temptations.
But that they should deny them to be any means or instrument in God`'s hand,
is either great ignorance or injustice in their adversaries.
God has made use of the Scriptures, and daily does and will make use of them,
for instruction, reproof, comfort and edification, through the Spirit,
to those that read them as they ought to do.
Thus they say they have felt them, and so they have been and are made unto them,
through the good Spirit of God, coming in upon their spirits,
in the reading and considering of them;
and wish heartily they were more in request with the professors of Christianity.

=== Section IV. Of the holy Spirit of God, and its office, with respect to man, and of ministry, etc.

Perversion 8. The Quakers assert the Spirit of God to be the immediate teacher,
and that there is no other means now to be used, as ministry, ordinances, etc.

Principle.
They never spoke such language, and their daily practice confutes the reflection.

But herein we perceive the great subtlety of Satan, as well as in other things,
to darken the appearance of the Truth, and prepossess people`'s minds against it.
For since he cannot hinder the exaltation of the Spirit above all visible instruments,
nor the necessity of its manifestations, convictions, motions and operations,
to be known in the hearts of men,
and the great suitableness thereof to the Gospel administration,
he would spoil all by overdoing the matter, and carrying our assertions beyond bounds.
They never denied the use of means, but to this day, from the beginning,
they have been in the practice of them.
But then they are such means as are used in the life and power of God,
and not in and from man`'s mere wit, will, or carnal invention or imitation;
the only thing they strike at.
For instance, they cannot own that to be a Gospel ministry,
that is without a Gospel Spirit,
or that such can be sent of God who are not taught of God,
or that they are fit to teach others what regeneration and the way to heaven are,
who have never been born again themselves; or that such can bring souls to God,
who are themselves strangers (like those in the Acts
19:21) to the baptism of fire and the Holy Spirit;
never having been circumcised with the circumcision of the heart in the Spirit, Rom. 2:29.
: which is so absolutely necessary to make a true Jew, or a real Christian,
and consequently the requisite qualification of a Gospel ministry.

This unexperienced and lifeless ministry, is the only ministry,
and such the only ministers, that the people called Quakers cannot own and receive,
and therefore cannot maintain.
For the ministry and the ministers that are according to Scripture, they both own,
respect, and delight in, and are ready to assist and support in their service for God.

It is strange, because they deny all false means, or means not sanctified,
or used in the openings and leadings of God`'s power and Spirit,
that therefore they must deny all means, however rightly used or employed.
This is an injustice to their profession and practice.
Wherefore all are desired to take notice,
that evangelical means and order they love and desire to keep:
for they diligently assemble themselves together to wait upon God,
to enable them to worship him; where they both pray and prophesy, one by one,
as prepared and moved in their hearts by his Spirit, and as anything is revealed to them,
according to primitive practice; otherwise they are silent before the Lord.
Nor are they without spiritual songs,
making melody in their hearts to God their Redeemer, by the same Holy Spirit,
as often as they are comforted and moved by it, as was the primitive practice.

=== Section V. Of the Holy Three, or Scripture Trinity.

Perversion 9. The Quakers deny the Trinity.

Principle.
Nothing less: they believe in the holy three, or Trinity of Father, Word and Spirit,
according to Scripture.
And that these three are truly and properly one; of one nature as well as will.
But they are very tender of quitting Scripture terms and phrases, for schoolmen`'s,
such as distinct and separate persons and subsistences, etc., are;
from which people are apt to entertain gross ideas and notions of the Father, Son,
and Holy Spirit.
And they judge, that a curious inquiry into those high and Divine revelations,
or into speculative subjects, though never so great truths in themselves,
tend little to godliness, and less to peace;
which should be the chief aim of true Christians.
Therefore they cannot gratify that curiosity in themselves, or others:
speculative truths are, in their judgment, to be sparingly and tenderly declared,
and never to be made the measure and condition of Christian communion.
For besides that Christ Jesus has taught them other things, the sad consequence,
in all times, of superfining upon Scripture texts,
do sufficiently caution and forbid them.
Men are too apt to let their heads outrun their hearts,
and their notion exceed their obedience, and their passion support their conceits;
instead of a daily cross, a constant watch, and a holy practice.
The despised Quakers desire this may be their care, and the text their creed in this,
as in all other points; preferring self-denial to opinion, and charity to knowledge,
according to that great Christian doctrine, 1 Cor.
xiii.

=== Section VI. Of the Divinity of Christ.

Perversion 10. The Quakers deny Christ to be God.

Principle.
A most untrue and unreasonable censure:
for their great and characteristic principle being this, that Christ, as the Divine Word,
enlightens the souls of all men that come into the world,
with a spiritual and saving light, according to John 1:9., viii.
12., which nothing but the Creator of souls can do,
it sufficiently shows that they believe him to be God,
for they truly and expressly own him to be so, according to Scripture: In him was Life,
and that Life the light of men; and he is God over all, blessed forever.

=== Section VII.
Of the Manhood of Christ.

Perversion 11. The Quakers deny the human nature of Christ.

Principle.
We never taught, said, or held so gross a thing,
if by human nature be understood the manhood of Christ Jesus.
For as we believe him to be God over all, blessed forever,
so we do as truly believe him to be of the seed of Abraham and David after the flesh,
and therefore truly and properly man, like us in all things,
and once subject to all things for our sakes, sin only excepted.

=== Section VIII.
Of Christ Jesus, his Death and Sufferings.

Perversion 12. The Quakers expect to be justified and saved by the Light within them,
and not by the death and sufferings of Christ.

Principle.
This is both unfairly and untruly stated and charged upon us.
But the various senses of the word justification,
oblige me here to distinguish the use of it; for in the natural and proper sense,
it plainly implies, making men just, who were unjust; godly, that were ungodly; upright,
that were depraved; as the Apostle expresses himself, 1 Cor. 6:11.;
And such were some of you, but you are washed, but you are sanctified,
but you are justified in the name of our Lord Jesus, and by the Spirit of our God.
In the other use of the word, which some call a law-sense, it refers to Christ,
as a sacrifice and propitiation for sin, as in Rom. 5:9., Much more then,
being now justified by his blood, we shall be saved from wrath through him:
and 1 John 2:1-2., If any man sin, we have an advocate with the Father,
Jesus Christ the righteous; and he is the propitiation for our sins;
and not for ours only, but also for the sins of the whole world.
Which, though a great truth and most firmly believed by us,
yet no man can be entitled to the benefit thereof,
but as he comes to believe and repent of the evil of his ways;
and then it may be truly said, that God justifies even the ungodly,
and looks upon them through Christ, as if they had never sinned;
because their sins are forgiven them for his beloved Son`'s sake.
Not that God looks on people to be in Christ, who are not in Christ; that is,
who are not in the faith, obedience and self-denial of Christ; nor sanctified,
nor led by his Spirit, but rebel against it; and instead of dying to sin,
through a true and unfeigned repentance, live and indulge themselves daily in it;
for they that are in Christ, become new creatures; old things are passed away,
and all things, with them, become new.
Wherefore we say, that whatever Christ then did, both living and dying,
was of great benefit to the salvation of all who have believed, and now do,
and who hereafter shall believe in him unto justification and acceptance with God:
but the way to come to that faith,
is to receive and obey the manifestation of his Divine light and grace in their consciences,
which leads men to believe and value, and not to disown or undervalue Christ,
as the common sacrifice and mediator.
For we do affirm, that to follow this holy Light in the conscience,
and to turn our minds, and bring all our deeds and thoughts to it, is the readiest, no,
the only right way to have true living and sanctifying faith in Christ,
as he appeared in the flesh, and to discern the Lord`'s body,
coming and sufferings aright, and to receive any real benefit by him,
as their only sacrifice and mediator:
according to the beloved disciple`'s emphatical passages, If we walk in the light,
as (God) is in the light, we have fellowship one with another,
and the blood of Jesus Christ his Son cleanses us from all sin.
And because this people say,
that Christ`'s outward coming and sufferings profit not to their
salvation who live in sin and rebel against this Divine light,
some have untruly and uncharitably concluded,
that they deny the virtue and benefit of Christ`'s coming and sufferings in the flesh,
as a sacrifice for sin.
Whereas we only deny and oppose a false and dangerous
application of them in and to a disobedient state.
For we believe Christ came not to save men in their sins, but from their sins;
and that those that open the door of their hearts at his inward and spiritual knocks,
+++[+++namely, the reproofs and convictions of his light and grace]
have their consciences sprinkled with his blood (that is,
discharged from the guilt of them) from dead works, to serve the living God.
And so far only as men come by faith, repentance and amendment, to be Christ`'s,
Christ is theirs, and as he has an interest in their hearts,
they have an interest in his love and salvation: that is,
so far as they are obedient to his grace, and take up his cross,
and follow him in the ways of meekness, holiness and self-denial,
so far they have an interest in Christ, and no farther.
And here there is no condemnation to them that are in Christ Jesus,
because such walk not after the flesh, but after the Spirit;
for we have seen a shoal or sand here, upon which we fear many thousands have split,
and which we desire to avoid, and are earnest that others may beware of it also; namely,
that because Christ died a sacrifice for the sins of the whole world,
by which he put mankind into a capacity of salvation,
and has given every one a talent of grace to work it out by;
they presume upon that sacrifice, and sin on, without a thorough repentance,
reformation and conversion to God, not dying with Christ to the world, but living in it,
according to the lusts and spirit of it.
Such as these may be assured, that where Christ is gone they shall never come;
for says the blessed Apostle, God sent his Son to bless us,
by turning every one of us from the evil of our way.
So that the contrite, humble, meek, and self-denying people,
are those that have the true and full benefit of Christ`'s coming,
sufferings and mediation,
and of all those holy ends for which God his Father anointed and gave Him to the world,
to be the Way, Truth and Life, Light, Leader and Saviour, to be a King, Priest, Prophet,
Sacrifice, Sanctifier and Mediator;
being sensibly felt of all such to reign over their hearts,
to teach them God`'s royal law, to give them saving knowledge, and to mediate, atone for,
sanctify and justify them in the sight of God his Father, forever.

By all which it is evident to any moderate inquirer,
that we acknowledge Christ in his double appearance; as in the flesh,
of the seed of Abraham, so in the Spirit, as he is God over all, blessed forever.
Wherein is a full confession to him, both as a blessed person,
and as a Divine Spirit of light and life in the soul;
the lack of which necessary and evident distinction occasions our adversaries frequent
mistakes about our belief and application of the Scriptures of Truth concerning Christ,
in that two-fold capacity.

For it is not another than that eternal Word, Light, Power, Wisdom and Righteousness,
which then took flesh, and appeared in that holy Body, by whom they have received,
or can receive, any true spiritual benefit.
They holding, that Light is only from him, forgiveness only through him,
and sanctification only by him.
So that their ascribing salvation from sin and death eternal to him,
who now appears by his holy Spirit to their souls, as before expressed,
cannot render him no Saviour in that age,
or make void the end and benefit of his blessed appearance in the flesh on earth,
or his mediation now in glory, for those that believe in him in this age.
Whose doctrine pierced, whose life preached, whose miracles astonished,
whose blood atoned, and whose death, resurrection and ascension,
confirmed that blessed manifestation to be no less than the Word
God (the life and light of men) manifested in the flesh,
according to the Apostle Paul, for the salvation of the world:
and therefore properly and truly He was the Son of Man on earth,
and is now as truly the Son of Man in glory, as the head of our manhood,
which shall also be glorified, if we now receive him into our hearts, as the true Light,
that leads in the way of life eternal, and continue in well-doing to the end.

=== Section IX. Of Good Works.

Perversion 13. Thus it is the Quakers set up works, and meriting by works,
like the papists; whereby justification by faith in Christ is laid aside.

Principle.
By no means: but they say with the Apostle James, ch.
ii., that true faith in Christ cannot be without works,
any more than a body can live without a spirit; and that where there is life,
there is motion, and where there is no Divine life and motion,
there can be no true faith; believing being a fruit of Divine life.
No, by the comparison, if they were separable, works being compared to the Spirit,
they would have the better.
The very believing is an act of the mind,
concurring with God`'s working in or upon the mind, and therefore a godly work.
And no sooner is true faith begotten in a soul, but it falls to working;
which is both the nature, and in some respects, the end of it.

Nor yet do we say, that our very best works, proceeding from the true faith itself,
can merit; no, nor faith joined with them, because eternal life is the gift of God.
All that man is capable of believing or performing can never
properly be said to merit everlasting blessedness,
because there can be no proportion (as there must be in case of merit)
between the best works that can be performed in the life of man,
and an eternal felicity.
Wherefore all that man can do, even with the assistance of the holy Spirit,
can never be said strictly to merit, as a debt due to the creature.
But on the other hand, that right faith, and good works, which arise out of it,
or will follow it, may and do obtain the blessed immortality,
which it pleases Almighty God to give, and to privilege the sons of men with,
who perform that necessary condition, is a Gospel and necessary truth.
And this the Quakers ground upon, and therefore boldly affirm to the world.
So that they deny all merit from the best of works,
especially by such as some papists may conceive to be meritorious.
But as they on the one hand, deny the meritoriousness of works, so on the other hand,
neither can they join with that lazy faith which works not
out the salvation of the soul with fear and trembling.
Pray let not good works make men papists, because they make men Christians.

I am sure believing and not working, and imagining a salvation from wrath,
where there is no salvation or cleansing from sin, which is the cause of it,
is no whit less unscriptural, and abundantly more pernicious to the soul.
Blessed is he that hears Christ`'s words and does them.
The doer is only accepted.
Wherefore it shall be said at the last day, not well professed,
but well done good and faithful servant, enter into the joy of your Lord.
You holy, humble, patient and meek liver; you that loved me above all,
and your neighbour as yourself; enter.
For you and such as you are, was it prepared from the foundation of the world.
Which recompense of his faithfulness, is the infinite love of God,
revealed and given to man, through Christ.
For though death be the wages of sin, yet the gift of God is eternal life to such.
So that as the people called Quakers do not hold that their good works merit,
neither believe they that their good works justify them;
for though none are justified that are not in measure sanctified, yet all that man does,
is duty, and therefore cannot blot out old scores; for that is mere grace and favour,
upon repentance, through Christ the sacrifice and mediator, our great scapegoat.
So that men are not justified, because they are sanctified,
but for his sake that sanctifies them,
and works all their good works in them and for them, and presents them blameless, namely,
Christ Jesus, who is made unto them, as he was to the saints of old, wisdom,
righteousness, sanctification and redemption; that he that glories,
might glory in the Lord.

=== Section X. Of Water-Baptism and the Supper.

Perversion 14. The Quakers deny the two great sacraments or ordinances of the Gospel,
baptism and the supper.

Principle.
Whatever is truly and properly a Gospel ordinance, they desire to own and practise:
but they observe no such language in the Scripture as in the reflection.
They do confess the practice of John`'s baptism and the supper is to be found there;
but practice only, is no institution, nor a sufficient reason of continuation.
That they were then proper, they believe, it being a time of great infancy,
and when the mysteries of truth lay yet couched and folded up in figures and shadows,
as is acknowledged by Protestants.
But it is their belief, that no figures or signs are perpetual, or of institution,
under the Gospel administration, when Christ, who is the substance of them, is come:
though their use might have been indulged to young converts in primitive times,
because of the condescension of former practices.

It were to overthrow the whole Gospel dispensation,
and to make the coming of Christ of none effect,
to render signs and figures of the nature of the Gospel, which is inward and spiritual.
If it be said, but they were used after the coming of Christ, and his ascension too;
they answer, so were many Jewish ceremonies, not easily abolished, as circumcision, etc.
It is sufficient to them, that water baptism was John`'s, and not Christ`'s,
see Matt. 3:11., Acts 1:5.; that Jesus never used it, John 4:2.;
that it was no part of Paul`'s commission, which if it were evangelical, and of duration,
it certainly would have been, 1 Cor. 4:15-17.; that there is but one baptism,
as well as one faith, and one Lord, Eph. 5:4;
and that baptism ought to be of the same nature with the kingdom of which it is an ordinance,
and that is spiritual.
The same holds also as to the supper, both alluding to old Jewish practices,
and used as a signification of a near and accomplishing work, that is,
the substance they represented.

If any say, but Christ commanded that one of them should continue in remembrance of him;
which the Apostle to the church of Corinth explains thus;
that thereby they do show forth the Lord`'s death till he comes; we alledge,
that he that said so, told his disciples also, that he would come to them again;
that some should not taste death till they saw him coming in the kingdom;
and that he that dwells with them, should be in them;
and that he would drink no more of this fruit of the vine,
till he should drink it new with them in the kingdom of God.
Which is the new wine that was to be put into the new bottles,
and is the wine of the kingdom; as he expressed it in the same place:
which kingdom is within, as may be read in Luke.
He was the heavenly Bread that they had not yet known, nor his flesh and blood,
as they were to know them; as may be seen, John vi.
So that though Christ came to end all signs, yet,
till he was known to be the Substance to the soul,
as the great Bread of life from heaven, signs had their service with them, to show forth,
and hold in hand, and in remembrance of Christ: especially to the people of that day,
whose religion was attended with a multitude of the like types,
shadows and signs of the one good thing and substance of all,
Christ manifested in his people.
And that great Apostle Paul says expressly of the Jewish observations,
that they were shadows of the good things to come, but the substance was of Christ.
Hence it is, that the people called Quakers cannot be said to deny them;
that is too hard a word: but they,
truly feeling in themselves the very thing which outward water,
bread and wine do signify, or point forth, +++[+++to say nothing here of their abuse,
and what in that case may be argued,
from the instance of Hezekiah`'s taking away the brazen serpent by God`'s command]
they leave them off, as fulfilled in Christ, who is in them the hope of their glory:
and henceforth they have but one Lord, one faith, one baptism, one bread,
and one cup of blessings; and that is the new wine of the kingdom of God,
which is within.

=== Section XI. Of the Resurrection, and Everlasting Recompense.

Perversion 15. They acknowledge no resurrection of the dead, nor rewards to come.

Principle.
In this also we are greatly abused.
We deny not, but believe the resurrection according to the Scripture, not only from sin,
but also from death and the grave:
but are conscientiously cautious in expressing the
manner of the resurrection intended in the charge,
because it is left a secret by the holy Spirit in the Scripture.
Should people be angry with us for not expressing or asserting what is hidden,
and which is more curious than necessary to be known,
and in which the objectors themselves cannot be positive?
You fool, is to the curious inquirer, as says the Apostle:
which makes the Quakers contented with that body,
which God shall please to give them hereafter:
being assured that their corruptible shall put on incorruption,
and their mortal shall put on immortality, but in such a manner as pleases God.
And in the mean time they esteem it their duty, as well as wisdom,
to acquiesce in his holy will.
It is enough they believe a resurrection,
and that with a glorious and incorruptible body, without farther niceties;
for to that was the ancient hope.

Now as to future rewards, they not only believe them, but as the Apostle says of old,
above all people, have the greatest reason so to do; for otherwise, who is so miserable?
Do they inherit the reproach and suffering of all that have
separated from time to time from national churches;
that is to say, are the outcries that have been against the Protestants by the Papists,
and those of the Church of England against the Puritans, Brownists, and Separatists,
fallen so thick upon them,
and shall they hold principles inconsistent with an everlasting recompense of reward?
By no means.
It is their faith, their hope, their interest, and what they wait and have suffered for,
and press, as an encouragement to faithfulness, upon one another:
and the contrary therefore must be both an unjust,
and an improbable suggestion of their adversaries.

=== Section XII.
Of Civil Honour and Respect.

Perversion 16. The Quakers deny all civil honour and respect,
but what is relative or equal between men.

Principle.
We honour all men in the Lord,
but not in the spirit and fashion of this world that passes away.
And though we do not pull off our hats, or make courtesyings, or give flattering titles,
or use compliments, because we believe there is no true honour, but flattery and sin,
in the using of them; yet we treat all men with seriousness and gentleness,
though it be with plainness, and our superiors with a modest and respectful distance;
and are ready to do them any reasonable benefit or service,
in which we think real honour consists.
Whereas those that thus reproach us, are often proud, peevish, snappish,
abusive and oppressive one to another;
though at the same time they can give one another the cap and knee, with smooth words,
which too generally they never mean: which is far from true civility,
or honouring all men in the sense that they are exhorted to by the Apostle.
As for expressing our respect to our superiors in all countries,
we think it best done by obeying just laws under their government,
according to the saying of the centurion unto Christ,
and which Christ so much approved of, namely, when he said to one, come, and he came,
to another, go, and he went, to a third, do this, and he did it.
Reasonable commands, and ready obedience.
This is honouring government and governors, and not empty titles,
and servile and fantastic gestures,
and drinking of their healths till they drink away their own;
the vain and evil customs of the world, taken from the heathens`' practices,
and adopted by loose Christians in their conduct, and so become the fashion of the times.
If to dissent from these things, be to be vile,
we are contented to be accounted more vile, having Christ`'s commands, primitive example,
and our own convictions on our side.

=== Section XIII.
Of Civil Government.

Perversion 17. The Quakers are enemies to all government.
First, in that every one acts according to his own conceit.
Secondly, because they will not support civil government.
Thirdly, because they refuse to give evidence upon oath, as the law requires.

Principle.
That this is a calumny, their lives and conduct sufficiently show;
for no people give the magistrates less trouble,
or cause the burden to sit lighter upon their shoulders than these people do.
And for their principle, they believe magistracy to be an ordinance of God,
and that he that rules well, is worthy of double honour,
and deserves to be much valued and esteemed: as such certainly do,
who are a terror to evil doers, and a praise to them that do well.
And farther, to show that they are a people that love order and good government,
they carefully practise it among themselves:
for if there be twenty meetings for worship in a county, they, peradventure,
make three or four Monthly Meetings of business,
and these monthly meetings are resolved into a Quarterly Meeting for the county,
by such members as they severally appoint to constitute it.
And all the Quarterly Meetings in the nation, by chosen men out of themselves,
do constitute one general Yearly Meeting; unto which, the meetings of those people,
in all parts of the world, have their recourse, by chosen messengers, or by epistles.
The business of which meetings, in their several degrees,
is to promote virtue and charity, peace and unity.

Perversion 18. The Quakers will not support civil government, and so are useless,
if not dangerous to government.

Principle.
This also is untrue, upon experience:
for what people is more industrious under government,
or pay their taxes better to it than they do?
And, tribute from the people, and justice from the rulers,
are the support of government in all countries.
It is true indeed, that they cannot kill or slay their own kind,
and so are not fit for warriors with carnal weapons of destruction,
because they believe their blessed Lord forbade the use of them to his followers,
when he said, They that take the sword, shall perish with the sword;
and that the use of the sword in war,
was one of those things that God suffered for the hardness of men`'s hearts,
and that from the beginning it was not so.
In fine, that it came in with the fall, and must go out with it also.
And as Christ the repairer of breaches and restorer of paths to dwell in,
comes to be known to rule in the heart, love will take place of wrath,
and forgiveness overcome injury and revenge.
So the lamb will be preferred before the lion,
and the lion resign to and lie down with the lamb,
and destruction come to a perpetual end.
For which cause, the weapons of this people`'s warfare are not carnal,
but mighty through God, to the pulling down the strong holds of sin and Satan,
according to the apostle`'s doctrine.
Which is the holy war indeed, styled by the holy Spirit, The saints`' warfare.
And since so holy, lamb-like and peaceable a state, is both prophesied of and promised,
as the happiness of the latter times;
and that it and they take their beginning in Christ,
the beginning and the end of all true Christians;
let not this people be thought useless or inconsistent with government,
for introducing that harmless, glorious way to this distracted world,
for some body must begin it, but rather adore the providence,
embrace the principle and cherish and follow the example: believing with them,
that Christ, the blessed Shepherd of his flock,
will ever preserve the faithful followers of his meekness
and the disciples of his peaceable and forgiving doctrine.

Perversion 19. The Quakers refuse to give evidence, etc.

Principle.
It cannot be their fault, which is so much their desire, that is,
To be able to give evidence upon all occasions.
Nor, with justice, can it be reputed their stubbornness, but their tenderness,
since they cannot swear at all, and that the law requires an oath in evidence.
Now Christ having commanded his followers not to swear at all,
and that instead of an oath, or in cases where oaths are allowed under the law,
their yes, yes, and no, no, should serve instead of swearing; and for this reason,
because what is more than yes, yes, and no, no, comes of evil;
and for that Christians are commanded to avoid the very appearance of evil,
much more that which comes of evil; upon these accounts they dare not swear at all.
So that it is for Christ`'s sake, and the tender respect they bear to his evangelical,
positive and general precept, that they cannot swear, who is the Truth,
and has taught them to speak the truth without an oath.

Now if this would be admitted, +++[+++and often they have prayed that it might be,
and for lack of it,
are not only less serviceable to their neighbours than otherwise they could be,
but are great sufferers in their persons and estates,]
and the government would be pleased to accept their yes, yes, and no, no,
instead of an oath, as other countries do in the like cases,
they would be ready to submit to the same punishment in case of untruth,
as is due by law to perjury,
and upon all occasions would be glad to help and
serve their neighbours with all their hearts.
Wherefore let not that be made their fault, which is so much against their will,
and their unhappiness and affliction.

Thus, sober reader, you have a brief account of this people,
their principles and practice, and therefore you may see, if you please,
with how little reason they are despised by some and abused by others;
which has been their lot, in a large measure, ever since they have been a people.
Though the whole bent of their spirits and testimony, since God, by his grace,
has distinguished them,
has been to promote the experimental and saving knowledge of Christ Jesus in the world,
by turning the minds of people from the darkness that is in them,
to the light of Christ which is in them, as the great,
singular and necessary agent and spirit,
by which only man is enlightened and enabled to see and do the will of God.
For, till men receive and are quickened by the holy Spirit,
they are hypocrites and not Christians; bastards and not sons.

Neither can they have true and living faith, whatsoever they profess;
nor can they truly and acceptably worship God, whatsoever they perform.
O then, let the poor Quakers,
and their abused principles have better entertainment with you, reader.
And do not conclude because they direct people to the Light of Christ in them,
that therefore it is a mere natural and not a Divine light;
or because they assert Christ to be the Word of God,
and that he is revealed in the heart, according to the Scripture, and that the Scripture,
in that excellent sense, is not so;
that therefore they deny the Divine authority of the Scriptures,
and that the mind and truth thereof, as declared by them,
is not in any sense the word of the Lord to men.
Or because they do not receive the schoolmen`'s trinity,
that therefore they deny the Scripture-trinity of Father, Word and Spirit.
Or that therefore they deny the Divinity of Christ the Word.
Or that they deny Christ without them, who was the Son of Man,
in a suffering state on earth, and is now the Son of Man in glory,
because they exalt and press an experimental knowledge of Christ within, as the truth,
substance, and excellency of the hope of the glory that hereafter shall be revealed,
as being the riches of the glory of the mystery revealed,
and to be revealed in these latter days, according to the Scriptures of truth.
Neither do you say, they hope to be saved by their own works,
because they press the necessity of well-doing toward acceptance with God;
since they maintain,
that no works that are not wrought by the Spirit of God are acceptable with him;
or that they hold even such works to be meritorious, because they say,
good works are necessary and rewardable.
Or that they are forgiven for what they do, and not for what Christ did.
Or that they deny the use of means, because they reject ungospel ones.
Or that they deny baptism and the supper, because they say,
they are but signs of the spiritual grace, and that they served but for a time,
and that they experience their accomplishment.

Neither say that they are uncivil, and honour no man,
because they forbear such titles and ceremonies,
in which true honour and civility do not consist.
Or that they are against government, because they cannot out of tenderness,
and not obstinacy, conform to it in matters relating to religion and conscience;
in which Christ only is Lord and King.
Since, reader, you plainly see, that they believe the Light to be Divine,
and the Scriptures to be of Divine authority.
That they own the Scripture-trinity, or Holy three, of Father, Word and Spirit,
to be truly and properly one.
That Christ is God, and that Christ is man.
That he came in the flesh, died, rose again, ascended, and sits on God`'s right hand,
the only sacrifice and mediator, for man`'s happiness.
That truly Gospel means and ordinances are requisite, and to be reverently practised.
That good works are necessary and rewardable.
That all men are to be honoured in the Lord, according to their degrees.
And that government in church and state is God`'s ordinance,
and both requisite and very beneficial.

Now reader, that which remains,
is to recommend you to this holy Spirit of light and life,
which they make the root and spring of all true sense of God and religion in man.
Even the light within which they began with, and which comes from Christ,
and indeed is Christ the eternal Word,
and which brings all that follow the convictions and leadings of it, to Christ; that is,
to his nature, which is meek, patient, loving, humble, harmless, self-denying and holy;
and hereby to know him in themselves according to Scripture,
to be the hope of their eternal glory.
Who, as he is of Abraham after the flesh, so is he God over all blessed forever;
the true light, who enlightens all, in order to life and blessedness.
Unto the manifestation of whose most holy and blessed Light within, you, reader,
are earnestly exhorted.

Bring your deeds to it, and love it, and walk in it,
and you will assuredly have the light of life; and your fellowship shall be with God,
and with his Son and saints,
and the blood of Jesus Christ his Son shall cleanse you from all sin.
And whatsoever things are true, whatsoever thing are honest, whatsoever things are just,
whatsoever things are pure, whatsoever things are of good report, if there be any virtue,
and if there be any praise, think on these things.
Which reader, is, I know, most earnestly desired on your behalf,
by this despised and most abused people called Quakers.
So be it.
Amen.

=== Postscript.

Being an exhortation to all people, to turn speedily to the Lord,
and seek him while he may be found, whatever persuasion they are of,
or forms they are under, before the dreadful day of God`'s vengeance overtake them.

O you inhabitants of the world, but more especially you that know this people,
and among whom the testimony which they bear, has been held forth; hear,
and be entreated for your soul`'s sake!
O that you knew your Creator to be also your Redeemer! who does as certainly visit you
by the spirit of the second Adam as ever he created you in the nature of the first Adam.
That as in one you fell,
so in the other you may arise out of your fallen and foul estate, and become a reformed,
regenerate and chosen people to God.
This is my beloved Son, in whom I am well pleased, hear him, said God the Father.
And what says Christ, the Son?
Learn of me, for I am meek and lowly in heart, and you shall find rest unto your souls.
For, out of Christ; out of his spirit and nature, verily we cannot have peace.
No peace to the wicked, no peace to the proud and ungodly, says the Lord.
Friends, you must take up your cross daily and follow him,
or you cannot be his disciples, his followers, his people, his friends;
those in whom he is well pleased.
Whose doctrine is not so much the good words you read in creeds and catechisms,
as it is the living teaching of his Spirit in your own hearts;
and whose religion is not opinion, but experience; not notion, but enjoyment.
Life from death, and conversion, and regeneration: in short, undefiledness, and holiness,
without which no man shall see the Lord.

Here is the faith of Jesus.
A faith that overcomes the world, and works by love, not violence.
Where zeal and charity are companions,
and knowledge does not puff up but lives and works by obedience,
this is the faith and religion of Jesus:
all others are the faith and religion of hypocrites and devils; which they may have,
and be hypocrites and devils still.
For though they believe, their faith works not by love; and though they know the truth,
they obey it not.

Wherefore friends, it behooves you much to see what faith and religion you have;
and not flatter yourselves on to perdition.
If it be the true, the pure, the undefiled,
according to the apostle James 1:27. then you will have light hearts,
and easy consciences, and a hope that will not make you ashamed.
Else, believe it, heaviness,
anguish and tribulation will (whatever be your profession) overwhelm
you in the day that God shall enter into judgment with you.
For which cause, my dear country folks and people, be entreated while it is to day,
to turn unto the Lord with all your hearts, and hearken to his voice,
in your own consciences, that calls you to holiness,
and harden not your hearts against his reproof,
for the reproof of instruction is the way to life, endless life.
Did you but feel that God sees you everywhere and in everything, and that continually,
it would abundantly alter the case with you.
Then would you say as one of old, The Lord was here and I knew it not.
Fear, a holy fear would take hold of you,
an awe of the Omnipotent Majesty would seize you, and you would not do that before God,
which you would be ashamed men should see you do.
For no place is secret to him; the light and darkness are alike.
His witness is with you as much alone, as in company,
and may perhaps be better heard by you.

Sin not then in the face of God, in contempt of his witness,
in despite of his Spirit that is in you; but hear it, receive it, and love it,
and you will be born of it,
and become the children of him whose eye penetrates the darkest coverts,
and finds out the most secret corners;
even he that searches the heart and tries the reins of man,
and sets his sins in order before him, and tells unto him his most inward thoughts.

This being the case, what manner of persons ought you to be, you children of men!
Do not satisfy yourselves with out-sides, with a name, a profession, a church-membership, etc.
For it is not what you say, but what you do.
But turn in, and examine your own hearts,
see how they stand affected towards God and his law and truth in your inward parts.
Be strict and true in the search, as you would save your souls.
If your minds be set on heavenly things,
and holiness and charity be the zealous bent thereof, well will it be with you forever:
to live then will be Christ, and to die will be your everlasting gain.
For blessed is that people and nation whose God is the Lord.
But if the love and spirit of the world prevail; if pride, covetousness and luxury, envy,
bitterness and vain-glory,
that are so very opposite to the will and nature of God and his holy Lamb;
if these things have power over you, flatter not yourselves,
you cannot be true Christians, not in favour with God, for you take his name in vain.
And your very prayers and oblations are an abomination to the Lord, in that state.
God calls for the heart: My son, give me your heart.
He has given man the rest; but that, God will have for himself,
if man will have him for his God and friend.
Deceive not yourselves therefore, O you sons and daughters of Adam! for believe it,
such as you sow, such you must reap, and there is no repentance in the grave.
And a short but great work will God do in the earth; and great judgments,
of various kinds, will begin it, and they are at the door.
Yes, they are begun, if you could but see them.

Awake then, awake out of the sleep of this world!
Behold the Judge is at hand,
and the midnight cry is coming upon you as a thief in the night.
Prepare, prepare, or you are excluded forever!
And remember, salvation is from sin, or it will never be from wrath; so said the angel,
You shall call his name Jesus, for he shall save his people from their sins.
For it is the pure in heart that see God, and nothing unlike him can please him,
and less live with him forever.

The eternal God reach unto you by his powerful Spirit, break your peace in the broad way,
touch you deeply with a sense of your disobedience to him,
give you true contrition and repentance, and create in you a clean heart,
and renew a right spirit within you.
To conclude, make you holy, make you zealous, and make you charitable; that you may do,
as well as say, and not only profess,
but possess the truth of the living God in your inward parts; that pearl of price,
that hidden and eternal treasure.
So shall you know that the times of refreshing are come from the presence of the Lord,
and that the kingdom is again restored unto Israel!
Israel, the Prince of peace, who has prevailed with God for man;
whose sceptre is a sceptre of righteousness, and of whose dominion there shall be no end.
So come Lord Jesus; come quickly.
Amen.

Written in behalf of the said people, for the information and good of all, by

William Penn.

[.asterism]
'''

A periodical work published at this time in London, called the Athenian Mercury,
made an attack upon the Society of Friends.
In three of the numbers, objections were raised to their practice and doctrines.
In the first they were charged with being persecutors,
on account of the exercise of their discipline; and silly enthusiasts,
because they refused to swear.
In the second they were charged with speaking contemptibly of the Bible;
turning the Scriptures into jejune allegories.

In the third a number of doctrines are noted, on which Friends are, by these writers,
supposed to hold erroneous opinions.

To these several charges, William Penn returned an answer,
in a small work entitled "`The New Athenians, no noble Bereans.`"

In this tract he sufficiently exposed the unsoundness of the charges,
and vindicated the doctrine and practice of Friends.

Another valuable treatise written during this period of seclusion,
was entitled "`Some fruits of solitude,
in reflections and maxims relating to the conduct of human life.`"

Of this work I shall not attempt an analysis.
It is too dense to be abridged;--and too valuable to be mutilated.
The serious reader will find every part of it worthy of a careful perusal.

During this retirement, it probably was, that he produced a small work,
bearing the appearance of a political character,
but essentially a philanthropic and religious essay.
It was published, I apprehend, anonymously.
The date as given in the margin of this tract in his printed works, is 1695,
but is referred by his original biographer to this period.

The nations of Europe were, at that time, very generally engaged in a sanguinary war.
William Penn commiserating the sufferings inevitably attendant on these extensive hostilities,
made an effort to draw the attention of his contemporaries to a
more rational method of adjusting the controversies of nations.
In pursuance of this design,
he wrote "`An Essay toward the present and future peace of Europe,
by the establishment of an European diet, parliament or estates.`"
In this he first lays down the advantages of peace, and the evils, the dangers,
the expenses and desolations of war.
He then explains the ostensible object of war to be the establishment of justice,
but that a lawless ambition is a more common stimulant.
That justice in a government preserves the internal peace of a country,
but violence on the part of those in power,
seldom fails to excite discontent and insurrections among the people.
Domestic peace is maintained by justice, which is a fruit of government,
as government is from society, and society from consent.

In the third section he shows that the object of government
is the preservation of peace among its members.
That as by the restraint which government imposes upon the passions of individuals,
the prevention and redress of injuries, are entrusted to impartial hands,
each individual receives the protection of society, and thereby gains more than he loses,
by giving up the privilege of being judge and executioner in his own cause.

He then suggests the expediency of applying the same principles to the disputes of nations,
which are applied to those of individuals;
by forming a general congress among the princes of Europe,
by which a code of laws for the regulation of their mutual interactions,
should be established, and to which they should all be required to submit.

He next shows that the usual causes of war would be in great
measure removed by the establishment of such a tribunal,
without the necessity of exercising its compulsive power.

A number of objections which may be offered to the plan,
are afterwards stated and answered.

In the last section,
the various advantages which would result from the adoption of the plan are enumerated.

First, The effusion of blood, and the tears of the numerous widows and orphans,
consequent upon war, would be spared.

Second, The reputation of Christianity,
which has been greatly impaired in the view of unbelieving nations,
by the prosecution of war, would be restored.
The Author of Christianity is emphatically styled the Prince of peace.
In his kingdom the lion is to lie down with the lamb; not the lamb with the lion.

Third, The enormous expenditures of war would be saved;
and the resources of nations might therefore be applied
to objects directly conducive to general prosperity.

Fourth, The desolation of towns and countries,
of which various parts of Europe had recently furnished such terrible examples,
would be saved.

Fifth, The convenience and safety of commerce and travelling would be greatly promoted.
The perplexities and delays to which travellers are subjected
from the jealousy of the various governments of Europe,
would be avoided;
and the advantages of a universal government without its evils be attained.

Other advantages are noticed,
particularly the facility which this plan would afford to a personal interaction,
and consequent friendship, among the princes of Europe.
By which means they would be enabled to choose their wives themselves,
instead of performing it by proxy.
Marriages might thus be founded upon personal attachment,
and not upon mere considerations of interest,
as they too generally are among that class of people.
Hence more harmony, and a more virtuous education of their children,
might be expected to exist in the families of princes.

Finally, In the conclusion, he shows that a plan, nearly analogous to his,
had been actually adopted to a limited extent, in some provinces of the Netherlands;
and that Henry IV, one of the greatest monarchs who ever reigned in France,
had it in contemplation to compel the princes to adopt one of a similar character,
when he was suddenly cut off by the hand of an assassin.
He adds, "`this great king`'s example tells us it is fit to be done;
Sir William Temple`'s history shows us by a surpassing instance, that it may be done;
and Europe by her incomparable miseries, makes it now necessary to be done.`"

The following letter written in the autumn of 1693, while he remained in retirement,
shows the warmth of his friendship,
and the state of piety in which his mind was preserved:

Dear Friend,

I was surprised last night, when I was told of your great illness and weakness,
and desire to see me.
Surely had I ever heard it I should have broken through
all my exercises to have seen you;
and I cannot express my trouble that my landlord should not have told it me,
though ordered by Joseph B. seventh-day week;
and truly I wonder Joseph never hinted it himself.
I now dispatch my kinsman this morning to hear of the state of your health,
desiring of the Lord his merciful lovingkindness towards you and yours in your preservation.
And I pray God sanctify this visitation to you on your better part`'s account,
that Truth in the inward parts may get ground,
and the testimony and cross of Jesus may prevail to your prosperity every way.
I have been thinking to see you sometimes; then interrupted by sorrowful occasions;
then of writing to your dear wife, whom I love and esteem above most I know,
and with my letter of sending her a few books: but I know not how I have been prevented.
The all-wise God give us faith to believe all shall work together for the best!
So, with our true love and concern for you and yours, I rest your most assured friend,

William Penn.

William Penn had now been about three years, in great measure, secluded from the world,
and from the public service of society.
It is probable that many who were acquainted with the rumours of the day,
gave credit to the charges against him.
Yet there were a number of men conspicuous for their talents and standing in the world,
who had formed a more just estimate of his character.
Among these was the celebrated John Locke,
who had returned to England in the same fleet with the princess of Orange.
Finding in what manner William Penn was persecuted, he used his interest with the king,
to procure a pardon for his supposed offences.
But William Penn had too much regard for his own character,
and was too confident that his innocence would be eventually proved,
to accept of enlargement upon conditions which implied
that he had been guilty of an offence.
Several noblemen, conscious of his worth,
and fully convinced that the charges against him were unfounded,
interested themselves in his favour.

Three of them, Ranelagh, Rochester and Sidney, went together,
and represented the hardship of his case to the king.
They stated that there was nothing against him but what was advanced by impostors,
or such as had fled their country; or by men, who, when pardoned for their crimes,
had refused to verify their charges.
They had themselves long known William Penn, some of them not less than thirty years,
and had never known him do an ill action, but many good ones;
and that it was because he was unwilling to incur the suspicion
of leaving the country in defiance of government,
that he had continued in it.
King William told them that William Penn was his old acquaintance, as well as theirs,
and that he might follow his business as freely as ever,
for he had nothing to say against him.
At their request,
Lord Sidney was authorized to communicate the king`'s declaration to Sir John Trenchard,
the principal secretary of state.
The secretary upon receiving this information, was well pleased,
and acknowledged that he was under personal obligations to William Penn.
He afterwards received a direct command of similar import, from the king,
in consequence of which, he informed William Penn,
in the presence of the Marquis of Winchester, that he was as free as ever,
and assured him that he should not be molested nor injured
in any of his affairs as long as he held the post he did.
It however, appears probable,
that William Penn was desirous his innocence should be more openly acknowledged,
for we find that he appeared before the king and council,
where he so successfully pleaded his cause as to obtain a full acquittal.

Though the cloud which had so long hung over him was now dissipated,
and his innocency clearly established, yet another heavy trial,
and one that affected the tenderest sensibilities of his heart, was at hand.
In about a month after his discharge his wife was removed by death.

Of the character of this amiable woman we have a portrait,
beside that given by her husband, drawn by an able hand,
from an intimate knowledge of her accomplishments and worth.
Thomas Ellwood, in his account of his own life, frequently mentions her,
and always in terms which give a favourable impression of her character.
It may be remembered that a short time previous to her birth, her mother became a widow,
and was afterwards married to Isaac Penington.
Before Thomas had espoused the principles of Friends,
he accompanied his father on a visit to that family.
He was then a sprightly young man, and having known Gulielma in her childhood,
he took care to cast himself in her way, as she was gathering flowers in the garden,
accompanied by her maid.
He addressed her in his customary way, with a view of engaging her in familiar discourse.
She treated him courteously, yet young as she was, being then only about fifteen,
the gravity of her look and behaviour struck such an awe upon him,
that he found himself unable to make any further attempt at conversation with her.
He therefore asked pardon for having intruded into her private walks and withdrew.

When she arrived at a marriageable age, as her person was comely,
her mental endowments in every respect extraordinary, and her estate considerable,
she was much sought after, by men of various conditions and character;
but she conducted herself with singular prudence and propriety;
giving encouragement to none, until he came whom she accepted,
and yet affording no just cause of offence to any.

A number of years after her marriage, and while her husband was in America,
we meet with an instance in which her worth was attested by men,
who do not appear to have been prejudiced in favour of the Society.

Soon after the discovery of the Ryehouse plot,
Thomas Ellwood was summoned to appear before two justices of the peace,
who lived in the neighbourhood where William Penn
had resided for some years after his marriage.
The charge against him was founded upon a book which he had recently published,
and although that book had no connection with the plot,
the Earl of Bridgewaler directed that the author should be arrested.
It so happened, that shortly after this citation was received,
a message came to him from Gulielma Penn, informing him that she was dangerously ill,
and was very desirous of seeing him.
To attend to this request without neglecting the summons,
he immediately called on the justices and informed them of the case.
They both expressed their regard for Madam Perm, as they called her,
manifesting a strong desire to leave him at liberty to attend to her request;
and although they seemed to consider his case as a serious one,
they eventually set him at liberty upon his giving them a verbal assurance that he would,
if at liberty, appear before them whenever they might require it;
and notwithstanding the orders under which those justices were then acting,
they gave him no further trouble on the subject.
He, in that case, attributed his escape, under providential disposal,
from a troublesome prosecution,
to the well-merited esteem which those justices entertained
for the virtues of Gulielma Maria Penn.

But the best account of her character and end, is given by her husband,
which containing several edifying passages, is here inserted.

My dear wife,
after eight months illness (though she never perfectly
recovered her weakness the year before,
which held her about six months) departed this life the 23rd of the twelfth month,
1693-4, about half an hour past two in the afternoon, being the sixth day of the week,
and the fiftieth year of her age, and was sensible to the very last.

During her illness she uttered many living and weighty expressions,
upon several occasions, both before and near her end.
Some of which I took down for my and her dear children`'s consolation.

At one of the many meetings held in her chamber,
we and our children and one of our servants only being present,
in a tendering and living power she broke out as she sat in her chair,
'`Let us all prepare, not knowing what hour or watch the Lord comes.
O, I am full of matter! shall we receive good,
and shall we not receive evil things at the hand of the Lord?
I have cast my care upon the Lord; he is the physician of value;
my expectation is wholly from him.
He can raise up and he can cast down.`' A while after she said,
'`Oh what shall be done to the unprofitable servant?`' At another meeting,
before which much heaviness seemed to lie upon her natural spirits, she said,
'`This has been a precious opportunity to me; I am finely relieved and comforted,
blessed be the Lord.`' At another time,
as I was speaking to her of the Lord`'s love and
the witness of his Spirit that was with her,
to give her the peace of well doing, she returned to me, looking up, she said,
'`I never did, to my knowledge, a wicked thing in all my life.`'

To a friend aged seventy-five years that came to see her, she said,
you and I to all appearance are near our ends.
And to another about sixty-five years old, who came also to see her, she said,
'`how much older has the Lord made me by this weakness, than you are! but I am contented,
I do not murmur; I submit to his holy will.`'

In the strength of her disease she said, '`it is the great goodness of the Lord,
that I should be able to lie thus still.
He is the physician of value to me, can I say; let my tongue set forth his praise,
and my spirit magnify him while I have breath.
O, I am ready to be transported beyond my strength.
God was not in the thunder, nor in the lightning,
but he was heard in the still voice.`' She did at several times pray very sweetly,
and in all her weakness manifested the most equal, undaunted and resigned spirit,
as well as in all other respects.
She was an excellent example both as a child, wife, mother, mistress,
friend and neighbour.

She called the children one day when weak, and said, '`Be not affrighted children,
I do not call you to take my leave of you, but to see you,
and I would have you walk in the fear of the Lord,
and with his people in his holy Truth,`' or to that effect.

Speaking at another time solemnly to the children, she said,
'`I never desired any great things for you,
but that you may fear the Lord and walk in his Truth, among his people,
to the end of your days,`' etc.

She would not allow me to neglect any public meeting, after I had my liberty,
upon her account, saying often, '`O go my dearest! do not hinder any good for me.
I desire you go: I have cast my care upon the Lord: I shall see you again.`'

"`About three hours before her end, a relation taking leave of her, she said again,
'`I have cast my care upon the Lord.
My dear love to all Friends,
and (lifting up her dying hands and eyes) prayed the Lord
to preserve them and bless them.`' About an hour after,
causing all to withdraw, we were half an hour together, in which we took our last leave,
saying all that was fit upon that solemn occasion.
She continued sensible, and did eat something about an hour before her departure;
at which time our children, and most of the family were present.
She quietly expired in my arms, her head upon my bosom,
with a sensible and devout resignation of her soul to Almighty God.
I hope I may say, she was a public as well as private loss.

For she was not only an excellent wife and mother, but an entire and constant friend,
of more than common capacity, and great modesty and humility;
yet most equal and undaunted in danger.
Religious as well as ingenuous, without affectation.
An easy mistress, and good neighbour, especially to the poor.
Neither lavish, nor penurious, but an example of industry, as well as of other virtues.
Therefore our great loss is her own eternal gain.`"

Before passing from the events of 1693,
it may be proper to take a transient notice of the charges against William Penn,
which stand uncontradicted in the pages of some respectable historians.
Bishop Burnet, in relating the circumstance of the capture of Lord Preston,
and his companions,
and the discovery of the efforts which they were making for the restoration of James,
expressly asserts that he was one of those by whom the plan was laid.
He afterwards relates, that when Preston and Ashton were tried and convicted,
the Earl of Clarendon was seized and committed to the tower, but the Bishop of Ely,
Graham, and Penn absconded.
And this account is followed by Smollet.
Hence, we should infer that the participation of William Penn in this conspiracy,
was an unquestionable fact;
and that he had either fled his country or concealed his
person so as to elude the search of the officers of justice.
If the fidelity of history required the relation that William
Penn was accused of taking part in this treasonable proceeding,
it would have been nothing more than fair to state also,
that among the letters found in possession of Ashton none were written by him,
nor was he mentioned in them;
and that so far was he from absconding in the usual acceptation of the term,
he remained in London,
and eventually established his innocence to the satisfaction of the king and council.
The historian who has transmitted to posterity these unqualified
and unmitigated charges upon the character of William Penn,
could hardly have been ignorant that he sustained soon after these reputed treasons,
a public character, both in his own Society and in the world;
that he openly travelled through his native country as a minister of the Gospel--that
he held the highly conspicuous station of Proprietary and Governor of Pennsylvania--and
that he was neither an unfrequent nor unwelcome visitor at the court of queen Ann.

William Penn is also charged,
about the same time by an historian of less celebrity than Bishop Burnet,
with holding a treasonable correspondence with the emissaries of the exiled king.
In the original papers published by Macpherson,
he is represented as giving his advice to Williamson
who had been sent over to England as a spy,
to collect information conducive to the restoration of James.

The information received through the medium of spies and conspirators,
ought unquestionably to be admitted, if admitted at all, with the utmost caution;
and never credited when it is improbable in itself
and unsupported by circumstantial evidence.
But the part which William Penn is represented, in the narrative of Williamson,
to have taken, is totally inconsistent with the whole tenor of his life,
and supported by no testimony except the declaration of the informer; and may therefore,
be safely considered as a sheer fabrication.
But to stamp the proper stigma upon such accusations,
we find him near twenty years afterwards, represented upon the authority of an Irish spy,
as plotting in favour of the pretender,
at a time when it is well known that his memory and
understanding were so far impaired by disease,
that he was incapable of transacting the ordinary affairs of life.
