== Chapter XXVII.

About fifteen years had now passed away since William Penn left his province in America.
In the year to which we have arrived, he found his way open to return.
On his former visit, we may remember, he left his family behind;
but he now resolved upon taking his wife and children with him;
expecting in all probability to spend the remainder of his days in Pennsylvania.

In the course of this year, 1699,
and probably while he was preparing for his American voyage,
he wrote the following tract, which is a valuable compendium of Christian morality,
deserving the serious perusal of every person,
especially those in the early walks of life.

[.asterism]
'''

[.old-style]
=== The Advice of William Penn to His Children, Relating to Their Civil and Religious Conduct. / Section I.

[.salutation]
My dear children,

Not knowing how long it may please God to continue me among you,
I am willing to embrace this opportunity of leaving you my advice and counsel,
with respect to your Christian and civil capacity and duty in this world:
and I both beseech you and charge you, by the relation you have to me,
and the affection I have always shown to you, and indeed received from you,
that you lay up the same in your hearts, as well as your heads,
with a wise and religious care.

I will begin with that which is the beginning of all true wisdom and happiness,
the holy fear of God.

Children, fear God; that is to say,
have a holy awe upon your minds to avoid that which is evil,
and a strict care to embrace and do that which is good.
The measure and standard of which knowledge and duty,
is the light of Christ in your consciences, by which, as in John 3:20-21.,
you may clearly see if your deeds, aye and your words and thoughts too,
are wrought in God or not; for thoughts are the deeds of the mind,
for which you must be judged.
I say with this Divine light of Christ in your consciences, you may bring your thoughts,
words and works, to judgment in yourselves,
and have a right true sound and unerring sense of your duty towards God and man.
And as you come to obey this blessed light in its holy convictions,
it will lead you out of the world`'s dark and degenerate ways and works,
and bring you unto Christ`'s way and life,
and to be of the number of his true self-denying followers,
to take up your cross for his sake, who bore his for yours;
and to become the children of the light, putting it on, as your holy armour;
by which you may see and resist the fiery darts of Satan`'s temptations,
and overcome him in all his assaults.

I would a little explain this to you.
Christ is called light, John 1:9, chapter 3:19, 20, 21, and chapter 8:12.
Eph. 5:13-8. 1 Thess. 5:5. First Epistle of John 1:0,5,7. Rev. 21:23.,
because he gives man a sight of his sin.
And he is also called the quickening Spirit; and the Lord from heaven,
as 1 Cor. 15:45,47, who is called and calls himself the Light of the world,
John 8:12, and why is he called the Spirit?
Because he gives man spiritual life.
And John 16:8. Christ promised to send his Spirit to convince the world of their sins:
wherefore that which convinces you and all people of their sins, is the Spirit of Christ.
This is highly prized, Rom. 8.
as you may read in that great and sweet chapter, for the children of God are led by it.
This reveals the things of God, that appertain to man`'s salvation and happiness,
as 1 Cor. 2:10-12. It is the earnest God gives his people. 2 Cor. 5:5.
It is the great end and benefit and blessing of the coming of Christ,
namely, The shining forth of this light and pouring forth of this spirit.
Yes, Christ is not received by them that resist his light and Spirit in their hearts;
nor can they have the benefit of his birth, life, death, resurrection, intercession, etc.,
who rebel against the light.
God sent his Son to bless us, in turning us from the evil of our ways:
therefore have a care of evil, for that turns you away from God;
and wherein you have done evil, do so no more: but be turned, my dear children,
from evil, in thought, as well as in word and deed, or that will turn you from God,
your Creator, and Christ whom he has given you for your Redeemer;
who redeems and saves his people from their sins. Tit. 2:14.
, not in their sins.
Read Acts ii.
and Heb.
viii.
and the Christian dispensation will appear to be that of the Spirit, which sin quenches,
hardens the heart against, and bolts the door upon.
This holy Divine principle is called grace too, 1 Tit. 2:11-12.,
there you will see the nature and office of it,
and its blessed effects upon those that were taught of it in the primitive days.
And why grace?
Because it is God`'s love and not our desert, his goodwill, his kindness.
'`He so loved the world, that he gave his only begotten Son into the world,
that whosoever believes in him should not perish,
but have everlasting life;`' and this holy Son is declared in John 1:14,16,
to be full of grace and truth, and that of his grace we receive grace for grace, that is,
we receive of him the fulness, what measure of grace we need.
And the Lord told Paul in his great trials,
when ready to stagger about the sufficiency of the grace he had received, to deliver him,
'`My grace is sufficient for you.`' O children, love the grace, hearken to this grace,
it will teach you, it will sanctify you, it will lead you to the rest and kingdom of God,
as it taught the saints of old first, what to deny, that is:
'`To deny ungodliness and worldly lusts;`' and then what to do, namely:
'`to live soberly,
righteously and godly in this present world.`' And he who is full of grace,
is full of light, and he who is full of light is the quickening Spirit,
who gives a manifestation of his Spirit to every one to profit with. 1 Cor. 12:7.
And he that is the quickening Spirit is the Truth.
I am the way, the truth and the life, said he, to his poor followers, John 14:6.
And if the Truth make you free, said he to the Jews,
then are you free indeed. John 8:32,36.
And this Truth sheds abroad itself in man,
and begets truth in the inward parts, and makes false, rebellious, hypocritical man,
a true man to God again.
Truth in the inward parts is of great price with the Lord.
And why is it called Truth?
Because it tells man the truth of his spiritual state; it shows him his state,
deals plainly with him, and sets his sins in order before him.
So that my dear children, the light, spirit,
grace and truth are not different principles,
but different words or denominations given to one
eternal power and heavenly Spirit in you,
though not of you, but of God,
according to the manifestation or operation thereof in the servants of God of old time:
light to discover and give discerning: Spirit to quicken and enliven: grace, that is,
the love of God: Truth, because it tells man the truth of his condition,
and redeems him from the errors of his ways; that as darkness, death,
sin and error are the same, so light, spirit, grace and Truth are the same.

This is that which is come by Christ, and a measure of this light, spirit,
grace and truth, is given to every man and woman to see their way to go by.
This is that, which distinguishes Friends from all other societies,
as they are found walking in the same, which leads out of the vain honours, compliments,
lusts and pleasures of the world.

O my dear children, this is the pearl of price, part with all for it,
but never part with it for all the world.
This is the Gospel leaven, to leaven you, that is, sanctify and season you in body,
soul and spirit, to God, your heavenly Father`'s use and service,
and your own lasting comfort.
Yes, this is the Divine and incorruptible Seed of the kingdom;
of which all truly regenerate men and women, christians of Christ`'s making, are born.
Receive it into your hearts, give it room there, let it take deep root in you,
and you will be fruitful unto God in every good word and work.
As you take heed to it and the holy enlightenings and motions of it,
you will have a perfect discerning of the spirit of this world,
in all its appearances in yourselves and others; the motions,
temptations and workings of it, as to pride, vanity, covetousness, revenge, uncleanness,
hypocrisy and every evil way; you will see the world in all its shapes and features,
and you will be able to judge the world by it,
and the spirit of the world in all its appearances:
you will see as I have done that there is much to deny, much to suffer and much to do:
and you will see that there is no power or virtue, but in the light, spirit,
grace and truth of Christ,
to carry you through the world to God`'s glory and your everlasting peace.
Yes, you will see what religion is from above, and what is from below;
what is of God`'s working, and of man`'s making and forcing;
also what ministry is of his Spirit and giving, and what of man`'s studying,
framing and imposing.
You will, I say, discern the rise, nature,
tokens and fruits of the true from the false ministry, and what worship is spiritual,
and what carnal; and what honour is of God, and what that honour is, which is from below,
of men, yes, fallen men, which the Jews and the world so generally love,
and which is spoken against in John 5:44. You will see the vain and evil communication,
that corrupts good manners; the snares of much company and business,
and especially the danger of the friendship of this present evil world.
And you will also see,
that the testimony unto which the eternal God has brought our poor Friends,
as to religion, worship, truth-speaking, ministry, plainness, simplicity,
and moderation in apparel, furniture, food, salutation,
as you may read in their writings, from the very beginning,
is a true and heavenly testimony of his mind, will,
work and dispensation in this last age of the world to mankind,
being the revival of true primitive Christianity:
where your most tender father prays that you may be kept,
and charges you to watch that you may be preserved
in the faith and practice of that blessed testimony;
and count it no small mercy from God, and honour to you,
that you come of parents who counted nothing too dear or near to part with,
nor too great to do or suffer, that they might approve themselves to God,
and testify their love to his most precious Truth in the inward parts,
in their generation.

I do also charge you, my dear children,
to retain in your remembrance those worthy ancients in the work of Christ,
who remained alive to your day and memory, and yet remain to your knowledge;
more especially that man of God and prince in Israel,
the first-born and begotten of our day and age of truth,
and the first and the great early instrument of God among us, George Fox.
And what you have heard, seen and observed, of those heavenly worthies,
their holy wisdom, zeal, love, labours and sufferings, and particular tenderness to you,
treasure up for your children after you, and tell them what you have heard,
seen and known, of the servants and work of God, and progress thereof, as a holy,
exemplary, and edifying tradition unto them.
And be sure, that you forsake not the assembling yourselves with God`'s people,
as the manner of some was, Heb. 10:25., and is at this day,
especially among young people, the children of some Friends,
whom the love of this present evil world has hurt
and cooled in their love to God and his Truth.
But do you keep close to meetings, both of worship and business of the church,
when of an age and capacity proper for it; and that not out of novelty, formality,
or to be seen of men, but in pure fear, love and conscience to God your Creator,
as the public, just and avowed testimony of your duty and homage to him.
In which be exemplary both by timely coming and a
reverent and serious deportment during the assembly;
in which, be not weary or think the time long till it be over,
as some did of the sabbaths of old;
but let your eye be to him whom you come to wait upon and serve,
and do what you do as to him, and he will be your refreshment and reward;
for you shall return with the seals and pledges of his love, mercy and blessings.

Above all things, my dear children, as to your communion and fellowship with Friends,
be careful to keep the unity of the faith in the bond of peace.
Have a care of reflectors, detractors and backbiters,
who undervalue and undermine brethren behind their backs,
or slight the good and wholesome order of Truth, for preserving things quiet,
sweet and honourable in the church.
Have a care of novelties and airy changeable people, the conceited,
censorious and puffed up;
who at last have always shown themselves to be clouds without rain,
and wells without water;
who will rather disturb and break the peace and fellowship of the church,
where they dwell, than not have their wills and ways take place.
I charge you in the fear of the living God, that you carefully beware of all such:
mark them as the apostle says, Rom. 16:17, and have no fellowship with them;
but to advise, exhort, entreat and finally reprove them. Eph. 5:11.
For God is and will be with his people
in this holy dispensation which we are now under,
and which is among us, unto the end of days: it shall grow and increase in gifts,
graces, power and lustre, for it is the last and unchangeable one:
and blessed are your eyes, if they see it, and your ears if they hear it,
and your hearts if they understand it;
which I pray that you may to God`'s glory and your everlasting comfort.

Having thus expressed myself to you, my dear children, as to the things of God,
his Truth and kingdom, I refer you to his light, grace, Spirit and Truth within you,
and to the Holy Scriptures of Truth without you, which from my youth I loved to read,
and were ever blessed to me, and which I charge you to read daily;
the Old Testament for history chiefly, the Psalms for meditation and devotion,
the prophets for comfort and hope, but especially the New Testament for doctrine,
faith and worship: for they were given forth by holy men of God in various ages,
as they were moved of the holy Spirit;
and they are the declared and revealed mind and will of the holy God to mankind,
under various dispensations, and they are certainly able to make the man of God perfect,
through faith unto salvation;
being a true and clear testimony to the salvation that is of God,
through Christ the second Adam, the light of the world, the quickening Spirit,
who is full of grace and truth; whose light, grace,
Spirit and Truth bear witness to them in every sensible soul, as they frequently,
plainly and solemnly bear testimony to the light, spirit, grace and truth,
both in himself and in and to his people, to their sanctification, justification,
redemption and consolation; and in all men to their visitation,
reproof and conviction of their evil ways.
I say, having thus expressed myself in general, I refer you, my dear children,
to the light and Spirit of Jesus, that is within you,
and to the Scriptures of Truth without you,
and such other testimonies to the one same eternal Truth as have been borne in our day;
and shall now descend to particulars,
that you may more directly apply what I have said in general both as to
your religious and civil direction in your pilgrimage upon earth.

[.blurb]
=== Section II.

I will begin here also, with the beginning of time, the morning: so soon as you wake,
retire your minds into a pure silence, from all thoughts and ideas of worldly things,
and in that frame wait upon God, to feel his good presence,
to lift up your hearts to him,
and commit your whole self into his blessed care and protection.
Then rise, if well, immediately: being dressed, read a chapter or more in the Scriptures,
and afterwards dispose yourselves for the business of the day;
ever remembering that God is present, the overseer of all your thoughts,
words and actions; and demean yourselves, my dear children, accordingly;
and do not you dare to do that in his holy all-seeing presence,
which you would be ashamed a man, yes a child, should see you do.
As you have intervals, from your lawful occasions, delight to step home,
within yourselves, I mean, and commune with your own hearts, and be still;
and as Nebuchadnezzar said on another occasion,
you shall find and enjoy one like the Son of God, with you and in you;
a treasure the world knows not of, but which is the aim,
end and diadem of the children of God.
This will bear you up against all temptations,
and carry you sweetly and evenly through your day`'s business,
supporting you under disappointments,
and moderating your satisfaction in success and prosperity.
The evening being come, read again the holy Scripture,
and have your times of retirement before you close your eyes, as in the morning;
that so the Lord may be the Alpha and Omega of every day of your lives.
And if God bless you with families, remember good Joshua`'s resolution,
"`But as for me and my house, we will serve the Lord.`"

Fear God: show it in desire, refraining and doing: keep the inward watch;
keep a clear soul and a light heart.
Mind an inward sense, upon doing anything; when you read the Scripture,
remark the most notable places, as your spirits are most touched and affected,
in a common-place book, with that sense or opening which you receive;
for they come not by study or in the will of man, no more than the Scripture did;
and they may be lost by carelessness,
and the over growing thoughts and business of this life;
so in perusing any other good or profitable book; yet rather meditate than read much.
For the spirit of a man knows the things of a man, and with that spirit,
by observation of the tempers and actions of men you see in the world,
and looking into your own spirit and meditating thereupon,
you will have a deep and strong judgment of men and things.
For from what may be, what should be, and what is most probable or likely to be,
you can hardly miss in your judgment of human affairs;
and you have a better spirit than your own, in reserve for a time of need,
to pass the final judgment in important matters.

In conversation, mark well what others say or do, and hide your own mind,
at least till last; and then open it as sparingly as the matter will let you.
A just observance and reflection, upon men and things, give wisdom;
these are the great books of learning seldom read.
The laborious bee draws honey from every flower.
Be always on your watch, but especially in company:
then be sure to have your wits about you, and your armour on; speak last and little,
but to the point.
Interrupt none; anticipate none: '`Be quick to hear,
slow to speak.`' It gives time to understand, and ripens an answer.
Affect not words, but matter, and chiefly to be pertinent and plain:
truest eloquence is plainest, and brief speaking, I mean brevity and clearness,
to make yourselves easily understood by every body,
and in as few words as the matter will admit of, is the best.

Prefer the aged, the virtuous and the knowing,
and choose those that excel for your company and friendship, but despise not others.
Return no answer to anger, unless with much meekness, which often turns it away:
but rarely make replies, less rejoinders; for these add fuel to the fire.
It is a wrong time to vindicate yourselves, the true ear being then never open to hear it.
Men are not themselves, and know not well what spirits they are of: silence, to passion,
prejudice and mockery, is the best answer, and often conquers what resistance inflames.

Learn and teach your children fair writing, and the most useful parts of mathematics,
and some business when young, whatever else they are taught.
Cast up your income and live on half; if you can, on one third,
reserving the rest for casualties, charities, portions.
Be plain in clothes, furniture and food, but clean, and then the coarser the better,
the rest is folly and a snare.
Therefore, next to sin, avoid daintiness and choiceness about your persons and houses.
For if it be not an evil in itself, it is a temptation to it;
and maybe accounted a nest for sin to brood in.
Avoid differences; what are not avoidable, refer,
and keep awards strictly and without grudgings; read Prov. 18:17-18. xxv.
8+++.+++ Matt. 5:38 to 41. 1 Cor. 1:10 to 13. It is good counsel.

Be sure to draw your affairs into as narrow a compass as you can,
and into method and proportion, time and other requisites proper for them.
Have very few acquaintances and fewer intimates, but of the best in their kind.
Keep your own secrets, and do not covet others, but if trusted, never reveal them,
unless mischievous to some body; nor then, before warning the party to desist and repent.
Trust no man with the main chance, and avoid to be trusted.
Make few resolutions, but keep them strictly.
Prefer elders and strangers on all occasions;
be rather last than first in conveniency and respect; but first in all virtues.

Have a care of trusting to after games, for then there is but one throw for all;
and precipices are ill places to build upon.
Wisdom gains time, is before hand, and teaches to choose seasonably and pertinently;
therefore ever strike while the iron is hot.
But if you lose an opportunity, it differs in this from a relapse;
less caution and more resolution and industry must recover it.

Above all, remember your Creator: remember yourselves and your families,
when you have them, in the youthful time and forepart of your life;
for good methods and habits obtained then,
will make you easy and happy the rest of your days.
Every estate has its snare: youth and middle age, pleasure and ambition; old age, avarice.
Remember, I tell you, that man is a slave where either prevails.
Beware of the pernicious lusts of the eye and the flesh, and the pride of life,
which are not of the Father, but of the world.
Get higher and nobler objects, for your immortal part, my dear children,
and be not tied to things without you;
for then you can never have the true and free enjoyment of yourselves, to better things;
no more than a slave, in Algiers, has of his house or family in London.
Be free, live at home, in yourselves I mean, where greater treasures lie hidden,
than in the Indies.
The pomp, honour and luxury of the world, are cheats,
and the unthinking and inconsiderate are taken by them.
But the retired man is upon higher ground; he sees and is aware of the trick,
contemns the folly and bemoans the deluded.
This very consideration, doubtless,
produced those two passions in the two greatest gentiles of their time,
Democritus and Heraclitus; the one laughing, the other weeping,
for the madness of the world, to see so excellent and reasonable a creature as man,
so meanly trifling and lavishly employed.

Choose God`'s trades before men`'s: Adam was a gardener, Cain a ploughman,
and Abel a grazier or shepherd: these began with the world,
and have least of snare and most of use.
When Cain became a murderer, as a witty man said, he turned a builder of cities,
and quitted his husbandry: mechanics, as handicrafts, are also commendable,
but they are but a second brood and younger brothers.
If grace employ you not, let nature and useful arts; but avoid curiosity there also,
for it devours much time to no profit.
I have seen the ceiling of a room, that cost half as much as the house;
a folly and sin too.

Have but few books, but let them be well chosen and well read,
whether of religious or civil subjects.
Shun fantastic opinions: measure both religion and learning by practice;
reduce all to that, for that brings a real benefit to you,
the rest is a thief and a snare.
And indeed, reading many books is but taking off the mind too much from meditation.
Reading yourselves and nature, in the dealings and conduct of men,
is the truest human wisdom.
The spirit of a man knows the things of man,
and more true knowledge comes by meditation and just reflection, than by reading;
much reading is an oppression of the mind, and extinguishes the natural candle;
which is the reason of so many senseless scholars in the world.
Do not that which you blame in another.
Do not that to another which you would not another should do to you.
But above all, do not that in God`'s sight which you would not man should see you do.

That you may order all things profitably, divide your day:
a share of time for your retirement and worship of God; a proportion for your business;
in which remember to ply that first which is first to be done;
so much time for yourselves, be it for study, walking, visits, etc.
In this be first, and let your friends know it,
and you will cut off many impertinences and interruptions,
and save a treasure of time to yourselves, which people most unaccountably lavish away.
And to be more exact, for much lies in this, keep a short journal of your time,
though a day require but a line; many advantages flow from it.

Keep close to the meetings of God`'s people; and wait diligently at them,
to feel the heavenly life in your hearts.
Look for that more than words in ministry, and you will profit most.
Above all look to the Lord, but despise not instruments, man or woman, young or old,
rich or poor, learned or unlearned.

Avoid discontented persons, unless to inform or reprove them.
Abhor detraction, the sin of fallen angels, and the worst of fallen men.
Excuse faults in others, own them in yourselves, and forgive them against yourselves,
as you would have your heavenly Father and Judge forgive you.
Read Prov. 17:9. and Matt. 6:14-15. Christ
returns and dwells upon that passage of his prayer,
above all the rest, forgiveness, the hardest lesson to man,
who of all other creatures most needs it.

Be natural; love one another; and remember, that to be void of natural affection,
is a mark of apostacy set by the apostle, 2 Tim. 3:3. Let not time, I charge you,
wear out nature.
It may wear out kindred according to custom, but it is an ill one,
therefore follow it not.
It is a great fault in families at this day: have a care of it,
and shun that unnatural carelessness.
Live as near as you can, visit often, correspond oftener,
and communicate with kind hearts to one another,
in proportion to what the Lord gives you; and do not be close,
nor hoard up from one another as if you had no right or claim in one another,
and did not descend of one most tender father and mother.

What I write is to yours, as well as you, if God gives you children.
And in case a prodigal should ever appear among them,
make not his folly an excuse to be strange or close,
and so to expose such a one to more evil.
But show bowels, as John did to the young man that fell into ill company,
whom with love he reclaimed, after His example that sends his sun and rain upon all.

Love silence, even in the mind; for thoughts are to that, as words to the body,
troublesome; much speaking, as much thinking, spends, and in many thoughts,
as well as words, there is sin.
True silence is the rest of the mind, and is to the spirit, what sleep is to the body,
nourishment and refreshment.
It is a great virtue; it covers folly, keeps secrets, avoids disputes, and prevents sin.

The wisdom of nations lies in their proverbs, which are brief and pithy;
collect and learn them, they are notable measures and directions for human life;
you have much in little; they save time in speaking; and upon occasion,
may be the fullest and safest answers.

Never meddle with other folks`' business, and less with the public,
unless called to the one by the parties concerned,
in which move cautiously and uprightly;
and required to the other by the Lord in a testimony for his name and Truth;
remembering that old, but most true and excellent proverb,
He lives happily who lives hiddenly or privately, for he lives quietly.
It is a treasure to them that have it: study it, get it, keep it;
too many miss it who might have it: the world knows not the value of it.
It doubles man`'s life, by giving him twice the time to himself,
that a large acquaintance or much business will allow him.

Have a care of resentment, or taking things amiss, a natural,
ready and most dangerous passion; but be apter to remit than resent,
it is more christian and wise.
For as softness often conquers, where rough opposition fortifies; so resentment,
seldom knowing any bounds, makes many times greater faults than it finds;
for some people have out-resented their wrong so far,
that they made themselves more faults by it,
by which they cancel the debt through a boundless passion,
overthrow their interest and advantage, and become debtor to the offender.

Rejoice not at the calamity of any, though they be your enemies.
Envy none; it is God who makes rich and poor, great and small, high and low.

Be entreatable.
Never aggravate.
Never revile or give ill names.
It is unmannerly as well as unchristian.
Remember Matt. 5:22, where it is said, '`He that calls his brother fool,
is in danger of hell-fire.`' "`Be not morose or conceited; one is rude,
the other troublesome and nauseous.
Avoid questions and strife; it shows a busy and contentious disposition.

Add no credit to a report upon conjecture, nor report to the hurt of any.
Beware of jealousy, except it be godly, for it devours love and friendship;
it breaks fellowship, and destroys the peace of the mind.
It is a groundless and evil surmise.

Be not too credulous; read Prov. 14:15. Caution is a medium, I recommend it.
Speak not of religion, neither use the name of God, in a familiar manner.

Meddle not with government; never speak of it, let others say or do as they please.
But read such books of law as relate to the office of a justice, a coroner,
sheriff and constable; also the doctor and student; some book of clerkship,
and a treatise of wills, to enable you about your own private business only,
or a poor neighbour`'s. For it is a charge I leave with you and yours,
meddle not with the public, neither business nor money; but understand how to avoid it,
and defend yourselves, upon occasion, against it.
For much knowledge brings sorrow, and much doing more.
Therefore know God, know yourselves; love home, know your own business and mind it,
and you have more time and peace than your neighbours.

If you incline to marry, then marry your inclination rather than your interest:
I mean what you love, rather than what is rich.
But love for virtue, temper, education and person, before wealth or quality,
and be sure you are beloved again.
In all which, be not hasty, but serious; lay it before the Lord, proceed in his fear,
and be you well advised.
And when married, according to the way of God`'s people, used among Friends,
out of whom only choose; strictly keep covenant.
Avoid occasion of misunderstanding; allow for weaknesses,
and variety of constitution and disposition;
and take care of showing the least disgust or misunderstanding to others,
especially your children.
Never lie down with any displeasure in your minds,
but avoid occasions of dispute and offence.
Overlook and cover failings.
Seek the Lord for one another; wait upon him together, morning and evening,
in his holy fear, which will renew and confirm your love and covenant:
give way to nothing that would in the least violate it: use all means of true endearment,
that you may recommend and please one another;
remembering that your relation and union is the figure of Christ`'s to his church;
therefore, let the authority of love only bear sway your whole life.

If God give you children, love them with wisdom, correct them with affection:
never strike in passion, and suit the correction to their age as well as fault.
Convince them of their error before you chastise them, and try them,
if they show remorse, before severity;
never use that but in case of obstinacy or impenitency.
Punish them more by their understandings than the rod, and show them the folly,
shame and undutifulness of their faults, rather with a grieved than an angry countenance,
and you will sooner affect their natures, and with a nobler sense,
than a servile and rude chastisement can produce.
I know the methods of some are severe corrections for faults,
and artificial praises when they do well, and sometimes rewards.
But this course awakens passions worse than their faults; for one begets base fear,
if not haired; the other pride and vain-glory,
both which should be avoided in a religious education of youth;
for they equally vary from it, and deprave nature.
There should be the greatest care imaginable, what impressions are given to children.
That method which earliest awakens their understandings to love, duty, sobriety,
and just and honourable things, is to be preferred.
Education is the stamp parents give their children; they pass for what they breed them,
or less value perhaps, all their days.
The world is in nothing more lacking and reprovable, both in precept and example;
they do with their children as with their souls,
put them out at livery for so much a year.
They will trust their estates or shops with none but themselves,
but for their souls and posterity they have less solicitude.
But do you breed your children yourselves; I mean as to their morals,
and be their bishops and teachers in the principles of conversation:
as they are instructed, so they are likely to be qualified,
and your posterity by the precepts and examples which they receive from yours.
And were mankind herein more cautious,
they would better discharge their duty to God and posterity;
and their children would owe them more for their education than for their inheritances.
Be not unequal in your love to your children, at least in the appearances of it;
it is both unjust and indiscreet: it lessens love to parents,
and provokes envy among children.
Let them wear the same clothes, eat of the same dish,
have the same allowance as to time and expense.
Breed them to some employment, and give all equal.
Teach them also frugality, and they will not lack substance for their posterity.
A little beginning, with industry and thrift, will make an estate;
but there is a great difference between saving and sordidness.
Be not scanty any more than superfluous; but rather make bold with yourselves,
than be strait to others; therefore let your charity temper your frugality and theirs.

What I have written to you, I have written to your children and theirs.

Servants you will have, but remember, the fewer the better,
and those rather aged than young; you must make them such, or dispose of them often.
Change is not good, therefore choose well, and the rather because of your children;
for children, thinking they can take more liberty with servants than with their parents,
often choose the servants company, and if they are idle, wanton, ill examples,
children are in great danger of being perverted.
Let them therefore be Friends, and such as are well recommended:
let them know their business as well as their wages; and as they do the one,
pay them honestly the other.
Though servants, yet remember they are brethren in Christ,
and that you also are but stewards, and must account to God.
Wherefore let your moderation appear unto them,
and that will provoke them to diligence for love rather than fear,
which is the truest and best motive to service.
In short, as you find them, so keep, use and reward them, or dismiss them.

Distrust is of the nature of jealousy, and must be warily entertained upon good grounds,
or it is injurious to others, and instead of being safe, is troublesome to you.
If you trust little, you will have but little cause to distrust.
Yet I have often been whispered to in myself of persons and things,
at first sight and motion, that hardly ever failed to be true;
though by neglecting the sense, or allowing myself to be argued or importuned from it,
I have more than once failed of my expectation.
Have therefore a most tender and nice regard to those first and unpremeditated sensations.

For your conduct in your business, and in the whole course of your life,
though what I have said to you, and recommended you to, might be sufficient;
yet I will be more particular as to those good and gracious qualifications,
with which I pray God Almighty to season and accomplish you,
to his glory and your temporal and eternal felicity.

[.blurb]
=== Section III.

Be humble: it becomes a creature; a depending and borrowed being,
that lives not of itself, but breathes in another`'s air with another`'s breath,
and is accountable for every moment of time, and can call nothing its own,
but is absolutely a tenant at will of the great Lord of heaven and earth.
And of this excellent quality you cannot be lacking,
if you dwell in the holy fear of the omnipresent and all seeing God:
for that will show you your vileness and his excellency, your meanness and his majesty,
and withal, the sense of his love to such poor worms,
in the testimonies he gives of his daily care, mercy and goodness;
that you cannot but be abased, laid low and humbled.
I say, the fear and love of God beget humility, and humility fits you for God and men.
You cannot step well amiss, if this virtue dwell richly in you;
for then God will teach you.
The humble he teaches his ways, and they are all pleasant and peaceable to his children:
yes, he '`gives grace to the humble,
but resists the proud.`' '`He regards the proud afar
off`".`' They shall not come near him,
nor will he hear them in the day of their distress.
Humility seeks not the last word, nor the first place.
She offends none, but prefers others, and thinks lowly of herself;
is not rough or self-conceited, high, loud or domineering;
blessed are they that enjoy her.
'`Learn of me,`' said Christ,
'`for I am meek and lowly in heart.`' He washed his disciples`' feet.
Indeed himself was the greatest pattern of it.
Humility goes before honour.

There is nothing shines more clearly through Christianity than humility.
Of this the holy Author of it is the greatest instance.
He was humble in his incarnation; for he that thought it no robbery to be equal with God,
humbled himself to become a man; and many ways made himself of no reputation.
As first, in his birth or descent: it was not of the princes of Judah,
but of a virgin of low degree, the espoused of a carpenter;
and so she acknowledges in her heavenly anthem,
speaking of the great honour God had done her;
'`My spirit has rejoiced in God my Saviour,
for he has regarded the low state of his hand-maiden;
he has put down the mighty from their seats, and exalted them of low degree.`' Secondly,
he was humble in his life.
He kept no court but in deserts and mountains, and in solitary places;
neither was he served in state, his attendants being mechanics.
By the miracles he wrought, we may understand the food he ate, namely,
barley bread and fish;
and it is not to be thought there was any curiosity in dressing them.
We have reason to believe his apparel was as moderate as his table.
Thirdly, he was humble in his sufferings and death: he took all affronts patiently,
and in our nature triumphed over revenge: he was despised, spit upon, buffeted, whipped,
and finally crucified between thieves, as the greatest malefactor;
yet he never reviled them, but answered all in silence and submission, pitying, loving,
and dying for those by whom he was ignominiously put to death.
O mirror of humility! let your eyes be continually upon it,
that you may see yourselves by it.
Indeed his whole life was one continued great act of self-denial:
and because he needed it not for himself, he must needs do it for us;
thereby leaving us an example that we should follow his steps; and as he was,
we should be, in this world, according to the beloved disciple, 1 John 2:6.
What he did for us, was not to excuse, but to excite our humility.
For as he is like God, we must be like him; and that the froward, the contentious,
the revengeful, the striker, the duelist, etc., cannot be said to be of that number,
is very evident.
The more to illustrate this virtue,
I would have you to consider the folly and danger of pride, its opposite.
This it was that threw the angels out of heaven, man out of paradise,
destroyed cities and nations, was one of the sins of Sodom,
the destruction of Assyria and Israel,
and the reason given by God for his great vengeance upon Moab and Ammon.
Besides, pride is the vainest passion that can rule in man,
because he has nothing of his own to be proud of;
and to be proud of another`'s shows lack of wit and honesty too.
He not only did not make himself,
but is born the nakedest and most helpless of almost all creatures.
Nor can he add to his days or stature,
or so much as make one hair of his head white or black.
He is so absolutely in the power of another, that, as I have often said,
he is at best but a tenant at will of the great Lord of all, holding life, health,
substance, and everything at his sovereign disposal; and the more man enjoys,
the less reason he has to be proud,
because he is the more indebted and engaged to thankfulness and humility.

Wherefore avoid pride as you would avoid the devil; remembering you must die,
and consequently those things must die with you which could be any temptation to pride;
and that there is a judgment follows, at which you must give an account,
both for what you have enjoyed and done.

From humility springs meekness.
Of all the rare qualities of wisdom, learning, valour, etc., with which Moses was endued,
he was denominated by his meekness:
this gave the rest a lustre they must otherwise have lacked.
The difference is not great between these excellent graces;
yet the Scripture observes some.
God will teach the humble his way, and guide the meek in judgment.
It seems to be humility perfectly digested, and from a virtue become a nature.
A meek man is one that is not easily provoked, yet easily grieved; not peevish or testy,
but soft, gentle, and inoffensive.
O blessed will you be, my dear children, if this grace adorn you!
There are many great and precious promises to the meek, in Scripture.
God will clothe the meek with salvation; and blessed are they,
for they shall inherit the earth.
Christ presses it in his own example, '`Learn of me, for I am meek,`' etc.,
and requires his to become as little children, in order to salvation, Matt. 18:3.
A meek and quiet spirit is of great price with the Lord, 1 Pet. 3:4.
It is a fruit of the spirit, Gal. 5:22-23,
exhorted to in Eph. 4:2. Col. 3:12. Tit. 3:2,
and many places more to the same effect.

Patience is an effect of a meek spirit and flows from it.
It is a bearing and suffering disposition; not choleric or soon moved to wrath,
or vindictive; but ready to hear and endure too,
rather than be swift and hasty in judgment or action.
Job is as much famed for this, as was Moses for the other virtue:
without it there is no running the christian race, or obtaining the heavenly crown;
without it there can be no experience of the work of God, Rom. 5:3-5. For patience,
says the apostle, works experience; nor hope of an eternal recompense,
for experience works that hope.
Therefore, says James,
'`Let patience have its perfect work.`' It is made the saints`' excellency;
here is the patience of the saints, Rev. 13:10.
It is joined with the kingdom of Christ, Rev. 1:9.
Read Luke 21:19. '`In patience possess your souls.`' '`Be patient
towards all men;`' which shows the excellency and necessity of patience,
as that does the true dignity of a man.
It is wise, and will give you great advantage over those you converse with,
on all accounts.
For passion blinds men`'s eyes, and betrays men`'s weakness;
patience sees the advantage and improves it.
Patience inquires, deliberates and brings to a mature judgment.
Through your civil as well as christian course,
you cannot act wisely and safely without it;
therefore I recommend this blessed virtue to you.

Show mercy whenever it is in your power, that is, forgive, pity and help,
for so it signifies.
Mercy is one of the attributes of God.
It is exalted in Scripture above all his works, and is a noble part of his image in man.
God has recommended it.
'`Keep mercy and judgment and wait on the Lord.`' God has shown it to man,
and made it his duty.
He has showed you O man what is good, and what does the Lord require of you,
but to do justly, and to love mercy and to walk humbly,
or to humble yourself to walk with your God:
a short but ample expression of God`'s love and man`'s duty;
happy are you if you mind it.
In this you see mercy is one of the noblest virtues.
Christ has a blessing for them that have it, '`Blessed are the merciful,
for they shall find mercy;`' a strong motive indeed.
In Luke 6:35-36, he commands it.
'`Be you merciful as your Father is merciful.`' He bid the Jews,
that were so over-righteous, but so very unmerciful, learn what this means;
'`I will have mercy and not sacrifice.`' In his parable of the lord and his servants,
he shows what will be the end of the unmerciful steward,
that having been forgiven much by his master,
would not forgive a little to his fellow servant.
Mercy is a great part of God`'s law, Ex. 23:4-5.
It is a material part of God`'s true fast, Isa. 58:6-7.
It is a main part of God`'s covenant, Jer. 31:34.
Heb. 8:12. And the reason and rule of the last judgment,
Matt. 25:31, to the end: pray read it.
It is a part of the undefiled religion, James 1:27, 3:17.
Read Prov. 14:21-22. But the merciful man`'s mercy reaches further,
even to his beast; then surely to man, his fellow creature,
he shall not be lacking in it.
Wherefore, I charge you, oppress no body, man or beast.
Take no advantage upon the unhappy, pity the afflicted, make their case your own,
and that of their wives and poor innocent children the condition of yours,
and you cannot lack sympathy, bowels, forgiveness,
nor a disposition to help and succour them to your ability.
Remember, it is the way for you to be forgiven and helped in time of trial.
Read the Lord`'s prayer.
Remember the nature and goodness of Joseph to his brethren;
follow the example of the good Samaritan, and let Edom`'s unkindness to Jacob`'s stock,
and the heathen`'s to Israel, be a warning to you.

Charity is a near neighbour to mercy: it is generally taken to consist in this,
not to be censorious, and to relieve the poor.
For the first, remember you must be judged.
And for the last, remember you are but stewards.
'`Judge not, therefore,
lest you be judged.`' Be clear yourselves before you fling the stone.
Get the beam out of your own eye; it is humbling doctrine, but safe.
Judge, therefore, at your own peril: see it be righteous judgment,
as you will answer it to the great Judge.
This part of charity also excludes whisperings, backbiting, talebearing, evil surmising,
most pernicious follies and evils, of which beware.
Read 1 Cor.
xiii.
For the other part of charity, relieving the poor, it is a debt you owe to God:
you have all you have or may enjoy, with the rent-charge upon it.
The saying is, that '`He who gives to the poor, lends to the Lord:`' but it may be said,
not improperly, the Lord lends to us to give to the poor:
they are at least partners by Providence with you, and have,
a right you must not defraud them of.
You have this privilege, indeed, when, what, and to whom; and yet,
if you heed your Guide, and observe the object, you will have a rule for that too.

I recommend little children, widows, infirm and aged persons, chiefly to you:
spare something out of your own belly rather than let theirs go pinched.
Avoid that great sin of needless expense on your persons and on your houses,
while the poor are hungry and naked.
My bowels have often been moved, to see the very aged and infirm people,
but especially poor helpless children, lie all night in bitter weather,
at the thresholds of doors, in the open streets, for lack of better lodging.
I have made this reflection, if you were so exposed, how hard would it be to endure?
The difference between our condition and theirs, has drawn from me humble thanks to God,
and great compassion and some supply to those poor creatures.
Once more, be good to the poor: what do I say?
be just to them, and you will be good to yourselves.
Think it your duty, and do it religiously.
Let the moving passage, Matt. 25:35. to the end, live in your minds:
I was hungry and thirsty, and naked, sick and in prison, and you administered unto me,
and the blessing that followed: also what he said to another sort,
'`I was hungry and thirsty, and naked, and sick, and in prison,
and you administered not unto me;`' for a dreadful
sentence follows to the hard-hearted world.
Woe be to them that take the poor`'s pledge, Ezek. 18:12-13,
or eat up the poor`'s right.
O devour not their part! less lay it out in vanity, or lay it up in bags,
for it will curse the rest.
Hear what the Psalmist says, '`Blessed is he that considers the poor,
the Lord will deliver him in time of trouble: The Lord will preserve and keep him alive,
and he shall be blessed upon the earth:
And you will not deliver him into the will of his enemies.
The Lord will strengthen him upon the bed of languishing:
You will make all his bed in his sickness.`' This is the reward
of being faithful stewards and treasurers for the poor of the earth.
Have a care of excuses, they are, I know, ready at hand:
but '`Withhold not good from them to whom it is due,
when it is in the power of your hand to do it.
Say not unto your neighbour go, and come again, and tomorrow I will give,
when you have it by you.`' Also bear in mind Christ`'s doctrine,
'`Give to him that asks you, and from him that would borrow of you,
turn not away.`' But above all, remember the poor woman, that gave her mite;
which Christ preferred above all, because she gave all, but it was to God`'s treasury.

Liberality or bounty is a noble quality in man, entertained of few, yet praised of all;
but the covetous dislike it, because it reproaches their sordidness.
In this she differs from charity, that she has sometimes other objects,
and exceeds in proportion.
For she will cast her eye on those that are not absolutely in need,
as well as those that are; and always outdoes necessities and services.
She finds out virtue in a low degree, and exalts it.
She eases their burden who labour hard to live:
many kind and generous spells such find at her hand, that do not quite want,
whom she thinks worthy.
The decayed are sure to hear of her: she takes one child and puts out another,
to lighten the loads of over-charged parents, more to the fatherless.
She shows the value of services in her rewards, and is never debtor to kindnesses,
but will be creditor on all accounts.
Where another gives sixpence, the liberal man gives his shilling;
and returns double the tokens he receives.
But liberality keeps temper too; she is not extravagant any more than she is sordid;
for she hates niggard`'s feasts as much as, niggard`'s fasts; and as she is free,
and not starched, so she is plentiful, but not superfluous and extravagant.
You will hear of her in all histories, especially in Scripture,
the wisest as well as best of books; her excellency and her reward are there.
She is commanded and commended; '`The righteous shows mercy and gives,
and the good man is merciful and ever lends.`' He shows favour and lends,
and disperses abroad.
There is that scatters, and yet increases;
and there is that withholds more than is fitting, but it tends to poverty.
The liberal soul shall be fat; the bountiful eye shall be blessed.
The churl and liberal man are described, and a promise to the latter,
that his liberality shall uphold him, Isa. 32:78.
Christ makes it a part of his religion
and the way to be the children of the highest,
to lend and not receive again, and this to enemies as well as friends;
yes to the unthankful and to the evil; no exception is made, no excuse admitted.
The apostle Paul, 2 Cor. 9:5-10, enjoins it, threatens the strait-handed,
and promises the open-hearted a liberal reward.

Wheresoever, therefore, my dear children; liberality is required of you,
God enabling you, sow not sparingly nor grudgingly, but with a cheerful mind,
and you shall not go without your reward; though that ought not to be your motive.
But avoid ostentation, for that is using virtue to vanity,
which will run you to profuseness, and that to poverty; which begets greediness,
and that avarice, the contrary extreme.
As men may go westward till they come east,
and travel till they and those they left behind them, stand antipodes, up and clown.

Justice or righteousness, is another attribute of God,
of large extent in the life and duty of man.
Be just therefore in all things, to all.
To God as your Creator; render to him that which is his, your heart,
for that acknowledgment he has reserved to himself,
by which only you are entitled to the comforts of this and a better life.
And if he has your hearts, you have him for your treasure,
and with him all things requisite to your felicity.
Render also to Caesar that which is his, lawful subjection; not for fear only,
but conscience sake.
To parents, a filial love and obedience.
To one another, natural affection.
To all people, in doing as you would be done by.
Hurt no man`'s name or person.
Covet no man`'s property in any sort.
Consider well of David`'s tenderness to Saul, when he sought his life,
to excite your duty; and Ahab`'s unjust covetousness and murder of Naboth,
to provoke your abhorrence of injustice.
David, though anointed king, took no advantages; he believed,
and therefore did not make haste, but left it to God, to conclude Saul`'s reign,
for he would not hasten it.
A right method and a good end, my dear children; God has shown it you,
and requires it of you.

Remember the tenth commandment, it was God who gave it, and will judge you by it.
It comprehends restitution as well as acquisition, and especially the poor man`'s wages.
Samuel is a great and good example of righteousness, 1 Sam. 12:3.
He challenged the whole house of Israel,
to say whom he had oppressed or defrauded?
The like did the apostle to the Corinthians, 2 Cor. 7:2.
He exhorted the Christians to be careful that they did not defraud,
1 Thess. 4:6, for this reason, that God was the avenger of the injured.
But as bad as it was, there must be no going to law among Christians, 1 Cor. 6:7.
To your utmost power, therefore, owe no one anything but love,
and that in prudence as well as righteousness.
Justice gives you reputation, and adds a blessing to your substance;
it is the best security you can have for it.

I will close this head, with a few Scriptures to each branch.
To your superiors; '`Submit to every ordinance of man,
for the Lord`'s sake.`' '`Obey those that have rule over
you.`' '`Speak not evil of dignities.`' '`My son,
fear the Lord and the king,
and meddle not with them that are given to change.`' To your parents;
'`Honour your father and your mother, that your days may be long in the land,
which the Lord your God shall give you.`' '`Children,
obey your parents,`' it is the first commandment with promise, Eph. 6:1-2.
Great judgments follow those that disobey this law,
and defraud their parents of their due: '`Whoever robs his father or his mother,
and says it is no transgression,
the same is the companion of a destroyer.`' Or such
would destroy their parents if they could.
It is charged by the prophet Ezekiel upon Jerusalem, as a mark of her wicked state;
'`In you have your princes set light by father and mother, oppressed strangers,
and vexed the fatherless and widows.`' To your neighbour;
hear what God`'s servants taught: '`To do justice and judgment,
is more acceptable to the Lord than sacrifice.`' Diverse
weights and measures are alike abomination unto the Lord, Lev. 19:36.
Duet. 25:13 to 16 inclusive.
Prov. 11:1, xx.
10, 23. Read Prov. 22:16,22,23, xxiii.
10, 23. Peruse the sixth of Micah;
also Zech. 8:16-17. And especially the fifteenth Psalm,
as a short but full measure of life, to give acceptance with God.

I have said but little to you of distributing justice,
or being just in power or government;
for I should desire you may never be concerned therein,
unless it were upon your own principles, and then the less the better,
unless God require it from you.
But if it ever be your lot, know no man after the flesh; know neither rich nor poor,
great nor small, nor kindred, nor stranger; but judge the cause,
according to your understanding and conscience,
and that upon deliberate inquiry and information.
Read Exod. 23 from 1 to 10. Duet. 1:16-17, 16:19, 20, 24:17. 2 Sam. 23:3. Jer. 22:3-4.
Prov. 24:23. Lam. 3:35-36. Hos. 12:6. Amos 8:4-8.
Zeph. 2:3, 3:1,3. Zech. 7:10-9. Jer. 5:4-6, 8:6, 7.
Which show both God`'s commands and complaints, and man`'s duty in authority;
which as I said before, avoid industriously at all times,
for privacy is freed from the clamour, danger, encumbrance and temptation,
that attend stations in government: never meddle with it, but for God`'s sake.

Integrity is a great and commendable virtue.
A man of integrity, is a true man, a bold man, and a steady man;
he is to be trusted and relied upon.
No bribes can corrupt him, no fear daunt him; his word is slow in coming, but sure.
He shines brightest in the fire, and his friend hears of him most when he most needs him.
His courage grows with danger, and conquers opposition by constancy.
As he cannot be flattered or frighted into that which he dislikes,
so he hates flattery and temporizing in others.
He runs with truth, and not with the times; with right, and not with might.
His rule is straight; soon seen but seldom followed: it has done great things.
It was integrity preferred Abel`'s offering, translated Enoch, saved Noah,
raised Abraham to be God`'s friend, and father of a great nation,
rescued Lot out of Sodom, blessed and increased Jacob, kept and exalted Joseph,
upheld and restored Job, honoured Samuel before Israel,
crowned David over all difficulties, and gave Solomon peace and glory, while he kept it;
it was this preserved Mordecai and his people,
and so signally defended Daniel among the lions, and the children in the flames,
that it drew from the greatest king upon earth, and a heathen too,
a most pathetical confession to the power and wisdom of the God that saved them,
and whom they served.
Thus is the Scripture fulfilled,
'`The integrity of the upright shall guide them.`' O my dear children, fear,
love and obey this great, holy and unchangeable God,
and you shall be happily guided and preserved through
your pilgrimage to everlasting glory.

Gratitude or thankfulness, is another virtue of great lustre,
and so esteemed with God and all good men: it is an owning of benefits received,
to their honour and service who confer them.
It is indeed a noble sort of justice, and might, in a sense,
be referred as a branch to that head; with this difference,
that since benefits exceed justice, the tie is very strong to be grateful;
and consequently there is something exceedingly base and reproachful in ingratitude.
So that, though you are not obliged by legal bonds or judgments,
to restitution with due interest, your virtue, honour and humanity,
are naturally pledges for your thankfulness;
and by how much the less you are under external ties,
esteem your inward ties so much the stronger.
Those who can break them, would know no bounds: for make it a rule to you,
the ungrateful would be unjust too, but for fear of the law.
Always own therefore the benefits you receive,
and then choose when and how you may most honour or serve those that conferred them.
Some have lived to need the favours they have done; and should they be put to ask,
where they ought to be invited?
No matter if they have nothing to show for it,
they show enough when they show themselves to those they have obliged:
and such see enough to induce their gratitude,
when they see their benefactors in adversity;
the less law the more grace and the stronger tie.
It is an evangelical virtue, and works, as faith does, only by love:
in this it exactly resembles a Christian state; '`We are not under the law,
but under grace,`' and it is by grace, and not by merit,
'`that we are saved.`' But are our obligations the less to God,
that he heaps his favours so undeservedly upon us?
Surely no.
It is the like here; that which we receive is not owed or compelled, but freely given,
so no tie; it is of choice, a voluntary goodness without bargain or condition:
but has this therefore no security?
Yes, certainly, the greatest; a judgment written and acknowledged in the mind.
He is his friend`'s to the altar with a good conscience: but how long?
As long as he lives.
The characters of gratitude, like those of friendship, are only defaced by death,
else indelible.
'`A friend loves at all times,`' says Solomon.
And '`your own friend, and your father`'s friend,
forsake not.`' It is injustice which makes gratitude a precept.
There are three sorts of men who can hardly be grateful; the fearful man,
for in danger be loses his heart, with which he should help his friend: the proud man,
for he takes that virtue for a reproach:
he who unwillingly remembers he owes anything to God,
will not readily remember he is beholden to man.
History lays it to the charge of some of this sort of great men,
who being uneasy to see the authors of their greatness,
have not been quiet till they have accomplished the ruin of those who raised them.
Lastly, the covetous man is as ill at it as the other two.
His gold has spoiled his memory, and will not let him be grateful,
though perhaps he owes the best part, at least the beginning of it, to another`'s favour.
As there is nothing more unworthy in a man than ingratitude,
so nothing in man is so frequently reproached in Scripture.
How often does God put the Jews in mind of their forgetfulness and unthankfulness
for the mercies and favours they received from him;
read Duet. 32:15. Jesurun waxed fat, and kicked against God, grew unmindful,
forgot and forsook his Rock, who had done mighty things for him.
Thus Moses, Duet. 31:16-17.
Also Judges 10:11-13. And 1 Sam. 8:8.
David likewise in his lxxviii.
cv. cvi.
Psalms, gives a history of God`'s love to Israel, and their ingratitude.
It is made a mark of apostacy from Christianity by the apostle, 2 Tim. 3:2.

Diligence is another virtue useful and laudable among men;
it is a discreet and understanding application of one`'s self to business;
and avoids the extremes of idleness and drudgery.
It gives great advantages to men: it loses no time, it conquers difficulties,
recovers disappointments, gives dispatch, supplies the lack of natural abilities;
and is to them what a pond is to a spring; though it has no water of itself,
it will keep what it gets, and is never dry.
Though that has the heels, this has the wind; and often wins the prize.
Nor does it only concern handicrafts and bodily affairs; the mind is also engaged,
and grows foul, rusty and distempered without it.
It belongs to you, throughout your whole man;
be no more sauntering in your minds than in your bodies.
And if you would have the full benefit of this virtue, do not baulk it by a confused mind.
Shun diversions; think only of the present business, till that be done.
Be busy to purpose; for a busy man and a man of business, are two different things.
Lay your matters right, and diligence succeeds in them, else pains is lost.
How laborious are some to no purpose?
Consider your end well, suit your means to it, and then diligently employ them,
and you arrive where you would be, with God`'s blessing.
Solomon praises diligence very highly.
First, it is the way to wealth: '`The diligent hand makes rich.
The soul of the diligent shall be made fat.`' There is a promise to it,
and one of another sort to the sluggard.
Secondly, it prefers men.
'`Do you see a man diligent in his business, he shall stand before kings.`' Thirdly,
it preserves an estate: '`Be diligent to know the state of your flocks,
and look well to your herds;
for riches are not forever.`' There is no living upon the principal,
you must be diligent to preserve what you have, whether it be acquisition or inheritance;
else it will consume.
In short the wise man advises, '`Whatsoever your hand finds to do,
do it with your might.`' As it mends a temporal state,
no spiritual one can be gotten or kept without it.
Moses earnestly presses it upon the Israelites, Duet. 4:9. and 6:7.
The apostle Paul commends it in the Corinthians, and Titus to them for that reason, 2 Cor. 8:22-7.
So he does Timothy to the Philippians on the same account,
and urges them to work out their salvation.
Peter also exhorts the churches to that purpose: '`Wherefore the rather brethren,
says he, give diligence to make your calling and election sure:
for if you do these things you shall never fall.`' Wherefore, beloved,
seeing that you look for such things; the end of the world and last judgment;
be diligent that you may be found of him in peace, without spot and blameless.
Thus diligence is an approved virtue:
but remember that is a reasonable pursuit or execution of honest purposes,
and not an overcharging or oppressive prosecution, to mind or body,
of most lawful enterprises.
Abuse it not therefore to ambition or avarice.
Let necessity, charity and conveniency govern it, and il will be well employed,
and you may expect prosperous returns.

Frugality is a virtue too, and not of little use in life, the better way to be rich,
for it has less toil and temptation.
Il is proverbial, a penny saved is a penny got.
It has a significant moral;
for this way of getting is more in your own power and less subject to hazard,
as well as snares, free of envy, void of suits, and is beforehand with calamities.
Many get who cannot keep, and for lack of frugality spend what they get,
and so come to feel the lack of what they have spent.
But have a care of the extreme: want not with abundance, for that is avarice,
even to sordidness.
It is fit that you consider children, age and casualties,
but never pretend these things to palliate and gratify covetousness.
As I would have you liberal but not prodigal, and diligent but not drudging;
so I would have you frugal but not sordid.
If you can, lay up one half of your income for those uses,
in which let charity have at least the second consideration; but no Judas`'s,
for that was in the wrong place.

Temperance I must earnestly recommend to you, throughout the whole course of your life:
it is numbered among the fruits of the Spirit, Gal.
22, 23, and is a great and requisite virtue.
Properly and strictly speaking, it refers to diet;
but in general may be considered as having relation
to all the affections and practices of men.
I will therefore begin with it in regard to food,
the sense in which it is customarily taken.
Eat to live, and not live to eat, for that is below a beast.
Avoid curiosities and provocations; let your chiefest sauce be a good stomach,
which temperance will help you to get.
You cannot be too plain in your diet, so you are clean; nor too sparing,
so you have enough for nature.
For that which keeps the body low, makes the spirit clear, as silence makes it strong.
It conduces to good digestion, that to good rest, and that to a firm constitution.
Much less feast any, except the poor; as Christ taught, Luke 14:12-13.
Entertainments are rarely without sin; but receive strangers readily.

As in diet so in apparel, observe I charge you an exemplary plainness.
Choose your clothes for their usefulness not the fashion,
and for covering and not finery, or to please a vain mind in yourselves or others:
they are fallen souls that think clothes can give beauty to man.
'`The life is more than raiment.`' Man cannot mend God`'s work,
who can give neither life nor parts.
They show little esteem for the wisdom and power of their Creator,
who under-rate his workmanship (I was a going to say his image) to a tailor`'s invention:
gross folly and profanity!
But do you, my dear children, call to mind who they were of old, that Jesus said,
took so much care about what they should eat, drink and put on.
Were they not gentiles, heathens, a people without God in the world?
Read Mat.
vi., and when you have done that,
peruse those excellent passages of the apostle Paul and Peter, 1 Tim. 2:10-9,
and 1 Pet. 3:3,5, where if you find the exhortation to women only,
conclude it was to the effeminate,
and a shame then for men to use such arts and cost upon their persons.
Follow you the example of those primitive Christians, and not voluptuous gentiles,
who perverted the very order of things: For they set lust above nature,
and the means above the end, and preferred vanity to conveniency:
a wanton excess that has no sense of God`'s mercies,
and therefore cannot make a right use of them, and less yield the returns they deserve.
In short, these intemperances are great enemies to health and to posterity;
for they disease the body, rob children, and disappoint charity, and are of evil example;
very catching, as well as pernicious evils.
Nor do they end there: they are succeeded by other vices,
which made the apostle put them together in his epistle to the Galatians 5:20-21.
The evil fruits of this part of intemperance are so many and great,
that upon a serious reflection, I believe there is not a country, town or family, almost,
that does not labour under the mischief of it.
I recommend to your perusal the
first part of, [.book-title]#No Cross no Crown,# and of the _Address to Protestants,_
in which I am more particular in my censure of it.
But the virtue of temperance does not only regard eating, drinking and apparel;
but furniture, attendance, expense, gain, parsimony, business, diversion, company,
speech, sleeping, watchings, and every passion of the mind, love, anger, pleasure, joy,
sorrow, resentment, are all concerned in it.
Therefore bound your desires, learn your wills subjection,
take Christ for your example as well as guide.
It was he who led and taught a life of faith in Providence,
and told his disciples the danger of the cares and pleasures of this world;
they choked the seed of the kingdom, stifled and extinguished virtue in the soul,
and rendered man barren of good fruit.
His sermon upon the mount is one continued Divine authority in favour of universal temperance.
The apostle, well aware of the necessity of this virtue,
gave the Corinthians a seasonable caution.
'`Do you not know, says he, that they which run in a race, run all,
but one receives the prize?
So run that you may obtain.`' '`And every man that strives for mastery,`' or seeks victory,
'`is temperate in all things:`' he acts discreetly and with a right judgment.
'`Now, they do it to obtain a corruptible crown, but we an incorruptible.
I therefore so run as not uncertainly; so fight I, not as one that beats the air:
but I keep under my body, and bring it into subjection; lest that by any means,
when I have preached to others,
I myself should become a castaway.`' In another chapter
he presses temperance almost to indifference:
'`But this I say, brethren, the time is short: It remains then,
that both they that have wives, be as though they had none;
and those that weep as though they wept not; and they that rejoice,
as though they rejoiced not;
and they that use this world as not abusing it.`' And all this is not without reason:
he gives a very good one for it.
'`For, says he, the fashion of the world passes away:
but I would have you without carefulness.`' It was for this cause he pressed
it so hard upon Titus to warn the elders of that time to be sober,
grave, temperate; not eager, violent, obstinate, tenacious, or inordinate in any sort.
He makes it an indispensable duty in pastors of churches, that they be not self-willed,
soon angry, given to wine or filthy profit, but lovers of hospitality, of good men,
sober, just, holy, temperate.
And why so?
Because against these excellent virtues there is no law.

I will shut up this head, being touched upon in various places of this advice,
with this one most comprehensive passage of the apostle,
'`Let your moderation be known unto all men,
for the Lord is at hand.`' As if he had said, Take heed!
Look to your ways!
Have a care what you do!
For the Lord is near you, even at the door; he sees you, he marks your steps,
tells your wanderings, and he will judge you.
Let this excellent, this home and close sentence live in your minds:
let it ever dwell upon your spirits, my beloved children, and influence all your actions,
aye, your affections and thoughts.
It is a noble measure, sufficient to regulate the whole;
they that have it are easy as well as safe.
No extreme prevails; the world is kept at arm`'s-end;
and such have power over their own spirits,
which gives them the truest enjoyment of themselves and what they have.
A dominion greater than that of empires.
O may this virtue be yours!
You have grace from God for that end, and it is sufficient: employ it,
and you cannot miss of temperance,
nor therein of the truest happiness in all your conduct.

[.signed-section-signature]
William Penn.

[.asterism]
'''

As my object is to give an account of the life and religious labours of William Penn,
and not the history of his province,
I have made but little mention of the events which occurred there during his absence.
A transient notice will now be proper.

After the recall of governor Blackwell, in the twelfth month, 1689,
the charge of the government again devolved upon Thomas Lloyd; who,
although a man of excellent abilities and unquestionable integrity,
does not appear to have possessed either the talents or the influence of William Penn.
Difficulties and jealousies arose among the members of the government.
The representatives from the province and those from
the territories or three lower counties,
being supposed to have separate interests to promote, could not cordially unite.
The proprietary had taken abundance of pains to form an
intimate connection between the province and territories,
both in the legislative and executive capacities.
But the members from the territories,
seeing themselves likely to be outnumbered by those from the province,
and consequently thrown into the minority upon all questions
in which their separate interests were involved,
demanded concessions for their security, which were considered unreasonable,
and consequently refused.
These jealousies at length, in the early part of 1691,
rose to such a height as to occasion a rupture between them,
which resulted in the establishment of two separate governments.
To this separation, William Penn gave a very reluctant assent.
This we may fairly consider as a consequence of his absence;
for we find that he retained the confidence and affection of both parties.
He had penetration enough to discover the ill consequences
likely to result both to his interest and theirs,
from these animosities.
The unpleasant news reached him soon after the commencement of
his troubles arising from the accusation of Preston and Fuller.
He did not fail to apprise his friends in America of his apprehensions on their account,
and to urge upon them the necessity of cultivating a better temper;
but the people of the territories appear to have been too
jealous of their rights and too tenacious of their opinions,
to be diverted from their purpose by his influence or authority,
while residing on the other side of the Atlantic.

In 1691, the province of Pennsylvania was agitated in a manner,
which must have caused greater pain to the sensitive mind of William Penn,
than the dissensions between the province and territories.
The latter arose from questions of worldly interest;
but the new disturbance arose in the bosom of his own Society.
George Keith, who for between twenty and thirty years,
had been an approved member and minister in the Society,
became about that time a subject of much exercise to his friends.
He began to differ with them on points of discipline,
proposing alterations which Friends were not free to adopt.
Finding his influence in the Society less than he
seems to have supposed due to his talents and service,
he gave way to a captious and acrimonious spirit.
He began to question the soundness of the ministers on some doctrinal points,
and falling under the government of his passions rather than his understanding,
indulged in very harsh and vituperative language,
towards Friends of the fairest character;
and at length charged the meeting of ministers with
coming together to cloak heresies and deceit;
asserting that there were more abominable doctrines among the Quakers,
than among any other profession of Protestants.

This opposition to Friends was not confined to questions of doctrine or discipline,
but extended to the measures of civil government.
A large part of the original settlers in Pennsylvania,
being of the same religious profession with the founder,
many of the executive and judicial offices were exercised by members of this Society.
George Keith indulged his spleen by representing the conduct
of these Friends in bringing robbers to justice,
as a violation of their principles.^
footnote:[In the year 1691, one Babit and a few others,
stole a small sloop from a wharf in Philadelphia, and going down the river,
committed a number of robberies.
Information being given to the magistrates there,
three of them issued a warrant for their apprehension; in consequence of which,
they were taken and brought to justice.
The magistrates who granted this warrant being Friends, George Keith and his adherents,
made their comments on this proceeding as inconsistent
with their avowed principles in regard to war,
and dressed it in the most odious garb which their imbittered imaginations could supply.
Yet the most they could make of it was, that a Peter Boss and a few others,
took them without gun, sword or spear.]
His opposition to the measures and officers of the government,
rendered him at length an object of judicial inquiry.
He and another were presented by the grand jury of Philadelphia,
as the authors of a defamatory publication;
for which on conviction they were fined five pounds each; but the fines were not levied.
News of the disturbances occasioned by him and his party,
were soon carried to the mother country; and those who were inimical to Friends,
the province or the proprietary,
took care to circulate them with the usual exaggerations.
The account of his trial was circulated with such colouring
as to give it the appearance of a religious persecution.
It was industriously reported at court, Westminster hall, and the parliament house,
and excited much odium against William Penn and the Society of Friends.
It was laid hold of as an evidence of their unfitness
for the exercise of political power,
and William Penn himself does not appear to have approved of this prosecution.
The magistrates published a declaration,
exculpating themselves from the charge of religious persecution;
showing that they had not proceeded against George
Keith and his adherents without ample provocation;
and giving an opinion that such conduct, if not restrained,
tended to sedition and the subversion of the existing government.

Although King William seemed to have entertained a friendship for William Penn,
yet the general complexion of his court was averse to the adherents of James;
and this aversion to the political friends of the exiled monarch,
would naturally extend to his personal friends also,
of which number William Penn was avowedly one.
This circumstance,
together with the exaggerated reports which were circulated respecting
the disorders and mal-administration existing in the province and territories,
prevailed with the king and council to adopt the resolution
of depriving William Penn of his authority there.
In pursuance of this resolution, a commission was issued,
bearing date the 21st of October 1692, to Benjamin Fletcher, governor of New York,
authorizing him to assume the government of Pennsylvania,
and the territories thereto belonging.
This, as far as can be ascertained, was a simple act of power;
without even the colour of law or legal procedure.

In the commission no notice was taken of William Penn or the charter
of Charles II. The commission of governor Fletcher was not received
by him until the spring of the following year;
at which time he notified Thomas Lloyd of his appointment,
and soon afterwards repaired to Philadelphia,
to engage in the concerns of his new government.
Official information of the change was not given to the constituted authorities of Pennsylvania,
by the king, yet upon the arrival of colonel Fletcher,
the government was surrendered to him without opposition; but Friends,
who held the offices of magistrates,
generally refused to accept from him the renewal of their commissions.

It is not probable that the government at home gave William Penn notice of their proceedings,
and he was probably ignorant of them till the information
reached him from the western side of the Atlantic.
He afterwards wrote to some of them,
giving them to understand that he apprehended they had too tamely given up his rights,
yet without censuring them, as he supposed their intentions were good.
He also wrote to colonel Fletcher, warning him of the illegality of his appointment,
and reminding him of his particular obligations to him.
A letter in reply to the former of these, from six of the inhabitants of Pennsylvania,
dated 18th of eleventh month, 1693-4,
stated their wish that his letter to colonel Fletcher had come sooner to hand;
as they understood it would probably have prevented his taking the part he did,
and thus saved them as well as him the trouble and loss which had fallen upon them.

The administration of governor Fletcher,
was not marked by any event of such permanent interest as to demand particular recital.
He appears to have been, or at least to have become,
convinced that the exclusion of William Penn from
the government was an unjust assumption of power;
and that his own exercise of that authority was likely to be of very short duration.

In the year 1694, William Penn was restored to the government,
of which he had been unjustly divested, by letters patent, dated the 20th of August.
In this document,
the disorders assigned as the cause of the royal assumption of authority there,
are attributed to the absence of the proprietor.
There, an intimation at least is given that his prudence and authority, if present,
would have prevented the disorders complained of.

It has been intimated, by more historians than one,
that William Penn promised King William, upon the restoration of his government,
that the province should contribute to the general defence of the colonies.
Such a promise seems to imply a dereliction of his avowed principles in relation to war;
and if generally known,
must have seriously affected his character as a member
and minister in the Society of Friends.
This supposed engagement, was probably inferred from an expression in the letters patent,
which revoked the commission of governor Fletcher.
It is there stated that he had given assurance that he would
take care of the government of the province and territories,
and as far as in him lay, provide for their safety and security.
Had he been a military man, such an assurance might have been understood to imply,
that he would promote such measures of defence as
the usual policy of the world is accustomed to provide.
But he had provided for the security of the province,
in the early part of his administration, by conciliating the good will of the natives.
We know not in what terms he expressed himself, when he gave this assurance to the king,
and we have no reason to suppose that any engagement,
inconsistent with his well known principles, was made or implied.
We are told that in a letter from Bristol, 5th of ninth month, 1695,
he blamed the province for refusing to send money to New York,
for what he called a common defence.
If this letter alludes, as supposed by Proud, to the application of governor Fletcher,
in his message to the assembly in the third month, 1694,
it is unfair to suppose that the defence intended was a military one.
The governor had proposed a supply of such articles as would
be likely to secure the continual friendship of the Indians,
in the neighbourhood of Albany.
That was the kind of defence which was most congenial to
the policy as well as the principles of William Penn.

Thomas Lloyd, who was, during several years, the deputy of William Penn,
in the government of Pennsylvania, having died in the seventh month 1694;
the appointment upon William Perm`'s restoration, was conferred upon William Markham,
who held it till the arrival of the governor himself, in 1699.
Little remarkable seems to have occurred under his
administration to attract the historian`'s notice.
It may be proper however to observe, that in 1696,
three hundred pounds were remitted from the province to governor Fletcher of New York,
to be applied to the relief of the Indians in the neighbourhood of Albany;
and that in the following year a letter was received by governor Markham,
informing him that the money had been expended in food and clothing for them as directed.

In the sixth month 1699, William Penn with his wife and family embarked for Pennsylvania;
and from on board the ship, while lying at the Isle of Wight,
he addressed the following farewell epistle to his friends wherever scattered in England,
Ireland, Scotland, Holland, Germany or other parts of Europe.

[.embedded-content-document.epistle]
--

My dearly beloved, and highly esteemed in Christ, our heavenly head;
the living and good Shepherd of the sheep, by whom we have been found out,
(one of a family, and two of a tribe,) and made one holy flock and family unto him,
in this day of his spiritual and glorious appearance: grace, mercy and peace, yes,
his peace, which the world can neither give you, nor take from you,
be plentifully multiplied among you from day to day; that a holy, harmless,
and faithful people you may be, yielding to the Lord the fruits of his goodness,
by a circumspect and self-denying conduct to the end.

And now, my dear friends, whom I know and love, and you also whom I truly love,
though I do not know personally, nor may be so known of some of you,
since it has pleased the good and all-wise God to order my course from you,
so that I cannot visit you, as I have often desired before I left you,
this therefore is to be my brotherly farewell unto you.
And surely my soul is bowed in humble petitions to Israel`'s God, the true,
and living and powerful God, that it may be well with you all here and forever.
And, my dear brethren, this is certain, if you do well, you shall fare well;
and in the end of all your trials, troubles, and temptations, it shall be said unto you,
Well done good and faithful servants, enter into the joy of the Lord.
O it is this which crowns the work: not saying but doing: we must not only begin,
but end well; and hold out to the end: not be of those who are weary of well-doing,
but who follow the Lord fully, as Caleb and Joshua did in old time, and are famed for it.
So that though God has appeared to us,
and given us many and undeniable testimonies that it was he, and not another,
who reached our hearts, and touched our consciences, and brought us to confession, yes,
and forsaking too, of that which offended him, in great measure, blessed be his name,
yet we are not to stop, or take up our rest here; we must watch still, pray still,
fight still, that good fight of faith, till we have overcome the enemy of our souls.
And even then must we watch and pray, and that to the end of our days;
that we may not lose that crown of glory, which God, the righteous judge,
shall give to all those that love his appearance, overcome, and persevere to the end.
For be assured we shall reap if we faint not; but we shall faint,
if we wait not upon God, who alone is the strength of his people.

This, my dear friends, is that which lies with greatest stress upon my spirit;
watch to your daily preservation, and be not satisfied unless you feel it.
Sufficient is the day for the evil thereof, said our blessed Lord.
God is not lacking: he who long stood at the door of our hearts,
under our impenitency in times past, till his locks were wet with the dew,
and his hair with the drops of the night,
till we were wakened out of our carnal security, and came to judgment in ourselves,
unto unfeigned repentance,
to be sure he is not weary of waiting to be gracious now to his poor people;
especially if they are poor in spirit, and hungering and thirsting after righteousness;
and are not filled, overlaid, and choked with the cares and incumbrances of this world.
No, he was ever good unto Israel, yes, unto all that are of an upright and clean heart.
Wherefore, brethren, let your eye be to the Lord, and wait often upon him; walk with him,
and dwell with him, and he will walk and dwell with you.
And then no weapon formed against you, be it in particular, or in general, shall prosper;
that is, not finally.
It may perhaps try you, and bruise your heel,
as it did your Lord and master`'s but it shall never finally prevail against you,
if you keep the eye of your mind to him, and have faith in him,
who saved Daniel in the lion`'s den, and Shadrach, Meshach, and Abednego,
in the fiery furnace, and has upheld us to this day under various afflictions.

And though Balaams there are, who may be hired by the Balaks of our age,
to curse our Israel-family of God, of which some of us have been very sensible,
yet this we know, the Son of God is among us, who commands the fire and the water,
and the winds, as well now as then.
And there is no enchantment against Jacob, nor divination against Israel,
that can prosper.
And who knows but even some of these present Balaams may yet live to say,
before they die, as others of them have done since we were a people,
'`How goodly are your tents, O Jacob!`' '`How pleasant is your dwelling place,
O Israel!`' But then friends, we must keep our tents,
we must be a retired and a peculiar people, and dwell alone.
We must keep above the world, and clear of the spirit of it, and those many trifles,
cares and troubles that abound in it,
with which many have visibly wounded and pierced their own souls.

Beware of this in the name of the Lord, and do not tempt God;
it is in Christ you have peace, in the world is the trouble:
keep therefore in him who has called himself, and we have found him so, the way, Truth,
and life; and you shall live, because he lives: he the root, you the branches,
by whom you will be kept green and fruitful,
bringing forth the fruits and graces of the holy Spirit in all your converse,
and commerce, that it may be seen and said, God is with you and among you.
O let humility, charity, meekness and self-denial,
shine among you! so will you come to sit, as did the primitive Christians,
in heavenly places in Christ Jesus, and be preserved through the noise, snares,
and hurry of this present evil world.

Much I could say, for my heart is open, and full too of Divine love and matter to you;
but time fails me; therefore feel me, my dear friends,
in that love of God which is over sea and land; where distance cannot separate,
or time decay, nor many waters quench.
In which love I embrace and salute you all, with the kiss of our heavenly fellowship,
which the Lord has given us in the blessed Truth.
And my strong desires are to him,
that we may maintain our blessed relation by the same means,
by which we came at first into it, that is,
by '`the true fear and love of God;`' which did not
only make us careful not to offend him,
but also to be willing to forsake all things that came in competition with him,
or our duty to him.

Oh let this chaste fear and first love abound among you, my beloved, in Christ,
our blessed light and life; or you will decay, wither, and die to God,
and your good beginnings; which God Almighty forbid.

I know there is a serious and diligent people among you,
who do not only know when good comes from the hand of the Lord, but wait upon him for it,
and that daily; that their souls may be strengthened in the way and work of the Lord:
and these can no more live without his presence, his mystical and hidden manna,
in their spiritual journey to the eternal Canaan of God,
than outward Israel was able to live without manna in the wilderness,
in their journey to their temporal Canaan.
And I beseech my God and my Father, and your God and your Father, my dear brethren,
to attend all these holy waiters upon him with the good things of his house,
and daily make them glad in his holy house of prayer.

But the condition of some, who pretend to follow Christ, yet are afar off,
affects my spirit; for they know little of these enjoyments,
and hardly eat so much as the crumbs which fall from Christ`'s table,
and seem to satisfy themselves with a mere convincement of the Truth, or at best,
with a bare confession to it.
Who taking up with a formal going to meetings, and hearing what others have to say,
of the work and goodness of God in and to them, shun the daily cross of Christ;
whereby they should die daily to their earthly wills and vain affections,
and overcome the world, the flesh, and the devil.
Oh! these are still their own, and not the Lord`'s; and gird themselves, and go where,
and do what they list!
For which cause they are lean, barren, and unfruitful to God, and to their own souls;
and worship him in the form only, and not the power of godliness;
such must needs be weak in faith, ready to slip and start aside at every windy doctrine,
or sensual temptation.

Oh!
My dear friends, let me prevail with you in this my farewell to you,
to turn your minds inward, and wait to feel your Redeemer,
and meet him in the way of his righteous judgments;
for there is no redemption but through judgment, nor conversion,
but through righteousness.
Come and be baptized by Christ; he will baptize you with his fire and Holy Spirit.
He will scour and rinse you; for, believe me,
his fan is still in his hand and he will if you will let him, thoroughly purge his floor,
which is your hearts, and make all things clean and new there, by his Spirit and power.
So will you come to find your interest in Christ,
as you feel his workmanship and interest in and over you.
And as you thus come to be related to Christ, the heavenly Head,
by knowing him to be head in you, so will you come to be related to his body, the church,
and see your proper membership and service therein; which I pray God effect,
to his glory, and your comfort.

And now to the whole family and flock of God, in this European part of the world,
of the same communion, according to the dispensation of God, be they high or low,
young or old, rich or poor, wise or simple, strong or weak, male or female, bond or free,
I send this parting salutation, of my most dear love in the Truth;
beseeching you all to have me and mine in your remembrance,
not only when upon the mighty waters, but when in the solitary deserts of America,
if it please the Lord to bring us safe there;
for I am not above the love and prayers of my dear brethren, knowing I need them,
and have often found, by good experience, that they avail much with the Lord.

I must leave you, but I can never forget you;
for my love to you has been even as David`'s and Jonathan`'s, above the love of women:
and permit me to say, that, to my power,
I have from the first endeavoured to serve you and my poor country too,
and that at my own charges, with an upright mind,
however mis-understood and treated by some whom I heartily forgive.
Accept you my services, and ever love and remember, my dear friends and brethren,
your old, true, and affectionate friend, brother, and servant, in Christ Jesus.

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Cowes, Isle of Wight, weighing anchor, the 3rd of the seventh month, 1699.

--

They sailed on the 9th of seventh month,
and were nearly three months before they reached their intended port.
But this detention upon the ocean,
preserved them from exposure to a very fatal malady which prevailed that autumn in Philadelphia.

There were six or seven, and sometimes eight who died in a day of the prevailing disease,
and that for several weeks in succession;
which out of the number then composing the population of Philadelphia,
must have been a very awful mortality.
Thomas Story, who was in the city and attended the Yearly Meeting there^
footnote:[Previous to the time of this meeting`', some Friends of Burlington,
wrote to Friends in Philadelphia,
suggesting the expediency of adjourning the Yearly
Meeting to a cooler season of the year.
But it was answered, that until the meeting convened they had no power to adjourn;
but thought it would be well that such only should come
as were concerned in the service of the meetings.]
during the prevalence of that distemper, informs us that there were few,
if any houses free from sickness.
"`Great,`" says he, "`was the majesty and hand of the Lord.
Great was the fear that fell upon all flesh.
I saw no lofty or airy countenance, nor heard any vain jesting to move men to laughter;
nor witty repartee, to raise mirth; nor extravagant feasting,
to excite the lusts and desires of the flesh above measure.
But every face gathered paleness, and many hearts were humbled,
and countenances fallen and sunk,
as such that waited every moment to be summoned to the bar, and numbered to the grave.
But the just appeared with open face, and walked upright in the streets,
and rejoiced in secret, in that perfect love that casts out all fear;
and sang praises to Him who lives and reigns, and is worthy forever,
being resigned unto his holy will in all things; saying, Let it be as you will,
in time and in eternity, now and forevermore!
Nor love of the world, nor fear of death, could hinder their resignation,
abridge their confidence, or cloud their enjoyments in the Lord.`"

Whether medical writers have given an accurate description of this disease,
I cannot tell; but from the imperfect accounts which we have in general history,
it appears probably that this was the same disorder which has several
times raged in that city and other parts of the United States,
within a few years past; and which is known by the name of the Yellow Fever.
It appears that it was very fatal in some of the West Indian
islands about the time of its first visit to Philadelphia.

After a voyage of nearly three months,
the vessel in which William Penn and his family were, arrived in the Delaware.
Passing up the river into the neighbourhood of Chester,
he went in his barge to the shore, on the southern side of Chester creek,
where he met with his particular friend Thomas Story,
who had then nearly completed a general visit to Friends on the American continent.
They lodged there together, and on the following day,
which was the first of the tenth month, they crossed Chester creek to the town in a boat;
where a circumstance occurred which must have given
him considerable uneasiness at the time;
and furnished matter for the tongue of slander.

As they were about landing, some officious young men,
desirous of honouring the governor`'s arrival,
undertook contrary to the express orders of some of the magistrates, to fire a salute.
They had two small cannon, which they discharged,
and being in haste to make a third report,
one of them darted in a cartridge before the gun was sponged, which instantly exploded,
and shattered his left hand to pieces.
A surgeon being called, the arm was amputated.

After a short stay at Chester, William Penn returned to the ship,
and proceeded to Philadelphia.
The people there, welcomed his arrival with great joy,
which was heightened by the information that he expected
to spend the rest of his life among them.

Notwithstanding the winter set in with great severity, soon after their arrival,
we find William Penn visited Friends and attended the meetings
in various places in the vicinity of Philadelphia.

He met the assembly not long after his arrival,
and strongly represented to them the odium to which
the government of Pennsylvania was exposed,
on account of their supposed connivance at piracy and illicit trade.
For some time previous to his leaving England,
rumours had been extensively circulated there,
in which the people of Pennsylvania were represented
as giving encouragement to those practices.
Of these reports and the scandal which they occasioned,
he took care duly to apprize the authorities of the province;
in consequence of which a proclamation was issued in 1698,
by the deputy governor and his council,
requiring the magistrates and officers of the province and territories,
to enforce the laws of trade and navigation, and to execute those against piracy,
where occasion was given.
The assembly enacted two laws to prevent practices of that character,
and measures were taken to clear the government from
all unjust imputations of that nature.
These bills being dispatched the assembly broke up and the members returned home.

After the separation of the legislature,
William Penn retired to his mansion at Pennsbury, the usual place of his residence.
The affairs of the government must have occupied great part of his care and attention,
for many things had got out of order.
But there were two subjects which particularly claimed his consideration:
the instruction and civilization of the Indians; and the improvement of the negroes.
He had devoted considerable attention to the former while in America before,
and during his absence the subject does not appear to have been entirely neglected.

In regard to the negroes, it may be observed,
that neither their slavery nor the trade in their persons, had at that time,
attracted much attention, from Christian philanthropists.
The English engaged in that abominable traffic during the reign of Elizabeth;
and a few slaves were carried into Virginia as early as 1620.
But the nature of this traffic was very imperfectly understood.
Those who were interested in its continuance,
would of course endeavour to conceal its enormities.
In the first settlement of Pennsylvania, a few slaves were introduced.
The great amount of labour inseparable from the opening of a wilderness,
created a demand for labourers; and the supposition seems to have been admitted,
without much examination, that the removal of these people from a land of pagan darkness,
to one illumined with the light of Christianity, was an improvement of their condition.
Such it would, no doubt, have been,
if their removal and subsequent treatment had been conducted upon Christian principles.
But slavery and the slave trade seem to have been
at all times conducted upon selfish principles,
and the profits of the labour of the slaves have been more
regarded than their moral and religious improvement.
That Friends of reputable characters,
should fall into a practice which is now seen to be glaringly unchristian,
appears surprising; yet this was the case, both in the West Indies,
and on the American continent.
But though Friends incautiously fell into this practice, yet there were some,
who at an early day,
saw the necessity of endeavouring to imbue the minds
of the negroes with the love of virtue,
and to lead them in the way of holiness.

When George Fox was in the island of Barbados, in 1671,
he held a number of meetings among them, in which he admonished them to justice,
sobriety, chastity and piety.
He also exhorted the masters to treat them kindly,
to endeavour to train them up in the fear of God, and after a time of servitude,
to make them free.
In his letter to the governor and council of that island,
he reminded them that they would be answerable at the great day of final retribution,
for the use which they made of their power over these people.
In an epistle to Friends in the ministry, who were gone to America,
written about a month before his death,
he exhorted them to keep up meetings among the negroes, and with the Indian kings.

Thomas Story, in his account of his travels in North Carolina in 1698,
relates some instances of tender religious impressions made on the minds of negro slaves,
in the families of Friends;
from which it appears that considerable notice of them had been
taken by some Friends who were travelling in the work of the Gospel.

In 1688, the Friends from Crisheim in Germany, who were settled at Germantown,
made a communication to the Yearly Meeting then held at Burlington,
giving it as their sentiment that the buying,
selling and holding of men in slavery was inconsistent with the Christian religion.
But no action of that meeting ensued at that time.
In the year 1696, that meeting discouraged the further importation of slaves,
and recommended measures for their moral improvement.

At the Monthly Meeting of Philadelphia, which occurred in the first month 1700,
William Penn opened his concern, which he informed them had long engaged his mind,
for the benefit and welfare of the Indians and negroes;
pressingly exhorting Friends to discharge their duty to those people;
more particularly in relation to the improvement of their minds.
Advising that they should, as frequently as possible,
enjoy the advantage of attending religious meetings,
and receiving instruction in the principles of the Christian religion.
In consequence of this communication,
a meeting was appointed particularly for the negroes, to be held once a month.
Measures were also adopted for having meetings more frequently with the Indians,
William Penn taking upon himself the charge of regulating the manner,
and procuring interpreters.

It was mentioned in a former chapter, that the three lower counties, in 1691,
separated from the province, and that William Penn,
then in retirement on account of the accusations of Preston and Fuller,
was induced to give a reluctant assent to this separation.
When the government of the province and territories was conferred upon colonel Fletcher,
he reunited them, apparently without consulting their choice on the subject.
The legislative assembly, thus composed of members from the province and territories,
was convened at Philadelphia, in the third month, 1700.
In the commencement of the session, William Penn sent them information,
that as he understood they were not satisfied with
the charter which was granted by his deputy,
in 1696, he was prepared to offer them another.
This information was given at the opening of the session,
for the double purpose of proving his readiness to oblige them,
and of giving time to consider the subject deliberately.

His next object was to secure, by legislative enactments,
the improvement in the condition and treatment of the negroes and Indians,
in the province;
which he had previously laboured to effect within the limits of his own religious Society.
In pursuance of this object he presented soon afterwards,
a t)ill for regulating the morals and marriages of the negroes,
and another for the regulation of their trials and punishment,
substituting the judgment of the law for the will of the master.
A third, was also laid before the assembly, for preventing abuses upon the Indians.
Of these bills he had the mortification to find the first and last rejected,
the reasons for which, are not transmitted to us in the history of the time.
What portion of the members of the assembly belonged to the Society of Friends is uncertain;
but the council of the governor consisting altogether of Friends,
had united with him in proposing these bills, and the Monthly Meeting of Philadelphia,
had sanctioned the principle of them.
Hence we may very rationally conclude that this rejection was the effect of an influence,
extraneous to his own Society.
The assembly after a short session was dissolved by the governor.

When William Penn was released from his attendance on the legislature,
he took the opportunity of renewing his friendly relationship with the Indians.
For this purpose he visited them in the forests,
and received them in return at his mansion at Pennsbury.

It may be readily supposed that he frequently visited the meetings of Friends,
both in his own province, and in its vicinity.
A few memorials of those visits remain.
It is related that one day on his way to the meeting at Haverford,
he overtook a little girl on foot who was going to the same meeting.
Being on horse back, he invited her to get up behind him, which she did.
Being without shoes or stockings her naked feet hung dangling by the side of the horse,
and in this way they went on to the meeting.
Though he was then the governor and proprietor of Pennsylvania,
he did not think it beneath him to assist a little barefooted girl on her way to meeting.
We also hear of his being at a meeting in New Jersey.
An account is likewise given of his going to a meeting
at Third-haven on the eastern shore of Maryland,
in company with Lord Baltimore and his lady.
But that must have been in the following year,
for the circumstance is related by John Richardson,
who did not land in America till the beginning of 1701.

Another legislative assembly was convoke! in the autumn of the same year 1700,
to meet at New-Castle.
One of the objects to which their attention was called by the governor,
was the adjustment of the new charter or frame of government,
which the former assembly had left unfinished.
He also advised them to revise the laws formerly enacted, while he was among them,
and expunge, alter or enlarge, as they might see proper; and he promised to afford them,
during their deliberations, all the assistance in his power.

They made, however, very little progress,
before the jealousies and surmisings which had formerly
rent the territories from the province,
began to appear.
The members from the lower counties,
perceiving that the growing population and wealth of the province,
must inevitably at no distant day render the balance of power very unequal,
and fearing or professing to fear, that an improper advantage would be taken,
demanded that no greater number of representative`'s should at any subsequent time,
be sent from the province than from the territories.
This proposal being rejected by the provincial members,
a separation seemed in danger of taking place.
But both parties agreed to consult the governor upon the subject;
and he suggested arr expedient, to which they all agreed;
that in all legislative acts in which the interests or privileges
of the territories were separately involved,
the concurrence of two-thirds of the members from the lower counties,
as well as a majority of those from the province should be required.

This question being settled, another almost immediately arose.
It was agreed that provision should be made for defraying the expense of government;
but the adjustment of the mode and the proportion to be paid by the different sections,
was the difficulty.
Several plans were proposed and rejected, the members from the territories,
and those from the province, uniformly taking opposite sides.
As there were then only three counties in the province,
this division of their votes produced an exact equilibrium.
But again the wisdom and discretion of William Penn,
brought the contending parties to an agreement.^
footnote:[Of two thousand pounds then agreed to be raised,
the sums paid by the respective counties, were,
Philadelphia one thousand and twenty-five, Chester three hundred and twenty-five,
Bucks two hundred and twenty-five, New-Castle one hundred and eighty,
Kent one hundred and thirty-nine, Sussex one hundred and six.]

In the early part of 1701,
a circumstance occurred that appeared for a short time not unlikely to test the
safety of the pacific principles upon which William Penn conducted his government.
It appears that some commotions had arisen in East Jersey,
in consequence of the insolent behaviour of a criminal in one of the courts.
To what extent the commotion arose is not clearly stated,
but the influence of the constituted authorities
was not competent to its immediate suppression.
Upon receiving information of this event, William Penn hastened to Philadelphia,
not to engage a military force, as a governor acting upon the usual policy of the world,
would probably have done;
but he there selected twelve of the most respectable members of his own Society,
with whom he set out for the scene of disorder.
From the kind of companions whom he selected in this enterprise,
we may readily discover that it was by moral and religious, rather than physical force,
he expected to suppress the insurrection.
Happily he had no occasion to exercise either, for while on the way,
he received information that the difficulty was adjusted.

In the spring of the same year a number of Indians came to Philadelphia,
to renew their friendship with the English.
The principal of these were the king of the Susquehanna or Coneslogo Indians;
the king of the Shawanese; the chief of the Ganawese,
a tribe residing near the head of Potomac;
and the brother to the emperor of the Five Nations.
These were accompanied by a number of others, amounting together to about forty.

William Penn and his council concluded with those Indians a treaty of peace and friendship,
of which the following is a summary.

That there should be forever thereafter a firm and lasting peace between William Penn,
his heirs and successors, and all the Christian inhabitants of the province,
and the said Indian chiefs, their successors,
and the nations of Indians whom they represented.
That the said chiefs should not at any time commit any injury,
or allow the Indians under their control to commit any injury
upon the persons or property of the inhabitants of the province,
and that William Penn, his heirs and successors,
should not permit the English inhabiting the province to
commit any act of hostility or violence upon the Indians.
That the Indians while residing near to or among the English inhabitants,
should be obedient to the laws of the government,
and be entitled to the benefit and protection of those laws.
That the said Indians should not at any time abet or assist other Indians who
were not in amity with the crown of Great Britain and government of Pennsylvania.
That neither of the contracting parties should give credit
to any reports of hostile designs on the part of the other,
until they had taken the proper means to become fully
informed of the truth of such reports.
That the said Indians should not introduce any foreign
Indians into any part of the province,
without the consent of William Penn or his successors.
That to prevent abuses in the trade with the Indians,
no person should be permitted to prosecute any traffic with them
but such as should be approved by William Penn or his representative.
That the Indians should not sell their peltry or furs to any person out of the province;
and that William Penn and his successors should be always prepared
to supply the Indians with goods at a reasonable rate.
The Conestogo Indians confirmed a sale previously made of
a tract of land in the vicinity of the Susquehanna river.

Finally, William Penn engaged on behalf of himself and his successors,
that they would show themselves true friends and brothers to the Indians,
and assist them with their advice and direction;
the Indians conducting themselves peaceably and submitting to the laws of the province.

As a pledge for the faithful observance of every part of this treaty,
the Indians presented the governor with five parcels of skins;
and he in return presented them with a quantity of goods and merchandise.

It appears that notwithstanding the solicitude manifested by William Penn,
from his first interactions with the Indians of Pennsylvania,
to prevent his people from taking a fraudulent advantage of their ignorance and simplicity,
still great abuses were practised;
for soon after the above mentioned treaty was ratified,
we find he brought the subject before the council,
urging the adoption of some effectual measures for preventing and redressing those evils.
It was therefore resolved,
that the trade with them should be carried on by a company with a joint stock,
under certain regulations and restrictions,
more particularly in regard to the sale of spirituous liquors;
which company should use all reasonable endeavours to impress upon
the Indians a proper sense of the value of the Christian religion;
by setting before them an example of probity and candour, both in conduct and commerce.
And that care should be taken to instruct them in the fundamental doctrines of Christianity.
The plan thus digested,
appears to have been afterwards acted upon as far as they found it practicable.

In the beginning of the sixth month,
the assembly was convened on an occasion which must
have been very unpleasant to William Penn.
A letter had been received from the king,
demanding three hundred and fifty pounds sterling,
to be employed in fortifying the frontiers of New York.

This demand was probably considered by the king as nothing more than a
requisition for the performance of the engagement which William Penn is
said to have made when his government was restored to him.
The subject must have been an embarrassing one.
He could not, consistently with his religious principles,
advocate a compliance with this demand;
and yet it was not his province to reject it upon his own responsibility.
He therefore, when he had convened the assembly, laid the subject before them,
and left it for their decision.
It is evident, from the proceedings which followed,
that the members would gladly have excused themselves from acting upon the case.
They at length agreed upon an address to the governor,
replete with expressions of loyalty to the king,
and requesting that he might be assured of their readiness to comply with all his demands,
as far as their circumstances and religious persuasions would permit;
but excusing themselves from a present compliance with this requisition,
on account of the infancy of the colony and the great expense the
inhabitants had incurred in the formation of their settlements.
To these reasons for delay, they added the consideration,
that the other colonies had hitherto done nothing in furtherance of the object in view.^
footnote:[It may be observed, that the British nation was not then engaged in war.
The people of Pennsylvania probably took very little
interest in the dispute respecting the Spanish succession,
which then agitated the European courts.
The assembly could therefore advance a political argument for deferring their decision,
without particularly adverting to their religious scruples in relation to war.]
This address was received by the governor without comment; and the assembly,
at their own request, dissolved the next day.

During the time which William Penn had passed in America,
he had applied himself industriously to the affairs of the government;
endeavouring to rectify the disorders which had crept into the province;
always preferring the good of the country and its inhabitants) to his own private interest;
rather remitting than strictly exacting his lawful revenues;
so that under his paternal administration,
the people of the province were advancing in prosperity,
and accumulating the necessaries and comforts of life.
But the ambition of rulers and the intrigues of their enemies, raised another storm,
which in a short time separated William Penn forever from his province.

The growing wealth and population of the American colonies,
began before this time to excite the jealousy of the government at home,
and the project appears to have been formed soon after the revolution,
to purchase the proprietorship of the more important ones, if not of all,
and vest their government in the crown.
A bill was, at this time, actually before the house of lords,
for changing the colonial governments into regal ones.
The excuse for this intended assumption of power,
was the national advantage to be derived from it, on one hand, and the pretended abuses,
existing among them on the other.
The friends of William Penn and others interested in the affairs of Pennsylvania,
represented to parliament the hardship of his case,
and solicited a suspension of their proceedings,
until he could return and answer for himself.
Letters were also dispatched,
giving him information of the measures in progress and urging his immediate return.

Painful as the prospect of abandoning the colony,
in which he had expected to spend the evening of his day, unquestionably was,
there appeared no alternative.
The experiment which he had attempted,
of maintaining a government upon Christian principles,
and making the settlement of the country subservient
to the civilization of the original inhabitants,
was in danger of being totally frustrated.
A military government might be reasonably expected,
in case the bill in question should be completed;
and very possibly the barbarous contests with the natives which
marked the early settlements in Virginia and New England,
would be renewed upon the banks of the Delaware.

Having decided upon a voyage to Europe,
William Penn again convened the assembly at Philadelphia,
to whom on the 15th of seventh month, he delivered the following address:

[.embedded-content-document.address]
--

[.letter-heading]
The Governor`'s Speech to the Assembly at Philadelphia.

[.salutation]
Friends,

You cannot be more concerned than I am at the frequency of your service in assembly,
since I am very sensible of the trouble and charge it contracts upon the country:
but the motives being considered, and that you must have met of course in the next month,
I hope you will not think it a hardship now.
The reason that hastens your sessions, is the necessity I am under,
through the endeavours of the enemies of the prosperity of this country,
to go for England, where, taking advantage of my absence,
some have attempted by false or unreasonable charges to undermine our government,
and thereby the true value of our labours and property;
government having been our first encouragement.
I confess I cannot think of such a voyage without great reluctancy of mind,
having promised myself the quietness of a wilderness,
and that I might stay so long at least with you,
as to render every body entirely easy and safe.
For my heart is among you, as well as my body, whatever some people may please to think,
and no unkindness or disappointment shall, with submission to God`'s providence,
ever be able to alter my love to the country,
and resolution to return and settle my family and posterity in it;
but having reason to believe.
I can at this time best serve you and myself on that side of the water,
neither the rudeness of the season,
nor tender circumstances of my family can overrule my inclinations to undertake it.

Think therefore, since all men are mortal,
of some suitable expedient and provision for your safety,
as well in your privileges as property,
and you will find me ready to comply with whatsoever
may render us happy by a nearer union of our interests.

Review again your laws; propose new ones that may better your circumstances,
and what you do, do it quickly,
remembering that the Parliament sits the end of the next month,
and that the sooner I am there, the safer I hope we shall be here.

I must recommend to your serious thoughts and care,
the king`'s letter to me for the assistance of New York,
with three hundred and fifty pounds sterling, as a frontier government;
and therefore exposed to a much greater expense in proportion to other colonies,
which I called the last assembly to take into their consideration,
and they were pleased for the reasons then given to refer to this.^
footnote:[The letter we may remember,
required this sum towards the erection of fortifications,
and the reference here made to it, has been construed as recommending a compliance.
The recommendation, however, is that they would seriously consider the subject.
The result is certainly left to them.
As the succeeding paragraph states that the governor of
New York had made peace with the neighbouring Indians,
the assembly might very consistently have made an appropriation
for securing and perpetuating that peace,
by presents to them.
Such a course seems to be obliquely intimated in the passage before us.]

I am also to tell you the good news of the governor of New York;
the happy result of his conferences with the Five Nations of Indians;
that he has not only made peace with them, for the king`'s subjects of that colony, but,
as I had by some letters`' before desired him,
for those of all other governments under the crown of England,
on the continent of America,
as also the nations of Indians within those respective colonies:
which certainly merits our acknowledgments.

I have done when I have told you, that unanimity and dispatch are the life of business,
and that I desire and expect from you, for your own sakes,
since it may so much contribute to the disappointment of those
that too long have sought the ruin of our young country.

--

[.offset]
To this they returned the following answer:

[.embedded-content-document.address]
--

[.letter-heading]
The Assembly`'s Address to the Governor.

[.salutation]
May it please the proprietary and governor,

We have this day in our assembly read your speech, delivered yesterday, in council;
and having duly considered the same,
cannot but be under a deep sense of sorrow for your purpose of so speedily leaving us;
and at the same time taking notice of your paternal regard to us and our posterity,
the freeholders of this province and territories annexed,
in your loving and kind expressions,
of being ready to comply with whatsoever expedient
and provisions we shall offer for our safety,
as well in privileges as property, and what else may render us happy in a nearer,
union of our interests;
not doubting the performance of what you have been so lovingly pleased to promise,
do in much humility, and as a token of our gratitude,
return unto you the unfeigned thanks of this house.

[.signed-section-closing]
Subscribed by order of the House,

[.signed-section-signature]
Joseph Growdon, Speaker.

--

It is not necessary to enter into a detail of the proceedings of this assembly.
Suffice it to observe, that the jealousies of the lower counties again appeared;
but were so far allayed by the mildness and firmness of the governor,
that the members agreed to proceed with those from the province,
in the settlement of the business for which they were convened.
The charter of privileges was completed and signed,
to the general satisfaction of the parties concerned.

As the first and last clauses of this charter manifest the care of William Penn,
to secure the inhabitants of the province and territories
in the full enjoyment of their conscientious rights,
I shall transcribe them for the information of my readers.

[quote]
____
Because no people can be truly happy,
though under the greatest enjoyment of civil liberties,
if abridged of the freedom of their consciences, as to religious profession and worship;
and Almighty God being the only Lord of conscience, Father of lights and Spirits,
and the Author as well as object, of all Divine knowledge, faith and worship,
who only does enlighten the mind, and persuade and convince the understandings of people,
I do hereby grant and declare, that no person or persons,
inhabiting this province or territories,
who shall confess and acknowledge one Almighty God, the creator,
upholder and ruler of the world;
and profess him or themselves obliged to live quietly under the civil government,
shall be, in any case molested or prejudiced, in his or their person or estate,
because of his or their conscientious persuasion or practice,
nor be compelled to frequent or maintain any religious worship, place or ministry,
contrary to his or their minds, or to do or suffer, any other act or thing,
contrary to their religious persuasion.

And because the happiness of mankind depends so much
upon the enjoying of liberty of their consciences,
as aforesaid, I do hereby solemnly declare, promise and grant, for me,
my heirs and assigns, that the first article of this charter,
relating to liberty of conscience, and every part and clause therein,
according to the true intent and meaning thereof,
shall be kept and remain without any alteration, inviolably forever.
____

The news that William Penn was going to England,
soon brought a number of Indians to visit him.
Some of these visits were received at Pennsbury,
probably before the meeting of the assembly, and one, at least, at Philadelphia,
during the session.

John Richardson, who was then in Pennsylvania, upon a religious visit,
has left us a brief account of an interview between
William Penn and the Indians at Pennsbury.
The conference was conducted with great sobriety and decorum.
One of the chiefs speaking of their covenants, which they were then reviving, told them,
that they never first broke their covenants with any people; for,
striking his hand upon his head, he said they did not make them there; but said,
striking his hand on his breast, they made them there.
After the proper business was finished,
William Penn presented them with some articles of clothing, and before they left him,
assured them that if any differences should arise between them and any of his people,
it need not be the cause of war; for that justice should be done in such cases;
that animosities might be prevented on both sides forever.

Of the visit made during the session of the assembly, but little is now known,
though the interview is said to have been very interesting.
It appears to have been in the presence of the council.

William Penn told them, the assembly was then about enacting a law,
according to the desire of the Indians,
to prevent their being abused by the sale of rum among them;
and he requested them to unite their utmost efforts with those of the government,
to secure its due execution.

Observing to them at the same time,
that this was likely to be his last interview with them, at least until his return,
he assured them he had always loved them, and been kind to them,
and should always continue so to be, not from policy or to promote his own interest,
but from a real affection; and he desired them, in his absence,
to cultivate friendship with those whom he should leave in authority behind him;
for they would always, in some degree,
continue their friendship to them as he had ever done.
Lastly, he told them, that he had charged the members of council,
and he then repeated the charge, that they should in all respects be kind to them,
and entertain them with all courtesy and demonstrations of good will,
as he had always done.
The members then promised that they would faithfully observe the charge.
Some presents were then made to the Indians, after which they withdrew.

Preparations being made for his voyage, and the vessel nearly ready to sail,
he appointed a council of state, consisting of ten persons, of whom Thomas Story was one;
he likewise presented the citizens of Philadelphia with a charter,
constituting it a city, with the necessary powers for its government; and lastly,
he constituted Andrew Hamilton,
who was sometime governor both of East and West New Jersey,
his deputy governor for the province and territories.

On the 31st of eighth month, 1701, he embarked with his wife and family,
and arrived safely at Portsmouth, about the middle of the tenth month following.
