== Chapter XXIII.

There can be no doubt that William Penn, upon his arrival in England,
paid all the needful attention to the subject, which occasioned his voyage;
yet we do not find that any considerable efforts on his part were required.
The attention of the government was sufficiently
engrossed by objects of greater interest to the nation,
and the death of the king which occurred on the 8th of first month, 1701-2,
produced a sensible change in the situation of William Penn,
in relation to the government at home.
His well known friendship for the unfortunate and bigoted James,
as we have had ample reason to observe,
without any participation in the arbitrary measures of the court,
rendered him an object of suspicion, during the reign of William.
But upon the accession of Ann, the second daughter of James,
those jealousies disappeared, and he became once more an acceptable visiter at court.
Amidst these changes of influence and power,
the bill for converting the colonial into regal governments,
was allowed to fall into oblivion.

The new queen having, soon after her accession,
publicly declared her resolution to maintain the toleration in favour of dissenters,
an address on the occasion was prepared at the Yearly Meeting of London,
in the spring of 1702, and a number of Friends, of whom William Penn was one,
were appointed to present it.
He delivered it to the queen, who spoke to him very kindly on the subject,
and renewed the assurance of her protection.

Though the bill for converting the colonial governments into regal ones, was dropped,
as already mentioned, another was enacted,
requiring the royal assent to the appointment of deputy governors.
This indicates a disposition to render them more dependent upon the crown,
than they had hitherto been.
It was probably with a view of being at hand to counteract
any measures on the part of the government,
injurious to the interests of the colonies,
that William Penn took lodgings for himself and family at Kensington,
where he appears to have resided during the year 1702.

About this time a bill was introduced into Parliament,
"`to prevent occasional conformity,`" on which he wrote a small tract entitled,
"`Considerations upon the bill against occasional conformity.`"
He also wrote near the same time,
a second part to his "`Reflections and Maxims relating to the conduct of human life.`"

In the year 1703, he wrote a preface to a book, published by Daniel Philips,
and entitled, "`Vindicise Veritatis,`" being a defence of the principles of Friends,
in answer to a treatise by John Stillingfleet, a clergyman in Lincolnshire.
Also a preface to the writings of Charles Marshall,
entitled "`Zion`'s travellers comforted;`" and in the following year,
he wrote a preface to the works of John Whitehead.

In 1705, he addressed a short epistle to his friends, as follows:

[.embedded-content-document.epistle]
--

[.salutation]
My dear friends,

Hold all your meetings in that which set them up, the heavenly power of God,
both ministers and hearers, and live under it, and not above it,
and the Lord will give you dominion over that which seeks
to draw you again into captivity to the spirit of this world,
under various appearances;
that the Truth may shine through you in righteousness and holiness, in self-denial,
long suffering, patience, and brotherly kindness,
so shall you approve yourselves the redeemed of the Lord,
and his living witnesses in and to an evil generation.
So prays your friend and brother,
through the many tribulations that lead to the rest and kingdom of God.

[.signed-section-signature]
William Penn.

--

In the same year he visited the meetings of Friends in the western parts of England,
where he had good service, and his testimony was effectual to the information of many.

In 1706, he removed with his family to a house near Brentford,
about eight miles from London, where he resided several years.
It is probable there were few if any other Friends in the neighbourhood,
for a meeting was then appointed to be held there, once a month,
partly for the accommodation of his family and partly with a view to general service.

In the year 1707,
he had the unhappiness to be involved in a law-suit with the executors of Philip Ford,
a person who had been entrusted with the management of his estates in Ireland.
The demands which were made in behalf of that man,
appeared to him so unreasonable and exorbitant,
that he thought himself bound both in justice and conscience to resist them.
The circumstances of the case are involved in considerable obscurity.
But I shall present the best view of it which I have been able to obtain.

It appears he had treated Ford with great kindness,
and supposing him bound by a sense of gratitude,
entrusted more to his integrity than prudence would justify,
and that he had signed papers presented to him without
sufficiently scrutinizing their contents.
About the time of the war in Ireland,
when William and James were contending for the mastery of the island, Ford made,
or professed to have made, considerable advances on William Penn`'s account.
The heavy expenses which the latter had incurred in the
management of his province had embarrassed his circumstances,
so that instead of paying these advances, he mortgaged his property in Pennsylvania,
as security for the debt.`' But Ford managed to procure
an absolute conveyance of the province,
and gave an informal defeasance in return.
During the life of Ford this transaction remained a secret, but after his death,
his executors claimed not only the proprietorship but the government of the province.
The latter claim was however abandoned, as it was not included in the conveyance.
William Penn insisted that the transaction was a mortgage, not a conveyance,
and instituted a suit in chancery for opening and liquidating Ford`'s accounts,
whose demand amounted to about twelve thousand pounds sterling.
He considered two-thirds of this charge to be unjust,
being made up by computing compound interest, and by exorbitant commissions.
The chancellor seems to have been convinced that the account was not fairly stated,
but the settlements which had been sanctioned at several times by William Penn,
rendered it improper in his view to open the accounts.
While this suit was pending in chancery,
the representatives of Ford instituted a suit in the king`'s bench for arrears of rent,
upon a lease of the province, made by Phillip Ford to the proprietary,
and obtained a verdict for three thousand pounds.
Execution was issued,
and an officer sent to arrest William Penn while he was attending a public meeting.
But the bailiff permitted him to stay the meeting,
upon the assurance of Henry Gouldneyand others,
that he would surrender himself when it was over.
This was accordingly done, and he in consequence,
was obliged to live for several months within the rules of the Fleet.
A compromise was at length effected,
and the sum of seven thousand pounds accepted in lieu of the sums demanded.
The money was chiefly advanced by his friends,
and a mortgage on the province for six thousand six hundred pounds,
was given as security.^
footnote:[This debt was afterwards paid by the commissioners
appointed to superintend the interest of the mortgages,
out of funds derived from quit rents and the sale of land.]
The imposition practised by this unworthy confidant,
may be in part computed from the fact,
that he received seventeen thousand pounds of William Penn`'s money,
and disbursed on his own account, only sixteen thousand pounds,
and yet brought his employer twelve thousand pounds in debt for interest and services.

After this troublesome affair was adjusted,
he again travelled through some of the western parts of England,
in the work of the ministry, as his health and strength would admit.
He likewise visited the counties of Berks, Buckingham, Surrey and other places.

In the same year, 1709,
he wrote an account of the life and writings of Bulstrode Whitelock,
prefixed to his memorials of English affairs, to the end of the reign of King James I.,
now published from his original manuscripts.

About this time we find the first notice of the failure of his physical powers.
The numerous perplexities through which he had recently passed,
together with necessary decays of nature,
were producing their visible effects on his once athletic constitution.
The air in the vicinity of London was found unfavourable to his declining powers,
and he removed to Rushcomb, in Buckinghamshire,
where he fixed his residence for the rest of his life.
His removal to Rushcomb occurred in 1710,
and it appears probable that he travelled but little
from home after his settlement there.
We only hear of his being once at a Monthly Meeting in Reading,
and once in London subsequent to this time.

In the year 1711, the works of John Banks, an ancient friend of his,
and a valuable minister, being ready for the press, he dictated a preface,
to an amanuensis; walking at the time about the room with his cane,
and occasionally giving answers to other matters.
This was the last essay which he published.^
footnote:[This preface, is contained in the beginning of Vol.
II. of the Friends`' Library.
It may be proper to mention, that the John Wilkinson mentioned in that preface,
was not the one who caused the separation,
but one who remained faithful to the end of his days.]

As I have now arrived nearly at the close of William Penn`'s active life,
a brief review of the affairs of Pennsylvania, so far as he was connected with them,
during the time which had elapsed since his return to England, will be taken.

After the departure of the proprietary,
the jealousies between the province and territories,
which he found so much trouble in controlling, effectually prevented their union,
so that they never afterwards acted in joint legislation; and in 1703,
it was finally settled to form two independent legislative assemblies.
The administration of governor Hamilton was of short duration,
being terminated by his death in the twelfth month, 1702.

The person appointed as successor to Andrew Hamilton, was John Evans,
a young man of twenty-six years, who arrived in Pennsylvania in the twelfth month, 1703.
The appointment of so young a man to such an important station,
is of itself a sufficient indication of the difficulty
experienced in finding one properly qualified,
who was willing to occupy that troublesome station.
He was recommended to James Logan, secretary for the province,
on whose talents and fidelity William Penn placed great reliance, and under whose,
direction, the new deputy promised to place himself.
He was accompanied by William Penn junior,
whom his father was anxious to detach from the dissipations of Europe,
and engage in the business of the province.

The administration of governor Evans, was an unhappy one.
Dissentions soon arose between him and the leading men in the province,
which were productive of acrimonious actions and feelings not toward him alone,
but extending in some measure to William Penn himself.
From a number of his actions which are recorded,
there can be no doubt that the proprietary was misinformed of his character,
or that his character underwent an unfavourable change after his appointment.
There is also reason to believe, that the influx of emigrants,
of a class less moral and religious than those who accompanied William Penn in 1682,
had somewhat deteriorated the general tone of morals in the province.
After a turbulent administration of about five years, governor Evans was removed,
and Charles Gookin appointed in his place.

Governor Gookin was a man of years and experience,
from whose temper and abilities considerable hopes were
entertained of a satisfactory and harmonious administration.
He was the bearer of a letter from William Penn to his friends in Pennsylvania,
dated the 28th of seventh month, 1708,
in which he expressed the warmth of his love for them, as in times that were past,
and earnestly exhorted them to humility,
and a deep and constant care to experience an establishment on the ancient foundation;
to cry aloud to the Lord in faith and courage, for his renewing and refreshing power;
that by a blameless life, they might manifest the Divine work upon their hearts,
and be the means of leading others into the fold of rest.
He entreated them to promote the collection of his dues there,
to enable him to discharge the debt then recently contracted,
so that he might reputably and speedily return to Pennsylvania;
which he was anxious to do.
And he added that if the Lord should bring him and his family safely to them,
he should hardly be induced upon any consideration to leave them again;
for he was desirous of settling his minor children among them,
greatly preferring that they should be planters in Pennsylvania,
rather than merchants in their native land.

From this letter we may clearly infer, that his continuance in England was chiefly,
if not entirely owing to pecuniary embarrassment;
and that the difficulty of procuring a deputy who was competent
to manage the complicated concerns of the government,
and the discordant propensities of the new settlers,
rendered him very solicitous to try what his own presence and influence could accomplish.

The new governor arrived at Philadelphia en the 1st of first month, 1709,
when the assembly for the province was in session.
That body immediately presented an address,
in which they very injudiciously claimed a redress of grievances,
arising as they alleged, from the maladministration of his predecessor.
As many of these grievances were such as the new governor had no power to redress,
this reference to them upon his arrival,
gave no very favourable prospect of future harmony.
His answer was mild yet firm,
and he assured them that he was disposed to do what
lay in his power to render them as happy as possible.
But he observed that the way to escape from all apprehension of grievances,
was to lay aside former animosities,
and apply themselves to the promotion of the public good.

Dissensions soon arose between the governor and the assembly,
which greatly impeded the public business,
and were the source of much painful anxiety to William Penn.
James Logan, secretary of the province, a firm and faithful friend of the proprietary,
became an object of manifest aversion to the assembly.
They even issued a warrant signed by the speaker,
for apprehending and committing him to jail, when on the eve of embarking for England,
but a supersedeas from the governor prevented its execution.
He prosecuted his voyage,
and satisfied his friend and benefactor of the correctness and integrity of his conduct.

The dispatches, which reached William Penn through the instrumentality of James Logan,
or through other channels,
put him into full possession of the turbulent spirit which distracted the province.
Roused by a clear perception of the evils necessarily resulting from the
prevalence of these dispositions and the scandal which they occasioned,
he addressed to the assembly, the following energetic expostulation.

[.embedded-content-document.address]
--

[.signed-section-context-open]
London, 29th Fourth month, 1710.

[.salutation]
My old friends,

It is a mournful consideration, and the cause of deep affliction to me, that I am forced,
by the oppressions and disappointments, which have fallen to my share in this life,
to speak to the people of that province, in a language, I once hoped,
I should never have occasion to use.
But the many troubles and oppositions, I have met with from there, oblige me,
in plainness and freedom, to expostulate with you, concerning the causes of them.

When it pleased God to open a way for me to settle that colony,
I had reason to expect a solid comfort from the services done to many hundreds of people;
and it is no small satisfaction to me,
that I have not been disappointed in seeing them prosper,
and growing up to a flourishing country, blessed with liberty, ease and plenty,
beyond what many of themselves could expect; and lacking nothing to make them happy,
but what, with a right temper of mind and prudent conduct, they might give themselves.
But, alas! as to my part, instead of reaping the like advantages,
some of the greatest of my troubles have arisen from there;
the many combats I have engaged in; the great pains and incredible expense,
for your welfare and ease, to the decay of my former estate;
of which (however some there would represent it) I too sensibly feel the effects;
with the undeserved opposition I have met with from there, sink me into sorrow; that,
if not supported by a superior hand, might have overwhelmed me long ago.
And I cannot but think it hard measure,
that while that has proved a land of freedom and flourishing, it should become to me,
by whose means it was principally made a country, the cause of grief,
trouble and poverty.

For this reason I must desire you all, even of all professions and degrees,
for although all have not been engaged in the measures that have been taken,
yet every man who has an interest there, is, or must be, concerned in them,
by their effects; I must, therefore, I say, desire you all,
in a serious and true weightiness of mind, to consider what you are, or have been, doing;
why matters must be carried on with these divisions and contentions,
and what real causes have been given, on my side,
for that opposition to me and my interest, which I have met with; as if I were an enemy,
and not a friend, after all I have done and spent, both here and there.
I am sure, I know not of any cause whatsoever.
Were I sensible you really lacked anything of me in the relation between us,
that would make you happier, I should readily grant it,
if any reasonable man would say it were fit for you to demand;
provided you would also take such measures as were fit for me to join with.

Before any one family had transported themselves there,
I earnestly endeavoured to form such a model of government,
as might make all concerned in it, easy; which nevertheless was subject to be altered,
as there should be occasion.
Soon after we got over, that model appeared, in some parts of it,
to be very inconvenient, if not impracticable; the number of members,
both in the council and assembly, was much too large;
some other matters also proved inconsistent with the king`'s charter to me; so that,
according to the power reserved for an alteration, there was a necessity to make one,
in which, if the lower counties were brought in, it was well known, at that time,
to be on a view of advantage to the province itself,
as well as to the people of those counties,
and to the general satisfaction of those concerned,
without the least apprehension of any irregularity in the method.

Upon this they had another charter passed, nemine contradicente;
which I always desired might be continued, while you yourselves would keep up to it,
and put it in practice; and many there know how much it was against my will, that,
upon my last going over, it was vacated.
But after this was laid aside (which indeed was begun by yourselves,
in Colonel Fletcher`'s time) I, according to my engagement, left another,
with all the privileges, that were found convenient for your good government; and,
if any part of it has been, in any case, infringed, it was never by my approbation.
I desired it might be enjoyed fully.
But though privileges ought to be tenderly preserved, they should not, on the other hand,
be asserted under that name, to a licentiousness:
the design of government is to preserve good order;
which may be equally broken in upon by the turbulent endeavours of the people,
as well as the overstraining of power, in a governor.
I designed the people should be secured of an annual fixed election and assembly;
and that they should have the same privileges in it, that any other assembly has,
in the queen`'s dominions; among all which this is one constant rule,
as in the parliament here, that they should sit on their own adjournments;
but to strain this expression to a power, to meet, at all times during the year,
without the governor`'s concurrence, would be to distort government,
to break the due proportion of the parts of it,
to establish confusion in the place of necessary order,
and make the legislative the executive part of government.
Yet, for obtaining this power, I perceive, much time and money have been spent,
and great struggles have been made, not only for this, but some other things,
that cannot at all be for the advantage of the people to be possessed of;
particularly the appointing of judges; because the administration might, by such means,
be so clogged, that it would be difficult, if possible, under our circumstances,
at some times, to support it.
As for my own part,
as I desire nothing more than the tranquility and prosperity of the province and government,
in all its branches.
Could I see that any of these things, that have been contended for,
would certainly promote these ends-,
it would be a matter of indifference to me how they were settled.
But seeing the frame of every government ought to be regular in itself,
well-proportioned and subordinate, in its parts,
and every branch of it invested with sufficient power to discharge its respective duty,
for the support of the whole,
I have cause to believe that nothing could be more destructive to it,
than to take so much of the provision and executive part of the government,
out of the governor`'s hands, and lodge it in an uncertain collective body;
and more especially since our government is dependent, and I am answerable to the crown,
if the administration should fail, and a stop be put to the course of justice.
On these considerations I cannot think it prudent in the people, to crave these powers;
because not only I, but they themselves, would be in danger of suffering by it.
Could I believe otherwise, I should not be against granting anything of this kind,
that were asked of me with any degree of common prudence and civility.
But, instead of finding cause to believe that the contentions
which have been raised about these matters,
have proceeded only from mistakes of judgment, with an earnest desire, notwithstanding,
at the bottom, to serve the public (which, I hope,
has still been the inducement of several concerned in them) I have had but too
sorrowful a view and sight to complain of the manner in which I have been treated.
The attacks on my reputation, the many indignities put upon me, in papers sent over here,
into the hands of those who could not be expected
to make the most discreet and charitable use of them;
the secret insinuations against my justice, besides the attempt made upon my estate;
resolves past in the assemblies, for turning my quit-rents, never sold by me,
to the support of government; my lands entered upon, without any regular method;
my manors invaded,
(under pretence I had not duly surveyed them) and both these by
persons principally concerned in these attempts against me here;
a right to my overplus land unjustly claimed by the
possessors of the tracts in which they are found;
my private estate continually exhausting, for the support of that government,
both here and there; and no provision made for it by that country;
to all which I cannot but add,
the violence that has been particularly shown to my secretary; of which (though I shall,
by no means, protect him in anything, he can be justly charged with,
but allow him to stand or fall by his own actions,) I cannot but thus far take notice,
that, from all the charges I have seen or heard of, against him, I have cause to believe,
that had he been as much in opposition to me, as he has been understood to stand for me,
he might have met with a milder treatment from his prosecutors;
and to think that any man should be the more exposed there, on my account, and,
instead of finding favour, meet with enmity, for his being engaged in my service,
is a melancholy consideration!
In short, when I reflect, on all these heads, of which I have so much cause to complain,
and, at the same time,
think of the hardships I and my suffering family have been reduced to,
in no small measure owing to my endeavours for, and disappointments from, that province,
I cannot but mourn the unhappiness of my portion, dealt to me from those,
of whom I had reason to expect much better and different things;
nor can I but lament the unhappiness, that too many of them are bringing on themselves,
who, instead of pursuing the amicable ways of peace, love and unity, which I, at first,
hoped to find in that retirement, are cherishing a spirit of contention and opposition;
and, blind to their own interest, are oversetting that foundation,
on which your happiness might be built.

Friends, the eyes of many are upon you;
the people of many nations of Europe look on that country, as a land of ease and quiet,
wishing to themselves, in vain, the same blessings which they conceive you enjoy: but,
to see the use you make of them, is no less the cause of surprise to others,
while such bitter complaints and reflections are seen to come from you,
of which it is difficult to conceive even the sense or meaning.
Where are the distresses, grievances and oppressions, that the papers sent from there,
so often say, you languish under! while others have cause to believe,
you have hitherto lived, or might live, the happiest of any, in the queen`'s dominions?

Is it such a grievous oppression, that the courts are established by my power,
founded on the king`'s charter, without a law of your making,
when upon the same plan you propose?
If this disturb any, take the advice of other able lawyers on the main,
without tying me up to the opinion of principally one man,
whom I cannot think so very proper to direct in my affairs (for
I believe the late assembly have had but that one lawyer among
them) and I am freely content you should have any law,
that, by proper judges, should be found suitable.
Is it your oppression that the officers`' fees are not settled by an act of assembly?
No man can be a greater enemy to extortion, than myself: do, therefore,
allow such fees as may reasonably encourage fit persons to undertake these offices,
and you shall soon have (and should have always cheerfully had) mine,
and I hope my lieutenant`'s concurrence and approbation.
Is it such an oppression, that licences for public houses have not been settled,
as has been proposed?

It is a certain sign you are strangers to oppression, and know nothing but the name,
when you so highly bestow it on matters so inconsiderable; but that business, I find,
is adjusted.
Could I know any real oppression, you lie under,
that is in my power to remedy (and what I wish you would take proper measures to remedy,
if you truly feel any such) I would be as ready, on my part, to remove them,
as you to desire it;
but according to the best judgment I can make of the complaints
I have seen (and you once thought I had a pretty good one) I must,
in a deep sense of sorrow, say, that I fear the kind hand of Providence,
that has so long favoured and protected you, will,
by the ingratitude of many there to the great mercies of God, hitherto shown them,
be at length provoked to convince them of their unworthiness; and,
by changing into calamities the blessings that so
little care has been taken by the public to deserve,
reduce those who have been so clamorous and causelessly discontented,
to a true but smarting sense of their duty.
I write not this with a design to include all; I doubt not,
many of you have been burdened at, and can, by no means join in,
the measures that have been taken;
but while such things appear under the name of an
assembly that ought to represent the whole,
I cannot but speak more generally than I would desire,
though I am not insensible what methods may be used to obtain the weight of such a name.

I have already been tedious, and shall now, therefore, briefly say,
that the opposition I have met with from there must, at length,
force me to consider more closely of my own private and sinking circumstances,
in relation to that province.
In the mean time, I desire you all seriously to weigh what I have written,
together with your duty to yourselves, to me, and to the world,
who have their eyes upon you, and are witnesses of my early and earnest care for you.
I must think there is a regard due to me, that has not of late been paid; pray, consider,
of it fully, and think soberly, what you have to desire of me, on the one hand,
and ought to perform to me, on the other; for, from the next assembly,
I shall expect to know what you resolve, and what I may depend on.
If I must continue my regards to you,
let me be engaged to it by a like disposition in you towards me.
But if a plurality after this shall think they owe me none,
or no more than for some years I have met with, let it, on a fair election,
be so declared, and I shall then, without further suspense,
know what I have to rely upon.
God give you his wisdom and fear to direct you,
that yet our poor country may be blessed with peace, love and industry,
and we may once more meet good friends, and live so to the end; our relation,
in the truth, having but the same true interest.

I am, with great truth and most sincere regard, your real friend,
as well as just proprietor and governor,

[.signed-section-signature]
William Penn.

--

It does not appear that any reply was returned by the assembly to this epistle.
But the effect upon the people of the province seems to have been electric.
The measures to which he alluded in the penultimate paragraph, most probably alarmed them.
To be transferred from the paternal government of the benevolent father of his country,
to that of the crown, even when Anne held the sceptre,
was not likely to diminish the grievances of which they so loudly complained.
The consequence was, that at the ensuing election,
an entirely new set of members was returned to the assembly;
and a degree of harmony between them and the governor,
which had been unknown for several years, marked the progress of the session;
and this state of things continued with little interruption,
during the short time in which William Perm was capable
of taking an active part in these concerns.

It may be proper to mention,
though not immediately connected with the biography of William Penn,
that during the administration of Governor Gookin,
an effort was made by the legislature of Pennsylvania,
to check the importation of African slaves.
The Yearly Meeting of Friends, as noted in a former chapter, in the year 1696,
had expressed its disapprobation of the traffic;
and it does not appear that the people of Pennsylvania were ever deeply engaged in it.
But the effort now made to restrain it by legislative
authority was overruled by the mother country.
The encouragement of that abominable commerce,
was then a part of the settled policy of Great Britain.
In the treaty of Utrecht, a stipulation was made, securing to the South Sea Company,
the privilege of importing annually, from 1713 to 1743,
four thousand eight hundred negroes, into the Spanish West Indies.

In the year 1712, William Penn agreed with the ministers of the crown,
upon a sale of his interest in the province and territories,
to which he had devoted so large a part of his laborious life.
His pecuniary difficulties and the impossibility
of giving his personal attention to their concerns,
were probably the moving causes of this measure.
The sum to be paid was twelve thousand pounds;^
footnote:[The smallness of this sum, is no inconsiderable evidence,
that the original grant, in 1681,
was not considered or intended as the payment of
a debt amounting to sixteen thousand pounds.
For notwithstanding the quantity of land which had been sold,
the proprietary rights which remained in 1712,
were unquestionably of much greater value at that
time than the whole wilderness province was in 1681;
particularly,
as the Indian claims to the most valuable parts of
the province had been extinguished by amicable purchase.]
one thousand of which were actually paid.
But before the documents for making a legal transfer, were completed,
he was attacked with a disease of an apoplectic character,
which left him with a memory so far impaired,
that he was judged incompetent to their execution.

He had, in the same year, three attacks of this distemper,
the last of which appeared at the time, likely to close his earthly career.
He at length revived, but his understanding and memory were so completely prostrated,
that he was never afterwards capable of public action.

In the following year, 1713, an intimate friend, who spent a few days at his house,
relates that he found him pretty well in health, and cheerful of disposition,
but defective in memory, so that though he could relate many past transactions,
yet he could not readily recollect the names of absent persons;
nor could he deliver his words so readily as formerly:
yet he uttered many sensible and savoury expressions,
which rendered his company still acceptable,
and manifested the religious settlement and stability of his mind.

In the spring of 1714, the same Friend, paying another visit,
found him but little changed since the former year.
The Friend went with him in his chariot to meeting at Reading,
where he spoke several sensible sentences, but was not able to say much.
At parting, he took leave of his friends with much tenderness and affection.

In the autumn, or beginning of winter, of the same year,
he was visited by his intimate friend, Thomas Story,
who was then just returned from America.
He found his memory almost gone, and the use of his understanding suspended;
so that he was not so conversable as formerly,
but as near the Truth in the love of it as before.
He was then incapable of any business,
and yet as sensible of the enjoyment of the Truth as at any time in his life.

[.embedded-content-document]
--

When I went, +++[+++says he,+++]+++ to his house,
I thought myself strong enough to see him in that condition; but when I entered the room,
and perceived the great defect of his expressions for lack of memory,
it greatly bowed my spirit,
under a consideration of the uncertainty of all human qualifications;
and what the finest of men are soon reduced to, by a disorder of the organs of that,
body with which the soul is connected and acts, during this present state of being.
When these are a little obstructed in their various functions,
a man of the clearest parts and finest expression, becomes scarcely intelligible.
Nevertheless, no insanity or lunacy at all appeared in his actions;
and his mind was in an innocent state,
as appeared by his very loving deportment to all that came near him.
And that he had a good sense of truth was plain,
by some very clear sentences he spoke in the life and power of truth,
in an evening meeting we had there; wherein we were greatly comforted,
so that I was ready to think this was a sort of sequestration
of him from all the concerns of this life,
which so much oppressed him; not in judgment, but in mercy,
that he might not be oppressed thereby to the end.

--

In 1715, the annual visit of the first-mentioned Friend was repeated.
His memory was found to be still more defective,
but his love of the Truth and sense of religious enjoyment apparently continued;
for he frequently went in his chariot to the meeting at Reading,
and there sometimes uttered short, but sound and savoury expressions.

In the year 1716, the same Friend and another paid him a visit.
He seemed glad to see them, though he could not remember their names;
yet it appeared by his answers that he knew their persons.
He was then much weaker than in the former year,
but still at times expressed himself sensibly.
When they were about going away, he took leave of them in these words.
"`My love is with you; the Lord preserve you,
and remember me in the everlasting covenant.`"

In the summer of 1717, the same Friend found his understanding so much impaired,
that he scarcely knew his old acquaintances;
he was almost too weak to walk without assistance;
and he could hardly express himself intelligibly.
Thus his powers of body and mind suffered a gradual decline for about six years.

On the 24th of fifth month, 1718,
Thomas Story paid him a visit and remained with him till the 27th,
when he left him and proceeded to Bristol;
at which place he received a letter from Hannah Penn,
informing him of the decease of her husband,
who departed on the 30th. No symptoms of the disorder of which he died,
were observable when Thomas Story left him three days before.

We find by what little remains of the closing years of this remarkable man,
that as he was made willing in his youthful days, to purchase the pearl of great price,
the consolation which flows from the Divine presence and
a conscience void of offence toward God and toward man,
whatever it might cost, so in his closing period,
when his mind was incapable of enjoyment from any other source,
the consolations of religion continued unabated.
Thus, though a cloud was permitted to cover his understanding,
yet as regards his everlasting prospects, his sun went down in brightness.

The account given by Thomas Story relative to his funeral, is in the following words:

[.embedded-content-document.testimony]
--

On the 1st of sixth month, we arrived at Rushcomb late in the evening,
where we found the widow and most of the family together.
Our coming occasioned a fresh remembrance of the deceased,
and also a renewed flood of many tears from all eyes.
A solid time we had, but few words among us for some time;
for it was a deep baptizing season, and the Lord was near at that time.

Here I stayed till the 5th, and that day accompanied the corpse to the grave,
at Jordan`'s meeting-place, in the county of Bucks,
where we had a large meeting of Friends and others, from many places.
And as the Lord had made choice of him, in the days of his youth,
for great and good services,
and had been with him in many dangers and difficulties of various kinds;
so he did not leave him in his last moments,
but honoured the occasion with his blessed presence,
and gave us a happy season of his goodness, to the general satisfaction of all,
the meeting being well spoken of by strangers afterwards.

--

Having now traced the course of William Penn from
his youth to the close of his earthly pilgrimage,
a few lines may with propriety be added,
in relation to the great outlines of his character.

That he possessed extraordinary powers of mind,
is sufficiently proved by the numerous valuable works which he left behind him.
And that he was zealously devoted to the promotion of pure and undefiled religion,
is clearly demonstrated by his extensive and continual labours,
either in the ministry of the word or by his pen.
Of his contemporaries, there were probably none who enjoyed more favourable opportunities,
or possessed better qualifications,
to judge of his religious character than Thomas Story.
He introduces his acquaintance with him in the year 1693, in the following terms.
"`We had the satisfaction to meet with our eminent and honourable Friend, William Penn,
which was the first time I saw him; and with whom at that time,
I contracted so near a friendship, in the life of Truth,
and tendering love thereof in many tears, as never wore out to his dying day;
and in which his memory still lives, as a sweet odour in my mind,
as a faithful servant of the Lord, a man of God indeed in his time.`"
Afterwards, in the following year,
when Thomas Story went to London under considerable fear,
being then young in the ministry,
he found great encouragement from the fatherly care
and behaviour of the ministers in general,
"`but especially of that great minister of the Gospel and faithful servant of Christ,
William Penn; who abounded in wisdom, discretion, prudence,
love and tenderness of affection, with all sincerity, above most in this generation;
and indeed I never knew his equal.`"

After the death of William Penn,
the province of Pennsylvania became subject to considerable
contests in relation to the rights of his family.
The claims of his heirs were resisted by many of the inhabitants.
Those disputes, indeed, may be easily traced to a period antecedent to his decease;
but they assumed a more acrimonious character afterwards.
Hence arose the proprietary and the popular parties; whose disputes and animosities,
have caused some unfounded reflections to be cast upon the memory of the venerable founder;
but we are furnished with unquestionable evidence of the regard
which Friends of Pennsylvania bore for his integrity and services,
by the following testimony issued a few months after his death.

[.asterism]
'''

[.embedded-content-document.testimony]
--

[.blurb]
=== A Testimony of Friends in Pennsylvania Concerning Their Deceased Friend and Governor, William Penn.

We find ourselves under obligation and concern, both in duty and affection,
to give this mark of our love and the honourable regard we bear
to the memory of our late worthy governor and well-beloved friend,
William Penn;
though it may not be our part to attempt so ample
and general a testimony as seems justly called for,
by his early convincement of the blessed Truth, his noble resignation thereunto,
his steadfastness therein, and great services to the church of Christ;
as well by incessant labours in word and doctrine,
(made more extensive by the many excellent writings he has
published,) as his valiant sufferings for purity of worship,
and the testimonies he had received,
which to him might be the greater trial and conflict,
his birth and station in the world placing him more
in the notice of those of high rank among men,
than was commonly the lot of many others of our worthy elders.
Neither can it, we presume, be forgotten, how,
when it pleased the Lord to give some ease to his people,
this our dear friend employed the interest he then had with success,
and devoted his time and purse to serve,
not only his friends in their religious liberties, but them and others distressed,
or any lacking favour even to the neglect of his own just interest.
But these memorials we leave to be made by those of our worthy elders in Great Britain,
who have more instances and greater knowledge of those his trials, services, and labours,
than many of us can be presumed to be so fully acquainted with.

Yet it becomes us particularly to say, that as he was our governor,
he merited from us love and true honour,
and we cannot but have the same regard to his memory,
when we consider the blessings and ease we have enjoyed under his government;
and are rightly sensible of his care, affection, and regard,
always shown with anxious concern for the safety and prosperity of the people,
who many of them,
removed from comfortable livings to be adventurers with
him--not so much with views of better acquisitions,
or greater riches, but the laudable prospect of retired,
quiet habitations for themselves and posterity,
and the promotion of truth and virtue in the earth.
And as his love was great and endeavours constant for the happiness of his friends,
countrymen, and fellow-subjects, so was his great tenderness, justice,
and love towards the Indians, from first to last, always conspicuous and remarkable.
Here we cannot but gratefully and humbly acknowledge
to the gracious God of all our mercies,
the wonderful preservation of this colony from such injuries
and barbarous depredations as have befallen most others;
and add that we believe the same love wherewith the Lord had so fully
and effectually prevailed on the heart of this our worthy friend,
was the chief and durable motive of his affection and kind behaviour towards those people;
and was the cause, as he was made a means, of this our peace and preservation;
so that his name remains precious, even among the heathens.

More might be truly said of him as he was the proprietary and governor of this province;
and we now find it our duty,
(incited thereto by the love of our heavenly Father in our souls)
to add a few lines concerning him as he was our worthy elder,
friend, and brother in the blessed Truth; many of us having been often comforted,
edified, and solaced with him in the enjoyment thereof.
As was his testimony, so was his conduct,--edifying and lovely,
administering grace and knowledge.
His behaviour was sweet and engaging, and his condescension great,
even to the weakest and meanest; affable and of easy access;
tender of every person and thing that had simplicity of truth,
or honesty for a foundation.

It was our comfort to understand that after all his various troubles, trials,
and afflictions, when, in an advanced age, infirmity of body,
and a distemper which affected his memory in most other things which befell him,
yet the love of God remained with him,
and his sense thereof was frequently strong and evident, and, we doubt not,
the blessing of the Almighty was his Omega.

So that we have assured hope, those afflictions being put off with his mortal body,
immortality is given him by our Lord Jesus, and as he faithfully bore the cross,
the crown, which was his hope, and long since in his eye, is his possession;
and his soul received into that bliss prepared and appointed for the righteous.

[.signed-section-context-close]
Signed at the time of our General Meeting, held in Philadelphia, the 16th of first month,
1718-19.

--

This testimony bears the signatures of fifty Friends, and among them that of David Lloyd,
who was speaker of the assembly to which in 1710, that pathetic epistle was addressed.

If William Penn did not accomplish, in the settlement of Pennsylvania,
all that his ardent and`' comprehensive mind originally anticipated,
he unquestionably effected more towards establishing the practicability
of supporting a government upon strictly Christian principles,
than ever was effected by any other man.
To disarm by lenient means, the wild and untutored inhabitants of the woods;
to obtain possession by fair and honourable purchase,
of such an extensive tract of country without exciting a murmur among its original occupants;
to bring so many discordant tribes into treaties of friendship and peace;
and to establish a relationship with them,
which was maintained on friendly terms as long as the authorities
of Pennsylvania adhered to the principles of the founder,
was certainly to set an important example to succeeding ages.
If we judge from the history of the early settlers in New England and Virginia,
we shall probably adopt the conclusion,
that there is quite as much difficulty in maintaining the relations of
peace with such people as those who occupied the forests of North America,
as with the civilized nations of Europe;
yet from the experience of William Penn`'s settlement here,
we have ample reason to believe that if the whole continent of
North America had been colonized upon the same Christian principles,
and the system been steadily maintained,
we might at this day have pointed to the western
world for a verification of the prophetic declaration,
that "`nation should not lift up sword against nation,
or the people learn war any more.`"
