[quote.epigraph, , Luke 9:23]
____
And Jesus said unto His disciples:
If any man will come after Me, let him deny himself,
and take up his cross daily, and follow Me.
____

[quote.epigraph, , 2 Tim. 4:7]
____
I have fought a good fight, I have finished my course, I have kept the faith:
Henceforth there is laid up for me a crown of righteousness, etc.
____

== Forward

The treatise entitled "`No Cross, No Crown,`"
written by William Penn (1644-1718)
during his imprisonment in the Tower of London,
in 1668, has justly been considered among the best productions of his pen.
His education and rank in life eminently qualified him to judge of the emptiness, vanity,
and sinfulness of those worldly pleasures and compliances which he here censures,
and against which he produces such conclusive arguments from the Holy Scriptures.
Admired and courted for his talents and accomplishments,
beloved for his amiable disposition and engaging manners,
with the road to honor and preferment open before him,
he had all the inducements that the world could offer to pursue its gratifications.
But in the vigor and freshness of youth, when all before him was bright and promising,
in obedience to the will of his heavenly Father,
William Penn voluntarily relinquished his prospects of earthly honor and advantage,
renounced the fashions and customs of the age, and lived a serious, self-denying life,
in conformity with the example of the holy men of ancient time
and the precepts of our Lord and His apostles,
as set forth in the Scriptures of Truth.

In consequence of this change he endured much
opposition from his relations and friends,
and was even banished from his father`'s house.
But neither these trials nor his subsequent imprisonment,
could shake his constancy nor induce him to shrink from
what he believed to be his religious duty.
And God, whom he endeavored to serve and honor in the midst of scorn and reproach,
not only supported him above the fear of man,
and filled his soul with peace and contentment,
but restored his place in the esteem and affections of his relatives,
and made him honorable in the eyes of the world for his Christian virtues.
His father loved him with increased tenderness,
and with his dying breath bore testimony in favor of
the religious principles which his son had adopted.

William Penn was in the twenty-fourth year of his age when he wrote "`No Cross,
No Crown.`"
It was not therefore produced by weariness of the world,
or that disgust which arises from long indulgence.
It was the result of a calm and deliberate survey of the world`'s manners and customs,
viewed with the eye of a sincere and devoted Christian.
He thought, and felt, and wrote,
as one sensible of the dignity and noble endowments of man,
and of his high destiny as an immortal being.
The solidity of the argument, the depth of Christian experience,
the exalted morality and pure religion, with which the work is fraught,
commend it to the serious and attentive perusal of all denominations of Christendom.

[.signed-section-signature]
William Evans & Thomas Evans

[.signed-section-context-close]
Editors of [.book-title]#The Friend`'s Library# -- 1837
