== Chapter I. A Crossless Christianity

Though the knowledge and obedience of the doctrine of
the cross of Christ be of infinite importance to the souls of
men--being the only door to true Christianity,
and the path which the ancients ever trod to blessedness--yet,
with extreme affliction let me say, it is so little understood, so much neglected,
and what is worse, so bitterly contradicted, by the vanity, superstition,
and intemperance of professed Christians.
Indeed, such is the state of things in this day,
that we must either renounce a belief in what the Lord Jesus has told us,
that "`whosoever does not take up His daily cross, and come after Me,
cannot be My disciple;`" or, admitting it for truth,
conclude that the generality of Christians do miserably
deceive themselves in the great business of Christianity,
and disappoint their own salvation.

For,
let us be ever so tender and charitable in the survey of those
nations that claim an interest in the holy name of Christ,
if we will be just too,
we must acknowledge that after all the gracious advantages of light
which these latter ages of the world have received--by the coming,
life, doctrine, miracles, death, resurrection, and ascension of Christ,
with the gifts of His Holy Spirit; to which we can add, the writings,
labors and martyrdom of His dear followers in all times--there
seems very little left of Christianity but the name.
And lamentably, the name Christian, being now usurped by the old heathen nature and life,
makes so many of the professors of it but true heathens in disguise.
For though they do not worship the same idols,
yet they worship Christ with the same heart; and they can never do otherwise,
while they live in the same lusts.
The unmortified Christian and the heathen are of the same religion.

For though they have different objects to which they direct their prayers,
still the adoration in both is but forced and ceremonious,
and the deity they truly worship is the god of this world, the great lord of lusts;
to him they bow with all the powers of soul and sense.
What shall we eat?
What shall we drink?
What shall we wear?
And how shall we pass away our time?
Which way may we gather wealth, increase power, enlarge our territories,
and dignify and perpetuate our names and families in the earth?
This base sensuality is comprised by the beloved apostle John in these words:
"`The lust of the flesh, the lust of the eye, and the pride of life,
which are not of the Father, but of the world that lies in wickedness.`"^
footnote:[1 John 2:16-5:19]

It is a mournful reflection, but a truth which will not be denied,
that these worldly lusts fill up a great part of the study, care,
and conduct of Christendom.
And, what aggravates the misery is that these things grow with time.
For as the world is older, it is worse.
The examples of former lewd ages, and their miserable conclusions, have not deterred,
but rather excited ours.
Indeed, the people of this day, seem improvers of the old stock of impiety,
and have carried it so much farther than former examples,
that instead of advancing in virtue,
they have scandalously fallen below the life of heathens.
Their high-mindedness, lasciviousness, uncleanness, drunkenness, swearing, lying, envy,
backbiting, cruelty, treachery, covetousness, injustice and oppression,
are so common and committed with such invention and excess,
that they have stumbled and embittered infidels and made them scorn that
holy religion to which their good example should have won their affections.

This miserable defection from primitive times,
when the glory of Christianity was the purity of its professors,
I cannot but call the second and worst part of the
tragedy which came upon the blessed Savior of mankind.
For the Jews,
from the power of ignorance and their prejudice
against the unworldly way of His appearance,
would not acknowledge Him when He came,
and so for two or three years persecuted and finally crucified Him in one day.
But the false Christians`' cruelty lasts much longer.
They have first, with Judas, professed Him, and then, for these many ages,
most basely betrayed, persecuted,
and crucified Him by a perpetual apostasy in conduct
from the self-denial and holiness of His doctrine;
their lives showing the falseness of their faith.
These are they that the author of the epistle to the Hebrews tells us,
"`crucify to themselves the Son of God afresh, and put Him to open shame.`"^
footnote:[Hebrews 6:6]
Their defiled hearts, John, in his revelation, calls,
"`the streets of Sodom and Egypt spiritually so-called,`"^
footnote:[Revelation 11:8]
where he beheld the Lord Jesus crucified long after He had ascended.
As Christ said of old, that a man`'s enemies are those of his own house;
so Christ`'s enemies now are chiefly those of His own profession.
Indeed, these spit upon Him, nail and pierce Him, crown Him with thorns,
and give Him gall and vinegar to drink.
Nor is this hard to apprehend;
for they that live in the same evil nature and seed that the Jews did,
who crucified Him outwardly, must necessarily crucify Him inwardly.
They that reject the grace now in their own hearts,
are one in stock and generation with the hard-hearted Jews who
resisted the grace that then appeared in and by Christ.

Sin is of one nature all the world over; for though a liar is not a drunkard,
nor a swearer a whoremonger, nor are either properly a murderer,
yet they are all of one church, all branches of the one wicked root, all of one family.
They have but one father, the devil, as Christ said to the professing Jews,
the visible church of that age.
He slighted their pretensions to Abraham and Moses, and plainly told them,
"`He that committed sin, was the servant of sin.`"^
footnote:[John 8:34]
They did the devil`'s works, and therefore were the devil`'s children.
This argument will always hold upon the same reasons, and therefore is good still.
"`His servants you are,`" says Paul, "`whom you obey.`"^
footnote:[Romans 6:16]
And John says to the church of old,
"`Let no man deceive you, he that commits sin is of the devil.`"^
footnote:[1 John 3:8]
Was Judas a better Christian for crying, "`Hail, master!`" and kissing Christ?
By no means!
These words were the signal of his treachery,
the token given by which the bloody Jews should know and take Him.
He called Him Master, but betrayed Him.
He kissed, but sold Him to be killed.
This is the substance of the false Christian`'s religion.
If a man ask them, "`Is Christ your Lord?`"
They will cry, "`God forbid anything else!
Yes, He is our Lord!`" "`Very well, but do you keep His commandments?`"
"`No, how should we?`"
"`How then are you His disciples?`"
"`It is impossible,`" they say,
"`What! Would you have us keep His commandments? No man can!`"
But is it impossible to do that,
without which Christ has made it impossible to be a Christian?
Is Christ unreasonable?
Does He reap where He has not sown, or require where He has not enabled?
Thus it is, that, with Judas, they call Him Master,
but take part with the evil of the world to betray Him.
They kiss and embrace Him, as far as their profession goes;
and then sell Him to gratify the passions they most indulge.

Let no man deceive his own soul; grapes are not gathered of thorns,
nor figs of thistles; a wolf is not a sheep, nor is a vulture a dove.
Whatever form, people, or church you are of, this is the truth of God to mankind:
they who have the form of godliness, but by their unmortified lives deny its power,
make up the false church, not the true.
And though this church may call herself the Lamb`'s bride, or the church of Christ,
she is that mystery or mysterious Babylon, who is fitly called by the Holy Spirit,
"`the mother of harlots, and all abominations.`"^
footnote:[Revelation 17:5]
She has degenerated from Christian chastity and purity,
into all the enormities of heathen Babylon--a sumptuous city of old time,
much noted as the seat of the kings of Babylon,
and at that time a place of the greatest pride and luxury.
As she was then, so mystical Babylon is now, the great enemy of God`'s true people.

True it is that they who are born of the flesh,
hate and persecute those who are born of the Spirit, the circumcised in heart.
These cannot acknowledge nor worship God according to Babylon`'s inventions, methods,
and prescriptions, nor receive for doctrine her vain traditions,
any more than they can comply with her corrupt fashions and customs in their conduct.
And because they cannot conform, apostate Babylon quickly turns persecutor.
It is not enough that she herself declines from ancient purity; others must do so too.
She will give those no rest who will not partake with her in her degeneracy,
or receive her mark.
Are any wiser than she, than the so-called mother church?
No, no,
nor can any make war with the beast she rides upon--those worldly powers that
protect her and vow to maintain her against the cries of her dissenters.
Apostasy and superstition are ever proud and impatient of dissent.
All must conform or perish.
Therefore the slain witnesses, and the blood of the souls under the altar,
are found within the walls of this mystical Babylon, this great city of false Christians,
and are charged upon her by the Holy Spirit in the book of Revelation.

The children of Babylon are reduced so entirely under the dominion of darkness,
by means of their continued disobedience to the
manifestation of the divine light in their souls,
that they forget what man once was, or what they should now be.
They do not recognize true and pure Christianity when they meet it,
though they pride themselves in professing it.
Their views about salvation are so carnal and false, that they call good evil,
and evil good.
They make a devil a Christian, and a saint a devil.
And though the unrighteous indulgence of their lives is a
source of lamentation (as it is of destruction to themselves),
yet the false notion that they may be children of God while in
a state of disobedience to His holy commandments,
is, of all other deceptions, the most deadly to their eternal condition.
Alas, they believe they are disciples of Jesus even though they revolt from His cross.
They flatter themselves members of His true church which is without spot or wrinkle,
notwithstanding their lives are full of spots and wrinkles.
For they are at peace in sin, and under security in their transgression.

Their vain hope silences their inward convictions and
buries all tender motions to repentance,
so that their mistake about their duty to God is
as mischievous as their rebellion against Him.
Thus they walk on precipices and flatter themselves till the grave swallows them up,
and the judgment of the great God breaks their lethargy and undeceives their poor,
wretched souls with the anguish of the wicked as the reward of their work.

This has been, is,
and will be the doom of all worldly Christians--an end so dreadful,
that compassion alone would be sufficient to excite me to
dissuade all against the world`'s superstition and lusts,
and to invite the professors of Christianity to the knowledge and
obedience of the daily cross of Christ as the only way given by Him,
and appointed unto us to blessedness.
By this daily cross, those who now do but usurp the name may have the thing itself;
and by its power they may be made partakers of the
resurrection that is in Christ Jesus unto newness of life.
For they that are truly in Christ, that is, redeemed by Him and engrafted in Him,
are new creatures.
They have received a new will, such as does the will of God, not their own.
They pray in truth, and do not mock God when they say,
"`Your will be done in earth as it is in heaven.`"^
footnote:[Matthew 6:10; Luke 11:2]
They have new affections, such as are set on things above,
and make Christ their eternal treasure.
They have new faith,
such as overcomes the snares and temptations of the world`'s spirit in themselves,
or as it appears through others.
And they have new works, not of superstitious contrivance, or of human invention,
but the pure fruits of the Spirit of Christ working in them--such as love, joy, peace,
meekness, long-suffering, temperance, brotherly kindness, faith, patience,
gentleness and goodness, against which there is no law.

They who do not have this Spirit of Christ, and walk not in it,
the apostle Paul has told us, "`are none of His;`"^
footnote:[Roman 8:9]
but the wrath of God, and the condemnation of the law, will lie upon them.
There is indeed "`no condemnation to them that are in Christ,
who walk not after the flesh, but after the Spirit.`"^
footnote:[Romans 8:1]
But by this same doctrine,
they who do _not_ walk according to that Holy Spirit are not in Christ.
These have no inheritance in Him, nor a just claim to salvation by Him;
and consequently there _is_ condemnation to such.

=== An Inward Reprover and Savior

The religion of the wicked is a lie: "`There is no peace,`"
says the prophet, "`to the wicked.`"^
footnote:[Isaiah 48:22; Isaiah 57:21]
Indeed there can be none,
for they are reproved in their own consciences and condemned
in their own hearts for all their disobedience.
Go where they will, rebukes go with them, and oftentimes terrors too.
It is an offended God who pricks them,
and by His light "`sets their sins in order before them.`"^
footnote:[Ps. 50:21]
Sometimes they strive to appease Him by their outward devotion and worship, but in vain;
for the true worship of God is the doing of His will, which will they transgress.
Sometimes they fly to sports and company to
drown the Reprover`'s voice and blunt His arrows,
to chase away troubled thoughts and secure themselves
out of the reach of the Disquieter of their pleasures.
But the Almighty, sooner or later, is sure to overtake them.
There is no flying from His justice for those who reject the terms of His mercy.
Indeed their Accuser is always with them,
they can no more be rid of Him than of themselves.
He is in the midst of them, and will stick close to them.
That Spirit which bears witness with the spirits
of the just will bear witness against theirs.
Yes, their own hearts will abundantly condemn them;
and "`if our heart condemns us,`" says the apostle John,
"`God is greater, and knows all things;`"^
footnote:[1 John 3:20]
that is, there is no escaping the judgments of God if a man is
not able to escape the condemnation of himself.

In that Day,
proud and luxurious Christians shall learn that God is no respecter of persons;
that all sects, denominations, and names shall be swallowed up in these two kinds:
sheep and goats, just and unjust.
Indeed, the very righteous must be tried, which made a holy man cry out,
"`If the righteous scarcely be saved, where shall the ungodly and the sinner appear?`"^
footnote:[1 Peter 4:18]
If their thoughts, words and works must stand the test,
and come under scrutiny before the impartial Judge of heaven and earth,
how then should the ungodly be exempted?
No, we are told by Him that cannot lie that many shall then cry, "`Lord, Lord!`"
They shall set forth their profession, and recount the works they have done in His name,
and yet be rejected with this awful sentence; "`Depart from Me, you workers of iniquity,
I know you not.`"^
footnote:[Luke 13:24-27]
As if He had said, '`Be gone, you evil-doers; for though you have professed Me,
I do not know you.
Go hence, and go to the gods whom you have served; your beloved lusts,
which you have worshipped, and the evil world that you have so much coveted and adored.
Let them save you now, if they can, from the wrath to come upon you,
which is the wages of the deeds you have done.`'
Here is the end of their work who build upon the sand;
the breath of the Judge will blow it down, and woeful will be its fall.

But to the righteous the sentence is changed, and the Judge smiles.
He casts the eye of love upon His own sheep and invites them with a,
"`Come, you blessed of My Father, who through patient continuance in well-doing,
have long waited for immortality.
You have been the true companions of My tribulations and cross,
and with unwearied faithfulness, in obedience to My holy will,
have valiantly endured to the end, looking unto Me, the Author of your precious faith,
for the recompense of reward, which I have promised to them that love Me and faint not.
O enter into the joy of your Lord,
and inherit the kingdom prepared for you from the foundation of the world.`"

O Christendom!
My soul most fervently prays,
that after all your lofty professions of Christ and His meek and holy religion,
your unsuitable and unchrist-like life may not
cast you off at that great tribunal of the world,
and you lose this great salvation at last.
Hear me once, I beseech you: Can Christ be your Lord and you not obey Him?
Or, can you be His servant and yet not truly serve Him?
Be not deceived, such as you sow, that you shall reap.
He is not your Savior while you reject His grace in your heart by which He would save you.
Come now, what has He saved you from?
Has He saved you from your sinful lusts, your worldly affections and vain conversations?
If not, then He is not your Savior.
For though He be offered a Savior to all,
yet He is actually a Savior to those only who are saved by Him;
and none are saved by Him who still live in those evils by which they are lost to God,
and from which He came to save them.

It is from sin that Christ is come to save man,
and from death and wrath as the wages of it.
But those who are not saved--that is,
truly delivered by the power of Christ in their souls from the power
that sin has had over them--can never be saved from the death and
wrath which are the certain wages of the sin they live in.
So far as people obtain victory over the evil and
fleshly lusts to which they have been addicted,
that far they are truly saved,
and are witnesses of the redemption that comes by Jesus Christ.
Indeed His name shows His work; "`And you shall call His name Jesus,
for He shall save His people from their sins.`"^
footnote:[Matthew 1:21]
"`Behold,`" said John of Christ,
"`the Lamb of God that takes away the sin of the world!`"^
footnote:[John 1:29]
Behold Him, whom God has given as a Light to the people,
and for salvation to as many as receive His light and grace in their hearts,
and take up their daily cross and follow Him--such as would
rather deny themselves the pleasure of fulfilling their lusts,
than sin against the knowledge He has given them of His will,
or do that which they know they ought not to do.
