== Chapter II. A Great Apostasy

By all which has been said, O Christendom,
and by the lamp that the Lord has lit in you (if you would use it),
it should evidently appear: First, how great your backsliding has been;
for instead of the temple of the Lord, you have become a cage of unclean birds;
and instead of a house of prayer, you are a den of thieves, a synagogue of Satan,
and the dwelling of every defiled spirit.
And second, that under all this manifest defection,
you have nevertheless valued your corrupt self
based upon your profession of Christianity,
and fearfully deluded yourself with the hopes of salvation.
The first makes your disease dangerous, but the last makes it almost incurable.

Nevertheless there is mercy with the God of compassion, that He may be feared.
He takes no delight in the eternal death of poor sinners and backsliders,
but desires that all should come to the knowledge and obedience of the truth,
and be saved.
Thus He has sent forth His Son as a propitiation,
and given Him as a Savior to take away the sins of the whole world,
that those who believe and follow Him,
may feel the righteousness of God in the remission of their
sins and the blotting out of their transgressions forever.
Behold the remedy!
An infallible cure, one of God`'s appointing!
A precious antidote indeed that never failed!
A universal medicine which no malady could ever escape!

But you will say, what is Christ, and where is He to be found?
How is He received and applied, in order to work this mighty cure?
I will tell you then: First,
He is the great spiritual Light of the world who
"`enlightens every one that comes into the world.`"^
footnote:[John 1:9]
As such, He manifests to men their deeds of darkness and wickedness,
and reproves them for committing them.
Secondly, He is not far away from you, as the apostle Paul said of God to the Athenians.
And Christ Himself says, "`Behold I stand at the door and knock;
if any man hear My voice and open the door, I will come in to him and sup with him,
and he with Me.`"^
footnote:[Revelation 3:20]
What door can this be, but that of the heart of man?

But alas, like the inn of old, you have been full of other guests.
Your affections have entertained other lovers;
there has been no room for your Savior in your soul.
Therefore salvation has not yet come into your house, though it has come to your door,
and you have often been offered it, and have professed it long.
But if He still calls, if He still knocks, that is,
if His light yet shines and reproves you, then there is hope that your day is not over,
and that repentance is not hidden from your eyes.
Yes, His love is toward you still, and His holy invitation continues in order to save you.

Therefore, O Christendom, believe, receive, and apply Him rightly!
This is of absolute necessity, that your soul may live forever with Him.
He told the Jews, "`If you believe not that I am He, you shall die in your sins;
and where I go, you cannot come.`"^
footnote:[John 8:21,24]
Because they believed Him not, they did not receive Him, nor any benefit by Him.
But they that believed Him, received Him:
"`And as many as received Him,`" His own beloved disciple tells us,
"`to them He gave power to become the sons of God; which are born not of blood,
nor of the will of the flesh, nor of the will of man, but of God.`"^
footnote:[John 1:12-13]
That is, these are not children of God according to the fashions,
prescriptions and traditions of men.
These are not His church and people after the will of flesh and blood,
or the inventions of carnal men unacquainted with the
regeneration and power of the Holy Spirit.
No, these are born of God, according to His will,
and the working and sanctification of His Spirit and Word of life in them.
Such as these are well acquainted with the right application of Christ,
for He is indeed made unto them propitiation, reconciliation, salvation, righteousness,
redemption and justification.

So I say to you,
unless you believe that He who stands at the door of your heart and knocks,
and sets your sins in order before you, and calls you to repentance,
is the Savior of the world, you too will die in your sins; and where He has gone,
you will never come.
For if you do not believe in Him,
it is impossible that He will do you good or effect your salvation.
Christ works not _against_ faith, but by it.
It is said of old,
that He did not do many mighty works in some
places because the people did not believe in Him.
If you truly believe in Him, your ear will be attentive to His voice in you,
and the door of your heart will open to His knocks.
You will yield to the discoveries of His light,
and the teachings of His grace will be very dear to you.

It is the nature of true faith to beget a holy fear of offending God,
a deep reverence for His precepts,
and a most tender regard to the inward testimony
of His Spirit as that by which His children,
in all ages, have safely been led to glory.
For as they that truly believe, receive Christ in all His offers to the soul,
so those who thus receive Him, receive power to become the sons of God; that is,
they receive an inward power and ability to do whatever He requires:
strength to mortify their lusts, to control their affections, resist evil motions,
deny themselves, and overcome the world in its most enticing appearances.
This is the life of the blessed cross of Christ,
which is the subject of the following discourse; and this is what you, O man,
must take up, if you intend to be a disciple of Jesus.
For you cannot truly receive Christ, or believe in Him, while you reject His cross.
Receiving Christ is the means appointed of God unto salvation,
and so bearing your daily cross after Him is the true testimony of having received Him,
and the great token of discipleship.
"`If any man will come after Me, let him deny himself,
and take up his cross, and follow Me.`"^
footnote:[Matthew 16:24]

This, Christendom, is what you have so much lacked,
and the lack of it has proved the cause of your
miserable declension from pure Christianity.
Consider this well, for it is your duty, and will be of great use to your restoration.
As the proper knowledge of a disease guides the physician to make a
right and safe judgment in the application of his medicine,
so it will much enlighten you in the way of your recovery to know and weigh
the first cause of this spiritual fault and malady which has befallen you.
To do this, a general view of the primitive state of Christianity,
and the work of those who first labored in Christ`'s vineyard, will be needful.

=== Primitive Christianity

The work of apostleship, we are told by a principal laborer in it, was,
"`to turn people from darkness to light, and from the power of Satan unto God.`"^
footnote:[Acts 26:18]
That is, instead of yielding to the temptations and motions of Satan,
who is the prince of darkness or wickedness
(the one word being a metaphor for the other)
by whose power their understandings were
obscured and their souls held in the service of sin,
they should turn their minds to the appearance of Christ,
the Light and Savior of the world.
By His light He shines in their souls and thereby gives them a sight of their sins.
He uncovers every temptation and motion in them unto evil,
and reproves them whenever they give way thereto,
that so they might become the children of light, and walk in the path of righteousness.
For this blessed work of reformation,
Christ endued His apostles with His Spirit and power,
that men might no longer sleep in a security of sin and ignorance of God,
but awaken to righteousness, and receive life from the Lord Jesus Christ.
These then were enabled to leave off sinning,
deny themselves the pleasures of wickedness,
and by true repentance turn their hearts to God in well-doing, in which they found peace.
And truly,
God so blessed the faithful labors of these poor
tradesmen (His great ambassadors to mankind),
that, in a few years,
many thousands who had lived without God in the world--without a sense or fear of Him,
in lawlessness and as strangers to the work of His Spirit in their hearts,
being captivated by fleshly lusts--were inwardly
struck and quickened by the Word of life,
and made sensible of the coming and power of the Lord
Jesus Christ as a Judge and Lawgiver in their souls.
By His holy light and Spirit,
the hidden things of darkness were brought to light and condemned,
and pure repentance from those dead works was begotten in them
that they might serve the living God in newness of Spirit.

Consequently, these lived no longer unto themselves,
nor were they carried away by their former lusts
which had seduced them from the true fear of God.
Instead, the law of the Spirit of life
(by which they overcame the law of sin and death)
was their delight, and therein they meditated day and night.
Their regard towards God was no longer derived from the precepts of men,
but from the knowledge they had received by His own work and impressions in their souls.
They had forsaken their old masters--the world,
the flesh and the devil--and delivered themselves up to
the holy guidance of the grace of Christ,
which taught them to "`deny ungodliness and the world`'s lusts, and to live soberly,
righteously and godly, in this present life.`"^
footnote:[Titus 2:11]
This is the cross of Christ indeed:
and here is the victory it gives to those that take it up.
By this cross they died daily to the old life they had lived,
and by a holy watchfulness against the secret motions of evil in their hearts,
they crushed sin in its conception, yes, even in its temptations.
So that, as the apostle John advises, they
"`kept themselves, that the evil one touched them not.`"^
footnote:[1 John 5:18]

The light, which Satan cannot endure, and with which Christ had enlightened them,
uncovered their adversary in all his approaches and assaults upon the mind,
and the power they received through their obedience to the manifestations of that
blessed light enabled them to resist and vanquish him in all his stratagems.
So it was that, where once nothing was examined, now nothing went unexamined.
Every thought must come to judgment,
and the rise and tendency of it must be well approved
before they allowed it any room in their minds.
There was no fear of entertaining enemies for friends while
this strict guard was kept upon the very gateway of the soul.
The old heavens and earth, that is, the old earthly manner of living,
and the old carnal or shadowy worship, passed away quickly,
and every day all things became new.
"`He was no more a Jew who was one outwardly,
nor was circumcision that which was in the flesh; but he was a Jew who was one inwardly;
and circumcision was of the heart, in the spirit and not in the letter,
whose praise is not of man, but of God.`"^
footnote:[Romans 2:28-29]

The glory of the cross shined so conspicuously through
self-denial in the lives of those who daily bore it,
that it filled the heathen with astonishment, and in a small time so shook their altars,
discredited their oracles, struck the multitude, invaded the court,
and overcame their armies, that it led priests,
magistrates and generals in triumph after it as trophies of its power and victory.

While this integrity dwelt with Christians, mighty was the presence,
and invincible the power that attended them.
It quenched fire, daunted lions, turned the edge of the sword,
out-faced instruments of cruelty, convicted judges, and converted executioners.
The ways their enemies sought to destroy them only increased them;
and by the deep wisdom of God,
those who in all their designs endeavored to extinguish
the truth were made great promoters of it.
Among the faithful not a vain thought, nor an idle word,
nor an unseemly action was permitted; no, not even an immodest look.
There was no courtly dress, flashy apparel, flattering addresses, or personal honors;
much less could those lewd immoralities and scandalous vices now in
vogue with Christians find either example or place among them.
Their great care was not how to sport away their precious time, but how to redeem it,
that they might have enough to
"`work out their great salvation with fear and trembling;`"^
footnote:[Philippians 2:12]
not with balls and masquerades, with play-houses, dancing, feasting and gaming, no, no!
To "`make their heavenly calling and election sure`"^
footnote:[2 Peter 1:10]
was much dearer to them than the poor and trifling joys of mortality.

Having, with Moses, "`seen Him that is invisible,`"^
footnote:[Hebrews 11:27]
and found that His loving-kindness was better than life,
and the peace of His Spirit more than the favor of princes,
so they feared not Caesar`'s wrath,
and chose rather to sustain the afflictions of Christ`'s true
pilgrims than to enjoy the passing pleasures of sin.
Yes, they esteemed His reproaches of more value than the perishing treasures of the earth.
And if the tribulations of Christianity were more
desirable to them than the comforts of the world,
and the reproaches of the one more enticing than all the honors of the other,
then there was surely no temptation in the world
that could shake the integrity of Christendom.

=== The Great Apostasy

By this short view of what Christendom was, you may see, O Christendom,
what you are not, and what you ought to be.

But how is it, that from a people so meek, merciful, self-denying, suffering,
temperate, holy, just and good, and so like Christ whose name she bore,
we find a Christendom now that is superstitious, idolatrous, persecuting, proud,
passionate, envious, malicious, selfish, drunken, lascivious, unclean, lying, swearing,
cursing, covetous, oppressing,
defrauding--with all other abominations known in the earth,
and that to an excess justly scandalous to the worst of heathen ages,
surpassing them more in evil than in time: I say,
how came about this lamentable defection?
I offer this as the undoubted reason of this degeneracy, namely:
_the disregard in your mind to the light of Christ shining in you,
which first showed you your sins, reproved them,
and taught and enabled you to deny and resist them._
For it is certain that,
whatever measure of fear towards God and abstinence from unrighteousness you witness,
was not taught by the precepts of men,
but by that light and grace which reveals the
most secret thoughts and purposes of your heart,
searches your most inward parts,
sets your sins in order before you and reproves you for them,
not permitting one unfruitful thought, word, or work of darkness to go unjudged.
So then, when you began to disregard this light and grace,
to be careless about the holy watchfulness that was once set up in your heart,
and did not keep watch there as formerly for God`'s glory and your own peace,
then the restless enemy of man`'s good quickly took advantage of this slackness,
and often surprised you with temptations,
whose suitableness to your own inclinations made his conquest over you not difficult.

Yes, you neglected to take up Christ`'s holy yoke, and to bear your daily cross.
You were careless with your affections, and kept no check upon your actions,
forgetting to keep accounts in your own conscience by Christ your light,
the great Bishop of your soul and Judge of your works.
In this way, your holy fear decayed and your love waxed cold;
and so vanity abounded and duty became burdensome.

Then up came formality, instead of the power of godliness; and superstition,
in the place of Christ`'s working.
And though Christ`'s business was to draw off the minds of His
disciples from an outward temple with its carnal rites and services,
to the inward and spiritual worship of God (suitable to the nature of divinity),
yet a worldly, human, pompous worship is brought in again, and a worldly priesthood,
temple and altar are reestablished.
Now the "`sons of God once more saw that the daughters of men were fair,`"^
footnote:[Genesis 6:2]
that is, the pure eye grew dim which repentance had opened,
and which saw no beauty outside of Christ;
and the eye of lust was opened again by the god of the world.
And then those worldly pleasures--that make such as love them forget God,
though they were once despised for the sake of Christ--began
to recover their old beauty and interest in your affections;
and liking them, they came to be the pursuit, care, and pleasure of your life.

True, there still remained the exterior forms of worship,
and a nominal and verbal reverence to God and Christ.
But this is all that survived; for the offense of the holy cross ceased,
the power of godliness was denied, self-denial was lost,
and though you became fruitful in the invention of ceremonious ornaments,
you remained barren in the blessed fruits of the Spirit.
And alas, a thousand shells cannot make one kernel,
nor can many dead corpses make one living man.

Thus religion fell from experience to tradition, and worship from power to form,
from life to letter.
Instead of putting up lively and powerful requests to God,
animated by a deep sense of need and the assistance of the Holy Spirit
(by whom the ancients prayed, wrestled and prevailed with God);
behold, a prescribed repetition,
a dull and insipid formality, made up of bowing and kneeling,
special garments and furniture, perfumes,
voices and music--a performance fitter for the reception of some earthly prince,
than for the heavenly worship of the only true and immortal God,
who is an eternal and invisible spirit.

As your heart grew carnal, your religion did so too; and not liking it as it was,
you fashioned it to your liking.
No doubt you forgot the words of the holy prophet,
"`The sacrifice of the wicked is an abomination to the Lord,`"^
footnote:[Proverbs 15:8]
and the saying of James, "`You ask and receive not,`" and why?
"`because you ask amiss,`" that is, with a heart that is not right, but insincere,
and unmortified, not in the faith that purifies the soul,
and so can never receive what is asked.
Thus it may now be said in truth,
that the condition of many is made worse by their religion,
for they are tempted to think themselves the better for it, though they are not.

By this view that is given of your fall from primitive Christianity,
and the true cause of it-- namely,
a neglect of the daily cross of Christ--I trust
the way of your recovery may be easily seen.
At the door by which you went out, you must come in.
As all was lost through neglecting and letting fall the daily cross,
so taking up and enduring the daily cross will be your means of recovery.
This is the way by which sinners and apostates become the disciples of Jesus.
"`Whosoever,`" says Christ,
"`will come after Me and be My disciple, let him deny himself,
and take up his daily cross, and follow Me.`"
Nothing short of this will do.
As it is sufficient, so is it indispensable.
There is no crown but by the cross; no life eternal but through death.
And it is only just that those evil and barbarous
affections that crucified Christ afresh,
should now, by His holy cross, be crucified in you.
Blood requires blood; His cross is the death of the sin that caused His death;
and He is the death of death, according to that passage,
"`O death! I will be your death!`"^
footnote:[Hosea 13:14, Vulgate]
