== Chapter III. The Daily Cross

Therefore, O Christendom,
the daily cross being both then and now the only way to glory,
it will be to the great advantage to your soul to most seriously consider:

[.numbered]
_First,_ What the cross of Christ is.

[.numbered]
_Secondly,_ Where the cross of Christ is to be taken up.

[.numbered]
_Thirdly,_ How and after what manner it is to be borne.

[.numbered]
_Fourthly,_ What is the great work and business of the cross.

As to the first--What is the cross of Christ?
The cross of Christ is a figure of speech, borrowed from the outward tree,
or wooden cross, on which Christ submitted to the will of God,
in permitting Him to suffer death at the hands of evil men.
The mystical or daily cross is that divine grace and
power which crucifies the carnal wills of men,
contradicts their corrupt affections,
and constantly opposes the inordinate and fleshly appetites of their minds.
This power may be justly termed the instrument of man`'s holy dying to
the world and being made conformable to the will of God.
Nothing else can mortify sin,
or make it easy for us to submit to the divine will in
things otherwise very contrary to our own.

"`The preaching of the cross`" in primitive times was
fitly called by Paul (that famous and skillful apostle in
spiritual things) "`the power of God,`"^
footnote:[1 Corinthians 1:18]
though to them that perish, it was then, as now, foolishness.
That is, to those who were truly weary and heavy laden and in need of a deliverer,
to whom sin was burdensome and odious,
the preaching of the cross (by which sin was to be mortified) was the power of God,
or the preaching of the divine power by which they were
made disciples of Christ and children of God.
And this power wrought so mightily upon them that no proud or
licentious mockers could put them out of love with it.
But to those who walked in the broad way, in the full latitude of their lusts,
and dedicated their time and care to the pleasure of their corrupt appetites,
to whom all yokes and bridles were and are intolerable,
to these the preaching of the cross was and is foolishness.

Where does this cross appear, and where must it be taken up?
I answer, within; that is, in the heart and soul--for where the sin is,
there the cross must be.
All evil comes from within.
Christ taught, "`From within, out of the heart of man proceed evil thoughts, adulteries,
fornications, murders, thefts, covetousness, wickedness, deceit, lasciviousness,
an evil eye, blasphemy, pride, foolishness: all these evils come from within,
and defile the man.`"^
footnote:[Mark 7:21-23]
The heart of man is the seat of sin, and where he is defiled,
there he must be sanctified; where sin lives, there it must die, it must be crucified.
Custom in evil has made it natural for men to do evil; and as the soul rules the body,
so this corrupt nature sways the whole man.
But still, it is all from within.

Experience teaches every son and daughter of Adam the truth of this.
The enemy`'s temptations are ever directed to the heart or mind, which is within:
if they take not, the soul sins not; but if they are embraced,
then lust (or inordinate desire) is immediately conceived,
and as the apostle says,"`when lust has conceived, it brings forth sin;
and when sin is finished (that is, acted) it brings forth death.`"^
footnote:[James 1:15]
Here is both the cause and the effect, the genealogy of sin, its rise and its end.

In all this, the heart of evil man is the devil`'s mint, his work-house,
the place of his residence, where he exercises his power and art.
Therefore the redemption of the soul is aptly called
"`the destruction of the works of the devil,`"^
footnote:[1 John 3:8]
and "`the bringing in of everlasting righteousness.`"^
footnote:[Daniel 9:24]
When the Jews would have defamed Christ`'s miracle of casting out
devils by a blasphemous imputation of it to the power of Beelzebub,
Christ says, "`No man can enter into a strong man`'s house, and spoil his goods,
till he first bind the strong man.`"^
footnote:[Matthew 12:29]
This both shows us the contrariety between Beelzebub
and the power by which Christ dispossessed him,
and it teaches us that the souls of the wicked
are the devil`'s "`house,`" and that his goods,
his evil works, can never be destroyed until he that wrought them,
and keeps the house, is bound.
All this makes it easy to know where the cross must be taken up,
by which alone the strong man can be bound, his goods spoiled,
and his temptations resisted--that is, within, in the heart of man.

In the next place, how, and in what manner, is the cross to be daily borne?
The way, like the cross, is spiritual.
_It is an inward submission of the soul to the will of God as it is
manifested by the light of Christ in the consciences of men,_
though it be contrary to their own inclinations.
For example; when evil presents,
that which reveals the evil does also instruct not to yield to it,
and if a man complies with its counsel, it gives him power to escape it.
But they that look and gaze upon the temptation,
at last fall in with it and are overcome by it;
the consequence of which is guilt and judgment.

Therefore, as the cross of Christ is that Spirit and power in men
(though not of men, but of God)
which crosses and reproves the fleshly lusts and affections,
_so the way of taking up the cross is an entire resignation of
soul to the discoveries and requirings of it,
without consulting worldly pleasure,
or carnal ease or interest_
(for these are captivated in a moment).
Thus the soul must continually watch against every appearance of evil, and,
by the obedience of faith
(in true love to, and confidence in God)
cheerfully offer up to the death
of the cross that evil nature in themselves which,
not enduring the heat of the siege, and being impatient in the hour of temptation, would,
by its near relation to the tempter, easily betray their souls into his hands.

This may show to everyone`'s experience
how hard it is to be a true disciple of Jesus!
The way is narrow indeed, and the gate very strait, where not a word, no,
not a thought must slip the watch, or escape judgment.
Such circumspection, such caution, such patience, such constancy,
such holy fear and trembling, give an easy interpretation to that hard saying,
"`Flesh and blood cannot inherit the kingdom of God.`"
For those who are captivated with fleshly lusts and affections cannot bear the cross;
and those that cannot endure the cross, must never have the crown.
To reign, it is necessary first to suffer.
