== Chapter IV. Denying Lawful Self

Fourthly, what is the great work and business of the cross respecting man?
It is of such great importance that this be truly, plainly and thoroughly answered,
that all that went before seems only to serve as a preface to it.
Miscarrying in this is no less than a misguidance of
the soul about its way to blessedness.
I shall therefore pursue the question, with God`'s help,
and the best knowledge He has given me, in the experience of several years`' discipleship.

The great work and business of the cross of Christ, in man,
is self-denial--a word little understood, but of much depth in itself,
and of sore contradiction to the world.
The Son of God has gone before us, and,
by the bitter cup He drank and the baptism He suffered,
has left us an example that we should follow in His steps.
This made Him put that hard question to the wife of Zebedee and her two sons,
upon her soliciting that one might sit at His right and
the other at His left hand in His kingdom:
"`Are you able to drink of the cup that I shall drink,
and be baptized with the baptism I am baptized with?`"
It seems their faith was strong; they answered, "`We are able.`"
Upon which He replied, "`You shall indeed drink of My cup,
and be baptized with the baptism I am baptized with;`"^
footnote:[Matthew 20:20-23]
but their reward He left to His Father.

What was the cup He drank, and the baptism He suffered?
I answer;
they were the denial and offering up of Himself by the eternal Spirit to the will of God,
undergoing the tribulations of His life, and the agonies of His death upon the cross,
for man`'s salvation.

Now, what is _our_ cup and cross that we must drink and suffer?
They are the denying and offering up of ourselves, by the same Spirit,
to do or suffer the will of God for His service and glory.
This is the true life and obedience of the cross of Jesus--narrow still,
but previous to Christ it was an unbeaten way.
For Christ came in the greatness of His love and strength when there was none to help,
not one to open the seals, to give knowledge,
or to direct the course of poor man`'s recovery.
And though clothed with the weaknesses of a mortal man,
being inwardly fortified by the almightiness of an immortal God,
He travelled through all the straits and difficulties of humanity; and,
as the first of all others, trod the untrodden path to blessedness.

O come let us follow Him, the most unwearied,
the most victorious Captain of our salvation,
to whom all the great Alexanders and mighty Caesars cannot be compared.
For these were all great princes of their kind, and conquerors too,
but on very differing principles.
Christ made Himself of no reputation to save mankind;
but these thoroughly ruined people in order to augment their name.
They vanquished others, not themselves; but Christ conquered self,
the very power that vanquished them.
They advanced their empire by rapine and blood; but He by suffering and persuasion.
They prevailed through force, but Christ never made use of compulsion.
Misery and slavery followed all their victories,
but Christ brought freedom and felicity to those He overcame.
In all they did, they sought to please themselves; in all He did,
He aimed to please His Father, who is God of gods, King of kings, and Lord of lords.
Rightly then is He called the most excellent prince and conqueror.
And it is this most perfect pattern of self-denial we must follow,
if ever we will come to glory.

=== The Lawful Self

To do this, let us consider self-denial in its true distinction and extent.
There is a lawful and an unlawful self, and both must be denied for the sake of Him who,
in submission to the will of God, counted nothing dear that He might save us.
And though scarcely any part of the world has progressed as far as to
need a lesson in the denial of lawful self
(since every day they most greedily sacrifice to the pleasures of unlawful self),
yet I shall at least touch upon it,
as this may possibly meet with some who are so far advanced in this spiritual warfare,
as to receive benefit from it.

The lawful self, which we are to deny, is that convenience, ease,
enjoyment and plenty which, in itself,
is so far from being evil that it may be considered the
bounty and blessing of God towards us:
things such as husbands, wives, children, houses, land,
reputation, liberty, and life itself.
These are God`'s favors, which we may enjoy with lawful pleasure,
and justly improve as our honest interest.
But when God requires them, at what time soever,
or if He is pleased to try our affections by making us part with them; I say,
when they are brought in competition with Him, they must not be preferred, but denied.

Christ Himself descended from the glory of His Father,
and willingly made Himself of no reputation
among men in order that He might bring us to God.
Thinking it no robbery to be equal with God,
He humbled Himself to the poor form of a servant; yes,
to the ignominious death of the Cross,
and so delivered to us an example of pure humility,
and entire submission to the will of our heavenly Father.

This doctrine He teaches us in these words: "`He that loves father or mother,
son or daughter, more than Me, is not worthy of Me.`"
Again, "`Whosoever of you that forsakes not all that he has, cannot be My disciple.`"
He plainly told the rich young man that if he would have eternal life,
he must sell all and follow Him: a doctrine which was sad to him,
as it also is to those like him who,
notwithstanding all their high pretenses to religion,
love their possessions more than Christ.
Still, this doctrine of self-denial stands as the condition to eternal happiness:
"`He that will come after Me, let him deny himself, and take up his cross and follow Me.`"

This made those honest fishermen quit their
lawful trades and follow Him when He called them;
and caused others who waited for the consolation of Israel to offer up their estates,
reputations, liberties, and lives also,
to the displeasure and fury of their kindred and the government they lived under,
for the spiritual advantage that accrued to them
by their faithful adherence to His holy doctrine.

It is true, many sought to excuse themselves from following Him,
as is seen in the parable of the wedding feast.
Some had bought land, some had married wives,
and others had bought yokes of oxen and said they could not come.
Alas, an immoderate love of the world hindered them.
Instead of acting as their servants, these lawful enjoyments became their idols;
they worshipped them more than God, and would not renounce them to come to God.
This is recorded to their reproach,
and we may herein see the power of self upon the worldly man,
and the danger that comes to him by the abuse of lawful things.
What! Your wife dearer to you than your Savior?
Your land and oxen preferred before your soul`'s salvation?
O beware, that your comforts prove not snares first, and then curses.
To over-rate them is to provoke Him that gave them to take them away again.
Come instead to follow Him that gives eternal life to the soul.

Woe to them that have their hearts in their earthly possessions!
For when they are gone, their heaven stays here.
It is the sin of the greatest part of the world
that they adhere to their worldly treasures,
and how lamentable to behold their affections soiled and
entangled with their conveniences and accommodations in it.
The true self-denying man is a pilgrim; but the selfish man is an inhabitant of the world.
The one uses the world as men do ships,
to transport themselves or their supplies in a journey towards home;
the other looks no further (whatever he claims)
than to be settled in fulness and ease here,
and he likes it so well that, if he could, he would never exchange it.
No, he will not trouble himself to think of the other world
till he is sure he must live no longer in this.
Then alas, it will prove too late!
Not to Abraham`'s bosom, but to the rich man he must go; the story is as true as it is sad.

On the other hand,
it is not for nothing that the disciples of Jesus deny themselves; and indeed,
Christ Himself had the eternal joy in His eye.
"`For the joy that was set before Him,`" says the author to the Hebrews,
"`He endured the cross;`"^
footnote:[Hebrews 12:2]
that is, He denied Himself and bore the reproaches and death of the wicked,
despising the shame, the dishonor, and the derision of the world.
This made Him not afraid nor shrink,
and He has set down on the right hand of the throne of God.
To the encouragement and great consolation of His disciples,
when Peter asked Him what they should have who had forsaken all to follow Him;
He answered, "`Verily I say unto you, you who have followed Me in the regeneration,
when the Son of man shall sit on the throne of His glory,
you also shall sit upon twelve thrones, judging the twelve tribes of Israel,`"^
footnote:[Matthew 19:28 KJV]
who were then in apostasy from the life and power of godliness.
This was the lot of His disciples, the more immediate companions of His tribulations,
and the first messengers of His kingdom.
But that which follows is to all:
"`And everyone that has forsaken houses, or brethren,
or sisters, or father or mother, or wife, or children, or lands, for My name`'s sake,
shall receive a hundred fold, and shall inherit everlasting life.`"^
footnote:[Matthew 19:28-29]
It is this recompense of reward, this eternal crown of righteousness, which,
in every age, has raised in the souls of the just a holy neglect, yes,
a contempt of the world.

=== The Example of the Ancients

This is no new doctrine; it is as old as Abraham.
In several most remarkable instances, his life was made up of self-denial.
First, in quitting his own land,
where we may well suppose him to have been settled in the midst of plenty,
or at least sufficiency.
And why did he leave it?
Because God called him.
This should be reason enough; but such is the world`'s degeneracy that,
in reality, it is not.
Indeed, the same act, upon the same incentive in any man now, though praised in Abraham,
would be mocked and derided.
Alas, how apt are people to commend what they do not understand.
And how they admire in their ancestors the very same acts which they
despise in the faithful disciples of their own times.

But Abraham obeyed, and the consequence was that God gave him a mighty land.
This was the first reward of his obedience; the next was a son in his old age,
past the time of his wife`'s bearing children.
Yet God soon called for his darling, their only child, the joy of their age,
the son of a miracle,
and the one upon whom the fulfilling of the promise made to Abraham depended.
God called for this son,
bringing a trial which one would think might very well overturn his faith,
and shake his integrity, or at least bring about this dispute in himself:
"`This command is unreasonable and cruel; it must be the tempter`'s,
it cannot be God`'s. For, would God give me a son to make a sacrifice of him?
Should a father be the butcher of his only child?
That He should require me to offer up the son of His own promise,
by whom His covenant is to be performed, is absurd.`"
Thus might Abraham have naturally argued,
in order to withstand the voice of God and indulge his
great affections to his beloved Isaac.
But good old Abraham, who knew the voice that had promised him a son,
had not forgotten it when it called to him again.
He disputed not, though it looked strange,
and though he no doubt felt a measure of surprise and horror as a man.
He had learned to believe that God who gave him a child by a
miracle could work another to preserve or restore him.
His affections could not outbalance his duty, much less overcome his faith.

To the voice of the Almighty Abraham bowed, built an altar,
bound his only son upon it, kindled the fire,
and stretched forth his hand to take the knife; but the angel stopped the stroke.
"`Hold, Abraham, your integrity is proved.`"
And what followed?
A ram served for the sacrifice, and Isaac was his again.
This shows how little will serve where all is resigned,
and how low a sacrifice contents the Almighty where the heart is approved.
It is not the sacrifice that recommends the heart,
but the heart that gives the sacrifice acceptance.

God often touches our greatest comforts,
and calls for that which we most love and are least willing to part with.
He does not always take them utterly away, but He proves the soul`'s integrity,
cautions us from excesses,
and in order that we may remember Him
(the Author of all blessings we possess)
teaches us to live loose to the world.
I speak my experience: the way to keep our enjoyments is to resign them.
And though this be hard, it is sweet to see them returned,
as Isaac was to his father,
with more love and blessing than before.
O foolish world!
O worldly Christians!
Not only strangers, but enemies to this excellent faith!
And while you are so, you can never know the reward of it.

Job`'s self-denial was also very remarkable.
For when the messengers of his afflictions came thick
upon him with one doleful story after another,
until he was left almost as naked as when he was born,
the first thing he did was fall to the ground and worship that power, and kiss that hand,
that stripped him.
He was so far from murmuring,
he concluded his losses of estate and children with these words:
"`Naked came I out of my mother`'s womb, and naked shall I return: the Lord gave,
and the Lord has taken away, blessed be the name of the Lord.`"^
footnote:[Job 1:21]
O the deep faith, patience, and contentment of this excellent man!
One would have thought that this repeated news of ruin
had been enough to overset his confidence in God,
but it did not; his faith stayed him.
And he tells us why--"`I know (says he) that my Redeemer lives.`"^
footnote:[Job 19:25]
And it is manifest that His Redeemer indeed did live,
for He had redeemed him from the world.
His heart was not in his worldly comforts;
his hope lived above the joys of time and the troubles of mortality.
He was not tempted by the one, nor shaken by the other; but firmly fixed,
"`that after my skin has been struck off from my flesh, yet I shall see God.`"^
footnote:[Job 19:26 LitV Translation]
Thus the heart of Job was both submitted to, and comforted in, the will of God.

Moses is the next great example in the sacred story for remarkable self-denial,
before the times of Christ`'s appearance in the flesh.
He had been saved, when an infant, by an extraordinary Providence,
and it seems by what followed, for an extraordinary service.
Pharaoh`'s daughter,
whose compassion was the means of his preservation
(when the king decreed the slaughter of the Hebrew males),
took him for her son, and gave him the education of her father`'s court.
His own graceful presence and extraordinary abilities,
joined with her love to him and desire for her father to promote him,
must have rendered him, if not capable of succession to the throne,
at least of being a chief minister of affairs under that wealthy and powerful prince.
For Egypt was then what Athens and Rome were afterward,
the most famous center for learning, arts and glory.

But Moses was ordained for other work, and guided by a better star,
a higher principle.
No sooner had he come to an age of discretion,
than the impiety of Egypt and the oppressions of his brethren there,
grew a burden too heavy for him to bear.
And though so wise and good a man could not have been lacking in generous and
grateful sentiments because of the kindness of the king`'s daughter to him,
yet he had also "`seen that God who is invisible,`"^
footnote:[Hebrews 11:27]
and did not dare to live in the ease and plenty of Pharaoh`'s house
while his poor brethren were required to make brick without straw.
And so, with the fear of the Almighty taking deep hold of his heart,
he nobly refused to be called the son of Pharaoh`'s daughter,
and chose rather a life of affliction with the despised and oppressed Israelites,
and to be the companion of their temptations and jeopardies,
"`than to enjoy the pleasures of sin for a season;`"^
footnote:[Hebrews 11:25]
esteeming the reproaches of Christ
(which he suffered for making that unworldly choice)
greater riches than all the treasures of that kingdom.

Nor was he so foolish as they thought; for he had reason on his side.
It is said, "`He had an eye to the recompense of reward;`"^
footnote:[Hebrews 11:26]
so he did but refuse a lesser benefit for a greater.
In this his wisdom transcended that of the Egyptians;
for they made the present world their choice
(which is as uncertain as the weather)
and so lost that world which has no end.
Moses looked deeper, weighed the enjoyments of this life in the scales of eternity,
and found they had no weight there.
He governed himself, not by the immediate possession,
but by the nature and duration of the reward.
His faith corrected his affections,
and taught him to sacrifice the pleasures of self to the hope he had of a future,
more excellent recompense.

Isaiah was no inconsiderable instance of this same blessed self-denial; who,
from a courtier, became a prophet,
and left the worldly interests of the one for the faith, patience,
and sufferings of the other.
His choice did not only lose him the favor of men,
but their wickedness
(enraged by his integrity to God in his fervent and bold reproofs of them)
made a martyr of him in the end;
for they barbarously sawed him asunder in the reign of king Manasseh.
Thus died that excellent man, commonly called, the Evangelical Prophet.

I shall add one example more, from the fidelity of Daniel.
This was a holy and wise young man, who,
when his external advantages came into competition with his duty to Almighty God,
relinquished them all.
Instead of being solicitous how to secure himself, as one minding nothing less, he was,
to the utmost hazard of himself,
most careful how to preserve the honor of God by fidelity to His will.
And though at first it exposed him to ruin, yet,
(as a great encouragement to all who keep a clear conscience in an evil time),
his faithfulness to his Creator at last advanced him greatly in the world;
and the God of Daniel was made famous and fearful through his perseverance,
even in the eyes of heathen kings.

What shall I say of all the rest, who,
counting nothing dear that they might do the will of God,
abandoned their worldly comforts and exposed their ease and safety
(as often as the heavenly vision called them)
to the wrath and malice of degenerate princes,
and an apostate church?
More especially Jeremiah, Ezekiel and Micah, who, after they had denied themselves,
in obedience to the divine voice, sealed up their testimony with their blood.

Thus was self-denial the practice and glory of the ancients,
who were predecessors to the coming of Christ in the flesh.
And shall we hope for heaven without it now,
when our Savior himself was made the most excellent example of it?
And that, not as some would eagerly have it, namely,
"`He suffered for us, so that we need not suffer;`"
but rather, He suffered for us,
that we might deny ourselves and so be the true followers of His blessed example.

=== Leave All for Him

Whoever you are, therefore, that desire to do the will of God,
but faint because of the opposition of worldly considerations; remember I tell you,
in the name of Christ, that he who prefers father or mother, sister or brother,
wife or child, house or land, reputation, honor, office, liberty or life,
before the testimony of the light of Jesus in his own conscience,
shall be rejected of Him, in the solemn and general examination of the world,
when all shall be judged and receive according to the
deeds done (not the profession made) in this life.
It is the doctrine of Jesus that if your right hand offends you, you must cut it off;
and if your right eye offends you, you must pluck it out; that is, if the most dear,
the most useful and tender comforts you enjoy, stand in your soul`'s way,
interrupting your obedience to the voice of God and
your conformity to His holy will revealed in your soul,
you are engaged, under the penalty of damnation, to part with them.

The way of God is a way of faith,
which is as dark to natural sense as it is mortal to self.
The children of obedience, with holy Paul,
count all things dross and dung that they may win Christ,
and know and walk in this narrow way.
Speculation will not do, nor can refined notions enter it.
Only the obedient will eat the good of this land.
"`They that will to do My Father`'s will,`" says the blessed Jesus,
"`shall know of My doctrine;`"^
footnote:[John 7:17]
them He will instruct.
There is no room in the heart for instruction
where the lawful self is lord and not servant.
For self cannot receive it; and that which should receive it is oppressed by self,
with fears and doubts:
"`What will my father or mother say?
How will my husband treat me?
Or, what will the magistrates do with me?
For though I feel a most powerful persuasion,
and a clear conviction upon my soul of this or that thing,
yet considering how unpopular it is, what enemies it has,
and how strange I shall seem to some, I hope God will pity my weakness if I sink.
I am but flesh and blood; it may be that hereafter He will better enable me;
and there is time enough.`"
Thus speaks the selfish, fearful man.

Deliberating is always the worst, for the soul loses in consultation;
but the manifestation of light brings power with it.
Never does God seek to convince people; but upon their submission, He empowers them.
He requires nothing without ability to perform it; for that would be mocking,
not saving men.
It is enough for you to do what God shows to be your duty,
provided you consent to the light and Spirit by which He gives you that knowledge.
They that lack power,
are those who do not receive Christ in His convictions upon the soul,
and such will always lack it.
But such as do receive Him,
receive power also (like those of old) to become the children of God,
through the pure obedience of faith.

Therefore, let me beseech you by the love and mercy of God,
by the life and death of Christ, by the power of His Spirit and the hope of immortality,
you whose hearts are established in your temporal comforts and
are lovers of self more than of these heavenly things;
let the time past suffice for such things!
Do not think it enough to be clear of certain gross impieties which others are found in,
while your inordinate love of lawful things defiles your enjoyment of them,
and draws your heart from the fear, love, obedience,
and self-denial of a true disciple of Jesus.
Turn about then, and hearken to the still voice in your conscience;
it tells you of your sins, and of your misery in them.
It gives a living discovery of the vanity of the world,
and opens to your soul some prospect of eternity,
and the comforts of the righteous who are at rest.
If you adhere to this, it will divorce you from sin and self.
You will soon find that the power of its charms exceeds that of the wealth,
honor, and the beauty of the world, and,
will finally give you that tranquility which the
storms of time can never shipwreck or disorder.
Here all your enjoyments are blessed.
Though they be small, yet they are great because of that presence which is within them.

Even in this world the righteous have the better part,
for they use the world without rebuke, and do not abuse it.
They see and bless the hand that feeds and clothes and preserves them.
Beholding Him in all His gifts, they do not adore them, but Him.
Indeed,
the sweetness of His blessing is an advantage which such have over those who see Him not.
In their increase they are not lifted up, nor in their adversities are they cast down;
for they are moderated in the one, and comforted in the other, by His divine presence.

In short, heaven is the throne, and earth is but the footstool,
of that man who has self under foot.
Those who know this station will not easily be moved.
They learn to number their days that they may not be surprised at their dissolution.
They learn to "`redeem their time, because the days are evil;`"^
footnote:[Ephesians 5:16]
remembering that they are but stewards,
and must deliver up their accounts to an impartial Judge.
Therefore, not to self, but to Him they live, and in Him they die,
and are blessed with them that die in the Lord.
Thus I conclude my discourse of the right use of lawful self.
