== Chapter V. Denying Unlawful Self

I now come to unlawful self, which, more or less,
is the immediate concern of the greater part of mankind.
This unlawful self is twofold.
First, that which relates to religious worship: Second,
that which concerns moral and civil conduct in the world.
They are both of infinite consequence to be considered by us.
I shall be as brief as I may with ease to my
conscience and no injury to the matter at hand.

That unlawful self in religion,
which ought to be mortified by the cross of Christ,
is man`'s invention and performance of the worship to God, which is not truly so,
either in its institution or performance.
In this great error,
many of those who attribute to themselves the name of Christians take the lead,
being most exterior, pompous and superstitious in their worship.
These not only err exceedingly by a spiritual unpreparedness in the way of
their performing worship to God Almighty
(who is an eternal spirit),
but the worship itself is composed of what is utterly inconsistent with the
very form and practice of Christ`'s doctrine and the apostolic example.
The worship of the apostles was plain and spiritual;
the worship of today is gaudy and worldly.
Christ`'s worship was inward, in the soul; the world`'s worship is outward and bodily.
The true worship was suited to the nature of God, who is a spirit;
but man`'s invented worship is accommodated to the carnal part.
Instead of excluding flesh and blood,
behold there is now a worship calculated to gratify flesh,
as though the goal were not to present God with a worship pleasing to Him,
but to make one pleasing to man.

This is a worship dressed with stately buildings and imagery,
rich furniture and garments, polished voices and music, costly lamps,
wax candles and perfumes,
and all acted with the most pleasing variety to the
external senses that art can invent or cost procure.
They act as though the world were to turn Jew or Egyptian again,
or that God was an old man, and Christ a little boy,
to be treated with a kind of religious masquerade--for
so they picture Him in their temples,
and too many in their minds.
Such a carnal worship may very well suit this idea of God,
for when men can think Him such a one as themselves,
it is no wonder they address Him and entertain Him in a way
that would be most pleasing from others to themselves.

But what said the Almighty to such a sensual people of old,
upon the like occasion?
"`You thought I was such a one as yourself, but I will reprove you,
and set your sins in order before you.
Now consider this, you that forget God, lest I tear you in pieces,
and there be none to deliver.
But to him that orders his conduct aright,
I will show the salvation of God.`"^
footnote:[Ps. 50:21-23]
The worship acceptable to Him is,
"`To do justly, love mercy, and walk humbly with God.`"^
footnote:[Micah 6:8]
He that searches the heart and tries the thoughts of man,
and sets his sins in order before him, who is the God of the spirits of all flesh,
looks not to the external fabric, but the internal frame of the soul,
and the inclination of the heart.
Nor can it be soberly thought, that He who is "`clothed with divine honor and majesty,
who covers Himself with light as with a garment,
who stretches out the heavens like a curtain,
who lays the beams of His chambers in the deep, who makes the clouds His chariots,
who walks upon the wings of the wind,
who makes His angels spirits and His ministers a flaming fire,
and who laid the foundation of the earth, that it should not be moved forever,`"^
footnote:[Ps. 104:1-5]
can be adequately worshipped by those human inventions which
are the refuge of a people who have apostatized from the
primitive power and spirituality of Christian worship.

=== An Inward Temple

Christ drew off His disciples from the glory and worship of the outward temple,
and instituted a more inward and spiritual worship, in which He instructed His followers.
"`You shall neither in this mountain, nor in Jerusalem,`"
says Christ to the Samaritan woman, "`worship the Father.
God is a spirit, and they that worship Him, must worship Him in spirit and in truth.`"^
footnote:[John 4:24]
It is as if He had said, '`For the sake of the weakness of the people, God condescended,
in times past, to limit Himself to an outward time, place, temple and service,
in and by which He would be worshipped;
but this was during men`'s ignorance of His omnipresence,
when they considered not what God is, nor where He is.
I am come to reveal Him to as many as receive Me. God is a spirit,
and He will be worshipped in spirit and in truth.`'

People must be acquainted with Him as a spirit,
considering and worshiping Him as such.
It is not the bodily worship,
nor the ceremonial services in use among you now that will
serve or give acceptance with this God who is a spirit.
You must obey His Spirit that strives with you
to gather you out of the evil of the world,
so that bowing to His instructions and commands in your own souls,
you may know what it is to worship Him as a spirit.
Then you will understand, that it is not going to this mountain, nor to Jerusalem,
but doing the will of God and keeping His commandments.
Commune with your own heart and do not sin; take up your cross, meditate on His holy law,
and follow the example of Him whom the Father has sent.

Stephen, that bold and constant martyr of Jesus,
told the Jews when a prisoner at their bar, "`Solomon built God a house,
however the Most High dwells not in temples made with hands; as says the prophet,
heaven is My throne and the earth is My footstool, where is the house you will build Me,
says the Lord, or what is the place of My rest?
Has not My hand made all these things?`"^
footnote:[Acts 7:47-50]
Behold,
here is a total overthrow to all worldly temples and their ceremonious accessories!
The martyr follows up his blow upon those apostate Jews, who were the pompous,
ceremonious, worldly worshippers of that time:
"`You stiff-necked and uncircumcised in heart and ears,
you always resist the Holy Spirit; as your fathers did, so do you.`"^
footnote:[Acts 7:51]
It is as if He had told them, '`Neither your outward temple, rites and shadowy services,
nor your pretensions to succession in nature from Abraham, and, by religion,
from Moses are of any import;
for you are resistors of the Spirit and opposers of His instructions.
You will not bow to His counsel, nor are your hearts right towards God.
You are the successors of your fathers`' iniquity!
And, though you are verbal admirers of the prophets,
you are not the successors of their faith and life.`'

The prophet Isaiah carries it a little farther than what is cited by Stephen.
For, after having declared what is not God`'s house (the place where His glory dwells),
these words immediately follow: "`But to this man will I look, even to him that is poor,
and of a contrite spirit, and trembles at My word.`"^
footnote:[Isaiah 66:2]
Behold, O carnal and superstitious man, the true worshipper, and the place of God`'s rest!
This is the house and temple of Him whom the heaven of
heavens cannot contain--a house which self cannot build,
nor the art or power of man prepare or consecrate.

Paul, that great apostle of the Gentiles,
twice expressly uses the word temple to refer to man,
and not to a building of man`'s hand and art.
In his first epistle to the church at Corinth he writes,
"`Know you not that you are the temples of the Holy Spirit, which is in you,
which you have from God?`"^
footnote:[1 Corinthians 6:19]
And again, he tells the same people, in his second epistle,
"`For you are the temple of the living God, as God has said;`"
and then cites God`'s words by the prophet,
"`I will dwell in them, and walk in them;
and I will be their God, and they shall be My people.`"^
footnote:[2 Corinthians 6:16]
This is the evangelical temple, the Christian church,
whose ornaments are not the embroideries and furnitures of worldly art and wealth,
but the graces of the Spirit--meekness, love, faith, patience, self-denial, and charity.
Here it is that the eternal Wisdom--"`who was with God from everlasting,
before the hills were brought forth, or the mountains laid`"--chooses to dwell,
"`rejoicing (He says) in the habitable part of His earth,
and My delight is with the sons of men;`"^
footnote:[Proverbs 8:31]
not in houses built of wood and stone.
This living house is more glorious than Solomon`'s dead house, which was but a figure;
even as Solomon was a figure of Christ, who builds us up as a holy temple to God.
It was promised of old,
that "`the glory of the latter house should transcend the glory of the former;`"^
footnote:[Haggai 2:9]
which indeed may be applied to this.
For the prophet spoke not of one outward temple
or house excelling another in outward luster;
for where is the benefit of that?
But the promise was that the divine glory,
the beauty of holiness in the Gospel-house or church, made up of renewed believers,
should exceed the outward glory of Solomon`'s temple, which,
in comparison of the latter days, was but as flesh to spirit,
fading resemblances compared to the eternal substance.

Christians do indeed have meeting places, yet not in the Jewish or heathen way,
but rather plain, void of pomp and ceremony,
suiting the simplicity of their blessed Lord`'s life and doctrine.
For God`'s presence is not with the house, but with them that are in it,
who _are_ the Gospel-church, and not the house.
O that such as call themselves Christians knew a real sanctity
in themselves by the washing of God`'s regenerating grace,
instead of that imaginary sanctity ascribed to places!
Then they would know what the church is,
and where it is that God appears in this gospel day.
Yes, this made the prophet David say,
"`The King`'s daughter is all glorious within; her clothing is of wrought gold.`"^
footnote:[Ps. 45:13]
What is the glory that is within the true church,
and that gold which makes up her inward glory?
Tell me, O superstitious man!
Is it your stately temples, altars, carpets, tables, tapestries, vestments, organs,
voices, candles, lamps, censers, plates and jewels,
with the same furniture found in your worldly temples?
No such thing!
These are nothing in comparison with the divine
adornment of the King of heaven`'s daughter,
the blessed and redeemed church of Christ.
O miserable apostasy!
O wretched substitute for the loss of the apostolic life,
the spiritual glory of the primitive church.

=== The False Crosses of Men

Yet some of these admirers of external pomp and
glory want to be thought lovers of the cross,
and so have made themselves many.
But alas! what hope is there of reconciling this to Christianity?
For while these pretend to worship God with their outward crosses,
they most dangerously err from the true cross of Christ and that holy
abnegation of self which was of His blessed appointment.
Indeed such crosses seem to stand in the way of the true one,
for instead of mortifying their wills by it,
they have both made it and do use it according to their wills;
so that these decorative crosses have become an emblem
of those who do nothing but what they wish.
Yet by this they desire to be thought the disciples of Him who never did His own will,
but only the will of His heavenly Father.

These outward crosses are such as flesh and blood can easily carry,
for flesh and blood invented them.
They are therefore not the cross of Christ,
which is the power of God to crucify flesh and blood.
Thousands of them have no more virtue than a crumb.
They are poor, empty shadows, carried about as charms,
though they cannot repel a single evil.
Indeed, men sin with them upon their backs;
and though they display them over their heart, alas,
their beloved lusts lie there too without the least disquiet.
They are as silent as the mock-gods of Baal, having no life or power in them.
And how could they?
For their substance is earthly,
and their image and workmanship are but the inventions and labors of worldly artists.
They are yokes without restraint, and crosses that never crucify.
A whole cartload of them would leave a man as unmortified as it found him.
Men may sooner knock their brains out with them than their sins; and this, I fear,
is already known in the very conscience of those who use them and adore them.

Nor is a reclusive life (the boasted righteousness of some who lock
themselves up in monasteries and convents) much more commendable,
or one bit nearer to the nature of the true cross; for though this is not unlawful,
it is unnatural, and true religion does not teach it.
The true Christian convent and monastery are within,
where the soul is en-cloistered from sin.
And this religious house the true followers of Christ carry about with them,
not exempting themselves from interactions with the world,
though they keep themselves from its evils.

But the monastic life is an idle and unprofitable kind of self-denial,
which is burdensome to others.
Men and women are locked up within lest they do mischief without,
learning a kind of patience by force, a self-denial against their own will,
avoiding temptation rather than learning to be faithful and constant in it.
It is no great feat if they do not commit the sins they are not tempted to commit;
for where the eye does not view, there the heart does not crave.

The cross of Christ is of another nature.
It truly overcomes the world, and leads to a life of purity in the face of allurements.
Those who bear it are not thus chained up for fear they should bite; nor locked up,
lest their faith be stolen away.
They receive power from Christ their captain to resist
evil and do that which is good in the sight of God.
Indeed, they despise the world, and love its reproach above its praise.
They do not offend others, but love those who offend them.
What a world should we have if everybody, for fear of transgressing,
should cage themselves up behind four walls?
No, the perfection of the Christian life extends into every
honest labor and commerce used among men.
Such severity is not the effect of Christ`'s free spirit,
but a voluntary and fleshly humility--shackles of man`'s own making and putting on,
without prescription or reason.

Monasteries and convents are their own law-givers, and set their own rules,
punishments and penance,
a constrained harshness that is out of joint with the rest of the creation.
For society is one of the great ends of creation,
and not to be destroyed for fear of evil.
It is the sin that spoils it which must be banished,
by steady reproof and a conspicuous example of tried virtue.
True godliness does not turn men out of society, but enables them to live better in it,
and excites their endeavors to mend it--"`not hiding their candle under a bushel,
but setting it upon a table, in a lampstand.`"

Besides, such things are selfish inventions,
for by them men run away by themselves and leave the world behind to be lost.
Christians should rather keep the helm, and guide the vessel to its proper port;
not quietly flee the ship from the back, leaving those that remain without a pilot,
to be driven by the fury of evil times upon the rocks or sands of ruin.

Taking up the cross of Jesus is a much more interior exercise.
It is the circumspection and discipline of the soul,
in conformity to the divine mind revealed therein.
Does not the body follow the soul, and not the soul the body?
Consider then, that no outward cell can shut up the soul from lust,
or the mind from its infinite unrighteous imaginations.
"`The thoughts of man`'s heart are only evil, and that continually.`"^
footnote:[Genesis 6:5]
Evil comes from within, and not from without.
How then can an external application remove an internal cause?
Or how can a restraint upon the body work a confinement of the mind?

Examine, O man, your foundation, what it is, and who placed you there;
lest in the end it should appear that you have put an eternal cheat upon your own soul.
I must confess I am jealous of the salvation of my own kind.
Having found mercy with my heavenly Father,
I would have none deceive themselves to perdition, especially about religion,
where people are most apt to take all for granted and
lose infinitely by their own flatteries and neglect.

The inward,
steady righteousness of Jesus is something far different than
all the contrived devotions of poor superstitious man;
and to stand approved in the sight of God excels all bodily
exercises in religion which result from the invention of men.
The soul that is awakened and preserved by His holy power and
Spirit lives unto Him in the way of His own institution,
and worships Him in His own Spirit--that is, in the holy sense, life,
and leadings of it--which indeed is the true gospel worship.

I mean no disregard for true Christian retirement; for I do not only acknowledge,
but I admire solitude.
Christ himself was an example of it.
He loved and chose to frequent many mountains, gardens, seasides alone.
Indeed, it is requisite to the growth of piety,
and I reverence the virtue that seeks and uses it,
wishing there were more of it in the world.
But this should be free, and not constrained.
