[quote.epigraph, , Luke 9:23]
____
And Jesus said unto them all; If any man will come after me,
let him deny himself, and take up his cross daily, and follow me.
____

[quote.epigraph, , 2 Tim. 4:7-8]
____
I have fought a good fight, I have finished my course, I have kept the faith;
henceforth there is laid up for me a crown of righteousness, etc.
____

== Preface.

[.salutation]
Reader,

The great business of man`'s life, is to answer the end for which he lives;
and that is to glorify God and save his own soul: this is the decree of Heaven,
as old as the world.
But so it is, that man mindeth nothing less than what he should most mind;
and despiseth to inquire into his own being, its original duty and end;
choosing rather to dedicate his days (the steps he
should make to blessedness) to gratify the pride,
avarice, and luxury of his heart: as if he had been born for himself,
or rather given himself being,
and so not subject to the reckoning and judgment of a superior power.
To this wild and lamentable pass hath poor man brought himself
by his disobedience to the law of God in his heart,
by doing that which he knows he should not do,
and leaving undone what he knows he should do.
And as long as this disease continueth upon man he will make his God his enemy,
and himself incapable of the love and salvation that He hath manifested,
by his Son Jesus Christ, to the world.

If, Reader, thou art such an one, my counsel to thee is, to retire into thyself,
and take a view of the condition of thy soul;
for Christ hath given thee light with which to do it; search carefully and thoroughly;
thy life is in it; thy soul is at stake.
It is but once to be done; if thou abuse thyself in it, the loss is irreparable;
the world is not price enough to ransom thee: wilt thou then, for such a world,
belate thyself, overstay the time of thy salvation, and lose thy soul?
Thou hast to do, I grant thee, with great patience; but that also must have an end:
therefore provoke not that God that made thee, to reject thee.
Dost thou know what it is?
It is Tophet; it is hell, the eternal anguish of the damned.
Oh!
Reader, as one knowing the terrors of the Lord, I persuade thee to be serious, diligent,
and fervent about thy own salvation.
Aye, and as one knowing the comfort, peace, joy,
and pleasure of the ways of righteousness too,
I exhort and invite thee to embrace the reproofs and convictions
of Christ`'s light and spirit in thine own conscience,
and bear the judgment, who hast wrought the sin.
The fire burns but the stubble: the wind blows but the chaff: yield up the body, soul,
and spirit to Him that maketh all things new: new heavens, and new earth, new love,
new joy, new peace, new works, a new life and conversation.
Men are grown corrupt and drossy by sin, and they must be saved through fire,
which purgeth it away: therefore the word of God is compared to a fire,
and the day of salvation to an oven;
and Christ himself to a refiner and purifier of silver.

Come, Reader, hearken to me awhile; I seek thy salvation; that is my plot;
thou wilt forgive me.
A refiner is come near thee, his grace hath appeared unto thee:
it shows thee the world`'s lusts, and teaches thee to deny them.
Receive his leaven, and it will change thee: his medicine, and it will cure thee:
he is as infallible as free; without money, and with certainty.
A touch of his garment did it of old: it will do it still: his virtue is the same,
it cannot be exhausted: for in him the fulness dwells;
blessed be God for his sufficiency.
He laid help upon him, that he might be mighty to save all that come to God through him:
do thou so, and he will change thee: aye, thy vile body like unto his glorious body.
He is the great philosopher indeed; the wisdom of God, that turns lead into gold,
vile things into things precious: for he maketh saints out of sinners,
and almost gods of men.
What rests to us, then, that we must do, to be thus witnesses of his power and love?
This is the Crown: but where is the Cross?
Where is the bitter cup and bloody baptism?
Come, Reader, be like him; for this transcendant joy lift up thy head above the world;
then thy salvation will draw nigh indeed.

Christ`'s Cross is Christ`'s way to Christ`'s Crown.
This is the subject of the following Discourse;
first written during my confinement in the Tower of London, in the year 1668,
now reprinted with great enlargements of matter and testimonies, that thou, Reader,
mayest be won to Christ; and if won already, brought nearer to Him.
It is a path, God, in his everlasting kindness, guided my feet into,
in the flower of my youth, when about twenty-two years of age:
then He took me by the hand, and led me out of the pleasures, vanities,
and hopes of the world.
I have tasted of Christ`'s judgments and mercies,
and of the world`'s frowns and reproaches: I rejoice in my experience,
and dedicate it to thy service in Christ.
It is a debt I have long owed, and has been long expected: I have now paid it,
and delivered my soul.
To my country, and to the world of Christians, I leave it: my God, if He please,
make it effectual to them all, and turn their hearts from that envy, hatred,
and bitterness, they have one against another, about worldly things;
sacrificing humanity and charity to ambition and covetousness,
for which they fill the earth with trouble and oppression;
that receiving the Spirit of Christ into their hearts, the fruits of which are love,
peace, joy, temperance, and patience, brotherly kindness and charity, they may in body,
soul, and spirit, make a triple league against the world, the flesh, and the devil,
the common enemies of mankind; and having conquered them through a life of self-denial,
by the power of the Cross of Jesus,
they may at last attain to the eternal rest and kingdom of God.

[.signed-section-closing]
So desireth, so prayeth,

[.signed-section-closing]
Friendly Reader,

[.signed-section-closing]
Thy fervent Christian Friend,

[.signed-section-signature]
William Penn.
