== Chapter I.

1+++.+++ Of the necessity of the Cross of Christ in general;
yet the little regard Christians have to it.--2.
The degeneracy of Christendom from purity to lust,
and moderation to excess.--3. That worldly lusts
and pleasures are become the care and study of Christians,
so that they have advanced upon the impiety of infidels.--4.
This defection a second part to the Jewish tragedy,
and worse than the first:
the scorn Christians have cast on their Saviour.--5.
Sin is of one nature all the world over;
sinners are of the same church, the devil`'s children:
profession of religion in wicked men makes them but the worse.--6. A wolf is not a lamb;
a sinner cannot be, whilst such, a saint.--7. The wicked will persecute the good; this,
false Christians have done to the true, for non-compliance with their superstitions;
the strange carnal measures false Christians have taken of Christianity;
the danger of that self-seduction.--8. The sense of that has obliged me
to make this discourse for a dissuasive against the world`'s lusts,
and an invitation to take up the daily cross of Christ as the way left
us by him to blessedness.--9. Of the self-condemnation of the wicked;
that religion and worship are comprised in doing the will of God.
The advantage good men have over bad men in the last
judgment.--10. A supplication for Christendom,
that she may not be rejected in that great assize of the world.
She is exhorted to consider what relation she bears to Christ; if her Saviour, how saved,
and from what: what her experience is of that great work.
That Christ came to save from sin and wrath by consequence; not to save men in sin,
but from it, and so from the wages of it.

I+++.+++ Though the knowledge and obedience of the doctrine of the cross
of Christ be of infinite moment to the souls of men,
for that is the only door to true Christianity,
and that path the ancients ever trod to blessedness; yet,
with extreme affliction let me say, it is so little understood, so much neglected,
and what is worse, so bitterly contradicted by the vanity, superstition,
and intemperance of professed Christians,
that we must either renounce to believe what the Lord Jesus hath told us,
that whosoever doth not bear his cross, and come after him, cannot be his disciple;^
footnote:[Luke 14:27.]
or, admitting that for truth, conclude,
that the generality of Christendom do miserably deceive
and disappoint themselves in the great business of Christianity,
and their own salvation.

II. For,
let us be never so tender and charitable in the survey of those nations
that entitle themselves to any interest in the holy name of Christ,
if we will but be just too, we must needs acknowledge,
that after all the gracious advantages of light, and obligations to fidelity,
which these latter ages of the world have received by the coming, life, doctrine,
miracles, death, resurrection, and ascension of Christ,
with the gifts of his Holy Spirit; to which add the writings, labours,
and martyrdom of his dear followers in all times,
there seems very little left of Christianity but the name;
which being now usurped by the old heathen nature and life,
makes the professors of it but true heathens in disguise.
For though they worship not the same idols, they worship Christ with the same heart:
and they can never do otherwise, whilst they live in the same lusts.
So that the unmortified Christian and the heathen are of the same religion.
For though they have different objects to which they do direct their prayers,
that adoration in both is but forced and ceremonious,
and the deity they truly worship is the god of the world, the great lord of lusts:
to him they bow with the whole powers of soul and sense.
What shall we eat?
What shall we drink?
What shall we wear?
And how shall we pass away our time?
Which way may we gather wealth, increase our power, enlarge our territories,
and dignify and perpetuate our names and families in the earth?
Which base sensuality is most pathetically expressed
and comprised by the beloved Apostle John,
in these words: "`The lust of the flesh, the lust of the eyes,
and the pride of life,`" which, says he, "`are not of the Father, but of the world,
that lieth in wickedness.`"^
footnote:[1 John 2:16.]

III.
It is a mournful reflection, but a truth no confidence can be great enough to deny,
that these worldly lusts fill up the study, care,
and conversation of wretched Christendom! and, which aggravates the misery,
they have grown with time.
For as the world is older, it is worse; and the examples of former lewd ages,
and their miserable conclusions, have not deterred, but excited ours;
so that the people of this seem improvers of the old stock of impiety,
and have carried it so much further than example,
that instead of advancing in virtue upon better times,
they are scandalously fallen below the life of heathens.
Their high-mindedness, lasciviousness, uncleanness, drunkenness, swearing, lying, envy,
backbiting, cruelty, treachery, covetousness, injustice, and oppression, are so common,
and committed with such invention and excess,
that they have stumbled and embittered infidels to a degree of scorning that holy religion,
to which their good example should have won their affections.

IV. This miserable defection from primitive times,
when the glory of Christianity was the purity of its professors,
I cannot but call the second and worst part of the
Jewish tragedy upon the blessed Saviour of mankind.
For the Jews, from the power of ignorance,
and the extreme prejudice they were under to the unworldly way of his appearance,
would not acknowledge him when he came, but for two or three years persecuted,
and finally crucified him in one day.
But the false Christians`' cruelty lasts longer: they have first, with Judas,
professed him, and then, for these many ages, most basely betrayed, persecuted,
and crucified him, by a perpetual apostasy in manners,
from the self-denial and holiness of his doctrine;
their lives giving the lie to their faith.
These are they that the author of the epistle to the Hebrews tells us,
"`Crucify to themselves the Son of God afresh, and put him to open shame:`"^
footnote:[Heb. 6:6., Rev. 11:8.]
whose defiled hearts John in his Revelation styles, "`The streets of Sodom and Egypt,
spiritually so called, where also our Lord was crucified.`"^
footnote:[Rev. 11:8.]
And as Christ said of old, a man`'s enemies are those of his own house,
so Christ`'s enemies now are chiefly those of his own profession; they spit upon him,
they nail and pierce him, they crown him with thorns,
and give him gall and vinegar to drink.^
footnote:[Matt. 27:34.]
Nor is it hard to apprehend;
for they that live in the same evil nature and principle the Jews did,
that crucified him outwardly, must needs crucify him inwardly;
since they that reject the grace now in their own hearts,
are one in stock and generation with the hard-hearted Jews,
that resisted the grace that then appeared in and by Christ.

V+++.+++ Sin is of one nature all the world over; for though a liar is not a drunkard,
nor a swearer a whoremonger, nor either properly a murderer,
yet they are all of a church; all branches of the one wicked root; all of kin.
They have but one father, the devil, as Christ said to the professing Jews,
the visible church of that age: he slighted their claims to Abraham and Moses,
and plainly told them "`That he that committed sin, was the servant of sin.`"^
footnote:[John 8:34 to 45.]
They did the devil`'s works, and therefore were the devil`'s children.
The argument will always hold upon the same reasons, and therefore good still:
"`His servants ye are,`" saith Paul, "`whom ye obey:`"^
footnote:[Rom. 6:16.]
and saith John to the church of old, "`Let no man deceive you;
he that committeth sin is of the devil.`"^
footnote:[1 John 3:7-8.]
Was Judas ever the better Christian for crying, Hail, Master, and kissing Christ?^
footnote:[Matt. 26:49.]
By no means; they were the signal of his treachery;
the tokens given by which the bloody Jews should know and take him.
He called him Master, but betrayed him; he kissed, but sold him to be killed;
this is the upshot of the false Christians`' religion.
If a man ask them, Is Christ your Lord?
they will cry, God forbid else: yes, he is our Lord.
Very well; but do you keep his commandments?
No, how should we?
How then are you his disciples?
It is impossible, say they.
What! would you have us keep his commandments?
No man can.
What! impossible to do that without which Christ hath made it impossible to be a Christian?
Is Christ unreasonable?
Does he reap where he has not sown?^
footnote:[Matt. 25:24.]
Require where he has not enabled?
Thus it is, that with Judas they call him Master,
but take part with the evil of the world to betray him;
and kiss and embrace him as far as a specious profession goes; and then sell him,
to gratify the passion that they most indulge.
Thus as God said of old, they make him serve with their sins and for their sins too.^
footnote:[Isa. 43:24.]

VI. Let no man deceive his own soul; "`grapes are not gathered of thorns,
nor figs of thistles:`"^
footnote:[Matt. 7:16]
a wolf is not a sheep, nor is a vulture a dove.
What form, people, or church soever thou art of, it is the truth of God to mankind,
that they which have even the form of godliness, but by their unmortified lives,
deny the power thereof, make not the true, but false church: which,
though she entitle herself the Lamb`'s bride, or church of Christ,^
footnote:[Rev. 17:5.]
she is that mystery, or mysterious Babylon, fitly called by the Holy Ghost,
the mother of harlots and all abominations:^
footnote:[Rev. 17:5.]
because degenerated from Christian chastity and purity,
into all the enormities of heathen Babylon; a sumptuous city of old time,
much noted for the seat of the kings of Babylon,
and at that time the place in the world of the greatest pride and luxury.
As she was then, so mystical Babylon is now the great enemy of God`'s people.

VII.
True it is, "`they that are born of the flesh,
hate and persecute them that are born of the spirit,`"^
footnote:[Gal. 4:29.]
who are the circumcision in heart.
It seems they cannot own nor worship God after her inventions, methods,
and prescriptions, nor receive for doctrine her vain traditions,
any more than they can comply with her corrupt fashions and customs in their conversation.
The case being thus, from an apostate she becomes a persecutor.
It is not enough that she herself declines from ancient purity, others must do so too.
She will give them no rest that will not partake with her in that degeneracy,
or receive her mark.
Are any wiser than she, than mother church?
No, no: nor can any make war with the beast she rides upon,
those worldly powers that protect her,
and vow their maintenance against the cries of her dissenters.
Apostasy and superstition are ever proud and impatient of dissent:
all must conform or perish.
Therefore the slain witnesses, and blood of the souls under the altar,^
footnote:[Rev. 6:9.]
are found within the walls of this mystical Babylon, this great city of false Christians,
and are charged upon her, by the Holy Ghost in the Revelation.
Nor is it strange that she should slay the servants who first crucified the Lord:
but strange and barbarous too, that she should kill her husband and murder her Saviour;
titles she seems so fond of, and that have been so profitable to her;
and that she would recommend herself by, though without all justice.
But her children are reduced so entirely under the dominion of darkness,
by means of their continued disobedience to the manifestation
of the divine light in their souls,
that they forget what man once was, or they should now be;
and know not true and pure Christianity when they meet it;
yet pride themselves upon professing it.
Their measures are so carnal and false about salvation, they call good evil,
and evil good; they make a devil a Christian, and a saint a devil.
So that though the unrighteous latitude of their lives be matter of lamentation,
as to themselves it is of destruction; yet that common apprehension,
that they may be children of God,
while in a state of disobedience to his holy commandments; and disciples of Jesus,
though they revolt from his cross, and members of his true church,
which is without spot or wrinkle,
notwithstanding their lives are full of spots and wrinkles; is,
of all other deceptions upon themselves, the most pernicious to their eternal condition.
For they are at peace in sin, and under a security in their transgression.
Their vain hope silences their convictions,
and overlays all tender motions to repentance;
so that their mistake about their duty to God is
as mischievous as their rebellion against him.

Thus they walk on precipices, and flatter themselves, till the grave swallows them up,
and the judgments of the great God break their lethargy,
and undeceive their poor wretched souls with the anguish of the wicked,
as the reward of their work.

VIII.
This has been, is, and will be the doom of all worldly Christians: an end so dreadful,
that if there were nothing of duty to God, or obligation to men, being a man,
and one acquainted with the terrors of the Lord in the way and work of my own salvation,
compassion alone were sufficient to excite me to this dissuasive
against the world`'s superstitions and lusts,
and to invite the professors of Christianity to the
knowledge and obedience of the daily cross of Christ,
as the alone way, left by him, and appointed us to blessedness;
that they who now do but usurp the name may have the thing;
and by the power of the cross, to which they are now dead,
instead of being dead to the world by it,
may be made partakers of the resurrection that is in Christ Jesus, unto newness of life.
For they that are truly in Christ, that is, redeemed by, and interested in him,
are new creatures.^
footnote:[Gal. 6:15.]
They have received a new will; such as does the will of God, not their own.
They pray in truth, and do not mock God, when they say,
Thy will be done on earth as it is in heaven.
They have new affections; such as are set on things above,^
footnote:[Col. 3:1-3.]
and make Christ their eternal treasure.
New faith;^
footnote:[1 John 4-5.]
such as overcomes the snares and temptations of the world`'s spirit in themselves,
or as it appears through others: and lastly, new works;
not of a superstitious contrivance, or of human invention,
but the pure fruits of the Spirit of Christ working in them, as love, joy, peace,
meekness, long-suffering, temperance, brotherly-kindness, faith, patience, gentleness,
and goodness, against which there is no law;^
footnote:[Gal. 5:22-23]
and they that have not the Spirit of Christ, and walk not in it,
the apostle Paul has told us, are none of his;^
footnote:[Rom. 8:9.]
but the wrath of God, and condemnation of the law, will lie upon them.
For if there is no condemnation to them that are in Christ; who walk not after the flesh,
but after the Spirit, which is Paul`'s doctrine;
they that walk not according to that Holy Spirit, by his doctrine, are not in Christ:
that is, have no interest in him, nor just claim to salvation by him:
and consequently there is condemnation to such.

IX. And the truth is, the religion of the wicked is a lie: "`there is no peace,
saith the prophet, to the wicked.`"^
footnote:[Isa. 48:22.]
Indeed there can be none; they are reproved in their own consciences,
and condemned in their own hearts, in all their disobedience.
Go where they will, rebukes go with them, and oftentimes terrors too:
for it is an offended God that pricks them, and who, by his light,
sets their sins in order before them.
Sometimes they strive to appease him by their corporeal framed devotion and worship,
but in vain; for true worshipping of God is doing his will, which they transgress.
The rest is a false compliment, like him that said he would go, and did not.^
footnote:[Matt. 21:30.]
Sometimes they fly to sports and company, to drown the reprover`'s voice,
and blunt his arrows, to chase away troubled thoughts,
and secure themselves out of the reach of the disquieter of their pleasures;
but the Almighty, first or last, is sure to overtake them.
There is no flying his final justice, for those that reject the terms of his mercy.
Impenitent rebels to his law may then call to the mountains,
and run to the caves of the earth for protection, but in vain.
His all-searching eye will penetrate their thickest coverings,
and strike up a light in that obscurity, which shall terrify their guilty souls;
and which they shall never be able to extinguish.
Indeed, their accuser is with them, they can no more be rid of him than of themselves;
he is in the midst of them, and will stick close to them.
That spirit which bears witness with the spirits
of the just will bear witness against theirs.
Nay, their own hearts will abundantly come in against them; and,
"`if our hearts condemn us,`" saith the apostle John, "`God is greater,
and knows all things;`"^
footnote:[1 John 3:20.]
that is, there is no escaping the judgments of God, whose power is infinite,
if a man is not able to escape the condemnation of himself.
It is at that day proud and luxurious Christians
shall learn that God is no respecter of persons;
that all sects and names shall be swallowed up in these two kinds, sheep and goats,
just and unjust: and the very righteous must have a trial for it;
which made that holy man cry out, "`If the righteous scarcely be saved,
where shall the ungodly and the sinner appear?`"^
footnote:[1 Pet. 4:18.]
If their thoughts, words, and works must stand the test,
and come under scrutiny before the impartial Judge of heaven and earth,
how then should the ungodly be exempted?
No; we are told by him that cannot lie, many shall then even cry, Lord,
Lord! set forth their profession, and recount the works that they have done in his name,
to make him propitious, and yet be rejected with this direful sentence, "`Depart from me,
ye workers of iniquity; I know you not.`"^
footnote:[Matt. 7:23.]
As if he had said, Get you gone, you evil doers; though you have professed me,
I will not know you; your vain and evil lives have made you unfit for my holy kingdom:
get you hence, and go to the gods whom you have served;
your beloved lusts which you have worshipped,
and the evil world that you have so much coveted and adored: let them save you now,
if they can, from the wrath to come upon you,
which is the wages of the deeds you have done.
Here is the end of their work that build upon the sand;
the breath of the Judge will blow it down, and woful will the fall thereof be.
Oh, it is now that the righteous have the better of the wicked! which made an apostate cry,
in old time, "`Let me die the death of the righteous,
and let my last end be like unto his.`"^
footnote:[Num. 23:10.]
For the sentence is changed, and the Judge smiles;
he casts the eye of love upon his own sheep, and invites them with "`Come,
ye blessed of my Father,`"^
footnote:[Matt. 25:34.]
that through patient continuance in well-doing have long waited for immortality;
you have been the true companions of my tribulation and cross, and,
with unwearied faithfulness, in obedience to my holy will, valiantly endured to the end,
looking to me, the Author of your precious faith,
for the recompense of reward that I have promised to them that love me, and faint not: O,
enter ye into the joy of your Lord,
and inherit the kingdom prepared for you from the foundation of the world.

X+++.+++ O Christendom! my soul most fervently prays,
that after all thy lofty profession of Christ, and his meek and holy religion,
thy unsuitable and un-Christ-like life may not cast
thee at that great assize of the world,
and lose thee so great salvation at last.
Hear me once, I beseech thee: can Christ be thy Lord, and thou not obey him?
or, canst thou be his servant, and never serve him?
"`Be not deceived, such as thou sowest shalt thou reap.`"^
footnote:[Gal. 6:7.]
He is none of thy Saviour whilst thou rejectest his grace in thy heart,
by which he should save thee.
Come, what has he saved thee from?
Has he saved thee from thy sinful lusts, thy worldly affections, and vain conversations?
If not, then he is none of thy Saviour.
For, though he be offered a Saviour to all,
yet he is actually a Saviour to those only that are saved by him;
and none are saved by him that live in those evils by which they are lost from God,
and which he came to save them from.

It is sin that Christ is come to save man from, and death and wrath, as the wages of it;
but those that are not saved, that is delivered, by the power of Christ in their souls,
from the power that sin has had over them, can never be saved from the death and wrath,
that are the assured wages of the sin they live in.

So that look how far people obtain victory over those
evil dispositions and fleshly lusts,
they have been addicted to, so far they are truly saved,
and are witnesses of the redemption that comes by Jesus Christ.
His name shows his work: "`And thou shalt call his name JESUS,
for he shall save his people from their sin.`"^
footnote:[Matt. 1:21.]
"`Behold,`" said John, of Christ,
"`the Lamb of God that takes away the sins of the world.`"^
footnote:[John 1:29.]
That is, behold him whom God hath given to enlighten people,
and for salvation to as many as receive him, and his light and grace in their hearts,
and take up their daily cross and follow him;
such as rather deny themselves the pleasure of fulfilling their
lusts than sin against the knowledge he has given them of his will,
or do that they know they ought not to do.
