== Chapter II.

[.chapter-synopsis]
* 1+++.+++ By this Christendom may see her lapse, how foul it is, and next, the worse for her pretence to Christianity.
* 2+++.+++ But there is mercy with God upon repentance, and propitiation in the blood of Jesus.
* 3+++.+++ He is the light of the world that reproves the darkness, that is, the evil of the world; and he is to be known within.
* 4+++.+++ Christendom, like the inn of old, is full of other guests: she is advised to believe in, receive, and apply to Christ.
* 5+++.+++ Of the nature of true faith; it brings power to overcome every appearance of evil: this leads to consider the Cross of Christ, which has been so much wanted.
* 6+++.+++ The apostolic ministry, and end of it; its blessed effect; the character of apostolic times.
* 7+++.+++ The glory of the cross, and its triumph over the heathen world. A measure to Christendom, what she is not, and should be.
* 8+++.+++ Her declension, and cause of it.
* 9+++.+++ The miserable effects that followed.
* 10+++.+++ From the consideration of the cause the cure may be more easily known, viz., Not faithfully taking up the daily cross; then, faithfully taking it daily up must be the remedy.

[.numbered-group]
====

[.numbered]
I+++.+++ By all which has been said, O Christendom! and by that better help,
if thou wouldst use it, the lamp the Lord has lighted in thee, not utterly extinct,
it may evidently appear, first, how great and full thy backsliding has been, who,
from the temple of the Lord, art become a cage of unclean birds;
and of a house of prayer, a den of thieves, a synagogue of Satan,
and the receptacle of every defiled spirit.
Next, that under all this manifest defection,
thou hast nevertheless valued thy corrupt self upon thy profession of Christianity,
and fearfully deluded thyself with the hopes of salvation.
The first makes thy disease dangerous, but the last almost incurable.

[.numbered]
II. Yet, because there is mercy with God that he may be feared,
and that he takes no delight in the eternal death of poor sinners, no,
though backsliders themselves,^
footnote:[Ezek. 18:20,23-24.]
but is willing all should come to the knowledge and obedience of the Truth, and be saved,
he hath set forth his Son a propitiation,
and given him as a Saviour to take away the sins of the whole world,
that those that believe and follow him may feel the
righteousness of God in the remission of their sins,
and blotting out their transgressions forever.^
footnote:[Matt. 1:21; Luke 1:77; Rom. 3:25; Heb. 9:24-28; 1 John 2:1-2.]
Now, behold the remedy! an infallible cure, one of God`'s appointing; a precious elixir,
indeed, that never fails; and that universal medicine which no malady could ever escape.

[.numbered]
III.
But thou wilt say, What is Christ?
and where is he to be found?
and how received and applied, in order to this mighty cure?
I tell thee then, first,
he is the great spiritual light of the world that
enlightens every one that comes into the world;
by which he manifests to them their deeds of darkness and wickedness,
and reproves them for committing them.
Secondly, he is not far away from thee,^
footnote:[Acts 17:27.]
as the apostle Paul said of God to the Athenians.
"`Behold,`" says Christ himself, "`I stand at the door and knock;
if any man hear my voice, and open the door, I will come in to him, and sup with him,
and he with me.`"^
footnote:[Rev. 3:20.]
What door can this be but that of the heart of man?

[.numbered]
IV. Thou, like the inn of old, hast been full of guests;
thy affections have entertained other lovers;
there has been no room for thy Saviour in thy soul.
Wherefore salvation is not yet come into thy house, though it is come to thy door,
and thou hast been often proffered it, and hast professed it long.
But if he calls, if he knocks still, that is, if his light yet shines,
if it reproves thee still, there is hope thy day is not over,
and that repentance is not yet hid from thine eyes; but his love is after thee still,
and his holy invitation continues to save thee.

Wherefore, O Christendom! believe, receive, and apply him rightly;
this is of absolute necessity, that thy soul may live forever with him.
He told the Jews, "`If you believe not that I am he, ye shall die in your sins;
and whither I go ye cannot come.`"^
footnote:[John 8:21,24.]
And because they believed him not, they did not receive him, nor any benefit by him.
But they that believed him received him; and as many as received him,
his own beloved disciple tells us, "`to them gave he power to become the sons of God,
which are born not of blood, nor of the will of the flesh, nor of the will of man,
but of God.`"^
footnote:[John 1:12-13.]
That is, who are not children of God after the fashions, prescriptions,
and traditions of men, that call themselves his church and people,
which is not after the will of flesh and blood, and the invention of carnal man,
unacquainted with the regeneration and power of the Holy Ghost, but of God; that is,
according to his will and the working and sanctification
of his Spirit and word of life in them.
And such were ever well versed in the right application of Christ,
for he was made to them indeed propitiation, reconciliation, salvation, righteousness,
redemption, and justification.

So I say to thee,
unless thou believest that he that stands at the door of thy heart and knocks,
and sets thy sins in order before thee, and calls thee to repentance,
be the Saviour of the world, thou wilt die in thy sins,
and where he is gone thou wilt never come.
For, if thou believest not in him, it is impossible that he should do thee good,
or effect thy salvation: Christ works not against faith, but by it.
It is said of old, "`He did not many mighty works in some places,
because the people believed not in him.`"^
footnote:[Matt. 13:58]
So that, if thou truly believest in him,
thine ear will be attentive to his voice in thee,
and the door of thine heart open to his knocks.
Thou wilt yield to the discoveries of his light,
and the teachings of his grace will be very dear to thee.

[.numbered]
V+++.+++ It is the nature of true faith to beget a holy fear of offending God,
a deep reverence to his precepts,
and a most tender regard to the inward testimony of his Spirit,
as that by which his children in all ages have been safely led to glory.
For, as they that truly believe receive Christ in all his tenders to the soul,
so as true it is that those who receive him thus,
with him receive power to become the sons of God: that is,
an inward force and ability to do whatever he requires; strength to mortify their lusts,
controul their affections, resist evil motions, deny themselves,
and overcome the world in its most enticing appearances.
This is the life of the blessed Cross of Christ,
which is the subject of the following discourse, and what thou, O man, must take up,
if thou intendest to be the disciple of Jesus.
Nor canst thou be said to receive Christ, or to believe in him,
whilst thou rejectest his cross.
For, as receiving of Christ is the means appointed of God to salvation,
so bearing the daily cross after him is the only true testimony of receiving him,
and therefore it is enjoined by him as the great token of discipleship,
"`If any man will come after me, let him deny himself, and take up his cross,
and follow me.`"^
footnote:[Matt. 16:24.]

This, Christendom, is that thou hast so much wanted,
and the want of which has proved the only cause of
thy miserable declension from pure Christianity.
To consider which well, as it is thy duty, so it is of great use to thy restoration.

For as the knowledge of the cause of any distemper guides the physician
to make a right and safe judgment in the application of his medicine,
so it will much enlighten thee in the way of thy recovery,
to know and weigh the first cause of this spiritual
lapse and malady that has befallen thee.
To do which, a general view of thy primitive estate,
and consequently of their work that first laboured in the Christian vineyard,
will be needful; and if therein something be repeated,
the weight and dignity of the subject will bear it, without the need of an apology.

[.numbered]
VI. The work of apostleship, we are told by a prime labourer in it,
was to turn people "`from darkness to light, and from the power of Satan unto God.`"^
footnote:[Acts 26:18.]
That is, instead of yielding to the temptations and motions of Satan,
who is the prince of darkness or wickedness, the one being a metaphor to the other,
by whose power their understandings were obscured,
and their souls held in the service of sin,
they should turn their minds to the appearance of Christ,
the Light and Saviour of the world; who by his light shines in their souls,
and thereby gives them a sight of their sins,
and discovers every temptation and motion in them unto evil,
and reproves them when they give way thereunto;
that so they might become the children of light, and walk in the path of righteousness.
And for this blessed work of reformation did Christ
endue his apostles with his spirit and power,
that so men might not longer sleep in a security of sin and ignorance of God,
but awake to righteousness, that the Lord Jesus might give them life; that is,
that they might leave off sinning, deny themselves the pleasure of wickedness, and,
by true repentance, turn their hearts to God in well doing, in which is peace.
And truly God so blessed the faithful labours of these poor mechanics,
yet his great ambassadors to mankind,
that in a few years many thousands that had lived without God in the world,
without a sense or fear of him, lawlessly,
very strangers to the work of his Spirit in their hearts,
being captivated by fleshly lusts,
were inwardly struck and quickened by the word of life,
and made sensible of the coming and power of the Lord Jesus
Christ as a judge and lawgiver in their souls,
by whose holy light and spirit the hidden things
of darkness were brought to light and condemned,
and pure repentance from those dead works begotten in them,
that they might serve the living God in newness of spirit.
So that thenceforward they lived not to themselves,
neither were they carried away of those former divers lusts,
by which they had been seduced from the true fear of God;
but "`the law of the spirit of life,`"^
footnote:[Rom. 8:2.]
by which they overcame the law of sin and death, was their delight,
and therein did they meditate day and night.
Their regard towards God was not taught by the precepts of men any longer,^
footnote:[Isaiah 29:13.]
but from the knowledge they had received by his own work and impressions in their souls.
They had quitted their old masters, the world, the flesh, and the devil,
and delivered up themselves to the holy guidance of the grace of Christ,
that taught them to "`deny ungodliness and the world`'s lusts, and to live soberly,
righteously, and godly in this present life:`"^
footnote:[Tit. 2:11-12.]
this is the cross of Christ indeed,
and here is the victory it gives to them that take it up;
by this cross they died daily to the old life they had lived,
and by holy watchfulness against the secret motions of evil
in their hearts they crushed sin in its conceptions,
yea in its temptations.
So that they, as the apostle John advised them, "`kept themselves,
that the evil one touched them not.`"^
footnote:[1 John 5:18.]

For the light, which Satan cannot endure, and with which Christ had enlightened them,
discovered him in all his approaches and assaults upon the mind;
and the power they received through their inward
obedience to the manifestations of that blessed light,
enabled them to resist and vanquish him in all his stratagems.
And thus it was that, where once nothing was examined, nothing went unexamined;
every thought must come to judgment,
and the rise and tendency of it be also well approved,
before they allowed it any room in their minds.
There was no fear of entertaining enemies for friends,
whilst this strict guard was kept upon the very wicket of the soul.
Now the old heavens and earth, that is, the old earthly conversation, and old carnal,
that is Jewish or shadowy worship, passed away apace,
and every day all things became new.
He was no more a Jew that was one outwardly, nor that circumcision that was in the flesh;
but he was the Jew that was one inwardly, and that circumcision which was of the heart,
in the Spirit, and not in the letter, whose praise is not of man, but of God.^
footnote:[Rom. 2:28-29.]

[.numbered]
VII.
Indeed,
the glory of the cross shined so conspicuously through
the self-denial of their lives who daily bore it,
that it struck the heathen with astonishment; and in a small time so shook their altars,
discredited their oracles, struck the multitude, invaded the court,
and overcame their armies, that it led priests, magistrates,
and generals in triumph after it, as the trophies of its power and victory.

And, while this integrity dwelt with Christians, mighty was the presence,
and invincible that power that attended them; it quenched fire, daunted lions,
turned the edge of the sword, outfaced instruments of cruelty, convicted judges,
and converted executioners.^
footnote:[Heb. 11:32, to the end; Isaiah 43:2; Daniel 3:12, to the end.]
In fine, the way their enemies took to destroy, increased them; and,
by the deep wisdom of God,
they who in all their designs endeavoured to extinguish
the truth were made great promoters of it.^
footnote:[Dan. 6:16, to the end.]
Now, not a vain thought, not an idle word, not an unseemly action was permitted; no,
not an immodest look, no courtly dress, gay apparel, complimental respects,
or personal honours: much less those lewd immoralities and scandalous vices,
now in vogue with Christians, could find either example or connivance among them.
Their care was not how to sport away their precious time, but how to redeem it,^
footnote:[Eph. 5:15-16,]
that they might have enough to work out their great salvation, which they carefully did,
with fear and trembling: not with balls and masks, with playhouses, dancing, feasting,
and gaming; no, no;
to make sure of their heavenly calling and election was
much dearer to them than the poor and trifling joys of mortality.
For they having, with Moses, seen him that is invisible,
and found that his lovingkindness was better than life,
the peace of his Spirit than the favour of princes,--as they feared not
// lint-disable invalid-characters "æ"
Cæsar`'s wrath,--so they chose rather to sustain the afflictions of Christ`'s
true pilgrims than enjoy the pleasures of sin that were but for a season;
esteeming his reproaches of more value than the perishing treasures of the earth.
And if the tribulations of Christianity were more
eligible than the comforts of the world,
and the reproaches of one than all the honour of the other,
there was then surely no temptations in it that could shake the integrity of Christendom.

[.numbered]
VIII.
By this short draught of what Christendom was, thou mayest see, O Christendom,
what thou are not, and consequently what thou oughtest to be.
But how comes it that from a Christendom that was thus meek, merciful, self-denying,
suffering, temperate, holy, just, and good, so like to Christ, whose name she bore,
we find a Christendom now that is superstitious, idolatrous, persecuting, proud,
passionate, envious, malicious, selfish, drunken, lascivious, unclean, lying, swearing,
cursing, covetous, oppressing, defrauding,
with all other abominations known in the earth?

I lay this down as the undoubted reason of this degeneracy, to wit,
the inward disregard of thy mind to the light of Christ shining in thee,
that first showed thee thy sins and reproved them,
and that taught and enabled thee to deny and resist them.
For as thy fear towards God, and holy abstinence from unrighteousness, was, at first,
not taught by the precepts of men,
but by that light and grace which revealed the most
secret thoughts and purposes of thine heart,
and searched the most inward parts, setting thy sins in order before thee,
and reproving thee for them, not suffering one unfruitful thought, word,
or work of darkness to go unjudged;
so when thou didst begin to disregard that light and grace,
to be careless of that holy watch that was once set up in thine heart,
and didst not keep sentinel there, as formerly, for God`'s glory and thy own peace,
the restless enemy of man`'s good quickly took advantage of this slackness,
and often surprised thee with temptations,
whose suitableness to thy inclinations made his conquest over thee not difficult.

In short, thou didst omit to take up Christ`'s holy yoke, to bear thy daily cross;
thou wast careless of thy affections, and kept no journal or check upon thy actions;
but didst decline to audit accounts in thy own conscience, with Christ thy light,
the great Bishop of thy soul and Judge of thy works,
whereby the holy fear decayed and love waxed cold, vanity abounded,
and duty became burdensome.
Then up came formality, instead of the power of godliness; superstition,
in place of Christ`'s institution:
and whereas Christ`'s business was to draw on the
minds of his disciples from an outward temple,
and carnal rites and services, to the inward and spiritual worship of God,
suitable to the nature of divinity, a worldly, human,
pompous worship is brought in again, and a worldly priesthood, temple, and altar,
are reestablished.
Now it was that the sons of God once more saw the daughters of men were fair,^
footnote:[Gen. 6:2.]
that is, the pure eye grew dim, which repentance had opened,
that saw no comeliness out of Christ,
and the eye of lust became unclosed again by the god of the world;
and those worldly pleasures that make such as love them forget God,
though once despised for the sake of Christ,
began now to recover their old beauty and interest in thy affections,
and from liking them, to be the study, care, and pleasure of thy life.

True, there still remained the exterior forms of worship
and a nominal and oral reverence to God and Christ,
but that was all; for the offence of the holy cross ceased,
the power of godliness was denied, self-denial lost, and,
though fruitful in the invention of ceremonious ornaments,
yet barren in the blessed fruits of the Spirit.
And a thousand shells cannot make one kernel, or many dead corpses one living man.

[.numbered]
IX. Thus religion fell from experience to tradition, and worship from power to form,
from life to letter; and, instead of putting up lively and powerful requests,
animated by a deep sense of want and the assistance
of the Holy Spirit,--by which the ancients prayed,
wrestled, and prevailed with God,--behold a by-rote mumpsimus,
a dull and insipid formality, made up of corporeal bowings and cringings,
garments and furnitures, perfumes, voices, and music,
fitter for the reception of some earthly prince than the
heavenly worship of the one true and immortal God,
who is an eternal, invisible Spirit.

But thy heart growing carnal, thy religion did so too; and, not liking it as it was,
thou fashionedst it to thy liking: forgetting what the holy prophet said,
"`The sacrifice of the wicked is an abomination to the Lord,`"^
footnote:[Prov. 15:8.]
and what St. James saith, "`Ye ask, and receive not.`"
Why? "`Because ye ask amiss;`"^
footnote:[James 4:3.]
that is, with a heart that is not right, but insincere, unmortified,
not in the faith that purifies the soul, and therefore can never receive what is asked:
so that a man may say with truth, thy condition is worse by thy religion,
because thou art tempted to think thyself better for it, and art not.

[.numbered]
X+++.+++ Well;
by this prospect that is given thee of thy foul fall from primitive Christianity,
and the true cause of it,--to wit,
a neglect of the daily cross of Christ,--it may be easy
for thee to inform thyself of the way of thy recovery.

For, look, at what door thou wentest out, at that door thou must come in; and,
as letting fall and forbearing the daily cross lost thee,
so taking up and enduring the daily cross must recover thee.
It is the same way by which the sinners and apostates become the disciples of Jesus.
"`Whosoever,`" says Christ, "`will come after me and be my disciple,
let him deny himself, and take up his daily cross and follow me.`"^
footnote:[Matthew 16:24; Mark 8:34; Luke 14:27.]
Nothing short of this will do; mark that! for, as it is sufficient,
so it is indispensable; no crown but by the cross, no life eternal but through death;
and it is but just that those evil and barbarous affections that crucified Christ afresh,
should, by his holy cross, be crucified.
Blood requires blood; his cross is the death of sin, that caused his death;
and he the death of death, according to that passage, O death!
I will be thy death!^
footnote:[Hos. 13:14; 1 Cor. 15:55.]

====
