== Chapter III.

1+++.+++ What the cross of Christ is.
A figurative speech,
but truly the Divine power that mortifies the world.--2. It is so called
by the apostle Paul to the Corinthians.--3. Where it is the cross appears,
and must be borne?
Within; where the lusts are,
there they must be crucified.--4. Experience teaches every one this;
to be sure Christ asserts it, from within comes murder, etc.,
and that is the house where the strong man must be
bound.--5. How is the cross to be borne?
The way is spiritual, a denial of self, of the pleasure of sin; to please God,
and obey his will as manifested to the soul by the
light He gives it.--6. This shows the difficulty,
yet the necessity of the cross.

The daily cross being then, and still, O Christendom! the way to glory,
that the succeeding matter, which wholly relates to the doctrine of it,
may come with most evidence and advantage upon thy conscience
it is most seriously to be considered by thee,--

First, What the cross of Christ is?

Secondly, Where the cross of Christ is to be taken up?

Thirdly, How, and after what manner it is to be borne?

Fourthly, What is the great work and business of the cross?
In which, the sins it crucifies, with the mischiefs that attend them,
will be at large expressed.

Fifthly and lastly,
I shall add many testimonies from living and dying persons of great reputation,
either for their quality, learning, or piety,
as a general confirmation of the whole tract.

To the first, What is the cross of Christ?

I+++.+++ The cross of Christ is a figurative speech, borrowed from the outward tree,
or wooden cross, on which Christ submitted to the will of God,
suffering death at the hands of evil men.
So that the cross mystical is that Divine grace and
power which crosseth the carnal wills of men,
and gives a contradiction to their corrupt affections,
and that constantly opposeth itself to the inordinate
and fleshly appetite of their minds,
and so may be justly termed the instrument of man`'s wholly dying to the world,
and being made conformable to the will of God.
For nothing else can mortify sin,
or make it easy for us to submit to the Divine will
in things otherwise very contrary to their own.

II. The preaching of the cross, therefore, in primitive times was fitly called by Paul,
that famous and skilful apostle in spiritual things,
"`the power of God,`" though to them that perish, then, as now, "`foolishness.`"
That is, to those that were truly weary and heavy laden, and needed a deliverer,
to whom sin was burdensome and odious, the preaching of the cross,
by which sin was to be mortified, was, as to them, the power of God,
or a preaching of the Divine power by which they
were made disciples of Christ and children of God;
and it wrought so powerfully upon them that no proud nor
licentious mockers could put them out of love with it.
But to those that walked in the broad way, in the full latitude of their lusts,
and dedicated their time and care to the pleasure of their corrupt appetites,
to whom all yoke and bridle were and are intolerable,
the preaching of the cross was and is foolishness.

III.
Well: but then where does this cross appear, and where must it be taken up?

I answer, within: that is, in the heart and soul; for where the sin is, the cross must be.
Now all evil comes from within: this Christ taught: "`From within,`" saith Christ,
"`out of the heart of man proceed evil thoughts, adulteries, fornications, murders,
thefts, covetousness, wickedness, deceit, lasciviousness, an evil eye, blasphemy, pride,
foolishness: all these evils come from within, and defile the man.`"^
footnote:[Mark 7:21-23.]

The heart of man is the seat of sin, and where he is defiled he must be sanctified;
and where sin lives, there it must die: it must be crucified.
Custom in evil hath made it natural to men to do evil; and as the soul rules the body,
so the corrupt nature sways the whole man: but still, it is all from within.

IV. Experience teaches every son and daughter of Adam to assent to this;
for the enemy`'s temptations are ever directed to the mind, which is within:
if they take not, the soul sins not; if they are embraced, lust is presently conceived,
that is, inordinate desires; lust conceived, brings forth sin; and sin finished, that is,
acted, brings forth death.^
footnote:[James 5:15.]
Here is both the cause and the effect, the very genealogy of sin, its rise and end.

In all this, the heart of evil man is the devil`'s mint, his work-house,
the place of his residence, where he exercises his power and art.
And therefore the redemption of the soul is aptly
called the destruction of the works of the devil,
and bringing in of everlasting righteousness.^
footnote:[1 John 3:8.; Dan. 9:24.]
When the Jews would have defamed Christ`'s miracle of casting out devils,
by a blasphemous imputation of it to the power of Beelzebub,
he says that "`no man can enter into a strong man`'s house, and spoil his goods,
till he first bind the strong man.`"^
footnote:[Matt. 12:29.]
Which,
as it shows the contrariety that was between Beelzebub
and the power by which he dispossessed him,
so it teaches us to know that the souls of the wicked are the devil`'s house,
and that his goods, his evil works,
can never be destroyed till first he that wrought them, and keeps the house, be bound.
All which makes it easy to know where the cross must be taken up,
by which alone the strong man must be bound, his goods spoiled,
and his temptations resisted, that is, within, in the heart of man.

V+++.+++ But in the next place, how and in what manner is the cross to be daily borne?

The way, like the cross, is spiritual:
that is an inward submission of the soul to the will of God,
as it is manifested by the light of Christ in the consciences of men,
though it be contrary to their own inclinations.
For example: when evil presents,
that which shows the evil does also tell them they should not yield to it;
and if they close with its counsel, it gives them power to escape it.
But they that look and gaze upon the temptation, at last fall in with it,
and are overcome by it; the consequence of which is guilt and judgment.
Therefore, as the cross of Christ is that spirit and power in men, though not of men,
but of God, which crosseth and reproveth their fleshly lusts and affections;
so the way of taking up the cross is an entire resignation
of soul to the discoveries and requirings of it:
not to consult their worldly pleasure, or carnal ease, or interest,
for such are captivated in a moment,
but continually to watch against the very appearances of evil,
and by the obedience of faith, that is, of true love to, and confidence in God,
cheerfully to offer up to the death of the cross, that evil part,
that Judas in themselves, which, not enduring the heat of the siege,
and being impatient in the hour of temptation, would,
by its near relation to the tempter, more easily betray their souls into his hands.

VI. O this shows to every one`'s experience how hard it
is to be a true disciple of Jesus! the way is narrow indeed,
and the gate very strait, where not a word, no not a thought must slip the watch,
or escape judgment; such circumspection, such caution, such patience, such constancy,
such holy fear and trembling.
This gives an easy interpretation to that hard saying,
"`Flesh and blood cannot inherit the kingdom of God;`"^
footnote:[Matt. 24:42; xxv.
13; xxvi.
38, 42;]
those that are captivated with fleshly lusts and affections:
for they cannot bear the cross;
and they that cannot endure the cross must never have the crown.
To reign, it is necessary first to suffer.^
footnote:[Phil. 2:12; 1 Cor. 15:50.]
