== Chapter IV.

[.chapter-synopsis]
* 1+++.+++ What is the great work of the cross? The answer to this is of great moment.
* 2+++.+++ The work of the cross is self-denial.
* 3+++.+++ What was the cup and cross of Christ?
* 4+++.+++ What is our cup and cross?
* 5+++.+++ Our duty is to follow Christ as our captain.
* 6+++.+++ Of the distinction in self, a lawful and unlawful self.
* 7+++.+++ What the lawful self is.
* 8+++.+++ That it is to be denied in some cases by Christ`'s doctrine and example.
* 9+++.+++ By the Apostle`'s pattern.
* 10+++.+++ The danger of preferring lawful self above our duty to God.
* 11+++.+++ The reward of self-denial an excitement to it.
* 12+++.+++ This doctrine as old as Abraham.
* 13+++.+++ His obedience of faith memorable.
* 14+++.+++ Job a great instance of self-denial, his contentment.
* 15+++.+++ Moses also a mighty example, his neglect of Pharaoh`'s court.
* 16+++.+++ His choice.
* 17+++.+++ The reason of it, viz. the recompense of reward.
* 18+++.+++ Isaiah no inconsiderable instance, who of a courtier, became a holy prophet.
* 19+++.+++ These instances concluded with that of holy Daniel, his patience and integrity, and the success they had upon the king.
* 20+++.+++ There might be many mentioned to confirm this blessed doctrine.
* 21+++.+++ All must be left for Christ, as men would be saved.
* 22+++.+++ The way of God is a way of faith and self-denial.
* 23+++.+++ An earnest supplication and exhortation to all, to attend upon these things.

But fourthly, What is the great work and business of the cross respecting man?

[.numbered-group]
====

[.numbered]
I+++.+++ This indeed is of that mighty moment to be truly, plainly, and thoroughly answered,
that all that went before seems only to serve for preface to it;
and miscarrying in it to be no less than a misguidance
of the soul about its way to blessedness.
I shall therefore pursue the question, with God`'s help,
and the best knowledge He hath given me in the experience of several years`' discipleship.

[.numbered]
II. The great work and business of the cross of Christ in man is self-denial;
a word of as much depth in itself as of sore contradiction to the world,
little understood but less embraced by it, yet it must be borne for all that.
The Son of God is gone before us, and,
by the bitter cup He drank and the baptism He suffered,
has left us an example that we should follow in his steps;
which made him put that hard question to the wife of Zebedee and her two sons,
upon her soliciting that one might sit at his right
and the other at his left hand in his kingdom,
"`Are ye able to drink of the cup that I shall drink of,
and to be baptized with the baptism I am baptized with?`"
It seems their faith was strong; they answered, "`We are able.`"
Upon which he replied, "`Ye shall drink indeed of my cup,
and be baptized with the baptism I am baptized with;`"
but their reward he left to his Father.^
footnote:[Matt. 20:21-23.]

[.numbered]
III.
What was his cup he drank, and baptism he suffered?
I answer,
they were the denial and offering up of himself by the eternal Spirit to the will of God,
undergoing the tribulations of his life and agonies
of his death upon the cross for man`'s salvation.

[.numbered]
IV. What is our cup and cross that we should drink and suffer?
They are the denial and offering up of ourselves, by the same Spirit,
to do or suffer the will of God for his service and glory,
which is the true life and obedience of the cross of Jesus; narrow still,
but before an unbeaten way.
For when there was none to help, not one to open the seals, to give knowledge,
to direct the course of poor man`'s recovery,
He came in the greatness of his love and strength;
and though clothed with the infirmities of a mortal man,
being within fortified with the almightiness of an immortal God,
He travelled through all the straits and difficulties of humanity, and first,
of all others, trod the untrodden path to blessedness.

[.numbered]
V+++.+++ O come! let us follow Him, the most unwearied,
the most victorious captain of our salvation;
// lint-disable invalid-characters "æ"
to whom all the great Alexanders and mighty Cæsars of the world
are less than the poorest soldier of their camps could be to them.
True, they were all great princes of their kind, and conquerors too,
but on very different principles.
For Christ made himself of no reputation, to save mankind;
but these plentifully ruined people to augment theirs.
They vanquished others, not themselves; Christ conquered self, that ever vanquished them;
of merit therefore the most excellent Prince and Conqueror.
Besides, they advanced their empire by rapine and blood,
but He by suffering and persuasion; He never by compulsion,
they always by force prevailed.
Misery and slavery followed all their victories,
his brought greater freedom and felicity to those he overcame.
In all they did they sought to please themselves;
in all He did he aimed to please his Father, who is King of kings and Lord of lords.

It is this most perfect pattern of self-denial we must follow,
if ever we will come to glory;
to do which let us consider self-denial in its true distinction and extent.

[.numbered]
VI. There is a lawful and unlawful self: and both must be denied for the sake of him,
who in submission to the will of God counted nothing dear that he might save us.
And, though the world be scarcely in any part of it at that pass
as yet to need that lesson of the denial of lawful self,
that every day most greedily sacrifices to the pleasure of unlawful self;
yet to take the whole thing before me,
and for that it may possibly meet with some that are so far advanced
in this spiritual warfare as to receive some service from it,
I shall at least touch upon it.

[.numbered]
VII.
The lawful self which we are to deny, is that conveniency, ease, enjoyment, and plenty,
which in themselves are so far from being evil,
that they are the bounty and blessings of God to us, as husband, wife, child, house,
land, reputation, liberty, and life itself; these are God`'s favours,
which we may enjoy with lawful pleasure and justly improve as our honest interest.
But when God requires them,
at what time soever the lender calls for them or is pleased
to try our affections by our parting with them;
I say, when they are brought in competition with him, they must not be preferred,
they must be denied.
Christ himself descended from the glory of his Father,
and willingly made himself of no reputation among men,
that he might make us of some with God; and,
from the quality of thinking it no robbery to be equal with God,
he humbled himself to the poor form of a servant; yea,
the ignominious death of the cross,^
footnote:[Phil. 2:5-8.]
that he might deliver us an example of pure humility,
and entire submission to the will of our heavenly Father.

[.numbered]
VIII.
It is the doctrine he teaches us in these words, "`He that loveth father or mother,
son or daughter, more than me, is not worthy of me.`"^
footnote:[Matt. 10:37.]
Again, "`Whoever he be of you that forsaketh not all that he hath,
cannot be my disciple.`"^
footnote:[Luke 14:33.]
And he plainly told the young rich man that if he would have eternal life,
he should sell all and follow him;^
footnote:[Mark 10:21-22.]
a doctrine sad to him as it is to those that, like him,
for all their high pretences to religion,
in truth love their possessions more than Christ.
This doctrine of self-denial is the condition to eternal happiness,
"`He that will come after me, let him deny himself,
and take up his cross and follow me.`"^
footnote:[Matt. 16:24.]

[.numbered]
IX. This made those honest fishermen quit their lawful trades and follow him,
when he called them to it,
and others that waited for the consolation of Israel to offer up their estates,
reputations, liberties, and also lives,
to the displeasure and fury of their kindred and the government
they lived under for the spiritual advantage that accrued
to them by their faithful adherence to his holy doctrine.
True, many would have excused their following him in the parable of the feast:
some had bought land, some had married wives, and others had bought yokes of oxen,
and could not come;^
footnote:[Luke 14:18-20.]
that is, an immoderate love of the world hindered them: their lawful enjoyments,
from servants became their idols; they worshipped them more than God,
and would not quit them to come to God.
But this is recorded to their reproach;
and we may herein see the power of self upon the worldly man,
and the danger that comes to him by the abuse of lawful things.
What, thy wife dearer to thee than thy Saviour! and thy
land and oxen preferred before thy soul`'s salvation!
O beware, that thy comforts prove not snares first, and then curses: to overrate them,
is to provoke him that gave them to take them away again: come,
and follow him that giveth life eternal to the soul.

[.numbered]
X+++.+++ Woe to them that have their hearts in their earthly
possessions! for when they are gone,
their heaven is gone with them.
It is too much the sin of the greatest part of the world,
that they stick in the comforts of it.
And it is lamentable to behold how their affections are bemired
and entangled with their conveniencies and accommodations in it.
The true self-denying man is a pilgrim;
but the selfish man is an inhabitant of the world: the one uses it, as men do ships,
to transport themselves or tackle in a journey, that is, to get home;
the other looks no further, whatever he prates,
than to be fixed in fulness and ease here, and likes it so well, that if he could,
he would not exchange.
However, he will not trouble himself to think of the other world,
till he is sure he must live no longer in this: but then, alas! it may prove too late;
not to Abraham, but to Dives he may go; the story is as true as sad.

[.numbered]
XI. But on the other hand,
it is not for nought that the disciples of Jesus deny themselves; and indeed,
Christ himself had the eternal joy in his eye:
"`For the joy that was set before him,`" says the author to the Hebrews,
"`he endured the cross;`"^
footnote:[Heb. 12:2.]
that is, he denied himself, and bore the reproaches and death of the wicked;
and despised the shame, to wit, the dishonour and derision of the world.
It made him not afraid nor shrink, he contemned it;
and is set down at the right hand of the throne of God.^
footnote:[Heb. 12:2.]
And to their encouragement, and great consolation, when Peter asked him,
what they should have that had forsaken all to follow him, he answered them,
"`Verily I say unto you, that ye, which have followed me in the regeneration,
when the Son of Man shall sit on the throne of his glory,
ye also shall sit upon twelve thrones, judging the twelve tribes of Israel,`"^
footnote:[Matt. 19:27-29.]
that were then in an apostacy from the life and power of godliness.
This was the lot of his disciples; the more immediate companions of his tribulations,
and first messengers of his kingdom.
But the next that follows is to all: and "`every one that hath forsaken houses,
or brethren, or sisters, or father, or mother, or wife, or children, or lands,
for my name`'s sake, shall receive an hundred fold, and shall inherit everlasting life.`"
It was this recompense of reward, this eternal crown of righteousness,
that in every age has raised, in the souls of the just, a holy neglect, yea,
contempt of the world.
To this is owing the constancy of the martyrs, as to their blood,
the triumph of the Truth.

[.numbered]
XII.
Nor is this a new doctrine; it is as old as Abraham.^
footnote:[Gen.
xviii.]
In several most remarkable instances, his life was made up of self-denial.
First, in quitting his own land,
where we may well suppose him settled in the midst of plenty, at least sufficiency:
and why?
Because God called him.
Indeed this should be reason enough,
but such is the world`'s degeneracy that in fact it is not: and the same act,
upon the same inducement, in any now, though praised in Abraham, would be derided.
So apt are people not to understand what they commend; nay, to despise those actions,
when they meet them in the people of their own times,
which they pretend to admire in their ancestors.

[.numbered]
XIII.
But he obeyed: the consequence was, that God gave him a mighty land.
This was the first reward of his obedience.
The next was, a son in his old age; and which greatened the blessing, after it had been,
in nature, past the time of his wife`'s bearing of children.^
footnote:[Gen.
Xxi.]
Yet God called for his darling, their only child, the joy of their age,
the son of a miracle,
and he upon whom the fulfilling of the promise made to Abraham did depend.
For this son, I say, God called: a mighty trial: that which, one would have thought,
might very well have overturned his faith, and stumbled his integrity;
at least have put him upon this dispute in himself.
This command is unreasonable and cruel; it is the tempter`'s, it cannot be God`'s. For,
is it to be thought that God gave me a son to make a sacrifice of him?
that the father should be butcher of his only child?
Again, that he should require me to offer up the son of his own promise,
by whom his covenant is to be performed; this is incredible.
I say, thus Abraham might naturally enough have argued, to withstand the voice of God,
and indulge his great affections to his beloved Isaac.
But good old Abraham, that knew the voice that had promised him a son,
had not forgotten to know it, when it required him back again; he disputes not,
though it looked strange, and perhaps with some surprise and horror, as a man.
He had learned to believe that God, that gave him a child by a miracle,
could work another to preserve or restore him.
His affections could not balance his duty, much less overcome his faith;
for he received him in a way that would let him doubt
of nothing that God had promised to him.

To the voice of this Almightiness he bows, builds an altar, binds his only son upon it,
kindles the fire, and stretches forth his hand to take the knife:
but the angel stopped the stroke: Hold, Abraham, thy integrity is proved.
What followed?
a ram served, and Isaac was his again.
This shows how little serves, where all is resigned,
and how mean a sacrifice contents the Almighty, where the heart is approved.
So that it is not the sacrifice that recommends the heart,
but the heart that gives the sacrifice acceptance.

God often touches our best comforts, and calls for that which we most love,
and are least willing to part with.
Not that he always takes it utterly away, but to prove the soul`'s integrity,
to caution us from excesses, and that we may remember God,
the author of those blessings we possess, and live loose to them.
I speak my experience; the way to keep our enjoyments is to resign them;
and though that be hard, it is sweet to see them returned,
as Isaac was to his father Abraham, with more love and blessing than before.
O stupid world!
O worldly Christians; not only strangers,
but enemies to this excellent faith! and whilst so, the rewards of it you can never know.

[.numbered]
XIV.
But Job presses hard upon Abraham: his self-denial also was very signal.
For when the messengers of his afflictions came thick upon him,
one doleful story after another, till he was left almost as naked as when he was born;
the first thing he did, he fell to the ground, and worshipped that power,
and kissed that hand that stripped him; so far from murmuring,
that he concludes his losses of estate and children with these words:
"`Naked came I out of my mother`'s womb, and naked shall I return:
the Lord gave and the Lord hath taken away; blessed be the name of the Lord.`"^
footnote:[Job 1:21.]
O the deep faith, patience,
and contentment of this excellent man! one would have thought this repeated
news of ruin had been enough to have overset his confidence in God;
but it did not; that stayed him.
But indeed he tells us why; his Redeemer lived; "`I know,`" says he,
"`that my Redeemer lives.`"^
footnote:[Job 19:25-26.]
And it appeared he did; for he had redeemed him from the world:
his heart was not in his worldly comforts:
his hope lived above the joys of time and troubles of mortality; not tempted by the one,
nor shaken by the other; but firmly believed,
that when after his skin worms should have consumed his body,
yet with his eyes he should see his God.
Thus was the heart of Job both submitted to and comforted in the will of God.

[.numbered]
XV. Moses is the next great example in sacred story for remarkable self-denial,
before the times of Christ`'s appearance in the flesh.
He had been saved when an infant, by an extraordinary providence, and it seems,
by what followed, for an extraordinary service: Pharaoh`'s daughter,
whose compassion was the means of his preservation,
when the king decreed the slaughter of the Hebrew males,^
footnote:[Ex. 2:1,10.]
took him for her son, and gave him the education of her father`'s court.
His own graceful presence and extraordinary abilities, joined with her love for him,
and interest in her father to promote him, must have rendered him,
if not capable of succession,
at least of being chief minister of affairs under that wealthy and powerful prince.
For Egypt was then what Athens and Rome were after, the most famous for learning, art,
and glory.

[.numbered]
XVI.
But Moses, ordained for other work and guided by a higher principle,
no sooner came to years of discretion, than the impiety of Egypt,
and the oppressions of his brethren there, grew a burden too heavy for him to bear.
And though so wise and good a man could not want those generous and grateful acknowledgments,
that became the kindness of the king`'s daughter to him;
yet he had also seen that God that was invisible;^
footnote:[Heb. 11:24-27.]
and did not dare to live in the ease and plenty of Pharaoh`'s house,
whilst his poor brethren were required to make brick without straw.^
footnote:[Ex. 5:16-7.]

Thus the fear of the Almighty taking deep hold of his heart,
he nobly refused to be called the son of Pharaoh`'s daughter,
and chose rather a life of affliction, with the most despised and oppressed Israelites,
and to be the companion of their tribulations and jeopardies,
than to enjoy the pleasures of sin for a season; esteeming the reproaches of Christ,
which he suffered for making that unworldly choice,
greater riches than all the treasures of that kingdom.

[.numbered]
XVII.
Nor was he so foolish as they thought him; he had reason on his side; for it is said,
he had an eye to the recompense of reward,
he did but refuse a lesser benefit for a greater.
In this his wisdom transcended that of the Egyptians;
for they made the present world their choice, as uncertain as the weather,
and so lost that which has no end.
Moses looked deeper, and weighed the enjoyments of this life in the scales of eternity,
and found they made no weight there.
He governed himself not by the immediate possession,
but the nature and duration of the reward.
His faith corrected his affections, and taught him to sacrifice the pleasure of self,
to the hope he had of a future more excellent recompense.

[.numbered]
XVIII.
Isaiah^
footnote:[Dorotheus in his Lives of the Prophets.]
was no inconsiderable instance of this blessed self-denial;
who of a courtier became a prophet, and left the worldly interests of the one,
for the faith, patience, and sufferings of the other.
For his choice did not only lose him the favour of men, but their wickedness,
enraged at his integrity to God, in his fervent and bold reproofs of them,
made a martyr of him in the end,
for they barbarously sawed him asunder in the reign of king Manasseh.
Thus died that excellent man, and commonly called the Evangelical Prophet.

[.numbered]
XIX.
I shall add, of many, one example more, and that is from the fidelity of Daniel;
a holy and wise young man,
who when his external advantages came in competition with his duty to Almighty God,
relinquished them all; and instead of being solicitous how to secure himself,
as one minding nothing less, he was, to the utmost hazard of himself,
most careful how to preserve the honour of God, by his fidelity to his will.
And though at the first it exposed him to ruin, yet,
as an instance of great encouragement to all that like him
will choose to keep a good conscience in an evil time,
at last it advanced him greatly in the world;
and the God of Daniel was made famous and terrible through
his perseverance even in the eyes of heathen kings.

[.numbered]
XX. What shall I say of all the rest,
who counted nothing dear that they might do the will of God,
abandoned their worldly comforts, and exposed their ease and safety,
as often as the heavenly vision called them,^
footnote:[Dorotheus in his Lives of the Prophets.]
to the wrath and malice of degenerate princes and an apostate church?
More especially Jeremiah, Ezekiel, and Micah, who after they had denied themselves,
in obedience to the divine voice, sealed their testimony with their blood.

Thus was self-denial the practice and glory of the ancients,
that were predecessors to the coming of Christ in the flesh:
and shall we hope to go to heaven without it now,
when our Saviour himself is become the most excellent example of it?
and that not as some would fain have it, viz. for us, that we need not; but for us,
that we might deny ourselves, and so be the true followers of his blessed example.^
footnote:[1 Peter 2:20-22.]

[.numbered]
XXI.
Whoever therefore thou art that wouldst do the will of God, but faintest in thy desires,
from the opposition of worldly considerations, remember I tell thee,
in the name of Christ, that he that prefers father or mother, sister or brother,
wife or child, house or land, reputation, honour, office, liberty, or life,
before the testimony of the light of Jesus, in his own conscience,
shall be rejected of him in the solemn and general inquest upon the world,
when all shall be judged, and receive according to the deeds done,
not the profession made, in this life.
It was the doctrine of Jesus, that if thy right hand offend thee, thou must cut it off;
and if thy right eye offend thee, thou must pluck it out:^
footnote:[Matt. 5:29-30.]
that is, if the most dear, the most useful and tender comforts thou enjoyest,
stand in thy soul`'s way, and interrupt thy obedience to the voice of God,
and thy conformity to his holy will revealed in thy soul, thou art engaged,
under the penalty of damnation, to part with them.

[.numbered]
XXII.
The way of God is a way of faith, as dark to sense, as mortal to self.
It is the children of obedience, who count, with holy Paul, all things dross and dung,
that they may win Christ, and know and walk in this narrow way.
Speculation will not do, nor can refined notions enter;
the obedient only eat the good of this land.^
footnote:[Isaiah 1:19.]
They that do his will, says the blessed Jesus, shall know of my doctrine;^
footnote:[John 7:17.]
them He will instruct.
There is no room for instruction, where lawful self is lord, and not servant.
For self cannot receive it; that which should is oppressed by self, fearful, and dare not.
O! what will my father or mother say?
How will my husband use me?
or finally, what will the magistrate do with me?
For though I have a most powerful persuasion, and clear conviction upon my soul,
of this or that thing, yet considering how unmodish it is, what enemies it has,
and how strange and singular I shall seem to them, I hope God will pity my weakness:
if I sink, I am but flesh and blood; it may be hereafter He may better enable me;
and there is time enough.
Thus selfish, fearful man.

But deliberating is ever worst; for the soul loses in parley:
the manifestation brings power with it.
Never did God convince people, but, upon submission, he empowered them.
He requires nothing without giving ability to perform it: that were mocking,
not saving men.
It is enough for thee to do thy duty, that God shows thee thy duty;
provided thou closest with that light and spirit by which he gives thee that knowledge.
They that want power, are such as do not receive Christ in his convictions upon the soul,
and such will always want it; but such as do, they receive power, like those of old,
to become the children of God, through the pure obedience of faith.

[.numbered]
XXIII.
Wherefore, let me beseech you, by the love and mercy of God,
by the life and death of Christ, by the power of his Spirit, and the hope of immortality,
that you, whose hearts are established in your temporal comforts, and so lovers of self,
more than of these heavenly things, would let the time past suffice:
that you would not think it enough to be clear of such impieties,
as too many are found in,
whilst your inordinate love of lawful things has defiled your enjoyment of them,
and drawn your hearts from the fear, love, obedience,
and self-denial of a true disciple of Jesus.
Turn about then, and hearken to the still voice in thy conscience;
it tells thee thy sins, and thy misery in them;
it gives a lively discovery of the very vanity of the world,
and opens to the soul some prospect of eternity,
and the comforts of the just that are at rest.
If thou adhere to this, it will divorce thee from sin and self: thou wilt soon find,
that the power of its charms exceeds that of wealth, honour, and beauty of the world,
and finally will give thee that tranquillity which
the storms of time can never shipwreck nor disorder.
Here all thy enjoyments are blest, though small,
yet great by that presence that is within them.

Even in this world the righteous have the better of it,
for they use the world without rebuke, because they do not abuse it.
They see and bless the hand that feeds, and clothes, and preserves them.
And as by beholding him in all his works, they do not adore them, but him;
so the sweetness of his blessings that gives them,
is an advantage such have upon those that see him not.
Besides, in their increase, they are not lifted up,
nor in their adversities are they cast down: and why?
Because they are moderated in the one, and comforted in the other, by his divine presence.

In short, heaven is the throne,
and the earth but the footstool of that man that hath self under foot.
And those that know that station will not easily be moved;
such learn to number their days, that they may not be surprised with their dissolution;
and to redeem their time, because their days are evil;^
footnote:[Eph. 5:16.]
remembering they are stewards, and must deliver up their accounts to an impartial judge.
Therefore not to self but to him they live, and in him die,
and are blessed with them that die in the Lord.
And thus I conclude my discourse on the right use of lawful self.

====
