== Chapter V.

[.chapter-synopsis]
* 1+++.+++ Of unlawful self; it is two-fold: 1st, in religion; 2nd, in morality.
* 2+++.+++ Of those that are most formal, superstitious, and pompous in worship.
* 3+++.+++ God`'s rebuke of carnal apprehensions.
* 4+++.+++ Christ drew off his disciples from the Jewish exterior worship, and instituted a more spiritual one.
* 5+++.+++ Stephen is full and plain in this matter.
* 6+++.+++ Paul refers the temple of God twice to man.
* 7+++.+++ Of the cross of these worldly worshippers.
* 8+++.+++ Flesh and blood make their cross, therefore cannot be crucified by it.
* 9+++.+++ They are yokes without restraint.
* 10+++.+++ Of the gaudiness of their cross, and their respect to it.
* 11+++.+++ A recluse life no true gospel abnegation.
* 12+++.+++ Comparison between Christ`'s self-denial and theirs: his leads to purity in the world, theirs to voluntary imprisonment, that they might not be tempted of the world. The mischief which that example, if followed, would do to the world. It destroys useful society and honest labour. A lazy life the usual refuge of idleness, poverty, and guilty age.
* 13+++.+++ Of Christ`'s cross in this case. The impossibility that such an external application can remove an internal cause.
* 14+++.+++ An exhortation to the men of this belief, not to deceive themselves.

[.numbered-group]
====

[.numbered]
I+++.+++ I am now come to unlawful self, which, more or less,
is the immediate concern of much the greater part of mankind.
This unlawful self is two-fold.
First, that which relates to religious worship: secondly,
that which concerns moral and civil conversation in the world.
And they are both of infinite consequence to be considered by us.
In which I shall be as brief as I may, with ease to my conscience,
and no injury to the matter.

[.numbered]
II. That unlawful self in religion that ought to be mortified by the cross of Christ,
is man`'s invention and performance of worship to God as divine, which is not so,
either in its institution or performance.
In this great error those people have the van of
all that attribute to themselves the name of Christians,
that are most exterior, pompous, and superstitious in their worship;
for they do not only miss exceedingly by a spiritual unpreparedness,
in the way of their performing worship to God Almighty, who is an Eternal Spirit;
but the worship itself is composed of what is utterly inconsistent
with the very form and practice of Christ`'s doctrine,
and the apostolical example.
For whereas that was plain and spiritual, this is gaudy and worldly:
Christ`'s most inward and mental, theirs most outward and corporeal:
that suited to the nature of God, who is a Spirit,
this accommodated to the most carnal part.
So that instead of excluding flesh and blood,
behold a worship calculated to gratify them:
as if the business were not to present God with a worship to please Him,
but to make one to please themselves.
A worship dressed with such stately buildings and imagery, rich furnitures and garments,
rare voices and music, costly lamps, wax candles, and perfumes;
and all acted with that most pleasing variety to
the external senses that art can invent or cost procure;
as if the world were to turn Jew or Egyptian again; or that God was an old man indeed,
and Christ a little boy, to be treated with a kind of religious mask:
for so they picture him in their temples, and too many in their minds.
And the truth is, such a worship may very well suit such an idea of God:
for when men can think Him such a one as themselves,
it is not to be wondered if they address Him in a way that
would be the most pleasing from others to themselves.

[.numbered]
III.
But what said the Almighty to such a sensual people of old, much upon the like occasion?
"`Thou thoughtest I was such an one as thyself, but I will reprove thee,
and set thy sins in order before thee.
Now consider this, ye that forget God,
lest I tear you in pieces and there be none to deliver.`"
But, "`to him that ordereth his conversation aright, will I show the salvation of God.`"^
footnote:[Ps. 50:21-23.]
This is the worship acceptable to him, "`to do justly, to love mercy,
and to walk humbly with God.`"^
footnote:[Mic. 6:8.]
For He that searcheth the heart, and tries the reins of man,
and sets his sins in order before him, who is the God of the spirits of all flesh,
looks not to the external fabric, but internal frame of the soul,
and inclination of the heart.
Nor is it to be soberly thought, that He who is clothed with divine honour and majesty;
who covers himself with light as with a garment;
who stretches out the heavens like a curtain;
who layeth the beams of his chambers in the deep; who maketh the clouds his chariot,
and walks upon the wings of the wind: who maketh his angels spirits,
his ministers a flaming fire: who laid the foundation of the earth,
that it should not be moved forever;
can be adequately worshipped by those human inventions,
the refuge of an apostate people from the primitive
power of religion and spirituality of Christian worship.

[.numbered]
IV. Christ drew off his disciples from the glory and worship of the outward temple,
and instituted a more inward and spiritual worship, in which He instructed his followers,
"`Ye shall neither in this mountain,
nor yet at Jerusalem,`" says Christ to the Samaritan woman, "`worship the Father;
God is a Spirit, and they that worship Him, must worship Him in spirit and in truth.`"^
footnote:[John 4:21,24]
As if he had said, for the sake of the weakness of the people,
God condescended in old time to limit himself to an outward time, place, temple,
and service, in and by which he would be worshipped;
but this was during men`'s ignorance of his omnipresence,
and that they considered not what God is, nor where he is;
but I am come to reveal him to as many as receive me;
and I tell you that God is a spirit, and will be worshipped in Spirit and in truth.
People must be acquainted with him as a spirit, consider and worship him as such.
It is not that bodily worship, or these ceremonial services, in use among you now,
will serve, or give acceptance with this God that is a Spirit: no,
you must obey his Spirit that strives with you,
to gather you out of the evil of the world,
that by bowing to the instructions and commands of his Spirit in your own souls,
you may know what it is to worship him as a Spirit;
then you will understand that it is not going to this mountain, nor to Jerusalem,
but to do the will of God, to keep his commandments, and commune with thine own heart,
and sin not; take up thy cross, meditate in his holy law,
and follow the example of Him whom the Father hath sent.

[.numbered]
V+++.+++ Wherefore Stephen, that bold and constant martyr of Jesus, told the Jews,
when a prisoner at the bar for disputing about the end of their beloved temple,
and its services, but falsely accused of blasphemy; "`Solomon,`" said Stephen,
"`built God an house; howbeit God dwelleth not in temples made with hands;
as saith the prophet,^
footnote:[Acts 7:47-50.]
Heaven is my throne, and the earth is my footstool: what house will ye build me?
saith the Lord: or what is the place of my rest?
Hath not my hand made all these things?`"^
footnote:[Isaiah 66:1-2.]
Behold a total overthrow to all worldly temples, and their ceremonial appendages.
The martyr follows his blow upon those apostate Jews, who were of those times,
the pompous, ceremonious, worldly worshippers:
"`Ye stiff-necked and uncircumcised in heart and ears,
ye do always resist the Holy Ghost; as did your fathers, so do ye.`"^
footnote:[Acts 7:51.]
As if He had told them, no matter for your outward temples, rites, and shadowy services,
your pretensions to succession in nature from Abraham; and by religion from Moses.
You are resisters of the Spirit, gainsayers of its instructions:
you will not bow to his counsel, nor are your hearts right towards God:
you are the successors of your father s`' iniquity; and though verbal admirers,
yet none of the successors of the prophets in faith and life.

But the prophet Isaiah carries it a little further than is cited by Stephen.
For after having declared what is not God`'s house, the place where his honour dwells,
immediately follow these words: "`But to this man will I look, even to him that is poor,
and of a contrite spirit, and trembleth at my word.`"^
footnote:[Isa.
lxvi.]
Behold, O carnal and superstitious man, the true worshipper, and the place of God`'s rest!
This is the house and temple of Him whom the heaven of heavens cannot contain;
a house self cannot build, nor the art or power of man prepare or consecrate.

[.numbered]
VI. Paul, that great apostle of the Gentiles,
twice expressly refers the word temple to man:
once in his epistle to the church of Corinth; "`Know ye not,`" says he,
"`that your body is the temple of the Holy Ghost which is in you,
which ye have of God?`"^
footnote:[1 Cor. 6:19,]
etc. and not the building of man`'s hand and heart.
Again, he tells the same people, in his second epistle,
"`For ye are the temple of the living God, as God hath said;`"^
footnote:[2 Cor. 6:16.]
and then cites God`'s words by the prophet, "`I will dwell in them, and walk in them;
I will be their God, and they shall be my people.`"
This is the evangelical temple, the Christian church,
whose ornaments are not the embroideries and furnitures of worldly art and wealth,
but the graces of the Spirit; meekness, love, faith, patience, self-denial, and charity.
Here it is, that the eternal wisdom, that was with God from everlasting,
before the hills were brought forth, or the mountains laid, chooses to dwell;
"`rejoicing,`" says Wisdom, "`in the habitable part of the earth,
and my delights were with the sons of men:`"^
footnote:[Prov. 8:22-23, 25, 31.]
not in houses built of wood and stone.
This living house is more glorious than Solomon`'s dead house;
and of which his was but a figure, as he, the Builder, was of Christ,
who builds up a holy temple to God.
It was promised of old,
that the glory of the latter house should transcend the glory of the former;^
footnote:[Hag. 2:9.]
which may be applied to this:
not one outward temple or house to excel another in outward lustre;
for where is the benefit of that?
But the divine glory, the beauty of holiness in the gospel house or church,
made up of renewed believers, should exceed the outward glory of Solomon`'s temple,
which in comparison of the latter days, was but flesh to spirit,
fading resemblance to the eternal substance.

But for all this, Christians have meeting-places, yet not in Jewish or Heathen state,
but plain, void of pomp or ceremony,
suiting the simplicity of their blessed life and doctrine.
For God`'s presence is not with the house, but with them that are in it,
who are the gospel church, and not the house.
O! that such as call themselves Christians, knew but a real sanctity in themselves,
by the washing of God`'s regenerating grace,
instead of that imaginary sanctity ascribed to places;
they would then know what the church is, and where, in these evangelical days,
is the place of God`'s appearance.
This made the prophet David say, "`The king`'s daughter is all glorious within;
her clothing is of wrought gold.`"
What is the glory that is within the true church,
and that gold that makes up that inward glory?
Tell me, O superstitious man! is it thy stately temples, altars, tables, carpets,
tapestries; thy vestments, organs, voices, candles, lamps, censers, plate, and jewels,
with the like furniture of thy worldly temples?
No such matter;
they bear no proportion with the divine adornment of the King of Heaven`'s daughter,
the blessed and redeemed church of Christ.
Miserable apostacy that it is! and a wretched supplement
in the loss and absence of the apostolic life,
the spiritual glory of the primitive church.

[.numbered]
VII.
But yet some of these admirers of external pomp and
glory in worship would be thought lovers of the cross,
and to that end have made to themselves many.
But alas! what hopes can there be of reconciling that to Christianity,
that the nearer it comes to its resemblance, the further off it is in reality?
for their very cross and self-denial are most unlawful self:
and whilst they fancy to worship God thereby,
they most dangerously err from the true cross of Christ,
and that holy abnegation that was of his blessed appointment.
It is true, they have got a cross, but it seems to be in the room of the true one:
and so mannerly, that it will do as they will have it that wear it;
for instead of mortifying their wills by it, they made it, and use it according to them.
So that the cross is become their ensign, that do nothing but what they list.
Yet by that they would be thought his disciples, who never did his own will,
but the will of his heavenly Father.

[.numbered]
VIII.
This is such a cross as flesh and blood can carry, for flesh and blood invented it;
therefore not the cross of Christ, that is to crucify flesh and blood.
Thousands of them have no more virtue than a chip: poor empty shadows,
not so much as images of the true one.
Some carry them for charms about them, but never repel one evil with them.
They sin with them upon their backs; and though they put them in their bosoms,
their beloved lusts lie there too, without the least disquiet.
They are as dumb as Elijah`'s mock gods;^
footnote:[1 Kings 18:27.]
no life nor power in them: and how should they, whose matter is earthly,
and whose figure and workmanship are but the invention and labour of worldly artists?
Is it possible that such crosses should mend their makers?
Surely not.

[.numbered]
IX. These are yokes without restraint, and crosses that never contradict:
a whole cart-load of them would leave a man as unmortified as they find him.
Men may sooner knock their brains out with them than their sins; and that, I fear,
too many of them know in their very consciences that use them, indeed adore them: and,
which can only happen to the false cross, are proud of them too,
since the true one leaves no pride, where it is truly borne.

[.numbered]
X+++.+++ For as their religion, so their cross is very gaudy and triumphant: but in what?
In precious metals and gems, the spoil of superstition upon the people`'s pockets.
These crosses are made of earthly treasure,
instead of teaching their hearts that wear them to deny it: and like men,
they are respected by their finery.
A rich cross shall have many gazers and admirers: the mean in this, as other things,
are more neglected.
I could appeal to themselves of this great vanity and superstition.
O! how very short is this of the blessed cross of Jesus,
that takes away the sins of the world!

[.numbered]
XI. Nor is a recluse life, the boasted righteousness of some, much more commendable,
or one whit nearer to the nature of the true cross:
for if it be not unlawful as other things are, it is unnatural,
which true religion teaches not.
The Christian convent and monastery are within, where the soul is encloistered from sin.
And this religious house the true followers of Christ carry about with them,
who exempt not themselves from the conversation of the world,
though they keep themselves from the evil of the world in their conversation.
That is a lazy, rusty, unprofitable self-denial,
burdensome to others to feed their idleness; religious bedlams,
where people are kept lest they should do mischief abroad; patience per force;
self-denial against their will, rather ignorant than virtuous:
and out of the way of temptation, than content in it.
No thanks if they commit not what they are not tempted to commit.
What the eye views not, the heart craves not, as well as rues not.

[.numbered]
XII.
The cross of Christ is of another nature; it truly overcomes the world,
and leads a life of purity in the face of its allurements;
they that bear it are not thus chained up, for fear they should bite; nor locked up,
lest they should be stolen away: no, they receive power from Christ their captain,
to resist the evil, and do that which is good in the sight of God; to despise the world,
and love its reproach above its praise; and not only not to offend others,
but love those that offend them: though not for offending them.
What a world should we have if every body, for fear of transgressing,
should mew himself up within four walls!
No such matter;
the perfection of the Christian life extends to every
honest labour or traffic used among men.
This severity is not the effect of Christ`'s free spirit, but a voluntary,
fleshly humility: mere trammels of their own making and putting on,
without prescription or reason.
In all which it is plain they are their own lawgivers, and set their own rule, mulct,
and ransom: a constrained harshness, out of joint to the rest of the creation;
for society is one great end of it, and not to be destroyed for fear of evil;
but sin that spoils it, banished by a steady reproof,
and a conspicuous example of tried virtue.
True godliness does not turn men out of the world, but enables them to live better in it,
and excites their endeavours to mend it; not to hide their candle under a bushel,
but to set it upon a table in a candlestick.
Besides, it is a selfish invention; and that can never be the way of taking up the cross,
which the true cross is therefore taken up to subject.
But again, this humour runs away by itself, and leaves the world behind to be lost;
Christians should keep the helm, and guide the vessel to its port;
not meanly steal out at the stern of the world,
and leave those that are in it without a pilot, to be driven by the fury of evil times,
upon the rock or sand of ruin.
In fine, this sort of life, if taken up by young people, is commonly to cover idleness,
or to pay portions, to save the lazy from the pain of punishment,
or quality from the disgrace of poverty; one will not work, and the other scorns it;
if aged, a long life of guilt sometimes flies to superstition for a refuge,
and after having had its own will in other things,
would finish it in a wilful religion to make God amends.

[.numbered]
XIII.
But taking up the cross of Jesus is a more interior exercise:
it is the circumspection and discipline of the soul
in conformity to the divine mind therein revealed.
Does not the body follow the soul, not the soul the body?
Do not such consider, that no outward cell can shut up the soul from lust,
the mind from an infinity of unrighteous imaginations?
The thoughts of man`'s heart are evil, and that continually.
Evil comes from within, and not from without:
how then can an external application remove an internal cause;
or a restraint upon the body, work a confinement of the mind?
which is much less than without doors, for where there is least of action,
there is most time to think; and if those thoughts are not guided by a higher principle,
convents are more mischievous to the world than exchanges.
And yet retirement is both an excellent and needful thing;
crowds and throngs were not much frequented by the ancient holy pilgrims.

[.numbered]
XIV.
But then examine, O man, thy foundation, what it is, and who placed thee there;
lest in the end it should appear thou hast put an eternal cheat upon thy own soul.
I must confess I am jealous of the salvation of my own kind,
having found mercy with my heavenly Father.
I would have none to deceive themselves to perdition, especially about religion,
where people are most apt to take all for granted,
and lose infinitely by their own flatteries and neglect.
The inward,
steady righteousness of Jesus is another thing than all
the contrived devotion of poor superstitious man;
and to stand approved in the sight of God, excels that bodily exercise in religion,
resulting from the invention of men.
And the soul that is awakened and preserved by his holy power and spirit,
lives to Him in the way of his own institution, and worships Him in his own spirit,
that is, in the holy sense, life, and leadings of it:
which indeed is the evangelical worship.
Not that I would be thought to slight a true retirement:
for I do not only acknowledge but admire solitude.
Christ himself was an example of it: He loved and chose to frequent mountains, gardens,
and sea-sides.
It is requisite to the growth of piety,
and I reverence the virtue that seeks and uses it;
wishing there were more of it in the world: but then it should be free, not constrained.
What benefit to the mind, to have it for a punishment, and not for a pleasure?
Nay, I have long thought it an error among all sorts, that use not monastic lives,
that they have no retreats for the afflicted, the tempted, the solitary, and the devout,
where they might undisturbedly wait upon God, pass through their religious exercises,
and, being thereby strengthened, may, with more power over their own spirits,
enter into the business of the world again: though the less the better, to be sure.
For divine pleasures are found in a free solitude.

====
