== Chapter VI.

[.chapter-synopsis]
* 1+++.+++ But men of more refined belief and practice are yet concerned in this unlawful self about religion.
* 2+++.+++ It is the rise of the performance of worship God regards.
* 3+++.+++ True worship is only from a heart prepared by God`'s Spirit.
* 4+++.+++ The soul of man is dead without the divine breath of life, and so not capable of worshipping the living God.
* 5+++.+++ We are not to study what to pray for. How Christians should pray. The aid they have from God.
* 6+++.+++ The way of obtaining this preparation: it is by waiting, as David and others did of old, in holy silence, that their wants and supplies are best seen.
* 7+++.+++ The whole and the full think they need not this waiting, and so use it not; but the poor in spirit are of another mind, wherefore the Lord hears, and fills them with his good things.
* 8+++.+++ If there were not this preparation, the Jewish times would have been more holy and spiritual than the gospel; for even then it was required; much more now.
* 9+++.+++ As sin, so formality, cannot worship God: thus David, Isaiah, etc.
* 10+++.+++ God`'s own forms and institutions hateful to Him, unless his own Spirit use them; much more those of man`'s contriving.
* 11+++.+++ God`'s children ever met God in his way, not their own; and in his way they always found help and comfort. In Jeremiah`'s time it was the same; his goodness was manifested to his children that waited truly upon him: it was an inward sense and enjoyment of him they thirsted after. Christ charged his disciples also to wait for the Spirit.
* 12+++.+++ This doctrine of waiting further opened, and ended with an allusion to the pool of Bethesda; a lively figure of inward waiting and its blessed effects.
* 13+++.+++ Four things necessary to worship; the sanctification of the worshipper, and the consecration of the offering, and the thing to be prayed for, and lastly, faith to pray in: and all must be right, that is, of God`'s giving.
* 14+++.+++ The great power of faith in prayer; witness the importunate woman. The wicked and formal ask, and receive not; the reason why. But Jacob and his true offspring, the followers of his faith, prevail.
* 15+++.+++ This shows why Christ upbraided his disciples with their little faith. The necessity of faith. Christ works no good on men without it.
* 16+++.+++ This faith is not only possible now but necessary.
* 17+++.+++ What it is, further unfolded.
* 18+++.+++ Who the heirs of this faith are; and what were the noble works of it in the former ages of the just.

[.numbered-group]
====

[.numbered]
I+++.+++ But there be others of a more refined speculation, and reformed practice,
who dare not use, and less adore, a piece of wood or stone, an image of silver and gold;
nor yet allow of that Jewish, or rather Pagan pomp in worship, practised by others,
as if Christ`'s worship were of this world, though his kingdom be of the other,
but are doctrinally averse to such superstition,
and yet refrain not to bow to their own religious duties,
and esteem their formal performance of several parts of
worship that go against the grain of their fleshly ease,
and a preciseness therein, no small cross unto them;
and that if they abstain from gross and scandalous sins, or if the act be not committed,
though the thoughts of it are embraced, and that it has a full career in the mind,
they hold themselves safe enough within the pale of discipleship and walls of Christianity.
But this also is too mean a character of the discipline of Christ`'s cross:
and those that flatter themselves with such a sort of taking it up,
will in the end be deceived with a sandy foundation, and a midnight cry.
For said Christ, "`But I say unto you, that every idle word that men shall speak,
they shall give an account thereof in the day of judgment.`"^
footnote:[Matt. 12:36.]

[.numbered]
II. For first, it is not performing duties of religion,
but the rise of the performance that God looks at.
Men may, and some do, cross their own wills in their own wills:
voluntary omission and commission: "`Who has required this at your hands?`"^
footnote:[Isa. 1:12.]
said the Lord of old to the Jews, when they seemed industrious to have served him;
but it was in a way of their own contriving or inventing, and in their own time and will;
not with the soul truly touched and prepared by the divine power of God,
but bodily worship only: that, the apostle tells us, profits little.
Not keeping to the manner of taking up the cross in worship as well as other things,
has been a great cause of the troublesome superstition that is yet in the world.
For men have no more brought their worship to the test, than their sins: nay less;
for they have ignorantly thought the one a sort of excuse for the other;
and not that their religious performances should need a cross, or an apology.

[.numbered]
III.
But true worship can only come from a heart prepared by the Lord.^
footnote:[Prov. 16:1; Rom. 8:14.]
This preparation is by the sanctification of the Spirit; by which,
if God`'s children are led in the general course of their lives, as Paul teaches,
much more in their worship to their Creator and Redeemer.
And whatever prayer be made, or doctrine be uttered,
and not from the preparation of the Holy Spirit, it is not acceptable with God:
nor can it be the true evangelical worship, which is in spirit and truth; that is,
by the preparation and aid of the Spirit.
For what is a heap of the most pathetical words to God Almighty;
or the dedication of any place or time to him?
He is a Spirit, to whom words, places, and times, strictly considered,
are improper or inadequate.
And though they be the instruments of public worship, they are but bodily and visible,
and cannot carry our requests any further, much less recommend them to the invisible God;
by no means; they are for the sake of the congregation:
it is the language of the soul God hears, nor can that speak but by the Spirit,
or groan aright to Almighty God without the assistance of it.

[.numbered]
IV. The soul of man, however lively in other things, is dead to God,
till He breathe the spirit of life into it: it cannot live to Him, much less worship Him,
without it.
Thus God tells us, by Ezekiel, when in a vision of the restoration of mankind,
in the person of Israel, an usual way of speaking among the prophets,
and as often mistaken, "`I will open your graves,`" saith the Lord,
"`and put my Spirit in you, and you shall live.`"^
footnote:[Ezek. 37:12-14.]
So, though Christ taught his disciples to pray, they were, in some sort,
disciples before he taught them; not worldly men,
whose prayers are an abomination to God.
And his teaching them is not an argument that every body must say that prayer,
whether he can say it with the same heart, and under the same qualifications,
as his poor disciples or followers did, or not;
as is now too superstitiously and presumptuously practised; but rather as they then,
so we now, are not to pray our own prayers, but his: that is,
such as He enables us to make, as He enabled them then.

[.numbered]
V+++.+++ For if we are not to take thought what we shall say when we come before worldly princes,
because it shall then be given us; and that "`it is not we that speak,
but the Spirit of our heavenly Father that speaketh in us;`"^
footnote:[Matt. 10:19-20.]
much less can our ability be needed,
or ought we to study to ourselves forms of speech
in our approaches to the great Prince of princes,
King of kings, and Lord of lords.^
footnote:[Matt.
vi.]
For be it his greatness, we ought not by Christ`'s command;
be it our relation to him as children, we need not; he will help us, he is our Father;
that is, if he be so indeed.
Thus not only the mouth of the body but of the soul is shut, till God opens it;
and then he loves to hear the language of it.
In which the body ought never to go before the soul: his ear is open to such requests,
and his Spirit strongly intercedes for those that offer them.

[.numbered]
VI. But it may be asked, how shall this preparation be obtained?

[.discourse-part]
I answer: By waiting patiently, yet watchfully and intently upon God:
"`Lord,`" says the Psalmist, "`thou hast heard the desire of the humble;
thou wilt prepare their heart, thou wilt cause thine ear to hear:`"^
footnote:[Ps. 10:17.]
and, says wisdom, "`The preparation of the heart in man is from the Lord.`"^
footnote:[Prov. 16:1.]
Here it is thou must not think thy own thoughts, nor speak thy own words,
which indeed is the silence of the holy cross,
but be sequestered from all the confused imaginations that are
apt to throng and press upon the mind in those holy retirements.
It is not for thee to think to overcome the Almighty by the most composed matter,
cast into the aptest phrase; no, no; one groan, one sigh, from a wounded soul,
a heart touched with true remorse, a sincere and godly sorrow,
which is the work of God`'s Spirit, excels and prevails with God.
Wherefore stand still in thy mind, wait to feel something that is divine,
to prepare and dispose thee to worship God truly and acceptably.
And thus taking up the cross,
and shutting the doors and windows of the soul against everything
that would interrupt this attendance upon God,
how pleasant soever the object be in itself, how lawful or needful at another season,
the power of the Almighty will break in, his Spirit will work and prepare the heart,
that it may offer up an acceptable sacrifice.
It is he that discovers and presses wants upon the soul; and when it cries,
it is he alone that supplies them.
Petitions, not springing from such a sense and preparation, are formal and fictitious:
they are not true; for men pray in their own blind desires, and not in the will of God;
and his ear is stopped to them: "`but for the oppression of the poor,
for the sighing of the needy,`" God hath said, "`I will arise;`"^
footnote:[Ps. 12:5.]
that is, the poor in spirit, the needy soul, those that want his assistance,
who are ready to be overwhelmed, that feel a need, and cry aloud for a deliverer,
and that have none on earth to help: none in heaven but Him,
nor in the earth in comparison of Him: "`He will deliver,`" said David,
"`the needy when he cries, and the poor, and him that has no helper.`"
He shall redeem their soul from deceit and violence,
and precious shall their blood be in His sight.^
footnote:[Ps. 72:12,14.]
"`This poor man,`" says he, "`cried, and the Lord heard him,
and saved him out of all his troubles.`"^
footnote:[Ps. 34:6-8.]
"`The angel of the Lord encampeth round about them that fear him,
and delivers them,`" and then invites all to come and taste how good the Lord is; "`yea,
He will bless them that fear the Lord, both small and great.`"^
footnote:[Ps. 115:13.]

[.numbered]
VII.
But what is that to them that are not hungry?
"`They that be whole need not a physician:`"^
footnote:[Matt. 9:12;]
the full have no need to sigh, nor the rich to cry for help.
Those that are not sensible of their inward wants,
that have not fears and terrors upon them, who feel no need of God`'s power to help them,
nor of the light of his countenance to comfort them, what have such to do with prayer?
their devotion is but at best, a serious mockery of the Almighty.
They know not, they want not, they desire not what they pray for.
They pray the will of God may be done, and do constantly their own:
for though it be soon said, it is a most terrible thing to them.
They ask for grace, and abuse that they have: they pray for the Spirit,
but resist it in themselves, and scorn at it in others:
they request mercies and goodness of God, and feel no real want of them.
And in this inward insensibility, they are as unable to praise God for what they have,
as to pray for what they have not.
"`They shall praise the Lord,`" says David, "`that seek him:
for he satisfieth the longing soul, and filleth the hungry with good things.`"^
footnote:[Ps. 22:26; cvii.
9.]
This also he reserves for the poor and needy, and those that fear God.
"`Let the (spiritually) poor and the needy praise thy name: ye that fear the Lord,
praise him; and ye the seed of Jacob, glorify him.`"^
footnote:[Ps. 74:21. Ps. 22:23.]
Jacob was a plain man, of an upright heart: and they that are so, are his seed.
And though (with him) they may be as poor as worms in their own eyes,
yet they receive power to wrestle with God, and prevail as he did.

[.numbered]
VIII.
But without the preparation and consecration of this power,
no man is fit to come before God;
else it were matter of less holiness and reverence to worship God under the gospel,
than it was in the times of the law, when all sacrifices were sprinkled before offered;
the people consecrated that offered them,
before they presented themselves before the Lord.^
footnote:[Numb.
viii.
xix; 2 Chron. 29:36; xxx.
16-17.]
If the touching of a dead or unclean beast then made people unfit for temple or sacrifice,
yea, society with the clean, till first sprinkled and sanctified,
how can we think so meanly of the worship that is instituted by Christ in gospel times,
as that it should admit of unprepared and unsanctified offerings?
Or, allow that those, who either in thoughts, words, or deeds,
do daily touch that which is morally unclean, can, without coming to the blood of Jesus,
that sprinkles the conscience from dead works, acceptably worship the pure God:
it is a downright contradiction to good sense:
the unclean cannot acceptably worship that which is holy;
the impure that which is perfect.
There is a holy intercourse and communion betwixt Christ and his followers;
but none at all betwixt Christ and Belial;
between him and those that disobey his commandments,
and live not the life of his blessed cross and self-denial.^
footnote:[2 Cor. 6:15-16.]

[.numbered]
IX. But as sin, so formality cannot worship God; no,
though the manner were of his own ordination.
Which made the prophet, personating one in a great strait, cry out,
"`Wherewith shall I come before the Lord, and bow myself before the high God?
shall I come before him with burnt offerings, with calves of a year old?
will the Lord be pleased with thousands of rams, or with ten thousands of rivers of oil?
shall I give my first-born for my transgression,
the fruit of my body for the sin of my soul?
He hath showed, thee, O man, what is good; and what doth the Lord require of thee,
but to do justly, to love mercy, and to walk humbly with thy God?`"^
footnote:[Micah 6:6-8.]
The royal prophet, sensible of this, calls thus also upon God; "`O Lord,
open thou my lips, and my mouth shall show forth thy praise.`"^
footnote:[Ps. 51:15-17.]
He did not dare open his own lips, he knew that could not praise God; and why?
"`for thou desirest not sacrifice,
else would I give it:`" if my formal offerings would serve, thou shouldst not want them;
thou delightest not in burnt-offerings.
"`The sacrifices of God are a broken spirit; a broken and a contrite heart, O God,
thou wilt not despise:`" and why?
because this is God`'s work, the effect of his power; and his own works praise him.
To the same purpose doth God himself speak by the mouth of Isaiah,
in opposition to the formalities and lip-worship of the degenerate Jews:
"`Thus saith the Lord, the heaven is my throne, and the earth is my footstool,
where is the house that ye build to me?
and where is the place of my rest?
For all these things hath my hand made.
But to this man will I look, even to him that is poor, and of a contrite spirit,
and trembleth at my word.`"^
footnote:[Isaiah 66:1-2.]
O behold the true worshipper! one of God`'s preparing, circumcised in heart and ear,
that resists not the Holy Spirit, as those lofty professing Jews did.
Was this so then, even in the time of the law,
which was the dispensation of external and shadowy performances:
and can we now expect acceptance without the preparation
of the Spirit of the Lord in these gospel times,
which are the proper times for the effusion of the Spirit?
By no means: God is what he was; and none else are his true worshippers,
but such as worship him in his own spirit: these he tenders as the apple of his eye;
the rest do but mock him, and he despises them.
Hear what follows to that people,
for it is the state and portion of Christendom at this day; "`He that killeth an ox,
is as if he slew a man; he that sacrificeth a lamb, as if he cut off a dog`'s neck;
he that offereth an oblation, as if he offered swine`'s blood; he that burneth incense,
as if he blessed an idol.
Yea, they have chosen their own ways, and their soul delighteth in their abominations.`"^
footnote:[Isaiah 66:3.]
Let none say, we offer not these kinds of oblations, for that is not the matter;
God was not offended with the offerings, but offerers.
These were the legal forms of sacrifice by God appointed;
but they not presenting them in that frame of spirit,
and under that right disposition of soul that was required, God declares his abhorrence,
and that with great aggravation; and elsewhere, by the same prophet,
forbids them to bring any more vain oblations before him; "`incense,`" saith God,
"`is an abomination to me: your sabbaths and calling of assemblies I cannot away with;
it is iniquity, even the solemn meeting.`"
And "`when you spread forth your hands, I will hide mine eyes from you;
when you make many prayers, I will not hear you.`"^
footnote:[Isaiah 1:13-18.]
A most terrible renunciation of their worship; and why?
Because their hearts were polluted; they loved not the Lord with their whole hearts,
but broke his law, and rebelled against his Spirit,
and did not that which was right in his sight.
The cause is plain, by the amendment He requires; "`Wash ye,`" says the Lord,
"`make you clean, put away the evil of your doings from before mine eyes:
cease to do evil, learn to do well: seek judgment, relieve the oppressed,
judge the fatherless, plead for the widow.`"
Upon these terms, and nothing short, He bids them come to Him, and tells them,
that "`though their sins be as scarlet, they shall be white as snow;
and though they be as crimson, they shall be white as wool.`"

So true is that notable passage of the Psalmist, "`Come and hear, all ye that fear God,
and I will declare what he hath done for my soul: I cried to him with my mouth,
and he was extolled with my tongue.
If I regard iniquity in my heart, the Lord will not hear me.
But verily God hath heard me: he hath attended to the voice of my prayer.
Blessed be God, who hath not turned away my prayer, nor his mercy from me.`"^
footnote:[Ps. 66:16,20.]

[.numbered]
X+++.+++ Much of this kind might be cited,
to show the displeasure of God against even his own forms of worship,
when performed without his own Spirit,
and that necessary preparation of the heart in man, that nothing else can work or give:
which above all other penmen of sacred writ,
is most frequently and emphatically recommended to us by the example of the Psalmist,
who ever and anon calling to mind his own great slips, and the cause of them,
and the way by which he came to be accepted of God,
and to obtain strength and comfort from him, reminds himself to wait upon God.
"`Lead me in thy truth, and teach me, for thou art the God of my salvation;
on thee do I wait all the day long.`"^
footnote:[Ps. 25:5.]
His soul looked to God for salvation,
to be delivered from the snares and evils of the world.
This shows an inward exercise, and a spiritual attendance,
that stood not in external forms, but in inward divine aid.

And truly, David had great encouragement so to do;
the goodness of God invited him to it and strengthened him in it.
For says he, "`I waited patiently for the Lord; and he inclined unto me, and heard my cry.
He brought me up also out of an horrible pit, out of the miry clay,
and set my feet upon a rock.`"^
footnote:[Ps. 40:1-2.]
That is, the Lord appeared inwardly to console David`'s soul, that waited for his help,
and to deliver it from the temptations and afflictions that were ready to overwhelm it,
and gave him security and peace.
Therefore, he says, "`The Lord hath established my goings;`" that is,
fixed his mind in righteousness.
Before, every step he took bemired him, and he was scarcely able to go without falling:
temptation on all hands; but he waited patiently upon God: his mind retired, watchful,
and intent to his law and Spirit; and he felt the Lord to incline to him.
His needy and sensible cry entered heaven, and prevailed;
then came deliverance and rescue to David, in God`'s time,
not David`'s strength to go through his exercises, and surmount all his troubles.
For which he tells us, a new song was put into his mouth, even praises to his God.^
footnote:[Ps. 40:3.]
But it was of God`'s making and putting, and not his own.

Another time, we have him crying thus: "`As the hart panteth after the water-brooks,
so panteth my soul after thee, O God.
My soul thirsteth for God, for the living God; when shall I come and appear before God?`"
This goes beyond formality, and can be tied to no lesson.
But we may by this see, that true worship is an inward work;
that the soul must be touched and raised in its heavenly desires by the heavenly Spirit,
and that the true worship is in God`'s presence.
When shall I come and appear?
Not in the temple, nor with outward sacrifices, but before God in his presence.
So that souls of true worshippers see God, make their appearance before him;
and this they wait, they pant, they thirst for.
O how is the greater part of Christendom degenerated from David`'s example!
No wonder therefore that this good man tells us,
"`Truly my soul waiteth upon God;`" and that he gives it in charge to his soul so to do;
"`O my soul, wait thou only upon God; for my expectation is from him.`"
As if he had said, None else can prepare my heart, or supply my wants;
so that my expectation is not from my own voluntary performance,
or the bodily worship I can give him; they are of no value; they can neither help me,
nor please him.
But I wait upon him for strength and power to present myself so before him,
as may be most pleasing to him;
for he that prepares the sacrifice will certainly accept it.
Wherefore in two verses he repeats it thrice;
"`I wait for the Lord--My soul doth wait--My soul waiteth
for the Lord more than they that watch for the morning.`"^
footnote:[Ps. 130:5-6.]
Yea, so intently, and with that unweariedness of soul, that he says in one place,
"`Mine eyes fail while I wait for my God.`"^
footnote:[Ps. 69:3.]
He was not contented with so many prayers, such a set worship, or limited repetition: no;
he leaves not till he finds the Lord, that is, the comforts of his presence:
which brings the answer of love and peace to his soul.
Nor was this his practice only, as a man more than ordinarily inspired;
for he speaks of it as the way of worship, then amongst the true people of God,
the spiritual Israel, and circumcision in heart, of that day: "`Behold,`" says he,
"`as the eyes of servants look unto the hand of their masters,
and as the eyes of a maiden unto the hand of her mistress,
so our eyes wait upon the Lord our God until he have mercy on us.`"^
footnote:[Ps. 123:2.]
In another place, "`Our soul waiteth for the Lord; he is our help and our shield.`"^
footnote:[Ps. 33:20.]
"`I will wait on thy name, for it is good before thy saints.`"^
footnote:[Ps. 52:9.]
It was in request with the truly godly in that day, and the way they came to enjoy God,
and worship him acceptably.
And from his own experience of the benefit of waiting upon God,
and the saints`' practice of those times, he recommends it to others:
"`Wait upon the Lord: be of good courage, and he will strengthen thy heart: wait, I say,
on the Lord.`"^
footnote:[Ps. 27:14.]
That is, wait in faith and patience, and he will come to save thee.
Again, "`Rest in the Lord, and wait patiently upon him.`"^
footnote:[Ps. 37:7.]
That is, cast thyself upon him; be contented, and wait for him to help thee in thy wants;
thou canst not think how near he is to help those that wait upon him:
O try and have faith.
Yet again, he bids us, "`Wait upon the Lord, and keep his way.`"^
footnote:[Ps. 37:34.]
Behold the reason why so few profit! they are out of his way;
and such can never wait rightly upon him.
Great reason had David for what he said,
who had with so much comfort and advantage met the Lord in his blessed way.

[.numbered]
XI. The prophet Isaiah tells us,
that though the chastisements of the Lord were sore upon the people for their backslidings,
yet in the way of his judgments, in the way of his rebukes and displeasure,
they waited for him, and the desire of their soul, that is the great point,
was to his name, and the remembrance of him.^
footnote:[Isaiah 26:8.]
They were contented to be chid and chastised, for they had sinned;
and the knowledge of him so was very desirable to them.
But what! did he not come at last, and that in mercy too?
Yes, he did, and they knew him when he came, a doctrine the brutish world knows not,
"`This is our God; we have waited for him, and he will save us.`"^
footnote:[Isaiah 25:9.]
O blessed enjoyment!
O precious confidence! here is a waiting in faith which prevailed.
All worship not in faith is fruitless to the worshipper, as well as displeasing to God:
and this faith is the gift of God, and the nature of it is to purify the heart,
and give such as truly believe victory over the world.
Well, but they go on: "`We have waited for him; we will be glad,
and rejoice in his salvation.`"^
footnote:[Isa. 25:9.]
The prophet adds, "`Blessed are all they that wait upon God:`" and why?
for "`they that wait upon the Lord shall renew their strength;`" they shall never faint,
never be weary:^
footnote:[Isaiah 30:18; xl.
31.]
the encouragement is great.
O hear him once more: "`For since the beginning of the world, men have not heard,
nor perceived by the ear, neither hath the eye seen, O God! besides thee,
what he hath prepared for him that waiteth for him.`"^
footnote:[Isaiah 64:4.]
Behold the inward life and joy of the righteous, the true worshippers;
those whose spirits bowed to the appearance of God`'s Spirit in them,
leaving and forsaking all it appeared against, and embracing whatever it led them to.
In Jeremiah`'s time, the true worshippers also waited upon God:^
footnote:[Jer. 14:22.]
and he assures us,
that "`The Lord is good to them that wait for them to the soul that seeketh him.`"^
footnote:[Lam. 3:25.]
Hence it is, that the prophet Hosea exhorts the church then to turn and wait upon God.
"`Therefore turn thou to thy God; keep mercy and judgment,
and wait on thy God continually.`"^
footnote:[Hos. 12:6.]

And Micah is very zealous and resolute in this good exercise:
"`I will look unto the Lord, I will wait for the God of my salvation;
my God will hear me.`"^
footnote:[Mic. 7:7.]
Thus did the children of the Spirit, that thirsted after an inward sense of him.
The wicked cannot say so; nor they that pray, unless they wait.
It is charged upon Israel in the wilderness,
as the cause of their disobedience and ingratitude to God,
that they waited not for his counsels.
We may be sure it is our duty, and expected from us; for God requires it in Zephaniah:
"`Therefore wait upon me, saith the Lord, until the day that I arise,`" etc.^
footnote:[Zeph. 3:8.]
O that all who profess the name of God, would wait so,
and not offer to arise to worship without him.
And they would feel his stirrings and arisings in them to help and prepare,
and sanctify them.
Christ expressly charged his disciples, "`They should not stir from Jerusalem,
but wait till they had received the promise of the Father,
the baptism of the Holy Ghost,`"^
footnote:[Acts 1:4,8.]
in order to their preparation for the preaching of
the glorious gospel of Christ to the world.
And though that were an extraordinary effusion for an extraordinary work,
yet the degree does not change the kind; on the contrary,
if so much waiting and preparation by the Spirit
was requisite to fit them to preach to man;
some, at least, may be needful to fit us to speak to God.

[.numbered]
XII.
I will close this great Scripture doctrine of waiting,
with that passage in John about the pool of Bethesda: "`There is at Jerusalem,
by the sheep-market, a pool, which is called in the Hebrew tongue Bethesda,
having five porches; in these lay a great multitude of impotent folks, of blind, halt,
and withered, waiting for the moving of the water.
For an angel went down at a certain season into the pool, and troubled the water:
whosoever then first after the troubling of the water, stepped in,
was made whole of whatsoever disease he had.`"^
footnote:[John 5:2-4.]
A most exact representation of what is intended by
all that has been said upon the subject of waiting.
For as there was then an outward and legal,
so there is now a gospel and spiritual Jerusalem, the church of God;
consisting of the faithful.
The pool in that old Jerusalem, in some sort, represented that fountain,
which is now set open in this new Jerusalem.
That pool was for those that were under infirmities of body;
this fountain for all that are impotent in soul.
There was an angel then that moved the water, to render it beneficial;
it is God`'s angel now, the great angel of his presence,
that blesseth this fountain with success.
They that then went in before, and did not watch the angel,
and take advantage of his motion, found no benefit of their stepping in:
those that now wait not the moving of God`'s angel,
but by the devotion of their own forming and timing, rush before God,
as the horse into the battle, and hope for success,
are sure to miscarry in their expectation.
Therefore, as then they waited with all patience and attention upon the angel`'s motion,
that wanted and desired to be cured; so do the true worshippers of God now,
that need and pray for his presence, which is the life of their souls,
as the sun is to the plants of the field.
They have often tried the unprofitableness of their own work,
and are now come to the sabbath indeed.
They dare not put up a device of their own, or offer an unsanctified request,
much less obtrude bodily worship,
where the soul is really insensible or unprepared by the Lord.
In the light of Jesus they ever wait to be prepared, retired,
and recluse from all thoughts that cause the least
distraction and discomposure in the mind,
till they see the angel move, and till their beloved please to awake:
nor dare they call him before his time.
And they fear to make a devotion in his absence;
for they know it is not only unprofitable, but reprovable:
"`Who has required this at your hands?`"
"`He that believes, makes not haste.`"^
footnote:[Isaiah 1:12; xxviii.
16.]
They that worship with their own, can only do as the Israelites,
turn their earrings into a molten image, and be cursed for their pains.
Nor fared they better, "`that gathered sticks of old, and kindled a fire,
and compassed themselves about with the sparks that they had kindled;`"^
footnote:[Isaiah 1:11.]
for God told them, "`they should lie down in sorrow.`"
It should not only be of no advantage, and do them no good,
but incur a judgment from him: sorrow and anguish of soul should be their portion.
Alas! flesh and blood would fain pray, though it cannot wait; and be a saint,
though it cannot abide to do or suffer the will of God; with the tongue it blesses God,
and with the tongue it curses men, made in his similitude.
It calls Jesus LORD, but not by the Holy Ghost; and often names the name of Jesus, yea,
bows the knee to it too; but departs not from iniquity: this is abominable to God.

[.numbered]
XIII.
In short, there are four things so necessary to worshipping God aright,
and which put its performance beyond man`'s power,
that there seems little more needed than the naming of them.
The first is, the sanctification of the worshipper.
Secondly, the consecration of the offering;
which has been spoken to before somewhat largely.
Thirdly, what to pray for; which no man knows that prays not by the aid of God`'s Spirit;
and therefore without that Spirit no man can truly pray.
This the apostle puts beyond dispute; "`We know not,`" says he, "`what we would pray for,
as we ought, but the Spirit helpeth our infirmities.`"^
footnote:[Rom. 8:26.]
Men unacquainted with the work and power of the Holy Spirit,
are ignorant of the mind of God; and those, certainly,
can never please him with their prayers.
It is not enough to know we want;
but we should learn whether it be not sent as a blessing, disappointments to the proud,
losses to the covetous, and to the negligent stripes; to remove these,
were to secure the destruction, not help the salvation of the soul.

The vile world knows nothing but carnally, after a fleshly manner and interpretation;
and too many that would be thought enlightened are
apt to call providences by wrong names,
for instance, afflictions they style judgments, and trials,
more precious than the beloved gold, they call miseries.
On the other hand, they call the preferments of the world by the name of honour,
and its wealth happiness; when for once that they are so,
it is much to be feared they are sent of God a hundred times for judgments,
at least trials, upon their possessors.
Therefore, what to keep, what to reject, what to want,
is a difficulty God only can resolve the soul.
And since God knows better than we what we need,
he can better tell us what to ask than we can him:
which made Christ exhort his disciples to avoid long and repetitious prayers;^
footnote:[Matt. 6:7-8.]
telling them that their heavenly Father knew what they needed before they asked:
and therefore gave them a pattern to pray by; not as some fancy,
to be a text for human liturgies,
which of all services are most justly noted and taxed for length and repetition;
but expressly to reprove and avoid them.
But if those wants that are the subject of prayer were once agreed upon,
though that might be a weighty point,
yet how to pray is of still greater moment than to pray; it is not the request,
but the frame of the petitioner`'s spirit.
The what may be proper, but the how defective.
As I said, God needs not to be told of our wants by us, who must tell them to us;
yet he will be told them from us, that both we may seek him, and he may come down to us.
But when this is done, "`To this man will I look, saith the Lord,
even to him that is poor, and of a contrite spirit, and that trembleth at my word:`"^
footnote:[Isaiah 66:2.]
to the sick heart, the wounded soul, the hungry and thirsty,
the weary and heavy laden ones: such sincerely want a helper.

[.numbered]
XIV.
Nor is this sufficient to complete gospel-worship; the fourth requisite must be had,
and that is faith; true faith, precious faith, the faith of God`'s chosen,
that purifies their hearts, that overcomes the world, and is the victory of the saints.^
footnote:[1 Tim. 1:5; Acts 15:9; Tit. 1:1; 2 Pet. 1:1; 1 John 5:4.]
This is that which animates prayer and presses it home, like the importunate woman,
that would not be denied; to whom Christ, seeming to admire, said, "`O woman,
great is thy faith!`"^
footnote:[Matt. 15:28.]
This is of the highest moment on our part, to give our addresses success with God;
and yet not in our power neither, for it is the gift of God: from him we must have it;
and with one grain of it more work is done, more deliverance is wrought,
and more goodness and mercy received, than by all the runnings, willings,
and toilings of man, with his inventions and bodily exercises: which, duly weighed,
will easily spell out the meaning,
why so much worship should bring so little profit to the world, as we see it does,
viz. true faith is lost.
"`They ask, and receive not; they seek, and find not: they knock,
and it is not opened unto them:`"^
footnote:[James 4:3.]
the case is plain; their requests are not mixed with purifying faith,
by which they should prevail, as good Jacob`'s were,
when he wrestled with God and prevailed.
And the truth is, the generality are yet in their sins, following hearts`' lusts,
and living in worldly pleasure, being strangers to this precious faith.
It is the reason rendered by the deep author to the Hebrews,
of the unprofitableness of the word preached to some in those days;
"`Not being,`" says he, "`mixed with faith in them that heard it.`"
Can the minister then preach without faith?
No: and much less can any man pray to purpose without faith, especially when we are told,
that "`the just live by faith.`"
For worship is the supreme act of man`'s life;
and whatever is necessary to inferior acts of religion must not be wanting there.

[.numbered]
XV. This may moderate the wonder in any,
why Christ so often upbraided his disciples with, O ye of little faith! yet tells us,
that one grain of it, though as little as that of mustard, one of the least of seeds,
if true and right, is able to remove mountains.
As if he had said, There is no temptation so powerful that it cannot overcome:
wherefore those that are captivated by temptations,
and remain unsupplied in their spiritual wants, have not this powerful faith:
that is the true cause.
So necessary was it of old,
that Christ did not many mighty works where the people believed not;
and though his power wrought wonders in other places, faith opened the way:
so that it is hard to say, whether that power by faith, or faith by that power,
wrought the cure.
Let us call to mind what famous things a little clay and spittle,
one touch of the hem of Christ`'s garment, and a few words out of his mouth,^
footnote:[John 9:6; Luke 8:47-48.]
did by the force of faith in the patients:
"`Believe ye that I am able to open your eyes?`"^
footnote:[Matt. 9:28.]
"`Yea, Lord,`" say the blind, and see.
To the ruler, "`only believe;`"^
footnote:[Matt. 9:23.]
he did, and his dead daughter recovered life.
Again, "`If thou canst believe:`" I do believe; says the father, help my unbelief:
and the evil spirit was chased away, and the child recovered.
He said to one, "`Go, thy faith hath made thee whole;`" and to another,
"`Thy faith hath saved thee; thy sins are forgiven thee.`"^
footnote:[Mark 10:52; Luke 7:48,50.]
And to encourage his disciples to believe,
that were admiring how soon his sentence was executed upon the fruitless fig-tree,
he tells them, "`Verily, if ye have faith, and doubt not, ye shall not only do this,
which is done to the fig-tree; but also, if ye shall say unto this mountain,
Be thou removed, and cast into the sea, it shall be done:
and all things whatsoever ye shall ask in prayer, believing, ye shall receive,`"^
footnote:[Matt. 21:20-22.]
This one passage convicts Christendom of gross infidelity; for she prays,
and receives not.

[.numbered]
XVI.
But some may say, It is impossible to receive all that a man may ask.
It is not impossible to receive all that a man, that so believes, can ask.
The fruits of faith are not impossible to those that
truly believe in the God that makes them possible.^
footnote:[Matt. 18:19; Luke 18:27.]
When Jesus said to the ruler, "`If thou canst believe,`" he adds,
"`all things are possible to him that believeth.`"^
footnote:[Matt. 19:26.]
Well, but then some will say, it is impossible to have such faith:
for this very faithless generation would excuse their want of faith,
by making it impossible to have the faith they want.
But Christ`'s answer to the infidelity of that age,
will best confute the disbelief of this.
"`The things that are impossible with men, are possible with God.`"^
footnote:[Matt. 19:24-26; Luke 18:25-27.]
It will follow then, that it is not impossible with God to give that faith;
though it is certain that without it it is impossible to please God:^
footnote:[Heb. 11:6.]
for so the author to the Hebrews teaches.
And if it be else impossible to please God,
it must be so to pray to God without this precious faith.

[.numbered]
XVII.
But some may say, What is this faith that is so necessary to worship,
and gives it such acceptance with God and returns that benefit to men?
I say, It is a holy resignation to God, and confidence in him,
testified by a religious obedience to his holy requirings,
which gives sure evidence to the soul of the things not yet seen,
and a general sense and taste of the substance of those things that are hoped for;
that is, the glory which is to be revealed hereafter.
As this faith is the gift of God, so it purifies the hearts of those that receive it.
The apostle Paul is witness, that it will not dwell but in a pure conscience:^
footnote:[1 Tim. 3:9.]
he therefore in one place couples a pure heart and faith unfeigned together: in another,
faith and a good conscience.^
footnote:[1 Tim. 1:5]
James joins faith with righteousness,^
footnote:[James, ii.]
and John with victory over the world; "`This,`" says be,
"`is the victory which overcomes the world, even our faith.`"^
footnote:[1 John 5:4.]

[.numbered]
XVIII.
The heirs of this faith are the true children of Abraham,^
footnote:[John 16:10-9.]
in that they walk in the steps of Abraham, according to the obedience of faith,
which only entitles people to be the children of Abraham.^
footnote:[Rom. 4:12.]
This lives above the world, not only in its sin, but righteousness: to this no man comes,
but through death to self by the cross of Jesus, and an entire dependence by him,
upon God.

Famous are the exploits of this divine gift; time would fail to recount them:
all sacred story is filled with them.
But let it suffice, that by it the holy ancients endured all trials,
overcame all enemies, prevailed with God, renowned his truth, finished their testimony,
and obtained the reward of the faithful, a crown of righteousness,
which is the eternal blessedness of the just.

====
