== Chapter VII.

[.chapter-synopsis]
* 1+++.+++ Of pride, the first capital lust; its rise.
* 2+++.+++ Its definition and distinction.
* 3+++.+++ That an inordinate desire of knowledge in Adam, introduced man`'s misery.
* 4+++.+++ He thereby lost his integrity.
* 5+++.+++ Knowledge puffs up.
* 6+++.+++ The evil effects of false, and the benefit of true knowledge.
* 7+++.+++ Cain`'s example a proof in the case.
* 8+++.+++ The Jews`' pride in pretending to be wiser than Moses, God`'s servant, in setting their post by God`'s post.
* 9+++.+++ The effect of which was the persecution of the true prophets.
* 10+++.+++ The divine knowledge of Christ brought peace on earth.
* 11+++.+++ Of the blind guides, the priests, and the mischief they have done.
* 12+++.+++ The fall of Christians, and the pride they have taken in it, hath exceeded the Jews; under the profession of their new-moulded Christianity, they have murdered the witness of the Lord Jesus.
* 13+++.+++ The angels sang peace on earth at the birth of the Lord of meekness and humility: but the pride of the Pharisees withstood and calumniated him.
* 14+++.+++ As Adam and the Jews lost themselves by their ambition, so the Christians losing the fear of God, grew creed and worship-makers, with this injunction, Conform or burn.
* 15+++.+++ The evil effects of this in Christendom, so called.
* 16+++.+++ The way of recovery out of such miserable defection.

[.numbered-group]
====

[.numbered]
I+++.+++ Having thus discharged my conscience against that part of unlawful self,
that fain would be a Christian, a believer, a saint,
whilst a plain stranger to the cross of Christ, and the holy exercises of it;
and in that briefly discovered what is true worship,
and the use and business of the holy cross therein,
to render its performance pleasing to Almighty God; I shall now,
the same Lord assisting me, more largely prosecute that other part of unlawful self,
which fills the study, care, and conversation of the world,
presented to us in these three capital lusts, that is to say, pride, avarice, and luxury;
from whence all other mischiefs daily flow, as streams from their proper fountains:
the mortifying of which makes up the other;
and indeed a very great part of the work of the true cross; and though last in place,
yet first in experience and duty: which done,
it introduces in the room of those evil habits,
the blessed effects of that so much needed reformation, to wit, "`mortification,
humility, temperance, love, patience, and heavenly-mindedness,`"^
footnote:[Gal. 5:22-23.]
with all other graces of the Spirit, becoming followers of the perfect Jesus,
that most heavenly man.

The care and love of all mankind are either directed to God or themselves.
Those that love God above all, are ever humbling self to his commands,
and only love self in subserviency to him that is Lord of all.
But those who are declined from that love to God, are lovers of themselves more than God:
for supreme love must centre in one of these two.
To that inordinate self-love, the apostle rightly joins proud and high-minded.^
footnote:[2 Tim. 3:2,4.]
For no sooner had the angels declined their love, duty and reverence to God,
than they inordinately loved and valued themselves; which made them exceed their station,
and aspire above the order of their creation.
This was their pride, and this sad defection their dismal fall;
who are reserved in chains of darkness unto the judgment of the great day of God.

[.numbered]
II. Pride, that pernicious evil, which begins this chapter,
did also begin the misery of mankind: a most mischievous quality;
and so commonly known by its motions and sad effects,
that every unmortified breast carries its definition in it.
However, I will say, in short, that pride is an excess of self-love,
joined with an undervaluing of others, and a desire of dominion over them:
the most troublesome thing in the world.
There are four things by which it hath made itself best known to mankind,
the consequences of which have brought a misery equal to its evil.
The first is, an inordinate pursuit of knowledge; the second,
an ambitious craving and seeking after power; the third,
an extreme desire of personal respect and deference:
the last excess is that of worldly furniture and ornaments.
To the just and true witness of the eternal God, placed in the souls of all people,
I appeal as to the truth of these things.

[.numbered]
III.
To the first, it is plain,
that an inordinate desire of knowledge introduced man`'s misery,
and brought an universal lapse from the glory of his primitive state.
Adam would needs be wiser than God had made him.
It did not serve his turn to know his Creator,
and give him that holy homage his being and innocency
naturally engaged and excited him too;
nor to have an "`understanding above all the beasts of the field, the fowls of the air,
and the fishes of the sea,`"^
footnote:[Gen. 2:19-29.]
joined with a power to rule over all the visible creation of God;
but he must be as wise as God too.
This unwarrantable search, and as foolish as unjust ambition,
made him unworthy of the blessings he received from God.
This drives him out of paradise; and instead of being lord of the whole world,
Adam becomes the wretchedest vagabond of the earth.

[.numbered]
IV. A strange change! that instead of being as gods,
they should fall below the very beasts;
in comparison of whom even God had made them as gods.
The lamentable consequence of this great defection,
has been an exchange of innocency for guilt, and a paradise for a wilderness.
But, which is yet worse,
in this state Adam and Eve had got another god than the only true and living God:
and he that enticed them to all this mischief, furnished them with a vain knowledge,
and pernicious wisdom: the skill of lies and equivocations, shifts, evasions,
and excuses.
They had lost their plainness and sincerity, and from an upright heart,
the image in which God had made man, he became a crooked, twining, twisting serpent;
the image of that unrighteous spirit, to whose temptations he yielded up,
with his obedience, his paradisaical happiness.

[.numbered]
V+++.+++ Nor is this limited to Adam; for all who have fallen short of the glory of God,
are right-born sons of his disobedience.
They, like him, have eaten of what they have been forbidden:
they have "`committed the things they ought not to have done,
and left undone the things they ought to have done.`"^
footnote:[Rom.
vii.]
They have sinned against that divine light of knowledge, which God has given them:
they have grieved his spirit: and that dismal sentence has been executed.
"`In the day that thou eatest thereof thou shalt die.`"^
footnote:[Gen. 2:17.]
That is, when thou doest the thing which thou oughtest not to do,
thou shalt no more live in my favour, and enjoy the comforts of the peace of my spirit;
which is a dying to all those innocent and holy desires and affections,
which God created man with: and he be comes as one cold and benumbed;
insensible of the love of God, of his Holy Spirit, power and wisdom;
of the light and joy of his countenance, and of the evidence of a good conscience,
and the co-witnessing and approbation of God`'s Holy Spirit.

[.numbered]
VI. So that fallen Adam`'s knowledge of God stood no more in a
daily experience of the love and work of God in his soul,
but in a notion of what he once did know and experience:
which being not the true and living wisdom that is from above, but a mere picture,
it cannot preserve man in purity; but puffs up, makes people proud, high-minded,
and impatient of contradiction.
This was the state of the apostate Jews before Christ came;
and has been the condition of apostate Christians ever since he came:
their religion standing, some bodily performances excepted,
either in what they once knew of the work of God in themselves,
and which they have revolted from; or in an historical belief,
and an imaginary conception and paraphrase upon the experiences
and prophecies of such holy men and women of God,
as in all ages have deserved the style and character of his true children.

[.numbered]
VII.
As such a knowledge of God cannot be true, so by experience we find,
that it ever brings forth the quite contrary fruits to the true wisdom.
For as this "`is first pure, then peaceable, gentle, and easy to be entreated;`"^
footnote:[James 3:17.]
so the knowledge of degenerated and unmortified men is first impure:
for it came by the commission of evil,
and is held in an evil and impure conscience in them that disobey God`'s laws,
and that daily do those things which they ought not to do;
and for which they stand condemned before God`'s judgment seat in the souls of men:
the light of whose presence searches the most hidden things of darkness,
the most secret thoughts, and concealed inclinations of ungodly men.
This is the science, falsely so called: and as it is impure, so it is unpeaceable, cross,
and hard to be entreated; froward, perverse, and persecuting;
jealous that any should be better than they, and hating and abusing those that are.

[.numbered]
VIII.
It was this pride made Cain a murderer:^
footnote:[Gen. 4:8.]
it is a spiteful quality; full of envy and revenge.
What! was not his religion and worship as good as his brother`'s?
He had all the exterior parts of worship;
he offered as well as Abel; and the offering of itself might be as good:
but it seems the heart that offered it was not.
So long ago did God regard the interior worship of the soul.
Well, what was the consequence of this difference?
Cain`'s pride stomached it: he could not bear to be outdone by his brother.
He grew wrathful,
and resolved to vindicate his offering by revenging
the refusal of it upon his brother`'s life:
and without any regard to natural affection, or the low and early condition of mankind,
he barbarously dyed his hands in his brother`'s blood.

[.numbered]
IX. The religion of the apostatized Jews did no better; for, having lost the inward life,
power, and spirit of the law, they were puffed up with that knowledge they had:
and their pretences to Abraham, Moses, and the promises of God, in that frame,
served only to blow them up into an insufferable pride, arrogancy, and cruelty.
For they could not bear true vision when it came to visit them;
and entertained the messengers of their peace as if they had been wolves and tigers.

[.numbered]
X+++.+++ Yea, it is remarkable, the false prophets, the great engineers against the true ones,
were ever sure to persecute them as false; and, by their interest with earthly princes,
or the poor seduced multitude, made them the instruments of their malice.
Thus it was, that one holy prophet was sawn asunder, another stoned to death, etc.
So proud and obstinate is false knowledge, and the aspirers after it;
which made holy Stephen cry out, "`Ye stiff-necked and uncircumcised in heart and ears,
ye do always resist the Holy Ghost: as did your fathers, so do ye.`"^
footnote:[Acts 7:51.]

[.numbered]
XI. The true knowledge came with the joy of angels, singing, "`Peace on earth,
and good-will towards men;`"^
footnote:[Luke 2:14.]
the false knowledge entertained the message with calumnies:
Christ must needs be an impostor; and that must prove him so, to wit,
his power of working miracles; which was that which proved the contrary.
They frequently sought to kill him: which at last they wickedly accomplished.
But what was the chief motive to it?
Why, he cried out against their hypocrisy, the broad phylacteries,
the honour they sought of men.
To be short, they give the reason themselves in these words: If we let him thus alone,
all men will believe on him:^
footnote:[John 11:48.]
that is, he will take away our credit with the people; they will adhere to him,
and desert us; and so we shall lose our power and reputation with the multitude.

[.numbered]
XII.
And the truth is, he came to level their honour, to overthrow their Rabbiship,
and by his grace to bring the people to that inward knowledge of God, which they,
by transgression, were departed from;
that so they might see the deceitfulness of their blind guides,
who by their vain traditions had made void the righteousness of the law:
and who were so far from being the true doctors and lively expounders of it,
that in reality they were the children of the devil,
who was a proud liar and cruel murderer from the beginning.

[.numbered]
XIII.
Their pride in false knowledge having made them incapable
of receiving the simplicity of the gospel,
Christ thanks his Father, that he had hid the mysteries of it from the wise and prudent,
and revealed them to babes.^
footnote:[Matt. 11:25.]
It was this false wisdom swelled the minds of the Athenians to that degree,
that they despised the preaching of the apostle Paul as a vain and foolish thing.
But that apostle who, of all the rest, had an education in the learning of those times,
bitterly reflects on that wisdom, so much valued by Jews and Greeks; "`Where,`" says he,
"`is the wise?
Where is the scribe?
Where is the disputer of this world?
Hath not God made foolish the wisdom of this world?`"^
footnote:[1 Cor. 1:20.]
And he gives a good reason for it, "`That no flesh should glory in his presence.`"^
footnote:[1 Cor. 1:29.]
Which is to say, God will stain the pride of man in false knowledge,
that he should have nothing on this occasion to be proud of:
it should be owing only to the revelation of the Spirit of God.
The apostle goes further, and affirms, "`That the world by wisdom knew not God:`"^
footnote:[1 Cor. 1:21.]
that is, it was so far from a help, that as men use it,
it was a hindrance to the true knowledge of God.
And in his first epistle to his beloved Timothy, he concludes thus:
"`O Timothy! keep that which is committed to thy trust,
avoiding profane and vain babblings, and oppositions of science, falsely so called.`"^
footnote:[Tim.
vi. 20.]
This was the sense of apostolical times,
when the divine grace gave the true knowledge of God, and was the guide of Christians.

[.numbered]
XIV.
Well, but what has been the success of those ages that followed the apostolical?
Any whit better than that of the Jewish times?
Not one jot.
They have exceeded them; as with their pretences to greater knowledge,
so in their degeneracy from the true Christian life:
for though they had a more excellent pattern than the Jews,
to whom God spoke by Moses his servant, he speaking to them by his beloved Son,
the express image of his substance, the perfection of all meekness and humility;
and though they seemed addicted to nothing more than an adoration of his name,
and a veneration for the memory of his blessed disciples and apostles,
yet so great was their defection from the inward
power and life of Christianity in the soul,
that their respect was little more than formal and ceremonious.
For notwithstanding they, like the Jews,
were mighty zealous in garnishing their sepulchres, and curious in carving their images;
not only keeping with pretence what might be the relics of their persons,
but recommending a thousand things as relics, which are purely fabulous,
and very often ridiculous, and to be sure altogether unchristian;
yet as to the great and weighty things of the Christian law, viz. love, meekness,
and self-denial, they were degenerated.
They grew high-minded, proud, boasters, without natural affection, curious,
and controversial, ever perplexing the church with doubtful questions;
filling the people with disputations, strife, and wrangling, drawing them into parties,
till at last they fell into blood:
as if they had been the worse for being once Christians.

O the miserable state of these pretended Christians!
that instead of Christ`'s and his apostles`' doctrine,
of loving enemies, and blessing them that curse them, they should teach the people,
under the notion of Christian zeal, most inhumanly to butcher one another;
and instead of suffering their own blood to be shed for the testimony of Jesus,
they should shed the blood of the witnesses of Jesus for heretics.
Thus that subtle serpent, or crafty evil spirit, that tempted Adam out of innocency,
and the Jews from the law of God, has beguiled the Christians, by lying vanities,
to depart from the Christian law of holiness, and so they are become slaves to him;
for he rules in the hearts of the children of disobedience.

[.numbered]
XV. And it is observable, that as pride,
which is ever followed by superstition and obstinacy,
put Adam upon seeking a higher station than God placed him in; and as the Jews,
out of the same pride, to outdo their pattern, given them of God by Moses upon the mount,
taught for doctrines their own traditions,
insomuch that those that refused conformity to them, ran the hazard of Crucify, crucify:
so the nominal Christians, from the same sin of pride,
with great superstition and arrogance, have introduced,
instead of a spiritual worship and discipline,
that which is evidently ceremonious and worldly;
with such innovations and traditions of men as are
the fruit of the wisdom that is from below;
witness their numerous and perplexed councils and creeds, with Conform or burn,
at the end of them.

[.numbered]
XVI.
And as this unwarrantable pride set them first at work,
to pervert the spirituality of the Christian worship,
making it rather to resemble the shadowy religion of the Jews,
and the gaudy worship of the Egyptians,
than the great plainness and simplicity of the Christian institution,
which is neither to resemble that of the mountain, nor the other of Jerusalem;
so has the same pride and arrogancy spurred them on,
by all imaginable cruelties to maintain this great Diana of theirs.
No meek supplications, nor humble remonstrances,
of those that kept close to primitive purity in worship and doctrine,
could prevail with these nominal Christians to dispense
with the imposition of their unapostolical traditions;
but as the ministers and bishops of these degenerate Christians
left their painful visitation and care over Christ`'s flock,
and grew ambitious, covetous, and luxurious, resembling rather worldly potentates,
than the humble-spirited and mortified followers of the blessed Jesus;
so almost every history tells us, with what pride and cruelty, blood and butchery,
and that with unusual and exquisite tortures,
they have persecuted the holy members of Christ out of the world;
and that upon such anathemas, as far as they could,
they have disappointed them of the blessing of heaven too.
These, true Christians call martyrs; but the clergy, like the persecuting Jews,
have styled them blasphemers and heretics;
in which they have fulfilled the prophecy of our Lord Jesus Christ, who did not say,
that they should think they do the gods good service to kill the Christians,
his dear followers, which might refer to the persecutions of the idolatrous Gentiles;
but that they should think they do God good service to kill them:^
footnote:[John 16:2.]
which shows, that they should be such as professedly owned the true God,
as the apostate Christians have all along pretended to do.
So that they must be those wolves, that the apostle foretold,
should arise out of themselves, and worry the flock of Christ,^
footnote:[Acts 20:29.]
after the great falling away should commence, that was foretold by him,
and made necessary, in order to the proving of the faithful,
and the revelation of the great mystery of iniquity.

I shall conclude this head with this assertion, that it is too undeniable a truth,
where the clergy have been most in power and authority,
and have had the greatest influence upon princes and states,
there have been most confusions, wrangles, bloodshed, sequestrations, imprisonments,
and exiles: to the justifying of which I call the testimony of the records of all times.
How it is in our age I leave to the experience of the living;
yet there is one demonstration that can hardly fail us; the people are not converted,
but debauched, to a degree that time will not allow us an example.
The worship of Christendom is visible, ceremonious, and gaudy; the clergy,
ambitious of worldly preferments, under the pretence of spiritual promotion;
making the earthly revenues of churchmen much the reason of their function;
being almost ever sure to leave the present smaller livings,
to solicit and obtain benefices of larger title and income.
So that with their pride and avarice, which good old Peter foresaw would be their snares,
they have drawn after them ignorance, misery, and irreligion upon Christendom.

[.numbered]
XVII.
The way of recovery from this miserable defection
is to come to a saving knowledge of religion;
that is, an experience of the divine work of God in the soul:
to obtain which be diligent to obey the grace that appears in thy soul,
O man! that brings salvation;^
footnote:[Tit. 2:11-2-12, 14.]
it turns thee out of the broad way into the narrow way; from thy lusts to thy duty;
from sin to holiness; from Satan to God.
Thou must see and abhor self: thou must watch, and thou must pray, and thou must fast;
thou must not look at thy tempter, but at thy preserver; avoid ill company,
retire to thy solitudes, and be a chaste pilgrim in this evil world:
and thus thou wilt arrive at the knowledge of God and Christ,
that brings eternal life to the soul:
a well-grounded assurance from what a man feels and knows within himself:
such shall not be moved with evil tidings.

====
