== Chapter VIII.

1+++.+++ Pride craves power as well as knowledge.--2. The case of Korah,
etc. a proof.--3. Absalom`'s ambition confirms it.--4. Nebuchadnezzar`'s
does the like.--5. The history of Pisistratus,
// lint-disable invalid-characters "æ"
Alexander, Cæsar, etc. shows the same thing.--6. The Turks are a lively proof,
who have shed much blood to gratify pride for power.--7. The last ten years in
Christendom exceed in proof of this.--8. Ambition rests not in courts,
it finds room in private breasts too,
and spoils families and societies.--9. Their peace
is great that limit their desires by God`'s grace,
and having power, use it to the good of others.

I+++.+++ But let us see the next most common, eminent, and mischievous effect of this evil.
Pride does extremely crave power,
than which not one thing has proved more troublesome and destructive to mankind.
I need not labour myself much in evidence of this, since most of the wars of nations,
depopulation of kingdoms, ruins of cities,
with the slavery and misery that have followed,
both our own experience and unquestionable histories,
acquaint us to have been the effect of ambition, which is the lust of pride after power.

II. How specious soever might be the pretences of Korah, Dathan, and Abiram,
against Moses,
it was their emulation of his mighty power in the camp of
Israel that put them upon conspiracies and mutinies.
They longed for his authority, and their not having it was his crime:
for they had a mind to be the heads and leaders of the people.
The consequence of which was a remarkable destruction
to themselves and all their unhappy accomplices.

III.
Absalom, too,
was for the people`'s rights against the tyranny of his father and his king;^
footnote:[2 Sam.
xv.]
at least with this pretence he palliated his ambition;
but his rebellion showed he was impatient for power,
and that he resolved to sacrifice his duty as a son and
subject to the importunities of his restless pride;
which brought a miserable death to himself and an extraordinary slaughter upon his army.

IV. Nebuchadnezzar is a lively instance of the excessive lust of pride for power.
His successes and empire were too heady for him:
so much too strong for his understanding, that he forgot he did not make himself,
or that his power had a superior.
He makes an image, and all must bow to it, or be burnt.
And when Shadrach, Meshach, and Abednego refused to comply, "`Who,`" says he,
"`is that God that shall deliver you out of my hands?`"^
footnote:[Dan.
iii.]
And notwithstanding the convictions he had upon him,
at the constancy of those excellent men, and Daniel`'s interpretation of his dreams,
it was not long before the pride of his power had filled his heart, and then his mouth,
with this haughty question, "`Is not this great Babylon,
that I have built for the house of the kingdom, by the might of my power,
and for the honour of my majesty?`"^
footnote:[Dan. 4:30.]
But we are told, that while the words were in his mouth,
a voice from heaven rebuked the pride of his spirit,
and he was driven from the society of men, to graze among the beasts of the field.

V+++.+++ If we look into the histories of the world,
we shall find many instances to prove the mischief of this lust of pride.
I will mention a few of them for their sakes who have either not read or considered them.

Solon made Athens free by his excellent constitution of laws;
but the ambition of Pisistratus began the ruin of it before his eyes.
Alexander, not contented with his own kingdom, invaded others,
and filled with spoil and slaughter those countries he subdued:
and it was not ill said by the man, who, when Alexander accused him of piracy,
told him to his face that Alexander was the greatest pirate in the world.
// lint-disable invalid-characters "æ"
It was the same ambition that made Cæsar turn traitor to his masters,
and with their own army, put into his hand for their service, subdue them to his yoke,
and usurp the government;
which ended in the expulsion of freedom and virtue together in that commonwealth;
for goodness quickly grew to be faction in Rome;
and that sobriety and wisdom which ever rendered her senators venerable,
became dangerous to their safety:
insomuch that his successors hardly left one they did not kill or banish;
unless such as turned to be flatterers of their unjust acquisition,
and the imitators of their debauched manners.

VI. The Turks are a great proof to the point in hand, who to extend their dominion,
have been the cause of shedding much blood, and laying many stately countries waste.
And yet they are to be outdone by apostate Christians;
whose practice is therefore more condemnable, because they have been better taught:
they have had a master of another doctrine and example.
It is true, they call him Lord still, but they let their ambition reign:
they love power more than one another; and to get it kill one another;
though charged by him not to strike, but to love and serve one another.^
footnote:[Matt. 18:1 to 6; Mark 9:33 to 37.]
And, which adds to the tragedy,
all natural affection is sacrificed to the fury of this lust:
and therefore are stories so often stained with the murder of parents, children, uncles,
nephews, masters, etc.

VII.
If we look abroad into remoter parts of the world, we shall rarely hear of wars;
but in Christendom rarely of peace.
A very trifle is too often made a ground of quarrel here:
nor can any league be so sacred or inviolable that arts
shall not be used to evade and dissolve it to increase dominion.
No matter who, nor how many are slain, made widows and orphans,
or lose their estates and livelihoods; what countries are ruined;
what towns and cities spoiled:
if by all these things the ambitious can but arrive at their ends!
To go no further back than sixty years,
that little period of time will furnish us with many wars begun upon ill grounds,
and ended in great desolation.
Nay, the last twelve years of our time make as pregnant a demonstration
as we can furnish ourselves with from the records of any age.
It is too tedious, nor is it my business, to be particular:
it has been often well observed by others, and is almost known to all, I mean the French,
Spanish, German, English, and Dutch wars.

VIII.
But ambition does not only dwell in courts and senates:
it is too natural to every private breast to strain for power.
We daily see how much men labour their utmost wit and interest to be great,
to get higher places, or greater titles than they have,
that they may look bigger and be more acknowledged; take place of their former equals,
and so equal those that were once their superiors: compel friends,
and be revenged on enemies.
This makes Christianity so little loved of worldly men; its kingdom is not of this world;
and though they may speak it fair, it is the world they love:
that without uncharitableness we may truly say, People profess Christianity,
but they follow the world.
They are not for seeking the kingdom of heaven first, and the righteousness thereof,^
footnote:[Matt. 6:33.]
and to trust God with the rest;
but for securing to themselves the wealth and glory of this world,
and adjourning the care of salvation to a sick bed, and the extreme moments of life;
if yet they believe a life to come.

IX. To conclude this head; great is their peace,
who know a limit to their ambitious minds;
that have learned to be contented with the appointments and bounds of Providence:
that are not careful to be great; but, being great, are humble and do good.
Such keep their wits with their consciences, and, with an even mind,
can at all times measure the uneven world,
rest fixed in the midst of all its uncertainties,
and as becomes those who have an interest in a better, in the good time and will of God,
cheerfully leave this; when the ambitious, conscious of their evil practices,
and weighed down to their graves with guilt,
must go to a tribunal that they can neither awe nor bribe.
