== Chapter IX.

[.chapter-synopsis]
* 1+++.+++ The third evil effect of pride is love of honour and respect. Too many are guilty of it.
* 2+++.+++ It had like to have cost Mordecai dear. Great mischief has befallen nations on this account.
* 3+++.+++ The world is out in the business of true honour, as well as in that of true science.
* 4+++.+++ Reasons why the author, and the rest of the people he walks with, use not these fashions.
* 5+++.+++ The first is, the sense they had in the hour of their conviction, of the unsuitableness of them to the Christian spirit and practice, and that the root they came from was pride and self-love.
* 6+++.+++ Reproach could not move them from that sense and practice accordingly.
* 7+++.+++ They do it not to make sects, or for distinction.
* 8+++.+++ Nor yet to countenance formality, but passively let drop vain customs, and so are negative to forms.
* 9+++.+++ Their behaviour is a test upon the world.
* 10+++.+++ And this cross to the world a test upon them.
* 11+++.+++ The second reason against them is their emptiness.
* 12+++.+++ Honour in Scripture is not so taken as it is in the world. It is used for obedience.
* 13+++.+++ It is used for preferments.
* 14+++.+++ A digression about folly in a Scripture sense.
* 15+++.+++ Honour is used for reputation.
* 16+++.+++ Honour is also attributed to functions and capacities, by way of esteem.
* 17+++.+++ Honour is taken for help and countenance of inferiors.
* 18+++.+++ Honour is used for service and esteem to all states and capacities: honour all men.
* 19+++.+++ Yet there is a limitation, in a sense, to the righteous, by the Psalmist; to honour the godly, and contemn the wicked.
* 20+++.+++ Little of this honour found in the world`'s fashions.
* 21+++.+++ The third reason against them is, they moc and cheat people of the honour due to them.
* 22+++.+++ The author and his friends are for true honour.
* 23+++.+++ The fourth reason is, that if the fashions carried true honour in them, the debauched could honour men, which cannot be.
* 24+++.+++ The fifth reason is, that then men of spite, hypocrisy, and revenge, could pay honour, which is impossible.
* 25+++.+++ The sixth reason is drawn from the antiquity of true honour.
* 26+++.+++ The seventh reason is from the rise of the vain honour, and he teachers of it, wherein the clown, upon a comparison, excels the courtier for a man of breeding.
* 27+++.+++ The eighth reason against these honours is, that they may be had for money, which true honour cannot be.
* 28+++.+++ The ninth and last reason is, because the holy Scripture expressly forbids them to true Christians.
* 29+++.+++ As in the case of Mordecai.
* 30+++.+++ A passage between a bishop and the author in this matter.
* 31+++.+++ Likewise the case of Elihu in Job.
* 32+++.+++ Also the doctrine of Christ to his disciples.
* 33+++.+++ Paul against conforming to the world`'s fashions.
* 34+++.+++ Peter against fashioning ourselves according to the world`'s lusts.
* 35+++.+++ James against respect to persons.
* 36+++.+++ Yet Christians are civil and mannerly in a right way.
* 37+++.+++ But unlike the world in the nature of it, and motives to it.
* 38+++.+++ Testimonies in favour of our dissent and practice.

[.numbered-group]
====

[.numbered]
I+++.+++ The third evil effect of pride, is an excessive desire of personal honour and respect.

Pride, therefore loves power, that she might have homage,
and that every one may give her honour, and such as are wanting in that,
expose themselves to her anger and revenge.
And as pride, so this evil effect is more or less diffused through corrupt mankind;
and has been the occasion of great animosity, and mischief in the world.

[.numbered]
II. We have a pregnant instance in holy writ,
what malice and revenge proud man is capable of, when not gratified in this particular.
It had almost cost Mordecai his neck, and the whole people of the Jews their lives,
because he would not bow himself to Haman, who was a great favourite to king Ahasuerus.
And the practice of the world, even in our own age, will tell us,
that not striking a flag or sail, and not saluting certain ports or garrisons, yea,
less things have given rise to mighty wars between states and kingdoms,
to the expense of much treasure, but more blood.
The like has followed about the precedency of princes and their ambassadors.
Also the envy, quarrels, and mischiefs that have happened among private persons,
upon conceit that they have not been respected to their degree or quality among men,
without hat, knee, or title: to be sure, duels and murders not a few.
I was once myself in France^
footnote:[Which was before I professed the communion I am now of.]
set upon about eleven at night, as I was walking to my lodging,
by a person that waylaid me, with his naked sword in his hand,
who demanded satisfaction of me for taking no notice of him,
at a time when he civilly saluted me with his hat; though the truth was,
I saw him not when he did it.
I will suppose he had killed me, for he made several passes at me, or I, in my defence,
had killed him, when I disarmed him, as the earl of Crawford`'s servant saw, that was by;
I ask any man of understanding or conscience,
if the whole ceremony was worth the life of a man, considering the dignity of the nature,
and the importance of the life of man, both with respect to God his Creator, himself,
and the benefit of civil society.

[.numbered]
III.
But the truth is, the world, under its degeneracy from God,
is as much out of the way as to true honour and respect, as in other things;
for mere shows, and those vain ones, too,
are much of the honour and respect that are expressed in the world;
that a man may say concerning them, as the apostle speaks of science, that is,
they are honours and respects falsely so called;
having nothing of the nature of true honour and respect in them: but as degenerate men,
loving to be honoured, first devised them, so pride only loves and seeks them,
and is affronted and angry for want of them.
Did men know a true Christian state, and the honour that comes from above,
which Jesus teaches,^
footnote:[John 5:44.]
they would not covet these very vanities, much less insist upon them.

[.numbered]
IV. And here give me leave to set down the reasons more particularly, why I,
and the people with whom I walk in religious society, have declined, as vain and foolish,
several worldly customs and fashions of respect, much in request at this time of day:
and I beseech thee, reader, to lay aside all prejudice and scorn,
and with the meekness and inquiry of a sober and discreet mind,
read and weigh what may be here alleged in our defence: and if we are mistaken,
rather pity and inform, than despise and abuse our simplicity.

[.numbered]
V+++.+++ The first and most pressing motive upon our spirits,
to decline the practice of these present customs, pulling off the hat,
bowing the body or knee,
and giving people gaudy titles and epithets in our salutations and addresses,
was that savour, sight and sense of God, by his light and Spirit given us,
of the Christian world`'s apostacy from God,
and the cause and effects of that great and lamentable defection.
In the discovery of which the sense of our state came first before us,
and we were made to see him whom we pierced, and to mourn for it.
A day of humiliation overtook us,
and we fainted to that pleasure and delight we once loved.
Now our works went beforehand to judgment, and a thorough search was made,
and the words of the prophet became well understood by us;
"`Who can abide the day of his coming?
and who shall stand when he appears?`"
"`He is like a refiner`'s fire, and like fullers`' soap.`"^
footnote:[Mal. 3:2.]
And as the apostle said, "`If the righteous scarcely be saved,
where shall the ungodly and the sinner appear?`"^
footnote:[1 Peter 4:18.]
"`Wherefore,`" says the apostle Paul, "`knowing the terror of the Lord,
we persuade men:`"^
footnote:[2 Cor. 5:11.]
what to do?
To come out of the nature, spirit, lusts, and customs of this wicked world:
remembering that, as Jesus has said, "`For every idle word that man shall speak,
he shall give account thereof in the day of judgment.`"^
footnote:[Matt. 12:36.]

This concern of mind and dejection of spirit was visible to our neighbours;
and we are not ashamed to own, that the terrors of the Lord took such hold upon us,
because we had long, under a profession of religion, grieved God`'s Holy Spirit,
that reproved us in secret for our disobedience;
that as we abhorred to think of continuing in our old sins,
so we feared to use lawful things, lest we should use them unlawfully.
The words of the prophet were fulfilled on us:
"`Where fore do I see every man with his hands on his loins, as a woman in travail?`"^
footnote:[Jer. 30:6.]
Many a pang and throe have we had; our heaven seemed to melt away,
and our earth to be removed out of its place; and we were like men, as the apostle said,
upon whom the ends of the world were come.
God knows it was so in this day; the brightness of his coming to our souls discovered,
and the breath of his mouth destroyed every plant he had not planted in us.
He was a swift witness against every evil thought and every unfruitful work; and,
blessed be his name, we were not offended in him, or at his righteous judgments.
Now it was that a grand inquest came upon our whole life: every word, thought,
and deed was brought to judgment, the root examined, and its tendency considered.
"`The lust of the eye, the lust of the flesh, and the pride of life,`"^
footnote:[1 John 2:16.]
were opened to our view; the mystery of iniquity in us.
And by knowing the evil leaven, and its divers evil effects in ourselves,
how it had wrought, and what it had done,
we came to have a sense and knowledge of the states of others: and what we could not,
nay, we dare not let live and continue in ourselves,
as being manifested to us to proceed from an evil principle in the time of man`'s degeneracy,
we could not comply with in others.
Now this I say, and that in the fear and presence of the all-seeing, just God,
the present honours and respect of the world, among other things,
became burdensome to us: we saw they had no being in paradise,
that they grew in the night-time, and came from an ill root;
and that they only delighted a vain and ill mind,
and that much pride and folly were in them.

[.numbered]
VI. And though we easily foresaw the storms of reproach
that would fall upon us for our refusing to practise them;
yet we were so far from being shaken in our judgment,
that it abundantly confirmed our sense of them.
For so exalted a thing is man, and so loving of honour and respect,
even from his fellow creatures,
that so soon as in tenderness of conscience towards
God we could not perform them as formerly,
he became more concerned than for all the rest of our differences,
however material to salvation.
So that let the honour of God and our own salvation do as it will,
it was greater heresy and blasphemy to refuse him the homage of the hat,
and his usual titles of honour; to deny to pledge his healths,
or play with him at cards and dice, than any other principle we maintained:
for being less in his view, it seemed not so much in his way.

[.numbered]
VII.
And though it be frequently objected that we seek to set up outward forms of preciseness,
and that is but as a green ribbon, the badge of the party, the better to be known:
I do declare, in the fear of Almighty God,
that these are but the imaginations and vain constructions of insensible men,
that have not had that sense which the Lord hath given us,
of what arises from the right and the wrong root in man:
and when such censurers of our simplicity shall be inwardly
touched and awakened by the mighty power of God,
and see things as they are in their proper natures and seeds,
they will then know their own burden, and easily acquit us,
without the imputation of folly or hypocrisy herein.

[.numbered]
VIII.
To say that we strain at small things,
which becomes not people of so fair pretensions to liberty and freedom of spirit:
I answer with meekness, truth, and sobriety; first,
nothing is small that God makes matter of conscience to do, or leave undone.
Next as inconsiderable as they are made, by those that object upon us,
they are much set by; so greatly as for our not giving them to be beaten, imprisoned,
refused justice, etc.
To say nothing of the derision and reproach that
hath been frequently flung at us on this account.
So that if we had wanted a proof of the truth of our inward belief and judgment,
the very practice of them that opposed it would have abundantly confirmed us.
But let it suffice to us, that "`Wisdom is justified of her children:`"^
footnote:[Matt. 11:19.]
we only passively let fall the practice of what we
are taught to believe is vain and unchristian:
in which we are negative to forms: for we leave off, we do not set up forms.

[.numbered]
IX. The world is so set upon the ceremonious parts and outside of things,
that it has well beseemed the wisdom of God in all ages to bring forth
his dispensations with very different appearances to their settled customs;
thereby contradicting human inventions, and proving the integrity of his confessors.
Nay, it is a test upon the world: it tries what patience, kindness, sobriety,
and moderation they have:
if the rough and homely outside of truth stumble
not their minds from the reception of it,
whose beauty is within: it makes a great discovery upon them.
For he who refuses a precious jewel, because it is presented in a plain box,
will never esteem it to its value, nor set his heart upon keeping it;
therefore I call it a test,
because it shows where the hearts and affections of the people stick,
after all their great pretence to more excellent things.

[.numbered]
X+++.+++ It is also a mighty trial upon God`'s people,
in that they are put upon the discovery of their contradiction
to the customs generally received and esteemed in the world;
which exposes them to the wonder, scorn, and abuse of the multitude.
But there is a hidden treasure in it: it inures us to reproach,
it teaches us to despise the false reputation of the world,
and silently to undergo the contradiction and scorn of its votaries;
and finally with a Christian meekness and patience to overcome their injuries and reproaches.
Add to this; it weans thee of thy familiars; for being slighted of them as a ninny,
a fool, a frantic, etc. thou art delivered from a greater temptation;
and that is the power and influence of their vain conversation.
And last of all, it lists thee of the company of the blessed, mocked, persecuted JESUS:
to fight under his banner against the world, the flesh, and the devil:
that after having faithfully suffered with him in a state of humiliation,
thou mayst reign with him in a state of glorification: who glorifies his poor, despised,
constant followers with the glory he had with the Father before the world began.^
footnote:[John 17:5.]
This was the first reason of our declining to practise the before-mentioned honours,
respect, etc.

[.numbered]
XI. The second reason why we decline and refuse the present
use of these customs in our addresses and salutations,
is from the consideration of their very emptiness and vanity:
that there is nothing of true honour and respect in them, supposing them not to be evil.
And, as religion and worship are degenerated into form and ceremony,
and they not according to primitive practice neither, so is honour and respect too;
there being little of that in the world as well as of the other; and to be sure,
in these customs, none that is justifiable by Scripture or reason.

[.numbered]
XII.
In Scripture we find the word honour often and diversely used.
First for obedience: as when God saith, "`They that honour me;`"^
footnote:[1 Sam. 2:30.]
that is, that keep my commandments.
"`Honour the king;`"^
footnote:[1 Pet. 2:17.]
that is, obey the king.
"`Honour thy father and mother;`"^
footnote:[Ex. 20:12.]
that is, saith the apostle to the Ephesians,
"`Obey thy father and thy mother in the Lord, for that is right:`"^
footnote:[Eph. 6:1-2.]
take heed to their precepts and advice: presupposing always,
that rulers and parents command lawful things,
else they dishonour themselves to enjoin unlawful things;
and subjects and children dishonour their superiors and parents,
in complying with their unrighteous commands.
Also Christ uses this word so, when he says, "`I have not a devil,
but I honour my Father, and ye dishonour me;`"^
footnote:[John 8:49.]
that is, I do my Father`'s will in what I do, but you will not hear me;
you reject my counsel, and will not obey my voice.
It was not refusing hat and knee, nor empty trifles: no, it was disobedience;
resisting him that God had sent, and not believing in him.
This was the dishonour he taxed them with; using him as an impostor,
that God had ordained for the salvation of the world.
And of these dishonourers there are but too many at this day.
Christ has a saying to the same effect; "`That all men should honour the Son,
even as they honour the Father; and he that honoureth not the Son,
honoureth not the Father, which hath sent him:`"^
footnote:[John 5:23.]
that is, they that hearken not to Christ, and do not worship and obey him,
they do not hear, worship, nor obey God.
As they pretended to believe in God, so they were to have believed in him;
he told them so.
This is pregnantly manifested in the case of the centurion,
whose faith was so much commended by Christ; where,
giving Jesus an account of his honourable station, he tells him,
"`He had soldiers under his authority, and when he said to one, Go, he went; to another,
Come, he came; and to a third, Do this, he did it.`"^
footnote:[Luke 7:8.]
In this it was he placed the honour of his capacity, and the respect of his soldiers,
and not in hats and legs: nor are such customs yet in use amongst soldiers,
being effeminate, and unworthy of masculine gravity.

[.numbered]
XIII.
In the next place, honour is used for preferment to trust and eminent employments.
So the Psalmist, speaking to God: "`For thou hast crowned him with glory and honour:`"^
footnote:[Ps. 8:5.]
again, "`Honour and majesty hast thou laid on him;`"^
footnote:[Ps. 21:5.]
that is, God hath given Christ power over all his enemies,
and exalted him to great dominion.
Thus the wise man intimates, when he says,
"`The fear of the Lord is the instruction of wisdom, and before honour is humility.`"^
footnote:[Prov. 15:33.]
That is, before advancement or preferment is humility.
Further, he has this saying, "`As snow in summer, and as rain in harvest,
so honour is not seemly for a fool:`"^
footnote:[Prov. 26:1.]
that is, a fool is not capable of the dignity of trust, employment, or preferment:
they require virtue, wisdom, integrity, diligence, with which fools are unfurnished.
And yet if the respects and titles in use amongst us are to go for marks of honour,
Solomon`'s proverb will take place, and doubtless doth, upon the practice of this age,
that yields so much of that honour to a great many of Solomon`'s fools;
who are not only silly men, but wicked too; such as refuse instruction,
and hate the fear of the Lord;^
footnote:[Prov. 13:18;]
which only maketh one of his wise men.

[.numbered]
XIV.
And as virtue and wisdom are the same, so folly and wickedness.
Thus Shechem`'s lying with Dinah, Jacob`'s daughter, is called:^
footnote:[Gen. 34:7:]
so is the rebellion and wickedness of the Israelites in Joshua.^
footnote:[Josh. 7:15.]
The Psalmist expresses thus: "`My wounds stink, because of my foolishness:`"^
footnote:[Ps. 38:5.]
that is, his sin.
And, "`The Lord will speak peace to his saints, but let them not turn again to folly:`"^
footnote:[Ps. 85:8.]
that is, to evil.
"`His own iniquities,`" says Solomon, "`shall take the wicked himself,
and he shall be holden with the cords of his sins: he shall die without instruction,
and in the greatness of his folly he shall go astray.`"^
footnote:[Prov. 5:22-23.]
Christ puts foolishness with blasphemy, pride, theft, murders, adulteries, wickedness,
etc.^
footnote:[Mark 7:10-12.]
I was the more willing to add these passages,
to show the difference that there is between the mind of the Holy Ghost,
and the notion that those ages had of fools, that deserve not honour,
and that which is generally meant by fools and folly in our time;
that we may the better understand the disproportion there is between honour,
as then understood by the Holy Ghost, and those that were led thereby;
and the apprehension of it,
and the practice of those latter ages of professed Christians.

[.numbered]
XV. But honour is also taken for reputation, and it is so understood with us:
"`A gracious woman,`" says Solomon, "`retaineth honour;`"^
footnote:[Prov. 11:16.]
that is, she keeps her credit: and by her virtue, maintains her reputation,
of sobriety and chastity.
In another place, "`It is an honour for a man to cease from strife:`"^
footnote:[Prov. 20:3:]
that is, it makes for his reputation, as a wise and good man.
Christ uses the word thus, where he says, "`A prophet is not without honour,
save in his own country;`"^
footnote:[Matt. 13:57.]
that is, he has credit, and is valued, save at home.
The apostle to the Thessalonians has a saying to this effect:
"`That every one of you should know how to possess
his vessel in sanctification and honour:`"^
footnote:[1 Thess. 4:4.]
that is, in chastity and sobriety.
In all which nothing of the fashions by us declined
is otherwise concerned than to be totally excluded.

[.numbered]
XVI.
There is yet another use of the word honour in Scripture,
and that is to functions and capacities: as, "`An elder is worthy of double honour:`"^
footnote:[1 Tim. 5:17.]
that is, he deserves double esteem, love, and respect; being holy, merciful, temperate,
peaceable, humble, etc., especially one that labours in word and doctrine.
So Paul recommends Epaphroditus to the Philippians;
"`Receive him therefore in the Lord with all gladness, and hold such in reputation:`"^
footnote:[Phil. 2:29.]
as if he had said, Let them be valued and regarded by you in what they say and teach.
Which is the truest,
and most natural and convincing way of testifying respect to a man of God;
as Christ said to his disciples, "`If ye love me ye will keep my sayings.`"
Further, the apostle bids us, To honour widows indeed: that is,
such women who are of chaste lives and exemplary virtue are honourable.
Marriage is honourable too, with this proviso, that the bed be undefiled:^
footnote:[Heb. 13:4.]
so that the honour of marriage, is the chastity of the married.

[.numbered]
XVII.
The word honour, in the Scripture, is also used from superiors to inferiors.
Which is plain in the instance of Ahasuerus to Haman;
"`What shall be done to the man whom the king delighteth to honour?`"^
footnote:[Esther 6:6.]
Why, he mightily advanced him, as Mordecai afterwards.
And more particularly it is said, that "`the Jews had light, and gladness, and joy,
and honour:`"^
footnote:[Esther 8:16.]
that is, they escaped the persecution that was like to fall upon them,
and by the means of Esther and Mordecai, they enjoyed not only peace,
but favour and countenance too.
In this sense the apostle Peter advised Christian men "`To honour their wives:`"^
footnote:[1 Pet. 3:7.]
that is, to love, value, cherish, countenance, and esteem them,
for their fidelity and affection to their husbands,
for their tenderness and care over their children,
and for their diligence and circumspection in their families.
There is no ceremonious behaviour, or gaudy titles requisite to express this honour.
Thus God honours holy men: "`Them that honour me,`" says the Lord, "`I will honour;
and they that despise me shall be lightly esteemed:`"^
footnote:[1 Sam. 2:30.]
that is, I will do good to them, I will love, bless, countenance,
and prosper them that honour me, that obey me: but they that despise me,
that resist my Spirit, and break my law, they shall be lightly esteemed,
little set by or accounted of; they shall not find favour with God, nor righteous men.
And so we see it daily among men:
if the great visit or concern themselves to aid the poor; we say,
that such a great man did me the honour to come and see, or help me in my need.

[.numbered]
XVIII.
I shall conclude this with one passage more, and that is a very large, plain,
and pertinent one: "`Honour all men, and love the brotherhood:`"^
footnote:[1 Pet. 2:17.]
that is, love is above honour, and that is reserved for the brotherhood.
But honour, which is esteem and regard, that thou owest to all men; and if all,
then thy inferiors.
But why for all men?
Because they are the creation of God, and the most noble part of his creation too:
they are also thy own kind: be natural, and assist them with what thou canst;
be ready to perform any real respect, and yield them any good or countenance thou canst.

[.numbered]
XIX.
And yet there seems a limitation to the command, Honour all men,
in that passage of godly David, "`Who shall abide in thy tabernacle?
who shall dwell in thy holy hill?
he in whose eyes a vile person is contemned; but he honoureth them that fear the Lord.`"^
footnote:[Ps. 15:1,4.]
Here honour is confined and affixed to godly persons;
and dishonour made the duty of the righteous to the wicked,
and a mark of their being righteous, that they dishonour, that is,
slight or disregard them.
To conclude this Scripture inquiry after honour,
I shall contract the subject of it under three capacities, superiors, equals,
and inferiors: honour, to superiors is obedience; to equals, love; to inferiors,
countenance and help: that is honour after God`'s mind,
and the holy people`'s fashion of old.

[.numbered]
XX. But how little of all this is to be seen or had in a poor empty hat, bow, cringe,
or gaudy, flattering title, let the truth-speaking witness of God in all mankind judge.
For I must not appeal to corrupt, proud, and self-speaking man,
of the good or evil of those customs; that as little as he would render them,
are loved and sought by him, and he is out of humour and angry if he has them not.

This is our second reason why we refuse to practise
the accustomed ceremonies of honour and respect;
because we find no such notion or expression of honour and respect,
recommended to us by the Holy Ghost in the Scriptures of truth.

[.numbered]
XXI.
Our third reason for not using them as testimonies of honour and respect is,
because there is no discovery of honour or respect to be made by them:
it is rather eluding and equivocating it;
cheating people of the honour and respect that is due to them;
giving them nothing in the show of something.
There is in them no obedience to superiors, no love to equals,
no help or countenance to inferiors.

[.numbered]
XXII.
We are, we declare to the whole world, for true honour and respect; we honour the king,
our parents, our masters, our magistrates, our landlords, one another; yea, all men,
after God`'s way, used by holy men and women of old time:
but we refuse these customs as vain and deceitful;
not answering the end they are used for.

[.numbered]
XXIII.
But, fourthly, there is yet more to be said: we find that vain, loose,
and worldly people are the great lovers and practisers of them,
and most deride our simplicity of behaviour.
Now we assuredly know, from the sacred testimonies,
that those people cannot give true honour that live in a dishonourable spirit;
they understand it not; but they can give the hat and knee,
and that they are very liberal of, nor are any more expert at it.
This is to us a proof that no true honour can be testified by those customs,
which vanity and looseness love and use.

[.numbered]
XXIV.
Next to them I will add hypocrisy, and revenge too.
For how little do many care for each other!
Nay, what spite, envy, animosity, secret backbiting, and plotting one against another,
under the use of these idle respects; till passion, too strong for cunning,
breaks through hypocrisy into open affront and revenge!
It cannot be so with the Scripture honour: to obey, or prefer a man, out of spite,
is not usually done: and to love, help, serve, and countenance a person,
in order to deceive and be revenged of him, is a thing never heard of:
these admit of no hypocrisy nor revenge.
Men do not these things to palliate ill-will,
which are the testimonies of quite the contrary.
It is absurd to imagine it, because impossible to be done.

[.numbered]
XXV.
Our sixth reason is, that honour was from the beginning:
but hat-respects and most titles are of late:
therefore there was true honour before hats or titles;
and consequently true honour stands not in them.
And that which ever was the way to express true honour is the best way still;
and this the Scripture teaches better than dancing-masters can do.

[.numbered]
XXVI.
Seventhly, if honour consists in such-like ceremonies, then will it follow,
that they are most capable of showing honour who perform it most exactly,
according to the mode or fashion of the times; consequently,
that man hath not the measure of true honour,
from a just and reasonable principle in himself,
but by the means and skill of the fantastic dancing-masters of the times:
and for this cause it is we see that many give much
money to have their children learn their honours,
falsely so called.
And what doth this but totally exclude the poor country people; who, though they plough,
till, sow, reap, go to market, and in all things obey their justices, landlords, fathers,
and masters, with sincerity and sobriety, rarely use those ceremonies;
but if they do it is so awkwardly and meanly,
that they are esteemed by a court critic so ill favoured
as only fit to make a jest of and be laughed at:
but what sober man will not deem their obedience beyond the others`' vanity and hypocrisy?
This base notion of honour turns out of doors the true, and sets the false in its place.
Let it be further considered,
that the way or fashion of doing it is much more in the design of its performers,
as well as view of its spectators, than the respect itself.
Whence it is commonly said, He is a man of good mien; or,
She is a woman of exact behaviour.
And what is this behaviour but fantastic, cramped postures and cringings,
unnatural to their shape; and, if it were not fashionable,
ridiculous to the view of all people;
and is therefore to the Eastern countries a proverb.

[.numbered]
XXVII.
But yet, eighthly, real honour consists not in a hat, bow, or title,
because all these things may be had for money, for which reason,
how many dancing-schools, plays, etc. are there in the land,
to which youth is generally sent to be educated in these vain fashions!
Whilst they are ignorant of the honour that is of God,
and their minds are allured to visible things that perish;
and instead of remembering their Creator, are taken up with toys and fopperies;
and sometimes so much worse, as to cost themselves a disinheriting,
and their indiscreet parents grief and misery all their days.^
footnote:[Prov. 3:9.]
If parents would honour God in the help of his poor
with the substance they bestow on such an education,
they would find a far better account in the end.

[.numbered]
XXVIII.
But lastly, we cannot esteem bows, titles, and pulling off of hats, to be real honour,
because such-like customs have been prohibited by God, his Son,
and servants in days past.
This I shall endeavour to show by three or four express authorities.

[.numbered]
XXIX.
My first example and authority is taken from the story of Mordecai and Haman;
so close to this point,
that methinks it should at least command silence
to the objections frequently advanced against us.
Haman was first minister of state, and favourite to king Ahasuerus.
The text says, That the king set his seat above all the princes that were with him;
and all the king`'s servants bowed and reverenced Haman;
for the king had so commanded concerning him; but Mordecai, it seems, bowed not,
nor did him reverence.^
footnote:[Est. 3:1-2.]
This at first made ill for Mordecai; a gallows was prepared for him at Haman`'s command.
But the sequel of the story shows that Haman proved his own invention,
and ended his pride with his life upon it.
Well now, speaking as the world speaks,
and looking upon Mordecai without the knowledge of the success;
was not Mordecai a very clown, at least a silly, morose, and humorous man,
to run such a hazard for a trifle?
What hurt had it done him to have bowed to and honoured one the king honoured?
Did he not despise the king, in disregarding Haman?
Nay, had not the king commanded that respect; and are not we to honour and obey the king?
One would have thought he might have bowed for the king`'s sake,
whatever he had in his heart, and yet have come off well enough;
for that he bowed not merely to Haman, but to the king`'s authority; besides,
it was but an innocent ceremony.
But it seems Mordecai was too plain and stout,
and not fine and subtle enough to avoid the displeasure of Haman.

Howbeit, he was an excellent man: he feared God, and wrought righteousness.
And in this very thing also he pleased God, and even the king too, at last,
that had most cause to be angry with him: for he advanced him to Haman`'s dignity;
and if it could be to greater honour.
It is true, sad news first came; no less than destruction to Mordecai,
and the whole people of the Jews besides, for his sake:
but Mordecai`'s integrity and humiliation, his fasting,
and strong cries to God prevailed, and the people were saved,
and poor condemned Mordecai comes, after all, to be exalted above the princes,
whether in this or any other respect.
They that endure faithful in that which they are convinced God requires of them,
though against the grain and humour of the world and themselves too,
they shall find a blessed recompense in the end.
My brethren, remember the cup of cold water: "`We shall reap if we faint not.`"
And call to mind, that our Captain bowed not to him that told him,
"`If thou wilt fall down and worship me, I will give thee all the glory of the world:`"^
footnote:[Matt. 4:8-9.]
shall we bow then?
O no!
Let us follow our blessed Leader.

[.numbered]
XXX.
But before I leave this section, it is fit I add, that in conference with a late bishop,
and none of the least eminent, upon this subject and instance,
I remember he sought to evade it thus: "`Mordecai,`" says he, "`did not refuse to bow,
as it was a testimony of respect to the king`'s favourite; but he,
being a figure and type of Christ, refused, because Haman was of the uncircumcision,
and ought to bow to him rather.`"
To which I replied, That allowing Mordecai to be a figure of Christ,
and the Jews of God`'s people or church; and that as the Jews were saved by Mordecai,
so the church is saved by Christ; this makes for me; for then, by that reason,
the spiritual circumcision, or people of Christ,
are not to receive and bow to the fashions and customs of the spiritual uncircumcision,
who are the children of the world;
of which such as were condemnable so long ago in the time of the type and figure,
can by no means be justifiably received or practised
in the time of the antitype or substance itself.
On the contrary, this shows expressly, we are faithfully to decline such worldly customs,
and not to fashion ourselves according to the conversation of earthly-minded people;
but be renewed and changed in our ways, and keep close to our Mordecai;
who having not bowed, we must not bow, that are his people and followers.
And whatever be our sufferings or reproaches, they will have an end: Mordecai,
our captain, that appears for his people throughout all the provinces,
in the king`'s gate, will deliver us at last; and, for his sake,
we shall be favoured and loved of the king himself too.
So powerful is faithful Mordecai at last.
Therefore let us all look to Jesus, our Mordecai, the Israel indeed;
He that has power with God, and would not bow in the hour of temptation,
but has mightily prevailed; and therefore is a Prince forever,
and "`of his government there shall be no end.`"^
footnote:[Isa. 9:7.]

[.numbered]
XXXI.
The next Scripture instance I urge against these customs, is a passage in Job,
thus expressed: "`Let me not, I pray you, accept any man`'s person;
neither let me give flattering titles unto man, for I know not to give flattering titles;
in so doing, my Maker would soon take me away.`"^
footnote:[Job 32:21-22.]
The question that will arise upon the allegation of this Scripture is this,
viz. What titles are flattering?
The answer is as obvious, namely, Such as are empty and fictitious,
and make him more than he is: as to call a man what he is not, to please him;
or to exalt him beyond his true name, office, or desert, to gain upon his affections;
who, it may be, lusteth to honour and respect: such as these,--most excellent,
most sacred, your grace, your lordship, most dread majesty, right honourable,
right worshipful, may it please your majesty, your grace, your lordship, your honour,
your worship, and the like unnecessary titles and attributes,
calculated only to please and tickle poor, proud, vain, yet mortal man.
Likewise to call man what he is not, as my lord, my master, etc., and wise, just,
or good, when he is neither, only to please him, or show him respect.

It was familiar thus to do among the Jews, under their degeneracy;
wherefore one came to Christ, and said, "`Good master,
what shall I do to have eternal life?`"^
footnote:[Luke 18:18.]
It was a salutation or address of respect in those times.
It is familiar now: good my lord, good sir, good master, do this, or do that.
But what was Christ`'s answer?
how did he take it?
"`Why callest thou me good?`"
says Christ; "`there is none good, save one, that is God.`"^
footnote:[Luke 18:19.]
He rejected it that had more right to keep it than all mankind: and why?
Because there was one greater than he;
and that he saw the man addressed it to his manhood, after the way of the times,
and not to his divinity which dwelt within it: therefore Christ refuses it,
showing and instructing us that we should not give
such epithets and titles commonly to men;
for good being due alone to God and godliness,
it can only be said in flattery to fallen man, and therefore sinful to be so said.

This plain and exact life well became Him,
that was on purpose manifested to return and restore man from his lamentable degeneracy,
to the innocency and purity of his first creation;
who has taught us to be careful how we use and give
attributes unto man by that most severe saying,
"`That every idle word that man shall speak,
he shall give an account thereof in the day of judgment.`"^
footnote:[Matt. 12:3,6.]
And that which should warn all men of the latitude they take herein,
and sufficiently justifies our tenderness is this,
That man can scarcely commit greater injury and offence against Almighty God,
than to ascribe any of his attributes unto man, the creature of his word,
and the work of his hands.
He is a jealous God of his honour, and will not give his glory unto another.
Besides, it is so near the sin of the aspiring fallen angels,
that affected to be greater and better than they
were made and stated by the great Lord of all,
and to entitle man to a station above his make and orb,
looks so like idolatry (the unpardonable sin under the law) that
it is hard to think how men and women professing Christianity,
and seriously reflecting upon their vanity and evil in these things,
can continue in them, much less plead for them;
and least of all reproach and deride those that through
tenderness of conscience cannot use and give them.
It seems that Elihu did not dare to do it;
but put such weight upon the matter as to give this for one reason for his forbearance,
to wit, lest my Maker should soon take me away: that is,
for fear God should strike me dead, I dare not give man titles that are above him,
or titles merely to please him.
I may not, by any means, gratify that spirit which lusteth after such things.
God is to be exalted, and man abased.
God is jealous of man`'s being set higher than his station:
he will have him keep his place, know his original,
and remember the rock from whence he came: that what he has is borrowed;
not his own but his Maker`'s, who brought him forth and sustained him;
which man is very apt to forget:
and lest I should be accessory to it by flattering titles,
instead of telling him truly and plainly what he is,
and using them as he ought to be treated, and thereby provoke my Maker to displeasure,
and he in his anger and jealousy should take me soon away,
or bring sudden death and an untimely end upon me, I dare not use,
I dare not give such titles unto men.

[.numbered]
XXXII.
But if we had not this to allege from the Old Testament writings,
it should and ought to suffice with Christians,
that these customs are severely censured by the great Lord and Master of their religion;
who is so far from putting people upon giving honour one to another,
that he will not indulge them in it, whatever be the customs of the country they live in:
for he charges it upon the Jews as a mark of their apostasy;
"`How can ye believe which receive honour one of another,
and seek not the honour that cometh from God only?`"
where their infidelity concerning Christ is made the effect of seeking worldly,
and not heavenly honour only.
And the thing is not hard to apprehend,
if we consider that self-love and desire of honour from
men is inconsistent with the love and humility of Christ.
They sought the good opinion and respect of the world;
how then was it possible they should leave all and follow him,
whose kingdom is not of this world;
and that came in a way so cross to the mind and humour of it?
And that this was the meaning of our Lord Jesus is plain:
for he tells us what that honour was they gave and received, which he condemned them for,
and of which he bid the disciples of his humility and cross beware.
His words are these, and he speaks them not of the rabble but of the doctors,
the great men, the men of honour among the Jews: "`They love,`" says he,
"`the uppermost rooms at feasts,`"^
footnote:[Matt. 23:6.]
"`that is, places of greatest rank and respect; and greetings,`" that is,
salutations of respect, such as pulling off the hat, and bowing the body are in our age;
"`in the market-places,`"^
footnote:[Mark 12:38; Luke 11:43.]
viz. in the places of note and concourse, the public walks and exchanges of the country.
And lastly, "`they love,`" says Christ, "`to be called of men, Rabbi,
Rabbi:`" one of the most eminent titles among the Jews.
A word comprehending an excellency equal to many titles: it may stand for your grace,
your lordship, right reverend father, etc.
It is upon these men of breeding and quality that he pronounces his woes,
making these practices some of the evil marks by which to know them,
as well as some of the motives of his threatenings against them.
But he leaves it not here:
he pursues this very point of honour above all the rest in his caution to his disciples;
to whom he gave in charge thus: "`But be not ye called Rabbi; for one is your Master,
even Christ, and all ye are brethren.`"^
footnote:[Matt. 18:10-8-12.]
"`Neither be ye called Masters;
but he that is greatest amongst you shall be your servant:
and whoever shall exalt himself shall be abased.`"
Plain it is that these passages carry a severe rebuke, both to worldly honour in general,
and to those members and expressions of it in particular, which,
as near as the language of Scripture and customs of that age will permit,
do distinctly reach and allude to those of our own time;
for the declining of which we have suffered so much scorn and abuse,
both in our persons and estates; God forgive the unreasonable authors of it!

[.numbered]
XXXIII.
The apostle Paul has a saying of great weight and fervency, in his epistle to the Romans,
very agreeable to this doctrine of Christ; it is this:
"`I beseech you therefore brethren, by the mercies of God,
that ye present your bodies a living sacrifice, holy, acceptable unto God,
which is your reasonable service; and be not conformed to this world,
but be ye transformed by the renewing of your mind, that ye may prove what is that good,
that acceptable, and perfect will of God.`"^
footnote:[Rom. 12:1-2.]
He wrote to a people, in the midst of the ensnaring pomp and glory of the world.
// lint-disable invalid-characters "æ"
Rome was the seat of Cæsar, and the empire; the mistress of invention.
Her fashions, as those of France now, were as laws to the world, at least at Rome:
whence it is proverbial,

[verse]
____
// lint-disable invalid-characters "æ"
Cum fueris Romæ, Romano vivito more.

When thou art at Rome, thou must do as Rome does.
____

But the apostle is of another mind; he warns the Christians of that city,
that they be not conformed; that is,
that they do not follow the vain fashions and customs of this world, but leave them.
The emphasis lies upon this, as well as upon conformed; and it imports, that this world,
which they were not to conform to,
was the corrupt and degenerate condition of mankind in that age.
Wherefore the apostle proceeds to exhort those believers, and that by the mercies of God,
the most powerful and winning of all arguments, that they would be transformed; that is,
changed from the way of life customary among the Romans;
and prove what is that acceptable will of God.
As if he had said, Examine what you do and practise; see if it be right,
and that it please God; call every thought, word, and action to judgment;^
footnote:[John 3:21.]
try whether they are wrought in God or not; that so you may prove or know,
what is that good, and acceptable, and perfect will of God.

[.numbered]
XXXIV.
The next scripture authority we appeal to, in our vindication,
is a passage of the apostle Peter,
in his first epistle written to the believing strangers
throughout the countries of Pontus,
Galatia, Cappadocia, Asia, and Bithynia;
which were the churches of Christ Jesus in those parts of the world,
gathered by his power and spirit: it is this; "`Gird up the loins of your minds;
be sober and hope to the end,
for the grace that is to be brought unto you at the revelation of Jesus Christ;
as obedient children,
not fashioning yourselves according to the former lusts in your ignorance.`"^
footnote:[1 Pet. 1:13-14.]
That is, be not found in the vain fashions and customs of the world,
unto which you conformed in your former ignorance;
but as you have believed in a more plain and excellent way, so be sober and fervent,
and hope to the end: do not give out; let them mock on;
bear ye the contradiction of sinners constantly, as obedient children,
that you may receive the kindness of God, at the revelation of Jesus Christ.
And therefore does the apostle call them strangers, a figurative speech,
people estranged from the customs of the world, of new faith and manners;
and so unknown of the world: and if such strangers,
then not to be fashioned or conformed to their pleasing respects and honours,
whom they were estranged from:
because the strangeness lay in leaving that which
was customary and familiar to them before.
The following words, verse 17, prove he used the word strangers in a spiritual sense;
"`Pass the time of your sojourning here in fear;`" that is,
pass the time of your being as strangers on earth in fear;
not after the fashions of the world.
A word in the next chapter, further explains his sense, where he tells the believers,
that they are a peculiar people; to wit, a distinct,
a singular and separate people from the rest of the world:
not any longer to fashion themselves according to their customs.
But I do not know how that could be, if they were to live in communion with the world,
in its respects and honours;
for that is not to be a peculiar or separate people from them, but to be like them,
because conformable to them.

[.numbered]
XXXV.
I shall conclude my scripture testimonies against the foregoing respects,
with that memorable and close passage of the apostle James against
respect of persons in general after the world`'s fashion:
"`My brethren, have not the faith of our Lord Jesus Christ, the Lord of glory,
with respect of persons: for if there come unto your assembly a man with a gold ring,
in goodly apparel: and there come in also a poor man in vile raiment,
and ye have respect to him that weareth the gay clothing, and say unto him,
Sit thou here in a good place, (or well and seemly, as the word is;) and say to the poor,
Stand thou there, or sit here under my footstool; are ye not then partial in yourselves,
and are become judges of evil thoughts?`"^
footnote:[James 2:1-4.]
That is, they knew they did amiss: "`If ye fulfill the royal law,
according to the scripture, Thou shalt love thy neighbour as thyself, ye do well;
but if ye have respect to persons, ye commit sin,
and are convinced of the law as transgressors.`"^
footnote:[James 2:8-9.]
This is so full there seems nothing left for me to add, or others to object.
We are not to respect persons, that is the first thing: and the next thing is,
if we do we commit sin, and break the law; At our own peril be it.
And yet perhaps some will say, that by this we overthrow all distinction amongst men,
under their divers qualities,
and introduce a reciprocal and relational respect in the room of it: but if it be so,
I cannot help it, the apostle James must answer for it,
who has given us this doctrine for Christian and apostolical.
And yet one greater than he told his disciples, of whom James was one,
"`Ye know that the princes of the Gentiles exercise dominion over them, etc.
But it shall not be so among you; but whosoever will be chief among you,
let him be your servant.`"^
footnote:[Matt. 20:25-27.]
That is, he that affects rule, and seeks to be uppermost,
shall be esteemed least among you.
And to say true on the whole matter, whether we regard those early times of the world,
that were antecedent to the coming of Christ or soon after,
there was yet a greater simplicity than in the times in which we are fallen.
For those early times of the world, as bad as they were in other things,
were great strangers to the frequency of these follies: nay,
they hardly used some of them, at least very rarely.
For if we read the Scriptures, such a thing as my lord Adam, though lord of the world,
is not to be found: nor my lord Noah neither, the second lord of the earth:
nor yet my lord Abraham, the father of the faithful; nor my lord Isaac;
nor my lord Jacob; but much less is my lord Paul, etc. to be found in the Bible:
and less your holiness, or your grace.
Nay, among the Gentiles, the people wore their own names with more simplicity,
and used not the ceremony of speech that is now practised among Christians,
nor yet anything like it.
My lord Solon, my lord Phocion, my lord Plato, my lord Aristotle, my lord Scipio,
my lord Fabius, my lord Cato, my lord Cicero,
are not to be read in any of the Greek or Latin stories,
and yet they were some of the sages and heroes of those great empires.
No, their own names were enough to distinguish them from other men,
and their virtue and employments in the public service were their titles of honour.
Nor has this vanity yet crept far into the Latin writers,
where it is familiar for authors to cite the most learned and the most noble,
without any addition to their names, unless worthy or learned:
and if their works give it them, we make no conscience to deny it them.
// lint-disable invalid-characters "æ"
For instance; the Fathers they only cite thus: Polycarpus, Ignatius, Irenæus, Cyprian,
Tertullian, Origen, Arnobius, Lactantius, Chrysostom, Jerom, etc.
More modern writers; Damascen, Rabanus, Paschasius, Theophylact, Bernard, etc.
And of the last age, Luther, Melancthon, Calvin, Beza, Zuinglius, Marlorat, Vossius,
Grotius, Dalleus, Amyralldus, etc.
And of our own country, Gildas, Beda, Alcuinus, Horn, Bracton, Grosteed, Littleton,
Cranmer, Ridley, Jewel, Whitaker, Seldon, etc.
And yet I presume this will not be thought uncivil or rude.
Why then is our simplicity (and so honestly grounded too,
as conscience against pride in man,
that so evilly and perniciously loves and seeks worship
and greatness) so much despised and abused,
and that by professed Christians too, who take themselves to be the followers of Him,
that has forbidden these foolish customs,
as plainly as any other impiety condemned in his doctrine?
I earnestly beg the lovers, users, and expecters of these ceremonies,
to let this I have written have some consideration and weight with them.

[.numbered]
XXXVI.
However, Christians are not so ill-bred as the world think; for they show respect too:
but the difference between them lies in the nature of the respect they perform,
and the reasons of it.
The world`'s respect is an empty ceremony, no soul nor substance in it:
the Christian`'s is a solid thing, whether by obedience to superiors, love to equals,
or help and countenance to inferiors.
Next, their reasons and motives to honour and respect, are as wide one from the other:
for fine apparel, empty titles, or large revenues are the world`'s motives,
being things her children worship:
but the Christian`'s motives are the sense of his duty in God`'s sight;
first to parents and magistrates; and then to inferior relations:
and lastly to all people, according to their virtue, wisdom, and piety;
which is far from respect to the mere persons of men,
or having their persons in admiration for reward:
much less on such mean and base motives as wealth and sumptuous raiment.

[.numbered]
XXXVII.
We shall easily grant, our honour, as our religion, is more hidden;
and that neither are so discernible by worldly men, nor grateful to them.
Our plainness is odd, uncouth, and goes mightily against the grain;
but so does Christianity too, and that for the same reasons.
But had not the Heathen spirit prevailed too long under a Christian profession,
it would not be so hard to discern the right from the wrong.
O that Christians would look upon themselves with the glass of righteousness;
that which tells true, and gives them an exact knowledge of themselves!
And then let them examine, what in them, and about them,
agrees with Christ`'s doctrine and life; and they may soon resolve,
whether they are real Christians, or but Heathens christened with the name of Christians.

====

[.blurb]
=== Some Testimonies from Ancient and Modern Writers in Favour of Our Behavior

[.numbered-group]
====

[.numbered]
XXXVIII.
Marlorat, out of Luther and Calvin,
upon that remarkable passage I just now urged from the apostle James,
gives us the sense those primitive reformers had of respect to persons in these words,
viz. '`To respect persons here, is to have regard to the habit and garb:
the apostle signifies, that such respecting of persons is so contrary to true faith,
that they are altogether inconsistent: but if the pomp,
and other worldly regards prevail, and weaken what is of Christ,
it is a sign of a decaying faith.
Yea, so great is the glory and splendour of Christ in a pious soul,
that all the glories of the world have no charms, no beauty, in comparison of that,
unto one so righteously inclined.
The apostle maketh such respecting of persons, to be repugnant to the light within them,
insomuch as they who follow these practices, are condemned from within themselves.
So that sanctity ought to be the reason or motive of all outward respect;
and that none is to be honoured, upon any account but holiness.`' Thus much Marlorat.
But if this be true doctrine,
we are much in the right in refusing conformity to the vain respects of worldly men.

[.numbered]
XXXIX.
But I shall add to these, the admonition of a learned ancient writer,
who lived about 1200 years since, of great esteem, namely Jerom,
who writing to a noble matron, Celantia,
directing her how to live in the midst of her prosperity and honours,
amongst many other religious instructions, speaks thus: '`Heed not thy nobility,
nor let that be a reason for thee to take place of any;
esteem not those of a meaner extraction to be thy inferiors;
for our religion admits of no respect of persons, nor doth it induce us to repute men,
from any external condition, but from their inward frame and disposition of mind:
it is hereby that we pronounce men noble or base.
With God, not to serve sin is to be free; and to excel in virtue is to be noble.
God has chosen the mean and contemptible of this world, whereby to humble the great ones.
Besides, it is a folly for any to boast his gentility,
since all are equally esteemed by God.
The ransom of the poor and rich cost Christ an equal expense of blood.
Nor is it material in what state a man is born; the new creature hath no distinction.
But if we will forget how we all descended from one Father;
we ought at least perpetually to remember that we have but one Saviour.`'

[.numbered]
XL. But since I am engaged against these fond and fruitless customs,
the proper effects and delights of vain and proud minds,
let me yet add one memorable passage more, as it is related by the famous Casaubon,
in his discourse of Use and Custom, where he briefly reports,
what passed between Sulpitius Severus and Paulinus, bishop of Nola,
(but such an one as gave all to redeem captives; whilst others of that function,
that they may show who is their master, are making many both beggars and captives,
by countenancing the plunder and imprisonment of Christians, for pure conscience to God);
he brings it in thus: '`He is not counted a civil man now, of late years amongst us,
who thinks it much, or refuseth to subscribe himself servant,
though it be to his equal or inferior.`' Yet Sulpitius Severus
was once sharply chid by Paulinus for subscribing himself his servant,
in a letter of his, saying, '`Take heed hereafter,
how thou being from a servant called into liberty,
dost subscribe thyself servant unto one who is thy brother and fellow servant;
for it is a sinful flattery, not a testimony of humility, to pay those honours to a man,
and a sinner, which are due to the one Lord, and one Master,
and one God.`' By this we may see the sense of some of the more apostolical bishops,
about the civilities and fashions so much reputed
with people that call themselves Christians and bishops,
and who would be thought their successors.
It was then a sin, it is now an accomplishment: it was then a flattery,
it is now respect: it was then fit to be severely reproved; and now,
alas! it is to deserve severe reproof not to use it.
O monstrous vanity!
How much, how deeply,
have those who are called Christians revolted from the plainness of the primitive days,
and practice of holy men and women in former ages!
How are they become degenerated into the loose, proud, and wanton customs of the world,
which knows not God; to whom use hath made these things, condemned by scripture, reason,
and example, almost natural!
And so insensible are they of both their cause and bad effects,
that they not only continue to practise them, but plead for them,
and unchristianly make a very mock of those who cannot imitate them.
But I shall proceed to what remains yet further to be said in our defence,
for declining another custom,
which helps to make us so much the stumbling-block of this light, vain,
and inconsiderate age.

====
