== Chapter X.

[.chapter-synopsis]
* 1+++.+++ Another piece of nonconformity to the world, which is our simple and plain speech, thou for you.
* 2+++.+++ Justified from the use of words and numbers, singular and plural.
* 3+++.+++ It was, and is the Hebrew, Greek, and Latin speech, in schools and universities.
* 4+++.+++ It is the language of all nations.
* 5+++.+++ The original of the present customs defends our disuse of it.
* 6+++.+++ If custom should prevail, in a sense it would be on our side.
* 7+++.+++ It cannot be uncivil or improper, for God himself, the fathers, prophets, Christ, and his apostles used it.
* 8+++.+++ An instance given in the case of Peter, in the palace of the high priest.
* 9+++.+++ It is the practice of men to God in their prayers: the pride of man to expect better to himself.
* 10+++.+++ Testimonies of several writers in vindication of us.
* 11+++.+++ The Author`'s convictions; and his exhortation to his reader.

[.numbered-group]
====

[.numbered]
I+++.+++ There is another piece of our nonconformity to the world,
that renders us very clownish to the breeding of it, and that is, thou for you,
and that without difference or respect to persons:
a thing that to some looks so rude it cannot well go down without derision or wrath.
But as we have the same original reason for declining this, as the foregoing customs,
so I shall add, what to me looks reasonable in our defence;
though it is very probable height of mind, in some of those that blame us,
will very hardly allow them to believe that the word reasonable
is reconcileable with so silly a practice as this is esteemed.

[.numbered]
II. Words of themselves are but as so many marks set and
employed for necessary and intelligible mediums,
or means,
whereby men may understandingly express their minds and conceptions to each other:
from whence comes conversation.
Now, though the world be divided into many nations, each of which, for the most part,
has a peculiar language, speech, or dialect,
yet have they ever concurred in the same numbers and persons,
as much of the ground of right speech.
For instance; I love, thou lovest, he loveth, are of singular number,
importing but one whether in the first, second, or third person: also we love, ye love,
they love, are of the plural number, because in each is implied more than one.
Which undeniable grammatical rule, might be enough to satisfy any,
that have not forgotten their accidence, that we are not beside reason in our practice.
For if thou lovest, be singular, and you love, be plural; and if thou lovest,
signifies but one; and you love, many; is it not as proper to say, thou lovest,
to ten men, as to say, you love, to one man?
Or, why not, I love, for we love; and we love, instead of I love?
Doubtless it is the same, though most improper, and in speech ridiculous.

[.numbered]
III.
Our next reason is; if it be improper or uncivil speech, as termed by this vain age,
how comes it that the Hebrew, Greek, and Roman authors, used in schools and universities,
have no other?
Why should they not be a rule in that, as well as other things?
And why, I pray then, are we so ridiculous for being thus far grammatical?
Is it reasonable that children should be whipped at school for putting you for thou,
as having made false Latin; and yet that we must be, though not whipped, reproached,
and often abused, when we use the contrary propriety of speech?

[.numbered]
IV. But in the third place, it is neither improper nor uncivil, but much otherwise;
because it is used in all languages, speeches, and dialects, and that through all ages.
This is very plain: as for example, it was God`'s language when he first spake to Adam,
viz. Hebrew: also it is the Assyrian, Chaldean, Grecian and Latin speech.
And now among the Turks, Tartars, Muscovites, Indians, Persians, Italians, Spaniards,
French, Dutch, Germans, Polonians, Swedes, Danes, Irish, Scotch, Welsh,
as well as English there is a distinction preserved,
and the word thou is not lost in the word which goes for you.
And though some of the modern tongues have done as we do, yet upon the same error.
But by this it is plain, that thou is no upstart, nor yet improper,
but the only proper word to be used in all languages to a single person;
because otherwise all sentences, speeches, and discourses may be very ambiguous,
uncertain, and equivocal.
If a jury pronounce a verdict or a judge a sentence, three being at the bar,
upon three occasions, very differently culpable, and should say,
You are here guilty and to die; or innocent, and discharged:
who knows who is guilty or innocent?
May be but one, perhaps two; or it may be, all three:
therefore our indictments run in the singular number, as Hold up thy hand:
thou art indicted by the name of, etc., for that thou, not having the fear of God, etc.
And it holds the same in all conversation.
Nor can this be avoided but by many unnecessary circumlocutions.
And as the preventing of such length and obscurity
was doubtless the first reason for the distinction,
so cannot that be justly disused till the reason be first removed;
which can never be whilst two are in the world.

[.numbered]
V+++.+++ But this is not all;
it was first ascribed in way of flattery to proud popes and emperors,
imitating the heathens`' vain homage to their gods;
thereby ascribing a plural honour to a single person:
as if one pope had been made up of many gods, and one emperor of many men;
for which reason, you only to be used to many, became first spoken to one.
It seems the word thou looked like too lean and thin a respect; and therefore,
some bigger than they should be, would have a style suitable to their own ambition:
a ground we cannot build our practice on; for what began it only loves it still.
But supposing you to be proper to a prince, it will not follow it is to a common person.
For his edict runs, We will and require, because, perhaps,
in conjunction with his council:
and therefore you to a private person is an abuse of the word.
But as pride first gave it birth, so hath she only promoted it.
Monsieur, sir, and madam, were originally names given to none but the king, his brother,
and their wives, both in France and England;
yet now the ploughman in France is called monsieur, and his wife madame:
and men of ordinary trades in England, sir, and their wives, dame;
which is the legal title of a lady, or else mistress,
which is the same with madame in French.
So prevalent hath pride and flattery been in all ages,
the one to give and the other to receive respects, as they term it.

[.numbered]
VI. But some will tell us, custom should rule us; and that is against us.
But it is easily answered, and more truly,
that though in things reasonable or indifferent, custom is obliging or harmless,
yet in things unreasonable or unlawful, she has no authority.
For custom can no more change numbers than genders, nor yoke one and you together,
than make a man into a woman, or one into a thousand.
But if custom be to conclude us, it is for us;
for as custom is nothing more than ancient usage, I appeal to the practice of mankind,
from the beginning of the world, through all nations,
against the novelty of this confusion, viz. you to one person.
Let custom, which is ancient practice and fact, issue this question.
Mistake me not: I know words are nothing, but as men give them a value or force by use;
but then, if you will discharge thou, and that you must succeed in its place,
let us have a distinguishing word instead of you to be used in speech to many:
but to use the same word for one and many, when there are two,
and that only to please a proud and haughty humour in man,
is not reasonable in our sense: which we hope is Christian, though not modish.

[.numbered]
VII.
But if thou to a single person be improper or uncivil, God himself,
all the holy fathers and prophets, Christ Jesus, and his apostles, the primitive saints,
all languages throughout the world, and our own law proceedings are guilty; which,
with submission, were great presumption to imagine.
Besides,
we all know it is familiar with most of our authors to preface their discourses
to the reader in the same language of thee and thou:
as, Reader, thou art desired, etc.
Or, Reader, this is written to inform thee of the occasion, etc.
And it cannot be denied, that the most famous poems, dedicated to love or majesty,
are written in this style.
Read of each in Chaucer, Spenser, Waller, Cowley, Dryden, etc.
Why then should it be so homely, ill-bred, and insufferable in us?
This, I conceive, can never be answered.

[.numbered]
VIII.
I doubt not at all that something altogether as singular
attended the speech of Christ and his disciples:
for I remember it was urged upon Peter in the high priest`'s palace,
as a proof of his belonging to Jesus, when he denied his Lord: "`Surely,`" said they,
"`thou art also one of them: for thy speech bewrayeth thee.`"^
footnote:[Matt. 26:73.]
They had guessed by his looks but just before that he had been with Jesus;
but when they discoursed with him, his language put them all out of doubt:
surely then he was one of them, and he had been with Jesus.
Something it was he had learned in his company that was odd and observable; to be sure,
not of the world`'s behaviour.
Without question, the garb, gait, and speech of his followers differed,
as well as his doctrine, from the world;
for it was a part of his doctrine it should be so.
It is easy to believe they were more plain, grave, and precise,
which is more credible from the way which poor, confident,
fearful Peter took to disguise the business;
for he fell to cursing and swearing--a sad shift.
But he thought that the likeliest way to remove the suspicion,
that was most unlike Christ.
And the policy took; for it silenced their objections, and Peter was as orthodox as they.
But though they found him not out, the cock`'s crow did;
which made Peter remember his dear suffering Lord`'s words: and he went forth,
and wept bitterly; that he had denied his Master,
who was then delivered up to die for him.

[.numbered]
IX. But our last reason is of most weight with me, and because argumentum ad hominem,
it is most heavy with our despisers, which is this:
it should not therefore be urged upon us,
because it is a most extravagant piece of pride in a mortal man to require
or expect from his fellow creature a more civil speech or grateful language,
than he is wont to give to the immortal God and his Creator in all his worship to him.
Art thou, O man, greater than he that made thee?
Canst thou approach the God of thy breath and great Judge of thy life with thou and thee,
and when thou risest off thy knees, scorn a Christian for giving to thee,
poor mushroom of the earth,
no better language than thou hast given to God but just before?
An arrogancy not to be easily equalled!
But again, it has either too much or too little respect; if too much,
do not reproach and be angry, but gravely and humbly refuse it; if too little,
why dost thou show to God no more?
O whither is man gone!
To what a pitch does he soar!
He would be used more civilly by us than he uses God;
which is to have us make more than a God of him: but he shall want worshippers of us,
as well as he wants the divinity in himself that deserves to be worshipped.
Certain we are, that the Spirit of God seeks not these respects,
much less pleads for them,
or would be wroth with any that conscientiously refuse to give them.
But that this vain generation is guilty of using them, to gratify a vain mind,
is too palpable.
What capping, what cringing, what scraping, what vain, unmeant words,
most hyperbolical expressions, compliments, gross flatteries, and plain lies,
under the name of civilities, are men and women guilty of in conversation!
Ah! my friends! whence fetch you these examples?
What part of all the writings of the holy men of God warrants these things?
But, to come nearer to your own profession, is Christ your example herein,
whose name you pretend to bear; or those saints of old that lived in desolate places,
of whom the world was not worthy:^
footnote:[Heb. 11:38.]
or do you think you follow the practice of those Christians that,
in obedience to their Master`'s life and doctrine, forsook the respect of persons,
and relinquished the fashions, honour, and glory of this transitory world;
whose qualifications lay not in external gestures, respects, and compliments,
but in a meek and quiet spirit,^
footnote:[1 Pet. 3:4.]
adorned with temperance, virtue, modesty, gravity, patience, and brotherly kindness;
which were the tokens of true honour,
and only badges of respect and nobility in those Christian times?
O no.
But is it not to expose ourselves both to your contempt and fury, that we imitate them,
and not you?
And tell us, pray, are not romances, plays, masks, gaming, fiddlers,
etc. the entertainments that most delight you?
Had you the spirit of Christianity indeed,
could you consume your most precious little time in so many unnecessary visits, games,
and pastimes; in your vain compliments, courtships, feigned stories, flatteries,
and fruitless novelties, and what not; invented and used to your diversion,
to make you easy in your forgetfulness of God:
which never was the Christian way of living,
but entertainment of the heathens that knew not God?
Oh! were you truly touched with a sense of your sins, and in any measure born again;
did you take up the cross of Jesus and live under it, these,
which so much please your wanton and sensual nature, would find no place with you.
This is not seeking the things that are above,^
footnote:[Col. 3:1.]
to have the heart thus set on things that are below;
nor working out your own salvation with fear and trembling, to spend your days in vanity.
This is not crying with Elihu, "`I know not to give flattering titles to men;
for in so doing my Maker would soon take me away.`"
This is not to deny self, and lay up a more hidden and enduring substance,
an eternal inheritance in the heavens, that will not pass away.
Well, my friends, whatever you think,
your plea of custom will find no place at God`'s tribunal:
the light of Christ in your own hearts will overrule it; and this Spirit,
against which we testify, shall then appear to be what we say it is.
Say not I am serious about slight things; but beware you of levity in serious things.

[.numbered]
X+++.+++ Before I close, I shall add a few testimonies from men of general credit,
in favour of our nonconformity to the world in this particular.

Luther, the great reformer, whose sayings were oracles with the age he lived in,
and of no less reputation now, with many that object against us,
was so far from condemning our plain speech, that in his _Ludus,_
he sports himself with you to a single person as an incongruous and ridiculous speech,
viz. _Magister, vos estis iratus?_
Master, are you angry?
As absurd with him in Latin, as My masters, art thou angry?
is in English.
Erasmus, a learned man, and an exact critic in speech,
than whom I know not any we may so properly refer the grammar of the matter to,
not only derides it, but bestows a whole discourse upon rendering it absurd:
plainly manifesting that it is impossible to preserve numbers if you,
the only word for more than one, be used to express one: as also,
that the original of this corruption was the corruption of flattery.
Lipsius affirms of the ancient Romans,
"`That the manner of greeting now in vogue was not in use amongst them.`"
To conclude: Howel, in his History of France,
gives us an ingenious account of its original; where he not only assures us,
"`That anciently the peasants thou`'d their kings,
but that pride and flattery first put inferiors upon paying
a plural respect to the single person of every superior,
and superiors upon receiving it.`"
And though we had not the practice of God and man
so undeniably to justify our plain and homely speech,
yet, since we are persuaded that its original was from pride and flattery,
we cannot in conscience use it.
And however we may be censured as singular by those loose and airy minds,
that through the continual love of earthly pleasures,
consider not the true rise and tendency of words and things;
yet to us whom God has convinced by his light and Spirit
in our hearts of the folly and evil of such courses,
and brought into a spiritual discerning of the nature and ground of the world`'s fashions,
they appear to be fruits of pride and flattery;
and we dare not continue in such vain compliances to earthly minds, lest we offend God,
and burden our consciences.
But having been sincerely affected with the reproofs of instruction,
and our hearts being brought into a watchful subjection to the righteous law of Jesus,
so as to bring our deeds to the light,^
footnote:[John 3:19-21,]
to see in whom they are wrought, if in God or not; we cannot,
we dare not conform ourselves to the fashions of the world that pass away;
knowing assuredly, that "`for every idle word that men shall speak,
they shall give account thereof in the day of judgment.`"^
footnote:[Matt. 12:36.]

[.numbered]
XI. Wherefore, reader, whether thou art a night-walking Nicodemus, or a scoffing scribe;
one that would visit the blessed Messiah, but in the dark customs of the world,
that thou mightest pass as undiscerned, for fear of bearing his reproachful cross;
or else a favourer of Haman`'s pride,
and countest these testimonies but a foolish singularity; I must say,
Divine love enjoins me to be a messenger of truth to thee,
and a faithful witness against the evil of this degenerate world, as in other,
so in these things; in which the spirit of vanity and lust hath got so great a head,
and lived so long uncontrolled, that it hath impudence enough to term its darkness light,
and to call its evil offspring by the names due to a better nature,
the more easily to deceive people into the practice of them.
And truly, so very blind and insensible are most of what spirit they are,
and ignorant of the meek and self-denying life of holy Jesus, whose name they profess;
that to call each other Rabbi, that is, master; to bow to men, which I call worship;
and to greet with flattering titles, and to do their fellow creatures homage;
to scorn that language to themselves that they give to God,
and to spend their time and estate to gratify their wanton minds;
the customs of the Gentiles, that knew not God, pass with them for civility,
good-breeding, decency, recreation, accomplishments, etc.
O that man would consider, since there are but two spirits, one good, the other evil,
which of them it is that inclines the world to these things;
and whether it be Nicodemus or Mordecai in thee,
that doth befriend these despised Christians,
which makes thee ashamed to disown that openly in conversation with the world,
which the true light hath made vanity and sin to thee in secret!
Or if thou art a despiser, tell me, I pray thee, what dost thou think thy mockery, anger,
or contempt dost most resemble, proud Haman, or good Mordecai?
My friend, know that no man hath more delighted in,
or been prodigal of those vanities called civilities than myself;
and could I have covered my conscience under the fashions of the world,
truly I had found a shelter from showers of reproach
that have fallen very often and thick upon me;
but had I, with Joseph, conformed to Egypt`'s customs,
I had sinned against my God and lost my peace.
But I would not have thee think it is a mere thou or title
simply or nakedly in themselves we boggle at,
or that we would beget or set up any form inconsistent with sincerity or true civility:
there is but too much of that;
but the esteem and value the vain minds of men do put upon them,
that ought to be crossed and stripped of their delights,
constrains us to testify so steadily against them.
And this know, from the sense God`'s Holy Spirit hath begotten in us,
that that which requires these customs, and begets fear to leave them,
and pleads for them, and is displeased, if not used and paid,
is the spirit of pride and flattery in the ground; though frequency, use,
or generosity may have abated its strength in some:
and this being discovered by the light that now shines from heaven
in the hearts of the despised Christians I have communion with,
necessitates them to this testimony; and myself, as one of them and for them,
in a reproof of the unfaithful, who would walk undiscerned,
though convinced to the contrary; and for an allay to the proud despisers,
who scorn us as a people guilty of affectation and singularity.
For the eternal God, who is great amongst us,
and on his way in the earth to make his power known,
will root up every plant that his right hand hath not planted.
Wherefore let me beseech thee, reader, to consider the foregoing reasons,
which were mostly given me from the Lord, in that time,
when my condescension to these fashions would have been purchased at almost any rate;
but the certain sense I had of their contrariety
to the meek and self-denying life of holy JESUS,
required of me my disuse of them, and faithful testimony against them.
I speak the truth in Christ; I lie not:
I would not have brought myself under censure and disdain for them, could I,
with peace of conscience, have kept my belief under a worldly behaviour.
It was extremely irksome to me to decline, and expose myself;
but having an assured and repeated sense of the original of these vain customs,
that they rise from pride, self-love, and flattery,
I dared not gratify that mind in myself or others.
And for this reason it is,
that I am earnest with my readers to be cautious how they reprove us on this occasion;
and do once more entreat them that they would seriously weigh in themselves,
whether it be the spirit of the world or of the Father, that is so angry with our honest,
plain, and harmless thou and thee:
that so every plant that God our heavenly Father hath not
planted in the sons and daughters of men may be rooted up.

====
