== Chapter XI.

1+++.+++ Pride leads people to an excessive value of their persons.--2. It is plain,
from the racket that is made about blood and families:
also in the case of shape and beauty.--3. Blood no nobility,
but virtue.--4. Virtue no upstart: antiquity no nobility without it,
else age and blood would bar virtue in the present
age.--5. God teaches the true sense of nobility,
who made of one blood all nations;
there is the original of all blood.--6. These men of blood, out of their feathers,
look like other men.--7. This is not said to reject, but humble the gentleman:
the advantages of that condition above others.
An exhortation to recover their lost economy in families,
out of interest and credit.--8. But the author has a higher motive; the gospel,
and the excellencies of it,
which they profess.--9. The pride of persons respecting shape and beauty: the washes,
patches, paintings, dresses, etc.
This excess would keep the poor:
the mischiefs that attend it.--10. But pride in the old and homely yet more hateful:
that it is usual.
The madness of it.
Counsel to the beautiful to get their souls like their bodies;
and to the homely to supply want of that in the adornment of their lasting part,
their souls, with holiness.
Nothing homely with God but sin.
The blessedness of those that wear Christ`'s yoke and cross,
and are crucified to the world.

I+++.+++ But pride stops not here;
she excites people to an excessive value and care of their persons:
they must have great and punctual attendance, stately furniture, rich and exact apparel.
All which help to make up that pride of life that John tells us is not of the Father,
but of the world.^
footnote:[1 John 2:16.]
A sin God charged upon the haughty daughters of Zion,^
footnote:[Isaiah, iii.]
and on the proud prince and people of Tyrus.^
footnote:[Ezek.
xxvii.
xxviii.]
Read these chapters, and measure this age by their sins,
and what is coming on these nations by their judgments.
But at the present I shall only touch upon the first,
viz. the excessive value people have of their persons;
leaving the rest to be considered under the last head of this discourse, which is luxury,
where they may be not improperly placed.

II. That people are generally proud of their persons is too visible and troublesome;
especially if they have any pretence either to blood or beauty;
the one has raised many quarrels among men, and the other among women,
and men too often for their sakes and at their excitements.
But to the first:
What a pother has this noble blood made in the world:--antiquity of name or family,
whose father, or mother, great grandfather,
or great grandmother was best descended or allied:--what stock or what
clan they came of:--what coat of arms they gave:--which had,
of right, the precedence!
But methinks nothing of man`'s folly has less show of reason to palliate it.

III.
For, first, what matter is it of whom any one is descended, that is not of ill fame:
since it is his own virtue that must raise, or vice depress him?
An ancestor`'s character is no excuse to a man`'s ill actions,
but an aggravation of his degeneracy: and since virtue comes not by generation,
I neither am the better nor the worse for my forefather; to be sure,
not in God`'s account,
nor should it be in man`'s. Nobody would endure injuries the easier,
or reject favours the more, for coming by the hand of a man well or ill descended.
I confess it were greater honour to have had no blots, and with an hereditary estate,
to have had a lineal descent or worth; but that was never found: no;
not in the most blessed of families upon earth,
I mean Abraham`'s. To be descended of wealth and titles,
fills no man`'s head with brains or heart with truth:
those qualities come from a higher cause.
It is vanity then and most condemnable pride for a man of bulk and character to despise
another of less size in the world and of meaner alliance for want of them:
because the latter may have the merit,
where the former has only the effects of it in an ancestor:
and though the one be great by means of a forefather, the other is so too,
but it is by his own: then, pray, which is the braver man of the two?

IV. O, says the person proud of blood,
It was never a good world since we have had so many upstart gentlemen!
But what should others have said of that man`'s ancestor,
when he started first up into the knowledge of the world?
For he, and all men and families, aye, and all states and kingdoms too,
have had their upstarts, that is, their beginnings.
This is being like the true church, because old, not because good:
for families to be noble by being old, and not by being virtuous.
No such matter: it must be age in virtue, or else virtue before age;
for otherwise a man should be noble by the means of his predecessor,
and yet the predecessor less noble than he, because he was the acquirer:
which is a paradox that will puzzle all their heraldry to explain.
Strange! that they should be more noble than their
ancestor that got their nobility for them!
But if this be absurd, as it is, then the upstart is the noble man:
the man that got it by his virtue;
and those are only entitled to his honour that are imitators of his virtue:
the rest may bear his name from his blood, but that is all.
If virtue then give nobility, which heathens themselves agree,
then families are no longer truly noble than they are virtuous.
And if virtue go not by blood, but by the qualifications of the descendants,
it follows blood is excluded: else blood would bar virtue;
and no man that wanted the one, should be allowed the benefit of the other:
which were to stint and bound nobility for want of antiquity, and make virtue useless.

No, let blood and name go together; but pray let nobility and virtue keep company,
for they are nearest of kin.
It is thus profited by God himself,
that best knows how to apportion things with an equal and just hand.
He neither likes nor dislikes by descent; nor does He regard what people were, but are.
He remembers not the righteousness of any man that leaves his righteousness;^
footnote:[Ezek.
xviii.]
much less any unrighteous man for the righteousness of his ancestor.

V+++.+++ But if these men of blood please to think themselves
concerned to believe and reverence God in his holy Scriptures,
they may learn that "`in the beginning He made of one blood
all nations of men to dwell upon all the earth;`"^
footnote:[Acts 17:26.]
and that we all descended from one father and mother.
A more certain original than the best of us can assign.
From thence go down to Noah, who was the second planter of the human race,
and we are upon some certainty for our forefathers.
What violence has reaped or virtue merited since,
and how far we that are alive are concerned in either,
will be hard for us to determine but a very few ages off us.

VI. But, methinks it should suffice to say, our own eyes see that men of blood,
out of their gear and trappings, without their feathers and finery,
have no more marks of honour by nature stamped upon them, than their inferior neighbours.
Nay, themselves being judges, they will frankly tell us,
they feel all those passions in their blood, that make them like other men,
if not further from the virtue that truly dignifies.
The lamentable ignorance and debauchery that now
rages among too many of our greater sort of folks,
is too clear and casting an evidence in the point:
and pray tell me of what blood are they come?

VII.
Howbeit, when I have said all this, I intend not, by debasing one false quality,
to make insolent another that is not true.
I would not be thought to set the churl on the present gentleman`'s shoulder;
by no means: his rudeness will not mend the matter.
But what I have written is to give aim to all where true nobility dwells,
that every one may arrive at it by the ways of virtue and goodness.
But for all this, I must allow a great advantage to the gentleman,
and therefore prefer his station: just as the apostle Paul,
who after he had humbled the Jews,
that insulted the Christians with their laws and rites,
gave them the advantage over all other nations in statutes and judgments.
I must grant that the condition of our great men is much
to be preferred to the ranks of our inferior people.
For, first, they have more power to do good;
and if their hearts be equal to their ability,
they are blessings to the people of any country.
Secondly, the eyes of the people are usually directed to them; and if they will be kind,
just, and hopeful, they shall have their affections and services.
Thirdly, they are not under equal straits with the inferior sort;
and consequently they have more help, leisure,
and occasion to polish their passions and tempers with books and conversation.
Fourthly, they have more time to observe the actions of other nations:
to travel and view the laws, customs, and interests of other countries,
and bring home whatsoever is worthy or imitable.
And so an easier way is open for great men to get honour;
and such as love true reputation will embrace the best means to it.
But because it too often happens that great men do
but little mind to give God the glory of their prosperity,
and to live answerable to his mercies; but on the contrary,
live without God in the world, fulfilling the lusts thereof, his hand is often seen,
either in impoverishing or extinguishing them,
and raising up men of more virtue and humility to their estates and dignity.
However,
I must allow that among people of this rank there
have been some of them of more than ordinary virtue,
whose examples have given light to their families.
And it has been something natural for some of their descendants to endeavour
to keep up the credit of their houses in proportion to the merit of their founder.
And to say true, if there be any advantage in such descent,
it is not from blood but education: for blood has no intelligence in it,
and is often spurious and uncertain;
but education has a mighty influence and strong bias
upon the affections and actions of men.
In this the ancient nobles and gentry of this kingdom did excel:
and it were much to be wished that our great people would
set about to recover the ancient economy of their houses,
the strict and virtuous discipline of their ancestors,
when men were honoured for their achievements,
and when nothing more exposed a man to shame,
than being born to a nobility that he had not a virtue to support.

VIII.
O, but I have a higher motive!
The glorious gospel of Jesus Christ, which having taught this northern isle,
and all ranks professing to believe in it,
let me prevail upon you to seek the honour that it has brought from heaven,
to all the true disciples of it, who are indeed the followers of God`'s Lamb,
that takes away the sin of the world.^
footnote:[John 1:29.]
Receive with meekness his gracious word into your hearts,
that subdues the world`'s lusts, and leads in the holy way to blessedness.
Here are charms no carnal eye hath seen, nor ear heard, nor heart perceived,
but they are revealed to such humble converts by his spirit.
Remember you are but creatures, and that you must die, and after all be judged.

IX. But personal pride ends not in nobility of blood;
it leads folks to a fond value of their persons, be they noble or ignoble;
especially if they have any pretence to shape or beauty.
It is admirable to see, how much it is possible for some to be taken with themselves,
as if nothing else deserved their regard, or the good opinion of others.
It would abate their folly,
if they could find in their hearts to spare but half
the time to think of God and their latter end,
which they most prodigally spend in washing, perfuming, painting, patching, attiring,
and dressing.
In these things they are precise, and very artificial; and for cost they spare not.
But that which aggravates the evil is,
the pride of one might comfortably supply the need of ten.
Gross impiety that it is, that a nation`'s pride should not be spared to a nation`'s poor!
But what is this for at last?
Only to be admired, to have reverence, draw love,
and command the eyes and affections of beholders.
And so fantastic are they in it, as hardly to be pleased too.
Nothing is good, or fine, or fashionable enough for them: the sun itself,
the blessing of heaven, and comfort of the earth, must not shine upon them,
lest it tan them; nor the wind blow, for fear it should disorder them.
O impious nicety!
Yet while they value themselves above all else,
they make themselves the vassals of their own pride; worshipping their shape, feature,
or complexion, whichsoever is their excellency.
The end of all which, is but too often to excite unlawful love, which I call lust,
and draw one another into as miserable as evil circumstances:
in single persons it is of ill consequence; for if it does not awaken unchaste desires,
it lays no foundation for solid and lasting union:
the want of which helps to make so many unhappy marriages in the world:
but in married people the sin is aggravated; for they have none of right to please,
but one another; and to affect the gaiety and vanity of youth,
is an ill sign of loving and living well at home:
it looks rather like dressing for a market.
It has sad effects in families: discontents, partings, duels, poisonings,
and other infamous murders.
No age can better tell us the sad effects of this sort of pride than this we live in; as,
how excessively wanton, so how fatal it has been to the sobriety, virtue, peace,
and health of families in this kingdom.

X+++.+++ But I must needs say, that of all creatures,
this sort of pride does least become the old and homely,
if I may call the ill-favoured and deformed so;
for the old are proud only of what they had, which shows, to their reproach,
their pride has outlived their beauty, and, when they should be repenting,
they are making work for repentance.
But the homely are yet worse, they are proud of what they never had, nor ever can have:
nay, their persons seem as if they were given for a perpetual humiliation to their minds;
and to be proud of them is loving pride for pride`'s sake, and to be proud,
without a temptation to be proud.
And yet in my whole life I have observed nothing more doting on itself:
a strange infatuation and enchantment of pride!
What!
Not to see right with their eyes, because of the partiality of their minds?
This self-love is blind indeed.
But to add expense to the vanity, and to be costly upon that which cannot be mended,
one would think they should be downright mad; especially if they consider,
that they look the homelier for the things that are thought handsome,
and do but thereby draw their deformity more into notice,
by that which does so little become them.

But in such persons`' follies we have a specimen of man;
what a creature he is in his lapse from his primitive image.
All this, as Jesus said of sin of old, comes from within;^
footnote:[Matt. 15:11,18-20.]
that is the disregard that men and women have to
the word of their Creator in their hearts;^
footnote:[Duet. 30:14; Rom. 10:8;]
which shows pride and teaches humility, and self-abasement,
and directs the mind to the true object of honour and worship;
and that with an awe and reverence suitable to his sovereignty and majesty.
Poor mortals!
But living dirt!
Made of what they tread on: who, with all their pride,
cannot secure themselves from the spoil of sickness, much less from the stroke of death!
O! did people consider the inconstancy of all visible things,
the cross and adverse occurrences of man`'s life, the certainty of his departure,
and eternal judgment,
it is to be hoped they would bring their deeds to Christ`'s light in their hearts,^
footnote:[John 3:20-21,]
and they would see if they were wrought in God, or not,
as the beloved disciple tells us from his dear Master`'s mouth.
Art thou shapely, comely, beautiful--the exact draught of a human creature?
Admire that Power that made thee so.
Live an harmonious life to the curious make and frame of thy creation;
and let the beauty of thy body teach thee to beautify thy mind with holiness,
the ornament of the beloved of God.
Art thou homely or deformed; magnify that goodness that did not make thee a beast;
and with the grace that is given unto thee, for it has appeared unto all,
learn to adorn thy soul with enduring beauty.
Remember the King of heaven`'s daughter, the church,
of which true Christians are members, is all glorious within.
And if thy soul excel, thy body will only set off the lustre of thy mind.
Nothing is homely in God`'s sight but sin;
and that man and woman that commune with their own hearts, and sin not; who,
in the light of holy Jesus, watch over the movings and inclinations of their own souls,
and that suppress every evil in its conception, they love the yoke and cross of Christ,
and are daily by it crucified to the world,
but live to God in that life which outlives the fading satisfactions of it.
