== Chapter XII.

[.chapter-synopsis]
* 1+++.+++ The character of a proud man: a glutton upon himself: is proud of his pedigree.
* 2+++.+++ He is insolent and quarrelsome, but cowardly, yet cruel.
* 3+++.+++ An ill child, subject, and servant.
* 4+++.+++ Inhospitable.
* 5+++.+++ No friend to any.
* 6+++.+++ Dangerous and mischievous in power
* 7+++.+++ Of all things, pride bad in ministers.
* 8+++.+++ They claim prerogative above others.
* 9+++.+++ And call themselves the clergy: their lordliness and avarice.
* 10+++.+++ Death swallows all.
* 11+++.+++ The way to escape these evils.

[.numbered-group]
====

[.numbered]
I+++.+++ To conclude this great head of pride, let us briefly see, upon the whole matter,
what is the character of a proud man in himself, and in divers relations and capacities.
A proud man then is a kind of glutton upon himself;
for he is never satisfied with loving and admiring himself; whilst nothing else,
with him, is worthy either of love or care: if good enough to be the servant of his will,
it is as much as he can find in his heart to allow:
as if he had been only made for himself, or rather that he had made himself.
For as he despises man, because he cannot abide an equal, so he does not love God,
because he would not have a superior: he cannot bear to owe his being to another,
lest he should thereby acknowledge one above himself.
He is one that is mighty big with the honour of his ancestors,
but not of the virtue that brought them to it;
much less will he trouble himself to imitate them.
He can tell you of his pedigree, his antiquity, what estate, what matches;
but forgets that they are gone, and that he must die too.

[.numbered]
II. But how troublesome a companion is a proud man!
Ever positive and controlling; and if you yield not, insolent and quarrelsome:
yet at the upshot of the matter, cowardly: but if strongest, cruel.
He feels no more of other men`'s miseries than if he were not a man,
or it were a sin to be sensible.
For not feeling himself interested, he looks no further;
he will not disquiet his thoughts with other men`'s infelicities;
it shall content him to believe they are just:
and he had rather churlishly upbraid them as the cause,
than be ready to commiserate or relieve them.
So that compassion and charity are with him as useless
as humility and meekness are hateful.

[.numbered]
III.
A proud man makes an ill child, servant, and subject; he contemns his parents, master,
and prince; he will not be subject.
He thinks himself too wise, or too old, to be directed;
as if it were a slavish thing to obey;
and that none were free that may not do what they please;
which turns duty out of doors and degrades authority.
On the other hand, if he be a husband, or father, or master,
there is scarcely any enduring:
he is so insufferably curious and testy that it is an affliction to live with him;
for hardly can any hand carry it even enough to please him.
Some peccadillo about his clothes, his diet, his lodging,
or attendance quite disorders him:
but especially if he fancies any want of the state and respect he looks for.
Thus pride destroys the nature of relations: on the one side, learns to contemn duty;
and on the other side, it turns love into fear, and makes the wife a servant,
and the children and servants slaves.

[.numbered]
IV. But the proud man makes an ill neighbour too; for he is an enemy to hospitality:
he despises to receive kindness, because he would not show any,
nor be thought to need it.
Besides, it looks too equal and familiar for his haughty humour.
Emulation and detraction are his element;
for he is jealous of attributing any praise to others, where just;
lest that should cloud and lessen him, to whom it never could be due:
he is the man that fears, what he should wish, to wit, that others should do well.
But that is not all; he maliciously miscalls their acts of virtue,
which his corruptions will not let him imitate, that they may get no credit by them.
If he wants any occasion of doing mischief, he can make one: either they use him ill,
or have some design upon him; the other day they paid him not the cap and knee;
the distance and respect he thinks his quality, parts, or merits do require.
A small thing serves a proud man to pick a quarrel; of all creatures the most jealous,
sullen, spiteful and revengeful: he can no more forgive an injury,
than forbear to do one.

[.numbered]
V+++.+++ Nor is this all: a proud man can never be a friend to anybody.
For besides that his ambition may always be bribed
by honour and preferment to betray that relation,
he is unconversable; he must not be catechised and counselled,
much less reproved or contradicted: no,
he is too covetous of himself to spare another man a share, and much too high, stiff,
and touchy: he will not away with those freedoms that a real friendship requires.
To say true, he contemns the character; it is much too familiar and humble for him:
his mighty soul would know nothing besides himself and vassals to stock the world.
He values other men, as we do cattle, for their service only; and, if he could,
would use them so; but as it happens, the number and force are unequal.

[.numbered]
VI. But a proud man in power is very mischievous;
for his pride is the more dangerous by his greatness, since from ambition in private men,
it becomes tyranny in him: it would reign alone; nay live so,
// lint-disable invalid-characters "æ"
rather than have competitors: _aut Cæsar, aut nullus._
Reason must not check it, nor rules of law limit it; and either it can do no wrong,
or it is sedition to complain of the wrong that it does.
The men of this temper would have nothing thought amiss they do; at least,
they count it dangerous to allow it to be so, though so it be;
for that would imply they had erred, which it is always matter of state to deny: no,
they will rather choose to perish obstinately, than by acknowledging,
yield away the reputation of better judging to inferiors,
though it were their prudence to do so.
And indeed,
it is all the satisfaction that proud great men make to
the world for the miseries they often bring upon it,
that, first or last, upon a division,
they leave their real interest to follow some one excess of humour,
and are almost ever destroyed by it.
This is the end pride gives proud men, and the ruin it brings upon them,
after it has punished others by them.

[.numbered]
VII.
But above all things, pride is intolerable in men pretending to religion;
and of them in ministers; for they are names of the greatest contradiction.
I speak without respect or anger, to persons or parties;
for I only touch upon the bad of all.
What shall pride do with religion, that rebukes it?
Or ambition with ministers, whose very office is humility?
And yet there are but too many of them, that,
besides an equal guilt with others in the fleshly pride of the world,
are even proud of that name and office, which ought always to remind them of self-denial.
Yea, they use it as the beggars do the name of God and Christ, only to get by it:
placing to their own account the advantages of that reverend profession,
and thereby making their function but a political handle
to raise themselves to the great preferments of the world.
But O then! how can such be his ministers, that said,
"`My kingdom is not of this world`"?^
footnote:[John 18:36.]
Who, of mankind, more self-conceited than these men?
If contradicted, as arrogant and angry, as if it were their calling to be so.
Counsel one of them, he scorns you: reprove him,
and he is almost ready to excommunicate you:
'`I am a minister and an elder:`' flying thither
to secure himself from the reach of just censure,
which indeed exposes him but the more to it: and therefore his fault cannot be the less,
by how much it is worse in a minister to do ill, and spurn at reproof,
than an ordinary man.

[.numbered]
VIII.
O, but he pleads an exemption by his office: what!
Shall he breed up chickens to pick out his own eyes!
Be rebuked or instructed by a layman or parishioner!
A man of less age, learning, or ability!
No such matter:
he would have us believe that his ministerial prerogative
has placed him out of the reach of popular impeachment.
He is not subject to vulgar judgments.
Even questions about religion are schism: believe as he says:
it is not for you to pry so curiously into the mysteries of religion:
never good day since laymen meddle so much with the minister`'s office.
Not considering, poor man, that the contrary is most true:
not many good days since ministers meddled so much in laymen`'s business.
Though perhaps there is little reason for this distinction, besides spiritual gifts,
and the improvement of them by a diligent use of them for the good of others.

Such good sayings as these, Be ready to teach: answer with meekness:
let every man speak as of the gift of God that is in him:
if anything be revealed to him that sits by, let the first hold his peace:
be not lords over God`'s heritage, but meek and lowly; washing the feet of the people,^
footnote:[2 Tim. 2:24-25; Tit.
iii; 1 Cor. 14:30.]
as Jesus did those of his poor disciples;--are unreasonable
and antiquated instructions with some clergy,
and it is little less than heresy to remind them of these things:
a mark of great disaffection to the church in their opinion.
For by this time their pride has made them the church,
and the people but the porch at best; a cipher that signifies nothing,
unless they clap their figure before it: forgetting,
that if they were as good as they should be, they could be but ministers, stewards,
and under-shepherds; that is, servants to the church, family, flock, and heritage of God:
and not that they are that church, family, flock, and heritage,
which they are only servants unto.
Remember the words of Christ, "`Let him that would be greatest be your servant.`"^
footnote:[Matt. 20:26.]

[.numbered]
IX. There is but one place to be found in the Holy Scripture,
// lint-disable invalid-characters "κλήρυς"
where the word _Clerus_ (κλήρυς), can properly be applied to the church,
and they have got it to themselves; from whence they call themselves the clergy, that is,
the inheritance or heritage of God.
Whereas Peter exhorts the ministers of the gospel,
"`Not to be lords over God`'s heritage, nor to feed them for filthy lucre.`"^
footnote:[1 Peter 5:2-3.]
Peter belike, foresaw pride and avarice to be the ministers`' temptations;
and indeed they have often proved their fall: and to say true,
they could hardly fall by worse.
Nor is there any excuse to be made for them in these two respects,
which is not worse than their sin.
For if they have not been lords over God`'s heritage,
it is because they have made themselves that heritage, and disinherited the people:
so that now they may be the people`'s lords,
with a salvo to good old Peter`'s exhortation.

And for the other sin of avarice, they can only avoid it, and speak truth thus;
that never feeding the flock, they cannot be said to feed it for lucre: that is,
they get the people`'s money for nothing.
An example of which is given us, by the complaint of God himself,
from the practice of the proud, covetous, false prophets of old,
that the people gave their money for that which was not bread,
and their labour for that which did not profit them:^
footnote:[Isa. 55:2.]
And why?
Because then the priest had no vision; and too many now despise it.

[.numbered]
X+++.+++ But alas! when all is done, what folly, as well as irreligion, is there in pride!
It cannot add one cubit to any man`'s stature: what crosses can it hinder?
What disappointments help, or harm frustrate?
It delivers not from the common stroke; sickness disfigures, pain misshapes,
and death ends the proud man`'s fabric.
Six feet of cold earth bounds his big thoughts; and his person,
that was too good for any place,
must at last lodge within the streight limits of so little and so dark a cave:
and he who thought nothing well enough for him,
is quickly the entertainment of the lowest of all animals, even worms themselves.
Thus pride and pomp come to the common end; but with this difference,
less pity from the living, and more pain to the dying.
The proud man`'s antiquity cannot secure him from death, nor his heraldry from judgment.
Titles of honour vanish at this extremity; and no power or wealth,
no distance or respect, can rescue or insure them.
As the tree falls, it lies; and as death leaves men, judgment finds them.

[.numbered]
XI. O! what can prevent this ill conclusion?
And what can remedy this woeful declension from ancient meekness, humility, and piety,
and that godly life and power which were so conspicuous in the
authority of the preachings and examples of the living,
of the first and purest ages of Christianity?
Truly, nothing but an inward and sincere examination,
by the testimony of the holy light and spirit of Jesus,
of the condition of their souls and minds towards Christ,
and a better inquiry into the matter and examples of holy record.
It was his complaint of old, "`that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.`"^
footnote:[John 3:19.]
If thou wouldst be a child of God, and a believer in Christ,
thou must be a child of Light.
O man, thou must bring thy deeds to it and examine them by that holy lamp in thy soul,
which is the candle of the Lord, that shows thee thy pride and arrogancy,
and reproves thy delight in the vain fashions of this world.
Religion is a denial of self; yea, of self-religion too.
It is a firm tie or bond upon the soul to holiness, whose end is happiness;
for by it men come to see the Lord.
The pure in heart, says Jesus, see God:^
footnote:[Matt. 5:8.]
he that once comes to bear Christ`'s yoke,
is not carried away by the devil`'s allurements;
he finds excelling joys in his watchfulness and obedience.
If men loved the cross of Christ, his precepts and doctrine,
they would cross their own wills, which lead them to break Christ`'s holy will,
and lose their own souls,
in doing the devil`'s. Had Adam minded that holy
light in Paradise more than the serpent`'s bait;
and stayed his mind upon his Creator, the rewarder of fidelity,
he had seen the snare of the enemy, and resisted him.
O do not delight in that which is forbidden!
Look not upon it, if thou wouldst not be captivated by it.
Bring not the guilt of sins of knowledge upon thy own soul.
Did Christ submit his will to his Father`'s, and for the joy that was set before him,
endure the cross and despise the shame^
footnote:[Heb. 12:2.]
of a new and untrodden way to glory?
Thou also must submit thy will to Christ`'s holy law and light in thy heart,
and for the reward He sets before thee, to wit, eternal life, endure his cross,
and despise the shame of it.
All desire to rejoice with Him, but few will suffer with Him, or for Him.
Many are the companions of his table; not many of his abstinence.
The loaves they follow, but the cup of his agony they leave: it is too bitter,
they like not to drink thereof.
And divers will magnify his miracles, that are offended at the ignominy of his cross.
But O man, as He, for thy salvation, so thou, for the love of Him, must humble thyself,^
footnote:[Phil. 2:7.]
and be contented to be of no reputation, that thou mayest follow Him, not in a carnal,
formal way, of vain man`'s tradition and prescription, but as the Holy Ghost,
by the apostle, doth express it, in a new and living way,^
footnote:[Heb. 10:19-20.]
which Jesus had consecrated, that brings all that walk in it to the eternal rest of God:
whereunto He himself is entered, who is the holy and only blessed Redeemer.

====
