== Chapter XIII.

1+++.+++ Avarice, the second capital lust,
its definition and distinction.--2. It consists in a desire
of unlawful things.--3. As in David`'s case about Uriah`'s
wife.--4. Also Ahab`'s about Naboth`'s vineyard.--5. Next,
in unlawful desires of lawful things.--6. Covetousness is a mark of false prophets.--7.
A reproach to religion.--8. An enemy to government.--9. Treacherous.--10. Oppressive.--11.
Judas an example.--12. So Simon Magus.--13. Lastly,
in unprofitable hoarding of money.--14. The covetous man a common
evil.--15. His hypocrisy.--16. Gold his god.--17. He is sparing,
to death.--18. Is reproved by Christ and his followers.--19. Ananias`'
and Sapphira`'s sin and judgment.--20. William Tindall`'s discourse on
that subject referred unto.--21. Peter Charron`'s testimony against it.--22.
Abraham Cowley`'s witty and sharp satire upon it.

I+++.+++ I am come to the second part of this discourse, which is avarice, or covetousness,
an epidemic and a raging distemper in the world,
attended with all the mischiefs that can make men miserable in themselves,
and in society; so near akin to the foregoing evil, pride, that they are seldom apart:
Liberality being almost as hateful to the proud, as to the covetous,
I shall define it thus: Covetousness is the love of money or riches;^
footnote:[Eph. 5:3-5.]
which, as the apostle hath it, "`is the root of all evil.`"^
footnote:[1 Tim. 6:9-10.]
It branches itself into these three parts: first, desiring of unlawful things; secondly,
unlawfully desiring of lawful things; and lastly, hoarding up,
or unprofitably withholding the benefit of them from the relief of private persons,
or the public.
I shall first deliver the sense of Scripture,
and what examples are therein afforded against this impiety: and next, my own reasons,
with some authorities from authors of credit.
By which it will appear,
that the working of the love of riches out of the hearts of people,
is as much the business of the cross of Christ,
as the rooting out of any one sin that man is fallen into.

II. And first, of desiring, or coveting of unlawful things:
it is expressly forbidden by God himself,
in the law He delivered to Moses upon Mount Sinai,
for a rule to his people the Jews to walk by: "`Thou shalt not covet,`" said God,
"`thy neighbour`'s house: thou shalt not covet thy neighbour`'s wife,
nor his man-servant, nor his maid-servant, nor his ox, nor his ass,
nor anything that is thy neighbour`'s.`"^
footnote:[Exodus, xx.]
This God confirmed by thundering and lightnings, and other sensible solemnities,
to strike the people with more awe in receiving and keeping of it,
and to make the breach of these moral precepts more terrible to them.
Micah complains in his time, "`They covet fields, and take them by violence;`"^
footnote:[Mic. 2:2.]
but their end was misery.
Therefore was it said of old,
"`Woe to them that covet an evil covetousness:`" this is to our point.
We have many remarkable instances of this in Scripture;
two of which I will briefly report.

III.
David, though otherwise a good man, by unwatchfulness is taken;
the beauty of Uriah`'s wife was too hard for him, being disarmed,
and off from his spiritual watch.
There was no dissuasive would do; Uriah must be put upon a desperate service,
where it was great odds if he survived it.
This was to hasten the unlawful satisfaction of his desires,
by a way that looked not like direct murder.
The contrivance took; Uriah is killed,
and his wife is quickly David`'s. This interpreted David`'s covetousness.
But went it off so?
No, his pleasure soon turned to anguish and bitterness of spirit:
his soul was overwhelmed with sorrow: the waves went over his head:^
footnote:[Psalm li; lxxvii; xlii.
7.]
he was consumed within him: he was stuck in the mire and clay; he cried, he wept: yea,
his eyes were as a fountain of tears.^
footnote:[Ibid.
lxix.
2, 14.]
Guiltiness was upon him, and he must be purged; his sins washed white as snow,
that were as red as crimson, or he is undone forever.
His repentance prevailed: behold, what work this part of covetousness makes!
What evil!
What sorrow!
O that the people of this covetousness would let the sense
of David`'s sorrow sink deep into their souls,
that they might come to David`'s salvation!
Restore me, saith that good man: it seems he once knew a better state: yes,
and this may teach the better sort to fear, and stand in awe too, lest they sin and fall.
For David was taken at a disadvantage; he was off his watch, and gone from the cross;
the law was not his lamp and light, at that instant; he was a wanderer from his safety,
his strong tower, and so surprised: then and there it was the enemy met him,
and vanquished him.

IV. The second instance is that of Naboth`'s vineyard:^
footnote:[1 Kings, xxi.]
it was coveted by Ahab and Jezebel: that, which led them to such an unlawful desire,
found means to accomplish it.
Naboth must die, for he would not sell it.
To do it they accuse the innocent man of blasphemy, and find two knights of the post,
sons of Belial, to evidence against him.
Thus, in the name of God, and in show of pure zeal to his glory, Naboth must die;
and accordingly was stoned to death.
The news of which coming to Jezebel, she bid Ahab arise and take possession,
for Naboth was dead.
But God followed both of them with his fierce vengeance.
"`In the place where the dogs licked the blood of Naboth,`" said Elijah,
in the name of the Lord, "`shall dogs lick thy blood, even thine;
and I will bring evil upon thee, and take away thy posterity;`" and of Jezebel,
his wife and partner in his covetousness and murder, he adds,
"`The dogs shall eat her flesh by the walls of Jezreel.`"
Here is the infamy and punishment due to this part of covetousness.
Let this deter those that desire unlawful things, the rights of others:
for God that is just, will certainly repay such with interest in the end.
But perhaps these are few; either that they do not, or dare not show it,
because the law will bite if they do.
But the next part hath company enough,
that will yet exclaim against the iniquity of this part of covetousness;
and by their seeming abhorrence of it, would excuse themselves of all guilt in the rest:
let us consider that.

V+++.+++ The next,
and most common part of covetousness is the unlawful desire of lawful things;
especially of riches.
Money is lawful, but the love of it is the root of all evil.
So riches are lawful, but they that pursue them, fall into divers temptations, snares,
and lusts; He calls them uncertain, to show their folly and danger,
that set their hearts upon them.
Covetousness is hateful to God;
he hath denounced great judgments upon those that are guilty of it.
God charged it on Israel of old, as one of the reasons of his judgments;
"`For the iniquity of his covetousness,`" saith God, "`was I wroth and smote him.`"^
footnote:[Isa. 57:17.]
In another place, "`Every one is given to covetousness,
and from the prophet to the priest, every one dealeth falsely;`"^
footnote:[Jer. 6:13.]
"`therefore will I give their wives unto others,
and their fields to them that shall inherit them.`"^
footnote:[Ibid.
viii.
10.]
In another place God complained thus:
"`But thine eyes and thine heart are not but for thy covetousness.`"^
footnote:[Chap.
xxii.
17.]
By Ezekiel, God renews and repeats his complaint against their covetousness:
"`And they come to thee as the people cometh, and sit before thee as my people:
they hear thy words, but will not do them; with their mouths they show much love,
but their heart goeth after their covetousness.`"^
footnote:[Ezek. 33:31.]
Therefore God, in the choice of magistrates, made it part of their qualification,
to hate covetousness;
foreseeing the mischief that would follow to that society
or government where covetous men were in power;
that self would bias them, and they would seek their own ends at the cost of the public.
David desired, that his heart might not incline to covetousness,
but to the testimonies of his God.^
footnote:[Ps. 119:36.]
And the wise man expressly tells us,
that "`he that hateth covetousness shall prolong his days:`"^
footnote:[Prov. 28:16.]
making a curse to follow it.
And it is by Luke charged upon the Pharisees as a mark of their wickedness: and Christ,
in that evangelist, bids his followers "`Take heed and beware of covetousness:`"^
footnote:[Luke 12:15.]
and he giveth a reason for it that carrieth a most excellent instruction in it; for,
saith he,
"`a man`'s life consisteth not in the abundance of the things which he possesseth:`"^
footnote:[Mark 7:21-22.]
but he goeth further; he joins covetousness with adultery, murder, and blasphemy.
No wonder then if the apostle Paul is so liberal in his censure of this evil:
he placeth it with all unrighteousness, to the Romans;
to the Ephesians he writeth the like, adding,
"`Let not covetousness be so much as named among you:`"^
footnote:[Rom. 1:29; Eph. 5:3.]
and bids the Colossians mortify their members;^
footnote:[Col. 3:5.]
and names several sins, as fornication, uncleanness, and such like,
but ends with covetousness: which, saith he, is idolatry.
And we know there is not a greater offence against God: nay,
this very apostle calls "`the love of money the root of all evil;`" "`which,`" said he,
"`whilst some have coveted after, they have erred from the faith,
and pierced themselves through with many sorrows.
For they that will be rich, fall into temptation, and a snare,
and many foolish and hurtful lusts.
O man of God,`" saith he to his beloved friend Timothy, "`flee these things,
and follow after righteousness, faith, patience, and meekness,`"

VI. Peter was of the same mind;
for he maketh covetousness to be one of the great marks of the
false prophets and teachers that should arise among Christians,
and by that they might know them, "`who,`" saith he,
"`through covetousness shall with feigned words make merchandise of you.`"^
footnote:[2 Peter 2:3.]
To conclude, therefore, the author to the Hebrews, at the end of his epistle,
leaves this, with other things, not without great zeal and weight upon them:
"`Let,`" says he,
"`your conversation be without covetousness;`" he rests not in this generality,
but goes on, "`and be content with such things as ye have; for God hath said,
I will never leave thee nor forsake thee.`"^
footnote:[Heb. 13:5.]
What then?
Must we conclude that those who are not content, but seek to be rich, have forsaken God?
The conclusion seems hard; but yet it is natural; for such, it is plain,
are not content with what they have; they would have more: they covet to be rich,
if they may:
they live not with that dependence and regard to Providence to which they are exhorted,
nor is godliness, with content, great gain to them.

VII.
And truly it is a reproach to a man, especially to a religious man,
that he knows not when he hath enough; when to leave off; when to be satisfied:
that notwithstanding God sends him one plentiful season of grain after another,
he is so far from making that the cause of withdrawing from the traffic of the world,
that he makes it a reason for launching further into it; as if the more he hath,
the more he may.
He therefore reneweth his appetite, bestirs himself more than ever,
that he may have a share in the scramble, while anything is to be got:
this is as if cumber, not retirement; and gain, not content,
were the duty and comfort of a Christian.
O that this thing were better considered! for by
not being so observable nor obnoxious to the law,
as other vices are, there is more danger for want of that check.
It is plain that most people strive not for substance, but for wealth.
Some there be that love it strongly, and spend it liberally when they have got it.
Though this be sinful, yet more commendable than to love money for money`'s sake;
that is one of the basest passions the mind of man can be captivated with;
a perfect lust; and a greater,
and more soul-defiling one there is not in the whole catalogue of concupiscence.
Which considered, should quicken people into a serious examination,
how far this temptation of love of money hath entered them;
and the rather because the steps it maketh into the mind, are almost insensible,
which renders the danger greater.
Thousands think themselves unconcerned in the caution,
that yet are perfectly guilty of the evil.
Now can it be otherwise, when those that have, from a low condition, acquired thousands,
labour yet to advance, yea, double and treble those thousands;
and that with the same care and contrivance by which they got them?
Is this to live comfortably, or to be rich?
Do we not see how early they rise; how late they go to bed?
How full of the change, the shop, the warehouse, the custom-house; of bills, bonds,
charter-parties, etc. they are?
Running up and down, as if it were to save the life of a condemned innocent.
An insatiable lust, and therein ungrateful to God, as well as hurtful to men,
who giveth it to them to use, and not to love: that is, the abuse.
And if this care, contrivance, and industry, and that continually,
be not from the love of money in those that have ten times more than they began with,
and much more than they spend or need,
I know not what testimony man can give of his love for anything.

VIII.
To conclude: It is an enemy to government in magistrates; for it tends to corruption.
Wherefore those that God ordained were such as feared Him and hated covetousness.
Next, it hurts society: for old traders keep the young ones poor:
and the great reason why some have too little,
and so are forced to drudge like slaves to feed their families,
and keep their chin above the water, is,
because the rich hold fast and press to be richer, and covet more,
which dries up the little streams of profit from smaller folks.
There should be a standard, both as to the value and time of traffic;
and then the trade of the master to be shared among his servants that deserve it.
This were both to help the young to get their livelihood,
and to give the old time to think of leaving this world well,
in which they have been so busy, that they might obtain a share in the other,
of which they have been so careless.

IX. There is yet another mischief to government;
for covetousness leads men to abuse and defraud it,
by concealing or falsifying the goods they deal in:
as bringing in forbidden goods by stealth: or lawful goods,
so as to avoid the payment of dues, or owning the goods of enemies for gain;
or that they are not well made, or full of measure;
with abundance of that sort of deceit.

X+++.+++ But covetousness has caused destructive feuds in families;
for estates falling into the hands of those whose avarice has put them
upon drawing greater profit to themselves than was consistent with justice,
has given birth to much trouble, and caused great oppression; it too often falling out,
that such executors have kept the right owners out
of possession with the money they should pay them.

XI. But this is not all; for covetousness betrays friendship;
a bribe cannot be better placed to do an ill thing, or undo a man.
Nay, it is too often a murderer both of soul and body; of the soul,
because it kills that life it should have in God: where money masters the mind,
it extinguishes all love to better things: of the body, for it will kill for money,
by assassinations, poisons, false witness, etc.
I shall end this head on covetousness, with the sin and doom of two covetous men, Judas,
and Simon the sorcerer.

Judas`'s religion fell in thorny ground: love of money choked him.
Pride and anger in the Jews endeavoured to murder Christ;
but till covetousness set her hand to effect it, they were all at a loss.
They found Judas had the bag, and probably loved money; they would try him, and did.
The price was set, and Judas betrays his Master, his Lord,
into the hands of his most cruel adversaries.
But to do him right he returned the money, and to be revenged on himself,
was his own hangman.
A wicked act, a wicked end.
Come on, you covetous: what say you now to brother Judas?
was he not an ill man?
did he not very wickedly?
Yes, yes: would you have done so?
No, no: by no means.
Very well; but so said those wicked Jews of stoning the prophets,
and that yet crucified the beloved Son of God; He that came to save them,
and would have done it, if they had received Him,
and not rejected the day of their visitation.
Rub your eyes well, for the dust is got into them;
and carefully read in your own consciences, and see if, out of love to money,
you have not betrayed the Just One in yourselves,
and so are brethren with Judas in iniquity.
I speak for God against an idol; bear with me.
Have you not resisted, yea,
quenched the good Spirit of Christ in your pursuit after your beloved wealth?
Examine yourselves, try yourselves; know ye not your own selves: if Christ dwell not,
if He rule not, and be not above all beloved in you, ye are reprobates:
in an undone condition!^
footnote:[2 Cor. 13:5.]

XII.
The other covetous man is Simon the sorcerer, a believer too:
but his faith could not go deep enough for covetousness.^
footnote:[Acts 8:9-24.]
He would have driven a bargain with Peter: so much money for so much Holy Ghost;
that he might sell it again, and make a good trade of it;
corruptly measuring Peter by himself,
as if he had only a better knack of cozening the people than himself,
who had set up in Samaria for the great power of God,
before the power of God in Philip and Peter undeceived the people.
But what was Peter`'s answer and judgment?
"`Thy money,`" says he, "`perish with thee;
thou hast neither part nor lot in this matter: thou art in the gall of bitterness,
and in the bond of iniquity.`"
A dismal sentence.
Besides, covetousness tends to luxury, and rises often out of it: for from having much,
they spend much, and so become poor by luxury: such are covetous to get, to spend more,
which temperance would prevent.
For if men would not, or could not, by good laws well executed, and a better education,
be so lavish in their tables, houses, furniture, apparel, and gaming,
there would be no such temptation to covet earnestly after what they could not spend:
for there is but here and there a miser that loves money for money`'s sake.

XIII.
Which leads to the last and basest part of covetousness, which is yet the most sordid,
to wit, hoarding up, or keeping money unprofitably, both to others and themselves too.
This is Solomon`'s miser, "`that makes himself rich, and hath nothing:`"^
footnote:[Prov. 17:7]
a great sin in the sight of God.
He complained of such as had stored up the labours of the poor in their houses;
he calls it their spoils, and it is a grinding of the poor,
because they see it not again.
But he blesseth those that consider the poor, and commandeth every one,
to open freely to his brother that is in need;^
footnote:[Ps. 41:1; Duet. 15:7-8.]
not only he that is spiritually, but naturally so;
and not to withhold his gift from the poor.
The apostle chargeth Timothy, in the sight of God, and before Jesus Christ,
that "`he fail not to charge them that are rich in this world,
that they trust not in their uncertain riches, but in the living God,
who giveth liberally; and that they do good with them,
that they may be rich in good works.`"^
footnote:[1 Tim. 6:17-18.]
Riches are apt to corrupt; and that which keeps them sweet and best is charity:
he that uses them not gets them not for the end for which they are given,
but loves them for themselves, and not their service.
The miser is poor in his wealth: he wants for fear of spending;
and increases his fear with his hope, which is his gain;
and so tortures himself with his pleasure;
the most like to the man that hid his talent in a napkin, of all others,
for this man`'s talents are hid in his bags out of sight, in vaults, under boards,
behind wainscots: else upon bonds and mortgages, growing but as underground;
for it is good to none.

XIV.
The covetous man hates all useful arts and sciences as vain,
lest they should cost him something the learning:
wherefore ingenuity has no more place in his mind than in his pocket.
He lets houses fall, to prevent the charge of repairs: and for his spare diet,
plain clothes, and mean furniture, he would place them to the account of moderation.
O monster of a man! that can take up the cross for covetousness, and not for Christ.

XV. But he pretends negatively to some religion too; for he always rails at prodigality,
the better to cover his avarice.
If you would bestow a box of spikenard on a good man`'s head; to save money,
and to seem righteous, he tells you of the poor: but if the poor come,
he excuses his want of charity with the unworthiness of the object,
or the causes of his poverty,
or that he can bestow his money upon those that deserve it better;
who rarely opens his purse till quarter-day for fear of losing it.

XVI.
But he is more miserable than the poorest; for he enjoys not what he yet fears to lose;
they fear not what they do not enjoy.
Thus is he poor by overvaluing his wealth:
but he is wretched that hungers with money in a cook`'s shop:
yet having made a god of his gold, who knows,
but he thinks it unnatural to eat what he worships?

XVII.
But, which aggravates this sin, I have myself once known some,
that to get money have wearied themselves into the grave;
and to be true to their principle, when sick would not spare a fee to a doctor,
to help the poor slave to live; and so died to save charges:
a constancy that canonizes them martyrs for money.

XVIII.
But now let us see what instances the Scripture will give
us in reproof of the sordid hoarders and hiders of money.
A good-like young man came to Christ, and inquired the way to eternal life:
Christ told him, he knew the commandments: he replied, he had kept them from his youth:
it seems he was no loose person, and indeed such are usually not so, to save charges.
And "`yet lackest thou one thing,`" saith Christ; "`sell all, distribute it to the poor,
and thou shalt have treasure in heaven,
and come and follow Me.`" It seems Christ pinched him in the sore place; He hit the mark,
and struck him to the heart: who knew his heart;
by this He tried how well he had kept the commandment, "`To love God above all.`"
It was said, the young man was very sorrowful, and went his way;
and the reason which is given is, that he was very rich.
The tides met, money and eternal life: contrary desires: but which prevailed?
Alas! his riches.
But what said Christ to this?
How hardly shall they that have riches enter into the kingdom of God!
He adds, "`It is easier for a camel to go through a needle`'s eye,
than for a rich man to enter the kingdom of heaven:`" that is, such a rich man, to wit,
a covetous rich man, to whom it is hard to do good with what he has:
it is more than a miracle: O who then would be rich and covetous!
It was upon these rich men that Christ pronounced his woe, saying,
"`Woe unto you that are rich, for ye have received your consolation here.`"
What! none in the heavens?
No, unless you become willing to be poor men, can resign all, live loose to the world,
have it at arm`'s end, yea, under foot; a servant, and not a master.

XIX.
The other instance is a very dismal one too: it is that of Ananias and Sapphira.
In the beginning of the apostolical times,
it was customary for those who received the word of life,
to bring what substance they had and lay it at the apostles`' feet: of these Joses,
surnamed Barnabas, was exemplary.
Among the rest, Ananias and his wife Sapphira, confessing to the truth,
sold their possession,
but covetously reserved some of the purchase-money from the common purse to themselves,
and brought a part for the whole, and laid it at the apostles`' feet.
But Peter, a plain and bold man, in the majesty of the Spirit, said, "`Ananias,
why hath Satan filled thine heart to lie to the Holy Ghost;
and to keep back part of the price of the land?
Whilst it remained, was it not thine own?
And after it was sold, was it not in thine own power?
Why hast thou conceived this thing in thine heart?
Thou hast not lied unto men, but unto God.`"^
footnote:[Acts 5:3-4.]
But what followed this covetousness and hypocrisy of Ananias?
Why, "`Ananias hearing these words, fell down, and gave up the ghost.`"
The like befel his wife, being privy to the deceit their avarice had led them to.
And it is said, that "`great fear came upon all the church,
and those that heard of these things:`" and also should on those that now read them.
For if this judgment was shown and recorded that we should beware of the like evils,
what will become of those who, under the profession of Christianity,
a religion that teaches men to live loose from the world,
and to yield up all to the will and service of Christ and his kingdom,
not only retain a part, but all; and cannot part with the least thing for Christ`'s sake?
I beseech God to incline the hearts of my readers to weigh these things.
This had not befallen Ananias and Sapphira, if they had acted as in God`'s presence,
and with that entire love, truth, and sincerity that became them.
O that people would use the light that Christ has given them,
to search and see how far they are under the power of this iniquity!
For would they but watch against the love of the world,
and be less in bondage to the things that are seen, which are temporal,
they would begin to set their hearts on things above, that are of an eternal nature.
Their life would be hid with Christ in God,
out of the reach of all the uncertainties of time, and troubles,
and changes of mortality.
Nay, if people would but consider how hardly riches are got,
how uncertainly they are kept, the envy they bring;
that they can neither make a man wise, nor cure diseases, nor add to life,
much less give peace in death; no,
nor hardly yield any solid benefit above food or raiment,
(which may be had without them,) and that if there be any good use for them,
it is to relieve others in distress;
being but stewards of the plentiful providences of God,
and consequently accountable for our stewardship; if, I say,
these considerations had any room in our minds, we should not thus post to get,
nor care to hide and keep such a mean and impotent thing.
O that the cross of Christ, which is the Spirit and power of God in man,
might have more place in the soul, that it might crucify us more and more to the world,
and the world to us; that, like the days of paradise,
the earth might again be the footstool, and the treasure of the earth a servant,
and not a god to man!--Many have written against this vice; three I will mention.

XX. William Tindall, that worthy apostle of the English reformation,
has an entire discourse, to which I refer the reader, entitled,
The Parable of the Wicked Mammon.
The next is--

XXI.
Peter Charron, a famous Frenchman, and in particular for the book he wrote of wisdom,
hath a chapter against covetousness; part of which take as followeth:
"`To love and affect riches is covetousness: not only the love and affection,
but also every over-curious care and industry about riches.
The desire of goods, and the pleasure we take in possessing them,
are grounded only upon opinion:
the immoderate desire to get riches is a gangrene in our soul,
which with a venomous heat consumeth our natural affections,
to the end it might fill us with virulent humours.
So soon as it is lodged in our hearts, all honest and natural affection,
which we owe either to our parents, our friends, or ourselves, vanisheth away:
all the rest, in respect of our profit, seemeth nothing; yea, we forget in the end,
and condemn ourselves, our bodies, our minds, for this transitory trash;
and as our proverb is, We sell our horse to get us hay.
Covetousness is the vile and base passion of vulgar fools,
who account riches the principal good of a man, and fear poverty as the greatest evil;
and not contenting themselves with necessary means, which are forbidden no man,
weigh that which is good in a goldsmith`'s balance;
when nature hath taught us to measure it by the ell of necessity.
For, what greater folly can there be than to adore that
which nature itself hath put under our feet,
and hidden in the earth, as unworthy to be seen; yea, rather to be contemned,
and trampled under foot?
This is that which the sin of man hath only torn out of the entrails of the earth,
and brought unto light to kill himself.
We dig out the earth, and bring to light those things for which we would fight:
we are not ashamed to esteem those things most highly
which are in the lowest parts of the earth.
Nature seemeth even in the first birth of gold, after a sort,
to have presaged the misery of those that are in love with it;
for it hath so ordered the matter,
that in those countries where it groweth there groweth with it neither grass nor plant,
nor other thing that is worth anything: as giving us to understand thereby,
that in those minds where the desire of this metal groweth,
there cannot remain so much as a spark of true honour and virtue.
For what thing can be more base than for a man to degrade,
and to make himself a servant and a slave to that which should be subject unto him?
Riches serve wise men, but command a fool: for a covetous man serveth his riches,
and not they him: and he is said to have goods as he hath a fever,
which holdeth and tyrannizeth over a man, not he over it.
What thing more vile, than to love that which is not good, neither can make a good man?
Yea is common, and in the possession of the most wicked in the world;
which many times perverts good manners, but never amends them: without which,
so many wise men have made themselves happy;
and by which so many wicked men have come to a wicked end.
To be brief; what thing more miserable, than to bind the living to the dead,
as Mezentius did, to the end their death might be languishing, and the more cruel;
to tie the spirit unto the excrement and scum of the earth;
to pierce through his own soul with a thousand torments,
which this amorous passion of riches brings with it;
and to entangle himself with the ties and cords of this malignant thing,
as the Scripture calls them, which doth likewise term them thorns and thieves,
which steal away the heart of man, snares of the devil, idolatry,
and the root of all evil?
And truly he that shall see the catalogue of those envies and molestations
which riches engender into the heart of man,
as their proper thunderbolt and lightning,
they would be more hated than they are now loved.
Poverty wants many things, but covetousness all: a covetous man is good to none,
but worse to himself.`"
Thus much of Charron, a wise and great man.
My next testimony is yielded by an author not unlikely
to take with some sort of people for his wit;
may they equally value his morality, and the judgment of his riper time.

XXII.
Abraham Cowley, a witty and ingenious man, yieldeth us the other testimony:
of avarice he writeth thus: "`There are two sorts of avarice,
the one is but a bastard-kind, and that is a rapacious appetite of gain;
not for its own sake,
but for the pleasure of refunding it immediately
through all the channels of pride and luxury.
The other is the true kind, and properly so called,
which is a restless and insatiable desire of riches, not for any further end or use,
but only to hoard and preserve, and perpetually increase them.
The covetous man of the first kind, is like a greedy ostrich, which devoureth any metal,
but it is with an intent to feed upon it, and in effect,
it maketh a shift to digest and excern it.
The second is like the foolish chough, which loveth to steal money, only to hide it.
The first doth much harm to mankind, and a little good to some few:
the second doth good to none; no, not to himself.
The first can make no excuse to God or angels, or rational men, for his actions:
the second can give no reason or colour, not to the devil himself, for what he doth:
he is a slave to mammon without wages.
The first maketh a shift to be beloved, aye, and envied too, by some people:
the second is the universal object of hatred and contempt.
There is no vice hath been so pelted with good sentences, and especially by the poets,
who have pursued it with satires and fables, and allegories and allusions, and moved,
as we say, every stone to fling at it;
among which I do not remember a finer correction
than that which was given it by one line of Ovid`'s:

Multa

// lint-disable invalid-characters "æ"
Luxuriæ desunt, omnia avaritiæ.

Which is,

Much is wanting to luxury, all to avarice.

To which saying I have a mind to add one member, and render it thus: poverty wants some,
luxury many, avarice all things.
Somebody saith of a virtuous and wise man that having nothing, he hath all.
This is just his antipode, who having all things, yet hath nothing.

And O! what man`'s condition can be worse

Than his, whom plenty starves, and blessings curse?

The beggars but a common fate deplore,

The rich poor man`'s emphatically poor.

"`I wonder how it cometh to pass, that there hath never been any law made against him:
against him do I say?
I mean for him.
As there are public provisions made for all other madmen,
it is very reasonable that the king should appoint some persons to manage his estate,
during his life, for his heirs commonly need not that care,
and out of it to make it their business to see that
he should not want alimony befitting their condition;
which he could never get out of his own cruel fingers.
We relieve idle vagrants and counterfeit beggars,
but have no care at all of these really poor men, who are, methinks,
to be respectfully treated, in regard of their quality.
I might be endless against them,
but I am almost choked with the superabundance of the matter.
Too much plenty impoverisheth me, as it doth them.`"
Thus much against avarice, that moth of the soul, and canker of the mind.
