== Chapter XIV.

[.chapter-synopsis]
* 1+++.+++ Luxury, what it is, and the mischief of it to mankind. An enemy to the cross of Christ.
* 2+++.+++ Of luxury in diet, how unlike Christ, and contrary to Scripture.
* 3+++.+++ The mischief it does to the bodies, as well as the minds of people.
* 4+++.+++ Of luxury in the excess of apparel, and of recreations; that sin brought the first coat: people not to be proud of the badge of their misery.
* 5+++.+++ The recreations of the times, enemies to virtue: they rise from degeneracy.
* 6+++.+++ The end of clothes allowable; the abuse reprehended.
* 7+++.+++ The chief recreation of good men of old was to serve God, and do good to mankind, and follow honest vocations, not vain sports and pastimes.
* 8+++.+++ The Heathen knew and did better things. The sobriety of infidels above Christians.
* 9+++.+++ Luxury condemned in the case of the rich man.
* 10+++.+++ The doctrine of the Scripture positively against a voluptuous life.

[.numbered-group]
====

[.numbered]
I+++.+++ I am now come to the other extreme, and that is luxury,
which is an excessive indulgence of self, in ease and pleasure.
This is the last great impiety struck at in this discourse of the holy cross of Christ,
which indeed is much the subject of its mortifying virtue and power.
A disease as epidemical, as killing: it creeps into all stations and ranks of men:
the poorest often exceeding their ability to indulge their appetite;
and the rich frequently wallowing in those things
that please the lusts of their eye and flesh,
and the pride of life: as regardless of the severe discipline of Jesus,
whom they call Saviour, as if luxury, and not the cross, were the ordained way to heaven.
What shall we eat, what shall we drink, and what shall we put on?
once the care of luxurious heathens, is now the practice of, and which is worse,
the study of pretended Christians.
But let such be ashamed, and repent;
remembering that Jesus did not reproach the Gentiles for those things,
to indulge his followers in them.
They that will have Christ to be theirs, must be sure to be his; to be like-minded,
to live in temperance and moderation, as knowing the Lord is at hand.
Sumptuous apparel, rich unguents, delicate washes, stately furniture, costly cookery,
and such diversions as balls, masques, music-meetings, plays, romances, etc.,
which are the delight and entertainment of the times,
belong not to the holy path that Jesus and his true
disciples and followers trod to glory.
No, "`Through many tribulations,`" says none of the least of them,
"`must we enter the kingdom of God.`"^
footnote:[Acts 14:22.]
I do earnestly beseech the gay and luxurious,
into whose hands this discourse shall be directed,
to consider well the reasons and examples here advanced against their way of living;
if happily they may come to see how remote it is from true Christianity,
and how dangerous to their eternal peace.
God Almighty, by his grace, soften their hearts to instruction,
and shed abroad his tender love in their souls, that they may be overcome to repentance,
and to the love of the holy way of the cross of Jesus, the blessed Redeemer of men.
For they cannot think that He can benefit them,
while they refuse to lay down their sins for the love of
Him that laid down his life for the love of them.
Or that He will give them a place in heaven, that refuse Him any in their hearts on earth.
But let us examine luxury in all its parts.

[.numbered]
II. Luxury has many parts; the first that is forbidden by the self-denying Jesus,
is gluttony, "`Take no thought, saying, What shall we eat,
or what shall we drink?--for after these things do the Gentiles seek:`"^
footnote:[Matt. 6:31-32.]
as if He had said, The Heathen, such as live without the true God,
whose care is to please their appetite, more than to seek God and his kingdom:
you must not do so, but "`seek ye first the kingdom of God, and his righteousness,
and all these things shall be added unto you.`"^
footnote:[Matt. 6:33.]
That which is convenient for you will follow: let everything have its time and order.

This carries a serious reprehension to the luxurious eater and drinker,
who is taken up with an excessive care of his palate, what shall he eat,
and what shall he drink: who being often at a loss what to have next,
therefore has an officer to invent, and a cook to dress, disguise, and drown the species,
that it may cheat the eye, look new and strange; and all to excite an appetite,
or raise an admiration.
To be sure there is great variety, and that curious and costly; the sauce, it may be,
dearer than the meat; and so full is he fed,
that without it he can scarce find out a stomach; which is to force a hunger,
rather than to satisfy it.--And as he eats, so he drinks: rarely for thirst,
but pleasure: to please his palate.
For that purpose he will have divers sorts, and he must taste them all: one,
however good, is dull and tiresome; variety is more delightful than the best;
and therefore the whole world is little enough to fill his cellar.
But were he temperate in his proportions,
his variety might be imputed rather to curiosity than luxury.
But what the temperate man uses as a cordial, he drinks by full draughts,
till inflamed by excess, he is fitted to be an instrument of mischief,
if not to other persons, yet always to himself, whom perhaps at last he knows not:
for such brutality are some come to, they will sip themselves out of their own knowledge.
This is the lust of the flesh, that is not of the Father, but of the world;
for upon this comes in the music and dance, and mirth, and the laughter,
which is madness;^
footnote:[Ecc. 2:2.]
that the noise of one pleasure may drown the iniquity of another,
lest his own heart should deal too plainly with him.
Thus the luxurious live: they forget God, they regard not the afflicted.
O that the sons and daughters of men would consider
their wantonness and their iniquity in these things!
How ill do they requite the goodness of God in the
use and abuse of the plenty He yields them!
How cruel are they to his creatures, how lavish of their lives and virtue,
how thankless for them: forgetting the Giver, and abusing his gifts,
and despising counsel, and casting instruction behind them!
They lose tenderness and forget duty, being swallowed up of voluptuousness,
adding one excess to another.
God rebuked this sin in the Jews, by the prophet Amos:
"`Ye that put far away the evil day, and cause the seat of violence to come near;
that lie upon beds of ivory, and stretch themselves upon their couches,
and eat the lambs out of the flock, and the calves out of the stall;
that chant to the sound of the viol, and invent to themselves instruments of music,
like David; that drink wine in bowls, and anoint themselves with the chief ointments;
but they are not grieved for the affliction of Joseph.`"^
footnote:[Amos 6:3-6.]
These, it seems, were the vices of the degenerate Jews,
under all their pretence to religion; and are they not of Christians at this day?
Yea they are, and these are the great parts of luxury struck at in this discourse.
Remember the rich man, with all his sumptuous fare, went to hell:
and the apostle pronounces heavy woes upon those "`whose god is their belly:
for such glory in their shame.`"^
footnote:[Phil. 3:19.]

Christ places these things to the courts of worldly kings, not his kingdom:
making them unseemly in his followers: his feast therefore, to the multitude,
which was his miracle, was plain and simple; enough,
but without curiosity or art of cookery: and it went down well, for they were hungry;
the best and fittest time to eat.
And the apostle, in his directions to his much-beloved Timothy,
debases the lovers of worldly fulness;
advising him to godliness and content as the chiefest gain: adding,
"`and having food and raiment, let us therewith be content.`"^
footnote:[1 Tim. 6:6,8.]
Behold the abstemious, and most contented life of those pilgrims, the sons of heaven,
and immortal offspring of the great power of God; they were in fasts and perils often,
and ate what was set before them; and in all conditions learned to be contented.
O blessed men!
O blessed spirits!
Let my soul dwell with yours forever.

[.numbered]
III.
But the diseases which luxury begets and nourishes, make it an enemy to mankind:
for besides the mischief it brings to the souls of people, it undermines health,
and shortens the life of man,
in that it gives but ill nourishment and so leaves and feeds corrupt humours,
whereby the body becomes rank and foul, lazy and scorbutic; unfit for exercise,
and more for honest labour.
The spirits being thus loaded with ill flesh, and the mind effeminated,
a man is made inactive, and so useless in civil society; for idleness follows luxury,
as well as diseases.
These are the burdens of the world, devourers of good things, self-lovers,
and so forgetters of God: but which is sad, and yet just,
the end of those that forget God, is to be turned into hell.^
footnote:[Ps. 9:19.]

[.numbered]
IV. But there is another part of luxury that has great place with vain man and woman,
and that is the gorgeousness of apparel, one of the most foolish, because most costly,
empty, and unprofitable excesses people can well be guilty of.
We are taught by the scriptures of truth to believe that sin brought the first coat;
and if consent of writers be of force, it was as well without as within:
to those that so believe, I direct my discourse, because they, I am sure,
are the generality.
I say, if sin brought the first coat,
poor Adam`'s offspring have little reason to be proud or curious in their clothes;
for it seems their original was base,
and the finery of them will neither make them noble, nor man innocent again.`"^
footnote:[Gen. 3:21.]
But doubtless blessed was that time, when innocence, not ignorance,
freed our first parents from such shifts: they were then naked and knew no shame;
but sin made them ashamed to be longer naked.
Since therefore guilt brought shame, and shame an apron and a coat,
how very low are they fallen, that glory in their shame,
that are proud of their fall! for so they are that use care and cost to
trim and set off the very badge and livery of that lamentable lapse.
It is all one, as for a man that had lost his nose by a scandalous distemper,
to take pains to set out a false one, in such shape and splendour,
as should give but the greater occasion for all to gaze upon him;
as if he would tell them, he had lost his nose, for fear they should think he had not.
But would a wise man be in love with a false nose, though ever so rich,
and however finely made: Surely no; and shall people that call themselves Christians,
shew so much love for clothes, as to neglect innocence, their first clothing?
Doth it not shew what cost of time, pains, and money,
people are at to set off their shame,
with the greatest shew and solemnity of folly is
it not to delight in the effect of that cause,
which they rather should lament?
If a thief were to wear chains all his life, would their being gold, and well made,
abate his infamy?
to be sure his being choice of them would increase it.
Why, this is the very case of the vain fashion-mongers of this shameless age;
yet will they be Christians, judges in religion, saints, what not?
O miserable state indeed to be so blinded by the lust of the eye, the lust of the flesh,
and the pride of life, as to call shame decency,
and to be curious and ex pensive about that which should be their humiliation.
And not only are they grown in love with these vanities,
and thereby express how wide they are from primitive innocence;
but it is notorious how many fashions have been and
are invented on purpose to excite lust:
which still puts them at a greater distance from a simple and harmless state,
and enslaves their minds to base concupiscence.

[.numbered]
V+++.+++ Nor is it otherwise with recreations, as they call them; for these are nearly related.
Man was made a noble, rational, grave creature; his pleasure stood in his duty,
and his duty in obeying God: which is to love, fear, adore, and serve Him;
and in using the creation with true temperance and godly moderation;
as knowing well that the Lord, his judge, was at hand,
the inspector and rewarder of his works.
In short, his happiness was in his communion with God;
his error was to leave that conversation,
and let his eyes wander abroad to gaze on transitory things.
If the recreations of the age were as pleasant and
necessary as they are said and made to be,
unhappy then would Adam and Eve have been, that never knew them.
But had they never fallen, and the world been tainted by their folly and ill example,
perhaps man had never known the necessity or use of many of these things.
Sin gave them birth, as it did the other; they were afraid of the presence of the Lord,
which was the joy of their innocency, when they had sinned;
and then their minds wandered, sought other pleasures, and began to forget God;
as He complained afterwards by the prophet Amos, "`They put far away the evil day:
they eat the fat of the flock: they drink wine in bowls:
they anoint themselves with the chief perfumes:
they stretch themselves upon beds of ivory: they chant to the sound of the viol,
and invent upon themselves instruments of music, like David,`"^
footnote:[Amos 6:3-6.]
not heeding or remembering the afflictions and captivity of poor Joseph:
him they wickedly sold, innocency was quite banished,
and shame soon began to grow a custom, till they were grown shameless in the imitation.
And truly, it is now no less a shame to approach primitive innocence by modest plainness,
than it was matter of shame to Adam that he lost it,
and became forced to tack fig-leaves for a covering.
Wherefore in vain do men and women deck themselves with specious pretences to religion,
and flatter their miserable souls with the fair titles of Christian, innocent, good,
virtuous, and the like, whilst such vanities and follies reign.
Wherefore to you all, from the eternal God, I am bound to declare,
you mock Him that will not be mocked, and deceive yourselves;^
footnote:[Gal. 6:7.]
such intemperance must be denied, and you must know yourselves changed,
and more nearly approached to primitive purity,
before you can be entitled to what you do now but usurp;
for none but those who are led by the Spirit of God are the children of God,^
footnote:[Rom. 8:14; Gal. 5:23.]
which guides into all temperance and meekness.

[.numbered]
VI. But the Christian world, as it would be called, is justly reprovable,
because the very end of the first institution of apparel is grossly perverted.
The utmost service that clothes originally were designed for,
when sin had stripped them of their native innocence, was, as hath been said,
to cover them; therefore plain and modest: next, to fence out cold;
therefore substantial: lastly, to declare sexes; therefore distinguishing.
So that then necessity provoked to clothing, now, pride and vain curiosity;
in former times some benefit obliged, but now, wantonness and pleasure:
then they minded them for covering, but now, that is the least part;
their greedy eyes must be provided with gaudy superfluities:
as if they made their clothes for trimming, to be seen rather than worn;
only for the sake of other curiosities that must be tacked upon them,
although they neither fence from cold, nor distinguish sexes;
but signally display their wanton, fantastic, full-fed minds, that have them.

[.numbered]
VII.
Then the recreations were to serve God, be just, follow their vocations,
mind their flocks, do good,
exercise their bodies in such a manner as was suitable to gravity, temperance,
and virtue; but now that word is extended to almost every folly;
so much are men degenerated from Adam in his disobedience;
so much more confident and artificial are they grown in all impieties: yea, their minds,
through custom,
are become so very insensible of the inconveniency that attends the like follies,
that what was once mere necessity, is now the delight, pleasure, and recreation of age.
How ignoble is it, how ignominious and unworthy of a reasonable creature!
Man, who is endued with understanding, fit to contemplate immortality,
and made a companion (if not superior) to angels, that he should mind a little dust,
a few shameful rags; inventions of mere pride and luxury; toys so apish and fantastic,
entertainments so dull and earthly, that a rattle, a baby, a hobby-horse, a top,
are by no means so foolish in a simple child, not unworthy of his thoughts,
as are such inventions of the care and pleasure of men!
It is a mark of great stupidity that such vanities should exercise the noble mind of man,
and image of the great Creator of heaven and earth.

[.numbered]
VIII.
Of this many among the very Heathens of old had so
clear a prospect that they detested all such vanity,
looking upon curiosity in apparel, and that variety of recreations,
now in vogue and esteem with false Christians, to be destructive of good manners,
in that it more easily stole away the minds of people from sobriety to wantonness,
idleness, effeminacy, and made them only companions for the beast that perishes:
witness those famous men, Anaxagoras, Socrates, Plato, Aristides, Cato, Seneca,
Epictetus, etc.,
who placed true honour and satisfaction in nothing below virtue and immortality.
Nay, such are the remains of innocence among some Moors and Indians in our times,
that if a Christian (though he must be an odd one) fling out a filthy word,
it is customary with them, by way of moral, to bring him water to purge his mouth.
How much do the like virtues and reasonable instances accuse people,
professing Christianity, of gross folly and intemperance!
O that men and women had the fear of God before their eyes;
and that they were so charitable to themselves, as to remember whence they came,
what they are doing, and to what they must return: that so more noble, more virtuous,
more rational and heavenly things might be the matters of their pleasure and entertainment;
that they would be once persuaded to believe how inconsistent the folly, vanity,
and conversation they are mostly exercised in,
really are with the true nobility of a reasonable soul; and let that just principle,
which taught the Heathens, teach them;
lest it be found more tolerable for Heathens than such Christians, in the day of account.
For if their shorter notions,
and more imperfect sense of things could yet discover so much vanity;
if their degree of light condemned it, and they, in obedience thereunto, disused it,
doth it not behoove Christians much more?
Christ came not to extinguish, no, but to improve that knowledge:
and they who think they need do less now than before,
had need to act better than they think.
I conclude,
that the fashions and recreations now in repute are
very abusive of the end of man`'s creation;
and that the inconveniences that attend them, as wantonness, idleness, prodigality,
pride, lust, respect of persons, witness a plume of feathers, or a lace-coat,
in a country village, whatever be the man that wears them, with the like fruits,
are repugnant to the duty, reason, and true pleasure of man,
and absolutely in consistent with that wisdom, knowledge, manhood, temperance, industry,
which render man truly noble and good.

[.numbered]
IX. Again these things, which have been hitherto condemned,
have never been the conversation or practice of the holy men and women of old times,
whom the Scriptures recommend for holy examples, worthy of imitation.
Abraham, Isaac, and Jacob were plain men, and princes, as graziers are,
over their families and flocks.
They were not solicitous for the vanities so much lived in by the people of this generation,
for they pleased God by faith.
The first forsook his father`'s house, kindred, and country;
a true type or figure of that self-denial all must know,
that would have Abraham to their father.
They must not think to live in those pleasures, fashions,
and customs they are called to leave; no,
but part with all hopes of the great recompense of reward,
and that better country which is eternal in the heavens.^
footnote:[Heb. 11:15,26; Rom. 5:1.]
The prophets were generally poor; one a shepherd, another a herdsman, etc.
They often cried out unto the full-fed wanton Israelites to repent,
to fear and dread the living God, to forsake the sins and vanities they lived in;
but they never imitated them.
John the Baptist, the messenger of the Lord,
preached his embassy to the world in a coat of camel`'s-hair,
a rough and homely garment.^
footnote:[Matt. 3:4.]
Nor can it be conceived that Jesus Christ himself was much better apparelled, who,
according to the flesh, was of poor descent, and in life, of great plainness;
insomuch that it was usual in a way of derision to say, "`Is not this Jesus,
the carpenter, the son of Mary?`"^
footnote:[Matt. 13:55; Mark 6:3.]
And this Jesus tells his followers, "`That as for soft raiment,
gorgeous apparel and delicacies, they were for king`'s courts:`"^
footnote:[Luke 7:25.]
implying, that He and his followers were not to seek after those things;
but seems thereby to express the great difference that was
betwixt the lovers of the fashions and customs of the world,
and those whom He had chosen out of it.
And He did not only come in that mean and despicable manner himself,
that He might stain the pride of all flesh,
but therein became exemplary to his followers, what a self-denying life they must lead,
if they would be his true disciples.
Nay, He further leaves it with them in a parable,
to the end that it might make the deeper impression,
and that they might see how inconsistent a pompous,
worldly-pleasing life is with the kingdom He came
to establish and call men to the possession of:
and that is the remarkable story of Dives, who is represented first, as a rich man;^
footnote:[Luke 16:19. etc.]
next as a voluptuous man, in his rich apparel, his many dishes, and his pack of dogs;
and lastly, as an uncharitable man,
or one who was more concerned to please the lust of the eye, the lust of the flesh,
and the pride of life, and fare sumptuously every day,
than to take compassion of poor Lazarus at his gate: no,
his dogs were more pitiful and kind than he.
But what was the doom of this jolly man, this great rich man?
We read it was everlasting torment; but that of Lazarus, eternal joy with Abraham, Isaac,
and Jacob, in the kingdom of God.
In short, Lazarus was a good man, the other a great man: the one poor and temperate,
the other rich and luxurious: there are too many of them alive; and it were well,
if his doom might awaken them to repentance.

[.numbered]
X+++.+++ Nor were the twelve apostles, the immediate messengers of the Lord Jesus Christ,
other than poor men, one a fisherman, another a tent-maker;
and he that was of the greatest, though perhaps not the best employment,
was a custom-gatherer.^
footnote:[Matt. 4:18; ix.
9; Acts 18:3.]
So that it is very unlikely that any of them were followers of the fashions of the world:
nay, they were so far from it, that, as became the followers of Christ,^
footnote:[1 Cor. 4:9-14.]
they lived poor, afflicted, self-denying lives;
bidding the churches to walk as they had them for examples.^
footnote:[Phil. 3:1,7; 1 Pet. 2:21.]
And to shut up this particular,
they gave this pathetic account of the holy women in former times,
as an example of godly temperance, namely,
that first they did expressly abstain from gold, silver, plaited hair, fine apparel,
or such like; and next, that their adornment was a meek and quiet spirit,
and the hidden man of the heart, which are of great price with the Lord;^
footnote:[1 Pet. 3:3-4.]
affirming that such as live in pleasure, are dead whilst they live:^
footnote:[1 Tim. 5:6; Luke 8:14.]
for that the cares and pleasures of this life choke and destroy the seed of the kingdom,
and quite hinder all progress in the hidden and divine life.
Wherefore we find that the holy men and women of former times were
not accustomed to these pleasures and vain recreations;
but having their minds set on things above, sought another kingdom,
which consists in righteousness, peace, and joy in the Holy Spirit:
who having obtained a good report, and entered into their eternal rest;
therefore their works follow, and praise them in the gates.^
footnote:[Rom. 14:17; Heb. 11:2; iv.
9; Rev. 14:13.]

====
