== Chapter XV.

1+++.+++ The judgments of God denounced upon the Jews for their luxury;
all ranks included.--2. Christ charges his disciples to have a care of the guilt of it:
a supplication to the inhabitants of England.--3. Temperance pressed upon the
churches by the apostles.--4. An exhortation to England to measure herself by
that rule.--5. What Christian recreations are.--6. Who need other sports to pass
away their time are unfit for heaven and eternity.--7. Man has but a few days:
they may be better bestowed:
this doctrine is ungrateful to none that would be truly blessed.--8.
Not only good is omitted by this luxurious life,
but evil committed, as breach of marriage and love, loss of health and estate, etc.
Playhouses and stages most instrumental to this mischief.--9.
How youth are by them inflamed to vanity:
what mischief comes of revels, gamings, etc.
Below the life of noble heathens.--10. The true disciples
of Jesus are mortified in these things:
the pleasure and reward of a good employment of time.

I+++.+++ But such excess in apparel and pleasure was not only forbidden in Scripture,
but it was the ground of that lamentable message
by the prophet Isaiah to the people of Israel:
"`Moreover the Lord saith, Because the daughters of Zion are haughty,
and walked with stretched-forth necks and wanton eyes, walking and mincing as they go,
and making a tinkling with their feet;
therefore the Lord will smite with a scab the crown of the head of the daughters of Zion,
and the Lord will discover their secret parts;
in that day the Lord will take away the bravery of their tinkling ornaments,
and their cauls, (or net-works in the Hebrew,) and their round tires like the moon;
the chains and the bracelets, and the mufflers; the bonnets,
and the ornaments of the legs, and the head-bands, and the tablets, and ear-rings,
the rings and nose-jewels; the changeable suits of apparel, and the mantles,
and the wimples, and the crisping-pins; the glasses, and the fine linen,
and the hoods and the veils; and it shall come to pass, that instead of sweet smell,
there shall be a stink; and instead of a girdle, a rent; and instead of well-set hair,
baldness; and instead of a stomacher, a girding of sackcloth,
and burning instead of beauty: thy men shall fall by the sword,
and thy mighty in the war; and her gates shall lament and mourn, and she being desolate,
shall sit upon the ground.`"^
footnote:[The very practice, and garb,
and vanity of this age being as liable to the wrath of God,
which hangs over England and Europe,
and is ready to be executed on their rebellious inhabitants.]^
footnote:[Isa. 3:16-26.] Behold,
O vain and foolish inhabitants of England and Europe, your folly and your doom!
Yet read the prophet Ezekiel`'s vision of miserable Tyre,
what punishment her pride and pleasure brought upon her;
and amongst many other circumstances these are some:
"`These were thy merchants in all sorts of things; in blue clothes and broidered work,
and in chests of rich apparel, emeralds, purple, fine linen, coral and agate, spices,
with all precious stones, and gold, horses, chariots,`" etc.;
for which hear part of her doom: "`Thy riches, and thy fairs, thy merchandize,
and all thy company, which is in the midst, of thee,
shall fall into the midst of the sea in the day of thy ruin;
and the inhabitant of the isles shall be astonished at thee;
and their merchants hiss at thee; thou shalt be a terror, and shalt be no more.`"^
footnote:[Ezek.
xxvii.]
Thus hath God declared his displeasure against the luxury of this wanton world.
Yet further the prophet Zephaniah goes, for thus he speaks:
"`And it shall come to pass in the day of the Lord`'s sacrifice,
that I will punish the princes, and the king`'s children,
and all such as are clothed with strange apparel.`"^
footnote:[Zeph. 1:8.]
Of how evil consequence was it in those times,
for the greatest men to give themselves the liberty
of following the vain customs of other nations;
or of changing the usual end of clothes, or apparel, to gratify foolish curiosity!

II. This did the Lord Jesus Christ expressly charge
his disciples not to be careful about:
insinuating that such as were could not be his disciples: for, says he,
"`Take no thought, saying, What shall we eat?
or What shall we drink?
or Wherewithal shall we be clothed?
for after all these things do the Gentiles seek:
for your heavenly Father knoweth that you have need of all these things:
but seek ye first the kingdom of God and his righteousness,
and all these things shall be added unto you.`"^
footnote:[Matt. 6:31-33.]
Under which of eating, and drinking, and apparel,
he comprehends all external things whatsoever; and so much appears,
as well because they are opposed to the kingdom of God and his righteousness,
which are invisible and heavenly things,
as those very matters he enjoins them not to be careful about, are the most necessary,
and the most innocent in themselves.
If then, in such cases, the minds of his disciples were not to be solicitous;
much less in foolish, superstitious, idle inventions,
to gratify the carnal appetites and minds of men:
so certain it is that those who live therein are none of his followers, but the Gentiles;
and as He elsewhere says, "`The nations of the world who know not God.`"^
footnote:[Luke 12:22-30.]
If now then the distinguishing mark between the disciples
of Jesus and those of the world is,
that one minds the things of heaven, and God`'s kingdom, that "`stands in righteousness,
peace, and joy in the Holy Ghost;`"^
footnote:[Rom. 14:17.]
being not careful of external matters, even the most innocent and necessary:
and that the other minds eating, drinking, apparel, and the affairs of this world,
with the lusts, pleasures, profits, and honours that belong to it;
be you entreated for your souls`' sakes, O inhabitants of England, to be serious,
to reflect awhile upon yourselves what care and cost you are at of time and money,
about foolish, nay vicious things:
so far are you degenerated from the primitive Christian life.
What buying and selling, what dealing and chaffering, what writing and posting,
what toil and labour, what noise, hurry, bustle, and confusion, what study,
what little contrivances and overreachings, what eating, drinking, vanity of apparel,
most ridiculous recreations; in short, what rising early, going to bed late,
expense of precious time is there about things that perish!
View the streets, shops, exchanges, plays, parks, coffee-houses,
etc. and is not the world, this fading world, written upon every face?
Say not within yourselves, How otherwise should men live and the world subsist?
The common, though frivolous objection.
There is enough for all.
Let some content themselves with less: a few things, plain and decent,
serve a Christian life.
It is lust, pride, avarice, that thrust men upon such folly:
were God`'s kingdom more the exercise of their minds,
these perishing entertainments would have but little of their time or thoughts.

III.
This self-denying doctrine was confirmed and enforced by the apostles in their example,
as we have already shown; and in their precepts too,
as we shall yet evince in those two most remarkable passages of Paul and Peter;
where they do not only tell us what should be done,
but also what should be denied and avoided: "`In like manner I will,
that women adorn themselves in modest apparel; with shamefacedness and sobriety,
not with broidered hair, or gold, or pearls,
or costly array (then it seems these are immodest)
but which becometh women professing godliness,
with good works.`"^
footnote:[1 Tim. 2:10-9.]
Absolutely implying, that those who attire themselves with gold, silver, broidered hair,
pearls, costly array, cannot in so doing, be women professing godliness;
making those very things to be contrary to modesty, and consequently that they are evil,
and unbecoming women professing godliness.
To which the apostle Peter joins another precept after the like sort,
viz. "`Whose adorning, let it not be that outward adorning of plaiting the hair,
and of wearing of gold, and of putting on of apparel:`" what then?
"`But let it be the hidden man of the heart, in that which is not corruptible,
even the ornament of a meek and quiet spirit,
which is in the sight of God of great price.`"^
footnote:[1 Pet. 3:3-5.]
And as an inducement, he adds: "`for after this manner in the old time the holy^
footnote:[Note, not a word of men, as if this vanity belonged not to the sex;
let them observe that.]
women also, who trusted in God, adorned themselves.`"
Which doth not only intimate that both holy women were so adorned,
and that it behooves such as would be holy, and trust in the holy God, to be so adorned;
but also, that they who used those forbidden ornaments,
were the women and people in all ages, that, for all their talk, were not holy,
nor did trust in God.
Such are so far from trusting in God that the apostle Paul expressly says,
that "`she that liveth in pleasure is dead whilst she liveth.`"^
footnote:[1 Tim. 5:6.]
And the same apostle further enjoined,
that Christians should have their conversation in heaven,
and their minds fixed on things above:^
footnote:[Phil. 3:20; Col. 3:1-4; Rom. 13:13.]
"`walk honestly as in the day, not in rioting and drunkenness,
not in chambering and wantonness, not in envy and strife:`"^
footnote:[Eph. 5:3-4.]
"`let not fornication, uncleanness, or covetousness be once named among you:
neither filthiness, nor foolish talking nor jesting, which are not convenient;
but rather giving of thanks:`"^
footnote:[Eph. 4:29.]
"`let no corrupt communication proceed out of your mouth, but that which is good,
to the use of edifying, that it may minister grace unto the hearers.
But put ye on the Lord Jesus Christ, and make no provision for the flesh,
to fulfill the lusts thereof.`"^
footnote:[Rom. 13:14; Eph. 4:30.]
And, "`Grieve not the Holy Spirit;
(intimating such conversation doth;) but be ye followers of God, as dear children:
walk circumspectly, not as fools, but as wise; redeeming the time,
because the days are evil.`"^
footnote:[Eph. 5:1,15-16.]

IV. By this, measure yourselves, O inhabitants of this land,
who think yourselves wronged, if not accounted Christians:
see what proportion your life and spirit bear with
these most holy and self-denying precepts and examples.
Well, my friends, my soul mourns for you: I have been with and among you;
your life and pastime are not strangers to my notice; and with compassion, yea,
inexpressible pity, I bewail your folly.
O that you would be wise!
O that the just principle in yourselves would be heard!
O that eternity had time to plead a little with you!
Why should your beds, your glasses, your clothes, your tables, your loves, your plays,
your parks, your treats, your recreations, poor perishing joys, have all your souls,
your time, your care, your purse, and consideration?
Be ye admonished, I beseech you, in the name of the living God,
by one that some of you know hath had his share in these things,
and consequently time to know how little the like
vanities conduce to true and solid happiness.
No, my Friends, God Almighty knows, and would to God, you would believe and follow me,
they end in shame and sorrow.
Faithful is that most holy One, who hath determined,
that every man and woman shall reap what they sow: and will not trouble, anguish,
and disappointment be a sad and dreadful harvest for you to reap,
for all your misspent time and substance, about superfluities and vain recreations?
Retire then; quench not the Holy Spirit in yourselves; redeem your precious abused time:
frequent such conversation as may help you against your evil inclinations;
so shall you follow the examples, and keep the precepts of Jesus Christ,
and all his followers; for hitherto we have plainly demonstrated,
that no such way of living, as is in request among you of the land, ever was, or can be,
truly Christian.

V+++.+++ But the best recreation is to do good: and all Christian customs tend to temperance,
and some good and beneficial end; which more or less may be in every action.^
footnote:[1 Pet. 1:15; Heb. 10:25; 1 Pet. 4:9-11; Matt. 25:36-37;
Phil. 2:4; Ibid.
iv. 8.]
For instance, if men and women would be diligent to follow their respective callings;
frequent the assemblies of religious people; visit sober neighbours to be edified,
and wicked ones to reform them; be careful in the tuition of their children,
exemplary to their servants; relieve the necessitous, see the sick, visit the imprisoned;
administer to their infirmities and indispositions, endeavour peace amongst neighbours:
also, study moderately such commendable and profitable arts, as navigation, arithmetic,
geometry, husbandry, gardening, handicraft, medicine, etc.; and that women spin, sew,
knit, weave, garden, preserve, and the like housewife and honest employments,
the practice of the greatest and noblest matrons, and youth, among the very heathens;
helping others, who for want are unable to keep servants,
to ease them in their necessary affairs;
often and private retirements from all worldly objects, to enjoy the Lord:
secret and steady meditations on the divine life and heavenly inheritance;
which to leave undone and prosecute other things, under the notion of recreations,
is impiety; it is most vain in any to object, that they cannot do these always,
and therefore why may not they use these common diversions?
for I ask, what would such be at?
what would they do?
and what would they have?
They that have trades have not time enough to do the half of what hath been recommended.
And as for those who have nothing to do, and indeed do nothing, which is worse, but sin,
which is worst of all, here is variety of pleasant, of profitable, yea,
of very honourable employments and diversions for them.
Such can with great delight sit at a play, a ball, a masque, at cards, dice,
etc. drinking, revelling, feasting, and the like, an entire day; yea turn night into day,
and invert the very order of the creation, to humour their lusts;^
footnote:[Amos 6:3-8.]
and were it not for eating and sleeping, it would be past a doubt,
whether they would ever find time to cease from those vain and sinful pastimes,
till the hasty calls of death should summon their appearance in another world:
yet do they think it intolerable, and hardly possible,
for any to sit so long at a profitable or religious exercise.

VI. But how do these think to pass their vast eternity away?
"`For as the tree falls, so it lies.`"^
footnote:[Ecc. 11:3.]
Let none deceive themselves, nor mock their immortal souls with a pleasant,
but most false and pernicious dream,
that they shall be changed by a constraining and irresistible power,
just when their souls take leave of their bodies; no, no, my friends, "`what you sow,
that shall you reap:`"^
footnote:[Gal. 6:4-9; Eph. 5:6.]
if vanity, folly, visible delights, fading pleasures;
no better shall you ever reap than corruption,
sorrow and the woful anguish of eternal disappointments.
But alas! what is the reason that the cry is so common,
Must we always dote on these things?
Why most certainly it is this,
they know not what is the joy and peace of speaking and acting,
as in the presence of the most holy God:^
footnote:[Eph. 4:18-20.]
that passes such vain understandings,
darkened with the glories and pleasures of the god of this world;^
footnote:[Rom. 10:2.]
whose religion is so many mumbling and ignorantly devout said words,
as they teach parrots; for if they were of those whose hearts are set on things above,
and whose treasure is in heaven, there would their minds inhabit,
and their greatest pleasure constantly be: and such who call that a burden,
and seek to be refreshed by such pastimes as a play, a morrice-dance, a punchinello,
a ball, a masque, cards, dice, or the like, I am bold to affirm,
they not only never knew the divine excellency of God, and his truth,
but thereby declare themselves most unfit for them in another world.
For how is it possible, that they can be delighted to eternity with that satisfaction,
which is so tedious and irksome for thirty or forty years, that,
for a supply of recreation to their minds,
the little toys and fopperies of this perishing world
must be brought into practice and request?
Surely, those who are to reckon for every idle word,^
footnote:[Matt. 12:36.]
must not use sports to pass away that time which
they are commanded so diligently to redeem,
considering no less work is to be done, than making their calling and election sure:^
footnote:[Eph. 5:16; Phil. 3:14; 2 Pet. 1:10; Col. 4:5.]
much less study to invent recreations for their vain minds,
and spend the greatest part of their days, and months, and years therein,
not allowing a quarter of that time toward the great
concernment of their lives and souls,
for which that time was given them.

VII.
There is but little need to drive away that, by foolish divertisements,
which flies away so swiftly of itself; and when once gone, is never to be recalled.
Plays, parks, balls, treats, romances, music, love-sonnets, and the like,
will be a very invalid plea,
for any other purpose than their condemnation who are taken and delighted with them,
at the revelation of the righteous judgment of God.
O my friends! these were never invented,
but by that mind which had first lost the joy and
ravishing delights of God`'s holy presence.
So that we conclude first that of those many excellent employments already mentioned,
as worthy to possess such minds as are inclined to these vanities,
there is store enough of time, not only to take up their spare hours, but double so much,
and that with great delight, diversion, and profit, both to themselves and others;
were they but once weaned from vain and fruitless fopperies, and did they but consider,
how great the satisfaction, and how certain the rewards are, which attend this,
and the other life, for such universal benefits and virtuous examples.
The second conclusion is, that what is alleged by me,
can be displeasing and ungrateful to none,
but such as know not what it is to walk with God, to prepare for an eternal mansion,
to have the mind exercised on heavenly and good things,
to follow the examples of the holy men and women of former happy ages:
such as know not Christ`'s doctrine, life, death, and resurrection,
but only have their minds fastened to the flesh, and by the objects of it are allured,
deceived, and miserably ruined: and lastly, that despise heaven,
and the joys that are not seen, though eternal,
for a few perishing trifles that they do see; though they are decreed to pass away.^
footnote:[Rom. 6:3-8; 1 Cor. 12:13; Gal. 3:27; Col. 2:12-13; Eph. 4:13.
]
How these are baptized with Christ, into his holy life, cruel sufferings, shameful death,
and raised with him to immortal desires, heavenly meditations, a divine new life,
growing into the knowledge of heavenly mysteries, and all holiness,
even unto the measure of the stature of Jesus Christ, the great example of all: how,
I say, these resemble most necessary Christian qualifications,
and what share they have therein,
let their consciences tell them upon a serious inquiry in the cool of the day.

VIII.
But in the next place,
such attire and pastimes do not only show the exceeding worldliness of people`'s inclinations,
and their very great ignorance of the divine joys; but by imitating these fashions,
and frequenting these places and diversions, not only much good is omitted,
but a certain door is open to much evil to be committed: as first, precious time,
that were worth a world on a dying bed, is lost:
money that might be employed for the general good, vainly expended,
pleasure is taken in mere shame; lusts are gratified,
the minds of the people alienated from heavenly things, and exercised about mere folly;
// lint-disable invalid-characters "à"
and men become acceptable by their trims and the à-la-modeness of their dress and apparel;
from whence respect to persons doth so naturally arise,
that to deny it is to affirm the sun shines not at noon-day;^
footnote:[James 2:1-9.]
nothing being more notorious than the cringing, scraping, sirring,
and madaming of persons, according to the gaudiness of their attire:
which is detestable to God, and so absolutely forbidden in the Scriptures,
that to do it is to break the whole law,
and consequently to incur the punishment thereof.
Next, what great holes do the like practices make in men`'s estates!
How are their vocations neglected, young women deluded, the marriage-bed invaded,
contentions and family animosities begotten, partings of man and wife,
disinheriting of children, dismissing of servants!
On the other hand, servants made slaves, children disregarded,
wives despised and shamefully abused, through the intemperance of their husbands;
which either puts them upon the same extravagance,
or laying such cruel injustice to heart, they pine away their days in grief and misery.
But of all these wretched inventions, the playhouses, like so many hellish seminaries,
do most perniciously conduce to these sad and miserable ends;
where little besides frothy, wanton,
if not directly obscene and profane humours are represented,
which are of notoriously ill consequence upon the minds of most;
especially the youth that frequent them.
And thus it is that idle and debauched stages are encouraged and maintained;
than which scarcely a greater abomination can be thought on of that rank of impieties,
as will anon particularly be shown;
and truly nothing but the excessive pleasure people
take therein could blind their eyes from seeing it.

IX. But lastly, the grand indisposition of mind in people to solid, serious,
and heavenly meditations, by the almost continual,
as well as pleasant rumination in their minds,
of those various adventures they have been entertained with,
which in the more youthful can never miss to inflame
and animate their boiling and airy constitutions.^
footnote:[Job 35:13.]
And in the rest of the common recreations of balls, masques, treats, cards, dice,
etc. there are the like opportunities to promote the like evils.
And yet further; how many quarrels, animosities, nay, murders too,
as well as expense of estate and precious time,
have been the immediate consequences of the like practices!
In short, these were the ways of the Gentiles that knew not God,
but never the practice of them that feared Him:^
footnote:[Eph. 4:17-25.]
nay, the more noble among the heathens themselves, namely, Anaxagoras, Socrates, Plato,
Antisthenes, Heraclitus, Zeno, Aristides, Cato, Tully, Epictetus, Seneca,
etc. have left their disgust to these things upon record, as odious and destructive,
not only of the honour of the immortal God, but of all good order and government;
as leading into looseness, idleness, ignorance, and effeminacy,
the great cankers and bane of all states and empires.
And the pretended innocency of these things steals
away their minds from that which is better,
into the love of them; nay, it gives them confidence to plead for them,
and by no means will they think the contrary.
But why?
because it is a liberty that feeds the flesh and
gratifies the lustful eye and palate of poor mortality:
wherefore they think it a laudable condition to be no better than the beast,
that eats and drinks but what his nature doth require;
although the number is very small of such,
so very exorbitant are men and women grown in this present age:
for either they do believe their actions are to be ruled by their own will;
or else at best,
that not to be stained with the vilest wickedness is matter of great boasting:
and indeed it is so in a time when nothing is too wicked to be done.
But certainly, it is a sign of universal impiety in a land,
when not to be guilty of the sins the very heathens loathe, is to be virtuous, yes,
and Christian too, and that to no small degree of reputation:
a dismal symptom to a country!
But is it not to be greatly blinded,
that those we call infidels should detest those practices
as infamous which people that call themselves Christians,
cannot or will not see to be such, but gild them over with the fair titles of ornaments,
decency, recreation, and the like?
Well, my friends, if there were no God, no heaven, no hell, no holy examples,
no Jesus Christ, in cross, doctrine, and life, to be conformed unto;
yet would charity to the poor, help to the needy, peace amongst neighbours,
visits to the sick, care of the widow and fatherless,
with the rest of those temporal good offices already repeated, be a nobler employment,
and much more worthy of your expense and pains.
Nor indeed is it to be conceived,
that the way to glory is smoothed with such a variety of carnal pleasures;
for then conviction, a wounded spirit, a broken heart, a regenerate mind;^
footnote:[Prov. 18:14; Ps. 51:17; Matt. 5:4; Luke 6:25; Rom. 2:7;
Ps. 40:8; Rom. 7:22; Heb. 11:13-16; Rom. 1:25-30.]
in a word, immortality, would prove as mere fictions as some make them,
and others therefore think them: no,
these practices are forever to be extinguished and expelled all Christian society.
For I affirm, that to one who internally knows God,
and hath a sense of his blessed presence, all such recreations are death; yea,
more dangerously evil, and more apt to steal away the mind from the heavenly exercise,
than grosser impieties.
For they are so big they are plainly seen; so dirty, they are easily detected:
which education and common temperance, as well as constitution in many,
teach them to abhor: and if they should be committed,
they carry with them a proportionable conviction.
But these pretended innocents, these supposed harmless satisfactions,^
footnote:[Job 1:4.]
are more surprising, more destructive:
for as they easily gain an admission by the senses,
so the more they pretend to innocency the more they secure the
minds of people in the common use of their evil consequences,
that with a mighty confidence they can plead for them.

X+++.+++ But as this is plainly not to deny themselves,^
footnote:[1 John 2:15-17.]
but on the contrary, to employ the vain inventions of carnal men and women,
to gratify the desire of the eye, the desire of the flesh, and the pride of life,
(all which exercise the mind below the divine and only true pleasure, or else,
tell me what does,) so be it known to be such,
that the heavenly life and Christian joys are of another kind,
as hath already been expressed: yea,
that the true disciples of the Lord Christ must be hereunto crucified,
as to objects and employments that attract downwards,
and that their affections should be raised to a more sublime and spiritual conversation,
as to use this world, even in its most innocent enjoyments, as if they used it not.
But if they take pleasure in anything below,
it should be in such good offices as before mentioned,
whereby a benefit may redound in some respect to others:
in which God is honoured over all visible things, the nation relieved,
the government bettered, themselves rendered exemplary of good,
and thereby justly entitled to present happiness, a sweet memorial with posterity,
as well as to a seat at his right hand, where there are joys and pleasures forever:^
footnote:[Job 36:7; Ps. 5:12; Prov. 10:11-7.]
than which there can be nothing more honourable, nothing more certain, world without end.
