== Chapter XVI.

1+++.+++ Luxury should not be used by Christians,
because of its inconsistency with the spirit of Christianity.--2. The
cup of which Christ`'s true disciples drank.--3. O! who will drink of
this cup!--4. An objection answered of the nature of God`'s kingdom,
and what it stands in.--5. Of the frame of the spirit of Christ`'s followers.

I+++.+++ But the luxury opposed in this discourse should not be allowed among Christians,
because both that which invents it, delights in it, and pleads so strongly for it,
is inconsistent with the true spirit of Christianity;
nor doth the very nature of the Christian religion admit thereof.
For therefore was it, that immortality and eternal life were brought to light,
that all the invented pleasures of mortal life, in which the world lives,
might be denied and relinquished: and for this reason it is,
that nothing less than immense rewards and eternal mansions are promised,
that men and women might therefore be encouraged willingly
to forsake the vanity and fleshly satisfactions of the world,
and encounter with boldness the shame and sufferings
they must expect to receive at the hand of,
it may be, their nearest intimates and relations.

For if the Christian religion had admitted the possession of this world
in any other sense than the simple and naked use of those creatures,
really given of God for the necessity and convenience of the whole creation;
for instance, did it allow all that pride, vanity, curiosity, pomp, exchange of apparel,
honours, preferments, fashions, and the customary recreations of the world,
with whatever may delight and gratify their senses; then what need of a daily cross;
a self-denying life; working out salvation with fear and trembling;
seeking the things that are above; having the treasure and heart in heaven;
no idle talking, no vain jesting, but fearing and meditating all the day long;
undergoing all reproach, scorn, hard usage, bitter mockings, and cruel deaths?
What need these things?
And why should they be expected in order to that glorious immortality and eternal crown,
if the vanity, pride, expense, idleness, concupiscence, envy, malice,
and whole manner of living among the called Christians,
were allowed by the Christian religion?
No certainly;
but as the Lord Jesus Christ well knew in what foolish trifles and vain pleasures,
as well as grosser impieties, the minds of men and women were fixed,
and how much they were degenerated from the heavenly principle of life,
into a lustful or unlawful seeking after the enjoyments of this perishing world, nay,
inventing daily new satisfactions to gratify the carnal appetites,
so did He not less foresee the difficulty that all would
have to relinquish and forsake them at his call,
and with what great unwillingness they would take their leave of them,
and be weaned from them.
Wherefore to induce them to it, He did not speak unto them in the language of the law,
that they should have an earthly Canaan, great dignities, a numerous issue, a long life,
and the like: no, rather the contrary, at least to take these things in their course;^
footnote:[Matt. 16:24; Luke 9:23; Phil. 2:12; Col. 3:1-2; Eph. 5:4-5;
Neh. 13; Psal. Cxii 1; Isa. 28:14; Ps. 119:97; Luke 18:23; Heb. 11:16, ch. x. 33, ch. xi. 37, 38.]
but He speaks to them in a higher strain; namely,
He assures them of a kingdom and a crown that are immortal, that neither time, cruelty,
death, grave, or hell, with all its instruments,
shall ever be able to disappoint or take away from those who should believe and obey Him.
Further, that they should be taken into that near alliance of loving friends, yea,
the intimate divine relation of dear brethren,
and co-heirs with Him of all celestial happiness, and a glorious immortality.
Wherefore, if it be recorded that those who heard not Moses were to die,
much more they who refuse to hear and obey the precepts of this great
and eternal Rewarder of all that diligently seek and follow Him.^
footnote:[Luke 6:20, ch.
xii. 32, ch.
Xxii.
29; Col. 1:13; 1 Thess.
Ii 12; Heb. 12:28; James 2:5; John 15:14-15; Rom. 8:17; Heb. 2:11, ch.
xii. 2. 1 Pet. 2:21; Luke 12:29-31; 2 Tim. 5:6; Matt. 19:27-29; Luke 6:22.
; John 15:10.]

II. And therefore it was that He was pleased to give us, in his own example,
a taste of what his disciples must expect to drink deeply of, namely,
the cup of self-denial, cruel trials, and most bitter afflictions:
He came not to consecrate a way to the eternal rest, through gold, and silver, ribbons,
laces, prints, perfumes, costly clothes, curious trims, exact dresses, rich jewels,
pleasant recreations, plays, treats, balls, masques, revels, romances, love-songs,
and the like pastimes of the world: no, no,
alas! but by forsaking all such kind of entertainments, yea,
and sometimes more lawful enjoyments too;
and cheerfully undergoing the loss of all on the one hand, and the reproach, ignominy,
and the most cruel persecution from ungodly men on the other.
He needed never to have wanted such variety of worldly pleasures,
had they been suitable to the nature of his kingdom: for He was tempted,
as are his followers, with no less bait than all the glories of the world:^
footnote:[Matt. 10:37-38; Luke 12:32-36.]
but He commanded to seek another country,
and to lay up treasures in the heavens that fade not away;
and therefore charged them never to be much inquisitive about what they should eat,
drink, or put on, "`because,`" saith He,
"`after these things the Gentiles,`" that know not God, "`do seek;`"^
footnote:[Matt. 6:29-33.]
and Christians that pretend to know Him too,) but "`having food and raiment,
therewith to be content:`"^
footnote:[1 Tim. 6:11:]
He, I say, that enjoined this doctrine, and led that holy and heavenly example,
even the Lord Jesus Christ, bade them that would be his disciples take up the same cross,
and follow Him.^
footnote:[Luke 14:26-27, 33.]

III.
O who will follow Him!
Who will be true Christians?
We must not think to steer another course, nor to drink of another cup,
than hath the Captain of our salvation done before us:^
footnote:[Heb. 2:10.]
no, for it is the very question He asked James and John, the sons of Zebedee of old,
when they desired to sit at his right and left hand in his kingdom,
"`Are ye able to drink of the cup that I shall drink of,
and to be baptized with the baptism that I am baptized with?`"^
footnote:[Matt. 20:22.]
Otherwise no disciples, no Christians.
Whoever they are that would come to Christ, and be right Christians,
must readily abandon every delight that would steal away the affections of the mind,
and exercise it from the divine principle of life,
and freely write a bill of divorce for every beloved vanity; and all,
under the Sun of Righteousness is so, compared with Him.

Objection 1.

IV. But some are ready to object, who will not seem to want Scripture for their lusts,
although it be evidently misapplied.
The kingdom of God stands not in meats, or in drinks, or in apparel, etc.
Answer.
Right; therefore it is that we stand out of them.
But surely you have the least reason of any to object this to us,
who make those things so necessary to conversation,
as our not conforming to them renders us obnoxious to your reproach; which how Christian,
or resembling it is of the righteousness, peace,
and joy in which the heavenly kingdom stands,
let the just principle in your own consciences determine.
Our conversation stands in temperance, and that stands in righteousness,
by which we have obtained that kingdom,
your latitude and excess have no share or interest in.
If none, therefore, can be true disciples but they that come to bear the daily cross,
but those who follow the example of the Lord Jesus Christ,^
footnote:[Phil. 3:10; 1 Pet. 4:13; Tit. 2:11-13; John 1:9; Rom. 6:6;
Gal. 2:20; v. 24; vi.
4.]
through his baptism, afflictions, and temptations;
and that none are so baptized with Him but those whose minds are retired
from the vanities in which the generality of the world live,
and become obedient to the holy light and divine grace with
which they have been enlightened from on high,
and thereby are daily exercised to the crucifying of every contrary affection,
and bringing of immortality to light; if none are true disciples but such,
as most undoubtedly they are not,
then let the people of these days a little soberly reflect upon themselves,
and they will conclude that none who live and delight in these
vain customs and this un-christ-like conversation can be true Christians,
or disciples of the crucified Jesus:^
footnote:[Rom. 6:3-6; Phil. 3:10; 1 Pet. 4:13; Tit. 2:11-13; John 1:9;
Rom. 6:6; Gal. 2:20, ch. v. 24, ch. vi. 4; 2 Tim. 1:10.]
for otherwise, how would it be a cross;
or the Christian life matter of difficulty and reproach?
No, the offence of the cross would soon cease,
which is "`the power of God to them that believe;`"^
footnote:[Gal. 5:11; 1 Cor. 1:18.]
that every lust and vanity may be subdued,
and the creature brought into a holy subjection of
mind to the heavenly will of its Creator.
For therefore has it been said, that Jesus Christ was and is manifested,
that by his holy self-denying life and doctrine, and by the immortality He brought,
and daily brings to light, He might stain the glory of their fading rests and pleasures;^
footnote:[1 Cor. 1:27-29.]
that having their minds weaned from them, and being crucified thereunto,
they might seek another country, and obtain an everlasting inheritance:
for "`the things that are seen are temporal,`"^
footnote:[2 Cor. 4:18.]
and those they were, and all true Christians are, to be redeemed from resting in:
but the things that are not seen are eternal; those they were,
and all are to be brought to, and have their affections chiefly fixed upon.

V+++.+++ Wherefore a true disciple of the Lord Jesus Christ is
to have his mind so conversant about heavenly things,
that the things of this world may be used as if they were not:
that having such things as are necessary and convenient, he be therewith content,
without the superfluity of the world;^
footnote:[1 Tim. 6:8.]
whereby the pleasure that in times of ignorance was
taken in the customs and fashions of the world,
may more abundantly be supplied in the hidden and heavenly life of Jesus:
for unless there be an abiding in Christ,
it will be impossible to bring forth that much fruit^
footnote:[John 15:4,7-8.]
which He requires at the hand of his followers, and wherein his Father is glorified.
But as it is clear that such as live in the vanities, pleasures, recreations,
and lusts of the world, abide not in Him, neither know Him,
for they that know Him depart from iniquity;
so is their abiding and delighting in those bewitching follies,
the very reason why they are so ignorant and insensible of Him:
Him who continually stands knocking at the door of their hearts;^
footnote:[Rev. 3:20.]
in whom they ought to abide,
and whose divine power they should know to be the cross on which
every beloved lust and alluring vanity should be slain and crucified;
that so they might feel the heavenly life to spring up in their hearts,
and themselves to be quickened to seek the things that are above;
that when Christ shall appear, they might appear with Him in glory who is over all,
God blessed forever.^
footnote:[Col. 3:1; Rom. 9:5.]
Amen.
