== Chapter XVII.

1+++.+++ The customs, fashions, etc. which make up the attire and pleasure of the age,
are enemies to inward retirement.--2. Their end is
to gratify lust.--3. Had they been solid,
Adam and Eve had not been happy,
that never had them.--4. But the confidence and presumption of Christians,
as they would be called,
in the use of them is abominable.--5. Their authors further condemn them,
who are usually loose and vain people.--6. Mostly borrowed of the Gentiles,
that knew not God.--7. An objection of their usefulness considered and answered,
and the objectors reproved.--8. The best heathens abhorring what pretended Christians
plead for.--9. The use of these things encourages the authors and makers of them
to continue in them.--10. The objection of the maintenance of families answered.
None must do evil, that good should follow:
but better employments may be found more serviceable
to the world.--11. Another objection answered:
GOD no author of their inventions,
and so not excusable by his institution.--12. People
pleading for these vanities show what they are.
An exhortation to the weighty and considerate.
A great part of the way to true discipleship, is to abandon the school and shop of Satan.

I+++.+++ Next, those customs and fashions,
which make up the common attire and conversation of the times,
do eminently obstruct the inward retirement of people`'s minds,
by which they may come to behold the glories of immortality:
who instead of fearing their Creator in the days of their youth,
and seeking the kingdom of God in the first place,^
footnote:[Ecc. 12:1; Luke 12:31.]
expecting the addition of such other things as may be necessary and convenient,
according to the injunctions of God and the Lord Jesus Christ;
as soon as they can do anything, they look after pride, vanity,
and that conversation which is most delightful to the flesh,^
footnote:[Jer. 18:18-20.]
which becomes their most delightful entertainment:
all which do but evidently beget lustful conceptions, and inflame to inordinate thoughts,
wanton discourses, lascivious treats, if not at last to wicked actions.
To such it is tedious and offensive to speak of heaven or another life.
Bid them reflect upon their actions, not grieve the Holy Spirit,
consider of an eternal doom, prepare for judgment;^
footnote:[Ecc. 4:8. 2 Tim. 2:16,21-22. Eph. 4:30.]
and the best return that is usual is reproachful jests,^
footnote:[Eph. 5:3-4.]
profane repartees, if not direct blows.
Their thoughts are otherwise employed: their mornings are too short for them to wash,
to smooth, to paint, to patch, to braid, to curl, to gum, to powder,
and otherwise to attire and adorn themselves;^
footnote:[Ps. 12:2; Isa.
v.; xii.; lix.
3, 4.]
whilst their afternoons are as commonly bespoke for visits and for plays;
where their usual entertainment is some stories fetched from the more approved romances;
some strange adventures, some passionate amours, unkind refusals, grand impediments,
importunate addresses, miserable disappointments, wonderful surprises,
unexpected encounters, castles surprised, imprisoned lovers rescued,
and meetings of supposed dead ones; bloody duels,
languishing voices echoing from solitary groves, overheard mournful complaints,
deep-fetched sighs sent from wild deserts, intrigues managed with unheard-of subtlety;
and whilst all things seem at the greatest distance, then are dead people alive,
enemies friends, despair turned to enjoyment, and all their impossibilities reconciled:
things that never were, nor are, nor ever shall or can be, they all come to pass.
And as if men and women were too slow to answer the loose suggestions of corrupt nature;
or were too intent on more divine speculations and heavenly affairs,
they have all that is possible for the most extravagant wits to invent;
not only express lies, but utter impossibilities to very nature,
on purpose to excite their minds to those idle passions,
and intoxicate their giddy fancies with swelling nothings but airy fictions:
which not only consume their time, effeminate their natures, debase their reason,
and set them on work to reduce these things to practice,
and make each adventure theirs by imitation;
but if disappointed,--as who can otherwise expect from such mere
phantasms?--the present remedy is latitude in the greatest vice.
And yet these are some of their most innocent recreations,
which are the very gins of Satan, to ensnare people;
contrived most agreeable to their weakness,
and in a more insensible manner mastering their affections
by entertainments most taking to their senses.
On such occasions it is their hearts breed vanity,
and their eyes turn interpreters to their thoughts,
and their looks do whisper the secret inflammations of their intemperate minds;^
footnote:[Prov. 7:10-21.]
wandering so long abroad, till their lascivious actings bring night home,
and load their minds and reputations with lust and infamy.

II. Here is the end of all their fashions and recreations,
to gratify the lust of the eye, the lust of the flesh, and the pride of life:^
footnote:[1 John 2:15-16.]
clothes that were given to cover, now want a covering for their shameful excess;
and that which should remind men of lost innocency, they pride and glory in:
but the hundredth part of these things cost man the loss of Paradise,
that now make up the agreeable recreation, aye, the accomplishment of the times.
For as it was Adam`'s fault to seek a satisfaction to himself,
other than what God ordained; so it is the exercise, pleasure, and perfection of the age,
to spend the greatest portion of their time in vanities,
which are so far from the end of their creation, namely, a divine life,
that they are destructive of it.
^
footnote:[Ecc. 12:1.]

III.
Were the pleasures of the age true and solid,
Adam and Eve had been miserable in their innocency, who knew them not:
but as it was once their happiness, not to know them in any degree; so it is theirs,
that know Christ indeed,
to be by his eternal power redeemed and raised to the love of immortality:
which is yet a mystery to those who live and have pleasure in their curious trims,
rich and changeable apparel, nicety of dress, invention and imitation of fashions,
costly attire, mincing gaits, wanton looks, romances, plays, treats, balls, feasts,
and the like conversation in request: for as these had never been,
if man had stayed at home with his Creator,
and given the entire exercise of his mind to the noble ends of his creation;
so certain it is, that the use of these vanities,
is not only a sign that men and women are yet ignorant of their true rest and pleasure,
but it greatly obstructs and hinders the retirement of their minds,
and their serious inquiry after those things that are eternal.^
footnote:[Eph. 2:1-5; Col. 2:13; 1 Pet. 1:14-18; Tit. 2:11-12;
James 5:5; Matt. 7:17-19; Rom. 8:8; Matt. 16:26; 1 Cor. 6:13;
Job 35:15; Isa. 40:6; 1 Pet. 1:24.]
O that there should be so much noise, clutter, invention, traffic, curiosity, diligence,
pains, and vast expense of time and estate, to please and gratify poor vain mortality!
And that the soul, the very image of divinity itself,
should have so little of their consideration.
What, O what more pregnant instances and evident tokens can be given,
that it is the body, the senses, the case, a little flesh and bone covered with skin,
the toys, fopperies, and very vanities of this mortal life and perishing world,
that please, that take, that gain them; on which they dote;
and think they never have too much time, love, or money to bestow upon them!

IV. Thus are their minds employed; and so vain are they in their imaginations,
and dark in their understandings, that they not only believe them innocent,
but persuade themselves they are good Christians all this while;
and to rebuke them is worse than heresy.^
footnote:[Luke 8:14; Prov. 1:30, x. 17, xii. 1, xv. 14;
Isa. 57:1-10; Jer. 16:19-21; Matt. 6:7.]
Thus are they strangers to the hidden life;
and by these things are they diverted from all serious examination of themselves:
and a forced zeal of half-an-hour`'s talk in other men`'s words,
which they have nothing to do with, is made sufficient; being no more their states,
or at least their intention, as their works show,
than it was the young man`'s in the Gospel, that said, he would go, and did not.^
footnote:[Luke 8:14. Prov. 1:25,30, ch. x. 17, ch. xii. 1, ch.
xv. 15, Isa. 58:1-2 to 10. Jer. 16:19-21. 2 Tim. 3:4. Matt. 6:7.]
But alas! why?
O there are other guests!
What are they?
Pharamond, Cleopatra, Cassandra, Clelia; a play, a ball a spring-garden; the park,
the gallant, the exchange, in a word, the world.
These stay, these call, these are importunate, and these they attend,
and these are their most familiar associates.
Thus are their hearts captivated from the divine exercise; nay,
from such external affairs, as immediately concern some benefit to themselves,
or needy neighbours;
pleasing themselves with the received ideas of those
toys and fopperies into their loose and airy minds;
and if in all things they cannot practise them, because they want the means of it,
yet as much as may be, at least to dote upon them, be taken with them,
and willingly suffer their thoughts to be hurried after them.
All which greatly indisposes the minds,
and distracts the souls of people from the divine life and principle of the holy Jesus;
but, as it hath been often said, more especially the minds of the younger sort:
to whom the like divertisements^
footnote:[Isa. 59:4; Jer. 2:5; Ecc. 11:10.]
(where their inclinations being presented with what is very suitable to them,
they become excited to more vanity than ever they thought upon before,)
are incomparably dearer than all that can be said of God`'s fear,
a retired life, eternal rewards, and joys unspeakable and full of glory: so vain,
so blind, and so very insensible are men and women,
of what truly makes a disciple of Christ.^
footnote:[Rom. 13:11-12; Matt. 15:7-14.]
O! that they would ponder on these things, and watch against,
and come out of all these vanities, for the coming of the Lord, lest being unprepared,
and taken up with other guests, they enter not into his everlasting rest.

V+++.+++ That which further manifests the unlawfulness
of these numerous fashions and recreations is,
that they are either the inventions of vain, idle, and wanton minds,
to gratify their own sensualities, and raise the like wicked curiosity in others,
to imitate the same; by which nothing but lust and folly are promoted:
or the contrivances of indigent and impoverished wits,
who make it the next way for their maintenance: in both which respects,
and upon both which considerations, they ought to be detested.
For the first licenses express impiety,
and the latter countenances a wretched way of livelihood,
and consequently diverts from more lawful, more serviceable,
and more necessary employments.
That such persons are both the inventors and actors of all these follies,
cannot be difficult to demonstrate: for were it possible,
that any one could bring us father Adam`'s girdle, and mother Eve`'s apron,
what laughing, what fleering, what mocking of their homely fashions would there be!
Surely their tailor would find but little custom, although we read,
it was God himself that made them coats of skins.^
footnote:[Gen. 3:21.]
The like may be asked of all the other vanities,
concerning the holy men and women through all the generations of holy writ.
How many pieces of ribbon, and what feathers, lace-bands, and the like,
did Adam and Eve wear in Paradise, or out of it?
What rich embroideries, silks, points, etc. had Abel, Enoch, Noah, and good old Abraham?
Did Eve, Sarah, Susannah, Elizabeth, and the Virgin Mary use to curl, powder, patch,
paint, wear false locks, or strange colours, rich points, trimmings, laced gowns,
embroidered petticoats, shoes with slip-slaps, laced with silver or silver lace,
and ruffled like pigeons`' feet, with several yards, if not pieces of ribbons?
How many plays did Jesus Christ and his apostles recreate themselves at?
What poets, romances, comedies, and the like did the apostles and saints make,
or use to pass away their time withal?
I know, they bid all redeem their time, to avoid foolish talking, vain jesting,
profane babblings, and fabulous stories; as what tend to godliness: and rather to watch,
to work out their salvation with fear and trembling, to flee foolish and youthful lusts,
and to follow righteousness, peace, goodness, love, charity;
and to mind the things that are above as they would have honour, glory, immortality,
and eternal life.^
footnote:[Eph. 5:1-5, 15, 16; 2 Tim. 2:16,22; Matt. 25:13; Phil. 2:12-13;
Col. 3:1,2,5; Rom. 2:6-7.]

VI. But if I were asked, Whence came they then?
I could quickly answer, From the Gentiles, that knew not God;
for some amongst them detested them, as will be shown;
they were the pleasures of an effeminate Sardanapalus, a fantastic Miracles,
a comical Aristophanes, a prodigal Charaxus, a luxurious Aristippus;
and the practices of such women as the infamous Clytemnestra, the painted Jezebel,
the lascivious Campaspe, the immodest Posthumia, the costly Corinthian Lais,
the most impudent Flora, the wanton Egyptian Cleopatra, and most insatiable Messalina:
persons whose memories have stunk through all ages,
and that carry with them a perpetual rot: these,
and not the holy self-denying men and women in ancient times,
were devoted to the like recreations and vain delights.
Nay, the more sober of the very heathens themselves,
and that upon a principle of great virtue, as is by all confessed,
detested the like folly and wanton practices.
There is none of them to be found in Plato, or in Seneca`'s works: Pythagoras, Socrates,
Phocion, Zeno, etc. did not accustom themselves to these entertainments.
The virtuous Penelope, the chaste Lucretia, and the grave Cornelia, with many others,
could find themselves employment enough among their children, servants, and neighbours;
they, though nobles, next to their devotion, delighted most in spinning, weaving,
gardening, needlework, and such like good housewifery, and commendable entertainment:
who, though called Heathens, expressed much more Christianity in all their actions,
than do the wanton, foolish people of this age,
who notwithstanding will be called Christians.
But above all, you playmongers, whence think you,
came your so passionately beloved comedies; than which,
as there is not any one diversion that is more pernicious, so not one more in esteem,
and fondly frequented?
Why, I will tell you; their greatgrandfather was a Heathen,
and that not of the best sort: his name was Epicharmus.
It is true, he is called a philosopher, or a lover of wisdom; but he was only so by name;
and no more in reality than the comedians of these times are true Christians.
It is reported of him by Suidas, a Greek historian,
that he was the first man who invented comedies; and by the help of one Phormus,
he made also fifty fables.
But would you know his country, and the reason of his invention?
His country was Syracuse, the chief city in Sicily,
famous for the infamy of many tyrants; to please and gratify the lusts of some of whom,
he set his wits to work.
And do not you think this an ill original?
And is it less in any one to imitate, or justify the same,
since the more sober Heathens have themselves condemned them?
Nay, is it not abominable, when such as call themselves Christians,
do both imitate and justify the like inventions?
Nor had the melancholy tragedies a better parentage, namely, one Thespis,
an Athenian poet;
to whom they also do ascribe the original of that impudent custom of painting faces,
and the counterfeit, or representation of other persons, by change of habit, humours,
etc., all which are now so much in use and reputation with the great ones of the times.
To these let me add that poetical amoroso,
whom an inordinate passion of love first transported to those poetical raptures of admiration,
indeed sordid effeminacy, if not idolatry; they call him Alcman or Alcina, a Lydian:
he being exceedingly in love with a young woman of his own country,
is said to have been the first person that gave the world a sight of that kind of folly,
namely, love stories, and verses;
which have been so diligently imitated by almost all nations ever since in their romances.

Objection 2.

VII.
I know that some will say, But we have many comedies and tragedies, sonnets, catches,
etc. that are on purpose to reprehend vice, from whence we learn many commendable things.
Though this be shameful, yet many have been wont, for want of shame or understanding,
or both, to return me this for answer.
Now I readily shall confess,
that amongst the heathens it was the next remedy against the common
vices to the more grave and moral lectures of their philosophers,
of which number I shall instance two: Euripides,
whom Suidas calls a learned tragical poet, and Eupolis,
whom the same historian calls a comical poet.
The first was a man so chaste, and therefore so unlike those of our days,
that he was called one that hated women, that is, wanton ones,
for otherwise he was twice married;
the other he characters as a most severe reprehender of faults.
From which I gather, that their design was not to feed the idle lazy fancies of people,
nor merely to get money;
but since by the means of loose wits the people had been debauched,
their work was to reclaim them, rendering vice ridiculous,
and turning wit against wickedness.
And this appears the rather, from the description given,
as also that Euripides was supposed to have been torn in pieces by wanton women;
which doubtless was for declaiming against their impudence:
// lint-disable invalid-characters "æ"
and the other being slain in the battle betwixt the Athenians and Lacedæmonians,
was so regretted, that a law was made,
that never after such poets should be allowed to bear arms:
doubtless it was because in losing him they lost a reprover of vice.
So that the end of the approved comedians and tragedians of those
times was but to reform the people by making sin odious:
and that not so much by a rational and argumentative way, usual with their philosophers;
as by sharp jeers, severe reflections, and rendering their vicious actions shameful,
ridiculous, and detestable;
so that for reputation sake they might not longer be guilty of them:
which is to me but a little softer than a whip or a bridewell.
Now if you that plead for them will be contented to be accounted heathens,
and those of the more dissolute and wicked sort too,
that will sooner be jeered than argued out of your sins,
we shall acknowledge to you that such comedies and tragedies as these may be serviceable;
but then for shame abuse not the name of Jesus Christ
so impudently as to call yourselves Christians,
whose lusts are so strong,
that you are forced to use the low shifts of heathens to repel them:
to leave their evils not for the love of virtue, but out of fear, shame, or reputation.
Is this your love to Jesus, your reverence to the Scriptures,
that through faith are able to make the man of God perfect?
Is all your prattle about ordinances, prayers, sacraments, Christianity, and the like,
come to this;
that at last you must betake yourselves to such instructors as were by the sober heathens
permitted to reclaim the most vicious of the people that were amongst them?
And such remedies too as below which there is nothing but corporal punishment?

VIII.
This is so far from Christianity, that many of the nobler heathens, men and women,
were better taught, and better disposed; they found out more heavenly contemplations,
and subjects of an eternal nature to meditate upon.
Nay, so far did they outstrip the Christians of these times,
that they not only were exemplary by their grave and sober conversation;
// lint-disable invalid-characters "æ"
but for their public benefit the Athenians instituted the Gynæcosmi, or twenty men,
who should make it their business to observe the people`'s apparel and behaviour;
that if any were found immodest, and to demean themselves loosely,
they had full authority to punish them.
But the case is altered; it is punishable to reprove such: yes,
it is matter of the greatest contumely and reproach.
Nay, so impudent are some grown in their impieties,
that they sport themselves with such religious persons:
and not only manifest a great neglect of piety, and a severe life by their own looseness,
but their extreme contempt of it, by rendering it ridiculous,
through comical and abusive jests on public stages.
Which, how dangerous it is, and apt to make religion little worth in the people`'s eyes,
besides the demonstration of this age,
let us remember that Aristophanes had not a readier way to bring
the reputation of Socrates in question with the people,
who greatly reverenced him for his grave and virtuous life and doctrine,
than by his abusive representations of him in a play: which made the airy, wanton,
unstable crowd, rather part with Socrates in earnest, than Socrates in jest.
Nor can a better reason be given why the poor Quakers are made so much the scorn of men,
than because of their severe reprehensions of sin and vanity,
and their self-denying conversation,
amidst so great intemperance in all worldly satisfactions:
yet can such libertines all this while strut and swell for Christians,
and strut it out against precept and example; but we must be whimsical, conceited,
morose, melancholy, or else heretics, deceivers, and what not?
O blindness!
Pharisaical hypocrisy!
As if such were fit to be judges of religion;
or that it were possible for them to have a sight and sense of true religion,
or really to be religious,
whilst darkened in their understandings by the god of the pleasures of this world;
and their minds so wrapped up in external enjoyments, and the variety of worldly delight:
no, in the name of the everlasting God, you mock Him, and deceive your souls;
for the wrath of the Almighty is against you all, whilst in that spirit and condition;
in vain are all your babbles and set performances, God laughs you to scorn;
his anger is kindling because of these things: wherefore be ye warned to temperance,
and repent.

IX. Besides, this sort of people are not only wicked, loose, and vain,
who both invent and act these things;
but by your great delight in such vain inventions you encourage them therein,
and hinder them from more honest and more serviceable employments.
For what is the reason that most commodities are held at such excessive rates,
but because labour is so very dear?
And why is it so, but because so many hands are otherwise bestowed,
even about the very vanity of all vanities?
Nay, how common is it with these mercenary procurers to people`'s folly,
that when their purses begin to grow low,
they shall present them with a new and pretendedly more convenient fashion;
and that perhaps before the former costly habits shall have done half their service;
// lint-disable invalid-characters "à"
which either must be given away, or new vamped in the cut most à-la-mode.
O prodigal, yet frequent folly!

Objection 3.

X+++.+++ I know I am coming to encounter the most plausible objection
they are used to urge when driven to a pinch,
viz. But how shall those many families subsist whose livelihood depends
upon such fashions and recreations as you so earnestly decry?
I answer:
it is a bad argument to plead for the commission of the
least evil that never so great a good may come of it:
if you and they have made wickedness your pleasure and your profit,
be ye content that it should be your grief and punishment
till the one can learn to be without such vanity,
and the others have found out more honest employments.
It is the vanity of the few great ones that makes so much toil for the many small:
and the great excess of the one occasions the great labour of the other.
Would men learn to be contented with few things, such as are necessary and convenient,
(the ancient Christian life,) all things might be at a cheaper rate,
and men might live for little.
If the landlords had less lusts to satisfy, the tenants might have less rent to pay,
and turn from poor to rich,
whereby they might be able to find more honest and domestic employments
for their children than becoming sharpers and living by their wits,
which is but a better word for their sins.
And if the report of the more intelligent in husbandry be credible,
lands are generally improvable ten in twenty:
and were there more hands about more lawful and serviceable manufactures,
they would be cheaper, and greater vent might be made of them,
by which a benefit would redound to the world in general; nay,
the burden lies the heavier upon the laborious country,
that so many hands and shoulders as have the lust-caterers of the cities,
should be wanting to the plough and useful husbandry.
If men never think themselves rich enough, they may never miss of trouble and employment;
but those who can take the primitive state and God`'s creation for their model,
may learn with a little to be contented;
as knowing that desires after wealth do not only prevent or destroy true faith,
but when got increase snares and trouble.
It is no evil to repent of evil: but that cannot be,
whilst men maintain what they should repent of: it is a bad argument to avoid temperance,
or justify the contrary,
because otherwise the actors and inventors of excess would want a livelihood;
since to feed them that way is to nurse the cause instead of starving it.
Let such of those vanity hucksters as have got sufficient, be contented to retreat,
and spend it more honestly than they got it; and such as really are poor,
be rather helped by charity to better callings: this were more prudent, nay Christian,
than to consume money upon such foolish toys and fopperies.
Public workhouses would be effectual remedies to all these lazy and lustful distempers,
with more profit and a better conscience.
Therefore it is that we cannot, we dare not square our conversation by the world`'s: no,
but by our plainness and moderation to testify against such extravagant vanities;
and by our grave and steady life to manifest our dislike, on God`'s behalf,
to such intemperate and wanton curiosity: yea,
to deny ourselves what otherwise perhaps we lawfully could use with a just indifferency,
if not satisfaction; because of that abuse that is amongst the generality.

Objection 4.

XI. I know, that some are ready further to object:
Hath God given us these enjoyments on purpose to condemn us, if we use them?
Answer: But to such miserable, poor, silly souls,
who would rather charge the most high and holy God with
the invention or creation of their dirty vanities,
than want a plea to justify their own practice, not knowing how, for shame, or fear,
or love to throw them off; I answer, that what God made for man`'s use, was good,
and what the blessed Lord Jesus Christ allowed or enjoined,
or gave us in his most heavenly example, is to be observed, believed, and practised.^
footnote:[Luke 8:14; xii.
28-31.]
But in the whole catalogue the Scriptures give of both, I never found the attires,
recreations, and way of living,
so much in request with the generality of the Christians of these times: no certainly,
God created man a holy, wise, sober, grave, and reasonable creature,
fit to govern himself and the world:
but divinity was then the great object of his reason and pleasure;
all external enjoyments of God`'s giving being for necessity, convenience,
and lawful delight, with this proviso too, that the Almighty was to be seen,
and sensibly enjoyed and reverenced in every one of them.
But how very wide the Christians of these times are from
this primitive institution is not difficult to determine,
although they make such loud pretensions to that most holy Jesus,
who not only gave the world a certain evidence of a happy restoration, by his own coming,
but promised his assistance to all that would follow
Him in the self-denial and way of his holy cross;^
footnote:[John 8:12; xv.
7-8; xvii.
20.]
and therefore hath so severely enjoined no less on all,
as they would be everlastingly saved.
But whether the minds of men and women are not as
profoundly involved in all excess and vanity,
as those who know Him not any further than by hearsay;
and whether being thus banished the presence of the Lord,
by their greedy seeking the things that are below,
and thereby having lost the taste of divine pleasure,
they have not feigned to themselves an imaginary pleasure,
to quiet or smother conscience,
and pass their time without that anguish and trouble which are the consequences of sin,
that so they might be at ease and security while in the world,
let their own consciences declare.^
footnote:[Rom. 2:8-9.]
Adam`'s temptation is represented by the fruit of a tree,^
footnote:[Gen. 3:6.]
thereby intimating the great influence external objects, as they exceed in beauty,
carry with them upon our senses: so that unless the mind keep upon its constant watch,
so prevalent are visible things,
that hard it is for one to escape being insnared in them;^
footnote:[Mark 13:33-37.]
and he shall need to be only sometimes entrapped,
to cast so thick a veil of darkness over the mind,
that not only it shall with pleasure continue in its fetters to lust and vanity,
but proudly censure such as refuse to wear them, strongly pleading for them,
as serviceable and convenient:
that strange passion do perishing objects raise in those minds where way is made,
and entertainment given to them.
But Christ Jesus is manifested in us,
and hath given unto us a taste and understanding of Him that is true;
and to all such a proportion of his good spirit, as is sufficient, would they obey it,
to redeem their minds from that captivity they have been in to lust and vanity,
and entirely ransom them from the dominion of all visible objects,
and whatsoever may gratify the desires of the eye, the lust of the flesh,
and the pride of life;^
footnote:[1 John 2:15-16.]
that they might be regenerated in their minds, changed in their affections,
and have their whole hearts set on things that are above,
where moth nor rust can ever pass, or enter to harm or destroy.

XII.
But it is a manifest sign of what mold and make the persons
are who practise and plead for such shameful Egyptian rags,
as pleasures.
It is to be hoped that they never knew, or to be feared they have forgotten, the humble,
plain, meek, holy, self-denying, and exemplary life,
which the eternal Spirit sanctifies all obedient hearts into; yea,
it is indubitable that either such always have been ignorant,
or else they have lost sight of that good land, that heavenly country,
and blessed inheritance they once had some glimmering prospect of.^
footnote:[Gal. 5:22-25; Eph. 5:8-11, 15-16.]
O that they would but withdraw a while, sit down,
weigh and consider with themselves where they are,
and whose work and will they are doing! that they would once believe the
devil hath not a stratagem more pernicious to their immortal souls,
than this of exercising their minds in the foolish
fashions and wanton recreations of the times!
Great and gross impieties beget a detestation in
the opinion of sober education and reputation;
and therefore since the devil rightly sees such things have no success with many;
it is his next, and most fatal design, to find some other entertainments,
that carry less of infection in their looks, (though more of security,
because less of scandal,) and more of pleasure in their enjoyment,
on purpose to busy and arrest people from a diligent search and inquiry
after those matters which necessarily concern their eternal peace:^
footnote:[Eph. 6:12-19.]
that being ignorant of the heavenly life, they may not be induced to press after it;
but being only formally religious, according to the traditions and precepts of others,
proceed to their common pleasures, and find no check therefrom,
their religion and conversation for the most part agreeing well together,
whereby an improvement in the knowledge of God, going on from grace to grace,
growing to the measure of the stature of Jesus Christ himself, is not known;
but as it was in the beginning at seven, so it is at seventy; nay, not so innocent,
unless by reason of the old saying, "`Old men are twice children.`"^
footnote:[Eph. 1:16-23; iv.
12, 13.]

O! the mystery of godliness, the heavenly life, the true Christian, are another thing.
Wherefore we conclude that as the design of the devil,
where he cannot involve and draw into gross sin, is to busy, delight,
and allure the minds of men and women by more seeming innocent entertainments,
on purpose that he may more easily secure them from minding their duty and progress,
and obedience to the only true God, which is eternal life;^
footnote:[John 17:3.]
and thereby take up their minds from heavenly and eternal things;
so those who would be delivered from these snares should mind the holy, just, grave,
and self-denying teachings of God`'s grace and Spirit in themselves,
that they may reject, and forever abandon the like vanity and evil;^
footnote:[Tit. 2:11-15.]
and by a reformed conversation condemn the world of its intemperance:
so will the true discipleship be obtained:
for otherwise many enormous consequences and pernicious effects will follow.
It is to encourage such impious persons,
to continue and proceed in the like trades of feeding the people`'s lusts;
and thereby such make themselves partakers of their plagues,
who by continual fresh desire to the like curiosities,
and that way of spending time and estate,
induce them to spend more time in studying how to abuse time; lest,
through their pinching and small allowance,
those prodigals should call their father`'s house to mind: for whatsoever any think,
more pleasant baits, alluring objects, grateful entertainments, cunning emissaries,
acceptable sermons, insinuating lectures, taking orators,
the crafty devil has not ever had, by which to entice and insnare the minds of people,
and totally to divert them from heavenly reflections and divine meditations,
than the attire, sports, plays, and pastimes of this godless age,
the school and shop of Satan, hitherto so reasonably condemned.
