== Chapter XVIII.

[.chapter-synopsis]
* 1+++.+++ But if these customs, etc. were but indifferent, yet being abused they deserve to be rejected.
* 2+++.+++ The abuse is acknowledged by those that use them, therefore should leave them.
* 3+++.+++ Such as pretend to seriousness should exemplarily withdraw from such latitudes: a wise parent weans his child of what it dotes too much upon; and we should watch over ourselves and neighbours.
* 4+++.+++ God, in the case of the brazen serpent, etc. gives us an example to put away the use of abused things.
* 5+++.+++ If these things were sometimes convenient, yet when their use is prejudicial in example, they should be disused.
* 6+++.+++ Such as yet proceed to love their unlawful pleasures more than Christ and his cross; the mischief they have brought to persons and estates, bodies and souls.
* 7+++.+++ Ingenuous people know this to be true: an appeal to God`'s witness in the guilty: their state, that of Babylon.
* 8+++.+++ But temperance in food, and plainness in apparel, and sober conversation conduce most to good: so the apostle teaches in his epistles.
* 9+++.+++ Temperance enriches a land: it is a political good, as well as a religious one, in all governments.
* 10+++.+++ When people have done their duty to God, it will be time enough to think of pleasing themselves.
* 11+++.+++ An address to the magistrates and all people, how to convert their time and money to better purposes.

[.numbered-group]
====

[.numbered]
I+++.+++ But should these things be as indifferent, as they are proved perniciously unlawful;
for I never heard any advance their plea beyond the bounds of mere indifferency;
yet so great is their abuse, so universal the sad effects thereof, like to an infection,
that they therefore ought to be rejected of all;
especially those whose sobriety hath preserved theta on this side of that excess,
or whose judgments, though themselves be guilty, suggest the folly of such intemperance.
For what is an indifferent thing, but that which may be done, or left undone?
Granting, I say, this were the case,
yet do both reason and religion teach that when they are used with such
an excess of appetite as to leave them would be a cross to their desires,
they have exceeded the bounds of mere indifferency,
and are thereby rendered no less than necessary.
Which being a violation of the very nature of the things themselves,
a perfect abuse enters;
and consequently they are no longer to be considered in the rank of things simply indifferent,
but unlawful.

[.numbered]
II. Now that the whole exchange of things, against which I have so earnestly contended,
are generally abused by the excess of almost all ages, sexes, and qualities of people,
will be confessed by many, who yet decline not to conform themselves to them;
and to whom, as I have understood, it only seems lawful, because, say they,
the abuse of others should be no argument why we should not use them.
But to such I answer, That they have quite forgotten, or will not remember,
they have acknowledged these things to be but of an indifferent nature; if so,
and vanity never urged more, I say, there can be nothing more clear,
than since they acknowledge their great abuse, that they are wholly to be forsaken:
for since they may as well be let alone as done at any time,
surely they should then of duty be let alone,
when the use of them is an abetting the general excess,^
footnote:[Phil. 3:17.]
and a mere exciting others to continue in their abuse,
because they find persons reputed sober to imitate them,
or otherwise give them an example.
Precepts are not half so forcible as examples.

[.numbered]
III.
Every one that pretends to seriousness ought to inspect himself,
as having been too forward to help on the excess,
and can never make too much haste out of those inconveniencies
that by his former example he encouraged any to;
that by a new one he may put a seasonable check upon the intemperance of others.^
footnote:[Rom.
xiv. to the end.]
A wise parent ever withdraws those objects, however innocent in themselves,
which are too prevalent upon the weak senses of his children,
on purpose that they might be weaned:
and it is as frequent with men to bend a crooked stick as much the contrary way,
that they might make it straight at last.
Those that have more sobriety than others should not forget their stewardships,
but exercise that gift of God to the security of their neighbours.
It was murdering Cain that rudely asked the Lord, "`Was he his brother`'s keeper?`"^
footnote:[Gen. 4:9.]
For every man is necessarily obliged thereto;
and therefore should be so wise as to deny himself the use of such indifferent enjoyments
as cannot be used by him without too manifest an encouragement to his neighbour`'s folly.

[.numbered]
IV. God hath sufficiently excited men to what is said;
for in the case of the brazen serpent,
which was a heavenly institution and type of Christ,
he with great displeasure enjoined it should be broken to pieces,
because they were too fond and doting upon it.^
footnote:[2 Kings 18:3-4.]
Yes, the very groves themselves, however pleasant for situation,
beautiful for their walks and trees, must be cut down: and why?
Only because they had been abused to idolatrous uses.
And what is an idol but that which the mind puts an over-estimate or value upon?
None can benefit themselves so much by an indifferent
thing as others by not using that abused liberty.

[.numbered]
V+++.+++ If those things were convenient in themselves,
which is a step nearer necessity than mere indifferency,
yet when by circumstances they become prejudicial,
such conveniency itself ought to be put off;
much more what is but indifferent should be denied.
People ought not to weigh their private satisfactions more than a public good;
nor please themselves in too free a use of indifferent things,
at the cost of being so really prejudicial to the public as they certainly are,
whose use of them, if no worse, becomes exemplary to others,
and begets an impatience in their minds to have the like.
Wherefore it is both reasonable and incumbent on all to
make only such things necessary as tend to life and godliness,
and to employ their freedom with most advantage to their neighbours.^
footnote:[2 Pet. 1:3.]
So that here is a two-fold obligation;
the one not to be exemplary in the use of such things, which though they may use them,
yet not without giving too much countenance to the
abuse and excessive vanity of their neighbours.
The other obligation is, that they ought so far to condescend to such religious people,
who are offended at these fashions, and that kind of conversation as to reject them.^
footnote:[Rom. 14:1, to the end.]

[.numbered]
VI. Now those who, notwithstanding what I have urged, will yet proceed;
what is it but that they have so involved themselves and their affections in them,
that it is hardly possible to reform them;
and that for all their many protestations against their fondness to such fopperies,
they really love them more than Christ and his cross.
Such cannot seek the good of others, who do so little respect their own.
For, after a serious consideration, what vanity, pride, idleness,
expense of time and estates have been and yet are!
How many persons debauched from their first sobriety,
and women from their natural sweetness and innocency to loose, airy, wanton,
and many times more enormous practices!
How many plentiful estates have been overrun by numerous debts,
chastity ensnared by accursed lustful intrigues;
youthful health overtaken by the hasty seizure of unnatural distempers,
and the remaining days of such spent upon a rack of their vice`'s procuring,
and so made slaves to the unmerciful but necessary effects of their own
inordinate pleasures! in which agony they vow the greatest temperance,
but are no sooner out of it, than in their vice again.^
footnote:[Lam. 4:5; Job 21:13-14; Ps. 55:23; xxxvii.
10; Ecc. 8:12; Ps. 37:1-2; Prov. 2:22.]

[.numbered]
VII.
That these things are the case, and almost innumerable more,
I am persuaded no ingenuous person of any experience will deny: how then,
upon a serious reflection, any that pretend conscience or the fear of God Almighty,
can longer continue in the garb, livery,
and conversation of those whose whole life tends to little else than what I have repeated,
much less join with them in their abominable excess,
I leave to the just principle in themselves to judge.^
footnote:[Jer. 16:5-9.]
No, surely! this is not to obey the voice of God, who in all ages did loudly cry to all,
Come out of--of what?--the ways, fashions, converse, and spirit of Babylon.^
footnote:[Isa. 3:13-16; Jer. 50:8; xv.
6, 7; Amos 6:3-7.]
What is that?
The great city of all these vain, foolish, wanton, superfluous, and wicked practices,
against which the Scriptures denounce most dreadful judgments;
ascribing all the intemperance of men and women to
the cup of wickedness she hath given them to drink;
whose are the things indifferent, if they must be so.
And for witness, John in his revelation says in her description:
How much she hath glorified herself, and lived deliciously,
so much torment and sorrow give her.
And the kings of the earth, who have lived deliciously with her,
shall bewail her and lament her;
and the merchants of the earth shall weep and mourn over her;
for no man buyeth her merchandise any more; the merchandise of gold, and silver,
and precious stones, and of pearls, and fine linen, and purple, and silk, and scarlet,
and thyine-wood, and all manner of vessels of ivory,
and all manner of vessels of most precious wood, and of brass, and iron, and marble;
and cinnamon, and odours, and ointments, and frankincense, and wine, and oil,
and fine flour, and wheat, and beasts, and sheep, and horses, and chariots, and slaves,
and souls of men.^
footnote:[Rev. 18:11,7,9-13.]
Behold the character and judgment of luxury:
and though I know it hath a further signification than what is literal,
yet there is enough to show the pomp, plenty, fulness, idleness, ease, wantonness,
vanity, lust, and excess of luxury that reign in her.
But at the terrible day, who will go to her exchange any more?
Who to her plays?
Who will follow her fashions then?
And who shall traffic in her delicate inventions?
Not one; for she shall be judged.
No plea shall excuse or rescue her from the wrath of the Judge; for strong is the Lord,
who will perform it.^
footnote:[Rev. 18:8.]
If these reasonable pleas will not prevail,
yet however I shall caution such in the repetition of part of Babylon`'s miserable doom:
mind, my friends, more heavenly things,
hasten to obey that righteous principle which would
exercise and delight you in that which is eternal;
or else with Babylon, the mother of lust and vanity,
the fruits that your souls lust after shall depart from you,
and all things which are dainty and goodly shall
depart from you and you shall find them no more:
O Dives!
No more.^
footnote:[Rev. 18:14.]
Lay your treasures, therefore, up in heaven, O ye inhabitants of the earth,
where nothing can break through to harm them;
but where time shall shortly be swallowed up of eternity.^
footnote:[Luke 12:33-34.]

[.numbered]
VIII.
But my arguments against these things end not here:
for the contrary most of all conduces to good; namely, temperance in food,
plainness in apparel, with a meek, shame-faced, and quiet spirit,
and that conversation which doth only express the same in all godly honesty:
as the apostle saith, "`Let no corrupt communication proceed out of your mouth,
but that which is good to the use of edifying, that it may minister grace to the hearers;
neither filthiness, nor foolish talking, nor jesting, but rather giving of thanks:
for let no man deceive you with vain words,
because of these things cometh the wrath of God upon the children of disobedience.`"^
footnote:[Col. 4:5-6; 1 Thess. 4:11-12; 1 Pet. 3:1-4; Eph. 4:2; v. 3-6;
1 Tim. 4:12; Phil. 3:16-20.]
And if men and women were but thus adorned after this truly Christian manner,
impudence would soon receive a check, and lust, pride, vanity,
and wantonness find a rebuke.^
footnote:[1 Pet. 2:12; Prov. 31:23-31; James 2:2-9.]
They would not be able to attack such universal chastity or encounter such godly austerity:
virtue would be in credit, and vice afraid and ashamed,
and excess not dare to show its face.
There would be an end of gluttony and gaudiness of apparel, flattering titles,
and a luxurious life;^
footnote:[2 Pet. 3:11; Ps. 26:6.]
and then primitive innocency and plainness would come back again, and that plain-hearted,
downright, harmless life would be restored, of not much caring what we should eat, drink,
or put on,^
footnote:[Luke 12:22-30.]
as Christ tells us the Gentiles did, and as we know this age daily does,
under all its talk of religion; but as the ancients,
who with moderate care for necessaries and conveniencies of life,
devoted themselves to the concernments of a celestial kingdom,
and more minded their improvement in righteousness than their increase in riches;
for they laid their treasure up in heaven,^
footnote:[Matt. 25:21.]
and endured tribulation for an inheritance that cannot be taken away.

[.numbered]
IX. But the temperance I plead for is not only religiously but politically good:
it is the interest of good government to curb and rebuke excesses:
it prevents many mischiefs.
Luxury brings effeminacy, laziness, poverty, and misery;^
footnote:[Prov. 10:4; Ecc. 10:16-18.]
but temperance preserves the land.
It keeps out foreign vanities, and improves our own commodities:
now we are their debtors; then they would be debtors to us for our native manufactures.
By this means, such persons who by their excess, not charity,
have deeply engaged their estates,
may in a short space be enabled to clear them from those incumbrances which otherwise,
like moths, soon eat out plentiful revenues.
It helps persons of mean substance to improve their small stocks,
that they may not expend their dear earnings,
and hard-got wages upon superfluous apparel, foolish May-games, plays, dancings, shows,
taverns, ale-houses, and the like folly and intemperance,
of which this land is more infested,
and by which it is rendered more ridiculous than any kingdom in the world:
for none I know of is so infested with cheating mountebanks, savage morrice-dancers,
pick-pockets, and profane players, and stagers, to the slight of religion,
the shame of government, and the great idleness, expense, and debauchery of the people:
for which the Spirit of the Lord is grieved,
and the judgments of the Almighty are at the door,
and the sentence ready to be pronounced, "`Let him that is unjust be unjust still.`"^
footnote:[Rev. 22:11.]
Wherefore it is that we cannot but loudly call upon the generality of the times,
and testify both by our life and doctrine against the like vanities and abuses,
if possibly any may be weaned from their folly,
and choose the good old path of temperance, wisdom, gravity, and holiness,
the only way to inherit the blessings of peace and plenty here,
and eternal happiness hereafter.

[.numbered]
X+++.+++ Lastly,
supposing we had none of these foregoing reasons justly
to reprove the practice of the land in these particulars;
however, let it be sufficient for us to say, that when people have first learned to fear,
worship, and obey their Creator, to pay their numerous vicious debts,
to alleviate and abate their oppressed tenants; but above all outward regards,
when the pale faces are more commiserated, when the famished poor, the distressed widow,
and helpless orphan, God`'s works, and your fellow creatures, are provided for; then,
I say, if then,
it will be time enough for you to plead the indifferency of your pleasures.
But that the sweet and tedious labour of the husbandman, early and late, cold and hot,
wet and dry, should be converted into the pleasure, ease,
and pastime of a small number of men; that the cart, the plough, the flail,
should be in that continual severity laid upon nineteen parts of the land,
to feed the inordinate lusts and delicious appetites of the twentieth,
is so far from the appointment of the great Governor of the world,
and God of the spirits of all flesh, that,
to imagine such horrible injustice as the effects of his determinations,
and not the intemperance of men, were wretched and blasphemous.
As on the other side, it would be to deserve no pity, no help,
no relief from God Almighty, for people to continue that expense in vanity and pleasure,
whilst the great necessities of such objects go unanswered;
especially since God hath made the sons of men but
stewards to each other`'s exigencies and relief.
Yea, so strict is it enjoined, that on the omission of these things,
we find this dreadful sentence partly to be grounded, "`Depart from me, ye cursed,
into everlasting fire,`" etc.
As on the contrary, to visit the sick, see the imprisoned, relieve the needy,
etc. are such excellent properties in Christ`'s account,
that thereupon He will pronounce such blessed, saying, "`Come, ye blessed of my Father,
inherit the kingdom prepared for you,`" etc.^
footnote:[Matt. 25:34-41.]
So that the great are not, with the leviathan in the deep, to prey upon the small,
much less to make a sport of the lives and labours of the lesser ones,
to gratify their inordinate senses.^
footnote:[Ecc. 12:1; Ps. 37:21; Ps. 10:2; Ps. 4:2; Psal.
1Xxix.
12; Ps. 82:3-4; Prov. 22:7; Isa. 3:14-15; Ezek. 22:29; Amos 5:11-12, ch.
Viii.
4, 7-8; Isa. 1:16-18; Jer. 7:6; Rom. 12:20; 2 Cor. 9:7; Ps. 40:4;
Acts 10:34; Rom. 2:11; Eph. 6:9; Col. 3:25; 1 Pet. 1:17; James 5:4-5;
Ps. 41:1; Matt. 25:34-36; James 2:15-16; Ps. 112:9.]

[.numbered]
XI. I therefore humbly offer an address to the serious consideration of the civil magistrate,
that,
if the money which is expended in every parish in such vain fashions as wearing of laces,
jewels, embroideries, unnecessary ribbons, trimmings, costly furniture, and attendance,
together with what is commonly consumed in taverns, feasts, gaming,
etc. could be collected into a public stock,
or something in lieu of this extravagant and fruitless expense,
there might be reparation to the broken tenants, workhouses for the able,
and alms-houses for the aged and impotent.^
footnote:[Prov. 14:21; Matt. 19:21.]
Then should we have no beggars in the land,
the cry of the widow and the orphan would cease,
and charitable relief might easily be afforded towards the redemption of poor captives,
and the refreshment of such distressed Protestants as labour
under the miseries of persecution in other countries:
nay, the Exchequer`'s needs, on just emergencies, might be supplied by such a bank:
this sacrifice and service would please the just and merciful God:
it would be a noble example of gravity and temperance to foreign states,
and an unspeakable benefit to ourselves at home.

Alas! why should men need persuasions to what their
own felicity so necessarily leads them?
Had these vitiosos of the times but a sense of heathen Cato`'s generosity,
they would rather deny their carnal appetites than leave such noble enterprises unattempted.
But that they should eat, drink, play, game, and sport away their health, estates, and,
above all, their irrevocable precious time, which should be dedicated to the Lord,
as a necessary introduction to a blessed eternity, and than which, did they but know it,
no worldly solace would come in competition: I say,
that they should be continually employed about these poor,
low things is to have the heathens judge them in God`'s days,
as well as Christian precepts and examples condemn them.
And their final doom will prove the more astonishing,
in that this vanity and excess are acted under a
profession of the self-denying religion of Jesus,
whose life and doctrine are a perpetual reproach to the most of Christians.
For He was humble, but they are proud; He forgiving, they revengeful; He meek,
they fierce; He plain, they gaudy; He abstemious, they luxurious; He chaste,
they lascivious: He a pilgrim on earth, they citizens of the world: in fine,
He was meanly born, poorly attended, and obscurely brought up; He lived despised,
and died hated of the men of his own nation.
O you pretended followers of this crucified Jesus! examine yourselves, try yourselves,
know you not your own selves; if He dwell not, if He rule not in you,
that you are reprobates?
Be ye not deceived, for God will not be mocked,
(at last with forced repentances,) such as you sow, such you must reap.^
footnote:[1 Cor. 13:5; Gal. 6:8.]
I beseech you to hear me,
and remember you were invited and entreated to the salvation of God.
I say; as you sow, you reap:
if you are enemies to the cross of Christ,--and you are so if you will not bear it,
but do as you list, and not as you ought;--if you are uncircumcised in heart and ear,
and you are so, if you will not hear, and open to Him that knocks at the door within,
and if you resist and quench the Spirit in yourselves, that strives with you,
to bring you to God, (and that you certainly do who rebel against its motions, reproofs,
and instructions,) then you sow to the flesh, to fulfill the lusts thereof,
and of the flesh will you reap the fruits of corruption,^
footnote:[Rom. 2:8.]
woe, anguish, and tribulation, from God, the Judge of quick and dead, by Jesus Christ.
But if you will daily bear the holy cross of Christ, and sow to the Spirit;
if you will listen to the light and grace that comes by Jesus,
and which He has given to all people for salvation, and square your thoughts, words,
and deeds thereby,
which leads and teaches the lovers of it to deny all ungodliness and the world`'s lusts,
and to live soberly, righteously, and godly in this present evil world,
then may you with confidence look for the blessed hope and joyful coming,
and glorious appearance of the great God and our Saviour Jesus Christ.^
footnote:[Tit. 2:11-13.]
Let it be so, O you Christians, and escape the wrath to come!
Why will you die?
Let the time past suffice: remember, that No Cross, no Crown.
Redeem then the time, for the days are evil,^
footnote:[Eph. 5:16.]
and yours are but very few.
Therefore gird up the loins of your minds, be sober, fear, watch, pray,
and endure to the end; calling to mind for your encouragement and consolation,
that all such as through patience and well-doing wait for immortality,^
footnote:[Rom. 2:7.]
shall reap glory, honour, and eternal life in the kingdom of the Father:
whose is the kingdom, the power, and the glory forever.
Amen.

====

[.the-end]
End of Part I.
