== Preface.

No Cross, No Crown, should have ended here;
but that the power which examples and authorities have put upon the minds of the people,
above the most reasonable and pressing arguments,
inclined me to present my readers with some of those many instances that might be given,
in favour of the virtuous life recommended in our discourse.
I chose to cast them into three sorts of testimonies,
not after the threefold subject of the book; but suitable to the times, qualities,
and circumstances of the persons that gave them forth;
whose divers excellencies and stations have transmitted
their names with reputation to our own times.
The first testimony comes from those called Heathens;
the second from professed Christians; and the last, from retired, aged, and dying men;
being their last and serious reflections,
to which no ostentation or worldly interests could induce them.
Where it will be easy for the considerate reader to observe, how much the pride, avarice,
and luxury of the world stood reprehended in the
judgments of persons of great credit amongst men;
and what was that life and conduct, that in their most retired meditations,
when their sight was clearest, and judgment most free and disabused,
they thought would give peace here, and lay foundations of eternal blessedness.
