== Chapter XIX.

The Testimonies of several great, learned, and virtuous personages among the Gentiles,
urged against the excesses of the age, in favour of the self-denial, temperance,
and piety, recommended in the first part of this discourse.

=== I. Among the Greeks, etc. viz.

1+++.+++ Cyrus.--2. Artaxerxes.--3. Agathocles.--4. Philip.--5. Alexander.--6.
Ptolemy.--7. Xenophanes.--8. Antigonus.--9. Themistocles.--10. Aristides.--11.
Pericles.--12. Phocion.--13. Clitomachus.--14. Epaminondas.--15. Demosthenes.--16.
Agasicles.--17. Agesilaus.--18. Agis.--19. Alcamenes.--20. Alexandrides.--21.
Anaxilas.--22. Ariston.--23. Archidamus.--24. Cleomenes.--25. Dersyllidas.--26.
Hippodamus.--27. Leonidas.--28. Lysander.--29. Pausanias.--30. Theopompus,
etc.--31. The manner of life and government of the
// lint-disable invalid-characters "æ"
Lacedæmonians in general.--32. Lycurgus their lawgiver.

I+++.+++ Cyrus, than whom a greater monarch we hardly find in story,
is more famous for his virtue than his power; God calls him his shepherd.
Now let us see the principles of his conduct and life.
So temperate was he in his youth, that when Astyages, urged him to drink wine,
he answered, "`I am afraid lest there should be poison in it,
having seen thee reel and sottish after having drunk thereof.`"
And so careful was he to keep the Persians from corruption of manners,
that he would not suffer them to leave their rude and mountainous country,
for one more pleasant and fruitful, lest through plenty and ease,
luxury at last might debase their spirits.
And so very chaste was he, that having taken a lady of quality, a most beautiful woman,
his prisoner, he refused to see her, saying,
"`I have no mind to be a captive to my captive.`"
It seems, he claimed no such propriety; but shunned the occasion of evil.
The comptroller of his household asking him one day
what he would please to have for his dinner;
"`Bread,`" said he;
"`for I intend to encamp nigh the water:`" a short and easy bill of fare:
but this shows the power he had over his appetite as well as his soldiers;
and that he was fit to command others, that could command himself:
according to another saying of his, "`No man,`" saith he, "`is worthy to command,
who is not better than those who are to obey.`"
And when he came to die, he gave this reason of his belief of immortality;
"`I cannot,`" said he, "`persuade myself to think that the soul of man,
after having sustained itself in a mortal body, should perish when delivered out of it,
for want of it;`" a saying of perhaps as great weight,
as may be advanced against Atheism, from more enlightened times.

II. Artaxerxes Mnemon, being upon an extraordinary occasion reduced to eat barley bread,
and dried figs, and drink water, "`What pleasure,`" saith he, "`have I lost till now,
through my delicacies and excess!`"

III.
Agathocles becoming king of Sicily, from being the son of a potter,
always to humble his mind to his original,
would be daily served in earthen vessels upon his table:
an example of humility and plainness.

IV. Philip, king of Macedon, upon three sorts of good news, arrived in one day,
feared too much success might transport him immoderately;
and therefore prayed for some disappointments to season his prosperity,
and caution his mind under the enjoyment of it.
He refused to oppress the Greeks with his garrisons, saying,
"`I had rather retain them by kindness than fear, and to be always beloved,
than for a while terrible.`"
One of his minions persuading him to decline hearing a cause,
wherein a particular friend was interested, "`I had much rather,`" says he,
"`thy friend shall lose his cause, than I my reputation.`"
Seeing his son, Alexander, endeavouring to gain the hearts of the Macedonians,
by gifts and rewards, "`Canst thou believe,`" says he,
"`that a man that thou hast corrupted to thy interests, will ever be true to them?`"
When his court would have had him quarrel with and correct
the Peloponnenses for their ingratitude to him,
he said, "`By no means; for if they despise and abuse me after being kind to them,
what will they do if I do them harm?`"--a great example of patience in a king,
and wittily said.
Like to this was his reply to the ambassadors of Athens, whom asking after audience,
if he could do them any service, and one of them surlily answering,
The best thou canst do us is to hang thyself, he was nothing disturbed,
though his court murmured; but calmly said to the ambassador,
"`Those who suffer injuries are better people than those that do them.`"
To conclude with him: being one day fallen along the ground,
and seeing himself in that posture he cried out,
"`What a small spot of earth do we take up, and yet the whole world cannot content us!`"

V+++.+++ Alexander was very temperate and virtuous in his youth:
a certain governor having written to him,
that a merchant of the place had several fine boys to sell,
he returned him this answer with great indignation,
What hast thou seen in any act of my life,
that should put thee upon such a message as this?
and avoided the woman his courtiers flung in his way to debauch him.
Nay, he would not see the wife of Darius,
famed for the most beautiful princess of the age; which with his other virtues,
made Darius (the last Persian king) to say,
"`If God has determined to take my empire from me, I wish it into the hands of Alexander,
my virtuous enemy.
He hated covetousness; for though he left great conquests,
he left no riches;`" which made him thus to answer one that asked him dying,
"`Where he had hid his treasures:`" "`Among my friends,`" says he.
He was wont to say, He owed more to his master for his education,
than to his father for his birth; by how much it was less to live, than to live well.

VI. Ptolemy, son of Lagus, being reproached for his mean original,
and his friends angry that he did not resent it; "`We ought,`" says he,
"`to bear reproaches patiently.`"

VII.
Xenophanes being jeered for refusing to play at a forbidden game, answered:
"`I do not fear my money, but my reputation: they that make laws, must keep them.`"
A commendable saying.

VIII.
Antigonus being taken sick, he said,
it was a warning from God to instruct him of his mortality.
A poet flattered him with the title of the Son of God, he answered,
"`My servant knows the contrary.`"
Another sycophant telling him, that the will of kings is the rule of justice:
"`No,`" saith he,
"`rather justice is the rule of the will of kings;`" and
being pressed by his minions to put a garrison into Athens,
to hold the Greeks in subjection, he answered,
"`he had not a stronger garrison than the affections of his people.`"

IX. Themistocles, after all the honour of his life, sits down with this conclusion,
"`That the way to the grave is more desirable than the way to worldly honours.`"
His daughter being courted by one of little wit and great wealth,
and another of little wealth and great goodness;
he chose the poor man for his son-in-law: "`For,`" saith he,
"`I will rather have a man without money, than money without a man;`" reckoning,
that not money, but worth, makes the man.
Being told by Symmachus, that he would teach him the art of memory; he gravely answered,
he had rather learn the art of forgetfulness: adding, he could remember enough,
but many things he could not forget, which were necessary to be forgotten:
as the honours, glories, pleasures, and conquests he had spent his days in:
too apt to transport to vain glory.

X+++.+++ Aristides, a wise and just Greek,
of greatest honour and trust with the Athenians;--he
was a great enemy to cabals in government:
the reason he renders is, "`Because,`" saith he,
"`I would not be obliged to authorize injustice.`"
He so much hated covetousness, though he was thrice chosen treasurer of Athens,
that he lived and died poor, and that of choice:
for being therefore reproached by a rich usurer, he answered,
"`Thy riches hurt thee more than my poverty hurts me.`"
Being once banished by a contrary faction in the state, he prayed to God,
that the affairs of his country might go so well, as never to need his return:
which however caused him presently to be recalled: whereupon he told them,
that he was not troubled for his exile with respect to himself,
but the honour of his country.
Themistocles, their general, had a project to propose,
to render Athens mistress of Greece, but it required secrecy:
the people obliged him to communicate it to Aristides, whose judgment they would follow.
Aristides having privately heard it from Themistocles, publicly answered the people,
"`True there was nothing more advantageous,
nothing more unjust:`" which quashed the project.

XI. Pericles, as he mounted the tribunal,
prayed to God that not a word might fall from him, that might scandalize the people,
wrong the public affairs, or hurt his own.
One of his friends praying him to speak falsely in his favour;
"`We are friends,`" saith he,
"`but not beyond the altar;`" meaning not against religion and truth.
Sophocles being his companion, upon sight of a beautiful woman, said to Pericles, "`Ah,
what a lovely creature is that!`"
To whom Pericles replied, "`It becometh a magistrate not only to have his hands clean,
but his tongue and eyes also.`"

XII.
Phocion, a famous Athenian, was honest and poor, yea, he contemned riches:
for a certain governor making rich presents, he returned them; saying,
"`I refused Alexander`'s.`" And when several persuaded him to accept of such bounty,
or else his children would want, he answered, "`If my son be virtuous,
I shall leave him enough; and if he be vicious, more would be too little.`"
He rebuked the excess of the Athenians, and that openly; saying,
"`He that eateth more than he ought, maketh more diseases than he can cure.`"
To condemn or flatter him, was to him alike.
Antipater pressing him to submit to his sense, he answered,
"`Thou canst not have me for thy friend and flatterer too.`"
Seeing a man in office to speak much, and do little, he asked,
"`How can that man do business, that is always drunk with talking?`"
After all the great services of his life, he was unjustly condemned to die;
and going to the place of execution, lamented by the people,
one of his enemies spit in his face; he took it without any disorder of mind,
only saying, "`Take him away.`"
Before execution, his friends asked him, whether he had nothing to say to his son?
"`Yes,`" said he, "`let him not hate my enemies, nor revenge my death:
I see it is better to sleep on the earth with peace,
than with trouble upon the softest bed: that he ought to do that which is his duty;
and what is more is vanity: that he must not carry two faces: that he promise little,
but keep his promises: the world does the contrary.`"

XIII.
Clitomachus had so great a love to virtue, and practised it with such exactness,
that if at any time in company he heard wanton or obscene discourse,
he was wont to quit the place.

XIV.
Epaminondas being invited to a sacrificial feast, so soon as he entered he withdrew,
because of the sumptuous furniture and attire of the place and people; saying,
"`I was called at Leurtra to a sacrifice, but I find it is a debauch.`"
The day after the great battle he obtained upon his enemies, he seemed sad and solitary,
which was not his ordinary temper; and being asked why, answered,
"`I would moderate the joy of yesterday`'s triumphs.`"
A Thessalian general, and his colleague in a certain enterprise, knowing his poverty,
sent him two thousand crowns to defray his part of the charges; but he seemed angry,
and answered,
"`This looks like corrupting me;`" contenting himself with less than five pounds,
which he borrowed of one of his friends for that service.
The same moderation made him refuse the presents of the Persian emperor, saying,
"`They were needless if he only desired of him what was just; if more,
he was not rich enough to corrupt him.`"
Seeing a rich man refuse to lend one of his friends money that was in affliction,
he said, "`Art not thou ashamed to refuse to help a good man in necessity?`"
After he had freed Greece from trouble, and made the Thebans, his countrymen,
// lint-disable invalid-characters "æ"
triumph over the Lacedæmonians, till then invincible,
that ungrateful people arraigned him and his friends,
under pretence of acting something without authority: he, as general,
took the blame upon himself, justified the action both from necessity and success,
arraigning his judges for ingratitude whilst himself was at the bar,
which caused them to withdraw with fallen countenances,
and hearts smitten with guilt and fear.
To conclude, he was a man of great truth and patience, as well as wisdom and courage;
for he was never observed to lie in earnest or in jest.
And notwithstanding the ill and cross humours of the Thebans,
aggravated by his incomparable hazards and services for their freedom and renown,
it is reported of him that he ever bore them patiently,
often saying that he ought no more to be revenged of his country than of his father.

XV. Demosthenes, the great orator of Athens, had these sentences:
"`That wise men speak little,
and that therefore nature hath given men two ears and one tongue,
to hear more than they speak.`"
To one that spoke much he said, "`How cometh it that he who taught thee to speak,
did not teach thee to hold thy tongue?`"
He said of a covetous man, "`That he knew not how to live all his lifetime,
and that he left it for another to live after he was dead.
That it was an easy thing to deceive one`'s self,
because it was easy to persuade one`'s self to what one desired.`"
He said, "`That calumnies were easily received, but time would always discover them.
That there was nothing more uneasy to good men than
not to have the liberty of speaking freely;
and that if any one knew what he had to suffer from the people,
he would never meddle to govern them.
In fine, that man`'s happiness was to be like God; and to resemble Him,
we must love truth and justice.`"

XVI.
// lint-disable invalid-characters "æ"
Agasicles, king of the Lacedæmonians, or Spartans, which are one,
was of the opinion that it was better to govern without force: and, says he,
the means to do it is to govern the people as a father governs his children.

XVII.
Agesilaus, king of the same people, would say,
that he had rather be master of himself than of the greatest city of his enemies:
and to preserve his own liberty than to usurp the liberty of another man.
"`A prince,`" says he, "`ought to distinguish himself from his subjects by his virtue,
and not by his state or delicacy of life.`"
Wherefore he wore plain, simple clothing;
his table was as moderate and his bed as hard as that of any ordinary subject.
And when he was told that one time or other he would be obliged to change his fashion:
"`No,`" saith he, "`I am not given to change even in a change: and this I do,`" saith he,
"`to remove from young men any pretence of luxury,
that they may see their prince practise what he counsels them to do.`"
// lint-disable invalid-characters "æ"
He added, "`That the foundation of the Lacedæmonian laws was to despise luxury,
and to reward with liberty; nor,`" saith he,
"`should good men put a value upon that which mean and base souls make their delight.`"
Being flattered by some with divine honour, he asked them if they could not make gods too?
If they could why did they not begin with themselves?--The same austere conduct
of life made him refuse to have his statue erected in the cities of Asia:
nor would he suffer his picture to be taken; and his reason is good: "`for,`" saith he,
"`the fairest portraiture of men is their own actions.`"--Whatsoever
was to be suddenly done in the government,
he was sure to set his hand first to the work, like a common person.
He would say, it did not become men to make provision to be rich but to be good.
Being asked the means to true happiness; he answered,
"`To do nothing that should make a man fear to die:`" another time, "`To speak well,
and do well.`"
Being called home by the ephori, or supreme magistrates,
the way of the Spartan constitution, he returned, saying,
"`It is not less the duty of a prince to obey laws than to command men.`"
He conferred places of trust and honour upon his enemies,
that he might constrain their hatred into love.
A lawyer asking him for a letter to make a person judge that was of his own friends;
"`My friends,`" says he,
"`have no need of recommendation to do justice.`"--A comedian of note,
wondering that Agesilaus said nothing to him, asked if he knew him; "`Yes,`" said he,
"`art not thou the buffoon Callipedes?`"
One calling the king of Persia the Great king, he answered,
"`He is not greater than I unless he hath more virtue than
I.`"--One of his friends catching him playing with his children,
he prevented him thus:
"`Say nothing till thou art a father too.`"--He had great care of the education of youth,
often saying, "`We must teach children what they should do when they are men.`"
The Egyptians despising him because he had but a small train and a mean equipage;
"`Oh,`" said he,
"`I will have them to know royalty consists not in vain pomp but in virtue.`"

XVIII.
// lint-disable invalid-characters "æ"
Agis, another king of Lacedæmon,
imprisoned for endeavouring to restore their declining discipline,
being asked whether he repented not of his design; answered, "`No; for,`" saith he,
"`good actions never need repentance.`"
His father and mother desiring of him to grant something he thought unjust, he answered,
"`I obeyed you when I was young; I must now obey the laws,
and do that which is reasonable.`"--As he was leading
to the place of execution one of his people wept,
to whom he said, "`Weep not for me;
for the authors of this unjust death are more in fault than I.`"

XIX.
Alcamenes, king of the same people,
being asked which was the way to get and preserve honour; answered,
"`To despise wealth.`"
Another wondering why he refused the presents of the Messenians, he answered,
"`I make conscience to keep the laws that forbid it.`"
To a miser, accusing him of being so reserved in his discourse, he said,
"`I had rather conform to reason than thy covetousness; or,
I had rather be covetous of my words than money.`"

XX. Alexandrides hearing an exile complain of his banishment, saith he,
"`Complain of the cause of it, to wit, his deserts,
for there is nothing hurtful but vice.`"
// lint-disable invalid-characters "æ"
Being asked why they were so long in making the process of criminals in Lacedæmon,
"`Because,`" saith he, "`when they are once dead they are past repentance.`"
This shows their belief of immortality and eternal blessedness;
and that even poor criminals, through repentance, may obtain it.

XXI.
Anaxilas would say that the greatest advantage kings had upon other
men was their power of excelling them in good deeds.

XXII.
Ariston hearing one admire this expression,
"`We ought to do good to our friends and evil to our enemies;`" answered, "`By no means;
we ought to do good to all; to keep our friends and to gain our enemies.`"
A doctrine the most difficult to flesh and blood in all
the precepts of Christ`'s sermon upon the mount:
nay, not allowed to be his doctrine, but both an eye for an eye,
defended against his express command, and oftentimes an eye put out,
an estate sequestered, and life taken away under a specious zeal for religion too;
as if sin could be christened, and impiety entitled to the doctrine of Christ: O,
will not such heathens rise up in judgment against
our worldly Christians in the great day of God!

XXIII.
// lint-disable invalid-characters "æ"
Archidamus also, king of Sparta, being asked who was master of Lacedæmonia;
"`The laws,`" saith he, "`and after them the magistrates.`"
One praising a musician in his presence, "`Ah!`" saith he,
"`but when wilt thou praise a good man?`"--Another saying,
that man is an excellent musician: "`That is all one,`" saith he,
"`as if thou wouldst say,
there is a good cook:`" counting both trades of voluptuousness.--Another
promising him some excellent wine;
"`I care not,`" saith he,
"`for it will only put my mouth out of taste to my ordinary liquor;`"
which it seems was water.--Two men chose him an arbitrator;
to accept it, he made them promise to do what he would have them: "`Then,`" said he,
"`stir not from this place till you have agreed the
matter between yourselves,`" which was done.--Dionysius,
king of Sicily, sending his daughters rich apparel, he forbad them to wear it, saying,
"`You will seem to me but the more homely.`"
This great man certainly was not of the mind to breed up his children at the exchanges,
dancing-schools, and play-houses.

XXIV.
Cleomenes, king of the same people, would say, "`That kings ought to be pleasant;
but not to cheapness and contempt.`"
He was so just a man in power, that he drove away Demaratus his fellow-king,
(for they always had two,) for offering to corrupt him in a cause before them,
"`Lest,`" saith he, "`he should attempt others less able to resist him,
and so ruin the state.`"

XXV.
Dersyllidas perceiving that Pyrrhus would force a prince upon his countrymen,
// lint-disable invalid-characters "æ"
the Lacedæmonians, whom they lately rejected, stoutly opposed him, saying,
"`If thou art God, we fear thee not, because we have done no evil;
and if thou art but a man we are men too.`"

XXVI.
Hippodamus seeing a young man ashamed, that was caught in bad company,
he reproved him sharply, saying, "`For time to come,
keep such company as thou needest not blush at.`"

XXVII.
Leonidas, brother to Cleomenes, being offered by Xerxes to be made an emperor of Greece,
answered, "`I had rather die for my own country,
than have an unjust command over other men`'s;`" adding, "`Xerxes deceived himself,
to think it a virtue to invade the right of other men.`"

XXVIII.
Lysander being asked by a person, what was the best frame of government;
"`That,`" says he, "`where every man hath according to his deserts.`"
Though one of the greatest captains that Sparta bred,
he had learned by his wisdom to bear personal affronts:
"`Say what thou wilt,`" says he to one that spoke abusively to him, "`empty thyself,
I shall bear it.`"
His daughters were contracted in marriage to some persons of quality, but he dying poor,
they refused to marry them;
upon which the ephori condemned each of them in a great sum of money,
because they preferred money before faith and engagement.

XXIX.
Pausanias, son of Cleombrotus, and colleague of Lysander, beholding,
among the Persian spoils they took, the costliness of their furniture, said,
"`It had been much better if they had been worth less, and their masters more.`"
// lint-disable invalid-characters "æ"
And after the victory of Platæa, having a dinner dressed according to the Persian manner,
and beholding the magnificence and furniture of the treat; "`What,`" saith he,
"`do these people mean, that live in such wealth and luxury,
to attack our meanness and poverty?`"

XXX.
Theopompus saith, "`The way to preserve a kingdom,
is to embrace the counsel of one`'s friends,
and not to suffer the meaner sort to be oppressed.`"
One making the glory of Sparta to consist in commanding well, he answered, "`No,
it is in knowing how to obey well.`"
He was of opinion, that great honours hurt a state; adding,
that time would abolish great, and augment moderate honours among men; meaning,
that men should have the reputation they deserve, without flattery and excess.

// lint-disable invalid-characters "æ"
A rhetorician, bragging himself of his art, was reproved by a Lacedæmonian;
"`Dost thou call that an art,`" saith he, "`which hath not truth for its object?`"
// lint-disable invalid-characters "æ"
Also a Lacedæmonian being presented with a harp after dinner, by a musical person,
"`I do not,`" saith he, "`know how to play the fool.`"
Another being asked, what he thought of a poet of the times, answered,
"`Good for nothing but to corrupt youth.`"
Nor was this only the wisdom and virtue of some particular persons,
which may be thought to have given light to the dark body of their courts;
but their government was wise and just, and the people generally obeyed it;
making virtue to be true honour, and that honour dearer to them than life.

XXXI.
// lint-disable invalid-characters "æ"
Lacedæmonian customs, according to Plutarch, were these:
they were very temperate in their eating and drinking,
their most delicate dish being a pottage made for the nourishment of ancient people.
They taught their children to write and read, to obey the magistrates, to endure labour,
and to be bold in danger:
the teachers of other sciences were not so much as
// lint-disable invalid-characters "æ"
admitted in Lacedæmonia.--They had but one garment,
and that new once a year.
They rarely used baths or oil,
the custom of those parts of the world.--They accustomed
their youth to travel by night without light,
to use them not to be afraid.--The old governed the young;
and those of them who obeyed not the aged,
were punished.--It was a shame not to bear reproof among the youth; and among the aged,
matter of punishment not to give it.
They made ordinary cheer, on purpose to keep out luxury; holding,
that mean fare kept the spirit free, and the body fit for action.
They permitted not their youth to travel, lest they should corrupt their manners;
and for the same reason they permitted not strangers to dwell amongst them,
that conformed not to their way of living.
In this they were so strict,
that such of their youth that were not educated in their customs,
enjoyed not the privileges of natives.
They would suffer neither comedies nor tragedies to be acted in their country.
They condemned a soldier but for painting his buckler of several colours:
and publicly punished a young man for having learned
but the way to a town given to luxury.
They also banished an orator for bragging,
that he could speak a whole day upon any subject: for they did not like much speaking,
much less for a bad cause.--They buried their dead without any ceremony or superstition;
for they only used a red cloth upon the body, broidered with olive leaves;
this burial had all degrees.
Mourning they forbad, and epitaphs too.--When they prayed to God,
they stretched forth their arms, which with them was a sign that they must do good works,
as well as make good prayers.
They asked of God but two things, patience in labour, and happiness in well-doing.

This account is mostly the same with Xenophon`'s: adding, that they ate moderately,
and in common: the aged mixed with the youth, to awe them,
and give them good example.--When they were fifteen years of age,
instead of leaving them to their own conduct, as in other places,
they had most care of their conversation,
that they might preserve them from the mischiefs that age is incident to.
And those that would not comply with these rules,
were not counted always honest people.--And in this, their government was excellent;
that they thought there was no greater punishment for a bad man,
than to be known and used as such, at all times, and in all places;
for they were not to come into the company of persons
of reputation.--They were to give place to all others;
to stand when they sat;
to be accountable to every honest man that met them of their conversation.--That
they must keep their poor kindred.--That they used not the same
freedoms that honest people might use:
by which means they kept virtue in credit,
and vice in contempt.--They used all things necessary for life,
without superfluity or want; despising riches, and sumptuous apparel, and living:
judging, that the best ornament of the body is health, and of the mind, virtue.
"`And since,`" saith Xenophon, "`it is virtue and temperance that render us commendable,
// lint-disable invalid-characters "æ"
and that it is only the Lacedæmonians that reverence them publicly,
and have made it the foundation of their state; their government, of right,
merits preference to any other in the world.
But that,`" saith he, "`which is strange, is, that all admire it, but none imitate it.`"
Nor is this account and judgment fantastical.

XXXII.
Lycurgus, their famous founder and lawgiver, instilled these principles,
and by his power with them, made them laws to rule them.
Let us hear what he did: Lycurgus,
willing to retire his citizens from a luxurious to a virtuous life,
and show them how much good conduct and honest industry
might meliorate the state of mankind,
applied himself to introduce a new model of government, persuading them to believe,
that though they were descended of noble and virtuous ancestors,
if they were not exercised in a course of virtue, they would,
like the dog in the kitchen, rather leap at the meat than run at the game.
In fine, they agreed to obey him.
The first thing then that he did to try his power with them, was,
to divide the land into equal portions,
so that the whole Laconic country seemed but the lots of brethren: this grieved the rich;
but the poor, which were the most, rejoiced.--He rendered wealth useless by community;
and forbad the use of gold and silver: he made money of iron,
too base and heavy to make a thief.
He retrenched their laws of building,
suffering no more ornament than could be made with a hatchet and a saw:
and their furniture was like their houses.
This course disbanded many trades: no merchant, no cook, no lawyer, no flatterer,
// lint-disable invalid-characters "æ"
no divine, no astrologer, was to be found in Lacedæmonia.
Injustice was banished, their society having cut up the root of it, which is avarice,
by introducing a community, and making gold and silver useless.
To prevent the luxury of tables, as well as of apparel,
he ordained public places of eating, where all should publicly be served;
those that refused to come thither, were reputed voluptuous and reproved,
if not corrected.
He forbad costly offerings in the temple, that they might offer often;
for that God regardeth the heart, not the offering.--These and some more,
were the laws he instituted; and whilst the Spartans kept them,
it is certain they were the first state of Greece; which lasted about five hundred years.
It is remarkable, that he would never suffer the laws to be written, to avoid barratry;
and that the judges might not be tied religiously to the letter of the law;
but left to the circumstances of fact; in which no inconvenience was observed to follow.

=== II. The Romans also yielded us instances to our point in hand, viz.

1+++.+++ Cato.--2. Scipio Africanus.--3. Augustus.--4. Tiberius.--5. Vespasian.--6.
Trajan.--7. Adrian.--8. Marcus Aurelius Antoninus.--9. Pertinax.--10. Pescennius.--11.
Alexander Severus.--12. Aurelainus.--13. Dioclesian.--14. Julian.--15. Theodosius.

I+++.+++ Cato, that sage Roman, seeing a luxurious man loaded with flesh,
"`Of what service,`" saith he, "`can that man be, either to himself,
or the commonwealth?`"
One day beholding the statues of several persons erecting,
that he thought little worthy of remembrance, that he might despise the pride of it,
"`I had rather,`" said he, "`they should ask, why they set not up a statue to Cato,
than why they do.`"--He was a man of severity of life,
both example and judge.--His competitors in the government, hoping to be preferred,
took the contrary humour, and mightily flattered the people:
this good man despised their arts, and with an unusual fervency cried out,
"`That the distempers of the commonwealth did not require flatterers to deceive them,
but physicians to cure them;`" which struck so great an awe upon the people,
that he was first chosen of them all.--The fine dames
of Rome became governors to their husbands;
he lamented the change, saying,
"`It is strange that those who command the world should
yet be subject to women.`"--He thought those judges,
that would not impartially punish malefactors,
greater criminals than the malefactors themselves: a good lesson for judges of the world.
He would say, That it was better to lose a gift than a correction; "`for,`" says he,
"`the one corrupts us,
but the other instructs us.--That we ought not to separate honour from virtue;
for then there would be few any more virtuous.`"
He would say, "`No man is fit to command another, that cannot command himself.
Great men should be temperate in their power, that they may keep it.
For men to be too long in offices in a government,
is to have too little regard to others, or the dignity of the state.
They that do nothing, will learn to do evil.
That those who have raised themselves by their vices,
should gain to themselves credit by virtue.`"
He repented him, that ever he passed away one day without doing good.
And that there is no witness any man ought to fear, but that of his own conscience.
Nor did his practice fall much short of his principles.

II. Scipio Africanus, though a great general, loaded with honours and triumphs,
preferred retirement to them all; being used to say, That he was never less alone,
than when he was alone: implying, that the most busy men in the world,
are the most destitute of themselves; and,
that external solitariness gives the best company within.
After he had taken Carthage, his soldiers brought him a most beautiful prisoner;
he answered, "`I am your general;`" refusing to debase himself, or dishonour her.

III.
Augustus eating at the table of one of his friends,
where a poor slave breaking a crystal vessel, fell upon his knees,
begging him that his master might not fling him to the lampreys;
as he had use to do for food, with such of them that offended him:
Augustus hating his friend`'s cruelty, broke all his friend`'s crystal vessels,
both reproving his luxury and his severity.
He never recommended any of his own children, but he always added, If they deserve it.
He reproved his daughter for her excess in apparel,
and both rebuked and imprisoned her for her immodest latitudes.
The people of Rome complaining that wine was dear, he sent them to the fountains,
telling them they were cheap.

IV. Tiberius would not suffer himself to be called Lord, nor yet His Sacred Majesty: For,
says he, they are divine titles, and belong not to man.
The commissioners of his treasury advising him to increase his taxes upon the people,
he answered, No, it was fit to shear, but not to flay the sheep.

V+++.+++ Vespasian was a great and an extraordinary man,
who maintained something of the Roman virtue in his time.
One day seeing a young man finely dressed, and richly perfumed,
he was displeased with him, saying, "`I had rather smell the poor man`'s garlic,
than thy perfume:`" and took his place and government from him.
A certain person being brought before him, that had conspired against him,
he reproved him, and said, "`That it was God who gave and took away empires.`"
Another time conferring favour upon his enemy, and being asked why he did so,
he answered, that he should remember the right way.

VI. Trajan would say, "`That it became an emperor to act towards his people,
as he would have his people act towards him.`"
The governor of Rome having delivered the sword into his hand, and created him emperor;
"`Here,`" saith he, "`take it again: if I reign well, use it for me: if ill,
use it against me.`"
An expression which shows great humility and goodness, making power subservient to virtue.

VII.
Adrian, also emperor, had several sayings worthy of notice: one was,
"`That a good prince did not think the estates of his subjects belonging to him.`"
He would say, "`That kings should not act the king:`" that is, should be just,
and mix sweetness with greatness, and be conversible with good men.
"`That the treasures of princes are like the spleen, that never swells,
but it makes other parts shrink:`" teaching princes thereby to spare their
subjects.--Meeting one that was his enemy before he was emperor,
he cried out to him, "`Now thou hast no more to fear:`" intimating, that,
having power to revenge himself, he would rather use it to do him good.

VIII.
Marcus Aurelius Antoninus, a good man,
(the Christians of his time felt it,) commended his
son for weeping at his tutor`'s death,
answering those that would have rendered it unsuitable to his condition,
"`Let him alone,`" says he, "`it is fit he should show himself a man,
before he be a prince.`"
He did nothing in the government without consulting his friends, and would say,
"`It is more just that one should follow the advice of many, than many the mind of one.`"
He was more philosopher than emperor: for his dominions were greater within than without.
And having commanded his own passions by a circumspect conformity to virtuous principles,
he was fit to rule those of other men.
Take some of his excellent sayings, as followeth:
"`Of my grandfather Verus I have learned to be gentle and meek,
and to refrain from all anger and passion.
From the fame and memory of him that begot me, shamefacedness, and manlike behaviour.
I observed his meekness, his constancy without wavering, in those things, which,
after a due examination and deliberation, he had determined.
How free from all vanity he carried himself in matters of honour and dignity!
His laboriousness and assiduity: his readiness to hear any man that had ought to say,
tending to any common good.
His moderate condescending to other men`'s occasions as an ordinary man.--Of my mother,
to be religious and bountiful, and to forbear not only to do, but to intend any evil.
To content myself with a spare diet,
and to fly all such excess as is incident to great wealth.--Of my grandfather,
both to frequent public schools and auditories,
and to get me good and able teachers at home; and that I ought not to think much,
if upon such occasions I were at excessive charge.
I gave over the study of rhetoric and poetry, and of elegant, neat language.
I did not use to walk about the house in my senator`'s robe, nor to do any such things.
I learned to write letters without any affectation and curiosity; and to be easy,
and ready to be reconciled, and well pleased again with them that had offended me,
as soon as any of them would be content to seek unto me again.
To observe carefully the several dispositions of my friends,
and not to be offended with idiots, nor unreasonably to set upon those,
that are carried away with the vulgar opinions,
with the theorems and tenets of philosophers.
To love truth and justice, and to be kind and loving to all them of my house and family,
I learned from my brother Severus:
and it was he that put me in the first conceit and desire of an equal commonwealth,
administered by justice and equality; and of a kingdom,
wherein should be regarded nothing more than the good and welfare,
or liberty of the subjects.
As for God, and such suggestions, helps, and inspirations, as might be expected,
nothing did hinder, but that I might have begun long before to live according to nature:
or that even now, that I was not yet partaker, and in present possession of that life,
I myself (in that I did not observe those inward motions and suggestions; yea,
and almost plain and apparent instructions and admonitions of God) was
the only cause of it.--I that understand the nature of that which is good,
that it is to be desired; and of that which is bad, that it is odious and shameful:
who know moreover, that this transgressor, whoever he be, is my kinsman,
not by the same blood and seed, but by participation of the same reason,
and of the same divine participle, or principle:
how can I either be hurt by any of these,
since it is not in their power to make me incur anything that is reproachful,
or be angry or ill affected towards him, who by nature is so near unto me?
For we are all born to be fellow-workers, as the feet, the hands, and the eyelids;
as the rows of upper and under teeth: for such therefore to be in opposition,
is against nature.`"--He saith, "`It is high time for thee to understand true nature,
both of the world, whereof thou art a part, and of that Lord and Governor of the world,
from whom, as a channel from the spring, thou thyself didst flow.
And that there is but a certain limit of time appointed unto thee,
which if thou shalt not make use of, to calm and allay the many distempers of thy soul,
it will pass away, and thou with it, and never after return.--Do, soul,
do abuse and contemn thyself yet awhile,
and the time for thee to repent thyself will be at an end.
Every man`'s happiness depends upon himself; but, behold! thy life is almost at an end,
whilst not regarding thyself as thou oughtest,
thou dost make thy happiness to consist in the souls and conceits of other men.
Thou must also take heed of another kind of wandering;
for they are idle in their actions who toil and labour in their life,
and have no certain scope to which to direct all their motions and desires.
As for life and death, honour and dishonour, labour and pleasure, riches and poverty,
all these things happen unto men indeed, both good and bad equally; but as things,
which of themselves are neither good nor bad,
because of themselves neither shameful nor praiseworthy.
Consider the nature of all worldly visible things; of those especially,
which either ensnare by pleasure, or for their irksomeness are dreadful;
or for their outward lustre and show, are in great esteem and request;
how vile and contemptible, how base and corruptible,
how destitute of all true life and being they are.
There is nothing more wretched than that soul,
which in a kind of circuit compasseth all things;
searching even the very depths of all the earth, and, by all signs and conjectures,
prying into the very thoughts of other men`'s souls; and yet of this is not sensible,
that it is sufficient for a man to apply himself wholly,
and confine all his thoughts and cares to the guidance
of that Spirit which is within him,
and truly and really serve him.
For even the least things ought not to be done without relation unto the end;
and the end of the reasonable creature is, to follow and obey him who is the reason,
as it were, and the law of this great city, and most ancient commonwealth.
Philosophy doth consist in this, for a man to preserve that spirit which is within him,
from all manner of contumelies and injuries, and above all pains and pleasures,
never to do anything either rashly, or feignedly, or hypocritically:
he that is such is surely indeed a very priest and minister of God, well acquainted,
and in good correspondence with him especially, that is seated and placed within himself;
to whom also he keeps and preserveth himself; neither spotted by pleasure,
nor daunted by pain; free from any manner of wrong or contumely.
Let thy God that is in thee, to rule over thee, find by thee,
that he hath to do with a man, an aged man, a sociable man, a Roman, a prince,
and that hath ordered his life, as one that expecteth, as it were,
nothing but the sound of the trumpet,
sounding a retreat to depart out of this life with all readiness.
Never esteem anything as profitable, which shall ever constrain thee,
either to break thy faith, or to lose thy modesty: to hate any man, to suspect, to curse,
to dissemble, to lust after anything that requireth the secret of walls or veils.
But he that preferreth, before all things, his rational part and spirit,
and the sacred mysteries of virtue which issue from it,
he shall never want either solitude or company; and, which is chiefest of all,
he shall live without either desire or fear.
If thou shalt intend that which is present,
following the rule of right and reason carefully, solidly, meekly;
and shalt not intermix any other business, but shalt study this,
to preserve thy spirit unpolluted and pure:
and as one that were even now ready to give up the ghost; shalt cleave unto him,
without either hope or fear of anything,
in all things that thou shalt either do or speak, contenting thyself with heroical truth,
thou shalt live happily: and from this there is no man that can hinder thee.
Without relation to God, thou shalt never perform aright anything human;
nor on the other side anything divine.
At what time soever thou wilt, it is in thy power to retire into thyself,
and to be at rest: for a man cannot retire any whither to be more at rest,
and freer from all business, than into his own soul.
Afford then thyself this retiring continually, and thereby refresh and renew thyself.
Death hangeth over thee, whilst yet thou livest, and whilst thou mayest be good.
How much time and leisure doth he gain,
who is not curious to know what his neighbour hath said, or hath done, or hath attempted,
but only what he doth himself, that it may be just and holy.
Neither must he use himself to cut off actions only,
but thoughts and imaginations also that are not necessary;
for so will unnecessary consequent actions the better be prevented and cut off.
He is poor that stands in need of another,
and hath not in himself all things needful for his life.
Consider well, whether magnanimity rather, and true liberty, and true simplicity,
and equanimity, and holiness, whether these be not most reasonable and natural.
Honour that which is chiefest and most powerful in the world,
and that is it which makes use of all things, and governs all things: so also in thyself,
honour that which is chiefest and most powerful, and is of one kind and nature with that;
for it is the very same, which being in thee, turneth all other things to its own use,
and by whom also thy life is governed.
What is it that thou dost stay for?
An extinction or a translation; for either of them, with a propitious and contented mind.
But till that time come, what will content thee?
What else, but to worship and praise God, and do good unto men?`"
As he lay dying, and his friends about him, he spake thus: "`Think more of death,
than of me, and that you and all men must die as well as I.`" Adding,
"`I recommend my son to you, and to God, if he be worthy.`"

IX. Pertinax, also emperor, being advised to save himself from the fury of the mutineers,
answered "`No: what have I done that I should do so?`"
Showing that innocence is bold, and should never give ground where it can show itself,
be heard, and have fair play.

X+++.+++ Pescennius seeing the corruption that reigned among officers of justice, advised,
"`That judges should have first salaries,
that they might do their duty without any other bribes or perquisites.`"
He said, "`He would not offend the living that he might be praised when he was dead.`"

XI. Alexander Severus having tasted both of a private life, and the state of an emperor,
had this censure; "`Emperors,`" says he,
"`are ill managers of the public revenue to feed so many unuseful
mouths;`" wherefore he retrenched his family from pompous to serviceable.
He would not employ persons of quality in his domestic service,
thinking it too mean for them and too costly for him: adding,
"`That personal service was the work of the lowest order of the people.`"
He would never suffer offices of justice to be sold; "`For,`" saith he,
"`it is not strange that men should sell what they buy;`" meaning justice.
He was impartial in correction: "`My friends,`" says he, "`are dear to me;
but the commonwealth is dearer.`"
Yet he would say, "`That sweetening power to the people made it lasting.
That we ought to gain our enemies as we keep our friends:`" that is, by kindness.
He said, "`That we ought to desire happiness and to bear afflictions;
that those which are desirable may be pleasant;
but the troubles we avoid may have most profit in the end.`"
He did not like pomp in religion: for it is not gold that recommends the sacrifice,
but the piety of him that offers it.
A house being in contest betwixt some Christians and keepers of taverns,
the one to perform religion, the other to sell drink therein, he decided the matter thus:
"`That it were much better that it were any way employed
to worship God than to make a tavern of it.`"
Behold! by this we may see the wisdom and virtue that shined among the heathens.

XII.
Aurelianus, the emperor, having threat ened a certain town that had rebelled against him,
That he would not leave a dog alive therein;
and finding the fear he raised brought them easily to their duty,
bid his soldiers go kill all their dogs, and pardon the people.

XIII.
Dioclesian would say, that there was nothing more difficult than to reign well:
and the reason he gave was,
that those who had the ears of princes do so continually
lay ambushes to surprise them to their interests,
that they can hardly make one right step.

XIV.
Julian, coming to the empire, drove from the palace, troops of eunuchs, cooks, barbers,
&c. His reason was this, That having no women he needed no eunuchs;
and loving simple plain meat, he needed no cooks: and he said,
One barber would serve a great many.
A good example for the luxuri ous Christians of our times.

XV. Theodosius the younger was so merciful in his nature,
that instead of putting people to death,
he wished it were in his power to call the dead to life again.

These were the sentiments of the ancient grandees of the world, to wit, emperors, kings,
princes, captains, statesmen,
etc. not unworthy of the thoughts of persons of the same figure and quality now in being:
and for that end they are here collected,
that such may with more ease and brevity behold the true statutes of the ancients,
not lost or lessened by the decays of time.

==== III.

I will now proceed to report the virtuous doctrines and sayings of men of more retirement;
such as philosophers and writers, both Greeks and Romans,
who in their respective times were masters in the civility, knowledge,
and virtue that were among the Gentiles,
being most of them many ages before the coming of Christ, viz.

1+++.+++ Thales.--2. Pythagoras.--3. Solon.--4. Chilon.--5. Periander.--6. Bias.--7. Cleobulus.--8.
Pittacus.--9. Hippias.--10. The Gymnosophistae.--11. The Bambycatii.--12. The Athenians.--13.
Anacharsis.--14. Anaxagoras.--15. Heraclitus.--16. Democritus.--17. Socrates.--18. Plato.--19.
Antisthenes.--20. Xenocrates.--21. Bion.--22. Demonax.--23. Diogenes.--24. Crates.--25.
Aristotle.--26. Mandanis.--27. Zeno.--28. Seneca.--29. Epictetus.

I+++.+++ Thales, an ancient Greek philosopher,
being asked by a person that had committed adultery if he might swear, answered,
"`By no means; for perjury is no less sinful than adultery;
and so thou wouldst commit two sins to cover one.`"
Being asked what was the best condition of a government, answered,
"`That the people be neither rich nor poor:`" for he placed external happiness in moderation.
He would say, "`That the hardest thing in the world was to know a man`'s self;
but the best to avoid those things which we reprove
in others;`" an excellent and close saying,
"`That we ought to choose well and then to hold fast.
That the felicity of the body consists in health, and that in temperance;
and the felicity of the soul in wisdom.`"
He thought "`That God was without beginning or end; that he was the searcher of hearts;
that he saw the thoughts as well as actions:
for being asked of one if he could sin and hide it from God, he answered, '`No:
how can I when he who thinks evil cannot?`'`"

II. Pythagoras, a famous and virtuous philosopher of Italy,
being asked when men might take the pleasure of their passions, answered,
"`When they have a mind to be worse.`"
He said the world was like a comedy, and the true philosophers the spectators.
He would say, "`That luxury led to debauchery, and debauchery to violence,
and that to bitter repentance:
that he who taketh too much care of his body makes the prison of his soul more insufferable:
that those who do reprove us are our best friends;
that men ought to preserve their bodies from diseases by temperance,
their souls from ignorance by meditation, their will from vice by self-denial,
and their country from civil war by justice: that it is better to be loved than feared;
that virtue makes bold: but,`" saith he,
"`there is nothing so fearful as an evil conscience.`"
He said, "`That men should believe in a Divinity, that he is, and that he overlooks them,
and neglecteth them not; there is no being nor place without God.`"
He told the senators of Croton, being two thousand, praying his advice,
"`That they received their country as a depositum, or trust from the people;
wherefore they should manage it accordingly, since they were to resign their account,
with their trust to their children;
that the way to do it was to be equal to all citizens,
and to excel them in nothing more than justice;
that every one of them should so govern his family that he might
refer himself to his own house as to a court of judicature,
taking great care to preserve natural affection;
that they be examples of temperance in their own families, and to the city;
that in courts of judicature none attest God by an oath,
but use themselves so to speak as they may be believed without an oath:
that the discourse of that philosopher is vain, by which no passion of a man is healed;
for as there is no benefit of medicine if it expel not diseases out of bodies,
so neither of philosophy if it expel not evil out of the soul.`"

Of God, an heavenly life and state, he saith thus, They mutually exhorted one another,
that they should not tear asunder "`God which is in them.`"
Their study and friendship by words and actions,
had reference to some divine temperament; and to union with God,
and to unity with the mind, and the Divine Soul.
That all which they determine to be done aims and
tends to the acknowledgment of the Deity.
This is the principle; and the whole life of man consists in this,
"`That he follow God;`" and this is the ground of philosophy.
He saith,

Hope all things; for to none belongs despair:

All things to God easy and perfect are.

The work of the Mind is life.
The work of God is immortality, eternal life.
The Mind in man is termed God, by participation:
the rational soul is directed by the Mind, it inclines the will to virtue,
and is termed the good Daemon, Genius, or Spirit.
If by phantasy and ill affections, it draws the will to vices, the evil Daemon:
whence Pythagoras desired of God, to keep us from evil,
and to shew every one the Daemon or good Spirit, he ought to use.
The rational man is more noble than other creatures, as more divine;
not content solely with one operation, as all other things drawn along by nature,
which always acts after the same manner, but endued with various gifts,
which he useth according to his free will; in respect of which liberty,

--Men are of heavenly race,

Taught by Diviner Nature what t`'embrace.

By Diviner Nature, is meant the intellectual soul; as to intellect,
man approaches nigh to God; as to inferior senses, he recedeth from God.
By chorus, the infinite joy of the blessed spirits, their immutable delight,
// lint-disable invalid-characters
styled by Homer, ἆσβεςος γέλως (inextinguishable laughter).
For what greater pleasure, than to behold the serene aspect of God,
and next him the ideas and forms of all things, more purely and trans parently,
than secondarily, in created beings.
The Pythagoreans had this distich, among those commonly called the Golden Verses:

Rid of this body, if the heavens free

You reach, henceforth immortal you shall be.

Or thus:

Who after death, arrived at th`' heavenly plain,

Are straight like Gods, and never die again.

III.
Solon, esteemed as Thales, one of the seven sages of Greece, a noble philosopher,
and a lawgiver to the Athenians,
was so humble that he refused to be prince of that people,
and voluntarily banished himself when Pisastratus usurped the government there;^
footnote:[Plutarch. Herod.]
resolving never to outlive the laws and freedom of his country.
He would say, that to make a government last the magistrates must obey the laws,
and the people the magistrates.
It was his judgment, that riches brought luxury, and luxury brought tyranny.
// lint-disable invalid-characters "œ"
Being asked by Crœsus, king of Lydia,
when seated on his throne richly clothed and magnificently attended,
if he had ever seen anything more glorious; he answered, cocks, peacocks, and pheasants;
by how much their beauty is natural.
These undervaluing expressions of wise Solon,
// lint-disable invalid-characters "œ"
meeting so pat upon the pride and luxury of Crœsus, they parted;
the one desirous of toys and vanities,
the other an example and instructor of true nobility and virtue,
that contemned the king`'s effeminacy.
// lint-disable invalid-characters "œ"
Another time Crœsus asked him who was the happiest man in the world;
// lint-disable invalid-characters "œ"
expecting he would have said Crœsus,^
footnote:[Plutarch. Laert.]
because the most famous for wealth in those parts: he answered, "`Tellus, who,
though poor, yet was an honest and good man, and contented with what he had: who,
after he had served the commonwealth faithfully,
and seen his children and grandchildren virtuously educated,
died for his country in a good old age, and was carried by his children to his grave.`"
// lint-disable invalid-characters "œ"
This much displeased Crœsus, but he dissembled it.
// lint-disable invalid-characters "œ"
Whilst Solon recommended the happiness of Tellus, Crœsus, moved,
demanded to whom he assigned the next place;
making no question but himself should be named, "`Cleobis,`" saith he, "`and Bito,
brethren that loved well, had a competency, were of great health and strength;
most tender and obedient to their mother, religious of life,
who after sacrificing in the temple fell asleep and waked no more.`"
// lint-disable invalid-characters "œ"
Hereat Crœsus growing angry, "`Strange!`" saith he,
"`doth our happiness seem so despicable that thou
wilt not rank us equal with private persons?`"
Solon answered, "`Dost thou inquire of us about human affairs?
Knowest thou not that Divine Providence is severe, and often full of alteration?
Do not we in process of time see many things we would not?
Aye, and suffer many things we would not?
Count man`'s life at seventy years, which makes^
footnote:[According to the Athenian account.]
twenty-six thousand two hundred and fifty and odd days,
there is scarcely one day like another: so that every one,
// lint-disable invalid-characters "œ"
O Crœsus! is attended with crosses.
Thou appearest to me very rich, and king over many people;
but the question thou askest I cannot resolve till I hear thou hast ended thy days happily:
for he that hath much wealth is not happier than he that gets his bread from day to day,
unless Providence continue those good things, and that he dieth well.
// lint-disable invalid-characters "œ"
Solon, after his discourse, not flattering Crœsus, was dismissed,
and accounted unwise that he neglected the present good out of regard to the future.
// lint-disable invalid-characters "œ"
Æsop, that wrote the fables, being then at Sardis, sent for thither by Crœsus,
and much in favour with him, was grieved to see Solon so unthankfully dismissed,
and said to him, "`Solon,
we must either tell kings nothing at all or what may please them:`" "`No,`" saith Solon,
"`either nothing at all, or what is best for them.`"
// lint-disable invalid-characters "œ"
However it was not long ere Crœsus was of another mind;
for being taken prisoner by Cyrus, the founder of the Persian monarchy,
and by his command fettered and put on a pile of wood to be burned,
// lint-disable invalid-characters "œ"
Crœsus sighed deeply,^
footnote:[Herodot. Halicar.]
and cried, "`O Solon! Solon!`"
Cyrus bid the interpreter ask on whom he called.
He was silent; at last pressing him, answered, "`Upon him who I desire above all wealth,
would have spoken with all tyrants.`"
This not understood, upon further importunity he told them, "`Solon, an Athenian,
who long since,`" says he, "`came to me, and seeing my wealth, despised it; besides,
what he told me is come to pass; nor did his counsel belong to me alone,
but to all mankind, especially those that think themselves happy.`"
// lint-disable invalid-characters "œ"
Whilst Crœsus said thus,
the fire began to kindle and the outparts to be seized by the flame: Cyrus,
// lint-disable invalid-characters "œ"
informed of the interpreters what Crœsus said, began to be troubled;
and knowing himself to be a man, and that to use another,
not inferior to himself in wealth, so severely, might one day be retaliated,
instantly commanded the fire to be quenched,
// lint-disable invalid-characters "œ"
and Crœsus and his friends to be brought off: whom ever after, as long as he lived,
Cyrus had in great esteem.
Thus Solon gained due praise,
that of two kings his advice saved one and instructed the other.
And as it was in Solon`'s time that tragical plays were first invented,
so he was most severe against them;
foreseeing the inconveniencies that followed upon the people`'s
being affected with the novelty of pleasure.
It is reported of him that he went himself to the play,
and after it was ended he went to Thespis, the great actor,
and asked him if he were not ashamed to tell so many
lies in the face of so great an auditory.
Thespis answered, as it is now usual,
"`There is no harm nor shame to act such things in jest.`"
Solon, striking his staff hard upon the ground, replied,
"`But in a short time we who approve of this kind of jest
shall use it in earnest in our common affairs and contracts.`"
In fine, he absolutely forbade him to teach or act plays,
conceiving them deceitful and unprofitable;
diverting youth and tradesmen from more necessary and virtuous employments.
He defined them happy who are competently furnished with their outward callings,^
footnote:[Stob. Sent. 3.]
that live temperately and honestly:
he would say that cities are the common sewer of wickedness.
He affirmed that to be the best family which got not unjustly, kept not unfaithfully,
spent not with repentance.
"`Observe,`" saith he, "`honesty in thy conversation more strictly than an oath.
Seal words with silence; silence with opportunity.
Never lie, but speak the truth.
Fly pleasure, for it brings sorrow.
Advise not the people what is most pleasant, but what is best.
Make not friends in haste, nor hastily part with them.
Learn to obey, and thou wilt know how to command.
Be arrogant to none; be mild to those about thee.
Converse not with wicked persons.
Meditate on serious things.
Reverence thy parents.
Cherish thy friend.
Conform to reason, and in all things take counsel of God.`"
In fine, his two short sentences were these:^
footnote:[Clem. Alex. Strom. 1.]
"`Of nothing too much;`" and "`Know thyself.`"

IV. Chilon, another of the wise men of Greece, would say,
that it was the perfection of a man, to foresee and prevent mischiefs;
that herein good people differ from bad ones, their hopes were firm and assured;
that God was the great touchstone, or rule of mankind;
that men`'s tongues ought not to outrun their judgment:
that we ought not to flatter great men, lest we exalt them above their merit and station;
nor to speak hardly of the helpless.
They that would govern a state well, must govern their families well.
He would say, that a man ought so to behave himself,
that he fall neither into hatred nor disgrace.
That that commonwealth is happiest where the people mind the law more than the lawyers.
Men should not forget the favours they receive, nor remember those they do.
Three things, he said, were difficult, yet necessary to be observed: to keep secrets,
forgive injuries, and use time well.
"`Speak not ill,`" says he, "`of thy neighbour.
Go slowly to the feast of thy friends, but swiftly to their troubles.
Speak well of the dead.
Shun busybodies.
Prefer loss before covetous gain.
Despise not the miserable.
If powerful, behave thyself mildly, that thou mayst be loved rather than feared.
Order thy house well: bridle thy anger: grasp not at much: make not haste,
neither dote upon anything below.
A prince,`" saith he, "`must not take up his time about transitory and mortal things;
eternal and immortal are fittest for him.`"
To conclude: he was so just in all his actions, that Laertius tells us,
he professed in his old age,
that he had never done anything contrary to the conscience of an upright man; only,
that of one thing he was doubtful, having given sentence against his friend,
according to law, he advised his friend to appeal from him his judge,
so to preserve both his friend and the law.
Thus true and tender was conscience in heathen Chilon.

V+++.+++ Periander, prince and philosopher too, would say, that pleasures are mortal,
but virtues immortal.^
footnote:[Baart. Suid. Protag. Stob. xxviii.]
"`In success be moderate, in disappointments, patient and prudent.
Be alike to thy friends, in prosperity, and in adversity.
Peace is good; rashness dangerous; gain sordid.
Betray not secrets: punish the guilty: restrain men from sin.
They that would rule safely, must be guarded by love, not arms.
To conclude,`" saith he, "`live worthy of praise, so wilt thou die blessed.`"

VI. Bias, one of the seven wise men, being in a storm with wicked men,
who cried mightily to God; "`Hold your tongues,`"^
footnote:[Laert. Stob.]
saith he,
"`it were better He knew not you were here:`" a saying that hath great doctrine in it;
the devotion of the wicked doth them no good: it answers to that passage in Scripture,
"`The prayers of the wicked are an abomination to the Lord.`"^
footnote:[Prov. 15:8.]
An ungodly man asking him what godliness was, he was silent: but the other murmuring,
saith he, "`What is that to thee, that is not thy concern?`"
He was so tender in his nature, that he seldom judged a criminal to death, but he wept;
adding, "`One part goeth to God, and the other part I must give the law.`"
"`That man is unhappy,`" saith he, "`that cannot bear affliction.
It is a disease of the mind, to desire that which cannot, or is not fit to be had.
It is an ill thing, not to be mindful of other men`'s miseries.`"
To one that asked what is hard, he answered,
"`To bear cheerfully a change for the worse.`"
"`Those,`" says he, "`who busy themselves in vain knowledge,
resemble owls that see by night, and are blind by day;
for they are sharp-sighted in vanity,
but dark at the approach of true light and knowledge.`"
He adds, "`Undertake deliberately; but then go through.
Speak not hastily, lest thou sin.
Be neither silly nor subtle.
Hear much; speak little and seasonably.
Make profession of God everywhere; and impute the good thou dost, not to thyself,
but to the power of God.`"
His country being invaded, and the people flying with the best of their goods, asked,
why he carried none of his; "`I,`" saith he,
"`carry my goods within me.`"--Valerius Maximus adds,
"`in his breast;`" not to be seen by the eye, but to be prized by the soul;
not to be demolished by mortal hands; present with them that stay,
and not forsaking those that fly.

VII.
Cleobulus, prince and philosopher of Lyndus:^
footnote:[Laert. Plut. Sympos. Sap. Sep. Stob. Ser.]
he would say,
"`That it was man`'s duty to be always employed upon something that was good.`"
Again, "`Be never vain nor ungrateful.
Bestow your daughters, virgins in years, but matrons in discretion.
Do good to thy friend, to keep him; to thy enemy, to gain him.
When any man goeth forth, let him consider what he hath to do; when he returneth,
examine what he hath done.
Know, that to reverence thy father is thy duty.
Hear willingly, but trust not hastily.
Obtain by persuasion, not by violence.
Being rich, be not exalted: poor, be not dejected.
Forego enmity.
Instruct thy children.
Pray to God, and persevere in godliness.`"

VIII.
Pittacus being asked what was best, he answered, "`to do the present thing well.`"^
footnote:[Plutarch. Stob. xxviii.]
He would say, what thou dost take ill in thy neighbour, do not thyself.
Reproach not the unhappy; for the hand of God is upon them.
Be true to thy trust.
Bear with thy neighbour: love thy neighbour.
Reproach not thy friend, though he recede from thee a little.
He would say that commonwealth is best ordered where the wicked have no command,
and that family, which hath neither ornament nor necessity.
To conclude: he advised to acquire honesty; love discipline; observe temperance;
gain prudence; mind diligence; and keep truth, faith, and piety.
He had a brother, who, dying without issue, left him his estate;
// lint-disable invalid-characters "œ"
so that when Crœsus offered him wealth he answered,
"`I have more by half than I desire.`"
He also affirmed that family the best who got not unjustly, kept not unfaithfully,
spent not with repentance; and that happiness consists in a virtuous and honest life:
in being content with a competency of outward things, and in using them temperately.
And to conclude, he earnestly enjoined all to flee corporeal pleasure; "`for,`" says he,
"`it certainly brings sorrow: but observe an honest life more strictly than an oath:
meditate on serious things.`"

IX. Hippias, a philosopher: it is recorded of him^
footnote:[Cic. lib. de Orat.]
that he would have every one provide his own necessaries; and,
that he might do what he taught, he was his own tradesman.
He was singular in all such arts and employments,
insomuch as he made the very buskins he wore.
A better life than Alexander`'s.

X+++.+++ The Gymnosophistae were a sect of philosophers in Egypt,
that so despised gaudy apparel, and the rest of the world`'s intemperance,
that they went almost naked; living poorly, and with great meanness:
by which they were enabled against all cold, and overcame that lust by innocence,
which people, that are called Christians, though covered, are overcome withal.^
footnote:[Plin. 7; 2 Cic. Tusc. Quest. 5.]

XI. The Bambycatii were a certain great people that inhabited about the river Tigris,
in Asia, who, observing the great influence gold, silver,
and precious jewels had upon their minds,
agreed to bury all in the earth to prevent the corruption
of their manners.--They used inferior metals,
and lived with very ordinary accommodation;
wearing mostly but one very grave and plain robe to cover nakedness.
It were well if Christians would mortify their insatiable
appetites after wealth and vanity any way,
for heathens judge their excess.^
footnote:[Plin.]

XII.
// lint-disable invalid-characters "æ"
The Athenians had two distinct numbers of men, called the Gynæcosmi and Gynæconomi.^
footnote:[Vid. Suid.]
These were appointed by the magistrates to overlook the actions of the people:
the first were to see that they apparelled and behaved themselves gravely;
especially that women were of modest behaviour;
and the other were to be present at their treats and festivals,
to see that there was no excess, nor disorderly carriage;
and in case any were found criminal, they had full power to punish them.
When, alas! when shall this care and wisdom be seen amongst the Christians of these times,
that so intemperance might be prevented?
But it is too evident they love the power and the profits,
but despise the virtue of government,
making it an end instead of a means to that happy end,
viz. the well ordering the manners and conversation of the people,
and equally distributing rewards and punishments.

XIII.
Anacharsis, a Scythian, was a great philosopher;^
footnote:[Cic. Tusc. Quest. 5; Clem. Alex. Strom.]
// lint-disable invalid-characters "œ"
Crœsus offered him large sums of money, but he refused them.
Hanno did the like, to whom he answered, "`My apparel is a Scythian rug; my shoes,
the hardness of my feet; my bed, the earth; my sauce, hunger:
you may come to me as one that is contented; but those gifts which you so much esteem,
bestow on your citizens.`"

XIV.
Anaxagoras, a nobleman, but true philosopher,^
footnote:[Plut. contra Usur. Lysand. Cic. Tusc. Quest. 5.]
left his great patrimony to seek out wisdom;
and being reproved by his friends for the little care he had of his estate, answered,
"`It is enough that you care for it.`"
One asked him why he had no more love for his country than to leave it;
"`Wrong me not,`" saith he,
"`my greatest care is my country,`" pointing his finger towards heaven.
Returning home, and taking a view of his great possessions,
"`If I had not disregarded them,`" saith he, "`I had perished.`"
He was a great clearer and improver of the doctrine of One Eternal God,
denying divinity to sun, moon, and stars, saying, "`God was infinite,
not confined to place; the eternal wisdom and efficient cause of all things;
the divine mind and understanding; who, when matter was confused,
came and reduced it to order, which is the world we see.`"
He suffered much from some magistrates for his opinion; yet dying, was admired by them.
His epitaph in English thus:

Here lies, who through the truest paths did pass

To th`' world celestial Anaxagoras.

XV. Heraclitus was invited by king Darius, for his great virtue and learning,
to this effect: "`Come as soon as thou canst to my presence and royal palace;
for the Greeks, for the most part, are not obsequious to wise men,
but despise the good things which they deliver.
With me thou shalt have the first place, and daily honour and titles:
thy way of living shall be as noble as thy instructions.`"
But Heraclitus, refusing his offer, returned this answer:
"`Heraclitus to Darius the king, health.
Most men refrain from justice and truth to pursue insatiableness and vain glory,
by reason of their folly: but I, having forgotten all evil,
and shunning the society of inbred envy and pride,
will never come to the kingdom of Persia,
being contented with a little according to my own mind.`"
He also slighted the Athenians.
He had great and clear apprehensions of the nature and power of God,
maintaining his divinity against the idolatry in fashion.
This definition he gives of God: "`He is not made with hands.
The whole world, adorned with his creatures, is his mansion.
Where is God?
Shut up in temples?
Impious men! who place their God in the dark.
It is a reproach to a man to tell him he is a stone,
yet the god you profess is born of a rock: you ignorant people! you know not God:
his works bear witness of him.`"
Of himself he saith, "`O ye men, will ye not learn why I never laugh?
It is not that I hate men, but their wickedness.
If you would not have me weep, live in peace: you carry swords in your tongues;
you plunder wealth, poison friends, betray the trust the people repose in you:
shall I laugh when I see men do these things?
Their garments, beards, and heads adorned with unnecessary care;
a mother deserted by a wicked son; or young men consuming their patrimony;
others filling their bellies at feasts more with poison than with dainties.
Virtue would strike me blind if I should laugh at your wars.
By music, pipes, and stripes you are excited to things contrary to all harmony.
Iron, a metal more proper for ploughs and tillage, is fitted for slaughter and death;
men raising armies of men, covet to kill one another,
and punish them that quit the field for not staying to murder men.
They honour as valiants such as are drunk with blood; but lions, horses, eagles,
and other creatures, use not swords, bucklers, and instruments of war:
their limbs are their weapons,--some their horns, some their bills, some their wings;
to one is given swiftness, to another bigness, to a third swimming.
No irrational creature useth a sword, but keeps itself within the laws of its creation,
except man, that doth not so, which brings the heavier blame,
because he hath the greatest understanding.--You must leave your wars,
and your wickedness, which you ratify by a law, if you would have me leave my severity.
I have overcome pleasure, I have overcome riches, I have overcome ambition,
I have mastered flattery: fear hath nothing to object against me,
drunkenness hath nothing to charge upon me, anger is afraid of me:
I have won the garland in fighting against these enemies.`"--This, and much more,
did he write in his epistles to Hermodorus,
of his complaints against the great degeneracy of the Ephesians.
And in an epistle to Aphidamus he writes, "`I am fallen sick, Aphidamus, of a dropsy;
whatsoever is of us, if it get the dominion, it becomes a disease.
Excess of heat is a fever; excess of cold, a palsy; excess of wind a cholic:
my disease cometh from excess of moisture.
The soul is something divine, which keeps all these in a due proportion.
I know the nature of the world; I know that of man; I know diseases; I know health:
but if my body be overpressed, it must descend to the place ordained; however,
my soul shall not descend; but being a thing immortal, I shall ascend on high,
where a heavenly mansion shall receive me.`"

A most weighty and pathetical discourse:
they that know anything of God may savour something divine in it.
O that the degenerate Christians of these times would but take a view of the virtue,
temperance, zeal, piety, and faith of this heathen,
who notwithstanding that he lived five hundred years
before the coming of Christ in the flesh,
had these excellent sentences!
Yet again, he taught that God punisheth not by taking away riches;
he rather alloweth them to the wicked to discover them; for poverty may be a veil.
Speaking of God, "`How can that light which never sets be ever hidden or obscured?`"
"`Justice,`" saith he,
"`shall seize one day upon defrauders and witnesses of false things.`"
Unless a man hope to the end for that which is to be hoped for,
he shall not find that which is unsearchable; which Clemens, an ancient father,
applied to Isaiah vi.
"`Unless you believe, you shall not understand.`"
Heraclitus lived solitarily in the mountains; had a sight of his end;
and as he was prepared for it, so he rejoiced in it.
These certainly were the men who, having not a law, without them,
became a law unto themselves, showing forth the work of the law written in their hearts;^
footnote:[Rom. 2:14.]
and who for that reason shall judge the circumcision,
and receive the reward of "`Well done,`" by him who is Judge of quick and dead.

XVI.
Democritus would say,
that he had lived to an extraordinary age by keeping himself from luxury and excess.
That a little estate went a great way with men that were neither covetous nor prodigal.
That luxury furnished great tables with variety: and temperance furnished little ones.
That riches do not consist in the possession, but right use of wealth.
He was a man of great retirement, avoiding public honours and employments;
bewailed by the people of Abdera as mad,
whilst indeed he only smiled at the madness of the world.

XVII.
Socrates, the most religious and learned philosopher of his time,
and of whom it is reported Apollo gave this character,
that he was the wisest man on earth,^
footnote:[Plat. Apolog. Diog. Laert. Helvic+++.+++; Cic. Tusc. Quest.
1; Xenoph. Brut. Cic. Orat. Liban.]
was a man of a severe life, and instructed people gratis in just, grave,
and virtuous manners; for which, being envied by Aristophanes, the vain,
comical wit of that age, as one spoiling the trade of plays,
and exercising the generality of the people with more noble and virtuous things,^
footnote:[Apol. Varro. Hist. Schol. Artist.]
was represented by him in a play, in which he rendered Socrates so ridiculous,
that the vulgar would rather part with Socrates in earnest than Socrates in jest;
which made way for their impeaching him as an enemy to their gods;
for which they put him to death.
But in a short space his eighty judges and the whole people so deeply resented the loss,
that they slew many of his accusers: some hanged themselves;
none would trade with them nor answer them a question.
They erected several statues to his praise; they forbad his name to be mentioned,
that they might forget their injustice:
they called home his banished friends and scholars;
and by the most wise and learned men of that age it is observed,
that famous city Athens was punished with the most
dreadful plagues that ever raged amongst them,
and all Greece with it never prospered in any considerable undertaking,
but from that time always decayed.
Amongst many of his sober and religious maxims upon
which he was accustomed to discourse with his disciples,
these are some:

He taught everywhere that an upright man and a happy man are all one.
They that do good are employed; they that spend their time in recreations are idle.^
footnote:[Clem. Alex. Strom. ii. 417; Xen. Mem. iii. pp. 720,
778, 779, 780. Stob. Ech. Strom. i. 11.]
To do good is the best course of life; he only is idle who might be better employed.
A horse is not known by his furniture, but qualities;
so men are to be esteemed for virtue, not wealth.
Being asked who lived without trouble, he answered,
"`Those who are conscious to themselves of no evil thing.`"^
footnote:[Stob. iv. 6; Ibid. ii. 18; Xenoph. Mem. 3; Seneca Epist. i. 104; Stob.
// lint-disable invalid-characters "Æ"
28; Ibid. 32; Xen. Mem. 1; Ælian. 9; Stob. 37.]
To one who demanded what was nobility, he answered,
"`A good temper and disposition of soul and body.
They who know what they ought to do, and do it not, are not wise and temperate,
but fools and stupid.`"
To one that complained he had not been benefited by his travels,
"`Not without reason,`" says Socrates, "`thou didst travel with thyself:`" intimating,
he knew not the eternal mind of God to direct and inform him.
Being demanded what wisdom was, said, "`A virtuous composure of the soul.`"
And being asked who were wise, answered, "`Those that sin not.`"
Seeing a young man rich, but ignorant of heavenly things, and pursuing earthly pleasures;
"`Behold,`" says he, "`a golden slave.^
// lint-disable invalid-characters "Æ"
footnote:[Stob. 37; Ibid. 87; Xen. Mem. 34; Ælian. Ver. Hist. 9.]
Soft ways of living beget neither a good constitution of body nor mind.
Fine and rich clothes are only for comedians.`"
Being demanded from what things men and women ought to refrain, he answered, "`Pleasure.`"
Being asked what continence and temperance were, said,
"`Government of corporeal desires and pleasures.
The wicked live to eat, etc. but the good eat to live.
Temperate persons become the most excellent:
eat that which neither hurts the body nor mind, and which is easy to be gotten.`"
One saying it was a great matter to abstain from what one desires; "`But,`" says he,
"`it is better not to desire at all.`"
This is deep religion, even very hard to professed Christians.
"`It is the property of God to need nothing;^
// lint-disable invalid-characters "æ"
footnote:[Stob. 37; Xen. Mem. iv. 802.; Plat. Phæd.]
and they that need and are contented with least come nearest to God.
The only and best way to worship God is to mind and obey whatsoever he commands.
That the souls of men and women partake of the divine nature:
that God is seen of the virtuous mind:
that by waiting upon him they are united unto him
in an accessible place of purity and happiness;
which God he asserted always to be near him.`"

Many more are the excellent sayings of this great man,
who was not less famous for his sayings than his example, with the greatest nations;
yet died he a sacrifice to the sottish fury of the vain world.
The history of his life reports that his father was told^
footnote:[Xen. Mem. i. p. 710.]
he should have the guide of his life within him,
which should be more to him than five hundred masters; which proved true.
Instructing his scholars herein,
charging them not to neglect these divine affairs which chiefly concern man,
to mind or inquire after such things as are without in the visible world.
He taught the use of outward things^
footnote:[Xen. Mem. 4.; Plat. de Legib.]
only as they were necessary to life and commerce;
forbidding superfluities and curiosities.
He was martyred for his doctrine, after having lived seventy years, the most admired,
followed, and visited of all men in his time by kings and commonwealths;
and than whom antiquity mentions none with more reverence and honour.
Well were it for poor England if her conceited Christians were true Socrateses;
whose strict, just,
and self-denying life doth not bespeak him more famous than it
will Christians infamous at the revelation of the righteous judgment,
where heathens`' virtue shall aggravate Christians`' intemperance; and their humility,
the others`' excessive pride: and justly too, since a greater than Socrates is come,
whose name they profess, but they will not obey his law.

XVIII.
Plato, that famous philosopher and scholar to Socrates,^
footnote:[Plato de Rep.]
was so grave and devoted to divine things, nay, so discreetly politic,
that in his commonwealth he would not so much as harbour poetical fancies,
much less upon stages, as being too effeminate,
and apt to withdraw the minds of youth from more noble, more manly,
as well as more heavenly exercises.
Plato seeing a young man play at dice, reproved him sharply; the other answered, "`What,
for so small a matter?`"
"`Custom,`" saith Plato, "`is no small thing:^
footnote:[Diog. Laert. in vit.]
let idle hours be spent more usefully.
Let youth,`" said he, "`take delight in good things; for pleasures are the baits of evil.
Observe, the momentary sweetness of a delicious life is followed with eternal sorrow;
the short pain of the contrary, with eternal pleasure.`"
Being commanded to put on a purple garment by the king of Sicily, he refused,
saying he was a man, and scorned such effeminacies.
Inviting Timothy, the Athenian general to supper, he treated him with herbs, water,
and such spare diet as he was accustomed to eat.
Timothy`'s friends next day, laughing, asked how he was entertained, he answered,^
// lint-disable invalid-characters "Æ"
footnote:[Xen. Crat. Stob. Ælian.]
"`Never better in life;
for he slept all night after his supper:`" thereby commending his temperance.
He addicted himself to religious contemplations:
and is said to have lived a virtuous and single life, always eyeing and obeying the mind,
which he sometimes called, "`God, the Father of all things;`" affirming,
"`Who lived so should become like him, and so be related to,
and joined with the Divinity itself.`"
This same Plato, upon his dying bed, sent for his friends about him,
and told them the whole world was out of the way, in that they understood not,
nor regarded the mind, assuring them,
those men died most comfortably that lived most conformably to right reason,
and sought and adored the First Cause, meaning God.

XIX.
Antisthenes, an Athenian philosopher,^
// lint-disable invalid-characters "Æ"
footnote:[Laert. vit. Socr. Ælian.]
had taught in the study of eloquence several years;
but upon his hearing Socrates treat of the seriousness of religion, of the divine life,
eternal rewards, etc. bid all his scholars seek them a new master,
for he had found one for himself: wherefore selling his estate,
he distributed it to the poor,
and betook himself wholly to the consideration of heavenly things;
going cheerfully six miles every day to hear Socrates.--But where are
the like preachers and converts amongst the people called Christians?
Observe the daily pains of Socrates;
surely he did not study a week to read a written sermon; we are assured of the contrary;
for it was frequent with him to preach to the people at any time of the day,
in the very streets, as occasion served, and his good genius moved him.
Neither was he a hireling, or covetous, for he did it gratis:
surely then he had not fat benefices, tithes, glebes, etc.
And let the self-denial and diligence of Antisthenes be considered,
who of a philosopher and master became a scholar, and that a daily one; surely,
it was then matter of reproach, as it is now; showing thereby both want of knowledge,
though called a philosopher,
and his great desire to obtain it of one that could teach him.
None of these used to go to plays, balls, treats, etc.
They found more serious employments for their minds,
and were examples of temperance to the world.--I will repeat some of his grave sentences,
as reported by Laertius, and others; namely, "`That those are only noble,
who are virtuous.^
footnote:[Laert.]
That virtue was self-sufficient to happiness: that it consisteth in actions,
not requiring many words, nor much learning, and is self-sufficient to wisdom:
for that all other things have reference thereunto.
That men should not govern by force, nor by laws, unless good, but by justice.`"^
footnote:[Stob.]
To a friend, complaining he had lost his notes,
"`Thou shouldst have written them upon thy mind,`" saith he, "`and not in a book.
Those who would never die,
must live justly and piously.`"--Being asked what learning was best, "`That,`" saith he,
"`which unlearneth evil.`"^
footnote:[Stob. 177.]
To one that praised a life full of pleasures and delicacies:^
footnote:[Diog. Laert.]
"`Let the sons of my enemies,`" saith he,
"`live delicately:`" counting it the greatest misery.
"`We ought,`" saith he, "`to aim at such pleasures as follow honest labour;
and not those which go before it.`"^
footnote:[Agel. lib. c. 5.]
When at any time he saw a woman richly dressed, he would, in a way of reproach,
bid her husband bring out his horse and arms: meaning,
if he were prepared to justify the injuries such wantonness used to produce,
he might the better allow those dangerous freedoms: "`Otherwise,`" saith he,
"`pluck off her rich and gaudy attire.`"
He is said to exclaim bitterly against pleasures; often saying,
"`I had rather be mad than addicted to pleasure,
and spend my days in decking and feeding my carcase.
Those,`" says he, "`who have once learned the way to temperance and virtue,
let them not offer to entangle themselves again with fruitless stories and vain learning,
nor be addicted to corporeal delicacies, which dull the mind,
and will divert and hinder them from the pursuit of those more noble and heavenly virtues.`"
Upon the death of his beloved master, Socrates,^
footnote:[Laert. vit. Mem.]
he instituted a sect called Cynics, out of whom came the great sect of Stoics;
both which had these common principles, which they daily,
with great and unwearied diligence, did maintain and instruct people in the knowledge of,
viz., "`No man is wise and happy but the good and virtuous man.^
footnote:[Laert. Plut. de Rep. Stoi. Cic. de aut. Deo, lib. ii.]
That not much learning nor study of many things was necessary.
That a wise man is never drunk nor mad: that he never sinneth;
that a wise man is void of passion: that he is sincere, religious, grave:
that he only is divine.
That such only are priests and prophets that have God in themselves.
And that his law is imprinted in their minds, and the minds of all men:^
footnote:[Lactant. de Ira Dei, cap. 10.]
that such an one only can pray who is innocent, meek, temperate, ingenuous, noble,
a good magistrate, father, son, master, servant, and worthy of praise.`"
On the contrary, "`that wicked men can be none of these:
that the same belongs to men and women.`"

Their diet was slender, their food only what would satisfy nature.^
footnote:[Plat. Pl. Ph. 16. Cic. Tul. Quest. 4. Diog. Laert. vit. Mem. Stob.]
Their garments exceeding mean.
Their habitations solitary and homely.
They affirmed, those who lived with fewest things and were contented,
most nearly approached God, who wants nothing.
They voluntarily despised riches, glory, and nobility,
as foolish shows and vain fictions,
that had no true and solid worth or happiness in them.
They made all things to be good and evil,
and flatly denied the idle stories of fortune and chance.

Certainly these were they who, having no external law, became a law unto themselves,
and did not abuse the knowledge they had of the invisible God,
but to their capacities instructed men in the knowledge of that righteous, serious,
solid,
and heavenly principle which leads to true and everlasting
happiness all those that embrace it.

XX. Xenocrates refused Alexander`'s present,^
footnote:[Laert. Val. Max. 4, 3, 2, 16. Cic. Pro. Fal. Val. Max. 7, 2.]
yet treated his ambassadors after his temperate and spare manner, saying,
"`You see I have no need of your master`'s bounty, that am so well pleased with this.`"
He would say,
"`that one ought not to carry one`'s eyes or one`'s
hands into another man`'s house:`" that is,
to be a busy-body.
That one ought to be most circumspect of one`'s actions before children,
lest by example one`'s faults should outlive one`'s self.
He said pride was the greatest obstruction to true knowledge.
His chastity and integrity were remarkable and reverenced in Athens: Phryne,
the famous Athenian courtezan, could not place a temptation upon him, nor Philip,
king of Macedon, a bribe, though the rest sent in the embassy were corrupted.
And being once brought for a witness, the judges rose up, and cried out,
"`Tender no oath to Xenocrates, for he will speak the truth.`"
A respect they did not allow to one another.
Holding his peace at some detracting discourse, they asked him why he spoke not:
"`Because,`" saith he, "`I have sometimes repented of speaking,
but never of holding my peace.`"

XXI.
Bion would say, that great men walk in slippery places:
that it is a great mischief not to bear affliction;
that ungodliness is an enemy to assurance.
He said to a covetous man, that he did not possess his wealth,
but his wealth possessed him; abstaining from using it,
as if it were another man`'s. In fine, that men ought to pursue a course of virtue,
without regard to the praise or reproach of men.

XXII.
Demonax seeing the great care that men had of their bodies, more than of their minds;
"`They deck the house,`" saith he, "`but slight the master.`"
He would say, that many are inquisitive after the make of the world,
but are little concerned about their own,
which were a science much more worthy of their pains.
To a city that would establish the gladiators, or prize-fighters, he said,
that they ought first to overthrow the altar of mercy;
intimating the cruelty of such practices.
One asking him why he turned philosopher; "`Because,`" saith he, "`I am a man.`"
He would say of the priests of Greece, if they could better instruct the people,
they could not give them too much; but if not, the people could not give them too little.
He lamented the unprofitableness of good laws, by being in bad men`'s hands.

XXIII.
Diogenes was angry with critics that were nice of words and not of their own actions;
with musicians, that tune their instruments but could not govern their passions;
with astrologers, that have their eyes in the sky, and look not at their own goings;
with orators, that study to speak well but not to do well; with covetous men,
that take care to get but never use their estates;
with those philosophers that despise greatness, and yet court great men;
and with those that sacrifice for health,
and yet surfeit themselves with eating their sacrifices.
One time, discoursing of the nature, pleasure, and reward of virtue,
and the people not regarding what he said, he fell a singing,
at which every one pressed to hear; whereupon he cried out,
in abhorrence of their stupidity, "`O God,
how much more is the world in love with folly than with wisdom!`"
Seeing a man sprinkling himself with water after having done some ill thing,
"`Unhappy man,`" saith he,
"`dost thou not know that the errors of life are not to be washed away with water?`"
To one who said, "`Life is an ill thing;`" he answered, "`Life is not an ill thing,
but an ill life is an ill thing.`"
He was very temperate, for his bed and his table he found everywhere.
One seeing him wash herbs, said, "`If thou hadst followed Dionysius, king of Sicily,
thou wouldst not have needed to have washed herbs;`" he answered,
"`If thou hadst washed herbs, thou needest not to have followed Dionysius.`"
He lighted a candle at noon, saying,
"`I look for a man;`" implying that the world was darkened by vice, and men effeminated.
To a luxurious person, that had wasted his means, supping upon olives; "`If,`" saith he,
"`thou hadst used to dine so, thou wouldst not have needed to sup so.`"
To a young man, dressing himself neatly; "`If this,`" saith he, "`be for the sake of men,
thou art unhappy; if for women, thou art unjust.`"
Another time, seeing an effeminate young man; "`Art thou not ashamed,`" saith he,
"`to use thyself worse than nature hath made thee?
She hath made thee a man, but thou wilt force thyself to be a woman.`"
To one that courted a bad woman; "`O wretch!`" said he,
"`what meanest thou to ask for that which is better lost than found?`"
To one that smelled of sweet unguents, "`Have a care,`" saith he,
"`that this perfume make not thy life stink.`"
He compared covetous men to such as have the dropsy; those are full of money,
yet desire more; these of water, yet thirst for more.
Being asked what beasts were the worst; "`In the field,`" saith he, "`bears and lions;
in the city, usurers and flatterers.`"
At a feast, one giving him a great cup of wine, he threw it away: for which being blamed,
"`If I had drunk it,`" saith he, "`not only the wine would have been lost, but I also.`"
One asking him how he might order himself best, he said,
"`By reproving those things in thyself which thou blamest in others.`"
Another demanding what was the hardest, he answered, "`To know ourselves;
to whom we are partial.`"
An astrologer discoursing to the people of the wandering stars; "`No,`" saith he,
"`it is not the stars, but these,`" pointing to the people that heard him.
Being asked what men are most noble; "`They,`" saith he, "`who contemn wealth, honour,
and pleasure, and endure the contraries, to wit, poverty, scorn, pain, and death.`"
To a wicked man, reproaching him for his poverty; "`I never knew,`" saith he,
"`a man punished for his poverty, but many for their wickedness.`"
To one bewailing himself that he should not die in his own country;
"`Be of comfort,`" saith he, "`for the way to heaven is alike in every place.`"
One day he went backwards; whereat the people laughing,
"`Are you not ashamed,`" saith he, "`to do that all your lifetime,
which you deride in me?`"

XXIV.
Crates, a Theban, famous for his self-denial and virtue,
descended from the house of Alexander, of great estate, at least two hundred talents,
which having mostly distributed amongst the poor citizens,
he became a constant professor of the Cynic philosophy.
He exceedingly inveighed against common women.
Seeing at Delphos a golden image, that Phryne, the courtezan,
had set up by the gains of her trade, he cried out,
"`This is a trophy of the Greeks`' intemperance.`"
Seeing a young man highly fed and fat: "`Unhappy youth,`" said he,
"`do not fortify thy prison.`"
To another, followed by a great many parasites; "`Young man,`" saith he,
"`I am sorry to see thee so much alone.`"
Walking one day upon the Exchange,
where he beheld people mighty busy after their divers callings;
"`These people,`" saith he, "`think themselves happy;
but I am happy that have nothing to do with them; for I place my happiness in poverty,
not in riches.
Oh! men do not know how much a wallet, a measure of lupins, with security, is worth.`"
Of his wife, Hipparchia, a woman of wealth and extraction,
but nobler for her love to true philosophy, and how they came together,
there will be occasion to make mention in its place.

XXV.
Aristotle, a scholar to Plato,^
footnote:[Stob. Strom. 45.]
and the oracle of philosophy to these very times,
though not so divinely contemplative as his master, nevertheless follows him in this,
"`That luxury should by good discipline be exiled human societies.`"^
footnote:[Stob. 161.]
Aristotle seeing a youth finely dressed, said, "`Art thou not ashamed,
when nature hath made thee a man, to make thyself a woman?`"^
footnote:[Ibid. 46.]
And to another, gazing on his fine cloak;
"`Why dost thou boast thyself of a sheep`'s fleece?`"
He said it was the duty of a good man to live so
under laws as he should do if there were none.

XXVI.
Mandanis, a great and famous philosopher of the Gymnosophists,
whom Alexander the Great required to come to the feast of Jupiter`'s son,
(meaning himself,) declaring, that if he came he should be rewarded, if not,
he should be put to death; the philosopher contemned his message as vain and sordid:
he first told them, that he denied him to be Jupiter`'s son; a mere fiction.
Next, that as for his gifts, he esteemed them nothing worth;
his own country could furnish him with necessaries; beyond which he coveted nothing.
And lastly, as for the death he threatened, he did not fear it; but of the two,
he wished it rather, "`In that,`" saith he,
"`I am sure it is a change to a more blessed and happy state.`"

XXVII.
Zeno, the great Stoic,^
footnote:[Stob. Laert.]
and author of that philosophy, had many things admirable in him; who not only said,
but practised.
He was a man of that integrity, and so reverenced for it by the Athenians,
that they deposited the keys of the city in his hands,
as the only person fit to be entrusted with their liberties; yet by birth a stranger,
being of Citium in Cyprus.
Antigonus, king of Macedonia, had a great respect for him, and desired his company,
as the following letter expresseth:

"`King Antigonus to Zeno the philosopher, health:
I think that I exceed thee in fortune and glory; but in learning and discipline,
and that perfect felicity which thou hast attained, I am exceeded by thee;
wherefore I thought it expedient to write to thee, that thou wilt come to me,
assuring myself thou wilt not deny it.
Use all means therefore to come to us, and know, thou art not to instruct me only,
but all the Macedonians; for he who teacheth the king of Macedonia,
and guideth him to virtue,
it is evident that he doth likewise instruct all his subjects in virtue;
for such as is the prince,
such for the most part are those who live under his government.`"

Zeno answered thus: "`To king Antigonus, Zeno wisheth health:
I much esteem thy earnest desire of learning, in that thou aimest at philosophy;
not popular, which perverteth manners, but that true discipline which conferreth profit;
avoiding that generally commended pleasure, which effeminates the souls of men.
It is manifest that thou art inclined to generous things,
not only by nature but by choice; with indifferent exercise and assistance,
thou mayest easily attain to virtue.
But I am very infirm of body, being fourscore years of age, and so not well able to come;
yet I will send thee some of my chief disciples, who in those things concerning the soul,
are nothing inferior to me; and whose instructions, if thou wilt follow them,
will conduct thee to perfect blessedness.`"

// lint-disable invalid-characters "æ"
Thus Zeno refused Antigonus, but sent Persæus, his countryman, and Philonides, a Theban.
He would say, that nothing was more unseemly than pride, especially in youth,
which was a time of learning.
He therefore recommended to young men modesty in three things; in their walking,
in their behaviour, and in their apparel: often repeating those verses of Euripides,
in honour of Capaneus:

He was not puff`'d up with his store,

Nor thought himself above the poor.

Seeing a man very finely dressed, stepping lightly over a kennel: "`That man,`" saith he,
"`doth not care for the dirt, because he could not see his face in it.`"
He also taught, that people should not affect delicacy of diet, no, not in their sickness.
To one that smelt with unguents; "`Who is it,`" saith he, "`that smells so effeminately?`"
Seeing a friend of his taken too much up with the business of his land;
"`Unless thou lose thy land,`" saith he, "`thy land will lose thee.`"
Being demanded, whether a man that doth wrong may conceal it from God: "`No,`" saith he,
"`nor yet he who thinks it;`" which testifies to the omnipresence of God.
Being asked, who was his best friend, he answered:
"`My other self;`" intimating the divine part that was in him.
He would say, the end of man was not to live, eat, and drink;
but to use his life so as to obtain a happy life hereafter.
He was so humble that he conversed with mean and ragged persons: whence Timon thus:

And for companions, gets of servants store,

Of all men the most empty and most poor.

He was patient, and frugal in his household expenses; Laertius saith,
he had but one servant; Seneca avers he had none.
He was mean in his clothes: in his diet, by Philemon thus described:

He water drinks, then broth and herbs doth eat;

Teaching his scholars, almost without meat.

His chastity was so eminent, that it became a proverb; "`As chaste as Zeno.`"
When the news of his death came to Antigonus, he broke forth into these words,
"`What an object have I lost!`"
And being asked, why he admired him so much?
"`Because,`" saith he, "`though I bestowed many great things upon him,
he was never therewith exalted nor dejected.`"
The Athenians, after his death, by a public decree, erected a statue to his memorial;
it runs thus: "`Whereas Zeno, the son of Mnaseas, a Cittian,
has professed philosophy about fifty-eight years in this city,
and in all things performed the office of a good man,
encouraging those young men who applied themselves to him,
to the love of virtue and temperance,
leading himself a life suitable to the doctrine which he professed;
a pattern to the best to imitate: the people have thought fit to do honour to Zeno,
and to crown him with a crown of gold, according to law,
in regard of his virtue and temperance, and to build a tomb for him, publicly,
in the Ceramick, etc.`"
These two were his epitaphs, one by Antipater:

Here Zeno lies, who tall Olympus scal`'d;

Not heaping Pelion on Ossa`'s head;

Nor by Herculean labours so prevailed;

But found out virtue`'s paths, which thither led.

The other by Xenodotus, the Stoic, thus:

Zeno, thy years to hoary age were spent,

Not with vain riches, but with self-content.

XXVIII.
Seneca, a great and excellent philosopher,
who with Epictetus shall conclude the testimonies of the men of their character,
hath so much to our purpose that his works are but a kind of continued evidence for us:
he saith, "`Nature was not so much an enemy,
as to give an easy passage of life to all other creatures,
and that man alone should not live without so many arts;
she hath commanded us none of these things.
We have made all things difficult to us, by disdaining things that are easy: houses,
clothes, meats, and nourishment of bodies,
and those things which are now the care of life, were easy to come by, freely gotten,
and prepared with a light labour: for the measure of these things was necessity,
not voluptuousness: but we have made them pernicious and admirable:
they must be sought with art and skill.
Nature sufficeth to that which she requireth.

"`Appetite hath revolted from nature, which continually inciteth itself,
and increaseth with the ages, helping vice by wit.
First it began to desire superfluous, then contrary things: last of all,
it sold the mind to the body, and commanded it to serve the lusts thereof.
All these arts, wherewith the city is continually set at work, and maketh such a stir,
do center in the affairs of the body,
to which all things were once performed as to a servant,
but now are provided as for a lord: hence the shops of engravers, perfumers, etc.
Hence, of those that teach effeminate motions of the body, and vain and wanton songs:
for natural behaviour is despised, which completed desires with necessary help;
now it is clownishness and ill-breeding to be contented with as much as is requisite.
What shall I speak of rich marbles curiously wrought,
wherewith temples and houses do shine?
What of stately galleries and rich furniture?
these are but the devices of most vile slaves; the inventions of men, not of wise men:
for wisdom sits deeper; it is the mistress of the mind.
Wilt thou know what things she hath found out, what she hath made?
Not unseemly motions of the body, nor variable singing by trumpet or flute;
nor yet weapons of wars, or fortifications: she endeavoureth profitable things;
she favours peace, and calls all mankind to agreement: she leadeth to a blessed estate;
she openeth the way to it, and shows what is evil from what is good,
and chaseth vanity out of the mind.
She giveth solid greatness, but debaseth that which is puffed up,
and would be seen of men:
she bringeth forth the image of God to be seen in the souls of men:
and so from corporeal, she translateth into incorporeal things.`"
Thus in the 90th epistle to Luculius.
To Gallio, he writeth thus: "`All men, brother Gallio, are desirous to live happy,
yet blind to the means of that blessedness.
As long as we wander hither and thither, and follow not our guide,
but the dissonant clamour of those that call on us to undertake different ways,
our short life is wearied and worn away amongst errors,
although we labour to get us a good mind: there is nothing therefore to be more avoided,
than following the multitude without examination, and believing anything without judging.
Let us inquire, what is best done, not what is more usually done;
and what planted us in the possession of eternal felicity;
not what is ordinarily allowed of by the multitude,
which is the worst interpreter of truth.
I call the multitude, as well those that are clothed in white, as those in other colours:
for I examine not the colours of the garments, wherewith their bodies are clothed:
I trust not mine eyes to inform me what a man is; I have a better and truer light,
whereby I can distinguish truth from falsehood.
Let the soul find out the good of the soul;
if once she may have leisure to withdraw into herself, Oh! how will she confess,
I wish all I have done were undone; and all I have said, when I recollect it,
I am ashamed of it, when I now hear the like in others.
These things below, whereat we gaze, and whereat we stay,
and which one man with admiration shows unto another, do outwardly shine,
but are inwardly empty.
Let us seek out somewhat that is good, not in appearance, but solid, united, and best,
in that which least appears: let us discover this.
Neither is it far from us: we shall find it if we seek it.
For it is wisdom not to wander from that immortal nature,
but to form ourselves according to his law and example.
Blessed is the man who judgeth rightly:
blessed is he who is contented with his present condition:
and blessed is he who giveth ear to that immortal principle,
in the government of his life.`"
A whole volume of these excellent things hath he written.
No wonder a man of his doctrine and life escaped not the cruelty of brutish Nero,
under whom he suffered death; as also did the apostle Paul, with whom,
it is said Seneca had conversed.
When Nero`'s messenger brought him the news, that he was to die;
with a composed and undaunted countenance he received the errand,
and presently called for pen, ink, and paper, to write his last will and testament;
which the captain refusing, he turned towards his friends, and took his leave thus:
"`Since, my loving friends,
I cannot bequeath you any other thing in acknowledgment of what I owe you,
I leave you at least the richest and best portion I have,
that is the image of my manners and life, which doing, you will obtain true happiness.`"
His friends showing great trouble for the loss of him; "`Where,`" saith he,
"`are those memorable precepts of philosophy?
And what is become of those provisions,
which for so many years together we have laid up
against the brunts and afflictions of Providence?
Was Nero`'s cruelty unknown to us?
What could we expect better at his hands,
that killed his brother and murdered his mother,
but that he would put also his tutor and governor to death?`"
Then turning to his wife Pompeia Paulina, a Roman lady, young and noble,
besought her for the love she bore him and his philosophy,
to suffer patiently his affliction: "`For,`" saith he,
"`my hour is come wherein I must show, not only by discourse but by death,
the fruit I have reaped by my meditations; I embrace it without grief,
wherefore do not dishonour it with thy tears.
Assuage thy sorrow, and comfort thyself in the knowledge thou hast had of me,
and of my actions;
and lead the rest of thy life with that honest industry thou hast addicted thyself unto.`"
And dedicating his life to God, he expired.

XXIX.
Epictetus, contemporary with Seneca, and an excellent man,
thought no man worthy of the profession of philosophy,
that was not purified from the errors of his nature.
His morals were very excellent, which he comprised under these two words, sustaining,
and abstaining; or bearing, and forbearing; to avoid evil,
and patiently to suffer afflictions,
which do certainly comprise the christian doctrine and life,
and is the perfection of the best philosophy that was at any time taught by Egyptians,
Greeks, or Romans, when it signified virtue, self-denial,
and a life of religious solitude and contemplation.

How little the Christians of the times are true philosophers,
and how much more these philosophers were Christians, than they,
let the righteous principle in every conscience judge.
But is it not then intolerable, that they should be esteemed Christians,
who are yet to learn to be good Heathens?
That prate of grace and nature, and know neither?
Who will presume to determine what is become of Heathens,
and know not where they are themselves, nor mind what may become of them?
That can run readily over a tedious list of famous personages,
and calumniate such as will not, with them,
celebrate their memories with extravagant and superfluous praises,
whilst they make it laudable to act the contrary: and none so ready a way to become vile,
as not to be vicious?
A strange paradox, but too true; so blind, so stupified, so besotted,
are the foolish sensualists of the world, under their great pretences to religion, faith,
and worship.
Ah! did they but know the peace, the joy, the unspeakable ravishments of soul,
that inseparably attend the innocent, harmless, still, and retired life of Jesus?
Did they but weigh within themselves, the authors of their vain delights and pastimes,
the nature and disposition they are so grateful to,
the dangerous consequence of exercising the mind and its affections below,
and arresting and taking them up from their due attendance and
obedience to the most holy voice crying in their consciences,
"`Repent, return, all is vanity,
and vexation of spirit:`" were but these things reflected upon;
were the incessant wooings of Jesus, and his importunate knocks and entreaties,
by his light and grace, at the door of their hearts, but kindly answered,
and He admitted to take up his abode there: and lastly,
were such resolved to give up to the instructions and holy guidance of his eternal Spirit,
in all the humble, heavenly, and righteous conversation it requires,
and of which He is become our Captain and example; then, O then,
both root and branch of vanity, the nature that invented,
and that which delights herself therein, with all the follies themselves,
would be consumed and vanish.
But they, alas! cheat themselves by misconstrued Scriptures,
and daub with the untempered mortar of misapplied promises.
They will be saints whilst they are sinners; and in Christ,
whilst in the spirit of the world, walking after the flesh, and not after the Spirit,
by which the true children of God are led.
My friends, mind the just witness and holy principle in yourselves,
that you may experimentally know more of the Divine life, in which,
and not in a multitude of vain repetitions, true and solid felicity eternally consists.

=== IV. Nor is this reputation, wisdom, and virtue, only to be attributed to men: there were women also in the Greek and Roman ages, that honoured their sex, by great examples of meekness, prudence, and chastity; and which I do the rather mention, that the honour, story yields to their virtuous conduct, may raise an allowable emulation in those of their own sex, at least, to equal the noble character given them by antiquity, viz.

1+++.+++ Penelope.--2. Hipparchia.--3. Cornelia.--4. Pompeia Plautina.--5.
Plotina.--6. A reproof to voluptuous women of the times.

I+++.+++ Penelope, wife to Ulysses, a woman eminent for her beauty and quality,
but more for her singular chastity.
Her husband was absent from her twenty years, partly in the service of his country,
and partly in exile; and being believed to be dead,
she was earnestly sought by divers lovers,
and pressed by her parents to change her condition; but all the importunities of the one,
or persuasions of the other, not prevailing, her lovers seemed to use a kind of violence,
that where they could not entice, they would compel: to which she yielded,
upon this condition, that they would not press her to marry,
till she had ended the work she had in hand: which they granting,
"`she undid by night what she wrought by day;`" and
with that honest device she delayed their desire,
till her husband returned, whom she received, though in beggar`'s clothes,
with a heart full of love and truth.
A constancy that reproaches too many of the women of the times.
Her work shows the industry and employment,
even of the women of great quality in those times;
whilst those of the present age despise such honest labour as mean and mechanical.

II. Hipparchia, a fair Macedonian virgin, noble of blood, as they term it,
but more truly noble of mind, I cannot omit to mention:
who entertained so earnest an affection for Crates, the Cynical philosopher,
as well for his severe life as excellent discourse, that by no means could her relations,
nor suitors, by all their wealth, nobility, and beauty,
dissuade her from being his companion.
Upon which strange resolution, they all betook themselves to Crates,
beseeching him to show himself a true philosopher, in persuading her to desist:
which he strongly endeavoured by many arguments; but not prevailing, went his way,
and brought all the little furniture of his house, and showed her: "`This,`" saith he,
"`is thy husband; that, the furniture of thy house: consider on it,
for thou canst not be mine,
unless thou followest the same course of life:`" for being rich above twenty talents,
which is more than £50,000, he neglected all to follow a retired life:
all which had so contrary an effect, that she immediately went to him, before them all,
and said, "`I seek not the pomp and effeminacy of this world, but knowledge and virtue,
Crates; and choose a life of temperance, before a life of delicacies;
for true satisfaction, thou knowest, is in the mind;
and that pleasure is only worth seeking, that lasts forever.`"
Thus was it she became the constant companion both of his love and life,
his friendship and his virtues; travelling with him from place to place,
and performing the public exercises of instruction with Crates, wherever they came.
She was a most violent enemy to all impiety, but especially to wanton men and women,
and those whose garb and conversation showed them devoted to vain pleasures and pastimes;
effeminacy rendering the like persons not only unprofitable,
but pernicious to the whole world.
Which she as well made good by the example of her exceeding industry, temperance,
and severity, as those are wont to do by their intemperance and folly:
for ruin of health, estates, virtue, and loss of eternal happiness, have ever attended,
and ever will attend, such earthly minds.

III.
Cornelia, also a noble Roman matron, and sister to Scipio,
was esteemed the most famous and honourable personage of her time,
not more for the greatness of her birth, than her exceeding temperance.
And history particularly mentions this, as one great instance of her virtue,
for which she was so much admired, to wit,
that she never was accustomed to wear rich apparel,
but such apparel as was very plain and grave; rather making her children,
whom her instructions and example had made virtuous, her greatest ornament:
a good pattern for the vain and wanton dames of the age.

IV. Pompeia Plautina, wife to Julianus the emperor,
commended for her compassion to the poor,
used the power her virtue had given her with her husband,
to put him upon all the just and tender things that became his charge,
and to dissuade him from whatsoever seemed harsh to the people:
particularly she diverted him from a great tax his
flatterers advised him to lay upon the people.

V+++.+++ Plotina, the wife of Trajan, "`a woman,`" saith a certain author,
"`adorned with piety, chastity, and all the virtues that a woman is capable of.`"
There are two instances; one of her piety, the other of her chastity; the first is this:
when her husband was proclaimed emperor, she mounted the capitol after the choice, where,
in a religious manner, she said, "`Oh, that I may live under all this honour,
with the same virtue and content, that I enjoyed before I had it.`"
The second is this: her husband being once exiled, she caused her hair to be cut short,
as the men wore it,
that with less notice and danger she might be the companion of his banishment.

VI. Thus may the voluptuous women of the times read
their reproof in the character of a brave Heathen,
and learn, that solid happiness consists in a neglect of wealth and greatness,
and a contempt of all corporeal pleasures,
as more befitting beasts than immortal spirits: and which are loved by none but such,
as not knowing the excellency of heavenly things, are both inventing and delighting,
like brutes, in that which perisheth: giving the preference to poor mortality,
and spending their lives to gratify the lusts of a little dirty flesh and blood,
that shall never enter into the kingdom of heaven;
by all which their minds become darkened, and so insensible of more celestial glories,
that they do not only refuse to inquire after them,
but infamously scoff and despise those that do, as a foolish and mad people:
to that strange degree of darkness and impudence this age has got.
But if the exceeding temperance, chastity, virtue, industry,
and contentedness of very Heathens,
with the plain and necessary enjoyments God has been pleased
to vouchsafe to the sons and daughters of men,
as sufficient to their wants and conveniency,
that they may be the more at leisure to answer the great end of their being born,
will not suffice, but that they will exceed the bounds, precepts, and examples,
both of Heathens and Christians; anguish and tribulation will overtake them,
when they shall have an eternity to think upon, with gnashing teeth,
what to all eternity they can never remedy; these dismal wages are decreed for them,
who so far affront God, heaven, and eternal felicity,
as to neglect their salvation from sin here and wrath to come,
for the enjoyment of a few fading pleasures.
For such to think, notwithstanding their lives of sense and pleasure,
wherein their minds become slaves to their bodies,
that they shall be everlastingly happy, is an addition to their evils:
since it is a great abuse to the holy God,
that men and women should believe Him an eternal
companion for their carnal and sensual minds:
for "`As the tree falls, so it lies; and as death leaves men,
judgment finds them;`" and there is no repentance in the grave.
Therefore, I beseech you, to whom this comes, to retire: withdraw a while:
let not the body see all, taste all, enjoy all; but let the soul see too,
taste and enjoy those heavenly comforts and refreshments proper to that eternal world,
of which she is an inhabitant,
and where she must ever abide in a state of peace or plagues,
when this visible one shall be dissolved.
