== Chapter XX.

[.chapter-subtitle--blurb]
The doctrine and practice of the blessed Lord Jesus, and his Apostles;
the primitive Christians, and those of more modern times, in favour of this discourse.

[.chapter-synopsis]
* 1+++.+++ The Doctrine of Christ, from Matt. 5. about denial of self.
* 2+++.+++ John the Baptist`'s example.
* 3+++.+++ The testimonies of the apostle Peter, etc.
* 4+++.+++ Paul`'s godly exhortation against pride, covetousness, and luxury.
* 5+++.+++ The primitive Christians`' nonconformity to the world.
* 6+++.+++ Clemens Romanus against the vanity of the Gentiles.
* 7+++.+++ Machiavel, of the zeal of the primitive Christians.
* 8+++.+++ Tertullian, Chrysostom, etc. on Matt. 12:36.
* 9+++.+++ Gregory Nazianzen.
* 10+++.+++ Jerom.
* 11+++.+++ Ambrose.
* 12+++.+++ Augustine.
* 13+++.+++ Council of Carthage.
* 14+++.+++ Cardan.
* 15+++.+++ Gratian.
* 16+++.+++ Cardan.
* 17+++.+++ Waldenses.
* 18+++.+++ What they understood by daily bread in the Lord`'s Prayer.
* 19+++.+++ Their judgment concerning taverns.
* 20+++.+++ Dancing, Music, etc.
* 21+++.+++ An epistle of Bartholomew Tertian to the Waldensian churches, etc.
* 22+++.+++ Their extreme suffering and faithfulness. Their degeneracy reproved, that call them their ancestors.
* 23+++.+++ Paulinus, Bishop of Nola, relieving slaves and prisoners.
* 24+++.+++ Acacius, Bishop of Amida, his charity to enemies.

Having abundantly shown how much the doctrine and the conversation
of the virtuous Gentiles condemn the pride,
avarice, and luxury of the professed Christians of the times; I shall, in the next place,
to discharge my engagement, and farther fortify this discourse,
present my reader with the judgment and practice of the most christian times;
as also of eminent writers, both ancient and modern.
I shall begin with the blessed Author of that religion.^
footnote:[The doctrine and practice of the blessed Lord Jesus and his apostles,
the primitive Christians, and those of more modern times in favour of this discourse.]

[.numbered-group]
====

[.numbered]
I+++.+++ Jesus Christ, in whose mouth there was found no guile, sent from God,
with a testimony of love to mankind, and who laid down his life for their salvation;
whom God hath raised by his mighty power to be Lord of all,
is of right to be first heard in this matter; for never man spake like him to our point;
shot, clear, and close; and all opposite to the way of this wicked world.
"`Blessed,`" says he, "`are the poor in spirit, for theirs is the kingdom of God:`"^
footnote:[Matt. 5.]
He doth not say, blessed are the proud, the rich, the high-minded:
here is humility and the fear of the Lord blest.
"`Blessed are they that mourn, for they shall be comforted:`" He doth not say,
blessed are the feasters, dancers, and revellers of the world,
whose life is swallowed up of pleasure and jollity: no; as He was a man of sorrows,
so He blest the godly sorrowful.
"`Blessed are the meek, for they shall inherit the earth:`" He doth not say,
blessed are the ambitious, the angry, and those that are puffed up:
He makes not the earth a blessing to them: and though they get it by conquest and rapine,
it will at last fall into the hands of the weak to inherit.
Again,
"`Blessed are they which do hunger and thirst after righteousness:`"
but no blessing to the hunger and thirst of the luxurious man.
"`Blessed are the merciful,
for they shall obtain mercy:`" He draws men to tenderness and forgiveness by reward.
Hast thou one in thy power that hath wronged thee?
Be not rigorous; exact not the utmost farthing; be merciful, and pity the afflicted,
for such are blessed.
Yet further, "`Blessed are the pure in heart, for they shall see God.`"
He doth not say, blessed are the proud, the covetous, the unclean, the voluptuous,
the malicious: no; such shall never see God.
Again, "`Blessed are the peacemakers, for they shall be called the children of God.`"
He doth not say, blessed are the contentious, back-biters, tale-bearers, brawlers,
fighters, makers of war; neither shall they be called the children of God,
whatever they may call themselves.
Lastly, "`Blessed are ye when men shall revile you, and persecute you,
and say all manner of evil against you, falsely for my sake:
rejoice and be exceeding glad, for great is your reward in heaven.`"
He blesseth the troubles of his people,
and translates earthly sufferings into heavenly rewards.
He doth not say, blessed are you when the world speaks well of you, and fawns upon you:
so that his blessings cross the world`'s. For the world blesseth those as happy,
that have the world`'s favour; He blesseth those as happy that have the world`'s frowns.
This solveth the great objection, Why are you so foolish to expose yourselves to the law,
to incur the displeasure of magistrates,
and suffer the loss of your estates and liberties?
Cannot a man serve God in his heart, and do as others do?
Are you wiser than your forefathers?
Call to mind your ancestors.
Will you question their salvation by your novelties,
and forget the future good of your wife and children,
as well as sacrifice the present comforts of your life, to hold up the credit of a party?
A language I have more than once heard: I say,
this doctrine of Christ is an answer and antidote against the power of this objection.
He teaches us to embrace truth under all those scandals.
The Jews had more to say of this kind than any,
whose way had a more extraordinary institution;
but Christ minds not either institution or succession.
He was a new man, and came to consecrate a new way, and that in the will of God;
and the power that accompanied his ministry, and that of his followers,
abundantly proved the Divine authority of his mission,
who thereby warns his to expect and to bear contradiction, reviling, and persecution:
for if they did it to the green tree,
much more were they to expect that they would do it to the dry; if to the Lord,
then to the servant.

Why then should Christians fear that reproach and tribulation,
that are the companions of his religion,
since they work to his sincere followers a far more
exceeding and eternal weight of glory?
But indeed they have great cause to fear and be ashamed,
who are the authors of such reproach and suffering,
so contrary to the meek and merciful spirit of Christ: for if they are blessed,
who are reviled and persecuted for his sake, the revilers and persecutors must be cursed.
But this is not all: He bids his disciples follow Him, learn of Him,
for He was meek and lowly: He taught them to bear injuries, and not smite again;
to exceed in kindness: to go two miles when asked to go one;
to part with cloak and coat too; to give to them that ask,
and to lend to them that would borrow; to forgive, aye, and love enemies too;
commanding them, saying, "`Bless them that curse you; do good to them that hate you;
and pray for them which despitefully use you, and persecute you.`"^
footnote:[Matt 5.]
Urging them with a most sensible demonstration, "`That,`" saith He,
"`ye may be the children of your Father, which is in heaven:
for He maketh his sun to rise upon the good and the evil,
and his rain to descend upon the just and the unjust.
He also taught his disciples to believe and rely upon God`'s providence,
from the care that He had over the least of his creatures: "`Therefore,`" saith He,
"`I say unto you, take no thought for your life, what ye shall eat,
and what ye shall drink, nor yet for your body, what ye shall put on:
is not the life more than meat, and the body than raiment?
Behold the fowls of the air, for they sow not, neither do they reap,
nor gather into barns; yet your heavenly Father feedeth them;
are ye not much better than they?
Which of you, by taking thought, can add one cubit unto his stature?
And why take ye thought for raiment?
Consider the lilies of the field, how they grow; they toil not, neither do they spin:
and yet I say unto you,
that even Solomon in all his glory was not arrayed like one of these.
Wherefore, if God so clothe the grass of the field, which today is,
and tomorrow is cast into the oven, shall He not much more clothe you,
O ye of little faith?
Therefore take no thought, saying, What shall we eat, or what shall we drink,
or wherewithal shall we be clothed?
For after all these things do the Gentiles seek,
for your heavenly Father knoweth that ye have need of all these things.
But seek ye first the kingdom of God, and his righteousness,
and all these things shall be added unto you.
Take therefore no thought for the morrow,
for the morrow shall take thought for the things of itself:
sufficient unto the day is the evil thereof.`"^
footnote:[Mat.
vi.]
Oh! how plain, how sweet, how full, yet how brief are his blessed sentences!
They thereby show from whence they came, and that Divinity itself spoke them:
what are laboured, what are forced and scattered in the best of other writers,
and not all neither, is here comprised after a natural, easy, and conspicuous manner.
He sets nature above art, and trust above care.
This is He that himself came poor into the world, and so lived in it: He lay in a manger,
conversed with mechanics; fasted much, retired often: and when He feasted,
it was with barley loaves and fish, dressed doubtless in an easy and homely manner.
He was solitary in his life, in his death ignominious.
The foxes had holes, the birds of the air had nests,
but the Son of Man had not a place whereon to lay his head.
He that made all things as God, had nothing as man;
which hath this blessed instruction in it,
that the meanest and poorest should not be dejected,
nor yet the richest and highest be exalted.
In fine, having taught this doctrine, and lived as He spoke, He died to confirm it,
and offered up Himself a propitiation for the sins of the whole world,
when no other sacrifice could be found, that could atone for man with God, who,
rising above the power of death and the grave, hath led captivity captive,
and is become the first-born from the dead, and Lord of the living;
and his living people praise Him, who is worthy forever.

[.numbered]
II. John the Baptist, who was the fore-runner of Christ`'s appearance in the flesh,
did by his own abstinence sufficiently declare what sort of person
it was he came to prepare and bespeak people to receive.
For, though sanctified from his birth and declared by Christ to be the greatest of all prophets;
yet his clothing was but a coarse garment of camel`'s hair, and a leather girdle;
and his food, only locusts and wild honey: a life very natural, and of great simplicity.
This was all the pomp and retinue,
which the greatest ambassador that ever came to the world was attended with;
about the best of messages, to wit, Repent, for the kingdom of God is at hand: and,
there is one coming after me, whose shoes-latchet I am not worthy to unloose,
who shall baptize you with fire, and with the Holy Ghost;
and is the Lamb of God that taketh away the sin of the world.^
footnote:[Matt. 3:11; John 1:29.]
Did the fore-runner of the coming of God, for Immanuel is God with men,
appear without the state, grandeur, and luxury of the world;
and shall those who pretend to receive the message, and that for glad tidings too,
and confess the Immanuel, Jesus Christ, to be the Lord,
live in the vanity and excess of the world, and care more for their fine clothes,
delicate dishes, rich furniture, stately attendance, and pleasant diversion,
than for the holy cross of Christ, and blessed narrow way that leadeth to salvation.
Be ashamed, and repent!

[.numbered]
III.
Peter, Andrew, Philip, and the rest of the holy apostles, were,
by calling as well as doctrine, not a luxurious people;
for they were made up of poor fishermen and mechanics;
for Christ called not his disciples out of the higher ranks of men,
nor had they ability any more than will to use the excesses herein reproved.
You may conceive what their lives were, by what their Master`'s doctrine was;
for they were the true scholars of his heavenly discipline.
Peter thus speaks, and exhorteth the Christians of his time,
"`Let not your adorning be that outward adorning of plaiting the hair,
and the wearing of gold, and of putting on of apparel;
but let it be the hidden man of the heart, in that which is not corruptible,
even the ornament of a meek and quiet spirit,
which is in the sight of God of great price; for after this manner, in the old time,
the holy women, who also trusted in God, adorned themselves.`"^
footnote:[1 Pet. 3:3-4.]
Wherefore gird up the loins of your minds, be sober and hope to the end,
as obedient children, not fashioning yourselves according to your former lusts,
in your ignorance, but as He which hath called you is holy,
so be ye holy in all manner of conversation:^
footnote:[1 Pet. 1:13-15.]
and giving all diligence, add to your faith, virtue; to virtue, knowledge;
and to knowledge, temperance; and to temperance, patience; and to patience, godliness;
and to godliness, brotherly-kindness; and to brotherly-kindness, charity;
for if these things be in you and abound, they make you,
that you shall be neither barren nor unfruitful:
for so an entrance shall be ministered unto you abundantly,
into the everlasting kingdom of our Lord and Saviour Jesus Christ;^
footnote:[2 Pet. 1:5-8, 11.]
not rendering evil for evil, or railing for railing; but contrariwise, blessing;
knowing that ye are thereunto called, that ye shall inherit a blessing:^
footnote:[1 Pet. 3:9.]
for even hereunto were ye called, because Christ also suffered for us,
leaving us an example, that ye should follow his steps, who did no sin,
neither was guile found in his mouth; who, when He was reviled, reviled not again;
when He suffered, He threatened not,
but committed himself to Him that judgeth righteously.^
footnote:[1 Pet. 2:21-23.]

[.numbered]
IV. Paul, who was also an apostle, though, as he saith, born out of due time:
a man of great knowledge and learning, but, "`I count it,`" saith he,
"`all loss for the excellency of the knowledge of Christ Jesus, my Lord,
for whom I have suffered the loss of all things, and do count them but dung,
that I may win Christ.
Brethren, be followers of me, and mark them which walk so, as ye have us for an ensample:
for many walk, of whom I have told you often, and now tell you even weeping,
that they are the enemies of the cross of Christ, whose end is destruction;
whose god is their belly; they glory in their shame, and they mind earthly things.
For our conversation is in heaven; from whence we look also for the Saviour,
the Lord Jesus Christ.`"^
footnote:[Phil. 3:18-8.]
In like manner also, "`I will that women adorn themselves in modest apparel,
with shame-facedness and sobriety, not with broidered hair, or gold, or pearls,
or costly array; but with good works, as becometh women professing godliness.`"^
footnote:[1 Tim. 2:10-9.]
"`Be followers of God, as dear children, and walk in love, as Christ also hath loved us:
but fornication, and all uncleanness, and covetousness,
let it not be once named amongst you, as becometh saints;
neither filthiness nor foolish talking, nor jesting, which are not convenient;
but rather giving of thanks: for this ye know, that no whoremonger, unclean person,
nor covetous man, who is an idolater, hath any inheritance in the kingdom of Christ,
and of God.
See, then, that you walk circumspectly, not as fools, but as wise, redeeming the time,
because the days are evil.
Wherefore be ye not unwise, but understanding what the will of the Lord is;
and be not drunk with wine, wherein is excess; but be filled with the Spirit,
speaking to yourselves in hymns and spiritual songs,
singing and making melody in your hearts to the Lord.`"^
footnote:[Ephes. 5.]
"`Rejoice in the Lord always; and again, I say rejoice.
Let your moderation be known to all men, for the Lord is at hand.`"^
footnote:[Phil. 4:4-6.]
"`Be careful for nothing, for we brought nothing into this world,
and it is certain we can carry nothing out: and, having food and raiment,
let us be therewith content; for godliness, with contentment, is great gain:
but they that will be rich, fall into temptation, and a snare,
and into many foolish and hurtful lusts, which drown men in perdition and destruction;
for the love of money is the root of all evil, which whilst some coveted after,
they have erred from the faith, and pierced themselves through with many sorrows.
But thou, O man of God, flee these things, and follow after righteousness, godliness,
faith, love, patience, meekness.
Fight the good fight of faith, and lay hold on eternal life,
whereunto thou art also called,
and hast professed a good profession before many witnesses.
I give thee charge in the sight of God, who quickeneth all things,
and before Christ Jesus, who before Pontius Pilate witnessed a good confession,
that thou keep this commandment without spot, unrebukeable,
until the appearing of our Lord Jesus Christ.
Charge them that are rich in this world, that they be not high-minded,
nor trust in uncertain riches, but in the living God,
who giveth us richly all things to enjoy; that they do good,
that they be rich in good works, ready to distribute, willing to communicate,
laying up in store for themselves a good foundation against the time to come,
that they may lay hold on eternal life.
O Timothy, keep that which is committed to thy trust,
avoiding profane and vain babblings, and oppositions of science, falsely so called,
which some professing, have erred concerning the faith.
Grace be with thee, Amen.`"^
footnote:[1 Tim. 6:7, to the end.]
This was the blessed doctrine these messengers of eternal life declared,
and what is more, they lived as they spoke.
You find an account of their reception in the world, and the way of their living,
in his first epistle to the Corinthians; "`For I think,`" saith he,
"`that God hath set forth us, the apostles last, as it were, appointed to death;
for we are made a spectacle to the world, to angels, and to men.
We are fools for Christ`'s sake: we are weak, we are despised:
even unto this present hour we both hunger and thirst,
and have no certain dwelling-place, and labour, working with our hands: being reviled,
we bless; being persecuted we suffer it; being defamed, we entreat.
We are made as the filth of the world,
and are as the off-scouring of all things unto this day.`"^
footnote:[1 Cor. 4:9.]
This was the entertainment those faithful followers
of Jesus received at the hands of an ungrateful world;
but he who tells us of this, also tells us, it is no unusual thing: "`For,`" saith he,
"`such as will live godly in Christ Jesus, must suffer persecution.`"
Besides, he knew it had been the portion of the righteous in preceding ages,
as in his excellent account of the faith, trials, and victory of the holy ancients,
in his epistle to the Hebrews he does largely express, where he tells us,
how great a sojourner Abraham was, even in the land of promise,
a stranger in his own country, for God had given it unto him and his posterity, dwelling,
saith he, in tents with Isaac and Jacob.
And why not better settled?
Was it for want of understanding, or ability, or materials?
No; he gives a better reason; for, saith he,
Abraham looked for a city which had foundations, whose builder and maker is God.
And speaking of Moses, he tells us, "`that, by faith,
when he was come to years of discretion,
he refused to be called the son of Pharaoh`'s daughter,
choosing rather to suffer affliction with the people of God,
than to enjoy the pleasures of sin for a season,
esteeming the reproach of Christ greater riches than the treasures of Egypt;
for he had respect unto the recompense of reward; nor feared he the wrath of the king,
for he endured, seeing him who is invisible.`"
He adds, "`And others had trials of cruel mockings and scourgings; yea,
moreover of bonds and imprisonments; they were stoned, they were sawn asunder,
were tempted, were slain with the sword;
they wandered about in sheep-skins and goat-skins, being destitute, afflicted, tormented,
of whom the world was not worthy.
They wandered in deserts, and in mountains, and in dens, and caves of the earth,
and these all have obtained a good report.`"
Methinks this should a little abate the intemperance of professed Christians.
I do not bid them be thus miserable,
but I would not have them make themselves so hereafter;
for this afflicted life hath joys transcending the utmost pleasure that sin can give,
and in the end it will be found, that it were better to be a poor pilgrim,
than a citizen of the world.
Nor was this only the life and instruction of apostolical teachers;
the same plainness and simplicity of life was also followed by the first Christians.

[.numbered]
V+++.+++ "`The primitive Christians,`"^
footnote:[Animad. in Min. Fel. p. 25.]
Ouzelius, in his animadversions on Minutius Felix, saith,
"`were reproached by the Gentiles for their ill-breeding, rude and unpolished language,
unfashionable behaviour,
as a people that knew not how to carry themselves in their addresses and salutations,
calling them rustics and clowns, which the Christians easily bore,
valuing their profession the more for its nonconformity to the world:
wherefore it was usual with them, by way of irony and contempt, to call the Gentiles,
the well-bred, the eloquent, and the learned.`"
This he proves by ample testimonies out of Arnobius, Lactantius, Isidorus Pelusiota,
Theodoret, and others.
Which may instruct us,
that the Christians`' behaviour was not regulated
by the customs of the country they lived in,
as is usually objected against our singularity: no,
they refused the embellishment of art, and would not wear the furniture of her invention,
but as they were singular in their religion,
so in the way of their conversation among men.

[.numbered]
VI. Clement Romanus,^
footnote:[Constit. Clem Rom. 50:1, chap. 2.]
if author of the constitutions that go under his name, hath this among the rest,
"`Abstain from the vain books of the Gentiles.
What have you to do with strange and unprofitable discourses,
which only serve to seduce weak persons?`"
This Clement is remembered by Paul in one of his epistles,^
footnote:[Phil. 4:3.]
who in this exactly follows his advice to Timothy, about vain questions,
doubtful disputes, and opposition of science.
Let us see how this moderation and purity of manners continued.

[.numbered]
VII. Machiavel,^
footnote:[Mach. DIsa. 50:2, chap. 5.]
no mean author, in his Disputations, assures us,
"`That the first promoters of Christianity were so diligent in
rooting out the vanities and superstitions of the Gentiles,
that they commanded all such poets`' and historians`' books,
who commended anything of the Gentile conversation or worship,
to be burned;`" but that zeal is evidently extinguished,
and those follies revived among the professors of the religion of Jesus.

[.numbered]
VIII. Tertullian,^
footnote:[Tert. lib. de Patien. Chrysost.]
Chrysostom, Theophylact, Gregory Nazianzene, upon these words of Christ,
"`But I say unto you, that every idle word that men shall speak,
they shall give an account thereof in the day of judgment:`"^
footnote:[Matt. 12:36:]
thus reflect upon vain discourse: "`These words mean,`" saith Tertullian,
"`of all vain and superfluous speech, more talk than is necessary.`"
Says Chrysostom, "`of such words as are not convenient or profitable,
but move immodestly.`"
Says Theophylact, "`of all lies, calumnies, all inordinate and ridiculous speeches.`"
Says Gregory, "`such words men shall account for,
which want that profit ever redounding from modest discourses,
and that are seldom uttered from any preceding necessity or cause; things frivolous,
fables, old wives`' tales.`"
All which sufficiently reprehend the plays, poetry, and romances of the times,
of great folly, vanity, and sin.

[.numbered]
IX. Gregory, and this a father of the church, a very extraordinary man,
was so zealous for the simplicity and purity of the mind, language,
and lives of the Christians of his time, that he suppressed several Greek authors,
as Menander, Diphilus, Apollodorus, Philemon, Alexis, Sappho, and others,
which were the recreations of the vain Gentiles: thus Cardan.
Hear his judgment of fine clothes,
none of the least part of the luxury and vanity of the age.
"`There be some,`" saith he, "`are of opinion,
that the wearing of precious and sumptuous apparel is no sin; which if it were no fault,
the Divine word would never have so punctually expressed, nor historically related,
how the rich man, that was tormented in hell, was clothed in purple and silk:
whence we may note, that, touching the matter or subject of attire,
human curiosity availeth highly.
The first substance of our garments was very mean, to wit, skins, with wool;
when it is we read, God made Adam and his wife coats of skins; that is,
of skins of dead beasts.
Afterwards, to see the growing pride and vanity of men and women, they came to pure wool,
because lighter; after that to flax: then to dung and ordure of worms, to wit, silk;
lastly, to gold and silver, and precious stones,
which excess of apparel highly displeased God: for instance whereof,
which the very Pagans themselves observed,
we read that the very first among the Romans that
ever wore purple was struck with a thunder-bolt,
and so died suddenly for a terror to all succeeding times,
that none should attempt to live proudly in precious attire.`"
This was the sense of Gregory Nazianzene, that ancient Christian writer,
who wore commonly a poor coat, like to a frock; so did Justin Martyr, Jerome, and Austin,
as their best robe.

[.numbered]
X+++.+++ Jerom, a famous man, also styled a father of the church,
above all others seems positive in this matter, in an epistle he wrote to a noble virgin,
called Demetias, in which he exhorted her, That after she had ended her devotion,
she should take in hand wool and weaving, after the commendable example of Dorcas;
that by such changing and variety of works, the day might seem less tedious,
and the attempts of Satan less grievous;
concluding his religious exhortation with this positive sentence: saith he,
"`I speak generally;
No raiment or habit whatsoever shall seem precious in Christ`'s sight,
but that which thou makest thyself:
either for thy own particular use or example of other virgins,
or to give unto thy grandmother or mother: no,
though otherwise thou didst distribute thy goods to the poor.`"
Let but this strictness be considered,
and compared with the apparel and conversation of the age; for,
however Pharisee-like they otherwise saint him, and call him an Holy Father, sure it is,
they reject his counsel.

[.numbered]
XI. Hilary, bishop of Poictiers, a father of the church,
and famous for his writings against the Arians, having travelled into Syria,
was informed, that Abra, his only daughter, whom he left with her mother,
was by the greatest lords of the country solicited in marriage;
being a young woman well-bred, fair, and rich, and in the prime of her age.
He wrote to her, earnestly pressing her,
By no means to fix her affections upon the pleasure, greatness,
or advantage that might be presented to her;
for in his voyage he had found a greater and worthier match,
an husband of far more power and magnificence,
who would endow her with robes and jewels of an inestimable value.
This he did to take off her desires from the world, that he might wed her unto God:
and it was his fervent and frequent prayer, which in some sense was answered;
for she lived religiously, and died a virgin: Which shewed great nobility of mind,
that taught his daughter to tread upon the mountains of worldly glory;
and it was not less honourable in her that so readily yielded
to the excellent counsel of her pious father.

[.numbered]
XII.
Ambrose, called a father, who was lieutenant to the province and city of Milan,
and upon his discreet appeasing the multitude,
disordered upon some difference amongst them about electing a bishop,
was by their uniform consent chosen himself: although this person, of all others,
might have been thought to plead for the accustomed recreations,
especially not having been long a Christian, for he was a Catechumen,
or one but lately instructed, at the time of his being elected;
yet doth he in so many words determine the matter thus:
"`Plays ought not to be known by Christians;`" then not made, heard,
and defended by Christians; or they must be none that do so.

[.numbered]
XIII. Augustine,^
footnote:[August. de Civit. Dei. l. ii. c. 7.]
more famous for his many books, and knowledge in church affairs,
whose sentences are oracles with some, gives this as his opinion of plays,
and the like recreations,
that they were more pernicious and abominable than those idolatrous sacrifices,
which were offered in honour of the pagan gods.
Doubtless he thought the one not so offensive to reason and
the impressions divinity hath made on every understanding,
as the other were very pleasant to the senses,
and therefore apt to steal away the mind from better things; for it was his maxim,^
footnote:[De ira Dei. l. 9, c. 7.]
that everything a man doth, is either a hindrance or furtherance to good.
This would be esteemed intolerable doctrine in a poor Quaker,
yet will the Quaker rejoice,
if it be esteemed and followed as good doctrine in Augustine.

[.numbered]
XIV.
The council of Carthage, though times began to look somewhat mistier,
and the purity and spirituality of religion to be
much declined by the professors of Christianity;
yet there was so much zeal left against the worst part of Heathenism,
that I find an express canon against the reading of vain books and comedies of the Gentiles,
lest the minds of the people should be defiled by them.
But this age either hath no such canon, or executeth it not,
to the shame of their profession.

[.numbered]
XV. Cardan more particularly relateth,^
footnote:[Cardan de Sapient. l. 2.]
how even Gregory the Great was so zealous of preserving purity of manners among Christians,
who lived almost two hundred years after the Carthaginian council,
// lint-disable invalid-characters "æ"
that he caused many Latin authors to be burned, as vain and lascivious; as Cæcilianus,
Affranius, Navius, Licinus, Ennius, Attilius, Victor, Lucian`'s Dialogues;
nor did Plautus, Martial, and Terence,
so much in request both in the schools and academies of the land,
escape their honest zeal,
although the multitude of copies so far frustrated their good intentions,
as that they are multiplied of late.

[.numbered]
XVI. Gratian also^
footnote:[Jac. Laurentio de lib. Gentil. p. 40, 41.]
had such like passages as these, "`We see that the priests of the Lord,
neglecting the gospel and the prophets, read comedies or play-books,
and sing love verses, and read Virgil,`" a book in which are some good expressions.
Strange! that these things should have been so sincerely censured of old,
and that persons whose names are had in so much reverence,
should repute these their censures the constructions of Christ`'s precepts,
and the natural consequences of the Christian doctrine;
and yet that they should be so far neglected of this age,
as not to be judged worthy an imitation.
But pray let us hear what doctrine the Waldenses teach in this affair.

[.numbered]
XVII.
Petrus Bellonius, that great and inquisitive traveller, when he came to Mount Athos,
where there live in several monasteries six thousand Coloeri, or religious persons,
so called, he did not so much as find there, no, nor in all Greece,
one man acquainted with the conversation of those parts;
for though they had several manuscripts of divinity in their libraries,
yet not one poet or historian;
for the rulers of that church were such enemies to that sort of learing,
that they anathematized all such priests and religious persons,
as should read or transcribe any books but what treated of religion:
and persuaded all others, that it was not lawful for a Christian to study poesy,
etc. though nothing is more grateful in these days.
Zeno was of the same opinion against poetry.^
footnote:[Pet. Bell. obser. l. 1, c. 35; ibid. c. 40, cap. 39.]

[.numbered]
XVIII. The Waldenses^
footnote:[XII. Cap. Hist. de orig. Walden. Vignia Hist. Bibl. p. 130. Dubran Hist.
Bohem. 14. Thuan. in Hist. sui. temp. p. 458. Mat. Paris Hist. of Eng. Angl. 1174;
Bellar. tom. 2, lib. 1, cap. 26, co. 86. Ecchius. com. loc. c. 28. Apl. l. 6. con.
Hieret. p. 99.]
were a people so called from one Peter Waldo, a citizen of Lyons in France,
in the year 1160, who inhabited Piedmont, elsewhere called Albigenses, from Albi,
a city of Languedoc in France; Lollards in England, from one Reynard Lollard,
who some time after came into these parts, and preached boldly against the idolatries,
superstitions, and vain conversation of the inhabitants of this island.
They had many other names, as Arnoldists, Esperonists, Henricians, Siccars, Insabaches,
Paterenians, Turlupins, Lyonists, Fraticelli, Hussites,
Bohemians (still the same;) but finally, by their enemies, damnable heretics,
though by the Protestants, the true church of Christ.
And to omit many testimonies, I will instance only in Bishop Usher,
who in his discourse of the succession of the Christian church,
defends them not only as true reformers,
but makes the succession of the Protestant church
to be mainly evincible from their antiquity.
I shall forbear all the circumstances and principles they held,
or in which he strongly defends them against the cruelty and ignorance of their adversaries,
particularly Rainerius, Rubis, Capetaneis,
etc. only what they held concerning our present subject of apparel and recreations,
I cannot be so injurious to the truth, their self-denial, the good of others,
at whose reformation I aim, and my own discourse, as to omit it.
And therefore I shall proceed to allege their faith and practice in these matters,
however esteemed but of a trifling importance, by the loose, wanton,
and carnal-minded of this generation,
whose feeling is lost by the enjoyment of their inordinate desires,
and that think it a high state of Christianity to
be no better than the beasts that perish,
namely, in not being excessive in Newgate and mere kennel enormities.
That these ancient reformers had another sense of these things,
and that they made the conversation of the gospel of a crucified
Jesus to intend and require another sort of life,
than what is used by almost all those who account themselves members of his church,
I shall show out of their own doctrines, as found in their most authentic histories.

[.numbered]
XIX. To be brief, in their exposition upon the Lord`'s prayer,
that part of it which speaks thus, "`Give us this day our daily bread:`"^
footnote:[Jo. Paul. Per. Hist. Wald. l. 1. in p. 37, 38. Dona nos le nostre pan quotidian.
en choi. Memor. Morrel. Vign. Mem. f. 7.]
where, next to that spiritual bread,
which they make it to be the duty of all to seek more than life,
they come positively to deny the praying for more than is requisite for outward necessities,
or that it is lawful to use more; condemning all superfluity and excess, out of fashion,
pride, or wantonness, not only of bread, but all outward things,
which they judge to be thereby comprehended; using Ezekiel`'s words,^
footnote:[Thesaur. fed. Ap. Wald.]^
footnote:[Ezek. 16:45,] that fulness of bread,
and abundance of idleness were the cause of the wickedness and the abominations of Sodom,
for which God by fire destroyed them off the earth.
Whereupon they conclude with an ancient father of the primitive church,
after this manner, that costly apparel, superfluity in diet,
as three dishes when one will serve, play, idleness, and sleep, fatten the body,
nourish luxury, weaken the spirit, and lead the soul unto death; "`But,`" say they,
"`a spare diet, labour, short sleep, plain and mean garments, help to purify the soul,
tame the body, mortify the lusts of the flesh, and comfort the spirit.`"
So severe were they, that, in the chapter of the instructions of their children,^
footnote:[Thesaur. fed. Ap. Wald. l. 2, c. 3. Lifill. sign.
nassion ali patrons carnals de non esser rendus, etc.]
they would not suffer them to converse with those of strange places or principles,
whose conversation was gaming, plays, and the like wanton recreations;
but especially concerning young women.
"`A man,`" say they, "`must have a great care of his daughter.
Hast thou daughters?
Keep them within to wholesome things; see they wander not; for Dinah, Jacob`'s daughter,
was corrupted by being seen of strangers.`"
They affirm no better to be the general event of such conversation.

To which I shall add their judgment and practice concerning taverns,^
footnote:[Ibid. l. 2, c. 3.]
public houses for treats and pleasures, with which the land swarms in our days.

[.numbered]
XX. "`A tavern is the fountain of sin,^
footnote:[La taverna de maisons de pleisirs es fontana de pecca e schola del diavolo, etc.]
the school of the devil; it works wonders fitting the place.
It is the custom of God to show his power in his church, and to work miracles;
that is to say, to give sight to the spiritually blind, to make the lame to leap,
the dumb to sing, the deaf to hear:
but the devil doth quite contrary to all these in taverns,
and the like places of pleasure.
For when the drunkard goes to the tavern, he goes upright: but when he comes forth,
he cannot go at all; he has lost his sight, speech, and hearing too.`"
"`The lectures that are read in this school of the devil,`" say these poor Waldenses,
and first reformers, "`are gluttonies, oaths, perjuries, lyings, blasphemies, flatteries,
and divers other wicked villanies and pernicious effects,
by which the heart is withdrawn further and further from God.`"
And, as the book of Ecclesiasticus saith, the taverner shall not be freed from sin.

But above other recreations, do but seriously observe,
of what danger and ill consequence these first reformers thought dancing, music,
and the like pastimes to be, which are the greatest divertisements of the times, viz.:

[.numbered]
XXI. "`Dancing is the devil`'s procession,^
footnote:[La bal es la proces.
del diavol, e qui intra en la bal, etc.]
and he that entereth into a dance entereth into his procession, the devil is the guide,
the middle, and the end of the dance; as many paces as man maketh in dancing,
so many paces doth he make to go to hell.^
footnote:[Sp. Alm. fol. 50-54.]
A man sinneth in dancing divers ways, for all his steps are numbered, in his touch,
in his ornaments, in his hearing, sight, speech, and other vanities.
And therefore we will prove, first by the Scripture,
and afterwards by divers other reasons, how wicked a thing it is to dance.
The first testimony that we will produce is that which we read in the gospel,
where it is said, it pleased Herod so well, that it cost John Baptist his life.^
footnote:[Mark 6:22-28; Exodus 32:4-7, 19.]
The second is in Exodus, when Moses, coming near to the congregation, saw the calf,
he cast the tables from him, and broke them at the foot of the mountain;
and afterwards it cost three thousand of their lives.
Besides, the ornaments which women wear in their dances,
are as crowns for many victories which the devil hath got against the children of God:
for the devil hath not only one sword in the dance,
but as many as there are beautiful and well-adorned persons in the dance;
for the words of a woman are a glittering sword.
And therefore that place is much to be feared wherein the enemy hath so many swords,
since that only one sword of his may be justly feared.
Again, the devil in this place strikes with a sharpened sword; for women,
who make it acceptable, come not willingly to the dance,
if they be not painted and adorned;
which painting and ornament is as a whetstone on which the devil
sharpeneth his sword.--They that deck and adorn their daughters,
are like those that put dry wood to the fire, to the end it may burn the better:
for such women kindle the fire of luxury in the hearts of men.
As Sampson`'s foxes fired the Philistines`' corn, so these women,
they have fire in their faces, and in their gestures and actions,
their glances and wanton words, by which they consume the goods of men.`"
They proceed, "`The devil in the dance useth the strongest armour that he hath:
for his most powerful arms are women; which is made plain unto us,
in that the devil made choice of the woman to deceive the first man; so did Balaam,
that the children of Israel might be rejected of God.
By a woman he made Sampson, David, and Absalom to sin.
The devil tempteth men by women three manner of ways; that is, by the touch, by the eye,
by the ear; by these three means he tempteth foolish men to dancing,
by touching their hands, beholding their beauty, hearing their songs and music.`"--Again,
"`They that dance break that promise and agreement they have made with God in baptism,
when their godfathers promise for them,
that they shall renounce the devil and all his pomp;
for dancing is the pomp of the devil; and he that danceth maintaineth his pomp,
and singeth his mass.
For the woman that singeth in the dance is the prioress, or chief of the devil,
and those that answer are the clerks, and the beholders are the parishioners,
and the music are the bells, and the fiddlers the ministers of the devil.
For, as when hogs are strayed, if the hogherd call one, all assemble themselves together;
so the devil causeth one woman to sing in the dance, or to play on some instrument,
and presently gather all the dancers together.`"--Again, "`In a dance,
a man breaks the ten commandments of God: as first, Thou shalt have no other God but me,
etc., for in dancing, a man serves that person whom he most desires to serve,
after whom goes his heart; and therefore Jerome saith,
'`Every man`'s god is that he serves and loves best;`'^
footnote:[Jerom. in dec. int. oper.]
and that he loves best which his thoughts wander and gad most after.
He sins against the second commandment when he makes an idol of that he loves.
Against the third, in that oaths, and frivolously using God`'s name,
are frequently among dancers.
Against the fourth, for that by dancing the sabbath-day is profaned.
Against the fifth, for in the dance parents are many times dishonoured,
since thereby many bargains are made without their counsel.
Against the sixth, a man kills in dancing,
for every one that sets about to please another,
he kills the soul as oft as he persuades unto lust.
Against the seventh, for the party that danceth, be it male or female,
committeth adultery with the party they lust after;
for he that looketh on a woman to lust after her,
hath already committed adultery with her in his heart.
Against the eighth,
a man sins in dancing when he withdraweth the heart of another from God.
Against the ninth, when in dancing he speaks falsely against the truth,
and for some little honour, or secret lascivious end, denies what is true,
or affirms what is false.
Against the tenth, when women affect the ornaments of others, and men covet the wives,
daughters, and servants of their neighbours,
which undeniably attends all such plays and sports.`"--Again,
"`A man may prove how great an evil dancing is,
by the multitude of sins that accompany those that dance;
for they dance without measure or number;`" "`And therefore,`" saith Augustine,^
footnote:[August. de Civit. Dei.]
"`the miserable dancer knows not, that as many paces as he makes in dancing,
so many leaps he makes to hell.
They sin in their ornaments after a five-fold manner: First, by being proud thereof.
Secondly, by inflaming the hearts of those that behold them.
Thirdly, when they make those ashamed that have not the like ornaments,
giving them occasion to covet the like.
Fourthly, by making women importunate in demanding the like ornaments of their husbands:
and, Fifthly, when they cannot obtain them of their husbands,
they seek to get them elsewhere by sin.
They sin by singing and playing on instruments;
for their songs bewitch the hearts of those that hear them with temporal delight,
forgetting God; uttering nothing in their songs but lies and vanities;
and the very motion of the body which is used in dancing,
gives testimony enough of evil.--Thus, you see that dancing is the devil`'s procession,
and he that enters into a dance, enters into the devil`'s procession.
Of dancing, the devil is the guide, the middle, and the end;
and he that entereth a good and wise man into the dance,
if it can be that such an one is either good or wise,
cometh forth a corrupt and wicked man: Sarah, that holy woman, was none of these.`"^
footnote:[August. l. 2.]
Behold the apprehensions of those good old reformers,
touching those things that are so much in practice and reputation in these times,
with such as profess their religion: thus far verbatim.
But I cannot leave off here,
till I have yet added the conclusion of their catechism and direction,
and some passages out of one of their pastor`'s letters, fit to the present occasion.

They conclude with this direction, namely, how to rule their bodies,^
footnote:[Concl. p. 68. Encaren qual manier fidel debian regir li ler Corps:
non servali desirier mort. etc.]
and live in this world as becomes the children of God.
Not to serve the mortal desires of the flesh.
To keep their members, that they be not arms of iniquity and vanity.
To rule their outward senses.
To subject the body to the soul.
To mortify their members.
To fly idleness.
To observe a sobriety and measure in eating and drinking,
in their words and cares of this life.
To do works of mercy.
To live a moral or just life by faith.
To fight against the desires.
To mortify the works of the flesh.
To give themselves to the exercise of religion.
To confer together touching the will of God: to examine diligently the conscience.
To purge and amend, and pacify the spirit.

To which I add the epistle of one of their pastors,
as I find it recorded amongst other matters relating to these poor afflicted people.

[.numbered]
XXII. An epistle of pastor Bartholomew Tertian,
written to the Waldensian churches of the valley of Pragela, thus translated:

====

[.embedded-content-document.epistle]
--

[.salutation]
Jesus be with you.

To all our faithful and well beloved brethren in Christ Jesus,^
footnote:[Hist. Wald. l. 4, c. 11, p. 55-57.]
health and salvation be with you all: Amen!
These are to put you in remembrance, and to admonish you, my brethren,
hereby acquitting myself of that duty which I owe unto you all, in the behalf of God,
principally touching the care of your souls`' salvation,
according to that light of the truth, which the most high God hath bestowed on us,
that it would please every one of you to maintain, increase, and nourish,
to the utmost of your power, without diminution,
those good beginnings and examples which have been left unto us by our forefathers,
whereof we are no ways worthy.
For it would little profit us to have been renewed by the fatherly visitation,
and the light which hath been given us of God, if we give ourselves to worldly,
carnal conversations, which are diabolical; abandoning the principle which is of God,
and the salvation of our souls, for this short and temporal life.
For the Lord saith, '`What doth it profit a man to gain the whole world,
and to lose his own soul?`' For it would be better
for us never to have known the way of righteousness,
than having known it, to do the contrary.
Let me therefore entreat you, by the love of God, that you decrease not, or look back;
but rather increase the charity, fear, and obedience, which is due unto God,
and to yourselves, amongst yourselves; and stand fast in all these good principles,
which you have heard and understood of God, by our means:
and that you would remove from amongst you all vain conversation and evil surmises,
troubling the peace, the love, the concord,
and whatsoever would indispose or deaden your minds to the service of God,
your own salvation, and the administration of the truth,
if you desire that God should be merciful to you in your goods temporal and spiritual:
for you can do nothing without Him; and if you desire to be heirs of his glory,
do that which He commandeth: If you would enter into life, keep my commandments.^
footnote:[Matt. 19:17.]

Likewise be careful that there be not nourished among you any sports, gluttony, whoredom,
dancings, nor any lewdness, nor riot, nor questions, nor deceits, nor usury,
nor discords; nor support nor entertain any persons of a wicked conversation,
or that give any scandal or ill example amongst you;
but let charity and fidelity reign amongst you, and all good example;
doing to one another as every one desires should be done unto him;
for otherwise it is impossible that any should be saved, or can have the grace of God,
or be good men in this world, or have glory in another.
And therefore, if you hope and desire to possess eternal life,
to live in esteem and credit, and to prosper in this world,
in your goods temporal and spiritual, purge yourselves from all disorderly ways,
to the end that God may be always with you, who forsakes not those that trust in him.
But know this for certain, that God heareth not, nor dwelleth with sinners,
nor in the soul that is given unto wickedness, nor in the man that is subject to sin.
And therefore let every one cleanse the ways of his heart, and fly the danger,
if he would not perish therein.
I have no other things at this present, but that you would put in practice these things;
and the God of peace be with you all, and go along with us,
and be present among us in our sincere, humble, and fervent prayers,
and that He will be pleased to save all those his faithful, that trust in Christ Jesus.

Entirely yours, ready to do you service in all things possible,
according to the will of God.

[.signed-section-signature]
Bartholomew Tertian.

--

[.numbered-group]
====

[.numbered]
XXIII.
Behold the life and doctrine, instruction and practice, of the ancient Waldenses.^
footnote:[Bern de Gir lora. de Hail. Hist. de la Fr. 1. 10. Vesemb. Orat.
in Wald. Beza Hist. hom. dig. virer de ver. et fals. Rel. 1. 4, c. 13, p. 249, Cat.
Test. ve. 334, Vigin, Bibl. Hist. p. 1.]
How harmless, how plain, how laborious,
how exceeding serious and heavenly in their conversations!
These were the men, women, aye children too, who, for above five hundred years,
have valiantly, but passively maintained a cruel war,
at the expense of their own innocent blood,
against the unheard of cruelties and severities of several princes, nuncios, and bishops;
but above all, of certain cruel inquisitors, of whom their historians report,
that they held it was a greater evil to conceal a heretic than to be guilty of perjury;
and for a clergyman to marry a wife than to keep a whore.
In short, to dissent, though never so conscientiously, was worse than open immorality.
It was against the like adversaries these poor Waldenses fought,
by sufferings throughout the nations, by prisons, confiscations, banishments,^
footnote:[Vieaux Mem. fol. 6, 7.]
wandering from hill to valley, from den to cave; being mocked, whipped, racked,
thrown from rocks and towers, driven on mountains,^
footnote:[Mut. Par. in Hen. 3, Anno, 1220. Sigonius de Reg. Ital. 1, 7.]
and in one night thousands perished by excessive frost and snow, smothered in caves,
starved, imprisoned, ripped up, hanged, dismembered, rifled, plundered, strangled,
broiled, roasted, burned; and whatsoever could be invented to ruin men, women,
and children.
These Waldenses, you Protestants pretend to be your ancestors: from them, you say,
you have your religion; and often, like the Jews of the prophets,
are you building their praises in your discourses: but, O look back, I beseech you,
how unlike are you to these afflicted pilgrims!
What resemblance is there of their life in yours?
Did they help to purchase and preserve you a liberty and religion, can you think,
at the loss of all that was dear to them,
that you might pass away your days and years in pride, wantonness, and vanity?
What proportion bears your excess with their temperance;^
footnote:[Sernay, c. 47, Chef. 1. 3, c. 7.]
your gaudiness with their plainness;
your luxury and flesh-pleasing conversations with their simplicity and self-denial?
But are you not got into that spirit and nature they condemned in their day;
into that carnality and worldly mindedness they reproved in their persecutors, nay,
into a strain of persecution too, which you seem to hide under a cloak of reformation?
How can you hope to refute their persecutors whose worst part perhaps was their cruelty,
that turn persecutors yourselves?
What have you besides their good words, that is like them?
And do you think that words will send off the blows of eternal vengeance?
That a little by-rote babble, though of never so good expressions in themselves,
shall serve your turn at the great day?
No, from God I tell you, that whilst you live in the wantonness, pride,
and luxury of the world, pleasing and fulfilling the lust of the eye,
the lust of the flesh, and the pride of life,^
footnote:[1 John 2:14-17.]
God detests you all, and laughs you and your worship to scorn.
Never tell me, I am too rash; it is the devil that says so;
he has got two scriptures by the end in these days: one,
that there is none that doth good: and why?^
footnote:[The devil is a Scripturian sometimes.]
That he may persuade all it is impossible to overcome him:
which is the reason so many are overcome;
although glory is promised to none but conquerors.
The second, that we must not judge, lest we be judged: that is,
whilst we are guilty of the same things that are equivalent, lest we are judged.
But away with Satan and his hypocrisy too: I know what I say, and from whom I speak:
once more I tell you all, whether you will hear or forbear,
that unless you forsake your pride, luxury, avarice, and the whole variety of vanities,
and diligently mind the eternal light of God in your hearts, to obey it;
wrath will be your portion forever.
Trust not your souls upon misapplied Scriptures; he that is a child of God must be holy,
for God is holy;
and none are his sons and daughters but those who are adopted by the eternal Spirit,
and led thereby.^
footnote:[1 Pet. 1:15-16; Rom. 8:1-16.]
It was a holy, plain, humble, divine life,
these poor suffering Christians both professed and practised,
refusing to converse with such as lived in the superfluities and excess of the world;
for which, if you will believe their very adversaries, they were persecuted:
"`For,`" says Rainerius,^
footnote:[Rain. cap. de stud. pervert. alios et modo dicendi. l. 98. Baron.
Eccl. Annal. tom. 18, an. 1176, p. 835. Kranz. in Metrop. l. 8. sect.
18, and in Sax. l. 8, cap. 16.]
a great writer against them, "`they used to teach, first,
what the disciples of Christ ought to be,
and that none are his disciples but they that imitate his life; and that the popes,
cardinals, etc., because they live in luxury, pride, avarice, etc.,
are not the successors of Christ; but themselves only,
in that they walk up to his commandments; thus,`" says he, "`they win upon the people.`"
But if so, that none are Christians but those that imitate Christ,
what will become of those who call themselves Christians
and yet live at ease in the flesh,
not regarding the work of the holy cross of Christ in their hearts,
that crucifies them that bear it to the world, and the world to them?
This was the true ground of their sufferings,
and their loud cries against the impieties of the greatest; not sparing any ranks,
from the throne to the dunghill, as knowing their God was no respecter of persons.
And now, if you would follow them indeed, if you would be Protestants in substance,
and learn your enemies a way worth their changing for--else better words
go but a little way--if you would obtain the heavenly inheritance,
and you would be eternally blessed,
be ye persuaded to forsake all the pride and pomp of this vain world.
O mind the concerns of an everlasting rest!
Let the just and serious principle of God within
you be the constant guide and companion of your minds,
and let your whole hearts be exercised thereby,
that you may experience an entire reformation and change of affections,
through the power of that divine leaven which leavens the whole lump, viz. body, soul,
and spirit, where it is received; to which, and its work in man,
our blessed Lord likened the kingdom of God which He came to set up in the soul:
that so having the joys and glory of another world in your view,
you may give your best diligence to make your calling
and election to the possession of them sure and certain;
lest, selling that noble inheritance for a poor mess of perishing pottage,
you never enter into his eternal rest.
And though this testimony may seem too tedious,
yet could it by no means be omitted.--To authorize our last reason,
of converting superfluities into the relief of distressed persons,
although one would think it so equal and sober,
that it needs no other authority than its own,
yet I shall produce two testimonies so remarkable,
that as they ever were esteemed truly good,
so they cannot be approved by any that refuse to do the same,
without condemning themselves of great iniquity.
Oh, you are called with an high and holy call; as high as heaven, and as holy as God;
for it is He that calls us to holiness through Christ, who sent his Son to bless us,
in turning us from the evil of our ways;
and unless we are so turned we can have no claim
to the blessing that comes by Christ to men.

[.numbered]
XXIV.
It is reported of Paulinus,^
footnote:[Eccl. Hist. p. 5, 393.]
bishop of Nola in Italy, that,
instead of converting the demesnes of his diocese to particular enrichment,
he employed it all in the redemption of poor slaves and prisoners:
believing it unworthy of the Christian faith,
to see God`'s creation labour under the want of what he had to spare.
All agree this was well done, but few agree to do the same.

[.numbered]
XXV.
But more particularly that of Acacius,^
footnote:[Socrat. Scholast.]
bishop of Amida, given us by Socrates Scholasticus, in this manner:
"`When the Roman soldiers purposed in nowise to restore again unto the
king of Persia such captives as they had taken at the winning of Azazena,
being about seven thousand in number, to the great grief of the king of Persia,
and all of them ready to starve for want of food: Acacius lamented their condition,
and calling his clergy together, said thus unto them,
'`Our God hath no need of dishes or of cups, for He neither eateth nor drinketh;
these are not his necessaries; wherefore, seeing the church hath many precious jewels,
both of gold and silver, bestowed of the free-will and liberality of the faithful,
it is requisite that the captive soldiers should be therewith redeemed,
and delivered out of prison and bondage,
and they perishing with famine should therewith be refreshed and relieved.`'`"
Thus he prevailed to have them all converted into money;
some for their immediate refreshment, some for their redemption,
and the rest for coastage or provision, to defray the charges of their voyage.
Which noble act had such an universal influence,
that it more famed the Christian religion among the Infidels,
than all their disputes and battles: insomuch that the King of Persia, a Heathen, said,
"`The Romans endeavour to win their adversaries both by
wars and favours;`" and greatly desired to behold that man,
whose religion taught so much charity to enemies; which, it is reported, Theodosius,
the emperor, commanded Acacius to gratify him in.
And if the Apostle Paul`'s expression hath any force,
that "`He is worse than an infidel who provides not for his family;`"^
footnote:[1 Tim. 5.]
how greatly doth his example aggravate your shame,
that can behold such pity and compassion expressed to strangers, nay, enemies,
and those infidels too, and be so negligent of your own family; (for England, aye,
Christendom, in a sense, if not the world,
is no more;) as not only to see their great necessities unanswered,
but that wherewith they should be satisfied, converted to gratify the lust of the eye,
the lust of the flesh, and the pride of life?
But however such can please themselves,
in the deceitful daubing of their mercenary priests,
and dream they are members of Jesus Christ,
it is certain that things were otherwise in the beginning; for then all was sold,
and put into a common purse, to supply indigences:^
footnote:[Acts 4:32-37.]
not mattering earthly inheritances, further than as they might, in some sense,
be subservient to the great end for which they were given; namely,
the good of the creation.
Thus had the purest Christians their minds and thoughts taken up with the better things,
and raised with the assurance of a more excellent life and inheritance in the heavens,
that will never pass away.
And for any to flatter themselves with being Christians,
whilst so much exercised in the vanities, recreations, and customs of the world,
as at this very day we see they are, is to mock the great God,
and abuse their immortal souls.
The Christian life is quite another thing.

And lest that any should object,
many do great and seemingly good actions to raise their reputation only;
and others only decry pleasure, because they have not wherewithal,
or know not how to take it;
I shall present them with the serious sayings of aged and dying men,
and those of the greatest note and rank,
whose experience could not be wanting to give the truest account, how much their honours,
riches, pleasures, and recreations, conduced to their satisfaction,
upon a just reckoning, as well before their extreme moments as upon their dying beds,
when death, that hard passage into eternity, looked them in the face.

====
