== Chapter XXI.

=== Serious dying, as well as living testimonies of Men of Fame and Learning, viz.

[.chapter-synopsis]
* 1+++.+++ Solomon.
* 2+++.+++ Chilon.
* 3+++.+++ Ignatius.
* 4+++.+++ Justin Martyr.
* 5+++.+++ Chrysostom.
* 6+++.+++ Charles V.
* 7+++.+++ Michael de Montaigne.
* 8+++.+++ Cardinal Wolsey.
* 9+++.+++ Sir Philip Sidney.
* 10+++.+++ Secretary Walsingham.
* 11+++.+++ Sir John Mason.
* 12+++.+++ Sir Walter Raleigh.
* 13+++.+++ H. Wotton.
* 14+++.+++ Sir Christopher Hatton.
* 15+++.+++ Lord Chancellor Bacon.
* 16+++.+++ The great Duke of Montmorency.
* 17+++.+++ Henry Prince of Wales.
* 18+++.+++ Philip III. King of Spain.
* 19+++.+++ Count Gondamor.
* 20+++.+++ Cardinal Richlieu.
* 21+++.+++ Cardinal Mazarine.
* 22+++.+++ Chancellor Oxenstiern.
* 23+++.+++ Dr. Donne.
* 24+++.+++ Jo. Selden.
* 25+++.+++ H. Grotius.
* 26+++.+++ P. Salmasius.
* 27+++.+++ Fran. Junius.
* 28+++.+++ A. Rivetus.
* 29+++.+++ The late Earl of Marlborough.
* 30+++.+++ Sir Henry Vane.
* 31+++.+++ Abraham Crowley.
* 32+++.+++ Late Earl of Rochester.
* 33+++.+++ One of the family of Howard.
* 34+++.+++ Princess Elizabeth of the Rhine.
* 35+++.+++ Commissioner Whitlock.
* 36+++.+++ A Sister of the family of Penn.
* 37+++.+++ My own Father.
* 38+++.+++ Anthony Lowther of Mask.
* 39+++.+++ Seigneur du Renti.

[.numbered-group]
====

[.numbered]
I+++.+++ Solomon,
than whom none is believed to have more delighted himself in the enjoyments of the world,
at least better to have understood them; hear what he says, after all his experience:
"`I said in my heart, Go to now, I will prove thee with mirth, therefore enjoy pleasure:
and behold, this also is vanity.
I said of laughter, it is mad: and of mirth, what doth it?
I made me great works, builded houses, planted vineyards, made gardens and orchards,
planted trees in them of all kinds of fruit: I got me servants and maidens,
also great possessions: I gathered me silver and gold,
and the peculiar treasure of kings and provinces; also men and women, singers,
and the delights of the sons of men, as musical instruments, and that of all sorts.
So I was great, and increased more than all that were before me in Jerusalem,
and whatsoever mine eyes desired, I kept not from them:
I withheld not mine heart from any joy.
Then I looked on the works which mine hands had wrought, and behold,
all was vanity and vexation of spirit.`"
The reason he gives in the 18th and 19th verses is,
that the time of enjoying them was very short,
and it was uncertain who should be benefited by them when he was gone.
Wherefore, he concludes with all this: "`Fear God, and keep his commandments,
for this is the whole duty of man: for God shall bring every work into judgment,
whether it be good, or whether it be evil.`"
O that men would lay this to heart!

[.numbered]
II. Chilon,^
footnote:[Severus Apop. p. 175.]
one of the seven wise men of Greece, already mentioned upon another occasion,
affords us a dying testimony of great example.
It is related thus by A. Gellius: when his life drew towards an end,
ready to be seized by death, he spoke thus to his friends about him:
"`My words and actions, in this long term of years, have been, almost all,
such as I need not repent of; which, perhaps, you also know: truly,
even at this time I am certain I never committed anything
the remembrance of which begets any trouble in me,
unless this one thing only: which, whether it were done amiss or not, I am uncertain.
I sat with two others as judge, upon the life of my friend: the law was such,
as the person must of necessity be condemned,
so that either my friend must lose his life, or some deceit be used towards the law.
Revolving many things in my mind, for relief of a condition so desperate,
I conceived that which I put in practice to be of all others the most easy to be borne:
silently I condemned him, and persuaded those others who judged, to absolve him:
thus I preserved in so great a business, the duty both of a judge and a friend.
But from that act I received this trouble:
that I fear it is not free from perfidiousness and guilt, in the same business,
at the same time, and in a public affair,
to persuade others contrary to what was in my own judgment best.`"
Oh, tender conscience!
Yet an Heathen`'s. Where dwells the Christian that excelleth?
Hard to be found among the great rabbies of Christendom.

[.numbered]
III.
Ignatius,^
footnote:[Ignatius Epist. ad Ephes. Mag. Trall. Eus. 1. iii. c. 32, Rom.]
who lived within the first hundred years after Christ, left this, amongst other things,
behind him, who was torn in pieces of wild beasts at Rome, for his true faith in Jesus,
"`There is nothing better than the peace of a good conscience;`"
intimating there might be a peace to wicked consciences,
that are past feeling anything to be evil,
but swallowed up of the wickedness of the world.
And in his epistles to the churches at Ephesus, Magnesia, Trallis, and Rome,
upon his martyrdom, saith, "`Now I begin to be a disciple,
I weigh neither visible nor invisible things, so that I may gain Christ.`"
Oh, heavenly-minded man!
A blessed martyr of Jesus indeed.

[.numbered]
IV. Justin Martyr,
a philosopher who received Christianity five-and-twenty years after the death of Ignatius,
plainly tells us, in his relation of his conversion to the Christian faith,
that the power of godliness in a plain, simple Christian,
had that influence and operation on his soul,
that he could not but betake himself to a serious and strict life; and yet, before,
he was a Cynic, a strict sect: and this gave him joy at his martyrdom,
having spent his days as a serious teacher, and a good example.
And Eusebius relates, that, though he was also a follower of Plato`'s doctrine,^
footnote:[Euseb. Eccl. Hist. 1. 4, c. 8.]
yet when he saw the Christians`' piety and courage, he concluded, no people so temperate,
less voluptuous, and more set on divine things:
which first induced him to be a Christian.

[.numbered]
V+++.+++ Chrysostom, another father, so called, lays this down for necessary doctrine,
"`To sacrifice the whole soul and body to the Lord,
is the highest service we can pay unto Him.
God promiseth mercy unto penitent sinners;
but He doth not promise them they shall have so much time as tomorrow for their repentance.`"

[.numbered]
VI. Charles V. Emperor of Germany, King of Spain, and Lord of the Netherlands,
after three-and-twenty pitched fields, six triumphs, four kingdoms conquered,
and eight principalities added to his dominions,
a greater instance than whom can scarce be given,
resigned up all his pomp to other hands, and betook himself to his retirement;
leaving this testimony behind him,
concerning the life he spent in the honours and pleasures of the world,
and in that little time of his retreat from them all: that the sincere study, profession,
and practice of the Christian religion,
had in it such joys and sweetness as courts were strangers to.

[.numbered]
VII.
Michael De Montaigne, a lord of France,
famous with men of letters for his book of Essays, giveth these instructions to others,
and this character of himself, viz. "`Amidst our banquets, feasts, and pleasures,
let us have ever this restraint or object of Death before us; that is,
the remembrance of our condition: And let not pleasure so much mislead or transport us,
that we altogether neglect or forget how many ways our joys, or our feastings,
be subject unto Death, and by how many holdfasts she threateneth us and you.
So did the Egyptians, who in the midst of their banquetings,
and in the full of their greatest cheer,
caused the Anatomy of a Dead Man to be brought before them,
as a memorandum and warning to their guests.
I am now, by means of the mercy of God, in such a taking,
that without regret or grieving at any worldly matter, I am prepared to dislodge,
whensoever he shall please to call me.
I am everywhere free: My farewell is soon taken of all my friends, except of myself.
No man did ever prepare himself to quit the world more simply and fully,
or more generally lay aside all thoughts of it, than I am fully assured I shall do.
All the glory I pretend in my life, is, that I have lived Quietly: Quietly,
not according to Metrodorus, Arcesilaus, or Aristippus; but according to Myself.
Since philosophy could never find any way for tranquillity,
that might be generally good;`" "`Let every man in his own particular seek for it.`"
Let us not propose so fleeting and so wavering an end unto ourselves,
as the World`'s Glory: Let us constantly follow reason:
And let the Vulgar Approbation follow us that way, if it please.
I care not so much what I am with others, as I respect what I am in myself:
I will be rich in myself, and not by borrowing.
Strangers see but external appearances and events:
Every man can set a good face upon the matter, when within he is full of care,
grief and infirmities: They see not my heart, when they look upon my outward countenance.
We are nought but ceremony; Ceremony doth trans port us,
and we leave the Substance of things: we hold fast by the boughs,
and leave the trunk or body, the Substance of things, behind us.`"

[.numbered]
VIII.
Cardinal Wolsey, the most absolute and wealthy minister of state this kingdom ever had,
that in his time seemed to govern Europe as well as England,
when come to the period of his life,
left the world with this close reflection upon himself:
"`Had I been as diligent to serve my God, as I was to please my king,
He would not have left me now in my grey hairs.`"
A dismal reflection for all worldly-minded men; but those more especially,
who have the power and means of doing more good than ordinary in the world,
and do it not; which seems to have been the case and reflection of this great man.

[.numbered]
IX. Sir Philip Sidney, a subject indeed of England, but they say chosen king of Poland,
whom Queen Elizabeth called her Philip; the Prince of Orange, his master;
whose friendship the lord Brooks was so proud of,
that he would have it part of his epitaph,
"`Here lies Sir Philip Sidney`'s friend;`" whose death was
lamented in verse by the then kings of France and Scotland,
and the two universities of England;
repented so much at his death of that witty vanity of his life, his Arcadia, that,
to prevent the unlawful kindling of heats in others,
he would have committed it to the flames himself:
and left this farewell amongst his friends, "`Love my memory, cherish my friends;
their faith to me may assure you that they are honest;
but above all govern your wills and affections by the will and word of your Creator.
In me behold the end of this world, and all its vanities.`"
And indeed he was not much out in saying so,
since in him was to be seen the end of all natural parts, acquired learning,
and civil accomplishments.
His farewell seems spoken without terror, with a clear sense, and an equal judgment.

[.numbered]
X+++.+++ Secretary Walsingham, an extraordinary man in Queen Elizabeth`'s time,
towards the conclusion of his days, in a letter to his fellow-secretary Burleigh,
then lord-treasurer of England, writes thus: "`We have lived enough to our country,
our fortunes, our sovereign: it is high time we begin to live to ourselves,
and to our God.`"
Which, giving occasion for some court-droll to visit and try to divert him:
"`Ah!`" said he, "`while we laugh, all things are serious round about us; God is serious,
when He preserveth us, and hath patience towards us;
Christ is serious when He dieth for us; the Holy Ghost is serious,
when He striveth with us; the whole creation is serious, in serving God and us;
they are serious in hell and in heaven: and shall a man, that has one foot in the grave,
jest and laugh?`"
O that our statesmen would weigh the conviction, advice,
and conclusion of this great man, and the greatest man, perhaps,
that has borne that character in our nation!
For true it is, that none can be serious too soon, because none can be good too soon.
Away, then, with all foolish talking and jesting,
and let people mind more profitable things.

[.numbered]
XI. John Mason, knight, who had been privy-counsellor to four princes,
and spent much time in the preferments and pleasures of the world,
retired with these pathetical and regretful sayings: "`After so many years`' experience,
seriousness is the greatest wisdom; temperance the best physic;
a good conscience is the best estate.
And were I to live again, I would change the court for a cloister,
my privy-counsellor`'s bustles for a hermit`'s retirement,
and the whole life I lived in the palace, for one hour`'s enjoyment of God in the chapel.
All things else forsake me, besides my God, my duty, and my prayers.`"

[.numbered]
XII.
Sir Walter Raleigh is an eminent instance, being as extraordinary a man,
as our nation hath produced; in his person well descended; of health, strength,
and a masculine beauty; in understanding quick: in judgment sound; learned and wise,
valiant and skilful; a historian, a philosopher, a general, a statesman.
After a long life, full of experience, he drops these excellent sayings,
a little before his death, to his son, to his wife, and to the world, viz.:
"`Exceed not in the humour of rags and bravery, for these will soon wear out of fashion:
and no man is esteemed for gay garments but by fools and women.
On the other side, seek not riches basely, nor attain them by evil means:
destroy no man for his wealth, nor take anything from the poor;
for the cry thereof will pierce the heavens: and it is most detestable before God,
and most dishonourable before worthy men,
to wrest anything from the needy and labouring soul: God will never prosper thee,
if thou offendest therein; but use thy poor neighbours and tenants well.`"
A most worthy saying.
But he adds, "`Have compassion on the poor and afflicted, and God will bless thee for it:
make not the hungry soul sorrowful; for if he curse thee in the bitterness of his soul,
his prayer shall be heard of Him that made him.
Now, for the world, dear child,
I know it too well to persuade thee to dive into the practices of it;
rather stand upon thy own guard against all those that tempt thee to it,
or may practise upon thee; whether in thy conscience, thy reputation, or thy estate:
resolve, that no man is wise or safe but he that is honest.
Serve God; let Him be the Author of all thy actions: commend all thy endeavours to Him,
who most either wither or prosper them: please Him with prayer; lest if He frown,
He confound all thy fortune and labour, like the drops of rain upon the sandy ground.
Let my experienced advice and fatherly instructions sink deep into thy heart:
so God direct thee in all thy ways, and fill thy heart with his grace.`"

====

[.embedded-content-document.letter]
--

[.letter-heading]
Sir Walter Raleigh`'s Letter to his Wife, after his Condemnation.

You shall receive, my dear wife, my last words, in these my last lines.
My love I send you, that you may keep when I am dead; and my counsel,
that you may remember it when I am no more.
I would not, with my will, present you sorrows, dear Bess;
let them go to the grave with me, and be buried in the dust: and,
seeing that it is not the will of God that I shall see you any more,
bear my destruction patiently, and with a heart like yourself.
First, I send you all the thanks which my heart can conceive, or my words express,
for your many travails and cares for me; which,
though they have not taken effect as you wished, yet my debt to you is not the less;
but pay it I never shall in this world.
Secondly, I beseech you, for the love you bear me living,
that you do not hide yourself many days;
but by your travails seek to help my miserable fortunes,
and the right of your poor child: your mourning cannot avail me, who am but dust.
Thirdly, you shall understand, that my lands were conveyed, bona fide, to my child;
the writings were drawn at Midsummer was at twelvemonth, as divers can witness:
and I trust my blood will quench their malice who desired my slaughter,
that they will not seek to kill you and yours with extreme poverty.
To what friend to direct you, I know not, for all mine have left me,
in the true time of trial: most sorry am I, that, being surprised by death,
I can leave you no better estate: God hath prevented all my determinations,
that great God, which worketh all in all.
If you can live free from want, care for no more, for the rest is but a vanity.
Love God, and begin betimes; in Him shall you find true, everlasting,
and endless comfort:
when you have travailed and wearied yourself with all sorts of worldly cogitations,
shall you sit down by sorrow in the end.
Teach your son also to serve and fear God, whilst he is young,
that the fear of God may grow up in him; then will God be a husband to you,
and a father to him; a husband and a father that can never be taken from you.
Dear wife, I beseech you, for my soul`'s sake, pay all poor men.
When I am dead, no doubt but you will be much sought unto,
for the world thinks I was very rich.
Have a care of the fair pretences of men;
for no greater misery can befal you in this life, than to become a prey unto the world,
and afterwards to be despised.
As for me, I am no more yours, nor you mine: death has cut us asunder,
and God hath divided me from the world, and you from me.
Remember your poor child, for his father`'s sake, who loved you in his happiest estate.
I sued for my life, but God knows, it was for you and yours that I desired it:
for know it, my dear wife, your child is the child of a true man,
who in his own respect despiseth death, and his misshapen and ugly forms.
I cannot write much.
God knows how hardly I steal this time, when all are asleep,
and it is also time for me to separate my thoughts from the world.
Beg my dead body, which living was denied you; and either lay it in Sherborne,
or in Exeter church, by my father and mother.
I can say no more; time and death call me away.
The everlasting God, powerful, infinite, and inscrutable, God Almighty,
who is goodness itself, the true light and life, keep you and yours,
and have mercy upon me, and forgive my persecutors, and false accusers;
and send us to meet in his glorious kingdom.
My dear wife, farewell; bless my boy; pray for me;
and let my true God hold you both in his arms.

[.signed-section-closing]
Your`'s that was, but not now mine own,

[.signed-section-signature]
Walter Raleigh.

--

Behold wisdom, resolution, nature, and grace!
How strong in argument, wise in counsel, firm, affectionate, and devout!
O that your heroes and politicians would make him their example in his death,
as well as magnify the great actions of his life.
I doubt not, had he been to live over his days again, with his experience,
he had made less noise, and yet done more good to the world and himself.
It is a sad thing to consider, that, men hardly come to know themselves or the world,
till they are ready to leave it.

[.numbered-group]
====

[.numbered]
XIII.
Henry Wotton, knight, thought it the greatest happiness in this life,
"`to be at leisure to be and to do good;`" as in his latter end he was wont to say,
when he reflected on past times, though a man esteemed sober and learned,
"`How much time have I to repent of, and how little to do it in!`"

[.numbered]
XIV.
Sir Christopher Hatton, a little before his death,
advised his relations to be serious in the search after
"`the will of God in the holy word:`" "`for,`" said he,
"`it is deservedly accounted a piece of excellent knowledge,
to understand the law of the land, and the customs of a man`'s country;
how much more to know the statutes of heaven, and the laws of eternity;
those immutable and eternal laws of justice and righteousness;
to know the will and pleasure of the great Monarch, and universal King of the world:
I have seen an end of all perfection, but thy commandments, O God, are exceeding broad.`"

Whatever other knowledge a man may be endued withal,
could he by a vast and imperious mind,
and a heart as large as the sand upon the sea-shore,
command all the knowledge of art and nature, of words and things;
could he attain a mystery in all languages, and sound the depth of all arts and sciences;
could he discourse of the interests of all states, the intrigues of all courts,
the reason of all civil laws and constitutions, and give an account of all histories;
and yet not know the Author of his being, and the Preserver of his life, his Sovereign,
and his Judge; his surest refuge in trouble: his best Friend; the support of his life,
and the hope of his death; his future happiness, and his portion forever;
he doth but sapienter descendere in infernum,
with a great deal of wisdom go down to Hell.

[.numbered]
XV. Francis Bacon, lord high-chancellor of England, some time before his death,
confessed, that, to be religious, was to live strictly and severely;
for if the opinion of another world be false,
yet the sweetest life in this world is piety, virtue, and honesty; if it were true,
there be none so wretched and miserable, as loose, carnal, and profane persons.

[.numbered]
XVI.
The great duke de Montmorency, colleague to the duke of Orleans,
brother to the French king, Lewis XIII.,
in the war by them agitated against the ministry of Cardinal Richlieu,
being taken and convicted at Lyons, a little before his beheading, looking upon himself,
then very richly attired; "`Ah!`" says he,
"`this becomes not a servant of the crucified Jesus!
What do I with these vanities about me?
He was poor, despised, and naked,
when He went to the cross to die for my sins;`" and
immediately he stripped himself of all his finery,
and put a more grave and modest garment on him: a serious reflection,
at a time when he best knew what was best.

[.numbered]
XVII.
Henry, Prince of Wales, eldest son to king James I.,
of whom others say many excellent things, hear what account he gives of himself at last:
a person whom he loved, and that had been the companion of his diversions,
being with him in his sickness, and asking him how he did, was,
amongst many other sober expressions, answered thus: "`Ah, Tom!
I in vain wish for that time I lost with thee and others in vain recreations.`"
So vain were recreations, and so precious was time to a prince,
and no ordinary one neither, upon a dying bed.
But why wished he with others for more time, but that it might be better employed?
Thus hath the just principle and holy Spirit of God in men, throughout all generations,
convinced them of their vanity and folly upon their dying beds,
who before were too much taken up to mind either a dying bed, or a vast eternity;
but when their days were almost numbered, when mortality hasted on them,
when the revelation of the righteous judgment was at the door,
and that all their worldly recreations and enjoyments must be parted with,
and that eye forever shut, and flesh turned to worm`'s-meat, that took delight therein;
then, O then, was it the holy witness had room to plead with conscience:
then nothing but a holy, strict, and severe life was valuable;
then all the world for a little time,
who before had given all their time for a little of a vain world.
But if so short a representation of the inconsistency
of the vanities of the world with the Christian life,
could make so deep an impression;
oh! to what a noble stature and large proportion
had they been grown in all pious and heavenly knowledge;
and how much greater had their rewards been if they contentedly
had foregone those perishing entertainments of the world betimes,
and given the exercise of their minds to the tuition and
guidance of that universal grace and Holy Spirit of God,
which had so long shined in darkness, uncomprehended of it,
and was at last but just perceived to give a sight
of what they had been doing all their days.

[.numbered]
XVIII. Philip III.

King of Spain, seriously reflecting upon the life he had led in the world,
cried out upon his deathbed, "`Ah! how happy were I,
had I spent these twenty-three years that I have held my kingdom, in a retirement.`"
Crying out to his confessor, "`My concern is for my soul, not my body.
I lay all that God has given me, my dominion, power, and my life,
at the feet of Jesus Christ my Saviour.`"
Would kings would live, as well as die so!

[.numbered]
XIX.
Count Gondamor, ambassador in England for that very king,
and held the ablest man of his time,
took great freedom as to his religion in his politics,
serving his ends by those ways that would best accomplish them.
When, towards his latter end, he grew very thoughtful of his past life,
and after all his negotiations and successes in business, said to one of his friends,
"`I fear nothing in the world more than sin;`" often professing,
he had rather endure hell than sin: so clear and strong were his convictions,
and so exceeding sinful did sin appear to him, upon a serious consideration of his ways.

[.numbered]
XX. Cardinal Richelieu, after having been first minister of state of Europe,
as well as of France, confessed to old Peter de Moulin,
the famous Protestant of that country, that,
being forced upon many irregularities by that which they call reason of state,
he could not tell how to satisfy his conscience for several things,
and therefore had many temptations to doubt and disbelieve a God, another world,
and the immortality of the soul, and thereby to relieve his mind from any disquiet,
but in vain.
So strong, he said, was the notion of God on his soul,
so clear the impression of Him upon the frame of the world,
so unanimous the consent of mankind, so powerful the convictions of his own conscience,
that he could not but taste the power of the world to come,
and so live as one that must die, and so die as one that must live forever.
And being asked one day why he was so sad, answered, "`Monsieur, Monsieur,
the soul is a serious thing; it must be either sad here for a moment,
or be sad forever.`"

[.numbered]
XXI.
Cardinal Mazarin, reputed the most cunning statesman of his time,
and who gave great proofs of it in the successes of the French crown, under his ministry:
his aim was the grandeur of the world, to which he made all other considerations submit:
but, poor man! he was of another mind a little before his death: for,
being awakened by the smart lashes of conscience,
which represented his soul`'s condition very dismal,
with astonishment and tears he cried out, "`Oh, my poor soul, what will become of thee!
Whither wilt thou go?`"
and spake one day thus to the Queen-mother of France, "`Madam,
your favours have undone me.
Were I to live again, I would be a Capuchin, rather than a courtier.`"

[.numbered]
XXII.
Count Oxenstiern, chancellor of Sweden, a person of the first quality, station,
and ability in his own country, and whose share and success,
not only in the chief ministry of affairs in that kingdom,
but in the greatest negotiations of Europe during his time,
made him no less considerable abroad.
After all his knowledge and honour, being visited in his retreat from public business,
by commissioner Whitlock, ambassador from England to Queen Christiana,
in the conclusion of their discourse, he said to the ambassador, "`I have seen much,
and enjoyed much of this world, but I never knew how to live till now.
I thank my good God that has given me time to know Him, and to know myself.
All the comfort I have, and all the comfort I take,
and which is more than the whole world can give,
is feeling the good Spirit of God in my heart,
and reading in this good book,`" holding up the Bible, "`that came from it.`"
And further addressed himself thus to the ambassador:
"`You are now in the prime of your age and vigour, and in great favour and business;
but this will all leave you,
and you will one day better understand and relish what I say to you;
and then you will find that there is more wisdom, truth, comfort, and pleasure,
in retiring and turning your heart from the world, to the good Spirit of God,
and in reading the Bible, than in all the courts and favours of princes.`"
This I had, as near as I am able to remember, from the ambassador`'s own mouth,
more than once.
A very edifying history, when we consider from whom it came;
one of the greatest and wisest men of his age,
while his understanding was as sound and vigorous,
as his experience and knowledge were great.

[.numbered]
XXIII.
Dr. Donne, a great poet, taking his farewell of his friends, on his dying bed,
left this saying behind him, for them to measure their fancies and their actions by:
"`I repent of all my life, but that part of it I spent in communion with God,
and doing good.`"

[.numbered]
XXIV.
Selden, one of the greatest scholars and antiquaries of his time:
one who had taken a diligent survey of what knowledge was considerable amongst the Jews,
Heathens, and Christians; at last professeth this toward the end of his days,
in his conference with Bishop Usher, that,
notwithstanding he had been so laborious in his inquiries,
and curious in his collections,
and had possessed himself of a treasure of books and manuscripts,
upon all ancient subjects; yet he could rest his soul on none, save the Scriptures,
and above all that passage lay most remarkably upon his spirit,^
footnote:[Titus 2:11-15,]
"`For the grace of God, that bringeth salvation, hath appeared unto all men, teaching us,
that, denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in this present world: looking for that blessed hope,
and glorious appearing of the great God, and our Saviour Jesus Christ;
who gave Himself for us, that He might redeem us from all iniquity,
and purify unto Himself a peculiar people, zealous of good works: these things speak,
and exhort, and rebuke with all authority.`"
And indeed it is one of the most comprehensive passages in the Scripture;
for it comprises the end, means, and recompense of Christianity.

[.numbered]
XXV.
Hugo Grotius,
than whom these latter ages think they have not had a man of more universal knowledge,
"`a light,`" say the statesmen; "`a light,`" say the churchmen too; witness his Annals,
and his Book, De Jure Belli et Pacis; also his Christian Religion,
and elaborate Commentaries.
He winds up his life and choice in this remarkable saying,
which should abate the edge of other men`'s inordinate
desires after what they falsely call learning;
namely, "`I would give all my learning and honour for the plain integrity of Jean Urick,
who was a religious poor man, that spent eight hours of his time in prayer,
eight in labour, and but eight in meals, sleep, and other necessaries.`"
And to one that admired his great industry, he returned this by way of complaint: "`Ah!
I have consumed my life in laboriously doing nothing.`"
And to another, that inquired of his wisdom and learning, what course to take,
he solemnly answered, "`Be serious.`"
Such was the sense he had, how much a serious life excelled,
and was of force towards a dying hour.

[.numbered]
XXVI.
To whom I join Salmasius, that famous French scholar, and the other`'s contemporary,
who after his many volumes of learning,
by which he had acquired great veneration among men of books,
confessed so far to have mistaken true learning,
and that in which solid happiness consists, that he exclaimed thus against himself: "`Oh!
I have lost a world of time; time, that most precious thing in the world; whereof,
had I but one year more, it should be spent in David`'s Psalms, and Paul`'s Epistles.
Oh, Sirs,`" said he to those about him, "`mind the world less, and God more:
the fear of the Lord, that is wisdom; and to depart from evil, that is understanding.`"

[.numbered]
XXVII.
Francis Junius, an ingenious person, who hath written his own life,
as he was reading Tully de Legibus, fell into a persuasion, Nihil curare Deum, nec sui,
nec alieni; till in a tumult in Lyons,
the Lord wonderfully delivered him from imminent death;
so that he was forced to acknowledge a divine Providence therein,
and his father hearing the dangerous ways that his son was misled into,
sent for him home, where he carefully and piously instructed him,
and caused him to read over the New Testament; of which himself writeth thus:
"`When I opened the New Testament, I first lighted upon John`'s first chapter,
"`In the beginning was the word,`" etc.
I read part of the chapter, and was suddenly convinced,
that the divinity of the argument, and the majesty and authority of the writing,
did exceedingly excel all the eloquence of human writings: my body trembled,
my mind was astonished, and was so affected all that day,
that I knew not where and what I was.
Thou wast mindful of me, O my God, according to the multitude of thy mercies,
and calledst home thy lost sheep into the fold.`"
And, as Justin Martyr of old, so he of late professed,
that the power of godliness in a plain simple Christian wrought so upon him,
that he could not but take up a strict and a serious life.

[.numbered]
XXVIII.
A+++.+++ Rivetus, a man of learning, and much reverenced in the Dutch nation,
after a long life of study, in search of Divine knowledge, upon his death bed,
being discoursed by his friend of heavenly things, brake forth in this manner:
"`God has learned me more of himself in ten days`' sickness,
than I could get by all my labour and studies.`"
So near a way, so short a cut it is to the knowledge of God,
when people come into the right way, which is to turn, in their minds and hearts,
to the voice of God, and learn of Him, who is a Spirit, to be taught of Him,
and led by Him: For in righteousness such shall be established,
and great shall be their peace.

[.numbered]
XXIX.
A Letter from James, Earl of Marlborough, a little before his Death,
in the Battle at Sea, on the Coast of Holland, etc.

====

[.embedded-content-document.letter]
--

I believe the goodness of your nature, and the friendship you have always borne me,
will receive with kindness the last office of your friend.
I am in health enough of body, and, through the mercy of God, in Jesus Christ,
well disposed in mind.
This I premise,
that you may be satisfied that what I write proceeds
not from any fantastic terror of mind,
but from a sober resolution of what concerns myself,
and earnest desire to do you more good after my death,
than mine example (God of his mercy pardon the badness
of it!) in my lifetime may do you harm.
I will not speak aught of the vanity of this world;
your own age and experience will save that labour:
but there is a certain thing that goeth up and down in the world, called religion,
dressed, and pretended fantastically, and to purposes bad enough,
which yet by such evil dealings loseth not its being.
The great good God hath not left it without a witness, more or less, sooner or later,
in every man`'s bosom, to direct us in the pursuit of it;
and for the avoiding those inextricable disquisitions and
entanglements our own frail reasons would perplex us withal,
God in his infinite mercy hath given us his holy word, in which,
as there are many things hard to be understood,
so there is enough plain and easy to quiet our minds,
and direct us concerning our future being.
I confess to God and you, I have been a great neglecter, and, I fear, despiser of it:
God of his infinite mercy pardon me the dreadful fault!
But when I retired myself from the noise and deceitful vanity of the world,
I found no true comfort in any other resolution than what I had from thence: I commend,
from the bottom of my heart, the same to your, I hope, happy use.
Dear Hugh, let us be more generous, than to believe we die as the beasts that perish;
but with a christian, manly, brave resolution, look to what is eternal.
I will not trouble you further.
The only great God, and holy God, Father, Son, and Holy Ghost,
direct you to a happy end of your life, and send us a joyful resurrection!
So prays your true friend,

[.signed-section-signature]
Marlborough.

--

[.numbered-group]
====

[.numbered]
XXX.
The late Sir Henry Vane must be too fresh in memory to need a character;
but it is certain, his parts were of the first rate,
and superior to the generality of men; but he would often say, he owed them to religion.
In his youth he was much addicted to company, and promised little to business;
but in reading a book, called, The Signs of a Godly Man,
and being convicted in himself that they were just,
but that he had no share in any one of them,
he fell into that extreme anguish and horror,
that for some days and nights he took little food or rest,
which at once dissolved his old friendships,
and made those impressions and resolutions to religion, that neither university, courts,
princes, nor parents,
nor any losses or disappointments that threatened his new course of life,
could weaken or alter.
And though this laid him under some disadvantages for a time,
his great integrity and abilities quickly broke through that obscurity;
so that those of very differing sentiments did not only admire,
but very often desired him to accept the most eminent negotiations of his country,
which he served according to his own principles with great success,
and a remarkable self-denial.
This great man`'s maxim was, Religion was the best master, and the best friend;
for it made men wise, and would never leave them that never left it;
which he found true in himself:
for as it made him wiser than those that had been his teachers,
so it made him firmer than any hero, having something more than nature to support him:
which was the judgment as well of foreigners as others,
that had the curiosity to see him die.
Making good some meditations of his own, viz.:
"`The day of death is the judge of all our other days:
the very trial and touch-stone of the actions of our life.
It is the end that crowns the work, and a good death honoureth a man`'s whole life.
The fading corruption and loss of this life is the passage into a better.
Death is no less essential to us, than to live or to be born.
In flying death, thou fliest thyself; thy essence is equally parted into these two,
life and death.
It is no small reproach to a Christian, whose faith is in immortality,
and the blessedness of another life, to fear death much,
which is the necessary passage thereunto.

[.numbered]
XXXI.
Abraham Crowley, whom to name, is enough with the men of wit of our time and nation,
speaks not less in favour of the Temperance and Solitude
so much laboured in the preceding discourse:
Yet that his judgment may have the more force with the reader,
it may be fit that I should say, That he was a man of a sweet and singular wit,
great learning, and an even judgment; that had known what cities, universities,
and courts could afford; and that not only at home, but in divers nations abroad.
Wearied with the world, he broke through all the entanglements of it;
and which was hardest, great friendship and a perpetual praise;
and retired to a solitary cottage near Barn-Elms, where his garden was his pleasure,
and he his own gardener: Whence he giveth us this following doctrine of retirement,
which may serve for an account how well he was pleased in his change.
"`The first work,
(saith he) that a man must do to make himself capable of the good of solitude,
is the very eradication of all lusts; for how is it possible for a man to enjoy himself,
while his affections are tied to things without himself.
The first minister of state hath not so much business in public,
as a wise man hath in private: If the one have little leisure to be alone,
the other hath less leisure to be in company;
the one hath but part of the affairs of one nation,
the other all the works of God and nature under his consideration.
There is no saying shocks me so much, as that which I hear very often,
"`That a man doth not know how to pass his time.`"
"`It would have been but ill spoken of Methuselah,
in the nine hundred sixty-ninth year of his life.
But that is not to deceive the world, but to deceive ourselves, as Quintilian saith,
_Vitam fallere._
To draw on still, and amuse and deceive our life,
till it be advanced insensibly to the fatal period,
and fall into that pit which nature hath prepared for it.
The meaning of all this is no more, than that most vulgar saying, _Bene Gui latuit,
bene vixit;_ He hath lived well, who hath lain well hidden.
Which, if it be a truth, the world is sufficiently deceived; For my part, I think it is;
and that the pleasantest condition in life is in incognito.
What a brave privilege is it, to be free from all contentions, from all envying,
or being envied, from receiving and from paying all kind of ceremonies!
We are here among the vast and noble scenes of nature;
we are there among the pitiful shifts of policy: We walk here in the light,
and open ways of the divine bounty;
we grope there in the dark and confused labyrinths of human malice:
Our senses are here feasted with the clear and genuine taste of their objects;
which are all sophisticated there; and,
for the most part overwhelmed with their contraries.
Here pleasure looks, methinks, like a beautiful, constant, and modest wife;
it is there an impudent, fickle, and painted harlot.
Here is harmless and cheap plenty: There, guilty and expenceful luxury.
The antiquity of this art is certainly not to be contested by any other.
The three first men in the world, were a Gardener, a Ploughman, and Grazier:
And if any man object, That the second of these was a Murderer;
I desire he would consider, that as soon as he was so, he quitted our Profession,
and turned Builder.
It is for this reason, I suppose, that the son of Sirach for bids us to hate husbandary;
because (saith he) the Most High hath created it.
We were all born to this art,
and taught by nature to nourish our bodies by the same earth out of which they were made,
and to which they must return, and pay at last for their sustenance.
Behold the Original and Primitive Nobility of all those Great persons,
who are too proud now not only to Till the ground, but almost to tread upon it.
We may talk what we please of lilies and lions rampant, and spread eagles in fields _d`'or,_
or _d`'argent;_ but if heraldry were guided by Reason,
a Plough in a Field Arable would be the most noble and ancient arms.`'

[verse]
____
Blest be the man (and blest is he) whome`'er,

(Plac`'d far out of the roads of Hope or Fear) A little Field, a little Garden, feeds;

The Field gives all that Frugal nature needs:

The wealthy Garden lib`'rally bestows

All she can ask, when she Luxurious grows.

The specious inconveniences that wait

Upon a life of business and of state,

He sees (nor doth the sight disturb his rest)

By Fools desir`'d, by Wicked men possest.

--Ah wretched, and too Solitary, he

Who loves not his own Company:

He`'ll feel the weight of`'t many a day,

Unless he call in sin or vanity

To help to bear`'t away.
____

Out of Martial,
he gives us this following epigram which he makes his by Translation and Choice,
to own Solitude by: I place it here as his.

[verse]
____
Would you be free?
`'Tis your chief wish you say

Come on: I`'ll shew thee, friend, the certain way:

If to no feasts abroad thou lov`'st to go,

Whilst bounteous God doth bread at home bestow:

If thou the goodness of thy clothes dost prize

By thy own Use, and not by others`' Eyes:

If only safe from Weathers, thou canst dwell

In a small House, but a convenient Shell;

If thou without a Sigh or Golden Wish

Canst look upon thy Beechen Bowl, or Dish;

If in thy mind such Power and Greatness be,

The Persian King`'s a Slave, compar`'d with thee.

Whilst this hard truth I teach, methinks I see

The monster, London, laugh at me;

I should at thee too, foolish city,

If it were fit to laugh at Misery;

But thy estate I pity.

Let but thy wicked men from out thee go,

And all the fools that crowd thee so;

Even thou who dost thy millions boast,

A Village less than Islington wilt grow;

A solitude almost.
____

[.offset]
I shall conclude him with this prayer of his own.

[verse]
____
For the few hours of life allotted me,

Give me (great God) but Bread and Liberty;

I`'ll beg no more; if more thou`'rt pleas`'d to give,

I`'ll thankfully that Overplus receive.

If beyond This no more be freely sent,

I`'ll thank for This, and go away content.
____

Here ends the wit, the praise, the learning, the city, the court, with Abraham Cowley,
that once knew and had them all.

[.numbered]
XXXII.
The late earl of Rochester was inferior to nobody in wit,
and hardly anybody ever used it worse,
if we believe him against himself in his dying reflections;
an account of which I have had from some that visited him in his sickness,
besides that larger one, made public by the Bishop of Salisbury.
It was then that he came to think there was a God,
for he felt his lashes on his conscience, and that there was such a thing as virtue,
and a reward for it.
Christianity was no longer a worldly or absurd design; but Christ, a Saviour,
and a most merciful one; and his doctrines plain, just, and reasonable,
and the true way to felicity here and hereafter.
Admiring and adoring that mercy to him,
which he had treated with so much infidelity and obstinate contempt:
wishing only for more life to confute his past one,
and in some measure to repair the injuries he had done to religion by it;
begging forgiveness for Christ`'s sake,
though he thought himself the most unworthy of it
for his own,--thus died the witty Lord Rochester,
and this retreat he made from the world he had so great a name in.
May the loose wits of the times, as he desired, take warning by him,
and not leave their repentance to a dying bed!

[.numbered]
XXXIII.
A noble young man of the family of Howard,
having yielded too much to the temptations of youth, when upon his sick bed,
which proved his dying bed, fell under the power and agony of great convictions,
mightily bewailing himself in the remembrance of his former extravagancies;
crying strongly to God to forgive him, abhorring his former course,
and promising amendment, if God renewed life to him.
However, he was willing to die, having tasted of the love and forgiveness of God;
warning his acquaintance and kindred that came to see him to fear God,
and forsake the pleasures and vanity of this world:
and so willingly yielded his soul from the troubles of time, and frailties of mortality.

[.numbered]
XXXIV.
The late princess Elizabeth of the Rhine of right claimeth a memorial in this discourse,
her virtue giving greater lustre to her name than her quality,
which yet was of the greatest in the German empire.
She chose a single life, as freest of care,
and best suited to the study and meditation she was always inclined to;
and the chief diversion she took, next to the air,
was in some such plain and housewifely entertainments as knitting, etc.
She had a small territory, which she governed so well,
that she showed herself fit for a greater.
She would constantly, every last day in the week, sit in judgment,
and hear and determine causes herself; where her patience, justice,
and mercy were admirable; frequently remitting her forfeitures, where the party was poor,
or otherwise meritorious.
And what was excellent, though unusual, she would temper her discourses with religion,
and strangely draw concerned parties to submission and agreement;
exercising not so much the rigour of her power, as the power of her persuasion.
Her meekness and humility appeared to me extraordinary; she never considered the quality,
but the merit of the people she entertained.
Did she hear of a retired man, hid from the world,
and seeking after the knowledge of a better,
she was sure to set him down in the catalogue of her charity, if he wanted it;
I have casually seen, I believe,
fifty tokens sealed and superscribed to the several poor subjects of her bounty,
whose distances would not suffer them to know one another, though they knew her,
whom yet some of them had never seen.
Thus, though she kept no sumptuous table in her own court,
she spread the tables of the poor in their solitary cells;
breaking bread to virtuous pilgrims, according to their want, and her ability.
Abstemious in herself, and in apparel void of all vain ornaments.

I must needs say, her mind had a noble prospect;
her eye was to a better and more lasting inheritance than can be found below:
which made her often to despise the greatness of courts, and learning of the schools,
of which she was an extraordinary judge.
Being once at Hamburgh, a religious person, whom she went to see for religion`'s sake,
telling her it was too great an honour for him,
that he should have a visitant of her quality come under his roof,
that was allied to so many great kings and princes of this world, she humbly answered:
"`If they were godly as well as great, it would be an honour indeed;
but if you knew what that greatness was as well as I, you would value less that honour.`"
Being in some agony of spirit, after a religious meeting we had in her own chamber,
she said, "`It is a hard thing to be faithful to what one knows: Oh, the way is strait!
I am afraid I am not weighty enough in my spirit to walk in it.`"
After another meeting, she uttered these words: "`I have records in my library,
that the Gospel was first brought out of England hither into Germany, by the English,
and now it is come again.`"
She once withdrew, on purpose to give her servants the liberty of discoursing with us,
that they might the more freely put what questions
of conscience they desired to be satisfied in;
for they were religious: suffering both them, and the poorest of her town,
to sit by her in her own bedchamber, where we had two meetings.
I cannot forget her last words, when I took my leave of her:
"`Let me desire you to remember me, though I live at this distance,
and that you should never see me more: I thank you for this good time;
and know and be assured, though my condition subjects me to divers temptations,
yet my soul hath strong desires after the best things.`"
She lived her single life till about sixty years of age,
and then departed at her own house in Herwerden, in the year 1680,
as much lamented as she had lived beloved of the people: to whose real worth, I do,
with a religious gratitude, for her kind reception, dedicate this memorial.

[.numbered]
XXXV.
Bulstrode Whitlock,
has left his own character in his "`Memoirs of English affairs;`"
a book that shows both his employments and greater abilities.
He was almost ever a commissioner and companion with
those great men that the lords and commons of England,
at several times, appointed to treat with King Charles I. for a peace.
He was commissioner of the great seal, ambassador to the crown of Sweden,
and sometimes president to the council: a scholar, a lawyer, a statesman; in short,
he was one of the most accomplished men of the age.
Being with him sometimes at his own house in Berkshire,
where he gave me that account I have related of chancellor Oxenstiern,
amongst many serious things he spoke, this was very observable,
"`I have ever thought,`" said he, "`there has been one true religion in the world,
and that is the work of the Spirit of God in the hearts and souls of men.
There have been indeed divers forms and shapes of things,
through the many dispensations of God to men, answerable to his own wise ends,
in reference to the low and uncertain state of man in the world;
but the old world had the Spirit of God, for it strove with them;
and the new world has had the Spirit of God, both Jew and Gentile,
and it strives with all; and they that have been led by it,
have been the good people in every dispensation of God to the world.
And I myself must say, I have felt it from a child to convince me of my evil and vanity,
and it has often given me a true measure of this poor world,
and some taste of divine things;
and it is my grief I did not more early apply my soul to it.
For I can say, since my retirement from the greatness and hurries of the world,
I have felt something of the work and comfort of it,
and that it is both ready and able to instruct,
and lead and preserve those that will humbly and sincerely hearken to it.
So that my religion is the good Spirit of God in my heart; I mean,
what that has wrought in me and for me.`"
And after a meeting at his house,
to which he gave an entire liberty for all that pleased to come,
he was so deeply affected with the testimony of the light, spirit,
and grace of Christ in man, as the gospel dispensation,
that after the meeting closed in prayer, he rose up, and pulled off his hat, and said,
"`This is the everlasting gospel I have heard this day:
and I humbly bless the name of God, that He has let me live to see this day,
in which the ancient gospel is again preached to them that dwell upon the earth.`"

[.numbered]
XXXVI.
A sister of the family of Penn, in Buckinghamshire,
a young woman delighting in the finery and pleasures of the world,
was seized with a violent illness that proved mortal to her.
In the time of her sickness she fell into great distress of soul,
bitterly bewailing the want of that inward peace
which makes a deathbed easy to the righteous.
After several days`' languishing, a little consolation appeared after this manner.
She was some hours in a kind of trance;
she apprehended she was brought into a place where Christ was; to whom,
could she but deliver her petition, she hoped to be relieved.
But her endeavours increased her pain: for as she pressed to deliver it,
he turned his back upon her, and would not so much as look towards her.
But that which added to her sorrow, was, that she beheld others admitted: however,
she gave not over importuning him.
And when almost ready to faint, and her hope to sink,
he turned one side of his face towards her, and reached forth his hand,
and received her request: at which her troubled soul found immediate consolation.
Turning to those about her, she repeats what had befallen her, adding,
"`Bring me my new clothes, take off the lace and finery;`" and charged her relations,
not to deck and adorn themselves after the manner of the world: for that the Lord Jesus,
whom she had seen, appeared unto her in the likeness of a plain countryman,
without any trimming or ornament whatever; and that his servants ought to be like Him.

[.numbered]
XXXVII.
My own father, after thirty years employment, with good success,
in divers places of eminent trust and honour in his own country,
upon a serious reflection, not long before his death, spoke to me in this manner:
"`Son William, I am weary of the world: I would not live over my days again,
if I could command them with a wish:
for the snares of life are greater than the fears of death.
This troubles me, that I have offended a gracious God, that has followed me to this day.
Oh, have a care of sin: that is the sting both of life and death.
Three things I commend to you.
First, Let nothing in this world tempt you to wrong your conscience; I charge you,
do nothing against your conscience, so will you keep peace at home,
which will be a feast to you in the day of trouble.
Secondly, Whatever you design to do, lay it justly, and time it seasonably;
for that gives security and dispatch.
Lastly, Be not troubled at disappointments; for if they may be recovered, do it;
if they cannot, trouble is vain.
If you could not have helped it, be content;
there is often peace and profit in submitting to Providence, for afflictions make wise.
If you could have helped it, let not your trouble exceed instruction for another time:
these rules will carry you with firmness and comfort through this inconstant world.`"
At another time he inveighed against the profaneness and impiety of the age;
often crying out, with an earnestness of spirit, "`Woe to thee, O England!
God will judge thee, O England!
Plagues are at thy door, O England!`"
He much bewailed that divers men in power,
and many of the nobility and gentry of the kingdom, were grown so dissolute and profane;
often saying, "`God has forsaken us; we are infatuated; we will shut our eyes;
we will not see our true interests and happiness: we shall be destroyed!`"
Apprehending the consequences of the growing looseness of the age to be our ruin;
and that the methods most fit to serve the kingdom with true credit, at home and abroad,
were too much neglected:
the trouble of which did not a little help to feed his distemper,
which drew him daily nearer to his end: and as he believed it,
so less concerned or disordered, I never saw him at any time;
of which I took good notice: wearied to live, as well as near to die,
he took his leave of us, and of me, with this expression,
and a most composed countenance: "`Son William,
if you and your friends keep to your plain way of preaching,
and keep to your plain way of living,
you will make an end of the priests to the end of the world.
Bury me by my mother: live all in love: shun all manner of evil:
and I pray God to bless you all: and He will bless you.`"

[.numbered]
XXXVIII.
Anthony Lowther, of Mask, a person of good sense, of a sweet temper, a just mind,
and of a sober education; when of age to be under his own government,
was drawn by the men of pleasure of the town, into the usual freedoms of it,
and was as much a judge as anybody of the satisfaction that way of living could yield;
but some time before his sickness, with a free and strong judgment,
he would frequently upbraid himself,
and contemn the world for those unreasonable as well
as unchristian liberties that so much abound in it;
which apprehension increased by the instruction of a long and sharp sickness,
he would often despise their folly, and abhor their guilt; breathing,
with some impatience, after the knowledge of the best things, and the best company;
losing as little time as he could, that he might redeem the time he had lost;
testifying often, with a lively relish, to the truth of religion,
from the sense he had of it in his own breast: frequently professing,
he knew no joy comparable to that of being assured of the love and mercy of God; which,
as he often implored with strong convictions, and a deep humility and reverence,
so he had frequently tastes thereof before his last period;
pressing his relations and friends, in a most serious and affectionate manner,
to love God, and one another more, and this vile world less.
And of this he was so full,
it was almost ever the conclusion of his most inward discourses with his family;
though he sometimes said, he could have been willing to have lived, if God had pleased,
to see his younger children nearer a settlement in the world;
yet he felt no desire to live longer in the world,
but on the terms of living better in it.
For that he did not only think virtue the safest, but the happiest way of living:
commending and commanding it to his children upon his last blessing.

I shall conclude this chapter of retired, aged, and dying persons,
with some collections I have made out of the life of a person
of great piety and quality of the French nation.

[.numbered]
XXXIX.
Du Renti, a young nobleman of France, of admirable parts, as well as great birth,
touched with a sense of the vanity of the world,
and the sweetness of a retired and religious life,
notwithstanding the honours and employments that waited for him,
abandons the pride and pomp of the world, to enjoy a life of more communion with God:
do but hear him: "`I avow,`" saith he,
"`that I have no gust in anything where I find not Jesus Christ;
and for a soul that speaks not of Him,
or in which we cannot taste any effect of grace flowing from his Spirit,
(which is the principle of operations, both inward and outward,
that are solidly Christian,) speak not to me at all of such an one: could I,
as I may say, behold both miracles and wonders there, and yet not Jesus Christ,
nor hear any talk of Him, I count all but amusement of spirit, loss of time,
and a very dangerous precipice.
Let us encourage ourselves to lead this life unknown, and wholly hid from men,
but most known to and intimate with God; divesting ourselves,
and chasing out of our minds all those many superfluities, and those many amusements,
which bring with them so great a damage, that they take up our mind, instead of God.
So that when I consider that which thwarts and cuts into so many pieces this holy,
this sweet, and amiable union, which we should have continually with God, it appears,
that it is only a monsieur, a madame, a compliment, and chatting, indeed a mere foolery;
which notwithstanding doth ravish and wrest from us the time that is so precious,
and the fellowship that is so holy, and so desirable.
Let us quit this, I pray you, and learn to court it with our own Master;
let us well understand our part, our own world, as we here phrase it,
not that world I mean, which we do renounce,
but that wherein the children of God do their duties to their Father.
There is nothing in this world so separate from the world, as God;
and the greater the saints are, the greater is their retirement into Him.
This our Saviour taught us whilst He lived on earth,
being in all his visible employments united to God,
and retired into the bosom of his Father.
Since the time that I gave up my liberty to God, as I told you,
I was given to understand to what a state of annihilation the soul must be brought,
to render it capable of union with Him: I saw my soul reduced into a small point,
contracted and shrunk up to nothing: and at the same time I beheld myself,
as if encompassed with whatsoever the world loves and possesseth; and, as it were,
a hand removing all this far from me, throwing it into the ocean of annihilation.

"`In the first place, I saw removed all exterior things, kingdoms, great offices,
stately buildings, rich household-stuff, gold and silver, recreations, pleasures;
all which are great encumbrances to the soul`'s passing on to God,
of which therefore his pleasure is, that she be stripped,
that she may arrive at the point of nakedness and death,
which will bring her into possession of solid riches and real life.
Assure yourself, there is no security in any state, but this of dying and annihilation;
which is to be baptized into Christ`'s death, that we live the life of mortification.
Our best way is therefore to divest ourselves of all,
that the holy child Jesus may govern all.
All that can be imagined in this lower world is of small concernment,
though it were the losing of all our goods, and the death of all the men in it;
this poor ant-hill is not worthy of a serious thought.
Had we but a little faith, and a little love,
how happy should we esteem ourselves in giving away all, to attend no more,
save on God alone; and to say, Deus meus et omnia; my God,
and my all! '`Being,`' saith he, '`in a chapel richly wainscotted,
and adorned with very excellent sculpture, and with imagery,
I beheld it with some attention, having had some skill in these things,
and saw the bundles of fleurs-de-luce, and of flowers in the form of borders,
and of very curious workmanship; it was on a sudden put into my mind,
The original of what thou seest would not detain thee at all in seeing it.
And I perceived, that indeed all these, and those flowers themselves, not in pictures,
would not have taken me up;
and all the ornaments which architecture and art invent are but things most mean and low,
running in a manner only upon flowers, fruits, branches, harpies, and chimeras,
part whereof are in their very being but things common and low,
and part of them merely imaginary; and yet man, who croucheth to everything,
renders himself amorous and a slave of them;
no otherwise than as if a good workman should stand to copy out,
and counterfeit some trifles and fopperies.
I considered by this sight how poor man was to be cheated, amused,
and diverted from his sovereign good.
And since that time, I could make no more stand to consider any of these things;
and if I did it, I should reproach myself for it,
as no sooner seeing them in churches or elsewhere, but this presently put upon my spirit.
The original is nothing; the copy and the image is yet less; each thing is vain,
except the employment of ourselves about God alone.
An absolute abnegation will be necessary to all things, to follow in simplicity,
without reserve or reflection, what our Saviour shall work in us, or appoint for us,
let it be this or that.
This way was showed me, in which I ought to walk towards Him: and hence it is,
that all things to me ordinarily are without any gust or delight.
I assure you,
it is a great shame to a Christian to pass his days in this
world more at ease than Jesus Christ here passed his:
ah! had we but a little faith, what repose could we take out of the cross!`'`"

I will conclude his sayings with his dying blessing to his surviving children.

"`I pray God bless you, and may it please Him to bless you,
and to preserve you by his grace from the evil of the world,
that you may have no part therein: and, above all, my children,
that you may live in the fear and love of God, and yield due obedience to your mother.`"

Expressions of that weight and moment to the immortal good of man,
that they abundantly prove to all sensible readers,
that the author was a man of an enlightened mind, and of a soul mortified to the world,
and quickened to some tastes of a supernatural life: let his youth, let his quality,
adorned with so much zeal and piety, so much self-denial and constancy,
become exemplary to those of worldly quality, who may be the readers of this book.
Some perhaps will hear that truth from the several authors I have reported, whose names,
death, and time have recovered from the envy of mess that would hardly endure it from me,
if at all from the living.
Be it as it will, I shall abundantly rejoice,
if God shall please to make any part of this discourse
effectual to persuade any into the love of holiness,
without which, certain it is, no man shall see the Lord:
but the pure in heart shall behold Him forever.

To conclude,
I cannot pass this reflection upon what is observed of the sayings of dying men,
and which to me seems to have great instruction in it, viz.: All men agree,
when they come to die, it is best to be religious; to live a holy, humble, strict,
and self-denying life; retired, solitary, temperate, and disencumbered of the world.
Then loving God above all, and our neighbours as ourselves, forgiving our enemies,
and praying for them, are solid things, and the essential part of religion,
as the true ground of man`'s happiness.
Then all sin is exceeding sinful, and yields no more pleasure:
but every inordinate desire is burdensome, and severely reproved.
Then the world, with all the lawful comforts in it,
weighs light against that sense and judgment,
which such men have between the temporal and the eternal.
And since it is thus with dying men, what instruction is it to the living,
whose pretence for the most part is a perpetual contradiction?
O that men would learn to number their days,
that they might apply their hearts to wisdom! of which,
the fear of the Lord is the true and only beginning.
And blessed are they that fear always,
for their feet shall be preserved from the snares of death.

====
