== Chapter XXII.

[.chapter-synopsis]
* 1+++.+++ Of the way of living among the first Christians.
* 2+++.+++ An exhortation to all professing Christianity, to embrace the foregoing reasons and examples.
* 3+++.+++ Plain dealing with such as reject them.
* 4+++.+++ Their recompenses.
* 5+++.+++ The author is better persuaded and assured of some: an exhortation to them.
* 6+++.+++ Encouragement to the children of light to persevere, from a consideration of the excellency of their reward; the end and triumph of the Christian conqueror. The whole concluded with a brief supplication to Almighty God.

=== The Conclusion.

[.numbered-group]
====

[.numbered]
I+++.+++ Having finished so many testimonies as my time would give me leave,
in favour of this subject, No Cross, No Crown; no temperance, no happiness; no virtue,
no reward: no mortification, no glorification:
I shall conclude with a short description of the life and worship of the Christians,
within the first century or hundred years after Christ: what simplicity,
what spirituality, what holy love and communion,
did in that blessed age abound among them!
// lint-disable invalid-characters "æ"
It is delivered originally by Philo Judæus, and cited by Eusebius Pamphilius,
in his Ecclesiastical history;^
// lint-disable invalid-characters "æ"
footnote:[Philo Judæus, of the worship of Egypt and Alexandria.
Euseb. Pam. Eccl. Hist. 1. 2. c. 17.]
that those Christians renounced their substance,
and severed themselves from all the cares of this life; and forsaking the cities,
they lived solitarily in fields and gardens.
They accounted their company who followed the contrary life of cares and bustles,
as unprofitable and hurtful unto them, to the end that with earnest and fervent desires,
they might imitate them which led this prophetical
and heavenly life--`"In many places,`" says he,
"`this people liveth, for it behoveth as well the Grecians as the Barbarians,
to be partakers of this absolute goodness; but in Egypt, in every province, they abound:
and especially about Alexandria.
From all parts the better sort withdrew themselves
into the soil and place of these worshippers,
as they were called, as a most commodious place, adjoining to the lake of Mary,
in a valley very fit, both for its security and the temperance of the air.
They are further reported to have had meetinghouses,
where the most part of the day was employed in worshipping God:
that they were great allegorizers of the Scriptures, making them all figurative;
that the external show of words, or the letter, resembleth the superficies of the body;
and the hidden sense or understanding of the words seem in the place of the soul;
which they contemplate by their beholding names, as it were, in a glass.`"
That is, their religion consisted not chiefly in reading the letter, disputing about it,
accepting things in literal constructions,
but in the things declared of the substance itself, bringing things nearer to the mind,
soul, and spirit, and pressing into a more hidden and heavenly sense;
making religion to consist in the temperance and sanctity of the mind,
and not in the formal bodily worship, so much now-a-days in repute,
fitter to please comedians than Christians.
Such was the practice of those times: but now the case is altered;
people will be Christians, and have their worldly-mindedness too;
but though God`'s kingdom suffer violence by such, yet shall they never enter:
the life of Christ and his followers hath in all ages been another thing;
and there is but one way, one guide, one rest; all of which are pure and holy.

[.numbered]
II. But if any, notwithstanding our many sober reasons,
and numerous testimonies from Scripture, or the example or experience of religious,
worldly, and profane living and dying men at home and abroad, of the greatest note, fame,
and learning in the whole world,
shall yet remain lovers and imitators of the folly and the vanity condemned:
if the cries and groans, sighs and tears, and complaints,
and mournful wishes of so many reputed great, nay, some sober men;
"`O that I had more time!
O that I might live a year longer, I would live a stricter life!
O that I were a poor Jean Urick!
All is vanity in this world!
O my poor soul! whither wilt thou go?
O that I had the time spent in vain recreations!
A serious life is above all:`" and such like.
If, I say, this by no means can prevail, but if yet they shall proceed to folly,
and follow the vain world, what greater evidence can they give of their heady resolution,
to go on impiously to despise God, to disobey his precepts, to deny Christ, to scorn,
not to bear his cross, to forsake the examples of his servants,
to give the lie to the dying serious sayings and consent of all ages;
to harden themselves against the checks of conscience,
to befool and sport away their precious time, and poor immortal souls to woe and misery?^
footnote:[Ex. 32:6; Amos 6:3-6; Eph. 4:17,24.]
In short, it is plain to discover, you have neither reason to justify yourselves,
nor yet enough of modesty to blush at your own folly;
but as those that have lost the sense of one and the other, go on to eat and drink,
and rise up to play.^
footnote:[Matt. 19:16-22.]
In vain, therefore, is it for you to pretend to fear the God of heaven,
whose minds serve the god of the pleasure of this world: in vain is it to say,
you believe in Christ, who receive not his self-denying doctrine:
and to no better purpose will all you do avail.
If he that had loved God and his neighbour, and kept the commandments from his youth,
was excluded from being a disciple, because he sold not all, and followed Jesus;
with what confidence can you call yourselves Christians,
who have neither kept the commandments, nor yet forsaken anything to be so?
And if it was a bar betwixt him and the eternal life he sought, that,
notwithstanding all his other virtues,
love to money and his external possessions could not be parted with,
what shall be your end, who cannot deny yourselves many less things,
but are daily multiplying your inventions to please your fleshly appetites?
Certainly, much more impossible is it to forsake the greater.
Christ tried his love, in bidding him forsake all, because he knew, for all his brags,
that his mind was rivetted therein:
not that if he had enjoyed his possessions with Christian indifferency,
they might not have been continued; but what then is their doom,
whose hearts are so fixed in the vanities of the world,
that they will rather make them Christian, than not to be Christians in the use of them?
But such a Christian this young man might have been,
who had more to say for himself than the strictest Pharisee living dare pretend to;
yet he went away sorrowful from Jesus.
Should I ask you, if Nicodemus did well to come by night,^
footnote:[John 3:1-5,]
and be ashamed of the great Messiah of the world?
and if he was not ignorant when Christ spake to him of the new birth?
I know you will answer me, he did very ill, and was very ignorant; but stay a while;
the beam is in your own eyes: you are ready doubtless to condemn him, and the young man,
for not doing what you not only refuse to do yourselves, but laugh at others for doing.
Nay, had such passages not been writ,
and were it not for the reverence some pretend for the Scriptures,
they would both be as stupid as Nicodemus in their answers to such heavenly matters,
and ready to call it canting to speak so, as it is frequent for you,
when we speak to the same effect, though not the same words: just as the Jews,
at what time they called God their Father, they despised his Son;
and when He spake of sublime and heavenly mysteries, some cried, He has a devil; others,
He is mad; and most of them, These are hard sayings, who can hear them?

[.numbered]
III.
And to you all that sport yourselves after the manners of the world, let me say,
that you are of those who profess you know God, but in works deny Him;
living in those pleasures which slay the just in yourselves.^
footnote:[Tit. 1:16.]
For though you talk of believing,
it is no more than taking it for granted that there is a God, a Christ, Scriptures,
etc. without further concerning yourselves to prove
the verity thereof to yourselves or others,
by a strict and holy conversation:
which slight way of believing is but a light and careless
way of ridding yourselves of further examination;
and rather throwing them off with an inconsiderate granting of them to be so,
than giving yourselves the trouble of making better inquiry,
leaving that to your priests, ofttimes more ignorant,
and not less vain and idle than yourselves, which is so far from a gospel faith,
that it is the least respect you can show to God, Scriptures,
etc. and next to which kind of believing, is nothing, under a denial of all.

But if you have hitherto laid aside all temperance, reason, and shame,
at least be entreated to resume them now on a matter of this importance,
and whereon no less concernment rests, than your temporal and eternal happiness.
Oh, retire, retire; observe the reproofs of instruction in your own minds:
that which begets sadness in the midst of mirth, which cannot solace itself,
nor be contented below immortality, which calls often to an account at nights, mornings,
and other seasons: which lets you see the vanity, the folly,
the end and misery of these things;
this is the just principle and holy Spirit of the Almighty within you: hear Him,
obey Him: converse with them who are led by Him,
and let the glories of another world be eyed,
and the heavenly recompense of reward kept in sight.
Admit not the thoughts of former follies to revive; but be steady,
and continually exercised by his grace, to deny ungodliness and worldly lusts,
and to live soberly, righteously, and godly in this present world:^
footnote:[Tit. 2:12.]
for this is the true and heavenly nature of Christianity,
to be so awakened and guided by the Spirit and grace of God,
as to leave the sins and vanities of the world, and to have the affections regenerated,
the mind reformed,
and the whole man so baptised into purity and faithfulness towards God and man;
as to act with reverence, justice, and mercy: to care for very few things;
to be content with what you have: to use all as if you used them not;
and to be so disentangled from the lusts, pleasures, profits, and honours of the world,
as to have the mind raised to things above, the heart and affections fixed there:
that in all things you may glorify God, and be as lights set on a hill,
whose shining examples may be conducing to the happiness of others, who,
beholding such good works, may be converted, and glorify God the Father of lights,
in whom you all would be eternally blessed.

[.numbered]
IV. But if the impenitence of any is so great, their pursuit of folly so earnest,
and notwithstanding what has been thus seriously offered to reclaim them,
they are resolved to take their course, and not to be at leisure for more divine things,
I have this further to leave with them from the Almighty,
who first called me to this work: that tribulation, anguish, and sorrow,^
footnote:[Rom. 2:4-6, 9.]
shall make their dying beds; indignation and wrath shall wind up their days,
and trouble and vexation of mind and spirit shall
be the miserable fruits which they shall reap,
as the reward of all their wretched folly and rebellion!
Be not deceived, God will not be mocked:^
footnote:[Gal. 6:4-8.]
it is so irreversibly decreed, Whatever is sown here, shall be reaped hereafter.
And just is the Almighty, to make good his determinations upon such, who,
instead of employing the time given them to work out their salvation with fear and trembling,
have spent it in the pleasures of the flesh, which perish; as if their heaven were here.
Nor can it seem unreasonable, since He hath thus long waited with remission of sins,
and eternal life in his hand, to distribute to them that repent: that if such will not,
to recompense so great obstinacy and love of this perishing world,
with everlasting tribulation.^
footnote:[Rev. 3:20, xxi.
27, xxii.
13-15.]

[.numbered]
V+++.+++ But I am otherwise persuaded of many: yes,
I am assured the mercies of the everlasting God have been so extended to many,
that this will prove an effectual call to bring them out of the
ways and customs of this corrupted and corrupting world;
and a means of establishing such,
who hitherto have been unfaithful to what they have been already convinced of.
And you, my friends, whose minds have received the alarm,
whose hearts have truly heard the voice of one crying in the wilderness,
where you have been straying from the Lord, Repent! repent!
To you, in the name of the great and living God, I speak, I cry, Come away, come away:
ah! what do you do there?
Why are you yet behind?
That is not your rest; it is polluted with the sins and vanities of a perishing world:
gird up your loins: eye your light, one in all, Christ Jesus, the same yesterday, today,
and forever: who hath enlightened every one:^
footnote:[John 1:9.]
follow Him, He will lead you to the city of God, that has foundations,
into which the wicked cannot enter.

[.numbered]
VI. Mind not the difficulties of your march;
great and good things were never enterprised and accomplished without difficulty,
which does but render their enjoyment more pleasant and glorious in the end.
Let the holy men and women of old be your examples: remember good old Abraham,^
footnote:[Gen. 12:1-2.]
the excellency of whose faith is set out by his obedience to the voice of God,
in forsaking his father`'s house, kindred, country, etc.
And Moses, that might in probability have been made a king,
by faith in God leaves Egypt`'s glory and Pharaoh`'s favours,
and chooses rather a sojourn and pilgrimage with the despised, afflicted,
tormented Israelites in the wilderness,
than to enjoy the pleasures of that great court for a season;
esteeming Christ`'s reproaches greater riches than Egypt`'s treasures.^
footnote:[Heb. 11:24-27; Isaiah 54:3.]
But above all, how great was the reproach, how many the sufferings,
how bitter the mockings, which Jesus suffered at the hands of his enemies!
Yet with what patience, meekness, forgiveness, and constancy, did He in all his actions,
demean himself towards his bloody persecutors, despising the shame, enduring the cross,
for the joy that was set before him!^
footnote:[Heb. 12:12.]
And hath left us this glorious example, that we should follow his steps;^
footnote:[1 Peter 2:22-23.]
which hath in almost every age been imitated by some.
The apostles sealed their testimonies with their blood,
and multitudes after the example of their constancy, esteeming it the greatest honour,
as it was always attended with the signal demonstration of the Divine presence.
How memorable was that of Origen: "`If my father were weeping upon his knees before me,
and my mother hanging about my neck behind me, and all my brethren, sisters,
and kinsfolk lamenting on every side, to retain me in the life and practice of the world,
I would fling my mother to the ground, run over my father, despise all my kindred,
and tread them under my feet, that I might run to Christ.`"
Yet it is not unknown, how dutiful and tender he was in those relations.
Not much unlike to this was that noble and known instance of latter times,
in Galeacius Carraciolus, marquis of Vico, who abandoned his friends, estate,
and country, resolutely saying with Moses,
that he would rather suffer afflictions with the first reformers and Protestants,
than enjoy his former plenty, favours, and pleasures, with his old religion.^
footnote:[2 Tim. 3:12; 1 Peter 4:1-5.]
Nor is it possible for any now to quit the world, and live a serious,
godly life in Christ, without the like suffering and persecution.
There are among us also some who have suffered the displeasure
of their most dear and intimate relations and friends;
and all those troubles, disgraces, and reproaches,
which are accustomed to attend such as decline the honours, pleasures, ambition,
and preferments of the world, and that choose to live a humble, serious,
and self-denying life before the Lord:
but they are very unequal to the joy and recompense that follow.
For though there be no affliction that is not grievous for the present, yet,
what says the man of God?
it works a far more exceeding weight of glory in the end.
This has been both the faith and experience of those,
that in all ages have trusted in God, who have not fainted by the way; but enduring,
have obtained an eternal diadem.

Wherefore, since we are compassed about with so great a cloud of witnesses,
let us lay aside every weight and burden,
and the sin and vanities that do so easily beset us,
and with a constant holy patience run our race, having our eye fixed upon Jesus,
the Author and Finisher of our faith, not minding what is behind;^
footnote:[Heb. 12:1; Rom. 5:1-4.]
so shall we be delivered from every snare.
No temptations shall gain us, no frowns shall scare us from Christ`'s cross,
and our blessed self-denial.^
footnote:[Phil. 3:13; Rom. 2:7.]
And honour, glory, immortality,
and a crown of eternal life shall recompense all our sufferings in the end.

O Lord God! thou lovest holiness, and purity is thy delight in the earth;
wherefore I pray thee, make an end of sin, and finish transgression,
and bring in thy everlasting righteousness to the souls of men,
that thy poor creation may be delivered from the bondage it groans under,
and the earth enjoy her sabbath again:
that thy great Name may be lifted up in all nations,
and thy salvation renowned to the ends of the world.
For thine is the kingdom, the power, and the glory, forever.
Amen.

====
