[quote.epigraph, , 2 Cor. 6:9]
____
As unknown, and yet well known.
____

== An Epistle to the Reader

Reader, this following account of the people called Quakers,
etc. was written in the fear and love of God: first,
as a standing testimony to that ever blessed truth in the inward parts, with which God,
in my youthful time, visited my soul,
and for the sense and love of which I was made willing, in no ordinary way,
to relinquish the honours and interests of the world.
Secondly, as a testimony for that despised people,
that God has in his great mercy gathered and united by his
own blessed Spirit in the holy profession of it;
whose fellowship I value above all worldly greatness.
Thirdly, in love and honour to the memory of that worthy servant of God, George Fox,
the first instrument thereof,
and therefore styled by me--The great and blessed apostle of our day.
As this gave birth to what is here presented to thy view, in the first edition of it,
by way of preface to George Fox`'s excellent Journal;
so the consideration of the present usefulness of
the following account of the people called Quakers,
by reason of the unjust reflections of some adversaries
that once walked under the profession of Friends,
and the exhortations that conclude it,
prevailed with me to consent that it should be republished in a smaller volume;
knowing also full well, that great books, especially in these days, grow burdensome,
both to the pockets and minds of too many; and that there are not a few that desire,
so it be at an easy rate, to be informed about this people,
that have been so much everywhere spoken against:
but blessed be the God and Father of our Lord Jesus Christ,
it is upon no worse grounds than it was said of old time of the primitive Christians,
as I hope will appear to every sober and considerate reader.
Our business, after all the ill usage we have met with, being the realities of religion,
an effectual change before our last and great change: that all may come to an inward,
sensible, and experimental knowledge of God,
through the convictions and operations of the light and spirit of Christ in themselves;
the sufficient and blessed means given to all,
that thereby all may come savingly to know the only true God,
and Jesus Christ whom he hath sent to enlighten and redeem the world:
which knowledge is indeed eternal life.
And that thou, reader, mayst obtain it,
is the earnest desire of him that is ever thine in so good a work.

William Penn.
