== Chapter I.

[.blurb]
=== Containing a brief account of divers dispensations of God in the world, to the time he was pleased to raise this despised people, called Quakers.

Divers have been the dispensations of God since the creation of the world,
unto the sons of men; but the great end of all of them,
has been the renown of his own excellent name in the creation and restoration of man:
man, the emblem of himself, as a God on earth, and the glory of all his works.
The world began with innocency; all was then good that the good God had made:
and as he blessed the works of his hands,
so their natures and harmony magnified him their Creator.
Then the morning stars sang together for joy,
and all parts of his work said Amen to his law.
Not a jar in the whole frame; but man in paradise, the beasts in the field,
the fowl in the air, the fish in the sea, the lights in the heavens,
the fruits of the earth; yea, the air, the earth, the water, and fire, worshipped,
praised, and exalted his power, wisdom, and goodness.
O holy sabbath!
O holy day to the Lord!

But this happy state lasted not long; for man, the crown and glory of the whole,
being tempted to aspire above his place, unhappily yielded, against command and duty,
as well as interest and felicity, and so fell below it; lost the divine image,
the wisdom, power, and purity he was made in; by which, being no longer fit for paradise,
he was expelled that garden of God, his proper dwelling and residence,
and was driven out, as a poor vagabond, from the presence of the Lord,
to wander in the earth, the habitation of beasts.

Yet God that made him had pity on him; for he, seeing man was deceived,
and that it was not of malice, or an original presumption in him,
but through the subtlety of the serpent, who had first fallen from his own state,
and by the mediation of the woman, man`'s own nature and companion,
whom the serpent had first deluded,
in his infinite goodness and wisdom provided a way to repair the breach,
recover the loss, and restore fallen man again by a nobler and more excellent Adam,
promised to be born of a woman;
that as by means of a woman the evil one had prevailed upon man,
by a woman also he should come into the world, who would prevail against him,
and bruise his head, and deliver man from his power: and which, in a signal manner,
by the dispensation of the Son of God in the flesh,
in the fulness of time was personally and fully accomplished by him, and in him,
as man`'s Saviour and Redeemer.

But his power was not limited, in the manifestation of it to that time;
for both before and since his blessed manifestation in the flesh,
he has been the light and life, the rock and strength of all that ever feared God;
was present with them in their temptations,
followed them in their travels and afflictions,
and supported and carried them through and over the difficulties
that have attended them in their earthly pilgrimage.
By this, Abel`'s heart excelled Cain`'s, and Seth obtained the preeminence,
and Enoch walked with God.
It was this that strove with the old world, and which they rebelled against,
and which sanctified and instructed Noah to salvation.

But the outward dispensation that followed the benighted state of man, after his fall,
especially among the patriarchs, was generally that of angels;
as the scriptures of the Old Testament do in many places express, as to Abraham, Jacob, etc.
The next was that of the law by Moses, which was also delivered by angels,
as the apostle tells us.
This dispensation was much outward, and suited to a low and servile state;
called therefore, by the apostle Paul, that of a schoolmaster,
which was to point out and prepare that people to look and long for the Messiah,
who would deliver them from the servitude of a ceremonious and imperfect dispensation,
by knowing the realities of those mysterious representations in themselves.
In this time the law was written on stone, the temple built with hands,
attended with an outward priesthood, and external rites and ceremonies,
that were shadows of the good things that were to come,
and were only to serve till the seed came,
or the more excellent and general manifestation of Christ, to whom was the promise,
and to all men only in him, in whom it was yea and amen, even life from death,
immortality and eternal life.

This the prophets foresaw, and comforted the believing Jews in the certainty of it;
which was the top of the Mosaical dispensation, which ended in John`'s ministry,
the forerunner of the Messiah, as John`'s was finished in him, the fulness of all.
And then God, that at sundry times, and in divers manners,
had spoken to the fathers by his servants the prophets,
spoke to men by his Son Christ Jesus, who is heir of all things, being the gospel-day,
which is the dispensation of sonship: bringing in thereby a nearer testament,
and a better hope; even the beginning of the glory of the latter days,
and of the restitution of all things; yea, the restoration of the kingdom unto Israel.

Now the spirit, that was more sparingly communicated in former dispensations,
began to be poured forth upon all flesh, according to the prophet Joel;
and the light that shined in darkness, or but dimly before,
the most gracious God caused to shine out of darkness,
and the day-star began to rise in the hearts of believers,
giving unto them the knowledge of God in the face, or appearance,
of his Son Christ Jesus.

Now the poor in spirit, the meek, the true mourners,
the hungry and thirsty after righteousness, the peacemakers, the pure in heart,
the merciful and persecuted, came more especially in remembrance before the Lord,
and were sought out and blessed by Israel`'s true Shepherd.
Old Jerusalem with her children grew out of date, and the new Jerusalem into request,
the mother of the sons of the gospel-day.
Wherefore, no more at old Jerusalem, nor at the mountain of Samaria,
will God be worshipped above other places; for, behold, he is, by his own Son,
declared and preached a Spirit, and that he will be known as such,
and worshipped in the spirit and in the truth.
He will now come nearer than of old time, and he will write his law in the heart,
and put his fear and spirit in the inward parts, according to his promise.
Then signs, types, and shadows flew away,
the day having discovered their insufficiency in not reaching to the inside of the cup,
to the cleansing of the conscience; and all elementary services expired in and by him,
that is the substance of all.

And to this great and blessed end of the dispensation of the Son of God,
did the apostles testify, whom he had chosen and anointed by his spirit,
to turn the Jews from their prejudice and superstition,
and the Gentiles from their vanity and idolatry,
to Christ`'s light and spirit that shined in them;
that they might be quickened from the sins and trespasses in which they were dead,
to serve the living God, in the newness of the spirit of life,
and walk as children of the light, and of the day, even the day of holiness:
for such put on Christ, the light of the world, and make no more provision for the flesh,
to fulfill the lusts thereof.
So that the light, spirit, and grace, that come by Christ, and appear in man,
were that divine principle the apostles ministered from, and turned people`'s minds unto,
and in which they gathered and built up the church of Christ in their day.
For which cause they advise them not to quench the spirit, but to wait for the spirit,
and speak by the spirit, and pray by the spirit, and walk in the spirit too,
as that which approved them the truly begotten children of God,
born not of flesh and blood, or of the will of man, but of the will of God;
by doing his will, and denying their own; by drinking of Christ`'s cup,
and being baptized with his baptism of self-denial;
the way and path that all the heirs of life have ever trod to blessedness.

But alas! even in the apostles`' days,
those bright stars of the first magnitude of the gospel light, some clouds,
foretelling an eclipse of this primitive glory, began to appear;
and several of them gave early caution of it to the Christians of their time,
that even then there was, and yet would be more and more,
a falling away from the power of godliness,
and the purity of that spiritual dispensation,
by such as sought to make a fair show in the flesh,
but with whom the offence of the cross ceased.
Yet with this comfortable conclusion,
that they saw beyond it a more glorious time than ever to the true church.
Their sight was true; and what they foretold to the churches,
gathered by them in the name and power of Jesus, came to pass:
for Christians degenerated apace into outsides, as days, and meats,
and divers other ceremonies.
And, which was worse, they fell into strife and contention about them;
separating one from another, then envying, and, as they had power,
persecuting one another, to the shame and scandal of their common Christianity,
and grievous stumbling and offence of the heathen;
among whom the Lord had so long and so marvellously preserved them.
And having got at last the worldly power into their hands,
by kings and emperors embracing the Christian profession, they changed, what they could,
the kingdom of Christ, which is not of this world, into a worldly kingdom; or, at least,
styled the worldly kingdom that was in their hands, the kingdom of Christ,
and so they became worldly and not true Christians.
Then human inventions and novelties, both in doctrine and worship,
crowded fast into the church; a door opened thereunto,
by the grossness and carnality that appeared then among the generality of Christians,
who had long since left the guidance of God`'s meek and heavenly spirit,
and given themselves up to superstition, will-worship, and voluntary humility.
And as superstition is blind, so it is heady and furious,
for all must stoop to its blind and boundless zeal, or perish by it:
in the name of the spirit,
persecuting the very appearance of the spirit of God in others,
and opposing that in others, which they resisted in themselves, viz. the light, grace,
and spirit of the Lord Jesus Christ; but always under the notion of innovation, heresy,
schism, or some such plausible name; though Christianity allows of no name,
or pretence whatever, for persecuting of any man for matters of mere religion,
being in its very nature meek, gentle, and forbearing; and consists of faith, hope,
and charity, which no persecutor can have, whilst he remains a persecutor;
in that a man cannot believe well, or hope well,
or have a charitable or tender regard to another, whilst he would violate his mind,
or persecute his body, for matters of faith or worship towards his God.

Thus the false church sprang up, and mounted the chair; but, though she lost her nature,
she would needs keep her good name of the Lamb`'s bride, the true church,
and mother of the faithful: constraining all to receive her mark,
either in their forehead, or right-hand; that is, publicly, or privately.
But, in deed and in truth, she was mystery Babylon, the mother of harlots,
mother of those that, with all their show and outside of religion,
were adulterated and gone from the spirit, nature, and life of Christ, and grown vain,
worldly, ambitious, covetous, cruel, etc. which are the fruits of the flesh,
and not of the spirit.

Now it was, that the true church fled into the wilderness, that is,
from superstition and violence, to a retired, solitary, and lonely state: hidden,
and as it were, out of sight of men, though not out of the world.
Which shows,
that her wonted visibility was not essential to the being
of a true church in the judgment of the Holy Ghost;
she being as true a church in the wilderness, though not as visible and lustrous,
as when she was in her former splendor of profession.
In this state many attempts she made to return, but the waters were yet too high,
and her way blocked up; and many of her excellent children,
in several nations and centuries, fell by the cruelty of superstition,
because they would not fall from their faithfulness to the truth.

The last age did set some steps towards it, both as to doctrine, worship, and practice.
But practice quickly failed: for wickedness flowed, in a little time,
as well among the professors of the reformation, as those they reformed from;
so that by the fruits of conversation they were not to be distinguished.
And the children of the reformers, if not the reformers themselves, betook themselves,
very early, to earthly policy and power,
to uphold and carry on their reformation that had been begun with spiritual weapons;
which I have often thought has been one of the greatest
reasons the reformation made no better progress,
as to the life and soul of religion.
For whilst the reformers were lowly and spiritually minded, and trusted in God,
and looked to him, and lived in his fear, and consulted not with flesh and blood,
nor sought deliverance in their own way, there were daily added to the church such as,
one might reasonably say, should be saved:
for they were not so careful to be safe from persecution,
as to be faithful and inoffensive under it:
being more concerned to spread the truth by their faith and patience in tribulation,
than to get the worldly power out of their hands
that inflicted those sufferings upon them:
and it will be well if the Lord suffer them not to fall,
by the very same way they took to stand.

In doctrine they were in some things short; in other things, to avoid one extreme,
they ran into another: and for worship, there was, for the generality,
more of man in it than of God.
They owned the spirit, inspiration, and revelation, indeed,
and grounded their separation and reformation upon
the sense and understanding they received from it,
in the reading of the scriptures of truth.
And this was their plea; the scripture is the text, the spirit the interpreter,
and that to every one for himself.
But yet there was too much of human invention, tradition, and art,
that remained both in praying and preaching; and of worldly authority,
and worldly greatness in their ministers; especially in this kingdom, Sweden, Denmark,
and some parts of Germany.
God was therefore pleased in England to shift us from vessel to vessel;
and the next remove humbled the ministry, so that they were more strict in preaching,
devout in praying, and zealous for keeping the Lord`'s day,
and catechising of children and servants,
and repeating at home in their families what they had heard in public.

But even as these grew into power, they were not only for whipping some out,
but others into the temple: and they appeared rigid in their spirits,
rather than severe in their lives, and more for a party than for piety:
which brought forth another people, that were yet more retired and select.

They would not communicate at large, or in common with others;
but formed churches among themselves of such as could give some account of their conversion,
at least of very promising experiences of the work of God`'s grace upon their hearts,
and under mutual agreements and covenants of fellowship, they kept together.
These people were somewhat of a softer temper,
and seemed to recommend religion by the charms of its love, mercy, and goodness,
rather than by the terrors of its judgments and punishments;
by which the former party would have awed people into religion.

They also allowed greater liberty to prophesy than those before them;
for they admitted any member to speak or pray, as well as their pastor,
whom they always chose, and not the civil magistrate.
If such found anything pressing upon them to either duty,
even without the distinction of clergy or laity, persons of any trade had their liberty,
be it never so low and mechanical.
But alas! even these people suffered great loss: for tasting of worldly empire,
and the favour of princes, and the gain that ensued, they degenerated but too much.
For though they had cried down national churches and ministry, and maintenance too,
some of them, when it was their own turn to be tried,
fell under the weight of worldly honour and advantage,
got into profitable parsonages too much,
and outlived and contradicted their own principles; and, which was yet worse, turned,
some of them, absolute persecutors of other men for God`'s sake,
that but so lately came themselves out of the furnace; which drove many a step further,
and that was into the water: another baptism,
as believing they were not scripturally baptized:
and hoping to find that presence and power of God,
in submitting to this watery ordinance, which they desired and wanted.

These people also made profession of neglecting,
if not renouncing and censuring not only the necessity, but use, of all human learning,
as to the ministry; and all other qualifications to it,
besides the helps and gifts of the spirit of God, and those natural and common to men.
And for a time they seemed, like John of old,
a burning and a shining light to other societies.

They were very diligent, plain, and serious; strong in scripture, and bold in profession;
bearing much reproach and contradiction.
But that which others fell by, proved their snare.
For worldly power spoiled them too;
who had enough of it to try them what they would do if they had more:
and they rested also too much upon their watery dispensation,
instead of passing on more fully to that of the fire and Holy Ghost,
which was his baptism, who came with a fan in his hand, that he might thoroughly,
and not in part only, purge his floor, and take away the dross and the tin of his people,
and make a man finer than gold.
Withal, they grew high, rough, and self-righteous; opposing further attainment;
too much forgetting the day of their infancy and littleness,
which gave them something of a real beauty; insomuch that many left them,
and all visible churches and societies,
and wandered up and down as sheep without a shepherd, and as doves without their mates;
seeking their beloved, but could not find him, as their souls desired to know him,
whom their souls loved above their chiefest joy.

These people were called Seekers by some, and the Family of Love by others; because,
as they came to the knowledge of one another, they sometimes met together,
not formally to pray or preach at appointed times or places, in their own wills,
as in times past they were accustomed to do, but waited together in silence;
and as anything rose in any one of their minds,
that they thought savoured of a divine spring, they sometimes spoke.
But so it was, that some of them not keeping in humility, and in the fear of God,
after the abundance of revelation, were exalted above measure;
and for want of staying their minds in an humble
dependance upon him that opened their understandings,
to see great things in his law, they ran out in their own imaginations,
and mixing them with those divine openings, brought forth a monstrous birth,
to the scandal of those that feared God,
and waited daily in the temple not made with hands, for the consolation of Israel;
the Jew inward, and circumcision in spirit.

This people obtained the name of Ranters, from their extravagant discourses and practices.
For they interpreted Christ`'s fulfilling of the law for us,
to be a discharging of us from any obligation and duty the law required of us,
instead of the condemnation of the law for sins past, upon faith and repentance:
and that now it was no sin to do that which before it was a sin to commit;
the slavish fear of the law being taken off by Christ, and all things good that man did,
if he did but do them with the mind and persuasion that it was so.
Insomuch that divers fell into gross and enormous practices;
pretending in excuse thereof, that they could, without evil,
commit the same act which was sin in another to do:
thereby distinguishing between the action and the evil of it,
by the direction of the mind, and intention in the doing of it.
Which was to make sin super-abound by the aboundings of grace,
and to turn from the grace of God into wantonness; a securer way of sinning than before:
as if Christ came not to save us from our sins, but in our sins; not to take away sin,
but that we might sin more freely at his cost, and with less danger to ourselves.
I say, this ensnared divers,
and brought them to an utter and lamentable loss as to their eternal state;
and they grew very troublesome to the better sort of people,
and furnished the looser with an occasion to profane.
