== Chapter II.

[.blurb]
=== Of the rise of this People, their fundamental principle, and doctrine, and practice, in twelve points resulting from it: their progress and sufferings: an expostulation with England thereupon.

At was about that very time, as you may see in George Fox`'s annals, that the eternal,
wise, and good God, was pleased, in his infinite love,
to honour and visit this benighted and bewildered nation,
with his glorious day-spring from on high; yea,
with a more sure and certain sound of the word of light and life,
through the testimony of a chosen vessel, to an effectual and blessed purpose,
can many thousands say, glory be to the name of the Lord forever!

For as it reached the conscience, and broke the heart,
and brought many to a sense and search,
so that which people had been vainly seeking without, with much pains and cost, they,
by this ministry, found within, where it was they wanted what they sought for,
viz. the right way to peace with God.
For they were directed to the light of Jesus Christ within them,
as the seed and leaven of the kingdom of God; near all, because in all,
and God`'s talent to all: a faithful and true witness, and just monitor in every bosom.
The gift and grace of God to life and salvation, that appears to all,
though few regard it.
This the traditional Christian, conceited of himself,
and strong in his own will and righteousness, overcome with blind zeal and passion,
either despised as a low and common thing, or opposed as a novelty,
under many hard names and opprobrious terms; denying, in his ignorant and angry mind,
any fresh manifestations of God`'s power and spirit in man, in these days,
though never more needed to make true Christians.
Not unlike those Jews of old, that rejected the Son of God,
at the very same time that they blindly professed to wait for the Messiah to come;
because, alas! he appeared not among them according to their carnal mind and expectation.

This brought forth many abusive books, which filled the greater sort with envy,
and lesser with rage;
and made the way and progress of this blessed testimony strait and narrow, indeed,
to those that received it.
However, God owned his own work, and this testimony did effectually reach, gather,
comfort, and establish the weary and heavy laden, the hungry and thirsty,
the poor and needy, the mournful and sick of many maladies,
that had spent all upon physicians of no value, and waited for relief from heaven,
help only from above; seeing, upon a serious trial of all things,
nothing else would do but Christ himself; the light of his countenance,
a touch of his garment, and help from his hand, who cured the poor woman`'s issue,
raised the centurion`'s servant, the widow`'s son, the ruler`'s daughter,
and Peter`'s mother:
and like her they no sooner felt his power and efficacy upon their souls,
but they gave up to obey him in a testimony to his power:
and that with resigned wills and faithful hearts, through all mockings, contradictions,
confiscations, beatings, prisons,
and many other jeopardies that attended them for his blessed name`'s sake.

And, truly, they were very many, and very great;
so that in all human probability they must have been swallowed up quick
of the proud and boisterous waves that swelled and beat against them,
but that the God of all their tender mercies was with them in his glorious authority;
so that the hills often fled, and the mountains melted before the power that filled them;
working mightily for them, as well as in them; one ever following the other.
By which they saw plainly, to their exceeding great confirmation and comfort,
that all things were possible with him with whom they had to do.
And that the more that which God required seemed to cross man`'s wisdom,
and expose them to man`'s wrath,
the more God appeared to help and carry them through all to his glory.

Insomuch, that if ever any people could say in truth, Thou art our sun and our shield,
our rock and sanctuary; and by thee we have leaped over a wall,
and by thee we have run through a troop,
and by thee we have put the armies of the aliens to flight;
these people had a right to say it.
And as God had delivered their souls of the wearisome burdens of sin and vanity,
and enriched their poverty of spirit,
and satisfied their great hunger and thirst after eternal righteousness,
and filled them with the good things of his own house,
and made them stewards of his manifold gifts;
so they went forth to all quarters of these nations,
to declare to the inhabitants thereof, what God had done for them; what they had found,
and where and how they had found it, viz.--The way to peace with God:
inviting all to come and see, and taste for themselves,
the truth of what they declared unto them.

And as their testimony was to the principle of God in man,
the precious pearl and leaven of the kingdom,
as the only blessed means appointed of God to quicken, convince, and sanctify man;
so they opened to them what it was in itself, and what it was given to them for;
how they might know it from their own spirit,
and that of the subtle appearance of the evil one:
and what it would do for all those whose minds should
be turned off from the vanity of the world,
and its lifeless ways and teachers, and adhere to his blessed light in themselves,
which discovers and condemns sin in all its appearances, and shows how to overcome it,
if minded and obeyed in its holy manifestations and convictions: giving power to such,
to avoid and resist those things that do not please God, and to grow strong in love,
faith, and good works.
That so man, whom sin hath made as a wilderness, over-run with briers and thorns,
might become as the garden of God, cultivated by his divine power,
and replenished with the most virtuous and beautiful
plants of God`'s own right-hand planting,
to his eternal praise.

But these experimental preachers of glad tidings of God`'s
truth and kingdom could not run when they list,
or pray or preach when they pleased,
but as Christ their Redeemer prepared and moved them by his own blessed Spirit,
for which they waited in their services and meetings,
and spoke as that gave them utterance; and which was as those having authority,
and not like the dry, and formal Pharisees.
And so it plainly appeared to the serious-minded,
whose spiritual eye the Lord Jesus had in any measure opened:
so that to one was given the word of exhortation, to another the word of reproof,
to another the word of consolation, and all by the same Spirit,
and in the good order thereof, to the convincing and edifying of many.

And, truly, they waxed strong and bold through faithfulness;
and by the power and Spirit of the Lord Jesus became very fruitful; thousands,
in a short time, being turned to the truth in the inward parts,
through their testimony in ministry and sufferings: insomuch as, in most counties,
and many of the considerable towns of England, meetings were settled;
and daily there were added such as should be saved.
For they were diligent to plant and to water,
and the Lord blessed their labours with an exceeding great increase;
notwithstanding all the opposition made to their blessed progress, by false rumours,
calumnies, and bitter persecutions; not only from the powers of the earth,
but from every one that listed to injure and abuse them: so that they seemed, indeed,
to be as poor sheep appointed to the slaughter, and as a people killed all the day long.

It were fitter for a volume than a preface,
but so much as to repeat the contents of their cruel sufferings;
from professors as well as from profane, and from magistrates as well as the rabble:
that it may be said of this abused and despised people, they went forth weeping,
and sowed in tears, bearing testimony to the precious seed, even the seed of the kingdom,
which stands not in words, the finest, the highest that man`'s wit can use; but in power,
the power of Christ Jesus,
to whom God the Father hath given all power in heaven and in earth,
that he might rule angels above, and men below.
Who empowered them, as their work witnesseth,
by the many that were turned through their ministry, from darkness to light,
and out of the broad into the narrow way of life and peace: bringing people to a weighty,
serious, and God-like conversation; the practice of that doctrine which they taught.

And as without this secret divine power,
there is no quickening and regenerating of dead souls,
so the want of this generating and begetting power and life,
is the cause of the little fruit that the many ministries,
that have been and are in the world, bring forth.
O that both ministers and people were sensible of this!
My soul is often troubled for them,
and sorrow and mourning compass me about for their sakes.
O that they were wise!
O that they would consider,
and lay to heart the things that truly and substantially make for their lasting peace!

Two things are to be considered; the doctrine they taught,
and the example they led among all people.
I have already touched upon their fundamental principle,
which is as the corner-stone of their fabric: and, indeed,
to speak eminently and properly, their characteristic,
or main distinguishing point or principle, viz. the light of Christ within,
as God`'s gift for man`'s salvation.
This, I say,
is as the root of the goodly tree of doctrines that grew and branched out from it,
which I shall now mention in their natural and experimental order.

[.numbered-group]
====

[.numbered]
_First,_ repentance from dead works to serve the living God.
Which comprehends three operations.
First, a sight of sin.
Secondly, a sense and godly sorrow for sin.
Thirdly, an amendment for the time to come.
This was the repentance they preached and pressed,
and a natural result from the principle they turned all people unto.
For of light came sight; and of sight came sense and sorrow;
and of sense and sorrow came amendment of life.
Which doctrine of repentance leads to justification; that is,
forgiveness of the sins that are past, through Christ the alone propitiation,
and the sanctification or purgation,
of the soul from the defiling nature and habits of sin present,
by the Spirit of Christ in the soul;
which is justification in the complete sense of that word:
comprehending both justification from the guilt of the sins that are past,
as if they had never been committed, through the love and mercy of God in Christ Jesus;
and the creature`'s being made inwardly just,
through the cleansing and sanctifying power and Spirit of Christ revealed in the soul;
which is commonly called sanctification.
But none can come to know Christ to be their sacrifice,
that reject him as their sanctifier:
the end of his coming being to save his people from the nature and defilement,
as well as guilt of sin; and, therefore, those that resist his light and Spirit,
make his coming and offering of none effect to them.

[.numbered]
From hence sprang a _second_ doctrine they were led to declare,
as the mark of the prize of the high calling to all true Christians,
viz. Perfection from sin, according to the scriptures of truth;
which testify it to be the end of Christ`'s coming, and the nature of his kingdom,
and for which his Spirit was and is given,
viz. to be perfect as our Heavenly Father is perfect, and holy, because God is holy.
And this the apostles laboured for,
that the Christians should be sanctified throughout in body, soul, and spirit;
but they never held a perfection in wisdom and glory in this life,
or from natural infirmities, or death, as some have, with a weak or ill mind,
imagined and insinuated against them.

This they called a redeemed state, regeneration, or the new birth: teaching everywhere,
according to their foundation, that unless this work was known,
there was no inheriting of the kingdom of God.

[.numbered]
_Thirdly,_ this leads to an acknowledgment of eternal rewards and punishments,
as they have good reason; for else, of all people, certainly they must be most miserable,
who, for above forty years, have been exceeding great sufferers for their profession;
and, in some cases, treated worse than the worst of men; yea,
as the refuse and off-scouring of all things.

====

This was the purport of their doctrine and ministry; which for the most part,
is what other professors of Christianity pretend to hold in words and forms,
but not in the power of godliness; which, generally speaking,
has been long lost by men`'s departing from that
principle and seed of life that is in man,
and which man has not regarded, but lost the sense of;
and in and by which he can only be quickened in his
mind to serve the living God in newness of life.
For as the life of religion was lost,
and the generality lived and worshipped God after their own wills,
and not after the will of God, nor the mind of Christ,
which stood in the works and fruits of the Holy Spirit; so that which these pressed,
was not notion, but experience; not formality, but godliness;
as being sensible in themselves, through the work of God`'s righteous judgments,
that without holiness no man shall ever see the Lord with comfort.

Besides these general doctrines, as the larger branches,
there sprang forth several particular doctrines,
that did exemplify and farther explain the truth
and efficacy of the general doctrine before observed,
in their lives and examples.
As,

[.numbered-group]
====

[.numbered]
I+++.+++ Communion and loving one another.
This is a noted mark in the mouths of all sorts of people concerning them:
they will meet, they will help and stick one to another:
whence it is common to hear some say,
"`Look how the Quakers love and take care of one another.`"
Others, less moderate, will say,
"`The Quakers love none but themselves:`" and if loving one another,
and having an intimate communion in religion, and constant care to meet to worship God,
and help one another, be any mark of primitive Christianity, they had it,
blessed be the Lord, in an ample manner.

[.numbered]
II. To love enemies.
This they both taught and practised.
For they did not only refuse to be revenged for injuries done them,
and condemned it as of an unchristian spirit; but they did freely forgive, yea,
help and relieve those that had been cruel to them,
when it was in their power to have been even with them:
of which many and singular instances might be given: endeavouring,
through faith and patience, to overcome all injustice and oppression,
and preaching this doctrine as Christian, for others to follow.

[.numbered]
III.
Another was, the sufficiency of truth-speaking,
according to Christ`'s own form of sound words, of yea, yea, and nay, nay,
among Christians, without swearing,
both from Christ`'s express prohibition to swear at all;^
footnote:[Mat.
v.]
and for that, they being under the tie and bond of truth in themselves,
there was no necessity for an oath;
and it would be a reproach to their Christian veracity to
assure their truth by such an extraordinary way of speaking;
simple and uncompounded answers, as yea and nay, without asseveration, attestation,
or supernatural vouchers, being most suitable to evangelical righteousness.
But offering, at the same time, to be punished to the full for false-speaking,
as others for perjury, if ever guilty of it: and hereby they exclude with all true,
all false and profane swearing; for which the land did and doth mourn,
and the great God was, and is, not a little offended with it.

[.numbered]
IV. Not fighting, but suffering, is another testimony peculiar to this people:
they affirm that Christianity teacheth people to beat their swords into plough-shares,
and their spears into pruning-hooks, and to learn war no more;
that so the wolf may lie down with the lamb, and the lion with the calf,
and nothing that destroys be entertained in the hearts of people:
exhorting them to employ their zeal against sin, and turn their anger against Satan,
and no longer war one against another;
because all wars and fightings come of men`'s own hearts`' lusts,
according to the apostle James, and not of the meek Spirit of Christ Jesus,
who is captain of another warfare, and which is carried on with other weapons.
Thus, as truth-speaking succeeded swearing, so faith and patience succeeded fighting,
in the doctrine and practice of this people.
Nor ought they for this to be obnoxious to civil government, since,
if they cannot fight for it, neither can they fight against it;
which is no mean security to any state.
Nor is it reasonable,
that people should be blamed for not doing more for others than they can do for themselves.
And, Christianity set aside, if the costs and fruits of war were well considered, peace,
with all its inconveniencies, is generally preferable.
But though they were not for fighting, they were for submitting to government, and that,
not only for fear, but for conscience-sake,
where government doth not interfere with conscience;
believing it to be an ordinance of God, and where it is justly administered,
a great benefit to mankind.
Though it has been their lot, through blind zeal in some, and interest in others,
to have felt the strokes of it with greater weight
and rigour than any other persuasion in this age;
whilst they of all others, religion set aside,
have given the civil magistrate the least occasion
of trouble in the discharge of his office.

[.numbered]
V+++.+++ Another part of the character of this people was, and is,
they refuse to pay tithes or maintenance to a national ministry;
and that for two reasons: the one is, they believe all compelled maintenance,
even to gospel-ministers, to be unlawful,
because expressly contrary to Christ`'s command, who said, "`Freely you have received,
freely give:`" at least, that the maintenance of gospel-ministers should be free,
and not forced.
The other reason of their refusal is, because these ministers are not gospel ones,
in that the Holy Ghost is not their foundation, but human arts and parts.
So that it is not matter of humour or sullenness, but pure conscience towards God,
that they cannot help to support national ministries where they dwell,
which are but too much and too visibly become ways of worldly advantage and preferment.

[.numbered]
VI. Not to respect persons, was, and is, another of their doctrines and practices,
for which they were often buffeted and abused.
They affirmed it to be sinful to give flattering titles,
or to use vain gestures and compliments of respect.
Though to virtue and authority they ever made a deference;
but after their plain and homely manner, yet sincere and substantial way:
well remembering the examples of Mordecai and Elihu;
but more especially the command of their Lord and Master Jesus Christ,
who forbade his followers to call men Rabbi, which implies Lord or Master;
also the fashionable greetings and salutations of those times;
that so self-love and honour, to which the proud mind of man is incident,
in his fallen state, might not be indulged, but rebuked.
And though this rendered their conversation disagreeable,
yet they that will remember what Christ said to the Jews,
"`How can you believe which receive honour one of another?`"
will abate of their resentment, if his doctrine has any credit with them.

[.numbered]
VII.
They also used the plain language of Thee and Thou, to a single person,
whatever was his degree among men.
And, indeed,
the wisdom of God was much seen in bringing forth this people in so plain an appearance.
For it was a close and distinguishing test upon the spirits of those they came among;
showing their insides, and what predominated,
notwithstanding their high and great profession of religion.
This among the rest sounded harsh to many of them, and they took it ill,
forgetting the language they use to God in their own prayers,
and the common style of the scriptures,
and that it is an absolute and essential propriety of speech.
And what good, alas! had their religion done them,
who were so sensibly touched with indignation for the use of this plain, honest,
and true speech?

[.numbered]
VIII.
They recommended silence by their example, having very few words upon all occasions.
They were at a word in dealing: nor could their customers, with many words,
tempt them from it, having more regard to truth than custom, to example than gain.
They sought solitude: but when in company, they would neither use,
nor willingly hear unnecessary or unlawful discourses:
whereby they preserved their minds pure and undisturbed from unprofitable thoughts,
and diversions.
Nor could they humour the custom of Good Night, Good Morrow, God Speed;
for they knew the night was good, and the day was good, without wishing of either;
and that in the other expression,
the holy name of God was too lightly and unthankfully used, and therefore taken in vain.
Besides, they were words and wishes of course, and are usually as little meant,
as are love and service in the custom of cap and knee; and superfluity in those,
as well as in other things, was burdensome to them; and therefore,
they did not only decline to use them,
but found themselves often pressed to reprove the practice.

[.numbered]
IX. For the same reason they forbore drinking to people, or pledging of them,
as the manner of the world is: a practice that is not only unnecessary,
but they thought evil in the tendencies of it,
being a provocation to drink more than did people good,
as well as that it was in itself vain and heathenish.

[.numbered]
X+++.+++ Their way of marriage is peculiar to them;
and shows a distinguishing care above other societies professing Christianity.
They say, that marriage is an ordinance of God,
and that God only can rightly join man and woman in marriage.
Therefore, they use neither priest nor magistrate;
but the man and woman concerned take each other as husband and wife,
in the presence of divers credible witnesses, promising to each other,
with God`'s assistance, to be loving and faithful in that relation,
till death shall separate them.
But antecedent to this,
they first present themselves to the monthly meeting
for the affairs of the church where they reside;
there declaring their intentions to take one another as husband and wife,
if the said meeting have nothing material to object against it.
They are constantly asked the necessary questions, as in case of parents or guardians,
if they have acquainted them with their intention, and have their consent, etc.
The method of the meeting is, to take a minute thereof,
and to appoint proper persons to inquire of their
conversation and clearness from all others,
and whether they have discharged their duty to their parents or guardians;
and to make report thereof to the next monthly meeting,
where the same parties are desired to give their attendance.
In case it appears they have proceeded orderly, the meeting passes their proposal,
and so records it in their meeting book.
And in case the woman be a widow, and hath children,
due care is there taken that provision also be made by her for the orphans,
before the meeting pass the proposals of marriage: advising the parties concerned,
to appoint a convenient time and place, and to give fitting notice to their relations,
and such friends and neighbours,
as they desire should be the witnesses of their marriage:
where they take one another by the hand, and by name promise reciprocally,
love and fidelity, after the manner before expressed.
Of all which proceedings, a narrative in way of certificate is made,
to which the said parties first set their hands,
thereby confirming it as their act and deed; and then divers relations, spectators,
and auditors, set their names as witnesses of what they said and signed.
And this certificate is afterward registered in the record belonging to the meeting,
where the marriage is solemnized.
Which regular method has been, as it deserves, adjudged in courts of law a good marriage,
where it has been by cross and ill people disputed and contested,
for want of the accustomed formalities of priest and ring,
etc.--ceremonies they have refused, not out of humour,
but conscience reasonably grounded; inasmuch as no scripture example tells us,
that the priest had any other part, of old time, than that of a witness among the rest,
before whom the Jews used to take one another: and, therefore,
this people look upon it as an imposition,
to advance the power and profits of the clergy: and for the use of the ring,
it is enough to say, that it was a heathenish and vain custom,
and never in practice among the people of God, Jews, or primitive Christians.
The words of the usual form,
as "`with my body I thee worship,`" etc. are hardly defensible.
In short, they are more careful, exact, and regular, than any form now used;
and it is free of the inconveniences, with which other methods are attended;
their care and checks being so many, and such,
as that no clandestine marriages can be performed among them.

[.numbered]
XI. It may not be unfit to say something here of their births and burials,
which make up so much of the pomp of too many called Christians.
For births, the parents name their own children;
which is usually some days after they are born, in the presence of the midwife,
if she can be there, and those that were at the birth,
who afterwards sign a certificate for that purpose prepared,
of the birth and name of the child or children; which is recorded in a proper book,
in the monthly-meeting to which the parents belong;
avoiding the accustomed ceremonies and festivals.

[.numbered]
XII.
Their burials are performed with the same simplicity.
If the body of the deceased be near any public meeting-place,
it is usually carried thither,
for the more convenient reception of those that accompany it to the burying-ground.
And it so falls out sometimes, that while the meeting is gathering for the burial,
some or other has a word of exhortation, for the sake of the people there met together.
After which the body is borne away by young men,
or else those that are of their neighbourhood,
or those that were most of the intimacy of the deceased party:
the corpse being in a plain coffin, without any covering or furniture upon it.
At the ground they pause some time before they put the body into its grave,
that if any there should have anything upon them to exhort the people,
they may not be disappointed;
and that the relations may the more retiredly and solemnly
take the last leave of the body of their departed kindred,
and the spectators have a sense of mortality, by the occasion then given them,
to reflect upon their own latter end.
Otherwise, they have no set rites or ceremonies on those occasions.
Neither do the kindred of the deceased ever wear mourning;
they looking upon it as a worldly ceremony and piece of pomp;
and that what mourning is fit for a Christian to have,
at the departure of a beloved relation or friend, should be worn in the mind,
which is only sensible of the loss: and the love they had to them,
and remembrance of them, to be outwardly expressed by a respect to their advice,
and care of those they have left behind them, and their love of that they loved.
Which conduct of theirs, though unmodish or unfashionable,
leaves nothing of the substance of things neglected or undone;
and as they aim at no more,
so that simplicity of life is what they observe with great satisfaction;
though it sometimes happens not to be without the
mockeries of the vain world they live in.

These things gave them a rough and disagreeable appearance with the generality;
who thought them turners of the world upside down, as, indeed, in some sense they were:
but in no other than that wherein Paul was so charged,
viz. To bring things back into their primitive and right order again.
For these and such like practices of theirs were not the result of humour,
or for civil distinction, as some have fancied; but a fruit of inward sense,
which God through his holy fear, had begotten in them.
They did not consider how to contradict the world,
or distinguish themselves as a party from others; it being none of their business,
as it was not their interest; no, it was not the result of consultation,
or a framed design, by which to declare or recommend schism or novelty.
But God having given them a sight of themselves,
they saw the whole world in the same glass of truth;
and sensibly discerned the affections and passions of men,
and the rise and tendency of things; what it was that gratified the lust of the flesh,
the lust of the eye, and the pride of life, which are not of the Father,
but of the world.
And from thence sprang, in the night of darkness and apostacy,
which hath been over people through their degeneration from the light and Spirit of God,
these and many other vain customs, which are seen,
by the heavenly day of Christ that dawns in the soul,
to be either wrong in their original, or, by time and abuse, hurtful in their practice.
And though these things seemed trivial to some,
and rendered these people stingy and conceited in such persons`' opinion;
there was and is more in them, than they were, or are, aware of.

It was not very easy to our primitive friends to make themselves sights and spectacles,
and the scorn and derision of the world;
which they easily foresaw must be the consequence
of so unfashionable a conversation in it:
but here was the wisdom of God seen in the foolishness of these things; first,
that they discovered the satisfaction and concern
that people had in and for the fashions of this world,
notwithstanding their high pretences to another:
in that any disappointment about them came so very near them,
as that the greatest honesty, virtue, wisdom, and ability, were unwelcome without them.
Secondly, it seasonably and profitably divided conversation;
for this making their society uneasy to their relations and acquaintance,
it gave them the opportunity of more retirement and solitude;
wherein they met with better company, even the Lord God their Redeemer;
and grew strong in his love, power, and wisdom;
and were thereby better qualified for his service.
And the success abundantly showed it, blessed be the name of the Lord.

And though they were not great and learned in the esteem of this world,
(for then they had not wanted followers upon their own credit and authority,) yet they
were generally of the most sober of the several persuasions they were in,
and of the most repute for religion; and many of them of good capacity, substance,
and account among men.

And also some among them wanted not for parts, learning, or estate;
though then as of old, not many wise, or noble, etc., were called; or, at least,
received the heavenly call,
because of the cross that attended the profession of it in sincerity.
But neither do parts or learning make men the better Christians,
though the better orators and disputants;
and it is the ignorance of people about the divine gift,
that causes that vulgar and mischievous mistake.
Theory and practice, speculation and enjoyment, words and life, are two things.
O! it is the penitent, the reformed, the lowly, the watchful, the self-denying,
and holy soul, that is the Christian!
And that frame is the fruit and work of the Spirit, which is the life of Jesus;
whose life, though hid in the fulness of it in God the Father,
is shed abroad in the hearts of them that truly believe, according to their capacity.
O that people did but know this to cleanse them, to circumcise them, to quicken them,
and to make them new creatures indeed! recreated, or regenerated,
after Christ Jesus unto good works; that they might live to God, and not to themselves;
and offer up living prayers and living praises to the living God,
through his own living Spirit, in which he is only to be worshipped in this gospel day.

O that they that read me could but feel me! for my heart is affected with this
merciful visitation of the Father of lights and spirits to this poor nation,
and the whole world through the same testimony.
Why should the inhabitants thereof reject it?
Why should they lose the blessed benefit of it?
Why should they not turn to the Lord with all their hearts, and say from the heart,
Speak Lord, for now thy poor servants hear: O that thy will may be done, thy great,
thy good, and holy will, in earth as it is in heaven! do it in us, do it upon us,
do what thou wilt with us; for we are thine, and desire to glorify thee our Creator,
both for that, and because thou art our Redeemer;
for thou art redeeming us from the earth, from the vanities and pollutions of it,
to be a peculiar people unto thee.
O! this were a brave day for England, if so she could say in truth! but alas,
the case is otherwise! for which some of thine inhabitants,
O land of my nativity! have mourned over thee with bitter wailing and lamentation.
Their heads have been, indeed, as waters, and their eyes as fountains of tears,
because of thy transgression and stiffneckedness; because thou wilt not hear, and fear,
and return to the Rock, even thy Rock, O England! from whence thou art hewn.
But be thou warned, O land of great profession, to receive him into thy heart.
Behold, at that door it is he hath stood so long knocking;
but thou wilt yet have none of him.
O! be thou awakened! lest Jerusalem`'s judgments do swiftly overtake thee,
because of Jerusalem`'s sins that abound in thee.
For she abounded in formality, but made void the weighty things of God`'s law,
as thou daily dost.

She withstood the Son of God in the flesh,
and thou resistest the Son of God in the Spirit.
He would have gathered her, as a hen gathereth her chickens under her wings,
and she would not; so would he have gathered thee out of thy lifeless profession,
and have brought thee to inherit substance; to have known his power and kingdom:
for which he often knocked within, by his grace and Spirit; and without,
by his servants and witnesses: but, on the contrary,
as Jerusalem of old persecuted the manifestation of the Son of God in the flesh,
and crucified him, and whipped and imprisoned his servants; so hast thou,
O land! crucified to thyself afresh the Lord of life and glory,
and done despite to his Spirit of grace; slighting the fatherly visitation,
and persecuting the blessed dispensers of it by thy laws and magistrates:
though they have early and late pleaded with thee in the power and Spirit of the Lord;
in love and meekness, that thou mightest know the Lord, and serve him,
and become the glory of all lands.

But thou hast evilly entreated and requited them,
thou hast set at nought all their counsel, and wouldst have none of their reproof,
as thou shouldst have had.
Their appearance was too straight,
and their qualifications were too mean for thee to receive them; like the Jews of old,
that cried, Is not this the Carpenter`'s Son, and are not his brethren among us;
which of the scribes, of the learned (the orthodox) believe in him?
Prophesying their fall in a year or two,
and making and executing of severe laws to bring it to pass:
endeavouring to terrify them out of their holy way,
or destroy them for abiding faithful to it.
But thou hast seen how many governments that rose against them,
and determined their downfall, have been overturned and extinguished,
and that they are still preserved, and become a great and a considerable people,
among the middle sort of thy numerous inhabitants.
And notwithstanding the many difficulties without and within,
which they have laboured under, since the Lord God eternal first gathered them,
they are an increasing people; the Lord still adding unto them, in divers parts,
such as shall be saved, if they persevere to the end.
And to thee, O England! were they, and are they lifted up as a standard,
and as a city set upon a hill, and to the nations round about thee,
that in their light thou mayst come to see light,
even in Christ Jesus the light of the world, and, therefore, thy light and life too,
if thou wouldst but turn from thy many evil ways, and receive and obey it.
"`For in the light of the Lamb must the nations of them
that are saved walk,`" as the scripture testifies.

Remember,
O nation of great profession! how the Lord has waited upon thee since the dawning reformation,
and the many mercies and judgments by which he has pleaded with thee;
and awake and arise out of thy deep sleep, and yet hear his word in thy heart,
that thou mayst live.

Let not this thy day of visitation pass over thy head,
nor neglect thou so great salvation as is this which is come to thy house,
O England! for why shouldst thou die?
O land that God desires to bless,
be assured it is he that has been in the midst of this people, in the midst of thee,
and not a delusion, as thy mistaken teachers have made thee believe.
And this thou shalt find by their marks and fruits,
if thou wilt consider them in the spirit of moderation.

====
