== Chapter III.

[.blurb]
=== Of the Qualifications of their Ministry. Eleven marks that it is Christian.

[.numbered-group]
====

[.numbered]
I+++.+++ They were changed men themselves, before they went about to change others.
Their hearts were rent, as well as their garments;
and they knew the power and work of God upon them.
And this was seen by the great alteration it made, and their stricter course of life,
and more godly conversation that immediately followed upon it.

[.numbered]
II. They went not forth, or preached, in their own time or will, but in the will of God;
and spoke not their own studied matters, but as they were opened and moved of his Spirit,
with which they were well acquainted in their own conversion:
which cannot be expressed to carnal men, so as to give them any intelligible account;
for to such it is, as Christ said, like the blowing of the wind,
which no man knows whence it cometh, or whither it goeth.
Yet this proof and seal went along with their ministry,
that many were turned from their lifeless professions, and the evil of their ways,
to an inward and experimental knowledge of God, and a holy life,
as thousands can witness.
And as they freely received what they had to say from the Lord,
so they freely administered it to others.

[.numbered]
III.
The bent and stress of their ministry was conversion to God; regeneration and holiness.
Not schemes of doctrines and verbal creeds, or new forms of worship:
but a leaving off in religion the superfluous,
and reducing the ceremonious and formal part, and pressing earnestly the substantial,
the necessary and profitable part to the soul; as all, upon a serious reflection,
must and do acknowledge.

[.numbered]
IV. They directed people to a principle in themselves, though not of themselves,
by which all that they asserted, preached, and exhorted others to,
might be wrought in them, and known to them, through experience, to be true;
which is a high and distinguishing mark of the truth of their ministry,
both that they knew what they said, and were not afraid of coming to the test.
For as they were bold from certainty,
so they required conformity upon no human authority, but upon conviction,
and the conviction of this principle,
which they asserted was in them that they preached unto:
and unto that they directed them,
that they might examine and prove the reality of
those things which they had affirmed of it,
as to its manifestation and work in man.
And this is more than the many ministers in the world pretended to.
They declare of religion, say many things true, in words, of God, Christ, and the Spirit;
of holiness and heaven; that all men should repent and amend their lives,
or they will go to hell, etc.
But which of them all pretend to speak of their own knowledge and experience;
or ever directed to a divine principle, or agent, placed of God in man, to help him;
and how to know it,
and wait to feel its power to work that good and acceptable will of God in them?

Some of them, indeed, have spoken of the spirit,
and the operations of it to sanctification, and performance of worship to God;
but where and how to find it, and wait in it, to perform our duty to God,
was yet as a mystery to be declared by this farther degree of reformation.
So that this people did not only in words, more than equally press repentance,
conversion, and holiness, but did it knowingly and experimentally; and directed those,
to whom they preached, to a sufficient principle; and told them where it was,
and by what tokens they might know it,
and which way they might experience the power and efficacy of it to their souls`' happiness.
Which is more than theory and speculation, upon which most other ministers depend:
for here is certainty;
a bottom upon which man may boldly appear before God in the great day of account.

[.numbered]
V+++.+++ They reached to the inward state and condition of people;
which is an evidence of the virtue of their principle, and of their ministering from it,
and not from their own imaginations, glosses, or comments upon scripture.
For nothing reaches the heart, but what is from the heart; or pierces the conscience,
but what comes from a living conscience; insomuch as it hath often happened,
where people have under secrecy revealed their state or condition to some choice friends,
for advice or ease,
they have been so particularly directed in the ministry of this people,
that they have challenged their friends with discovering their secrets,
and telling their preachers their cases, to whom a word hath not been spoken.
Yea, the very thoughts and purposes of the hearts of many have been so plainly detected,
that they have, like Nathaniel, cried out, of this inward appearance of Christ,
"`Thou art the Son of God, thou art the King of Israel.`"
And those that have embraced this divine principle,
have found this mark of its truth and divinity,
that the woman of Samaria did of Christ when in the flesh, to be the Messiah,
viz. It had told them all that ever they had done; shown them their insides,
the most inward secrets of their hearts, and laid judgment to the line,
and righteousness to the plummet;
of which thousands can at this day give in their witness.
So that nothing has been affirmed by this people,
of the power and virtue of this heavenly principle,
that such as have turned to it have not found true, and more;
and that one half had not been told to them of what they have seen of the power, purity,
wisdom, and goodness of God therein.

[.numbered]
VI. The accomplishments,
with which this principle fitted even some of the
meanest of this people for their work and service,
furnishing some of them with an extraordinary understanding in divine things,
and an admirable, fluency, and taking-way of expression, gave occasion to some to wonder,
saying of them, as of their Master, "`Is not this such a mechanic`'s son,
how came he by this learning?`"
As from thence others took occasion to suspect and insinuate they were Jesuits in disguise,
who had the reputation of learned men for an age past;
though there was not the least ground of truth for any such reflection;
in that their ministers are known, the places of their abode,
their kindred and education.

[.numbered]
VII.
That they came forth low, and despised, and hated, as the primitive Christians did;
and not by the help of worldly wisdom or power, as former reformations in part have done:
but in all things it may be said, this people were brought forth in the cross;
in a contradiction to the ways, worships, fashions, and customs of this world; yea,
against wind and tide, that so no flesh might glory before God.

[.numbered]
VIII.
They could have no design to themselves in this work,
thus to expose themselves to scorn and abuse; to spend and be spent;
leaving wife and children, house and land, and all that can be accounted dear to men,
with their lives in their hands, being daily in jeopardy,
to declare this primitive message revived in their spirits,
by the good Spirit and power of God, viz.

That God is light, and in him is no darkness at all;
and that he has sent his Son a light into the world,
to enlighten all men in order to salvation;
and that they that say they have fellowship with God, and are his children and people,
and yet walk in darkness, viz. in disobedience to the light in their consciences,
and after the vanity of this world, lie and do not the truth.
But that all such as love the light, and bring their deeds to it, and walk in the light,
as God is light, the blood of Jesus Christ his Son should cleanse them from all sin.
Thus John 1:4. 19. Chap.
iii. 20, 21. 1 John 1:5-7.

[.numbered]
IX. Their known great constancy and patience in suffering
for their testimony in all the branches of it;
and that sometimes unto death, by beatings, bruisings, long and crowded imprisonments,
and noisome dungeons: four of them in New England dying by the hands of the executioner,
purely for preaching amongst that people: besides banishments,
and excessive plunders and sequestrations of their goods and estates,
almost in all parts, not easily to be expressed, and less to have been endured,
but by those that have the support of a good and glorious cause;
refusing deliverance by any indirect ways or means, as often as it was offered unto them.

[.numbered]
X+++.+++ That they did not only not show any disposition to revenge,
when it was at any time in their power, but forgave their cruel enemies;
showing mercy to those that had none for them.

[.numbered]
XI. Their plainness with those in authority, like the ancient prophets,
not fearing to tell them to their faces, of their private and public sins;
and their prophesies to them of their afflictions and downfal,
when in the top of their glory: also of some national judgments, as of the plague,
and fire of London, in express terms; and likewise particular ones to divers persecutors,
which accordingly overtook them; and were very remarkable in the places where they dwelt,
which in time may be made public for the glory of God.

Thus, reader, thou seest this people in their rise, principles, ministry, and progress,
both their general and particular testimony; by which thou mayst be informed how,
and upon what foot, they sprang, and became so considerable a people.
It remains next, that I show also their care, conduct,
and discipline as a Christian and reformed society,
that they might be found living up to their own principles and profession.
And this the rather,
because they have hardly suffered more in their character
from the unjust charge of error,
than by the false imputation of disorder: which calumny, indeed,
has not failed to follow all the true steps that were ever made to reformation,
and under which reproach none suffered more than the primitive Christians themselves,
that were the honour of Christianity,
and the great lights and examples of their own and succeeding ages.
