== Chapter IV.

[.chapter-subtitle--blurb]
Of the discipline and practice of this people, as a religious society.
The church power they own and exercise, and that which they reject and condemn:
with the method of their proceedings against erring and disorderly persons.

This people increasing daily both in town and country,
a holy care fell upon some of the elders among them,
for the benefit and service of the church.
And the first business in their view, after the example of the primitive saints,
was the exercise of charity; to supply the necessities of the poor,
and answer the like occasions.
Wherefore collections were early and liberally made
for that and divers other services in the church,
and entrusted with faithful men, fearing God, and of good report,
who were not weary in well doing; adding often of their own in large proportions,
which they never brought to account, or desired should be known,
much less restored to them, that none might want,
nor any service be retarded or disappointed.

They were also very careful, that every one that belonged to them,
answered their profession in their behaviour among men, upon all occasions;
that they lived peaceably, and were in all things good examples.
They found themselves engaged to record their sufferings and services:
and in the case of marriage,
which they could not perform in the usual methods of the nation, but among themselves,
they took care that all things were clear between the parties and all others:
and it was then rare,
that any one entertained an inclination to a person on that account,
till he or she had communicated it secretly to some
very weighty and eminent friends among them,
that they might have a sense of the matter;
looking to the counsel and unity of their brethren as of great moment to them.
But because the charge of the poor, the number of orphans, marriages, sufferings,
and other matters, multiplied;
and that it was good that the churches were in some way
and method of proceeding in such affairs among them,
to the end they might the better correspond upon occasion,
where a member of one meeting might have to do with one of another; it pleased the Lord,
in his wisdom and goodness,
to open the understanding of the first instrument of this dispensation of life,
about a good and orderly way of proceeding;
who felt a holy concern to visit the churches in person throughout this nation,
to begin and establish it among them: and by his epistles,
the like was done in other nations and provinces abroad;
which he also afterwards visited, and helped in that service,
as shall be observed when I come to speak of him.

Now the care, conduct, and discipline, I have been speaking of,
and which are now practised among this people, is as followeth.

This godly elder, in every county where he travelled, exhorted them that some,
out of every meeting of worship, should meet together once in the month,
to confer about the wants and occasions of the church.
And, as the case required,
so those monthly meetings were fewer or more in number in every respective county;
four or six meetings of worship, usually making one monthly meeting of business.
And accordingly, the brethren met him from place to place, and began the said meetings,
viz. For the poor, orphans, orderly walking, integrity to their profession, births,
marriages, burials, sufferings, etc.
And that these monthly meetings should, in each county, make up one quarterly meeting,
where the most zealous and eminent friends of the county should assemble to communicate,
advise, and help one another, especially when any business seemed difficult,
or a monthly meeting was tender of determining a matter.

Also that these several quarterly meetings should
digest the reports of their monthly meetings,
and prepare one for each respective county, against the yearly meeting,
in which all quarterly meetings resolve; which is held in London:
where the churches in this nation, and other nations and provinces,
meet by chosen members of their respective counties,
both mutually to communicate their church affairs, and to advise,
and be advised in any depending case, to edification.
Also to provide a requisite stock for the discharge
of general expenses for general services in the church,
not needful to be here particularized.

At these meetings any of the members of the churches may come, if they please,
and speak their minds freely, in the fear of God, to any matter;
but the mind of each quarterly meeting, therein represented, is chiefly understood,
as to particular cases, in the sense delivered by the persons deputed,
or chosen for that service by the said meeting.

During their yearly meeting, to which their other meetings refer in their order,
and naturally resolve themselves, care is taken by a select number,
for that service chosen by the general assembly,
to draw up the minutes of the said meeting,
upon the several matters that have been under consideration therein,
to the end that the respective quarterly and monthly
meetings may be informed of all proceedings;
together with a general exhortation to holiness, unity, and charity.
Of all which proceedings in yearly, monthly, and quarterly meetings,
due record is kept by some one appointed for that service,
or that hath voluntarily undertaken it.
These meetings are opened and usually concluded in their solemn waiting upon God,
who is sometimes graciously pleased to answer them
with as signal evidences of his love and presence,
as in any of their meetings of worship.

It is further to be noted, that in these solemn assemblies for the churches`' service,
there is no one presides among them after the manner of the assemblies of other people;
Christ only being their President,
as he is pleased to appear in life and wisdom in any one or more of them, to whom,
whatever be their capacity or degree, the rest adhere with a firm unity,
not of authority, but conviction,
which is the divine authority and way of Christ`'s power and Spirit in his people:
making good his blessed promise, "`that he would be in the midst of his,
where and whenever they were met together in his name, even to the end of the world.`"
So be it.

Now it may be expected,
I should here set down what sort of authority is exercised by this people,
upon such members of their society as correspond not in their lives with their profession,
and that are refractory to this good and wholesome order settled among them:
and the rather,
because they have not wanted their reproach and sufferings from some tongues and pens,
upon this occasion, in a plentiful manner.

The power they exercise, is such as Christ has given to his own people,
to the end of the world, in the persons of his disciples, viz. To oversee, exhort,
reprove, and, after long suffering and waiting upon the disobedient and refractory,
to disown them, as any longer of their communion,
or that they will stand charged with the behaviour of such transgressors,
or their conversation, until they repent.
The subject matter about which this authority, in any of the foregoing branches of it,
is exercised, is, first, in relation to common and general practice.
And, secondly,
about those things that more strictly refer to their own character and profession,
and which distinguish them from all other professors of Christianity;
avoiding two extremes upon which many split, viz. persecution and libertinism, that is,
a coercive power to whip people into the temple; that such as will not conform,
though against faith and conscience, shall be punished in their persons or estates;
or leaving all loose and at large, as to practice;
and so unaccountable to all but God and the magistrate.
To which hurtful extreme, nothing has more contributed than the abuse of church power,
by such as suffer their passion and private interests to prevail with them,
to carry it to outward force and corporal punishment:
a practice they have been taught to dislike, by their extreme sufferings,
as well as their known principle for a universal liberty of conscience.

On the other hand,
they equally dislike an independency in society:--an unaccountableness,
in practice and conversation, to the rules and terms of their own communion,
and to those that are the members of it.
They distinguish between imposing any practice that immediately regards faith or worship,
which is never to be done or suffered, or submitted unto;
and requiring Christian compliance with those methods that only
respect church-business in its more civil part and concern;
and that regard the discreet and orderly maintenance of
the character of the society as a sober and religious community.
In short, what is for the promotion of holiness and charity,
that men may practise what they profess, live up to their own principles,
and not be at liberty to give the lie to their own profession without rebuke,
is their use and limit of church power.
They compel none to them, but oblige those that are of them to walk suitably,
or they are denied by them: that is all the mark they set upon them,
and the power they exercise, or judge a Christian society can exercise,
upon those that are members of it.

The way of their proceeding against such as have lapsed or transgressed, is this.
He is visited by some of them, and the matter of fact laid home to him,
be it any evil practice against known and general virtue,
or any branch of their particular testimony, which he, in common, professeth with them.
They labour with him in much love and zeal, for the good of his soul, the honour of God,
and reputation of their profession, to own his fault and condemn it,
in as ample a manner as the evil or scandal was given by him; which, for the most part,
is performed by some written testimony under the party`'s hand: and if it so happen,
that the party prove refractory, and is not willing to clear the truth they profess,
from the reproach of his or her evil doing or unfaithfulness, they,
after repeated entreaties and due waiting for a token of repentance,
give forth a paper to disown such a fact, and the party offending:
recording the same as a testimony of their care for the honour of the truth they profess.

And if he or she shall clear their profession and themselves,
by sincere acknowledgment of their fault, and godly sorrow for so doing,
they are received and looked upon again as members of their communion.
For as God, so his true people, upbraid no man after repentance.

This is the account I had to give of the people of God called Quakers, as to their rise,
appearance, principles, and practices, in this age of the world,
both with respect to their faith and worship, discipline and conversation.
And I judge it very proper in this place,
because it is to preface the journal of the first, blessed,
and glorious instrument of this work,
and for a testimony to him in his singular qualifications and services,
in which he abundantly excelled in this day,
and which are worthy to be set forth as an example to all succeeding times,
to the glory of the most high God,
and for a just memorial to that worthy and excellent man,
his faithful servant and apostle to this generation of the world.
