== Chapter V.

[.blurb]
=== Of the first instrument or person by whom God was pleased to gather this people into the way they profess. His name George Fox: his many excellent qualifications; showing a divine, and not a human power to have been their original in him. His troubles and sufferings both from without and within. His end and triumph.

I am now come to the third head or branch of my preface, viz. the instrumental author.
For it is natural for some to say, Well, here is the people and work,
but where and who was the man, the instrument?
He that in this age was sent to begin this work and people?
I shall, as God shall enable me, declare who and what he was;
not only by report of others, but from my own long and most inward converse,
and intimate knowledge of him; for which my soul blesseth God, as it hath often done:
and I doubt not, but by that time I have discharged myself of this part of my preface,
my serious readers will believe I had good cause so to do.

The blessed instrument of, and in this day of God, and of whom I am now about to write,
was George Fox, distinguished from another of that name,
by that other`'s addition of younger to his name, in all his writings;
not that he was so in years, but that he was so in the truth:
but he was also a worthy man, witness, and servant of God in his time.

But this George Fox was born in Leicestershire, about the year 1624.
He descended of honest and sufficient parents, who endeavoured to bring him up,
as they did the rest of their children, in the way and worship of the nation:
especially his mother,
who was a woman accomplished above most of her degree in the place where she lived.
But from a child he appeared of another frame of mind than the rest of his brethren;
being more religious, inward, still, solid, and observing beyond his years,
as the answers he would give, and the questions he would put, upon occasion, manifested,
to the astonishment of those that heard him, especially in divine things.

His mother, taking notice of his singular temper, and the gravity, wisdom, and piety,
that very early shined through him, refusing childish and vain sports, and company,
when very young, was tender and indulgent over him,
so that from her he met with little difficulty.
As to his employment, he was brought up in country business,
and as he took most delight in sheep, so he was very skilful in them;
an employment that very well suited his mind in several respects,
both for its innocency and solitude;
and was a just emblem of his after ministry and service.

I shall not break in upon his own account, which is by much the best that can be given,
and therefore desire what I can, to avoid saying anything of what is said already,
as to the particular passages of his coming forth: but, in general,
when he was somewhat above twenty, he left his friends,
and visited the most retired and religious people in those parts;
and some there were in this nation, who waited for the consolation of Israel,
night and day; as Zacharias, Anna, and good old Simeon did of old time.
To these he was sent, and these he sought out in the neighbouring counties,
and among them he sojourned till his more ample ministry came upon him.
At this time he taught, and was an example of, silence,
endeavouring to bring them from self-performances; testifying of, and turning them to,
the light of Christ within them, and encouraging them to wait in patience,
and to feel the power of it to stir in their hearts,
that their knowledge and worship of God might stand in the power of an endless life,
which was to be found in the light, as it was obeyed in the manifestation of it in man.
For in the word was life, and that life is the light of men: life in the word,
light in men; and life in men too, as the light is obeyed:
the children of the light living by the life of the word,
by which the word begets them again to God, which is the regeneration and new birth,
without which there is no coming into the kingdom of God: and to which whoever comes,
is greater than John; that is, than John`'s dispensation,
which was not that of the kingdom, but the consummation of the legal,
and fore-running of the gospel-times, the time of the kingdom.
Accordingly several meetings were gathered in those parts;
and thus his time was employed for some years.

In 1652, he being in his usual retirement, his mind exercised towards the Lord,
upon a very high mountain in some of the higher parts of Yorkshire, as I take it,
he had a vision of the great work of God in the earth,
and of the way that he was to go forth in a public ministry, to begin it.
He saw people as thick as motes in the sun,
that should in time be brought home to the Lord,
that there might be but one shepherd and one sheepfold in all the earth.
There his eye was directed northward,
beholding a great people that should receive him and his message in those parts.
Upon this mountain he was moved of the Lord to sound out his great and notable day,
as if he had been in a great auditory; and from thence went north,
as the Lord had shown him.
And in every place where he came, if not before he came to it,
he had his particular exercise and service shown to him,
so that the Lord was his leader indeed.
For it was not in vain that he travelled;
God in most places sealing his commission with the convincement of some of all sorts,
as well publicans as sober professors of religion.
Some of the first and most eminent of those that came forth in a public ministry,
and who are now at rest, were Richard Farnsworth, James Nayler, William Dewsberry,
Thomas Aldam, Francis Howgil, Edward Burroughs, John Camm, John Audland,
Richard Hubberthorn, T. Taylor, T. Holmes, Alexander Parker, Wm. Simson, William Caton,
John Stubbs, Robert Withers, Thomas Low, Josiah Coale, John Burnyeat, Robert Lodge,
Thomas Salthouse, and many more worthies, that cannot well be here named;
together with divers yet living of the first and great convincement; who,
after the knowledge of God`'s purging judgment in themselves,
and some time of waiting in silence upon him,
to feel and receive power from on high to speak in his name,
(which none else rightly can,
though they may use the same words,) felt its divine motions,
and were frequently drawn forth, especially to visit the public assemblies, to reprove,
inform, and exhort them: sometimes in markets, fairs, streets, and by the highway-side:
calling people to repentance,
and to turn to the Lord with their hearts as well as their mouths;
directing them to the light of Christ within them, to see, examine,
and consider their ways by, and to eschew the evil,
and do the good and acceptable will of God.
And they suffered great hardships for this their love and good-will; being often stocked,
stoned, beaten, whipped, and imprisoned, though honest men,
and of good report where they lived; that had left wives, children,
and houses and lands to visit them with a living call to repentance.
And though the priests generally set themselves to oppose them, and wrote against them,
and insinuated most false and scandalous stories to defame them,
stirring up the magistrates to suppress them, especially in those northern parts;
yet God was pleased to fill them with his living power,
and give them such an open door of utterance in his service,
that there was a mighty convincement over those parts.

And through the tender and singular indulgence of judge Bradshaw, and judge Fell,
and colonel West, in the infancy of things,
the priests were never able to gain the point they laboured for,
which was to have proceeded to blood; and, if possible, Herod-like,
by a cruel exercise of the civil power, to have cut them off,
and rooted them out of the country.
But especially judge Fell,
who was not only a check to their rage in the course of legal proceedings,
but otherwise upon occasion; and finally countenanced this people.
For, his wife receiving the truth with the first, it had that influence upon his spirit,
being a just and wise man,
and seeing in his own wife and family a full confutation
of all the popular clamours against the way of truth,
that he covered them what he could, and freely opened his doors,
and gave up his house to his wife and her friends;
not valuing the reproach of ignorant or evil-minded people:
which I here mention to his and her honour, and which will be, I believe,
an honour and a blessing to such of their name and family,
as shall be found in that tenderness, humility, love,
and zeal for the truth and people of the Lord.

That house was for some years, at first especially,
until the truth had opened its way into the southern parts of this island,
an eminent receptacle of this people.
Others, of good note and substance in those northern countries,
had also opened their houses, together with their hearts, to the many publishers, that,
in a short time, the Lord had raised to declare his salvation to the people;
and where meetings of the Lord`'s messengers were frequently held,
to communicate their services and exercises,
and comfort and edify one another in their blessed ministry.

But lest this may be thought a digression, having touched upon this before,
I return to this excellent man; and for his personal qualities, both natural, moral,
and divine, as they appeared in his converse with the brethren, and in the church of God,
take as follows:

[.numbered-group]
====

[.numbered]
I+++.+++ He was a man that God endued with a clear and wonderful depth:
a discerner of others`' spirits, and very much a master of his own.
And though that side of his understanding which lay next to the world,
and especially the expression of it, might sound uncouth and unfashionable to nice ears,
his matter was nevertheless very profound;
and would not only bear to be often considered, but the more it was so,
the more weighty and instructing it appeared.
And as abruptly and brokenly as sometimes his sentences would seem to fall from him,
about divine things,
it is well known they were often as texts to many fairer declarations.

And indeed it showed, beyond all contradiction, that God sent him,
in that no arts or parts had any share in the matter or manner of his ministry;
and that so many great, excellent, and necessary truths,
as he came forth to preach to mankind,
had therefore nothing of man`'s wit or wisdom to recommend them.
So that as to man he was an original, being no man`'s copy;
and his ministry and writings show they are from one that was not taught of man,
nor had learned what he said by study.
Nor were they notional or speculative, but sensible and practical truths,
tending to conversion and regeneration,
and the setting up of the kingdom of God in the hearts of men:
and the way of it was his work.
So that I have many times been overcome in myself, and been made to say,
with my Lord and Master, upon the like occasion, "`I thank thee, O Father,
Lord of heaven and earth,
that thou hast hid these things from the wise and prudent of this world,
and revealed them to babes:`" for,
many times hath my soul bowed in an humble thankfulness to the Lord,
that he did not choose any of the wise and learned
of this world to be the first messenger in our age,
of his blessed truth to men; but that he took one that was not of high degree,
or elegant speech, or learned after the way of this world,
that his message and work he sent him to do might come with less suspicion,
or jealousy of human wisdom and interest,
and with more force and clearness upon the consciences of those
that sincerely sought the way of truth in the love of it.
I say, beholding with the eye of my mind, which the God of heaven had opened in me,
the marks of God`'s finger and hand visibly in this testimony,
from the clearness of the principle, the power and efficacy of it,
in the exemplary sobriety, plainness, zeal, steadiness, humility, gravity, punctuality,
charity, and circumspect care in the government of church-affairs,
which shined in his and their life and testimony, that God employed in this work,
it greatly confirmed me that it was of God, and engaged my soul in a deep love, fear,
reverence, and thankfulness for his love and mercy therein to mankind:
in which mind I remain, and shall, I hope, through the Lord`'s strength,
to the end of my days.

[.numbered]
II. In his testimony or ministry,
he much laboured to open truth to the people`'s understandings,
and to bottom them upon the principle and principal, Christ Jesus the light of the world;
that by bringing them to something that was from God in themselves,
they might the better know and judge of him and themselves.

[.numbered]
III.
He had an extraordinary gift in opening the scriptures.
He would go to the marrow of things, and show the mind, harmony, and fulfilling of them,
with much plainness, and to great comfort and edification.

[.numbered]
IV. The mystery of the first and second Adam, of the fall and restoration,
of the law and gospel, of shadows and substance, of the servant`'s and Son`'s state,
and the fulfilling of the scriptures in Christ and by Christ the true light,
in all that are his, through the obedience of faith,
were much of the substance and drift of his testimonies:
in all which he was witnessed to be of God:
being sensibly felt to speak that which he had received of Christ,
and was his own experience, in that which never errs nor fails.

[.numbered]
V+++.+++ But, above all, he excelled in prayer.
The inwardness and weight of his spirit,
the reverence and solemnity of his address and behaviour,
and the fewness and fulness of his words,
have often struck even strangers with admiration,
as they used to reach others with consolation.
The most awful, living, reverent frame I ever felt or beheld, I must say,
was his in prayer.
And truly it was a testimony he knew and lived nearer to the Lord than other men;
for they that know Him most,
will see most reason to approach him with reverence and fear.

[.numbered]
VI. He was of an innocent life, no busy-body, nor self-seeker:
neither touchy nor critical: what fell from him was very inoffensive,
if not very edifying.
So meek, contented, modest, easy, steady, tender, it was a pleasure to be in his company.
He exercised no authority but over evil, and that everywhere, and in all; but with love,
compassion, and long-suffering.
A most merciful man, as ready to forgive, as unapt to take or give an offence.
Thousands can truly say, he was of an excellent spirit and savour among them,
and because thereof,
the most excellent spirits loved him with an unfeigned and unfading love.

[.numbered]
VII.
He was an incessant labourer: for in his younger time, before his many, great,
and deep sufferings and travels had enfeebled his body for itinerant services,
he laboured much in the word and doctrine, and discipline, in England, Scotland,
and Ireland, turning many to God, and confirming those that were convinced of the truth,
and settling good order, as to church affairs, among them.
And towards the conclusion of his travelling service, between the years 1671, and 1677,
he visited the churches of Christ in the plantations of America,
and in the United Provinces, and Germany, as his journal relates;
to the convincement and consolation of many.
After that time he chiefly resided in and about the city of London; and,
besides his labour in the ministry, which was frequent and serviceable, he wrote much,
both to them that are within, and those that are without, the communion.

But the care he took of the affairs of the church in general was very great.

[.numbered]
VIII.
He was often where the records of the business of the church are kept,
and where the letters from the many meetings of God`'s
people over all the world use to come:
which letters he had read to him, and communicated them to the meeting,
that is weekly held for such services;
and he would be sure to stir them up to answer them, especially in suffering cases,
showing great sympathy and compassion upon all such occasions;
carefully looking into the respective cases, and endeavouring speedy relief,
according to the nature of them.
So that the churches, or any of the suffering members thereof,
were sure not to be forgotten, or delayed in their desires, if he was there.

[.numbered]
IX. As he was unwearied, so he was undaunted in his services for God and his people;
he was no more to be moved to fear than to wrath.
His behaviour at Derby, Lichfield, Appleby, before Oliver Cromwell, at Launceston,
Scarborough, Worcester, and Westminster Hall, with many other places and exercises,
did abundantly evidence it, to his enemies as well as his friends.

====

But as, in the primitive times,
some rose up against the blessed apostles of our Lord Jesus Christ,
even from among those that they had turned to the hope of the gospel,
and became their greatest trouble;
so this man of God had his share of suffering from some that were convinced by him; who,
through prejudice or mistake, ran against him,
as one that sought dominion over conscience, because he pressed,
by his presence or epistles,
a ready and zealous compliance with such good and wholesome things,
as tended to an orderly conversation about the affairs of the church,
and in their walking before men.
That which contributed much to this ill work, was, in some,
a begrudging of this meek man the love and esteem
he had and deserved in the hearts of the people;
and weakness in others,
that were taken with their groundless suggestions of imposition and blind obedience.

They would have had every man independent, that as he had the principle in himself,
he should only stand and fall to that, and nobody else:
not considering that the principle is one in all;
and though the measure of light or grace might differ, yet the nature of it was the same;
and being so, they struck at the spiritual unity which a people,
guided by the same principle, are naturally led into: so that what is an evil to one,
is so to all; and what is virtuous, honest, and of good repute to one, is so to all,
from the sense and savour of the one universal principle which is common to all,
and which the disaffected also profess to be the root of all true Christian fellowship,
and that spirit into which the people of God drink, and come to be spiritually minded,
and of one heart and one soul.

Some weakly mistook good order in the government of church affairs,
for discipline in worship,
and that it was so pressed or recommended by him and other brethren.
And thereupon they were ready to reflect the same things that dissenters
had very reasonably objected upon the national churches,
that have coercively pressed conformity to their respective creeds and worships.
Whereas these things related wholly to conversation, and the outward, and, as I may say,
civil part of the church; that men should walk up to the principles of their belief,
and not be wanting in care and charity.
But though some have stumbled and fallen through mistakes,
and an unreasonable obstinacy even to a prejudice; yet, blessed be God,
the generality have returned to their first love, and seen the work of the enemy,
that loses no opportunity or advantage by which he may check or hinder the work of God,
and disquiet the peace of his church, and chill the love of his people to the truth,
and one to another; and there is hope of divers of the few that yet are at a distance.

In all these occasions, though there was no person the discontented struck so sharply at,
as this good man, he bore all their weakness and prejudice,
and returned not reflection for reflection;
but forgave them their weak and bitter speeches, praying for them,
that they might have a sense of their hurt,
and see the subtlety of the enemy to rend and divide,
and return into their first love that thought no ill.

And truly, I must say,
that though God had visibly clothed him with a divine preference and authority,
yet he never abused it; but held his place in the church of God with great meekness,
and a most engaging humility and moderation.
For upon all occasions, like his blessed Master, he was a servant to all;
holding and exercising his eldership in the invisible power that had gathered them,
with reverence to the Head, and care over the body: and was received,
only in that Spirit and power of Christ, as the first and chief elder in this age: who,
as he was therefore worthy of double honour,
so for the same reason it was given by the faithful of this day;
because his authority was inward and not outward,
and that he got it and kept it by the love of God, and power of an endless life.
I write my knowledge, and not report; and my witness is true;
having been with him for weeks and months together on divers occasions,
and those of the nearest, and most exercising nature; and that by night and by day,
by sea and by land; in this and in foreign countries; and I can say,
I never saw him out of his place, or not a match for every service or occasion.
For in all things he acquitted himself like a man, yea, a strong man,
a new and heavenly-minded man, a divine and a naturalist,
and all of God Almighty`'s making.
I have been surprised at his questions and answers in natural things:
that whilst he was ignorant of useless and sophistical science,
he had in him the grounds of useful and commendable knowledge,
and cherished it everywhere.
Civil, beyond all forms of breeding, in his behaviour: very temperate, eating little,
and sleeping less, though a bulky person.

Thus he lived and sojourned among us: and, as he lived, so he died;
feeling the same eternal power, that had raised and preserved him, in his last moments.
So full of assurance was he, that he triumphed over death;
and so even in his spirit to the last, as if death were hardly worth notice,
or a mention: recommending to some of us with him,
the dispatch and dispersion of an epistle just before given
forth by him to the churches of Christ throughout the world,
and his own books: but, above all, Friends; and of all Friends,
those in Ireland and America, twice over, saying,
"`Mind poor Friends in Ireland and America.`"

And to some that came in and inquired how he found himself, he answered, "`Never heed,
the Lord`'s power is over all weakness and death; the seed reigns,
blessed be the Lord:`" which was about four or five
hours before his departure out of this world.
He was at the great meeting near Lombard-street, on the first day of the week,
and it was the third following about ten at night when he left us;
being at the house of Henry Goldney, in the same court.
In a good old age he went,
after having lived to see his children`'s children in the truth to many generations.
He had the comfort of a short illness, and the blessing of a clear sense to the last:
and we may truly say, with a man of God of old, that being dead, he yet speaketh:
and though now absent in body, he is present in spirit;
neither time nor place being able to interrupt the communion of saints,
or dissolve the fellowship of the spirits of the just.
His works praise him, because they are to the praise of Him that wrought by him;
for which his memorial is and shall be blessed.
I have done, as to this part of my preface,
when I have left this short epitaph to his name,--Many
sons have done virtuously in this day;
but, dear George, thou excellest them all.
