== Chapter VI.

[.blurb]
=== Containing five several exhortations: first, general, reminding this people of their primitive integrity and simplicit. Secondly, in particular, to the ministry. Thirdly, to the young convinced. Fourthly, to the children of Friends. Fifthly, to those that are yet strangers to this people and way, to whom this book, and that which it was preface to, in its former edition, may come. All the several exhortations accommodated to their several states and conditions: that all may answer the end of God`'s glory, and their own salvation.

And now, Friends,
you that profess to walk in the way that this blessed
man was sent of God to turn us into,
suffer, I beseech you, the word of exhortation, as well fathers as children,
and elders as young men.
The glory of this day,
and foundation of the hope that has not made us ashamed since we were a people, you know,
is that blessed principle of light and life of Christ which we profess,
and direct all people to,
as the great and divine instrument and agent of man`'s conversion to God.
It was by this that we were first touched, and effectually enlightened,
as to our inward state; which put us upon the consideration of our latter end,
causing us to set the Lord before our eyes, and to number our days,
that we might apply our hearts to wisdom.
In that day we judged not after the sight of the eye, or after the hearing of the ear;
but according to the light and sense this blessed principle gave us,
so we judged and acted, in reference to things and persons, ourselves and others; yea,
towards God our Maker.
For being quickened by it in our inward man,
we could easily discern the difference of things,
and feel what was right and what was wrong, and what was fit, and what not,
both in reference to religion and civil concerns.
That being the ground of the fellowship of all saints,
it was in that our fellowship stood.
In this we desired to have a sense of one another, acted towards one another,
and all men; in love, faithfulness, and fear.

In feeling of the stirrings and motions of this principle in our hearts,
we drew near to the Lord, and waited to be prepared by it,
that we might feel drawings and movings before we approached the Lord in prayer,
or opened our mouths in ministry.
And in our beginning and ending with this, stood our comfort, service, and edification.
And as we ran faster, or fell short in our services,
we made burdens for ourselves to bear;
finding in ourselves a rebuke instead of an acceptance; and,
in lieu of "`Well-done,`" "`Who has required this at your hands?`"
In that day we were an exercised people, our very countenances and deportment declared it.

Care for others was then much upon us, as well as for ourselves;
especially of the young convinced.
Often had we the burden of the word of the Lord to our neighbours, relations,
and acquaintance; and sometimes strangers also.
We were in travail likewise for one another`'s preservation; not seeking, but shunning,
occasions of any coldness or misunderstanding;
treating one another as those that believed and felt God present;
which kept our conversation innocent, serious, and weighty;
guarding ourselves against the cares and friendships of the world.
We held the truth in the Spirit of it, and not in our own spirits,
or after our own wills and affections.

We were bowed and brought into subjection,
insomuch that it was visible to them that knew us.
We did not think ourselves at our own disposal, to go where we list,
or say or do what we list, or when we list.
Our liberty stood in the liberty of the Spirit of truth; and no pleasure, no profit,
no fear, no favour, could draw us from this retired, strict, and watchful frame.
We were so far from seeking occasions of company, that we avoided them what we could;
pursuing our own business with moderation,
instead of meddling with other people`'s unnecessarily.

Our words were few and savoury, our looks composed and weighty,
and our whole deportment very observable.
True it is, that this retired and strict sort of life,
from the liberty of the conversation of the world, exposed us to the censures of many,
as humourists, conceited and self-righteous persons, etc.;
but it was our preservation from many snares, to which others were continually exposed,
by the prevalency of the lust of the eye, the lust of the flesh, and the pride of life,
that wanted no occasions or temptations to excite
them abroad in the converse of the world.

I cannot forget the humility and chaste zeal of that day.
O! how constant at meetings, how retired in them; how firm to truth`'s life,
as well as truth`'s principles; and how entire and united in our communion, as, indeed,
became those that profess one head, even Christ Jesus the Lord.

This being the testimony and example the man of God before
mentioned was sent to declare and leave amongst us,
and we having embraced the same, as the merciful visitation of God to us,
the word of exhortation, at this time,
is that we continue to be found in the way of this testimony,
with all zeal and integrity, and so much the more, by how much the day draweth near.

And first, as to you my beloved and much honoured brethren in Christ,
that are in the exercise of the ministry: O! feel life in your ministry.
Let life be your commission, your well-spring and treasury on all such occasions; else,
you well know, there can be no begetting to God:
since nothing can quicken or make people alive to God, but the life of God;
and it must be a ministry in and from life, that enlivens any people to God.
We have seen the fruit of all other ministries,
by the few that are turned from the evil of their ways.
It is not our parts, or memory, the repetition of former openings,
in our own will and time, that will do God`'s work.
A dry doctrinal ministry, however sound in words, can reach but the ears,
and is but a dream at the best.
There is another soundness that is soundest of all, viz. Christ the power of God.
This is the key of David, that opens, and none shuts; and shuts and none can open:
as the oil to the lamp, and the soul to the body, so is that to the best of words:
which made Christ to say, "`My words, they are Spirit, and they are life;`" that is,
they are from life, and therefore they make you alive, that receive them.
If the disciples that had lived with Jesus,
were to stay at Jerusalem till they received it;
much more must we wait to receive before we minister,
if we will turn people from darkness to light, and from Satan`'s power to God.

I fervently bow my knees to the God and Father of our Lord Jesus Christ,
that you may always be like-minded;
that you may ever wait reverently for the coming and opening of the word of life,
and attend upon it in your ministry and service, that you may serve God in his Spirit.
And be it little, or be it much, it is well; for much is not too much,
and the least is enough, if from the motion of God`'s Spirit; and without it, verily,
never so little is too much, because to no profit.

For it is the Spirit of the Lord immediately, or through the ministry of his servants,
that teacheth his people to profit; and to be sure,
so far as we take him along with us in our services, so far we are profitable,
and no further.
For if it be the Lord that must work all things in us for our salvation,
much more is it the Lord that must work in us for the conversion of others.
If therefore it was once a cross to us to speak,
though the Lord required it at our hands, let it never be so to be silent,
when he does not.

It is one of the most dreadful sayings in the book of God,
"`That he that adds to the words of the prophecy of this book,
God will add to him the plagues written in this book.`"
To keep back the counsel of God, is as terrible;
"`For he that takes away from the words of the book of this prophecy,
God shall take away his part out of the book of life.`"
And truly, it has great caution in it, to those that use the name of the Lord,
to be well assured the Lord speaks;
that they may not be found of the number of those
that add to the words of the testimony of prophecy,
which the Lord giveth them to bear; nor yet to mince or diminish the same,
both being so very offensive to God.

Wherefore, Brethren, let us be careful, neither to out-go our guide,
nor yet loiter behind him; since he that makes haste may miss his way,
and he that stays behind lose his guide.
For even those that have received the word of the Lord, had need wait for wisdom,
that they may see how to divide the word aright: which plainly implieth,
that it is possible for one that hath received the word of the Lord,
to miss in the dividing and application of it;
which must come from an impatiency of spirit, and a self-working,
which makes an unsound and dangerous mixture,
and will hardly beget a right-minded living people to God.

I am earnest in this, above all other considerations, as to brethren in the ministry,
(well knowing how much it concerns the present and future
state and preservation of the church of Christ Jesus,
that has been gathered and built up by a living and
powerful ministry,) that the ministry be held,
preserved, and continued in the manifestations, motions,
and supplies of the same life and power, from time to time.

And wherever it is observed, that any do minister more from gifts and parts,
than life and power, though they have an enlightened and doctrinal understanding,
let them in time be advised and admonished for their preservation,
because insensibly such will come to depend upon a self-sufficiency;
to forsake Christ the living Fountain, and hew out unto themselves cisterns,
that will hold no living waters: and, by degrees,
such will come to draw others from waiting upon the gift of God in themselves,
and to feel it in others, in order to their strength and refreshment, to wait upon them,
and to turn from God to man again,
and so make shipwreck of the faith once delivered to the saints,
and of a good conscience towards God:
which are only kept by that divine gift of life that begat the one,
and awakened and sanctified the other in the beginning.

Nor is it enough, that we have known the divine gift,
and in it have reached to the spirits in prison,
and been the instruments of the convincing of others of the way of God,
if we keep not as low and poor in ourselves, and as depending upon the Lord, as ever:
since no memory, no repetitions of former openings, revelations, or enjoyments,
will bring a soul to God, or afford bread to the hungry, or water to the thirsty,
unless life go with what we say, and that must be waited for.

O that we may have no other fountain, treasure, or dependence!
That none may presume at any rate to act of themselves for God,
because they have long acted from God; that we may not supply want of waiting,
with our own wisdom,
or think that we may take less care and more liberty in speaking than formerly;
and that where we do not feel the Lord by his power, to open us and enlarge us,
whatever be the expectation of the people,
or has been our customary supply and character,
we may not exceed or fill up the time with our own.

I hope we shall ever remember, who it was that said,
"`Of yourselves you can do nothing;`" our sufficiency is in him.
And if we are not to speak our own words,
or take thought what we should say to men in our defence, when exposed for our testimony;
surely, we ought to speak none of our own words,
or take thought what we shall say in our testimony and ministry, in the name of the Lord,
to the souls of the people: for then, of all times, and of all other occasions,
should it be fulfilled in us, "`For it is not you that speak,
but the Spirit of my Father that speaketh in you.`"

And, indeed,
the ministry of the Spirit must and does keep its
analogy and agreement with the birth of the Spirit:
that as no man can inherit the kingdom of God, unless he be born of the Spirit;
so no ministry can beget a soul to God, but that which is from the Spirit.
For this, as I said before, the disciples waited before they went forth;
and in this our elder brethren and messengers of God in our day, waited, visited,
and reached to us; and having begun in the Spirit,
let none ever hope or seek to be made perfect in the flesh:
for what is the flesh to the Spirit, or the chaff to the wheat?
And if we keep in the Spirit, we shall keep in the unity of it,
which is the ground of true fellowship.
For by drinking into that one Spirit, we are made one people to God,
and by it we are continued in the unity of the faith, and the bond of peace.
No envying, no bitterness, no strife, can have place with us.
We shall watch always for good, and not for evil, one over another;
and rejoice exceedingly,
and not begrudge at one another`'s increase in the riches
of the grace with which God replenisheth his faithful servants.

And Brethren, as to you is committed the dispensation of the oracles of God,
which give you frequent opportunities,
and great place with the people among whom you travel, I beseech you,
that you would not think it sufficient to declare the word of life in their assemblies,
however edifying and comfortable such opportunities may be to you and them: but,
as was the practice of the man of God before mentioned, in great measure, when among us,
inquire the state of the several churches you visit;
who among them are afflicted or sick, who are tempted,
and if any are unfaithful or obstinate;
and endeavour to issue those things in the wisdom and power of God,
which will be a glorious crown upon your ministry.
As that prepares your way in the hearts of the people, to receive you as men of God,
so it gives you credit with them to do them good by your advice in other respects;
the afflicted will be comforted by you, the tempted strengthened, the sick refreshed,
the unfaithful convicted and restored, and such as are obstinate,
softened and fitted for reconciliation; which is clinching the nail,
and applying and fastening the general testimony,
by this particular care of the several branches of it,
in reference to them more immediately concerned in it.

For though good and wise men, and elders too, may reside in such places,
who are of worth and importance in the general, and in other places;
yet it does not always follow,
that they may have the room they deserve in the hearts of the people they live among;
or some particular occasion may make it unfit for him or them to use that authority.
But you that travel as God`'s messengers, if they receive you in the greater,
shall they refuse you in the less?
And if they own the general testimony,
can they withstand the particular application of it in their own cases?
Thus ye will show yourselves workmen indeed, and carry your business before you,
to the praise of his name that hath called you from darkness to light,
that you might turn others from Satan`'s power unto God and his kingdom, which is within.
And O that there were more of such faithful labourers in the vineyard
of the Lord!--Never more need since the day of God.

Wherefore I cannot but cry and call aloud to you,
that have been long professors of the truth,
and know the truth in the convincing power of it,
and have had a sober conversation among men;
yet content yourselves only to know truth for yourselves, to go to meetings,
and exercise an ordinary charity in the church, and an honest behaviour in the world,
and limit yourselves within those bounds; feeling little or no concern upon your spirits,
for the glory of the Lord in the prosperity of his truth in the earth,
more than to be glad that others succeed in such service.
Arise ye in the name and power of the Lord Jesus!
Behold how white the fields are unto harvest, in this and other nations,
and how few able and faithful labourers there are to work therein!
Your country-folks, neighbours, and kindred, want to know the Lord and his truth,
and to walk in it.
Does nothing lie at your door upon their account!
Search and see, and lose no time, I beseech you, for the Lord is at hand.

I do not judge you; there is one that judgeth all men, and his judgment is true.
You have mightily increased in your outward substance,
may you equally increase in your inward riches, and do good with both,
while you have a day to do good.
Your enemies would once have taken what you had, from you,
for his name`'s sake in whom you have believed;
wherefore he has given you much of the world, in the face of your enemies.
But O, let it be your servant,
and not your master! your diversion rather than your
business! let the Lord be chiefly in your eye,
and ponder your ways, and see if God has nothing more for you to do:
and if you find yourselves short in your account with him, then wait for his preparation,
and be ready to receive the word of command, and be not weary of well-doing,
when you have put your hand to the plough; and, assuredly, you shall reap,
if you faint not, the fruit of your heavenly labour in God`'s everlasting kingdom.

And you, young convinced ones,
be you entreated and exhorted to a diligent and chaste waiting upon God,
in the way of his blessed manifestation and appearance of himself to you.
Look not out, but within: let not another`'s liberty be your snare:
neither act by imitation, but by sense and feeling of God`'s power in yourselves:
crush not the tender buddings of it in your souls, nor over-run,
in your desires and warmness of affections, the holy and gentle motions of it.
Remember it is a still voice that speaks to us in this day,
and that it is not to be heard in the noises and hurries of the mind;
but is distinctly understood in a retired frame.
Jesus loved and chose solitudes, often going to mountains, gardens, and sea sides,
to avoid crowds and hurries: to show his disciples it was good to be solitary,
and sit loose to the world.
Two enemies lie near your states, imagination and liberty; but the plain, practical,
living, holy truth, that has convinced you, will preserve you,
if you mind it in yourselves, and bring all thoughts, inclinations, and affections,
to the test of it, to see if they are wrought in God, or of the enemy,
or of your ownselves: so will a true taste, discerning, and judgment,
be preserved to you, of what you should do and leave undone.
And in your diligence and faithfulness in this way, you will come to inherit substance;
and Christ, the eternal wisdom, will fill your treasury.
And when you are converted, as well as convinced, then confirm your brethren;
and be ready to every good word and work, that the Lord shall call you to:
that you may be to his praise, who has chosen you to be partakers,
with the saints in light, of a kingdom that cannot be shaken,
an inheritance incorruptible in eternal habitations.

And now, as for you that are the children of God`'s people,
a great concern is upon my spirit for your good and often
are my knees bowed to the God of your fathers for you,
that you may come to be partakers of the same divine life and power,
that have been the glory of this day: that a generation you may be to God, a holy nation,
and a peculiar people, zealous of good works, when all our heads are laid in the dust.
O! you young men and women, let it not suffice you,
that you are the children of the people of the Lord; you must also be born again,
if you will inherit the kingdom of God.
Your fathers are but such after the flesh,
and could but beget you into the likeness of the first Adam;
but you must be begotten into the likeness of the second Adam, by a spiritual generation,
or you will not, you cannot, be of his children or offspring.
And therefore look carefully about you, O ye children of the children of God;
consider your standing, and see what you are in relation to this divine kindred, family,
and birth.
Have you obeyed the light, and received and walked in the Spirit,
which is the incorruptible seed of the word and kingdom of God,
of which you must be born again?
God is no respecter of persons.
The father cannot save or answer for the child, or the child for the father;
but in the sin thou sinnest thou shalt die; and in the righteousness thou doest,
through Christ Jesus, thou shalt live:
for it is the willing and obedient that shall eat the good of the land.
Be not deceived, God is mocked.
Such as all nations and people sow, such they shall reap at the hand of the just God.
And then your many and great privileges, above the children of other people,
will add weight in the scale against you, if you choose not the way of the Lord.
For you have had line upon line, and precept upon precept,
and not only good doctrine but good example; and which is more, you have been turned to,
and acquainted with, a principle in yourselves,
which others too generally have been ignorant of:
and you know you may be as good as you please, without the fear of frowns and blows,
or being turned out of doors, and forsaken of father and mother,
for God`'s sake and his holy religion;
as has been the case of some of your fathers in the
day they first entered into this holy path.
And if you,
after hearing and seeing the wonders that God has
wrought in the deliverance and preservation of them,
through a sea of troubles, and the manifold temporal, as well as spiritual,
blessings that he has filled them with, in the sight of their enemies,
should neglect and turn your backs upon so great and near a salvation,
you would not only be most ungrateful children to God and them,
but must expect that God will call the children of those that knew him not,
to take the crown out of your hands,
and that your lot will be a dreadful judgment at the hand of the Lord: but,
O that it may never be so with any of you!
The Lord forbid, saith my soul.

Wherefore, O ye young men and women! look to the rock of your fathers:
there is no other God but him, no other light but his, no other grace but his,
nor spirit but his, to convince you, quicken, and comfort you; to lead, guide,
and preserve you to God`'s everlasting kingdom.
So will you be possessors as well as professors of the truth, embracing it,
not only by education, but judgment and conviction; from a sense begotten in your souls,
through the operation of the eternal Spirit and power of God;
by which you may come to be the seed of Abraham, through faith,
and the circumcision not made with hands;
and so heirs of the promise made to the fathers, of an incorruptible crown.
That, as I said before, a generation you may be to God,
holding up the profession of the blessed truth in the life and power of it.
For formality in religion is nauseous to God and good men; and the more so,
where any form or appearance has been new and peculiar, and begun and practised,
upon a principle, with an uncommon zeal and strictness.
Therefore I say, for you to fall flat and formal, and continue the profession,
without that salt and savour by which it is come to obtain a good report among men,
is not to answer God`'s love, or your parents`' care, or the mind of truth in yourselves,
or in those that are without: who, though they will not obey the truth,
have sight and sense enough to see if they do that make a profession of it.
For where the divine virtue of it is not felt in the soul, and waited for and lived in,
imperfections will quickly break out, and show themselves,
and detect the unfaithfulness of such persons;
and that their insides are not seasoned with the
nature of that holy principle which they profess.

Wherefore, dear children,
let me entreat you to shut your eyes at the temptations
and allurements of this low and perishing world,
and not suffer your affections to be captivated by
those lusts and vanities that your fathers,
for the truth`'s sake, long since turned their backs upon:
but as you believe it to be the truth, receive it into your hearts,
that you may become the children of God: so that it may never be said of you,
as the evangelist writes of the Jews in his time, that Christ, the true light,
"`came to his own, but his own received him not; but to as many as received him,
to them he gave power to become the children of God; which were born, not of blood,
nor of the will of the flesh, nor of the will of man,
but of God;`" a most close and comprehensive passage to this occasion.
You exactly and peculiarly answer to those professing Jews,
in that you bear the name of God`'s people, by being the children,
and wearing of the form of God`'s people: and he, by his light in you,
may be very well said to come to his own, and if you obey it not,
but turn your backs upon it, and walk after the vanities of your minds,
you will be of those that received him not;
which I pray God may never be your case and judgment.
But that you may be thoroughly sensible of the many and
great obligations you lie under to the Lord for his love,
and to your parents for their care: and with all your heart, and all your soul,
and all your strength, turn to the Lord, to his gift and Spirit in you;
and hear his voice, and obey it, that you may seal to the testimony of your fathers,
by the truth and evidence of your own experience:
that your children`'s children may bless you, and the Lord for you,
as those that delivered a faithful example,
as well as record of the truth of God unto them.
So will the grey hairs of your dear parents, yet alive, go down to the grave with joy,
to see you the posterity of truth, as well as theirs: and that not only their nature,
but spirit, shall live in you when they are gone.

[.asterism]
'''

I shall conclude this account with a few words to those who are not of our communion,
into whose hands this may come; especially those of our own nation.

[.asterism]
'''

Friends, as you are the sons and daughters of Adam, and my brethren after the flesh,
often and earnest have been my desires and prayers to God on your behalf,
that you may come to know your Creator to be your Redeemer,
and Restorer to the holy image that through sin you have lost,
by the power and Spirit of his Son Jesus Christ,
whom he hath given for the light and life of the world.
And O that you, who are called Christians,
would receive him into your hearts! for there it is you want him,
and at that door he stands knocking, that you might let him in;
but you do not open to him; you are full of other guests,
so that a manger is his lot among you now as well as of old.
Yet you are full of profession, as were the Jews when he came among them,
who knew him not, but rejected and evily entreated him.
So that if you come not to the possession and experience of what you profess,
all your formality and religion will stand you in no stead in the day of God`'s judgment.

I beseech you ponder with yourselves your eternal condition, and see what title,
what ground and foundation you have for your Christianity: if more than a profession,
and an historical belief of the gospel.
Have you known the baptism of fire, and the Holy Ghost,
and the fan of Christ that winnows away the chaff in your minds, the carnal lusts,
and affections; that divine leaven of the kingdom, that, being received,
leavens the whole lump of man, sanctifying him throughout in body, soul, and spirit?
If this be not the ground of your confidence, you are in a miserable state.

You will say, perhaps, that though you are sinners, and live in daily commission of sin,
and are not sanctified, as I have been speaking, yet you have faith in Christ,
who has borne the curse for you, and in him you are complete by faith,
his righteousness being imputed to you.

But, my friends, let me entreat you not to deceive yourselves, in so important a point,
as is that of your immortal souls.
If you have true faith in Christ, your faith will make you clean; it will sanctify you:
for the saints`' faith was their victory of old: by this they overcame sin within,
and sinful man without.
And if thou art in Christ, thou walkest not after the flesh, but after the Spirit,
whose fruits are manifest.
Yea, thou art a new creature: new made, new fashioned, after God`'s will and mold.
Old things are done away, and, behold, all things are become new: new love, desires,
will, affections, and practices.
It is not any longer thou that livest; (thou disobedient, carnal,
worldly one;) but it is Christ that liveth in thee; and to live is Christ,
and to die is thy eternal gain: because thou art assured,
that thy corruptible shall put on incorruption, and thy mortal, immortality,
and that thou hast a glorious house, eternal in the heavens,
that will never wax old or pass away.
All this follows being in Christ, as heat follows fire, and light the sun.

Therefore have a care how you presume to rely upon such a notion,
as that you are in Christ, whilst in your old fallen nature.
For what communion hath light with darkness, or Christ with Belial?
Hear what the beloved disciple tells you: "`If we say we have fellowship with God,
and walk in darkness, we lie, and do not the truth.`"
That is, if we go on in a sinful way, are captivated by our carnal affections,
and are not converted to God, we walk in darkness,
and cannot possibly in that state have any fellowship with God.
Christ clothes them with his righteousness, that receive his grace in their hearts,
and deny themselves, and take up his cross daily, and follow him.
Christ`'s righteousness makes men inwardly holy; of holy minds, wills, and practices.
It is not the less Christ`'s, because we have it; for it is ours, not by nature,
but by faith and adoption: it is the gift of God.
But, still, though not ours, as of or from ourselves, (for in that sense it is Christ`'s,
for it is of and from him,) yet it is ours, and must be ours, in possession, efficacy,
and enjoyment, to do us any good; or Christ`'s righteousness will profit us nothing.
It was after this manner that he was made to the primitive Christians, righteousness,
sanctification, justification, and redemption; and if ever you will have the comfort,
kernel, and marrow of the Christian religion, thus you must come to learn and obtain it.

Now, my friends, by what you have read,
you may perceive that God has visited a poor people among you,
with this saving knowledge and testimony, whom he has upheld and increased to this day,
notwithstanding the fierce opposition they have met withal.
Despise not the meanness of this appearance: it was, and yet is, we know,
a day of small things and of small account with too many;
and many hard and ill names are given to it; but it is of God, it came from him,
because it leads to him.
This we know, but we cannot make another to know it,
unless he will take the same way to know it that we took.
The world talks of God, but what do they do?
They pray for power, but reject the principle in which it is.
If you would know God, and worship and serve God as you should do,
you must come to the means he has ordained and given for that purpose.
Some seek it in books, some in learned men; but what they look for is in themselves,
(though not of themselves,) but they overlook it.
The voice is too still, the seed too small, and the light shineth in darkness;
they are abroad, and so cannot divide the spoil: but the woman that lost her silver,
found it at home, after she had lighted her candle, and swept her house.
Do you so too, and you shall find what Pilate wanted to know, viz. Truth.
Truth in the inward parts, so valuable in the sight of God.

The light of Christ within, who is the light of the world, and so a light to you,
that tells you the truth of your condition, leads all, that take heed unto it,
out of darkness into God`'s marvellous light.
For light grows upon the obedient; it is sown for the righteous,
and their way is a shining light, that shines forth more and more to the perfect day.

Wherefore, O friends, turn in, turn in, I beseech you: where is the poison,
there is the antidote.
There you want Christ, and there you must find him; and blessed be God,
there you may find him.
Seek and you shall find, I testify for God.
But then you must seek aright, with your whole heart, as men that seek for their lives,
yea for their eternal lives: diligently, humbly, patiently,
as those that can taste no pleasure, comfort, or satisfaction in any thing else,
unless you find him whom your souls want to know and love above all.
O it is a travail, a spiritual travail! let the carnal, profane world,
think and say as it will.
And through this path you must walk to the city of God, that has eternal foundations,
if ever you will come there.

Well! and what doth this blessed light do for you?
Why, first, it sets all your sins in order before you:
it detects the spirit of this world in all its baits and allurements,
and shows how man came to fall from God, and the fallen state he is in.
Secondly, it begets a sense and sorrow, in such as believe in it, for this fearful lapse.
You will then see him distinctly whom you have pierced,
and all the blows and wounds you have given him by your disobedience,
and how you have made him to serve with your sins; and you will weep and mourn for it,
and your sorrow will be a godly sorrow.
Thirdly, after this it will bring you to the holy watch,
to take care that you do so no more, and that the enemy surprise you not again.
Then thoughts, as well as words and works, will come to judgment,
which is the way of holiness, in which the redeemed of the Lord do walk.
Here you will come to love God above all, and your neighbours as yourselves.
Nothing hurts, nothing harms, nothing makes afraid on this holy mountain.
Now you come to be Christ`'s indeed; for you are his in nature and spirit,
and not your own.
And when you are thus Christ`'s, then Christ is yours, and not before.
And here you will know communion with the Father and with the Son,
and the efficacy of the blood of cleansing, even the blood of Jesus Christ,
that immaculate Lamb, which speaks better things than the blood of Abel;
and which cleanseth from all sin, the consciences of those that,
through the living faith, come to be sprinkled with it,
from dead works to serve the living God.

[.asterism]
'''

To conclude; behold the testimony and doctrine of the people called Quakers;
behold their practice and discipline; and behold the blessed man and men,
at least many of them, that were sent of God in this excellent work and service;
all which is more particularly expressed in the annals of that man of God,
which I do heartily recommend to my reader`'s most serious perusal;
and beseech Almighty God, that his blessing may go along with both,
to the convincement of many, as yet strangers to this holy dispensation,
and also to the edification of God`'s church in general:
who for his manifold and repeated mercies and blessings to his people,
in this day of his great love, is worthy ever to have the glory, honour, thanksgiving,
and renown; and be it rendered and ascribed, with fear and reverence,
through him in whom he is well pleased, his beloved Son and Lamb, our light and life,
that sits with him upon the throne, world without end.
Amen.

Says one that God has long since mercifully favoured with his fatherly visitation,
and who was not disobedient to the heavenly vision and call;
to whom the way of truth is more lovely and precious than ever,
and that knowing the beauty and benefit of it above all worldly treasures,
has chosen it for his chiefest joy, and therefore recommends it to thy love and choice,
because he is with great sincerity and affection,

[.signed-section-closing]
Thy soul`'s friend,

[.signed-section-signature]
William Penn.

[.the-end]
Finis.
