[quote.epigraph, , Rev. 3:18]
____
I counsel you to buy from Me gold refined in the fire, that you may be rich;
and white garments, that you may be clothed,
that the shame of your nakedness may not be revealed;
and anoint your eyes with eye salve, that you may see.
____

== Forward

Though I have chosen the title [.book-title]#Primitive Christianity Revived#
as the principle name for this publication,
it is actually a combination of two separate publications by William Penn,
one being his book [.book-title]#Primitive Christianity Revived#
(first published in 1696), and the other,
[.book-title]#A Brief Account of the Rise and Progress of the People Called Quakers,#
which originally served as the introduction to the
[.book-title]#Journal of George Fox# (published in 1694)
but was later printed separately.
The two publications overlapped in their scope,
both dealing (in various degrees) with the rise of the Society of Friends,
and the distinct principles and practices of this people,
and it was thought that these short books could be combined and interwoven
in such a way as to present the reader with a more thorough presentation of
these subjects than either publication could do individually.
In attempting to do this,
I have taken a degree of editorial liberty--removing repetition,
adding short segues between sections,
and moving paragraphs around to where they seemed to fit best.
I have also attempted to carefully and conscientiously modernize and
sometimes re-word Penn`'s archaic (albeit beautiful) language,
adding an occasional Scripture reference or a
phrase of my own with the aim of greater clarity.
My objective was not simply to republish the works of William Penn;
all of his original publications still exist and
are available through many online sources.
My goal was to present the present-day seeker of truth with a readable and
heart-impacting account of what God did in the early Society of Friends,
which is the same that He desires to do in the
hearts and lives of every modern Christian.

It also perhaps needs to be said that, throughout these pages,
Penn relates the state of the Society of Friends as it was over three hundred years ago,
and his words are not at all descriptive (to my knowledge) of
any present day Quaker meetings or associations.
The light that shined so conspicuously in the hearts of these
men and women grew dimmer and dimmer in succeeding generations,
not being cleaved to or obeyed with the same zeal and resignation.
Thus Penn`'s exhortation to the children of Friends (in the
final pages of this book) proved both a warning and a prophecy,
and by the mid 1800`'s the great majority of those who bore
the name Quaker were strangers to that heavenly power and
presence which had first gathered them to be a people.

[.signed-section-signature]
Jason Henderson

[.signed-section-context-close]
February 2018
