== An Epistle to the Reader.

[.salutation]
Dear Reader,

The following account of the people called
Quakers was written in the fear and love of God:
first, as a standing testimony to that ever-blessed truth in the inward parts,
with which God visited my soul in the days of my youth,
and for the sense and love of which I was made willing
to relinquish the honors and interests of the world.
Secondly, as a testimony for that despised people,
whom God has in His great mercy gathered and united by His own blessed Spirit in
the holy profession of it--whose fellowship I value above all worldly greatness.

Herein I hope it will appear to every sober and considerate reader that,
despite all the ill usage we have met with from the world,
our great business has ever been the reality and experience of true religion, that is,
to know an effectual transformation before our great and final change.
And truly, we desire that all may come to this inward, discernible,
and experiential knowledge of God,
through the convictions and operations of the light and Spirit of
Christ in themselves (the sufficient and blessed means given to all),
and thereby come savingly to know the only true God,
and Jesus Christ whom He has sent to enlighten and redeem the world.
This knowledge is indeed life eternal; and that you, dear reader, may obtain it,
is the earnest desire of your sincere friend,

[.signed-section-signature]
William Penn.
