[#ch1, short="The Different Dispensations of God in the World"]
== Chapter I

[.chapter-subtitle--blurb]
Containing a Brief Account of the Different Dispensations of God in the World,
to the Time He Was Pleased to Raise Up the People Called Quakers.

Various have been the dispensations of God since the
creation of the world unto the sons of men;
but the great end of them all has been the renown of His own excellent name
in the creation and restoration of man--who was made the image of Himself,
and is the glory of all His works.
The world began with innocency, and all was then good that the good God had made.
And as He blessed the diverse works of His hands,
so their natures and harmony magnified their Creator.
Then the morning stars sang together for joy,
and every part of His work said '`amen`' to His law.
There was not the least discord in the whole frame; but man in paradise,
the beasts in the field, the fowl in the air, the fish in the sea,
the lights in the heavens, the fruits of the earth, yes, even the air, the earth,
the water, and fire, worshiped, praised, and exalted His power, wisdom, and goodness.
O holy Sabbath!
O holy day to the Lord!

But this happy state lasted not long; for man, the crown and glory of the whole,
being tempted to aspire above his place, unhappily yielded, against his command and duty,
as well as his interest and felicity, and so fell far below it.
Thus he lost the divine image--the wisdom, power, and purity in which he was made;
and being no longer fit for paradise,
he was expelled from the garden of God (his proper dwelling and residence)
and driven out as a poor vagabond from the presence of the Lord,
to wander in the earth, the habitation of beasts.

Yet the God that made him had pity upon him; for He saw that man was deceived,
and that it was not from malice,
but through the subtlety of the serpent (who had first fallen from his own state),
and through the mediation of the woman--man`'s own nature and
companion--whom the serpent had first deluded.
Accordingly, in infinite goodness and wisdom, God provided a way to repair the breach,
recover the loss,
and restore fallen man by a nobler and more excellent
Adam who was promised to be born of a woman.
And just as by means of a woman the evil one had prevailed upon man,
so too by a woman the last Adam would come into the world, prevail against the serpent,
bruise his head, and deliver man from his power--all of which, in an exceptional manner,
was personally and fully accomplished by and in the Son of God in the flesh,
as man`'s Savior and Redeemer.

But the manifestation of God`'s power through Him was not limited to that time;
for both before and since His blessed manifestation in the flesh,
He has been the light and life, the rock and strength, of all that have ever feared God.
He was present with them in their temptations,
followed them in their travels and afflictions,
and supported and carried them through and over the difficulties that
have attended them in their earthly pilgrimage.
It was by this alone that Abel`'s heart excelled Cain`'s,
that Seth obtained the preeminence, and that Enoch walked with God.
It was this light and power that strove with the old
world before the flood (against which they rebelled),
and the same that sanctified and instructed Noah unto salvation.

But the outward dealings of God with man, after his fall,
especially among the patriarchs, was generally through the agency of angels;
as the Scriptures of the Old Testament do in many places express, as with Abraham, Jacob, etc.
And the next dispensation was that of the law by Moses,
which was also delivered by angels, as the apostle tells us.
This administration was very much outward, suited to a low and servile state,
and was therefore called by the apostle Paul, that of a "`schoolmaster,`"^
footnote:[Galatians 3:24-25]
for it pointed out and prepared a people to look and long for the Messiah,
who would deliver them from the servitude of a ceremonious and imperfect dispensation,
by knowing (within themselves) the realities of those mysterious figures and types.
At this time the law was written on stone,
and the temple was built with hands and attended with an outward priesthood,
external rites and ceremonies, that were shadows of good things to come.
But these were only to serve "`until the Seed should come,`"^
footnote:[Galatians 3:19]
that is, the more excellent and general manifestation of Christ;
for to Him was the promise, and to all men only in Him,
in Whom the promise was yes and amen--even life from death, immortality and eternal life.

This the prophets foresaw,
and comforted the believing Jews in the certainty of it.
For the ministry of the prophets was the height of the Mosaic dispensation,
which ended in John, the forerunner of the Messiah;
and John`'s ministry finished in Him who was the fullness of all.
And then it was that God,
who at sundry times and in various manners had spoken
to the fathers by His servants the prophets,
spoke to men by His Son Christ Jesus, who is the Heir of all things.
This was the dawn of the gospel-day, the dispensation of sonship,
which ushered in a much nearer covenant and a better hope;
even the beginning of the glory of the latter days, and the restitution of all things;
yes, the restoration of the kingdom unto Israel.

Now the Spirit, which was more sparingly communicated in former dispensations,
began to be poured forth upon all flesh, according to the testimony of the prophet Joel.
And the light that shined in darkness, or but dimly before,
the most gracious God caused to shine out of darkness,
and the day-star began to rise in the hearts of believers,
giving unto them the knowledge of God in the face, or appearance,
of His Son Jesus Christ.

And now the poor in spirit, the meek, the true mourners,
the hungry and thirsty after righteousness, the peacemakers, the pure in heart,
the merciful and persecuted, came more especially in remembrance before the Lord,
and were sought out and blessed by Israel`'s true Shepherd.
Old Jerusalem with her children waxed old,
and the new Jerusalem became the mother of the sons of the gospel-day.
Thus, no more at old Jerusalem, nor at the mountain of Samaria,
would God be worshiped above other places; for, behold, He is, by His own Son,
declared and preached to be a Spirit, and will be known as such,
and worshiped in the Spirit and in the truth.
He will now come nearer than in ancient times, and will write His law in the heart,
and put His fear and Spirit in the inward parts, according to His promise.
And so all signs, types,
and shadows did fly away--the Day having discovered their
insufficiency in not reaching to the inside of the cup,
to the cleansing of the conscience--and all elementary services expired in and by Him,
who is the substance of all.

And to this great and blessed dispensation of
the Son of God the apostles did testify,
whom the Lord had chosen and anointed by His Spirit to
turn the Jews from prejudice and superstition,
and the Gentiles from vanity and idolatry,
to Christ`'s light and Spirit that shined within them, that they might be quickened^
footnote:[_quicken_ means to make alive.]
from the sins and trespasses in which they were dead,
to serve the living God in the newness of the Spirit of life,
and walk as children of the light and of the Day.
Such as these truly put on Christ, the light of the world,
and make no more provision for the flesh to fulfill its lusts.
And so this light, Spirit, and grace of God, which comes by Christ and appears in man,
was the divine principle from which the apostles ministered,
and to which they turned people`'s minds,
and into which they gathered and built up the church of Christ in their day.
And for this cause they warned all not to quench the Spirit, but to wait for the Spirit,
and speak by the Spirit, and pray by the Spirit, and walk in the Spirit,
as that alone which proved them to be the truly begotten children of God,
born not of flesh and blood, nor of the will of man, but of the will of God.
For by doing His will, and denying their own, by drinking Christ`'s cup,
and being baptized with His baptism,
the way and path is known upon which all the heirs of life have traveled to blessedness.

But alas, even in the apostles`' days
(those bright stars of the first gospel light), some clouds,
foretelling an eclipse of this primitive glory, began to appear!
Several of them gave early warning of it to the Christians of their time,
saying that even then there was, and yet would be more and more,
a falling away from the power of godliness,
and the purity of that spiritual dispensation,
by such as sought to make a fair show in the flesh,
but with whom the offense of the cross had ceased.
Their sight was true; and what they foretold to the churches,
gathered by them in the name and power of Jesus, came to pass;
for Christians degenerated quickly into outward things, such as days, and foods,
and various other ceremonies.
And even worse, they fell into strife and contention about these things,
separating one from another, and envying one another.
And, according as they found power to do so, they persecuted one another,
to the shame and scandal of their common Christianity,
and the grievous stumbling and offense of the heathen.
And then, having at last gotten worldly power into their hands,
by kings and emperors embracing the Christian profession,
they changed the kingdom of Christ, which is not of this world, into a worldly kingdom;
or, at least, they called the worldly kingdom that was in their hands,
the kingdom of Christ.
Then human inventions and novelties, both in doctrine and worship,
crowded fast into the church; for indeed,
a door was opened to such things by the grossness and carnality that
appeared then among the generality of Christians,
who had long since abandoned the guidance of God`'s meek and heavenly Spirit,
and given themselves up to superstition, will-worship, and voluntary humility.
And even as superstition is blind, so too it is rash and furious,
for all must stoop to its blind and boundless zeal, or perish by it.
So in the name of the Spirit,
they persecuted the very appearance of the Spirit of God in others,
opposing that in others which they resisted in themselves, namely, the light, grace,
and Spirit of the Lord Jesus Christ.
But this they did, and always do, by branding it heresy, schism, innovation,
or some such plausible name;
though true Christianity allows no foundation or pretense
whatsoever for persecuting a man for matters of mere religion,
being in its very nature meek, gentle, and forbearing, and consisting of faith, hope,
and love, which no persecutor can have.
For how can a persecutor believe well, hope well,
or have a charitable or tender regard to another,
while he seeks to violate another`'s mind, or persecute his body,
for matters of faith or worship towards God.

Thus the false church sprang up, and mounted the chair.
But, though she lost her nature,
she would by no means relinquish her good name--the Lamb`'s bride, the true church,
and mother of the faithful--constraining all to receive her mark,
either in their forehead, or right-hand; that is, publicly, or privately.
But, in deed and in truth, she was mystery Babylon, the mother of harlots,
the mother of those who, despite all their show and outward religion,
had adulterated and gone off from the Spirit, nature, and life of Christ,
having grown vain, worldly, ambitious, covetous, cruel, etc.,
which are the fruits of the flesh, and not of the Spirit.

Now it was, that the true church fled into the wilderness,^
footnote:[See Revelation 12:6]
that is, it fled from superstition and violence, to a retired, solitary,
and lonely state--hidden, and as it were, out of the sight of men,
though not out of the world.
And this does show,
that her former visibility was not essential to her
being a true church in the judgment of the Holy Spirit;
for she was as true a church in the wilderness (though not as visible and radiant),
as when in her former splendor.
From this wilderness state, many attempts were made to return,
but the waters were yet too high, and her way was blocked up;
and many of her excellent children, in several nations and centuries,
fell by the cruelty of superstition,
because they would not depart from their faithfulness to the truth.

The time of the reformation did make some steps towards it, both as to doctrine,
worship, and practice.
But any advancement in practice quickly failed; for wickedness flowed freely,
both among the professors^
footnote:[The word _professor_ is used throughout this book to
refer to one who professes or affirms a belief in something;
here it has nothing to do with teachers or scholars.
Likewise, a person`'s _profession_ refers to what they believe or profess to be true,
and is not related to their employment.]
of the reformation, as well as those from whom they reformed;
so that by the fruits of their conduct they could not be distinguished.
And the children of the reformers, if not the very reformers themselves,
then sought after earthly policy and power to uphold and carry
on their reformation which had begun with spiritual weapons;
which I have often thought to be one of the greatest reasons why the
reformation made no better progress as to the life and heart of religion.
For while the reformers remained lowly and spiritually minded, and trusted in God,
and looked to Him, and lived in His fear, and consulted not with flesh and blood,
nor sought deliverance in their own way,
there were daily added to the church those who were being saved.
For these, for a time, were not as concerned to be safe from persecution,
as to be faithful and harmless under it,
being more concerned to spread the truth by their faith and patience in tribulation,
than to get the worldly power out of the hands of their persecutors.

In doctrine they were in some things short; in other things,
to avoid one extreme, they ran into another; and as for worship, there was,
in the generality, far more of man in it than God.
They acknowledged the Spirit, inspiration, and revelation,
and indeed grounded their separation and reformation upon the
sense and understanding which they received from it,
in the reading of the Scriptures of truth.
And this was their plea: the Scripture is the text, the Spirit the interpreter,
and that every man is left for himself.
But yet there was too much human invention, tradition,
and art that remained both in praying and preaching; and of a worldly authority,
and worldly greatness in their ministers--especially in Great Britain, Sweden, Denmark,
and some parts of Germany.
God was therefore pleased in England to shift us from vessel to vessel,
and to humble the ministry, so that they became more strict in preaching,
devout in praying,
zealous for keeping the Lord`'s day and catechizing children and servants,
and repeating at home in their families what they had heard in religious service.
But as these grew into power, they were found not only whipping some out,
but forcing others into their temples.
They appeared rigid in their spirits, rather than serious in their lives,
and more for political parties than for inward piety; which brought forth another people,
who were yet more retired and select.

These would not fellowship with all, nor seek communion with the national church;
but formed churches among themselves of such as would be accountable of their conduct.
They had very promising experiences of the work of God`'s grace upon their hearts,
and lived under mutual agreements and covenants of fellowship, which kept them together.
Being of a somewhat softer temper,
this people seemed to recommend religion by the charms of its love, mercy, and goodness,
rather than by the terrors of its judgments and punishments;
by which the former party would have frightened people into religion.
They also allowed greater liberty to prophesy than those who were before them;
for they admitted any member to speak or pray,
as well as their pastor (whom they always appointed, and not the civil magistrate).
And if any found anything pressing upon them,
persons of any trade
(without the distinction of clergy or laity)
had their liberty to speak,
be they ever so simple and unschooled.

But alas, even this people suffered great loss!
For tasting of the worldly empire, the favor of princes, and the gains that ensued,
they degenerated much.
And though they had criticized the national church and ministry,
and forced maintenance too, many, when it was their turn to be tried,
were overcome by the weight of worldly honor and advantage.
For they found their way into profitable parsonages,
and soon contradicted their own principles; and, what is worse,
some of them turned absolute persecutors of other men on behalf of God,
having only lately themselves come out of the same furnace.

And this drove many a step further, that is,
into the water--for another baptism--believing they were not scripturally baptized,
and hoping to find the presence and power of God that
they lacked by submitting to this watery ordinance.
This people also made profession of neglecting,
(if not renouncing and censuring) not only the necessity,
but the use of all human learning as regards to the ministry,
looking to nothing besides the helps and gifts of the Spirit of God,
and those abilities natural and common to men.

For a time these seemed like John of old,
a burning and a shining light to other Christian societies.
They were very diligent, plain, and serious; strong in Scripture and bold in profession,
bearing much reproach and contradiction.
But that which had bewitched others, proved their snare as well.
For they were spoiled by the taste of worldly power,
and rested too much in their watery dispensation,
instead of passing on more fully to that of the Holy Spirit and fire,
which was the baptism of Him who came with a fan in His hand
to thoroughly (and not in part only) purge His floor,
and take away the dross and the tin of His people, and make a man finer than gold.
So they grew high, rough, and self-righteous, opposing further growth in the Spirit,
and forgetting the day of their infancy and littleness,
which had given them something of real beauty.

Hence many left them, along with all visible churches and societies,
and wandered up and down as sheep without a shepherd, and as doves without their mates,
seeking their beloved,
but not able to find the One their souls loved above their chiefest joy.
These people were called Seekers by some, and the Family of Love by others.
And as they came to the knowledge of one another, they sometimes met together,
not formally to pray or preach at appointed times or places, in their own wills,
as in times past they were accustomed to do; but rather, they waited together in silence,
and as anything arose in any one of their minds which savored of the divine Spring,
they sometimes spoke.
But so it was, that some of them did not keep in humility, nor in the fear of God,
and so after an abundance of revelation they were exalted above measure.
And for lack of staying their minds in a humble dependence upon the
One that opened their understandings to see great things in His law,
they ran out in their own imaginations.
Then, mixing their dark ideas with divine openings, they brought forth a monstrous birth,
to the scandal of all who feared God and waited daily in the
temple not made with hands for the consolation of Israel;
that is, the inward Jew, and the circumcised in spirit.

This people obtained the name of Ranters,
from their extravagant discourses and practices.
For they interpreted Christ`'s fulfilling of the law for us to be a
discharge from any obligation and duty which the law required of us,
saying that now it was no sin to do that which before it was a sin to commit.
And declaring that the slavish fear of the law had been taken off by Christ,
they taught that all things that man did were good,
if he would but do them with the mind and persuasion that it was so.
Thus, many fell into gross and outrageous practices,
pretending (for an excuse) that they could, without evil,
commit the same act which was sin for another to do;
for they distinguished between the action and the evil of it
according to the direction of the mind and the intention in doing it.
This made sin to super-abound by the abounding of grace,
turning the grace of God into lewdness,
and providing a more secure way of sinning than before--
as if Christ came not to save us from our sins,
but in our sins; not to take away sin, but that we might sin more freely at His cost,
and with less danger to ourselves.
This deception ensnared many,
and brought them to an utter and lamentable loss with respect to their eternal state.
These grew very troublesome to the better sort of people,
and furnished the looser sort with an occasion to blaspheme.
