[short="The First Instrumental Author"]
== Chapter II

[.chapter-subtitle--blurb]
The First Instrumental Author, and the Rise of the People called Quakers.

It was about this very time that the eternal, wise, and good God was pleased,
in His infinite love,
to honor and visit this benighted and bewildered
nation with His glorious Day-spring from on high,
bringing a more sure and certain sound of the Word of light and life,
through the testimony of a chosen vessel, to an effectual and blessed purpose,
for which many thousands can say '`glory be to the name of the Lord forever!`'

The first instrument or person by whom God began to gather
this people into the way they now profess was George Fox,
whose many excellent qualifications manifested a divine,
and not a human power to have been their origin.
And having no desire to exalt the creature,
but rather to magnify the God who worked mightily in and through him,
I shall declare (as God shall enable me) who and what he was;
not only by the report of others,
but from my own long and most inward acquaintance and intimate knowledge of him.

This George Fox was born in Leicestershire, about the year 1624.
He descended of honest parents, who endeavored to bring him up,
as they did the rest of their children, in the way and worship of the national church,
his mother being a woman accomplished above most
of her degree in the place where she lived.
But from a child he appeared of another frame of mind than the rest of his brethren,
being more religious, inward, still, solid, and observant beyond his years,
as the answers he would give, and the questions he would ask, did manifest,
to the astonishment of those that heard him, especially in divine things.

His mother, taking notice of his unusual disposition, the gravity, wisdom,
and piety that very early shined through him,
and how he refused childish and vain sports and company even when very young,
was tender and indulgent over him, so that from her he met with little difficulty.
As to his employment, he was brought up in country business.
He took most delight in sheep, and was very skillful with them,
an employment that well suited his mind in several respects,
both for its innocency and solitude,
and as a just emblem of his latter ministry and service.

When he was somewhat above twenty years of age,
he left his friends and visited the most retired and religious people in those parts;
for there were some in this nation who waited
night and day for the consolation of Israel,
even as Zachariah, Anna, and good old Simeon did of old.
To such as these he was sent, and these he sought out in the neighboring counties,
and among them he sojourned till a more extensive ministry was given to him.
At this time he taught and was an example of silence,
endeavoring to bring people away from all self-performances.
He testified of, and turned people to, the light of Christ within them,
encouraging them to wait in patience,
and to feel after the power of Christ to stir in their hearts,
that their knowledge and worship of God might stand in the power of an endless life.
This power was to be found in the light, and obeyed in all its manifestations in man;
for in the Word is life, and that life is the light of men,
and so it becomes life in men too, as the light is obeyed.
And as the children of the light live by the life of the Word,
they are begotten again unto God,
which is the regeneration or new birth without which none may enter the kingdom of God.
But whosoever does enter by this door is greater than John; that is,
greater than John`'s dispensation, which was not that of the kingdom,
but of the consummation of the law, the forerunner of the gospel-time.
Accordingly, several meetings were gathered in those parts;
and thus his time was employed for some years.

In 1652,
he being in his usual retirement with his mind exercised towards the Lord,
upon a very high mountain in some of the higher parts of Yorkshire,
he had a vision of the great work of God in the earth,
and of the way that he was to go forth in a public ministry to begin it.
He saw people as thick as dust in a beam of sun,
who would in time be brought home to the Lord,
that there might be but one shepherd and one sheepfold in all the earth.
There his eye was directed northward,
beholding a great people that should receive him and his message in those parts.
Upon this mountain he was moved of the Spirit to
sound out the Lord`'s great and notable day,
as if he had been in a great auditory; and from there went north,
as the Lord had shown him.
And in every place where he came, if not before he came to it,
he had his particular exercise and service shown to him,
so that the Lord was his leader indeed.
And it was not in vain that he traveled,
for God sealed his commission in most places with the convincement of some of all sorts,
from open sinners to sober professors of religion.

Some of the first and most eminent of those that came forth in a public ministry,
and who are now at rest, were Richard Farnsworth, James Nayler, William Dewsberry,
Thomas Aldam, Francis Howgil, Edward Burroughs, John Camm, John Audland,
Richard Hubberthorn, Thomas Taylor, Thomas Holmes, Alexander Parker, William Simson,
William Caton, John Stubbs, Robert Withers, Thomas Low, Josiah Coale, John Burnyeat,
Robert Lodge, Thomas Salthouse, and many more worthies that cannot well be here named.
These, after knowing a time of God`'s purging judgment in themselves,
and a waiting in silence upon Him to feel and receive power
from on high to speak in His name
(which none else rightly can, though they may use the same words),
felt its divine motions,
and were frequently drawn forth to reprove, inform, and exhort the people.
Sometimes in markets, fairs, streets, and by the highway-side,
they called people to repentance,
and to turn to the Lord with all of their heart and strength,
directing them to the light of Christ within them, by which they could see, examine,
and consider their ways,
turning from evil in order to do the good and acceptable will of God.
These suffered great hardships for their love and good-will, being often stocked, stoned,
beaten, whipped, and imprisoned, though honest men and of good report where they lived,
who had left wives, children,
houses and lands to visit the nation with a living call to repentance.
And though the priests generally set themselves to oppose them, and wrote against them,
and insinuated the most false and scandalous stories to defame them,
stirring up the magistrates to suppress them, especially in those northern parts;
yet God was pleased to fill them with His living power,
and give them such an open door of utterance in His service,
that there was a great convincement in those parts.

But I return to this excellent man, whose qualities, both natural, moral,
and spiritual, manifestly appeared in his converse with the brethren,
and among the church of God.

He was a man that God endued with a clear and wonderful depth,
being a discerner of other men`'s spirits, and very much a master of his own.
And though his understanding of things, and especially his expression of them,
perhaps sounded uncultivated and unfashionable to more refined ears,
yet his matter was nevertheless found to be weighty, instructive, and profound.
And indeed it showed, beyond all contradiction, that God had sent him,
in that natural art and skill had no share in the matter or manner of his ministry.
Yes, the many excellent and necessary truths that he preached to
mankind had nothing of man`'s wit or wisdom to recommend them.

As a man he was an original, being no man`'s copy;
and his ministry and writings showed they were from one that was not taught of man,
nor had learned what he said by study.
Nor were these notional or speculative doctrines, but sensible and practical truths,
tending to conversion and regeneration,
and the setting up of the kingdom of God in the hearts of men.
Indeed, I have many times been overcome in myself,
and been made to say with my Lord and Master upon the like occasion,
"`I thank You, O Father, Lord of heaven and earth,
that You have hidden these things from the wise and learned of this world,
and revealed them to babes.`"^
footnote:[Matthew 11:25; Luke 10:21]
For, many times has my soul bowed in humble thankfulness to the Lord,
that He did not choose any of the wise and learned of this world to
be the first messenger in our age of His blessed truth to men;
but that He took one that was not of high degree, or elegant speech,
or learned after the way of this world,
that His message and work might appear with less
suspicion or envy of human wisdom and interest,
and with more force and clearness upon the consciences
of those that sincerely sought the way of truth.

Yes, beholding with the eye of my mind
(which the God of heaven had opened in me)
the visible marks of God`'s hand in this testimony--from the clearness,
the power, and the efficacy of it, in the exemplary sobriety, plainness, zeal,
steadiness, humility, gravity, charity,
and circumspect care in the government of church-affairs,
which shined in this man`'s life and testimony--it greatly confirmed that it was of God,
and engaged my soul in a deep love, fear, reverence,
and thankfulness for His love and mercy therein to mankind.

In his ministry,
George Fox labored much to open truth to the people`'s understandings,
and to establish them upon the one sure foundation--Jesus Christ the light of the world;
so that, by bringing them to know the gift of God in themselves,
they might better know and judge concerning both Him and themselves.
And indeed, he had an extraordinary gift for opening the Scriptures.
He would go to the marrow of things, and show the mind, harmony,
and fulfillment of them with much plainness, and to great comfort and edification.
He spoke much of the mystery of the first and second Adam, of the fall and restoration,
of the law and the gospel, of shadows and substance, of the servant`'s and Son`'s state,
and the fulfilling of the Scriptures in Christ and by Christ in all that are His,
through the obedience of faith.
And it was sensibly felt that he spoke only what he had
received of Christ and was his own experience,
in that Spirit which never errs nor fails.

But, above all, he excelled in prayer.
The inwardness and weight of his spirit,
the reverence and solemnity of his address and behavior,
and the fewness and fullness of his words,
have often struck even strangers with admiration.
The most awesome, living, reverent frame I ever felt or beheld, I must say,
was his in prayer.
And truly this was a testimony that he knew and lived nearer to the Lord than other men;
for they that know Him most see most reason to approach Him with reverence and fear.

He was of an innocent life, no busy-body or self-seeker.
He was neither touchy nor critical,
and what fell from his mouth was blameless and edifying.
So meek, contented, modest, easy, steady, and tender,
it was a pleasure to be in his company.
He exercised no authority except over evil, and that he did everywhere and with all,
but in love, compassion, and long-suffering.
He was a most merciful man, as ready to forgive,
as he was unlikely to take or give an offense.
Thousands can truly say, he was of an excellent spirit and savor among them,
and so it was that the most excellent spirits
loved him with an unfeigned and unfading love.

He was an incessant laborer.
In his younger years (before his many, great,
and deep sufferings and travels had too enfeebled his
body for itinerant services) he labored much in England,
Scotland, and Ireland, turning many to God,
confirming those that were convinced of the truth,
and settling good order in church affairs.
And towards the conclusion of his traveling service, between the years 1671 and 1677,
he visited the churches of Christ in the colonies of America, in the United Provinces,
and in Germany, to the convincement and consolation of many.

As he was unwearied, so he was undaunted in his services for God and His people,
and the care he took of the affairs of the church in general was very great.
And though there was no person who the discontented struck at so sharply,
this good man was no more to be moved to fear than to wrath.
He bore all their weakness and prejudice, and returned no evil for evil;
forgiving many weak and bitter speeches and praying for his enemies,
that they might have a sense of their course, and turn to the light of the world.

And truly, I must say,
that though God had visibly clothed him with preference and authority,
yet he never abused it; but held his place in the church of God with great meekness,
and a most engaging humility and moderation.
For upon all occasions he was a servant to all,
holding and exercising his eldership in the invisible power that gathered this people.
Yes, his authority was inward and not outward,
and he got it and kept it by the love of God, and in the power of an endless life.
I write my knowledge, and not a report; and my witness is true;
having been with him for weeks and months together on many occasions,
and those of the nearest and most exercising nature.
And I can say, that by night and by day, by sea and by land;
in this and in foreign countries, I never saw him out of his place,
or not a match for every service and occasion.
For in all things he acquitted himself like a man, yes, a strong man,
a new and heavenly-minded man, and all of God Almighty`'s making.

But I return now to the dawning of this great
gospel day in the nation of England,
where many were soon gathered by the arm of the Lord to
a true experience of the light and life of Christ,
both through the ministry of George Fox, and that of other worthies, both men and women,
who had been raised up by the same power.
And as their ministry reached the conscience, it broke the heart,
and brought many to a sense and understanding that that which they had
vainly sought without (with great pains and cost) was to be found within,
namely, the right way to peace with God.
For these were directed to the light of Jesus Christ within them,
as the Seed and Leaven of the kingdom of God, which is near to all,
because it is sown in all,
being God`'s gift or talent given to all--a faithful and
true Witness and righteous Monitor in every bosom.
This is the gift and grace of God unto life and salvation that appears to all,
though few regard it; which the traditional Christian, conceited in himself,
strong in his own will and righteousness, and overcome with blind zeal and passion,
has either despised as a low and common thing, or opposed as a novelty.
Yes, the professors of Christianity have given this
heavenly gift many hard names and abusive terms;
denying, in their ignorant and angry minds,
any fresh manifestations of God`'s power and Spirit in man in these days,
though it was never more needed to make true Christians.
These are not unlike those Jews of old,
who rejected the Son of God even while they blindly professed to wait for their Messiah.
For, alas!
He did not appear among them according to their carnal minds and expectations.

Thus the appearance of this ministry in England brought forth many abusive books,
which filled the greater sort with envy, and the lesser with rage;
making the way and progress of this blessed testimony
strait and narrow indeed to those that received it.
However, God acknowledged His own work, and this testimony did effectually reach, gather,
comfort, and establish the weary and heavy laden, the hungry and thirsty,
the poor and needy, the mournful and sick,
who had spent all they had upon physicians of no value,
and who waited for relief from heaven alone.
For many of these were made to see, upon a serious trial of all things,
that nothing else but Christ Himself would do--the light of His countenance,
a touch of His garment, help from His hand, who had cured the poor woman`'s issue,
raised the centurion`'s servant, the widow`'s son, and the ruler`'s daughter.
And like Peter`'s mother, they no sooner felt His power and efficacy upon their own souls,
then they gave up to obey Him in a testimony to His power,
which they did with resigned wills and faithful hearts, despite all mocking,
contradiction, confiscation, beatings, prisons,
and many other jeopardies that attended them for His blessed name`'s sake.

And, truly, their persecutions were very many, and very great;
so that in all human probability they must have been swallowed up quickly by
the proud and boisterous waves that swelled and beat against them,
except that the God of all their tender mercies was with them in His glorious authority.
For indeed, the hills often fled,
and the mountains melted before the power that filled them, working mightily for them,
as well as in them--the one ever following the other.
And by this they plainly saw, to their exceeding great confirmation and comfort,
that all things were possible with Him with whom they had to do.
And though what God required seemed to cross man`'s wisdom,
and expose them to man`'s wrath,
yet He appeared to help and carry them through all to His glory.

Insomuch, that if ever any people could say in truth,
'`You are our sun and our shield, our rock and sanctuary;
and by You we have leaped over a wall, and by You we have run through a troop,
and by You we have put the armies of the aliens
to flight`'-- these people had a right to say it.
And as God had delivered their souls of the wearisome burdens of sin and vanity,
and enriched their poverty of spirit,
and satisfied their great hunger and thirst after eternal righteousness,
and filled them with the good things of His own house,
and made them stewards of His manifold gifts;
so they went forth to all corners of these nations,
to declare what God had done for them--what they had found,
and where and how they had found it, that is: the way to peace with God;
inviting all to come and see, and taste for themselves,
the truth of what they declared unto them.

And as their testimony was to the light, grace, or Spirit of God in man,
the precious pearl and leaven of the kingdom,
as the only blessed means appointed of God to quicken, convince, and sanctify man;
so they opened unto others what this gift was in itself, what it was given to them for,
and how they might know it from their own spirit,
and from the subtle appearance of the evil one.
Moreover,
they showed what it would do for all whose minds would turn from the vanity of the world,
and its lifeless ways and teachers, and adhere to Christ`'s blessed light within,
which discovers and condemns sin in all its appearances, and shows how to overcome it,
if minded and obeyed in its holy manifestations and convictions.
For to these it gives power,
both to avoid and resist those things that do not please God, and to grow strong in love,
faith, and good works.
Thus man, whom sin has made like a wilderness, over-run with briers and thorns,
may become as the garden of God, cultivated by His divine power,
and replenished with the most virtuous and beautiful plants of God`'s own planting,
to His eternal praise.

But these experiential preachers of the glad tidings
of God`'s truth and kingdom could not run when they wanted,
nor pray or preach when they pleased,
but only as Christ their Redeemer prepared and moved them by His own blessed Spirit.
It was for this that they waited in their services and meetings,
and so spoke as He gave them utterance, which made them as those having authority,
and not like the dry and formal Pharisees.
And so it plainly appeared to all who were serious-minded,
whose spiritual eye the Lord Jesus had in any measure opened,
that to one was given the word of exhortation, to another the word of reproof,
to another the word of consolation, and all by the same Spirit, in His good order,
to the convincing and edifying of many.

And, truly,
these ministers of the gospel waxed strong and bold through faithfulness,
and by the power and Spirit of the Lord Jesus they became very fruitful.
Thousands, in a short time,
were turned through their testimony to the truth in the inward parts,
having been cut to the heart by both their ministry and sufferings; insomuch that,
in most counties, and in many of the towns of England, meetings were settled,
and daily there were added to the church such as were being saved.
For they were diligent to plant and to water,
and the Lord blessed their labors with an exceedingly great increase,
notwithstanding all the opposition made to their blessed progress by false rumors,
slander, and bitter persecution--not only from the powers of the land,
but from anyone that wished to injure and abuse them.
Thus they seemed as
"`poor sheep appointed to the slaughter, and as a people killed all the day long.`"^
footnote:[Romans 8:36]

To relate the extent of their cruel sufferings would doubtless fill many volumes,
for they received scoffing and abuse from professors as well as from profane,
from magistrates as well as rabble.
Indeed it may be said of this abused and despised people,
that "`they went forth weeping, and sowed in tears, bearing testimony to the precious Seed,`"^
footnote:[Ps. 126:6]
even the Seed of the kingdom,
which stands not in words
(even the finest and highest that man`'s wit can use)
but in power--that is, the power of Christ Jesus,
to whom God the Father has given all power in heaven and in earth,
that He might rule angels above, and men below.
It was this Jesus who empowered them, as their work clearly witnessed,
for multitudes were turned through their ministry from darkness to light,
and from the broad way to the narrow way of life and peace, bringing many to a weighty,
serious, and God-like conduct, the practice of that doctrine which they taught.

Yet their strict conformity to the dictates of Truth and to
that light which manifests all things that are reprovable,
gave them a strange and disagreeable appearance to many,
who considered them those who "`turn the world upside down.`"^
footnote:[Acts 17:6]
And indeed, in some sense they were,
but in no other way than that wherein Paul was so charged, namely,
in seeking to bring things back to their primitive and right order again.
For their unusual conduct and practice was not the result of personal fancy or conceit,
or any desire for civil distinction, as some have imagined;
but was the fruit of an inward sense, which God, through His holy fear,
had begotten in them.
They did not consider how to contradict the world,
or distinguish themselves as a particular party distinct from others;
having no desire to advocate either schism or novelty.
But having been given a true sight of themselves,
they saw the whole world through the same lens of truth.
Yes, they sensibly discerned the affections and passions of men,
and the rise and tendency of things;
understanding what it was that gratified the "`lust of the flesh, the lust of the eye,
and the pride of life, which are not of the Father, but of the world.`"^
footnote:[1 John 2:16]
For from these things many vain customs have arisen during the night
of darkness and apostasy which has spread over the people through
their degeneration from the light and Spirit of God.
But such things are seen by the heavenly Day of Christ that
dawns in the soul to be either wrong in their origin,
or, by time and abuse, hurtful in their practice.
And though their refusing to conform in these things seemed trivial to some,
and rendered this people foolish and conceited in such persons`' opinions;
there was far greater depth to them than many could perceive.
Indeed,
it was not easy for our primitive friends to make themselves sights and spectacles,
and the scorn and derision of the world;
but they easily discerned how this must be the
consequence of so unfashionable an interaction with it.

And though they were not often great and learned men
in the esteem of this world (for then they would not have
lacked followers by virtue of their own credit and authority),
yet they were generally among the most sober in the several
religious persuasions to which they formerly belonged,
and of the most repute for piety; and many of them were of good capacity, substance,
and account among men.

And also some among them were not at all lacking for education, learning,
or estate; though now, as of old, not many wise or noble, etc., are called; or,
at least not many among these receive the heavenly call,
by reason of the cross that accompanies every sincere response.
But talent and learning, though they make better orators and disputants,
do not make better Christians;
and it is the ignorance of people about the divine gift
that causes this vulgar and mischievous mistake.
Theory and practice, speculation and experience, words and life, are two separate things.
O, it is the repentant, the reformed, the lowly, the watchful,
the self-denying and holy soul that is the Christian!
And this character is the fruit and work of the Spirit,
which is the life of Jesus Christ--whose life,
though hid in its fullness in God the Father,
is shed abroad in the hearts of all that truly believe, according to their capacity.
O that people did but know this Spirit to cleanse them, to circumcise them,
to quicken them, and to make them new creatures indeed,
recreated or regenerated in Christ Jesus unto good works!
Then they might live unto God, and not to themselves;
and offer up living prayers and living praises to the living God,
through His own living Spirit, in which alone He is to be worshiped in this gospel day.

Now, concerning the ministry of this people,
and their right qualifications for it,
the following are several marks or signs that it was truly Christian:

First, they were changed men themselves, before they went about to change others.
Their hearts were rent as well as their garments,
and they knew the power and work of God upon themselves.
This was seen by the great alteration it had made, their stricter course of life,
and the more godly conduct that immediately followed upon it.

Second, they did not go forth or preach in their own time or will,
but in the will of God; and they spoke not their own studied matter,
but only as they were opened and moved by His Spirit,
with which they were well acquainted by their own regeneration.
This, I am aware, cannot be expressed to carnal men,
so as to give them an intelligible account; for to them such things, as Christ said,
are like the blowing of the wind,
which no man knows from where it comes or where it goes.
Yet this proof and seal went along with their ministry,
that many were turned from lifeless professions, and the evil of their ways,
to an inward and experiential knowledge of God, and a holy life,
as thousands can witness.
And as they freely received what they had to say from the Lord,
so they freely administered it to others.

Third, the stress and tendency of their ministry was
conversion to God--true regeneration and holiness.
It was not schemes of doctrines and verbal creeds, or new forms of worship;
but a leaving off all that is superfluous in religion,
reducing the ceremonial and formal part, and pressing earnestly after the substantial,
the necessary and profitable part to the soul.

Fourth, they directed people to a gift or Seed in themselves,
though not of themselves, by which all that they asserted, preached, and exhorted,
might be wrought in them and experientially known by them.
This indeed is a high and distinguishing mark of the truth of their ministry,
for they knew what they said, and encouraged all to put it to the test.
Yes, they were bold from certainty,
and desired that no one believe their testimony based on human authority,
but rather upon inward conviction--the conviction that came from this Seed,
which they asserted was sown in the ones to whom they preached.
It was unto this Seed of the kingdom, this measure of the Spirit,
that they directed all men,
that all might examine and prove the reality of
those things which they had affirmed of it,
as to its manifestation and work in man.
And truly, this is far more than many ministers can do,
who declare theory and speculation, and preach doctrines concerning God, Christ,
holiness and heaven, etc.; but do not speak their own knowledge and experience,
or ever direct their hearers to the divine gift,
to the "`implanted Word which is able to save the soul,`"^
footnote:[James 1:21]
or instruct where to find it,
and how to wait to feel it working the good and acceptable will of God in them.

Fifth, they reached to the inward state and condition of people,
which is an evidence of the virtue of this implanted Word,
and of their ministering from it, and not from their own imaginations, biases,
or opinions upon Scripture.
For nothing reaches the heart, except what is from the heart.
Nothing pierces the conscience, except what comes from a living conscience.
So that, in the ministry of this people,
it has often happened that the secrets of hearts have been revealed,
and true states and conditions have been declared.
Yes, the very thoughts and purposes of the hearts of many have been so plainly detected,
that they, like Nathaniel, have cried out concerning this inward appearance of Christ,
"`You are the Son of God, You are the King of Israel.`"^
footnote:[John 1:49]
And those that have embraced this divine Word or Seed,
have found the same mark of its truth and divinity which the
woman of Samaria found of Christ when He was in the flesh,
namely: "`It told them all that ever they had done.`"^
footnote:[John 4:29]
It showed them their insides, the most inward secrets of their hearts,
"`laying judgment to the line and righteousness to the plummet,`"^
footnote:[Isaiah 28:7]
of which thousands at this day can testify.
So that those who have turned to this heavenly Seed have had cause to say,
"`It was a true report which I have heard, and indeed the half was not told to me`"^
footnote:[1 Kings 10:6-7]
of the power, purity, wisdom and goodness of God therein.

Sixth,
the extraordinary understanding in divine things with which even some of the
lowest among them were furnished by the operation of this heavenly Seed,
gave occasion for many to wonder, saying of them, as some did of their Master,
"`Is this not the carpenter`'s son, how did he acquire such great learning?`"^
footnote:[Matthew 13:54-56]
From this,
others took occasion to suspect and insinuate that they
were Jesuits or great scholars in disguise;
though there was not the least ground of truth for any such reflection,
seeing that their places of abode, kindred, and education were known to all.

Seventh, these ministers came forth low, despised, and hated,
even as the primitive Christians did,
and not at all by the help of worldly wisdom or power,
as former reformations in part have done.
Yes, in all things it may be said that this people was brought forth in the cross,
in a true contradiction to the ways, worships, fashions, and customs of this world;
against all its currents and tides, so that no flesh might glory before God.

Eighth, they clearly had no design to themselves in their work and service,
thus to expose themselves to such scorn and abuse; to spend and be spent,
leaving wife and children, house and land, and all that can be accounted dear unto men,
with their lives in their hands, being daily in jeopardy,
to declare this primitive message revived in their
spirits by the good Spirit and power of God,
namely: That God is light, and in Him is no darkness at all;
and that He has sent His Son as a light into the world
to enlighten all men and lead them to salvation;
and that they that say they have fellowship with God, and yet walk in darkness--that is,
in disobedience to the light in their consciences,
and according to the vanity of this world--lie and do not practice the truth.
But all that love the light, and bring their deeds to it, and walk in the light,
even as God is light,
these experience the blood of Jesus Christ His Son cleansing them from all sin.
(1 John 1:19-4; 3:20-21; 1:5-7.)

Ninth, their great constancy and patience in suffering for their
testimony (in all of its branches) is well known to all;
and that sometimes they suffered even unto death, by beatings, bruisings,
and long and crowded imprisonments in filthy dungeons.
Four of them in New England died by the hands of the executioner,^
footnote:[William Robinson, Marmaduke Stevenson, Mary Dyer, and William Leddra.
See William Sewel`'s [.book-title]#The History of the Rise, Increase, and Progress of that Christian People called Quakers.#]
purely for preaching among the people of Boston.
Not to mention banishments and excessive plunderings of goods and estates,
in almost all places, for their faithfulness to the good and glorious cause;
often refusing deliverance by dishonorable ways or means,
though it was many times offered to them.

Tenth,
they not only showed no disposition to revenge when it was at any time in their power,
but they forgave their cruel enemies, showing mercy to those that had shown none to them.

Eleventh, their plain dealing with those in authority,
much like the ancient prophets,
not fearing to declare both the private and public sins
of rulers and magistrates to their faces,
and accurately prophesy their afflictions and downfall,
even when in the height of their glory.
They likewise foretold some national judgments in very express terms,
such as the plague of 1665,^
footnote:[The Great Plague of 1665-1666 was the last major
epidemic of the bubonic plague to occur in England,
killing an estimated 100,000 people in 18 months,
about a fourth of the population of London.]
and the great fire of London,^
footnote:[The Great Fire of London burned from Sunday, September 2nd to Wednesday,
September 5th 1666.
It consumed 87 parish churches, most buildings used by city authorities,
and 13,200 houses--the homes of 70,000 of the city`'s 80,000 inhabitants.]
as well as particular judgments to several wicked persecutors,
which accordingly overtook them.

O that those who read me could but feel me!
For my heart is affected with this merciful visitation
of the Father of lights and spirits to this poor nation,
and to the whole world through the same living testimony.
Why should the inhabitants of the land reject it?
Why should they lose the blessed benefit of it?
Why should they not turn to the Lord with all their hearts, and say from the heart,
"`Speak Lord, for now Your poor servants are listening.
O that Your will may be done--Your great, good, and holy will,
in earth as it is in heaven!
Do it in us, do it upon us, do what You will with us; for we are Yours,
and desire to glorify our Creator our Redeemer.
For You are redeeming us from the earth, from the vanities and pollutions of it,
to be a peculiar people unto You.`"
O, this would have been a great day for England, if she would have said so in truth;
but alas, the case is otherwise!

O land of my nativity!
Some have mourned over you with bitter wailing and lamentation.
Their heads have indeed been as waters, and their eyes as fountains of tears,
because of your transgression and rebellion; because you will not hear, and fear,
and return to the Rock from which you were hewn.
But be warned, O land of great profession, to receive Him into your heart.
Behold, He has stood long at the door knocking; but as of yet you will have none of Him.

O be awakened, lest Jerusalem`'s judgments do swiftly overtake you,
because her sins do abound in you!
For Jerusalem abounded in formality but made void the weighty things of God`'s law,
as you daily do.
She withstood the Son of God in the flesh, and you resist the Son of God in the Spirit.
He would have gathered her as a hen gathers her chicks under her wing,
and she was not willing;
so He would have gathered you out of your lifeless
professions and brought you to inherit substance,
to know His power and kingdom.
To this end He often knocked from within, by His grace and Spirit;
and called from without, by His servants and witnesses;
but just as Jerusalem of old persecuted the manifestation of the Son of God in the flesh,
and crucified Him, and whipped and imprisoned His servants;
so you have crucified to yourselves afresh the Lord of life and glory,
and insulted His Spirit of grace.
Yes, you have slighted His fatherly visitation, and persecuted those who declared it,
by your laws and magistrates,
though they have pleaded with you day and night in the power and Spirit of the Lord,
in love and meekness, that you might know the Lord, and serve Him,
and become the glory of all lands.

Alas, you have evilly entreated and requited them.
You have set aside all their counsel, and desired none of their reproof.
Their appearance was too plain,
and their qualifications were too low for you to receive them.
You are like the Jews of old who cried, "`Are not His brothers and sister among us?
Which of the scribes, and of the learned (the orthodox) believe in Him?`"
So you prophesied their downfall in a year or two,
and sought to bring it to pass by making and executing severe and unjust laws.
Yes, you endeavored to terrify them out of their holy way,
or destroy them for abiding faithful to it.
But you have seen how many governments that arose against them,
and determined their downfall, have been overturned and extinguished,
and that they are still preserved, and have become a great and numerous people.
And notwithstanding the many difficulties from without and within,
under which they have labored since the Lord first gathered them,
they are an increasing people; for the Lord still adds to them, in various places,
such as shall be saved if they persevere to the end.

Remember, O nation of great religious profession,
how the Lord has waited upon you and pleaded with you.
Awake and arise out of your deep sleep, and hear now His Word in your heart,
that you may live.
Do not let this your day of visitation pass over your head,
or neglect so great a salvation as this, which has come to your house, O England!
For why should you die?
O land that God desires to bless,
be assured it is He that has been in the midst of this despised people,
who are in the midst of you.
It is not a delusion, as your mistaken teachers have made you believe.
And this you shall surely find by their marks and their fruits,
if you will but consider these things in the spirit of moderation.
