[short="The Gift of God--Christ`'s Light Within"]
== Chapter III

[.chapter-subtitle--blurb]
The Gift of God--Christ`'s Light Within

Having now spoken something concerning their origin and rise,
and briefly portrayed the manner and aim of their ministry,
it remains upon me to speak more expressly of the fundamental
principles and practices that distinguish this people from the
many other professors of religion at this day.
I have already touched upon their fundamental principle,
which is the light of Christ within, as God`'s gift for man`'s salvation.
And as this is the root of the excellent tree of
doctrines that grew and branched out from it,
I believe it warrants further consideration and explanation.

That which the people called Quakers lay down
as a main fundamental in religion is this:
That God, through Jesus Christ, has placed a gift of His Spirit in every man,
to inform them of their duty, and to enable them to do it;
and that those who live in humble submission to this are the people of God,
and those that live in disobedience to it, are not God`'s people,
whatever name they may bear or profession they may make of religion.
This is their ancient, first and standing testimony.
With this they began, and this testimony they bore, and do bear to the world.

By a gift of His Spirit, they understand something that is divine;
but though it be in man, yet it is not of man, but rather of God;
and even as it came from Him, so it leads to Him all who will be led by it.

Now, there are several ways of speaking which this people have been led to use,
by which they declare and express what this Spirit is.
They call it the light of Christ within man, or simply light within,
which is their ancient, and most general and familiar phrase;
also the manifestation or appearance of Christ, the witness of God, the seed of God,
the seed of the kingdom, His wisdom or Word in the heart,
the grace that appears to all men, a measure of the Spirit given to every man,
the Truth in the inward parts,
the spiritual leaven that leavens the whole lump of man, etc.
Many of these are figurative expressions,
but all are such as the Holy Spirit has used in Scripture,
and will be used in this treatise,
for they are frequently found in the writings and ministry of this people.
But, to avoid any misapprehension or confusion in the reader,
I would have all know that,
by all of these various terms or designations,
they mean the same thing as was before mentioned, namely: that gift or grace which,
though it be in man, is not of man, but of God, and therefore divine.
This Spirit is one in itself, though diversely expressed by the penmen of Scripture,
according to its various manifestations and operations.

It is to this Spirit of light, life, and grace, that this people direct all;
for they say it is the great agent in all true religion, and that without it,
there is no conviction, and so no conversion or regeneration,
and consequently no entering into the kingdom of God.
That is to say, without this gift there can be no true sight of sin nor sorrow for it,
and therefore no forsaking or overcoming it, nor remission or justification from it.
A necessary and powerful Spirit indeed,
when neither sanctification nor justification can be had without it!
In short, there is no becoming virtuous, holy, and good, without this;
and there is no acceptance with God, nor peace of soul, but through it.
So then, the reason for so much irreligion among Christians,
so much superstition instead of devotion, so much profession without possession,
and so little heart-reformation,
is because people in religion generally overlook this Holy Spirit,
and leave it entirely behind.

Alas, men seek to be religious without it, to be Christians without it,
but this Spirit is the only means of making them so.
It is natural to men in their degenerate state to prefer sacrifice before obedience,
to make prayers pass for practice,
and to flatter themselves with hope because of their ceremonial and bodily services.
In this way they excuse themselves before God from the
stricter discipline of His Spirit in the soul,
which leads all to take up the cross, deny self,
and to do that which God requires of them.
This must be every man`'s true religion, for though a man cannot make himself holy,
humble, patient, meek, merciful, just, kind, and charitable;
yet the Holy Spirit will make all men so,
who embrace the convictions and teachings of it;
for this is the only Root of all true religion,
and the one good Seed from which all good fruits proceed.

It is by the measure of this Spirit, poured out upon all flesh,^
footnote:[Joel 2:28; Acts 2:17]
that man is given: First, the knowledge of God and of himself,
and therein a sight of his duty and any disobedience to it.
Secondly, it begets a true sense and sorrow for sin in those that
seriously regard the convictions of it.
Thirdly, it empowers them to forsake sin, and sanctifies them from it.
Fourthly, it applies God`'s mercies in Christ for the forgiveness
of sins that are past unto true justification,
upon sincere repentance and obedience.
Fifthly, it gives to the faithful perseverance unto a perfect man,
and the assurance of blessedness in the age to come.

=== The evidence of Scripture for the light of Christ

[.offset]
_John 1:1._ In the beginning was the Word, and the Word was with God,
and the Word was God.

[.offset]
_Verse 8._ All things were made by Him.

[.offset]
_Verse 4._ In Him was life, and the life was the light of men.

[.offset]
_Verse 9._ That was the true light, which enlightens every man that comes into the world.

I have begun with the account of the beloved disciple,
well-known for his excellent knowledge and wisdom in heavenly things.
He began his history with Him who was the beginning of the creation of God,
and tells us first what Christ was in the beginning, namely, the Word.
"`In the beginning was the Word.`"
And though this implies what the Word must be, yet he adds and explains,
that "`the Word was with God,
and the Word was God;`" lest any should doubt the divinity of the Word,
or have lower thoughts of Him than He deserves.
The Word then is divine; and this is indeed an appropriate name by which to call Him,
since He is so great an expression of the wisdom and power of God unto men.

"`All things were made by Him.`"
If this is so, He lacks no power.
Nothing can be too hard for Him who was sufficient to make all things,
and "`without whom nothing was made that was made.`"^
footnote:[John 1:3]
And even as we were first made by Him, so we must be newly made by Him,
or we can never enjoy our God.
Yes, even as man`'s Maker must be his husband,
so his Creator must be his Redeemer as well.^
footnote:[See Isaiah 54:5]

"`In Him was life, and the life was the light of men.`"
_This is precisely our point._
The evangelist first begins with the nature and being of the Word;
from there he descends to the works of the Word; and lastly,
he tells us what this same Word is with respect to man (who is
above the rest of the creation)--it is his light.
The Word was life, and the life was the light of men.
This relationship must be very near and intimate indeed,
for the very life of the Word (which was with God,
and was God) is said to be the light of men.
This is not said of any other creature.

Man, then, cannot be without light; no, not without a divine light;
for if this light is not divine (which is
clearly said to be the life of the divine Word),
then there can be no such thing at all as divine or supernatural light and life.
And this text does not only prove the divinity of the light,
but the universality of it also, for it is expressed in the ninth verse,
"`That was the true light, which enlightens every man that comes into the world.`"
John was not this light, but bore witness of Him who was, and who enlightens every man;
namely, the Word that became flesh.
Thus, both the divine nature, and the universality^
footnote:[In more recent years,
there have been misunderstandings and false conclusions derived from the
Quakers`' use of the term _universal_ with reference to the light of Christ.
This word was used by Friends to establish an intentional contrast with the
prevalent idea that God offers the saving knowledge of Christ to only a small,
predestined few.
The Quakers rejected the idea of individual predestination and a "`limited
atonement,`" insisting that Christ died for all men,
and that an offer of redemption extends towards all the
sons of Adam through the light and grace of God.
It is this gracious, inward invitation that is universal.
When received, followed, and obeyed,
the light of Christ becomes the life and salvation of the soul.
When rejected, the same light becomes man`'s eternal condemnation.
See John 3:19-21. Early Quakers were not at all proponents of universalism,
or universal reconciliation.]
of the light of Christ within, are here confirmed together.

=== Not a Natural Light

But though there is no passage or proposition to be
found in Holy Scripture in which mankind is more concerned,
or that is more clearly laid down by the Holy Spirit than this which I have produced,
yet scarcely has any Scripture been more industriously
twisted from its true and plain sense.
Some insist this to be but a natural light, or a part of man`'s nature,
though it is called the very life of the Word by whom the world was made.
But because I desire to be understood, and to deal with all plainness,
I will open the terms of this objection as well as I can,
and then offer my answer to it.

If by natural is meant a created thing, as man is,
or anything that is essential to the composition of man, I deny it.
The text is expressly against such an idea, and says,
the light with which man is enlightened is the life of the Word which was with God,
and was God.
But if by natural it is only intended,
that we have this light as sure as we are born,
and that it (at times) shines in our minds and understandings,
and is not the result of any outward revelation, as by angels or men,
then we mean and intend the same thing.
In this sense, it is natural to man to have a supernatural light,
and for the creature to be enlightened by an
uncreated light--the life of the creating Word.

And if people would but consider the constitution of man,
it would assist much to deliver them from any dilemma upon this account.
For man can no more be a light to his own mind, than he is to his own body.
He has the capacity of seeing objects when he has the help of light,
but cannot be a light to himself by which to see them.
Therefore, as the sun in the firmament is the light of the body,
and gives us discerning in our temporal affairs,
so the life of the Word is the glorious light and sun of the soul.
It is our inward luminary, that has power to inform our mind,
and give us true judgment and distinction about those things
that more immediately concern our better and inward man.

But others will make this text read, not that the Word enlightens all mankind,
but only all of those who are enlightened by it,
thereby not only narrowing and abusing the text,
but rendering God partial and so severe to His creatures as to
leave part of the world in perfect darkness,
without any means or opportunity of salvation.
However, we are assured from the Scriptures, that all have been given light,
that Christ is the "`light of the world,`"^
footnote:[John 8:12]
and that "`He died for all men;`"^
footnote:[2 Corinthians 5:14-15; Romans 6:10; Hebrews 2:9, etc.]
yes, even "`the ungodly,`"^
footnote:[Romans 5:6; see also 2 Peter 2:1]
and that "`God desires not the death of any,
but rather that all should repent and come to the knowledge of the Truth and be saved;`"^
footnote:[Ezekiel 18:32-33:1; 1 Timothy 2:4; 2 Peter 3:9]
and that the "`grace of God has appeared to all men,`"^
footnote:[Titus 2:11] etc.

There is a third sort who allege this Scripture to be speaking,
not of any illumination by a divine light or Spirit in man,
but by the doctrine Christ preached,
and the life and example He lived and led in the world.
But the knowledge of this reached not to the thousandth part of mankind,
nor is this in any way consistent with what the apostle
John intends in the beginning of his history,
which wholly relates to what Christ was before He took flesh,
and what He is to the soul of man by His immediate inshinings and influences.

It is most true that Christ was, in a sense,
the light of the world in His outward appearance,
and that He shined forth by His heavenly doctrine, His many admirable miracles,
and His self-denying life and death.
Yet this does not hinder the truth that He was and is also the spiritual light
which shines (in various degrees) in the hearts of the sons and daughters of men.
For the evangelist, seeking to distinguish Christ`'s light from John`'s,
who was not the true light, did not set forth Christ`'s fasting forty days,
preaching many sermons, working many miracles, nor His holy life and patient death,
but instead showed that the true light, the Messiah, the Word made flesh,
enlightens every man that comes into the world.
Thus Christ is manifested and distinguished by His giving of light; as indeed,
His true followers are distinguished from other people by their receiving and obeying it.
There are many other Scriptures,
in both Old and New Testaments that refer to the light within, either expressly,
or indirectly, which for brevity`'s sake, I shall forbear reciting.

=== The Efficacy of Christ`'s Light Within

Let us then consider the virtue and efficacy of this
light with regard to the end for which God has given it,
namely, to lead and guide the soul of man to blessedness.
In order to effect this,
the first thing it does in and for man is to
give him a true sight or discerning of himself,
what he is and what he does, that he may see his true condition,
and know what judgment to make concerning religion and a future state.
Let us hear what the Word himself, who cannot err, says of this light,
as John relates it in the third chapter of his gospel:
"`For everyone practicing evil hates the light and does not come to the light,
lest his deeds should be exposed.
But he who does the truth comes to the light,
that his deeds may be clearly seen,
that they have been wrought in God.`"^
footnote:[John 3:20-21]

This is a most pregnant description of the virtue and authority of the light.
First, it is said to be that by which men ought to examine themselves.
Secondly, it is that which gives a true discerning between good and evil,
what is of God and what is not of God.
And lastly, it is a judge, condemning or acquitting,
reproving or comforting the soul of man, according as he rejects or obeys it.
Now, that which is able to show unto man what is of God, and what is not,
and give the obedient a distinct knowledge of what has
been wrought or performed by God`'s power,
and after His will, and what is the mere workings of the creature,
this must indeed be both divine and efficacious.
For if it were not, it could by no means manifest the mind of God,
nor give man a grounded sense and discerning of the rise, nature,
and tendency of his mind or inward man,
as is both expressed and implied in these words of our Savior.

But that this light does indeed manifest God,
is evident from Romans 1:19.
"`Because that which may be known of God is manifest in men,
for God has showed it unto them.`"
This is a universal proposition, and we have the apostle`'s word for it,
who was inspired by the Spirit to tell us the truth;
let it then have its due weight with us.
If that which may be known of God is manifest in men,
the people called Quakers cannot be out of the
way in preaching up Christ`'s light within,
without which nothing can be manifested to the mind of man,
as the same apostle says in his epistle to the Ephesians (vs. 5:13):
"`Whatsoever makes manifest is light.`"
Rightly then, do they call this light a manifestation or appearance of God,
which shows in and to man all that may be known of God.

A passage much like this, is that of the prophet Micah,
chapter 6:8. "`He has shown you, O man, what is good;
and what does the Lord require of you but to do justly, to love mercy,
and to walk humbly with your God?`"
God has shown you, O man!
This is very emphatic.
But how has He shown him?
Why, by this light in the conscience, which the wicked rebel against.
For Job has said,
"`There are those who rebel against the light;
they do not know its ways, nor abide in its paths;`"^
footnote:[Job 24:13]
but its ways are ways of pleasantness, and all its paths are peace to those who obey it.

This light gives the light of life (which is eternal life)
to those who receive and obey it.
For, thus says the blessed Savior of the world, "`I am the light of the world.
He who follows Me shall not abide in darkness, but shall have the light of life.`"^
footnote:[John 8:12]
Now, He is the light of the entire world because He
enlightens every man that comes into the world.
Those who obey His light obey Him, and so have the light of life; that is to say,
His light becomes eternal life to their soul.
For again, it is the life of the Word which is the light in man,
and this becomes the life in man through his submissive
obedience to its various manifestations.

Furthermore, this light was the very ground of the apostolic message,
as the beloved disciple assures us, saying:
"`This then is the message which we have heard of Him and declare unto you,
that God is light, and in Him is no darkness at all.
If we say we have fellowship with Him, and walk in darkness, we lie,
and do not practice the truth.
But if we walk in the light, as He is in the light,
we have fellowship one with another,
and the blood of Jesus Christ, His Son, cleanses us from all sin.`"^
footnote:[1 John 1:5-7]
This is so comprehensive with regard to the virtue and
excellency of the light of Christ in reference to man,
that there is little more that can be added to it.
For here we see, first, that it reveals God, and that God Himself is light.
Secondly, it distinguishes darkness from light, there being no fellowship between them.
Thirdly, that man must walk in the light,
as the way to obtain both forgiveness of sin and sanctification from it.
And fourthly,
that this is the means to have peace and fellowship with God and His people--
His true church--who are redeemed from the pollutions of the world.
