[short="The Doctrines of Justification and Salvation"]
== Chapter V

[.chapter-subtitle--blurb]
The Doctrines of Justification and Salvation

Much has been rumored and falsely charged upon us by our adversaries with
respect to the important doctrines of Christ`'s satisfaction to God for our sins,
and the ground of a sinner`'s justification before God.
I shall first speak negatively, as to what we do not believe,
which perhaps has given occasion to those who have been more hasty than wise,
to judge us defective in our belief of the efficacy of
the death and sufferings of Christ unto justification.

First, we cannot believe that Christ`'s sufferings and death either satisfy God,
or justify men, in such a way that they are thereby immediately accepted of God.
We believe they are indeed thereby put into a state capable of being accepted of God,
but that it is through the obedience of faith and the sanctification of the Spirit,
that they come into a true state of acceptance.
We can never think a man justified before God while he remains self-condemned,
or that any man can be in Christ who is not a new creature;
or that God looks upon men otherwise than they really are.
We think it a state of presumption and not of salvation to call Jesus Lord,
and not by the work of the Holy Spirit; or Master,
when He is not yet master of their affections;
or Savior when they are not saved by Him from their sins;
or Redeemer when they are not yet redeemed by Him from their passion, pride,
covetousness, vanity, vain honors, friendships, and glory of this world.
This, we believe, is to deceive one`'s self, for God will not be mocked;
such as men sow, that they must reap.
And though Christ indeed did die for us,
yet we must, by the assistance of His grace,
"`work out our salvation with fear and trembling.`"^
footnote:[Philippians 2:12]
As He died for sin, so we must die to sin,
or we cannot truly be said to be saved by the death and sufferings of Christ,
or thoroughly justified and accepted with God.

Now positively, what we believe with respect to justification:

We most certainly believe that Jesus Christ was our holy sacrifice, atonement,
and propitiation; that He bore our iniquities,
and that by His stripes we were healed of the wounds which Adam gave us in his fall;
and that God is just in forgiving true penitents upon the credit of
that holy offering which Christ made of Himself to God for us.
We believe that what Christ did and suffered has satisfied and pleased God,
and that it was for the sake of fallen man who had displeased God.
And it is through the offering up of Himself once for all, through the eternal Spirit,
that "`He has forever perfected those (in all times) that are sanctified,`"^
footnote:[Hebrews 10:14]
who have "`walked not after the flesh, but after the Spirit.`"^
footnote:[Romans 8:1,4]

In short, we believe that justification consists of two parts,
or has a twofold consideration--namely: justification from the guilt of sin,
and justification from the power and pollution of sin;
and in this twofold sense justification gives a man full and clear acceptance before God.
It is for lack of this latter part that so many souls
(who are religiously inclined)
are often under doubts, scruples, and despair,
notwithstanding all that their teachers tell them of the
extent and efficacy of the first part of justification.
And it is too general a fault among the professors of Christianity,
that they seek to cloak their own active and passive
disobedience with the active and passive obedience of Christ.

The first part of justification, we do reverently and humbly acknowledge,
is only by virtue of the death and sufferings of Christ.
It is nothing we can do, but is done by the operation of the Holy Spirit,
who is able to cancel old debts and wipe out old scores.
It is the power and efficacy of this propitiatory offering, upon faith and repentance,
that justifies us from the sins that are past;^
footnote:[See Romans 3:25]
and it is the power of Christ`'s Spirit in our hearts
that purifies and makes us acceptable before God.
For until the heart of man is purged from sin, God will never accept it.
He reproves, rebukes and condemns those that entertain sin there,
and such as these cannot rightly be said to be in a justified
state--condemnation and justification being contraries.
Therefore, those who believe themselves to be in a justified state
because of the active and passive obedience of Christ,
even while they are not actively and passively obedient to the Spirit of Christ Jesus,
are under a strong and dangerous delusion.
And it is for crying out against this sin-pleasing imagination (and doctrine),
that we are represented and reproached as being deniers and
despisers of the death and sufferings of our Lord Jesus Christ!

But let it be known to all such who walk in
unholiness under a profession of justification:
these add to Christ`'s sufferings and crucify to themselves afresh the Son of God,
trampling the blood of His covenant under their feet.
For God will not acquit the guilty, nor justify the disobedient and unfaithful.
Such deceive themselves, and at the great and final judgment their sentence will not be,
"`Come you blessed,`" because it cannot be said to them,
"`Well done good and faithful servant;`" but rather "`Go you cursed,`"
for they live and die in a reproveable and condemnable state.
For none truly know Christ to be their sacrifice, who reject Him as their sanctifier;
for the end of His coming was to save His people from the nature and defilement,
as well as the guilt of sin.
Accordingly, those who resist His light and Spirit,
make His coming and offering of no effect to them.

Therefore, O my reader,
do not rest wholly satisfied with what Christ has done
for you in His blessed Person without you,
but press on to know His power and kingdom within you,
so that the strong man (who has too long kept your house) may be bound,
his goods spoiled, his works destroyed and sin finished,
according to 1 John 3:7. It is for this end, says that beloved disciple,
that Christ was manifested; that all things may become new--a new heavens and new earth,
in which righteousness dwells.
In this you will come to glorify God in your body and in your spirit, which are His;
and so live to Him and not to yourself.
Indeed, your love, joy, worship and obedience; your life, conduct and practice;
your study, meditation and devotion, will all be spiritual.

The Father and the Son will make their abode with you,
and Christ will manifest Himself to you;
for the secrets of the Lord are with those that fear Him,
and these have a holy anointing which leads them into all truth,
not needing the teachings of men.
Yes, these are better taught, being instructed by the Divine oracle.
They are not bare hear-say or traditional Christians,
but fresh and living witnesses--those who have seen with their own eyes,
heard with their own ears, and handled with their own hands, the Word of life,
in its various operations, to their souls`' salvation.
In this they meet together, in this they preach, and in this they pray and praise.
Behold the new covenant fulfilled; the church, anointing, and worship of Christ!

=== Salvation by Christ

And lest any should say we are ambiguous in our expressions,
and allegorize away Christ`'s appearance in the flesh,
meaning thereby only His inward appearance in our own flesh;
or that as often as we mention Him we speak only of the mystery,
or the spiritual and mystical sense of Him,
I desire to preserve all from being misled by such suggestions,
and to inform and reclaim such as are under the
prejudice of them by declaring the following:
We do truly believe and confess, to the glory of God the Father,
and the honor of His dear and beloved Son, that Jesus Christ took our nature upon Him,
and was like unto us in all things, sin excepted.
We believe He was born of the virgin Mary, suffered under Pontius Pilate,
the Roman governor, was crucified, dead,
and buried in the sepulcher of Joseph of Arimathea, that He rose again the third day,
ascended into heaven, and sits at the right hand of God,
in the power and majesty of His Father,
who will one day judge the world by Him--even that blessed Man,
Christ Jesus--according to their works.

But because we believe this, we must also believe what Christ has said,
"`He that is with you shall be in you.`"^
footnote:[John 14:17]
"`I in them, and they in Me,`"^
footnote:[John 14:20]
etc.
And the many similar statements of the apostles:
"`When it pleased God to reveal His Son in me.`"^
footnote:[Galatians 1:16]
"`The mystery hid from ages, which is Christ in the Gentiles, the hope of glory.`"^
footnote:[Colossians 1:27]
"`Unless Christ be in you, you are reprobates!`"^
footnote:[2 Corinthians 13:5]
Or must we be represented as deniers of Christ`'s coming in the flesh,
and all the parts and branches of His doing and suffering,
only because we believe and stress the necessity of believing, receiving,
and obeying His inward and spiritual appearance and manifestation, through His light,
grace, and Spirit in the hearts and consciences of men and women, to reprove, convict,
convert, and change them?
This we esteem hard and unrighteous treatment on the part of our adversaries.

However, we are very ready to declare to the whole world,
that we cannot believe men and women can be saved by their belief in the outward,
without the sense and experience of the inward.
It is this that we oppose, and not His blessed manifestation in the flesh.
For we plainly confess that Christ, at that time, overcame our common enemy,
foiled him in the open field, and, partaking of our nature,
triumphed over the one who had triumphed over it^
footnote:[i.e. the nature of man,
referring to Satan`'s conquest and long reign in and over the fallen nature of humanity.]
in our forefather Adam, and in all his posterity.
Nevertheless, as truly as Christ overcame him in His own person, so too,
by His Divine grace being received and obeyed by us, He overcomes the enemy in us;
that is, He detects him by His light in the conscience,
and enables the creature to resist his fiery darts,
to fight the good fight of faith and overcome, and to lay hold of eternal life.

This is the dispensation of grace which we declare has appeared to all,
in various measures, teaching all who will receive it,
"`to deny ungodliness and worldly lusts, and to live soberly, righteously,
and godly in this present world;
looking for the blessed hope and glorious appearing of
the great God and Savior Jesus Christ.`"^
footnote:[Titus 2:11]
And because it is from the teaching, experience,
and operation of this grace that we minister to others,
so the very purpose of our ministry is to turn
people`'s hearts to this grace in themselves,
that all may do the good and acceptable will of God,
and work out their salvation with fear and trembling,
making their heavenly calling and election sure.

For what a man sows, that he must reap;
and he is the servant of whomever he obeys.
We must know a true regeneration,
or we cannot be children of God and heirs of eternal glory.
To be born again, another Spirit must prevail, leaven, season, and govern us,
besides the spirit of the world, or our own depraved spirits.
This can be no other Spirit than that which dwelt in Christ; for we are told,
unless His Spirit dwells in us, we are none of His, Romans 8:9.
This Spirit begins in conviction, and ends in conversion and perseverance;
the one necessarily following the other.
For conversion is the consequence of convictions obeyed,
and perseverance is a natural fruit of conversion and being born of God.
Such as these "`do not sin, because the Seed of God abides in them,`"^
footnote:[1 John 3:9]
and through faithfulness they continue to the end and obtain the promise,
even everlasting life.

But let my reader be assured that we do acknowledge that Christ,
through His holy doing and suffering, has obtained mercy from God His Father for mankind,
and that His obedience has great influence upon our
salvation in all the parts and branches of it,
since thereby He became a conqueror, led captivity captive,
and obtained gifts for men (with other great and precious promises),
that thereby "`we might be partakers of the divine nature,
having escaped the corruption that is in the world through lust.`"^
footnote:[2 Peter 1:4]
I say, we most certainly believe and confess that the active and passive
obedience of Christ Jesus affects our salvation throughout,
saving from the power and pollution of sin, as well as from the guilt,
He being a conqueror as well as a sacrifice, and both through suffering.
Yet those who reject the divine gift which He thus obtained,
and which He has given to them,
and by which they may see their sin and the sinfulness
of it and repent and turn away from it,
and who do not wait upon God for daily strength to resist the fiery darts of the enemy,
and to be comforted through the obedience of faith in this divine
grace of the Son of God--such as these do not please God,
do not truly believe in God,
nor are they in a state of true Christianity or salvation.
"`Woman,`" said Christ to the Samaritan at the well,
"`If you had known the gift of God, and who it is that speaks to you,`"^
footnote:[John 4:10]
etc.
People do not know God or Christ, "`whom to know is life eternal,`"^
footnote:[John 17:3]
because they are ignorant of the gift of God, namely,
the "`manifestation of the Spirit of God which is given to every man to profit withal;`"^
footnote:[1 Corinthians 12:7]
which reveals Christ and God to the soul.

Flesh and blood cannot do it;
being educated at Oxford and Cambridge cannot do it;
languages and philosophy cannot do it;
for those "`who through wisdom did not know God,`"^
footnote:[1 Corinthians 1:21]
had these things for their wisdom.
They were strong, deep, and accurate in such learning;
but alas, they were clouded, puffed up,
and set further off from the inward and saving knowledge of
God because they sought for it where it cannot be found.
Yet the key of David is another thing, which shuts and no man opens,
and opens and no man shuts.
And all who receive the gift of God into their hearts do find this key,
and it opens to them the knowledge of God and of themselves,
and gives them quite another sight, taste,
and judgment of things than their intellectual or traditional knowledge can afford them.
This is the beginning of the new creation of God, and by it we become new creatures.

We are therefore bold to declare that there is no other way like this,
by which people can come into Christ, or be true Christians,
or receive the advantage that comes by the sufferings and death of the Lord Jesus Christ.

And therefore we say--and upon good authority, even that of our own experience,
as well as that of the Scriptures of Truth--that Christ will
prove no saving sacrifice for those who refuse to obey Him.
They that reject the gift, deny the Giver,
instead of rejecting themselves for the Giver`'s sake.
O that people were wise,
that they would consider their latter end and
the things that make for their eternal peace!
Why should they perish in a vain hope of life, while death still reigns within?
Or why do they hope to live forever with God, when they do not live unto Him,
nor walk with Him now?
Awake you that sleep in your sin, or at best, in your self-righteousness!
Awake, I say, and Christ shall give you life!
For He is the Lord from heaven, the life-giving Spirit, who quickens us by His Spirit,
if we do not resist it and quench it by our disobedience, but rather receive,
love and obey it, in all its holy leadings and teachings.
"`For as many as are led by the Spirit of God, these are sons of God.`"^
footnote:[Romans 8:14]

To this Holy Spirit I commend my reader, that you may the better see where He is,
and come to the true belief and advantage of the doings and
sufferings of our blessed Lord and Savior Jesus Christ.
For truly He saves from the power and pollution of sin, as well as the guilt of sin,
in all who will hear His knocks, open the door of their hearts to Him,
and allow Him to work a real and thorough reformation in and for them.
In this way the benefit, virtue, and efficacy of His doings and sufferings without us,
will come to be livingly and effectually applied and experienced within us,
and a fellowship with Christ in His death and sufferings will be felt and known,
according to the doctrine of the apostles.
But those who continue to live in that sin which made Christ suffer,
show they do not know Him, though they profess to be saved by His death and sufferings.

I conclude this chapter with this earnest desire:
that however people may mistake, misconstrue,
or misrepresent our views on this important subject,
they would not deceive themselves in the great business of their own salvation,
and while happily declaring that Christ has done all,
be found disowned by Him on the last day.
Read the 7th of Matthew:
it is the one who hears Christ--the great Word of God--and does what He enjoins,
commands, and recommends by His own blessed example,
that is compared to a wise builder with a strong foundation.
No other house will stand in the final shaking and judgment.
For this reason we are often plain, direct,
and earnest with people to consider that Christ came not to save them in,
but from, their sins.
Those who think to dismiss themselves from His yoke and burden, His cross and example,
and secure themselves by praising Christ for His having done all for them
(while He has wrought little or nothing in them,
nor have they parted with anything for the love of Him)
will finally awake in a dreadful surprise,
at the sound of the last trumpet, and this sad and irrevocable sentence,
"`Depart from Me you workers of iniquity, I do not know you.`"^
footnote:[Matthew 7:23; Luke 13:27]
May all avoid this terrible end by timely hearkening to wisdom`'s voice,
and turning at her reproof.
For surely she will lead you in the ways of righteousness,
and in the midst of the paths of judgment your souls will come to inherit
substance--even durable riches and righteousness in the kingdom of God.
