[short="True Worship and Ministry"]
== Chapter VI

[.chapter-subtitle--blurb]
On the True Worship of God, and the True Ministry, which is by His Spirit.

Now, as the Lord effectually wrought in the
hearts of this people by His divine grace,
He thus brought them to a divine worship and ministry,
whereby they came to experience Christ`'s words:
"`God is Spirit, and those who worship Him must worship in spirit and
truth&hellip;for the Father is seeking such to worship Him.`"
footnote:[John 4:23-24]
For having bowed to the convictions of the Spirit in themselves in their daily
course of living (by which they were taught to renounce every appearance of evil,
and to do that which was good), they then, in their assembling together,
sat down and waited for the preparation of the Holy Spirit,
in order to both see their true states and conditions before the Lord,
and to worship Him acceptably.
And as they were made sensible of any needs, shortcomings, or weaknesses,
so in the secret of their own hearts prayer would spring to God through Jesus Christ,
to help, assist, and supply.
But they did not dare awaken their Beloved before His time,^
footnote:[Song of Solomon 2:7, 3:5, 8:4,]
nor approach the throne of the King of glory until He held out His scepter.^
footnote:[Esther 4:11-5:2, 8:4]
Nor did they take thought what they should say,
or offer their own (or other men`'s) studied words and forms,
for they learned that this was to offer "`strange fire;`"^
footnote:[Leviticus 10:1]
to pray, but not by the Spirit; to ask, but not in the name.
For the name is the power of our Lord Jesus Christ,
who prayed and spoke as one having authority, that is, having power, divine energy,
and force that reached and pierced the heavens.
And this power He gives to all who obey His light, grace, and Spirit,
in their solemn waiting upon Him.
Accordingly, it is this people`'s principle, that fire must come from heaven,
life and power must come from God,
to enable the soul to pour itself out acceptably before Him.
And when a coal from His holy altar touches our lips,
then we can pray and praise Him as we ought to do.

And as this is our principle (which is according to Scripture),
so it is our experience and practice;
and therefore we have separated from the worship of men, under its variety of forms,
because it is not founded in the operation, motion,
and assistance of the Spirit of Christ, but in the appointment,
invention and framing of man, both as to matter, words and time.
We do not dissent from others in our own wills,
but we dare not comply with them against the will of Him who
has called us and brought us to His own spiritual worship.
Yes, it is in obedience to Him that we are what we are,
in our separation from the many ways of worship in the world.

Moreover,
even as our worship stands in the operation of the Spirit of Truth in our inward parts,
so does our ministry.
For as the testimonies of the servants of God of old
arose from the operation of His blessed Spirit,
so must those of His servants in every age;
and that which does not have the Spirit of Christ for its spring and source,
is of man, and not of Christ.
Christian ministers are to minister what they receive; this is Scripture.
And what we receive is not our own, and much less another man`'s,
but rather the Lord`'s.
Accordingly, not only must we cease to steal words from our neighbors,
but we must take care not to study or speak our own words as well.
For Christ told His ministers, "`When they deliver you up,
do not worry about how or what you should speak.
For it will be given to you in that hour what you should speak;
for it is not you who speak, but the Spirit of your Father who speaks in you.`"^
footnote:[Matthew 10:19-20]
Now, if we are not to study what to say before magistrates on behalf of ourselves,
much less should we study what to say on behalf of God to His people.
"`If anyone speaks, let him speak as the oracles of God.
If anyone ministers, let him do it as with the ability which God supplies.`"^
footnote:[1 Peter 4:11]
We are to minister as the oracles of God, and so must receive from Christ,
God`'s great Oracle, what we are to minister.
And if we minister what we receive, then it is not what we study, collect,
and fetch out of our brains, for this is not the mind of Christ,
but our own imaginations, and will not profit the people at all.

This was recommended to the Corinthians by the apostle Paul in 1 Corinthians 14,
that is, that they should speak as they were moved,
or as anything was revealed to them by the Spirit for the edification of the church.
"`For,`" he says, "`You may all prophesy;`"
that is, you may all preach unto edification,
as anything is revealed to you for the good of others,
and as the Spirit gives utterance.^
footnote:[See 1 Corinthians 14:29-31]
And knowing that the Spirit must give Christ`'s ministers their utterance,
so those whom He has prepared and sent are fearful and careful not to
utter anything in His name that is not out from His Spirit.
Consequently, those who go before the true Guide,
and utter words without the knowledge of the mind of the Spirit,
are none of Christ`'s true ministers.
These certainly run, but God has not sent them,
and they cannot profit the people at all.^
footnote:[Jeremiah 23:32]
And indeed, how could they?
For it is impossible that a mere man,
with all his abilities, arts, and acquirements,
can turn people from darkness to light, and from the power of Satan to God,
which is the very end and work of the Gospel ministry.
Indeed, it must be inspired men, gifted by God,
taught and influenced by His heavenly Spirit,
who are qualified for so great, so inward,
and so spiritual a work.

Ministers of Christ are said to be His witnesses,
and the credit of a witness is that he has heard,
seen, or handled something true.
Thus the beloved disciple states the truth and
authority of their mission and ministry in these words:
"`That which we have heard, which we have seen with our eyes, which we have looked upon,
and our hands have handled, that we declare unto you,
that your fellowship may be with us; and truly our fellowship is with the Father,
and with His Son Jesus Christ.`"^
footnote:[1 John 1:1-3]
I say, if Christ`'s ministers are His witnesses,
they must know what they speak; that is,
they must have experienced and passed through the
various states and conditions of which they preach,
and practically know the truths that they declare to the people.
Otherwise, they came not in by the door, but climbed over the wall,
and are thieves and robbers.

He that has the key of David comes in at the door (which is Christ Jesus),
and has his admission and approbation from Him, being anointed by Him,
the only high Priest of the Gospel dispensation.
He it is that breathes and lays His hands upon His own ministers.
Yes, He anoints them, refills their flask, and renews their horn with oil,
that they may have it fresh for every occasion and
service which He calls them to and engages them in.

And as they receive freely, freely they give; they do not teach for hire,
divine for money, nor preach for gifts and rewards.
It was Christ`'s holy command to His ministers to give freely, and this is our practice.
And truly we think it strange that this should be considered a fault,
and that preaching for hire should not be seen a mark of false prophets,
when it has been so frequently and severely cried out
against by the true prophets of God in former times.
I desire not to be uncharitable,
but it would be wise to call to mind the case of one
who formerly offered money to be made a minister,
and the answer he met with from the apostle Peter, Acts 8:18-20.
May the Lord touch the hearts of those who are giving their
money to be made professional ministers in order to live by their preaching,
that they may see what ground it is that they are building upon.
May they repent and turn to the Lord,
that they may find mercy and become living witnesses of
His power and goodness in their own souls.
Then they will be enabled to tell others what God has done for them,
which is the root and ground of all true ministry, and that which God does bless.

[.discourse-part]
Objection: But does not this sort of ministry and worship tend to make people careless,
and to raise spiritual pride in others?
And does it not give occasion for great mischief and irreligion?

[.discourse-part]
Answer: By no means, for the end of all words is to bring people to the great Word,
Jesus Christ, and then the promise of God is accomplished,
that "`they shall be all taught of the Lord, from the least to the greatest,
and in righteousness they shall be established, and great shall be their peace.`"^
footnote:[Isaiah 54:13-14; Jeremiah 31:34; Hebrews 8:11]
With this declaration of Isaiah, the beloved disciple agrees,
and thus gives a full answer to this objection:
"`These things I have written to you concerning those who try to deceive you.
But the anointing which you have received from Him abides in you,
and you do not need that anyone teach you;
but as the same anointing teaches you concerning all things, and is true,
and is not a lie, and just as it has taught you, you will abide in Him.`"^
footnote:[1 John 2:27]
Here there are three very observable things:
First, that John wrote his epistle upon a particular occasion,
that is, to prevent their delusion.
Secondly, that he recommends a nearer and superior minister than himself, namely,
the anointing or grace which they had received,
and which would accompany them in all situations.
Thirdly, that if they would but take heed to its teachings,
they would have no need of man`'s directions, nor fear of his deception.
In this way the apostle Paul also spoke to the Thessalonians, saying,
"`But concerning brotherly love you have no need that I should write to you,
for you yourselves are taught by God to love one another.`"^
footnote:[1 Thessalonians 4:9]

Nevertheless, outward helps are useful and a great blessing, when they are of God.
Such was John the Baptist; but remember he pointed all to Christ, saying,
"`Behold the Lamb of God!`"^
footnote:[John 1:29,36]
"`I baptize you with water,
but He shall baptize you with the Holy Spirit and with fire.`"^
footnote:[Matthew 3:11; Luke 3:16]
All true ministry does likewise.
Wherever people are sensual, and under a dark eclipse by the intrusion of sin and Satan,
God is pleased to send forth His enlightened servants to awaken and
turn them from the darkness to the light in themselves,
that through obedience to it, they may come to be children of the light,
and have their fellowship in it,
and an inheritance at last with the saints in light forever.

And because it is the way that God has chosen to call and gather His people,
so a living and holy ministry is of great advantage,
to watch over and build up the young,
and to comfort and establish the feeble and simple ones.
But still I say, the more inward, the less outward.
That is to say,
the more people come to be taught directly by God through the
light of His Word and Spirit in their hearts,
the less need they will have of outward means.
For the prophet writes:

[quote.scripture, , Isaiah 16:19-20]
____
The sun shall no longer be your light by day,
nor for brightness shall the moon give light to you;
But the Lord will be to you an everlasting light, and your God your glory.
Your sun shall no longer go down, nor shall your moon withdraw itself;
for the Lord will be your everlasting light,
and the days of your mourning shall be ended.
____

This is held by all to be a Gospel promise,
and the sun and moon here are generally understood to
signify the various external means in the church.
Compare this with John 1:13; Rom. 1:19; 1 Cor. 2:11,15; 1 Thess. 4:9;
1 John 2:20,27; and Rev. 21:22-24;
all of which prove what we assert concerning the sufficiency
and glorious privilege of inward and spiritual teachings.
And most certainly, as men grow in grace,
and know the anointing of the Word in themselves,
the dispensation will be less in words (though still in words) and more in life;
preaching will be in great measure turned to praising,
and worship will be more a walking with God than a talking of Him.
For the truest and highest worship that a man is capable of in this
world is to bow to God`'s will at all times and in all places.
Yes, it is conformity that gives communion; and there is no fellowship with God,
no light of His countenance to be enjoyed, no peace and assurance to be had,
further than there is an obedience to His will,
and a faithfulness to His indwelling Word,
according to the manifestation of its light in the heart.

I say, this is the truest and highest state of worship;
for set days and set places, with all their solemnity,
were most in use during the weakest dispensation of the Spirit.
Altars, arks and temples, sabbaths and feasts,
etc. are not to be found in the writings of the New Testament.
There, every day is alike, and every place is alike
(but if a day is kept, let it be kept unto the Lord).
Thus says the apostle,
but he plainly shows a state beyond the keeping of places and times;
for with him, to live was Christ, and to die was gain;
for the life he lived was by the faith of the Son of God,
and therefore it was not he that lived, but Christ that lived in him;
that is, Christ ruled, conducted, and bore sway in him.
This is the true Christian life, the life of conversion and regeneration,
to which all the dispensations of God and ministries of His servants have ever pointed,
as the consummation of God`'s work for man`'s happiness.
Here every man is a temple, and every family a church,
and every place a meeting-place, and every visit a meeting.

Not that we would be thought to undervalue public and solemn meetings;
for indeed, we have them all over the nation wherever the Lord has called us.
Yes, though but two or three of us be in a corner of a country, there we meet,
as the apostle exhorted the saints of his time,
and reproved such as neglected to assemble themselves.
We also meet together for a public testimony of religion and worship,
and for the edification and encouragement of those who are yet young in the truth,
and to call and gather others to the knowledge of it, who are yet going astray, etc.
And blessed be God, it is not in vain,
since many are thereby added to the church that we hope and believe shall be saved.
But yet we show unto you, O reader, a more excellent way of worship.
For many may come to meetings, and go away carnal, dead and dry;
but the worshipers in spirit and in truth--whose hearts bow,
whose minds adore the eternal God who is a Spirit, in and by His own Spirit,
and such as conform to His will,
and walk with Him in a spiritual life--these are the true, constant,
living and acceptable worshipers, whether they be in meetings or out of meetings.
