[short="Other Distinctive Principles and Practices"]
== Chapter VII

[.chapter-subtitle--blurb]
Other Distinctive Principles and Practices

Besides these general doctrines,
which were like larger branches of a gospel tree,
there sprang forth several particular doctrines and practices
that further evinced the truths which this people espoused.
And indeed,
many of these smaller branches or testimonies are what other
professors of Christianity pretend to hold in words and forms,
but not in the power of godliness.
For, generally speaking,
the power has long been lost because of man`'s departing
from that grace or Seed of life that is in him.
And having disregarded it, he has lost the sense of it,
though it is in and by this alone that man can be
quickened to serve the living God in newness of life.
Therefore, finding that the life of religion was largely abandoned,
and that the generality of men lived and worshiped God after their
own wills--and not after the will of God nor the mind of Christ--thus
what the people called Quakers pressed was not notion,
but experience; not formality, but true godliness;
for they had become sensible in themselves
(through the work of God`'s righteous judgments)
that "`without holiness no man will see the Lord.`"^
footnote:[Hebrews 12:14]
Some of their distinctive testimonies are as follows:

First, communion and loving one another.
This is a noted characteristic among them,
confessed by all sorts of men concerning this people.
They will meet, they will help, and they will stick one to another;
so that it is common to hear people say,
"`Look how the Quakers love and take care of one another!`"
Thus if loving one another, enjoying intimate communion in religion,
and manifesting a constant care to meet in order to worship God and help one another,
is any mark of primitive Christianity, they had it in an ample manner,
blessed be the Lord.

Second, they recommend silence by their example,
having very few words upon all occasions,
for "`in the multitude of words sin is not lacking.`"^
footnote:[Proverbs 10:19]
They seek frequent solitude and retirement,
but when in company endeavor not to use,
nor willingly listen to, unnecessary or unrighteous discourse,
whereby they preserve their minds pure and undisturbed
from many unprofitable thoughts and distractions.
They also keep to their word in business, their yes being yes, and their no being no;
nor can their customers, with many words, bring them off from it,
for they have more regard to truth than to custom or gain.

Third, they both teach and practice love to their enemies.
They not only refuse to seek revenge for any wrongs
done to them (condemning this as an unchristian spirit),
but they freely forgive, and even help and relieve those that have been cruel to them,
even when it is in their power to pay back their oppressors.
Many remarkable instances of this could be given if time would allow.

Fourth, not fighting but suffering, is another testimony peculiar to this people.
They affirm that the Spirit of Christ teaches men to
"`beat their swords into plowshares,
their spears into pruning hooks, and to learn war no more,`"^
footnote:[Isaiah 2:4]
so that "`the wolf may lie down with the lamb, and the lion with the calf,`"^
footnote:[Isaiah 11:6]
and nothing that hurts or destroys be entertained in the hearts of people.
Thus they exhort men to employ their zeal against sin,
and to turn their anger against Satan,
making war against sin and wickedness so as to dethrone the author of all enmity.
For all wars and fighting arise from the lusts of men`'s hearts,
according to the apostle James,^
footnote:[James 4:1-2]
and not from the meek Spirit of Christ Jesus,
who is captain of another warfare which is carried on with other weapons.
And truly,
their testimony in this regard ought not to be
considered disagreeable to civil government,
since, if they cannot fight for it, neither can they fight against it.
Nor is it reasonable that they should be blamed for not fighting for
others when they will not even fight for themselves.
But though they are not for fighting, yet they are for submitting to government,
and this they do not only from fear of punishment, but for conscience-sake,
wherever government does not interfere with conscience.
For they believe government to be an ordinance of God and a
great benefit to mankind wherever it is justly administered.

Fifth, as God has been pleased to call them out from a human ministry,
so they cannot (for conscience sake) support and maintain it;
and it is upon this ground,
and not out of defiance or covetousness, that they refuse to pay tithes,
or suchlike pretended church dues, concerning which,
many books have been written in their defense.
They cannot support what they cannot approve,
but must indeed testify against it for two reasons: First,
because all compelled maintenance is expressly contrary to Christ`'s command, who said,
"`Freely you have received, freely give;`"^
footnote:[Matthew 10:8]
so that any support of gospel ministers should be free and not forced.
And second,
because the national ministers do not have the Holy Spirit for their foundation,
but rather an assortment of human arts and acquirements.

Sixth, they speak truth on all occasions, but dare not swear oaths,
for Christ forbids it, saying, "`But I say to you, do not swear at all:
neither by heaven, for it is God`'s throne;
nor by the earth, for it is His footstool;
nor by Jerusalem, for it is the city of the great King&hellip;
But let your '`Yes`' be '`Yes,`' and your '`No,`' '`No.`'
For whatever is more than these is from the evil one.`"^
footnote:[Matthew 5:34-37]
And James, His follower, says, "`But above all, my brethren, do not swear,
either by heaven or by earth, or with any other oath.
But let your '`Yes`' be '`Yes,`' and your '`No,`' '`No,`' lest you fall into judgment.`"^
footnote:[James 5:12]
Swearing is needless as well as evil, for the reason of swearing is untruth,
when a man`'s yes is not yes.
Swearing was used to intimidate men into speaking the truth,
and to give others satisfaction that what was sworn was true.
But the true Christian`'s yes being yes
(they being under the bond of truth in themselves)
the purpose of an oath is answered,
and so the use of it is needless, superfluous, and must come from evil.

Seventh, they dare not give worldly honor, vain compliments, flattering titles,
or use the frequent and fashionable salutations of the times,^
footnote:[The normal greeting between peers at this time
involved scraping the right foot backwards along the ground,
bowing low while removing the hat,
and then flattering one another with titles like
"`your Lordship,`" "`your Eminency,`" etc.]
seeing plainly the vanity, pride, and ostentation that belong to them.
Christ also forbade such things in His day,
denouncing the self-flattering spirit that loves greetings in
marketplaces and to be called "`Rabbi`" by men.
Their nonconformity in these things comes not from pride, ill-breeding, or fancy,
nor do they seek in this way to distinguish themselves as a party,
but it is in obedience to the sight and sense they have received from
the Spirit of Christ of the evil ground and tendency of such things.
And though this has rendered their conduct disagreeable to many who
are lovers of themselves and of that honor which comes from men,
yet they are mindful of what Christ said to the Jews,
"`How can you believe, who receive honor from one another,
and do not seek the honor that comes from the only God?`"^
footnote:[John 5:44]

Eighth, for the same reason they have returned to plainness of speech, that is,
saying _thee_ and _thou_ to a single person, regardless of their status or degree among men.^
footnote:[Most modern English speakers are unaware that the words _you_ and
_your_ were originally plural pronouns used only to address two or more people,
whereas _thee_ and _thou_ were used to address one person.
In the 1600`'s, it became fashionable
(as a means of showing honor or flattery)
to use the plural _you_ and _your_ in addressing people of higher social status,
while _thee_ and _thou_ were reserved for servants, children,
or people of lower social or economic position.
Early Friends stuck to what was then considered "`plain language`"
(using _thee_ and _thou_ to every single person, and _you_ and _your_ to two or more),
rather than showing preferment by addressing certain individuals in the plural.
These may seem like small matters to the 21st century reader,
but it is remarkable how many thousands of Friends were insulted, beaten, imprisoned,
and even hanged for refusing to conform to these customs.]
And though men use no other language in their address unto God,
they will rarely endure the same from us,^
footnote:[Though people at this time would use
the plural _you_ and _your_ to address each other,
everyone continued using _thee_ and _thou_ in their addresses to God in prayer.
It seemed strangely hypocritical to early Friends that,
though their persecutors would pray to their Creator using _thee_ and _thou,_
they would not tolerate being addressed in the same language.]
so that this has been a great test upon the pride of many,
showing their blind and weak insides,
notwithstanding their lofty outward professions of religion.
And truly, this people`'s stance on this point is purely because of conscience,
whatever people may think or say of them for it.
And though they may be despised and evilly treated,
yet their plain appearance in this way is backed by both Scripture and grammar;
and as they have propriety of speech in favor of it,
so they also have found peace in the practice of it.

Ninth,
plainness and simplicity in dress and furniture is another testimony peculiar to them,
along with temperance in food,
and abstinence from the vain recreations and pastimes of the
world--all of which they have been taught by the Spirit of the
Lord Jesus Christ to be according to godliness.
They have therefore long exhorted all that
"`their moderation may be known unto all men;`"^
footnote:[Philippians 4:5]
for they have found that the Lord is at hand to enter into judgment for all extravagance,
immodesty, and excess.

Tenth, they cannot, in conscience to God, observe so-called holy days,
or public fasts and feasts, knowing that such things have no divine warrant,
but are instituted, ordained, and appointed in the will of man.

Lastly, they have been led by the good Spirit of our Lord Jesus Christ
(according to the example of the primitive saints)
to have a due care over one another,
for the preservation of the whole Society,
in a conduct and discipline suitable to their holy profession.
The first matter of business that arose among them was the exercise of charity,
supplying the necessities of the poor, and seeing that care was taken of widows, orphans,
and those who were helpless.
Accordingly,
collections were generously made for this and various other services in the church,
which were entrusted to faithful men of good report,
who feared God and did not grow weary in well-doing.
This continues to be their regular and careful practice
in all the places where this people is found.

And as their numbers greatly increased both in town and in country,
so that they were looked upon by all sorts of inquirers,
they were concerned that all who belonged to them walked
worthy of the gospel in all their behavior among men,
upon all occasions.
For as they compel none to join them,
so they rightly insist that those who are of them walk suitably to their profession,
in order to be acknowledged by them, and remain in fellowship with them.

And to the end that this good order may
be observed in the ways of truth and soberness,
for the comfort and edification of the Society, select meetings for business, oversight,
and discipline were fixed in all parts that they inhabit, which are held monthly,
and which resolve into Quarterly Meetings, and those into one larger Yearly Meeting.
These were established for their better communication one with
another in those things that maintain piety and charity,
and for the careful management of the poor, orphans, orderly walking,
integrity to their professions, births, marriages, burials, sufferings,
and other such concerns, to the end that this people live peaceably among men,
and are in all things good examples.

This then is the account I have to give of the people of God called Quakers,
as to their rise, appearance, principles, and practices, in this age of the world,
with respect to both their faith and worship, and their discipline and conduct.
