[#ch8, short="Several Exhortations"]
== Chapter VIII

[.chapter-subtitle--blurb]
Containing Several Exhortations.

And now, Friends, you that profess to walk in this way, allow, I beseech you,
a word of exhortation--fathers as well as children, elders as well as young men.
The glory of this day,
and the foundation of the hope that has made us unashamed since we were a people,
you know, is that blessed gift of the light and life of Christ which we profess,
and to which we direct all people,
as the great and divine instrument and agent of man`'s conversion to God.
It was by this that we were first touched and effectually enlightened,
as to our inward state, and which put us upon the consideration of our latter end,
causing us to set the Lord before our eyes, and to number our days,
that we might apply our hearts to wisdom.
In that day we judged not after the sight of the eye, nor after the hearing of the ear,
but according to the light and sense which this blessed gift gave to us; yes,
by it we judged and acted, in reference to things and persons, ourselves and others,
and even towards God our Maker.
For being quickened by it in our inward man,
we could easily discern the difference between things,
coming to feel what was right and what was wrong, what was fitting, and what was not,
both in reference to religious and civil concerns.
And this gift of light and life being the ground of the fellowship of all saints,
it was in it that our fellowship stood.
In this we desired to have a sense of one another, and to act towards one another,
and all men, in love, faithfulness, and fear.

In feeling the stirrings and motions of this grace in our hearts,
we drew near to the Lord, and waited to be prepared by it,
that we might feel drawings and movings before we approached the Lord in prayer,
or opened our mouths in ministry.
In beginning and ending with this stood our comfort, service, and edification.
And as we ran faster than it, or fell short of it in our services,
we made burdens for ourselves to bear;
finding in ourselves a rebuke instead of an acceptance;
and instead of "`Well-done,`"
we found, "`Who has required this at your hands?`"^
footnote:[Isaiah 1:12]
In that day we were an exercised people;
our very countenances and deportment declared it.

Care for others was then much upon us, as well as for ourselves,
and especially for the newly convinced.
Often we had the burden of the word of the Lord for our neighbors, relations,
and acquaintances, and sometimes for strangers also.
We were likewise in travail for one another`'s preservation; not seeking,
but shunning occasions of any coldness or misunderstanding,
treating one another as those who believed and felt God present,
which kept our conduct innocent, serious, and weighty,
guarding ourselves against the cares and friendships of the world.
We held the truth in the Spirit of it, and not in our own spirits,
nor after our own wills and affections.

We were bowed down and brought into subjection to the Lord,
to such an extent that it was visible to all who knew us.
We did not think ourselves at our own disposal, to go where we wished,
or say or do what we wished, or when we wished.
Our liberty stood in the liberty of the Spirit of truth; and no pleasure, no profit,
no fear, no favor, could draw us from this retired, strict, and watchful frame.
We were so far from seeking occasion of social company, that we avoided it when we could,
pursuing our own business with moderation,
instead of meddling unnecessarily with other people`'s affairs.

Our words were few and savory, our looks composed and weighty,
and our whole deportment was in plain view to all.
True it is,
that this retired and strict sort of life exposed us to
the criticism of many of the world`'s libertines,
humorists, and conceited and self-righteous persons,
but it was our preservation from many snares to which others were
continually exposed by the predominance of the lust of the eye,
the lust of the flesh, and the pride of life,
which never lack occasion to entice men abroad into communion with the world.

I cannot forget the humility and chaste zeal of that day.
O, how constant at meetings, and how watchful in them; how faithful to truth`'s life,
as well as to truth`'s principles; and how single and united we felt in our communion, as,
indeed, is fitting for those who profess one Head--even Christ Jesus the Lord.

Now then, first,
to you my beloved and much honored brethren in
Christ who are in the exercise of the ministry.
To you I say: O, feel life in your ministry!
Let life be your commission, your well-spring and treasury on all such occasions;
or else (as you well know) there can be no begetting unto God.
For nothing makes alive except the life of God;
and only a ministry in and from this life can enliven a people to Him.
We have seen the fruit of all other ministries,
and how few are truly turned by them from the evil of their ways.
It is not our learning, our memory,
or the repetition of former revelations in our own will and time that will do God`'s work.
A dry doctrinal ministry, however sound in words, can reach only the ears,
and its effect is like a dream at best.
There is another sort of soundness that is more effective than all, namely:
Christ the power of God.
This is the key of David, which opens and none can shut; and shuts and none can open.
This power is to words what oil is to a lamp, and what the soul is to the body,
which made Christ say, "`My words are Spirit and they are life;`"^
footnote:[John 6:63]
that is, they proceed from life, and therefore make all alive who receive them.
And if the disciples who had lived with Jesus
were to stay in Jerusalem until they received it,
much more must we wait to receive power from on high before we minister in His name,
if indeed we seek to "`turn people from darkness to light,
and from Satan`'s power to God.`"^
footnote:[Acts 26:18]

I fervently bow my knees to the God and Father of our Lord Jesus Christ,
that you may always be like-minded,
and that you may ever wait reverently for the coming and opening of the Word of life,
and attend to it in your ministry and service,
that thus you may serve God in His own Spirit.
And if your service be little or much, it is well; for much is not too much,
and the least is enough, so long as it issues from the motion of God`'s Spirit.
But truly, without it, ever so little is too much, and is to no profit at all.

For it is the Spirit of the Lord,
either directly or through the ministry of His servants,
"`that teaches His people to profit;`"^
footnote:[Isaiah 48:17]
and to be sure, so far as we take Him along with us in our services,
that far we are profitable, and no further.
For if it is the Lord that must work all things in us for our salvation,
much more must He work through us for the conversion and edification of others.
If, therefore, it was once a cross for us to speak in His assemblies,
though the Lord required it at our hands, let it never be so to remain silent,
when He does not.

It is one of the most dreadful sayings in the book of God,
that "`He who adds to the words of the prophecy of this book,
God will add to him the plagues written in this book.`"
And to keep back the counsel of God is just as terrible;
"`For he that takes away from the words of the book of this prophecy,
God shall take away his part out of the book of life.`"^
footnote:[Revelation 22:18-19]
Truly, this has a great caution in it for all who use the name of the Lord,
that they be well assured that the Lord indeed speaks,
and are not found to be of the number who add to
the testimony which the Lord gives them to bear,
nor withhold or diminish the same--both being so very offensive to God.

Therefore, brethren, let us be careful, neither to out-run our leader,
nor loiter behind Him, since he that makes haste may miss his way,
and he that stays behind may lose his guide.
For even those who formerly received power from on high,
had need to wait for wisdom to see how to "`rightly divide the word;`"^
footnote:[2 Timothy 2:15]
which plainly implies that it is possible for one who has received the word of the Lord,
to mis-step in the dividing and application of it.
This, no doubt,
comes from an impatient and self-working spirit
that makes an unsound and dangerous mixture.
Such ministry can never rightly beget unto God a living and right-minded people.

I am earnest about this, above all other considerations,
well knowing how much it concerns the present and future state
and preservation of the church of Christ Jesus,
which has been gathered and built up by a living and powerful ministry.
May your ministry, then, always be held, preserved,
and continued in the manifestations,
motions, and supplies of the same life and power.

And wherever it is observed,
that anyone ministers more from gifts and abilities than from life and power,
though they have an enlightened and doctrinal understanding,
let them be duly advised and admonished for their own preservation;
for such as these will no doubt come to depend upon their own self-sufficiency,
insensibly forsaking Christ the living Fountain,
to hew out cisterns for themselves that will hold no living waters.^
footnote:[See Jeremiah 2:13]
And, by degrees,
they will draw others away from waiting upon the gift of God in themselves,
and from feeling it work in others (to their strength and refreshment),
in order to wait upon them, and so turn from God to man again.
These make shipwreck of the faith once delivered to the saints,
and of a good conscience towards God,
which are only maintained by that divine gift of life which first begat the one,
and then awakened and sanctified the other.

Nor is it enough that we have once known the divine gift,
and by it have reached to the spirits in prison,
and been the instruments of convincing others of the way of God,
if we do not keep as low and poor in ourselves, and as dependent upon the Lord as ever.
For no memory, no repetition of former openings, revelations, or enjoyments,
will bring a soul to God, or give bread to the hungry, or water to the thirsty,
unless the life accompanies all that we say; and that must be waited for.

O that we may have no other fountain, treasure, or dependence!
O that none may presume to act of themselves for God,
merely because they have long acted from God!
May we never replace the necessity of waiting, with words that arise from our own wisdom,
or think that we may take less care and more liberty in speaking than we formerly did.
And whenever we do not feel the Lord by His power to open and enlarge us,
may we never exceed His supply, or fill up time with our own,
regardless of what we have formerly done, or what the expectation of the people may be.

I hope we shall ever remember who it was that said,
"`Of yourselves you can do nothing.`"^
footnote:[John 15:5]
Our sufficiency is in Him.
And, indeed,
the ministry of the Spirit must keep its parallel and
agreement with the birth of the Spirit;
that as no man can inherit the kingdom of God unless he is born of the Spirit,
so no ministry can beget a soul unto God but that which is from the Spirit.
It was for this, as I said before, that the disciples waited before they went forth;
and it was in this same power that our elder
brethren and messengers of God in our day waited,
visited, and reached unto us.
So then, having begun in the Spirit,
let none ever hope or seek to be made perfect in the flesh;
for what is the flesh to the Spirit, or the chaff to the wheat?
And if we keep in the Spirit, we shall keep in the unity of it,
which is the ground of all true fellowship.
For by drinking into that one Spirit, we are made one people to God,
and by it we are kept in the unity of the faith and the bond of peace.
In this way, no envying, no bitterness, and no strife can have place with us.
So shall we continue to watch over one another for good, and not for evil;
nor shall we ever begrudge, but rather exceedingly rejoice,
to see others increase in the riches of that grace by
which God replenishes His faithful servants.

And brethren,
as you have been committed with a dispensation of the oracles of God,
which gives you frequent opportunities and great
freedom with the people among whom you travel,
I beseech you,
not to think it sufficient merely to declare the word of life in their assemblies,
however edifying and comfortable such opportunities may be both to you and to them.
But, as was the practice of the man of God before mentioned when among us,^
footnote:[i.e. George Fox]
look into the state of the churches you visit,
inquiring who among them are afflicted or sick, who are tempted,
and if any are unfaithful or obstinate,
and so endeavor to attend to these things in the wisdom and power of God.
This will prepare your way in their hearts to receive you as men of God,
and will give you credit with them to do them good by your advice in other respects.
In this way, the afflicted will be comforted by you, the tempted strengthened,
the sick refreshed, the unfaithful convicted and restored,
and those who are obstinate will be softened and fitted for reconciliation.
Thus you will show yourselves God`'s workmen indeed,
carrying out your business to the praise of His
name who has called you from darkness to light,
that you might turn others from Satan`'s power unto God and His kingdom, which is within.

And you, young convinced ones,
be entreated and exhorted to a diligent and chaste waiting upon God,
in the way of His blessed manifestation and inward appearance to you.
Look not out, but within.
Let not another`'s liberty be your snare; nor act by imitation,
but by a true sense and feeling of God`'s power in yourselves.
O crush not the tender buddings of His plant in your souls,
nor outrun the holy and gentle motions of it because of
your desires and the warmth of your affections.
Remember it is a still, small voice that speaks to us in this day.
It is not to be heard in the noise and hurry of the mind,
but is distinctly understood in a retired and watchful frame.
Jesus loved and often chose solitude, going to mountains, gardens,
and seasides to avoid crowds and hurries,
and to show His disciples that it was good to be solitary and sit loose to the world.

Two enemies lie near you: imagination and fleshly liberty.
But the plain, holy, and living truth that has convinced you will also preserve you,
if you mind it in yourselves, and bring all thoughts, inclinations,
and affections to the light, to see if they are wrought in God, or of the enemy,
or of yourselves.
In this way, a true taste, discerning,
and judgment will be formed and preserved in you,
concerning what you should do and leave undone.
In your diligence and faithfulness you will come to inherit substance, and Christ,
the eternal wisdom of God, will fill your treasury.
And when you are converted, as well as convinced, then strengthen your brethren,
and be ready for every good word and work to which the Lord shall call you.
Then you may live to His praise,
who has chosen you to be partakers with the saints in
light of a kingdom that cannot be shaken,
an inheritance incorruptible in eternal habitations.

And now, as for you who are the children of God`'s people,^
footnote:[He is here addressing the children of the first generation of Friends.]
a great concern is upon my spirit for your good,
and often my knees are bowed to the God of your fathers for you,
that you may come to be partakers of the same divine
life and power that have been the glory of this day,
and that you may be a generation for God, a holy nation and special people,
zealous for good works, when all our heads are laid in the dust.
O you young men and women,
let it not suffice that you are the children of the people of the Lord;
you must also be born again if you will inherit the kingdom of God.
Your fathers are but flesh and can only beget you into the likeness of the first Adam;
but you must be begotten into the likeness of the second Adam by a spiritual generation,
or you will not, you cannot, be of His children or offspring.

Therefore look carefully about you, O you children of the children of God!
Consider your standing, and see what you are in relation to this divine kindred,
family, and birth.
Have you obeyed the light, and received and walked in the Spirit,
which is the incorruptible Seed and Word of the kingdom of God,
of which you must be born again?
God is no respecter of persons.
The father cannot save or answer for the child, nor the child for the father.
In the sin that you commit you shall die; and in the righteousness that you do,
through Christ Jesus, you shall live;
for it is "`the willing and obedient that shall eat the good of the land.`"^
footnote:[Isaiah 1:19]
Be not deceived, God is not mocked.
Whatever all nations and people sow, that they shall reap from the hand of the just God.
And then your many and great privileges
(above the children of other people)
will add weight in the scale against you,
if you do not choose the way of the Lord.
For you have not only had good doctrine but good example; and what is more,
you have been turned to, and acquainted with,
that heavenly light of which others have been too generally ignorant.
And if you,
after hearing and seeing the wonders that God has wrought in
the deliverance and preservation of your worthy parents,
even through a sea of troubles,
and beholding the temporal and spiritual blessings that
He has filled them with in the sight of their enemies,
I say, if you should neglect and turn your backs upon so great and near a salvation,
you would not only be the most ungrateful children both to God and to them,
but must expect a dreadful judgment at the hand of the Lord.
But may it never be so with any of you, says my soul!

Therefore, O young men and women, look to the Rock of your fathers;
there is no other God but Him.
There is no other light but His, no other grace but His,
nor any Spirit but His to convince, quicken, and comfort you; to lead, preserve,
and guide you to God`'s everlasting kingdom.
Seek Him, that you may be possessors as well as professors of the truth,
embracing it not only by education, but by judgment and conviction,
from a sense begotten in your souls through the
operation of the eternal Spirit and power of God.
By this alone you will come to be the seed of Abraham through faith,
and know the circumcision not made with hands,
and so become heirs of the promise made to the fathers of an incorruptible crown.
Then, as I said before, you will be a generation unto God,
holding up the profession of His blessed truth in the life and power of it.
For formality in religion is repugnant to God and to all good men.
Therefore I say, be careful not to fall flat and formal,
continuing our profession without that salt and savor
by which it has come to obtain a good report among men.
For wherever the divine virtue of it is not felt in the soul,
and waited for and lived in, impurities will quickly break out and show themselves,
and manifest the unfaithfulness of such persons whose insides are not
seasoned with the nature of that Holy Spirit which they profess.

Therefore, dear children,
let me entreat you to shut your eyes to the temptations
and allurements of this low and perishing world,
and to not allow your affections to be captivated by
those lusts and vanities that your fathers,
for the truth`'s sake, long since turned their backs upon.
Rather, believe the truth and receive it into your hearts,
that you may become the children of God,
and that it may never be said of you what the evangelist writes of the Jews in his time,
that Christ, the true light, "`came to His own, but His own received Him not.`"^
footnote:[John 1:11]
For like the Jews of that time,
you bear the name and practices of God`'s people (being their children),
and Christ by His light in you, may very well be said to have come to His own;
but if you obey Him not, and turn your back upon His light,
walking after the vanities of your minds,
you will be of that number who "`receive Him not.`"
So then, turn to the Lord, and to His gift and Spirit within you.
Hear His voice and obey it,
that you may set your seal to the testimony of your
fathers by the evidence of your own experience.
So will the grey hairs of your dear parents, who are yet alive,
go down to the grave with joy,
knowing that the Spirit and nature which they have
known and loved shall live in you when they are gone.

[.asterism]
'''

I shall conclude this chapter with a few words
to those who are not of our communion,
into whose hands this small book may come.

Friends, as you are the sons and daughters of Adam,
and my brethren after the flesh,
often and earnest have been my desires and prayers to God on your behalf,
that by the power and Spirit of His Son Jesus Christ,
whom He has given for the light and life of the world,
you may experience your Creator to become your Redeemer,
and a Restorer of that holy image which you have lost because of sin.
And O that you who are called Christians would truly receive Him into your hearts;
for it is there you have need of Him!
At the door of your hearts He stands and knocks that you might let Him in; but alas,
He finds you filled already with other guests,
so that a lonely manger is His lot among you, even as it was of old.
Nevertheless, you are full of beliefs and notions,
like the presumptuous Jews who knew Him not,
but rejected and mistreated Him in the days of His flesh.
And like them, if you do not come to possess and experience what you profess with words,
all your formality in religion will avail nothing in the day of God`'s judgment.

I beseech you to ponder your eternal condition, and to consider what title,
ground, and foundation you have for your Christianity.
Do you have more than a profession and a historical belief in the truths of the gospel?
Have you known the baptism of the Holy Spirit and fire,
and the fan of Christ that winnows away the chaff in your heart,
with all carnal lusts and affections?
Do you experience the divine leaven of the kingdom, which, being received,
leavens the whole lump of man,
"`sanctifying him completely in body, soul, and spirit`"?^
footnote:[1 Thessalonians 5:23]
If this is not the ground of your confidence, you are still in a miserable state.

Perhaps you will say that,
though you are sinners and live daily in the commission of sin,
and are not sanctified as I have described,
yet you have faith in Christ who has borne the curse for you,
and in Him you are complete by faith--His righteousness having been imputed to you.
But, my friends,
let me entreat you not to deceive yourselves in a
matter as important as the fate of your immortal souls.
If you have true faith in Christ, your faith will make you clean.^
footnote:[See Acts 15:9]
Yes, it will sanctify you;
for the faith of the saints was "`their victory over the world.`"^
footnote:[1 John 5:4]
By faith they overcame sin within and sinful men without.
And if you are indeed in Christ, you will walk not after the flesh, but after the Spirit,
the fruits of which are evident to all.
You will be a new creature--newly made, newly fashioned, after God`'s own will and mold.
Old things will be done away, and behold, all things will be new--new love, desires,
will, affections, and practices.
It will no longer be you who lives
(the disobedient, carnal, and worldly you),
but Christ who lives in you.
To live will be Christ, and to die will be your eternal gain,
being assured that your
"`corruptible shall put on incorruption, and your mortal, immortality,`"^
footnote:[1 Corinthians 15:53]
having a glorious house, eternal in the heavens, that will never wax old or pass away.
All of this follows a true being in Christ, even as heat follows fire,
and light follows the sun.

Therefore be careful how you presume to rely upon such a notion--believing
that you are in Christ even while living in your old fallen nature.
For "`what communion has light with darkness, or Christ with Belial?`"^
footnote:[2 Corinthians 6:14-15]
Hear what the beloved disciple tells you:
"`Little children, let no one deceive you.
He who practices righteousness is righteous, just as He is righteous.`"^
footnote:[1 John 3:7]
And, "`If we say we have fellowship with God, and walk in darkness, we lie,
and do not practice the truth.`"^
footnote:[1 John 1:6]
That is, if we go on in a sinful way, are captivated by our carnal affections,
and are not converted to God, we walk in darkness,
and in that state cannot possibly have any fellowship with God.
Christ clothes with His righteousness those who receive His grace in their hearts,
and deny themselves, and take up His cross daily and follow Him.
Christ`'s righteousness makes men inwardly holy--of holy minds, wills, and practices.
It is not less Christ`'s because we have it; for it is not ours by nature,
but by faith and adoption; it is the gift of God.
But, still, though it is not ours as of or from ourselves,
(for in that sense it is Christ`'s, being always of and from Him,)
yet it is ours, and must be ours, in possession, efficacy,
and experience, in order to do us any good;
otherwise Christ`'s righteousness will profit us nothing.
It was after this manner that He was made unto
the primitive Christians their
"`righteousness, sanctification, justification, and redemption`"^
footnote:[1 Corinthians 1:30]--not an unfelt imputation,
but a discernible transformation.
And if ever you will know the comfort, the substance,
the marrow of the Christian religion, thus you must also come to learn and obtain it.

Now, my friends, by what you have read,
you may perceive that God has indeed visited a despised people
among you with this saving knowledge and testimony--a people
whom He has upheld and increased to this day,
notwithstanding the fierce opposition they have met with.
Therefore, despise not the lowness of this appearance; it was, and yet is (we know),
a day of small things and of small account with many,
and many hard and ill names have been given to it.
Nevertheless, it is of God; it came from Him because it leads to Him.
This we know beyond any doubt, though we cannot make any man know what we know,
unless they will take the same path that we took.

The world talks of God, but what do they do?
They pray for power, but reject the light in which the power is known.
So then, if you desire to know God, and to worship and serve Him as you ought to do,
you must come to the means that He has ordained and given for this purpose.
Some seek it in books, and some in learned men;
but what they look for is found in themselves
(though not of themselves),
and so they overlook it.
The voice is too still, the seed is too small, and the light shines in darkness,
but men are wandering abroad.
The woman that lost her coin found it at home,
after lighting her candle and sweeping her house.
You must do the same, and so you will meet with the answer to Pilate`'s question,
"`What is truth?`"
Indeed, you will find Truth in the inward parts, the light of Christ within.
For Christ is the light of the world,
and will be a light unto you to show the truth of your condition.
And taking heed unto Him,
He will lead you out of all darkness into God`'s marvelous light;
for light increases upon the obedient.
Yes, "`Light is sown for the righteous,`"^
footnote:[Ps. 97:11]
and "`their way is as a shining sun,
that shines forth ever brighter unto the perfect day.`"^
footnote:[Proverbs 4:18]

Therefore, O friends, turn inward, turn inward, I beseech you!
Where the poison is found, there you shall find the antidote too.
It is there you need Christ, and there you must find Him.
Seek and you shall find, I testify for God!
But then you must seek rightly, with your whole heart, as men that seek for their lives,
yes, for their eternal lives--diligently, humbly, patiently,
as those who can taste no pleasure, comfort, or satisfaction in anything else,
unless they find the One their soul needs above all.
O, this path is a travail, a spiritual travail!
Let the carnal, profane world think and say what it will.
It is upon a path of travail you must walk to
the city of God that has eternal foundations,
if ever you will arrive.

And what will this blessed light do for you?
I will tell you:

First, it will show you how man has fallen from God,
and the miserable state he is in.
It will detect the spirit of the world in all of its baits and allurements,
and "`set all your sins in order before you.`"^
footnote:[Ps. 50:21; Ps. 90:8]

Secondly, it will beget a deep sense of sorrow in all who believe its testimony.
The light will show you the One whom you have pierced,
the blows and wounds you have given Him by your disobedience,
and how you have compelled Him to serve because of your sins.
Then you will weep and mourn for your frightful offense,
but your grief will be that "`godly sorrow which works repentance`"^
footnote:[2 Corinthians 7:10]
of which the apostle speaks.

Thirdly, it will bring you to a holy watchfulness,
to take care that you do so no more, and that the enemy does not surprise you again.
Thus you will be taught to bring every thought, word, and work to the judgment of light,
which is the highway of holiness where the redeemed of the Lord do walk.
Then, and not till then, you will truly love God above all,
and your neighbor as yourselves; and "`nothing will hurt, nothing will harm,
and nothing will make afraid upon this holy mountain.`"^
footnote:[Isaiah 11:9; 65:25]
So you will come to be Christ`'s indeed; for you will be of His nature and Spirit,
and not of your own.
And when you are Christ`'s, then Christ will be yours,
and you will experience precious communion with the Father and with the Son.
And you will know beyond words the power of the blood, even the blood of Jesus Christ,
that immaculate Lamb, which speaks better things than the blood of Abel,
and cleanses the conscience from dead works to serve the living God.

[.asterism]
'''

Behold the testimony and doctrine of the people called Quakers.
Behold their practice and discipline,
and the men and women who were sent of God in this excellent work and service.
May God, in this day of His great love and power, ever have the glory, honor,
thanksgiving, and renown, through His beloved Son and Lamb, our light and life,
who sits with Him upon the throne, forever and ever.
Amen.

[.small-break]
'''

--Says one whom God long ago favored with His merciful visitation,
and who was not disobedient to the heavenly vision and call;
to whom the way of truth is more lovely and precious than ever,
and knowing the beauty and benefit of it above all worldly treasures,
has chosen it for his chiefest joy, and therefore recommends it to your love and choice,
because he is with great sincerity and affection,

[.signed-section-closing]
Your soul`'s friend,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
1696
